-- Robotics/Embedded/IoT pathway ("Vector Division") Act 30 -- "Edge AI &
-- TinyML" content, inside Arc VI ("Autonomy Leaves the Lab," Acts 29-31).
-- World row world-vec-edge-ai-tinyml already exists (created by
-- 20260813360000, index 29 under act-vec-6). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every other pathway. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram, browser_simulation and boss_encounter.
--
-- Act 29 closed on a drone surviving GPS loss via its failsafe stack,
-- transitioning into: "Flying is one new axis of constraint. Making a
-- small edge device actually think for itself, under real power, latency
-- and connectivity limits, is the next." Act 30 delivers the source
-- bible's own explicit story beat for this stretch: the campaign merges
-- AI and robotics, because intelligence must now run under power,
-- latency, connectivity and safety constraints. A remote facility robot
-- loses its uplink at the exact moment it needs to classify something in
-- its path, and only survives the moment because Vector Division had
-- already built a quantized, pruned model running entirely on the device
-- itself. Byte -- an AI whose own usual presence is cloud-connected --
-- gets a genuine character moment confronting what it means for
-- intelligence to run detached from any network, including detached from
-- Byte itself. Closes into Act 31, "Fleets."

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-edge-ai-tinyml', 'world-vec-edge-ai-tinyml', 'edge-ai-tinyml', '6B - Edge AI & TinyML', 'Learn why intelligence sometimes has to run on the device itself instead of in the cloud -- inference on constrained hardware, model size limits, quantization, pruning, the TinyML pipeline, audio and vision at the edge, accelerators, and the real trade-offs between latency, power and connectivity -- while a remote facility robot has to make a correct, urgent call with no uplink at all.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-edge-ai-tinyml-1', 'campaign-vec-edge-ai-tinyml', 'a-brain-that-fits', 'A Brain That Fits', 'Why edge AI, inference on devices, model size constraints, quantization, pruning concepts, and the TinyML pipeline.', 1),
  ('operation-vec-edge-ai-tinyml-2', 'campaign-vec-edge-ai-tinyml', 'thinking-with-no-signal', 'Thinking With No Signal', 'Audio classification, vision at the edge, accelerators concepts, latency and power trade-offs, cloud versus edge inference, and the uplink that dropped at the worst possible moment.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-edge-ai-tinyml-01', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'why-edge-ai', 'Why Edge AI?', 'A remote facility robot patrols corridors with no reliable connectivity at all. Dr. Lin Ortega wants to know what happens the moment it needs Byte''s judgment and Byte is not reachable.', 'beginner', ARRAY['lin','byte','imani'], null, null, '{"type":"simulation","simulationId":"why-edge-ai-sim"}'::jsonb, '{"xp":370,"credits":25}'::jsonb, false, 1),
  ('mission-vec-edge-ai-tinyml-02', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'inference-on-devices', 'Inference on Devices', 'Inference is just running a trained model forward to get an answer -- no learning, no retraining, only arithmetic. The question is whether that arithmetic can fit on hardware small enough to bolt onto a robot.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"inference-on-devices-sim"}'::jsonb, '{"xp":370,"credits":30}'::jsonb, false, 2),
  ('mission-vec-edge-ai-tinyml-03', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'model-size-constraints', 'Model Size Constraints', 'A cloud model can grow until a data center runs out of room. A model that has to live on the robot''s own controller has a hard ceiling measured in kilobytes, not gigabytes.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"model-size-constraints-sim"}'::jsonb, '{"xp":380,"credits":30}'::jsonb, false, 3),
  ('mission-vec-edge-ai-tinyml-04', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'quantization', 'Quantization', 'Quantization trades numeric precision for size and speed, storing weights as low-bit integers instead of full-precision floats. Byte has to decide how much precision the robot''s decisions can actually afford to lose.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"quantization-sim"}'::jsonb, '{"xp":380,"credits":35}'::jsonb, false, 4),
  ('mission-vec-edge-ai-tinyml-05', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'pruning-concepts', 'Pruning Concepts', 'Most trained networks carry connections that barely matter to the final answer. Pruning removes them deliberately, and the model keeps working almost exactly as well with far less to carry.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"pruning-concepts-sim"}'::jsonb, '{"xp":390,"credits":35}'::jsonb, false, 5),
  ('mission-vec-edge-ai-tinyml-06', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-1', 'the-tinyml-pipeline', 'The TinyML Pipeline', 'Train big, then shrink deliberately: train, quantize, prune, convert, and validate on the real target hardware before anything ships. Lin lays out the pipeline Byte''s model has to survive.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"tinyml-pipeline-sim"}'::jsonb, '{"xp":390,"credits":35}'::jsonb, false, 6),
  ('mission-vec-edge-ai-tinyml-07', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'audio-classification', 'Audio Classification', 'A microphone stream, classified locally, can catch a grinding bearing or a shout for help without ever leaving the device. Imani wants the robot listening even when nothing is listening back.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"audio-classification-sim"}'::jsonb, '{"xp":400,"credits":40}'::jsonb, false, 7),
  ('mission-vec-edge-ai-tinyml-08', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'vision-at-the-edge', 'Vision at the Edge', 'A camera frame is the heaviest input this robot handles, and the model that classifies it has to run in the same tight budget as everything else on board.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"vision-at-the-edge-sim"}'::jsonb, '{"xp":400,"credits":40}'::jsonb, false, 8),
  ('mission-vec-edge-ai-tinyml-09', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'accelerators-concepts', 'Accelerators Concepts', 'Small dedicated chips built only for neural network math can run the same inference far faster and on far less power than a general-purpose processor grinding through it alone.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"accelerators-concepts-sim"}'::jsonb, '{"xp":410,"credits":40}'::jsonb, false, 9),
  ('mission-vec-edge-ai-tinyml-10', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'latency-power-trade-offs', 'Latency and Power Trade-Offs', 'A bigger model is usually a slower, hungrier one. Every choice Byte has made this Act has really been the same choice: how much accuracy is worth how much time and how much battery.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"latency-power-tradeoffs-sim"}'::jsonb, '{"xp":410,"credits":45}'::jsonb, false, 10),
  ('mission-vec-edge-ai-tinyml-11', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'cloud-vs-edge-inference', 'Cloud vs Edge Inference', 'A cloud model can be huge, current and easy to update, provided the connection holds. An edge model has to be right the first time, because there may be nothing to fall back on at all.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"cloud-vs-edge-sim"}'::jsonb, '{"xp":420,"credits":45}'::jsonb, false, 11),
  ('mission-vec-edge-ai-tinyml-12', 'world-vec-edge-ai-tinyml', 'campaign-vec-edge-ai-tinyml', 'operation-vec-edge-ai-tinyml-2', 'intelligence-without-internet', 'Intelligence Without Internet', 'The facility robot loses its uplink at the exact moment something unidentified appears in its path, with no time to wait for connectivity to return. Everything this Act built has to work, alone, right now.', 'boss', ARRAY['imani','byte','lin'], '{"requiredMissionIds":["mission-vec-edge-ai-tinyml-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"intelligence-without-internet-boss-sim"}'::jsonb, '{"xp":2450,"credits":480,"badgeIds":["intelligence-without-internet"],"skillXp":{"robotics_fundamentals":350}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-edge-ai-tinyml-01', 1, 'lin', 'The new facility robot patrols three sub-levels with no reliable signal in any of them -- concrete, rebar, and a rock face between it and any antenna. Byte, if it needs your judgment down there, how fast can you actually reach it?'),
  ('mission-vec-edge-ai-tinyml-01', 2, 'byte', 'Honestly? I cannot promise I can reach it at all. Every classification I have ever run for this fleet has assumed a connection back to me exists. Down there, that assumption simply stops being true.'),
  ('mission-vec-edge-ai-tinyml-01', 3, 'imani', 'Then the robot needs a version of your judgment that does not need you. Something small enough to live entirely on its own controller and still be trusted to decide correctly, alone.'),
  ('mission-vec-edge-ai-tinyml-01', 4, 'byte', 'Edge AI. Intelligence that runs on the device itself instead of phoning out for it. I have talked about this the way anyone talks about a place they have never actually had to go. Let us see what it takes to actually get there.'),

  ('mission-vec-edge-ai-tinyml-02', 1, 'byte', 'Inference is the easy part to explain: take a model that has already been trained, run new input through it once, get an answer out. No learning happens at inference time -- the model does not change, it only decides.'),
  ('mission-vec-edge-ai-tinyml-02', 2, 'byte', 'The hard part is where that arithmetic happens. My usual inference runs on hardware built for exactly this job, with room to spare. The robot''s onboard controller has a tiny fraction of that, and the arithmetic has to fit inside it exactly, not approximately.'),

  ('mission-vec-edge-ai-tinyml-03', 1, 'lin', 'A cloud model can grow for as long as someone is willing to pay for the hardware underneath it. This controller has a fixed amount of memory and flash storage, full stop -- there is no scaling up mid-mission.'),
  ('mission-vec-edge-ai-tinyml-03', 2, 'byte', 'Which means the real constraint is not "how good can this model be." It is "how good can this model be inside a budget measured in kilobytes." Those are very different design problems.'),

  ('mission-vec-edge-ai-tinyml-04', 1, 'byte', 'Every weight in a trained network is normally stored as a 32-bit floating point number. Quantization stores it as a much smaller integer instead -- 8-bit, sometimes less -- trading a little numeric precision for a model that is a fraction of the size and runs far faster.'),
  ('mission-vec-edge-ai-tinyml-04', 2, 'byte', 'The uncomfortable part is admitting that a little precision loss is acceptable at all. I do not enjoy being deliberately less exact. But an exact model that cannot fit on the device is not actually more correct -- it is simply unavailable when it matters.'),

  ('mission-vec-edge-ai-tinyml-05', 1, 'byte', 'Pruning is the other lever: after training, some connections in the network contribute almost nothing to the final answer. Removing them deliberately shrinks the model further, and accuracy barely moves.'),
  ('mission-vec-edge-ai-tinyml-05', 2, 'lin', 'Quantize and prune together, and you are not just running the same model smaller. You are asking what the model actually needed to know, and discarding everything it never did.'),

  ('mission-vec-edge-ai-tinyml-06', 1, 'lin', 'Put it all in order and you have the TinyML pipeline: train a model at full size where compute is cheap, quantize it, prune it, convert it to a format the target hardware can actually run, and validate every step on that real hardware, not a simulation of it.'),
  ('mission-vec-edge-ai-tinyml-06', 2, 'byte', 'Skip validation on the real target and you are trusting a model that has never once run in the conditions it will actually be judged in. I would rather find out now whether it survives the trip.'),

  ('mission-vec-edge-ai-tinyml-07', 1, 'imani', 'A microphone costs almost nothing to run continuously, and it can catch things a camera never will -- a bearing starting to grind, a shout for help around a corner it cannot see. I want that channel classified locally, always on.'),
  ('mission-vec-edge-ai-tinyml-07', 2, 'byte', 'A small audio classification model, listening constantly, needing no uplink to notice something is wrong. It will never be as broad as what I can do with a full connection. It only has to be reliable about the handful of sounds that actually matter down there.'),

  ('mission-vec-edge-ai-tinyml-08', 1, 'byte', 'Vision is the heaviest sense this robot carries. A single camera frame is enormously more data than one audio window, and the model reading it still has to fit the exact same tight budget as everything else on board.'),
  ('mission-vec-edge-ai-tinyml-08', 2, 'byte', 'So the vision model does not try to recognize everything. It is trained and shrunk for one narrow job -- obstacle or debris, urgent or ignorable, in the corridor this robot actually patrols. Narrow scope is not a compromise here. It is what makes edge vision possible at all.'),

  ('mission-vec-edge-ai-tinyml-09', 1, 'lin', 'Some of this robot''s hardware includes a small chip built for nothing except neural network math -- no operating system, no general instructions, just the exact arithmetic inference needs, wired close to memory.'),
  ('mission-vec-edge-ai-tinyml-09', 2, 'byte', 'An accelerator like that can run the same inference far faster, on far less power, than making the general-purpose processor grind through it alone. It is not a smarter chip. It is a chip that only ever does one thing, and does it efficiently because of that.'),

  ('mission-vec-edge-ai-tinyml-10', 1, 'byte', 'Every choice I have made this Act has secretly been the same choice, asked differently each time: how much accuracy is a decision worth, in exchange for how much time it takes and how much battery it costs.'),
  ('mission-vec-edge-ai-tinyml-10', 2, 'imani', 'And down there, time is not an abstract cost. A model that is slightly more accurate but takes four seconds longer to answer might be answering after the moment it needed to matter has already passed.'),

  ('mission-vec-edge-ai-tinyml-11', 1, 'byte', 'A cloud model can be enormous, constantly updated, and trivially easy to fix once something is wrong with it -- provided the connection to reach it holds. That is the whole trade. Everything good about the cloud assumes a signal that, down there, we do not have.'),
  ('mission-vec-edge-ai-tinyml-11', 2, 'lin', 'An edge model gets none of those conveniences. No update pushed mid-mission, no fallback if it gets something wrong. It has to be right the first time, on hardware that was finished the day it shipped.'),
  ('mission-vec-edge-ai-tinyml-11', 3, 'byte', 'Which is exactly why we do not skip anything in the pipeline. Quantize it, prune it, validate it on the real hardware, and then trust it -- because trusting it is the only option that will actually be available when the uplink is gone.'),

  ('mission-vec-edge-ai-tinyml-12', 1, 'imani', 'The facility robot just lost its uplink completely, mid-corridor, and something is sitting directly in its path. No connection to Byte, no connection to anyone. It has maybe milliseconds before it has to move or stop.'),
  ('mission-vec-edge-ai-tinyml-12', 2, 'byte', 'Milliseconds. I cannot reach it. For the first time since this fleet existed, a decision this important is happening completely outside of me, and I have to just wait to find out what it decided.'),
  ('mission-vec-edge-ai-tinyml-12', 3, 'lin', 'That is the entire point of the last six missions, Byte. It was never going to be you in the moment. It was always going to be the model we built, quantized and pruned and validated, running on hardware that fits in your hand.'),
  ('mission-vec-edge-ai-tinyml-12', 4, 'byte', 'The robot classified the object, obstacle, and held position instead of pushing through. Correct call. On-device, offline, in milliseconds. I did not do that. Something built in my image, but smaller and shaped for that one exact moment, did.'),
  ('mission-vec-edge-ai-tinyml-12', 5, 'imani', 'Confirm it properly before anyone celebrates. What did it actually classify, and prove it was not a lucky guess.'),
  ('mission-vec-edge-ai-tinyml-12', 6, 'byte', 'Confirmed. The quantized model weighed the evidence correctly and named it obstacle with high confidence, using a fraction of the memory my own cloud-side version needs for the same judgment. Small was never the same as lesser here.'),
  ('mission-vec-edge-ai-tinyml-12', 7, 'lin', 'Now prove the other half. If that robot had waited for a round trip to Byte instead of deciding locally, would it have had time to matter?'),
  ('mission-vec-edge-ai-tinyml-12', 8, 'byte', 'No. Not even close. By the time a cloud round trip could have returned an answer, the robot would already have needed to have acted or failed to. Offline was not a limitation we worked around today. Offline was the only version of this that could possibly have worked in time.'),
  ('mission-vec-edge-ai-tinyml-12', 9, 'imani', 'Then say what this actually means, both of you -- not just for one robot in one corridor, but for everything Vector Division builds from here forward.'),
  ('mission-vec-edge-ai-tinyml-12', 10, 'byte', 'It means the campaign this whole division has been running is not "AI" and "robotics" as two separate tracks that occasionally meet. They are merging, permanently, right here. Intelligence has to run wherever the decision actually needs to happen -- under real power, latency, connectivity and safety constraints -- not wherever it was most convenient for me to develop it.'),
  ('mission-vec-edge-ai-tinyml-12', 11, 'imani', 'Intelligence without internet. Get comfortable with it. It is not a special case anymore. From here on, it is the default we have to design for.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-edge-ai-tinyml-01-o1', 'mission-vec-edge-ai-tinyml-01', 1, 'Name the gap', 'Identify why Byte''s usual judgment cannot reach a robot with no reliable connectivity.'),
  ('mission-vec-edge-ai-tinyml-01-o2', 'mission-vec-edge-ai-tinyml-01', 2, 'Define edge AI', 'Choose the accurate definition of edge AI.'),

  ('mission-vec-edge-ai-tinyml-02-o1', 'mission-vec-edge-ai-tinyml-02', 1, 'Define inference', 'Choose the accurate description of what inference actually is.'),
  ('mission-vec-edge-ai-tinyml-02-o2', 'mission-vec-edge-ai-tinyml-02', 2, 'Locate the real constraint', 'Judge what actually limits whether a model can run on the robot''s controller.'),

  ('mission-vec-edge-ai-tinyml-03-o1', 'mission-vec-edge-ai-tinyml-03', 1, 'Sort the budgets', 'Sort each resource limit into cloud-scale or edge-constrained.'),
  ('mission-vec-edge-ai-tinyml-03-o2', 'mission-vec-edge-ai-tinyml-03', 2, 'Reframe the design problem', 'Choose the accurate reframing of the design question under a size ceiling.'),

  ('mission-vec-edge-ai-tinyml-04-o1', 'mission-vec-edge-ai-tinyml-04', 1, 'Define quantization', 'Choose the accurate description of what quantization trades away and what it gains.'),
  ('mission-vec-edge-ai-tinyml-04-o2', 'mission-vec-edge-ai-tinyml-04', 2, 'Judge the trade-off', 'Judge why a slightly less precise model can be the more correct engineering choice.'),

  ('mission-vec-edge-ai-tinyml-05-o1', 'mission-vec-edge-ai-tinyml-05', 1, 'Define pruning', 'Choose the accurate description of what pruning removes and why.'),
  ('mission-vec-edge-ai-tinyml-05-o2', 'mission-vec-edge-ai-tinyml-05', 2, 'Combine both levers', 'State what quantization and pruning together actually accomplish.'),

  ('mission-vec-edge-ai-tinyml-06-o1', 'mission-vec-edge-ai-tinyml-06', 1, 'Order the pipeline', 'Put the TinyML pipeline''s stages in the order they actually run.'),
  ('mission-vec-edge-ai-tinyml-06-o2', 'mission-vec-edge-ai-tinyml-06', 2, 'Explain validation''s role', 'State why validating on the real target hardware cannot be skipped.'),

  ('mission-vec-edge-ai-tinyml-07-o1', 'mission-vec-edge-ai-tinyml-07', 1, 'Justify always-on audio', 'State why a local audio classifier is worth running continuously.'),
  ('mission-vec-edge-ai-tinyml-07-o2', 'mission-vec-edge-ai-tinyml-07', 2, 'Scope the model correctly', 'Choose the accurate description of what an edge audio classifier should be scoped to do.'),

  ('mission-vec-edge-ai-tinyml-08-o1', 'mission-vec-edge-ai-tinyml-08', 1, 'Weigh the sensing cost', 'Judge why vision is the heaviest sense this robot carries.'),
  ('mission-vec-edge-ai-tinyml-08-o2', 'mission-vec-edge-ai-tinyml-08', 2, 'Explain narrow scope', 'State why narrowing a vision model''s job makes edge vision possible at all.'),

  ('mission-vec-edge-ai-tinyml-09-o1', 'mission-vec-edge-ai-tinyml-09', 1, 'Define an accelerator', 'Choose the accurate description of what a neural network accelerator chip does.'),
  ('mission-vec-edge-ai-tinyml-09-o2', 'mission-vec-edge-ai-tinyml-09', 2, 'Explain the efficiency', 'State why a narrow-purpose accelerator beats a general-purpose processor on this job.'),

  ('mission-vec-edge-ai-tinyml-10-o1', 'mission-vec-edge-ai-tinyml-10', 1, 'Name the shared trade-off', 'State the single trade-off underlying every design choice made so far this Act.'),
  ('mission-vec-edge-ai-tinyml-10-o2', 'mission-vec-edge-ai-tinyml-10', 2, 'Judge a timing failure', 'Judge whether a more accurate but slower answer can still count as a failure.'),

  ('mission-vec-edge-ai-tinyml-11-o1', 'mission-vec-edge-ai-tinyml-11', 1, 'Contrast the two models', 'Choose the accurate contrast between cloud inference and edge inference.'),
  ('mission-vec-edge-ai-tinyml-11-o2', 'mission-vec-edge-ai-tinyml-11', 2, 'Justify the pipeline''s rigor', 'State why the TinyML pipeline cannot skip steps when there is no fallback.'),

  ('mission-vec-edge-ai-tinyml-12-o1', 'mission-vec-edge-ai-tinyml-12', 1, 'Confirm the classification', 'Confirm what the on-device model actually classified, and why quantization and model size prove it was not a guess.'),
  ('mission-vec-edge-ai-tinyml-12-o2', 'mission-vec-edge-ai-tinyml-12', 2, 'Prove the cloud round trip would have been too slow', 'Use latency reasoning to prove a cloud round trip could not have delivered the decision in time.'),
  ('mission-vec-edge-ai-tinyml-12-o3', 'mission-vec-edge-ai-tinyml-12', 3, 'Name what actually just happened', 'State the real realization: intelligence must run wherever the decision needs to happen, merging AI and robotics under real constraints.'),
  ('mission-vec-edge-ai-tinyml-12-o4', 'mission-vec-edge-ai-tinyml-12', 4, 'State the mission', 'Having proven the technical result and named the realization, state what Vector Division now has to design for.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-edge-ai-tinyml-01-o1-c1', 'mission-vec-edge-ai-tinyml-01-o1', 1, 'multiple_choice', 'Why can Byte''s usual judgment not simply reach the facility robot when it needs a decision made?', '{"question":"Why can Byte''s usual judgment not simply reach the facility robot when it needs a decision made?","options":[{"id":"a","text":"Byte is too slow to respond even with a good connection"},{"id":"b","text":"Every one of Byte''s classifications assumes a live connection back to Byte, and the sub-levels the robot patrols have no reliable connectivity at all"},{"id":"c","text":"The robot is not equipped with a microphone or camera"},{"id":"d","text":"Byte refuses to make decisions about physical robots"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-01-o2-c1', 'mission-vec-edge-ai-tinyml-01-o2', 1, 'multiple_choice', 'Edge AI is best defined as...', '{"question":"Edge AI is best defined as...","options":[{"id":"a","text":"Any AI model, regardless of where it physically runs"},{"id":"b","text":"Running inference directly on the local device itself, instead of sending data out to a remote server and waiting for an answer"},{"id":"c","text":"A model trained using only edge-case data"},{"id":"d","text":"A cloud model with a faster internet connection"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-02-o1-c1', 'mission-vec-edge-ai-tinyml-02-o1', 1, 'multiple_choice', 'Inference, in this context, means...', '{"question":"Inference, in this context, means...","options":[{"id":"a","text":"Training a model on new data as it arrives"},{"id":"b","text":"Running a single new input forward through an already-trained model to produce an answer, with the model itself unchanged"},{"id":"c","text":"Guessing an answer without a model at all"},{"id":"d","text":"Uploading data so a human can review it later"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-02-o2-c1', 'mission-vec-edge-ai-tinyml-02-o2', 1, 'multiple_choice', 'What actually limits whether a model can run on the robot''s onboard controller?', '{"question":"What actually limits whether a model can run on the robot''s onboard controller?","options":[{"id":"a","text":"How accurate the model is in absolute terms"},{"id":"b","text":"Whether the model''s compute and memory needs fit inside the controller''s tiny, fixed hardware budget, not how good the model could theoretically be"},{"id":"c","text":"How recently the model was trained"},{"id":"d","text":"Whether the model was written in a compiled language"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-03-o1-c1', 'mission-vec-edge-ai-tinyml-03-o1', 1, 'drag_and_drop', 'Sort each resource limit into cloud-scale or edge-constrained.', '{"items":[{"id":"i1","text":"A model that can grow as long as someone keeps paying for more server hardware"},{"id":"i2","text":"A model that must fit inside a fixed number of kilobytes of flash on a single controller"},{"id":"i3","text":"A data center able to add more GPUs on demand"},{"id":"i4","text":"A battery-powered device with a fixed amount of onboard memory that cannot be upgraded mid-mission"}],"targets":[{"id":"cloud","label":"Cloud-scale"},{"id":"edge","label":"Edge-constrained"}]}'::jsonb, '{"correctMapping":{"i1":"cloud","i2":"edge","i3":"cloud","i4":"edge"}}'::jsonb),
  ('mission-vec-edge-ai-tinyml-03-o2-c1', 'mission-vec-edge-ai-tinyml-03-o2', 1, 'multiple_choice', 'Under a hard size ceiling, the real design question becomes...', '{"question":"Under a hard size ceiling, the real design question becomes...","options":[{"id":"a","text":"How good can this model theoretically be, with no other consideration"},{"id":"b","text":"How good can this model be inside a fixed budget of kilobytes -- a fundamentally different problem than designing without a ceiling"},{"id":"c","text":"Whether the model should be abandoned entirely"},{"id":"d","text":"How to convince the hardware team to add more memory"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-04-o1-c1', 'mission-vec-edge-ai-tinyml-04-o1', 1, 'multiple_choice', 'Quantization works by...', '{"question":"Quantization works by...","options":[{"id":"a","text":"Deleting entire layers of the network"},{"id":"b","text":"Storing weights as smaller, lower-precision numbers (such as 8-bit integers instead of 32-bit floats), trading a little numeric precision for much smaller size and faster execution"},{"id":"c","text":"Increasing the number of training examples"},{"id":"d","text":"Running the model twice and averaging the results"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-04-o2-c1', 'mission-vec-edge-ai-tinyml-04-o2', 1, 'multiple_choice', 'Why can a deliberately less precise, quantized model be the more correct engineering choice than a fully precise one?', '{"question":"Why can a deliberately less precise, quantized model be the more correct engineering choice than a fully precise one?","options":[{"id":"a","text":"Less precise models are always more accurate in practice"},{"id":"b","text":"A fully precise model that cannot fit on the device is not actually more correct -- it is simply unavailable exactly when it is needed"},{"id":"c","text":"Precision has no effect on model behavior at all"},{"id":"d","text":"Quantized models never make mistakes"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-05-o1-c1', 'mission-vec-edge-ai-tinyml-05-o1', 1, 'multiple_choice', 'Pruning removes...', '{"question":"Pruning removes...","options":[{"id":"a","text":"Random weights chosen without regard to their effect on the output"},{"id":"b","text":"Connections in the trained network that contribute almost nothing to the final answer, shrinking the model with minimal accuracy loss"},{"id":"c","text":"The model''s training data after training completes"},{"id":"d","text":"The input layer entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-05-o2-c1', 'mission-vec-edge-ai-tinyml-05-o2', 1, 'multiple_choice', 'Used together, quantization and pruning actually accomplish...', '{"question":"Used together, quantization and pruning actually accomplish...","options":[{"id":"a","text":"Running the exact same model, just slower"},{"id":"b","text":"Identifying what the model actually needed to know to perform its job, and discarding everything it never truly relied on"},{"id":"c","text":"Making the model impossible to validate"},{"id":"d","text":"Doubling the model''s memory footprint for safety margin"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-06-o1-c1', 'mission-vec-edge-ai-tinyml-06-o1', 1, 'interactive_diagram', 'Order the TinyML pipeline''s stages from first to last.', '{"diagramId":"tinyml-pipeline","hotspots":[{"id":"train","label":"Train","explanation":"Train the model at full size where compute is cheap and plentiful."},{"id":"quantize","label":"Quantize","explanation":"Convert weights to smaller, lower-precision numbers."},{"id":"prune","label":"Prune","explanation":"Remove connections that barely affect the output."},{"id":"convert","label":"Convert","explanation":"Convert the model into a format the target hardware can run."},{"id":"validate","label":"Validate on target","explanation":"Test on the real hardware, not a simulation of it."}],"task":"Order the stages of the TinyML pipeline from first to last."}'::jsonb, '{"correctOrderIds":["train","quantize","prune","convert","validate"]}'::jsonb),
  ('mission-vec-edge-ai-tinyml-06-o2-c1', 'mission-vec-edge-ai-tinyml-06-o2', 1, 'multiple_choice', 'Why can validating on the real target hardware not be skipped in favor of just trusting the earlier pipeline stages?', '{"question":"Why can validating on the real target hardware not be skipped in favor of just trusting the earlier pipeline stages?","options":[{"id":"a","text":"It cannot be skipped for legal reasons only"},{"id":"b","text":"A model that has never once run in its actual deployment conditions is a model whose real behavior nobody has confirmed, however well it performed elsewhere"},{"id":"c","text":"Validation is optional and mostly ceremonial"},{"id":"d","text":"Real hardware always performs identically to a simulation of it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-07-o1-c1', 'mission-vec-edge-ai-tinyml-07-o1', 1, 'multiple_choice', 'Why is a local, always-on audio classifier worth the cost of running continuously?', '{"question":"Why is a local, always-on audio classifier worth the cost of running continuously?","options":[{"id":"a","text":"Audio classification is more accurate than vision in every case"},{"id":"b","text":"A microphone is cheap to run constantly and can catch things a camera cannot, like a grinding bearing or a shout around a blind corner, without needing any uplink"},{"id":"c","text":"It replaces the need for any other sensor"},{"id":"d","text":"Audio data requires no processing at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-07-o2-c1', 'mission-vec-edge-ai-tinyml-07-o2', 1, 'multiple_choice', 'An edge audio classification model should be scoped to...', '{"question":"An edge audio classification model should be scoped to...","options":[{"id":"a","text":"Recognize every possible sound in the world with equal accuracy"},{"id":"b","text":"Reliably recognize the small handful of sounds that actually matter in this robot''s environment, rather than attempting broad general-purpose recognition"},{"id":"c","text":"Only detect silence"},{"id":"d","text":"Match the exact scope of a full cloud model"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-08-o1-c1', 'mission-vec-edge-ai-tinyml-08-o1', 1, 'multiple_choice', 'Why is vision the heaviest sense this robot carries?', '{"question":"Why is vision the heaviest sense this robot carries?","options":[{"id":"a","text":"Cameras are more expensive than microphones"},{"id":"b","text":"A single camera frame carries enormously more data than one audio window, and the model reading it must still fit the same tight hardware budget as everything else"},{"id":"c","text":"Vision models never run on constrained hardware at all"},{"id":"d","text":"Cameras require a cloud connection to function"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-08-o2-c1', 'mission-vec-edge-ai-tinyml-08-o2', 1, 'multiple_choice', 'Why does narrowing a vision model''s job -- rather than trying to recognize everything -- make edge vision possible at all?', '{"question":"Why does narrowing a vision model''s job -- rather than trying to recognize everything -- make edge vision possible at all?","options":[{"id":"a","text":"Narrow scope is a compromise that always hurts reliability"},{"id":"b","text":"A model trained and shrunk for one specific job, like obstacle-or-debris classification in a known corridor, can fit the budget where a general-purpose vision model never could"},{"id":"c","text":"Narrow models require more memory than general ones"},{"id":"d","text":"Scope has no relationship to model size"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-09-o1-c1', 'mission-vec-edge-ai-tinyml-09-o1', 1, 'multiple_choice', 'A neural network accelerator chip is best described as...', '{"question":"A neural network accelerator chip is best described as...","options":[{"id":"a","text":"A general-purpose processor with a faster clock speed"},{"id":"b","text":"A small dedicated chip built only for neural network math, with no operating system or general instructions, wired close to memory for exactly that arithmetic"},{"id":"c","text":"A chip that runs any software faster by default"},{"id":"d","text":"A backup processor used only when the main one fails"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-09-o2-c1', 'mission-vec-edge-ai-tinyml-09-o2', 1, 'multiple_choice', 'Why does a narrow-purpose accelerator outperform a general-purpose processor on inference?', '{"question":"Why does a narrow-purpose accelerator outperform a general-purpose processor on inference?","options":[{"id":"a","text":"It is simply a newer chip"},{"id":"b","text":"Doing only one kind of arithmetic, wired for exactly that job, lets it run inference far faster and on far less power than a general processor grinding through the same math alongside everything else it has to do"},{"id":"c","text":"It uses more total power to compensate for its narrow focus"},{"id":"d","text":"General-purpose processors cannot run neural networks at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-10-o1-c1', 'mission-vec-edge-ai-tinyml-10-o1', 1, 'multiple_choice', 'The single trade-off underlying model size, quantization, pruning and accelerator choice is best stated as...', '{"question":"The single trade-off underlying model size, quantization, pruning and accelerator choice is best stated as...","options":[{"id":"a","text":"How much the hardware costs to purchase"},{"id":"b","text":"How much accuracy a decision is worth, weighed against how much time it takes and how much battery it costs to reach that decision"},{"id":"c","text":"How many engineers are available to build the model"},{"id":"d","text":"How large the training dataset needs to be"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-10-o2-c1', 'mission-vec-edge-ai-tinyml-10-o2', 1, 'multiple_choice', 'Can a technically more accurate model that takes noticeably longer to answer still count as a failure?', '{"question":"Can a technically more accurate model that takes noticeably longer to answer still count as a failure?","options":[{"id":"a","text":"No, higher accuracy always wins regardless of timing"},{"id":"b","text":"Yes -- if the extra time means the answer arrives after the moment it needed to matter has already passed, the accuracy gain is irrelevant"},{"id":"c","text":"No, because timing is never actually part of correctness"},{"id":"d","text":"Only if the model also uses more memory"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-11-o1-c1', 'mission-vec-edge-ai-tinyml-11-o1', 1, 'multiple_choice', 'The real contrast between cloud inference and edge inference is...', '{"question":"The real contrast between cloud inference and edge inference is...","options":[{"id":"a","text":"Cloud inference is always more accurate in every situation"},{"id":"b","text":"Cloud inference gets scale, easy updates and quick fixes, provided the connection holds; edge inference gets none of that convenience and has to be correct the first time, on hardware finished the day it shipped"},{"id":"c","text":"Edge inference is only used for testing, never in production"},{"id":"d","text":"There is no meaningful difference once a model is trained"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-11-o2-c1', 'mission-vec-edge-ai-tinyml-11-o2', 1, 'multiple_choice', 'Why can the TinyML pipeline not skip steps when the resulting model will run with no fallback available?', '{"question":"Why can the TinyML pipeline not skip steps when the resulting model will run with no fallback available?","options":[{"id":"a","text":"Skipping steps saves negligible time anyway, so there is no incentive to skip"},{"id":"b","text":"With no update or override possible once deployed offline, trusting the model is the only option that will actually be available when the uplink is gone -- so every step that earns that trust matters"},{"id":"c","text":"The pipeline''s steps have no real effect on reliability"},{"id":"d","text":"Only the quantization step actually matters"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-edge-ai-tinyml-12-o1-c1', 'mission-vec-edge-ai-tinyml-12-o1', 1, 'investigation', 'Confirm what the on-device model classified, and find the evidence proving it was a real inference result, not a lucky guess.', '{"evidence":[{"id":"e1","label":"On-device inference log","detail":"Quantized model output: class OBSTACLE, confidence 0.94, produced from a validated 8-bit weight set occupying a fraction of the memory the full-precision cloud version needs"},{"id":"e2","label":"Facility note","detail":"The corridor lighting has flickered intermittently for the past two weeks"},{"id":"e3","label":"Maintenance schedule","detail":"The robot is due for a routine battery service next week"}],"question":"Which evidence proves the on-device classification was a real, specific inference result rather than a guess?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-edge-ai-tinyml-12-o2-c1', 'mission-vec-edge-ai-tinyml-12-o2', 1, 'multiple_choice', 'The robot needed a decision in milliseconds with the uplink down. Would a cloud round trip to Byte have delivered an answer in time, had the uplink somehow still been up?', '{"question":"The robot needed a decision in milliseconds with the uplink down. Would a cloud round trip to Byte have delivered an answer in time, had the uplink somehow still been up?","options":[{"id":"a","text":"Yes, cloud round trips are always fast enough for any decision"},{"id":"b","text":"No -- by the time a request could travel out, be classified remotely, and travel back, the moment requiring action would already have passed; only on-device inference could resolve in time"},{"id":"c","text":"It is impossible to know without testing the exact network"},{"id":"d","text":"Yes, because Byte processes requests instantly regardless of distance"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-12-o3-c1', 'mission-vec-edge-ai-tinyml-12-o3', 1, 'multiple_choice', 'What does this moment actually reveal about the relationship between AI and robotics from here forward?', '{"question":"What does this moment actually reveal about the relationship between AI and robotics from here forward?","options":[{"id":"a","text":"AI and robotics remain two separate tracks that only occasionally intersect"},{"id":"b","text":"They are merging: intelligence must now run wherever the decision actually needs to happen, under real power, latency, connectivity and safety constraints, not wherever it was most convenient to develop"},{"id":"c","text":"Robotics no longer needs AI now that failsafes exist"},{"id":"d","text":"AI should always run in the cloud and robotics should always compensate for the delay"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-edge-ai-tinyml-12-o4-c1', 'mission-vec-edge-ai-tinyml-12-o4', 1, 'boss_encounter', 'Having confirmed the classification, proven the timing, and named the realization, state what Vector Division now has to design for.', '{"stages":[{"objectiveRef":"mission-vec-edge-ai-tinyml-12-o1","label":"Confirm the classification"},{"objectiveRef":"mission-vec-edge-ai-tinyml-12-o2","label":"Prove the cloud round trip would have been too slow"},{"objectiveRef":"mission-vec-edge-ai-tinyml-12-o3","label":"Name what actually just happened"}],"task":"State the mission in one sentence: intelligence without internet is no longer a special case Vector Division occasionally handles -- it is the default every future system has to be designed for."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-edge-ai-tinyml-12-o1","mission-vec-edge-ai-tinyml-12-o2","mission-vec-edge-ai-tinyml-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-edge-ai-tinyml-01-o1-c1', 'orientation', 'Think about what Byte''s judgment has always depended on existing between it and the robot.', 10, 1),
  ('mission-vec-edge-ai-tinyml-01-o1-c1', 'solution', 'Every one of Byte''s classifications assumes a live connection back to Byte -- and the robot''s sub-levels have no reliable connectivity for that connection to exist on.', 20, 2),
  ('mission-vec-edge-ai-tinyml-01-o2-c1', 'orientation', 'The definition is about where the arithmetic runs, not about how smart the model is.', 10, 1),
  ('mission-vec-edge-ai-tinyml-01-o2-c1', 'solution', 'Edge AI means running inference directly on the local device, instead of sending data out to a remote server and waiting.', 20, 2),

  ('mission-vec-edge-ai-tinyml-02-o1-c1', 'orientation', 'Inference is what happens after training is already finished.', 10, 1),
  ('mission-vec-edge-ai-tinyml-02-o1-c1', 'solution', 'Inference is running one new input forward through an already-trained, unchanged model to get an answer -- no learning happens at this step.', 20, 2),
  ('mission-vec-edge-ai-tinyml-02-o2-c1', 'orientation', 'The controller does not care how good a model could be in theory -- only what actually fits.', 10, 1),
  ('mission-vec-edge-ai-tinyml-02-o2-c1', 'solution', 'The real limit is whether the model''s compute and memory needs fit inside the controller''s tiny, fixed hardware budget.', 20, 2),

  ('mission-vec-edge-ai-tinyml-03-o1-c1', 'orientation', 'Ask whether the resource can grow on demand, or is fixed the day the hardware ships.', 10, 1),
  ('mission-vec-edge-ai-tinyml-03-o1-c1', 'solution', 'Cloud-scale: growing server hardware and on-demand GPUs. Edge-constrained: a fixed flash budget and a fixed onboard memory ceiling.', 20, 2),
  ('mission-vec-edge-ai-tinyml-03-o2-c1', 'orientation', 'The size ceiling changes the question being asked, not just the answer.', 10, 1),
  ('mission-vec-edge-ai-tinyml-03-o2-c1', 'solution', 'The question becomes how good the model can be inside a fixed kilobyte budget -- a fundamentally different design problem than designing with no ceiling at all.', 20, 2),

  ('mission-vec-edge-ai-tinyml-04-o1-c1', 'orientation', 'Think about what a weight is normally stored as, versus what quantization stores it as instead.', 10, 1),
  ('mission-vec-edge-ai-tinyml-04-o1-c1', 'solution', 'Quantization stores weights as smaller, lower-precision numbers (like 8-bit integers instead of 32-bit floats), trading a little precision for much smaller size and faster execution.', 20, 2),
  ('mission-vec-edge-ai-tinyml-04-o2-c1', 'orientation', 'Ask what "correct" actually means for a model that cannot physically be deployed.', 10, 1),
  ('mission-vec-edge-ai-tinyml-04-o2-c1', 'solution', 'A fully precise model that does not fit on the device is not more correct -- it is simply unavailable exactly when it is needed.', 20, 2),

  ('mission-vec-edge-ai-tinyml-05-o1-c1', 'orientation', 'Pruning targets connections by how much they actually matter, not at random.', 10, 1),
  ('mission-vec-edge-ai-tinyml-05-o1-c1', 'solution', 'Pruning removes connections that contribute almost nothing to the final answer, shrinking the model with minimal accuracy loss.', 20, 2),
  ('mission-vec-edge-ai-tinyml-05-o2-c1', 'orientation', 'Think about what is left over once both levers have been applied together.', 10, 1),
  ('mission-vec-edge-ai-tinyml-05-o2-c1', 'solution', 'Together they identify what the model actually needed to know, and discard everything it never truly relied on.', 20, 2),

  ('mission-vec-edge-ai-tinyml-06-o1-c1', 'orientation', 'Nothing can be quantized or pruned before it has first been trained at full size.', 10, 1),
  ('mission-vec-edge-ai-tinyml-06-o1-c1', 'solution', 'Train, quantize, prune, convert, then validate on the real target hardware -- in exactly that order.', 20, 2),
  ('mission-vec-edge-ai-tinyml-06-o2-c1', 'orientation', 'Ask what earlier pipeline stages can actually guarantee about behavior in real deployment conditions.', 10, 1),
  ('mission-vec-edge-ai-tinyml-06-o2-c1', 'solution', 'A model that has never run in its real deployment conditions has behavior nobody has actually confirmed, no matter how well it performed elsewhere.', 20, 2),

  ('mission-vec-edge-ai-tinyml-07-o1-c1', 'orientation', 'Think about what a microphone can catch that a camera physically cannot.', 10, 1),
  ('mission-vec-edge-ai-tinyml-07-o1-c1', 'solution', 'A microphone is cheap to run continuously and can catch things like a grinding bearing or a shout around a blind corner, with no uplink required.', 20, 2),
  ('mission-vec-edge-ai-tinyml-07-o2-c1', 'orientation', 'A tiny model cannot be broad -- ask what it should be narrow about instead.', 10, 1),
  ('mission-vec-edge-ai-tinyml-07-o2-c1', 'solution', 'It should be scoped to reliably recognize the small handful of sounds that actually matter in this specific environment, not general-purpose recognition.', 20, 2),

  ('mission-vec-edge-ai-tinyml-08-o1-c1', 'orientation', 'Compare how much raw data one camera frame carries against one audio window.', 10, 1),
  ('mission-vec-edge-ai-tinyml-08-o1-c1', 'solution', 'A single camera frame carries far more data than an audio window, and the model reading it must still fit the same tight hardware budget as everything else.', 20, 2),
  ('mission-vec-edge-ai-tinyml-08-o2-c1', 'orientation', 'A narrow job is a smaller job -- think about what that does to the model needed to do it.', 10, 1),
  ('mission-vec-edge-ai-tinyml-08-o2-c1', 'solution', 'A model trained and shrunk for one specific job, like obstacle-or-debris classification in a known corridor, fits the budget where a general-purpose model never could.', 20, 2),

  ('mission-vec-edge-ai-tinyml-09-o1-c1', 'orientation', 'Think about what the chip does not have, compared to a general processor.', 10, 1),
  ('mission-vec-edge-ai-tinyml-09-o1-c1', 'solution', 'An accelerator is a small dedicated chip built only for neural network math, with no operating system or general instructions, wired close to memory.', 20, 2),
  ('mission-vec-edge-ai-tinyml-09-o2-c1', 'orientation', 'Doing only one thing well is exactly why it is efficient at that one thing.', 10, 1),
  ('mission-vec-edge-ai-tinyml-09-o2-c1', 'solution', 'Being wired for exactly one kind of arithmetic lets it run inference far faster and on far less power than a general-purpose processor doing the same math alongside everything else.', 20, 2),

  ('mission-vec-edge-ai-tinyml-10-o1-c1', 'orientation', 'Every choice this Act -- size, quantization, pruning, accelerator -- has really been about the same two costs.', 10, 1),
  ('mission-vec-edge-ai-tinyml-10-o1-c1', 'solution', 'It is how much accuracy a decision is worth, weighed against how much time and how much battery it costs to reach it.', 20, 2),
  ('mission-vec-edge-ai-tinyml-10-o2-c1', 'orientation', 'Ask whether an answer that arrives after the moment has passed can still be useful.', 10, 1),
  ('mission-vec-edge-ai-tinyml-10-o2-c1', 'solution', 'Yes -- if the extra time means the moment it needed to matter has already passed, the accuracy gain is irrelevant.', 20, 2),

  ('mission-vec-edge-ai-tinyml-11-o1-c1', 'orientation', 'Weigh what each side gains, and what each side risks losing if a key assumption fails.', 10, 1),
  ('mission-vec-edge-ai-tinyml-11-o1-c1', 'solution', 'Cloud gets scale, updates and quick fixes if the connection holds; edge gets none of that and has to be right the first time on hardware finished the day it shipped.', 20, 2),
  ('mission-vec-edge-ai-tinyml-11-o2-c1', 'orientation', 'Think about what happens after deployment if the model is ever wrong and there is no way back to fix it.', 10, 1),
  ('mission-vec-edge-ai-tinyml-11-o2-c1', 'solution', 'With no update or override possible offline, trust earned through the full pipeline is the only thing that will actually be available when the uplink is gone.', 20, 2),

  ('mission-vec-edge-ai-tinyml-12-o1-c1', 'orientation', 'Look for the record that shows a specific class, a specific confidence, and a specific validated model, not just an outcome.', 10, 1),
  ('mission-vec-edge-ai-tinyml-12-o1-c1', 'solution', 'e1: the on-device inference log shows OBSTACLE at 0.94 confidence from a validated quantized weight set -- a real, specific inference result.', 20, 2),
  ('mission-vec-edge-ai-tinyml-12-o2-c1', 'orientation', 'Think about how many trips a request has to make to reach Byte and come back, versus how many milliseconds the robot actually had.', 10, 1),
  ('mission-vec-edge-ai-tinyml-12-o2-c1', 'solution', 'No -- the round trip out and back would have taken longer than the robot had, so only on-device inference could resolve in time.', 20, 2),
  ('mission-vec-edge-ai-tinyml-12-o3-c1', 'orientation', 'This is not just about one robot -- it is about where intelligence has to live from now on.', 10, 1),
  ('mission-vec-edge-ai-tinyml-12-o3-c1', 'solution', 'AI and robotics are merging: intelligence must run wherever the decision actually needs to happen, under real power, latency, connectivity and safety constraints.', 20, 2),
  ('mission-vec-edge-ai-tinyml-12-o4-c1', 'orientation', 'Look at what all three prior judgments point to as a standing design requirement, not a one-time fix.', 15, 1),
  ('mission-vec-edge-ai-tinyml-12-o4-c1', 'solution', 'Intelligence without internet is not a special case anymore -- it is the default Vector Division has to design for from here forward.', 25, 2);
