-- Backend Engineering ("The Fracture") Act 1 -- "The Request" content.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every Cyber Guardians world.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be1', 'world-be-1', 'the-request', '1A - The Request', 'Trace one HTTP request end to end and learn why the city''s emergency endpoint cannot tell success from failure.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be1-1', 'campaign-be1', 'ground-floor', 'Ground Floor', 'The client/server model, addressing and the connections underneath every request.', 1),
  ('operation-be1-2', 'campaign-be1', 'the-secure-channel', 'The Secure Channel', 'TLS, the anatomy of a request and response, and the contract that broke.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be1-01', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'welcome-to-forge-division', 'Welcome to Forge Division', 'Mira Voss pulls you into Forge Division: nothing has been attacked, systems are just failing, and nobody knows why yet.', 'intro', ARRAY['mira','forge'], null, null, '{"type":"none"}'::jsonb, '{"xp":50,"credits":10}'::jsonb, false, 1),
  ('mission-be1-02', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'what-happens-when-you-enter-a-url', 'What Happens When You Enter a URL?', 'Six stages happen before a browser shows anything at all. Get the order wrong and every later diagnosis is built on sand.', 'beginner', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"url-lifecycle-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-be1-03', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'client-and-server', 'Client and Server', 'Two sides, one asking and one answering, with an asymmetry that decides where an investigation should actually start.', 'beginner', ARRAY['mira'], '{"requiredMissionIds":["mission-be1-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"client-server-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 3),
  ('mission-be1-04', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'ip-addresses-and-ports', 'IP Addresses and Ports', 'An address gets you to the right machine. A port gets you to the right door. Confuse them and you debug blind.', 'beginner', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"port-mapping-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 4),
  ('mission-be1-05', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'dns-resolution', 'DNS Resolution', 'A name has to become an address before anything else can happen, and the chain that does it has more steps -- and more places to go stale -- than people expect.', 'beginner', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be1-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"dns-lookup-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 5),
  ('mission-be1-06', 'world-be-1', 'campaign-be1', 'operation-be1-1', 'tcp-connection', 'TCP Connection', 'HTTP assumes a reliable stream underneath it. Three packets are what actually make that promise true.', 'beginner', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"tcp-handshake-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 6),
  ('mission-be1-07', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'tls-and-https', 'TLS and HTTPS', 'A reliable connection says nothing about who you''re really talking to, or who else might be reading it. TLS buys three separate guarantees at once.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be1-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"tls-handshake-sim"}'::jsonb, '{"xp":130,"credits":20}'::jsonb, false, 7),
  ('mission-be1-08', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'http-request-anatomy', 'HTTP Request Anatomy', 'Every request is just structured text. Learn to read it raw and no client library''s abstraction will ever fool you again.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"http-request-sim"}'::jsonb, '{"xp":120,"credits":20}'::jsonb, false, 8),
  ('mission-be1-09', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'http-response-anatomy', 'HTTP Response Anatomy', 'The actual response the emergency endpoint sent during the incident. Read it the way a client''s code would, not the way a human skims a log.', 'intermediate', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be1-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"http-response-sim"}'::jsonb, '{"xp":130,"credits":20}'::jsonb, false, 9),
  ('mission-be1-10', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'methods-and-status-codes', 'Methods and Status Codes', 'Methods say what you''re trying to do. Status codes say what actually happened. Mixing those up is exactly how you get a 200 that means "error."', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"methods-status-sim"}'::jsonb, '{"xp":130,"credits":20}'::jsonb, false, 10),
  ('mission-be1-11', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'json-and-serialization', 'JSON and Serialization', 'Every body you''ve read this Act is JSON on the wire and a real data structure in memory. Serialization is the bridge between the two, and bridges can be built wrong.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be1-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"json-debug-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 11),
  ('mission-be1-12', 'world-be-1', 'campaign-be1', 'operation-be1-2', 'the-silent-endpoint', 'The Silent Endpoint', 'The emergency dispatch endpoint, under real load, responding to real requests -- and clients still cannot tell success from failure. Everything this Act taught, at once.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be1-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"silent-endpoint-boss-sim"}'::jsonb, '{"xp":380,"credits":80,"badgeIds":["silent-endpoint"],"skillXp":{"networking":20,"backend_fundamentals":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be1-01', 1, 'mira', 'The Cybersecurity campaign is over. This isn''t that. Nothing here has been attacked -- not yet. It''s just... failing.'),
  ('mission-be1-01', 2, 'mira', 'A payment charged twice. A hospital request that never arrived. A database that tells two different investigators two different truths. No exploit, no intrusion. Just architecture doing exactly what it was built to do, and that not being enough.'),
  ('mission-be1-01', 3, 'forge', 'Ops link established. I''m Forge -- think of me as the part of this division that never sleeps and occasionally judges your indentation.'),
  ('mission-be1-01', 4, 'mira', 'We call the pattern The Fracture. It doesn''t ask ''how do I get in.'' It asks one question, over and over: what happens when this fails? Most systems never bother to answer that. We''re going to teach you to answer it before it''s asked.'),
  ('mission-be1-01', 5, 'mira', 'First lesson, older than any framework: understand what actually happens the moment someone hits enter on a URL. Everything else is built on top of that.'),
  ('mission-be1-02', 1, 'forge', 'The emergency endpoint''s failure log starts here: someone types a URL and hits enter. Everything downstream depends on this sequence happening correctly, in order.'),
  ('mission-be1-02', 2, 'forge', 'Six things happen before your screen shows anything at all. Get the order wrong in your head and you''ll misdiagnose everything after it.'),
  ('mission-be1-03', 1, 'mira', 'The endpoint that failed has exactly two sides: something asking, something answering. Sounds obvious. It''s the single most common thing engineers get wrong under pressure.'),
  ('mission-be1-03', 2, 'mira', 'A client can retry, cancel, or give up and never tell you. A server can''t do any of those -- it can only respond to what it''s given, when it''s asked. That asymmetry is the whole game.'),
  ('mission-be1-04', 1, 'forge', 'An IP address gets you to the right machine. A port gets you to the right door on that machine. Confuse the two and you''ll bang on a locked door for an hour.'),
  ('mission-be1-04', 2, 'forge', 'Forge Division runs a lot of services on one host during triage. If you don''t know which port is which, you''re debugging blind.'),
  ('mission-be1-05', 1, 'mira', 'Before any of this works, a name has to become an address. That''s the entire job of DNS, and it has more moving parts than people expect.'),
  ('mission-be1-05', 2, 'forge', 'Browser cache, OS cache, resolver, root, TLD, authoritative -- in the worst case, all six get consulted before anyone gets an answer.'),
  ('mission-be1-06', 1, 'forge', 'HTTP assumes a reliable, ordered stream underneath it. TCP is what actually makes that promise true. Three packets, and the whole rest of the web stands on them.'),
  ('mission-be1-06', 2, 'forge', 'Get this handshake wrong in your mental model and "connection refused" versus "connection timed out" will keep looking like the same bug. They are not the same bug.'),
  ('mission-be1-07', 1, 'mira', 'TCP gets your bytes there reliably. It says nothing about whether anyone else can read them, or whether you''re even talking to who you think you are. That''s TLS''s job, and it''s where the silent endpoint incident starts getting interesting.'),
  ('mission-be1-07', 2, 'mira', 'TLS buys you three things at once: confidentiality, integrity and authentication. Lose track of which one solves which problem and you''ll reach for encryption to fix something encryption was never going to fix.'),
  ('mission-be1-08', 1, 'forge', 'Every HTTP request is just structured text, even the ones flying past at ten thousand a second. Learn to read it raw and you''ll never be fooled by a client library''s abstraction again.'),
  ('mission-be1-09', 1, 'forge', 'Here''s the response the emergency endpoint actually sent back during the incident. Read it the way a client''s code would -- not the way a human skimming a log would.'),
  ('mission-be1-09', 2, 'mira', 'This is the one I want you to sit with. Somewhere in here is the entire reason clients couldn''t tell success from failure.'),
  ('mission-be1-10', 1, 'forge', 'Now the vocabulary itself. Methods say what you''re trying to do. Status codes say what actually happened. Mixing those up is exactly how you get a 200 that means "error."'),
  ('mission-be1-11', 1, 'forge', 'Every request and response body we''ve looked at is JSON on the wire and a real data structure in memory. Serialization is the bridge between those two. Bridges can be built wrong.'),
  ('mission-be1-12', 1, 'mira', 'Everything you''ve traced this Act led here. The emergency dispatch endpoint, under real load, responding to real requests -- and clients still can''t tell success from failure.'),
  ('mission-be1-12', 2, 'forge', 'I''ve pulled three responses from the incident window. Same endpoint, same nominal "success" status on all of them. Not all of them are actually successes.'),
  ('mission-be1-12', 3, 'mira', 'Don''t fix code today. Just tell me, for each one, whether the client should trust it -- and why. That''s the job. That''s always the job.'),
  ('mission-be1-12', 4, 'forge', '...one more thing. Every one of these came through a path with a doubled slash: /dispatch//emergency. It isn''t breaking anything today. It isn''t the first time I''ve seen it either.'),
  ('mission-be1-12', 5, 'mira', 'Noted. File it. We''re not done asking about that pattern -- not this Act, and I don''t think it stays quiet forever.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be1-01-o1', 'mission-be1-01', 1, 'Report for duty', 'Confirm you understand the situation before Mira sends you into the field.'),
  ('mission-be1-02-o1', 'mission-be1-02', 1, 'Order the journey', 'Put the six stages of a request in the order they actually happen.'),
  ('mission-be1-03-o1', 'mission-be1-03', 1, 'Assign the responsibility', 'Decide where an investigation should actually start when a request appears to hang.'),
  ('mission-be1-03-o2', 'mission-be1-03', 2, 'Name the layer', 'Sort each behavior into client or server.'),
  ('mission-be1-04-o1', 'mission-be1-04', 1, 'Match the ports', 'Match each well-known port to the service that owns it.'),
  ('mission-be1-04-o2', 'mission-be1-04', 2, 'Read the address', 'Find the evidence that explains why the same code behaves differently in two places.'),
  ('mission-be1-05-o1', 'mission-be1-05', 1, 'Trace the lookup', 'Order the DNS lookup chain from first-checked to final authority.'),
  ('mission-be1-05-o2', 'mission-be1-05', 2, 'Diagnose the failure', 'Explain why the same hostname resolves inconsistently right after a change.'),
  ('mission-be1-06-o1', 'mission-be1-06', 1, 'The three-way handshake', 'Order the three packets that open a TCP connection.'),
  ('mission-be1-06-o2', 'mission-be1-06', 2, 'Refused or timed out?', 'Tell apart two failures that look similar from the outside but mean very different things.'),
  ('mission-be1-07-o1', 'mission-be1-07', 1, 'Match the guarantee', 'Match each real-world need to the TLS guarantee that actually covers it.'),
  ('mission-be1-07-o2', 'mission-be1-07', 2, 'Spot the missing guarantee', 'Find the single root cause behind a dispatch endpoint leaking data in transit.'),
  ('mission-be1-08-o1', 'mission-be1-08', 1, 'Read the raw request', 'Identify the one line that determines the action being requested.'),
  ('mission-be1-09-o1', 'mission-be1-09', 1, 'Read the raw response', 'Identify the line that contradicts the response''s own status code.'),
  ('mission-be1-10-o1', 'mission-be1-10', 1, 'Match the method', 'Match each HTTP method to what it''s meant to do.'),
  ('mission-be1-10-o2', 'mission-be1-10', 2, 'Match the status code', 'Match each status code to what it actually means.'),
  ('mission-be1-11-o1', 'mission-be1-11', 1, 'Find the serialization bug', 'Find the line that breaks a client expecting a real boolean.'),
  ('mission-be1-12-o1', 'mission-be1-12', 1, 'Response Alpha', 'Judge whether the client should trust this response.'),
  ('mission-be1-12-o2', 'mission-be1-12', 2, 'Response Bravo', 'Judge whether the client should trust this response.'),
  ('mission-be1-12-o3', 'mission-be1-12', 3, 'Response Charlie', 'Judge whether the client should trust this response.'),
  ('mission-be1-12-o4', 'mission-be1-12', 4, 'Fix the contract', 'State the one architectural rule that would have prevented this incident.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be1-01-o1-c1', 'mission-be1-01-o1', 1, 'story_dialogue', 'Confirm you''re ready to continue.', '{"lines":[{"characterId":"mira","text":"Before we go further -- are you with us?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),

  ('mission-be1-02-o1-c1', 'mission-be1-02-o1', 1, 'interactive_diagram', 'Put the six stages of a request in the order they actually happen.', '{"diagramId":"url-request-lifecycle","hotspots":[{"id":"dns","label":"DNS resolution","explanation":"The browser turns the hostname into an IP address it can actually route to."},{"id":"tcp","label":"TCP handshake","explanation":"The client and server agree to open a reliable connection before any data is sent."},{"id":"tls","label":"TLS handshake","explanation":"Client and server negotiate encryption and verify identity, if the URL is https."},{"id":"request","label":"HTTP request sent","explanation":"The browser sends a method, a path, headers and maybe a body over the open connection."},{"id":"process","label":"Server processes the request","explanation":"The server routes the request to the right handler and does the actual work."},{"id":"response","label":"HTTP response returned","explanation":"The server sends back a status code, headers and a body, and the browser renders it."}],"task":"Put the six stages of a request in the order they actually happen."}'::jsonb, '{"correctOrderIds":["dns","tcp","tls","request","process","response"]}'::jsonb),

  ('mission-be1-03-o1-c1', 'mission-be1-03-o1', 1, 'multiple_choice', 'A user reports the page "just spins forever" after they submit a form. Where does the investigation actually start?', '{"question":"A user reports the page \"just spins forever\" after they submit a form. Where does the responsibility to investigate start?","options":[{"id":"a","text":"The server, since it does the real work"},{"id":"b","text":"The client, since that''s what the user can see"},{"id":"c","text":"Whichever side last had definite proof the request was sent, and definite proof a response came back"},{"id":"d","text":"It doesn''t matter, they''re the same thing"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-be1-03-o2-c1', 'mission-be1-03-o2', 1, 'drag_and_drop', 'Sort each behavior into client or server.', '{"items":[{"id":"d1","text":"Renders HTML/CSS so a human can read it"},{"id":"d2","text":"Stores data durably across requests and restarts"},{"id":"d3","text":"Initiates the request"},{"id":"d4","text":"Decides what a request is even allowed to do"},{"id":"d5","text":"Has no memory of the last request by default"}],"targets":[{"id":"client","label":"Client"},{"id":"server","label":"Server"}]}'::jsonb, '{"correctMapping":{"d1":"client","d2":"server","d3":"client","d4":"server","d5":"client"}}'::jsonb),

  ('mission-be1-04-o1-c1', 'mission-be1-04-o1', 1, 'drag_and_drop', 'Match each well-known port to the service that owns it.', '{"items":[{"id":"p1","text":"80"},{"id":"p2","text":"443"},{"id":"p3","text":"22"},{"id":"p4","text":"5432"},{"id":"p5","text":"3000"}],"targets":[{"id":"t1","label":"HTTP (plaintext web)"},{"id":"t2","label":"HTTPS (encrypted web)"},{"id":"t3","label":"SSH (remote admin)"},{"id":"t4","label":"PostgreSQL (database)"},{"id":"t5","label":"A typical local dev server"}]}'::jsonb, '{"correctMapping":{"p1":"t1","p2":"t2","p3":"t3","p4":"t4","p5":"t5"}}'::jsonb),
  ('mission-be1-04-o2-c1', 'mission-be1-04-o2', 1, 'investigation', 'Which piece of evidence best explains why the same code behaves differently in two places?', '{"evidence":[{"id":"ev1","label":"Request log entry","detail":"Client 203.0.113.7:51422 -> Server 10.0.4.12:443"},{"id":"ev2","label":"Firewall note","detail":"Port 4443 was left open on 10.0.4.12 from a decommissioned debug build"},{"id":"ev3","label":"Client complaint","detail":"\"It works fine on my machine at localhost:3000\""}],"question":"Which piece of evidence best explains why the same code behaves differently in two places?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be1-05-o1-c1', 'mission-be1-05-o1', 1, 'interactive_diagram', 'Order the DNS lookup chain from first-checked to final authority.', '{"diagramId":"dns-lookup-chain","hotspots":[{"id":"browser_cache","label":"Browser cache","explanation":"Checked first -- if this hostname was resolved recently, nothing else is even contacted."},{"id":"os_cache","label":"OS resolver cache","explanation":"The operating system keeps its own recent-answer cache, checked next."},{"id":"recursive_resolver","label":"Recursive resolver (ISP/public DNS)","explanation":"Takes over the search on your behalf once nothing was cached locally."},{"id":"root_server","label":"Root server","explanation":"Doesn''t know the answer -- just points to who handles this domain''s top-level suffix."},{"id":"tld_server","label":"TLD server","explanation":"Points to the authoritative server for this specific domain."},{"id":"authoritative_server","label":"Authoritative server","explanation":"The actual source of truth for this domain''s records -- gives the real answer."}],"task":"Order the DNS lookup chain from first-checked to final authority."}'::jsonb, '{"correctOrderIds":["browser_cache","os_cache","recursive_resolver","root_server","tld_server","authoritative_server"]}'::jsonb),
  ('mission-be1-05-o2-c1', 'mission-be1-05-o2', 1, 'investigation', 'What actually explains the inconsistent failures?', '{"evidence":[{"id":"ev1","label":"Client report","detail":"api.nexuscity.io fails to resolve for some users, works for others, at the same time"},{"id":"ev2","label":"TTL record","detail":"The DNS record''s TTL was set to 86400 seconds (24h) two hours after the IP changed"},{"id":"ev3","label":"Resolver test","detail":"A fresh DNS query from an uncached resolver returns the new, correct IP immediately"}],"question":"What actually explains the inconsistent failures?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be1-06-o1-c1', 'mission-be1-06-o1', 1, 'interactive_diagram', 'Order the three packets of the TCP handshake.', '{"diagramId":"tcp-three-way-handshake","hotspots":[{"id":"syn","label":"SYN","explanation":"Client proposes a connection and an initial sequence number."},{"id":"syn_ack","label":"SYN-ACK","explanation":"Server acknowledges the client''s SYN and proposes its own sequence number."},{"id":"ack","label":"ACK","explanation":"Client acknowledges the server''s SYN-ACK -- the connection is now open in both directions."}],"task":"Order the three packets of the TCP handshake."}'::jsonb, '{"correctOrderIds":["syn","syn_ack","ack"]}'::jsonb),
  ('mission-be1-06-o2-c1', 'mission-be1-06-o2', 1, 'multiple_choice', 'A client gets "connection refused" in under a second. A different client on the same request gets no response for 30 seconds, then a timeout. What''s the difference?', '{"question":"A client gets \"connection refused\" in under a second. A different client on the same request gets no response for 30 seconds, then a timeout. What''s the difference?","options":[{"id":"a","text":"They''re the same failure, just at different speeds"},{"id":"b","text":"Refused means a host answered and explicitly rejected the connection (nothing listening on that port); timeout means the packets likely never got a response at all (host down, or a firewall dropping them silently)"},{"id":"c","text":"Refused always means a firewall; timeout always means the server crashed"},{"id":"d","text":"A timeout is only possible over HTTPS"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be1-07-o1-c1', 'mission-be1-07-o1', 1, 'drag_and_drop', 'Match each need to the TLS guarantee that actually covers it.', '{"items":[{"id":"g1","text":"An eavesdropper on the network can''t read the request body"},{"id":"g2","text":"The client can verify it''s actually talking to nexuscity.io, not an impostor"},{"id":"g3","text":"If even one byte is altered in transit, the connection detects it"}],"targets":[{"id":"t1","label":"Confidentiality"},{"id":"t2","label":"Authentication"},{"id":"t3","label":"Integrity"}]}'::jsonb, '{"correctMapping":{"g1":"t1","g2":"t2","g3":"t3"}}'::jsonb),
  ('mission-be1-07-o2-c1', 'mission-be1-07-o2', 1, 'investigation', 'Which single change would restore the guarantee that''s actually missing here?', '{"evidence":[{"id":"ev1","label":"Endpoint URL","detail":"http://emergency.nexuscity.io/dispatch (no ''s'')"},{"id":"ev2","label":"Response headers","detail":"Server responds successfully over plaintext, no certificate involved"},{"id":"ev3","label":"Traffic capture","detail":"Dispatch payloads, including addresses and medical codes, visible in plaintext to anyone on the network path"}],"question":"Which single piece of evidence points at the actual root cause, not just a symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be1-08-o1-c1', 'mission-be1-08-o1', 1, 'code_debugging', 'Which single line determines both the action being requested and the resource it applies to?', '{"language":"http","code":"POST /dispatch/emergency HTTP/1.1\nHost: emergency.nexuscity.io\nContent-Type: application/json\nContent-Length: 58\nAuthorization: Bearer sx-forge-7734\n\n{\"unit\":\"ambulance-12\",\"priority\":\"critical\",\"eta\":4}","question":"Which single line determines both the action being requested and the resource it applies to?"}'::jsonb, '{"requiredLineIds":["POST /dispatch/emergency HTTP/1.1"]}'::jsonb),

  ('mission-be1-09-o1-c1', 'mission-be1-09-o1', 1, 'code_debugging', 'A client that only checks the HTTP status code would treat this as a success. Which line actually contradicts that?', '{"language":"http","code":"HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 47\n\n{\"status\":\"error\",\"message\":\"unit unavailable\"}","question":"A client that only checks the HTTP status code would treat this as a success. Which line actually contradicts that?"}'::jsonb, '{"requiredLineIds":["{\"status\":\"error\",\"message\":\"unit unavailable\"}"]}'::jsonb),

  ('mission-be1-10-o1-c1', 'mission-be1-10-o1', 1, 'drag_and_drop', 'Match each HTTP method to what it''s meant to do.', '{"items":[{"id":"m1","text":"GET"},{"id":"m2","text":"POST"},{"id":"m3","text":"PUT"},{"id":"m4","text":"PATCH"},{"id":"m5","text":"DELETE"}],"targets":[{"id":"t1","label":"Retrieve a resource, no side effects"},{"id":"t2","label":"Create a new resource"},{"id":"t3","label":"Replace a resource entirely"},{"id":"t4","label":"Partially update a resource"},{"id":"t5","label":"Remove a resource"}]}'::jsonb, '{"correctMapping":{"m1":"t1","m2":"t2","m3":"t3","m4":"t4","m5":"t5"}}'::jsonb),
  ('mission-be1-10-o2-c1', 'mission-be1-10-o2', 1, 'drag_and_drop', 'Match each status code to what it actually means.', '{"items":[{"id":"s1","text":"200"},{"id":"s2","text":"201"},{"id":"s3","text":"400"},{"id":"s4","text":"401"},{"id":"s5","text":"404"},{"id":"s6","text":"500"}],"targets":[{"id":"t1","label":"OK -- succeeded"},{"id":"t2","label":"Created -- a new resource now exists"},{"id":"t3","label":"Bad request -- malformed input"},{"id":"t4","label":"Unauthorized -- missing/invalid credentials"},{"id":"t5","label":"Not found -- resource doesn''t exist"},{"id":"t6","label":"Internal server error -- the server itself failed"}]}'::jsonb, '{"correctMapping":{"s1":"t1","s2":"t2","s3":"t3","s4":"t4","s5":"t5","s6":"t6"}}'::jsonb),

  ('mission-be1-11-o1-c1', 'mission-be1-11-o1', 1, 'code_debugging', 'A client checks `if (response.dispatched)` expecting a real boolean, and it always evaluates true -- even when dispatch failed. Which line is the actual bug?', '{"language":"json","code":"{\n  \"unit\": \"ambulance-12\",\n  \"dispatched\": \"true\",\n  \"eta_minutes\": 4,\n  \"priority\": \"critical\"\n}","question":"A client checks `if (response.dispatched)` expecting a real boolean, and it always evaluates true -- even when dispatch failed. Which line is the actual bug?"}'::jsonb, '{"requiredLineIds":["  \"dispatched\": \"true\","]}'::jsonb),

  ('mission-be1-12-o1-c1', 'mission-be1-12-o1', 1, 'multiple_choice', 'Response Alpha: HTTP/1.1 200 OK, body {"status":"ok","unit":"ambulance-3","eta_minutes":6}. Should the client trust it?', '{"question":"Response Alpha: `HTTP/1.1 200 OK` with body `{\"status\":\"ok\",\"unit\":\"ambulance-3\",\"eta_minutes\":6}`. Should the client treat this as a genuine success?","options":[{"id":"a","text":"Yes -- the status line and the body agree"},{"id":"b","text":"No -- the status code alone is never enough"},{"id":"c","text":"No -- eta_minutes should be a string"},{"id":"d","text":"Unknowable without seeing the request"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-be1-12-o2-c1', 'mission-be1-12-o2', 1, 'multiple_choice', 'Response Bravo: HTTP/1.1 200 OK, body {"status":"error","message":"no unit available"}. Should the client trust it?', '{"question":"Response Bravo: `HTTP/1.1 200 OK` with body `{\"status\":\"error\",\"message\":\"no unit available\"}`. Should the client treat this as a genuine success?","options":[{"id":"a","text":"Yes, the status code is 200"},{"id":"b","text":"No -- the status line and the body''s own status field contradict each other, and the body is the more specific source of truth"},{"id":"c","text":"No, because 200 responses can never have a message field"},{"id":"d","text":"Yes, the message field is purely informational"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be1-12-o3-c1', 'mission-be1-12-o3', 1, 'multiple_choice', 'Response Charlie: HTTP/1.1 503 Service Unavailable, empty body. Should the client trust it?', '{"question":"Response Charlie: `HTTP/1.1 503 Service Unavailable` with an empty body. Should the client treat this as a genuine success?","options":[{"id":"a","text":"Yes, an empty body means nothing went wrong"},{"id":"b","text":"No -- 503 itself already says the server couldn''t handle the request; no body is needed to know that"},{"id":"c","text":"Unknowable, need to see the headers"},{"id":"d","text":"Yes, since there''s no error message"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be1-12-o4-c1', 'mission-be1-12-o4', 1, 'boss_encounter', 'Having judged all three responses, state the one architectural rule that would have prevented this incident.', '{"stages":[{"objectiveRef":"mission-be1-12-o1","label":"Response Alpha"},{"objectiveRef":"mission-be1-12-o2","label":"Response Bravo"},{"objectiveRef":"mission-be1-12-o3","label":"Response Charlie"}],"task":"Having judged all three responses, state the one architectural rule that would have prevented this incident: the HTTP status code and the response body must always agree about success or failure."}'::jsonb, '{"requiredObjectiveIds":["mission-be1-12-o1","mission-be1-12-o2","mission-be1-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be1-01-o1-c1', 'orientation', 'There''s nothing to solve here -- just confirm you''re ready to continue.', 0, 1),

  ('mission-be1-02-o1-c1', 'orientation', 'Nothing can be sent anywhere until the browser knows an address to send it to.', 10, 1),
  ('mission-be1-02-o1-c1', 'concept', 'A connection has to exist before encryption can be negotiated on top of it, and encryption has to exist before request data is safe to send.', 20, 2),
  ('mission-be1-02-o1-c1', 'tool_direction', 'Separate ''getting connected'' from ''talking once connected'' -- three stages do the first, three do the second.', 30, 3),
  ('mission-be1-02-o1-c1', 'solution', 'DNS resolution, then the TCP handshake, then TLS, then the request goes out, the server processes it, then the response comes back.', 40, 4),

  ('mission-be1-03-o1-c1', 'orientation', '''Where the user is looking'' and ''where the truth is'' aren''t always the same place.', 10, 1),
  ('mission-be1-03-o1-c1', 'concept', 'A spinner just means the client hasn''t received a response yet -- it doesn''t tell you why.', 20, 2),
  ('mission-be1-03-o1-c1', 'solution', 'Find the last point with definite proof: did the request leave the client? Did the server receive it? Did it finish processing? Start where the evidence actually ends.', 30, 3),
  ('mission-be1-03-o2-c1', 'orientation', 'Statelessness is a hint about which side forgets by default.', 10, 1),
  ('mission-be1-03-o2-c1', 'solution', 'Client: renders, initiates, forgets by default. Server: stores durably, decides what''s authorized.', 20, 2),

  ('mission-be1-04-o1-c1', 'orientation', 'A few of these predate the modern web entirely.', 10, 1),
  ('mission-be1-04-o1-c1', 'concept', '80 and 443 are the same protocol family at two different trust levels; 22 belongs to a completely different kind of traffic.', 20, 2),
  ('mission-be1-04-o1-c1', 'solution', '80 -> HTTP, 443 -> HTTPS, 22 -> SSH, 5432 -> PostgreSQL, 3000 -> a typical local dev server (by convention, not a rule).', 30, 3),
  ('mission-be1-04-o2-c1', 'orientation', 'One of these three entries describes an address that can never belong to somebody else''s machine.', 10, 1),
  ('mission-be1-04-o2-c1', 'concept', 'localhost / 127.0.0.1 always resolves back to the machine you''re standing on, no matter which machine that is.', 20, 2),
  ('mission-be1-04-o2-c1', 'solution', 'ev3: ''works on my machine at localhost:3000'' isn''t evidence about the real server at all -- localhost always points home.', 30, 3),

  ('mission-be1-05-o1-c1', 'orientation', 'Caches exist specifically to avoid the expensive full chain -- they''re always checked first.', 10, 1),
  ('mission-be1-05-o1-c1', 'concept', 'Root servers don''t know domain answers, only who to ask next -- that''s a hint about where they sit in the order.', 20, 2),
  ('mission-be1-05-o1-c1', 'solution', 'Browser cache, then OS cache, then recursive resolver, then root, then TLD, then the authoritative server.', 30, 3),
  ('mission-be1-05-o2-c1', 'orientation', 'Two different users can legitimately get two different, both ''correct at some point,'' answers to the exact same query.', 10, 1),
  ('mission-be1-05-o2-c1', 'concept', 'A TTL is a promise about how long it''s fine to keep trusting an old answer -- not a guarantee anyone will ask again sooner than that.', 20, 2),
  ('mission-be1-05-o2-c1', 'solution', 'The record changed, but its old 24h TTL means resolvers that already cached the old IP won''t ask again until it expires -- that''s the inconsistency, not a broken record.', 30, 3),

  ('mission-be1-06-o1-c1', 'orientation', 'Nobody can acknowledge something that hasn''t been sent yet.', 10, 1),
  ('mission-be1-06-o1-c1', 'solution', 'SYN, then SYN-ACK, then ACK -- each side confirms the other before data flows.', 20, 2),
  ('mission-be1-06-o2-c1', 'orientation', 'One of these failures requires a reply. The other is defined by the total absence of one.', 10, 1),
  ('mission-be1-06-o2-c1', 'solution', 'A rejection needs someone home to say no. A timeout is what waiting for a reply that never comes looks like.', 20, 2),

  ('mission-be1-07-o1-c1', 'orientation', 'One of these is about secrecy, one is about identity, one is about tampering -- three genuinely different problems.', 10, 1),
  ('mission-be1-07-o1-c1', 'solution', 'g1 is confidentiality (encryption), g2 is authentication (the certificate chain), g3 is integrity (the connection''s built-in tamper detection).', 20, 2),
  ('mission-be1-07-o2-c1', 'orientation', 'Everything downstream of the root cause is a symptom. Look for the cause, not the symptoms.', 10, 1),
  ('mission-be1-07-o2-c1', 'solution', 'The URL itself is plain http:// -- there''s no TLS negotiated at all, which is why everything after it is readable in transit.', 20, 2),

  ('mission-be1-08-o1-c1', 'orientation', 'Headers describe the request. Exactly one line *is* the request.', 10, 1),
  ('mission-be1-08-o1-c1', 'concept', 'Method + path together answer ''do what, to what'' -- the whole action in five words or fewer.', 20, 2),
  ('mission-be1-08-o1-c1', 'solution', 'The request line: POST /dispatch/emergency HTTP/1.1 -- POST is the action, /dispatch/emergency is the resource.', 30, 3),

  ('mission-be1-09-o1-c1', 'orientation', 'The status line and the body are two independent sources of truth here -- and they disagree.', 10, 1),
  ('mission-be1-09-o1-c1', 'concept', 'An HTTP status code is a contract about the transport, not a guarantee the application logic succeeded -- a well-behaved server keeps those aligned, but nothing forces it to.', 20, 2),
  ('mission-be1-09-o1-c1', 'solution', 'The body''s own status field says "error" while the status line says 200 OK -- the response is internally contradictory.', 30, 3),

  ('mission-be1-10-o1-c1', 'orientation', 'One of these is the odd one out: it''s supposed to be safe to run a hundred times with no effect.', 10, 1),
  ('mission-be1-10-o1-c1', 'solution', 'GET -> retrieve, POST -> create, PUT -> replace entirely, PATCH -> partial update, DELETE -> remove.', 20, 2),
  ('mission-be1-10-o2-c1', 'orientation', '2xx means success, 4xx means the client did something the server won''t accept, 5xx means the server itself is the one that broke.', 10, 1),
  ('mission-be1-10-o2-c1', 'solution', '200 OK, 201 Created, 400 Bad request, 401 Unauthorized, 404 Not found, 500 Internal server error.', 20, 2),

  ('mission-be1-11-o1-c1', 'orientation', 'In JSON, a string and a boolean are two different types even when a human reads them as ''the same word.''', 10, 1),
  ('mission-be1-11-o1-c1', 'concept', '"true" (a non-empty string) is truthy in almost every language''s conditional check -- even when the value should have been false.', 20, 2),
  ('mission-be1-11-o1-c1', 'solution', '"dispatched": "true" serializes the boolean as a string. It should be "dispatched": true, unquoted, so a false case can actually serialize as false and evaluate falsy.', 30, 3),

  ('mission-be1-12-o1-c1', 'orientation', 'Start by checking whether the status line and the body actually agree here.', 10, 1),
  ('mission-be1-12-o1-c1', 'solution', 'Status 200 and a body whose own status field also says "ok" -- nothing contradicts, so it''s a genuine success.', 20, 2),
  ('mission-be1-12-o2-c1', 'orientation', 'You''ve seen this exact contradiction before, earlier this Act.', 10, 1),
  ('mission-be1-12-o2-c1', 'solution', 'The body says "error" while the status line says 200 -- trust the more specific, application-level source when they disagree.', 20, 2),
  ('mission-be1-12-o3-c1', 'orientation', 'A 5xx status code is already a complete statement on its own -- ask what an empty body would need to add to that.', 10, 1),
  ('mission-be1-12-o3-c1', 'solution', '503 already means the server failed to handle the request; there''s no missing information an empty body could contradict that with.', 20, 2),
  ('mission-be1-12-o4-c1', 'orientation', 'Look at what all three judgments had in common as a method, not as individual answers.', 15, 1),
  ('mission-be1-12-o4-c1', 'solution', 'The status line and the response body must always agree about success or failure -- a 2xx should never carry a body that says otherwise, and a failure should never be dressed as a 200.', 25, 2);
