-- world-13 ("Windows I: Windows of Opportunity") mission content, generated
-- from docs/12-world-story-bible.md. New host, a corporate workstation tied
-- to the same campaign as world-12's gateway -- suspicious logons, no
-- malware alert. Luna introduces Windows through operational response:
-- accounts, services, tasks, Event Viewer, registry and network state.
-- Mission 1 is cross-world-gated on world-12's boss mission.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-13a', 'world-13', 'windows-of-opportunity', '13A - Windows of Opportunity', 'A corporate workstation tied to the same campaign shows suspicious logons and no malware alert. Luna teaches Windows through operational response: who has access, what runs, and what the system already recorded about itself.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-13a-1', 'campaign-13a', 'foundations', 'Foundations', 'Accounts, services and scheduled tasks -- how a Windows endpoint describes its own configuration.', 1),
  ('operation-13a-2', 'campaign-13a', 'investigation', 'Investigation', 'Event Viewer, the registry and network state -- find the persistence mechanism and prove when it started.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-w13-01', 'world-13', 'campaign-13a', 'operation-13a-1', 'windows-of-opportunity', 'Windows of Opportunity', 'A corporate workstation tied to the same campaign shows suspicious logons -- and no malware alert at all. Luna takes point.', 'intro', ARRAY['ava', 'luna', 'byte'], '{"requiredMissionIds":["mission-w12-06"]}'::jsonb, null, '{"type":"none"}'::jsonb, '{"xp":60,"credits":10}'::jsonb, false, 1),
  ('mission-w13-02', 'world-13', 'campaign-13a', 'operation-13a-1', 'accounts-and-admins', 'Accounts and Admins', 'Every local account on this box claims to be routine. One has permissions it shouldn''t.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w13-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"win-user-group-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-w13-03', 'world-13', 'campaign-13a', 'operation-13a-1', 'the-service-nobody-registered', 'The Service Nobody Registered', 'A service is running under a name that almost matches a legitimate one -- and a scheduled task keeps bringing it back.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w13-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"win-services-tasks-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 3),
  ('mission-w13-04', 'world-13', 'campaign-13a', 'operation-13a-2', 'the-logon-nobody-remembers', 'The Logon Nobody Remembers', 'The event log remembers every logon, whether anyone was watching or not.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w13-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"win-event-viewer-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 4),
  ('mission-w13-05', 'world-13', 'campaign-13a', 'operation-13a-2', 'run-keys-and-open-ports', 'Run Keys and Open Ports', 'What starts automatically, and what''s talking outbound right now -- two different questions, two different places to look.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w13-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"win-registry-netstat-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 5),
  ('mission-w13-06', 'world-13', 'campaign-13a', 'operation-13a-2', 'the-scheduled-visitor', 'The Scheduled Visitor', 'Find the persistence mechanism that actually matters, and prove exactly when it first ran.', 'boss', ARRAY['luna', 'byte'], '{"requiredMissionIds":["mission-w13-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"scheduled-visitor-boss-sim"}'::jsonb, '{"xp":300,"credits":60,"badgeIds":["scheduled-visitor"],"skillXp":{"windows":50}}'::jsonb, true, 6);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-w13-01', 1, 'ava', 'Ava again -- Windows next, like I said. A corporate workstation tied to this same campaign lit up with suspicious logons a few minutes ago. No malware alert, nothing flagged automatically.'),
  ('mission-w13-01', 2, 'luna', 'I''m Luna. I handle Windows operations -- endpoints, identity, the audit trail a system leaves about itself. No malware alert doesn''t mean nothing happened. It means nothing matched a signature.'),
  ('mission-w13-01', 3, 'luna', 'A Windows machine describes itself constantly, if you know where to look: who has accounts, what runs automatically, what the event log recorded, what the registry remembers. We start there.'),
  ('mission-w13-01', 4, 'byte', 'I''ll stay on comms. Luna knows this terrain better than I do.'),
  ('mission-w13-02', 1, 'luna', 'Every account on this box claims to be routine. net user lists identity; net localgroup administrators lists who actually holds the keys. They should agree with each other.'),
  ('mission-w13-03', 1, 'luna', 'sc query shows what''s running. schtasks /query shows what''s scheduled to run. A name that almost matches svchost.exe is not the same as svchost.exe.'),
  ('mission-w13-04', 1, 'luna', 'The event log doesn''t forgive selective attention. Logon type tells you how someone got in -- console, network, or remote desktop -- and that matters as much as whether they got in at all.'),
  ('mission-w13-05', 1, 'luna', 'Two separate questions, two separate places: what does this account load automatically, in the registry -- and what is this machine talking to right now, on the wire.'),
  ('mission-w13-06', 1, 'luna', 'Everything you''ve found points to one task. Identify the actual persistence mechanism -- not just its symptoms -- and prove exactly when it first executed.'),
  ('mission-w13-06', 2, 'luna', 'Confirmed. The scheduled task recreates both the service and the registry entry every time the system starts. Removing only one of those was never going to work.'),
  ('mission-w13-06', 3, 'byte', 'Task Scheduler''s history puts its first real execution eleven days ago, 02:04 AM. And there''s something odd in the event message itself.'),
  ('mission-w13-06', 4, 'byte', 'It reads: "Do not trust the beacon." That''s not standard Windows log text. Someone wrote that on purpose.'),
  ('mission-w13-06', 5, 'luna', 'Planted, deliberately, inside a system log an analyst would only read closely if they already suspected something. That''s not attacker behavior. That reads like a warning.'),
  ('mission-w13-06', 6, 'luna', 'There''s something else. PowerShell command history on this box -- queries very similar to the ones we just ran -- timestamped before we ever touched this workstation.'),
  ('mission-w13-06', 7, 'byte', 'Someone else was already investigating. And they didn''t use CMD to do it.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-w13-01-o1', 'mission-w13-01', 1, 'Acknowledge the briefing', 'Confirm you''re ready to work the Windows domain.'),
  ('mission-w13-02-o1', 'mission-w13-02', 1, 'Find the unauthorized account', 'Identify the account holding privileges it has no documented reason to hold.'),
  ('mission-w13-03-o1', 'mission-w13-03', 1, 'Find the disguised service and task', 'Identify the service impersonating a legitimate process and the task keeping it alive.'),
  ('mission-w13-04-o1', 'mission-w13-04', 1, 'Find the real intrusion event', 'Identify the events that establish an actual remote, elevated logon.'),
  ('mission-w13-05-o1', 'mission-w13-05', 1, 'Tie persistence to live communication', 'Find the registry and network evidence that confirm this is both persistent and actively talking outbound.'),
  ('mission-w13-06-o1', 'mission-w13-06', 1, 'Identify the persistence mechanism', 'Find the artifact that, once removed, actually stops this from coming back.'),
  ('mission-w13-06-o2', 'mission-w13-06', 2, 'Prove the first execution', 'Find the timestamp that proves when this mechanism actually first ran.'),
  ('mission-w13-06-o3', 'mission-w13-06', 3, 'Close the investigation', 'State the persistence mechanism and the proven first-execution time.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-w13-01-o1-c1', 'mission-w13-01-o1', 1, 'story_dialogue', 'Confirm you''re ready to continue.', '{"lines":[{"characterId":"luna","text":"No signature match doesn''t mean no incident. Ready to see what this endpoint has to say for itself?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),

  ('mission-w13-02-o1-c1', 'mission-w13-02-o1', 1, 'investigation', 'Which findings identify the unauthorized account?', '{"evidence":[{"id":"u1","label":"net user output","detail":"Local accounts: Administrator (disabled), Guest (disabled), jsmith (standard user, last logon 2 days ago), svc_helpdesk (enabled, created 3 days ago, last logon today)"},{"id":"u2","label":"net localgroup administrators output","detail":"Administrators group members: Administrator, jsmith-adm (documented IT admin account), svc_helpdesk"},{"id":"u3","label":"IT asset inventory","detail":"svc_helpdesk does not appear as a documented service account anywhere in the inventory system"},{"id":"u4","label":"Password policy audit","detail":"svc_helpdesk has \"password never expires\" set, unlike every documented service account"}],"question":"Which findings identify the unauthorized account?"}'::jsonb, '{"requiredEvidenceIds":["u2","u3"]}'::jsonb),

  ('mission-w13-03-o1-c1', 'mission-w13-03-o1', 1, 'investigation', 'Which findings identify the disguised service?', '{"evidence":[{"id":"s1","label":"sc query output","detail":"Services running: WinDefend (normal), Spooler (normal), SysHelperSvc (running, binary path C:\\Windows\\Temp\\svchost32.exe)"},{"id":"s2","label":"Service binary path check","detail":"Legitimate svchost.exe only ever runs from C:\\Windows\\System32. This binary shares a similar name but runs from Temp."},{"id":"s3","label":"schtasks /query output","detail":"Scheduled task \"OneDriveSyncHelper\" runs powershell.exe with an encoded command every night at 2:14 AM."},{"id":"s4","label":"Digital signature check","detail":"Genuine svchost.exe is always signed by Microsoft. The Temp copy, svchost32.exe, is unsigned."}],"question":"Which findings identify the disguised service, not just a coincidence of naming?"}'::jsonb, '{"requiredEvidenceIds":["s2","s4"]}'::jsonb),
  ('mission-w13-03-o1-c2', 'mission-w13-03-o1', 2, 'multiple_choice', 'The scheduled task "OneDriveSyncHelper" runs powershell.exe with a base64-encoded command every night at 2:14 AM, but no OneDrive client is installed on this machine. What makes this task worth escalating?', '{"question":"The scheduled task \"OneDriveSyncHelper\" runs powershell.exe with a base64-encoded command every night at 2:14 AM, but no OneDrive client is installed on this machine. What makes this task worth escalating?","options":[{"id":"a","text":"Scheduled tasks running PowerShell are always malicious"},{"id":"b","text":"It''s named after a product it has no real connection to, runs an obfuscated command, and fires at an hour with no matching business process"},{"id":"c","text":"2:14 AM is outside business hours, and that alone is disqualifying"},{"id":"d","text":"Encoded PowerShell commands are a Microsoft-recommended practice for scheduled tasks"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-w13-04-o1-c1', 'mission-w13-04-o1', 1, 'investigation', 'Which events establish an actual remote, elevated logon?', '{"evidence":[{"id":"e1","label":"Event ID 4624 (successful logon)","detail":"Logon Type 10 (RemoteInteractive) for svc_helpdesk at 03:14 AM from external address 203.0.113.77"},{"id":"e2","label":"Event ID 4625 (failed logon)","detail":"Several failed attempts for jsmith, an ordinary lockout pattern resolved by a helpdesk ticket the same day"},{"id":"e3","label":"Event ID 4672 (special privileges assigned)","detail":"svc_helpdesk assigned elevated privileges on a logon session immediately following the 4624 event"},{"id":"e4","label":"Event ID 4688 (process creation)","detail":"Routine print spooler process launched under SYSTEM, entirely expected"}],"question":"Which events establish that an attacker actually logged on to this box remotely with elevated rights?"}'::jsonb, '{"requiredEvidenceIds":["e1","e3"]}'::jsonb),

  ('mission-w13-05-o1-c1', 'mission-w13-05-o1', 1, 'investigation', 'Which registry and network evidence tie the disguised binary to live outbound communication?', '{"evidence":[{"id":"r1","label":"HKLM\\...\\Run key","detail":"Entry \"WindowsSecurityHelper\" points to C:\\Windows\\Temp\\svchost32.exe"},{"id":"r2","label":"HKCU\\...\\Run key for jsmith","detail":"Only legitimate startup entries: OneDrive, a printer utility"},{"id":"r3","label":"netstat -ano output","detail":"The process ID behind svchost32.exe holds an established connection to 203.0.113.77:443"},{"id":"r4","label":"Windows Firewall outbound log","detail":"An unusually permissive outbound rule allows all traffic on that port range"}],"question":"Which findings tie the disguised binary to persistent startup and active outbound communication?"}'::jsonb, '{"requiredEvidenceIds":["r1","r3"]}'::jsonb),

  ('mission-w13-06-o1-c1', 'mission-w13-06-o1', 1, 'investigation', 'Which artifact, once removed, actually stops this from coming back?', '{"evidence":[{"id":"p1","label":"SysHelperSvc service","detail":"The visible service running the disguised binary -- reappears within minutes if deleted"},{"id":"p2","label":"HKLM Run key entry \"WindowsSecurityHelper\"","detail":"Also reappears if deleted, on the same interval"},{"id":"p3","label":"Scheduled task \"OneDriveSyncHelper\"","detail":"Runs at every system startup, before either the service or the Run key are checked"},{"id":"p4","label":"Task Scheduler action history for OneDriveSyncHelper","detail":"Shows the task''s own action step explicitly recreating both the service and the Run key entry each run"}],"question":"Which artifact, once removed, actually stops this from coming back -- not just the most visible symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["p3","p4"]}'::jsonb),
  ('mission-w13-06-o2-c1', 'mission-w13-06-o2', 1, 'investigation', 'Which timestamp actually proves when this persistence mechanism first executed?', '{"evidence":[{"id":"t1","label":"Task Scheduler Event ID 106 (task registered)","detail":"Timestamped 11 days ago, 02:03 AM -- proves when the task was installed, not when it first ran"},{"id":"t2","label":"Task Scheduler Event ID 200 (action started)","detail":"Logged 02:04:11, eleven days ago -- the earliest execution record for this task. Its free-text message field includes an unusual line: \"Do not trust the beacon.\""},{"id":"t3","label":"Event ID 4697 (service installed)","detail":"Timestamped 02:05, same day -- one minute after the task first ran, meaning this is a downstream effect, not the origin"},{"id":"t4","label":"SOC dashboard \"first seen\" alert","detail":"Flagged this host days after the fact, based only on recent noisy beacon traffic"}],"question":"Which timestamp actually proves when this persistence mechanism first executed?"}'::jsonb, '{"requiredEvidenceIds":["t2"]}'::jsonb),
  ('mission-w13-06-o3-c1', 'mission-w13-06-o3', 1, 'boss_encounter', 'State the actual persistence mechanism and the timestamp that proves when it first executed.', '{"stages":[{"objectiveRef":"mission-w13-06-o1","label":"The persistence mechanism"},{"objectiveRef":"mission-w13-06-o2","label":"The proven first-execution time"}],"task":"State the actual persistence mechanism and the timestamp that proves when it first executed."}'::jsonb, '{"requiredObjectiveIds":["mission-w13-06-o1","mission-w13-06-o2"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-w13-01-o1-c1', 'orientation', 'There''s nothing to solve here -- just confirm you''re ready to continue.', 0, 1),

  ('mission-w13-02-o1-c1', 'orientation', 'Three of these four accounts have a completely ordinary explanation.', 15, 1),
  ('mission-w13-02-o1-c1', 'concept', 'Compare group membership against what''s actually documented in inventory -- an account can be real and still not be supposed to be here.', 25, 2),
  ('mission-w13-02-o1-c1', 'tool_direction', 'Cross-reference the Administrators group membership against the IT asset inventory record.', 35, 3),
  ('mission-w13-02-o1-c1', 'solution', 'svc_helpdesk sits in the Administrators group (u2) with no matching entry in the documented service-account inventory (u3) -- that combination identifies it as unauthorized. jsmith-adm and Administrator are both documented; the password policy detail (u4) is supporting context, not the identifying evidence.', 45, 4),

  ('mission-w13-03-o1-c1', 'orientation', 'Two of these four services are completely ordinary -- Defender and the print spooler.', 15, 1),
  ('mission-w13-03-o1-c1', 'concept', 'A legitimate Windows binary lives in a specific, well-known path, and it''s digitally signed.', 25, 2),
  ('mission-w13-03-o1-c1', 'tool_direction', 'Compare SysHelperSvc''s binary path and signature status against genuine svchost.exe.', 35, 3),
  ('mission-w13-03-o1-c1', 'solution', 'svchost32.exe running from C:\Windows\Temp instead of System32 (s2), and unsigned where the real svchost.exe is always signed (s4), together identify it as disguised rather than legitimate.', 45, 4),
  ('mission-w13-03-o1-c2', 'orientation', 'None of these facts alone would be suspicious. Together, they tell a different story.', 10, 1),
  ('mission-w13-03-o1-c2', 'concept', 'A convincing disguise borrows a familiar name; a legitimate task doesn''t usually need to hide its command in an encoded blob.', 20, 2),
  ('mission-w13-03-o1-c2', 'solution', 'The combination -- a name it has no real tie to, an obfuscated payload, and no matching legitimate process running at that hour -- is what makes it worth escalating, not any single fact alone.', 30, 3),

  ('mission-w13-04-o1-c1', 'orientation', 'One of these four events is routine even though it involves a failed password.', 15, 1),
  ('mission-w13-04-o1-c1', 'concept', 'Logon type matters -- a remote interactive logon from outside the network is a very different event than a local one.', 25, 2),
  ('mission-w13-04-o1-c1', 'tool_direction', 'Check the logon type on the successful logon, and see what immediately follows it in the log.', 35, 3),
  ('mission-w13-04-o1-c1', 'solution', 'Event 4624 shows a Type 10 (RemoteInteractive) logon for svc_helpdesk from an external address (e1), immediately followed by a 4672 special-privileges assignment for that same session (e3) -- a remote attacker logging on with elevated rights. The failed logons (e2) and the routine spooler process (e4) are unrelated noise.', 45, 4),

  ('mission-w13-05-o1-c1', 'orientation', 'Two separate places, two separate questions -- what starts automatically, and what''s connected right now.', 15, 1),
  ('mission-w13-05-o1-c1', 'concept', 'A Run key entry pointing at the same disguised binary you already found isn''t a coincidence.', 25, 2),
  ('mission-w13-05-o1-c1', 'tool_direction', 'Match the process behind that Run key entry against netstat''s list of established connections.', 35, 3),
  ('mission-w13-05-o1-c1', 'solution', 'The HKLM Run key entry launching svchost32.exe (r1), and netstat showing that same process holding an established connection out to 203.0.113.77:443 (r3), together prove this is both persistent and actively communicating. jsmith''s Run key (r2) is clean, and the permissive firewall rule (r4) is a contributing weakness, not the direct tie.', 45, 4),

  ('mission-w13-06-o1-c1', 'orientation', 'Two of these four artifacts are symptoms that come back on their own if you only remove them.', 20, 1),
  ('mission-w13-06-o1-c1', 'concept', 'Ask which artifact, if deleted, doesn''t get recreated on the next system startup.', 30, 2),
  ('mission-w13-06-o1-c1', 'tool_direction', 'Check the scheduled task''s recorded action steps, not just its trigger.', 40, 3),
  ('mission-w13-06-o1-c1', 'near_solution', 'The task''s own history log shows it explicitly rewriting both the service and the registry entry every time it runs.', 50, 4),
  ('mission-w13-06-o1-c1', 'solution', 'The scheduled task "OneDriveSyncHelper" (p3, confirmed by its own action history in p4) is the actual persistence mechanism -- it recreates both the service and the Run key on every startup. Removing the service (p1) or the Run key (p2) alone would not have stopped this.', 65, 5),

  ('mission-w13-06-o2-c1', 'orientation', 'The task being registered and the task actually running for the first time are two different moments.', 20, 1),
  ('mission-w13-06-o2-c1', 'concept', 'A "first seen" from a monitoring dashboard only tells you when someone noticed -- not when it started.', 30, 2),
  ('mission-w13-06-o2-c1', 'tool_direction', 'Compare the task registration event against its first recorded action event, and read that event''s message field in full.', 40, 3),
  ('mission-w13-06-o2-c1', 'near_solution', 'The action-started event is one minute earlier than the service-creation event it triggered, and its message field contains something that isn''t standard Windows log text.', 50, 4),
  ('mission-w13-06-o2-c1', 'solution', 'Task Scheduler Event ID 200 (t2), logged 02:04:11 eleven days ago, is the earliest actual execution -- one minute before the service-creation event it caused (t3). Its message field also contains a deliberately planted line: "Do not trust the beacon." The registration event (t1) only proves when it was installed, and the SOC dashboard''s "first seen" (t4) reflects only when noise was noticed.', 65, 5),

  ('mission-w13-06-o3-c1', 'orientation', 'You''ve already found both pieces -- this is about stating them together, correctly.', 20, 1),
  ('mission-w13-06-o3-c1', 'concept', 'The report needs the mechanism that survives simple removal, and the timestamp that proves first execution, not just detection.', 30, 2),
  ('mission-w13-06-o3-c1', 'tool_direction', 'State the scheduled task by name, then the Task Scheduler action-start timestamp.', 40, 3),
  ('mission-w13-06-o3-c1', 'near_solution', 'OneDriveSyncHelper; first executed 02:04 AM, eleven days ago.', 50, 4),
  ('mission-w13-06-o3-c1', 'solution', 'The persistence mechanism is the scheduled task OneDriveSyncHelper, which recreates both the disguised service and its Run key entry on every startup. It first executed at 02:04:11, eleven days ago -- proven by Task Scheduler Event ID 200, not the later service-creation event or the SOC''s delayed detection.', 65, 5);
