-- AI/ML pathway ("Cipher Division") Act 25 -- "Transformer Architectures" content.
-- Arc V, Acts 24-27. 1 campaign, 2 operations, 12 missions (11 lessons + boss),
-- following the same campaigns -> operations -> missions -> dialogue ->
-- objectives -> challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-transformer-architectures row already exists.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-transformer-architectures', 'world-ai-transformer-architectures', 'transformer-architectures', '25A - Transformer Architectures', 'Match Cipher Division''s three real jobs -- classify what Echo says, generate a clear explanation of it, translate its garbled phrasing into something readable -- to the transformer architecture actually built for each, using causal versus bidirectional attention and training objectives as the deciding factors.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-transformer-architectures-1', 'campaign-ai-transformer-architectures', 'three-shapes', 'Three Shapes', 'Encoder-only, decoder-only and encoder-decoder transformers, and the causal versus bidirectional attention and training objectives that set them apart.', 1),
  ('operation-ai-transformer-architectures-2', 'campaign-ai-transformer-architectures', 'right-tool-right-job', 'Right Tool, Right Job', 'BERT, GPT and T5-style designs in practice, what scaling does and does not change, the tradeoffs each shape accepts, and choosing the right one for each of Cipher Division''s three jobs.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-transformer-architectures-01', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'encoder-only', 'Encoder-Only', 'Three real jobs, one transformer shape that fits none of them alone. Start with the shape built for understanding a sequence rather than writing a new one.', 'beginner', ARRAY['maya','elena','noah'], null, null, '{"type":"simulation","simulationId":"encoder-only-sim"}'::jsonb, '{"xp":460,"credits":115}'::jsonb, false, 1),
  ('mission-ai-transformer-architectures-02', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'decoder-only', 'Decoder-Only', 'Restrict what a token is allowed to see, and generation stops being a mystery -- it becomes the exact task the restriction was built for.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-transformer-architectures-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"decoder-only-sim"}'::jsonb, '{"xp":470,"credits":120}'::jsonb, false, 2),
  ('mission-ai-transformer-architectures-03', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'encoder-decoder', 'Encoder-Decoder', 'Translating Echo''s garbled phrasing is not pure understanding and not pure free generation. It needs both shapes, tied together.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-transformer-architectures-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"encoder-decoder-sim"}'::jsonb, '{"xp":470,"credits":120}'::jsonb, false, 3),
  ('mission-ai-transformer-architectures-04', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'causal-masking', 'Causal Masking', 'Decoder-only models do not just choose to ignore the future. Causal masking makes it structurally impossible for a token to see it.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-transformer-architectures-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"causal-masking-sim"}'::jsonb, '{"xp":480,"credits":120}'::jsonb, false, 4),
  ('mission-ai-transformer-architectures-05', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'bidirectional-attention', 'Bidirectional Attention', 'Drop the mask entirely and every position can see every other position at once -- the other half of the tradeoff causal masking makes.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-transformer-architectures-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"bidirectional-attention-sim"}'::jsonb, '{"xp":480,"credits":125}'::jsonb, false, 5),
  ('mission-ai-transformer-architectures-06', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-1', 'training-objectives', 'Training Objectives', 'Attention pattern decides what a model is allowed to look at. Training objective decides what it actually practices doing, and the two are matched on purpose.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-transformer-architectures-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"training-objectives-sim"}'::jsonb, '{"xp":490,"credits":125}'::jsonb, false, 6),
  ('mission-ai-transformer-architectures-07', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 'bert-concepts', 'BERT Concepts', 'Bidirectional attention plus masked language modeling has a name in practice: BERT, the reference design for understanding a sequence rather than writing one.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-transformer-architectures-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"bert-concepts-sim"}'::jsonb, '{"xp":490,"credits":125}'::jsonb, false, 7),
  ('mission-ai-transformer-architectures-08', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 'gpt-concepts', 'GPT Concepts', 'Causal masking plus next-token prediction has a name too: GPT, the reference design for generating one plausible word after another.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-transformer-architectures-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"gpt-concepts-sim"}'::jsonb, '{"xp":500,"credits":130}'::jsonb, false, 8),
  ('mission-ai-transformer-architectures-09', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 't5-concepts', 'T5 Concepts', 'T5 treats every task as text-to-text, and its encoder-decoder shape is exactly what turning garbled phrasing into something readable needs.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-transformer-architectures-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"t5-concepts-sim"}'::jsonb, '{"xp":500,"credits":130}'::jsonb, false, 9),
  ('mission-ai-transformer-architectures-10', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 'scaling-intuition', 'Scaling Intuition', 'Every one of these shapes uses the same attention block underneath. Scaling multiplies what it can hold, not which direction it is allowed to look.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-transformer-architectures-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"scaling-intuition-sim"}'::jsonb, '{"xp":510,"credits":130}'::jsonb, false, 10),
  ('mission-ai-transformer-architectures-11', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 'limitations', 'Limitations', 'Every shape buys something by giving something up. None of these three is simply the best one -- each is a tradeoff against a specific job.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-transformer-architectures-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"limitations-sim"}'::jsonb, '{"xp":510,"credits":135}'::jsonb, false, 11),
  ('mission-ai-transformer-architectures-12', 'world-ai-transformer-architectures', 'campaign-ai-transformer-architectures', 'operation-ai-transformer-architectures-2', 'choose-the-architecture', 'Choose the Architecture', 'Match all three jobs to their real architectures, with justification -- and confront a mismatch that has been sitting quietly in Cipher Division''s own tools all Arc.', 'boss', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-transformer-architectures-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"choose-the-architecture-boss-sim"}'::jsonb, '{"xp":1250,"credits":270,"badgeIds":["choose-the-architecture"],"skillXp":{"transformers":60,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-transformer-architectures-01', 1, 'maya', 'Cipher Division has three real jobs on the table -- classify what Echo says, generate a clear explanation of it, translate its garbled phrasing into something readable -- and one transformer shape does not fit all three.'),
  ('mission-ai-transformer-architectures-01', 2, 'elena', 'Every transformer we have built so far reuses the same attention block from last Act. What changes between them is how that block gets arranged, and which direction it is allowed to look. Three shapes: encoder-only, decoder-only, encoder-decoder.'),
  ('mission-ai-transformer-architectures-01', 3, 'noah', 'And in production those are not interchangeable. Pick the wrong shape for a job and you do not just lose a little accuracy -- you build a tool that was never suited to what it is doing, and it will quietly underperform for as long as nobody checks.'),
  ('mission-ai-transformer-architectures-01', 4, 'elena', 'Start with encoder-only. Every position attends to every other position, both directions, in one pass. Nothing hidden from anything. That makes it built for understanding a sequence, not writing a new one.'),

  ('mission-ai-transformer-architectures-02', 1, 'elena', 'Decoder-only flips it. Each token can only attend to itself and the tokens before it -- never what comes after. That restriction has a name: causal masking, and we will dig into it properly next mission.'),
  ('mission-ai-transformer-architectures-02', 2, 'elena', 'Restricting the view sounds like a limitation, but it is exactly what generation needs. To produce the next word, a model trained this way has only ever practiced predicting one word ahead from what came before -- which is the exact task "write a clear explanation" requires.'),

  ('mission-ai-transformer-architectures-03', 1, 'elena', 'Two of the three jobs are covered. The third -- translating Echo''s garbled phrasing into something readable -- is not quite classification and not quite free generation. It starts from one sequence and ends at a different one.'),
  ('mission-ai-transformer-architectures-03', 2, 'byte', 'That shape already exists. We used it two Acts back. An encoder reads the whole input bidirectionally, then a decoder generates the output causally, one token at a time, while also attending back to everything the encoder produced.'),
  ('mission-ai-transformer-architectures-03', 3, 'elena', 'Encoder-decoder. Understanding on one side, causal generation on the other, tied together by cross-attention. That is the shape for translation-style tasks -- and it is the third piece Cipher Division needs.'),

  ('mission-ai-transformer-architectures-04', 1, 'elena', 'Decoder-only models get their causal property from a very literal trick: causal masking. Before softmax, every attention score for a "future" position gets set to negative infinity, so it becomes zero after softmax. The token literally cannot see it.'),
  ('mission-ai-transformer-architectures-04', 2, 'elena', 'That is not a training-time convenience, it has to hold at inference too. Generation happens one token at a time, and each new token only ever exists after the ones before it -- so masking future positions is the only way training ever matches how the model actually gets used.'),

  ('mission-ai-transformer-architectures-05', 1, 'elena', 'Encoder-only models skip masking entirely. Every position sees every other position, both directions, in a single pass -- which is why it is called bidirectional attention.'),
  ('mission-ai-transformer-architectures-05', 2, 'elena', 'That access to the full sequence at once is exactly what understanding-style tasks want. To decide whether a sentence is a question or a status report, the clue can sit anywhere in it -- before or after the word that actually gives it away.'),

  ('mission-ai-transformer-architectures-06', 1, 'elena', 'Architecture decides what a model is allowed to look at. Training objective decides what it actually practices doing -- and the two are matched on purpose, not by accident.'),
  ('mission-ai-transformer-architectures-06', 2, 'noah', 'Decoder-only models train on next-token prediction: guess the next word, check it against the real one, adjust. That is also literally the inference task, which is why generation quality tracks training loss so cleanly.'),
  ('mission-ai-transformer-architectures-06', 3, 'elena', 'Encoder-only models cannot predict the next token; they can already see it. So BERT-style training hides some tokens and asks the model to fill them back in from context on both sides -- masked language modeling. Encoder-decoder models train on the sequence-to-sequence task itself: read one sequence with the encoder, generate a different one with the decoder, causally, one token at a time.'),

  ('mission-ai-transformer-architectures-07', 1, 'elena', 'BERT is the reference encoder-only design: bidirectional attention plus masked language modeling, trained to build a representation of a sequence, not to generate one.'),
  ('mission-ai-transformer-architectures-07', 2, 'elena', 'Because it never generates text token by token, BERT is not the tool for writing Echo''s explanation. It is the tool for deciding what kind of thing a piece of Echo''s output actually is -- classification, tagging, understanding tasks.'),

  ('mission-ai-transformer-architectures-08', 1, 'elena', 'GPT is the reference decoder-only design: causal masking plus next-token prediction, trained to keep generating one plausible next token after another.'),
  ('mission-ai-transformer-architectures-08', 2, 'byte', 'That is also, functionally, exactly what "explain this clearly" asks for. Generate a first word, then the next, each one conditioned on everything already written -- never on words that do not exist yet.'),
  ('mission-ai-transformer-architectures-08', 3, 'elena', 'GPT-style models are the right shape for the explanation job. Not because they understand Echo better than an encoder would, but because generation is a causal, one-direction-at-a-time process, and that is the only direction this architecture is built to move in.'),

  ('mission-ai-transformer-architectures-09', 1, 'elena', 'T5 is the reference encoder-decoder design, and its trick is treating every task as text-to-text: input text in, output text out, whether the job is translation, summarization, or something else entirely.'),
  ('mission-ai-transformer-architectures-09', 2, 'elena', 'For Echo''s garbled phrasing, that framing fits exactly. The encoder reads the garbled input bidirectionally and builds a full representation of it. The decoder then generates the readable version causally, attending back to that representation the entire time through cross-attention.'),

  ('mission-ai-transformer-architectures-10', 1, 'elena', 'All three shapes use the same attention block underneath. What changes as they scale is not the idea, it is how much of everything gets multiplied: more layers, wider representations, more attention heads, more parameters.'),
  ('mission-ai-transformer-architectures-10', 2, 'noah', 'And bigger is not automatically better for every job. A larger encoder-only model gets better at understanding, a larger decoder-only model gets better at generating fluent, coherent text over longer stretches -- but scaling does not change which direction a model is allowed to look. A bigger causal model is still causal.'),

  ('mission-ai-transformer-architectures-11', 1, 'elena', 'Every one of these shapes buys something by giving something up. Encoder-only cannot generate open-ended text at all -- there is no causal path to walk token by token. Decoder-only cannot look ahead, so a clue that only makes sense once you have read the ending stays invisible to it while it is still deciding earlier words.'),
  ('mission-ai-transformer-architectures-11', 2, 'noah', 'Encoder-decoder is the most flexible on paper, but that flexibility costs twice the components to train and serve -- an encoder and a decoder, both needing to be right, plus the cross-attention connecting them. Nothing here is a free upgrade. Every choice is a tradeoff against a specific job.'),

  ('mission-ai-transformer-architectures-12', 1, 'maya', 'Three jobs, three architectures, matched with real justification -- not guesswork. Then Noah found something in the record I want your eyes on before we close this Act.'),
  ('mission-ai-transformer-architectures-12', 2, 'elena', 'Classify, generate, translate. Encoder-only, decoder-only, encoder-decoder. Justify each pairing by attention pattern and training objective, not just by the name you remember.'),
  ('mission-ai-transformer-architectures-12', 3, 'noah', 'While that was happening I went back through every tool this Arc built, looking for exactly this kind of mismatch. Found one.'),
  ('mission-ai-transformer-architectures-12', 4, 'noah', 'The sequence-classification tool from Act 21. Its job was deciding what kind of message something is -- report, question, unclear. That decision benefits from context on both sides of every word. It was built on a unidirectional, causal-style sequence model that only ever looked backward.'),
  ('mission-ai-transformer-architectures-12', 5, 'elena', 'Matched correctly, each job gets the architecture actually built for it -- and the mismatch nobody caught earlier explains why one of Cipher Division''s own tools has been quietly underperforming all Arc.'),
  ('mission-ai-transformer-architectures-12', 6, 'maya', 'Not a new mystery about Echo. A real engineering mistake, sitting in a tool we already trusted, explained by exactly the concept this Act taught.'),
  ('mission-ai-transformer-architectures-12', 7, 'maya', 'Now that the right shape exists for every job, the next question is what happens when one of these gets scaled all the way up -- what that buys, and what it costs.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-transformer-architectures-01-o1', 'mission-ai-transformer-architectures-01', 1, 'Define encoder-only attention', 'State what an encoder-only transformer lets each token attend to.'),
  ('mission-ai-transformer-architectures-01-o2', 'mission-ai-transformer-architectures-01', 2, 'Match the job to encoder-only', 'Identify which of Cipher Division''s three jobs actually fits an encoder-only architecture.'),

  ('mission-ai-transformer-architectures-02-o1', 'mission-ai-transformer-architectures-02', 1, 'Define decoder-only attention', 'State what a decoder-only transformer lets a given token attend to.'),
  ('mission-ai-transformer-architectures-02-o2', 'mission-ai-transformer-architectures-02', 2, 'Match the job to decoder-only', 'Identify which of Cipher Division''s three jobs actually fits a decoder-only architecture.'),

  ('mission-ai-transformer-architectures-03-o1', 'mission-ai-transformer-architectures-03', 1, 'Describe the two-stage shape', 'State what an encoder-decoder transformer combines.'),
  ('mission-ai-transformer-architectures-03-o2', 'mission-ai-transformer-architectures-03', 2, 'Match all three jobs at once', 'Pair each of Cipher Division''s three jobs with its correct architecture family.'),

  ('mission-ai-transformer-architectures-04-o1', 'mission-ai-transformer-architectures-04', 1, 'Define causal masking', 'State what causal masking enforces during attention.'),
  ('mission-ai-transformer-architectures-04-o2', 'mission-ai-transformer-architectures-04', 2, 'Trace the masking steps', 'Order the steps causal masking adds to a standard attention computation.'),

  ('mission-ai-transformer-architectures-05-o1', 'mission-ai-transformer-architectures-05', 1, 'Define bidirectional attention', 'State what bidirectional attention lets each token see.'),
  ('mission-ai-transformer-architectures-05-o2', 'mission-ai-transformer-architectures-05', 2, 'Explain why it fits understanding tasks', 'Find the evidence explaining why bidirectional attention supports connecting a clue anywhere in a sequence in a single pass.'),

  ('mission-ai-transformer-architectures-06-o1', 'mission-ai-transformer-architectures-06', 1, 'Match objective to architecture', 'Pair each architecture family with the training objective it actually uses.'),
  ('mission-ai-transformer-architectures-06-o2', 'mission-ai-transformer-architectures-06', 2, 'Explain the constraint', 'State why an encoder-only model cannot simply be trained with next-token prediction.'),

  ('mission-ai-transformer-architectures-07-o1', 'mission-ai-transformer-architectures-07', 1, 'Define BERT''s use case', 'Identify the kind of task BERT-style models are the standard choice for.'),
  ('mission-ai-transformer-architectures-07-o2', 'mission-ai-transformer-architectures-07', 2, 'Justify the fit for classification', 'Find the evidence explaining why bidirectional attention suits tagging a message''s category.'),

  ('mission-ai-transformer-architectures-08-o1', 'mission-ai-transformer-architectures-08', 1, 'Define GPT''s training objective', 'Identify what GPT-style decoder-only models are trained on.'),
  ('mission-ai-transformer-architectures-08-o2', 'mission-ai-transformer-architectures-08', 2, 'Justify the fit for explanation', 'State why a GPT-style model, not a BERT-style model, fits generating a clear explanation.'),

  ('mission-ai-transformer-architectures-09-o1', 'mission-ai-transformer-architectures-09', 1, 'Define T5''s framing', 'Identify T5''s core text-to-text idea.'),
  ('mission-ai-transformer-architectures-09-o2', 'mission-ai-transformer-architectures-09', 2, 'Explain cross-attention''s role', 'State what cross-attention lets an encoder-decoder''s decoder do.'),

  ('mission-ai-transformer-architectures-10-o1', 'mission-ai-transformer-architectures-10', 1, 'Separate scale from shape', 'Identify what scaling a transformer changes, and what it does not.'),
  ('mission-ai-transformer-architectures-10-o2', 'mission-ai-transformer-architectures-10', 2, 'Judge a scaling proposal', 'Find the evidence that should change a plan to fix a classification problem by scaling up a decoder-only model.'),

  ('mission-ai-transformer-architectures-11-o1', 'mission-ai-transformer-architectures-11', 1, 'Match limitation to architecture', 'Pair each architecture family with its core limitation.'),
  ('mission-ai-transformer-architectures-11-o2', 'mission-ai-transformer-architectures-11', 2, 'State the general principle', 'Choose the correct principle for picking an architecture for a new job.'),

  ('mission-ai-transformer-architectures-12-o1', 'mission-ai-transformer-architectures-12', 1, 'Match Jobs to Architectures', 'Pair each of Cipher Division''s three jobs with the architecture actually built for it.'),
  ('mission-ai-transformer-architectures-12-o2', 'mission-ai-transformer-architectures-12', 2, 'Diagnose the Earlier Mismatch', 'Find the evidence proving the Act 21 sequence-classification tool used the wrong architecture shape for its job.'),
  ('mission-ai-transformer-architectures-12-o3', 'mission-ai-transformer-architectures-12', 3, 'Confirm the Fix', 'State what rebuilding that tool with the right attention pattern would actually fix.'),
  ('mission-ai-transformer-architectures-12-o4', 'mission-ai-transformer-architectures-12', 4, 'Choose the Architecture', 'Bring the three judgments together into Cipher Division''s final architecture decision.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-transformer-architectures-01-o1-c1', 'mission-ai-transformer-architectures-01-o1', 1, 'multiple_choice', 'In an encoder-only transformer, what can each token''s attention look at?', '{"question":"In an encoder-only transformer, what can each token''s attention look at?","options":[{"id":"a","text":"Only the tokens before it"},{"id":"b","text":"Only the tokens after it"},{"id":"c","text":"Every token in the input, both before and after"},{"id":"d","text":"Nothing -- encoder-only models have no attention"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-ai-transformer-architectures-01-o2-c1', 'mission-ai-transformer-architectures-01-o2', 1, 'multiple_choice', 'Which of Cipher Division''s three jobs is the natural fit for an encoder-only architecture?', '{"question":"Which of Cipher Division''s three jobs is the natural fit for an encoder-only architecture?","options":[{"id":"a","text":"Generate a clear explanation of Echo''s message"},{"id":"b","text":"Classify what Echo says"},{"id":"c","text":"Translate its garbled phrasing into something readable"},{"id":"d","text":"None -- encoder-only cannot be used for any of them"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-transformer-architectures-02-o1-c1', 'mission-ai-transformer-architectures-02-o1', 1, 'multiple_choice', 'In a decoder-only transformer, what can a given token attend to?', '{"question":"In a decoder-only transformer, what can a given token attend to?","options":[{"id":"a","text":"Itself and every token before it, never anything after"},{"id":"b","text":"The entire sequence in both directions"},{"id":"c","text":"Nothing but itself"},{"id":"d","text":"Only the very first token in the sequence"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-transformer-architectures-02-o2-c1', 'mission-ai-transformer-architectures-02-o2', 1, 'multiple_choice', 'Which Cipher Division job is decoder-only architecture actually built for?', '{"question":"Which Cipher Division job is decoder-only architecture actually built for?","options":[{"id":"a","text":"Classify what Echo says"},{"id":"b","text":"Generate a clear explanation of it"},{"id":"c","text":"Translate its garbled phrasing into something readable"},{"id":"d","text":"None of the three"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-transformer-architectures-03-o1-c1', 'mission-ai-transformer-architectures-03-o1', 1, 'multiple_choice', 'What does an encoder-decoder transformer combine?', '{"question":"What does an encoder-decoder transformer combine?","options":[{"id":"a","text":"Two decoders stacked on top of each other"},{"id":"b","text":"A bidirectional encoder reading the full input, and a causal decoder generating output while attending back to the encoder''s representations"},{"id":"c","text":"An encoder with no attention mechanism at all"},{"id":"d","text":"Two independent models that never share information"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-03-o2-c1', 'mission-ai-transformer-architectures-03-o2', 1, 'drag_and_drop', 'Match each of Cipher Division''s three jobs to the architecture family that fits it.', '{"items":[{"id":"job-classify","text":"Classify what Echo says"},{"id":"job-generate","text":"Generate a clear explanation of it"},{"id":"job-translate","text":"Translate its garbled phrasing into something readable"}],"targets":[{"id":"encoder-only","label":"Encoder-only"},{"id":"decoder-only","label":"Decoder-only"},{"id":"encoder-decoder","label":"Encoder-decoder"}]}'::jsonb, '{"correctMapping":{"job-classify":"encoder-only","job-generate":"decoder-only","job-translate":"encoder-decoder"}}'::jsonb),

  ('mission-ai-transformer-architectures-04-o1-c1', 'mission-ai-transformer-architectures-04-o1', 1, 'multiple_choice', 'What does causal masking enforce in a decoder-only transformer?', '{"question":"What does causal masking enforce in a decoder-only transformer?","options":[{"id":"a","text":"Every token attends equally to all tokens in the sequence"},{"id":"b","text":"A token can attend to itself and earlier tokens only, never later ones"},{"id":"c","text":"Tokens attend only to the very last token"},{"id":"d","text":"Attention is removed from the model entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-04-o2-c1', 'mission-ai-transformer-architectures-04-o2', 1, 'interactive_diagram', 'Order the steps causal masking adds to a standard attention computation.', '{"diagramId":"causal-masking-steps","hotspots":[{"id":"scores","label":"Compute raw attention scores for every position pair","explanation":"Before any masking, the model computes how much every position would attend to every other position."},{"id":"mask","label":"Set the score to negative infinity for any position that comes after the query","explanation":"This is the actual masking step -- future positions get a score that cannot survive softmax."},{"id":"softmax","label":"Apply softmax, turning masked scores into zero probability","explanation":"Negative infinity scores become exactly zero weight once softmax normalizes the row."},{"id":"weighted-sum","label":"Take the weighted sum of values using only the surviving, unmasked positions","explanation":"The token''s new representation is built only from itself and whatever came before it."}],"task":"Order the steps causal masking adds to standard attention, from first to last."}'::jsonb, '{"correctOrderIds":["scores","mask","softmax","weighted-sum"]}'::jsonb),

  ('mission-ai-transformer-architectures-05-o1-c1', 'mission-ai-transformer-architectures-05-o1', 1, 'multiple_choice', 'Bidirectional attention means a token''s representation is built from...', '{"question":"Bidirectional attention means a token''s representation is built from...","options":[{"id":"a","text":"Only the tokens before it"},{"id":"b","text":"Only itself"},{"id":"c","text":"Every other token in the sequence, both before and after"},{"id":"d","text":"Only the first token in the sequence"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-ai-transformer-architectures-05-o2-c1', 'mission-ai-transformer-architectures-05-o2', 1, 'investigation', 'Classifying whether a message is a question needs connecting a clue at the start of the sentence with the punctuation at the end, in a single pass. Which evidence explains why bidirectional attention supports that?', '{"evidence":[{"id":"e1","label":"Bidirectional attention","detail":"Every position can attend to every other position, before and after, within the same layer"},{"id":"e2","label":"Causal attention","detail":"A given position can only attend to itself and earlier positions; the first word can never attend forward to the ending punctuation"},{"id":"e3","label":"Positional encoding","detail":"Adds information about token order, independent of which directions attention is allowed to look"}],"question":"Which evidence explains why bidirectional attention supports connecting a clue at the start of a sentence with information at its end, in a single pass?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-transformer-architectures-06-o1-c1', 'mission-ai-transformer-architectures-06-o1', 1, 'drag_and_drop', 'Match each architecture family to the training objective it actually uses.', '{"items":[{"id":"obj-next-token","text":"Next-token prediction: guess the next word from everything before it"},{"id":"obj-mlm","text":"Masked language modeling: hide some tokens, predict them from context on both sides"},{"id":"obj-seq2seq","text":"Sequence-to-sequence generation: encode one sequence, causally generate a different one"}],"targets":[{"id":"decoder-only","label":"Decoder-only"},{"id":"encoder-only","label":"Encoder-only"},{"id":"encoder-decoder","label":"Encoder-decoder"}]}'::jsonb, '{"correctMapping":{"obj-next-token":"decoder-only","obj-mlm":"encoder-only","obj-seq2seq":"encoder-decoder"}}'::jsonb),
  ('mission-ai-transformer-architectures-06-o2-c1', 'mission-ai-transformer-architectures-06-o2', 1, 'multiple_choice', 'Why can an encoder-only model not simply be trained with next-token prediction?', '{"question":"Why can an encoder-only model not simply be trained with next-token prediction?","options":[{"id":"a","text":"It could, there is no real obstacle"},{"id":"b","text":"Its bidirectional attention already lets every position see the future tokens it would be asked to predict, making the task trivial and uninformative"},{"id":"c","text":"Next-token prediction only works on images"},{"id":"d","text":"Encoder-only models have no training objective at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-transformer-architectures-07-o1-c1', 'mission-ai-transformer-architectures-07-o1', 1, 'multiple_choice', 'BERT-style models are the standard choice for which kind of task?', '{"question":"BERT-style models are the standard choice for which kind of task?","options":[{"id":"a","text":"Open-ended text generation"},{"id":"b","text":"Understanding and classification tasks, like labeling or categorizing existing text"},{"id":"c","text":"Translating one language into another"},{"id":"d","text":"Predicting stock prices"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-07-o2-c1', 'mission-ai-transformer-architectures-07-o2', 1, 'investigation', 'Cipher Division wants to tag each of Echo''s logged messages as report, question, or unclear. Which property of BERT-style models makes them well suited to this?', '{"evidence":[{"id":"e1","label":"Bidirectional attention","detail":"Sees the whole message at once when deciding the label"},{"id":"e2","label":"Causal masking","detail":"Restricts a token to earlier context only -- not present in BERT-style models"},{"id":"e3","label":"Cross-attention to a decoder","detail":"Belongs to encoder-decoder models, not encoder-only ones"}],"question":"Which property of BERT-style models makes them well suited to tagging a full message''s category?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-transformer-architectures-08-o1-c1', 'mission-ai-transformer-architectures-08-o1', 1, 'multiple_choice', 'GPT-style decoder-only models are trained on...', '{"question":"GPT-style decoder-only models are trained on...","options":[{"id":"a","text":"Masked language modeling"},{"id":"b","text":"Next-token prediction, generating text one token at a time"},{"id":"c","text":"Sequence-to-sequence translation only"},{"id":"d","text":"Image classification"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-08-o2-c1', 'mission-ai-transformer-architectures-08-o2', 1, 'multiple_choice', 'Why is a GPT-style model, not a BERT-style model, the right fit for generating a clear explanation of Echo''s message?', '{"question":"Why is a GPT-style model, not a BERT-style model, the right fit for generating a clear explanation?","options":[{"id":"a","text":"BERT-style models cannot process text at all"},{"id":"b","text":"Generation is an inherently causal, one-token-at-a-time process, which matches decoder-only attention and training, not bidirectional understanding"},{"id":"c","text":"GPT-style models are simply newer"},{"id":"d","text":"There is no real difference -- either would work identically"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-transformer-architectures-09-o1-c1', 'mission-ai-transformer-architectures-09-o1', 1, 'multiple_choice', 'T5''s core idea is to treat every task as...', '{"question":"T5''s core idea is to treat every task as...","options":[{"id":"a","text":"Pure classification"},{"id":"b","text":"A text-to-text problem: some input text in, some output text out"},{"id":"c","text":"Image generation"},{"id":"d","text":"A fixed lookup table"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-09-o2-c1', 'mission-ai-transformer-architectures-09-o2', 1, 'multiple_choice', 'In an encoder-decoder model like T5, what does cross-attention let the decoder do?', '{"question":"In an encoder-decoder model like T5, what does cross-attention let the decoder do?","options":[{"id":"a","text":"Attend to future tokens it has not generated yet"},{"id":"b","text":"Attend back to the encoder''s representation of the full input while generating output causally"},{"id":"c","text":"Skip the encoder entirely"},{"id":"d","text":"Replace causal masking with bidirectional masking"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-transformer-architectures-10-o1-c1', 'mission-ai-transformer-architectures-10-o1', 1, 'multiple_choice', 'Scaling a transformer up (more layers, more parameters, more heads) changes...', '{"question":"Scaling a transformer up (more layers, more parameters, more heads) changes...","options":[{"id":"a","text":"Which direction attention is allowed to look, converting causal to bidirectional"},{"id":"b","text":"The capacity and quality of what the model can represent or generate, not its fundamental attention pattern"},{"id":"c","text":"Nothing meaningful"},{"id":"d","text":"Only the training objective"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-10-o2-c1', 'mission-ai-transformer-architectures-10-o2', 1, 'investigation', 'Cipher Division is deciding whether to simply scale up its existing decoder-only summarizer to fix a classification accuracy problem. Which evidence should change that plan?', '{"evidence":[{"id":"e1","label":"Architecture note","detail":"The summarizer is decoder-only with causal attention; classification needs a decision informed by the whole sequence at once, which causal attention cannot provide"},{"id":"e2","label":"Compute budget","detail":"More GPU hours are available this quarter than last quarter"},{"id":"e3","label":"Latency log","detail":"The summarizer''s average response time is under 400 milliseconds"}],"question":"Which evidence should change the plan to fix a classification problem by scaling up a decoder-only model?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-transformer-architectures-11-o1-c1', 'mission-ai-transformer-architectures-11-o1', 1, 'drag_and_drop', 'Match each architecture family to its core limitation.', '{"items":[{"id":"lim-encoder","text":"Cannot generate open-ended text token by token -- there is no causal path to walk"},{"id":"lim-decoder","text":"Cannot use later context when deciding earlier tokens"},{"id":"lim-encdec","text":"Needs twice the components -- an encoder and a decoder -- to train and serve"}],"targets":[{"id":"encoder-only","label":"Encoder-only"},{"id":"decoder-only","label":"Decoder-only"},{"id":"encoder-decoder","label":"Encoder-decoder"}]}'::jsonb, '{"correctMapping":{"lim-encoder":"encoder-only","lim-decoder":"decoder-only","lim-encdec":"encoder-decoder"}}'::jsonb),
  ('mission-ai-transformer-architectures-11-o2-c1', 'mission-ai-transformer-architectures-11-o2', 1, 'multiple_choice', 'Given these tradeoffs, how should Cipher Division choose an architecture for a new job?', '{"question":"Given these tradeoffs, how should Cipher Division choose an architecture for a new job?","options":[{"id":"a","text":"Always pick the largest model available"},{"id":"b","text":"Always default to encoder-decoder since it is the most flexible"},{"id":"c","text":"Match the architecture''s attention pattern and training objective to what the job actually needs"},{"id":"d","text":"Architecture choice does not matter once a model is large enough"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),

  ('mission-ai-transformer-architectures-12-o1-c1', 'mission-ai-transformer-architectures-12-o1', 1, 'drag_and_drop', 'Pair each of Cipher Division''s three jobs with the architecture actually built for it.', '{"items":[{"id":"job-classify","text":"Classify what Echo says"},{"id":"job-generate","text":"Generate a clear explanation of it"},{"id":"job-translate","text":"Translate its garbled phrasing into something readable"}],"targets":[{"id":"encoder-only","label":"Encoder-only (bidirectional attention, masked language modeling)"},{"id":"decoder-only","label":"Decoder-only (causal masking, next-token prediction)"},{"id":"encoder-decoder","label":"Encoder-decoder (bidirectional encoder, causal decoder, cross-attention)"}]}'::jsonb, '{"correctMapping":{"job-classify":"encoder-only","job-generate":"decoder-only","job-translate":"encoder-decoder"}}'::jsonb),
  ('mission-ai-transformer-architectures-12-o2-c1', 'mission-ai-transformer-architectures-12-o2', 1, 'investigation', 'Noah pulled records on the Act 21 sequence-classification tool. Which evidence points to an architecture mismatch, not a data or training problem?', '{"evidence":[{"id":"e1","label":"Architecture note (Act 21 tool)","detail":"Built on a unidirectional, causal-style sequence model -- each position could only use context that came before it"},{"id":"e2","label":"Task definition","detail":"The tool''s job was classifying a full message as report, question, or unclear -- a decision that benefits from context on both sides of a word, not just what precedes it"},{"id":"e3","label":"Training log","detail":"The tool was trained for a standard number of epochs on a clean, correctly labeled dataset"},{"id":"e4","label":"Deployment note","detail":"The tool has run in production without a single code change since Act 21"}],"question":"Which evidence points to an architecture mismatch, not a data or training problem, behind the tool''s underperformance?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-transformer-architectures-12-o3-c1', 'mission-ai-transformer-architectures-12-o3', 1, 'multiple_choice', 'If the Act 21 sequence-classification tool were rebuilt with bidirectional attention instead, what would that most directly fix?', '{"question":"If the Act 21 sequence-classification tool were rebuilt with bidirectional attention instead, what would that most directly fix?","options":[{"id":"a","text":"It would make the tool generate text instead of classifying it"},{"id":"b","text":"It would let the tool weigh context from both sides of each word when deciding a message''s category, instead of only what came before"},{"id":"c","text":"It would remove the need for training data entirely"},{"id":"d","text":"It would automatically convert the tool into an encoder-decoder model"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-transformer-architectures-12-o4-c1', 'mission-ai-transformer-architectures-12-o4', 1, 'boss_encounter', 'Bring the three judgments together into Cipher Division''s final architecture decision.', '{"stages":[{"objectiveRef":"mission-ai-transformer-architectures-12-o1","label":"Match Jobs to Architectures"},{"objectiveRef":"mission-ai-transformer-architectures-12-o2","label":"Diagnose the Earlier Mismatch"},{"objectiveRef":"mission-ai-transformer-architectures-12-o3","label":"Confirm the Fix"}],"task":"State Cipher Division''s final architecture decision: which shape for each job, and what the Act 21 tool''s mismatch actually revealed about matching attention pattern to task."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-transformer-architectures-12-o1","mission-ai-transformer-architectures-12-o2","mission-ai-transformer-architectures-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-transformer-architectures-01-o1-c1', 'orientation', 'Encoder-only models do not mask anything. Ask what "no restriction" would mean for a token''s view of the sequence.', 10, 1),
  ('mission-ai-transformer-architectures-01-o1-c1', 'solution', 'Every token attends to every other token, both before and after, in the same pass -- that is the defining property of encoder-only attention.', 20, 2),
  ('mission-ai-transformer-architectures-01-o2-c1', 'orientation', 'Encoder-only models build a representation of a sequence. They do not generate new sequences token by token.', 10, 1),
  ('mission-ai-transformer-architectures-01-o2-c1', 'solution', 'Classifying what Echo says is a decision about an existing sequence, not the production of a new one -- exactly what encoder-only models are built for.', 20, 2),

  ('mission-ai-transformer-architectures-02-o1-c1', 'orientation', 'Decoder-only is the mirror image of encoder-only: something gets hidden from each token.', 10, 1),
  ('mission-ai-transformer-architectures-02-o1-c1', 'solution', 'A token can attend to itself and everything before it, but never to anything that comes after -- that restriction is causal masking.', 20, 2),
  ('mission-ai-transformer-architectures-02-o2-c1', 'orientation', 'Ask which job actually produces new text, one word after another.', 10, 1),
  ('mission-ai-transformer-architectures-02-o2-c1', 'solution', 'Generating a clear explanation means producing new text one token at a time, which is exactly the causal, one-direction task decoder-only models train for.', 20, 2),

  ('mission-ai-transformer-architectures-03-o1-c1', 'orientation', 'Think of it as encoder-only and decoder-only, connected together rather than replacing each other.', 10, 1),
  ('mission-ai-transformer-architectures-03-o1-c1', 'solution', 'A bidirectional encoder reads the whole input, and a causal decoder generates the output while attending back to the encoder''s representation -- that link is cross-attention.', 20, 2),
  ('mission-ai-transformer-architectures-03-o2-c1', 'orientation', 'Match each job to the shape you just learned it needs: understanding, generating, or both in sequence.', 10, 1),
  ('mission-ai-transformer-architectures-03-o2-c1', 'concept', 'Translation-style tasks start from one sequence and produce a different one -- that is neither pure classification nor free generation.', 20, 2),
  ('mission-ai-transformer-architectures-03-o2-c1', 'solution', 'Classify -> encoder-only. Generate an explanation -> decoder-only. Translate garbled phrasing -> encoder-decoder.', 30, 3),

  ('mission-ai-transformer-architectures-04-o1-c1', 'orientation', 'The word "causal" is the clue -- causes come before effects, never after.', 10, 1),
  ('mission-ai-transformer-architectures-04-o1-c1', 'solution', 'Causal masking enforces that a token can only attend to itself and earlier tokens, never anything that comes later in the sequence.', 20, 2),
  ('mission-ai-transformer-architectures-04-o2-c1', 'orientation', 'Nothing can be masked until raw scores exist, and nothing can be summed until masking and softmax have both happened.', 10, 1),
  ('mission-ai-transformer-architectures-04-o2-c1', 'concept', 'Softmax is what actually turns a negative-infinity score into a true zero weight -- masking alone just sets the score.', 20, 2),
  ('mission-ai-transformer-architectures-04-o2-c1', 'solution', 'Compute raw scores, mask future positions with negative infinity, apply softmax, then take the weighted sum over the surviving positions.', 30, 3),

  ('mission-ai-transformer-architectures-05-o1-c1', 'orientation', 'Bidirectional is the opposite of causal -- nothing is hidden from any token.', 10, 1),
  ('mission-ai-transformer-architectures-05-o1-c1', 'solution', 'Every other token in the sequence, both before and after, contributes to a token''s representation under bidirectional attention.', 20, 2),
  ('mission-ai-transformer-architectures-05-o2-c1', 'orientation', 'Ask which attention pattern would let the very first word directly see the punctuation at the end of the sentence.', 10, 1),
  ('mission-ai-transformer-architectures-05-o2-c1', 'solution', 'e1: bidirectional attention lets every position attend to every other position, before and after, in the same layer -- exactly what connecting a start-of-sentence clue to an end-of-sentence signal requires in one pass.', 20, 2),

  ('mission-ai-transformer-architectures-06-o1-c1', 'orientation', 'Ask which objective is literally impossible for a model that can already see the answer.', 10, 1),
  ('mission-ai-transformer-architectures-06-o1-c1', 'concept', 'A bidirectional model that could see the next token would have nothing to predict -- so its objective has to hide information instead.', 20, 2),
  ('mission-ai-transformer-architectures-06-o1-c1', 'solution', 'Decoder-only -> next-token prediction. Encoder-only -> masked language modeling. Encoder-decoder -> sequence-to-sequence generation.', 30, 3),
  ('mission-ai-transformer-architectures-06-o2-c1', 'orientation', 'Think about what an encoder-only model''s attention pattern already reveals to it, before training even starts.', 10, 1),
  ('mission-ai-transformer-architectures-06-o2-c1', 'solution', 'Because bidirectional attention already exposes future tokens, predicting the next one would be trivial -- the model would just be copying an answer it can already see.', 20, 2),

  ('mission-ai-transformer-architectures-07-o1-c1', 'orientation', 'BERT never generates new text. Ask what kind of task does not require generation.', 10, 1),
  ('mission-ai-transformer-architectures-07-o1-c1', 'solution', 'Understanding and classification tasks -- labeling or categorizing text that already exists -- are what BERT-style models are built for.', 20, 2),
  ('mission-ai-transformer-architectures-07-o2-c1', 'orientation', 'Tagging a whole message needs the model to weigh the message as a whole, not just what came before any one word.', 10, 1),
  ('mission-ai-transformer-architectures-07-o2-c1', 'solution', 'e1: bidirectional attention lets the model see the whole message at once when deciding its label.', 20, 2),

  ('mission-ai-transformer-architectures-08-o1-c1', 'orientation', 'GPT''s attention pattern is causal. Ask which objective naturally matches only ever seeing what came before.', 10, 1),
  ('mission-ai-transformer-architectures-08-o1-c1', 'solution', 'Next-token prediction, generating text one token at a time, is what GPT-style decoder-only models train on.', 20, 2),
  ('mission-ai-transformer-architectures-08-o2-c1', 'orientation', 'Ask which model type actually practices producing a token, then the next one, then the next.', 10, 1),
  ('mission-ai-transformer-architectures-08-o2-c1', 'solution', 'Generation is inherently a causal, one-token-at-a-time process, and that matches decoder-only attention and training, not the bidirectional pattern BERT-style models use.', 20, 2),

  ('mission-ai-transformer-architectures-09-o1-c1', 'orientation', 'T5''s whole point is that it does not need a different model shape for every task.', 10, 1),
  ('mission-ai-transformer-architectures-09-o1-c1', 'solution', 'T5 treats every task as a text-to-text problem: text goes in, text comes out, regardless of the underlying task.', 20, 2),
  ('mission-ai-transformer-architectures-09-o2-c1', 'orientation', 'Cross-attention is the bridge between the two halves of an encoder-decoder model.', 10, 1),
  ('mission-ai-transformer-architectures-09-o2-c1', 'solution', 'Cross-attention lets the decoder attend back to the encoder''s representation of the full input while it generates the output causally, one token at a time.', 20, 2),

  ('mission-ai-transformer-architectures-10-o1-c1', 'orientation', 'Ask whether more layers and parameters change what direction attention looks, or just how much it can hold.', 10, 1),
  ('mission-ai-transformer-architectures-10-o1-c1', 'solution', 'Scaling changes the capacity and quality of what a model can represent or generate. It does not change the fundamental attention pattern -- causal stays causal, bidirectional stays bidirectional.', 20, 2),
  ('mission-ai-transformer-architectures-10-o2-c1', 'orientation', 'Ask whether a bigger model would still be structurally unable to see both sides of the sequence.', 10, 1),
  ('mission-ai-transformer-architectures-10-o2-c1', 'solution', 'e1: the summarizer''s causal attention cannot inform a decision that needs the whole sequence at once, no matter how large the model gets -- scaling cannot fix an architecture mismatch.', 20, 2),

  ('mission-ai-transformer-architectures-11-o1-c1', 'orientation', 'Match each limitation to the attention pattern that would actually produce it.', 10, 1),
  ('mission-ai-transformer-architectures-11-o1-c1', 'concept', 'A model with no causal path cannot generate token by token. A model that never sees the future cannot use it. A model built from two halves needs to train and serve both.', 20, 2),
  ('mission-ai-transformer-architectures-11-o1-c1', 'solution', 'Encoder-only -> cannot generate open-ended text. Decoder-only -> cannot use later context. Encoder-decoder -> needs twice the components.', 30, 3),
  ('mission-ai-transformer-architectures-11-o2-c1', 'orientation', 'None of the three shapes wins on every axis at once.', 10, 1),
  ('mission-ai-transformer-architectures-11-o2-c1', 'solution', 'Match the architecture''s attention pattern and training objective to what the job actually needs -- there is no single best shape independent of the task.', 20, 2),

  ('mission-ai-transformer-architectures-12-o1-c1', 'orientation', 'Use the same reasoning from earlier missions: understanding, causal generation, or both in sequence.', 10, 1),
  ('mission-ai-transformer-architectures-12-o1-c1', 'solution', 'Classify -> encoder-only. Generate an explanation -> decoder-only. Translate garbled phrasing -> encoder-decoder.', 20, 2),
  ('mission-ai-transformer-architectures-12-o2-c1', 'orientation', 'A mismatch needs two facts together: what the tool was built with, and what the task actually needed.', 10, 1),
  ('mission-ai-transformer-architectures-12-o2-c1', 'concept', 'A clean training log and a stable deployment history rule out data and drift problems, pointing back at the design itself.', 20, 2),
  ('mission-ai-transformer-architectures-12-o2-c1', 'solution', 'e1 and e2 together: a unidirectional, causal-style model was built for a task that needed context from both sides of every word -- the mismatch is architectural, not a training or data issue.', 30, 3),
  ('mission-ai-transformer-architectures-12-o3-c1', 'orientation', 'The fix should directly address the exact gap identified in the evidence, nothing more.', 10, 1),
  ('mission-ai-transformer-architectures-12-o3-c1', 'solution', 'Bidirectional attention would let the tool weigh context from both sides of each word when deciding a message''s category, instead of only what came before it.', 20, 2),
  ('mission-ai-transformer-architectures-12-o4-c1', 'orientation', 'Bring together which architecture fits which job, and what the Act 21 tool''s mismatch actually proved about that principle.', 15, 1),
  ('mission-ai-transformer-architectures-12-o4-c1', 'solution', 'Classify with encoder-only, generate with decoder-only, translate with encoder-decoder -- and the Act 21 tool''s causal design on a task that needed bidirectional context is exactly why matching architecture to job is not optional.', 25, 2);
