-- Robotics/Embedded/IoT pathway ("The Machine Below") Act 21 -- "Perception"
-- content, inside Arc IV ("Teach Machines Where They Are"). 1 campaign, 2
-- operations, 12 missions (11 lessons + boss), following the same
-- campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other Act. World row
-- (world-vec-perception) already exists and is not touched here. Act 20
-- closed on dead-reckoning drift against outdated maps and the idea that a
-- robot should sense the world directly. Act 21 gives one fleet robot a
-- real camera and depth sensor for a supervised test run -- and it drives
-- straight through a stack of crates without slowing down. The resolution:
-- nothing was broken. The range filter was correctly tuned to reject noisy
-- readings past a distance, and the crates happened to sit exactly inside
-- that rejected zone, so real data was discarded right alongside the noise
-- it was built to remove. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram and boss_encounter, same as prior Acts.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-perception', 'world-vec-perception', 'perception', '4D - Perception', 'Learn how a robot turns raw sensor signal into a usable understanding of the world -- camera models, depth sensing, LiDAR concepts, point clouds, feature detection, object detection and segmentation integration, range filtering, sensor timestamps and full perception pipelines -- while Dr. Lin Ortega investigates a supervised test run where a newly-sighted robot drove straight through a stack of crates it never slowed down for.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-perception-1', 'campaign-vec-perception', 'learning-to-see', 'Learning to See', 'Robot perception, camera models, depth sensing, LiDAR concepts, point clouds, and feature detection concepts.', 1),
  ('operation-vec-perception-2', 'campaign-vec-perception', 'what-the-pipeline-kept', 'What the Pipeline Kept', 'Object detection integration, segmentation integration, range filtering, sensor timestamps, perception pipelines, and the invisible obstacle.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-perception-01', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'robot-perception', 'Robot Perception', 'Vector Division fits one of the drifting fleet robots with a real camera and depth sensor for a supervised test run -- and it drives straight through the space where a stack of crates sits, without ever slowing down. Dr. Lin Ortega starts with the most basic question: what does it actually mean for a robot to perceive something.', 'beginner', ARRAY['imani','lin','byte'], null, null, '{"type":"simulation","simulationId":"robot-perception-sim"}'::jsonb, '{"xp":280,"credits":25}'::jsonb, false, 1),
  ('mission-vec-perception-02', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'camera-models', 'Camera Models Intuition', 'A camera does not hand a robot a scene. It hands the robot a flat grid of brightness values, and every notion of distance or size has to be recovered from that grid by something else entirely.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-perception-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"camera-models-sim"}'::jsonb, '{"xp":280,"credits":30}'::jsonb, false, 2),
  ('mission-vec-perception-03', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'depth-sensing', 'Depth Sensing', 'A single camera image cannot say how far away anything actually is -- a toy truck held close and a real truck parked far down the road can produce the exact same picture. Depth sensing exists to answer the one question a camera alone cannot.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-perception-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"depth-sensing-sim"}'::jsonb, '{"xp":290,"credits":30}'::jsonb, false, 3),
  ('mission-vec-perception-04', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'lidar-concepts', 'LiDAR Concepts', 'Where a depth camera infers distance from light patterns or timing across a small sensor, LiDAR measures it directly -- firing laser pulses outward and timing exactly how long each one takes to come back.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-perception-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"lidar-concepts-sim"}'::jsonb, '{"xp":290,"credits":35}'::jsonb, false, 4),
  ('mission-vec-perception-05', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'point-clouds', 'Point Clouds', 'Neither a depth camera nor a LiDAR hands a robot objects. Both hand it a point cloud -- a scattered set of individual three-dimensional measurements, with no labels, no shapes, and no idea yet which points belong together.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-perception-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"point-clouds-sim"}'::jsonb, '{"xp":300,"credits":35}'::jsonb, false, 5),
  ('mission-vec-perception-06', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-1', 'feature-detection', 'Feature Detection Concepts', 'Before a robot can recognize an object, something has to decide which parts of a point cloud or image are even worth paying attention to -- the edges, corners and clusters that make one patch of data distinct from the noise around it.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-perception-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"feature-detection-sim"}'::jsonb, '{"xp":300,"credits":35}'::jsonb, false, 6),
  ('mission-vec-perception-07', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'object-detection-integration', 'Object Detection Integration', 'Features alone are not an answer. Object detection is the stage that takes those distinct patches of data and turns them into a claim the rest of the robot can actually use: an object of a given kind, sitting at a given location.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-perception-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"object-detection-integration-sim"}'::jsonb, '{"xp":310,"credits":40}'::jsonb, false, 7),
  ('mission-vec-perception-08', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'segmentation-integration', 'Segmentation Integration', 'A detector draws a box around an object and calls it done. Segmentation goes further, labeling every individual point or pixel -- which means it can tell a robot exactly where an object ends, not just roughly where it starts.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-perception-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"segmentation-integration-sim"}'::jsonb, '{"xp":310,"credits":40}'::jsonb, false, 8),
  ('mission-vec-perception-09', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'range-filtering', 'Range Filtering', 'Every depth sensor gets noisier the farther it looks -- so most perception pipelines simply discard any reading past a tuned distance, trusting nothing beyond it. That cutoff has no idea what it is throwing away.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-perception-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"range-filtering-sim"}'::jsonb, '{"xp":320,"credits":40}'::jsonb, false, 9),
  ('mission-vec-perception-10', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'sensor-timestamps', 'Sensor Timestamps', 'A camera frame and a LiDAR sweep captured a tenth of a second apart describe two different moments, not one -- and fusing them without accounting for that gap quietly corrupts everything built on top.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-perception-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"sensor-timestamps-sim"}'::jsonb, '{"xp":320,"credits":45}'::jsonb, false, 10),
  ('mission-vec-perception-11', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'perception-pipelines', 'Perception Pipelines', 'Every stage this Act covered is not a menu of options -- it is one ordered pipeline, and whatever an earlier stage discards, no later stage ever gets a chance to recover.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-perception-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"perception-pipelines-sim"}'::jsonb, '{"xp":330,"credits":45}'::jsonb, false, 11),
  ('mission-vec-perception-12', 'world-vec-perception', 'campaign-vec-perception', 'operation-vec-perception-2', 'the-invisible-obstacle', 'The Invisible Obstacle', 'Nothing about the test-run robot was broken. Vector Division has to prove exactly where, in a pipeline built entirely out of correct decisions, a real stack of crates quietly stopped counting as real.', 'boss', ARRAY['imani','lin','byte'], '{"requiredMissionIds":["mission-vec-perception-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-invisible-obstacle-sim"}'::jsonb, '{"xp":1550,"credits":320,"badgeIds":["the-invisible-obstacle"],"skillXp":{"robotics_fundamentals":210}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-perception-01', 1, 'imani', 'One of the drifting fleet robots just finished its first supervised run with an actual camera and depth sensor bolted on -- and it drove straight through the space where a stack of crates was sitting. It did not swerve. It did not slow down.'),
  ('mission-vec-perception-01', 2, 'lin', 'Dr. Lin Ortega. Before anyone touches that pipeline, I want to be clear about what changed. Every robot last Act was estimating its position from nothing but its own wheels. This one is the first with a sensor that can actually look at the world.'),
  ('mission-vec-perception-01', 3, 'byte', 'And the logs are clean. No exception, no dropped frame, no sensor fault flagged anywhere in the run. Whatever happened, the pipeline believes it did its job correctly.'),
  ('mission-vec-perception-01', 4, 'lin', 'That is the part worth sitting with. Perception is not "having a camera." It is a whole chain of decisions that turns raw signal into something a robot is willing to act on -- and every one of those decisions can be individually correct while the chain as a whole still misses a stack of crates.'),
  ('mission-vec-perception-01', 5, 'imani', 'So before you go looking for what broke, learn what perceiving actually means. Nothing here is going to be a single obvious bug.'),

  ('mission-vec-perception-02', 1, 'lin', 'A camera does not capture a scene. It captures a flat grid of brightness values -- a projection of the three-dimensional world onto a two-dimensional plane. Everything about depth, about how far away something actually is, is thrown away in that projection.'),
  ('mission-vec-perception-02', 2, 'lin', 'Hold a toy truck close to a lens and park a real truck far down the road, and with the right framing, both can produce the exact same image. A camera model describes exactly how that projection happens -- and exactly what information it necessarily loses on the way.'),

  ('mission-vec-perception-03', 1, 'lin', 'A camera alone cannot answer how far away anything is. Depth sensing exists specifically to add that missing dimension back -- usually by projecting a known pattern of light and measuring how it distorts, or by timing how long emitted light takes to return.'),
  ('mission-vec-perception-03', 2, 'byte', 'The robot''s depth sensor produces exactly that: a distance value for a grid of points, not just a color. Structured light and time-of-flight are two different ways of measuring the same thing -- how far away is whatever is in front of this pixel.'),

  ('mission-vec-perception-04', 1, 'lin', 'LiDAR works on the same timing principle as a time-of-flight depth camera, but at a different scale entirely. It fires a laser pulse, times its return, and does that across a sweeping field of view -- meters of range outdoors, not the short indoor distances a depth camera is built for.'),
  ('mission-vec-perception-04', 2, 'lin', 'The tradeoff is density. A depth camera fills in an entire grid of points from a single frame. A LiDAR sweep produces a much sparser set of points, spread across a much larger area.'),

  ('mission-vec-perception-05', 1, 'byte', 'Whatever produces the distance measurements -- depth camera, LiDAR, does not matter -- the raw output is the same shape: a point cloud. A big scattered set of individual three-dimensional coordinates, each one just a location in space.'),
  ('mission-vec-perception-05', 2, 'lin', 'No labels. No boundaries. No idea which points belong to the same object and which belong to the floor next to it. A point cloud is measurement, not understanding -- understanding is everything that happens to it afterward.'),

  ('mission-vec-perception-06', 1, 'lin', 'A point cloud or an image on its own is too much data to reason about point by point. Feature detection is the step that picks out which parts are actually distinct -- an edge, a corner, a dense cluster of points -- so later stages have something structured to work with instead of raw noise.'),
  ('mission-vec-perception-06', 2, 'byte', 'It is not asking "what is this object." It is only asking "which parts of this data are worth paying attention to at all." That distinction becomes important very soon.'),

  ('mission-vec-perception-07', 1, 'lin', 'Object detection sits directly on top of feature detection. It takes those distinct patches of data and turns them into an actual claim: an object of this kind is located here. That claim is what the rest of the robot -- planning, navigation -- actually consumes.'),
  ('mission-vec-perception-07', 2, 'byte', 'Which means object detection is not one algorithm bolted onto raw sensor data. It is the receiving end of everything upstream of it. If the features it gets are wrong, or missing, the detector cannot invent an object out of nothing.'),

  ('mission-vec-perception-08', 1, 'lin', 'A detector draws a box and calls it a crate. Segmentation goes one level deeper -- it labels every individual point or pixel, so the boundary of that crate is exact, not just approximately inside a rectangle.'),
  ('mission-vec-perception-08', 2, 'byte', 'Same integration point as detection, though. Segmentation is still downstream of whatever features and raw points actually made it that far through the pipeline. It labels precisely -- but only what it is given to label.'),

  ('mission-vec-perception-09', 1, 'lin', 'Every depth sensor gets less reliable the farther out it looks -- more noise, more scatter, more readings that are just wrong. Range filtering is the standard fix: pick a distance, and discard anything the sensor reports past it.'),
  ('mission-vec-perception-09', 2, 'byte', 'It is a blunt tool by design. The filter does not evaluate whether an individual far-away reading is real or noisy. It only checks one number: is this point''s distance past the cutoff. Past it, gone -- correct data and noise, discarded exactly alike.'),
  ('mission-vec-perception-09', 3, 'lin', 'Tuned well, that tradeoff is worth it -- most of what gets discarded past the cutoff really is noise. But "most" is not "all," and the filter itself has no way to tell the difference.'),

  ('mission-vec-perception-10', 1, 'lin', 'A camera frame and a LiDAR sweep captured a tenth of a second apart are not describing the same instant. If the pipeline fuses them as though they were, it is quietly combining two different moments into one -- and calling the result a single measurement.'),
  ('mission-vec-perception-10', 2, 'byte', 'Every reading this pipeline records is stamped with the exact moment its sensor captured it, not the moment it happened to arrive at the processing stage. Arrival time can lag behind capture time for reasons that have nothing to do with what the sensor actually saw.'),
  ('mission-vec-perception-10', 3, 'lin', 'Which is why, when something goes wrong, checking whether a sensor''s timestamps stayed correct and consistent is one of the first ways to rule out a hardware or timing fault entirely.'),

  ('mission-vec-perception-11', 1, 'lin', 'Put every stage from this Act in order, and it is not a menu -- it is one pipeline. Raw signal, into a point cloud, into features, into detection or segmentation, into whatever planning consumes at the end. Each stage only ever sees what the stage before it decided to pass along.'),
  ('mission-vec-perception-11', 2, 'byte', 'Which means a downstream stage has no way to know what an earlier one discarded. Detection cannot flag a crate it was never given data for. It is not being careless -- it genuinely never received the evidence.'),
  ('mission-vec-perception-11', 3, 'lin', 'That is the property to hold onto going into this. Every stage in that chain can be individually correct, and the pipeline as a whole can still lose something real -- if the discarding happens early enough that nothing downstream ever gets a chance to see it.'),

  ('mission-vec-perception-12', 1, 'imani', 'Camera, depth sensor, LiDAR, point clouds, features, detection, segmentation, filtering, timestamps -- all of it, on one supervised run. A robot with real perception drove through a stack of crates that was sitting right in front of it.'),
  ('mission-vec-perception-12', 2, 'lin', 'Nothing crashed. Nothing threw an error. Every stage we have looked at this Act did exactly what it was built to do. Which means the answer is not "something broke." It is "something correct produced the wrong outcome," and we have to prove exactly where.'),
  ('mission-vec-perception-12', 3, 'byte', 'I pulled the raw sensor log from the run, not the processed output. If those crates were ever actually captured by the sensor before anything discarded them, it will be in there.'),
  ('mission-vec-perception-12', 4, 'lin', 'Three things, in order. Where in the pipeline the crates disappeared. Whether the raw sensor ever actually saw them at all. And whether this is a software decision or a hardware fault -- because those get fixed in completely different ways.'),
  ('mission-vec-perception-12', 5, 'imani', 'Prove all three, and you have the real diagnosis. Guess at any one of them, and Vector Division ships a fix for the wrong problem.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-perception-01-o1', 'mission-vec-perception-01', 1, 'Define perception correctly', 'Choose the accurate description of what robot perception actually is.'),
  ('mission-vec-perception-01-o2', 'mission-vec-perception-01', 2, 'Read the clean logs', 'Find the evidence proving the pipeline reported no error during the run.'),

  ('mission-vec-perception-02-o1', 'mission-vec-perception-02', 1, 'Define what a camera model captures', 'Choose the accurate description of what a camera model describes.'),
  ('mission-vec-perception-02-o2', 'mission-vec-perception-02', 2, 'Explain the size-distance ambiguity', 'Judge why a single camera image cannot tell size and distance apart.'),

  ('mission-vec-perception-03-o1', 'mission-vec-perception-03', 1, 'Explain what depth sensing adds', 'Choose the accurate description of what a depth sensor measures that a plain camera cannot.'),
  ('mission-vec-perception-03-o2', 'mission-vec-perception-03', 2, 'Match sensing methods to their principle', 'Sort each depth-sensing description into the technique it describes.'),

  ('mission-vec-perception-04-o1', 'mission-vec-perception-04', 1, 'Define LiDAR''s measurement principle', 'Choose the accurate description of how LiDAR measures distance.'),
  ('mission-vec-perception-04-o2', 'mission-vec-perception-04', 2, 'Contrast LiDAR with a depth camera', 'Judge the correct tradeoff between LiDAR and a short-range depth camera.'),

  ('mission-vec-perception-05-o1', 'mission-vec-perception-05', 1, 'Define a point cloud correctly', 'Choose the accurate description of what a point cloud actually contains.'),
  ('mission-vec-perception-05-o2', 'mission-vec-perception-05', 2, 'Order the raw-to-organized stages', 'Order the stages from raw sensor signal to a grouped point cloud.'),

  ('mission-vec-perception-06-o1', 'mission-vec-perception-06', 1, 'Define feature detection correctly', 'Choose the accurate description of what feature detection does.'),
  ('mission-vec-perception-06-o2', 'mission-vec-perception-06', 2, 'Separate detection from recognition', 'Judge whether feature detection alone can tell a robot what an object is.'),

  ('mission-vec-perception-07-o1', 'mission-vec-perception-07', 1, 'Define object detection''s role', 'Choose the accurate description of what the object detection stage produces.'),
  ('mission-vec-perception-07-o2', 'mission-vec-perception-07', 2, 'Trace the pipeline dependency', 'Judge what happens when object detection is missing data an earlier stage should have passed it.'),

  ('mission-vec-perception-08-o1', 'mission-vec-perception-08', 1, 'Distinguish segmentation from detection', 'Choose the accurate distinction between object detection and segmentation.'),
  ('mission-vec-perception-08-o2', 'mission-vec-perception-08', 2, 'Confirm segmentation''s dependency', 'Judge whether segmentation can label a point the pipeline never delivered to it.'),

  ('mission-vec-perception-09-o1', 'mission-vec-perception-09', 1, 'Define range filtering correctly', 'Choose the accurate description of what a range filter does and why it exists.'),
  ('mission-vec-perception-09-o2', 'mission-vec-perception-09', 2, 'Identify the filter''s blind spot', 'Judge what a range filter cannot distinguish once a reading passes its cutoff.'),

  ('mission-vec-perception-10-o1', 'mission-vec-perception-10', 1, 'Explain why capture time matters', 'Choose the accurate reason sensor timestamps must reflect capture time, not arrival time.'),
  ('mission-vec-perception-10-o2', 'mission-vec-perception-10', 2, 'Use timestamps to rule out a fault', 'Judge what consistent, correctly ordered timestamps would prove about a sensor.'),

  ('mission-vec-perception-11-o1', 'mission-vec-perception-11', 1, 'Order the full pipeline', 'Order the stages of a perception pipeline from raw signal to consumable output.'),
  ('mission-vec-perception-11-o2', 'mission-vec-perception-11', 2, 'Explain why downstream stages cannot recover a discard', 'Judge why an early discard is invisible to every later stage.'),

  ('mission-vec-perception-12-o1', 'mission-vec-perception-12', 1, 'Prove the range filter''s dead zone', 'Find the evidence proving the crates sat exactly inside the range filter''s rejected distance zone.'),
  ('mission-vec-perception-12-o2', 'mission-vec-perception-12', 2, 'Prove the raw sensor captured them', 'Find the evidence proving the raw sensor data recorded the crates before filtering discarded the reading.'),
  ('mission-vec-perception-12-o3', 'mission-vec-perception-12', 3, 'Rule out a hardware or timing fault', 'Judge whether the incident was caused by a hardware or timestamp fault, based on the sensor''s timing records.'),
  ('mission-vec-perception-12-o4', 'mission-vec-perception-12', 4, 'State the diagnosis', 'Having proven all three, state what actually happened to the crates in the pipeline.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-perception-01-o1-c1', 'mission-vec-perception-01-o1', 1, 'multiple_choice', 'What does "robot perception" actually mean?', '{"question":"What does \"robot perception\" actually mean?","options":[{"id":"a","text":"Owning a camera or other sensor"},{"id":"b","text":"A chain of processing stages that turns raw sensor signal into an understanding of the world a robot is willing to act on"},{"id":"c","text":"Any software that runs on a robot"},{"id":"d","text":"Perfectly accurate 3D reconstruction of the environment"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-01-o2-c1', 'mission-vec-perception-01-o2', 1, 'investigation', 'Which evidence proves the pipeline itself reported no error during the run?', '{"evidence":[{"id":"e1","label":"Run log summary","detail":"No exceptions, faults, or dropped frames recorded during the entire supervised run"},{"id":"e2","label":"Camera hardware check","detail":"Camera and depth sensor both passed self-test before the run began"},{"id":"e3","label":"Facilities note","detail":"The crates had been in that location for three days prior to the run"}],"question":"Which evidence proves the pipeline itself reported no error during the run?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-perception-02-o1-c1', 'mission-vec-perception-02-o1', 1, 'multiple_choice', 'A camera model describes...', '{"question":"A camera model describes...","options":[{"id":"a","text":"The exact color of every object in a scene"},{"id":"b","text":"How points in the three-dimensional world project onto a two-dimensional image plane, and what information that projection necessarily discards"},{"id":"c","text":"How to compress an image file"},{"id":"d","text":"The mechanical shutter speed of a camera"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-02-o2-c1', 'mission-vec-perception-02-o2', 1, 'multiple_choice', 'Why can a single camera image not tell a close small object apart from a distant large one?', '{"question":"Why can a single camera image not tell a close small object apart from a distant large one?","options":[{"id":"a","text":"It can, cameras always encode distance directly"},{"id":"b","text":"Because projection onto a flat image plane discards depth -- both scenarios can produce identical angular size in the image"},{"id":"c","text":"Because cameras only work in black and white"},{"id":"d","text":"Because lenses distort every image equally"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-03-o1-c1', 'mission-vec-perception-03-o1', 1, 'multiple_choice', 'What does a depth sensor add that a plain camera image cannot provide on its own?', '{"question":"What does a depth sensor add that a plain camera image cannot provide on its own?","options":[{"id":"a","text":"Higher resolution color"},{"id":"b","text":"A distance measurement for points in the scene, recovering the dimension a flat image projection discards"},{"id":"c","text":"Faster frame rates"},{"id":"d","text":"Automatic object labels"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-03-o2-c1', 'mission-vec-perception-03-o2', 1, 'drag_and_drop', 'Sort each description into the depth-sensing technique it describes.', '{"items":[{"id":"i1","text":"Projects a known light pattern and measures how it distorts across the surface it lands on"},{"id":"i2","text":"Times how long a pulse of light takes to leave the sensor and return"},{"id":"i3","text":"Compares the same scene from two slightly offset camera lenses to compute disparity"}],"targets":[{"id":"structured-light","label":"Structured light"},{"id":"time-of-flight","label":"Time-of-flight"},{"id":"stereo","label":"Stereo"}]}'::jsonb, '{"correctMapping":{"i1":"structured-light","i2":"time-of-flight","i3":"stereo"}}'::jsonb),

  ('mission-vec-perception-04-o1-c1', 'mission-vec-perception-04-o1', 1, 'multiple_choice', 'LiDAR measures distance by...', '{"question":"LiDAR measures distance by...","options":[{"id":"a","text":"Comparing two camera images for disparity"},{"id":"b","text":"Emitting laser pulses and timing how long each one takes to return, across a sweeping field of view"},{"id":"c","text":"Measuring the weight of reflected sound"},{"id":"d","text":"Reading a barcode on nearby objects"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-04-o2-c1', 'mission-vec-perception-04-o2', 1, 'multiple_choice', 'Compared to a short-range depth camera, LiDAR typically trades...', '{"question":"Compared to a short-range depth camera, LiDAR typically trades...","options":[{"id":"a","text":"Nothing, they produce identical output"},{"id":"b","text":"A much larger range for a sparser set of points per sweep"},{"id":"c","text":"Color accuracy for point density"},{"id":"d","text":"Power consumption for zero range at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-05-o1-c1', 'mission-vec-perception-05-o1', 1, 'multiple_choice', 'A point cloud is best described as...', '{"question":"A point cloud is best described as...","options":[{"id":"a","text":"A finished 3D model with labeled objects"},{"id":"b","text":"An unlabeled set of individual three-dimensional coordinate measurements, with no grouping or object identity yet assigned"},{"id":"c","text":"A 2D image with color only"},{"id":"d","text":"A single distance value for the whole scene"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-05-o2-c1', 'mission-vec-perception-05-o2', 1, 'interactive_diagram', 'Order the stages from raw sensor signal to a grouped point cloud.', '{"diagramId":"raw-to-cloud","hotspots":[{"id":"raw-signal","label":"Raw signal","explanation":"Unprocessed sensor return -- light timing, pattern distortion, and so on."},{"id":"point-cloud","label":"Point cloud","explanation":"The raw signal converted into individual 3D coordinate measurements."},{"id":"grouped","label":"Grouped structure","explanation":"Points organized into candidate clusters or surfaces."}],"task":"Order the stages from raw signal to grouped structure."}'::jsonb, '{"correctOrderIds":["raw-signal","point-cloud","grouped"]}'::jsonb),

  ('mission-vec-perception-06-o1-c1', 'mission-vec-perception-06-o1', 1, 'multiple_choice', 'Feature detection is the stage that...', '{"question":"Feature detection is the stage that...","options":[{"id":"a","text":"Assigns a class label like \"crate\" or \"person\" to an object"},{"id":"b","text":"Identifies which parts of raw sensor data -- edges, corners, dense clusters -- are distinct enough to be worth further processing"},{"id":"c","text":"Filters out all noisy readings automatically"},{"id":"d","text":"Converts a point cloud into an image"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-06-o2-c1', 'mission-vec-perception-06-o2', 1, 'multiple_choice', 'On its own, can feature detection tell a robot what kind of object it is looking at?', '{"question":"On its own, can feature detection tell a robot what kind of object it is looking at?","options":[{"id":"a","text":"Yes, features are labels by definition"},{"id":"b","text":"No -- it only flags which parts of the data are structurally distinct; deciding what those parts are is a separate, later stage"},{"id":"c","text":"Only for LiDAR data, never camera data"},{"id":"d","text":"Only if the object is moving"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-07-o1-c1', 'mission-vec-perception-07-o1', 1, 'multiple_choice', 'The object detection stage''s job is to...', '{"question":"The object detection stage''s job is to...","options":[{"id":"a","text":"Measure raw distance values directly from the sensor"},{"id":"b","text":"Take structured features and output a claim -- an object of a given kind, at a given location -- that later stages like planning can act on"},{"id":"c","text":"Replace feature detection entirely"},{"id":"d","text":"Calibrate the camera lens"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-07-o2-c1', 'mission-vec-perception-07-o2', 1, 'multiple_choice', 'If the data reaching object detection is missing real information the sensor actually captured, what happens?', '{"question":"If the data reaching object detection is missing real information the sensor actually captured, what happens?","options":[{"id":"a","text":"The detector fills in the gap using its training data alone"},{"id":"b","text":"The detector can only work with what it receives -- it cannot recover or invent an object out of data that never reached it"},{"id":"c","text":"The detector automatically re-requests raw sensor data"},{"id":"d","text":"Nothing, detection is independent of upstream stages"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-08-o1-c1', 'mission-vec-perception-08-o1', 1, 'multiple_choice', 'The difference between object detection and segmentation is...', '{"question":"The difference between object detection and segmentation is...","options":[{"id":"a","text":"They are the same technique with different names"},{"id":"b","text":"Detection outputs a rough bounding region per object; segmentation labels every individual point or pixel, producing an exact boundary"},{"id":"c","text":"Segmentation only works on color images, detection only on point clouds"},{"id":"d","text":"Detection is always more accurate than segmentation"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-08-o2-c1', 'mission-vec-perception-08-o2', 1, 'multiple_choice', 'Can segmentation label a point that never reached it from an earlier pipeline stage?', '{"question":"Can segmentation label a point that never reached it from an earlier pipeline stage?","options":[{"id":"a","text":"Yes, segmentation reconstructs missing points automatically"},{"id":"b","text":"No -- like detection, segmentation only labels the data that actually makes it through the stages upstream of it"},{"id":"c","text":"Only for LiDAR-based pipelines"},{"id":"d","text":"Only if the point was labeled once before"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-09-o1-c1', 'mission-vec-perception-09-o1', 1, 'multiple_choice', 'A range filter exists to...', '{"question":"A range filter exists to...","options":[{"id":"a","text":"Improve camera color accuracy"},{"id":"b","text":"Discard sensor readings past a tuned distance cutoff, because sensor noise increases with range"},{"id":"c","text":"Sort points into detected objects"},{"id":"d","text":"Synchronize timestamps between sensors"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-09-o2-c1', 'mission-vec-perception-09-o2', 1, 'multiple_choice', 'Once a reading falls past a range filter''s cutoff distance, what happens to it?', '{"question":"Once a reading falls past a range filter''s cutoff distance, what happens to it?","options":[{"id":"a","text":"It is flagged as low-confidence but kept"},{"id":"b","text":"It is discarded outright, with no distinction made between real data and actual noise -- the filter only checks distance, not truth"},{"id":"c","text":"It is automatically re-measured by a second sensor"},{"id":"d","text":"It is kept if it matches a known object shape"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-10-o1-c1', 'mission-vec-perception-10-o1', 1, 'multiple_choice', 'Why must a sensor reading be timestamped with its capture time rather than the time it arrives at the processing stage?', '{"question":"Why must a sensor reading be timestamped with its capture time rather than the time it arrives at the processing stage?","options":[{"id":"a","text":"Capture time and arrival time are always identical, so it does not matter"},{"id":"b","text":"Fusing readings from different sensors requires knowing what moment each one actually describes, and arrival can lag capture for reasons unrelated to what was sensed"},{"id":"c","text":"Arrival time is more accurate than capture time"},{"id":"d","text":"Timestamps are only needed for logging, not fusion"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-10-o2-c1', 'mission-vec-perception-10-o2', 1, 'multiple_choice', 'If every sensor reading around an incident is correctly timestamped and consistent with the others, what does that prove?', '{"question":"If every sensor reading around an incident is correctly timestamped and consistent with the others, what does that prove?","options":[{"id":"a","text":"Nothing, timestamps cannot prove anything"},{"id":"b","text":"It rules out a hardware or timing fault as the cause -- the sensors were capturing and reporting reliably at the moment that mattered"},{"id":"c","text":"It proves the object being sensed was moving"},{"id":"d","text":"It proves the range filter was misconfigured"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-11-o1-c1', 'mission-vec-perception-11-o1', 1, 'interactive_diagram', 'Order the pipeline stages from raw signal to final output.', '{"diagramId":"perception-pipeline-full","hotspots":[{"id":"raw-signal","label":"Raw signal","explanation":"Unprocessed sensor return."},{"id":"filtering","label":"Filtering","explanation":"Noisy or out-of-range readings discarded."},{"id":"point-cloud","label":"Point cloud","explanation":"Remaining readings organized into 3D coordinates."},{"id":"features","label":"Feature detection","explanation":"Distinct structures picked out."},{"id":"detection","label":"Detection/segmentation","explanation":"Features turned into labeled objects."},{"id":"output","label":"Output","explanation":"Consumed by planning and navigation."}],"task":"Order the pipeline stages from raw signal to final output."}'::jsonb, '{"correctOrderIds":["raw-signal","filtering","point-cloud","features","detection","output"]}'::jsonb),
  ('mission-vec-perception-11-o2-c1', 'mission-vec-perception-11-o2', 1, 'multiple_choice', 'Why can a later stage like object detection never recover an object an earlier filtering stage discarded?', '{"question":"Why can a later stage like object detection never recover an object an earlier filtering stage discarded?","options":[{"id":"a","text":"It can, detection re-scans raw sensor data independently"},{"id":"b","text":"Because each stage only receives what the stage before it passed along -- data discarded early never reaches any later stage at all"},{"id":"c","text":"Because detection only works on labeled data"},{"id":"d","text":"It cannot, because detection runs before filtering"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-perception-12-o1-c1', 'mission-vec-perception-12-o1', 1, 'investigation', 'Which evidence proves the crates sat exactly inside the range filter''s rejected zone?', '{"evidence":[{"id":"e1","label":"Range filter config","detail":"Filter tuned to discard any reading past 4.2 meters, a distance chosen from this sensor model''s published noise curve"},{"id":"e2","label":"Facilities measurement","detail":"The crate stack sat between 4.1 and 4.6 meters from the robot''s sensor for the entire run"},{"id":"e3","label":"Lighting log","detail":"Ambient warehouse lighting stayed within normal range throughout the test"}],"question":"Which evidence proves the crates sat exactly inside the range filter''s rejected zone?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-vec-perception-12-o2-c1', 'mission-vec-perception-12-o2', 1, 'investigation', 'Which evidence proves the raw sensor actually captured the crates before filtering discarded the reading?', '{"evidence":[{"id":"e1","label":"Raw point cloud dump","detail":"Raw depth sensor output for the run frame contains a dense cluster of points at 4.1-4.6 meters matching the crate stack''s shape and position"},{"id":"e2","label":"Post-filter point cloud","detail":"The same region is completely empty in the point cloud after range filtering runs"},{"id":"e3","label":"Object detector output","detail":"Detector reported zero objects for the entire run"}],"question":"Which evidence proves the raw sensor actually captured the crates before filtering discarded the reading?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-perception-12-o3-c1', 'mission-vec-perception-12-o3', 1, 'multiple_choice', 'Every reading from the run carries a correctly ordered, internally consistent timestamp with no gaps or duplicates around the moment the crates were in range. What does that indicate?', '{"question":"Every reading from the run carries a correctly ordered, internally consistent timestamp with no gaps or duplicates around the moment the crates were in range. What does that indicate?","options":[{"id":"a","text":"A hardware or timing fault is the likely cause"},{"id":"b","text":"The sensor was capturing and reporting reliably at the moment that mattered -- this rules out a hardware or timing fault, leaving the range filter''s configuration as the explanation"},{"id":"c","text":"The crates were never actually present"},{"id":"d","text":"The timestamps are irrelevant to diagnosing this incident"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-perception-12-o4-c1', 'mission-vec-perception-12-o4', 1, 'boss_encounter', 'Having proven where in the pipeline the crates disappeared, that the raw sensor actually captured them, and that no hardware fault was involved, state what actually happened to the crates.', '{"stages":[{"objectiveRef":"mission-vec-perception-12-o1","label":"Prove the range filter''s dead zone"},{"objectiveRef":"mission-vec-perception-12-o2","label":"Prove the raw sensor captured them"},{"objectiveRef":"mission-vec-perception-12-o3","label":"Rule out a hardware or timing fault"}],"task":"State the diagnosis in one sentence: the range filter was correctly tuned against sensor noise, and the crates happened to sit exactly inside the distance band it was built to reject, so real data was discarded right alongside the noise -- not a hardware fault, not a missed detection, a correctly-functioning filter with no way to tell true signal from noise at its own cutoff."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-perception-12-o1","mission-vec-perception-12-o2","mission-vec-perception-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-perception-01-o1-c1', 'orientation', 'Think about whether "having a sensor" and "understanding what it captured" are the same thing.', 10, 1),
  ('mission-vec-perception-01-o1-c1', 'solution', 'Perception is the whole chain of processing that turns raw sensor signal into something a robot is willing to act on -- not simply owning a camera.', 20, 2),
  ('mission-vec-perception-01-o2-c1', 'orientation', 'Look for a summary of the run itself, not a pre-run hardware check.', 10, 1),
  ('mission-vec-perception-01-o2-c1', 'solution', 'e1: the run log summary shows no exceptions, faults, or dropped frames -- the pipeline reported a clean run.', 20, 2),

  ('mission-vec-perception-02-o1-c1', 'orientation', 'Ask what happens to the third dimension when a 3D scene becomes a flat image.', 10, 1),
  ('mission-vec-perception-02-o1-c1', 'solution', 'A camera model describes how 3D points project onto a 2D image plane, and what depth information that projection discards.', 20, 2),
  ('mission-vec-perception-02-o2-c1', 'orientation', 'Picture the same size in the frame produced by two very different real-world sizes at two very different real-world distances.', 10, 1),
  ('mission-vec-perception-02-o2-c1', 'solution', 'A single image cannot separate size from distance because projection collapses both into the same angular size on the flat plane.', 20, 2),

  ('mission-vec-perception-03-o1-c1', 'orientation', 'Ask what a plain camera image is missing that a depth sensor specifically adds back.', 10, 1),
  ('mission-vec-perception-03-o1-c1', 'solution', 'A depth sensor adds a distance value per point, recovering the dimension a flat camera projection throws away.', 20, 2),
  ('mission-vec-perception-03-o2-c1', 'orientation', 'Think about what physical property each method actually measures -- a pattern''s distortion, a pulse''s travel time, or a difference between two viewpoints.', 10, 1),
  ('mission-vec-perception-03-o2-c1', 'concept', 'Structured light reads how a projected pattern distorts on a surface. Time-of-flight times a pulse''s round trip. Stereo compares two offset views for disparity.', 20, 2),
  ('mission-vec-perception-03-o2-c1', 'solution', 'i1 -> structured-light, i2 -> time-of-flight, i3 -> stereo.', 30, 3),

  ('mission-vec-perception-04-o1-c1', 'orientation', 'Focus on what LiDAR is actually timing.', 10, 1),
  ('mission-vec-perception-04-o1-c1', 'solution', 'LiDAR measures distance by timing how long emitted laser pulses take to return, swept across a field of view.', 20, 2),
  ('mission-vec-perception-04-o2-c1', 'orientation', 'Weigh coverage area against how many points come back per capture.', 10, 1),
  ('mission-vec-perception-04-o2-c1', 'solution', 'LiDAR trades a much larger effective range for a sparser set of points compared to a short-range depth camera.', 20, 2),

  ('mission-vec-perception-05-o1-c1', 'orientation', 'Ask whether a point cloud already knows which points belong to the same object.', 10, 1),
  ('mission-vec-perception-05-o1-c1', 'solution', 'A point cloud is an unlabeled set of individual 3D coordinate measurements -- grouping and identity come later.', 20, 2),
  ('mission-vec-perception-05-o2-c1', 'orientation', 'Nothing can be grouped before it has been measured, and nothing can be measured before a raw signal exists.', 10, 1),
  ('mission-vec-perception-05-o2-c1', 'concept', 'The order runs from the sensor''s unprocessed return, to a converted set of 3D points, to those points being organized into candidate groups.', 20, 2),
  ('mission-vec-perception-05-o2-c1', 'solution', 'raw-signal, then point-cloud, then grouped.', 30, 3),

  ('mission-vec-perception-06-o1-c1', 'orientation', 'Feature detection is not deciding what something is -- only whether it stands out.', 10, 1),
  ('mission-vec-perception-06-o1-c1', 'solution', 'Feature detection identifies which parts of raw data -- edges, corners, dense clusters -- are structurally distinct enough for later stages to use.', 20, 2),
  ('mission-vec-perception-06-o2-c1', 'orientation', 'Ask whether "this part of the data stands out" is the same claim as "this part of the data is a crate."', 10, 1),
  ('mission-vec-perception-06-o2-c1', 'solution', 'Feature detection alone only flags distinctness -- assigning what an object actually is happens in a separate, later stage.', 20, 2),

  ('mission-vec-perception-07-o1-c1', 'orientation', 'Ask what object detection hands to the rest of the robot, not what it receives.', 10, 1),
  ('mission-vec-perception-07-o1-c1', 'solution', 'Object detection turns features into a claim -- an object of a given kind, at a given location -- that stages like planning can act on.', 20, 2),
  ('mission-vec-perception-07-o2-c1', 'orientation', 'A detector cannot label evidence it was never handed.', 10, 1),
  ('mission-vec-perception-07-o2-c1', 'solution', 'A detector can only work with what reaches it -- it cannot recover or invent an object from data that never arrived.', 20, 2),

  ('mission-vec-perception-08-o1-c1', 'orientation', 'Think about the granularity of the output -- a box, or a boundary.', 10, 1),
  ('mission-vec-perception-08-o1-c1', 'solution', 'Detection outputs a rough region per object; segmentation labels every individual point or pixel for an exact boundary.', 20, 2),
  ('mission-vec-perception-08-o2-c1', 'orientation', 'Segmentation is downstream of the same pipeline as detection.', 10, 1),
  ('mission-vec-perception-08-o2-c1', 'solution', 'Segmentation can only label data that actually reaches it -- it cannot reconstruct points an earlier stage never delivered.', 20, 2),

  ('mission-vec-perception-09-o1-c1', 'orientation', 'Ask why a fixed distance cutoff would be useful at all.', 10, 1),
  ('mission-vec-perception-09-o1-c1', 'solution', 'A range filter discards readings past a tuned cutoff because sensor noise increases with distance, and the tradeoff is usually worth it.', 20, 2),
  ('mission-vec-perception-09-o2-c1', 'orientation', 'Ask what single number the filter actually checks.', 10, 1),
  ('mission-vec-perception-09-o2-c1', 'solution', 'Past the cutoff, a reading is discarded outright -- the filter only checks distance, with no way to tell real data from noise.', 20, 2),

  ('mission-vec-perception-10-o1-c1', 'orientation', 'Ask what "the same moment" actually requires when combining two sensors.', 10, 1),
  ('mission-vec-perception-10-o1-c1', 'solution', 'Fusing readings correctly requires knowing the moment each one describes -- arrival time can lag capture time for reasons unrelated to what was sensed.', 20, 2),
  ('mission-vec-perception-10-o2-c1', 'orientation', 'Ask what consistent timestamps would rule out, not what they would prove happened.', 10, 1),
  ('mission-vec-perception-10-o2-c1', 'solution', 'Correct, consistent timestamps rule out a hardware or timing fault -- the sensors were capturing and reporting reliably when it mattered.', 20, 2),

  ('mission-vec-perception-11-o1-c1', 'orientation', 'Filtering has to happen before the surviving points get organized into a cloud, and detection needs features before it can label anything.', 10, 1),
  ('mission-vec-perception-11-o1-c1', 'concept', 'The chain runs from unprocessed signal, through filtering, into an organized point cloud, through feature detection, into detection or segmentation, and finally to whatever consumes the output.', 20, 2),
  ('mission-vec-perception-11-o1-c1', 'solution', 'raw-signal, filtering, point-cloud, features, detection, output.', 30, 3),
  ('mission-vec-perception-11-o2-c1', 'orientation', 'Ask what a later stage actually receives versus what the sensor originally captured.', 10, 1),
  ('mission-vec-perception-11-o2-c1', 'solution', 'A later stage only ever sees what an earlier stage passed along -- data discarded early never reaches it at all, so it cannot recover what it never received.', 20, 2),

  ('mission-vec-perception-12-o1-c1', 'orientation', 'Compare the filter''s exact cutoff distance against the crate stack''s exact measured distance.', 10, 1),
  ('mission-vec-perception-12-o1-c1', 'concept', 'The filter''s cutoff was chosen from a noise curve, not from anything about this specific run -- so it has no way to know a real object happens to sit right where it draws the line.', 20, 2),
  ('mission-vec-perception-12-o1-c1', 'solution', 'e1 and e2 together: the filter cuts off at 4.2 meters, and the crates measured between 4.1 and 4.6 meters -- squarely straddling and mostly past that exact cutoff.', 30, 3),
  ('mission-vec-perception-12-o2-c1', 'orientation', 'Look for the data captured before filtering ran, not after.', 10, 1),
  ('mission-vec-perception-12-o2-c1', 'solution', 'e1: the raw point cloud dump shows a dense cluster of points matching the crate stack''s shape and position, before any filtering removed them.', 20, 2),
  ('mission-vec-perception-12-o3-c1', 'orientation', 'Ask what consistent timestamps would rule out, not confirm.', 10, 1),
  ('mission-vec-perception-12-o3-c1', 'solution', 'Correctly ordered, gap-free timestamps around the incident rule out a hardware or timing fault -- the sensors were working exactly as intended.', 20, 2),
  ('mission-vec-perception-12-o4-c1', 'orientation', 'Line up all three judgments: where it happened, whether it was ever really there, and whether hardware was at fault.', 15, 1),
  ('mission-vec-perception-12-o4-c1', 'solution', 'The range filter was correctly tuned against sensor noise, and the crates happened to sit exactly inside the distance band it was built to reject -- discarding real data alongside the noise, with no hardware fault anywhere in the chain.', 25, 2);
