-- Robotics/Embedded/IoT pathway ("Vector Division") Act 11 -- "The RTOS"
-- content, under world-vec-the-rtos (already inserted separately, under
-- act-vec-2, index 10). 1 campaign, 2 operations, 12 missions (11 lessons +
-- boss), following the same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every prior
-- Act. No new ChallengeType needed -- reuses multiple_choice, drag_and_drop,
-- investigation, interactive_diagram and boss_encounter. Arc II, "Firmware
-- Controls Reality": Vector Division ports the reactor arm's stabilized
-- control loop, the door fix, and Byte's own telemetry logging onto one
-- shared RTOS, and the very first multi-task build intermittently stalls
-- the control loop -- the whole Act builds toward diagnosing that stall as
-- priority inversion, not a deadlock, in the boss mission.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-the-rtos', 'world-vec-the-rtos', 'the-rtos', '2F - The RTOS', 'Learn the vocabulary of real-time multitasking -- tasks, the scheduler, priorities, queues, semaphores, mutexes, event groups, software timers, task notifications and deadlocks -- while Tomas Vey ports three independent jobs onto one shared RTOS and the very first build starts stalling under its own weight.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-the-rtos-1', 'campaign-vec-the-rtos', 'sharing-one-processor', 'Sharing One Processor', 'Why an RTOS, tasks, the scheduler, priorities, queues and semaphores.', 1),
  ('operation-vec-the-rtos-2', 'campaign-vec-the-rtos', 'the-stalling-loop', 'The Stalling Loop', 'Mutexes, event groups, software timers, task notifications, deadlocks and the diagnosis of the control loop''s intermittent stall.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-the-rtos-01', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'why-an-rtos', 'Why an RTOS?', 'Vector Division begins porting the reactor arm''s stabilized control loop, the door fix, and Byte''s own telemetry logging onto one shared RTOS-based firmware -- and the very first multi-task build already stalls the control loop for a few milliseconds at a time, for reasons nobody has explained yet.', 'beginner', ARRAY['imani','tomas','byte'], null, null, '{"type":"simulation","simulationId":"why-an-rtos-sim"}'::jsonb, '{"xp":180,"credits":25}'::jsonb, false, 1),
  ('mission-vec-the-rtos-02', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'tasks', 'Tasks', 'A control loop, a door fix, and a telemetry logger are no longer three functions inside one main loop. On an RTOS, each becomes its own task -- an independent thread of execution with its own stack, its own state, and its own priority.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"tasks-sim"}'::jsonb, '{"xp":180,"credits":25}'::jsonb, false, 2),
  ('mission-vec-the-rtos-03', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'the-scheduler', 'The Scheduler', 'Something has to decide which task actually runs at any given instant. That something is the scheduler, and it makes that decision far more often than anyone watching the firmware from the outside would expect.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-the-rtos-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-scheduler-sim"}'::jsonb, '{"xp":190,"credits":25}'::jsonb, false, 3),
  ('mission-vec-the-rtos-04', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'task-priorities', 'Priorities', 'Not every task deserves the same share of the processor. A stalled control loop is a stability risk. A stalled logging write is, at worst, a gap in a chart -- which is exactly why priority exists.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"task-priorities-sim"}'::jsonb, '{"xp":190,"credits":30}'::jsonb, false, 4),
  ('mission-vec-the-rtos-05', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'queues', 'Queues', 'The control loop task and the logging task now run independently, which means they can no longer just share a variable safely. A queue lets one hand data to the other without either one touching the other''s memory directly.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"queues-sim"}'::jsonb, '{"xp":200,"credits":30}'::jsonb, false, 5),
  ('mission-vec-the-rtos-06', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-1', 'semaphores', 'Semaphores', 'Not every signal between tasks carries data. Sometimes a task just needs to know that something happened -- an interrupt fired, a resource became free -- and a semaphore is built for exactly that.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"semaphores-sim"}'::jsonb, '{"xp":200,"credits":30}'::jsonb, false, 6),
  ('mission-vec-the-rtos-07', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'mutexes', 'Mutexes', 'Some resources cannot simply be handed off -- they have to be protected while one task is actively using them. A mutex is how the RTOS enforces that only one task touches a shared resource at a time, and it is about to become the center of the port''s open stall.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"mutexes-sim"}'::jsonb, '{"xp":210,"credits":35}'::jsonb, false, 7),
  ('mission-vec-the-rtos-08', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'event-groups', 'Event Groups', 'Not used by this port''s build, but worth knowing before the day a task needs to wait on more than one condition at once: an event group packs several independent flags into one word a task can wait on in combination.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-the-rtos-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"event-groups-sim"}'::jsonb, '{"xp":210,"credits":35}'::jsonb, false, 8),
  ('mission-vec-the-rtos-09', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'software-timers', 'Software Timers', 'Byte''s logging task needs to flush its buffer to storage on a fixed schedule without dedicating an entire task to watching a clock. A software timer solves exactly that, running a callback on a delay or a period.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"software-timers-sim"}'::jsonb, '{"xp":220,"credits":35}'::jsonb, false, 9),
  ('mission-vec-the-rtos-10', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'task-notifications', 'Task Notifications', 'Sometimes a task needs to hear from exactly one other task or interrupt, with nothing to share and no need for a full queue or semaphore. Every task already carries a built-in notification value for precisely that case.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"task-notifications-sim"}'::jsonb, '{"xp":220,"credits":40}'::jsonb, false, 10),
  ('mission-vec-the-rtos-11', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'deadlocks', 'Deadlocks', 'Before Vector Division diagnoses its own control loop stall, it needs to rule things out correctly -- starting with the specific, narrow failure mode everyone reaches for first and almost never actually has: deadlock.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"deadlocks-sim"}'::jsonb, '{"xp":230,"credits":40}'::jsonb, false, 11),
  ('mission-vec-the-rtos-12', 'world-vec-the-rtos', 'campaign-vec-the-rtos', 'operation-vec-the-rtos-2', 'priority-inversion', 'Priority Inversion', 'The control loop stalled again, for six milliseconds, in exactly the pattern that opened this Act. Diagnose it for real: which mutex, which task is actually stealing the time, and whether this was ever a deadlock at all.', 'boss', ARRAY['imani','tomas','byte'], '{"requiredMissionIds":["mission-vec-the-rtos-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"priority-inversion-sim"}'::jsonb, '{"xp":900,"credits":190,"badgeIds":["priority-inversion"],"skillXp":{"robotics_fundamentals":115}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-the-rtos-01', 1, 'imani', 'Vector Division can stabilize one control loop by hand now. That does not scale to dozens of them, and it never will. Tomas is porting the reactor arm''s loop, the door fix, and Byte''s own telemetry logging onto one shared real-time operating system today.'),
  ('mission-vec-the-rtos-01', 2, 'tomas', 'Tomas Vey. An RTOS does not make code run faster. It makes multiple independent jobs share one processor on a schedule you can actually reason about, instead of one giant loop doing everything in whatever order it happened to be written.'),
  ('mission-vec-the-rtos-01', 3, 'tomas', 'The first multi-task build is already running, and it already has a problem: every so often the control loop stalls for a few milliseconds, always right around the moment the logging task is mid-write.'),
  ('mission-vec-the-rtos-01', 4, 'byte', 'My telemetry logging task is one of the three tasks on that build. I did not expect to be a suspect in my own investigation, but I am not ruling myself out either.'),
  ('mission-vec-the-rtos-01', 5, 'imani', 'Nobody is diagnosing anything yet. Learn what an RTOS actually is first -- tasks, scheduling, priority -- before anyone accuses a piece of code of anything.'),

  ('mission-vec-the-rtos-02', 1, 'tomas', 'A task is the RTOS''s basic unit of work: its own stack, its own saved registers, its own priority, and its own state -- independent of every other task, even though every task shares one processor.'),
  ('mission-vec-the-rtos-02', 2, 'tomas', 'The control loop, the door fix, and Byte''s telemetry logger are no longer three functions called from one main loop. They are three separate tasks, and the scheduler decides which one actually runs at any given instant.'),
  ('mission-vec-the-rtos-02', 3, 'byte', 'Which means my logging task can be paused mid-write and resumed later without me writing a single line of code to make that happen. The RTOS handles it invisibly.'),

  ('mission-vec-the-rtos-03', 1, 'tomas', 'The scheduler is the part of the RTOS that decides which Ready task actually runs right now, and it makes that decision constantly -- on every tick of a hardware timer, and any time a task''s state changes.'),
  ('mission-vec-the-rtos-03', 2, 'tomas', 'A task is always in one of a few states: Ready, meaning it could run; Running, meaning it currently is; or Blocked, meaning it is waiting on something and cannot run yet, no matter how important it is.'),
  ('mission-vec-the-rtos-03', 3, 'tomas', 'Swapping which task is Running is called a context switch -- save the old task''s registers, load the new task''s registers, resume it exactly where it left off. It happens so fast that each task behaves as if it owns the processor alone.'),

  ('mission-vec-the-rtos-04', 1, 'tomas', 'Every task gets a priority number when it is created. When more than one task is Ready at the same time, the scheduler always runs the highest-priority Ready task -- no exceptions for fairness, no turn-taking.'),
  ('mission-vec-the-rtos-04', 2, 'tomas', 'That also means a higher-priority task that becomes Ready will preempt a lower-priority task that is currently Running, mid-instruction if it has to. The control loop task sits at the highest priority in this build for exactly that reason.'),
  ('mission-vec-the-rtos-04', 3, 'byte', 'My logging task sits near the bottom on purpose. Nobody wants a telemetry write to ever delay a control decision -- in theory.'),

  ('mission-vec-the-rtos-05', 1, 'tomas', 'Tasks cannot simply share a plain variable safely -- one task could be mid-write exactly when another reads it. A queue is the RTOS''s answer: a thread-safe, fixed-size buffer that one task can send into and another can receive from, first in, first out.'),
  ('mission-vec-the-rtos-05', 2, 'tomas', 'A task trying to receive from an empty queue can block -- go to sleep cheaply until data arrives -- instead of burning cycles checking over and over. The same is true for a task trying to send into a full queue.'),
  ('mission-vec-the-rtos-05', 3, 'byte', 'My logging task receives its sensor readings through exactly that kind of queue. The control loop task pushes a reading in, and I pull it out on my own schedule, without either of us ever touching the other''s memory directly.'),

  ('mission-vec-the-rtos-06', 1, 'tomas', 'A semaphore does not carry data at all. It carries a count, and it answers one question: how many of a resource, or how many occurrences of an event, are currently available to whoever is waiting.'),
  ('mission-vec-the-rtos-06', 2, 'tomas', 'A binary semaphore is the simplest case -- just zero or one. A task can block waiting to take it, and another task, or an interrupt, can give it to release exactly one waiter. It is how an interrupt hands work off to a task without doing the work itself inside the interrupt.'),
  ('mission-vec-the-rtos-06', 3, 'byte', 'A counting semaphore is the same idea generalized -- start it at however many identical resources exist, and it tracks how many are still free as tasks take it and give it back.'),

  ('mission-vec-the-rtos-07', 1, 'tomas', 'A mutex looks like a binary semaphore, but it means something different: mutual exclusion over one shared resource. Only the task that took a mutex may give it back, and while it is held, every other task is locked out of whatever it protects.'),
  ('mission-vec-the-rtos-07', 2, 'tomas', 'That ownership rule matters. Unlike a plain binary semaphore, a well-built mutex knows exactly which task is holding it -- which is the only reason an RTOS can ever do anything about a low-priority task holding one up.'),
  ('mission-vec-the-rtos-07', 3, 'byte', 'My logging task takes a mutex before it writes to the shared telemetry buffer, and gives it back the instant the write finishes. Anything else touching that buffer waits its turn.'),

  ('mission-vec-the-rtos-08', 1, 'tomas', 'An event group is a set of flags packed into one word, where a task can wait on any combination of them -- wait for this bit and that bit, or wait for either one, and unblock the moment the condition is satisfied.'),
  ('mission-vec-the-rtos-08', 2, 'tomas', 'It solves a narrower problem than a queue or a semaphore: not "here is data" or "here is one occurrence," but "here is a specific combination of conditions becoming true at once." This port does not use one yet, but the shape is worth recognizing before a task ever needs to wait on more than one thing at a time.'),

  ('mission-vec-the-rtos-09', 1, 'tomas', 'A software timer runs a callback function after a delay, or repeatedly on a fixed period, without dedicating an entire task to sleeping and checking a clock.'),
  ('mission-vec-the-rtos-09', 2, 'tomas', 'A one-shot timer fires once and stops. A periodic timer fires again and again on the same interval -- like Byte''s logging task using one to flush its buffer to storage every hundred milliseconds instead of polling a clock itself.'),
  ('mission-vec-the-rtos-09', 3, 'byte', 'The timer callback itself runs inside the RTOS''s own timer service task, not inside my logging task -- which matters, because a slow callback can delay every other timer waiting behind it in that same service task.'),

  ('mission-vec-the-rtos-10', 1, 'tomas', 'Every task already carries one built-in 32-bit notification value as part of its own control block -- no separate queue or semaphore object required. Another task, or an interrupt, can set bits in it or write a value directly, and the target task can block waiting on its own notification.'),
  ('mission-vec-the-rtos-10', 2, 'tomas', 'It is the cheapest way to signal one specific task directly. The tradeoff is exactly that directness -- a notification belongs to one task, so it cannot stand in for a queue or semaphore that several tasks need to share.'),
  ('mission-vec-the-rtos-10', 3, 'byte', 'The door task uses a notification from its own interrupt handler instead of a full semaphore, since only that one task ever needs to hear about it.'),

  ('mission-vec-the-rtos-11', 1, 'tomas', 'A deadlock is a specific kind of stuck: two or more tasks each hold a resource another one needs, waiting in a circle, and none of them can ever proceed. No progress, forever, until something outside the system intervenes.'),
  ('mission-vec-the-rtos-11', 2, 'tomas', 'Four conditions have to hold at once for it to happen: mutual exclusion over the resources, tasks holding one resource while waiting on another, no task willing to give up what it holds, and a circular chain of waiting. Break any one of those and deadlock cannot occur.'),
  ('mission-vec-the-rtos-11', 3, 'byte', 'Which is a very specific claim. A system that is merely slow, or unfair, is not automatically deadlocked -- it still has to actually stop making progress, permanently, for that word to apply.'),

  ('mission-vec-the-rtos-12', 1, 'imani', 'This is not hypothetical anymore. The control loop just stalled again, for six milliseconds, and I want a real diagnosis before it happens on a reactor arm nobody is watching by hand.'),
  ('mission-vec-the-rtos-12', 2, 'tomas', 'Everything from this Act, used for real, on our own stall. Start with what the control loop task was actually blocked on when it stopped executing.'),
  ('mission-vec-the-rtos-12', 3, 'byte', 'Trace confirms it: the control loop task called a take on telemetryMutex and did not return for six milliseconds. It was blocked on a mutex, not a queue, not a notification.'),
  ('mission-vec-the-rtos-12', 4, 'tomas', 'So who was holding it, and why did releasing it take six milliseconds? A logging write should never take that long on its own.'),
  ('mission-vec-the-rtos-12', 5, 'byte', 'It was not the logging task working slowly. Something else kept interrupting it before it could finish and release the lock.'),
  ('mission-vec-the-rtos-12', 6, 'imani', 'Then finish the trace. Name the mutex, name what actually stole its holder''s time, and tell me plainly whether this is the same kind of stuck as a deadlock, or something else entirely.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-the-rtos-01-o1', 'mission-vec-the-rtos-01', 1, 'Frame the port', 'Identify which evidence best explains why Vector Division needs an RTOS now, rather than more hand-tuned control loops.'),
  ('mission-vec-the-rtos-01-o2', 'mission-vec-the-rtos-01', 2, 'Define the payoff', 'Choose the accurate description of what an RTOS actually provides over one large bare-metal loop.'),

  ('mission-vec-the-rtos-02-o1', 'mission-vec-the-rtos-02', 1, 'Define a task', 'Choose the accurate description of what makes an RTOS task different from an ordinary function call.'),
  ('mission-vec-the-rtos-02-o2', 'mission-vec-the-rtos-02', 2, 'Match the port''s three tasks', 'Match each task''s behavior to the task it belongs to.'),

  ('mission-vec-the-rtos-03-o1', 'mission-vec-the-rtos-03', 1, 'Define the scheduler''s job', 'Choose the accurate description of what an RTOS scheduler decides, and how often.'),
  ('mission-vec-the-rtos-03-o2', 'mission-vec-the-rtos-03', 2, 'Order the lifecycle', 'Order what happens after a task''s blocking event clears, from blocked to running.'),

  ('mission-vec-the-rtos-04-o1', 'mission-vec-the-rtos-04', 1, 'Define preemption', 'Choose the accurate description of what happens when a higher-priority task becomes Ready.'),
  ('mission-vec-the-rtos-04-o2', 'mission-vec-the-rtos-04', 2, 'Read the priority table', 'Find the evidence showing the control loop task was deliberately given the highest priority in this build.'),

  ('mission-vec-the-rtos-05-o1', 'mission-vec-the-rtos-05', 1, 'Define a queue', 'Choose the accurate description of a queue''s defining property compared to a plain shared variable.'),
  ('mission-vec-the-rtos-05-o2', 'mission-vec-the-rtos-05', 2, 'Sort the use cases', 'Sort each scenario into a good fit for a queue, or not what a queue is for.'),

  ('mission-vec-the-rtos-06-o1', 'mission-vec-the-rtos-06', 1, 'Tell semaphores from queues', 'Choose the accurate distinction between a binary semaphore and a queue.'),
  ('mission-vec-the-rtos-06-o2', 'mission-vec-the-rtos-06', 2, 'Pick the right tool', 'Given the reactor arm interrupt''s needs, choose the mechanism that fits best.'),

  ('mission-vec-the-rtos-07-o1', 'mission-vec-the-rtos-07', 1, 'Define mutex ownership', 'Choose the accurate description of what specifically distinguishes a mutex from a plain binary semaphore.'),
  ('mission-vec-the-rtos-07-o2', 'mission-vec-the-rtos-07', 2, 'Find the shared mutex', 'Find the evidence showing the control loop task and the logging task depend on the very same mutex.'),

  ('mission-vec-the-rtos-08-o1', 'mission-vec-the-rtos-08', 1, 'Define the event group''s purpose', 'Choose the accurate description of the problem an event group solves that a single semaphore does not.'),

  ('mission-vec-the-rtos-09-o1', 'mission-vec-the-rtos-09', 1, 'Tell one-shot from periodic', 'Choose the accurate distinction between a one-shot and a periodic software timer.'),
  ('mission-vec-the-rtos-09-o2', 'mission-vec-the-rtos-09', 2, 'Find the logging task''s timer', 'Find the evidence identifying what triggers the logging task''s periodic buffer flush.'),

  ('mission-vec-the-rtos-10-o1', 'mission-vec-the-rtos-10', 1, 'Explain the cost advantage', 'Choose the accurate reason a task notification is cheaper than a semaphore for direct signaling.'),
  ('mission-vec-the-rtos-10-o2', 'mission-vec-the-rtos-10', 2, 'Know its limit', 'Choose the accurate reason a task notification cannot replace a mutex shared by three tasks.'),

  ('mission-vec-the-rtos-11-o1', 'mission-vec-the-rtos-11', 1, 'Define deadlock precisely', 'Choose the accurate definition of what specifically makes a stall a deadlock.'),
  ('mission-vec-the-rtos-11-o2', 'mission-vec-the-rtos-11', 2, 'Weigh the evidence', 'Find the evidence that weighs against calling the control loop''s stall a deadlock.'),

  ('mission-vec-the-rtos-12-o1', 'mission-vec-the-rtos-12', 1, 'Identify the blocked mutex', 'Trace exactly which mutex the control loop task is blocked on, and which task holds it.'),
  ('mission-vec-the-rtos-12-o2', 'mission-vec-the-rtos-12', 2, 'Trace the medium-priority interference', 'Explain why the logging task, holding the mutex, needed six milliseconds instead of finishing almost instantly.'),
  ('mission-vec-the-rtos-12-o3', 'mission-vec-the-rtos-12', 3, 'Rule out deadlock', 'Judge whether this stall is a deadlock, or a different failure mode entirely.'),
  ('mission-vec-the-rtos-12-o4', 'mission-vec-the-rtos-12', 4, 'Name the failure: priority inversion', 'Having identified the mutex, traced the medium-priority interference, and ruled out deadlock, name the actual failure mode and explain why it happened.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-the-rtos-01-o1-c1', 'mission-vec-the-rtos-01-o1', 1, 'investigation', 'Which evidence best explains why Vector Division needs an RTOS now, rather than more hand-tuned control loops?', '{"evidence":[{"id":"e1","label":"Act 10 note","detail":"The reactor arm''s control loop now requires constant manual retuning to stay stable, and Vector Division has dozens more control loops planned across other systems"},{"id":"e2","label":"Build log","detail":"The first multi-task firmware build merges the control loop, the door fix, and telemetry logging onto one shared processor"},{"id":"e3","label":"Incident note","detail":"The control loop occasionally stalls for a few milliseconds, correlated with the logging task''s write window"}],"question":"Which evidence best explains why Vector Division needs an RTOS now, rather than more hand-tuned control loops?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-the-rtos-01-o2-c1', 'mission-vec-the-rtos-01-o2', 1, 'multiple_choice', 'Compared to one large bare-metal loop that runs every job in sequence, what does an RTOS specifically provide?', '{"question":"Compared to one large bare-metal loop that runs every job in sequence, what does an RTOS specifically provide?","options":[{"id":"a","text":"Faster CPU clock speeds"},{"id":"b","text":"A scheduler that shares the processor among independent tasks according to priority and timing rules, so each job runs on a predictable schedule instead of whatever order it happened to be written in"},{"id":"c","text":"It removes the need for interrupts entirely"},{"id":"d","text":"It guarantees every task finishes in exactly the same amount of time"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-rtos-02-o1-c1', 'mission-vec-the-rtos-02-o1', 1, 'multiple_choice', 'What makes an RTOS task different from an ordinary function call?', '{"question":"What makes an RTOS task different from an ordinary function call?","options":[{"id":"a","text":"Tasks always run faster than function calls"},{"id":"b","text":"A task has its own stack, its own saved context, and its own priority, and can be paused and resumed by the scheduler independently of every other task"},{"id":"c","text":"Tasks can only ever run one at a time, in the exact order they were written"},{"id":"d","text":"A task is just another name for an interrupt handler"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-02-o2-c1', 'mission-vec-the-rtos-02-o2', 1, 'drag_and_drop', 'Match each task''s behavior to the task it belongs to.', '{"items":[{"id":"i1","text":"Reads the reactor arm''s position and recalculates motor output every two milliseconds"},{"id":"i2","text":"Watches the corridor door''s sensor state and drives the latch when it changes"},{"id":"i3","text":"Buffers sensor readings and writes them to storage every hundred milliseconds"}],"targets":[{"id":"control-loop","label":"Control loop task"},{"id":"door","label":"Door task"},{"id":"telemetry","label":"Telemetry logging task"}]}'::jsonb, '{"correctMapping":{"i1":"control-loop","i2":"door","i3":"telemetry"}}'::jsonb),

  ('mission-vec-the-rtos-03-o1-c1', 'mission-vec-the-rtos-03-o1', 1, 'multiple_choice', 'What does an RTOS scheduler actually decide, and how often?', '{"question":"What does an RTOS scheduler actually decide, and how often?","options":[{"id":"a","text":"Which files to load, once at startup only"},{"id":"b","text":"Which Ready task runs on the processor right now, re-evaluated on every timer tick or relevant task state change"},{"id":"c","text":"Which task crashed, and only when one does"},{"id":"d","text":"It decides once at boot and never revisits that decision"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-03-o2-c1', 'mission-vec-the-rtos-03-o2', 1, 'interactive_diagram', 'Order what happens after a task''s blocking event clears, from blocked to running.', '{"diagramId":"task-lifecycle","hotspots":[{"id":"blocked","label":"Blocked","explanation":"The task is waiting on something -- a queue, a semaphore, a mutex, a timer -- and cannot run no matter its priority."},{"id":"ready","label":"Ready","explanation":"Whatever the task was waiting on has arrived. It could run, but is not guaranteed the processor yet."},{"id":"running","label":"Running","explanation":"The scheduler has picked this task, among all Ready tasks, to actually execute right now."}],"task":"Order what happens after a task''s blocking event clears, from blocked to running."}'::jsonb, '{"correctOrderIds":["blocked","ready","running"]}'::jsonb),

  ('mission-vec-the-rtos-04-o1-c1', 'mission-vec-the-rtos-04-o1', 1, 'multiple_choice', 'In a fixed-priority preemptive RTOS, if a higher-priority task becomes Ready while a lower-priority task is Running, what happens?', '{"question":"In a fixed-priority preemptive RTOS, if a higher-priority task becomes Ready while a lower-priority task is Running, what happens?","options":[{"id":"a","text":"The higher-priority task waits politely until the lower one finishes"},{"id":"b","text":"The scheduler immediately preempts the lower-priority task and runs the higher-priority one"},{"id":"c","text":"Both tasks run simultaneously on one core with no switching"},{"id":"d","text":"Priority only matters when a task is created, never afterward"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-04-o2-c1', 'mission-vec-the-rtos-04-o2', 1, 'investigation', 'Which evidence shows the control loop task was deliberately given the highest priority in this build?', '{"evidence":[{"id":"e1","label":"Priority table","detail":"Control loop task: priority 5 (highest). Door task: priority 3. Logging task: priority 1 (lowest)"},{"id":"e2","label":"Power log","detail":"Board draws a stable current regardless of which task is Running"},{"id":"e3","label":"Build date","detail":"The multi-task firmware was first flashed three days ago"}],"question":"Which evidence shows the control loop task was deliberately given the highest priority in this build?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-the-rtos-05-o1-c1', 'mission-vec-the-rtos-05-o1', 1, 'multiple_choice', 'What is the defining property of an RTOS queue compared to a plain shared variable?', '{"question":"What is the defining property of an RTOS queue compared to a plain shared variable?","options":[{"id":"a","text":"A queue is simply faster to access"},{"id":"b","text":"A queue provides a thread-safe, ordered handoff of data between tasks, letting a task block cheaply instead of racing on shared memory"},{"id":"c","text":"A queue only works between tasks of equal priority"},{"id":"d","text":"A queue permanently stores every message ever sent through it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-05-o2-c1', 'mission-vec-the-rtos-05-o2', 1, 'drag_and_drop', 'Sort each scenario into a good fit for a queue, or not what a queue is for.', '{"items":[{"id":"i1","text":"Passing a stream of sensor readings from the control loop task to the logging task, in order"},{"id":"i2","text":"Waking one task the instant a button interrupt fires, with no data attached"},{"id":"i3","text":"Passing periodic reactor arm setpoint updates from a planning task to the control loop task"},{"id":"i4","text":"Making sure only one task at a time can write to a shared configuration structure"}],"targets":[{"id":"queue","label":"Good fit for a queue"},{"id":"not-queue","label":"Not what a queue is for"}]}'::jsonb, '{"correctMapping":{"i1":"queue","i2":"not-queue","i3":"queue","i4":"not-queue"}}'::jsonb),

  ('mission-vec-the-rtos-06-o1-c1', 'mission-vec-the-rtos-06-o1', 1, 'multiple_choice', 'How does a binary semaphore differ from a queue?', '{"question":"How does a binary semaphore differ from a queue?","options":[{"id":"a","text":"They are identical, just different names for the same object"},{"id":"b","text":"A semaphore only signals availability or occurrence with no data payload, while a queue actually transfers data between tasks"},{"id":"c","text":"A semaphore can only ever be used inside an interrupt handler"},{"id":"d","text":"A queue can only hold one item at a time, a semaphore can hold many"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-06-o2-c1', 'mission-vec-the-rtos-06-o2', 1, 'multiple_choice', 'The reactor arm''s position interrupt needs to wake the control loop task instantly, with no data of its own -- the position value gets read separately once the task wakes. Which mechanism fits best?', '{"question":"The reactor arm''s position interrupt needs to wake the control loop task instantly, with no data of its own -- the position value gets read separately once the task wakes. Which mechanism fits best?","options":[{"id":"a","text":"A queue holding the raw interrupt payload"},{"id":"b","text":"A binary semaphore given by the interrupt handler and taken by the control loop task"},{"id":"c","text":"A software timer"},{"id":"d","text":"A second, identical task"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-rtos-07-o1-c1', 'mission-vec-the-rtos-07-o1', 1, 'multiple_choice', 'What specifically distinguishes a mutex from a plain binary semaphore?', '{"question":"What specifically distinguishes a mutex from a plain binary semaphore?","options":[{"id":"a","text":"A mutex is always faster to take and give"},{"id":"b","text":"A mutex has ownership -- only the task that took it can give it back -- which lets the RTOS reason about exactly who is holding a shared resource"},{"id":"c","text":"A mutex can be given by any task or interrupt, regardless of which task took it"},{"id":"d","text":"A mutex never blocks the task that tries to take it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-07-o2-c1', 'mission-vec-the-rtos-07-o2', 1, 'investigation', 'Which evidence shows the control loop task and the logging task depend on the very same mutex?', '{"evidence":[{"id":"e1","label":"Code note","detail":"The logging task takes telemetryMutex before writing the shared telemetry buffer"},{"id":"e2","label":"Code note","detail":"The control loop task also takes telemetryMutex before reading the most recently logged setpoint"},{"id":"e3","label":"Power log","detail":"Board power draw stayed nominal throughout"}],"question":"Which evidence shows the control loop task and the logging task depend on the very same mutex?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),

  ('mission-vec-the-rtos-08-o1-c1', 'mission-vec-the-rtos-08-o1', 1, 'multiple_choice', 'What problem does an event group solve that a single semaphore does not?', '{"question":"What problem does an event group solve that a single semaphore does not?","options":[{"id":"a","text":"It transfers large amounts of data between tasks"},{"id":"b","text":"It lets a task wait on a specific combination of multiple independent condition flags becoming true, not just one single event"},{"id":"c","text":"It replaces the scheduler entirely"},{"id":"d","text":"It exists only to support logging tasks"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-rtos-09-o1-c1', 'mission-vec-the-rtos-09-o1', 1, 'multiple_choice', 'What is the difference between a one-shot and a periodic software timer?', '{"question":"What is the difference between a one-shot and a periodic software timer?","options":[{"id":"a","text":"A one-shot fires once and stops; a periodic timer fires again on a fixed interval until it is stopped"},{"id":"b","text":"They are identical in every respect"},{"id":"c","text":"A periodic timer can only ever run once per boot"},{"id":"d","text":"A one-shot timer never actually calls its callback"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-the-rtos-09-o2-c1', 'mission-vec-the-rtos-09-o2', 1, 'investigation', 'Which evidence identifies what triggers the logging task''s periodic buffer flush?', '{"evidence":[{"id":"e1","label":"Timer config","detail":"A 100-millisecond periodic timer is bound to the flushTelemetryBuffer callback"},{"id":"e2","label":"Priority table","detail":"The logging task runs at the lowest priority in the build"},{"id":"e3","label":"Power log","detail":"Board power draw stayed nominal throughout"}],"question":"Which evidence identifies what triggers the logging task''s periodic buffer flush?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-the-rtos-10-o1-c1', 'mission-vec-the-rtos-10-o1', 1, 'multiple_choice', 'What makes a task notification cheaper than a semaphore for simple direct signaling?', '{"question":"What makes a task notification cheaper than a semaphore for simple direct signaling?","options":[{"id":"a","text":"It uses less electrical power"},{"id":"b","text":"It is a value already built into the receiving task''s own control block, avoiding the need to create and manage a separate semaphore or queue object"},{"id":"c","text":"It can be shared identically among any number of receiving tasks"},{"id":"d","text":"It replaces the need for task priorities entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-10-o2-c1', 'mission-vec-the-rtos-10-o2', 1, 'multiple_choice', 'Why can a task notification not replace a mutex protecting a resource shared by three tasks?', '{"question":"Why can a task notification not replace a mutex protecting a resource shared by three tasks?","options":[{"id":"a","text":"Notifications are simply too slow"},{"id":"b","text":"A notification is a direct relationship belonging to one receiving task; it has no concept of ownership or mutual exclusion among multiple tasks contending for a resource"},{"id":"c","text":"Notifications can only ever be sent once, ever"},{"id":"d","text":"Notifications require a queue underneath them to function"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-rtos-11-o1-c1', 'mission-vec-the-rtos-11-o1', 1, 'multiple_choice', 'What specifically defines a deadlock, as opposed to a task simply running slowly?', '{"question":"What specifically defines a deadlock, as opposed to a task simply running slowly?","options":[{"id":"a","text":"Any task taking longer to run than expected"},{"id":"b","text":"A circular chain of tasks each holding a resource another needs, with none willing to release, so the whole set makes zero progress, forever"},{"id":"c","text":"Any situation where two tasks use the same mutex"},{"id":"d","text":"A task that never runs at all because its priority is too low"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-11-o2-c1', 'mission-vec-the-rtos-11-o2', 1, 'investigation', 'Which evidence weighs against calling the control loop''s stall a deadlock?', '{"evidence":[{"id":"e1","label":"Trace observation","detail":"The control loop task''s stall is intermittent, lasting a few milliseconds, and resolves on its own every single time with no outside intervention"},{"id":"e2","label":"Ownership trace","detail":"No two tasks in this port are ever shown simultaneously holding a resource the other is waiting on -- there is no circular chain"},{"id":"e3","label":"Power log","detail":"Reactor temperature stayed nominal throughout every stall"}],"question":"Which evidence weighs against calling the control loop''s stall a deadlock?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),

  ('mission-vec-the-rtos-12-o1-c1', 'mission-vec-the-rtos-12-o1', 1, 'investigation', 'Which two pieces of evidence together identify the exact mutex the control loop task is blocked on, and who holds it?', '{"evidence":[{"id":"e1","label":"Scheduler trace","detail":"Control loop task (priority 5) entered the Blocked state at t=0ms inside a take call on telemetryMutex"},{"id":"e2","label":"Mutex ownership log","detail":"telemetryMutex was taken by the logging task (priority 1) at t=-1ms and had not yet been given back"},{"id":"e3","label":"Unrelated trace","detail":"Door task (priority 3) sat idle the entire time, waiting on its own notification, uninvolved in this stall"}],"question":"Which two pieces of evidence together identify the exact mutex the control loop task is blocked on, and who holds it?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-vec-the-rtos-12-o2-c1', 'mission-vec-the-rtos-12-o2', 1, 'investigation', 'Which evidence explains why the low-priority logging task took six milliseconds to release a mutex that should only take microseconds?', '{"evidence":[{"id":"e1","label":"Scheduler trace","detail":"Between t=0ms and t=6ms, a medium-priority sensor-polling task (priority 3) ran to completion five separate times, each time preempting the logging task before it reached the mutex give call"},{"id":"e2","label":"Code note","detail":"The logging task''s critical section, mutex held, is only two lines of code and normally takes microseconds, not milliseconds"},{"id":"e3","label":"Unrelated trace","detail":"Reactor temperature stayed nominal throughout the entire six-millisecond stall"}],"question":"Which evidence explains why the low-priority logging task took six milliseconds to release a mutex that should only take microseconds?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-vec-the-rtos-12-o3-c1', 'mission-vec-the-rtos-12-o3', 1, 'multiple_choice', 'The control loop task eventually resumed every single time this happened, without any outside intervention. Does that rule out deadlock?', '{"question":"The control loop task eventually resumed every single time this happened, without any outside intervention. Does that rule out deadlock?","options":[{"id":"a","text":"No -- deadlocks always eventually resolve on their own given enough time"},{"id":"b","text":"Yes -- deadlock requires a circular wait where no task ever makes progress; this system made progress every time, just far later than the control loop task''s priority should ever allow, which is a different failure mode entirely"},{"id":"c","text":"It cannot be determined without more information"},{"id":"d","text":"Yes, but only because the door task happened to be involved"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-rtos-12-o4-c1', 'mission-vec-the-rtos-12-o4', 1, 'boss_encounter', 'Having identified the mutex, traced the medium-priority interference, and ruled out deadlock, name the actual failure mode and explain why it happened.', '{"stages":[{"objectiveRef":"mission-vec-the-rtos-12-o1","label":"Identify the blocked mutex"},{"objectiveRef":"mission-vec-the-rtos-12-o2","label":"Trace the medium-priority interference"},{"objectiveRef":"mission-vec-the-rtos-12-o3","label":"Rule out deadlock"}],"task":"State the diagnosis in one sentence: the low-priority logging task holds telemetryMutex, but an unrelated medium-priority sensor-polling task keeps preempting it before it can finish and release the lock, so the high-priority control loop task waits far longer than its own priority should ever allow -- not a deadlock, since the system does eventually make progress, but priority inversion. Multiple tasks now run reliably, in the right order, under real scheduling guarantees -- which raises the next question: what any of them can actually remember once the power cuts out."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-the-rtos-12-o1","mission-vec-the-rtos-12-o2","mission-vec-the-rtos-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-the-rtos-01-o1-c1', 'orientation', 'Ask which evidence is about the underlying scaling problem, not the specific bug that showed up once multitasking started.', 10, 1),
  ('mission-vec-the-rtos-01-o1-c1', 'solution', 'e1: dozens of planned control loops, each needing constant hand-tuning, is the scaling problem an RTOS solves. e3 is a symptom of already having one, not the reason to build one.', 20, 2),
  ('mission-vec-the-rtos-01-o2-c1', 'orientation', 'Rule out anything about raw speed -- an RTOS is about order and sharing, not clock rate.', 10, 1),
  ('mission-vec-the-rtos-01-o2-c1', 'solution', 'An RTOS provides a scheduler sharing the processor among independent tasks by priority and timing, giving a predictable schedule instead of one big loop''s fixed order.', 20, 2),

  ('mission-vec-the-rtos-02-o1-c1', 'orientation', 'A function call has no memory of its own state between calls. Ask what a task keeps that a function does not.', 10, 1),
  ('mission-vec-the-rtos-02-o1-c1', 'solution', 'A task owns its own stack, saved context, and priority, letting the scheduler pause and resume it independently of everything else.', 20, 2),
  ('mission-vec-the-rtos-02-o2-c1', 'orientation', 'Match the physical thing each description measures or drives to the task that owns it.', 10, 1),
  ('mission-vec-the-rtos-02-o2-c1', 'solution', 'i1 (position, motor output) is the control loop task. i2 (door sensor, latch) is the door task. i3 (buffering, storage writes) is the telemetry logging task.', 20, 2),

  ('mission-vec-the-rtos-03-o1-c1', 'orientation', 'Think about how often the world changes for an embedded system -- once at boot, or constantly.', 10, 1),
  ('mission-vec-the-rtos-03-o1-c1', 'solution', 'The scheduler decides which Ready task runs right now, and re-evaluates that decision on every timer tick or relevant state change, not just once.', 20, 2),
  ('mission-vec-the-rtos-03-o2-c1', 'orientation', 'A task cannot run again the instant it stops waiting -- something still has to decide it should be the one running.', 10, 1),
  ('mission-vec-the-rtos-03-o2-c1', 'solution', 'Blocked, then Ready once the wait clears, then Running once the scheduler actually picks it.', 20, 2),

  ('mission-vec-the-rtos-04-o1-c1', 'orientation', 'Fixed-priority preemptive means exactly what it says -- priority always wins, immediately.', 10, 1),
  ('mission-vec-the-rtos-04-o1-c1', 'solution', 'The scheduler immediately preempts the lower-priority task and runs the higher-priority one the moment it becomes Ready.', 20, 2),
  ('mission-vec-the-rtos-04-o2-c1', 'orientation', 'Look for a table of numbers, not a log of behavior over time.', 10, 1),
  ('mission-vec-the-rtos-04-o2-c1', 'solution', 'e1, the priority table, shows the control loop task assigned priority 5, the highest in the build.', 20, 2),

  ('mission-vec-the-rtos-05-o1-c1', 'orientation', 'A plain shared variable has no protection built in. Ask what a queue adds on top of that.', 10, 1),
  ('mission-vec-the-rtos-05-o1-c1', 'solution', 'A queue provides a thread-safe, ordered handoff between tasks, letting a task block cheaply instead of racing unsafely on shared memory.', 20, 2),
  ('mission-vec-the-rtos-05-o2-c1', 'orientation', 'Ask whether actual data needs to travel with the signal, or whether the signal alone is the whole message.', 10, 1),
  ('mission-vec-the-rtos-05-o2-c1', 'solution', 'i1 and i3 carry real data between tasks -- queues. i2 and i4 carry no data or need exclusive access rather than a handoff -- not what a queue is for.', 20, 2),

  ('mission-vec-the-rtos-06-o1-c1', 'orientation', 'Ask whether either mechanism actually carries a payload.', 10, 1),
  ('mission-vec-the-rtos-06-o1-c1', 'solution', 'A semaphore only signals availability or occurrence with no payload; a queue actually transfers data between tasks.', 20, 2),
  ('mission-vec-the-rtos-06-o2-c1', 'orientation', 'The position value is read separately once awake -- the wake-up itself carries no data of its own.', 10, 1),
  ('mission-vec-the-rtos-06-o2-c1', 'solution', 'A binary semaphore given by the interrupt and taken by the control loop task fits exactly -- signaling with no payload.', 20, 2),

  ('mission-vec-the-rtos-07-o1-c1', 'orientation', 'A plain binary semaphore can be given by anyone. Ask whether a mutex allows that.', 10, 1),
  ('mission-vec-the-rtos-07-o1-c1', 'concept', 'Only the task that took a mutex is allowed to give it back -- that rule is what gives a mutex the concept of ownership a semaphore lacks.', 20, 2),
  ('mission-vec-the-rtos-07-o1-c1', 'solution', 'A mutex has ownership: only the task that took it can give it back, which is the only reason the RTOS can ever reason about which task is holding up a shared resource.', 30, 3),
  ('mission-vec-the-rtos-07-o2-c1', 'orientation', 'Look for two separate code notes, each mentioning the same mutex by name.', 10, 1),
  ('mission-vec-the-rtos-07-o2-c1', 'concept', 'Both tasks calling the same take function on the same mutex object means they are contending for the exact same resource.', 20, 2),
  ('mission-vec-the-rtos-07-o2-c1', 'solution', 'e1 and e2 together show both the logging task and the control loop task take telemetryMutex -- they depend on the very same lock.', 30, 3),

  ('mission-vec-the-rtos-08-o1-c1', 'orientation', 'A single semaphore only ever tracks one count or one flag. Ask what happens when a task needs more than one condition at once.', 10, 1),
  ('mission-vec-the-rtos-08-o1-c1', 'solution', 'An event group lets a task wait on a specific combination of several independent flags becoming true together, not just a single event.', 20, 2),

  ('mission-vec-the-rtos-09-o1-c1', 'orientation', 'Ask whether the timer stops after its callback runs once, or keeps going.', 10, 1),
  ('mission-vec-the-rtos-09-o1-c1', 'solution', 'A one-shot fires once and stops. A periodic timer fires again and again on a fixed interval until something stops it.', 20, 2),
  ('mission-vec-the-rtos-09-o2-c1', 'orientation', 'Look for a config entry naming both an interval and a callback function.', 10, 1),
  ('mission-vec-the-rtos-09-o2-c1', 'solution', 'e1: a 100-millisecond periodic timer bound to flushTelemetryBuffer is exactly what triggers the periodic flush.', 20, 2),

  ('mission-vec-the-rtos-10-o1-c1', 'orientation', 'Ask what has to be created and managed for a semaphore that a notification does not need at all.', 10, 1),
  ('mission-vec-the-rtos-10-o1-c1', 'solution', 'A notification is a value already built into the receiving task''s own control block, so nothing separate has to be created or managed.', 20, 2),
  ('mission-vec-the-rtos-10-o2-c1', 'orientation', 'Ask how many tasks a notification actually belongs to, versus how many tasks were contending for the mutex.', 10, 1),
  ('mission-vec-the-rtos-10-o2-c1', 'solution', 'A notification is a direct relationship owned by one receiving task -- it has no concept of ownership or exclusion among multiple contending tasks the way a mutex does.', 20, 2),

  ('mission-vec-the-rtos-11-o1-c1', 'orientation', 'Slow is not the same claim as stuck forever. Ask what has to be true for a stall to never end on its own.', 10, 1),
  ('mission-vec-the-rtos-11-o1-c1', 'concept', 'All four conditions -- mutual exclusion, hold-and-wait, no forced release, and a circular chain -- have to hold simultaneously for a deadlock to occur.', 20, 2),
  ('mission-vec-the-rtos-11-o1-c1', 'solution', 'A deadlock is a circular chain of tasks each holding a resource another needs, with none willing to release, so the whole set makes zero progress, forever.', 30, 3),
  ('mission-vec-the-rtos-11-o2-c1', 'orientation', 'A deadlock, by definition, never resolves on its own. Ask what the trace actually shows happening after the stall.', 10, 1),
  ('mission-vec-the-rtos-11-o2-c1', 'solution', 'e1 and e2 together weigh against deadlock: the stall resolves on its own every time, and no circular holding pattern is ever observed.', 20, 2),

  ('mission-vec-the-rtos-12-o1-c1', 'orientation', 'Look for the trace showing exactly what call the control loop task was inside of when it stopped executing, and a separate log showing who else has that same object.', 10, 1),
  ('mission-vec-the-rtos-12-o1-c1', 'concept', 'A task being Blocked inside a take call on a specific mutex, plus a log showing another task already holding that exact mutex, together pin down both halves of the answer.', 20, 2),
  ('mission-vec-the-rtos-12-o1-c1', 'solution', 'e1 shows the control loop task blocked inside a take on telemetryMutex; e2 shows the logging task already holding that exact mutex -- together they identify the mutex and its holder.', 30, 3),
  ('mission-vec-the-rtos-12-o2-c1', 'orientation', 'The logging task''s own critical section is short. Ask what kept happening in between, over and over, before it could reach the line that releases the lock.', 10, 1),
  ('mission-vec-the-rtos-12-o2-c1', 'concept', 'A task repeatedly preempting the mutex holder, five times in a row, before the holder ever reaches its release call, is exactly what stretches a microsecond-long critical section into milliseconds.', 20, 2),
  ('mission-vec-the-rtos-12-o2-c1', 'solution', 'e1 shows a medium-priority task preempting the logging task five times in six milliseconds; e2 confirms the logging task''s own critical section should only take microseconds -- together they explain the delay.', 30, 3),
  ('mission-vec-the-rtos-12-o3-c1', 'orientation', 'Deadlock has one property above all others: it never resolves without outside help. Check whether that property actually holds here.', 10, 1),
  ('mission-vec-the-rtos-12-o3-c1', 'concept', 'Making progress, however late, is the one thing deadlock structurally cannot do -- so a stall that always eventually clears on its own cannot be a deadlock by definition.', 20, 2),
  ('mission-vec-the-rtos-12-o3-c1', 'solution', 'The system made progress every single time, just far later than the control loop task''s priority should have allowed -- that rules out deadlock and points to priority inversion instead.', 30, 3),
  ('mission-vec-the-rtos-12-o4-c1', 'orientation', 'Combine the three answers into one causal chain: who holds the lock, what is stealing their time, and what that pattern is actually called.', 15, 1),
  ('mission-vec-the-rtos-12-o4-c1', 'concept', 'A low-priority holder, starved by an unrelated medium-priority task, delaying a high-priority waiter far beyond what its own priority should allow, is the textbook shape of priority inversion -- not deadlock, since progress still happens.', 25, 2),
  ('mission-vec-the-rtos-12-o4-c1', 'solution', 'The logging task holds telemetryMutex; a medium-priority sensor-polling task keeps preempting it before it can release the lock; the control loop task waits far longer than its priority should ever allow. That is priority inversion, not deadlock, because the system always eventually makes progress -- and it sets up the next question: what any of these tasks can actually remember once the power cuts out.', 35, 3);
