-- AI/ML pathway ("Cipher Division") Act 9 -- "Trees of Decision" content.
-- Arc II, "Machines That Predict" (act-ai-2). Continues the emergency
-- classifier project from Act 8: the logistic regression baseline can only
-- draw one straight boundary, so this Act upgrades to decision trees and
-- tree ensembles (random forests, gradient boosting) that can capture
-- messier, branching patterns -- then teaches honest model comparison.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other pathway.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-trees-of-decision', 'world-ai-trees-of-decision', 'trees-of-decision', '9A - Trees of Decision', 'Move past a single straight-line boundary and build tree-based models that can capture messier, branching patterns -- then learn to tell a genuinely better model from one that just looks better on a convenient number.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-trees-of-decision-1', 'campaign-ai-trees-of-decision', 'one-good-question', 'One Good Question', 'How a single decision tree asks questions, measures impurity and decides where to split -- and why letting it grow unchecked backfires.', 1),
  ('operation-ai-trees-of-decision-2', 'campaign-ai-trees-of-decision', 'strength-in-numbers', 'Strength in Numbers', 'Ensembles that trade one tree for many: bagging, random forests, gradient boosting, and the honest comparison that decides which one actually deserves production.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-trees-of-decision-01', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'decision-trees', 'Decision Trees', 'A straight-line boundary keeps missing borderline cases. Byte proposes a model that decides with a sequence of yes/no questions instead of one boundary.', 'beginner', ARRAY['maya','byte'], null, null, '{"type":"simulation","simulationId":"decision-tree-basics-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 1),
  ('mission-ai-trees-of-decision-02', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'splits', 'Splits', 'Every branch in a tree starts with a split -- one feature, one threshold, one question the tree asks to divide the data.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"tree-splits-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 2),
  ('mission-ai-trees-of-decision-03', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'impurity', 'Impurity', 'Impurity turns "how mixed are the classes here" into a number the tree can actually compare across candidate splits.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"impurity-measures-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 3),
  ('mission-ai-trees-of-decision-04', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'tree-depth', 'Tree Depth', 'Depth is how many questions a prediction passes through before it reaches an answer -- and how much rule the tree is allowed to carve out.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"tree-depth-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 4),
  ('mission-ai-trees-of-decision-05', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'overfitting-trees', 'Overfitting Trees', 'A tree grown without limits scores almost perfectly on its own training data, then falls apart on anything new.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"overfitting-trees-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 5),
  ('mission-ai-trees-of-decision-06', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-1', 'random-forest', 'Random Forest', 'Do not trust one tree. Grow many, on randomized data, and let them vote.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"random-forest-sim"}'::jsonb, '{"xp":180,"credits":35}'::jsonb, false, 6),
  ('mission-ai-trees-of-decision-07', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'bagging', 'Bagging', 'Bootstrap aggregating: the exact mechanism behind a random forest''s randomized data and combined vote.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"bagging-sim"}'::jsonb, '{"xp":180,"credits":40}'::jsonb, false, 7),
  ('mission-ai-trees-of-decision-08', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'feature-importance', 'Feature Importance', 'A trained forest can say which features it leaned on -- but that number needs to be read carefully, not worshipped.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"feature-importance-sim"}'::jsonb, '{"xp":190,"credits":40}'::jsonb, false, 8),
  ('mission-ai-trees-of-decision-09', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'gradient-boosting', 'Gradient Boosting', 'Instead of many independent trees, boosting builds one tree at a time, each one aimed at the ensemble''s current mistakes.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"gradient-boosting-sim"}'::jsonb, '{"xp":190,"credits":40}'::jsonb, false, 9),
  ('mission-ai-trees-of-decision-10', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'xgboost-concepts', 'XGBoost Concepts', 'The production version of gradient boosting adds regularization, shrinkage and early stopping to keep the same idea from overfitting.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"xgboost-concepts-sim"}'::jsonb, '{"xp":200,"credits":40}'::jsonb, false, 10),
  ('mission-ai-trees-of-decision-11', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'model-comparison', 'Model Comparison', 'Four candidate models, one report. Some of it is evidence. Some of it is a number that will not survive scrutiny.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"model-comparison-sim"}'::jsonb, '{"xp":200,"credits":45}'::jsonb, false, 11),
  ('mission-ai-trees-of-decision-12', 'world-ai-trees-of-decision', 'campaign-ai-trees-of-decision', 'operation-ai-trees-of-decision-2', 'forest-of-decisions', 'Forest of Decisions', 'One overfit tree, one random forest, one boosted ensemble. Judge all three on evidence, then tell Cipher Division which one deserves production.', 'boss', ARRAY['maya','byte'], '{"requiredMissionIds":["mission-ai-trees-of-decision-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"forest-of-decisions-boss-sim"}'::jsonb, '{"xp":620,"credits":135,"badgeIds":["forest-of-decisions"],"skillXp":{"classical_ml":50,"ai_ml_fundamentals":15}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-trees-of-decision-01', 1, 'maya', 'The logistic regression classifier is live and it is a solid baseline. But look at last night''s borderline cases -- it keeps missing the same handful of spikes.'),
  ('mission-ai-trees-of-decision-01', 2, 'byte', 'Every one of those misses sits close to the decision boundary on more than one signal at once. Logistic regression can only draw a straight line -- or a flat plane once you add more features. Real activity does not sort that cleanly.'),
  ('mission-ai-trees-of-decision-01', 3, 'byte', 'So we try a different model family: a decision tree. Instead of one straight boundary, it asks a sequence of yes/no questions and lets each answer send the data down a different branch.'),
  ('mission-ai-trees-of-decision-01', 4, 'maya', 'If a chain of simple questions can catch what one straight line cannot, I want to see it work. Show me how a tree actually decides.'),

  ('mission-ai-trees-of-decision-02', 1, 'byte', 'Every branch point in a tree is called a split. It picks one feature and one threshold, like "signal_spike > 40?", and sends every example left or right depending on the answer.'),
  ('mission-ai-trees-of-decision-02', 2, 'byte', 'A good split makes the two resulting groups purer than before -- each group leans more toward one class than the mixed group did. A bad split barely changes anything.'),
  ('mission-ai-trees-of-decision-02', 3, 'byte', 'The tree tries many candidate splits at each node and keeps whichever one separates the classes best.'),

  ('mission-ai-trees-of-decision-03', 1, 'byte', 'To compare splits the tree needs a number, not a feeling. That number is impurity -- how mixed the classes are inside a node.'),
  ('mission-ai-trees-of-decision-03', 2, 'byte', 'Two common measures: Gini impurity and entropy. Both hit zero when a node is perfectly pure, one class only, and both are highest when a node is a fifty-fifty mix.'),
  ('mission-ai-trees-of-decision-03', 3, 'byte', 'The tree scores every candidate split by how much it reduces impurity compared to the parent node, and picks the split with the biggest drop.'),

  ('mission-ai-trees-of-decision-04', 1, 'byte', 'Depth is just how many splits a data point passes through from the root before it reaches a leaf and gets a final answer.'),
  ('mission-ai-trees-of-decision-04', 2, 'byte', 'A depth-1 tree, a "stump," can only ask one question total -- it will miss most of the nuance. Let the tree grow deep enough and it can carve out a rule for almost any combination of signals.'),
  ('mission-ai-trees-of-decision-04', 3, 'byte', 'That flexibility is exactly what a straight-line model like logistic regression could not offer us. It is also exactly what we need to watch closely next.'),

  ('mission-ai-trees-of-decision-05', 1, 'byte', 'I grew a tree with no depth limit on last quarter''s emergency data. Training accuracy: 99.8%. It is basically perfect.'),
  ('mission-ai-trees-of-decision-05', 2, 'byte', 'Then I ran it on this quarter''s incidents, data it never saw during training. Accuracy dropped to 61%, barely better than guessing on the harder cases.'),
  ('mission-ai-trees-of-decision-05', 3, 'byte', 'That gap is the signature of an overfit tree. Grown deep enough, it stops learning general rules and starts memorizing individual training examples, including their noise.'),

  ('mission-ai-trees-of-decision-06', 1, 'byte', 'One deep tree memorizes. So do not trust one tree -- grow many, and let them vote.'),
  ('mission-ai-trees-of-decision-06', 2, 'byte', 'A random forest trains a whole ensemble of decision trees, each one seeing a randomly resampled version of the data, and averages or majority-votes their predictions.'),
  ('mission-ai-trees-of-decision-06', 3, 'byte', 'Individually, some of those trees will still overfit their own random slice of data. But their mistakes tend to point in different directions, and averaging cancels a lot of that out.'),

  ('mission-ai-trees-of-decision-07', 1, 'byte', 'The randomized-data part of a random forest has a name: bagging, short for bootstrap aggregating.'),
  ('mission-ai-trees-of-decision-07', 2, 'byte', 'Bootstrap sampling means drawing a new training set the same size as the original, but with replacement -- some examples show up twice, others get left out entirely, for every single tree.'),
  ('mission-ai-trees-of-decision-07', 3, 'byte', 'Each tree only ever sees its own bootstrap sample, so each tree makes different mistakes. Aggregating -- voting or averaging -- is what turns those different mistakes into a more stable answer than any one tree gives alone.'),

  ('mission-ai-trees-of-decision-08', 1, 'byte', 'Once a forest is trained, it can tell you which features it actually leaned on. That is feature importance -- roughly, how much each feature reduced impurity, averaged across every split in every tree.'),
  ('mission-ai-trees-of-decision-08', 2, 'byte', 'It is useful for explaining a model, but it is not proof of cause and effect, and it gets distorted when two features carry almost the same information -- the importance gets split between them instead of credited to either one clearly.'),

  ('mission-ai-trees-of-decision-09', 1, 'byte', 'Bagging trains many trees independently and averages them. Gradient boosting does the opposite: it builds trees one at a time, in sequence, and each new tree is trained specifically to correct the errors the current ensemble is still making.'),
  ('mission-ai-trees-of-decision-09', 2, 'byte', 'The first tree is usually weak on its own. Each following tree looks at what is still being gotten wrong -- the residual error -- and focuses on fixing exactly that, added in with a small weight called the learning rate.'),
  ('mission-ai-trees-of-decision-09', 3, 'byte', 'Done carefully, boosting often reaches higher accuracy than bagging on the same data. Done carelessly -- too many trees, too high a learning rate -- it can overfit just as badly as one unrestrained tree did.'),

  ('mission-ai-trees-of-decision-10', 1, 'byte', 'XGBoost is not a different idea from gradient boosting -- it is a heavily optimized, regularized implementation of it, and it is the version most production systems actually run.'),
  ('mission-ai-trees-of-decision-10', 2, 'byte', 'On top of the boosting loop, it adds explicit regularization terms that penalize overly complex trees, a learning rate to shrink each tree''s contribution, and early stopping that halts training once held-out performance stops improving.'),
  ('mission-ai-trees-of-decision-10', 3, 'byte', 'None of that changes the core idea. It changes how safely you can push boosting hard without it running straight into the same overfitting trap as our first tree.'),

  ('mission-ai-trees-of-decision-11', 1, 'byte', 'We now have four candidate models for the same emergency classifier: the original logistic regression, a single decision tree, a random forest, and a gradient-boosted ensemble.'),
  ('mission-ai-trees-of-decision-11', 2, 'byte', 'Comparing them fairly means scoring all four on the same held-out data, with the same metrics, not just picking whichever one posts the best number on a slide.'),
  ('mission-ai-trees-of-decision-11', 3, 'byte', 'I pulled a comparison report. Some of it is solid evidence. Some of it is the kind of thing Maya would tear apart in about four seconds.'),

  ('mission-ai-trees-of-decision-12', 1, 'maya', 'Four models, one decision. Before Cipher Division puts anything into production, I want to see the evidence, not the headline.'),
  ('mission-ai-trees-of-decision-12', 2, 'byte', 'Agreed. I have three pieces of the record pulled up: the single tree''s overfitting signature, the random forest''s bagging evidence, and the boosted ensemble''s tradeoffs. Walk through all three before you call it.'),
  ('mission-ai-trees-of-decision-12', 3, 'maya', 'And do not let one flashy number decide this for you. A model that looks perfect on the data it was trained on has told you nothing about tomorrow''s incidents.'),
  ('mission-ai-trees-of-decision-12', 4, 'byte', 'Once you have judged all three, Cipher Division needs your actual recommendation -- which approach, and why, given both accuracy and how explainable it needs to stay for whoever is on call.'),
  ('mission-ai-trees-of-decision-12', 5, 'maya', 'Show me you understand the tradeoff, not just the winner. Because the moment this is settled, we are done picking single models one at a time -- next we run every classical approach Cipher Division has, including a few we have not tried yet, head to head, decided by proper cross-validation instead of one lucky split.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-trees-of-decision-01-o1', 'mission-ai-trees-of-decision-01', 1, 'Confirm the pivot', 'Confirm you are ready to move from a straight-line classifier to tree-based models.'),
  ('mission-ai-trees-of-decision-01-o2', 'mission-ai-trees-of-decision-01', 2, 'Define the tree', 'Identify how a decision tree actually produces a prediction.'),

  ('mission-ai-trees-of-decision-02-o1', 'mission-ai-trees-of-decision-02', 1, 'Name the split', 'Identify what a split actually does inside a decision tree.'),
  ('mission-ai-trees-of-decision-02-o2', 'mission-ai-trees-of-decision-02', 2, 'Pick the best split', 'Choose the candidate split that separates the classes most cleanly.'),

  ('mission-ai-trees-of-decision-03-o1', 'mission-ai-trees-of-decision-03', 1, 'Define impurity', 'Identify what impurity measures at a tree node.'),
  ('mission-ai-trees-of-decision-03-o2', 'mission-ai-trees-of-decision-03', 2, 'Sort by impurity', 'Match each node description to its impurity level.'),

  ('mission-ai-trees-of-decision-04-o1', 'mission-ai-trees-of-decision-04', 1, 'Know what depth controls', 'Identify what increasing a tree''s maximum depth actually changes.'),
  ('mission-ai-trees-of-decision-04-o2', 'mission-ai-trees-of-decision-04', 2, 'Trace a prediction', 'Order the steps a single example passes through to reach a prediction.'),

  ('mission-ai-trees-of-decision-05-o1', 'mission-ai-trees-of-decision-05', 1, 'Diagnose the overfit tree', 'Find the evidence proving the unlimited-depth tree overfit its training data.'),
  ('mission-ai-trees-of-decision-05-o2', 'mission-ai-trees-of-decision-05', 2, 'Name the fix', 'Identify the most direct fix for an overfit decision tree.'),

  ('mission-ai-trees-of-decision-06-o1', 'mission-ai-trees-of-decision-06', 1, 'Define the forest', 'Identify what a random forest actually is.'),
  ('mission-ai-trees-of-decision-06-o2', 'mission-ai-trees-of-decision-06', 2, 'Trace the build', 'Order the steps of building and using a random forest.'),

  ('mission-ai-trees-of-decision-07-o1', 'mission-ai-trees-of-decision-07', 1, 'Define bootstrap sampling', 'Identify what bootstrap sampling actually does.'),
  ('mission-ai-trees-of-decision-07-o2', 'mission-ai-trees-of-decision-07', 2, 'Prove aggregation helps', 'Find the evidence that aggregating many bootstrap-trained trees beats any single tree.'),

  ('mission-ai-trees-of-decision-08-o1', 'mission-ai-trees-of-decision-08', 1, 'Define feature importance', 'Identify what a feature importance score actually tells you.'),
  ('mission-ai-trees-of-decision-08-o2', 'mission-ai-trees-of-decision-08', 2, 'Read the importance report', 'Judge what the report''s correlated features should make you cautious about.'),

  ('mission-ai-trees-of-decision-09-o1', 'mission-ai-trees-of-decision-09', 1, 'Define gradient boosting', 'Identify how gradient boosting actually builds its ensemble.'),
  ('mission-ai-trees-of-decision-09-o2', 'mission-ai-trees-of-decision-09', 2, 'Sort bagging vs boosting', 'Sort each characteristic into bagging or boosting.'),

  ('mission-ai-trees-of-decision-10-o1', 'mission-ai-trees-of-decision-10', 1, 'Know what XGBoost adds', 'Identify what XGBoost adds on top of plain gradient boosting.'),
  ('mission-ai-trees-of-decision-10-o2', 'mission-ai-trees-of-decision-10', 2, 'Match the safeguards', 'Match each XGBoost concept to its definition.'),

  ('mission-ai-trees-of-decision-11-o1', 'mission-ai-trees-of-decision-11', 1, 'Expose the misleading number', 'Find the evidence that exposes the comparison report''s misleading headline.'),
  ('mission-ai-trees-of-decision-11-o2', 'mission-ai-trees-of-decision-11', 2, 'Define a fair comparison', 'Identify what a fair comparison between candidate models actually requires.'),

  ('mission-ai-trees-of-decision-12-o1', 'mission-ai-trees-of-decision-12', 1, 'Diagnose the single tree', 'Find the evidence proving the unlimited-depth tree overfit.'),
  ('mission-ai-trees-of-decision-12-o2', 'mission-ai-trees-of-decision-12', 2, 'Judge the random forest', 'Find the evidence that bagging measurably improved on any single tree.'),
  ('mission-ai-trees-of-decision-12-o3', 'mission-ai-trees-of-decision-12', 3, 'Judge the boosted ensemble', 'Identify the real tradeoff to weigh against the boosted ensemble''s top accuracy.'),
  ('mission-ai-trees-of-decision-12-o4', 'mission-ai-trees-of-decision-12', 4, 'Recommend the model', 'Having judged all three, state Cipher Division''s recommendation for production.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-trees-of-decision-01-o1-c1', 'mission-ai-trees-of-decision-01-o1', 1, 'story_dialogue', 'Confirm you are ready to continue.', '{"lines":[{"characterId":"maya","text":"Before we build anything -- are you ready to move past a straight-line model?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),
  ('mission-ai-trees-of-decision-01-o2-c1', 'mission-ai-trees-of-decision-01-o2', 1, 'multiple_choice', 'A decision tree makes a prediction by...', '{"question":"A decision tree makes a prediction by...","options":[{"id":"a","text":"Fitting one straight-line boundary through the data"},{"id":"b","text":"Asking a sequence of yes/no questions about the data, moving down branches to a final answer at a leaf"},{"id":"c","text":"Averaging every training example into one output"},{"id":"d","text":"Storing a lookup table of exact matches only"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-trees-of-decision-02-o1-c1', 'mission-ai-trees-of-decision-02-o1', 1, 'multiple_choice', 'A split in a decision tree is best described as...', '{"question":"A split in a decision tree is best described as...","options":[{"id":"a","text":"A rule on one feature and one threshold that divides the examples at a node into two branches"},{"id":"b","text":"A random shuffle of the entire dataset"},{"id":"c","text":"The final prediction stored at a leaf"},{"id":"d","text":"A measure of the whole model''s overall accuracy"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-trees-of-decision-02-o2-c1', 'mission-ai-trees-of-decision-02-o2', 1, 'investigation', 'Which candidate split best separates emergency from routine activity?', '{"evidence":[{"id":"e1","label":"Split A: signal_spike > 40","detail":"Left branch: 90% emergency, 10% routine. Right branch: 5% emergency, 95% routine."},{"id":"e2","label":"Split B: day_of_week == Monday","detail":"Left branch: 52% emergency, 48% routine. Right branch: 49% emergency, 51% routine."},{"id":"e3","label":"Split C: server_id is even","detail":"Left branch: 51% emergency, 49% routine. Right branch: 50% emergency, 50% routine."}],"question":"Which candidate split best separates emergency from routine activity?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-trees-of-decision-03-o1-c1', 'mission-ai-trees-of-decision-03-o1', 1, 'multiple_choice', 'Impurity at a tree node measures...', '{"question":"Impurity at a tree node measures...","options":[{"id":"a","text":"How many training examples reach that node"},{"id":"b","text":"How mixed the classes are among the examples at that node"},{"id":"c","text":"How deep the node sits in the tree"},{"id":"d","text":"How fast the tree finished training"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-03-o2-c1', 'mission-ai-trees-of-decision-03-o2', 1, 'drag_and_drop', 'Match each node description to its impurity level.', '{"items":[{"id":"i1","text":"A node containing 100 emergency examples and 0 routine examples"},{"id":"i2","text":"A node containing 50 emergency examples and 50 routine examples"},{"id":"i3","text":"A node containing 92 emergency examples and 8 routine examples"}],"targets":[{"id":"t1","label":"Zero impurity (pure)"},{"id":"t2","label":"Maximum impurity (fifty-fifty)"},{"id":"t3","label":"Low but nonzero impurity"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-trees-of-decision-04-o1-c1', 'mission-ai-trees-of-decision-04-o1', 1, 'multiple_choice', 'Increasing a decision tree''s maximum depth mainly increases...', '{"question":"Increasing a decision tree''s maximum depth mainly increases...","options":[{"id":"a","text":"How many training examples exist"},{"id":"b","text":"How many sequential yes/no questions a prediction can pass through, and therefore how complex a rule the tree can represent"},{"id":"c","text":"How many features were originally collected"},{"id":"d","text":"The color of the tree diagram"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-04-o2-c1', 'mission-ai-trees-of-decision-04-o2', 1, 'interactive_diagram', 'Order the steps a single example passes through to get a prediction from a decision tree.', '{"diagramId":"tree-prediction-walkthrough","hotspots":[{"id":"h1","label":"Start at the root node","explanation":"Every prediction begins at the top of the tree, before any question has been asked."},{"id":"h2","label":"Answer the root''s split question","explanation":"The example''s feature value is compared against the threshold, sending it left or right."},{"id":"h3","label":"Answer the next node''s split question","explanation":"The example keeps moving down, answering one split at a time."},{"id":"h4","label":"Arrive at a leaf node","explanation":"Once no more splits remain on that path, the example has reached a leaf."},{"id":"h5","label":"Read the leaf''s prediction","explanation":"The leaf stores the final class prediction for every example that lands there."}],"task":"Order the steps a single example passes through to get a prediction from a decision tree."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5"]}'::jsonb),

  ('mission-ai-trees-of-decision-05-o1-c1', 'mission-ai-trees-of-decision-05-o1', 1, 'investigation', 'Which combination of evidence proves this tree has overfit?', '{"evidence":[{"id":"e1","label":"Training report","detail":"The unlimited-depth tree reaches 99.8% accuracy on the exact data it was trained on."},{"id":"e2","label":"Held-out report","detail":"The same tree scores only 61% accuracy on incidents from a later, unseen time period."},{"id":"e3","label":"Compute log","detail":"Training the tree took 4 seconds on the available hardware."}],"question":"Which combination of evidence proves this tree has overfit?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-trees-of-decision-05-o2-c1', 'mission-ai-trees-of-decision-05-o2', 1, 'multiple_choice', 'What is the most direct fix for a decision tree that has overfit like this?', '{"question":"What is the most direct fix for a decision tree that has overfit like this?","options":[{"id":"a","text":"Collect the exact same training data again"},{"id":"b","text":"Limit how deep the tree is allowed to grow, or require a minimum number of examples per leaf, so it stops memorizing individual points"},{"id":"c","text":"Increase the learning rate"},{"id":"d","text":"Remove all features from the model"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-trees-of-decision-06-o1-c1', 'mission-ai-trees-of-decision-06-o1', 1, 'multiple_choice', 'A random forest is best described as...', '{"question":"A random forest is best described as...","options":[{"id":"a","text":"One very deep decision tree"},{"id":"b","text":"An ensemble of many decision trees, each trained on a randomized version of the data, combined by voting or averaging"},{"id":"c","text":"A decision tree with no splits at all"},{"id":"d","text":"A single tree retrained many times on the exact same data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-06-o2-c1', 'mission-ai-trees-of-decision-06-o2', 1, 'interactive_diagram', 'Order the steps of building and using a random forest.', '{"diagramId":"random-forest-build","hotspots":[{"id":"h1","label":"Draw a random bootstrap sample of the training data for each tree","explanation":"Every tree in the forest starts from its own resampled slice of the data."},{"id":"h2","label":"Train an independent decision tree on that sample","explanation":"Each tree learns from only the data it was given, with no knowledge of the other trees."},{"id":"h3","label":"At each split, consider only a random subset of features","explanation":"This keeps the trees from all leaning on the same few dominant features."},{"id":"h4","label":"Repeat across many trees, trained independently","explanation":"The forest is built from dozens or hundreds of these differently-trained trees."},{"id":"h5","label":"Combine every tree''s prediction by vote or average","explanation":"The final forest prediction comes from aggregating all the individual trees."}],"task":"Order the steps of building and using a random forest."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5"]}'::jsonb),

  ('mission-ai-trees-of-decision-07-o1-c1', 'mission-ai-trees-of-decision-07-o1', 1, 'multiple_choice', 'Bootstrap sampling, the first half of bagging, means...', '{"question":"Bootstrap sampling, the first half of bagging, means...","options":[{"id":"a","text":"Training every tree on the identical full dataset"},{"id":"b","text":"Sampling a new training set of the same size, with replacement, separately for each tree"},{"id":"c","text":"Removing all duplicate rows from the dataset"},{"id":"d","text":"Sorting the data by feature value before training"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-07-o2-c1', 'mission-ai-trees-of-decision-07-o2', 1, 'investigation', 'Which evidence shows that aggregating many bootstrap-trained trees produces a better result than any single tree?', '{"evidence":[{"id":"e1","label":"Individual tree accuracies","detail":"The 50 trees in the forest score between 68% and 84% accuracy on held-out data, each trained on its own bootstrap sample."},{"id":"e2","label":"Forest accuracy","detail":"Voting across all 50 trees together scores 89% accuracy on the same held-out data."},{"id":"e3","label":"Training log","detail":"All 50 trees finished training within the same job."}],"question":"Which evidence shows that aggregating many bootstrap-trained trees produces a better result than any single tree?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),

  ('mission-ai-trees-of-decision-08-o1-c1', 'mission-ai-trees-of-decision-08-o1', 1, 'multiple_choice', 'Feature importance from a trained forest tells you...', '{"question":"Feature importance from a trained forest tells you...","options":[{"id":"a","text":"Which feature causes emergencies to happen"},{"id":"b","text":"Roughly how much a feature contributed to reducing impurity across the ensemble''s splits"},{"id":"c","text":"The exact real-world cost of ignoring that feature"},{"id":"d","text":"Which feature was collected first"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-08-o2-c1', 'mission-ai-trees-of-decision-08-o2', 1, 'investigation', 'What should the near-identical importance scores of signal_spike and cpu_load make you cautious about?', '{"evidence":[{"id":"e1","label":"Importance report","detail":"signal_spike ranks highest at 0.41 importance; cpu_load ranks second at 0.39 importance; the two features are 97% correlated with each other in the raw data."},{"id":"e2","label":"Domain note","detail":"signal_spike and cpu_load are computed from nearly the same underlying sensor feed."},{"id":"e3","label":"Deployment note","detail":"The model serves predictions from an on-call dashboard."}],"question":"What should the near-identical importance scores of signal_spike and cpu_load make you cautious about?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-trees-of-decision-09-o1-c1', 'mission-ai-trees-of-decision-09-o1', 1, 'multiple_choice', 'Gradient boosting builds its ensemble by...', '{"question":"Gradient boosting builds its ensemble by...","options":[{"id":"a","text":"Training every tree independently on random bootstrap samples and voting"},{"id":"b","text":"Training trees one at a time in sequence, each new tree focused on correcting the current ensemble''s remaining errors"},{"id":"c","text":"Training exactly one very deep tree"},{"id":"d","text":"Discarding all but the single most accurate tree"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-09-o2-c1', 'mission-ai-trees-of-decision-09-o2', 1, 'drag_and_drop', 'Sort each characteristic into bagging or boosting.', '{"items":[{"id":"i1","text":"Trees are trained independently of each other, in parallel"},{"id":"i2","text":"Trees are trained one after another, each correcting the last ensemble''s errors"},{"id":"i3","text":"Reduces variance by averaging many high-variance trees"},{"id":"i4","text":"Can reduce bias by focusing new trees on previously mispredicted examples"},{"id":"i5","text":"Each tree is usually trained on a random bootstrap sample of the full data"},{"id":"i6","text":"Too many rounds, or too high a learning rate, can overfit the training data"}],"targets":[{"id":"t1","label":"Bagging"},{"id":"t2","label":"Boosting"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2","i5":"t1","i6":"t2"}}'::jsonb),

  ('mission-ai-trees-of-decision-10-o1-c1', 'mission-ai-trees-of-decision-10-o1', 1, 'multiple_choice', 'Compared to plain gradient boosting, XGBoost mainly adds...', '{"question":"Compared to plain gradient boosting, XGBoost mainly adds...","options":[{"id":"a","text":"A completely different algorithm unrelated to trees"},{"id":"b","text":"Regularization, shrinkage and early stopping on top of the same sequential-correction idea, to guard against overfitting"},{"id":"c","text":"The ability to train without any data"},{"id":"d","text":"A guarantee that the model can never be wrong"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-trees-of-decision-10-o2-c1', 'mission-ai-trees-of-decision-10-o2', 1, 'drag_and_drop', 'Match each XGBoost concept to its definition.', '{"items":[{"id":"i1","text":"Regularization term"},{"id":"i2","text":"Learning rate (shrinkage)"},{"id":"i3","text":"Early stopping"}],"targets":[{"id":"t1","label":"Penalizes overly complex trees so the model does not chase every training-set quirk"},{"id":"t2","label":"Scales down each new tree''s contribution so no single round can dominate the ensemble"},{"id":"t3","label":"Halts training once held-out performance stops improving, even if more training rounds are allowed"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-trees-of-decision-11-o1-c1', 'mission-ai-trees-of-decision-11-o1', 1, 'investigation', 'Which evidence exposes the report''s misleading headline number?', '{"evidence":[{"id":"e1","label":"Report headline","detail":"Single decision tree: 99.8% accuracy -- highlighted in bold as the best-performing model."},{"id":"e2","label":"Fine print","detail":"That 99.8% figure is measured on the tree''s own training data, not on the held-out set used for the other three models."},{"id":"e3","label":"Held-out comparison table","detail":"On the same held-out set: logistic regression 82%, single tree 61%, random forest 90%, gradient boosting 91%."}],"question":"Which evidence exposes the report''s misleading headline number?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-trees-of-decision-11-o2-c1', 'mission-ai-trees-of-decision-11-o2', 1, 'multiple_choice', 'A fair comparison between candidate models requires...', '{"question":"A fair comparison between candidate models requires...","options":[{"id":"a","text":"Reporting whichever single metric makes the newest model look best"},{"id":"b","text":"Evaluating every model on the same held-out data with the same metrics, not mixing training-set and held-out numbers"},{"id":"c","text":"Picking the model that was fastest to build"},{"id":"d","text":"Trusting the model with the most complex-sounding name"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-trees-of-decision-12-o1-c1', 'mission-ai-trees-of-decision-12-o1', 1, 'investigation', 'Which evidence proves the single tree overfit its training data?', '{"evidence":[{"id":"e1","label":"Training report","detail":"The unlimited-depth single tree reaches 99.8% accuracy on the data it was trained on."},{"id":"e2","label":"Held-out report","detail":"The same tree scores only 61% accuracy on this quarter''s unseen incidents."},{"id":"e3","label":"Compute log","detail":"Training the single tree took 4 seconds on the available hardware."}],"question":"Which evidence proves the single tree overfit its training data?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-trees-of-decision-12-o2-c1', 'mission-ai-trees-of-decision-12-o2', 1, 'investigation', 'Which evidence shows bagging measurably improved on any single tree?', '{"evidence":[{"id":"e1","label":"Individual tree accuracies","detail":"The random forest''s individual trees range from 68% to 84% accuracy on held-out data."},{"id":"e2","label":"Forest accuracy","detail":"Voting across the whole random forest scores 90% accuracy on the same held-out data."},{"id":"e3","label":"Training log","detail":"The random forest took longer to train than the single tree."}],"question":"Which evidence shows bagging measurably improved on any single tree?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-trees-of-decision-12-o3-c1', 'mission-ai-trees-of-decision-12-o3', 1, 'investigation', 'Which evidence is the real tradeoff to weigh against the boosted ensemble''s top accuracy?', '{"evidence":[{"id":"e1","label":"Held-out accuracy","detail":"The gradient-boosted ensemble scores 91% accuracy on held-out data, the highest of all four candidate models."},{"id":"e2","label":"Feature importance report","detail":"The boosted ensemble''s top two features are 97% correlated, making individual importance ranks unstable."},{"id":"e3","label":"Interpretability note","detail":"The boosted ensemble is the hardest of the four models to explain to an on-call engineer, since each prediction comes from summing many small sequential corrections rather than one visible rule."}],"question":"Which evidence is the real tradeoff to weigh against the boosted ensemble''s top accuracy?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),
  ('mission-ai-trees-of-decision-12-o4-c1', 'mission-ai-trees-of-decision-12-o4', 1, 'boss_encounter', 'Having judged the single tree, the random forest and the boosted ensemble, state Cipher Division''s recommendation for production.', '{"stages":[{"objectiveRef":"mission-ai-trees-of-decision-12-o1","label":"Diagnose the single tree"},{"objectiveRef":"mission-ai-trees-of-decision-12-o2","label":"Judge the random forest"},{"objectiveRef":"mission-ai-trees-of-decision-12-o3","label":"Judge the boosted ensemble"}],"task":"State Cipher Division''s recommendation: which approach should run in production, and why, given both held-out accuracy and how defensible the model is to explain."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-trees-of-decision-12-o1","mission-ai-trees-of-decision-12-o2","mission-ai-trees-of-decision-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-trees-of-decision-01-o1-c1', 'orientation', 'There is nothing to solve here -- just confirm you are ready to continue.', 0, 1),
  ('mission-ai-trees-of-decision-01-o2-c1', 'orientation', 'Think about what happens at each node in the tree: is it fitting one line, or asking something else entirely?', 10, 1),
  ('mission-ai-trees-of-decision-01-o2-c1', 'solution', 'A decision tree predicts by asking a sequence of yes/no questions at each node, branching until it reaches a leaf with a final answer.', 20, 2),

  ('mission-ai-trees-of-decision-02-o1-c1', 'orientation', 'A split acts at exactly one node, using exactly one feature and one threshold.', 10, 1),
  ('mission-ai-trees-of-decision-02-o1-c1', 'solution', 'A split is a rule on one feature and one threshold that divides the examples at a node into two branches.', 20, 2),
  ('mission-ai-trees-of-decision-02-o2-c1', 'orientation', 'Ignore splits that leave both resulting branches close to fifty-fifty.', 10, 1),
  ('mission-ai-trees-of-decision-02-o2-c1', 'concept', 'The best split is the one where each resulting branch leans heavily toward a single class.', 20, 2),
  ('mission-ai-trees-of-decision-02-o2-c1', 'solution', 'e1: Split A produces a 90/10 branch and a 5/95 branch -- both branches are far purer than the mixed starting group, unlike Splits B and C, which barely change anything.', 30, 3),

  ('mission-ai-trees-of-decision-03-o1-c1', 'orientation', 'Impurity is not about counts, depth or training speed -- it is about mixture.', 10, 1),
  ('mission-ai-trees-of-decision-03-o1-c1', 'solution', 'Impurity measures how mixed the classes are among the examples at a node -- zero when a node is one class only, highest at a fifty-fifty split.', 20, 2),
  ('mission-ai-trees-of-decision-03-o2-c1', 'orientation', 'A node with only one class present has nothing left in it to be mixed.', 10, 1),
  ('mission-ai-trees-of-decision-03-o2-c1', 'solution', 'Zero impurity: 100 emergency / 0 routine. Maximum impurity: 50/50. Low but nonzero impurity: 92/8.', 20, 2),

  ('mission-ai-trees-of-decision-04-o1-c1', 'orientation', 'Depth is measured in questions asked, not in examples or features.', 10, 1),
  ('mission-ai-trees-of-decision-04-o1-c1', 'solution', 'Depth controls how many sequential yes/no questions a prediction can pass through, and therefore how complex a rule the tree can represent.', 20, 2),
  ('mission-ai-trees-of-decision-04-o2-c1', 'orientation', 'Every prediction starts at the very top of the tree, before any question is asked.', 10, 1),
  ('mission-ai-trees-of-decision-04-o2-c1', 'concept', 'A prediction cannot reach a leaf without first passing through every split on its path, in order.', 20, 2),
  ('mission-ai-trees-of-decision-04-o2-c1', 'solution', 'Start at the root, answer the root''s split question, answer the next node''s split question, arrive at a leaf, read the leaf''s prediction.', 30, 3),

  ('mission-ai-trees-of-decision-05-o1-c1', 'orientation', 'Compare what the tree scores on data it trained on versus data it never saw.', 10, 1),
  ('mission-ai-trees-of-decision-05-o1-c1', 'concept', 'A model that is far more accurate on its own training data than on new data has memorized rather than generalized.', 20, 2),
  ('mission-ai-trees-of-decision-05-o1-c1', 'solution', 'e1 and e2 together: 99.8% on training data but only 61% on unseen data is the classic signature of an overfit tree.', 30, 3),
  ('mission-ai-trees-of-decision-05-o2-c1', 'orientation', 'The fix targets how much the tree is allowed to grow, not the data collection process.', 10, 1),
  ('mission-ai-trees-of-decision-05-o2-c1', 'solution', 'Limiting maximum depth, or requiring a minimum number of examples per leaf, stops the tree from carving out a branch for every individual training point.', 20, 2),

  ('mission-ai-trees-of-decision-06-o1-c1', 'orientation', 'A forest is not one tree grown bigger -- it is many trees, combined.', 10, 1),
  ('mission-ai-trees-of-decision-06-o1-c1', 'solution', 'A random forest trains many decision trees on randomized versions of the data and combines their predictions by vote or average.', 20, 2),
  ('mission-ai-trees-of-decision-06-o2-c1', 'orientation', 'Each tree needs its own randomized data before it can be trained.', 10, 1),
  ('mission-ai-trees-of-decision-06-o2-c1', 'concept', 'Training happens independently, tree by tree, before any voting occurs.', 20, 2),
  ('mission-ai-trees-of-decision-06-o2-c1', 'solution', 'Draw a bootstrap sample for each tree, train an independent tree on it while considering only a random subset of features at each split, repeat across many trees, then combine every tree''s prediction by vote or average.', 30, 3),

  ('mission-ai-trees-of-decision-07-o1-c1', 'orientation', 'Bootstrap sampling changes which rows each tree sees, not how many trees exist.', 10, 1),
  ('mission-ai-trees-of-decision-07-o1-c1', 'solution', 'Bootstrap sampling draws a new training set of the same size, with replacement, separately for every tree -- so some examples repeat and others are left out.', 20, 2),
  ('mission-ai-trees-of-decision-07-o2-c1', 'orientation', 'Look at the range of individual tree scores compared to the combined score.', 10, 1),
  ('mission-ai-trees-of-decision-07-o2-c1', 'concept', 'If aggregating did nothing, the forest would score about the same as the average individual tree, not noticeably better.', 20, 2),
  ('mission-ai-trees-of-decision-07-o2-c1', 'solution', 'e1 and e2 together: individual trees range from 68% to 84%, but voting across all 50 reaches 89% -- aggregating cancels out a lot of each tree''s individual error.', 30, 3),

  ('mission-ai-trees-of-decision-08-o1-c1', 'orientation', 'Importance describes contribution to splits, not real-world causation.', 10, 1),
  ('mission-ai-trees-of-decision-08-o1-c1', 'solution', 'Feature importance reflects roughly how much a feature contributed to reducing impurity across every split in the ensemble.', 20, 2),
  ('mission-ai-trees-of-decision-08-o2-c1', 'orientation', 'Two features that are almost perfectly correlated are, in effect, carrying the same information.', 10, 1),
  ('mission-ai-trees-of-decision-08-o2-c1', 'concept', 'When two correlated features can each explain the same splits, the tree can pick either one, so their reported importance gets divided instead of credited clearly to one.', 20, 2),
  ('mission-ai-trees-of-decision-08-o2-c1', 'solution', 'e1: signal_spike and cpu_load rank almost identically and are 97% correlated -- their close importance scores are likely a symptom of shared information, not proof that both independently matter.', 30, 3),

  ('mission-ai-trees-of-decision-09-o1-c1', 'orientation', 'Ask whether the trees are trained at the same time or one after another.', 10, 1),
  ('mission-ai-trees-of-decision-09-o1-c1', 'solution', 'Gradient boosting trains trees one at a time, each new tree focused on correcting the errors the current ensemble is still making.', 20, 2),
  ('mission-ai-trees-of-decision-09-o2-c1', 'orientation', 'Bagging trains in parallel and averages; boosting trains in sequence and corrects.', 10, 1),
  ('mission-ai-trees-of-decision-09-o2-c1', 'solution', 'Bagging: independent parallel trees, bootstrap samples, reduces variance by averaging. Boosting: sequential trees correcting prior errors, can reduce bias, and can overfit if pushed with too many rounds or too high a learning rate.', 20, 2),

  ('mission-ai-trees-of-decision-10-o1-c1', 'orientation', 'XGBoost keeps the same sequential-correction idea -- it adds safeguards around it.', 10, 1),
  ('mission-ai-trees-of-decision-10-o1-c1', 'solution', 'XGBoost adds regularization, a learning rate that shrinks each tree''s contribution, and early stopping on top of ordinary gradient boosting, mainly to guard against overfitting.', 20, 2),
  ('mission-ai-trees-of-decision-10-o2-c1', 'orientation', 'Match each concept to what it actually restrains during training.', 10, 1),
  ('mission-ai-trees-of-decision-10-o2-c1', 'solution', 'Regularization penalizes overly complex trees. Learning rate shrinks each new tree''s contribution. Early stopping halts training once held-out performance stops improving.', 20, 2),

  ('mission-ai-trees-of-decision-11-o1-c1', 'orientation', 'Check whether the headline number and the comparison table were measured on the same data.', 10, 1),
  ('mission-ai-trees-of-decision-11-o1-c1', 'concept', 'A number measured on training data is not comparable to numbers measured on held-out data, no matter how impressive it looks.', 20, 2),
  ('mission-ai-trees-of-decision-11-o1-c1', 'solution', 'e2: the 99.8% headline came from the tree''s own training data, not the held-out set used to score the other three models -- it is not a fair comparison.', 30, 3),
  ('mission-ai-trees-of-decision-11-o2-c1', 'orientation', 'Fairness comes from consistency across models, not from picking a favorite number.', 10, 1),
  ('mission-ai-trees-of-decision-11-o2-c1', 'solution', 'A fair comparison evaluates every model on the same held-out data with the same metrics, rather than mixing training-set and held-out numbers.', 20, 2),

  ('mission-ai-trees-of-decision-12-o1-c1', 'orientation', 'Same signature as before: compare the tree''s performance on data it trained on to its performance on data it did not.', 10, 1),
  ('mission-ai-trees-of-decision-12-o1-c1', 'concept', 'A tree that looks almost perfect on training data and much worse on held-out data has not learned a general rule.', 20, 2),
  ('mission-ai-trees-of-decision-12-o1-c1', 'solution', 'e1 and e2 together: 99.8% on training data against 61% on held-out data is decisive evidence the single tree overfit.', 30, 3),
  ('mission-ai-trees-of-decision-12-o2-c1', 'orientation', 'Look at what changed when many trees were combined by vote, not at any single tree in isolation.', 10, 1),
  ('mission-ai-trees-of-decision-12-o2-c1', 'concept', 'If the forest were not actually better than its individual trees, aggregating would not have been worth doing.', 20, 2),
  ('mission-ai-trees-of-decision-12-o2-c1', 'solution', 'e1 and e2 together: individual trees ranged 68% to 84% held-out, but the forest''s vote reached 90% -- bagging measurably improved on any single tree.', 30, 3),
  ('mission-ai-trees-of-decision-12-o3-c1', 'orientation', 'The boosted ensemble''s top accuracy is not free -- something else was traded away for it.', 10, 1),
  ('mission-ai-trees-of-decision-12-o3-c1', 'concept', 'The real tradeoff to weigh is not another accuracy number, it is how easy the winning model is to explain to whoever has to trust it on the job.', 20, 2),
  ('mission-ai-trees-of-decision-12-o3-c1', 'solution', 'e3: the boosted ensemble is the hardest of the four to explain, since its prediction comes from summing many small sequential corrections -- that interpretability cost is the real thing to weigh against its top accuracy.', 30, 3),
  ('mission-ai-trees-of-decision-12-o4-c1', 'orientation', 'Weigh accuracy and explainability together -- do not let the single highest number decide alone.', 15, 1),
  ('mission-ai-trees-of-decision-12-o4-c1', 'solution', 'The single tree is disqualified by its own overfitting evidence. Between the random forest and the boosted ensemble, recommend based on both held-out accuracy and how defensible the model is to explain in production, not on whichever posted the top number.', 25, 2);
