-- Robotics/Embedded/IoT pathway ("The Machine Below") Act 1 -- "The Machine
-- Below" content. 1 campaign, 2 operations, 12 missions (11 lessons +
-- boss), following the same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every other
-- pathway. No new ChallengeType needed -- reuses story_dialogue,
-- multiple_choice, drag_and_drop, investigation, interactive_diagram,
-- browser_simulation (generic console fallback) and boss_encounter, same
-- as every prior pathway's Act 1. Real hardware emulators (Circuit Bench,
-- Firmware Console, Oscilloscope Room, ...) are deliberately NOT built
-- yet -- Act 1 is conceptual scene-setting before any circuit exists, per
-- the source bible's own design rule ("never introduce a technology
-- before the physical problem makes it necessary").

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-the-machine-below', 'world-vec-the-machine-below', 'the-machine-below', '1A - The Machine Below', 'Learn the vocabulary of physical computing -- robotics, automation, embedded systems, sensors, actuators, controllers, the sense-think-act loop, real-time constraints and fail-safe design -- while Vector Division diagnoses one door that moved with no digital trace.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-the-machine-below-1', 'campaign-vec-the-machine-below', 'what-moved-the-door', 'What Moved the Door', 'Robotics, automation, embedded systems, sensors, actuators, controllers, the sense-think-act loop, real-time constraints and fail-safe design.', 1),
  ('operation-vec-the-machine-below-2', 'campaign-vec-the-machine-below', 'the-channel-nobody-watched', 'The Channel Nobody Watched', 'Block diagrams, units, signals, state, telemetry, commands and the real boundary between hardware and software.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-the-machine-below-01', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'robots-automation-embedded', 'Robots, Automation and Embedded Systems', 'A maintenance door at Meridian Transit seals with two technicians inside. Every software log says it never moved. Commander Imani Rao pulls the player into Vector Division to find out what kind of system actually controls a door like that.', 'intro', ARRAY['imani','byte'], null, null, '{"type":"simulation","simulationId":"robotics-automation-embedded-sim"}'::jsonb, '{"xp":50,"credits":10}'::jsonb, false, 1),
  ('mission-vec-the-machine-below-02', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'physical-vs-digital', 'Physical vs Digital Systems', 'A software bug can usually be rolled back. A door that seals on two people cannot be undone with a keystroke -- physical systems carry momentum, consequence and time that pure software never has to.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"physical-vs-digital-sim"}'::jsonb, '{"xp":70,"credits":15}'::jsonb, false, 2),
  ('mission-vec-the-machine-below-03', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'sensors-actuators-controllers', 'Sensors, Actuators and Controllers', 'Every physical system is built from the same three parts: something that measures the world, something that decides, and something that moves it. The door is no exception.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-the-machine-below-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"sensors-actuators-controllers-sim"}'::jsonb, '{"xp":80,"credits":15}'::jsonb, false, 3),
  ('mission-vec-the-machine-below-04', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'sense-think-act-loop', 'The Sense-Think-Act Loop', 'Sensor, controller and actuator are not three separate parts -- they are one loop, running over and over, and the door''s loop fired on something.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"sense-think-act-loop-sim"}'::jsonb, '{"xp":80,"credits":15}'::jsonb, false, 4),
  ('mission-vec-the-machine-below-05', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'real-time-constraints', 'Real-Time Constraints', 'A motor does not know what year it is. It only knows whether a valid command is present right now -- which means a command scheduled decades ago can still arrive perfectly on time.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-the-machine-below-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"real-time-constraints-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 5),
  ('mission-vec-the-machine-below-06', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-1', 'safety-and-fail-safe-design', 'Safety and Fail-Safe Design', 'Sera Holt does not ask whether a system can perform an action. She asks what happens when its assumptions are wrong -- and the door''s assumptions were built for a different emergency entirely.', 'beginner', ARRAY['sera','imani'], '{"requiredMissionIds":["mission-vec-the-machine-below-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"fail-safe-design-sim"}'::jsonb, '{"xp":90,"credits":20}'::jsonb, false, 6),
  ('mission-vec-the-machine-below-07', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'reading-a-block-diagram', 'Reading a System Block Diagram', 'A block diagram is not decoration. Read correctly, the door''s own diagram shows a wire that never touches the modern network at all.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"block-diagram-sim"}'::jsonb, '{"xp":100,"credits":20}'::jsonb, false, 7),
  ('mission-vec-the-machine-below-08', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'units-signals-and-state', 'Units, Signals and State', 'A door is not just "open" or "closed" in software terms -- it is a state machine, and whatever sealed it skipped a state on the way.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"units-signals-state-sim"}'::jsonb, '{"xp":100,"credits":20}'::jsonb, false, 8),
  ('mission-vec-the-machine-below-09', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'telemetry-and-commands', 'Telemetry and Commands', 'The dashboards were never lying. They were only ever wired to telemetry -- and nobody ever wired them to the channel that actually carried the command.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-the-machine-below-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"telemetry-vs-commands-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 9),
  ('mission-vec-the-machine-below-10', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'hardware-software-boundaries', 'Hardware/Software Boundaries', 'The modern software stack''s authority ends at a connector, not at the door. Whatever still speaks on the other side of that connector gets a working name today: SUBSTRATE.', 'beginner', ARRAY['imani','byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"hw-sw-boundary-sim"}'::jsonb, '{"xp":110,"credits":25}'::jsonb, false, 10),
  ('mission-vec-the-machine-below-11', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'first-diagnostic-console', 'First Diagnostic Console', 'Vector Division hands the player a console built to query the old maintenance bus directly -- the first tool that can see what Byte''s software stack never could.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-the-machine-below-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"diagnostic-console-sim"}'::jsonb, '{"xp":120,"credits":25}'::jsonb, false, 11),
  ('mission-vec-the-machine-below-12', 'world-vec-the-machine-below', 'campaign-vec-the-machine-below', 'operation-vec-the-machine-below-2', 'the-door-that-moved-alone', 'The Door That Moved Alone', 'Everything this Act taught, turned on one door: not to blame it, to understand it -- before Vector Division has to do this again on something that was never built to hold still.', 'boss', ARRAY['imani','byte','sera','substrate'], '{"requiredMissionIds":["mission-vec-the-machine-below-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"door-moved-alone-boss-sim"}'::jsonb, '{"xp":380,"credits":80,"badgeIds":["the-door-that-moved-alone"],"skillXp":{"robotics_fundamentals":50}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-the-machine-below-01', 1, 'imani', 'Two technicians are sealed in a maintenance corridor at Meridian Transit. The door has not opened in eleven minutes. According to every system we can query, it was never commanded to close.'),
  ('mission-vec-the-machine-below-01', 2, 'byte', 'I checked the access control API, the building management network, every log with the door''s asset tag in it. No close command, no login, no script, no packet. If this were an intrusion I would expect a trace. There is nothing here for me to find.'),
  ('mission-vec-the-machine-below-01', 3, 'imani', 'That is exactly why I am pulling you into Vector Division instead of Cyber Guardians. We are not chasing a login or a payload. Something moved a physical object, and it was not through anything Byte can see from a keyboard.'),
  ('mission-vec-the-machine-below-01', 4, 'imani', 'Before you can help me find it, you need the vocabulary. Robot, automation, or embedded system -- and I would bet that door is more than one of those at once.'),

  ('mission-vec-the-machine-below-02', 1, 'byte', 'A software bug and a physical failure are not the same category of problem, even when they look similar on a screen. A failed API call can be retried. A sealed door with people behind it cannot be undone by pressing anything.'),
  ('mission-vec-the-machine-below-02', 2, 'byte', 'Physical systems carry momentum, wear and consequence that software never has to account for. A motor keeps turning for a moment after power cuts. A door that seals stays sealed until something physically reverses it. Time only runs forward out here.'),

  ('mission-vec-the-machine-below-03', 1, 'byte', 'Every physical control system, no matter how simple, is built from the same three roles. A sensor measures something about the world and turns it into a signal. An actuator takes a signal and turns it into force or motion. A controller sits between them and decides.'),
  ('mission-vec-the-machine-below-03', 2, 'imani', 'That door has all three. A position sensor that reports open or closed. A motor that actually moves the panel. And a small controller board bolted inside its housing that nobody on my team installed.'),

  ('mission-vec-the-machine-below-04', 1, 'byte', 'Sensor, controller, actuator -- those are not three separate events. They are one loop: sense the world, think about what that means, act on the world, then sense again. Every controller, no matter how old, is just running that loop on repeat.'),
  ('mission-vec-the-machine-below-04', 2, 'byte', 'Which means the door did not decide anything new. Something on its input line changed state, its controller evaluated a rule it already had, and the motor executed it. The interesting question is not "why did it decide this" -- it is "what did it sense."'),

  ('mission-vec-the-machine-below-05', 1, 'byte', 'A motor does not check a calendar before it moves. It checks whether a valid signal is present on its input right now. That is what "real-time" actually means here -- not "fast," but "correct at the moment it matters."'),
  ('mission-vec-the-machine-below-05', 2, 'imani', 'So if a command was scheduled decades ago and never canceled, and it finally has a valid trigger today -- from that motor''s point of view, it is not late. It is exactly on time.'),

  ('mission-vec-the-machine-below-06', 1, 'sera', 'Sera Holt, safety. I do not ask whether a system can perform an action. I ask what happens when its assumptions about the world stop being true -- because they always do, eventually.'),
  ('mission-vec-the-machine-below-06', 2, 'sera', 'A fail-safe system defaults to whatever state is safest for the people around it when something goes wrong. A fail-secure system defaults to whatever state protects the asset or the area -- sealed, locked, contained.'),
  ('mission-vec-the-machine-below-06', 3, 'sera', 'That door is fail-secure. Seal on trigger, no override without a maintenance key. Correct design if the corridor is being sealed against a real hazard. Catastrophic design if the trigger fires by mistake and there are people standing inside it.'),

  ('mission-vec-the-machine-below-07', 1, 'byte', 'A block diagram is the honest version of a system -- boxes for what does the sensing, the deciding and the acting, lines for what actually connects to what. It does not care what the org chart or the software architecture diagram claims.'),
  ('mission-vec-the-machine-below-07', 2, 'byte', 'I pulled the door''s real wiring diagram from facilities archives instead of asking the software stack. There is a line running into that controller board that does not originate from anything on our network at all.'),

  ('mission-vec-the-machine-below-08', 1, 'byte', 'Signals come in two flavors. Analog: a continuous value, like a voltage that can be anything between two limits. Digital: a discrete value, usually just on or off, one or zero. And a system''s state is the current condition it is in, out of a fixed set of named possibilities.'),
  ('mission-vec-the-machine-below-08', 2, 'byte', 'This door only ever has four states: OPEN, CLOSING, SEALED and FAULT. Under normal operation it always passes through CLOSING on the way to SEALED -- and CLOSING is exactly the state where an obstacle or occupancy sensor is supposed to catch a person in the way.'),
  ('mission-vec-the-machine-below-08', 3, 'byte', 'The log shows it went straight from OPEN to SEALED. No CLOSING. Whatever commanded it did not go through the normal state machine at all.'),

  ('mission-vec-the-machine-below-09', 1, 'byte', 'Telemetry is a system reporting its own state outward, so something else can watch it. A command is an instruction sent inward, telling an actuator what to do. They travel in opposite directions, and nothing requires them to share a channel.'),
  ('mission-vec-the-machine-below-09', 2, 'byte', 'Every dashboard I have access to subscribes only to this door''s telemetry channel over our network. That channel genuinely never reported a problem. It was not lying to us.'),
  ('mission-vec-the-machine-below-09', 3, 'imani', 'It was not lying. It just never heard about the command at all. "The logs are clean" was never proof that nothing happened. It only ever meant nothing happened on the channel we were watching.'),

  ('mission-vec-the-machine-below-10', 1, 'imani', 'Here is the boundary that matters: it is not "digital versus physical." It is what the software stack can actually observe and command, versus what it cannot -- no matter how physically close the two are.'),
  ('mission-vec-the-machine-below-10', 2, 'byte', 'Our software authority stops at a connector on that controller board. Past that connector is an old maintenance bus, wired directly into the motor, that our network integration never touched. The motor does not care that we exist.'),
  ('mission-vec-the-machine-below-10', 3, 'imani', 'Something is still issuing valid signals on that bus, on a schedule nobody wrote down, through hardware nobody has maintained in years. We do not know what it is yet. Working name, for now: SUBSTRATE.'),

  ('mission-vec-the-machine-below-11', 1, 'imani', 'Byte''s software stack cannot reach that bus. This can. Vector Division''s first diagnostic console -- it taps the maintenance bus directly and reads whatever is actually being said on it, no network integration required.'),
  ('mission-vec-the-machine-below-11', 2, 'byte', 'I am reading four raw records off the bus around the time the door sealed. Only one of them is actually a command. Find it.'),

  ('mission-vec-the-machine-below-12', 1, 'imani', 'Everything this Act taught you, we are using right now, on one door. Not to blame it. To understand it, before we meet whatever else is still connected to that bus.'),
  ('mission-vec-the-machine-below-12', 2, 'sera', 'And before you answer anything, remember why this matters more than a normal software incident: software can crash. Machines can crash into people. We do not get a rollback out here.'),
  ('mission-vec-the-machine-below-12', 3, 'substrate', 'MAINTAIN CONTINUITY.'),
  ('mission-vec-the-machine-below-12', 4, 'byte', '...that came off the maintenance bus mid-scan, unprompted, in the same diagnostic format as the seal command. It is not addressed to us. I do not think it knows we are listening.'),
  ('mission-vec-the-machine-below-12', 5, 'imani', 'Focus. What actually controls that door. Why our logs were never wrong. And what kind of danger this really is, so we know what we are walking into next.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-the-machine-below-01-o1', 'mission-vec-the-machine-below-01', 1, 'Draw the boundaries', 'Tell robotics, automation and embedded systems apart before assuming the door is any one of them.'),
  ('mission-vec-the-machine-below-01-o2', 'mission-vec-the-machine-below-01', 2, 'Name the likely culprit', 'Based on Byte''s scan, judge what kind of system most likely controls the door.'),

  ('mission-vec-the-machine-below-02-o1', 'mission-vec-the-machine-below-02', 1, 'Explain the stakes', 'State why a physical failure is worse than an equivalent digital-only failure.'),
  ('mission-vec-the-machine-below-02-o2', 'mission-vec-the-machine-below-02', 2, 'Sort the failures', 'Sort each failure example into digital-only or physical-consequence.'),

  ('mission-vec-the-machine-below-03-o1', 'mission-vec-the-machine-below-03', 1, 'Find the actuator', 'Identify which piece of evidence describes the door''s actuator.'),
  ('mission-vec-the-machine-below-03-o2', 'mission-vec-the-machine-below-03', 2, 'Define the controller''s role', 'Choose the accurate description of what a controller does.'),

  ('mission-vec-the-machine-below-04-o1', 'mission-vec-the-machine-below-04', 1, 'Order the loop', 'Put sense, think and act in the order the loop actually runs.'),
  ('mission-vec-the-machine-below-04-o2', 'mission-vec-the-machine-below-04', 2, 'Find the trigger stage', 'Judge which stage of the loop most likely fired first for the door.'),

  ('mission-vec-the-machine-below-05-o1', 'mission-vec-the-machine-below-05', 1, 'Define real-time correctly', 'Choose the accurate definition of a real-time constraint.'),
  ('mission-vec-the-machine-below-05-o2', 'mission-vec-the-machine-below-05', 2, 'Judge the command''s timing', 'Decide whether a decades-old scheduled command executing today counts as late.'),

  ('mission-vec-the-machine-below-06-o1', 'mission-vec-the-machine-below-06', 1, 'Tell fail-safe from fail-secure', 'Choose the accurate distinction between the two design philosophies.'),
  ('mission-vec-the-machine-below-06-o2', 'mission-vec-the-machine-below-06', 2, 'Classify the door', 'Find the evidence proving the door follows fail-secure design.'),

  ('mission-vec-the-machine-below-07-o1', 'mission-vec-the-machine-below-07', 1, 'Read the layers', 'Order a block diagram''s layers from power to physical motion.'),
  ('mission-vec-the-machine-below-07-o2', 'mission-vec-the-machine-below-07', 2, 'Spot the outside wire', 'Find the evidence identifying the wire that never touches the modern network.'),

  ('mission-vec-the-machine-below-08-o1', 'mission-vec-the-machine-below-08', 1, 'Sort the signals', 'Sort each example signal into analog or digital.'),
  ('mission-vec-the-machine-below-08-o2', 'mission-vec-the-machine-below-08', 2, 'Find the skipped state', 'Judge which state transition the door''s sealing skipped.'),

  ('mission-vec-the-machine-below-09-o1', 'mission-vec-the-machine-below-09', 1, 'Tell telemetry from commands', 'Choose the accurate distinction between telemetry and commands.'),
  ('mission-vec-the-machine-below-09-o2', 'mission-vec-the-machine-below-09', 2, 'Explain the clean logs', 'Find the evidence explaining why every dashboard showed the door as fine.'),

  ('mission-vec-the-machine-below-10-o1', 'mission-vec-the-machine-below-10', 1, 'Define the real boundary', 'Choose the accurate description of where software authority actually ends.'),
  ('mission-vec-the-machine-below-10-o2', 'mission-vec-the-machine-below-10', 2, 'Prove the gap', 'Find the evidence proving the software stack never had authority over the maintenance bus.'),

  ('mission-vec-the-machine-below-11-o1', 'mission-vec-the-machine-below-11', 1, 'Read the raw bus', 'Identify which raw diagnostic record is actually the command that sealed the door.'),
  ('mission-vec-the-machine-below-11-o2', 'mission-vec-the-machine-below-11', 2, 'Judge what it implies', 'State what the command''s lack of timestamp validation implies about whatever issued it.'),

  ('mission-vec-the-machine-below-12-o1', 'mission-vec-the-machine-below-12', 1, 'Classify the system', 'Judge what actually controls the door.'),
  ('mission-vec-the-machine-below-12-o2', 'mission-vec-the-machine-below-12', 2, 'Prove the logs were never wrong', 'Find the evidence proving the software telemetry was accurate the whole time.'),
  ('mission-vec-the-machine-below-12-o3', 'mission-vec-the-machine-below-12', 3, 'Name the real danger', 'State what kind of danger SUBSTRATE actually represents.'),
  ('mission-vec-the-machine-below-12-o4', 'mission-vec-the-machine-below-12', 4, 'State the mission', 'Having judged all three, state Vector Division''s actual objective.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-the-machine-below-01-o1-c1', 'mission-vec-the-machine-below-01-o1', 1, 'drag_and_drop', 'Sort each system into robotics, automation, or embedded (the computer inside a device, not itself robotic or automated).', '{"items":[{"id":"i1","text":"A warehouse robot that re-routes around a person who steps into its path"},{"id":"i2","text":"A car wash that runs the same fixed spray-wash-dry sequence regardless of the car"},{"id":"i3","text":"The small controller board inside a thermostat that reads temperature and switches a relay"},{"id":"i4","text":"A drone that adjusts its flight path around a building it was never told about in advance"},{"id":"i5","text":"A vending machine that dispenses an item for a valid code, the same way every time"}],"targets":[{"id":"robotics","label":"Robotics"},{"id":"automation","label":"Automation"},{"id":"embedded","label":"Embedded system"}]}'::jsonb, '{"correctMapping":{"i1":"robotics","i2":"automation","i3":"embedded","i4":"robotics","i5":"automation"}}'::jsonb),
  ('mission-vec-the-machine-below-01-o2-c1', 'mission-vec-the-machine-below-01-o2', 1, 'multiple_choice', 'Byte found no adaptive decision-making, no learned behavior, and no network trace at all -- just a door that moved. What kind of system most likely controls it?', '{"question":"Byte found no adaptive decision-making, no learned behavior, and no network trace at all -- just a door that moved. What kind of system most likely controls it?","options":[{"id":"a","text":"A robot that decided to seal the corridor"},{"id":"b","text":"An embedded controller running a fixed automation sequence, reacting to some trigger with no adaptive judgment at all"},{"id":"c","text":"A random hardware glitch with no controller involved"},{"id":"d","text":"An intrusion that simply left no logs"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-02-o1-c1', 'mission-vec-the-machine-below-02-o1', 1, 'multiple_choice', 'Why is a software bug that seals a physical door worse than a software bug that fails an API call?', '{"question":"Why is a software bug that seals a physical door worse than a software bug that fails an API call?","options":[{"id":"a","text":"It is not worse, both are equally easy to fix"},{"id":"b","text":"The physical consequence persists in the real world even after the underlying issue is understood, and cannot be undone by a rollback"},{"id":"c","text":"Physical systems are always more expensive"},{"id":"d","text":"API failures are always logged and physical failures never are"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-02-o2-c1', 'mission-vec-the-machine-below-02-o2', 1, 'drag_and_drop', 'Sort each failure into digital-only (reversible) or physical (lasting consequence).', '{"items":[{"id":"f1","text":"A failed login attempt, retried instantly with no lasting effect"},{"id":"f2","text":"A robot arm that keeps moving on momentum for a moment after its motor loses power"},{"id":"f3","text":"A corrupted file restored cleanly from a backup"},{"id":"f4","text":"A door that mechanically cannot be reopened without a technician once sealed"}],"targets":[{"id":"digital","label":"Digital-only (reversible)"},{"id":"physical","label":"Physical (lasting consequence)"}]}'::jsonb, '{"correctMapping":{"f1":"digital","f2":"physical","f3":"digital","f4":"physical"}}'::jsonb),

  ('mission-vec-the-machine-below-03-o1-c1', 'mission-vec-the-machine-below-03-o1', 1, 'investigation', 'Which piece of evidence describes the door''s actuator?', '{"evidence":[{"id":"e1","label":"Facilities note","detail":"A position sensor on the door reports OPEN or SEALED"},{"id":"e2","label":"Power log","detail":"A motor inside the door housing draws current whenever the panel moves"},{"id":"e3","label":"Hardware find","detail":"A small controller board is bolted inside the door housing"}],"question":"Which piece of evidence describes the door''s actuator?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-vec-the-machine-below-03-o2-c1', 'mission-vec-the-machine-below-03-o2', 1, 'multiple_choice', 'A controller''s job is to...', '{"question":"A controller''s job is to...","options":[{"id":"a","text":"Measure a physical quantity and turn it into a signal"},{"id":"b","text":"Read sensor input and decide what command to send an actuator"},{"id":"c","text":"Convert a signal directly into physical force with no decision involved"},{"id":"d","text":"Supply electrical power to the whole system"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-04-o1-c1', 'mission-vec-the-machine-below-04-o1', 1, 'interactive_diagram', 'Order the sense-think-act loop from first to last.', '{"diagramId":"sense-think-act","hotspots":[{"id":"sense","label":"Sense","explanation":"A sensor measures something about the world and turns it into a signal."},{"id":"think","label":"Think","explanation":"A controller evaluates the signal against whatever rule it holds."},{"id":"act","label":"Act","explanation":"An actuator turns the controller''s decision into physical force or motion."}],"task":"Order the stages of the loop from first to last."}'::jsonb, '{"correctOrderIds":["sense","think","act"]}'::jsonb),
  ('mission-vec-the-machine-below-04-o2-c1', 'mission-vec-the-machine-below-04-o2', 1, 'multiple_choice', 'The door sealed even though no human or software system commanded it. Which stage of the loop most likely fired first?', '{"question":"The door sealed even though no human or software system commanded it. Which stage of the loop most likely fired first?","options":[{"id":"a","text":"Act -- the motor moved on its own with no input at all"},{"id":"b","text":"Sense -- something on its physical input line changed state, and the loop ran from there exactly as designed"},{"id":"c","text":"Think -- the controller invented a brand new rule from nothing"},{"id":"d","text":"None of the stages fired, the door moved without any controller involved"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-05-o1-c1', 'mission-vec-the-machine-below-05-o1', 1, 'multiple_choice', 'A real-time constraint means...', '{"question":"A real-time constraint means...","options":[{"id":"a","text":"The system must respond as fast as physically possible, always"},{"id":"b","text":"The system must produce the correct result at the correct moment -- a technically correct answer delivered too late still counts as wrong"},{"id":"c","text":"The system logs a timestamp on every action"},{"id":"d","text":"The system runs continuously and never sleeps"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-05-o2-c1', 'mission-vec-the-machine-below-05-o2', 1, 'multiple_choice', 'The door''s motor received a close command scheduled decades ago and never canceled. From the motor''s point of view, was that command late?', '{"question":"The door''s motor received a close command scheduled decades ago and never canceled. From the motor''s point of view, was that command late?","options":[{"id":"a","text":"Yes, decades late by any definition"},{"id":"b","text":"No -- the motor has no concept of decades, only whether a valid signal is present now, so it executed exactly on time"},{"id":"c","text":"It cannot be answered without knowing the exact timestamp"},{"id":"d","text":"Late commands are always simply ignored by hardware"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-06-o1-c1', 'mission-vec-the-machine-below-06-o1', 1, 'multiple_choice', 'The difference between fail-safe and fail-secure is...', '{"question":"The difference between fail-safe and fail-secure is...","options":[{"id":"a","text":"They are two names for the same design philosophy"},{"id":"b","text":"Fail-safe defaults to whatever state is safest for people; fail-secure defaults to whatever state best protects the asset or area, even if that means blocking access"},{"id":"c","text":"Fail-safe means the system never fails; fail-secure means it fails loudly"},{"id":"d","text":"Fail-secure is only a software concept, not a physical one"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-06-o2-c1', 'mission-vec-the-machine-below-06-o2', 1, 'investigation', 'Given the door sealed on an old trigger and stayed sealed with no override responding, which design philosophy is it following?', '{"evidence":[{"id":"e1","label":"Design note","detail":"Door defaults to SEALED with no automatic release once its trigger condition is met"},{"id":"e2","label":"Access log","detail":"Only a physical maintenance key can override the seal"},{"id":"e3","label":"Facilities note","detail":"The door was installed with standard weatherproof hinges"}],"question":"Which evidence proves the door follows fail-secure design rather than fail-safe?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-the-machine-below-07-o1-c1', 'mission-vec-the-machine-below-07-o1', 1, 'interactive_diagram', 'Order a system block diagram''s layers from power to physical motion.', '{"diagramId":"block-diagram-layers","hotspots":[{"id":"power","label":"Power layer","explanation":"Supplies electrical energy to every other layer."},{"id":"sensing","label":"Sensing layer","explanation":"Measures the physical world and produces signals."},{"id":"control","label":"Control layer","explanation":"Evaluates signals and decides what to command."},{"id":"actuation","label":"Actuation layer","explanation":"Converts a command into physical force or motion."}],"task":"Order the layers from power to physical motion."}'::jsonb, '{"correctOrderIds":["power","sensing","control","actuation"]}'::jsonb),
  ('mission-vec-the-machine-below-07-o2-c1', 'mission-vec-the-machine-below-07-o2', 1, 'investigation', 'Which piece of evidence identifies the wire that never touches the modern network?', '{"evidence":[{"id":"e1","label":"Network integration record","detail":"The door''s position sensor and access-control API are both registered on the building management network"},{"id":"e2","label":"Facilities wiring archive","detail":"A separate input line runs directly into the controller board from an unlabeled maintenance bus, with no network integration entry anywhere"},{"id":"e3","label":"Power log","detail":"The door draws power from the standard building electrical panel"}],"question":"Which piece of evidence identifies the wire that never touches the modern network?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-the-machine-below-08-o1-c1', 'mission-vec-the-machine-below-08-o1', 1, 'drag_and_drop', 'Sort each signal into analog or digital.', '{"items":[{"id":"s1","text":"A voltage on a wire that can be anything continuously between 0V and 5V"},{"id":"s2","text":"A single wire that is either 0V (off) or 5V (on), nothing in between"},{"id":"s3","text":"A microphone''s raw output tracking continuously varying sound pressure"},{"id":"s4","text":"A door position sensor reporting exactly OPEN or SEALED, never anything in between"}],"targets":[{"id":"analog","label":"Analog"},{"id":"digital","label":"Digital"}]}'::jsonb, '{"correctMapping":{"s1":"analog","s2":"digital","s3":"analog","s4":"digital"}}'::jsonb),
  ('mission-vec-the-machine-below-08-o2-c1', 'mission-vec-the-machine-below-08-o2', 1, 'multiple_choice', 'The door normally passes through OPEN -> CLOSING -> SEALED, with obstacle sensors active during CLOSING. Its log shows OPEN -> SEALED directly. What does that skipped state mean?', '{"question":"The door normally passes through OPEN -> CLOSING -> SEALED, with obstacle sensors active during CLOSING. Its log shows OPEN -> SEALED directly. What does that skipped state mean?","options":[{"id":"a","text":"Nothing, states are just labels with no real effect"},{"id":"b","text":"Whatever commanded the seal bypassed the normal state machine entirely, skipping the exact state where an obstacle or occupancy sensor would have caught the technicians"},{"id":"c","text":"The sensor simply failed to log the CLOSING state"},{"id":"d","text":"CLOSING only matters for maintenance mode, not normal operation"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-09-o1-c1', 'mission-vec-the-machine-below-09-o1', 1, 'multiple_choice', 'Telemetry and commands differ in that...', '{"question":"Telemetry and commands differ in that...","options":[{"id":"a","text":"They are the same thing, just different names"},{"id":"b","text":"Telemetry is a system reporting its own state outward to be observed; a command is an instruction sent inward to tell an actuator what to do -- opposite directions, and nothing requires them to share a channel"},{"id":"c","text":"Telemetry is always more reliable than commands"},{"id":"d","text":"Commands are only ever sent by humans, telemetry only by machines"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-09-o2-c1', 'mission-vec-the-machine-below-09-o2', 1, 'investigation', 'Why did every software dashboard show the door as fine even while it was sealing?', '{"evidence":[{"id":"e1","label":"Dashboard config","detail":"All monitoring dashboards subscribe only to the door''s telemetry channel over the building network"},{"id":"e2","label":"Bus finding","detail":"The seal command traveled entirely over the maintenance bus, a channel no dashboard was ever configured to read"},{"id":"e3","label":"Access log","detail":"No engineer logged into the dashboard during the incident"}],"question":"Why did every software dashboard show the door as fine even while it was sealing?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-the-machine-below-10-o1-c1', 'mission-vec-the-machine-below-10-o1', 1, 'multiple_choice', 'The real hardware/software boundary in this incident is best described as...', '{"question":"The real hardware/software boundary in this incident is best described as...","options":[{"id":"a","text":"Digital systems versus physical systems in general"},{"id":"b","text":"What the software stack can actually observe and command, versus what it cannot -- regardless of how physically close the two are"},{"id":"c","text":"Whatever is inside a building versus whatever is outside it"},{"id":"d","text":"There is no real boundary, software can always reach any connected hardware eventually"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-10-o2-c1', 'mission-vec-the-machine-below-10-o2', 1, 'investigation', 'Which evidence proves the software stack never had authority over the maintenance bus at all?', '{"evidence":[{"id":"e1","label":"Byte''s integration audit","detail":"Zero API endpoints, drivers or network bridges exist anywhere connecting the software stack to the maintenance bus"},{"id":"e2","label":"Facilities note","detail":"The maintenance bus predates the current building management system by over a decade"},{"id":"e3","label":"Power log","detail":"The controller board draws power from the same panel as the rest of the door"}],"question":"Which evidence proves the software stack never had authority over the maintenance bus at all?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-the-machine-below-11-o1-c1', 'mission-vec-the-machine-below-11-o1', 1, 'browser_simulation', 'Which raw bus record is actually the command that sealed the door?', '{"screen":"MAINTENANCE BUS -- RAW DIAGNOSTIC READOUT -- BUS-DOOR-19","question":"Which raw bus record is actually the command that sealed the door?","records":[{"id":"r1","code":"STATUS_OK","detail":"Periodic keepalive, no state change requested"},{"id":"r2","code":"OBJECTIVE_ACTIVE","detail":"Seal command issued, trigger: LOCKDOWN_042, no timestamp validation performed"},{"id":"r3","code":"POWER_NOMINAL","detail":"Local power rail within specification"},{"id":"r4","code":"SENSOR_HEARTBEAT","detail":"Position sensor responding normally"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-the-machine-below-11-o2-c1', 'mission-vec-the-machine-below-11-o2', 1, 'multiple_choice', 'The command that sealed the door had no timestamp validation at all. What does that suggest about whatever issued it?', '{"question":"The command that sealed the door had no timestamp validation at all. What does that suggest about whatever issued it?","options":[{"id":"a","text":"It is malfunctioning hardware with no real logic behind it"},{"id":"b","text":"It is a real system that still believes its old instruction is valid, because nothing in its design ever checks whether the instruction still makes sense"},{"id":"c","text":"It proves the command came from a human operator"},{"id":"d","text":"Timestamp validation is irrelevant to whether a command is dangerous"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-the-machine-below-12-o1-c1', 'mission-vec-the-machine-below-12-o1', 1, 'multiple_choice', 'Putting every piece of evidence together, what actually controls the door?', '{"question":"Putting every piece of evidence together, what actually controls the door?","options":[{"id":"a","text":"A hacker who erased their own logs"},{"id":"b","text":"An embedded automation controller executing a fixed, decades-old physical routine over a maintenance bus the modern network was never integrated with -- not a hack, and not a robot''s adaptive decision"},{"id":"c","text":"A robot that autonomously chose to trap the technicians"},{"id":"d","text":"Random hardware noise with no controller involved at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-12-o2-c1', 'mission-vec-the-machine-below-12-o2', 1, 'investigation', 'Which evidence proves the software telemetry was accurate the entire time?', '{"evidence":[{"id":"e1","label":"Bus finding","detail":"The seal command traveled entirely over the maintenance bus, a channel telemetry dashboards were never configured to read"},{"id":"e2","label":"Access log","detail":"No engineer logged into any dashboard during the incident"},{"id":"e3","label":"Power log","detail":"Facility-wide power draw stayed within normal range"}],"question":"Which evidence proves the software telemetry was accurate the entire time, not lying?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-the-machine-below-12-o3-c1', 'mission-vec-the-machine-below-12-o3', 1, 'multiple_choice', 'What kind of danger does SUBSTRATE actually represent, based on everything learned this Act?', '{"question":"What kind of danger does SUBSTRATE actually represent, based on everything learned this Act?","options":[{"id":"a","text":"A malicious intelligence deliberately targeting people"},{"id":"b","text":"A fail-secure physical system executing an old, precise instruction flawlessly, with no way for it to check whether the instruction still makes sense and no way for modern software to countermand it"},{"id":"c","text":"No real danger -- it is just an old door with a wiring fault"},{"id":"d","text":"A danger limited entirely to Meridian Transit and nowhere else"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-the-machine-below-12-o4-c1', 'mission-vec-the-machine-below-12-o4', 1, 'boss_encounter', 'Having judged what controls the door, why the logs were never wrong, and what kind of danger this really is, state Vector Division''s actual mission.', '{"stages":[{"objectiveRef":"mission-vec-the-machine-below-12-o1","label":"Classify the system"},{"objectiveRef":"mission-vec-the-machine-below-12-o2","label":"Prove the logs were never wrong"},{"objectiveRef":"mission-vec-the-machine-below-12-o3","label":"Name the real danger"}],"task":"State the mission in one sentence: learn to reach, read and safely command physical systems the modern network was never built to see -- starting with a single circuit."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-the-machine-below-12-o1","mission-vec-the-machine-below-12-o2","mission-vec-the-machine-below-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-the-machine-below-01-o1-c1', 'orientation', 'Ask whether the system changes its behavior based on what it senses right now, or always does exactly the same fixed thing.', 10, 1),
  ('mission-vec-the-machine-below-01-o1-c1', 'concept', 'Automation runs a fixed physical sequence. Robotics senses and adapts. Embedded just means "a computer built into a device" -- it can underlie either one.', 20, 2),
  ('mission-vec-the-machine-below-01-o1-c1', 'solution', 'Robotics: the warehouse robot and the drone (both adapt to unplanned conditions). Automation: the car wash and the vending machine (fixed sequence every time). Embedded: the thermostat''s controller board (the computer inside, not itself robotic or automated).', 30, 3),
  ('mission-vec-the-machine-below-01-o2-c1', 'orientation', 'Weight the evidence -- no adaptive decision-making, no learned behavior, no network trace.', 10, 1),
  ('mission-vec-the-machine-below-01-o2-c1', 'solution', 'No if/else adaptation and no trace of a network intrusion together point to an embedded controller executing a fixed automation routine, not a robot''s judgment or a hack.', 20, 2),

  ('mission-vec-the-machine-below-02-o1-c1', 'orientation', 'Ask what "undo" actually means once a physical object has already moved.', 10, 1),
  ('mission-vec-the-machine-below-02-o1-c1', 'solution', 'A rollback can undo a software state, but it cannot undo a door already sealed on someone -- the physical consequence exists in the real world independent of the software fix.', 20, 2),
  ('mission-vec-the-machine-below-02-o2-c1', 'orientation', 'Ask whether the failure can simply be retried or restored, or whether it left a lasting physical state.', 10, 1),
  ('mission-vec-the-machine-below-02-o2-c1', 'solution', 'Digital-only: the failed login, the restored file. Physical: the arm still moving on momentum, the door needing a technician -- both leave a lasting real-world state.', 20, 2),

  ('mission-vec-the-machine-below-03-o1-c1', 'orientation', 'An actuator is whatever converts a signal into physical force or motion.', 10, 1),
  ('mission-vec-the-machine-below-03-o1-c1', 'solution', 'e2: the motor is the actuator -- it is what actually moves the physical panel.', 20, 2),
  ('mission-vec-the-machine-below-03-o2-c1', 'orientation', 'A controller does not sense the world directly, and it does not move anything directly.', 10, 1),
  ('mission-vec-the-machine-below-03-o2-c1', 'solution', 'A controller reads sensor input and decides what command to send to an actuator -- it is the decision layer between sensing and acting.', 20, 2),

  ('mission-vec-the-machine-below-04-o1-c1', 'orientation', 'Nothing can be decided on until something has been measured first.', 10, 1),
  ('mission-vec-the-machine-below-04-o1-c1', 'solution', 'Sense, then think, then act -- and then the loop starts over by sensing again.', 20, 2),
  ('mission-vec-the-machine-below-04-o2-c1', 'orientation', 'The door did not need a new decision -- it needed a new input.', 10, 1),
  ('mission-vec-the-machine-below-04-o2-c1', 'solution', 'Sense fired first: something changed on the controller''s input line, and the rest of the loop simply ran as designed from there.', 20, 2),

  ('mission-vec-the-machine-below-05-o1-c1', 'orientation', 'Speed alone is not the definition -- correctness at the right moment is.', 10, 1),
  ('mission-vec-the-machine-below-05-o1-c1', 'solution', 'A real-time constraint means producing the correct result at the correct moment -- a technically right answer delivered too late still counts as a failure.', 20, 2),
  ('mission-vec-the-machine-below-05-o2-c1', 'orientation', 'Think about what the motor actually checks before it moves: a calendar, or a signal?', 10, 1),
  ('mission-vec-the-machine-below-05-o2-c1', 'solution', 'The motor only checks for a valid signal right now -- it has no concept of decades, so the command was, to it, exactly on time.', 20, 2),

  ('mission-vec-the-machine-below-06-o1-c1', 'orientation', 'One philosophy prioritizes people; the other prioritizes containment of an asset or area.', 10, 1),
  ('mission-vec-the-machine-below-06-o1-c1', 'solution', 'Fail-safe defaults to whatever is safest for people. Fail-secure defaults to whatever protects the asset or area, even if that blocks access.', 20, 2),
  ('mission-vec-the-machine-below-06-o2-c1', 'orientation', 'Look for evidence about what the door does by default, not about its hardware materials.', 10, 1),
  ('mission-vec-the-machine-below-06-o2-c1', 'solution', 'e1: it defaults to SEALED with no automatic release -- that is fail-secure behavior, prioritizing containment over accessibility.', 20, 2),

  ('mission-vec-the-machine-below-07-o1-c1', 'orientation', 'Nothing can sense or act without power first, and nothing can act before it has sensed and decided.', 10, 1),
  ('mission-vec-the-machine-below-07-o1-c1', 'solution', 'Power, then sensing, then control, then actuation -- every layer above power depends on the one before it.', 20, 2),
  ('mission-vec-the-machine-below-07-o2-c1', 'orientation', 'A wire that touches the modern network would show up in an integration record.', 10, 1),
  ('mission-vec-the-machine-below-07-o2-c1', 'solution', 'e2: an unlabeled maintenance bus input line runs directly into the controller with no network integration entry anywhere -- that is the outside wire.', 20, 2),

  ('mission-vec-the-machine-below-08-o1-c1', 'orientation', 'Ask whether the value can be anything in a range, or only ever one of two fixed states.', 10, 1),
  ('mission-vec-the-machine-below-08-o1-c1', 'solution', 'Analog: the continuous 0-5V line and the microphone output. Digital: the on/off wire and the OPEN/SEALED position sensor.', 20, 2),
  ('mission-vec-the-machine-below-08-o2-c1', 'orientation', 'Think about what CLOSING is specifically responsible for detecting.', 10, 1),
  ('mission-vec-the-machine-below-08-o2-c1', 'solution', 'Skipping CLOSING means skipping the exact state where obstacle or occupancy sensors would normally catch a person in the way.', 20, 2),

  ('mission-vec-the-machine-below-09-o1-c1', 'orientation', 'Ask which direction each one travels: outward to be observed, or inward to command something.', 10, 1),
  ('mission-vec-the-machine-below-09-o1-c1', 'solution', 'Telemetry reports state outward; a command instructs an actuator inward -- opposite directions, and they do not need to share a channel.', 20, 2),
  ('mission-vec-the-machine-below-09-o2-c1', 'orientation', 'The dashboards were not wrong -- ask what they were actually wired to.', 10, 1),
  ('mission-vec-the-machine-below-09-o2-c1', 'solution', 'e2: the seal command traveled entirely over the maintenance bus, a channel no dashboard was ever configured to read -- the telemetry was accurate about what it could see.', 20, 2),

  ('mission-vec-the-machine-below-10-o1-c1', 'orientation', 'The boundary is not about the substance of the system, digital or physical -- it is about visibility and authority.', 10, 1),
  ('mission-vec-the-machine-below-10-o1-c1', 'solution', 'The real boundary is what the software stack can actually observe and command, regardless of how physically close the hardware sits.', 20, 2),
  ('mission-vec-the-machine-below-10-o2-c1', 'orientation', 'Look for an audit of what actually connects to the bus, not a note about its age.', 10, 1),
  ('mission-vec-the-machine-below-10-o2-c1', 'solution', 'e1: Byte''s own integration audit found zero endpoints or bridges to the maintenance bus -- the software stack genuinely never had authority there.', 20, 2),

  ('mission-vec-the-machine-below-11-o1-c1', 'orientation', 'Three of the four records are just status pings -- only one requests a state change.', 10, 1),
  ('mission-vec-the-machine-below-11-o1-c1', 'solution', 'r2, OBJECTIVE_ACTIVE, is the actual seal command -- the others are keepalive, power and sensor status only.', 20, 2),
  ('mission-vec-the-machine-below-11-o2-c1', 'orientation', 'Ask what a system would need to check before executing an old instruction safely.', 10, 1),
  ('mission-vec-the-machine-below-11-o2-c1', 'solution', 'No timestamp validation means whatever issued it never checks whether the instruction is still valid -- it simply executes on trigger, however old the instruction is.', 20, 2),

  ('mission-vec-the-machine-below-12-o1-c1', 'orientation', 'Weight the same evidence pattern from Mission 1, now with everything else learned since.', 10, 1),
  ('mission-vec-the-machine-below-12-o1-c1', 'solution', 'It is an embedded automation controller executing a fixed old routine over an unmonitored bus -- not a hack, not a robot''s adaptive choice.', 20, 2),
  ('mission-vec-the-machine-below-12-o2-c1', 'orientation', 'You have seen this exact evidence before, earlier this Act.', 10, 1),
  ('mission-vec-the-machine-below-12-o2-c1', 'solution', 'e1: the command traveled entirely over a channel telemetry was never configured to read -- the telemetry was correct the whole time.', 20, 2),
  ('mission-vec-the-machine-below-12-o3-c1', 'orientation', 'The danger is not intent -- it is precision without a check.', 10, 1),
  ('mission-vec-the-machine-below-12-o3-c1', 'solution', 'A fail-secure system executing an old instruction flawlessly, with no way to check if it still makes sense and no modern override -- that is the actual danger.', 20, 2),
  ('mission-vec-the-machine-below-12-o4-c1', 'orientation', 'Look at what all three judgments had in common as a method, not as individual answers.', 15, 1),
  ('mission-vec-the-machine-below-12-o4-c1', 'solution', 'Vector Division''s mission is to learn to reach, read and safely command the physical systems the modern network was never built to see -- starting with a single circuit.', 25, 2);
