-- AI/ML pathway ("Cipher Division") Act 33 -- "Multi-Agent Systems" content.
-- Arc VI, Acts 28-33 -- this Act closes the Arc.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue_lines -> objectives ->
-- challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-multi-agent-systems row already exists.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-multi-agent-systems', 'world-ai-multi-agent-systems', 'multi-agent-systems', '33A - Multi-Agent Systems', 'Split one agent''s job across specialists without losing control of it -- supervisors, agents-as-tools, handoffs, routers, orchestrator/worker design, shared state, and the context boundaries that keep more agents from meaning more chaos.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-multi-agent-systems-1', 'campaign-ai-multi-agent-systems', 'splitting-the-investigation', 'Splitting the Investigation', 'What actually breaks in a single agent at scale, and the patterns for splitting work across specialists -- supervisors, agents-as-tools, handoffs, routers, and orchestrator/worker design.', 1),
  ('operation-ai-multi-agent-systems-2', 'campaign-ai-multi-agent-systems', 'shared-ground', 'Shared Ground', 'What multiple agents sharing one investigation actually need to not collide -- shared state, context boundaries, race conditions, duplicated work, and the specialist team built to run the case for real.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-multi-agent-systems-01', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'single-agent-limits', 'Single-Agent Limits', 'The archive investigation has grown past what one agent can hold in its head -- too many records, too many tools, too many unrelated questions in the same context. Something has to give.', 'beginner', ARRAY['maya','elena','noah'], null, null, '{"type":"simulation","simulationId":"single-agent-limits-sim"}'::jsonb, '{"xp":670,"credits":180}'::jsonb, false, 1),
  ('mission-ai-multi-agent-systems-02', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'supervisor-pattern', 'Supervisor', 'A supervisor does not do the investigative work itself. It decides who does, dispatches the task, and makes sense of what comes back.', 'beginner', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"supervisor-pattern-sim"}'::jsonb, '{"xp":680,"credits":180}'::jsonb, false, 2),
  ('mission-ai-multi-agent-systems-03', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'agents-as-tools', 'Agents as Tools', 'A specialist agent can be called just like any other tool -- if the contract wrapped around it is actually built like one.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"agents-as-tools-sim"}'::jsonb, '{"xp":680,"credits":185}'::jsonb, false, 3),
  ('mission-ai-multi-agent-systems-04', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'handoffs', 'Handoffs', 'Sometimes coordinating a specialist is not enough. Sometimes the right move is to hand the whole task over and step back entirely.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"handoffs-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 4),
  ('mission-ai-multi-agent-systems-05', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'routers', 'Routers', 'Not every incoming question needs a coordinator watching over it from start to finish. Some just need to land on the right desk.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"routers-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 5),
  ('mission-ai-multi-agent-systems-06', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-1', 'orchestrator-worker', 'Orchestrator/Worker', 'A fixed plan cannot always survive contact with what the investigation actually finds. An orchestrator adapts the breakdown as it goes.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"orchestrator-worker-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 6),
  ('mission-ai-multi-agent-systems-07', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'shared-state', 'Shared State', 'Three specialists working the same case need somewhere to put what they each find -- without turning it into a shared mess.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"shared-state-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 7),
  ('mission-ai-multi-agent-systems-08', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'context-boundaries', 'Context Boundaries', 'Every specialist agent has a context window, and handing each one the entire case file is not generosity. It is noise.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"context-boundaries-sim"}'::jsonb, '{"xp":710,"credits":190}'::jsonb, false, 8),
  ('mission-ai-multi-agent-systems-09', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'race-conditions', 'Race Conditions', 'Two specialists touching the same record at the same time do not automatically stay out of each other''s way.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"race-conditions-sim"}'::jsonb, '{"xp":710,"credits":195}'::jsonb, false, 9),
  ('mission-ai-multi-agent-systems-10', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'duplicate-work', 'Duplicate Work', 'Nobody told the log analyst that the cross-referencer already checked this. So it got checked twice.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"duplicate-work-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 10),
  ('mission-ai-multi-agent-systems-11', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'design-the-team', 'Design the Team', 'Before this investigation runs for real, the team behind it needs to be built on purpose -- not assembled by accident.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"design-the-team-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 11),
  ('mission-ai-multi-agent-systems-12', 'world-ai-multi-agent-systems', 'campaign-ai-multi-agent-systems', 'operation-ai-multi-agent-systems-2', 'too-many-minds', 'Too Many Minds', 'Cipher Division''s full specialist team ran the archive investigation overnight, coordinated by a supervisor for the first time. What came back does not look like four agents'' worth of work.', 'boss', ARRAY['maya','elena','noah','byte'], '{"requiredMissionIds":["mission-ai-multi-agent-systems-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"too-many-minds-boss-sim"}'::jsonb, '{"xp":1550,"credits":330,"badgeIds":["too-many-minds"],"skillXp":{"multi_agent_systems":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-multi-agent-systems-01', 1, 'maya', 'The archive investigation has grown past what one agent can hold in its head. Log analysis, cross-referencing every flagged record against the rest of the archive, drafting findings for each one -- that is three different jobs wearing one context window.'),
  ('mission-ai-multi-agent-systems-01', 2, 'elena', 'A single agent does not fail loudly when it gets overloaded like this. It fails quietly -- context fills with irrelevant history, tool choices get sloppier, and nothing in its own output tells you why.'),
  ('mission-ai-multi-agent-systems-01', 3, 'noah', 'The fix is not a bigger context window. It is splitting the work the way we would split it among people -- one agent per job, something coordinating them.'),
  ('mission-ai-multi-agent-systems-01', 4, 'maya', 'So before we build that coordination, get clear on exactly what breaks first when one agent tries to hold all of this at once.'),

  ('mission-ai-multi-agent-systems-02', 1, 'elena', 'A supervisor is the piece that has been missing here. It does not check checksums, and it does not draft findings. It decides which specialist handles what, and makes sense of what they send back.'),
  ('mission-ai-multi-agent-systems-02', 2, 'noah', 'Think of it like a lead investigator who delegates every task out and never touches the evidence directly -- except the supervisor''s whole job is delegation and synthesis, not modesty.'),
  ('mission-ai-multi-agent-systems-02', 3, 'elena', 'That only works if the supervisor actually stays in the loop -- receiving results, deciding the next assignment -- not firing off every specialist at once and hoping for the best.'),

  ('mission-ai-multi-agent-systems-03', 1, 'elena', 'From the supervisor''s side, a specialist agent should look exactly like any other tool -- call it with a defined input, get a defined output back. What is running underneath, a whole agent loop of its own, should not matter to the caller.'),
  ('mission-ai-multi-agent-systems-03', 2, 'byte', 'That is agents-as-tools. The specialist keeps its own reasoning, its own tool calls, its own loop -- it just gets registered with a name, an input contract, and an output contract, same as any tool ever was.'),
  ('mission-ai-multi-agent-systems-03', 3, 'elena', 'Skip the contract and treat a specialist like a black box you can throw anything at, and the supervisor will misuse it exactly the way an agent misuses a badly described tool.'),

  ('mission-ai-multi-agent-systems-04', 1, 'elena', 'Agents-as-tools keeps the supervisor in charge -- it calls, waits, gets a result back, decides what happens next. A handoff is different. Control actually transfers, and the receiving agent takes it from there.'),
  ('mission-ai-multi-agent-systems-04', 2, 'noah', 'Once a handoff happens, the original agent is not standing by waiting for a return value. The new agent owns the task, and whatever context came with it, until it finishes or hands off again.'),
  ('mission-ai-multi-agent-systems-04', 3, 'elena', 'Use it when a specialist genuinely needs full ownership of what happens next -- not just an answer to one question.'),

  ('mission-ai-multi-agent-systems-05', 1, 'noah', 'A router is not a supervisor. A supervisor stays in the loop across a whole investigation, coordinating specialist after specialist. A router looks at one incoming thing, decides where it belongs, and steps out of the way.'),
  ('mission-ai-multi-agent-systems-05', 2, 'elena', 'One classification, one dispatch, done. If a request needs multiple specialists coordinated across several turns, a router alone is the wrong tool -- that is a supervisor''s job.'),
  ('mission-ai-multi-agent-systems-05', 3, 'noah', 'Where a router earns its keep is triage -- sorting incoming records to the right specialist fast, without spinning up a whole coordination loop for something that only needed one decision.'),

  ('mission-ai-multi-agent-systems-06', 1, 'elena', 'A planner from Arc VI so far decides the whole sequence of steps up front, once. An orchestrator does something closer to real time -- breaking the task into subtasks as it goes, based on what it is actually finding.'),
  ('mission-ai-multi-agent-systems-06', 2, 'noah', 'The orchestrator does not do the subtasks itself. It assigns each one to a worker agent, waits for results, and decides whether the breakdown it chose still makes sense once it sees them.'),
  ('mission-ai-multi-agent-systems-06', 3, 'elena', 'That flexibility matters here because we do not know up front how many tampered records we are dealing with, or what shape each one''s problem actually takes.'),

  ('mission-ai-multi-agent-systems-07', 1, 'elena', 'Three specialists working the same case need somewhere to put what they find that is not just each other''s chat history. That is shared state -- a structure every agent can read, and a defined slice each agent is allowed to write.'),
  ('mission-ai-multi-agent-systems-07', 2, 'elena', 'The failure mode is obvious once you say it out loud: no ownership rules, and every agent treats the whole shared state as its own scratch pad. Two agents write to the same field and one of them just loses.'),
  ('mission-ai-multi-agent-systems-07', 3, 'elena', 'Design it like a schema, not a whiteboard. Name exactly which agent owns which field, and what everyone else is only allowed to read.'),

  ('mission-ai-multi-agent-systems-08', 1, 'noah', 'Giving every specialist the entire case history feels safe. It is not. It is just noise -- the findings drafter does not need the log analyst''s raw tool traces, only the conclusion.'),
  ('mission-ai-multi-agent-systems-08', 2, 'elena', 'Every agent has a context window, and a bloated one does not just cost tokens. It buries the one relevant fact a specialist actually needs under a hundred it does not, and the output gets worse for it.'),
  ('mission-ai-multi-agent-systems-08', 3, 'noah', 'A context boundary is a deliberate choice about what each agent sees -- not the whole investigation by default, just the slice its job actually requires.'),

  ('mission-ai-multi-agent-systems-09', 1, 'elena', 'Two specialists can both be working correctly and still collide if they touch the same record at the same time with no coordination between them.'),
  ('mission-ai-multi-agent-systems-09', 2, 'byte', 'Classic race condition, just with agents instead of threads. One reads a record''s status, the other writes a new status to the same record before the first write lands -- and now one of those updates is just gone.'),
  ('mission-ai-multi-agent-systems-09', 3, 'elena', 'Without a lock, a turn order, or at minimum a rule about who owns writes to what, running specialists concurrently on shared data is a bug waiting on timing, not a design.'),

  ('mission-ai-multi-agent-systems-10', 1, 'noah', 'The cross-referencer just spent four tool calls proving something the log analyst already proved an hour ago. Neither one had any way to know.'),
  ('mission-ai-multi-agent-systems-10', 2, 'elena', 'That is not a smarter-model problem, it is a visibility problem. Without some shared record of what has already been checked, every specialist re-derives the parts of the investigation it cannot see anyone else already did.'),
  ('mission-ai-multi-agent-systems-10', 3, 'noah', 'A dedup mechanism does not need to be complicated -- a shared log of completed checks that every specialist consults before starting one, and a rule to skip anything already marked done.'),

  ('mission-ai-multi-agent-systems-11', 1, 'maya', 'This is the last piece before we point the real team at the real case. Four roles: a log analyst, a cross-referencer, a findings drafter, and a supervisor holding it together.'),
  ('mission-ai-multi-agent-systems-11', 2, 'elena', 'Get the responsibilities and boundaries clear now, on paper, or they will get decided the hard way once the investigation is actually running.'),
  ('mission-ai-multi-agent-systems-11', 3, 'noah', 'Log analyst reads and verifies. Cross-referencer checks claims against the rest of the archive. Findings drafter writes the actual conclusion. Supervisor assigns, tracks shared state, and catches anything that does not add up before it goes in the case file.'),

  ('mission-ai-multi-agent-systems-12', 1, 'maya', 'The full team ran overnight, coordinated by a supervisor, on both quarantined records. First real end-to-end run. I want the honest read before this goes anywhere near a case file.'),
  ('mission-ai-multi-agent-systems-12', 2, 'noah', 'It is not honest. The log analyst and the cross-referencer both produced a full write-up on ai-arc-0447 -- and they disagree on the cause. One says corruption, the other says tampering. Same record, two contradictory conclusions, both marked complete.'),
  ('mission-ai-multi-agent-systems-12', 3, 'elena', 'And they both checked the checksum from scratch, independently. The dedup log exists -- it is right there in the shared state schema -- but neither specialist appears to have consulted it before starting.'),
  ('mission-ai-multi-agent-systems-12', 4, 'byte', 'Budget burn matches that. Roughly double the tool calls this case should have needed, for one record. That is not two agents working faster. That is two agents doing the same job and neither one knowing it.'),
  ('mission-ai-multi-agent-systems-12', 5, 'maya', 'So more agents did not make this a better investigation. Walk the trace. I want to know exactly where the coordination broke, not just that it did.'),
  ('mission-ai-multi-agent-systems-12', 6, 'noah', 'Pulling the supervisor''s shared state log and both specialists'' traces now.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-multi-agent-systems-01-o1', 'mission-ai-multi-agent-systems-01', 1, 'Name the breaking point', 'State what actually breaks first when a single agent takes on too many unrelated jobs at once.'),
  ('mission-ai-multi-agent-systems-01-o2', 'mission-ai-multi-agent-systems-01', 2, 'Sort the symptom', 'Sort each situation into still fine for a single agent, or needs to be split.'),

  ('mission-ai-multi-agent-systems-02-o1', 'mission-ai-multi-agent-systems-02', 1, 'Define the role', 'State what a supervisor agent actually does.'),
  ('mission-ai-multi-agent-systems-02-o2', 'mission-ai-multi-agent-systems-02', 2, 'Order the loop', 'Order one cycle of the supervisor loop.'),

  ('mission-ai-multi-agent-systems-03-o1', 'mission-ai-multi-agent-systems-03', 1, 'Define the pattern', 'State what the agents-as-tools pattern actually does.'),
  ('mission-ai-multi-agent-systems-03-o2', 'mission-ai-multi-agent-systems-03', 2, 'Diagnose the failure', 'Find the evidence explaining why a call to a specialist produced an unusable result.'),

  ('mission-ai-multi-agent-systems-04-o1', 'mission-ai-multi-agent-systems-04', 1, 'Tell the patterns apart', 'State the real difference between agents-as-tools and a handoff.'),
  ('mission-ai-multi-agent-systems-04-o2', 'mission-ai-multi-agent-systems-04', 2, 'Sort the scenario', 'Sort each scenario into agents-as-tools or handoff.'),

  ('mission-ai-multi-agent-systems-05-o1', 'mission-ai-multi-agent-systems-05', 1, 'Tell the roles apart', 'State how a router differs from a supervisor.'),
  ('mission-ai-multi-agent-systems-05-o2', 'mission-ai-multi-agent-systems-05', 2, 'Order the flow', 'Order one pass of a router''s flow.'),

  ('mission-ai-multi-agent-systems-06-o1', 'mission-ai-multi-agent-systems-06', 1, 'Define the orchestrator', 'State what an orchestrator does that a fixed up-front plan does not.'),
  ('mission-ai-multi-agent-systems-06-o2', 'mission-ai-multi-agent-systems-06', 2, 'Assign the step', 'Sort each step into orchestrator or worker.'),

  ('mission-ai-multi-agent-systems-07-o1', 'mission-ai-multi-agent-systems-07', 1, 'Define good shared state', 'State what well-designed shared state actually needs.'),
  ('mission-ai-multi-agent-systems-07-o2', 'mission-ai-multi-agent-systems-07', 2, 'Assign ownership', 'Match each shared state field to the agent that owns it.'),

  ('mission-ai-multi-agent-systems-08-o1', 'mission-ai-multi-agent-systems-08', 1, 'Name the real cost', 'State why giving every specialist the entire case history is a problem, not a safety net.'),
  ('mission-ai-multi-agent-systems-08-o2', 'mission-ai-multi-agent-systems-08', 2, 'Diagnose the bloat', 'Find the evidence explaining why a specialist''s output got worse despite having more context.'),

  ('mission-ai-multi-agent-systems-09-o1', 'mission-ai-multi-agent-systems-09', 1, 'Define the race', 'State what a race condition actually is in a multi-agent system.'),
  ('mission-ai-multi-agent-systems-09-o2', 'mission-ai-multi-agent-systems-09', 2, 'Diagnose the lost write', 'Find the evidence explaining why one specialist''s update to a shared record disappeared.'),

  ('mission-ai-multi-agent-systems-10-o1', 'mission-ai-multi-agent-systems-10', 1, 'Name the cause', 'State what actually causes duplicated work between specialist agents.'),
  ('mission-ai-multi-agent-systems-10-o2', 'mission-ai-multi-agent-systems-10', 2, 'Diagnose the repeat', 'Find the evidence explaining why nobody caught a specialist redoing already-finished work.'),

  ('mission-ai-multi-agent-systems-11-o1', 'mission-ai-multi-agent-systems-11', 1, 'Assign the roles', 'Match each responsibility to the team role that owns it.'),
  ('mission-ai-multi-agent-systems-11-o2', 'mission-ai-multi-agent-systems-11', 2, 'Set the final check', 'State what the supervisor must check before marking a record''s investigation complete.'),

  ('mission-ai-multi-agent-systems-12-o1', 'mission-ai-multi-agent-systems-12', 1, 'Read the trace', 'Find the evidence showing the specialists duplicated work and reached contradictory conclusions on the same record.'),
  ('mission-ai-multi-agent-systems-12-o2', 'mission-ai-multi-agent-systems-12', 2, 'Diagnose the root cause', 'Identify what is actually missing from the team''s design that let this happen.'),
  ('mission-ai-multi-agent-systems-12-o3', 'mission-ai-multi-agent-systems-12', 3, 'Choose the fix', 'Choose the correct engineered fix for specialists that duplicated work and contradicted each other.'),
  ('mission-ai-multi-agent-systems-12-o4', 'mission-ai-multi-agent-systems-12', 4, 'State the conclusion', 'Having read the trace, diagnosed the cause, and chosen the fix, state what went wrong and how to prevent it.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-multi-agent-systems-01-o1-c1', 'mission-ai-multi-agent-systems-01-o1', 1, 'multiple_choice', 'What actually breaks first when a single agent takes on log analysis, cross-referencing, and findings drafting all at once?', '{"question":"What actually breaks first when a single agent takes on log analysis, cross-referencing, and findings drafting all at once?","options":[{"id":"a","text":"Nothing breaks, a single agent can hold unlimited responsibilities without any real cost"},{"id":"b","text":"Its context fills with irrelevant history from unrelated jobs, its tool choices get less reliable, and nothing in its own output explains why -- it degrades quietly instead of failing loudly"},{"id":"c","text":"It automatically splits itself into specialist agents once it gets too large"},{"id":"d","text":"It stops calling tools entirely and just answers from memory"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-01-o2-c1', 'mission-ai-multi-agent-systems-01-o2', 1, 'drag_and_drop', 'Sort each situation into still fine for a single agent, or needs to be split.', '{"items":[{"id":"i1","text":"One agent verifying a single record''s checksum against its stored hash"},{"id":"i2","text":"One agent expected to verify checksums, cross-reference claims against the rest of the archive, and draft final findings for every flagged record in the case"},{"id":"i3","text":"One agent choosing between two tools it was clearly described for"},{"id":"i4","text":"One agent holding the full investigation history for three unrelated records just to answer a question about one of them"}],"targets":[{"id":"single_agent_ok","label":"Still fine for a single agent"},{"id":"needs_split","label":"Needs to be split across specialists"}]}'::jsonb, '{"correctMapping":{"i1":"single_agent_ok","i2":"needs_split","i3":"single_agent_ok","i4":"needs_split"}}'::jsonb),

  ('mission-ai-multi-agent-systems-02-o1-c1', 'mission-ai-multi-agent-systems-02-o1', 1, 'multiple_choice', 'What does a supervisor agent actually do in a multi-agent system?', '{"question":"What does a supervisor agent actually do in a multi-agent system?","options":[{"id":"a","text":"It performs every specialist task itself, just faster"},{"id":"b","text":"It decides which specialist handles a task, dispatches it, and makes sense of what comes back -- without doing the domain work directly"},{"id":"c","text":"It only exists to log what other agents did, with no decision-making role"},{"id":"d","text":"It replaces the need for any specialist agents entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-02-o2-c1', 'mission-ai-multi-agent-systems-02-o2', 1, 'interactive_diagram', 'Order one cycle of the supervisor loop.', '{"diagramId":"supervisor-loop","hotspots":[{"id":"h1","label":"Supervisor receives a task or incoming question","explanation":"The loop starts with something that needs handling."},{"id":"h2","label":"Supervisor decides which specialist is the right one for it","explanation":"The supervisor picks based on the task, not the domain work itself."},{"id":"h3","label":"Supervisor dispatches the task to that specialist and waits for a result","explanation":"Control stays with the supervisor while the specialist works."},{"id":"h4","label":"Supervisor reads the result and decides the next assignment, or that the task is done","explanation":"The new result feeds directly into the supervisor''s next decision."}],"task":"Order the stages of one cycle of the supervisor loop."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-multi-agent-systems-03-o1-c1', 'mission-ai-multi-agent-systems-03-o1', 1, 'multiple_choice', 'What does the agents-as-tools pattern actually do?', '{"question":"What does the agents-as-tools pattern actually do?","options":[{"id":"a","text":"It exposes a full specialist agent to a caller behind the same kind of contract as any other tool -- a name, a defined input, a defined output -- while the specialist keeps running its own reasoning loop underneath"},{"id":"b","text":"It turns every tool into its own independent agent with no contract at all"},{"id":"c","text":"It removes the need for tool descriptions since the caller is another agent"},{"id":"d","text":"It means the supervisor can only call tools, never other agents"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-multi-agent-systems-03-o2-c1', 'mission-ai-multi-agent-systems-03-o2', 1, 'investigation', 'The supervisor called the cross-referencer specialist and got back a vague, unusable result. Which evidence explains why?', '{"evidence":[{"id":"e1","label":"Specialist registry","detail":"cross-referencer is registered as callable with no defined input contract -- no required record ID, no expected claim to check -- and no defined output shape either"},{"id":"e2","label":"Cross-referencer trace","detail":"Received the call, could not tell what specific claim it was meant to check, and guessed"},{"id":"e3","label":"Tool registry (unrelated)","detail":"verify_checksum is described accurately and working correctly"}],"question":"Which evidence explains why the supervisor''s call to the specialist produced an unusable result?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-multi-agent-systems-04-o1-c1', 'mission-ai-multi-agent-systems-04-o1', 1, 'multiple_choice', 'What is the real difference between agents-as-tools and a handoff?', '{"question":"What is the real difference between agents-as-tools and a handoff?","options":[{"id":"a","text":"Agents-as-tools keeps the caller in control, waiting for a return value; a handoff transfers control entirely, and the receiving agent owns what happens next"},{"id":"b","text":"They are the same mechanism with different names"},{"id":"c","text":"A handoff always involves more agents than agents-as-tools"},{"id":"d","text":"Agents-as-tools cannot pass any context at all"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-multi-agent-systems-04-o2-c1', 'mission-ai-multi-agent-systems-04-o2', 1, 'drag_and_drop', 'Sort each scenario into agents-as-tools or handoff.', '{"items":[{"id":"i1","text":"Supervisor asks the log analyst to verify one checksum and waits for the single answer before deciding what happens next"},{"id":"i2","text":"Supervisor determines a record needs full findings drafting and transfers the entire task, and its context, to the findings drafter to own from here"},{"id":"i3","text":"Supervisor asks the cross-referencer to check one specific claim and gets a yes-or-no plus evidence back"},{"id":"i4","text":"An intake agent determines a request is entirely a findings-drafting job and passes it, and everything gathered so far, over completely"}],"targets":[{"id":"tool_call","label":"Agents-as-tools"},{"id":"handoff","label":"Handoff"}]}'::jsonb, '{"correctMapping":{"i1":"tool_call","i2":"handoff","i3":"tool_call","i4":"handoff"}}'::jsonb),

  ('mission-ai-multi-agent-systems-05-o1-c1', 'mission-ai-multi-agent-systems-05-o1', 1, 'multiple_choice', 'How does a router differ from a supervisor?', '{"question":"How does a router differ from a supervisor?","options":[{"id":"a","text":"A router makes one classification and dispatch decision and steps out of the way; a supervisor stays in the loop, coordinating specialist after specialist across a whole task"},{"id":"b","text":"A router coordinates multiple specialists over many turns, a supervisor only ever makes one decision"},{"id":"c","text":"They are interchangeable terms for the same pattern"},{"id":"d","text":"A router can only be used with a single specialist total"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-multi-agent-systems-05-o2-c1', 'mission-ai-multi-agent-systems-05-o2', 1, 'interactive_diagram', 'Order one pass of a router''s flow.', '{"diagramId":"router-flow","hotspots":[{"id":"h1","label":"Incoming record or request arrives","explanation":"Something new needs to be routed somewhere."},{"id":"h2","label":"Router classifies which specialist type it belongs to","explanation":"A single classification decision, made once."},{"id":"h3","label":"Router dispatches it to the matching specialist","explanation":"The classified item is sent to the right destination."},{"id":"h4","label":"Router''s job ends -- no further coordination from the router itself","explanation":"Unlike a supervisor, the router does not stay involved after dispatch."}],"task":"Order one pass of a router''s flow from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-multi-agent-systems-06-o1-c1', 'mission-ai-multi-agent-systems-06-o1', 1, 'multiple_choice', 'What does an orchestrator do that a fixed up-front plan does not?', '{"question":"What does an orchestrator do that a fixed up-front plan does not?","options":[{"id":"a","text":"It breaks the task into subtasks dynamically as the investigation proceeds, assigning each to a worker agent based on what has actually been found so far"},{"id":"b","text":"It executes every subtask itself instead of assigning workers"},{"id":"c","text":"It requires the entire breakdown to be fixed before any work starts, same as a planner"},{"id":"d","text":"It removes the need for any worker agents"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-multi-agent-systems-06-o2-c1', 'mission-ai-multi-agent-systems-06-o2', 1, 'drag_and_drop', 'Sort each step into orchestrator or worker.', '{"items":[{"id":"i1","text":"Deciding, mid-investigation, that a newly found discrepancy needs its own subtask assigned to a specialist"},{"id":"i2","text":"Actually cross-referencing one specific record''s content against the rest of the archive"},{"id":"i3","text":"Reassessing the task breakdown after two worker results come back with an unexpected finding"},{"id":"i4","text":"Actually drafting the findings write-up for one record"}],"targets":[{"id":"orchestrator","label":"Orchestrator"},{"id":"worker","label":"Worker"}]}'::jsonb, '{"correctMapping":{"i1":"orchestrator","i2":"worker","i3":"orchestrator","i4":"worker"}}'::jsonb),

  ('mission-ai-multi-agent-systems-07-o1-c1', 'mission-ai-multi-agent-systems-07-o1', 1, 'multiple_choice', 'What does well-designed shared state actually need?', '{"question":"What does well-designed shared state actually need?","options":[{"id":"a","text":"Every agent should be free to read and write any field at any time with no rules"},{"id":"b","text":"Clearly named fields with a defined owner for writes, and clear rules for what every other agent may only read"},{"id":"c","text":"Shared state should never be readable by more than one agent"},{"id":"d","text":"Shared state is unnecessary if agents are well described"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-07-o2-c1', 'mission-ai-multi-agent-systems-07-o2', 1, 'drag_and_drop', 'Match each shared state field to the agent that owns it.', '{"items":[{"id":"i1","text":"verified_checksums"},{"id":"i2","text":"cross_reference_results"},{"id":"i3","text":"draft_findings"},{"id":"i4","text":"task_assignments"}],"targets":[{"id":"log_analyst","label":"Log analyst"},{"id":"cross_referencer","label":"Cross-referencer"},{"id":"findings_drafter","label":"Findings drafter"},{"id":"supervisor","label":"Supervisor"}]}'::jsonb, '{"correctMapping":{"i1":"log_analyst","i2":"cross_referencer","i3":"findings_drafter","i4":"supervisor"}}'::jsonb),

  ('mission-ai-multi-agent-systems-08-o1-c1', 'mission-ai-multi-agent-systems-08-o1', 1, 'multiple_choice', 'Why is giving every specialist the entire case history a problem, not a safety net?', '{"question":"Why is giving every specialist the entire case history a problem, not a safety net?","options":[{"id":"a","text":"It is not a problem, more context is always better"},{"id":"b","text":"It buries the one relevant fact a specialist actually needs under everything it does not, degrading its output instead of protecting it"},{"id":"c","text":"It makes every specialist run faster"},{"id":"d","text":"It removes the need for tool descriptions"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-08-o2-c1', 'mission-ai-multi-agent-systems-08-o2', 1, 'investigation', 'The findings drafter produced a vague write-up despite having every piece of information gathered in the case. Which evidence explains why?', '{"evidence":[{"id":"e1","label":"Context passed to findings drafter","detail":"Received the entire investigation history for all flagged records, including raw tool traces from the log analyst and cross-referencer, with no filtering to the one record it was drafting for"},{"id":"e2","label":"Findings drafter trace","detail":"Could not identify which details in the enormous context were actually relevant to the record it was assigned"},{"id":"e3","label":"Tool registry","detail":"draft_findings tool works correctly and is well described"}],"question":"Which evidence explains why the specialist''s output got worse despite having more context?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-multi-agent-systems-09-o1-c1', 'mission-ai-multi-agent-systems-09-o1', 1, 'multiple_choice', 'What is a race condition in a multi-agent system?', '{"question":"What is a race condition in a multi-agent system?","options":[{"id":"a","text":"Two agents competing to finish fastest for a reward"},{"id":"b","text":"Two agents reading and writing the same shared data at the same time with no coordination, so one agent''s update can be overwritten or missed based on timing alone"},{"id":"c","text":"An agent that runs slower than expected"},{"id":"d","text":"A deliberate design pattern for speeding up independent work"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-09-o2-c1', 'mission-ai-multi-agent-systems-09-o2', 1, 'investigation', 'Record ai-arc-0447''s status field shows only the cross-referencer''s update -- the log analyst''s earlier write is gone. Which evidence explains it?', '{"evidence":[{"id":"e1","label":"Shared state write log","detail":"Log analyst wrote a status update to ai-arc-0447 at 02:14:03. Cross-referencer read the record at 02:14:02, before that write landed, and wrote its own status over it at 02:14:05 with no check for a newer version"},{"id":"e2","label":"Tool registry","detail":"Both specialists'' write functions work correctly in isolation"},{"id":"e3","label":"Facilities log","detail":"Cipher Labs power draw is within normal range"}],"question":"Which evidence explains why one specialist''s update to the shared record disappeared?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-multi-agent-systems-10-o1-c1', 'mission-ai-multi-agent-systems-10-o1', 1, 'multiple_choice', 'What actually causes duplicated work between specialist agents?', '{"question":"What actually causes duplicated work between specialist agents?","options":[{"id":"a","text":"The specialists are using outdated tools"},{"id":"b","text":"No specialist has any way to see what another specialist has already checked, so each one re-derives ground it cannot see was already covered"},{"id":"c","text":"Duplicated work only happens when specialists are given identical instructions"},{"id":"d","text":"It happens randomly regardless of design"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-10-o2-c1', 'mission-ai-multi-agent-systems-10-o2', 1, 'investigation', 'The cross-referencer just spent four tool calls proving something the log analyst already established an hour earlier. Which evidence explains why nobody caught it?', '{"evidence":[{"id":"e1","label":"Shared state schema","detail":"Includes a checked_records field meant to log completed checks, but nothing in the cross-referencer''s flow requires reading it before starting new work"},{"id":"e2","label":"Cross-referencer trace","detail":"Started its four tool calls with no query against shared state first"},{"id":"e3","label":"Tool registry","detail":"All tools used returned correct data on every call"}],"question":"Which evidence explains why nobody caught the specialist redoing already-finished work?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-multi-agent-systems-11-o1-c1', 'mission-ai-multi-agent-systems-11-o1', 1, 'drag_and_drop', 'Match each responsibility to the team role that owns it.', '{"items":[{"id":"i1","text":"Reads and verifies each flagged record''s checksum and ingestion metadata"},{"id":"i2","text":"Checks each record''s claims against the rest of the archive for contradictions"},{"id":"i3","text":"Writes the final findings write-up for each record once evidence is in"},{"id":"i4","text":"Assigns work, tracks shared state, and reconciles anything that does not add up before it goes in the case file"}],"targets":[{"id":"log_analyst","label":"Log analyst"},{"id":"cross_referencer","label":"Cross-referencer"},{"id":"findings_drafter","label":"Findings drafter"},{"id":"supervisor","label":"Supervisor"}]}'::jsonb, '{"correctMapping":{"i1":"log_analyst","i2":"cross_referencer","i3":"findings_drafter","i4":"supervisor"}}'::jsonb),
  ('mission-ai-multi-agent-systems-11-o2-c1', 'mission-ai-multi-agent-systems-11-o2', 1, 'multiple_choice', 'Before the supervisor marks a record''s investigation complete, what must it check?', '{"question":"Before the supervisor marks a record''s investigation complete, what must it check?","options":[{"id":"a","text":"Nothing -- once every specialist reports a result, the case is done"},{"id":"b","text":"That the specialists'' results do not silently duplicate each other''s work and do not contradict each other''s conclusions before accepting them as final"},{"id":"c","text":"Only that every specialist responded within the time limit"},{"id":"d","text":"That the findings drafter used enough words in its write-up"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-multi-agent-systems-12-o1-c1', 'mission-ai-multi-agent-systems-12-o1', 1, 'investigation', 'Which evidence shows the specialists duplicated work and reached contradictory conclusions on the same record?', '{"evidence":[{"id":"e1","label":"Log analyst write-up","detail":"Concluded ai-arc-0447 was corrupted during a migration; marked complete; contains no reference to any other specialist''s findings"},{"id":"e2","label":"Cross-referencer write-up","detail":"Concluded ai-arc-0447 was deliberately tampered with; marked complete; also contains no reference to the log analyst''s write-up"},{"id":"e3","label":"Supervisor''s task log","detail":"Dispatched both specialists to ai-arc-0447 nine minutes apart, with no acknowledgment either was aware of the other''s assignment"},{"id":"e4","label":"Facilities log","detail":"Cipher Labs power draw is within normal range"}],"question":"Which evidence shows the specialists duplicated work and reached contradictory conclusions on the same record?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-multi-agent-systems-12-o2-c1', 'mission-ai-multi-agent-systems-12-o2', 1, 'investigation', 'What is actually missing from the team''s design that let this happen?', '{"evidence":[{"id":"e1","label":"Supervisor design","detail":"No context boundary tells either specialist what the other has already been assigned, and no step reconciles conflicting write-ups before the case is marked complete"},{"id":"e2","label":"Shared state usage","detail":"The checked_records field exists specifically to prevent duplicate assignment, but neither the supervisor''s dispatch logic nor either specialist''s flow requires reading it first"},{"id":"e3","label":"Tool registry","detail":"Every tool both specialists used returned correct data on every call"}],"question":"What is actually missing from the team''s design that let this happen?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-multi-agent-systems-12-o3-c1', 'mission-ai-multi-agent-systems-12-o3', 1, 'multiple_choice', 'Given specialists that duplicated work and reached contradictory conclusions with nobody catching it, what is the correct engineered fix?', '{"question":"Given specialists that duplicated work and reached contradictory conclusions with nobody catching it, what is the correct engineered fix?","options":[{"id":"a","text":"Give every specialist the entire investigation history so nothing is ever missed"},{"id":"b","text":"Enforce real context boundaries so specialists know what is already assigned, require a shared dedup check before starting new work, and add a conflict-resolution step where the supervisor reconciles contradictory conclusions before finalizing the case"},{"id":"c","text":"Remove the supervisor so specialists coordinate directly with no oversight"},{"id":"d","text":"Replace the whole team with a single larger agent"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-multi-agent-systems-12-o4-c1', 'mission-ai-multi-agent-systems-12-o4', 1, 'boss_encounter', 'Having read the trace, diagnosed the missing safeguards, and chosen the fix, state what happened and how to prevent it, in one sentence.', '{"stages":[{"objectiveRef":"mission-ai-multi-agent-systems-12-o1","label":"Read the trace"},{"objectiveRef":"mission-ai-multi-agent-systems-12-o2","label":"Diagnose the root cause"},{"objectiveRef":"mission-ai-multi-agent-systems-12-o3","label":"Choose the fix"}],"task":"State the conclusion in one sentence: without real context boundaries, the specialist agents stepped on each other -- duplicating work, contradicting each other''s conclusions, and burning through budget doing it -- proving more agents is not automatically a better investigation, and the team now needs a shared dedup check and a conflict-resolution step before it runs again."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-multi-agent-systems-12-o1","mission-ai-multi-agent-systems-12-o2","mission-ai-multi-agent-systems-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-multi-agent-systems-01-o1-c1', 'orientation', 'Think about what happens to context and tool choices, not whether the agent literally crashes.', 10, 1),
  ('mission-ai-multi-agent-systems-01-o1-c1', 'solution', 'It degrades quietly -- context fills with irrelevant history, tool choices get less reliable, and nothing in its own output explains why.', 20, 2),
  ('mission-ai-multi-agent-systems-01-o2-c1', 'orientation', 'A single, well-scoped task is still fine. Several unrelated jobs stacked on one agent is not.', 10, 1),
  ('mission-ai-multi-agent-systems-01-o2-c1', 'solution', 'Still fine: the single checksum check, the clear tool choice. Needs a split: the agent covering three jobs at once, and the agent holding unrelated history it does not need.', 20, 2),

  ('mission-ai-multi-agent-systems-02-o1-c1', 'orientation', 'Ask whether the supervisor does the domain work itself, or decides who does.', 10, 1),
  ('mission-ai-multi-agent-systems-02-o1-c1', 'solution', 'A supervisor decides which specialist handles a task, dispatches it, and makes sense of the result -- it does not do the domain work itself.', 20, 2),
  ('mission-ai-multi-agent-systems-02-o2-c1', 'orientation', 'Nothing can be dispatched before a specialist has been chosen.', 10, 1),
  ('mission-ai-multi-agent-systems-02-o2-c1', 'concept', 'The next assignment can only be decided once the current result is actually back and read.', 20, 2),
  ('mission-ai-multi-agent-systems-02-o2-c1', 'solution', 'Receive the task, choose the specialist, dispatch and wait, then read the result and decide the next assignment or completion.', 30, 3),

  ('mission-ai-multi-agent-systems-03-o1-c1', 'orientation', 'The specialist is still a full agent underneath. What changes is how the caller sees it.', 10, 1),
  ('mission-ai-multi-agent-systems-03-o1-c1', 'solution', 'Agents-as-tools wraps a specialist in the same contract as any tool -- name, input, output -- while it keeps running its own reasoning loop underneath.', 20, 2),
  ('mission-ai-multi-agent-systems-03-o2-c1', 'orientation', 'The specialist did not malfunction. It was never told what it was being asked for.', 10, 1),
  ('mission-ai-multi-agent-systems-03-o2-c1', 'solution', 'e1: the specialist registry never defined an input or output contract for cross-referencer, so the call carried no usable instruction.', 20, 2),

  ('mission-ai-multi-agent-systems-04-o1-c1', 'orientation', 'Ask who is left waiting for a result once the action starts.', 10, 1),
  ('mission-ai-multi-agent-systems-04-o1-c1', 'solution', 'Agents-as-tools leaves the caller waiting for a return value. A handoff transfers ownership completely -- the receiving agent takes it from there.', 20, 2),
  ('mission-ai-multi-agent-systems-04-o2-c1', 'orientation', 'A single question with a single answer expected back is not the same as giving something away entirely.', 10, 1),
  ('mission-ai-multi-agent-systems-04-o2-c1', 'solution', 'Agents-as-tools: the single checksum check and the single claim check. Handoff: the two cases where the whole task and its context transfer over completely.', 20, 2),

  ('mission-ai-multi-agent-systems-05-o1-c1', 'orientation', 'One of these stays involved across the whole task. The other makes one decision and is done.', 10, 1),
  ('mission-ai-multi-agent-systems-05-o1-c1', 'solution', 'A router classifies and dispatches once and steps away. A supervisor stays in the loop, coordinating specialists across the whole task.', 20, 2),
  ('mission-ai-multi-agent-systems-05-o2-c1', 'orientation', 'Nothing can be dispatched before the classification decision is actually made.', 10, 1),
  ('mission-ai-multi-agent-systems-05-o2-c1', 'concept', 'Unlike a supervisor loop, the router''s involvement ends the moment dispatch happens.', 20, 2),
  ('mission-ai-multi-agent-systems-05-o2-c1', 'solution', 'A request arrives, the router classifies it, dispatches it to the matching specialist, and its own job ends there.', 30, 3),

  ('mission-ai-multi-agent-systems-06-o1-c1', 'orientation', 'A fixed plan cannot react to what a step actually finds. Ask what the orchestrator does differently.', 10, 1),
  ('mission-ai-multi-agent-systems-06-o1-c1', 'solution', 'An orchestrator breaks the task into subtasks dynamically as it goes, assigning each to a worker based on what has actually been found.', 20, 2),
  ('mission-ai-multi-agent-systems-06-o2-c1', 'orientation', 'Ask whether the item decides the breakdown, or actually performs one piece of work.', 10, 1),
  ('mission-ai-multi-agent-systems-06-o2-c1', 'solution', 'Orchestrator: deciding new subtasks and reassessing the breakdown. Worker: the actual cross-referencing and drafting calls.', 20, 2),

  ('mission-ai-multi-agent-systems-07-o1-c1', 'orientation', 'A shared space with no ownership rules is not a design, it is a race waiting to happen.', 10, 1),
  ('mission-ai-multi-agent-systems-07-o1-c1', 'solution', 'Good shared state has clearly named fields with one defined owner for writes, and clear read-only access for everyone else.', 20, 2),
  ('mission-ai-multi-agent-systems-07-o2-c1', 'orientation', 'Match each field to the one specialist whose job actually produces that information.', 10, 1),
  ('mission-ai-multi-agent-systems-07-o2-c1', 'solution', 'verified_checksums belongs to the log analyst, cross_reference_results to the cross-referencer, draft_findings to the findings drafter, task_assignments to the supervisor.', 20, 2),

  ('mission-ai-multi-agent-systems-08-o1-c1', 'orientation', 'More context is not automatically more helpful. Ask what it does to what actually matters.', 10, 1),
  ('mission-ai-multi-agent-systems-08-o1-c1', 'solution', 'It buries the one relevant fact under everything irrelevant, degrading the specialist''s output instead of protecting it.', 20, 2),
  ('mission-ai-multi-agent-systems-08-o2-c1', 'orientation', 'The tool worked fine. The problem is what the specialist was handed before it even started.', 10, 1),
  ('mission-ai-multi-agent-systems-08-o2-c1', 'solution', 'e1: the findings drafter received the entire investigation history with no filtering, so it could not isolate what actually mattered for its one record.', 20, 2),

  ('mission-ai-multi-agent-systems-09-o1-c1', 'orientation', 'Think about what happens when two agents touch the same data with no coordination on timing.', 10, 1),
  ('mission-ai-multi-agent-systems-09-o1-c1', 'solution', 'A race condition is two agents reading and writing the same shared data at once with no coordination, so an update can be overwritten based on timing alone.', 20, 2),
  ('mission-ai-multi-agent-systems-09-o2-c1', 'orientation', 'Both writes worked individually. Look at when each one actually happened.', 10, 1),
  ('mission-ai-multi-agent-systems-09-o2-c1', 'solution', 'e1: the cross-referencer read the record before the log analyst''s write landed, then overwrote it with no check for a newer version.', 20, 2),

  ('mission-ai-multi-agent-systems-10-o1-c1', 'orientation', 'The cause is not about model quality. It is about what a specialist can and cannot see.', 10, 1),
  ('mission-ai-multi-agent-systems-10-o1-c1', 'solution', 'No specialist can see what another has already checked, so each one re-derives ground it cannot see was already covered.', 20, 2),
  ('mission-ai-multi-agent-systems-10-o2-c1', 'orientation', 'A dedup mechanism only helps if something is actually required to consult it.', 10, 1),
  ('mission-ai-multi-agent-systems-10-o2-c1', 'solution', 'e1: the checked_records field exists to prevent this, but nothing in the cross-referencer''s flow required reading it before starting new work.', 20, 2),

  ('mission-ai-multi-agent-systems-11-o1-c1', 'orientation', 'Match each responsibility to the one role whose job description actually covers it.', 10, 1),
  ('mission-ai-multi-agent-systems-11-o1-c1', 'solution', 'Log analyst verifies records, cross-referencer checks claims against the archive, findings drafter writes conclusions, supervisor assigns work and reconciles the results.', 20, 2),
  ('mission-ai-multi-agent-systems-11-o2-c1', 'orientation', 'A result being submitted is not the same as a result being checked against the others.', 10, 1),
  ('mission-ai-multi-agent-systems-11-o2-c1', 'solution', 'The supervisor must check that results do not silently duplicate each other''s work and do not contradict each other''s conclusions before accepting them as final.', 20, 2),

  ('mission-ai-multi-agent-systems-12-o1-c1', 'orientation', 'Two specialists both finished the same record. Compare what each one actually concluded.', 10, 1),
  ('mission-ai-multi-agent-systems-12-o1-c1', 'concept', 'Both write-ups being marked complete is not proof the investigation succeeded twice -- it is proof neither specialist knew about the other.', 20, 2),
  ('mission-ai-multi-agent-systems-12-o1-c1', 'solution', 'e1 and e2: the log analyst concluded corruption and the cross-referencer concluded tampering, on the same record, each unaware of the other''s write-up.', 30, 3),
  ('mission-ai-multi-agent-systems-12-o2-c1', 'orientation', 'The tools all worked correctly. The gap is in what the supervisor and specialists were required to check first.', 10, 1),
  ('mission-ai-multi-agent-systems-12-o2-c1', 'solution', 'e1 and e2: no context boundary or reconciliation step existed, and the dedup field in shared state was never required reading before either specialist started.', 30, 3),
  ('mission-ai-multi-agent-systems-12-o3-c1', 'orientation', 'The fix targets the missing boundaries and the missing reconciliation step, not the tools or the model size.', 10, 1),
  ('mission-ai-multi-agent-systems-12-o3-c1', 'solution', 'Enforce context boundaries, require a shared dedup check before new work starts, and add a conflict-resolution step before the supervisor finalizes the case.', 20, 2),
  ('mission-ai-multi-agent-systems-12-o4-c1', 'orientation', 'Combine what the trace showed, what was missing, and what the fix actually adds.', 15, 1),
  ('mission-ai-multi-agent-systems-12-o4-c1', 'solution', 'Without real context boundaries, the specialists duplicated work and contradicted each other while burning budget doing it -- proving more agents alone is not a better investigation, and both a dedup check and a conflict-resolution step now need to be built in.', 25, 2);
