-- Robotics/Embedded/IoT pathway ("Vector Division") Act 2 -- "Electric
-- Language" content, under world-vec-electric-language (already inserted
-- separately). 1 campaign, 2 operations, 12 missions (11 lessons + boss),
-- following the same campaigns -> operations -> missions -> dialogue ->
-- objectives -> challenges -> hints pattern as Act 1. No new ChallengeType
-- needed -- reuses story_dialogue, multiple_choice, drag_and_drop,
-- investigation, interactive_diagram, browser_simulation (generic console
-- fallback) and boss_encounter. Tomas Vey's first Act speaking; introduces
-- foundational electronics (voltage/current/resistance through multimeter
-- workflow) as Vector Division reads the recovered door controller board
-- as a physical circuit before it ever reads firmware.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-electric-language', 'world-vec-electric-language', 'electric-language', '1B - Electric Language', 'Learn the vocabulary of electricity itself -- voltage, current, resistance, power, analog versus digital, logic levels, pull-ups and pull-downs, breadboards, LEDs, buttons and the multimeter -- while Tomas Vey reads the recovered door controller board as a plain circuit before anyone touches its firmware.', 2);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-electric-language-1', 'campaign-vec-electric-language', 'reading-the-board', 'Reading the Board', 'Voltage, current, resistance, Ohm''s law, power and energy, analog versus digital, and logic levels.', 1),
  ('operation-vec-electric-language-2', 'campaign-vec-electric-language', 'the-silent-circuit', 'The Silent Circuit', 'Pull-ups and pull-downs, breadboards, the LED and resistor lab, buttons and switches, debouncing and the multimeter workflow.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-electric-language-01', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'voltage-current-resistance', 'Voltage, Current and Resistance', 'Tomas Vey claims the recovered door controller board for Vector Division''s bench. Before anyone reads a single line of its firmware, the board has to be understood as a physical circuit -- voltages, currents, and the electrical assumptions the whole rest of it was built on.', 'beginner', ARRAY['imani','tomas','byte'], null, null, '{"type":"simulation","simulationId":"voltage-current-resistance-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 1),
  ('mission-vec-electric-language-02', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'ohms-law-intuition', 'Ohm''s Law Intuition', 'Three quantities, one relationship. Ohm''s law is not a formula to memorize -- it is a way of predicting what a circuit will do before it does it.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"ohms-law-intuition-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-vec-electric-language-03', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'power-and-energy', 'Power and Energy', 'Voltage and current together tell you how hard a circuit is working right now. Power is that number -- and it is the number that decides what melts.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"power-and-energy-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 3),
  ('mission-vec-electric-language-04', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'analog-vs-digital', 'Analog vs Digital', 'The board''s voltages do not stop being analog just because the firmware will eventually read them as ones and zeros. Digital is an interpretation layered on top of an analog world.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-electric-language-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"analog-vs-digital-sim"}'::jsonb, '{"xp":100,"credits":20}'::jsonb, false, 4),
  ('mission-vec-electric-language-05', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'logic-levels', 'Logic Levels', 'A digital chip does not require an exact voltage to read a one or a zero. It only requires the voltage to land inside the right range -- and the board''s ranges are not automatically the same as any other chip''s.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"logic-levels-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 5),
  ('mission-vec-electric-language-06', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-1', 'pull-up-and-pull-down', 'Pull-Up and Pull-Down Concepts', 'An input line with nothing driving it does not simply read zero. Left alone, it floats -- and a floating line is exactly the kind of thing a decades-old designer would have refused to leave to chance.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-electric-language-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"pull-up-pull-down-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 6),
  ('mission-vec-electric-language-07', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'breadboards-and-circuits', 'Breadboards and Circuits', 'Before touching the board itself, Tomas has the player build the same kind of circuit fresh, on a breadboard, so the rows and rails stop being an abstraction.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"breadboards-circuits-sim"}'::jsonb, '{"xp":120,"credits":20}'::jsonb, false, 7),
  ('mission-vec-electric-language-08', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'led-and-resistor-lab', 'LED and Resistor Lab', 'An LED with no current-limiting resistor does not glow brighter. It dies -- and Tomas would rather the player learn that on the bench than on the door''s only recovered board.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"led-resistor-lab-sim"}'::jsonb, '{"xp":120,"credits":25}'::jsonb, false, 8),
  ('mission-vec-electric-language-09', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'buttons-and-switches', 'Buttons and Switches', 'A button is nothing but a switch wired into a circuit -- but the board has one, and its wiring alone already suggests what the designer expected to happen when nobody is touching it.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-electric-language-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"buttons-switches-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 9),
  ('mission-vec-electric-language-10', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'debouncing', 'Debouncing', 'A mechanical contact does not close cleanly. For a few milliseconds it chatters -- and a controller reading too fast sees a dozen presses where a human made exactly one.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-electric-language-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"debouncing-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 10),
  ('mission-vec-electric-language-11', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'multimeter-workflow', 'Multimeter Workflow', 'Tomas hands over the one tool that turns every concept so far into a measurement. Set it wrong and it either lies to the player or trips a fuse -- set it right and the board finally starts answering questions.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-electric-language-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"multimeter-workflow-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 11),
  ('mission-vec-electric-language-12', 'world-vec-electric-language', 'campaign-vec-electric-language', 'operation-vec-electric-language-2', 'the-silent-circuit', 'The Silent Circuit', 'One section of the recovered board reads nothing at all. Everything this Act taught, turned on that single silent line -- before Vector Division can trust anything the firmware claims to say next.', 'boss', ARRAY['imani','tomas','byte'], '{"requiredMissionIds":["mission-vec-electric-language-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"silent-circuit-boss-sim"}'::jsonb, '{"xp":420,"credits":90,"badgeIds":["the-silent-circuit"],"skillXp":{"robotics_fundamentals":60}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-electric-language-01', 1, 'imani', 'The door''s controller board is off the maintenance bus and off the door. It is on a bench now, in Vector Division, and it is not going anywhere until someone can explain what it actually is.'),
  ('mission-vec-electric-language-01', 2, 'tomas', 'Tomas Vey. I do not read firmware until I can already predict what the copper underneath it is doing. Everyone in this room is about to learn electricity the way I did -- by hand, before by tool.'),
  ('mission-vec-electric-language-01', 3, 'tomas', 'Three quantities explain almost everything on this board before we power it on. Voltage is electrical pressure -- the push behind a wire, measured between two points. Current is the actual flow of charge, measured through a wire. Resistance is whatever opposes that flow.'),
  ('mission-vec-electric-language-01', 4, 'tomas', 'None of the three exist alone. A voltage with nowhere to push current is useless. A path with no resistance is a short. This board balances all three on every single trace, and it has for decades without anyone checking.'),
  ('mission-vec-electric-language-01', 5, 'byte', 'I can read firmware all day and it will not tell me any of that. This is the first Act where I am not the expert in the room.'),

  ('mission-vec-electric-language-02', 1, 'tomas', 'Ohm''s law: voltage equals current times resistance. Do not memorize it as algebra. Memorize it as a story -- push harder, more flows; add resistance, less flows, for the same push.'),
  ('mission-vec-electric-language-02', 2, 'tomas', 'Which means if you know any two of the three, the board tells you the third without a single line of firmware. That is the entire reason we start here.'),

  ('mission-vec-electric-language-03', 1, 'tomas', 'Power is voltage times current. It is the rate at which a circuit is actually doing work -- or, on a board this old, the rate at which a mistake turns into smoke.'),
  ('mission-vec-electric-language-03', 2, 'tomas', 'Energy is power sustained over time. A component rated for a certain power can survive a brief spike it could never survive continuously. That distinction is the difference between a working board and a dead one.'),

  ('mission-vec-electric-language-04', 1, 'tomas', 'An analog voltage can be anything continuously between two limits. A digital signal only ever means one of a small number of discrete states -- almost always just two, high and low.'),
  ('mission-vec-electric-language-04', 2, 'byte', 'But the wire itself never stops being analog. Digital is a rule someone chose for interpreting a voltage, layered on top of physics that does not know or care about that rule.'),
  ('mission-vec-electric-language-04', 3, 'tomas', 'Which is exactly why we read this board with a meter before we ever read it with software. The voltage is the ground truth. "High" and "low" are just labels we agree to put on it.'),

  ('mission-vec-electric-language-05', 1, 'tomas', 'Every digital chip has a logic family, and every family defines two thresholds: below one voltage is guaranteed low, above another is guaranteed high. Anything in between is undefined -- neither state, reliably.'),
  ('mission-vec-electric-language-05', 2, 'tomas', 'This board predates the chips on our modern gear by decades. Its thresholds are not automatically ours. Assuming otherwise is how you misread a perfectly healthy line as broken.'),

  ('mission-vec-electric-language-06', 1, 'tomas', 'Disconnect a digital input from everything and it does not settle at zero. It floats -- picking up stray voltage from whatever is nearby, reading high one moment and low the next for no real reason.'),
  ('mission-vec-electric-language-06', 2, 'tomas', 'A pull-up resistor quietly holds a line high until something actively pulls it low. A pull-down does the reverse. Either way, the line always has a defined rest state -- never left to chance.'),
  ('mission-vec-electric-language-06', 3, 'byte', 'Which means if this board has a pull-down on some line, that line was always meant to sit low until a specific event pulled it high. A silent line with no pull could just mean nothing is driving it at all.'),

  ('mission-vec-electric-language-07', 1, 'tomas', 'A breadboard''s rows are internally connected in short strips, and its outer rails run the full length of the board for power and ground. Nothing about it is magic -- it is just a fast way to wire without solder.'),
  ('mission-vec-electric-language-07', 2, 'tomas', 'Build the same section of circuit the board is running, fresh, on a breadboard you can see into. If you cannot explain a breadboard version of it, you cannot yet explain the real one.'),

  ('mission-vec-electric-language-08', 1, 'tomas', 'An LED is not a resistor. Wired straight across a supply with nothing else in the path, it draws far more current than it can survive and burns out in an instant.'),
  ('mission-vec-electric-language-08', 2, 'tomas', 'A single resistor in series limits that current to something safe, using exactly the relationship you already learned. Get the resistor value wrong and the LED either stays dark or dies -- there is no comfortable middle.'),

  ('mission-vec-electric-language-09', 1, 'tomas', 'A button or switch is nothing exotic. It simply completes or breaks a path in a circuit -- the interesting part was never the button, it is always what the rest of the circuit does when the path changes.'),
  ('mission-vec-electric-language-09', 2, 'byte', 'The board has one input wired exactly like that. Whether it is pulled up or pulled down when the button is not pressed tells us what state the designer expected as normal.'),

  ('mission-vec-electric-language-10', 1, 'tomas', 'Zoom in far enough on a mechanical contact closing and it is not one clean transition. It bounces -- opening and closing several times in a few milliseconds before it settles.'),
  ('mission-vec-electric-language-10', 2, 'tomas', 'A controller fast enough to see that bounce can register a dozen presses from one real one. Debouncing, in hardware or software, is simply waiting out that noisy window before trusting the reading.'),
  ('mission-vec-electric-language-10', 3, 'byte', 'Which matters here because the board''s original designers had to solve that same problem decades before either of us existed, with far less patience for waiting.'),

  ('mission-vec-electric-language-11', 1, 'tomas', 'Every measurement needs the meter set correctly first. Voltage: probes in parallel across the two points. Current: probes in series, breaking the circuit to route the flow through the meter. Resistance: only ever on power that is off.'),
  ('mission-vec-electric-language-11', 2, 'tomas', 'Get that order wrong -- current probes across a voltage, for instance -- and you do not just get a bad reading. You can blow the meter''s fuse or short the board outright.'),
  ('mission-vec-electric-language-11', 3, 'tomas', 'Everything up to now was theory so this tool would make sense the moment you picked it up. Now it is time to actually probe the board.'),

  ('mission-vec-electric-language-12', 1, 'imani', 'One section of the board reads nothing. Not a fault code, not noise -- just silence where a signal should be. Before we trust anything the firmware later tells us, we explain that silence with a meter.'),
  ('mission-vec-electric-language-12', 2, 'tomas', 'Everything this Act taught you is sitting in that one line. Logic levels, pull direction, and what a healthy versus a starved reading actually looks like on the meter. Walk it in order.'),
  ('mission-vec-electric-language-12', 3, 'byte', 'I keep wanting to jump straight to the firmware and ask it what is wrong. Tomas keeps reminding me the firmware cannot answer for a wire it never gets to see.'),
  ('mission-vec-electric-language-12', 4, 'tomas', 'Because it cannot. Diagnose the line the way I taught you, not the way Byte wants to guess it.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-electric-language-01-o1', 'mission-vec-electric-language-01', 1, 'Tell the three apart', 'Match each quantity -- voltage, current, resistance -- to its accurate definition.'),
  ('mission-vec-electric-language-01-o2', 'mission-vec-electric-language-01', 2, 'Apply it to the board', 'Identify which piece of bench evidence describes the board''s resistance.'),

  ('mission-vec-electric-language-02-o1', 'mission-vec-electric-language-02', 1, 'Predict with Ohm''s law', 'Judge how current changes when resistance increases at a fixed voltage.'),
  ('mission-vec-electric-language-02-o2', 'mission-vec-electric-language-02', 2, 'Solve for the missing value', 'Given voltage and resistance, choose the correct current for a board trace.'),

  ('mission-vec-electric-language-03-o1', 'mission-vec-electric-language-03', 1, 'Compute power', 'Choose the correct power draw given a trace''s voltage and current.'),
  ('mission-vec-electric-language-03-o2', 'mission-vec-electric-language-03', 2, 'Tell power from energy', 'Choose the accurate distinction between power and energy.'),

  ('mission-vec-electric-language-04-o1', 'mission-vec-electric-language-04', 1, 'Sort the signals', 'Sort each board reading into analog or digital.'),
  ('mission-vec-electric-language-04-o2', 'mission-vec-electric-language-04', 2, 'Explain the layering', 'Choose the accurate description of how digital relates to the underlying analog voltage.'),

  ('mission-vec-electric-language-05-o1', 'mission-vec-electric-language-05', 1, 'Read the thresholds', 'Judge whether a measured voltage reads as high, low, or undefined for a given logic family.'),
  ('mission-vec-electric-language-05-o2', 'mission-vec-electric-language-05', 2, 'Avoid the assumption', 'Find the evidence proving the board''s logic family is not automatically the same as modern gear.'),

  ('mission-vec-electric-language-06-o1', 'mission-vec-electric-language-06', 1, 'Explain a floating line', 'Choose the accurate description of what happens to an undriven digital input.'),
  ('mission-vec-electric-language-06-o2', 'mission-vec-electric-language-06', 2, 'Tell pull-up from pull-down', 'Sort each resistor description into pull-up or pull-down.'),

  ('mission-vec-electric-language-07-o1', 'mission-vec-electric-language-07', 1, 'Read the breadboard layout', 'Order a breadboard build from power source to completed path.'),

  ('mission-vec-electric-language-08-o1', 'mission-vec-electric-language-08', 1, 'Explain the resistor''s job', 'Choose the accurate reason an LED needs a series resistor.'),
  ('mission-vec-electric-language-08-o2', 'mission-vec-electric-language-08', 2, 'Pick a safe value', 'Given the LED''s rating and the supply voltage, choose the resistor that keeps current in a safe range.'),

  ('mission-vec-electric-language-09-o1', 'mission-vec-electric-language-09', 1, 'Read the board''s button wiring', 'Find the evidence describing how the board''s input line is wired at rest.'),
  ('mission-vec-electric-language-09-o2', 'mission-vec-electric-language-09', 2, 'Judge the expected normal state', 'Based on that wiring, judge what state the designer expected when the button is untouched.'),

  ('mission-vec-electric-language-10-o1', 'mission-vec-electric-language-10', 1, 'Explain contact bounce', 'Choose the accurate description of why a mechanical switch needs debouncing.'),
  ('mission-vec-electric-language-10-o2', 'mission-vec-electric-language-10', 2, 'Spot the undebounced read', 'Find the evidence showing a reading taken without waiting out the bounce window.'),

  ('mission-vec-electric-language-11-o1', 'mission-vec-electric-language-11', 1, 'Set up each measurement', 'Match each measurement type -- voltage, current, resistance -- to its correct probe technique.'),
  ('mission-vec-electric-language-11-o2', 'mission-vec-electric-language-11', 2, 'Diagnose from a reading', 'Given a meter reading on the board, judge what it implies about that trace.'),

  ('mission-vec-electric-language-12-o1', 'mission-vec-electric-language-12', 1, 'Check the logic level', 'Judge whether the silent line''s idle voltage falls in a defined logic range for its family.'),
  ('mission-vec-electric-language-12-o2', 'mission-vec-electric-language-12', 2, 'Check the pull direction', 'Find the evidence showing the silent section is missing its expected pull resistor.'),
  ('mission-vec-electric-language-12-o3', 'mission-vec-electric-language-12', 3, 'Check the meter evidence', 'Given the multimeter readings across the silent section, judge where the path actually breaks.'),
  ('mission-vec-electric-language-12-o4', 'mission-vec-electric-language-12', 4, 'Name the diagnosis', 'Having checked logic level, pull direction and the meter evidence, state what the silent circuit actually is and what it means about the board as a whole.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-electric-language-01-o1-c1', 'mission-vec-electric-language-01-o1', 1, 'drag_and_drop', 'Match each quantity to its accurate definition.', '{"items":[{"id":"i1","text":"Voltage"},{"id":"i2","text":"Current"},{"id":"i3","text":"Resistance"}],"targets":[{"id":"t1","label":"The electrical pressure pushing charge between two points, measured across a component"},{"id":"t2","label":"The actual flow of charge through a path, measured through a component"},{"id":"t3","label":"Whatever opposes that flow along the path"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),
  ('mission-vec-electric-language-01-o2-c1', 'mission-vec-electric-language-01-o2', 1, 'investigation', 'Which piece of bench evidence describes the board''s resistance?', '{"evidence":[{"id":"e1","label":"Meter reading","detail":"12 volts measured across the input header with the board unpowered"},{"id":"e2","label":"Component note","detail":"A resistor on the input trace measures 10,000 ohms end to end"},{"id":"e3","label":"Trace log","detail":"38 milliamps flowing through the same input trace once powered"}],"question":"Which piece of bench evidence describes the board''s resistance?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-electric-language-02-o1-c1', 'mission-vec-electric-language-02-o1', 1, 'multiple_choice', 'At a fixed voltage, if resistance on a trace increases, what happens to current?', '{"question":"At a fixed voltage, if resistance on a trace increases, what happens to current?","options":[{"id":"a","text":"Current increases along with resistance"},{"id":"b","text":"Current decreases -- more opposition to flow means less charge moves for the same push"},{"id":"c","text":"Current stays exactly the same"},{"id":"d","text":"Voltage and current are unrelated to resistance"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-electric-language-02-o2-c1', 'mission-vec-electric-language-02-o2', 1, 'multiple_choice', 'A board trace measures 5 volts across a 1,000 ohm resistor. What current is flowing?', '{"question":"A board trace measures 5 volts across a 1,000 ohm resistor. What current is flowing?","options":[{"id":"a","text":"5 amps"},{"id":"b","text":"0.005 amps (5 milliamps)"},{"id":"c","text":"5,000 amps"},{"id":"d","text":"1,000 amps"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-electric-language-03-o1-c1', 'mission-vec-electric-language-03-o1', 1, 'multiple_choice', 'A trace carries 5 volts at 0.1 amps. What power is it drawing?', '{"question":"A trace carries 5 volts at 0.1 amps. What power is it drawing?","options":[{"id":"a","text":"0.5 watts"},{"id":"b","text":"5 watts"},{"id":"c","text":"50 watts"},{"id":"d","text":"0.05 watts"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-electric-language-03-o2-c1', 'mission-vec-electric-language-03-o2', 1, 'multiple_choice', 'Power and energy differ in that...', '{"question":"Power and energy differ in that...","options":[{"id":"a","text":"They are the same quantity with different names"},{"id":"b","text":"Power is the rate of doing work right now; energy is that power sustained over time, which is why a brief spike can be survivable where a continuous one is not"},{"id":"c","text":"Energy is only relevant to batteries, power only to wired circuits"},{"id":"d","text":"Power is measured in volts, energy in amps"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-electric-language-04-o1-c1', 'mission-vec-electric-language-04-o1', 1, 'drag_and_drop', 'Sort each board reading into analog or digital.', '{"items":[{"id":"s1","text":"A supply rail voltage drifting continuously between 4.8V and 5.1V"},{"id":"s2","text":"An input line the controller only ever treats as high or low"},{"id":"s3","text":"A raw sensor voltage varying smoothly with temperature"},{"id":"s4","text":"A status line with exactly two defined states, asserted or not"}],"targets":[{"id":"analog","label":"Analog"},{"id":"digital","label":"Digital"}]}'::jsonb, '{"correctMapping":{"s1":"analog","s2":"digital","s3":"analog","s4":"digital"}}'::jsonb),
  ('mission-vec-electric-language-04-o2-c1', 'mission-vec-electric-language-04-o2', 1, 'multiple_choice', 'How does a digital reading relate to the actual voltage on the wire?', '{"question":"How does a digital reading relate to the actual voltage on the wire?","options":[{"id":"a","text":"The wire itself becomes digital, and the voltage stops varying continuously"},{"id":"b","text":"The wire stays a continuous analog voltage; \"digital\" is only an interpretation rule applied on top of that voltage by whatever reads it"},{"id":"c","text":"Digital signals do not use voltage at all"},{"id":"d","text":"Analog and digital are two separate wires that never share a value"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-electric-language-05-o1-c1', 'mission-vec-electric-language-05-o1', 1, 'multiple_choice', 'A logic family defines low as under 0.8V and high as over 2.0V. A line reads 1.4V. How does it read?', '{"question":"A logic family defines low as under 0.8V and high as over 2.0V. A line reads 1.4V. How does it read?","options":[{"id":"a","text":"Reliably high"},{"id":"b","text":"Reliably low"},{"id":"c","text":"Undefined -- inside the gap between the two thresholds, neither state reliably"},{"id":"d","text":"Impossible, that voltage cannot occur"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-vec-electric-language-05-o2-c1', 'mission-vec-electric-language-05-o2', 1, 'investigation', 'Which evidence proves the board''s logic family is not automatically the same as our modern gear?', '{"evidence":[{"id":"e1","label":"Component date code","detail":"The board''s primary logic chip carries a manufacture date decades before any hardware currently on Vector Division''s bench"},{"id":"e2","label":"Physical note","detail":"The board is roughly the size of a paperback book"},{"id":"e3","label":"Power log","detail":"The board draws power from a standard wall adapter"}],"question":"Which evidence proves the board''s logic family is not automatically the same as our modern gear?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-electric-language-06-o1-c1', 'mission-vec-electric-language-06-o1', 1, 'multiple_choice', 'A digital input with nothing connected to it will...', '{"question":"A digital input with nothing connected to it will...","options":[{"id":"a","text":"Always read a clean, stable zero"},{"id":"b","text":"Float -- pick up stray voltage and read unpredictably, sometimes high and sometimes low with no real driver"},{"id":"c","text":"Always read a clean, stable one"},{"id":"d","text":"Damage the chip immediately"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-electric-language-06-o2-c1', 'mission-vec-electric-language-06-o2', 1, 'drag_and_drop', 'Sort each resistor description into pull-up or pull-down.', '{"items":[{"id":"p1","text":"A resistor tied between the input line and the positive supply rail, holding the line high at rest"},{"id":"p2","text":"A resistor tied between the input line and ground, holding the line low at rest"},{"id":"p3","text":"A resistor that a button press pulls low, meaning it was resting high"},{"id":"p4","text":"A resistor that a button press pulls high, meaning it was resting low"}],"targets":[{"id":"pullup","label":"Pull-up"},{"id":"pulldown","label":"Pull-down"}]}'::jsonb, '{"correctMapping":{"p1":"pullup","p2":"pulldown","p3":"pullup","p4":"pulldown"}}'::jsonb),

  ('mission-vec-electric-language-07-o1-c1', 'mission-vec-electric-language-07-o1', 1, 'interactive_diagram', 'Order the breadboard build from power source to completed path.', '{"diagramId":"breadboard-build","hotspots":[{"id":"supply","label":"Power supply connected to the rail","explanation":"The rail carries a fixed voltage down the length of the board."},{"id":"row","label":"Component placed across a row","explanation":"A row''s holes are internally connected in a short strip, wiring the component in."},{"id":"jumper","label":"Jumper wire completing the path","explanation":"A jumper carries the connection from the row back to a rail or another row."},{"id":"verify","label":"Meter verifies continuity","explanation":"Checking continuity confirms the path is actually complete before power is applied."}],"task":"Order the steps of the breadboard build from power source to a verified completed path."}'::jsonb, '{"correctOrderIds":["supply","row","jumper","verify"]}'::jsonb),

  ('mission-vec-electric-language-08-o1-c1', 'mission-vec-electric-language-08-o1', 1, 'multiple_choice', 'Why does an LED need a series resistor rather than being wired directly across a supply?', '{"question":"Why does an LED need a series resistor rather than being wired directly across a supply?","options":[{"id":"a","text":"It does not, resistors are only for decoration"},{"id":"b","text":"An LED alone offers very little resistance to current, so without something limiting the flow it draws far more current than it can survive and burns out"},{"id":"c","text":"The resistor changes the LED''s color"},{"id":"d","text":"The resistor stores charge for the LED to use later"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-electric-language-08-o2-c1', 'mission-vec-electric-language-08-o2', 1, 'multiple_choice', 'A 5V supply drives an LED with a 2V forward drop, rated for a maximum safe current of 20 milliamps. Which series resistor keeps current at or below that safely?', '{"question":"A 5V supply drives an LED with a 2V forward drop, rated for a maximum safe current of 20 milliamps. Which series resistor keeps current at or below that safely?","options":[{"id":"a","text":"10 ohms"},{"id":"b","text":"150 ohms (drops the remaining 3V at roughly 20 milliamps or a touch under)"},{"id":"c","text":"1 ohm"},{"id":"d","text":"No resistor is needed since the LED only needs 2V"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-electric-language-09-o1-c1', 'mission-vec-electric-language-09-o1', 1, 'investigation', 'Which evidence describes how the board''s button input line is wired at rest?', '{"evidence":[{"id":"e1","label":"Wiring trace","detail":"The input line runs through a resistor to the positive supply rail, and the button connects that same line to ground"},{"id":"e2","label":"Physical note","detail":"The button is a standard momentary tactile switch"},{"id":"e3","label":"Power log","detail":"The board draws a steady 40 milliamps regardless of button state"}],"question":"Which evidence describes how the board''s button input line is wired at rest?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-electric-language-09-o2-c1', 'mission-vec-electric-language-09-o2', 1, 'multiple_choice', 'Given the input line is pulled to the positive rail and the button connects it to ground when pressed, what is the expected state when the button is untouched?', '{"question":"Given the input line is pulled to the positive rail and the button connects it to ground when pressed, what is the expected state when the button is untouched?","options":[{"id":"a","text":"Low, and pressing the button drives it high"},{"id":"b","text":"High, and pressing the button pulls it low"},{"id":"c","text":"Floating, since no resistor is present"},{"id":"d","text":"It cannot be determined from the wiring alone"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-electric-language-10-o1-c1', 'mission-vec-electric-language-10-o1', 1, 'multiple_choice', 'Why does a mechanical switch need debouncing?', '{"question":"Why does a mechanical switch need debouncing?","options":[{"id":"a","text":"Switches never actually close a circuit cleanly at all"},{"id":"b","text":"A mechanical contact bounces open and closed several times in a few milliseconds before settling, and a fast controller can misread that bounce as many separate presses"},{"id":"c","text":"Debouncing only matters for digital signals, never mechanical ones"},{"id":"d","text":"It is purely a software convention with no physical cause"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-electric-language-10-o2-c1', 'mission-vec-electric-language-10-o2', 1, 'investigation', 'Which evidence shows a reading taken without waiting out the bounce window?', '{"evidence":[{"id":"e1","label":"Log excerpt","detail":"Seven state transitions logged on the input line within 3 milliseconds of a single physical button press"},{"id":"e2","label":"Design note","detail":"The board''s input resistor is rated for standard tolerances"},{"id":"e3","label":"Power log","detail":"Supply voltage remained stable throughout the button press"}],"question":"Which evidence shows a reading taken without waiting out the bounce window?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-electric-language-11-o1-c1', 'mission-vec-electric-language-11-o1', 1, 'drag_and_drop', 'Match each measurement type to its correct probe technique.', '{"items":[{"id":"m1","text":"Measuring voltage"},{"id":"m2","text":"Measuring current"},{"id":"m3","text":"Measuring resistance"}],"targets":[{"id":"t1","label":"Probes placed in parallel across the two points, circuit left intact and powered"},{"id":"t2","label":"Probes placed in series, breaking the circuit so all current routes through the meter"},{"id":"t3","label":"Probes placed across the component with power off, never on a live circuit"}]}'::jsonb, '{"correctMapping":{"m1":"t1","m2":"t2","m3":"t3"}}'::jsonb),
  ('mission-vec-electric-language-11-o2-c1', 'mission-vec-electric-language-11-o2', 1, 'browser_simulation', 'Given this meter reading on the board, what does it imply about the trace?', '{"screen":"MULTIMETER -- TRACE J4 -- SESSION LOG","question":"Given this meter reading on the board, what does it imply about the trace?","records":[{"id":"r1","code":"V=4.98","detail":"Voltage across the trace reads near the expected supply rail, healthy"},{"id":"r2","code":"V=0.02","detail":"Voltage across the trace reads near zero where a pulled-high line was expected -- consistent with a missing or broken pull resistor rather than a healthy idle state"},{"id":"r3","code":"OL","detail":"Meter set to the wrong range for this measurement, reading overload"},{"id":"r4","code":"R=10k","detail":"Resistance reads a normal value with power correctly off"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),

  ('mission-vec-electric-language-12-o1-c1', 'mission-vec-electric-language-12-o1', 1, 'multiple_choice', 'The silent section belongs to a logic family with low under 0.8V and high over 2.0V. Its idle voltage measures 0.03V. What does that reading mean?', '{"question":"The silent section belongs to a logic family with low under 0.8V and high over 2.0V. Its idle voltage measures 0.03V. What does that reading mean?","options":[{"id":"a","text":"It is a clean, valid low -- well inside the defined low range, not undefined"},{"id":"b","text":"It is undefined, inside the gap between thresholds"},{"id":"c","text":"It is a valid high"},{"id":"d","text":"The reading is meaningless without knowing the chip''s serial number"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-electric-language-12-o2-c1', 'mission-vec-electric-language-12-o2', 1, 'investigation', 'Which evidence shows the silent section is missing its expected pull resistor?', '{"evidence":[{"id":"e1","label":"Original schematic fragment","detail":"The board''s design calls for a pull-up resistor on this exact line, resting it high until an event pulls it low"},{"id":"e2","label":"Visual inspection","detail":"The physical footprint for that pull-up resistor on the board is empty -- unpopulated, no component ever soldered there"},{"id":"e3","label":"Power log","detail":"The board''s main supply rail reads a healthy, stable voltage"}],"question":"Which evidence shows the silent section is missing its expected pull resistor?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-vec-electric-language-12-o3-c1', 'mission-vec-electric-language-12-o3', 1, 'browser_simulation', 'Given these meter readings across the silent section, where does the path actually break?', '{"screen":"MULTIMETER -- SILENT SECTION -- FULL SWEEP","question":"Given these meter readings across the silent section, where does the path actually break?","records":[{"id":"r1","code":"SUPPLY=4.97V","detail":"Main supply rail measured healthy at the board edge"},{"id":"r2","code":"PULLUP_PAD=0.00V","detail":"The unpopulated pull-up resistor footprint reads no voltage on either pad, confirming no component bridges it"},{"id":"r3","code":"LINE=0.03V","detail":"The signal line itself sits at 0.03V with the button untouched, matching a line with nothing holding it high"},{"id":"r4","code":"GROUND=0.00V","detail":"Ground reference reads a clean zero, ruling out a ground fault"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-electric-language-12-o4-c1', 'mission-vec-electric-language-12-o4', 1, 'boss_encounter', 'Having checked the logic level, the pull direction and the meter sweep, state what the silent circuit actually is.', '{"stages":[{"objectiveRef":"mission-vec-electric-language-12-o1","label":"Check the logic level"},{"objectiveRef":"mission-vec-electric-language-12-o2","label":"Check the pull direction"},{"objectiveRef":"mission-vec-electric-language-12-o3","label":"Check the meter evidence"}],"task":"State the diagnosis in one sentence: the board is not exotic hardware, it is ordinary, decades-old electronics wired with completely standard assumptions -- one section simply lost its pull-up resistor, so the line reads a clean, valid, silent low instead of the signal it was designed to carry."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-electric-language-12-o1","mission-vec-electric-language-12-o2","mission-vec-electric-language-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-electric-language-01-o1-c1', 'orientation', 'One is pressure, one is flow, one is opposition to flow. Match the word to the role, not the wire.', 10, 1),
  ('mission-vec-electric-language-01-o1-c1', 'solution', 'Voltage is the pressure measured across two points. Current is the flow measured through a path. Resistance is whatever opposes that flow.', 20, 2),
  ('mission-vec-electric-language-01-o2-c1', 'orientation', 'Resistance is measured as an opposition value, in ohms, not as a voltage or a current.', 10, 1),
  ('mission-vec-electric-language-01-o2-c1', 'solution', 'e2, the 10,000 ohm reading, is the resistance -- e1 is a voltage and e3 is a current.', 20, 2),

  ('mission-vec-electric-language-02-o1-c1', 'orientation', 'Think of voltage as a fixed push. More opposition against the same push means less gets through.', 10, 1),
  ('mission-vec-electric-language-02-o1-c1', 'solution', 'Current decreases as resistance increases, for the same fixed voltage.', 20, 2),
  ('mission-vec-electric-language-02-o2-c1', 'orientation', 'Current equals voltage divided by resistance.', 10, 1),
  ('mission-vec-electric-language-02-o2-c1', 'solution', '5 volts divided by 1,000 ohms is 0.005 amps, or 5 milliamps.', 20, 2),

  ('mission-vec-electric-language-03-o1-c1', 'orientation', 'Power equals voltage times current.', 10, 1),
  ('mission-vec-electric-language-03-o1-c1', 'solution', '5 volts times 0.1 amps is 0.5 watts.', 20, 2),
  ('mission-vec-electric-language-03-o2-c1', 'orientation', 'One is a rate, right now. The other is that rate held over a duration.', 10, 1),
  ('mission-vec-electric-language-03-o2-c1', 'solution', 'Power is the instantaneous rate of doing work; energy is power sustained over time -- which is why a brief spike can be survivable where the same power held continuously would not be.', 20, 2),

  ('mission-vec-electric-language-04-o1-c1', 'orientation', 'Ask whether the value can be anything in a range, or only ever one of a small fixed set of states.', 10, 1),
  ('mission-vec-electric-language-04-o1-c1', 'solution', 'Analog: the drifting rail voltage and the smooth sensor reading. Digital: the high/low input line and the two-state status line.', 20, 2),
  ('mission-vec-electric-language-04-o2-c1', 'orientation', 'The wire never stops carrying a continuous voltage -- ask what changes is the interpretation, not the physics.', 10, 1),
  ('mission-vec-electric-language-04-o2-c1', 'solution', 'The wire stays analog; "digital" is only an interpretation rule applied on top of the voltage by whatever is reading it.', 20, 2),

  ('mission-vec-electric-language-05-o1-c1', 'orientation', '1.4V sits between 0.8V and 2.0V -- ask what that gap means.', 10, 1),
  ('mission-vec-electric-language-05-o1-c1', 'solution', 'Anything between the two thresholds is undefined -- not reliably high or low.', 20, 2),
  ('mission-vec-electric-language-05-o2-c1', 'orientation', 'Look for evidence about the chip''s age, not its size or power source.', 10, 1),
  ('mission-vec-electric-language-05-o2-c1', 'solution', 'e1: the logic chip''s date code predates all of Vector Division''s modern hardware, so its thresholds cannot be assumed to match.', 20, 2),

  ('mission-vec-electric-language-06-o1-c1', 'orientation', 'Nothing is holding the line to a value, so ask what fills that gap instead.', 10, 1),
  ('mission-vec-electric-language-06-o1-c1', 'solution', 'It floats, picking up stray voltage and reading unpredictably rather than settling at a clean zero.', 20, 2),
  ('mission-vec-electric-language-06-o2-c1', 'orientation', 'Ask which rail the resistor connects to, and what a press pulls the line toward.', 10, 1),
  ('mission-vec-electric-language-06-o2-c1', 'solution', 'Pull-up: tied to the positive rail, resting high, pressed low (p1, p3). Pull-down: tied to ground, resting low, pressed high (p2, p4).', 20, 2),

  ('mission-vec-electric-language-07-o1-c1', 'orientation', 'Nothing can be verified before it is built, and nothing can be built before it has power to build against.', 10, 1),
  ('mission-vec-electric-language-07-o1-c1', 'solution', 'Supply, then row placement, then jumper wiring, then a meter verifying the completed path.', 20, 2),

  ('mission-vec-electric-language-08-o1-c1', 'orientation', 'Ask what stops current from climbing without any limit at all.', 10, 1),
  ('mission-vec-electric-language-08-o1-c1', 'solution', 'An LED alone offers little resistance, so without a series resistor limiting current it draws far more than it can survive and burns out.', 20, 2),
  ('mission-vec-electric-language-08-o2-c1', 'orientation', 'Subtract the LED''s forward drop from the supply, then divide by the target current.', 10, 1),
  ('mission-vec-electric-language-08-o2-c1', 'solution', '(5V - 2V) / 0.02A is 150 ohms, keeping current at roughly the safe 20 milliamp limit.', 20, 2),

  ('mission-vec-electric-language-09-o1-c1', 'orientation', 'Look for the wiring trace describing the resistor and the button together, not a note about the switch type alone.', 10, 1),
  ('mission-vec-electric-language-09-o1-c1', 'solution', 'e1: the line runs through a resistor to the positive rail, and the button ties that same line to ground.', 20, 2),
  ('mission-vec-electric-language-09-o2-c1', 'orientation', 'A pull-up resistor holds a line high until something actively pulls it low.', 10, 1),
  ('mission-vec-electric-language-09-o2-c1', 'solution', 'High at rest, pulled low when the button is pressed.', 20, 2),

  ('mission-vec-electric-language-10-o1-c1', 'orientation', 'Zoom into the first few milliseconds of a mechanical contact closing.', 10, 1),
  ('mission-vec-electric-language-10-o1-c1', 'solution', 'The contact bounces several times before settling, and a fast controller can misread that as many separate presses.', 20, 2),
  ('mission-vec-electric-language-10-o2-c1', 'orientation', 'Look for a log showing many transitions in an implausibly short window.', 10, 1),
  ('mission-vec-electric-language-10-o2-c1', 'solution', 'e1: seven transitions logged within 3 milliseconds of one physical press is the bounce, read before it settled.', 20, 2),

  ('mission-vec-electric-language-11-o1-c1', 'orientation', 'Ask whether the meter needs to sit alongside the circuit, break into its path, or require power off entirely.', 10, 1),
  ('mission-vec-electric-language-11-o1-c1', 'solution', 'Voltage: parallel, powered. Current: series, breaking the circuit. Resistance: only with power off.', 20, 2),
  ('mission-vec-electric-language-11-o2-c1', 'orientation', 'Compare the reading against what a healthy, pulled-high idle line should look like.', 10, 1),
  ('mission-vec-electric-language-11-o2-c1', 'solution', 'r2, near 0V where a pulled-high idle was expected, points to a missing or broken pull resistor rather than a healthy line.', 20, 2),

  ('mission-vec-electric-language-12-o1-c1', 'orientation', '0.03V is far below the 0.8V low threshold -- ask whether that is inside or outside the defined low range.', 10, 1),
  ('mission-vec-electric-language-12-o1-c1', 'solution', 'It is a clean, valid low reading, well inside the defined range, not an undefined in-between voltage.', 20, 2),
  ('mission-vec-electric-language-12-o2-c1', 'orientation', 'A schematic calling for a resistor is not the same as one actually being soldered onto the board.', 10, 1),
  ('mission-vec-electric-language-12-o2-c1', 'solution', 'e2: the pull-up footprint is unpopulated -- the design called for it, but nothing was ever placed there.', 20, 2),
  ('mission-vec-electric-language-12-o3-c1', 'orientation', 'Rule out supply and ground first, then look at the one measurement taken directly on the missing component''s own pads.', 10, 1),
  ('mission-vec-electric-language-12-o3-c1', 'solution', 'r2: 0.00V on both pads of the unpopulated pull-up footprint confirms nothing bridges that gap -- that is where the path actually breaks.', 20, 2),
  ('mission-vec-electric-language-12-o4-c1', 'orientation', 'Combine all three checks into one plain sentence: what the voltage means, what is missing, and where the meter proved it.', 15, 1),
  ('mission-vec-electric-language-12-o4-c1', 'solution', 'The board is ordinary, decades-old electronics wired with completely standard assumptions -- this one section simply lost its pull-up resistor, so the line reads a clean, valid, silent low instead of carrying the signal it was designed for.', 25, 2);
