-- Robotics/Embedded/IoT pathway ("Vector Division") Act 7 -- "Serial
-- Roads" content, under world-vec-serial-roads (already inserted
-- separately, under act-vec-2, index 6). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every prior Act. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram, browser_simulation (generic console fallback) and
-- boss_encounter. Vector Division characterizes the maintenance bus
-- protocol for the first time since Act 1 discovered its existence,
-- building up UART, I2C and SPI as points of contrast before landing on
-- RS-485, then diagnosing the first live write's silence as a half-duplex
-- collision rather than a dead bus.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-serial-roads', 'world-vec-serial-roads', 'serial-roads', '2B - Serial Roads', 'Learn the vocabulary of serial communication -- why devices talk at all, UART, baud rate and framing, I2C, addresses and pull-ups, SPI, chip select, CAN bus concepts, RS-485 concepts, protocol selection and logic-analyzer thinking -- while Vector Division finally identifies which bus protocol the maintenance line actually runs on.', 6);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-serial-roads-1', 'campaign-vec-serial-roads', 'point-to-point-and-shared-buses', 'Point-to-Point and Shared Buses', 'Why devices communicate, UART, baud rate and framing, I2C, addresses and pull-ups, and SPI.', 1),
  ('operation-vec-serial-roads-2', 'campaign-vec-serial-roads', 'the-bus-is-silent', 'The Bus Is Silent', 'Chip select, CAN bus concepts, RS-485 concepts, protocol selection, logic-analyzer thinking, and the first live write to the maintenance bus.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-serial-roads-01', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'why-devices-communicate', 'Why Devices Communicate', 'Before Vector Division can push the fix to the live door, they have to identify exactly which bus protocol the maintenance line runs on -- the same line Act 1 could only read, never speak on. Imani sets the stakes; Tomas starts with the most basic question of all.', 'beginner', ARRAY['imani','tomas','byte'], null, null, '{"type":"simulation","simulationId":"why-devices-communicate-sim"}'::jsonb, '{"xp":140,"credits":20}'::jsonb, false, 1),
  ('mission-vec-serial-roads-02', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'uart', 'UART', 'The simplest serial link either of them will ever wire: two wires, one direction each, no shared clock at all. Tomas walks the player through why that absence of a clock is the whole story.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"uart-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 2),
  ('mission-vec-serial-roads-03', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'baud-rate-and-framing', 'Baud Rate and Framing', 'With no shared clock, both ends of a UART link have to agree in advance on how fast to talk and how to mark where one byte ends and the next begins.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"baud-rate-framing-sim"}'::jsonb, '{"xp":150,"credits":25}'::jsonb, false, 3),
  ('mission-vec-serial-roads-04', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'i2c', 'I2C', 'UART only ever connects two devices. I2C puts many devices on the same two wires at once -- which means the bus needs a way to know who it is talking to.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-serial-roads-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"i2c-sim"}'::jsonb, '{"xp":150,"credits":25}'::jsonb, false, 4),
  ('mission-vec-serial-roads-05', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'addresses-and-pull-ups', 'Addresses and Pull-Ups', 'Every device on an I2C bus answers to a fixed address, and the two shared wires only work at all because they rest pulled high, never driven high directly.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"addresses-pull-ups-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 5),
  ('mission-vec-serial-roads-06', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-1', 'spi', 'SPI', 'I2C trades speed for simplicity. SPI trades wires for speed -- a dedicated clock line and separate data lines in each direction, running far faster than either UART or I2C.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"spi-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 6),
  ('mission-vec-serial-roads-07', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'chip-select', 'Chip Select', 'SPI has no addresses at all. Instead, a separate wire per device decides who is even allowed to listen -- which means adding a device means adding a wire.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"chip-select-sim"}'::jsonb, '{"xp":170,"credits":30}'::jsonb, false, 7),
  ('mission-vec-serial-roads-08', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'can-bus-concepts', 'CAN Bus Concepts', 'CAN was built for a harsher problem than any of the three so far: many controllers on one shared pair of wires, in a vehicle, where a message has to survive noise and a collision has to resolve itself without anyone in charge.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-serial-roads-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"can-bus-concepts-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 8),
  ('mission-vec-serial-roads-09', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'rs-485-concepts', 'RS-485 Concepts', 'One more standard, older than all of them, built for one specific problem: making a signal survive a long, noisy cable run inside a building without a modern chipset anywhere in sight.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-serial-roads-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"rs-485-concepts-sim"}'::jsonb, '{"xp":180,"credits":35}'::jsonb, false, 9),
  ('mission-vec-serial-roads-10', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'protocol-selection', 'Protocol Selection', 'Four protocols now sit on the bench. Choosing among them for a real system is never about which one is best -- it is about which constraints the wire actually has to survive.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"protocol-selection-sim"}'::jsonb, '{"xp":180,"credits":35}'::jsonb, false, 10),
  ('mission-vec-serial-roads-11', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'logic-analyzer-thinking', 'Logic-Analyzer Thinking', 'Before Vector Division writes a single byte to the live maintenance bus, Tomas has the player learn to read one blind: capture raw transitions first, guess the protocol from their shape second, never the other way around.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-serial-roads-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"logic-analyzer-thinking-sim"}'::jsonb, '{"xp":190,"credits":35}'::jsonb, false, 11),
  ('mission-vec-serial-roads-12', 'world-vec-serial-roads', 'campaign-vec-serial-roads', 'operation-vec-serial-roads-2', 'the-bus-is-silent', 'The Bus Is Silent', 'Vector Division writes to the live maintenance bus for the first time. Nothing answers. Everything this Act taught, turned on one silence: not a dead bus, but a protocol nobody had named until now.', 'boss', ARRAY['imani','tomas','byte'], '{"requiredMissionIds":["mission-vec-serial-roads-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"bus-is-silent-boss-sim"}'::jsonb, '{"xp":700,"credits":150,"badgeIds":["the-bus-is-silent"],"skillXp":{"robotics_fundamentals":90}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-serial-roads-01', 1, 'imani', 'The door fix is ready on the bench. It cannot go anywhere until Vector Division can actually put it on the maintenance line -- the same line Act 1 could only read, never speak on.'),
  ('mission-vec-serial-roads-01', 2, 'tomas', 'Tomas Vey. Every one of these lessons builds toward one question: what protocol does that maintenance bus actually speak. We start with the most basic question underneath all of it -- why does any device bother talking to another device at all.'),
  ('mission-vec-serial-roads-01', 3, 'byte', 'A sensor that never reported anything would be useless. A controller that never sent a command would be useless too. The moment a system has more than one part, those parts need a way to exchange information -- that exchange is what a protocol formalizes.'),
  ('mission-vec-serial-roads-01', 4, 'tomas', 'A protocol is just an agreed set of rules: what a wire''s voltage means, how fast to change it, and how to mark where one message ends and the next begins. Different protocols exist because different situations demand different tradeoffs on those rules.'),
  ('mission-vec-serial-roads-01', 5, 'imani', 'The maintenance bus has one of those rule sets. We do not know which yet. Learn all of them, then rule them out one at a time until only one is left standing.'),

  ('mission-vec-serial-roads-02', 1, 'tomas', 'UART -- Universal Asynchronous Receiver-Transmitter. The simplest serial link you will ever wire: one wire carries data out, a second wire carries data in, and that is the entire bus. Exactly two devices, nothing shared.'),
  ('mission-vec-serial-roads-02', 2, 'tomas', 'The word that matters most is asynchronous. There is no third wire carrying a shared clock signal. Both ends have to already agree, in advance, on the timing -- because neither one is going to tell the other when to sample the line.'),
  ('mission-vec-serial-roads-02', 3, 'byte', 'Which means UART only works between exactly two devices. Add a third device to those two wires and there is no way to tell whose message is whose.'),

  ('mission-vec-serial-roads-03', 1, 'tomas', 'Baud rate is how many symbol changes UART pushes onto the wire per second. Both ends must be configured to the identical baud rate -- mismatched by even a little, and every byte gets sampled at the wrong moment and comes out as garbage.'),
  ('mission-vec-serial-roads-03', 2, 'tomas', 'Framing is how a byte announces its own boundaries without a clock to mark them. A start bit signals the line is about to carry real data. The data bits follow. A stop bit signals the byte is done and the line is free again.'),
  ('mission-vec-serial-roads-03', 3, 'byte', 'So a UART capture is not just a stream of raw bits. It only becomes readable once you know the baud rate it was sent at and where each frame''s start and stop bits actually fall.'),

  ('mission-vec-serial-roads-04', 1, 'tomas', 'I2C -- Inter-Integrated Circuit. Two wires total, same as UART, but this time many devices share them: one line for data, one for a clock that every device on the bus reads together.'),
  ('mission-vec-serial-roads-04', 2, 'tomas', 'A shared clock means no baud rate to agree on in advance -- the clock line itself paces every bit. But sharing the wire among many devices raises a new problem UART never had: how does a message know which device it is for.'),
  ('mission-vec-serial-roads-04', 3, 'byte', 'That is the tradeoff. UART needs no addressing because it only ever has one listener. I2C needs addressing precisely because it can have many.'),

  ('mission-vec-serial-roads-05', 1, 'tomas', 'Every device on an I2C bus is configured with a fixed address, usually seven bits, unique on that bus. The controller starts every exchange by putting the target device''s address on the line first -- every other device simply ignores a message not addressed to it.'),
  ('mission-vec-serial-roads-05', 2, 'tomas', 'And neither shared wire is ever driven high by a device directly. Both rest through a pull-up resistor to the supply rail, and a device only ever pulls a line low to signal. That is the only way multiple devices can share one wire without fighting each other for control of it.'),
  ('mission-vec-serial-roads-05', 3, 'byte', 'Miss that pull-up on a real I2C bus and both lines float exactly the way an unpulled digital input floated back in Act 2 -- unreadable, for the same underlying reason.'),

  ('mission-vec-serial-roads-06', 1, 'tomas', 'SPI -- Serial Peripheral Interface. Where I2C shares one clock and one data line among everyone, SPI dedicates a clock line plus two separate data lines, one for each direction, so a controller and a device can send and receive at the exact same instant.'),
  ('mission-vec-serial-roads-06', 2, 'tomas', 'That extra wiring buys real speed. SPI routinely runs many times faster than I2C, because nothing on the bus has to wait its turn to talk -- both directions are always open.'),
  ('mission-vec-serial-roads-06', 3, 'byte', 'The cost is exactly what you would expect. More wires per connection, and as you are about to see, still no addressing scheme of its own.'),

  ('mission-vec-serial-roads-07', 1, 'tomas', 'SPI solves the many-devices problem completely differently than I2C. There is no address field on the wire at all. Instead, every device gets its own dedicated chip-select line from the controller.'),
  ('mission-vec-serial-roads-07', 2, 'tomas', 'A device only pays attention to the shared clock and data lines while its own chip-select line is actively asserted. Deassert it, and that device ignores everything on the bus completely, even though it is still physically connected.'),
  ('mission-vec-serial-roads-07', 3, 'byte', 'Which means SPI trades I2C''s two-wire simplicity for a wire count that grows with every device added. Fine for a handful of chips on one small board. Impossible to scale to a building.'),

  ('mission-vec-serial-roads-08', 1, 'tomas', 'CAN -- Controller Area Network. Built for cars, where dozens of controllers share one pair of wires across a vehicle full of electrical noise, and no single device is ever in charge of the bus.'),
  ('mission-vec-serial-roads-08', 2, 'tomas', 'Every message carries a priority identifier instead of an address. If two devices start transmitting at the same instant, the bus itself resolves the collision -- the higher-priority message simply wins and keeps transmitting, the other backs off automatically, no controller needed to referee it.'),
  ('mission-vec-serial-roads-08', 3, 'byte', 'That differential signaling is also what makes it noise-resistant. Two wires carrying deliberately opposite voltages, so electrical interference that hits both wires equally cancels out when a receiver reads the difference between them instead of either wire alone.'),

  ('mission-vec-serial-roads-09', 1, 'tomas', 'RS-485. Older than CAN, older than I2C and SPI, and built for a narrower problem: get a signal reliably down a long cable run through a building full of motors and machinery, with none of that modern differential collision-arbitration logic CAN has.'),
  ('mission-vec-serial-roads-09', 2, 'tomas', 'Like CAN, it uses a differential pair -- two wires carrying opposite voltages, noise-resistant for the same reason. Unlike CAN, RS-485 is usually half-duplex: one shared pair of wires that can carry data in either direction, but never both directions at the same instant.'),
  ('mission-vec-serial-roads-09', 3, 'byte', 'Half-duplex means every device sharing that pair has to take turns. If two devices write at the same moment, neither message survives intact -- and RS-485 itself has no built-in arbitration to sort that out the way CAN does.'),
  ('mission-vec-serial-roads-09', 4, 'tomas', 'Decades-old, differential, half-duplex, built to survive a long noisy run rather than to move data fast. Remember that profile. It is about to matter.'),

  ('mission-vec-serial-roads-10', 1, 'tomas', 'Choosing a protocol is never about which one is objectively best. UART, I2C, SPI, CAN and RS-485 all still exist because each one wins under a different set of constraints.'),
  ('mission-vec-serial-roads-10', 2, 'tomas', 'Ask what actually matters for the wire in question: how many devices, how far apart, how much electrical noise in between, how fast the data needs to move, and how old the surrounding hardware already is.'),
  ('mission-vec-serial-roads-10', 3, 'byte', 'A cable run the length of a building, through walls and machinery, wired decades before CAN or modern chipsets existed. That description alone should already narrow the field a great deal.'),

  ('mission-vec-serial-roads-11', 1, 'tomas', 'Before anyone writes a single byte to a live bus, learn to read one blind. A logic analyzer just captures raw voltage transitions over time -- it does not know or care what protocol produced them.'),
  ('mission-vec-serial-roads-11', 2, 'tomas', 'The discipline is capture first, guess second. Look at the shape of the transitions -- how many lines, whether one of them looks like a clock, whether the signal looks single-ended or differential -- before ever assuming which protocol you are looking at.'),
  ('mission-vec-serial-roads-11', 3, 'byte', 'Guess the protocol before capturing the evidence and you will keep finding whatever you expected to find. That is exactly the mistake Vector Division cannot afford on a bus this old.'),

  ('mission-vec-serial-roads-12', 1, 'imani', 'The fix is loaded. Vector Division is about to write to the live maintenance bus for the first time in this Act''s history. Everything up to this point was preparation for exactly this moment.'),
  ('mission-vec-serial-roads-12', 2, 'tomas', 'First, the capture, the way I taught you -- no assumptions. Read what the wire actually looks like before deciding what it is.'),
  ('mission-vec-serial-roads-12', 3, 'byte', 'Capture complete. Two wires, differential, no separate clock line anywhere. That already rules out three of the five protocols on the bench.'),
  ('mission-vec-serial-roads-12', 4, 'tomas', 'Now the write. Sending the fix now.'),
  ('mission-vec-serial-roads-12', 5, 'byte', 'Nothing. No acknowledgment, no error, no response of any kind. The bus looks dead.'),
  ('mission-vec-serial-roads-12', 6, 'imani', 'It is not dead. It was silent for a reason. Walk it in order -- what protocol this actually is, and why silence does not mean broken.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-serial-roads-01-o1', 'mission-vec-serial-roads-01', 1, 'Frame the incident', 'State why the fix cannot be deployed until the bus protocol is identified.'),
  ('mission-vec-serial-roads-01-o2', 'mission-vec-serial-roads-01', 2, 'Explain why protocols exist', 'Choose the accurate reason devices need an agreed protocol at all.'),

  ('mission-vec-serial-roads-02-o1', 'mission-vec-serial-roads-02', 1, 'Define UART', 'Choose the accurate description of a UART link.'),
  ('mission-vec-serial-roads-02-o2', 'mission-vec-serial-roads-02', 2, 'Explain the asynchronous limit', 'Judge why UART cannot support more than two devices on one link.'),

  ('mission-vec-serial-roads-03-o1', 'mission-vec-serial-roads-03', 1, 'Explain baud rate', 'Choose the accurate description of what happens when baud rates mismatch.'),
  ('mission-vec-serial-roads-03-o2', 'mission-vec-serial-roads-03', 2, 'Read a UART frame', 'Order a UART frame''s parts from first to last.'),

  ('mission-vec-serial-roads-04-o1', 'mission-vec-serial-roads-04', 1, 'Define I2C', 'Choose the accurate description of an I2C bus.'),
  ('mission-vec-serial-roads-04-o2', 'mission-vec-serial-roads-04', 2, 'Explain the addressing need', 'Judge why I2C requires addressing where UART does not.'),

  ('mission-vec-serial-roads-05-o1', 'mission-vec-serial-roads-05', 1, 'Trace an addressed exchange', 'Order an I2C exchange''s steps from first to last.'),
  ('mission-vec-serial-roads-05-o2', 'mission-vec-serial-roads-05', 2, 'Diagnose a missing pull-up', 'Find the evidence showing an I2C bus is failing because of a missing pull-up resistor.'),

  ('mission-vec-serial-roads-06-o1', 'mission-vec-serial-roads-06', 1, 'Define SPI', 'Choose the accurate description of an SPI bus.'),
  ('mission-vec-serial-roads-06-o2', 'mission-vec-serial-roads-06', 2, 'Compare the tradeoff', 'Sort each protocol trait into I2C or SPI.'),

  ('mission-vec-serial-roads-07-o1', 'mission-vec-serial-roads-07', 1, 'Explain chip select', 'Choose the accurate description of what a chip-select line does.'),
  ('mission-vec-serial-roads-07-o2', 'mission-vec-serial-roads-07', 2, 'Judge the scaling cost', 'Judge how wire count grows as devices are added on SPI versus I2C.'),

  ('mission-vec-serial-roads-08-o1', 'mission-vec-serial-roads-08', 1, 'Explain CAN arbitration', 'Choose the accurate description of how CAN resolves a collision.'),
  ('mission-vec-serial-roads-08-o2', 'mission-vec-serial-roads-08', 2, 'Explain differential noise resistance', 'Choose the accurate reason differential signaling resists electrical noise.'),

  ('mission-vec-serial-roads-09-o1', 'mission-vec-serial-roads-09', 1, 'Define RS-485', 'Choose the accurate description of RS-485''s core traits.'),
  ('mission-vec-serial-roads-09-o2', 'mission-vec-serial-roads-09', 2, 'Explain half-duplex', 'Judge what happens if two devices write on a half-duplex pair at the same instant.'),

  ('mission-vec-serial-roads-10-o1', 'mission-vec-serial-roads-10', 1, 'Weigh the constraints', 'Given a long, noisy, decades-old building cable run, choose the protocol that best fits those constraints.'),
  ('mission-vec-serial-roads-10-o2', 'mission-vec-serial-roads-10', 2, 'Rule out the alternatives', 'Find the evidence ruling out CAN as the maintenance bus protocol.'),

  ('mission-vec-serial-roads-11-o1', 'mission-vec-serial-roads-11', 1, 'Read a raw capture', 'Given a raw logic-analyzer capture''s traits, judge which protocol family it is consistent with.'),
  ('mission-vec-serial-roads-11-o2', 'mission-vec-serial-roads-11', 2, 'State the discipline', 'Choose the accurate description of the correct order of operations: capture, then guess.'),

  ('mission-vec-serial-roads-12-o1', 'mission-vec-serial-roads-12', 1, 'Identify the protocol', 'Given the capture''s traits, judge which protocol the maintenance bus actually runs.'),
  ('mission-vec-serial-roads-12-o2', 'mission-vec-serial-roads-12', 2, 'Explain why RS-485 fits', 'Find the evidence explaining why RS-485 was chosen over the other protocols for this bus.'),
  ('mission-vec-serial-roads-12-o3', 'mission-vec-serial-roads-12', 3, 'Diagnose the silence', 'Given the bus trace around the failed write, judge what actually caused the silence.'),
  ('mission-vec-serial-roads-12-o4', 'mission-vec-serial-roads-12', 4, 'State the mission', 'Having identified the protocol, explained the choice and diagnosed the silence, state what Vector Division can finally do next.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-serial-roads-01-o1-c1', 'mission-vec-serial-roads-01-o1', 1, 'multiple_choice', 'Why can Vector Division not simply push the door fix to the maintenance bus right now?', '{"question":"Why can Vector Division not simply push the door fix to the maintenance bus right now?","options":[{"id":"a","text":"The fix itself is still buggy and needs more testing"},{"id":"b","text":"Nobody yet knows which protocol the bus speaks, and a write in the wrong protocol will not be understood, or worse, will be misread as something else entirely"},{"id":"c","text":"The door has no power at the moment"},{"id":"d","text":"Imani has not approved the fix yet"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-01-o2-c1', 'mission-vec-serial-roads-01-o2', 1, 'multiple_choice', 'Why do communicating devices need an agreed protocol at all?', '{"question":"Why do communicating devices need an agreed protocol at all?","options":[{"id":"a","text":"Protocols exist purely as a formality, any wiring would work"},{"id":"b","text":"Without a shared, agreed set of rules for what a voltage means, how fast it changes, and where one message ends, a receiver has no way to correctly interpret whatever the wire is doing"},{"id":"c","text":"Protocols only matter for wireless communication"},{"id":"d","text":"A protocol is required only when more than two devices are involved"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-02-o1-c1', 'mission-vec-serial-roads-02-o1', 1, 'multiple_choice', 'A UART link is best described as...', '{"question":"A UART link is best described as...","options":[{"id":"a","text":"A shared bus supporting many devices addressed individually"},{"id":"b","text":"Two wires between exactly two devices, one carrying data each direction, with no shared clock line"},{"id":"c","text":"A single wire carrying both data and clock together"},{"id":"d","text":"A wireless protocol requiring no physical connection"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-02-o2-c1', 'mission-vec-serial-roads-02-o2', 1, 'multiple_choice', 'Why can a UART link only ever connect exactly two devices?', '{"question":"Why can a UART link only ever connect exactly two devices?","options":[{"id":"a","text":"UART hardware is physically incapable of handling more than two wires"},{"id":"b","text":"With no address field and no shared clock to coordinate turns, a third device on the same two wires would have no way to tell which messages were meant for it"},{"id":"c","text":"UART is limited by law to two devices"},{"id":"d","text":"It is not actually limited, a third device works fine"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-03-o1-c1', 'mission-vec-serial-roads-03-o1', 1, 'multiple_choice', 'Two UART devices are configured at different baud rates. What happens?', '{"question":"Two UART devices are configured at different baud rates. What happens?","options":[{"id":"a","text":"The faster device automatically slows down to match"},{"id":"b","text":"The receiver samples the line at the wrong moments relative to the sender''s timing, and the bytes it reconstructs come out as garbage"},{"id":"c","text":"Nothing, baud rate only affects speed, not correctness"},{"id":"d","text":"The link automatically negotiates a matching rate"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-03-o2-c1', 'mission-vec-serial-roads-03-o2', 1, 'interactive_diagram', 'Order a UART frame''s parts from first to last.', '{"diagramId":"uart-frame","hotspots":[{"id":"start","label":"Start bit","explanation":"Signals the line is about to carry a real data byte."},{"id":"data","label":"Data bits","explanation":"The actual byte being transmitted, one bit at a time."},{"id":"stop","label":"Stop bit","explanation":"Signals the byte is complete and the line is free again."}],"task":"Order the parts of a UART frame from first to last."}'::jsonb, '{"correctOrderIds":["start","data","stop"]}'::jsonb),

  ('mission-vec-serial-roads-04-o1-c1', 'mission-vec-serial-roads-04-o1', 1, 'multiple_choice', 'An I2C bus is best described as...', '{"question":"An I2C bus is best described as...","options":[{"id":"a","text":"Two wires, one data and one clock, shared by many devices at once"},{"id":"b","text":"A dedicated wire pair per device with no sharing at all"},{"id":"c","text":"A single wire carrying both directions with no clock"},{"id":"d","text":"A protocol limited to exactly two devices, same as UART"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-serial-roads-04-o2-c1', 'mission-vec-serial-roads-04-o2', 1, 'multiple_choice', 'Why does I2C require device addresses where UART does not?', '{"question":"Why does I2C require device addresses where UART does not?","options":[{"id":"a","text":"I2C hardware is simply more advanced"},{"id":"b","text":"UART only ever has one listener on the link, so there is nothing to distinguish; I2C shares its wires among many devices, so a message needs a way to say who it is for"},{"id":"c","text":"I2C addresses are only cosmetic and not actually required"},{"id":"d","text":"Addressing is required whenever a clock line is present"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-05-o1-c1', 'mission-vec-serial-roads-05-o1', 1, 'interactive_diagram', 'Order an I2C exchange''s steps from first to last.', '{"diagramId":"i2c-exchange","hotspots":[{"id":"address","label":"Address phase","explanation":"The controller puts the target device''s address on the line first."},{"id":"ack","label":"Acknowledge","explanation":"The addressed device pulls the line low to confirm it recognized its own address."},{"id":"data","label":"Data phase","explanation":"The actual data bytes are exchanged once the correct device is confirmed listening."}],"task":"Order the steps of an I2C exchange from first to last."}'::jsonb, '{"correctOrderIds":["address","ack","data"]}'::jsonb),
  ('mission-vec-serial-roads-05-o2-c1', 'mission-vec-serial-roads-05-o2', 1, 'investigation', 'Which evidence shows an I2C bus failing because of a missing pull-up resistor?', '{"evidence":[{"id":"e1","label":"Bench note","detail":"Both the data and clock lines measure near 0 volts at rest instead of resting high, and readings drift unpredictably with no device driving them"},{"id":"e2","label":"Power log","detail":"The supply rail to the bus measures a steady, healthy voltage"},{"id":"e3","label":"Component note","detail":"Every device on the bus has a unique seven-bit address configured correctly"}],"question":"Which evidence shows an I2C bus failing because of a missing pull-up resistor?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-serial-roads-06-o1-c1', 'mission-vec-serial-roads-06-o1', 1, 'multiple_choice', 'An SPI bus is best described as...', '{"question":"An SPI bus is best described as...","options":[{"id":"a","text":"A single shared data line with no clock at all"},{"id":"b","text":"A dedicated clock line plus separate data lines for each direction, allowing simultaneous two-way transfer at high speed"},{"id":"c","text":"Exactly the same wiring as I2C, just renamed"},{"id":"d","text":"A wireless short-range protocol"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-06-o2-c1', 'mission-vec-serial-roads-06-o2', 1, 'drag_and_drop', 'Sort each trait into I2C or SPI.', '{"items":[{"id":"t1","text":"Uses device addresses on a shared data line"},{"id":"t2","text":"Uses a dedicated select line per device instead of an address"},{"id":"t3","text":"Typically slower, but needs only two shared wires for any number of devices"},{"id":"t4","text":"Typically much faster, but wire count grows with every device added"}],"targets":[{"id":"i2c","label":"I2C"},{"id":"spi","label":"SPI"}]}'::jsonb, '{"correctMapping":{"t1":"i2c","t2":"spi","t3":"i2c","t4":"spi"}}'::jsonb),

  ('mission-vec-serial-roads-07-o1-c1', 'mission-vec-serial-roads-07-o1', 1, 'multiple_choice', 'What does a chip-select line actually do?', '{"question":"What does a chip-select line actually do?","options":[{"id":"a","text":"It carries the actual data being transferred"},{"id":"b","text":"It tells one specific device to pay attention to the shared clock and data lines; every other device with its select line inactive ignores the bus entirely"},{"id":"c","text":"It supplies power to the selected device"},{"id":"d","text":"It sets the baud rate for the selected device"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-07-o2-c1', 'mission-vec-serial-roads-07-o2', 1, 'multiple_choice', 'How does total wire count grow as devices are added, comparing SPI to I2C?', '{"question":"How does total wire count grow as devices are added, comparing SPI to I2C?","options":[{"id":"a","text":"Both stay fixed regardless of device count"},{"id":"b","text":"I2C stays at two shared wires no matter how many devices are added; SPI needs one additional chip-select wire per device on top of the shared clock and data lines"},{"id":"c","text":"SPI stays fixed while I2C grows with each device"},{"id":"d","text":"Both grow at exactly the same rate"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-08-o1-c1', 'mission-vec-serial-roads-08-o1', 1, 'multiple_choice', 'When two CAN devices transmit at the same instant, what resolves the collision?', '{"question":"When two CAN devices transmit at the same instant, what resolves the collision?","options":[{"id":"a","text":"Both messages are lost and must be retransmitted from scratch by a human operator"},{"id":"b","text":"The message with the higher-priority identifier wins automatically and keeps transmitting; the lower-priority sender detects it lost and backs off, with no central referee involved"},{"id":"c","text":"The bus locks up until manually reset"},{"id":"d","text":"Whichever device started transmitting fractionally first always wins, regardless of identifier"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-08-o2-c1', 'mission-vec-serial-roads-08-o2', 1, 'multiple_choice', 'Why does differential signaling resist electrical noise better than a single-ended wire?', '{"question":"Why does differential signaling resist electrical noise better than a single-ended wire?","options":[{"id":"a","text":"Differential wires are physically thicker and simply harder to interfere with"},{"id":"b","text":"Noise tends to affect both wires of the pair roughly equally, and a receiver reading the difference between the two wires cancels out that shared interference"},{"id":"c","text":"Differential signaling uses no voltage at all, so noise cannot affect it"},{"id":"d","text":"It does not actually resist noise better, that is a common misconception"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-09-o1-c1', 'mission-vec-serial-roads-09-o1', 1, 'multiple_choice', 'RS-485''s core traits are best summarized as...', '{"question":"RS-485''s core traits are best summarized as...","options":[{"id":"a","text":"A modern, high-speed, full-duplex standard designed for short cables inside a single board"},{"id":"b","text":"A decades-old differential serial standard, usually half-duplex, chosen for surviving long, electrically noisy cable runs rather than for raw speed"},{"id":"c","text":"A wireless standard with no physical wiring at all"},{"id":"d","text":"Identical to CAN in every respect except the name"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-09-o2-c1', 'mission-vec-serial-roads-09-o2', 1, 'multiple_choice', 'Two devices write onto a half-duplex RS-485 pair at the same instant. What happens?', '{"question":"Two devices write onto a half-duplex RS-485 pair at the same instant. What happens?","options":[{"id":"a","text":"Both messages are automatically merged into one valid message"},{"id":"b","text":"The two signals collide on the shared pair and neither message survives intact, since RS-485 itself has no built-in arbitration like CAN to sort out who goes first"},{"id":"c","text":"The bus automatically assigns priority the same way CAN does"},{"id":"d","text":"Nothing happens, RS-485 always supports simultaneous two-way traffic"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-10-o1-c1', 'mission-vec-serial-roads-10-o1', 1, 'multiple_choice', 'Given a signal that has to survive a long cable run through a noisy, decades-old building, with no modern chipset anywhere on that segment, which protocol best fits?', '{"question":"Given a signal that has to survive a long cable run through a noisy, decades-old building, with no modern chipset anywhere on that segment, which protocol best fits?","options":[{"id":"a","text":"I2C, since it needs only two wires"},{"id":"b","text":"RS-485, since it is a decades-old differential standard built specifically for long, noisy cable runs, unlike UART''s short point-to-point link, I2C and SPI''s short-range board-level wiring, or CAN''s newer chipset requirements"},{"id":"c","text":"SPI, since it is the fastest option"},{"id":"d","text":"UART, since it is the simplest option"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-10-o2-c1', 'mission-vec-serial-roads-10-o2', 1, 'investigation', 'Which evidence rules out CAN as the maintenance bus protocol?', '{"evidence":[{"id":"e1","label":"Facilities note","detail":"The maintenance bus wiring and its controller board predate CAN''s invention and any CAN-capable chipset by a significant margin"},{"id":"e2","label":"Cable note","detail":"The bus run is a single twisted differential pair the length of the building"},{"id":"e3","label":"Power log","detail":"The bus draws power from the standard building electrical panel"}],"question":"Which evidence rules out CAN as the maintenance bus protocol?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-serial-roads-11-o1-c1', 'mission-vec-serial-roads-11-o1', 1, 'multiple_choice', 'A raw capture shows exactly two wires, both carrying deliberately opposite voltages, with no separate clock line anywhere. That is most consistent with...', '{"question":"A raw capture shows exactly two wires, both carrying deliberately opposite voltages, with no separate clock line anywhere. That is most consistent with...","options":[{"id":"a","text":"UART, since it also uses two wires"},{"id":"b","text":"A differential protocol family such as CAN or RS-485, since single-ended protocols like UART, I2C and SPI do not carry deliberately opposite voltages on a pair"},{"id":"c","text":"SPI, since it always uses exactly two wires"},{"id":"d","text":"It could be any of the five protocols equally"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-11-o2-c1', 'mission-vec-serial-roads-11-o2', 1, 'multiple_choice', 'What is the correct order of operations when characterizing an unknown bus?', '{"question":"What is the correct order of operations when characterizing an unknown bus?","options":[{"id":"a","text":"Guess the protocol first, then look for a capture that confirms the guess"},{"id":"b","text":"Capture the raw transitions first, with no assumptions, then infer the protocol from the shape of what was actually captured"},{"id":"c","text":"Order does not matter as long as both steps happen eventually"},{"id":"d","text":"Skip the capture entirely if the protocol seems obvious"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-serial-roads-12-o1-c1', 'mission-vec-serial-roads-12-o1', 1, 'multiple_choice', 'The capture shows two wires, differential, no separate clock line, on wiring that predates modern chipsets by decades. What protocol is the maintenance bus?', '{"question":"The capture shows two wires, differential, no separate clock line, on wiring that predates modern chipsets by decades. What protocol is the maintenance bus?","options":[{"id":"a","text":"I2C, because it only needs two wires"},{"id":"b","text":"RS-485 -- differential, no clock line, and old enough to predate CAN entirely, which is exactly RS-485''s profile"},{"id":"c","text":"CAN, because it is also differential"},{"id":"d","text":"SPI, because it is fast"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-serial-roads-12-o2-c1', 'mission-vec-serial-roads-12-o2', 1, 'investigation', 'Which evidence explains why RS-485 was chosen for this bus over the other protocols?', '{"evidence":[{"id":"e1","label":"Facilities note","detail":"The maintenance bus cable runs the full length of the building through walls and machinery, decades older than CAN or any modern chipset on the property"},{"id":"e2","label":"Power log","detail":"The controller board draws power from the same panel as the rest of the door"},{"id":"e3","label":"Visual note","detail":"The controller board is roughly the size of a paperback book"}],"question":"Which evidence explains why RS-485 was chosen for this bus over the other protocols?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-serial-roads-12-o3-c1', 'mission-vec-serial-roads-12-o3', 1, 'browser_simulation', 'Given this bus trace around the failed write, what actually caused the silence?', '{"screen":"RS-485 BUS TRACE -- MAINTENANCE LINE -- WRITE ATTEMPT","question":"Given this bus trace around the failed write, what actually caused the silence?","records":[{"id":"r1","code":"LINE_IDLE","detail":"Bus idle immediately before the write, both wires at rest differential levels, consistent with a healthy line"},{"id":"r2","code":"COLLISION","detail":"Vector Division''s write began at the same instant the board''s own scheduled status broadcast began transmitting on the same half-duplex pair, corrupting both messages"},{"id":"r3","code":"POWER_NOMINAL","detail":"Bus power rail measured within specification throughout"},{"id":"r4","code":"CABLE_CONTINUITY_OK","detail":"Full cable run tested with continuity intact end to end"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-serial-roads-12-o4-c1', 'mission-vec-serial-roads-12-o4', 1, 'boss_encounter', 'Having identified the protocol, explained why it fits, and diagnosed the silence, state what Vector Division can finally do next.', '{"stages":[{"objectiveRef":"mission-vec-serial-roads-12-o1","label":"Identify the protocol"},{"objectiveRef":"mission-vec-serial-roads-12-o2","label":"Explain why RS-485 fits"},{"objectiveRef":"mission-vec-serial-roads-12-o3","label":"Diagnose the silence"}],"task":"State the diagnosis in one sentence: the maintenance bus is RS-485, a decades-old differential standard chosen to survive a long noisy building run, and the first write''s silence was a half-duplex collision with the board''s own scheduled status report, not a dead bus -- which means two-way communication is achievable, and for the first time Vector Division can ask the live door''s sensors what they actually see instead of only what the firmware claims."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-serial-roads-12-o1","mission-vec-serial-roads-12-o2","mission-vec-serial-roads-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-serial-roads-01-o1-c1', 'orientation', 'Think about what happens if a write is sent in the wrong protocol''s framing.', 10, 1),
  ('mission-vec-serial-roads-01-o1-c1', 'solution', 'Without knowing the protocol, a write will not be understood correctly, or worse, will be misinterpreted as a different valid message entirely.', 20, 2),
  ('mission-vec-serial-roads-01-o2-c1', 'orientation', 'Ask what a receiver would need to know in advance to make sense of a raw voltage on a wire.', 10, 1),
  ('mission-vec-serial-roads-01-o2-c1', 'solution', 'Without a shared, agreed rule set for voltage meaning, timing and message boundaries, a receiver has no way to correctly interpret the wire.', 20, 2),

  ('mission-vec-serial-roads-02-o1-c1', 'orientation', 'Count the wires and ask whether one of them is a shared clock.', 10, 1),
  ('mission-vec-serial-roads-02-o1-c1', 'solution', 'UART is two wires between exactly two devices, one direction each, with no shared clock line at all.', 20, 2),
  ('mission-vec-serial-roads-02-o2-c1', 'orientation', 'With no clock and no address field, ask how a third device would know a message was meant for it.', 10, 1),
  ('mission-vec-serial-roads-02-o2-c1', 'solution', 'With no address and no shared clock to coordinate turns, a third device would have no way to distinguish its messages from anyone else''s.', 20, 2),

  ('mission-vec-serial-roads-03-o1-c1', 'orientation', 'Without a shared clock, timing has to be agreed on beforehand -- ask what a mismatch does to that agreement.', 10, 1),
  ('mission-vec-serial-roads-03-o1-c1', 'solution', 'A mismatched baud rate means the receiver samples at the wrong moments relative to the sender, producing garbage instead of the intended bytes.', 20, 2),
  ('mission-vec-serial-roads-03-o2-c1', 'orientation', 'Nothing can be read as data before the line announces data is starting, and nothing ends before it is announced done.', 10, 1),
  ('mission-vec-serial-roads-03-o2-c1', 'solution', 'Start bit, then data bits, then stop bit.', 20, 2),

  ('mission-vec-serial-roads-04-o1-c1', 'orientation', 'Count I2C''s wires and ask how many devices can share them.', 10, 1),
  ('mission-vec-serial-roads-04-o1-c1', 'solution', 'Two shared wires, one data and one clock, with many devices able to sit on the same bus at once.', 20, 2),
  ('mission-vec-serial-roads-04-o2-c1', 'orientation', 'UART has exactly one possible listener. I2C does not.', 10, 1),
  ('mission-vec-serial-roads-04-o2-c1', 'solution', 'UART needs no addressing because only one device could ever be listening; I2C needs addressing because many devices share the same wires and a message must say who it is for.', 20, 2),

  ('mission-vec-serial-roads-05-o1-c1', 'orientation', 'A device cannot answer to an address before that address has been placed on the line.', 10, 1),
  ('mission-vec-serial-roads-05-o1-c1', 'solution', 'Address phase, then acknowledge, then data phase.', 20, 2),
  ('mission-vec-serial-roads-05-o2-c1', 'orientation', 'A healthy I2C line rests high through its pull-up. Look for evidence showing it is not resting high.', 10, 1),
  ('mission-vec-serial-roads-05-o2-c1', 'solution', 'e1: both lines resting near 0 volts with unpredictable drift is exactly what a missing pull-up produces -- floating, undriven lines.', 20, 2),

  ('mission-vec-serial-roads-06-o1-c1', 'orientation', 'Count SPI''s wires and ask whether both directions can be active at once.', 10, 1),
  ('mission-vec-serial-roads-06-o1-c1', 'solution', 'SPI has a dedicated clock plus separate data lines each direction, allowing simultaneous two-way transfer at high speed.', 20, 2),
  ('mission-vec-serial-roads-06-o2-c1', 'orientation', 'One protocol identifies devices by an address on a shared line; the other identifies them with a dedicated select wire.', 10, 1),
  ('mission-vec-serial-roads-06-o2-c1', 'solution', 'I2C: addressing on a shared line, slower, only two wires (t1, t3). SPI: dedicated select wire, faster, more wires as devices grow (t2, t4).', 20, 2),

  ('mission-vec-serial-roads-07-o1-c1', 'orientation', 'Ask what a device does with the shared clock and data lines while its own select line is inactive.', 10, 1),
  ('mission-vec-serial-roads-07-o1-c1', 'solution', 'Chip select tells one device to pay attention to the bus; every other device with its select inactive ignores the bus entirely.', 20, 2),
  ('mission-vec-serial-roads-07-o2-c1', 'orientation', 'One protocol''s wire count stays fixed at two. The other adds a wire per device.', 10, 1),
  ('mission-vec-serial-roads-07-o2-c1', 'solution', 'I2C stays at two shared wires regardless of device count; SPI needs one additional select wire for every device added.', 20, 2),

  ('mission-vec-serial-roads-08-o1-c1', 'orientation', 'CAN has no central referee -- the resolution happens through the identifiers themselves.', 10, 1),
  ('mission-vec-serial-roads-08-o1-c1', 'solution', 'The higher-priority identifier automatically wins and keeps transmitting; the loser detects the loss and backs off, with no controller needed to arbitrate.', 20, 2),
  ('mission-vec-serial-roads-08-o2-c1', 'orientation', 'Think about what happens when noise hits two paired wires roughly equally, and how a receiver reading the difference handles that.', 10, 1),
  ('mission-vec-serial-roads-08-o2-c1', 'solution', 'Noise tends to affect both wires of a differential pair equally, and reading the difference between them cancels that shared interference out.', 20, 2),

  ('mission-vec-serial-roads-09-o1-c1', 'orientation', 'Think about what RS-485 was built to survive, not how fast it moves data.', 10, 1),
  ('mission-vec-serial-roads-09-o1-c1', 'solution', 'RS-485 is a decades-old differential standard, usually half-duplex, chosen for surviving long noisy cable runs rather than for speed.', 20, 2),
  ('mission-vec-serial-roads-09-o2-c1', 'orientation', 'Half-duplex means the pair is shared -- ask what a shared pair does with no arbitration when two devices act at once.', 10, 1),
  ('mission-vec-serial-roads-09-o2-c1', 'solution', 'The two signals collide and neither survives intact, since RS-485 has no built-in arbitration like CAN to sort out who transmits first.', 20, 2),

  ('mission-vec-serial-roads-10-o1-c1', 'orientation', 'Match the constraints -- long, noisy, decades-old -- against each protocol''s known strengths from this Act.', 10, 1),
  ('mission-vec-serial-roads-10-o1-c1', 'solution', 'RS-485 fits: differential and old enough to predate any of the modern chipset requirements the others carry, built specifically for long noisy runs.', 20, 2),
  ('mission-vec-serial-roads-10-o2-c1', 'orientation', 'CAN requires a chipset that did not exist yet if the wiring predates it.', 10, 1),
  ('mission-vec-serial-roads-10-o2-c1', 'solution', 'e1: the wiring and controller board predate CAN''s invention and any CAN-capable chipset, ruling CAN out entirely.', 20, 2),

  ('mission-vec-serial-roads-11-o1-c1', 'orientation', 'A shared clock line is a strong signal for I2C or SPI. Its absence, paired with opposite voltages, points elsewhere.', 10, 1),
  ('mission-vec-serial-roads-11-o1-c1', 'solution', 'Two wires with deliberately opposite voltages and no clock line points to a differential family such as CAN or RS-485, not a single-ended protocol.', 20, 2),
  ('mission-vec-serial-roads-11-o2-c1', 'orientation', 'Which comes first logically: evidence, or a hypothesis about the evidence?', 10, 1),
  ('mission-vec-serial-roads-11-o2-c1', 'solution', 'Capture the raw transitions with no assumptions first, then infer the protocol from what was actually captured.', 20, 2),

  ('mission-vec-serial-roads-12-o1-c1', 'orientation', 'Match the capture''s traits -- two wires, differential, no clock, decades-old wiring -- against the protocol profiles from this Act.', 10, 1),
  ('mission-vec-serial-roads-12-o1-c1', 'solution', 'RS-485 -- differential, no clock line, and old enough to predate CAN entirely.', 20, 2),
  ('mission-vec-serial-roads-12-o2-c1', 'orientation', 'Look for the evidence about the cable run''s length, age and environment, not the door''s power source.', 10, 1),
  ('mission-vec-serial-roads-12-o2-c1', 'solution', 'e1: a full-building cable run through walls and machinery, decades older than CAN or any modern chipset, is exactly RS-485''s intended use case.', 20, 2),
  ('mission-vec-serial-roads-12-o3-c1', 'orientation', 'Rule out power and cable faults first, then look at what else was on the bus at the exact moment of the write.', 10, 1),
  ('mission-vec-serial-roads-12-o3-c1', 'solution', 'r2: the write collided with the board''s own scheduled status broadcast on the same half-duplex pair, corrupting both messages -- not a dead bus.', 20, 2),
  ('mission-vec-serial-roads-12-o4-c1', 'orientation', 'Combine all three checks: what the bus is, why that fits, and what the silence actually meant.', 15, 1),
  ('mission-vec-serial-roads-12-o4-c1', 'solution', 'The maintenance bus is RS-485, chosen to survive a long noisy building run, and the silence was a half-duplex collision with the board''s own status broadcast, not a dead bus -- so two-way communication is achievable, and Vector Division can finally ask the live door''s sensors what they actually see.', 25, 2);
