-- Robotics/Embedded/IoT pathway ("Vector Division") Act 5 -- "Firmware
-- Forge" content, closing Arc I ("Electricity Becomes Computation," Acts
-- 1-5). World row world-vec-firmware-forge already exists (created by
-- 20260813040000). 1 campaign, 2 operations, 12 missions (11 lessons +
-- boss), following the same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every other
-- pathway. No new ChallengeType needed -- reuses story_dialogue,
-- investigation, multiple_choice, interactive_diagram, drag_and_drop,
-- browser_simulation (generic console fallback) and boss_encounter, same
-- as Act 1. Byte and Tomas Vey pull the full firmware image off both
-- boards to read the actual code SUBSTRATE-era engineers wrote and find
-- out whether it can be safely touched -- landing on a genuine, mundane
-- memory leak baked into the firmware since the day it was written, not
-- new antagonist activity. Closes on the pivot into Act 6, "Time Is a
-- Requirement" (real-time/RTOS).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-firmware-forge', 'world-vec-firmware-forge', 'firmware-forge', '1E - Firmware Forge', 'Read the actual firmware source SUBSTRATE-era engineers wrote -- C and C++ for embedded systems, compilation and linking, headers, pointers to hardware, structs and enums, volatile, const correctness, static allocation, stack versus heap, memory constraints and defensive firmware -- to find out whether the frozen controllers can be safely repaired.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-firmware-forge-1', 'campaign-vec-firmware-forge', 'reading-the-source', 'Reading the Source', 'C and C++ for embedded systems, compilation and linking, headers and translation units, pointers for hardware, structs and enums, and volatile.', 1),
  ('operation-vec-firmware-forge-2', 'campaign-vec-firmware-forge', 'the-leak-in-the-loop', 'The Leak in the Loop', 'Const correctness, static allocation, stack versus heap, memory constraints, defensive firmware, and the leak that was always going to happen eventually.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-firmware-forge-01', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'c-cpp-for-embedded', 'C/C++ for Embedded Systems', 'Byte and Tomas Vey pull the full firmware image off both boards to finally read the actual code SUBSTRATE-era engineers wrote -- and to find out whether it can be safely touched at all. It starts with the language it was written in, and why that language was chosen for hardware like this.', 'beginner', ARRAY['tomas','byte'], null, null, '{"type":"simulation","simulationId":"c-cpp-for-embedded-sim"}'::jsonb, '{"xp":120,"credits":20}'::jsonb, false, 1),
  ('mission-vec-firmware-forge-02', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'compilation-and-linking', 'Compilation and Linking', 'A firmware image on the bench is not source code -- it is the end of a pipeline. Before Tomas trusts a single line the player reads, he wants them to understand exactly how that line became the bytes sitting in the controller''s flash.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-firmware-forge-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"compilation-and-linking-sim"}'::jsonb, '{"xp":120,"credits":25}'::jsonb, false, 2),
  ('mission-vec-firmware-forge-03', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'headers-and-translation-units', 'Headers and Translation Units', 'The recovered source is not one file. It is dozens, each compiled alone and stitched together only by a promise -- a header -- that another file will keep its side of the contract.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-firmware-forge-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"headers-translation-units-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 3),
  ('mission-vec-firmware-forge-04', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'pointers-for-hardware', 'Pointers for Hardware', 'In most software a pointer is just an address in memory. On this board, one specific address is not memory at all -- it is a register, and writing to it moves a motor.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-firmware-forge-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"pointers-for-hardware-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 4),
  ('mission-vec-firmware-forge-05', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'structs-and-enums', 'Structs and Enums', 'The firmware does not scatter the door''s state across loose variables. It groups everything that belongs together into one named shape, and names every state it can be in -- so nothing has to be guessed from a bare number again.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-firmware-forge-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"structs-and-enums-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 5),
  ('mission-vec-firmware-forge-06', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-1', 'volatile', 'Volatile', 'A compiler assumes it understands everything that can change a variable. A hardware register breaks that assumption on purpose, and the firmware has to tell the compiler so, or the compiler will optimize away the exact reads that matter most.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-firmware-forge-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"volatile-sim"}'::jsonb, '{"xp":140,"credits":30}'::jsonb, false, 6),
  ('mission-vec-firmware-forge-07', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'const-correctness', 'Const Correctness', 'Half of this firmware''s data should never change after the day it was flashed. Marking it const is not a formality -- it is the compiler''s promise that a bug can never accidentally rewrite it.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-firmware-forge-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"const-correctness-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 7),
  ('mission-vec-firmware-forge-08', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'static-allocation', 'Static Allocation', 'This controller has no operating system to ask for more memory later. Almost everything it will ever use has to be claimed once, by name, before the loop even starts running.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-firmware-forge-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"static-allocation-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 8),
  ('mission-vec-firmware-forge-09', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'stack-vs-heap', 'Stack vs Heap', 'The stack cleans up after itself automatically. The heap does not -- and the firmware''s one habit of asking the heap for space, on purpose, on every pass through its main loop, is starting to look less like a stylistic choice and more like a decision someone will eventually regret.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-firmware-forge-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"stack-vs-heap-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 9),
  ('mission-vec-firmware-forge-10', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'memory-constraints', 'Memory Constraints', 'This controller was given 64 kilobytes of RAM on the day it was manufactured, and it will never be given one byte more. Every allocation the firmware ever makes has to fit inside a budget that was fixed before the player was born.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-firmware-forge-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"memory-constraints-sim"}'::jsonb, '{"xp":160,"credits":35}'::jsonb, false, 10),
  ('mission-vec-firmware-forge-11', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'defensive-firmware', 'Defensive Firmware', 'Defensive firmware does not trust that the world will behave. It checks every allocation, bounds every loop, and refuses to assume that "it has always worked" means "it will keep working" -- which is precisely the assumption this firmware never made.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-firmware-forge-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"defensive-firmware-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 11),
  ('mission-vec-firmware-forge-12', 'world-vec-firmware-forge', 'campaign-vec-firmware-forge', 'operation-vec-firmware-forge-2', 'the-memory-leak-in-64kb', 'The Memory Leak in 64 KB', 'Every concept this Act taught, turned on one firmware image, closes the whole of Arc I: not a hack, not SUBSTRATE reaching for anything new -- a genuine memory leak, present since the day the firmware was written, slowly consuming the same 64 kilobytes every controller like this one was ever given.', 'boss', ARRAY['tomas','byte','imani'], '{"requiredMissionIds":["mission-vec-firmware-forge-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"memory-leak-64kb-boss-sim"}'::jsonb, '{"xp":600,"credits":130,"badgeIds":["the-64kb-leak"],"skillXp":{"robotics_fundamentals":80}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-firmware-forge-01', 1, 'tomas', 'We have the electronics. We have the register dump. What we do not have yet is the actual source code a SUBSTRATE-era engineer sat down and wrote. Today that changes -- Byte pulled the full firmware image off both boards.'),
  ('mission-vec-firmware-forge-02', 1, 'tomas', 'Before you trust a single line of this source, understand how it became the bytes sitting in that controller''s flash right now. Nothing about a compiled firmware image is magic. It is a pipeline, and every stage of that pipeline can hide a decision that matters.'),
  ('mission-vec-firmware-forge-03', 1, 'tomas', 'This is not one file. It is dozens, each one compiled completely alone, with no memory of any other file. A header is the only thing that lets them agree on anything -- a promise, checked by the compiler, that another file will keep its side of the deal.'),
  ('mission-vec-firmware-forge-04', 1, 'tomas', 'In application software, a pointer is just an address holding some value in RAM. On this board, address 0x40010000 is not a value in RAM at all. It is a register wired directly to a motor driver. Writing the wrong number there does not corrupt data. It moves the door.'),
  ('mission-vec-firmware-forge-05', 1, 'tomas', 'The firmware groups everything that belongs to the door -- state, position, fault flags -- into one struct, instead of scattering loose variables everywhere. And it names every state the door can be in with an enum, instead of leaving some bare integer for someone to misread later.'),
  ('mission-vec-firmware-forge-06', 1, 'tomas', 'A compiler is allowed to assume it fully understands what can change a variable, and to optimize accordingly. A hardware register breaks that assumption -- it can change from outside the program entirely, from the hardware itself, with no line of C responsible for it.'),
  ('mission-vec-firmware-forge-06', 2, 'byte', 'Which means without the volatile keyword telling the compiler "do not assume, always actually read this," an aggressive optimizer is free to cache a stale register value in a way that looks completely correct on paper and is wrong in practice.'),
  ('mission-vec-firmware-forge-07', 1, 'tomas', 'Half of what this firmware reads should never change after the day it was flashed -- calibration tables, lookup constants, the door''s own state names. Marking that data const is not decoration. It is the compiler refusing to compile any code that tries to write to it by mistake.'),
  ('mission-vec-firmware-forge-08', 1, 'tomas', 'This controller boots with no operating system underneath it. There is nobody to ask for more memory later. Nearly everything the firmware will ever use for its entire lifetime has to be claimed once, by name, before the main loop even begins.'),
  ('mission-vec-firmware-forge-09', 1, 'tomas', 'The stack is memory the compiler manages for you -- claimed on entering a function, automatically freed on leaving it. The heap is memory you ask for explicitly, and it stays claimed until something explicitly gives it back.'),
  ('mission-vec-firmware-forge-09', 2, 'byte', 'I found one call in the main loop that asks the heap for space on every single pass, every single time the loop runs. I have not yet found the matching call that gives any of it back.'),
  ('mission-vec-firmware-forge-10', 1, 'tomas', 'This board shipped from the factory with exactly 64 kilobytes of RAM. Not "64 kilobytes to start." Sixty-four kilobytes, full stop, for the entire operating life of the controller. Every byte the firmware ever asks for has to fit inside that number.'),
  ('mission-vec-firmware-forge-11', 1, 'tomas', 'Defensive firmware does not assume the world will cooperate. It checks whether an allocation actually succeeded before using it. It bounds every loop against a real limit instead of trusting it will terminate. It treats "this has always worked" as exactly zero evidence that it always will.'),
  ('mission-vec-firmware-forge-11', 2, 'byte', 'This firmware checks almost none of that. Not out of malice -- it reads like an engineer who trusted the loop to behave, decades before anyone here would be the one paying for that trust.'),
  ('mission-vec-firmware-forge-12', 1, 'imani', 'Two Acts ago, Vector Division could tell a door was moving on its own. Now you can read the exact code responsible. Tell me what it says.'),
  ('mission-vec-firmware-forge-12', 2, 'tomas', 'The main loop allocates a small history record on the heap every single pass, to log the last command it executed. It never frees a single one. Byte confirmed it across the full image -- there is no matching free anywhere in this firmware.'),
  ('mission-vec-firmware-forge-12', 3, 'byte', 'At the loop''s normal cycle rate, that consumes the entire 64 kilobyte budget in a little under four years of continuous uptime. It is not age. It is not interference. It is arithmetic that was true on the day this firmware was compiled.'),
  ('mission-vec-firmware-forge-12', 4, 'tomas', 'Every controller built from this same source has the same leak, on the same clock, counting down from the moment it was first powered on. It was never a question of whether one would eventually fail this way. It was only ever a question of when.'),
  ('mission-vec-firmware-forge-12', 5, 'imani', 'That closes Arc I. You went in able to say a door moved with no digital trace, and you come out able to explain, in the firmware''s own language, exactly why -- and now, how to actually repair it instead of treating it as a black box.'),
  ('mission-vec-firmware-forge-12', 6, 'imani', 'So here is the next question, and it is not what one board does anymore. It is how fast an entire fleet of them has to react, correctly, every single time, with a clock that does not forgive being late. Time is a requirement now, not a courtesy.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-firmware-forge-01-o1', 'mission-vec-firmware-forge-01', 1, 'Explain the choice of language', 'State why embedded firmware like this is typically written in C or C++ rather than a higher-level language.'),
  ('mission-vec-firmware-forge-01-o2', 'mission-vec-firmware-forge-01', 2, 'Judge the recovered image', 'Decide what having the actual source, instead of only the register dump, actually changes about what Vector Division can do next.'),

  ('mission-vec-firmware-forge-02-o1', 'mission-vec-firmware-forge-02', 1, 'Order the pipeline', 'Put preprocessing, compiling, assembling and linking in the order source code actually passes through them.'),
  ('mission-vec-firmware-forge-02-o2', 'mission-vec-firmware-forge-02', 2, 'Identify the linker''s job', 'Choose the accurate description of what the linker specifically resolves.'),

  ('mission-vec-firmware-forge-03-o1', 'mission-vec-firmware-forge-03', 1, 'Define a translation unit', 'Choose the accurate description of what a single translation unit actually is.'),
  ('mission-vec-firmware-forge-03-o2', 'mission-vec-firmware-forge-03', 2, 'Explain what a header promises', 'Find the evidence explaining why a mismatched header can compile cleanly and still be wrong.'),

  ('mission-vec-firmware-forge-04-o1', 'mission-vec-firmware-forge-04', 1, 'Tell data pointers from register pointers', 'Sort each pointer use into ordinary memory access or direct hardware register access.'),
  ('mission-vec-firmware-forge-04-o2', 'mission-vec-firmware-forge-04', 2, 'Judge the consequence', 'State what makes writing to a hardware register through a pointer riskier than writing to an ordinary variable.'),

  ('mission-vec-firmware-forge-05-o1', 'mission-vec-firmware-forge-05', 1, 'Choose the right tool', 'Judge whether a struct or an enum is the correct fit for a given piece of the door''s data.'),
  ('mission-vec-firmware-forge-05-o2', 'mission-vec-firmware-forge-05', 2, 'Explain the risk of bare integers', 'Find the evidence explaining why the door''s state used to be represented as a bare integer, and why that was fragile.'),

  ('mission-vec-firmware-forge-06-o1', 'mission-vec-firmware-forge-06', 1, 'Define volatile correctly', 'Choose the accurate description of what the volatile keyword tells the compiler.'),
  ('mission-vec-firmware-forge-06-o2', 'mission-vec-firmware-forge-06', 2, 'Spot the missing keyword', 'Find the evidence identifying which register read is unsafe without volatile.'),

  ('mission-vec-firmware-forge-07-o1', 'mission-vec-firmware-forge-07', 1, 'Explain what const guarantees', 'Choose the accurate description of what marking data const actually protects against.'),
  ('mission-vec-firmware-forge-07-o2', 'mission-vec-firmware-forge-07', 2, 'Sort the firmware''s data', 'Sort each piece of firmware data into should be const or should stay mutable.'),

  ('mission-vec-firmware-forge-08-o1', 'mission-vec-firmware-forge-08', 1, 'Define static allocation', 'Choose the accurate description of what static allocation actually means.'),
  ('mission-vec-firmware-forge-08-o2', 'mission-vec-firmware-forge-08', 2, 'Judge why it fits this controller', 'State why static allocation suits a controller with no operating system.'),

  ('mission-vec-firmware-forge-09-o1', 'mission-vec-firmware-forge-09', 1, 'Tell stack from heap', 'Sort each memory behavior into stack or heap.'),
  ('mission-vec-firmware-forge-09-o2', 'mission-vec-firmware-forge-09', 2, 'Read the loop''s habit', 'Find the evidence describing the exact heap-allocating call Byte found repeating on every pass through the main loop.'),

  ('mission-vec-firmware-forge-10-o1', 'mission-vec-firmware-forge-10', 1, 'State the budget''s nature', 'Choose the accurate description of what a fixed 64 kilobyte RAM budget actually means for firmware written for it.'),
  ('mission-vec-firmware-forge-10-o2', 'mission-vec-firmware-forge-10', 2, 'Judge the consequence of exceeding it', 'State what happens on a controller like this one when an allocation would exceed its fixed memory budget.'),

  ('mission-vec-firmware-forge-11-o1', 'mission-vec-firmware-forge-11', 1, 'Define defensive firmware', 'Choose the accurate description of what defensive firmware actually checks for.'),
  ('mission-vec-firmware-forge-11-o2', 'mission-vec-firmware-forge-11', 2, 'Judge this firmware''s posture', 'Find the evidence showing this firmware trusted the loop instead of defending against it.'),

  ('mission-vec-firmware-forge-12-o1', 'mission-vec-firmware-forge-12', 1, 'Apply stack vs heap to the leak', 'Judge which kind of memory the unfreed history record actually lives in.'),
  ('mission-vec-firmware-forge-12-o2', 'mission-vec-firmware-forge-12', 2, 'Apply memory constraints to the leak', 'Find the evidence proving the leak will eventually exhaust the controller''s fixed 64 kilobyte budget.'),
  ('mission-vec-firmware-forge-12-o3', 'mission-vec-firmware-forge-12', 3, 'Apply defensive firmware to the fix', 'Choose the defensive fix that actually closes the leak, not merely delays it.'),
  ('mission-vec-firmware-forge-12-o4', 'mission-vec-firmware-forge-12', 4, 'State the diagnosis', 'Having judged all three, state what the leak actually is and what it means for every controller built from this firmware.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-firmware-forge-01-o1-c1', 'mission-vec-firmware-forge-01-o1', 1, 'multiple_choice', 'Why is firmware like this typically written in C or C++ instead of a higher-level language?', '{"question":"Why is firmware like this typically written in C or C++ instead of a higher-level language?","options":[{"id":"a","text":"Because higher-level languages cannot express loops or conditionals"},{"id":"b","text":"Because C and C++ give direct, predictable control over memory and hardware addresses with minimal runtime overhead, which a controller with 64 kilobytes of RAM and no operating system requires"},{"id":"c","text":"Because C and C++ are the only languages that can be compiled at all"},{"id":"d","text":"Because higher-level languages are always slower to write in"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-01-o2-c1', 'mission-vec-firmware-forge-01-o2', 1, 'multiple_choice', 'Vector Division already had the register dump from an earlier Act. What does having the actual firmware source change?', '{"question":"Vector Division already had the register dump from an earlier Act. What does having the actual firmware source change?","options":[{"id":"a","text":"Nothing, a register dump and source code carry the same information"},{"id":"b","text":"The register dump showed what state the controller ended up in; the source shows why -- the actual logic, decisions and assumptions an engineer wrote, which is what repair requires"},{"id":"c","text":"The source is only useful for rewriting the firmware from scratch"},{"id":"d","text":"Source code cannot reveal anything a register dump does not already show"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-firmware-forge-02-o1-c1', 'mission-vec-firmware-forge-02-o1', 1, 'interactive_diagram', 'Order the build pipeline stages from source code to a runnable firmware image.', '{"diagramId":"build-pipeline","hotspots":[{"id":"preprocess","label":"Preprocessing","explanation":"Expands macros and #include directives into plain source text."},{"id":"compile","label":"Compiling","explanation":"Translates preprocessed source into assembly for the target processor."},{"id":"assemble","label":"Assembling","explanation":"Converts assembly into machine code object files."},{"id":"link","label":"Linking","explanation":"Combines object files and resolves references into one final image."}],"task":"Order the stages from source code to final firmware image."}'::jsonb, '{"correctOrderIds":["preprocess","compile","assemble","link"]}'::jsonb),
  ('mission-vec-firmware-forge-02-o2-c1', 'mission-vec-firmware-forge-02-o2', 1, 'multiple_choice', 'What does the linker specifically resolve that the compiler alone cannot?', '{"question":"What does the linker specifically resolve that the compiler alone cannot?","options":[{"id":"a","text":"Syntax errors inside a single source file"},{"id":"b","text":"References between separately compiled files -- a function or variable declared in one file and defined in another gets tied to its final address only at link time"},{"id":"c","text":"Whether a variable is spelled correctly"},{"id":"d","text":"The color scheme of the source code editor"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-firmware-forge-03-o1-c1', 'mission-vec-firmware-forge-03-o1', 1, 'multiple_choice', 'A translation unit is best described as...', '{"question":"A translation unit is best described as...","options":[{"id":"a","text":"The entire firmware project, all files combined"},{"id":"b","text":"One source file plus everything pulled into it by preprocessing, compiled as a single independent unit with no knowledge of any other file''s internals"},{"id":"c","text":"A single function inside a source file"},{"id":"d","text":"The final linked firmware image"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-03-o2-c1', 'mission-vec-firmware-forge-03-o2', 1, 'investigation', 'Why can a mismatched header compile cleanly and still be wrong?', '{"evidence":[{"id":"e1","label":"Build log","detail":"Every translation unit compiled with zero errors and zero warnings"},{"id":"e2","label":"Tomas''s note","detail":"A header only declares a promise -- the compiler checks that calls match the declaration''s shape, but never verifies the declaration matches what the other file actually defines until link time, and even then only partially"},{"id":"e3","label":"Facilities note","detail":"The firmware repository has no version control history preserved"}],"question":"Why can a mismatched header compile cleanly and still be wrong?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-firmware-forge-04-o1-c1', 'mission-vec-firmware-forge-04-o1', 1, 'drag_and_drop', 'Sort each pointer use into ordinary memory access or direct hardware register access.', '{"items":[{"id":"p1","text":"int *count = &loop_iterations; -- points at a normal variable on the stack"},{"id":"p2","text":"volatile uint32_t *motor_ctrl = (volatile uint32_t *)0x40010000; -- points at a fixed hardware address"},{"id":"p3","text":"char *name = door_label; -- points at a string stored in RAM"},{"id":"p4","text":"volatile uint8_t *status_reg = (volatile uint8_t *)0x40010004; -- points at a status register"}],"targets":[{"id":"ordinary","label":"Ordinary memory access"},{"id":"register","label":"Hardware register access"}]}'::jsonb, '{"correctMapping":{"p1":"ordinary","p2":"register","p3":"ordinary","p4":"register"}}'::jsonb),
  ('mission-vec-firmware-forge-04-o2-c1', 'mission-vec-firmware-forge-04-o2', 1, 'multiple_choice', 'What makes writing to a hardware register through a pointer riskier than writing to an ordinary variable?', '{"question":"What makes writing to a hardware register through a pointer riskier than writing to an ordinary variable?","options":[{"id":"a","text":"Register writes are always slower, nothing more"},{"id":"b","text":"An ordinary variable only holds data -- a register write can immediately trigger a physical effect, like energizing a motor driver, with no chance to catch the mistake before it happens"},{"id":"c","text":"Register writes cannot be represented with pointers at all"},{"id":"d","text":"There is no real difference in risk"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-firmware-forge-05-o1-c1', 'mission-vec-firmware-forge-05-o1', 1, 'drag_and_drop', 'Sort each piece of the door''s data into the tool that fits it best.', '{"items":[{"id":"d1","text":"The door''s current condition: OPEN, CLOSING, SEALED or FAULT, a fixed named set of possibilities"},{"id":"d2","text":"A bundle of the door''s position, fault flags and last command timestamp, all describing one door at once"},{"id":"d3","text":"The set of trigger reasons a seal command can carry: SCHEDULED, MANUAL, EMERGENCY"}],"targets":[{"id":"struct","label":"struct"},{"id":"enum","label":"enum"}]}'::jsonb, '{"correctMapping":{"d1":"enum","d2":"struct","d3":"enum"}}'::jsonb),
  ('mission-vec-firmware-forge-05-o2-c1', 'mission-vec-firmware-forge-05-o2', 1, 'investigation', 'Why was representing the door''s state as a bare integer fragile?', '{"evidence":[{"id":"e1","label":"Old source fragment","detail":"if (door_state == 2) { seal(); } -- with no comment anywhere explaining what value 2 means"},{"id":"e2","label":"Build log","detail":"The firmware compiled without any errors"},{"id":"e3","label":"Facilities note","detail":"The controller board has run for years without a hardware fault"}],"question":"Why was representing the door''s state as a bare integer fragile?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-firmware-forge-06-o1-c1', 'mission-vec-firmware-forge-06-o1', 1, 'multiple_choice', 'The volatile keyword tells the compiler...', '{"question":"The volatile keyword tells the compiler...","options":[{"id":"a","text":"To make a variable read-only"},{"id":"b","text":"That a variable''s value can change outside the program''s own control flow, so every read and write must actually touch memory instead of being cached or optimized away"},{"id":"c","text":"To allocate a variable on the heap instead of the stack"},{"id":"d","text":"To make a variable thread-safe automatically"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-06-o2-c1', 'mission-vec-firmware-forge-06-o2', 1, 'investigation', 'Which register read in the recovered source is unsafe without volatile?', '{"evidence":[{"id":"e1","label":"Source fragment A","detail":"uint32_t sensor_val = local_counter; -- reads an ordinary local variable"},{"id":"e2","label":"Source fragment B","detail":"uint32_t status = *status_reg; declared without volatile, read once in a loop that expects it to change from hardware"},{"id":"e3","label":"Source fragment C","detail":"const uint32_t max_retries = 5; -- a fixed compile-time constant"}],"question":"Which register read in the recovered source is unsafe without volatile?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-firmware-forge-07-o1-c1', 'mission-vec-firmware-forge-07-o1', 1, 'multiple_choice', 'Marking firmware data const actually protects against...', '{"question":"Marking firmware data const actually protects against...","options":[{"id":"a","text":"The hardware itself changing the value"},{"id":"b","text":"The compiler ever accepting code that writes to that data by mistake -- it turns an accidental write into a build failure instead of a silent runtime bug"},{"id":"c","text":"The value ever being read more than once"},{"id":"d","text":"Nothing at runtime, it is purely a style comment"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-07-o2-c1', 'mission-vec-firmware-forge-07-o2', 1, 'drag_and_drop', 'Sort each piece of firmware data into should be const or should stay mutable.', '{"items":[{"id":"c1","text":"A calibration lookup table written once at flash time and never changed again"},{"id":"c2","text":"The door''s current live state, updated every pass through the loop"},{"id":"c3","text":"The maximum retry count, a fixed limit the firmware never adjusts"},{"id":"c4","text":"A counter tracking how many times the loop has run"}],"targets":[{"id":"const","label":"Should be const"},{"id":"mutable","label":"Should stay mutable"}]}'::jsonb, '{"correctMapping":{"c1":"const","c2":"mutable","c3":"const","c4":"mutable"}}'::jsonb),

  ('mission-vec-firmware-forge-08-o1-c1', 'mission-vec-firmware-forge-08-o1', 1, 'multiple_choice', 'Static allocation means...', '{"question":"Static allocation means...","options":[{"id":"a","text":"Memory is allocated fresh every time a function runs"},{"id":"b","text":"Memory is reserved for a variable at compile time, for the entire lifetime of the program, with a fixed size and address decided before anything runs"},{"id":"c","text":"Memory is only ever allocated from the heap"},{"id":"d","text":"Memory allocation that requires an operating system to manage it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-08-o2-c1', 'mission-vec-firmware-forge-08-o2', 1, 'multiple_choice', 'Why does static allocation suit a controller with no operating system?', '{"question":"Why does static allocation suit a controller with no operating system?","options":[{"id":"a","text":"It does not, dynamic allocation is always preferred"},{"id":"b","text":"With no OS to manage a heap or recover from a failed allocation, memory whose size and address are fixed before the program runs cannot run out unexpectedly at runtime"},{"id":"c","text":"Static allocation is only a concept in higher-level languages"},{"id":"d","text":"It makes the firmware image smaller on disk, which is the only benefit"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-firmware-forge-09-o1-c1', 'mission-vec-firmware-forge-09-o1', 1, 'drag_and_drop', 'Sort each memory behavior into stack or heap.', '{"items":[{"id":"m1","text":"Memory automatically freed the instant the function that claimed it returns"},{"id":"m2","text":"Memory that stays claimed until an explicit free call releases it"},{"id":"m3","text":"A local variable declared inside a function body"},{"id":"m4","text":"A block requested explicitly at runtime with a size not known until the program is running"}],"targets":[{"id":"stack","label":"Stack"},{"id":"heap","label":"Heap"}]}'::jsonb, '{"correctMapping":{"m1":"stack","m2":"heap","m3":"stack","m4":"heap"}}'::jsonb),
  ('mission-vec-firmware-forge-09-o2-c1', 'mission-vec-firmware-forge-09-o2', 1, 'investigation', 'Which evidence describes the exact heap-allocating call Byte found repeating on every pass through the main loop?', '{"evidence":[{"id":"e1","label":"Source fragment","detail":"while (1) { HistoryRecord *rec = malloc(sizeof(HistoryRecord)); log_command(rec); } -- inside the main loop, with no matching free anywhere in the file"},{"id":"e2","label":"Source fragment","detail":"void init_sensors(void) { uint8_t buf[16]; read_calibration(buf); } -- a local stack buffer used once at startup"},{"id":"e3","label":"Build log","detail":"The firmware links successfully with no unresolved symbols"}],"question":"Which evidence describes the exact heap-allocating call repeating on every pass through the main loop?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-firmware-forge-10-o1-c1', 'mission-vec-firmware-forge-10-o1', 1, 'multiple_choice', 'A fixed 64 kilobyte RAM budget means, for firmware written to run on it...', '{"question":"A fixed 64 kilobyte RAM budget means, for firmware written to run on it...","options":[{"id":"a","text":"The operating system will page unused memory to disk once the budget is exceeded"},{"id":"b","text":"Every static allocation, every stack frame, and every heap allocation together must never exceed that number for the life of the device -- there is no more memory to grow into, ever"},{"id":"c","text":"The budget only applies while the debugger is attached"},{"id":"d","text":"64 kilobytes refers only to flash storage, not RAM used while running"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-10-o2-c1', 'mission-vec-firmware-forge-10-o2', 1, 'multiple_choice', 'What happens on a controller like this one when an allocation would exceed its fixed memory budget?', '{"question":"What happens on a controller like this one when an allocation would exceed its fixed memory budget?","options":[{"id":"a","text":"The controller automatically requests more RAM from the network"},{"id":"b","text":"With no operating system to intervene, the allocation either fails outright or, worse, silently corrupts adjacent memory -- and firmware that never checks for that failure has no way to notice"},{"id":"c","text":"Nothing, embedded controllers cannot run out of memory"},{"id":"d","text":"The firmware automatically frees the oldest allocation on its own"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-firmware-forge-11-o1-c1', 'mission-vec-firmware-forge-11-o1', 1, 'multiple_choice', 'Defensive firmware is best described as firmware that...', '{"question":"Defensive firmware is best described as firmware that...","options":[{"id":"a","text":"Runs as fast as possible with the fewest checks"},{"id":"b","text":"Actively checks whether allocations succeeded, bounds loops against real limits, and never assumes past behavior guarantees future behavior"},{"id":"c","text":"Only runs on hardware with an operating system"},{"id":"d","text":"Is written exclusively in a higher-level language for safety"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-11-o2-c1', 'mission-vec-firmware-forge-11-o2', 1, 'investigation', 'Which evidence shows this firmware trusted its main loop instead of defending against it?', '{"evidence":[{"id":"e1","label":"Source fragment","detail":"HistoryRecord *rec = malloc(sizeof(HistoryRecord)); log_command(rec); -- the return value of malloc is never checked for NULL, and rec is never freed"},{"id":"e2","label":"Build log","detail":"The firmware compiled cleanly with no warnings enabled"},{"id":"e3","label":"Facilities note","detail":"The controller board is bolted inside a weatherproof housing"}],"question":"Which evidence shows this firmware trusted its main loop instead of defending against it?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-firmware-forge-12-o1-c1', 'mission-vec-firmware-forge-12-o1', 1, 'multiple_choice', 'The unfreed HistoryRecord allocated every pass through the main loop lives in...', '{"question":"The unfreed HistoryRecord allocated every pass through the main loop lives in...","options":[{"id":"a","text":"The stack, so it is automatically reclaimed once the loop iteration ends"},{"id":"b","text":"The heap -- claimed explicitly by malloc and never released by a matching free, so it persists for the entire remaining uptime of the controller"},{"id":"c","text":"Read-only flash memory, so it cannot actually accumulate"},{"id":"d","text":"A hardware register, so it does not consume RAM at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-12-o2-c1', 'mission-vec-firmware-forge-12-o2', 1, 'investigation', 'Which evidence proves this leak will eventually exhaust the controller''s fixed 64 kilobyte budget?', '{"evidence":[{"id":"e1","label":"Byte''s calculation","detail":"At the loop''s normal cycle rate, the unfreed HistoryRecord allocations consume the entire 64 kilobyte RAM budget in a little under four years of continuous uptime, with no matching free anywhere in the firmware image"},{"id":"e2","label":"Build log","detail":"The firmware links with zero unresolved symbols"},{"id":"e3","label":"Facilities note","detail":"The second door''s controller has run since before the current facilities team was hired"}],"question":"Which evidence proves this leak will eventually exhaust the controller''s fixed 64 kilobyte budget?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-firmware-forge-12-o3-c1', 'mission-vec-firmware-forge-12-o3', 1, 'multiple_choice', 'What defensive fix actually closes this leak, rather than merely delaying it?', '{"question":"What defensive fix actually closes this leak, rather than merely delaying it?","options":[{"id":"a","text":"Increasing the controller''s RAM budget"},{"id":"b","text":"Replace the unbounded per-pass heap allocation with a fixed-size, statically allocated history buffer -- for example a small ring buffer of a bounded length -- so no allocation ever needs freeing because none is ever made after startup"},{"id":"c","text":"Rebooting the controller more frequently"},{"id":"d","text":"Removing the history logging feature''s only call site without replacing it with anything, leaving the loop otherwise unchanged"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-firmware-forge-12-o4-c1', 'mission-vec-firmware-forge-12-o4', 1, 'boss_encounter', 'Having judged where the leak lives, what proves it will exhaust the budget, and what actually fixes it, state the diagnosis for every controller built from this firmware.', '{"stages":[{"objectiveRef":"mission-vec-firmware-forge-12-o1","label":"Apply stack vs heap to the leak"},{"objectiveRef":"mission-vec-firmware-forge-12-o2","label":"Apply memory constraints to the leak"},{"objectiveRef":"mission-vec-firmware-forge-12-o3","label":"Apply defensive firmware to the fix"}],"task":"State the diagnosis in one sentence: the firmware runs clean for years before behaving strangely, not from age or interference, but from a genuine memory leak present since the day it was written, slowly consuming the same 64 kilobytes every controller like this one was ever given -- it was always going to fail eventually, the only open question was always going to be when."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-firmware-forge-12-o1","mission-vec-firmware-forge-12-o2","mission-vec-firmware-forge-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-firmware-forge-01-o1-c1', 'orientation', 'Think about what a controller with 64 kilobytes of RAM and no operating system cannot afford to spend cycles on.', 10, 1),
  ('mission-vec-firmware-forge-01-o1-c1', 'solution', 'C and C++ give direct, predictable control over memory and hardware addresses with almost no runtime overhead -- exactly what a resource-starved controller needs.', 20, 2),
  ('mission-vec-firmware-forge-01-o2-c1', 'orientation', 'A register dump is a snapshot of an outcome. Ask what source code is a record of instead.', 10, 1),
  ('mission-vec-firmware-forge-01-o2-c1', 'solution', 'The dump showed the end state; the source shows the actual logic and assumptions behind it -- which is what repairing, not just diagnosing, requires.', 20, 2),

  ('mission-vec-firmware-forge-02-o1-c1', 'orientation', 'Text has to become tokens before it can become assembly, and assembly before it can become machine code.', 10, 1),
  ('mission-vec-firmware-forge-02-o1-c1', 'solution', 'Preprocess, then compile, then assemble, then link -- each stage consumes the previous stage''s output.', 20, 2),
  ('mission-vec-firmware-forge-02-o2-c1', 'orientation', 'Ask what a compiler working on one file alone cannot possibly know about another file.', 10, 1),
  ('mission-vec-firmware-forge-02-o2-c1', 'solution', 'The linker resolves references across separately compiled files, tying a declared function or variable to its final address only once every file is combined.', 20, 2),

  ('mission-vec-firmware-forge-03-o1-c1', 'orientation', 'A translation unit is defined by what the preprocessor hands to the compiler, not by the project as a whole.', 10, 1),
  ('mission-vec-firmware-forge-03-o1-c1', 'solution', 'It is one source file plus everything pulled into it by preprocessing, compiled independently with no visibility into any other file''s internals.', 20, 2),
  ('mission-vec-firmware-forge-03-o2-c1', 'orientation', 'Ask what the compiler actually checks a header against, versus what it trusts.', 10, 1),
  ('mission-vec-firmware-forge-03-o2-c1', 'solution', 'e2: a header is only a promise -- the compiler checks the shape of calls against it, but never fully verifies the declaration matches the real definition until link time, and even then only partially.', 20, 2),

  ('mission-vec-firmware-forge-04-o1-c1', 'orientation', 'Ask whether the pointer''s target address is decided by the compiler''s memory layout, or fixed by the hardware itself.', 10, 1),
  ('mission-vec-firmware-forge-04-o1-c1', 'solution', 'Ordinary: p1 and p3, pointing at normal variables. Register: p2 and p4, pointing at fixed hardware addresses, both marked volatile for a reason.', 20, 2),
  ('mission-vec-firmware-forge-04-o2-c1', 'orientation', 'Think about what happens the instant after the write completes, not just what the write itself does.', 10, 1),
  ('mission-vec-firmware-forge-04-o2-c1', 'solution', 'A register write can trigger an immediate physical effect, with no window to catch a mistake before it happens -- unlike overwriting an ordinary variable.', 20, 2),

  ('mission-vec-firmware-forge-05-o1-c1', 'orientation', 'A struct groups related values that describe one thing together. An enum names a fixed, closed set of possibilities.', 10, 1),
  ('mission-vec-firmware-forge-05-o1-c1', 'solution', 'd1 and d3 are fixed named sets, so enum. d2 bundles several fields describing one door at once, so struct.', 20, 2),
  ('mission-vec-firmware-forge-05-o2-c1', 'orientation', 'Look for a code fragment comparing against a raw number with nothing nearby explaining what it means.', 10, 1),
  ('mission-vec-firmware-forge-05-o2-c1', 'solution', 'e1: door_state == 2 with no comment anywhere -- any future reader, or engineer, has to already know what 2 means, which is exactly how meaning gets lost over decades.', 20, 2),

  ('mission-vec-firmware-forge-06-o1-c1', 'orientation', 'Ask what the compiler is normally allowed to assume about a variable that no visible code has touched recently.', 10, 1),
  ('mission-vec-firmware-forge-06-o1-c1', 'solution', 'volatile tells the compiler the value can change outside the program''s control flow, so every access must actually touch memory rather than being cached or optimized away.', 20, 2),
  ('mission-vec-firmware-forge-06-o2-c1', 'orientation', 'Look for a register pointer declared without the volatile keyword at all.', 10, 1),
  ('mission-vec-firmware-forge-06-o2-c1', 'solution', 'e2: status_reg is read in a loop expecting it to change from hardware, but is declared without volatile -- the compiler is free to cache a stale value.', 20, 2),

  ('mission-vec-firmware-forge-07-o1-c1', 'orientation', 'const is enforced by the compiler, not by anything at runtime.', 10, 1),
  ('mission-vec-firmware-forge-07-o1-c1', 'solution', 'const turns an accidental write into a build failure the compiler catches, instead of a silent bug that only shows up at runtime.', 20, 2),
  ('mission-vec-firmware-forge-07-o2-c1', 'orientation', 'Ask whether each value changes as the firmware runs, or was fixed the moment it was flashed.', 10, 1),
  ('mission-vec-firmware-forge-07-o2-c1', 'solution', 'const: the calibration table and the retry limit, both fixed at flash time. Mutable: the live door state and the loop counter, both updated as the firmware runs.', 20, 2),

  ('mission-vec-firmware-forge-08-o1-c1', 'orientation', 'Static allocation is decided before the program ever starts running, not while it runs.', 10, 1),
  ('mission-vec-firmware-forge-08-o1-c1', 'solution', 'Static allocation reserves a fixed size and address at compile time, for the program''s entire lifetime.', 20, 2),
  ('mission-vec-firmware-forge-08-o2-c1', 'orientation', 'Think about who would normally catch a failed allocation on a system that does have an operating system.', 10, 1),
  ('mission-vec-firmware-forge-08-o2-c1', 'solution', 'With no OS to manage or recover a heap, memory fixed before runtime simply cannot run out unexpectedly later.', 20, 2),

  ('mission-vec-firmware-forge-09-o1-c1', 'orientation', 'Ask whether the memory frees itself automatically when a function returns, or waits for an explicit instruction.', 10, 1),
  ('mission-vec-firmware-forge-09-o1-c1', 'solution', 'Stack: automatic local variables, freed on return. Heap: explicit allocation that persists until an explicit free.', 20, 2),
  ('mission-vec-firmware-forge-09-o2-c1', 'orientation', 'Look specifically for a malloc call sitting inside the main loop''s body, not one used only once at startup.', 10, 1),
  ('mission-vec-firmware-forge-09-o2-c1', 'solution', 'e1: malloc(sizeof(HistoryRecord)) runs on every pass through the while(1) loop, and no free ever appears anywhere in the file.', 20, 2),

  ('mission-vec-firmware-forge-10-o1-c1', 'orientation', '"Fixed" means fixed for the entire operating life of the device, not just at boot.', 10, 1),
  ('mission-vec-firmware-forge-10-o1-c1', 'solution', 'Every allocation of every kind, for the device''s entire lifetime, must together stay inside that number -- there is no growing into more memory later.', 20, 2),
  ('mission-vec-firmware-forge-10-o2-c1', 'orientation', 'Think about who is watching for that failure on a system with nothing managing memory for it.', 10, 1),
  ('mission-vec-firmware-forge-10-o2-c1', 'solution', 'With no OS present, an over-budget allocation either fails outright or silently corrupts nearby memory, and firmware that never checks has no way to notice either outcome.', 20, 2),

  ('mission-vec-firmware-forge-11-o1-c1', 'orientation', 'Defensive firmware treats every assumption as something that eventually gets violated.', 10, 1),
  ('mission-vec-firmware-forge-11-o1-c1', 'solution', 'It checks whether allocations actually succeeded, bounds every loop against a real limit, and never trusts past behavior to predict future behavior.', 20, 2),
  ('mission-vec-firmware-forge-11-o2-c1', 'orientation', 'Look for a malloc call whose return value is never checked at all.', 10, 1),
  ('mission-vec-firmware-forge-11-o2-c1', 'solution', 'e1: the malloc return value is never checked for NULL, and the allocation is never freed -- the firmware simply trusted the loop to behave.', 20, 2),

  ('mission-vec-firmware-forge-12-o1-c1', 'orientation', 'Ask whether the allocation was claimed with malloc or simply declared as a local variable.', 10, 1),
  ('mission-vec-firmware-forge-12-o1-c1', 'solution', 'It lives on the heap -- malloc claims it explicitly, and with no matching free it survives for the rest of the controller''s uptime.', 20, 2),
  ('mission-vec-firmware-forge-12-o2-c1', 'orientation', 'You have seen this exact calculation before, earlier this Act -- find the evidence that turns the leak rate into a real timeline.', 10, 1),
  ('mission-vec-firmware-forge-12-o2-c1', 'solution', 'e1: Byte''s calculation shows the leak consumes the full 64 kilobyte budget in under four years of continuous uptime, with no free anywhere in the image.', 20, 2),
  ('mission-vec-firmware-forge-12-o3-c1', 'orientation', 'A real fix removes the need to free anything at all, rather than remembering to free it correctly.', 10, 1),
  ('mission-vec-firmware-forge-12-o3-c1', 'solution', 'Replacing the unbounded per-pass heap allocation with a fixed-size, statically allocated buffer closes the leak permanently, since no allocation happens after startup at all.', 20, 2),
  ('mission-vec-firmware-forge-12-o4-c1', 'orientation', 'Combine where the leak lives, how long it takes to matter, and what actually stops it -- that is the whole diagnosis.', 15, 1),
  ('mission-vec-firmware-forge-12-o4-c1', 'solution', 'A genuine memory leak, present since the day the firmware was written, slowly consumes the same 64 kilobytes every controller like this one was ever given -- it was always going to fail eventually, the only open question was always going to be when.', 25, 2);
