-- Backend Engineering ("The Fracture") Act 23 -- "Modular Monolith to
-- Microservices" content. Opens Arc VI''s middle stretch: two teams stepping
-- on each other in one codebase, and the actual reasoning behind when and
-- how to split it. 1 campaign, 2 operations, 12 missions (11 lessons + boss).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be23', 'world-be-23', 'modular-monolith-to-microservices', '23A - Modular Monolith to Microservices', 'Two teams keep stepping on each other inside one codebase. Learn when a monolith is actually fine, how to draw real boundaries inside it, and how to split it into services without rebuilding the same mess with a network in between.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be23-1', 'campaign-be23', 'where-to-cut', 'Where to Cut', 'Coupling, cohesion, domain-driven design and bounded contexts -- the actual reasoning behind where a boundary belongs, before anything gets extracted.', 1),
  ('operation-be23-2', 'campaign-be23', 'the-extraction', 'The Extraction', 'Pulling a service out for real: its own database, its own communication contract, and a front door that doesn''t force every client through the same shape.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be23-01', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'why-monoliths-are-not-bad', 'Why Monoliths Are Not Bad', 'Leadership wants everything split into microservices because the word sounds modern. Before anything gets cut, understand exactly what a monolith buys a small team -- and what splitting it costs.', 'advanced', ARRAY['mira'], null, null, '{"type":"simulation","simulationId":"monolith-tradeoffs-sim"}'::jsonb, '{"xp":270,"credits":52}'::jsonb, false, 1),
  ('mission-be23-02', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'modular-monolith', 'Modular Monolith', 'Not every problem needs a network between its pieces. A modular monolith draws the same internal walls a service boundary would, without paying for the distributed system yet.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be23-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"modular-monolith-sim"}'::jsonb, '{"xp":272,"credits":52}'::jsonb, false, 2),
  ('mission-be23-03', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'coupling-and-cohesion', 'Coupling and Cohesion', 'The actual metric behind ''where to cut'': how tightly a module''s own pieces belong together, and how little it needs to know about anyone else''s.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be23-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"coupling-cohesion-sim"}'::jsonb, '{"xp":274,"credits":53}'::jsonb, false, 3),
  ('mission-be23-04', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'domain-driven-design-concepts', 'Domain-Driven Design Concepts', 'Before any boundary gets drawn, the vocabulary has to be precise. Entities, value objects, aggregates and domain events are how a domain gets modeled honestly instead of as database rows.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be23-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"ddd-concepts-sim"}'::jsonb, '{"xp":276,"credits":53}'::jsonb, false, 4),
  ('mission-be23-05', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'bounded-contexts', 'Bounded Contexts', 'The same word means different things to different teams, and that''s not a bug -- it''s the actual shape of the boundary nobody''s drawn yet.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be23-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"bounded-context-sim"}'::jsonb, '{"xp":278,"credits":54}'::jsonb, false, 5),
  ('mission-be23-06', 'world-be-23', 'campaign-be23', 'operation-be23-1', 'service-boundaries', 'Service Boundaries', 'A bounded context is a modeling boundary. A service boundary is that same line, enforced in production: nothing crosses it except through a published interface.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be23-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"service-boundary-sim"}'::jsonb, '{"xp":280,"credits":54}'::jsonb, false, 6),
  ('mission-be23-07', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'extracting-a-service', 'Extracting a Service', 'A boundary on a diagram isn''t a running service. Pulling one out of a live system without stopping the world takes a plan, not a rewrite.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be23-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"strangler-fig-sim"}'::jsonb, '{"xp":282,"credits":54}'::jsonb, false, 7),
  ('mission-be23-08', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'database-per-service', 'Database per Service', 'A service that still shares its data with everyone else was never actually independent. Database-per-service is where the split either becomes real or turns out to be theater.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be23-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"database-per-service-sim"}'::jsonb, '{"xp":284,"credits":55}'::jsonb, false, 8),
  ('mission-be23-09', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'synchronous-service-communication', 'Synchronous Service Communication', 'A function call became a network call, and nothing about that is free. Every synchronous request between services is a new way for one system''s slowness to become another''s.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be23-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"sync-communication-sim"}'::jsonb, '{"xp":286,"credits":55}'::jsonb, false, 9),
  ('mission-be23-10', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'api-gateway', 'API Gateway', 'With several services now answering to the outside world, nobody wants a client that has to know all of their addresses individually. One door in, and the cross-cutting concerns handled exactly once.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be23-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"api-gateway-sim"}'::jsonb, '{"xp":288,"credits":56}'::jsonb, false, 10),
  ('mission-be23-11', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'backend-for-frontend', 'Backend for Frontend', 'One generic API trying to serve a phone on a bad connection and a dashboard that wants everything at once ends up serving neither well. Sometimes the right answer is more than one gateway, not one smarter one.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be23-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"backend-for-frontend-sim"}'::jsonb, '{"xp":290,"credits":56}'::jsonb, false, 11),
  ('mission-be23-12', 'world-be-23', 'campaign-be23', 'operation-be23-2', 'the-distributed-monolith', 'The Distributed Monolith', 'The team''s first split, three weeks old: three deployables, one shared database, and a synchronous call chain four hops deep. Diagnose exactly what makes it a distributed monolith, not real microservices -- and fix it before it gets worse.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be23-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"distributed-monolith-boss-sim"}'::jsonb, '{"xp":620,"credits":145,"badgeIds":["distributed-monolith"],"skillXp":{"software_architecture":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be23-01', 1, 'mira', 'Leadership wants a ''microservices roadmap'' by Friday. Nobody asked whether we should split anything yet -- just how fast.'),
  ('mission-be23-01', 2, 'mira', 'Before we cut anything: a monolith isn''t a mistake by default. One deploy, one transaction, one team that can hold the whole thing in their head -- that''s not nothing. Splitting throws all three away on purpose. Make sure the trade is worth it before you make it.'),
  ('mission-be23-02', 1, 'forge', 'Before we touch the network, there''s a cheaper move: draw the same walls inside the one deployable we already have. A modular monolith -- boundaries enforced by code review and module contracts, not by an API and a load balancer.'),
  ('mission-be23-02', 2, 'forge', 'If a team can''t keep boundaries clean in-process, splitting it across a network won''t fix that. It''ll just make the violations slower and harder to see.'),
  ('mission-be23-03', 1, 'mira', 'The question ''where do we cut'' has an actual answer, not a vibe: cohesion and coupling. High cohesion means everything inside a module changes for the same reason. Low coupling means no other module needs to know how it does it.'),
  ('mission-be23-04', 1, 'forge', 'Before we draw a single line, we need to agree on what we''re even modeling. Domain-driven design gives us the vocabulary: entities, value objects, aggregates, domain events. Get sloppy with these and every boundary drawn on top of them inherits the sloppiness.'),
  ('mission-be23-05', 1, 'mira', 'Billing''s ''Customer'' and Support''s ''Customer'' are not the same thing, and pretending they are is exactly how two teams end up silently overwriting each other''s assumptions.'),
  ('mission-be23-05', 2, 'mira', 'A bounded context is where a model''s meaning stays consistent. Once you leave it, the same word can -- and should -- mean something else.'),
  ('mission-be23-06', 1, 'forge', 'A bounded context is a line on a whiteboard. A service boundary is that same line, enforced in production: nothing crosses it except through a published interface. No shared table, no shared class, no exceptions for ''just this once.'''),
  ('mission-be23-07', 1, 'mira', 'We''ve picked the boundary. Now it has to become a running service without stopping the world for the teams still depending on the old code path.'),
  ('mission-be23-07', 2, 'forge', 'Strangler fig, not a rewrite: build the new service alongside the old module, mirror real traffic to prove it, then cut over -- and only then delete what it replaced.'),
  ('mission-be23-08', 1, 'forge', 'A service that still reads someone else''s tables was never actually independent, no matter how many deploy pipelines it has. Database-per-service is where the split gets tested for real.'),
  ('mission-be23-09', 1, 'mira', 'Every call that used to be a function call is now a network call, and network calls fail in ways function calls never do. That''s not a detail -- it''s the whole risk profile changing underneath you.'),
  ('mission-be23-09', 2, 'forge', 'File it for later: a slow service three hops deep can now make every service upstream of it slow too. We''re not fixing that this Act. We''re just naming it before it happens to us.'),
  ('mission-be23-10', 1, 'forge', 'Nobody wants a mobile client that has to know the individual address of six different services. One door in -- an API gateway -- routes traffic and handles the things every service would otherwise duplicate: auth, rate limits, logging.'),
  ('mission-be23-11', 1, 'mira', 'One gateway API, two very different clients: a phone on a bad connection that wants six fields, and a dashboard that wants five related resources in one round trip. Trying to serve both from one generic shape is how you end up with a wall of if-else per client.'),
  ('mission-be23-11', 2, 'mira', 'Sometimes the fix isn''t a smarter gateway. It''s a backend-for-frontend: a thin API shaped for exactly one client, instead of one API straining to fit all of them.'),
  ('mission-be23-12', 1, 'mira', 'Three weeks since the first split. Three deployables now instead of one monolith. That was supposed to be the win.'),
  ('mission-be23-12', 2, 'forge', 'It isn''t, not yet. All three still write to the same database. And the call chain for a single dispatch request now hops through all three, synchronously, in sequence. We didn''t remove the coupling -- we just put a network between the pieces.'),
  ('mission-be23-12', 3, 'mira', 'That''s not microservices. That''s a distributed monolith -- every cost of the split, none of the benefit. Find exactly what makes it one, and tell me how to actually fix it this time.'),
  ('mission-be23-12', 4, 'forge', '...building the database-per-service map meant tracing every table back to who actually owns it. Which meant tracing every place a query ever crossed a boundary it shouldn''t have. Which meant, for the first time, actually writing down every place the ''//'' pattern has physically touched -- not one incident, not one Act. All of it. On one page.'),
  ('mission-be23-12', 5, 'mira', 'How many?'),
  ('mission-be23-12', 6, 'forge', 'More than I want to say out loud before you''ve seen it. I''m not calling it finished. I''m calling it the first time anyone''s looked at the whole shape at once.'),
  ('mission-be23-12', 7, 'mira', 'Then look at it, and don''t touch anything else tonight. Whatever this turns out to be, it''s bigger than one dispatch endpoint. It always was.'),
  ('mission-be23-12', 8, 'mira', 'Fix the database split first. The map isn''t going anywhere.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be23-01-o1', 'mission-be23-01', 1, 'Weigh the trade-off', 'Judge whether splitting is actually the right call for this team, right now.'),
  ('mission-be23-02-o1', 'mission-be23-02', 1, 'Spot the leaky module', 'Sort each practice into a real modular-monolith boundary or a leaky one.'),
  ('mission-be23-03-o1', 'mission-be23-03', 1, 'Name the problem', 'Match each symptom to the coupling or cohesion problem it actually describes.'),
  ('mission-be23-04-o1', 'mission-be23-04', 1, 'Match the concept', 'Match each DDD term to the definition that actually belongs to it.'),
  ('mission-be23-05-o1', 'mission-be23-05', 1, 'Find the violation', 'Find the evidence that shows the actual bounded-context violation, not just a symptom of it.'),
  ('mission-be23-06-o1', 'mission-be23-06', 1, 'Judge the boundary', 'Decide which option actually respects a service boundary in production.'),
  ('mission-be23-07-o1', 'mission-be23-07', 1, 'Order the extraction', 'Put the steps of extracting a service without downtime in the order they actually happen.'),
  ('mission-be23-08-o1', 'mission-be23-08', 1, 'Find the shared table', 'Find the line that shows the split services still share one database.'),
  ('mission-be23-09-o1', 'mission-be23-09', 1, 'Name the new risk', 'Explain the risk a synchronous call chain introduces that didn''t exist inside the monolith.'),
  ('mission-be23-10-o1', 'mission-be23-10', 1, 'Sort the responsibilities', 'Sort each responsibility into the gateway or the service it actually belongs to.'),
  ('mission-be23-11-o1', 'mission-be23-11', 1, 'Make the case', 'Find the evidence that makes the actual case for a backend-for-frontend.'),
  ('mission-be23-12-o1', 'mission-be23-12', 1, 'Find the shared database', 'Find the evidence that the three deployables don''t actually have independent data.'),
  ('mission-be23-12-o2', 'mission-be23-12', 2, 'Trace the call chain', 'Identify what makes this call chain a distributed-monolith symptom, not a healthy boundary.'),
  ('mission-be23-12-o3', 'mission-be23-12', 3, 'Judge the split', 'Find the evidence that a service was split along the wrong line.'),
  ('mission-be23-12-o4', 'mission-be23-12', 4, 'Fix the split', 'State the one fix that addresses the database, the coupling and the boundary at once.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be23-01-o1-c1', 'mission-be23-01-o1', 1, 'multiple_choice', 'A five-person team ships one product, with a single database transaction spanning order creation and inventory decrement. Someone proposes splitting billing into its own service this sprint. What''s the strongest argument against it right now?', '{"question":"A five-person team ships one product, with a single database transaction spanning order creation and inventory decrement. Someone proposes splitting billing into its own service this sprint. What''s the strongest argument against it right now?","options":[{"id":"a","text":"Microservices are always slower to build, so it''s never worth it"},{"id":"b","text":"Splitting now trades one ACID transaction for a distributed one, adds network calls and two deploy pipelines to coordinate -- for a team too small to own both independently yet"},{"id":"c","text":"The database would need to be rewritten from scratch"},{"id":"d","text":"Only companies larger than 500 engineers are allowed to use microservices"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be23-02-o1-c1', 'mission-be23-02-o1', 1, 'drag_and_drop', 'Sort each practice into a real modular-monolith boundary or a leaky one.', '{"items":[{"id":"i1","text":"Billing module calls OrdersService.getOrderTotal(), a published method"},{"id":"i2","text":"Billing module imports OrdersRepository directly and runs its own SQL against the orders tables"},{"id":"i3","text":"Each module owns its own tables; no other module writes to them directly"},{"id":"i4","text":"A shared ''utils'' folder gradually accumulates business logic every module reaches into"}],"targets":[{"id":"good","label":"Real modular-monolith boundary"},{"id":"leaky","label":"Leaky boundary"}]}'::jsonb, '{"correctMapping":{"i1":"good","i2":"leaky","i3":"good","i4":"leaky"}}'::jsonb),

  ('mission-be23-03-o1-c1', 'mission-be23-03-o1', 1, 'drag_and_drop', 'Match each symptom to the coupling or cohesion problem it actually describes.', '{"items":[{"id":"c1","text":"Two modules must be deployed together or one breaks"},{"id":"c2","text":"A single module handles user auth, invoice PDF generation, and email templating"},{"id":"c3","text":"A module''s internal refactor doesn''t require any other module to change"},{"id":"c4","text":"Every function in the module works with the same data, serving one clear purpose"}],"targets":[{"id":"t1","label":"High coupling"},{"id":"t2","label":"Low cohesion"},{"id":"t3","label":"Low coupling"},{"id":"t4","label":"High cohesion"}]}'::jsonb, '{"correctMapping":{"c1":"t1","c2":"t2","c3":"t3","c4":"t4"}}'::jsonb),

  ('mission-be23-04-o1-c1', 'mission-be23-04-o1', 1, 'drag_and_drop', 'Match each DDD term to the definition that actually belongs to it.', '{"items":[{"id":"d1","text":"Entity"},{"id":"d2","text":"Value Object"},{"id":"d3","text":"Aggregate"},{"id":"d4","text":"Domain Event"}],"targets":[{"id":"def1","label":"Has an identity that persists over time, even as its attributes change"},{"id":"def2","label":"Defined only by its attributes -- two with the same values are interchangeable"},{"id":"def3","label":"A cluster of entities and value objects treated as one consistency boundary, changed only through its root"},{"id":"def4","label":"A record that something meaningful already happened, published for the rest of the system to react to"}]}'::jsonb, '{"correctMapping":{"d1":"def1","d2":"def2","d3":"def3","d4":"def4"}}'::jsonb),

  ('mission-be23-05-o1-c1', 'mission-be23-05-o1', 1, 'investigation', 'Which evidence points at the actual root cause of the conflict between the two teams'' models?', '{"evidence":[{"id":"ev1","label":"Billing''s model","detail":"Billing''s Customer includes creditLimit and paymentTerms"},{"id":"ev2","label":"Support''s model","detail":"Support''s Customer includes ticketHistory and preferredContactMethod"},{"id":"ev3","label":"Shared model","detail":"Both teams import the same shared Customer class and keep adding fields the other has no use for, occasionally overwriting each other''s assumptions about what a null field means"}],"question":"Which evidence points at the actual root cause of the conflict between the two teams'' models?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be23-06-o1-c1', 'mission-be23-06-o1', 1, 'multiple_choice', 'Billing and Fulfillment are now separate bounded contexts. Which of these is a service boundary actually being respected?', '{"question":"Billing and Fulfillment are now separate bounded contexts. Which of these is a service boundary actually being respected?","options":[{"id":"a","text":"Fulfillment reads directly from Billing''s database table to check payment status"},{"id":"b","text":"Fulfillment calls a published Billing API endpoint to check payment status, and doesn''t know how Billing stores it internally"},{"id":"c","text":"Both teams share one ORM model for Order so nothing gets out of sync"},{"id":"d","text":"Fulfillment imports Billing''s internal PaymentService class directly, since they''re in the same repository"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be23-07-o1-c1', 'mission-be23-07-o1', 1, 'interactive_diagram', 'Put the steps of extracting a service without stopping the world in the order they actually happen.', '{"diagramId":"service-extraction-strangler-fig","hotspots":[{"id":"identify_seam","label":"Identify the seam","explanation":"Confirm the bounded context and its boundary are already drawn clearly enough to extract along."},{"id":"build_new_service","label":"Build the new service","explanation":"Stand up the new deployable behind the boundary, not yet receiving any real traffic."},{"id":"shadow_traffic","label":"Shadow real traffic","explanation":"Mirror real production traffic to the new service and compare its results against the old path, without depending on its answer yet."},{"id":"cutover","label":"Cut callers over","explanation":"Switch the boundary''s callers to the new service now that it''s proven itself under real traffic."},{"id":"remove_old_code","label":"Remove the old code path","explanation":"Delete the in-process module now that nothing calls it anymore."}],"task":"Put the steps of extracting a service without stopping the world in the order they actually happen."}'::jsonb, '{"correctOrderIds":["identify_seam","build_new_service","shadow_traffic","cutover","remove_old_code"]}'::jsonb),

  ('mission-be23-08-o1-c1', 'mission-be23-08-o1', 1, 'code_debugging', 'BillingService and FulfillmentService were split into separate deployables, but which line shows they still share one database in a way that defeats the split?', '{"language":"typescript","code":"class BillingService {\n  async getShipmentStatus(orderId: string) {\n    return this.db.query(\"select status from fulfillment.shipments where order_id = $1\", [orderId]);\n  }\n}","question":"BillingService and FulfillmentService were split into separate deployables, but which line shows they still share one database in a way that defeats the split?"}'::jsonb, '{"requiredLineIds":["    return this.db.query(\"select status from fulfillment.shipments where order_id = $1\", [orderId]);"]}'::jsonb),

  ('mission-be23-09-o1-c1', 'mission-be23-09-o1', 1, 'multiple_choice', 'OrderService now calls PaymentService synchronously over HTTP with no timeout configured, three services deep in the chain. What risk does this introduce that didn''t exist inside the monolith?', '{"question":"OrderService now calls PaymentService synchronously over HTTP with no timeout configured, three services deep in the chain. What risk does this introduce that didn''t exist inside the monolith?","options":[{"id":"a","text":"None -- a function call and an HTTP call behave identically"},{"id":"b","text":"If PaymentService is slow, OrderService now blocks waiting on a network call it doesn''t control, and that wait can propagate up the whole chain"},{"id":"c","text":"HTTP calls are always faster than in-process function calls"},{"id":"d","text":"Synchronous calls are only a risk if the services run on different continents"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be23-10-o1-c1', 'mission-be23-10-o1', 1, 'drag_and_drop', 'Sort each responsibility into the gateway or the service it actually belongs to.', '{"items":[{"id":"g1","text":"Routes /billing/* requests to the Billing service"},{"id":"g2","text":"Validates the payment amount against the order total"},{"id":"g3","text":"Terminates TLS and checks the auth token once, for every request"},{"id":"g4","text":"Applies rate limiting per API key across all downstream services"},{"id":"g5","text":"Calculates the customer''s loyalty discount"}],"targets":[{"id":"gateway","label":"Belongs at the API gateway"},{"id":"service","label":"Belongs inside the service"}]}'::jsonb, '{"correctMapping":{"g1":"gateway","g2":"service","g3":"gateway","g4":"gateway","g5":"service"}}'::jsonb),

  ('mission-be23-11-o1-c1', 'mission-be23-11-o1', 1, 'investigation', 'Which evidence makes the actual case for giving mobile and web their own backend-for-frontend, instead of one shared endpoint?', '{"evidence":[{"id":"ev1","label":"Mobile complaint","detail":"The generic /order endpoint returns 40 fields when the app only renders 6, over a slow cell connection"},{"id":"ev2","label":"Web request","detail":"The web dashboard wants five related resources bundled into that same /order response instead of six separate calls"},{"id":"ev3","label":"Endpoint history","detail":"Both teams were told to just add query params to the one shared endpoint, and its conditional logic has grown an else-if branch per client for the past year"}],"question":"Which evidence makes the actual case for giving mobile and web their own backend-for-frontend, instead of one shared endpoint?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be23-12-o1-c1', 'mission-be23-12-o1', 1, 'investigation', 'Which evidence shows the three deployables don''t actually have independent data?', '{"evidence":[{"id":"ev1","label":"Connection strings","detail":"DispatchService, RoutingService, and NotifyService all point at the same nexuscity_core database instance"},{"id":"ev2","label":"Deploy pipelines","detail":"Each service has its own repository, its own URL, and its own deployment pipeline"},{"id":"ev3","label":"Migration log","detail":"RoutingService''s latest migration adds a column to the units table that DispatchService also reads from directly, with no coordination between the two teams"}],"question":"Which evidence shows the three deployables don''t actually have independent data?"}'::jsonb, '{"requiredEvidenceIds":["ev1","ev3"]}'::jsonb),
  ('mission-be23-12-o2-c1', 'mission-be23-12-o2', 1, 'multiple_choice', 'DispatchService calls RoutingService, waits, then calls NotifyService, waits -- three hops, fully sequential, before the original request can return anything. What makes this a distributed-monolith symptom rather than a healthy service boundary?', '{"question":"DispatchService calls RoutingService, waits, then calls NotifyService, waits -- three hops, fully sequential, before the original request can return anything. What makes this a distributed-monolith symptom rather than a healthy service boundary?","options":[{"id":"a","text":"Nothing -- calling other services over HTTP is completely normal"},{"id":"b","text":"The caller is now blocked on two other services'' availability and latency, in sequence, for a request that used to be one in-process call -- a hard-coded chain, not a boundary"},{"id":"c","text":"The problem is that the calls are asynchronous"},{"id":"d","text":"Three services is simply too many for a dispatch system"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be23-12-o3-c1', 'mission-be23-12-o3', 1, 'investigation', 'Which evidence shows a service was split along the wrong line -- file size, not a real bounded context?', '{"evidence":[{"id":"ev1","label":"DispatchService","detail":"Owns dispatch requests and unit assignment -- a real business capability"},{"id":"ev2","label":"RoutingService","detail":"Was split out because ''the routing logic file got too big'', not because it''s a distinct capability -- no model of its own, just functions extracted verbatim from DispatchService"},{"id":"ev3","label":"NotifyService","detail":"Sends SMS and push notifications for every other service, triggered by direct synchronous calls from each"}],"question":"Which evidence shows a service was split along the wrong line -- file size, not a real bounded context?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),
  ('mission-be23-12-o4-c1', 'mission-be23-12-o4', 1, 'boss_encounter', 'Having found all three problems, state the fix that addresses the database, the coupling and the boundary at once.', '{"stages":[{"objectiveRef":"mission-be23-12-o1","label":"The shared database"},{"objectiveRef":"mission-be23-12-o2","label":"The call chain"},{"objectiveRef":"mission-be23-12-o3","label":"The wrong boundary"}],"task":"Having found all three problems, state the fix: real bounded contexts, each service with its own database, replacing the tight synchronous chain with communication the team actually chose on purpose -- not just more deployables."}'::jsonb, '{"requiredObjectiveIds":["mission-be23-12-o1","mission-be23-12-o2","mission-be23-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be23-01-o1-c1', 'orientation', 'Ask what this split actually costs this specific team today, not teams in general.', 10, 1),
  ('mission-be23-01-o1-c1', 'solution', 'A five-person team splitting off billing trades one ACID transaction spanning order and inventory for a distributed one, plus network calls and a second deploy pipeline to coordinate -- for a team too small to own both independently yet.', 20, 2),

  ('mission-be23-02-o1-c1', 'orientation', 'A published method call and a direct table read look almost identical from the outside -- the difference is what breaks when the internals change.', 10, 1),
  ('mission-be23-02-o1-c1', 'solution', 'i1 and i3 only touch other modules through a published interface and their own tables; i2 and i4 both reach past that into internals nobody agreed to expose.', 20, 2),

  ('mission-be23-03-o1-c1', 'orientation', 'Ask, for each statement, whether it''s about how tightly one module holds together, or how tightly two modules are stuck to each other.', 10, 1),
  ('mission-be23-03-o1-c1', 'solution', 'c1 and c3 are about coupling (stuck together / not stuck together); c2 and c4 are about cohesion (unrelated jobs crammed in / one clear job).', 20, 2),

  ('mission-be23-04-o1-c1', 'orientation', 'Identity versus attributes is the fork in the road: does ''sameness'' mean same identity, or same values?', 10, 1),
  ('mission-be23-04-o1-c1', 'concept', 'An Entity keeps being ''the same one'' even after every attribute changes. A Value Object with different attributes is just a different value -- there''s no identity to track.', 20, 2),
  ('mission-be23-04-o1-c1', 'solution', 'Entity -> persists identity through change; Value Object -> defined only by its attributes; Aggregate -> a consistency boundary with one root; Domain Event -> a fact worth telling the rest of the system about.', 30, 3),

  ('mission-be23-05-o1-c1', 'orientation', 'Two teams can legitimately have two different models of the same real-world word -- that''s not automatically the bug.', 10, 1),
  ('mission-be23-05-o1-c1', 'solution', 'ev3 is the actual root cause: one shared class trying to serve two contexts at once, with each team silently overwriting assumptions the other made. ev1 and ev2 are just what two healthy, separate models would look like.', 20, 2),

  ('mission-be23-06-o1-c1', 'orientation', 'A service boundary that can still be bypassed by reading someone else''s table isn''t really a boundary.', 10, 1),
  ('mission-be23-06-o1-c1', 'solution', 'Only b keeps the interaction behind a published API -- the others all reach across the boundary directly, through a shared table, a shared model, or an internal class.', 20, 2),

  ('mission-be23-07-o1-c1', 'orientation', 'Nothing gets deleted before something new has already proven itself under real traffic.', 10, 1),
  ('mission-be23-07-o1-c1', 'concept', 'Building the new service and cutting real traffic over to it are two different, separated steps -- proving it works comes before anyone depends on it.', 20, 2),
  ('mission-be23-07-o1-c1', 'solution', 'Identify the seam, build the new service behind it, mirror real traffic to it without depending on the result, cut callers over, then delete the old code path.', 30, 3),

  ('mission-be23-08-o1-c1', 'orientation', 'Two services with two separate deploy pipelines can still share data the wrong way.', 10, 1),
  ('mission-be23-08-o1-c1', 'concept', 'If BillingService can name Fulfillment''s schema and table directly, the two were never actually independent -- a schema change in Fulfillment can break Billing without either team knowing.', 20, 2),
  ('mission-be23-08-o1-c1', 'solution', 'The query line reaches directly into fulfillment.shipments -- exactly the shared-database coupling database-per-service is supposed to remove.', 30, 3),

  ('mission-be23-09-o1-c1', 'orientation', 'Inside the monolith, a slow function just made one request slow. What''s different now that it''s a call over a network with no timeout?', 10, 1),
  ('mission-be23-09-o1-c1', 'solution', 'The caller now blocks on a service it doesn''t control, for as long as that service takes -- and with no timeout, that wait has no ceiling and can propagate up the chain.', 20, 2),

  ('mission-be23-10-o1-c1', 'orientation', 'Ask which of these has to happen identically for every request regardless of which service handles it, and which depends on that specific service''s own business rules.', 10, 1),
  ('mission-be23-10-o1-c1', 'solution', 'Routing, TLS/auth termination and rate limiting apply the same way to every request -- they belong at the gateway. Validating a payment or calculating a discount is specific business logic that belongs in the service.', 20, 2),

  ('mission-be23-11-o1-c1', 'orientation', 'Two teams wanting different things from the same endpoint is normal. The problem is what trying to serve both from one shape does to that endpoint over time.', 10, 1),
  ('mission-be23-11-o1-c1', 'solution', 'ev3 is the actual case for a BFF: a year of accumulated per-client conditionals in one shared endpoint. ev1 and ev2 are just the two teams'' legitimate, different needs -- the reason a BFF is worth building, but not themselves the evidence of the failure mode.', 20, 2),

  ('mission-be23-12-o1-c1', 'orientation', 'Two things can look independent -- separate URLs, separate pipelines -- while still writing to the exact same data underneath.', 10, 1),
  ('mission-be23-12-o1-c1', 'solution', 'ev1 (one shared database instance) and ev3 (an uncoordinated schema change one service silently depends on) both show the same underlying data, not independent data -- ev2 describes independent deployment, which isn''t the same thing as independent data.', 20, 2),
  ('mission-be23-12-o2-c1', 'orientation', 'Compare what this chain costs to what the exact same logic cost as three function calls inside one process.', 10, 1),
  ('mission-be23-12-o2-c1', 'solution', 'The request is now blocked on two other services'' availability and latency, in sequence, before it can return anything -- a chain of hard dependencies where there used to be one in-process call.', 20, 2),
  ('mission-be23-12-o3-c1', 'orientation', 'A boundary drawn because ''the file got big'' isn''t the same thing as a boundary drawn around a real business capability.', 10, 1),
  ('mission-be23-12-o3-c1', 'solution', 'ev2 is the tell: RoutingService has no model of its own, just code extracted verbatim because a file was too long -- split along a technical line, not a bounded context.', 20, 2),
  ('mission-be23-12-o4-c1', 'orientation', 'Look at what all three findings shared as a category, not as three separate problems to patch individually.', 15, 1),
  ('mission-be23-12-o4-c1', 'solution', 'The fix isn''t fewer services -- it''s real boundaries: split along actual bounded contexts, give each its own database, and replace the accidental synchronous chain with calls the team actually chose on purpose.', 25, 2);
