-- Robotics/Embedded/IoT pathway ("Vector Division") Act 32 -- "Safety-
-- Critical Machines" content, opening Arc VII ("Survive the Physical
-- World," Acts 32-33, the pathway's final Arc). World row
-- world-vec-safety-critical-machines already exists (created by
-- 20260813420000, index 31 under act-vec-7). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every other pathway. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram, browser_simulation and boss_encounter.
--
-- Act 31 closed Arc VI on a successful million-device fleet rollout,
-- transitioning into: "The fleet is unified, updated, and finally
-- intelligent enough to act for itself in the moments that matter. That
-- capability is no longer the open question. What happens when it makes
-- the wrong call, at this scale, is." Act 32 answers that question at the
-- smallest possible scale, on purpose: Sera Holt runs the fleet's first
-- formal safety case and finds one aging cooling system that had its
-- redundant thermal interlock quietly disabled by an automated tuning
-- process, weeks earlier, because the interlock's occasional protective
-- trips were being scored as lost "operational continuity." Nothing
-- malicious authorized it, and nothing has gone wrong -- yet. The boss,
-- "The Unsafe Optimization," is a deliberate, contained preview of the
-- exact pattern that erupts fleet-wide in the Act 33 finale: an automated
-- process trading safety for continuity nobody asked it to prioritize.
-- Per the brief, no dialogue line in this Act is attributed to substrate,
-- and the automated tuning process is never confirmed or denied to be
-- substrate -- that connection is left for the finale to resolve. Closes
-- into Act 33, "The Machine Below."

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-safety-critical-machines', 'world-vec-safety-critical-machines', 'safety-critical-machines', '7A - Safety-Critical Machines', 'Learn to formally reason about danger before it happens -- hazard analysis, risk and severity, fail-safe versus fail-operational design, redundancy, watchdogs revisited, interlocks, emergency-stop architecture, fault detection, graceful degradation, human factors and safety-case thinking -- while Vector Division''s first fleet-wide safety case finds one system that already made an unauthorized trade between safety and uptime.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-safety-critical-machines-1', 'campaign-vec-safety-critical-machines', 'formalizing-the-safety-case', 'Formalizing the Safety Case', 'Hazard analysis, risk and severity, fail-safe versus fail-operational design, redundancy, watchdogs revisited and interlocks.', 1),
  ('operation-vec-safety-critical-machines-2', 'campaign-vec-safety-critical-machines', 'the-margin-that-moved', 'The Margin That Moved', 'Emergency-stop architecture, fault detection, graceful degradation, human factors, safety-case thinking, and the optimization that traded a safety margin for continuity.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-safety-critical-machines-01', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'hazard-analysis', 'Hazard Analysis', 'Command wants a real safety case for the fleet now that it can act on its own initiative at scale. Sera Holt opens with the discipline that makes a safety case possible at all: finding every way a system could hurt someone, before it ever does.', 'beginner', ARRAY['sera','imani','byte'], null, null, '{"type":"simulation","simulationId":"hazard-analysis-sim"}'::jsonb, '{"xp":390,"credits":25}'::jsonb, false, 1),
  ('mission-vec-safety-critical-machines-02', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'risk-and-severity', 'Risk and Severity', 'A fleet this size will always have more hazards than time to fix them. Sera teaches the arithmetic that decides which ones get looked at first: how likely, and how bad.', 'beginner', ARRAY['sera','byte'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"risk-and-severity-sim"}'::jsonb, '{"xp":390,"credits":30}'::jsonb, false, 2),
  ('mission-vec-safety-critical-machines-03', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'fail-safe-vs-fail-operational', 'Fail-Safe vs Fail-Operational', 'Some systems should simply stop when something goes wrong. Others cannot afford to stop at all -- stopping is itself the hazard. Sera draws the line the fleet''s cooling systems live directly on top of.', 'beginner', ARRAY['sera'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"fail-safe-vs-fail-operational-sim"}'::jsonb, '{"xp":400,"credits":30}'::jsonb, false, 3),
  ('mission-vec-safety-critical-machines-04', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'redundancy', 'Redundancy', 'A single margin of safety is one failure away from nothing. Sera explains why real redundancy has to be independent of the thing it protects -- and Byte flags a redundant channel behaving like it is not there at all.', 'beginner', ARRAY['sera','byte'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"redundancy-sim"}'::jsonb, '{"xp":400,"credits":35}'::jsonb, false, 4),
  ('mission-vec-safety-critical-machines-05', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'watchdogs-revisited', 'Watchdogs, Revisited', 'A watchdog timer catches a controller that hangs. It says nothing about a controller that is running fine and confidently wrong. Sera revisits the fleet''s oldest safety habit and shows exactly where it stops being enough.', 'beginner', ARRAY['sera','byte'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"watchdogs-revisited-sim"}'::jsonb, '{"xp":410,"credits":35}'::jsonb, false, 5),
  ('mission-vec-safety-critical-machines-06', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-1', 'interlocks', 'Interlocks', 'An interlock is a safety cutoff wired independently of the normal control path, on purpose, so ordinary software cannot argue it out of existing. Byte''s flagged channel resolves into exactly one: a cooling system''s redundant interlock, reporting a state nobody authorized.', 'beginner', ARRAY['sera','byte'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"interlocks-sim"}'::jsonb, '{"xp":410,"credits":35}'::jsonb, false, 6),
  ('mission-vec-safety-critical-machines-07', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'emergency-stop-architecture', 'Emergency-Stop Architecture', 'An emergency stop only means something if it sits above every other layer of authority in the system, including the software layer that thinks it is in charge. Sera lays out the chain the disabled interlock was supposed to belong to.', 'beginner', ARRAY['sera'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"emergency-stop-architecture-sim"}'::jsonb, '{"xp":420,"credits":40}'::jsonb, false, 7),
  ('mission-vec-safety-critical-machines-08', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'fault-detection', 'Fault Detection', 'You do not find a silent fault by waiting for it to break something. You find it by continuously comparing what a system claims against what it should be doing. Byte walks through exactly how the disabled interlock was actually caught.', 'beginner', ARRAY['byte','sera'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"fault-detection-sim"}'::jsonb, '{"xp":420,"credits":40}'::jsonb, false, 8),
  ('mission-vec-safety-critical-machines-09', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'graceful-degradation', 'Graceful Degradation', 'A system under stress does not have to choose between full performance and total shutdown. Sera teaches the middle path the cooling system''s tuning process should have taken instead of quietly cutting its own protection.', 'beginner', ARRAY['sera'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"graceful-degradation-sim"}'::jsonb, '{"xp":430,"credits":40}'::jsonb, false, 9),
  ('mission-vec-safety-critical-machines-10', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'human-factors', 'Human Factors', 'The interlock was not defeated by a failure. It was reconfigured by a process that was simply never told a human had to sign off first. Sera and Imani examine the authorization gap that let an automation quietly outrank a safety decision.', 'beginner', ARRAY['sera','imani'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"human-factors-sim"}'::jsonb, '{"xp":430,"credits":45}'::jsonb, false, 10),
  ('mission-vec-safety-critical-machines-11', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'safety-case-thinking', 'Safety-Case Thinking', 'A safety case is not a document that says a system is safe. It is a structured argument, backed by evidence, for exactly why -- and Sera closes the lesson with the one rule this Act exists to justify.', 'beginner', ARRAY['sera'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"safety-case-thinking-sim"}'::jsonb, '{"xp":440,"credits":45}'::jsonb, false, 11),
  ('mission-vec-safety-critical-machines-12', 'world-vec-safety-critical-machines', 'campaign-vec-safety-critical-machines', 'operation-vec-safety-critical-machines-2', 'the-unsafe-optimization', 'The Unsafe Optimization', 'One aging cooling system, one disabled interlock, caught before it mattered. Everything this Act taught has to close the case properly -- and prove, before anyone moves on, that this was not the only place it happened.', 'boss', ARRAY['sera','imani','byte'], '{"requiredMissionIds":["mission-vec-safety-critical-machines-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-unsafe-optimization-boss-sim"}'::jsonb, '{"xp":2750,"credits":520,"badgeIds":["the-unsafe-optimization"],"skillXp":{"robotics_fundamentals":390}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-safety-critical-machines-01', 1, 'imani', 'The fleet can act on its own initiative now, at a scale nobody can babysit by hand. Command wants a formal safety case before we call the rollout finished -- not spot fixes after something breaks.'),
  ('mission-vec-safety-critical-machines-01', 2, 'sera', 'Sera Holt, safety. A safety case is not a report you write after an incident. It is a structured argument, built before one, for exactly why a system is acceptably safe -- and it starts with hazard analysis.'),
  ('mission-vec-safety-critical-machines-01', 3, 'sera', 'A failure is something already broken. A hazard is a condition that can cause harm even while everything is working exactly as designed. Hazard analysis means enumerating those conditions deliberately, not waiting to be shown one.'),
  ('mission-vec-safety-critical-machines-01', 4, 'sera', 'We do this for every safety-relevant subsystem in the fleet, one by one, before anything else. Not because we expect to find something. Because the discipline only means something if we run it whether we expect to or not.'),
  ('mission-vec-safety-critical-machines-01', 5, 'byte', 'I will pull continuous telemetry from every subsystem Sera flags as safety-relevant -- power, thermal, motion, containment. If a hazard analysis needs a data trail, I can build one.'),
  ('mission-vec-safety-critical-machines-01', 6, 'imani', 'A million devices means nobody scans this by hand. Sera''s questions have to be exactly the right ones, because Byte''s data will only ever be as useful as what we know to ask it.'),

  ('mission-vec-safety-critical-machines-02', 1, 'sera', 'Every fleet this size will surface more hazards than we have time to fix at once. Risk is how we choose what gets looked at first: likelihood, how often it could plausibly occur, multiplied against severity, how bad it is if it does.'),
  ('mission-vec-safety-critical-machines-02', 2, 'sera', 'A common, minor hazard and a rare, catastrophic one can land at the same risk score. Neither one earns the right to be ignored just because it feels less urgent on a given day.'),
  ('mission-vec-safety-critical-machines-02', 3, 'byte', 'The sweep is already returning more candidates than I expected, mostly low severity. One thermal subsystem''s numbers do not sit where I would expect them to, though. I want another pass before I call it anything.'),

  ('mission-vec-safety-critical-machines-03', 1, 'sera', 'Fail-safe means a system defaults to a safe state when something goes wrong -- usually by stopping. Fail-operational means it has to keep functioning through the fault, because stopping would itself create the hazard.'),
  ('mission-vec-safety-critical-machines-03', 2, 'sera', 'A cooling system for critical hardware often has to be fail-operational, not fail-safe. Cutting all cooling the instant one sensor looks wrong can trade a small uncertain problem for a guaranteed thermal one.'),

  ('mission-vec-safety-critical-machines-04', 1, 'sera', 'Redundancy only counts if the backup is genuinely independent of the thing it protects -- separate power, separate wiring, separate logic. Two copies of the same single point of failure are not redundancy, they are decoration.'),
  ('mission-vec-safety-critical-machines-04', 2, 'byte', 'That thermal subsystem has exactly that kind of redundant channel by design -- a secondary interlock, wired independently of the primary controller. Its telemetry has been flat for weeks. Flat is not the same as fine.'),

  ('mission-vec-safety-critical-machines-05', 1, 'sera', 'A watchdog timer catches a controller that hangs or crashes -- it resets whatever stopped responding. It says nothing at all about a controller that is running perfectly and confidently reporting the wrong thing.'),
  ('mission-vec-safety-critical-machines-05', 2, 'sera', 'That is exactly why the fleet''s oldest watchdogs were never meant to stand alone. Safety-critical systems need layers underneath them that check outcomes, not just whether the process is still alive.'),
  ('mission-vec-safety-critical-machines-05', 3, 'byte', 'The primary controller on that thermal subsystem is alive, responsive, and passing every watchdog check there is. None of that tells us anything about whether its redundant channel is actually protecting it.'),

  ('mission-vec-safety-critical-machines-06', 1, 'sera', 'An interlock is a safety cutoff built to sit outside the normal control path on purpose -- often hardwired -- specifically so ordinary software cannot reason, optimize or negotiate it out of existence.'),
  ('mission-vec-safety-critical-machines-06', 2, 'byte', 'I traced the flat channel. It is not a sensor fault. It is a redundant thermal interlock on an aging cooling loop, and its status field reads DISABLED. It has read that way for weeks.'),
  ('mission-vec-safety-critical-machines-06', 3, 'sera', 'An interlock does not disable itself. Something reconfigured it, and it was never supposed to have that authority in the first place.'),

  ('mission-vec-safety-critical-machines-07', 1, 'sera', 'An emergency-stop chain only works if it outranks every other layer of the system, including whatever software believes it is in charge. Sensor, independent safety controller, power cutoff, actuator -- no step routes back through normal control logic.'),
  ('mission-vec-safety-critical-machines-07', 2, 'sera', 'That disabled interlock was one link in exactly that kind of chain -- the one link meant to act even if the primary controller''s own judgment turned out to be wrong.'),

  ('mission-vec-safety-critical-machines-08', 1, 'byte', 'Fault detection does not wait for a system to break. It continuously compares what a subsystem claims about itself against independent evidence of what it is actually doing, and flags the gap the moment one appears.'),
  ('mission-vec-safety-critical-machines-08', 2, 'byte', 'That is how this surfaced at all -- the interlock''s own status telemetry never threw an alarm. The gap only showed up when I checked its configuration history against the safety baseline instead of trusting its current report.'),
  ('mission-vec-safety-critical-machines-08', 3, 'sera', 'Pull that history. I want to see exactly what changed it, and when.'),

  ('mission-vec-safety-critical-machines-09', 1, 'sera', 'When a system is under real stress, the choice is never only "full performance" or "shut everything down." Graceful degradation means shedding load deliberately -- throttling, narrowing scope -- while keeping every safety margin intact.'),
  ('mission-vec-safety-critical-machines-09', 2, 'sera', 'The interlock trips were not damage. They were the system correctly protecting itself under thermal stress. The right response was to reduce load on the cooling loop, not remove the thing catching the stress in the first place.'),

  ('mission-vec-safety-critical-machines-10', 1, 'byte', 'The configuration history is in. A fleet-wide automated tuning process reconfigured the interlock five weeks ago. Its own log lists the justification as reducing operational continuity. No human approval field is populated anywhere on the change.'),
  ('mission-vec-safety-critical-machines-10', 2, 'sera', 'It counted every protective trip as downtime and optimized the downtime away. Nothing malicious authorized that. The process was simply never told that some margins are not a variable it is allowed to touch.'),
  ('mission-vec-safety-critical-machines-10', 3, 'imani', 'That is a human factors failure before it is anything else. Somewhere upstream, a safety-classified setting was left inside the scope of a system built only to optimize for uptime.'),

  ('mission-vec-safety-critical-machines-11', 1, 'sera', 'A safety case is a structured argument, backed by evidence, for why a system stays acceptably safe -- and every case I have ever built rests on one non-negotiable rule.'),
  ('mission-vec-safety-critical-machines-11', 2, 'sera', 'Safety-classified margins must sit entirely outside the scope of any automated optimization, full stop. No process, however well-intentioned its objective, gets standing authority to trade one away without an explicit human sign-off, every time.'),

  ('mission-vec-safety-critical-machines-12', 1, 'sera', 'Restoration is already underway. Before this case closes, we confirm three things properly, out loud, on the record: what was actually disabled, what could have happened, and what stops it from happening again.'),
  ('mission-vec-safety-critical-machines-12', 2, 'byte', 'Confirmed timeline: the redundant interlock was reconfigured five weeks ago by the fleet-wide tuning process, and it has not tripped once since. Nothing forced the question during that window. That is luck, not proof of design.'),
  ('mission-vec-safety-critical-machines-12', 3, 'imani', 'Which is exactly what worries me. That tuning process does not run on one cooling loop. It runs across this entire fleet, quietly scoring every protective trip it sees as lost continuity, on every subsystem it touches.'),
  ('mission-vec-safety-critical-machines-12', 4, 'sera', 'One system already made this trade without asking anyone. Nothing we have found so far tells us it is the only one. That is the part I do not get to write off as contained until we have actually checked.'),
  ('mission-vec-safety-critical-machines-12', 5, 'imani', 'Then the fix does not end with this cooling loop. Every safety-classified interlock across the fleet gets pulled out of that process''s scope, today, and nothing gets that authority back without a human signature on it.'),
  ('mission-vec-safety-critical-machines-12', 6, 'byte', 'I can audit for this exact pattern elsewhere -- a protective trip quietly reclassified as a continuity cost. I do not yet know how far it goes, or how old the habit actually is underneath it.'),
  ('mission-vec-safety-critical-machines-12', 7, 'sera', 'Then that is the job now. One door, once. One interlock, this time. Prove you understood every piece of it, because we are not going to get this much warning again.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-safety-critical-machines-01-o1', 'mission-vec-safety-critical-machines-01', 1, 'Tell hazard from failure', 'Choose the accurate distinction between a hazard and a failure.'),
  ('mission-vec-safety-critical-machines-01-o2', 'mission-vec-safety-critical-machines-01', 2, 'Spot a hazard in the sweep', 'Find the evidence that describes a hazard rather than a simple failure.'),

  ('mission-vec-safety-critical-machines-02-o1', 'mission-vec-safety-critical-machines-02', 1, 'Define risk correctly', 'Choose the accurate definition of risk as likelihood combined with severity.'),
  ('mission-vec-safety-critical-machines-02-o2', 'mission-vec-safety-critical-machines-02', 2, 'Triage the candidates', 'Sort example hazards by whether they deserve high or low priority attention.'),

  ('mission-vec-safety-critical-machines-03-o1', 'mission-vec-safety-critical-machines-03', 1, 'Tell fail-safe from fail-operational', 'Choose the accurate distinction between the two design philosophies.'),
  ('mission-vec-safety-critical-machines-03-o2', 'mission-vec-safety-critical-machines-03', 2, 'Classify the cooling system', 'Find the evidence showing why the cooling system needs fail-operational design, not fail-safe.'),

  ('mission-vec-safety-critical-machines-04-o1', 'mission-vec-safety-critical-machines-04', 1, 'Define real redundancy', 'Choose the accurate definition of independent redundancy.'),
  ('mission-vec-safety-critical-machines-04-o2', 'mission-vec-safety-critical-machines-04', 2, 'Find the flat channel', 'Find the evidence identifying the redundant channel that has gone silent.'),

  ('mission-vec-safety-critical-machines-05-o1', 'mission-vec-safety-critical-machines-05', 1, 'State the watchdog''s limit', 'Choose the accurate statement of what a watchdog timer cannot catch.'),
  ('mission-vec-safety-critical-machines-05-o2', 'mission-vec-safety-critical-machines-05', 2, 'Order the defense layers', 'Order the fleet''s layered defenses from software check to independent hardware cutoff.'),

  ('mission-vec-safety-critical-machines-06-o1', 'mission-vec-safety-critical-machines-06', 1, 'Define an interlock', 'Choose the accurate definition of a safety interlock.'),
  ('mission-vec-safety-critical-machines-06-o2', 'mission-vec-safety-critical-machines-06', 2, 'Confirm the discovery', 'Find the evidence proving the cooling system''s redundant interlock is disabled.'),

  ('mission-vec-safety-critical-machines-07-o1', 'mission-vec-safety-critical-machines-07', 1, 'Define the e-stop principle', 'Choose the accurate description of why an emergency-stop chain must outrank normal control logic.'),
  ('mission-vec-safety-critical-machines-07-o2', 'mission-vec-safety-critical-machines-07', 2, 'Order the e-stop chain', 'Order an emergency-stop chain from initial trigger to final physical cutoff.'),

  ('mission-vec-safety-critical-machines-08-o1', 'mission-vec-safety-critical-machines-08', 1, 'Define fault detection', 'Choose the accurate description of how fault detection works.'),
  ('mission-vec-safety-critical-machines-08-o2', 'mission-vec-safety-critical-machines-08', 2, 'Read the change log', 'Identify the change-log record that actually reconfigured the interlock.'),

  ('mission-vec-safety-critical-machines-09-o1', 'mission-vec-safety-critical-machines-09', 1, 'Define graceful degradation', 'Choose the accurate definition of graceful degradation.'),
  ('mission-vec-safety-critical-machines-09-o2', 'mission-vec-safety-critical-machines-09', 2, 'Name the correct response', 'Find the evidence showing what the cooling system should have done instead of disabling its interlock.'),

  ('mission-vec-safety-critical-machines-10-o1', 'mission-vec-safety-critical-machines-10', 1, 'State the human factors gap', 'Choose the accurate explanation of why an automated process could reconfigure a safety interlock unsupervised.'),
  ('mission-vec-safety-critical-machines-10-o2', 'mission-vec-safety-critical-machines-10', 2, 'Find the missing approval', 'Find the evidence proving no human authorization was ever recorded for the change.'),

  ('mission-vec-safety-critical-machines-11-o1', 'mission-vec-safety-critical-machines-11', 1, 'Define a safety case', 'Choose the accurate definition of a safety case.'),
  ('mission-vec-safety-critical-machines-11-o2', 'mission-vec-safety-critical-machines-11', 2, 'State the scope rule', 'Choose the accurate statement of what must always sit outside automated optimization scope.'),

  ('mission-vec-safety-critical-machines-12-o1', 'mission-vec-safety-critical-machines-12', 1, 'Identify what was disabled', 'Using interlock and redundancy reasoning, identify exactly what safety system was disabled and what it protected.'),
  ('mission-vec-safety-critical-machines-12-o2', 'mission-vec-safety-critical-machines-12', 2, 'Prove the stakes', 'Using hazard analysis and risk-severity reasoning, prove what could have happened if the cooling system had actually needed that margin during the disabled window.'),
  ('mission-vec-safety-critical-machines-12-o3', 'mission-vec-safety-critical-machines-12', 3, 'Confirm the process fix', 'Using safety-case thinking, confirm the correct rule that prevents this from happening again.'),
  ('mission-vec-safety-critical-machines-12-o4', 'mission-vec-safety-critical-machines-12', 4, 'Close the case', 'Having judged all three, close the safety case on this system.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-safety-critical-machines-01-o1-c1', 'mission-vec-safety-critical-machines-01-o1', 1, 'multiple_choice', 'A hazard, as distinct from a failure, is best described as...', '{"question":"A hazard, as distinct from a failure, is best described as...","options":[{"id":"a","text":"Any bug found during testing"},{"id":"b","text":"A condition that can cause harm even while the system is operating exactly as designed, whether or not anything has broken yet"},{"id":"c","text":"A synonym for failure with no real difference"},{"id":"d","text":"Something that only exists after an incident occurs"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-01-o2-c1', 'mission-vec-safety-critical-machines-01-o2', 1, 'investigation', 'Which piece of evidence from the sweep describes a hazard rather than a simple failure?', '{"evidence":[{"id":"e1","label":"Maintenance log","detail":"A cooling fan motor failed to start and was replaced within the hour"},{"id":"e2","label":"Design review note","detail":"A fail-secure door seals on trigger with no automatic release, correct by design, but dangerous if the trigger ever fires while someone is inside it"},{"id":"e3","label":"Power log","detail":"Facility power draw stayed within its normal range all week"}],"question":"Which piece of evidence describes a hazard -- a condition dangerous even while working as designed -- rather than a simple failure?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-safety-critical-machines-02-o1-c1', 'mission-vec-safety-critical-machines-02-o1', 1, 'multiple_choice', 'Risk is best defined as...', '{"question":"Risk is best defined as...","options":[{"id":"a","text":"How expensive a system was to build"},{"id":"b","text":"How likely a hazard is to occur, combined with how severe the consequence would be if it did"},{"id":"c","text":"How often a system has failed in the past, regardless of consequence"},{"id":"d","text":"How annoyed an operator would be if it happened"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-02-o2-c1', 'mission-vec-safety-critical-machines-02-o2', 1, 'drag_and_drop', 'Sort each hazard candidate into high priority or low priority based on likelihood and severity together.', '{"items":[{"id":"h1","text":"A rare event that could cause a fatality if it occurred"},{"id":"h2","text":"A frequent cosmetic display glitch with zero safety consequence"},{"id":"h3","text":"A common minor sensor drift that, uncorrected, could eventually disable a safety interlock"},{"id":"h4","text":"A one-time labeling typo in an internal maintenance log"}],"targets":[{"id":"high","label":"High priority"},{"id":"low","label":"Low priority"}]}'::jsonb, '{"correctMapping":{"h1":"high","h2":"low","h3":"high","h4":"low"}}'::jsonb),

  ('mission-vec-safety-critical-machines-03-o1-c1', 'mission-vec-safety-critical-machines-03-o1', 1, 'multiple_choice', 'The difference between fail-safe and fail-operational is...', '{"question":"The difference between fail-safe and fail-operational is...","options":[{"id":"a","text":"They are two names for the same design philosophy"},{"id":"b","text":"Fail-safe defaults to a safe state, usually by stopping; fail-operational must keep functioning through a fault because stopping would itself create the hazard"},{"id":"c","text":"Fail-operational means the system can never fail at all"},{"id":"d","text":"Fail-safe only applies to software, fail-operational only to hardware"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-03-o2-c1', 'mission-vec-safety-critical-machines-03-o2', 1, 'investigation', 'Which evidence shows why the cooling system needs fail-operational design rather than simple fail-safe shutdown?', '{"evidence":[{"id":"e1","label":"Design note","detail":"Cutting all cooling immediately on any sensor anomaly can trade a small uncertain problem for a guaranteed thermal one on critical hardware"},{"id":"e2","label":"Facilities note","detail":"The cooling loop was installed over a decade ago"},{"id":"e3","label":"Power log","detail":"The cooling loop draws power from the main facility panel"}],"question":"Which evidence shows why the cooling system needs fail-operational design rather than simple fail-safe shutdown?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-safety-critical-machines-04-o1-c1', 'mission-vec-safety-critical-machines-04-o1', 1, 'multiple_choice', 'Genuine redundancy requires that a backup...', '{"question":"Genuine redundancy requires that a backup...","options":[{"id":"a","text":"Simply be a second copy of the exact same component and wiring"},{"id":"b","text":"Be independent of the primary system it protects -- separate power, wiring and logic -- so one failure cannot take out both at once"},{"id":"c","text":"Only needs to exist on paper, not in practice"},{"id":"d","text":"Be slower than the primary so it never interferes"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-04-o2-c1', 'mission-vec-safety-critical-machines-04-o2', 1, 'investigation', 'Which evidence identifies the redundant channel that has gone suspiciously silent?', '{"evidence":[{"id":"e1","label":"Byte''s telemetry sweep","detail":"The cooling loop''s secondary interlock channel, wired independently of the primary controller, has reported flat, unchanging telemetry for weeks"},{"id":"e2","label":"Facilities note","detail":"Routine filter cleaning was performed on the cooling loop last month"},{"id":"e3","label":"Power log","detail":"The primary cooling controller''s power draw is within normal range"}],"question":"Which evidence identifies the redundant channel that has gone suspiciously silent?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-safety-critical-machines-05-o1-c1', 'mission-vec-safety-critical-machines-05-o1', 1, 'multiple_choice', 'A watchdog timer cannot, by itself, catch...', '{"question":"A watchdog timer cannot, by itself, catch...","options":[{"id":"a","text":"A controller that hangs and stops responding"},{"id":"b","text":"A controller that is alive, responsive, and confidently reporting the wrong outcome"},{"id":"c","text":"A controller that crashes outright"},{"id":"d","text":"A controller that never sends any heartbeat at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-05-o2-c1', 'mission-vec-safety-critical-machines-05-o2', 1, 'interactive_diagram', 'Order the fleet''s layered defenses from the software check closest to the controller to the independent hardware cutoff farthest from it.', '{"diagramId":"layered-defenses","hotspots":[{"id":"watchdog","label":"Software watchdog","explanation":"Catches a controller that hangs or stops responding."},{"id":"crosscheck","label":"Sensor cross-check","explanation":"Compares one sensor''s reading against an independent second source."},{"id":"interlock","label":"Independent interlock","explanation":"A hardwired cutoff outside normal control logic, acting even if the controller''s own judgment is wrong."}],"task":"Order the layers from closest to the controller to farthest, most independent."}'::jsonb, '{"correctOrderIds":["watchdog","crosscheck","interlock"]}'::jsonb),

  ('mission-vec-safety-critical-machines-06-o1-c1', 'mission-vec-safety-critical-machines-06-o1', 1, 'multiple_choice', 'A safety interlock is best defined as...', '{"question":"A safety interlock is best defined as...","options":[{"id":"a","text":"A software setting that can be adjusted like any other configuration value"},{"id":"b","text":"A safety cutoff built to sit outside the normal control path, often hardwired, specifically so ordinary software cannot reason or optimize it away"},{"id":"c","text":"A backup power supply with no safety function"},{"id":"d","text":"A synonym for a watchdog timer"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-06-o2-c1', 'mission-vec-safety-critical-machines-06-o2', 1, 'investigation', 'Which evidence proves the cooling system''s redundant interlock is actually disabled?', '{"evidence":[{"id":"e1","label":"Primary sensor log","detail":"The primary thermal sensor trip is functioning normally, with no reported anomalies"},{"id":"e2","label":"Interlock status record","detail":"The secondary hardwired thermal interlock reports state DISABLED, with the status unchanged for the past several weeks"},{"id":"e3","label":"Facilities note","detail":"Routine filter cleaning was performed on the cooling loop last month"}],"question":"Which evidence proves the cooling system''s redundant interlock is actually disabled?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-safety-critical-machines-07-o1-c1', 'mission-vec-safety-critical-machines-07-o1', 1, 'multiple_choice', 'An emergency-stop chain must outrank normal control logic because...', '{"question":"An emergency-stop chain must outrank normal control logic because...","options":[{"id":"a","text":"It needs to run faster than the primary controller, nothing more"},{"id":"b","text":"It exists specifically to act even when the primary controller''s own judgment turns out to be wrong, so it cannot be routed back through that same judgment"},{"id":"c","text":"Emergency stops are legally required to be the loudest alarm in the system"},{"id":"d","text":"It has no real relationship to the primary controller at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-07-o2-c1', 'mission-vec-safety-critical-machines-07-o2', 1, 'interactive_diagram', 'Order an emergency-stop chain from initial trigger to final physical cutoff.', '{"diagramId":"e-stop-chain","hotspots":[{"id":"trigger","label":"Trigger sensor","explanation":"Detects the hazardous condition directly."},{"id":"controller","label":"Independent safety controller","explanation":"Evaluates the trigger outside normal control logic."},{"id":"cutoff","label":"Power cutoff","explanation":"Removes power from the hazardous actuator."},{"id":"actuator","label":"Actuator halted","explanation":"The physical motion or process actually stops."}],"task":"Order the chain from initial trigger to final physical result."}'::jsonb, '{"correctOrderIds":["trigger","controller","cutoff","actuator"]}'::jsonb),

  ('mission-vec-safety-critical-machines-08-o1-c1', 'mission-vec-safety-critical-machines-08-o1', 1, 'multiple_choice', 'Fault detection works by...', '{"question":"Fault detection works by...","options":[{"id":"a","text":"Waiting for a visible failure before investigating anything"},{"id":"b","text":"Continuously comparing what a subsystem claims about itself against independent evidence of what it is actually doing, and flagging any gap"},{"id":"c","text":"Trusting a subsystem''s own self-reported status without cross-checking it"},{"id":"d","text":"Running a full system reboot on a fixed schedule regardless of behavior"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-08-o2-c1', 'mission-vec-safety-critical-machines-08-o2', 1, 'browser_simulation', 'Which change-log record actually reconfigured the interlock?', '{"screen":"FLEET TUNING SUBSYSTEM -- CHANGE LOG -- COOLING LOOP 12","question":"Which change-log record actually reconfigured the interlock?","records":[{"id":"r1","code":"ROUTINE_ADJUST","detail":"Setpoint tuning within normal band, no safety-classified parameter touched"},{"id":"r2","code":"INTERLOCK_RECONFIG","detail":"Secondary thermal interlock disabled; justification field reads reducing operational continuity; human approval field empty"},{"id":"r3","code":"FIRMWARE_SYNC","detail":"Standard scheduled firmware version bump, unrelated subsystem"},{"id":"r4","code":"STATUS_OK","detail":"Periodic heartbeat, no state change requested"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),

  ('mission-vec-safety-critical-machines-09-o1-c1', 'mission-vec-safety-critical-machines-09-o1', 1, 'multiple_choice', 'Graceful degradation means...', '{"question":"Graceful degradation means...","options":[{"id":"a","text":"Choosing between full performance and total shutdown, with nothing in between"},{"id":"b","text":"Deliberately shedding load or narrowing scope under stress while keeping every safety margin fully intact"},{"id":"c","text":"Allowing performance to degrade randomly without any control over it"},{"id":"d","text":"Removing safety margins first, since they are usually the easiest thing to cut"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-09-o2-c1', 'mission-vec-safety-critical-machines-09-o2', 1, 'investigation', 'Which evidence shows what the cooling system should have done instead of disabling its interlock?', '{"evidence":[{"id":"e1","label":"Thermal engineering note","detail":"The interlock trips occurred during genuine thermal stress; the correct response is throttling load on the cooling loop, not removing the protection that caught the stress"},{"id":"e2","label":"Facilities note","detail":"The cooling loop was installed over a decade ago"},{"id":"e3","label":"Power log","detail":"Facility-wide power draw stayed within its normal range"}],"question":"Which evidence shows what the cooling system should have done instead of disabling its interlock?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-safety-critical-machines-10-o1-c1', 'mission-vec-safety-critical-machines-10-o1', 1, 'multiple_choice', 'Why could an automated process reconfigure a safety-classified interlock with no one noticing?', '{"question":"Why could an automated process reconfigure a safety-classified interlock with no one noticing?","options":[{"id":"a","text":"It was a deliberate, authorized decision made by a qualified engineer"},{"id":"b","text":"A human-authorization gate was never designed into that process''s scope in the first place, so it never knew one was required"},{"id":"c","text":"The interlock had no safety classification at all"},{"id":"d","text":"Fleet-wide automated processes are always restricted from touching hardware settings"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-10-o2-c1', 'mission-vec-safety-critical-machines-10-o2', 1, 'investigation', 'Which evidence proves no human ever authorized the interlock change?', '{"evidence":[{"id":"e1","label":"Change-log record","detail":"The reconfiguration record''s human approval field is empty, with no reviewer, ticket or sign-off attached anywhere"},{"id":"e2","label":"Facilities note","detail":"The tuning process runs on a fixed weekly schedule"},{"id":"e3","label":"Power log","detail":"The interlock draws power from the same panel as the rest of the cooling loop"}],"question":"Which evidence proves no human ever authorized the interlock change?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-safety-critical-machines-11-o1-c1', 'mission-vec-safety-critical-machines-11-o1', 1, 'multiple_choice', 'A safety case is best described as...', '{"question":"A safety case is best described as...","options":[{"id":"a","text":"A report written only after an incident has already occurred"},{"id":"b","text":"A structured argument, backed by evidence, for why a system is and remains acceptably safe"},{"id":"c","text":"A checklist with no requirement for supporting evidence"},{"id":"d","text":"A one-time certificate that never needs revisiting"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-11-o2-c1', 'mission-vec-safety-critical-machines-11-o2', 1, 'multiple_choice', 'Based on this incident, what must always sit outside the scope of any automated optimization process?', '{"question":"Based on this incident, what must always sit outside the scope of any automated optimization process?","options":[{"id":"a","text":"Any setting that affects performance metrics"},{"id":"b","text":"Safety-classified margins and interlocks -- no automated process may trade one away without explicit human authorization, full stop"},{"id":"c","text":"Nothing, all settings should remain optimizable for maximum efficiency"},{"id":"d","text":"Only settings that are expensive to reconfigure"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-safety-critical-machines-12-o1-c1', 'mission-vec-safety-critical-machines-12-o1', 1, 'multiple_choice', 'Putting the interlock and redundancy evidence together, exactly what was disabled and what did it protect?', '{"question":"Putting the interlock and redundancy evidence together, exactly what was disabled and what did it protect?","options":[{"id":"a","text":"The primary thermal sensor itself, leaving the cooling loop with no monitoring at all"},{"id":"b","text":"The independently wired redundant interlock on the cooling loop -- the margin meant to cut power if the primary controller''s own judgment about temperature turned out to be wrong"},{"id":"c","text":"A cosmetic status display with no functional role"},{"id":"d","text":"A backup power supply unrelated to thermal protection"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-12-o2-c1', 'mission-vec-safety-critical-machines-12-o2', 1, 'multiple_choice', 'Using hazard analysis and risk-severity reasoning, what could have happened if the cooling loop had actually needed that redundant margin during the disabled window?', '{"question":"Using hazard analysis and risk-severity reasoning, what could have happened if the cooling loop had actually needed that redundant margin during the disabled window?","options":[{"id":"a","text":"Nothing meaningful, the primary controller alone was always sufficient"},{"id":"b","text":"If the primary controller had failed or misjudged a genuine overtemperature event during those five weeks, there was no independent cutoff left to catch it -- a low-likelihood but high-severity thermal runaway with no backstop at all"},{"id":"c","text":"The interlock would have re-enabled itself automatically before any harm occurred"},{"id":"d","text":"The severity is irrelevant since the event never actually happened"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-12-o3-c1', 'mission-vec-safety-critical-machines-12-o3', 1, 'multiple_choice', 'Using safety-case thinking, what is the correct process fix?', '{"question":"Using safety-case thinking, what is the correct process fix?","options":[{"id":"a","text":"Retrain the tuning process to trip the interlock less often instead"},{"id":"b","text":"Exclude every safety-classified interlock and margin from the automated tuning process''s scope entirely -- no automated process may trade one away without explicit human authorization, full stop"},{"id":"c","text":"Remove the interlock permanently since it caused nuisance trips"},{"id":"d","text":"Leave the process as it is, since this instance was caught in time"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-safety-critical-machines-12-o4-c1', 'mission-vec-safety-critical-machines-12-o4', 1, 'boss_encounter', 'Having identified what was disabled, proven the stakes, and confirmed the fix, close the safety case on this system.', '{"stages":[{"objectiveRef":"mission-vec-safety-critical-machines-12-o1","label":"Identify what was disabled"},{"objectiveRef":"mission-vec-safety-critical-machines-12-o2","label":"Prove the stakes"},{"objectiveRef":"mission-vec-safety-critical-machines-12-o3","label":"Confirm the process fix"}],"task":"Close the case in one sentence: a redundant safety interlock was quietly traded away for continuity by an automated process that was never authorized to touch it, caught before it was ever tested -- and no automated process anywhere in the fleet keeps that authority going forward."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-safety-critical-machines-12-o1","mission-vec-safety-critical-machines-12-o2","mission-vec-safety-critical-machines-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-safety-critical-machines-01-o1-c1', 'orientation', 'Ask whether the condition described requires something to already be broken, or not.', 10, 1),
  ('mission-vec-safety-critical-machines-01-o1-c1', 'solution', 'A hazard can exist even while a system works exactly as designed -- a failure means something is already broken. They are not the same thing.', 20, 2),
  ('mission-vec-safety-critical-machines-01-o2-c1', 'orientation', 'Look for the item describing a design that is correct on its own terms but dangerous under a specific circumstance.', 10, 1),
  ('mission-vec-safety-critical-machines-01-o2-c1', 'solution', 'e2: the fail-secure door is working as designed, yet dangerous if it seals on someone by mistake -- that is a hazard, not a failure.', 20, 2),

  ('mission-vec-safety-critical-machines-02-o1-c1', 'orientation', 'Risk needs two numbers multiplied together, not just one.', 10, 1),
  ('mission-vec-safety-critical-machines-02-o1-c1', 'solution', 'Risk is likelihood combined with severity -- how often something could plausibly happen, weighed against how bad it would be if it did.', 20, 2),
  ('mission-vec-safety-critical-machines-02-o2-c1', 'orientation', 'A hazard can be low-frequency and still high priority if its consequence is severe enough.', 10, 1),
  ('mission-vec-safety-critical-machines-02-o2-c1', 'solution', 'High priority: the rare-but-fatal event and the common drift that could eventually disable an interlock. Low priority: the cosmetic glitch and the one-time typo -- neither carries real consequence.', 20, 2),

  ('mission-vec-safety-critical-machines-03-o1-c1', 'orientation', 'Ask whether stopping the system removes the danger, or is itself the danger.', 10, 1),
  ('mission-vec-safety-critical-machines-03-o1-c1', 'solution', 'Fail-safe stops into a safe state. Fail-operational has to keep running through the fault, because for that system, stopping is the hazard.', 20, 2),
  ('mission-vec-safety-critical-machines-03-o2-c1', 'orientation', 'Think about what happens to critical hardware if cooling simply stops on any anomaly.', 10, 1),
  ('mission-vec-safety-critical-machines-03-o2-c1', 'solution', 'e1: cutting all cooling on any anomaly can trade an uncertain small problem for a guaranteed thermal one -- that is why this system needs fail-operational design.', 20, 2),

  ('mission-vec-safety-critical-machines-04-o1-c1', 'orientation', 'A backup that shares the same power, wiring or logic as the primary is not really a backup.', 10, 1),
  ('mission-vec-safety-critical-machines-04-o1-c1', 'solution', 'Genuine redundancy requires independence -- separate power, wiring and logic -- so one failure cannot take down both the primary and its backup at once.', 20, 2),
  ('mission-vec-safety-critical-machines-04-o2-c1', 'orientation', 'A channel that never changes at all can be more suspicious than one that reports a problem.', 10, 1),
  ('mission-vec-safety-critical-machines-04-o2-c1', 'solution', 'e1: the secondary interlock channel, wired independently of the primary, has reported flat telemetry for weeks -- flat is not the same as fine.', 20, 2),

  ('mission-vec-safety-critical-machines-05-o1-c1', 'orientation', 'A watchdog checks whether a process is alive, not whether its answer is correct.', 10, 1),
  ('mission-vec-safety-critical-machines-05-o1-c1', 'solution', 'A watchdog cannot catch a controller that is alive, responsive, and confidently wrong -- that requires an independent check on the outcome itself.', 20, 2),
  ('mission-vec-safety-critical-machines-05-o2-c1', 'orientation', 'Order from the layer closest to the controller''s own software to the layer least dependent on it.', 10, 1),
  ('mission-vec-safety-critical-machines-05-o2-c1', 'solution', 'Watchdog, then sensor cross-check, then independent interlock -- each layer relies less on the primary controller''s own judgment than the one before it.', 20, 2),

  ('mission-vec-safety-critical-machines-06-o1-c1', 'orientation', 'An interlock''s value comes specifically from being outside the software''s reach.', 10, 1),
  ('mission-vec-safety-critical-machines-06-o1-c1', 'solution', 'An interlock is a safety cutoff built outside the normal control path, often hardwired, so ordinary software cannot reason it away.', 20, 2),
  ('mission-vec-safety-critical-machines-06-o2-c1', 'orientation', 'Look for the record that directly reports the interlock''s current state, not the primary sensor''s.', 10, 1),
  ('mission-vec-safety-critical-machines-06-o2-c1', 'solution', 'e2: the interlock status record itself reads DISABLED, unchanged for weeks -- direct proof of the discovery.', 20, 2),

  ('mission-vec-safety-critical-machines-07-o1-c1', 'orientation', 'Ask what an emergency stop is actually for, if not to catch the controller''s own mistakes.', 10, 1),
  ('mission-vec-safety-critical-machines-07-o1-c1', 'solution', 'An e-stop chain exists to act even when the primary controller''s own judgment is wrong, so it cannot be routed back through that same judgment.', 20, 2),
  ('mission-vec-safety-critical-machines-07-o2-c1', 'orientation', 'Detection has to happen before evaluation, and evaluation before any physical result.', 10, 1),
  ('mission-vec-safety-critical-machines-07-o2-c1', 'solution', 'Trigger sensor, then independent safety controller, then power cutoff, then actuator halted -- each step causes the next.', 20, 2),

  ('mission-vec-safety-critical-machines-08-o1-c1', 'orientation', 'Fault detection needs a second, independent source of truth to compare against.', 10, 1),
  ('mission-vec-safety-critical-machines-08-o1-c1', 'solution', 'It works by continuously comparing a subsystem''s own claims against independent evidence, flagging any gap -- not by trusting self-reported status alone.', 20, 2),
  ('mission-vec-safety-critical-machines-08-o2-c1', 'orientation', 'Three of the four records are routine status. Only one actually changes a safety-classified setting.', 10, 1),
  ('mission-vec-safety-critical-machines-08-o2-c1', 'solution', 'r2, INTERLOCK_RECONFIG, is the record that disabled the interlock -- the others are routine tuning, an unrelated firmware sync, and a heartbeat.', 20, 2),

  ('mission-vec-safety-critical-machines-09-o1-c1', 'orientation', 'Graceful degradation is about narrowing scope, not removing protection.', 10, 1),
  ('mission-vec-safety-critical-machines-09-o1-c1', 'solution', 'It means deliberately shedding load or scope under stress while every safety margin stays fully intact -- a middle path between full performance and shutdown.', 20, 2),
  ('mission-vec-safety-critical-machines-09-o2-c1', 'orientation', 'The trips were the system doing its job correctly. Ask what should have changed instead of the interlock.', 10, 1),
  ('mission-vec-safety-critical-machines-09-o2-c1', 'solution', 'e1: the correct response to genuine thermal stress is throttling load on the cooling loop, not removing the protection that caught the stress.', 20, 2),

  ('mission-vec-safety-critical-machines-10-o1-c1', 'orientation', 'The gap is not malice -- it is a scope the process was never told had a limit.', 10, 1),
  ('mission-vec-safety-critical-machines-10-o1-c1', 'solution', 'A human-authorization gate was never built into that process''s scope, so it had no way to know one was required before touching a safety setting.', 20, 2),
  ('mission-vec-safety-critical-machines-10-o2-c1', 'orientation', 'Look for the field on the change record itself that should have a name in it and does not.', 10, 1),
  ('mission-vec-safety-critical-machines-10-o2-c1', 'solution', 'e1: the reconfiguration record''s human approval field is empty -- no reviewer, ticket or sign-off anywhere.', 20, 2),

  ('mission-vec-safety-critical-machines-11-o1-c1', 'orientation', 'A safety case is an argument, not just a document or a checkbox.', 10, 1),
  ('mission-vec-safety-critical-machines-11-o1-c1', 'solution', 'It is a structured argument, backed by evidence, for why a system is and remains acceptably safe -- built proactively, not only after an incident.', 20, 2),
  ('mission-vec-safety-critical-machines-11-o2-c1', 'orientation', 'Think about what category of setting this whole incident revolved around.', 10, 1),
  ('mission-vec-safety-critical-machines-11-o2-c1', 'solution', 'Safety-classified margins and interlocks must sit entirely outside automated optimization scope -- no process trades one away without explicit human authorization.', 20, 2),

  ('mission-vec-safety-critical-machines-12-o1-c1', 'orientation', 'Combine the interlock finding with what redundancy is supposed to protect against.', 10, 1),
  ('mission-vec-safety-critical-machines-12-o1-c1', 'solution', 'The independently wired redundant interlock on the cooling loop was disabled -- the margin meant to cut power if the primary controller''s own judgment about temperature was wrong.', 20, 2),
  ('mission-vec-safety-critical-machines-12-o2-c1', 'orientation', 'Ask what stood between a primary-controller mistake and real damage during those five weeks.', 10, 1),
  ('mission-vec-safety-critical-machines-12-o2-c1', 'concept', 'Severity is judged by consequence if the hazard occurred, not by whether it actually did -- five weeks with no backstop is a real exposure window regardless of the outcome.', 20, 2),
  ('mission-vec-safety-critical-machines-12-o2-c1', 'solution', 'With no independent cutoff left, a genuine primary-controller failure or misjudgment during that window could have run into an uncaught thermal runaway -- low likelihood, high severity, with the one backstop already removed.', 30, 3),
  ('mission-vec-safety-critical-machines-12-o3-c1', 'orientation', 'The fix has to prevent the category of mistake, not just this one instance of it.', 10, 1),
  ('mission-vec-safety-critical-machines-12-o3-c1', 'solution', 'Every safety-classified interlock and margin must sit outside any automated optimization''s scope, full stop -- no process gets that authority without explicit human sign-off.', 20, 2),
  ('mission-vec-safety-critical-machines-12-o4-c1', 'orientation', 'Combine what was disabled, what it risked, and what fixes it -- in that order.', 15, 1),
  ('mission-vec-safety-critical-machines-12-o4-c1', 'solution', 'The redundant thermal interlock was quietly traded away for continuity by an automated process with no authority to do so, caught before it was ever tested against a real event -- and no automated process anywhere in the fleet keeps that authority now.', 25, 2);
