-- Backend Engineering ("The Fracture") -- post-game Arc IX Mastery world:
-- "GraphQL Mastery" content. World row already exists (spine migration
-- 20260810420000). 1 campaign, 2 operations, 12 missions (11 lessons +
-- boss), following the same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every prior
-- Act. Post-game tone: Mira and Forge as collegial mentors, no ongoing
-- mystery thread -- The Fracture was resolved in Act 32.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be-graphql-mastery', 'world-be-graphql-mastery', 'graphql-mastery', 'Mastery B - GraphQL at Scale', 'The core campaign taught GraphQL once, under pressure, at first contact. This pass goes back for real depth: resolver composition, batching, federation, realtime, and the defenses that keep a graph API honest once a client can shape its own query.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be-graphql-mastery-1', 'campaign-be-graphql-mastery', 'resolvers-and-composition', 'Resolvers and Composition', 'How a resolver tree actually executes, the N+1 problem it creates by default, and the two ways teams split one graph across more than one service.', 1),
  ('operation-be-graphql-mastery-2', 'campaign-be-graphql-mastery', 'defense-in-depth', 'Defense in Depth', 'Every layer that keeps a client-shaped query from becoming a client-shaped attack -- persisted queries, whitelisting, depth limits, cost analysis, field-level authorization, and the gateway that enforces all of it in one place.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be-graphql-mastery-01', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'nested-resolvers', 'Nested Resolvers', 'A query for one author pulls their books, and each book pulls its own publisher. Three fields deep, and the resolver tree runs more times than the query itself has fields.', 'advanced', ARRAY['mira','forge'], null, null, '{"type":"simulation","simulationId":"nested-resolvers-sim"}'::jsonb, '{"xp":404,"credits":78}'::jsonb, false, 1),
  ('mission-be-graphql-mastery-02', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'dataloader-batching', 'DataLoader Batching', 'Twenty books, twenty separate calls to fetch twenty authors -- the classic N+1, wearing a GraphQL costume instead of an ORM one.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"dataloader-batching-sim"}'::jsonb, '{"xp":406,"credits":78}'::jsonb, false, 2),
  ('mission-be-graphql-mastery-03', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'federation-concepts', 'Federation Concepts', 'One graph, several services, each one only willing to own the part of the schema it actually understands.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"federation-concepts-sim"}'::jsonb, '{"xp":408,"credits":79}'::jsonb, false, 3),
  ('mission-be-graphql-mastery-04', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'schema-stitching-concepts', 'Schema Stitching Concepts', 'Two independent schemas, merged into one gateway response -- without either service ever being told the other exists.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"schema-stitching-concepts-sim"}'::jsonb, '{"xp":410,"credits":79}'::jsonb, false, 4),
  ('mission-be-graphql-mastery-05', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'subscriptions', 'Subscriptions', 'A query asks once. A subscription asks Forge to keep the line open and speak up the moment something changes.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"subscriptions-sim"}'::jsonb, '{"xp":412,"credits":80}'::jsonb, false, 5),
  ('mission-be-graphql-mastery-06', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-1', 'persisted-queries-and-caching', 'Persisted Queries and Caching', 'The client stops sending the question and starts sending its hash -- and the server only has to recognize it, not read it.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"persisted-queries-and-caching-sim"}'::jsonb, '{"xp":414,"credits":80}'::jsonb, false, 6),
  ('mission-be-graphql-mastery-07', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'query-whitelisting', 'Query Whitelisting', 'Every query this API will ever execute, decided in advance. Anything not on the list never runs at all.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-whitelisting-sim"}'::jsonb, '{"xp":416,"credits":80}'::jsonb, false, 7),
  ('mission-be-graphql-mastery-08', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'depth-limits', 'Depth Limits', '"Just cap the nesting" sounds simple until a legitimate five-level comment thread and a five-level attack look exactly the same to the limiter.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"depth-limits-sim"}'::jsonb, '{"xp":418,"credits":81}'::jsonb, false, 8),
  ('mission-be-graphql-mastery-09', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'cost-analysis', 'Cost Analysis', 'Depth stayed within limits. The query still nearly took the gateway down -- because depth was never what made it expensive.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"cost-analysis-sim"}'::jsonb, '{"xp":420,"credits":81}'::jsonb, false, 9),
  ('mission-be-graphql-mastery-10', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'field-level-authorization', 'Field-Level Authorization', 'A field three levels deep, reachable through an otherwise harmless query, quietly returning data its own top-level check never saw.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"field-level-authorization-sim"}'::jsonb, '{"xp":422,"credits":82}'::jsonb, false, 10),
  ('mission-be-graphql-mastery-11', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'graphql-gateway-concepts', 'GraphQL Gateway Concepts', 'Routing, auth, rate limiting, query planning -- one front door doing four jobs so six services underneath don''t each have to.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"graphql-gateway-concepts-sim"}'::jsonb, '{"xp":424,"credits":82}'::jsonb, false, 11),
  ('mission-be-graphql-mastery-12', 'world-be-graphql-mastery', 'campaign-be-graphql-mastery', 'operation-be-graphql-mastery-2', 'the-query-of-infinite-depth', 'THE QUERY OF INFINITE DEPTH', 'Technically valid. Technically answerable. Expensive enough to be indistinguishable from an attack. Everything this world taught, applied at once.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-graphql-mastery-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-of-infinite-depth-boss-sim"}'::jsonb, '{"xp":800,"credits":195,"badgeIds":["query-of-infinite-depth"],"skillXp":{"graphql_mastery":35}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be-graphql-mastery-01', 1, 'mira', 'The Fracture''s closed, the campaign''s done, and you''re still here -- good. GraphQL is the last skill wing worth building out properly, and it starts with a question most people never ask: what actually runs when a nested field resolves?'),
  ('mission-be-graphql-mastery-01', 2, 'forge', 'Take a query for one author, their books, and each book''s publisher. Looks like one request. Under the hood it''s a resolver tree -- a function call per field, per object instance, all the way down.'),
  ('mission-be-graphql-mastery-01', 3, 'mira', 'Get that composition model wrong in your head and everything after it -- batching, federation, depth limits -- will feel like separate tricks instead of one consistent story.'),
  ('mission-be-graphql-mastery-01', 4, 'forge', 'Good place to start: a gateway that just spent four hundred milliseconds answering a query that looks, on paper, almost trivial.'),

  ('mission-be-graphql-mastery-02', 1, 'forge', 'Same author, fetched twenty separate times, because twenty different books each called their own resolver and none of them knew about the other nineteen.'),
  ('mission-be-graphql-mastery-02', 2, 'mira', 'That''s the N+1 problem wearing a GraphQL costume. The fix has a name: DataLoader. It doesn''t change what you write in a resolver -- it changes when the fetch actually happens.'),
  ('mission-be-graphql-mastery-02', 3, 'forge', 'Batch the keys, dedupe them, fire one call instead of twenty. Per request, not globally -- a cache that lives past one request is a very different, much scarier bug.'),

  ('mission-be-graphql-mastery-03', 1, 'mira', 'One graph stopped being one service a while back. Federation is how several teams each own a slice of the schema without stepping on each other''s fields.'),
  ('mission-be-graphql-mastery-03', 2, 'forge', 'Each subgraph declares what it owns and which types it can extend. A gateway sits in front, composes the pieces into one schema, and plans queries across all of them.'),
  ('mission-be-graphql-mastery-03', 3, 'mira', 'The team that owns Users never has to know Orders exists. That''s the entire value proposition.'),

  ('mission-be-graphql-mastery-04', 1, 'forge', 'Before federation was a formal spec, teams solved the same problem by hand: schema stitching. Take two independently executable schemas, merge their type definitions, delegate each field to whichever schema actually answers it.'),
  ('mission-be-graphql-mastery-04', 2, 'mira', 'The difference that matters: federation has each subgraph explicitly declare ownership and entity keys. Stitching does the merging and delegation at the gateway, with the underlying schemas often none the wiser.'),
  ('mission-be-graphql-mastery-04', 3, 'forge', 'Less structure, more flexibility, and a gateway carrying more of the coordination weight than it does under federation.'),

  ('mission-be-graphql-mastery-05', 1, 'mira', 'Query and mutation are both one-shot: ask, get an answer, connection closes. A subscription is Forge agreeing to keep the line open and tell you the moment something changes.'),
  ('mission-be-graphql-mastery-05', 2, 'forge', 'That''s a fundamentally different cost. A query is one unit of work. A subscription is a standing commitment -- a held connection, a live filter, for as long as the client stays subscribed.'),
  ('mission-be-graphql-mastery-05', 3, 'mira', 'Multiply that by ten thousand clients and "just add a subscription" turns into "just add ten thousand open connections and a fan-out problem." Usually backed by a pub/sub layer for exactly that reason.'),

  ('mission-be-graphql-mastery-06', 1, 'forge', 'A client sends the same query a thousand times a day. Persisted queries let it register that query once, get back a hash, and send the hash from then on -- smaller payload, and the server already knows exactly what it''s agreeing to run.'),
  ('mission-be-graphql-mastery-06', 2, 'mira', 'That second part matters more than the bandwidth savings. Once a query has to be pre-registered, an attacker can''t just invent a new one and send it.'),
  ('mission-be-graphql-mastery-06', 3, 'forge', 'Caching gets easier too -- a hash plus variables is a clean, stable cache key. A raw query string with whitespace differences never was.'),

  ('mission-be-graphql-mastery-07', 1, 'mira', 'Persisted queries buy you the shape. Whitelisting is the enforcement: in production, only the pre-approved set of query hashes is allowed to execute at all. Everything else is rejected before it touches a resolver.'),
  ('mission-be-graphql-mastery-07', 2, 'forge', 'It''s the most complete defense on this list, and also the least flexible one. A new feature that needs a new query shape means a deploy to register it first.'),

  ('mission-be-graphql-mastery-08', 1, 'forge', 'Simplest-sounding fix for a runaway nested query: cap how deep it''s allowed to go. Set maxDepth to, say, six, and reject anything deeper.'),
  ('mission-be-graphql-mastery-08', 2, 'mira', 'Except a legitimate org chart, or a comment thread with real replies-to-replies, can genuinely need seven or eight levels. Set the limit low enough to stop an attack and you start rejecting your own product''s real queries.'),
  ('mission-be-graphql-mastery-08', 3, 'forge', 'Depth limits are necessary. They were never going to be sufficient on their own -- that''s the whole reason cost analysis exists.'),

  ('mission-be-graphql-mastery-09', 1, 'mira', 'Here''s the query that got through the depth limit clean -- five levels, well under the cap -- and still nearly took the gateway down.'),
  ('mission-be-graphql-mastery-09', 2, 'forge', 'Depth was never what made it expensive. Every level requested first: 500, so five nested connections each pulling five hundred items multiplies out past anything a depth number alone could see coming.'),
  ('mission-be-graphql-mastery-09', 3, 'mira', 'Cost analysis assigns a weight to every field -- base cost, multiplied by list arguments -- sums it before execution, and rejects anything over budget. It sees breadth. Depth limits never could.'),

  ('mission-be-graphql-mastery-10', 1, 'forge', 'A top-level authorization check on the query is necessary and also not enough. A field like payrollId might be reachable three fields deep, off a path nobody thought to guard.'),
  ('mission-be-graphql-mastery-10', 2, 'mira', 'Field-level authorization puts the check inside the resolver for that specific field -- it runs no matter which path the client used to reach it, top-level query included.'),
  ('mission-be-graphql-mastery-10', 3, 'forge', 'It''s more checks to write, and it''s the only version that''s actually correct once a graph gets big enough that no one person can see every path through it.'),

  ('mission-be-graphql-mastery-11', 1, 'mira', 'Six subgraphs, one client. Nobody wants that client managing six connections, six auth checks, six rate limits.'),
  ('mission-be-graphql-mastery-11', 2, 'forge', 'That''s the gateway''s job: one front door. Route each part of the query to the subgraph that owns it, enforce auth and rate limits centrally, plan the query so pieces run in the right order, and stitch the responses back into one payload.'),
  ('mission-be-graphql-mastery-11', 3, 'mira', 'Every defense we''ve covered -- whitelisting, depth limits, cost analysis -- lives at the gateway too. One place to enforce it instead of six copies that can drift out of sync.'),

  ('mission-be-graphql-mastery-12', 1, 'forge', 'Incident, low priority, real: a single query, five levels of nested relations, hit the gateway and pinned it near saturation for almost a minute.'),
  ('mission-be-graphql-mastery-12', 2, 'mira', 'Technically valid. Every field in it is real, every relation exists. Technically answerable -- nothing about it is malformed. And expensive enough that it''s indistinguishable from an actual attack.'),
  ('mission-be-graphql-mastery-12', 3, 'forge', 'That''s the whole point of this one. No single defense we''ve covered catches this alone. Depth limits let it through -- it''s within the cap. Whitelisting alone would also block every future legitimate deep query nobody''s registered yet.'),
  ('mission-be-graphql-mastery-12', 4, 'mira', 'So: apply what you''ve built. Depth limits, cost analysis, and whitelisting, together, layered -- reject what''s actually dangerous, and let the legitimate deep queries keep working.'),
  ('mission-be-graphql-mastery-12', 5, 'forge', 'This is graduation, not incident response. Show me you know which layer catches what, and why none of them alone was ever going to be enough.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be-graphql-mastery-01-o1', 'mission-be-graphql-mastery-01', 1, 'Diagnose the resolver fan-out', 'Find the evidence that explains why a query with three nested fields triggered far more resolver calls than three.'),
  ('mission-be-graphql-mastery-02-o1', 'mission-be-graphql-mastery-02', 1, 'Order the batch cycle', 'Order the sequence DataLoader actually follows between a resolver calling load() and the batched result coming back.'),
  ('mission-be-graphql-mastery-03-o1', 'mission-be-graphql-mastery-03', 1, 'Explain what federation changes', 'Choose what actually changes about serving a cross-service query once federation splits the schema.'),
  ('mission-be-graphql-mastery-04-o1', 'mission-be-graphql-mastery-04', 1, 'Distinguish stitching from federation', 'Choose what actually distinguishes schema stitching from federation as a way to combine schemas.'),
  ('mission-be-graphql-mastery-05-o1', 'mission-be-graphql-mastery-05', 1, 'Explain the operational cost of a subscription', 'Choose why a subscription costs meaningfully more, operationally, than a query or mutation.'),
  ('mission-be-graphql-mastery-06-o1', 'mission-be-graphql-mastery-06', 1, 'Explain what persisted queries buy you', 'Choose what a persisted query hash actually buys the API beyond a smaller payload.'),
  ('mission-be-graphql-mastery-07-o1', 'mission-be-graphql-mastery-07', 1, 'Explain what whitelisting rejects', 'Choose what happens to a well-formed but never-registered query under whitelisting.'),
  ('mission-be-graphql-mastery-08-o1', 'mission-be-graphql-mastery-08', 1, 'Diagnose the depth-limit tension', 'Choose why a single flat depth limit can''t cleanly separate the attack it was meant to stop from a legitimate deep query.'),
  ('mission-be-graphql-mastery-09-o1', 'mission-be-graphql-mastery-09', 1, 'Diagnose the cost that depth missed', 'Find the evidence that explains why a query that passed the depth limit still nearly overwhelmed the gateway.'),
  ('mission-be-graphql-mastery-10-o1', 'mission-be-graphql-mastery-10', 1, 'Find the authorization gap', 'Choose what''s actually missing when only the top-level query has an authorization check.'),
  ('mission-be-graphql-mastery-11-o1', 'mission-be-graphql-mastery-11', 1, 'Explain what the gateway actually does', 'Choose what a gateway does for a federated or stitched graph beyond simply forwarding requests.'),
  ('mission-be-graphql-mastery-12-o1', 'mission-be-graphql-mastery-12', 1, 'Judge Query Zulu', 'Decide whether this deeply-nested, unregistered, high-breadth query should be rejected.'),
  ('mission-be-graphql-mastery-12-o2', 'mission-be-graphql-mastery-12', 2, 'Judge Query Yankee', 'Decide whether this deep but registered, in-budget query should be allowed.'),
  ('mission-be-graphql-mastery-12-o3', 'mission-be-graphql-mastery-12', 3, 'Choose the layered defense', 'Choose the combination of defenses that actually separates a query like Zulu from a query like Yankee.'),
  ('mission-be-graphql-mastery-12-o4', 'mission-be-graphql-mastery-12', 4, 'Close the mastery check', 'Synthesize the two judgments and the chosen defense into the full resolution.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be-graphql-mastery-01-o1-c1', 'mission-be-graphql-mastery-01-o1', 1, 'investigation', 'Which evidence explains why this three-field query produced far more than three resolver calls?', '{"evidence":[{"id":"ev1","label":"Query shape","detail":"The client query requests one author, that author''s 20 books, and each book''s publisher -- 3 nested fields, no more."},{"id":"ev2","label":"Resolver trace","detail":"The Book.publisher resolver fired 20 times during this request -- once per book object returned by Author.books, each running its own independent lookup."},{"id":"ev3","label":"Gateway timing","detail":"Total resolution time scaled linearly with the number of books returned, not with the number of fields in the query."}],"question":"Which evidence explains why this three-field query produced far more than three resolver calls?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be-graphql-mastery-02-o1-c1', 'mission-be-graphql-mastery-02-o1', 1, 'interactive_diagram', 'Order the sequence DataLoader follows between a resolver calling load() and the batched result coming back.', '{"diagramId":"dataloader-batch-cycle","hotspots":[{"id":"resolvers_call_load","label":"Twenty Book.author resolvers each call authorLoader.load(id)","explanation":"Each call returns a pending promise immediately -- nothing is fetched yet."},{"id":"keys_queued","label":"DataLoader queues every key requested during the current tick","explanation":"Duplicate ids collapse to one queued key automatically."},{"id":"tick_ends","label":"The current event-loop tick ends","explanation":"DataLoader waits for this moment specifically so it can catch every load() call issued during the same resolver pass."},{"id":"batch_fn_runs","label":"The batch load function runs once, with the full array of queued keys","explanation":"One database call for every author needed by this request, not twenty."},{"id":"results_mapped","label":"Results are mapped back to each pending promise, in the same order as the keys","explanation":"Every original load() call resolves with its own author, as if it had been fetched individually."}],"task":"Order the sequence DataLoader follows between a resolver calling load() and the batched result coming back."}'::jsonb, '{"correctOrderIds":["resolvers_call_load","keys_queued","tick_ends","batch_fn_runs","results_mapped"]}'::jsonb),

  ('mission-be-graphql-mastery-03-o1-c1', 'mission-be-graphql-mastery-03-o1', 1, 'multiple_choice', 'A monolithic GraphQL schema is split into a Users service and an Orders service under federation. What actually changes about how a client query spanning both is served?', '{"question":"A monolithic GraphQL schema is split into a Users service and an Orders service under federation. What actually changes about how a client query spanning both is served?","options":[{"id":"a","text":"Nothing -- clients must now query each service separately and merge results themselves"},{"id":"b","text":"The gateway plans the query, delegates each part to the subgraph that owns those fields, and stitches the responses into one payload the client never has to know is composed of two services"},{"id":"c","text":"Federation removes the need for a gateway entirely, since each subgraph responds directly to the client"},{"id":"d","text":"The Orders service must duplicate the entire Users schema so it can resolve user fields on its own"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-04-o1-c1', 'mission-be-graphql-mastery-04-o1', 1, 'multiple_choice', 'What actually distinguishes schema stitching from federation as a way to combine multiple GraphQL schemas into one?', '{"question":"What actually distinguishes schema stitching from federation as a way to combine multiple GraphQL schemas into one?","options":[{"id":"a","text":"Stitching merges type definitions and delegates fields at the gateway layer, without requiring subgraphs to declare formal ownership or entity keys the way federation does"},{"id":"b","text":"Stitching only works with REST APIs, never with other GraphQL schemas"},{"id":"c","text":"Federation and stitching are two names for the exact same mechanism"},{"id":"d","text":"Stitching requires every underlying schema to be rewritten in a special stitching-only syntax"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-be-graphql-mastery-05-o1-c1', 'mission-be-graphql-mastery-05-o1', 1, 'multiple_choice', 'Why does adding a GraphQL subscription cost meaningfully more, operationally, than adding another query or mutation?', '{"question":"Why does adding a GraphQL subscription cost meaningfully more, operationally, than adding another query or mutation?","options":[{"id":"a","text":"Subscriptions use a completely different data format that''s slower to parse"},{"id":"b","text":"A subscription requires a held, long-lived connection per client plus a way to fan out change events to every subscriber, instead of one request-response cycle that ends immediately"},{"id":"c","text":"Subscriptions can only return a single field, so they''re actually cheaper"},{"id":"d","text":"There''s no real operational difference -- subscriptions are just queries with a different keyword"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-06-o1-c1', 'mission-be-graphql-mastery-06-o1', 1, 'multiple_choice', 'A client switches from sending full query text to sending a pre-registered query hash. What does this actually buy the API, beyond a smaller request payload?', '{"question":"A client switches from sending full query text to sending a pre-registered query hash. What does this actually buy the API, beyond a smaller request payload?","options":[{"id":"a","text":"Nothing else changes -- it''s purely a bandwidth optimization"},{"id":"b","text":"The server now knows in advance the exact, finite set of query shapes it might be asked to run, and gets a clean, stable cache key (hash plus variables) instead of a raw query string that varies with whitespace"},{"id":"c","text":"It removes the need for authentication on every request"},{"id":"d","text":"It converts every query into a mutation automatically"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-07-o1-c1', 'mission-be-graphql-mastery-07-o1', 1, 'multiple_choice', 'A production GraphQL API enforces query whitelisting. A client sends a syntactically valid, perfectly well-formed query that was never pre-registered. What happens?', '{"question":"A production GraphQL API enforces query whitelisting. A client sends a syntactically valid, perfectly well-formed query that was never pre-registered. What happens?","options":[{"id":"a","text":"It executes normally -- whitelisting only applies to mutations"},{"id":"b","text":"It''s rejected before it reaches any resolver, regardless of how well-formed or harmless it is, because its hash isn''t in the approved set"},{"id":"c","text":"It executes, but with a warning logged"},{"id":"d","text":"It''s automatically added to the whitelist the first time it''s seen"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-08-o1-c1', 'mission-be-graphql-mastery-08-o1', 1, 'multiple_choice', 'A team sets a GraphQL server''s max query depth to 4 to stop deeply nested attacks. Support tickets soon report that a legitimate feature -- viewing a comment thread with real replies-to-replies -- now fails. What''s the actual tension here?', '{"question":"A team sets a GraphQL server''s max query depth to 4 to stop deeply nested attacks. Support tickets soon report that a legitimate feature -- viewing a comment thread with real replies-to-replies -- now fails. What''s the actual tension here?","options":[{"id":"a","text":"Depth limits are useless and should never be used"},{"id":"b","text":"A single flat depth limit can''t tell a malicious deeply-nested query apart from a legitimate deeply-nested one -- setting it low enough to stop the former can be low enough to break the latter"},{"id":"c","text":"The bug is unrelated to the depth limit -- comment threads never involve nested fields"},{"id":"d","text":"Depth limits only apply to mutations, not queries, so this shouldn''t have happened"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-09-o1-c1', 'mission-be-graphql-mastery-09-o1', 1, 'investigation', 'Which evidence explains why a query that passed the depth limit still nearly overwhelmed the gateway?', '{"evidence":[{"id":"ev1","label":"Depth check","detail":"The query passed the server''s max-depth-of-8 limit -- it only nests 5 levels deep."},{"id":"ev2","label":"Query arguments","detail":"Each of the 5 nested connections in the query passes first: 500, requesting up to 500 items at every level."},{"id":"ev3","label":"Gateway load","detail":"CPU and memory on the gateway spiked to near-saturation for the duration of this single request, before returning to normal once it completed."}],"question":"Which evidence explains why a query that passed the depth limit still nearly overwhelmed the gateway?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be-graphql-mastery-10-o1-c1', 'mission-be-graphql-mastery-10-o1', 1, 'multiple_choice', 'A query for a public user profile also nests employee.payrollId three fields deep. The top-level query resolver checks that the requester is allowed to view profiles, and nothing else does. What''s the actual gap?', '{"question":"A query for a public user profile also nests employee.payrollId three fields deep. The top-level query resolver checks that the requester is allowed to view profiles, and nothing else does. What''s the actual gap?","options":[{"id":"a","text":"There is no gap -- the top-level check already covers every field beneath it automatically"},{"id":"b","text":"payrollId is reachable through a path the top-level check never inspects; without a check on that specific field or resolver, anyone who can view a profile at all can also read it"},{"id":"c","text":"GraphQL automatically blocks sensitive-sounding field names"},{"id":"d","text":"The gap can only be fixed by removing nested fields from the schema entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-11-o1-c1', 'mission-be-graphql-mastery-11-o1', 1, 'multiple_choice', 'Beyond simply forwarding requests, what does a gateway sitting in front of a federated or stitched graph actually do?', '{"question":"Beyond simply forwarding requests, what does a gateway sitting in front of a federated or stitched graph actually do?","options":[{"id":"a","text":"Nothing beyond forwarding -- subgraphs handle all routing, auth, and rate limiting themselves"},{"id":"b","text":"It plans and routes each part of a client query to the subgraph that owns it, enforces authentication, rate limiting, and query policies (whitelisting, depth, cost) centrally, and stitches the sub-responses back into one payload"},{"id":"c","text":"It only handles TLS termination and nothing else"},{"id":"d","text":"It replaces the need for any subgraph to have its own resolvers"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-graphql-mastery-12-o1-c1', 'mission-be-graphql-mastery-12-o1', 1, 'multiple_choice', 'Query Zulu: depth 7 (under the depth-8 cap), requests first: 1000 at four different nested list levels, and its hash does not appear in the whitelist. Should the gateway execute it?', '{"question":"Query Zulu: depth 7 (under the depth-8 cap), requests first: 1000 at four different nested list levels, and its hash does not appear in the whitelist. Should the gateway execute it?","options":[{"id":"a","text":"Yes -- it''s under the depth cap, so it''s safe"},{"id":"b","text":"No -- it fails whitelisting outright, and even judged on cost alone its combined first: 1000 arguments at four nested levels would blow through any reasonable cost budget"},{"id":"c","text":"Yes, because whitelisting only applies to mutations"},{"id":"d","text":"Unknowable without seeing the full response body"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be-graphql-mastery-12-o2-c1', 'mission-be-graphql-mastery-12-o2', 1, 'multiple_choice', 'Query Yankee: depth 6, first: 20 at each nested level, and its hash is present in the whitelist. Its computed cost is well under budget. Should the gateway execute it?', '{"question":"Query Yankee: depth 6, first: 20 at each nested level, and its hash is present in the whitelist. Its computed cost is well under budget. Should the gateway execute it?","options":[{"id":"a","text":"No -- anything nested past depth 4 should always be rejected on principle"},{"id":"b","text":"Yes -- it''s a registered, whitelisted query shape, its depth is within policy, and its computed cost clears the budget with room to spare; there''s nothing here to reject"},{"id":"c","text":"No -- only queries with no nested fields at all should ever be allowed"},{"id":"d","text":"Unknowable without re-running the depth check twice"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be-graphql-mastery-12-o3-c1', 'mission-be-graphql-mastery-12-o3', 1, 'multiple_choice', 'Which combination of defenses correctly distinguishes a query like Zulu from a query like Yankee, rather than blocking both or neither?', '{"question":"Which combination of defenses correctly distinguishes a query like Zulu from a query like Yankee, rather than blocking both or neither?","options":[{"id":"a","text":"Depth limits alone -- both queries are within the depth cap, so depth limits alone reject neither"},{"id":"b","text":"Whitelisting alone -- it correctly blocks Zulu, but a brand-new legitimate query shape that hasn''t been registered yet would also get blocked, even if its cost and depth are both fine"},{"id":"c","text":"Depth limits, cost analysis, and whitelisting together -- whitelisting rejects unregistered shapes like Zulu outright, cost analysis catches expensive shapes that slip past a depth check, and depth limits still bound worst-case nesting -- each layer covers what the others miss"},{"id":"d","text":"Nothing -- a five-level query should never be allowed regardless of cost or registration"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-be-graphql-mastery-12-o4-c1', 'mission-be-graphql-mastery-12-o4', 1, 'boss_encounter', 'Having judged Zulu, judged Yankee, and chosen the layered defense, state the full resolution.', '{"stages":[{"objectiveRef":"mission-be-graphql-mastery-12-o1","label":"Judge Query Zulu"},{"objectiveRef":"mission-be-graphql-mastery-12-o2","label":"Judge Query Yankee"},{"objectiveRef":"mission-be-graphql-mastery-12-o3","label":"Choose the layered defense"}],"task":"Having judged Zulu, judged Yankee, and chosen the layered defense, state the resolution: THE QUERY OF INFINITE DEPTH is stopped not by any single mechanism but by depth limits, cost analysis, and query whitelisting applied together -- each covering a gap the others leave open -- while legitimate deep queries like Yankee keep working because they clear every layer cleanly."}'::jsonb, '{"requiredObjectiveIds":["mission-be-graphql-mastery-12-o1","mission-be-graphql-mastery-12-o2","mission-be-graphql-mastery-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be-graphql-mastery-01-o1-c1', 'orientation', 'Two of these describe the query itself or its overall timing. One actually names the mechanism causing the fan-out.', 15, 1),
  ('mission-be-graphql-mastery-01-o1-c1', 'solution', 'ev2: Book.publisher resolves once per book object handed to it by Author.books -- the resolver tree fans out per parent-returned item, not per field written in the query.', 30, 2),

  ('mission-be-graphql-mastery-02-o1-c1', 'orientation', 'DataLoader doesn''t fetch the instant load() is called -- it waits for something first.', 15, 1),
  ('mission-be-graphql-mastery-02-o1-c1', 'solution', 'Resolvers call load() and get pending promises, DataLoader queues the keys, the tick ends, one batch function runs with all queued keys, and results map back to each original promise in order.', 30, 2),

  ('mission-be-graphql-mastery-03-o1-c1', 'orientation', 'The client still sends one query to one endpoint -- ask what''s doing the extra work behind that single request.', 15, 1),
  ('mission-be-graphql-mastery-03-o1-c1', 'solution', 'b: the gateway performs query planning, delegating each sub-selection to the subgraph that owns it, then composes one response -- the split is invisible to the client.', 30, 2),

  ('mission-be-graphql-mastery-04-o1-c1', 'orientation', 'Federation has each subgraph declare what it owns, upfront, in its own schema. Ask which approach that isn''t.', 15, 1),
  ('mission-be-graphql-mastery-04-o1-c1', 'solution', 'a: stitching does the merging and field delegation centrally at the gateway, with underlying schemas typically unaware of each other -- federation instead has each subgraph formally declare its own entities and keys.', 30, 2),

  ('mission-be-graphql-mastery-05-o1-c1', 'orientation', 'A query''s connection closes the moment it answers. Ask what a subscription''s connection does instead.', 15, 1),
  ('mission-be-graphql-mastery-05-o1-c1', 'solution', 'b: a subscription holds a connection open per client and needs a fan-out mechanism (often a pub/sub layer) to push events to every one of them -- a standing cost a query never incurs.', 30, 2),

  ('mission-be-graphql-mastery-06-o1-c1', 'orientation', 'Think about what the server can assume once it only ever receives a hash it already recognizes.', 15, 1),
  ('mission-be-graphql-mastery-06-o1-c1', 'solution', 'b: pre-registration shrinks the set of possible query shapes to a known list and gives caching a stable key -- both the security and performance benefits ride on the same mechanism.', 30, 2),

  ('mission-be-graphql-mastery-07-o1-c1', 'orientation', 'Whitelisting checks the query''s identity against a list before anything about its content or intent is considered.', 15, 1),
  ('mission-be-graphql-mastery-07-o1-c1', 'solution', 'b: whitelisting rejects anything not on the pre-approved list outright -- validity and intent are irrelevant if the hash was never registered.', 30, 2),

  ('mission-be-graphql-mastery-08-o1-c1', 'orientation', 'The comment thread and the attack can, from the limiter''s point of view, look like the exact same shape.', 15, 1),
  ('mission-be-graphql-mastery-08-o1-c1', 'solution', 'b: a flat depth cap can''t distinguish structurally-identical deep queries by intent -- it either lets both through or blocks both, which is exactly why depth limits alone were never going to be enough.', 30, 2),

  ('mission-be-graphql-mastery-09-o1-c1', 'orientation', 'The depth check already passed -- that rules out depth as the explanation. Look at what else the query is asking for at each level.', 15, 1),
  ('mission-be-graphql-mastery-09-o1-c1', 'solution', 'ev2: first: 500 at every one of 5 nested levels multiplies out to an enormous item count -- breadth, not depth, is what made this query expensive, and only cost analysis is positioned to catch that.', 30, 2),

  ('mission-be-graphql-mastery-10-o1-c1', 'orientation', 'A check written at the top of the query doesn''t automatically run again for every field returned underneath it.', 15, 1),
  ('mission-be-graphql-mastery-10-o1-c1', 'solution', 'b: without an authorization check on the payrollId field or resolver itself, it''s exposed to anyone who clears the one check at the top -- field-level authorization exists precisely to close gaps like this.', 30, 2),

  ('mission-be-graphql-mastery-11-o1-c1', 'orientation', 'List everything this world has covered that needs one consistent place to be enforced across every subgraph.', 15, 1),
  ('mission-be-graphql-mastery-11-o1-c1', 'solution', 'b: query planning and routing, centralized auth and rate limiting, and enforcing whitelisting/depth/cost policy all live at the gateway -- one place instead of one copy per subgraph.', 30, 2),

  ('mission-be-graphql-mastery-12-o1-c1', 'orientation', 'Depth alone already looks fine here -- check the other two layers before deciding.', 15, 1),
  ('mission-be-graphql-mastery-12-o1-c1', 'solution', 'b: Zulu was never registered, so whitelisting rejects it outright regardless of depth, and its breadth (first: 1000 at four levels) would fail a cost budget on its own besides.', 30, 2),
  ('mission-be-graphql-mastery-12-o2-c1', 'orientation', 'Check all three layers, not just depth, before ruling this one out.', 15, 1),
  ('mission-be-graphql-mastery-12-o2-c1', 'solution', 'b: Yankee clears depth, cost, and whitelisting -- there is no layer here it fails, so it should execute normally.', 30, 2),
  ('mission-be-graphql-mastery-12-o3-c1', 'orientation', 'Think about what each single layer misses on its own, not just what it catches.', 15, 1),
  ('mission-be-graphql-mastery-12-o3-c1', 'solution', 'c: depth limits, cost analysis, and whitelisting together cover each other''s gaps -- no single one of the three, alone, correctly separates Zulu from Yankee.', 30, 2),
  ('mission-be-graphql-mastery-12-o4-c1', 'orientation', 'Pull together what each of the three judgments already established about which layer catches what.', 15, 1),
  ('mission-be-graphql-mastery-12-o4-c1', 'solution', 'THE QUERY OF INFINITE DEPTH is stopped by depth limits, cost analysis, and whitelisting applied together, not any single one alone -- and that same layering is exactly what lets a legitimate deep query like Yankee keep working.', 30, 2);
