-- Robotics/Embedded/IoT pathway ("Vector Division") Act 13 -- "Boot and
-- Update" content, closing Arc II ("Firmware Controls Reality," Acts
-- 6-13). World row world-vec-boot-and-update already exists (created
-- separately, under act-vec-2, index 12). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every other pathway. No new ChallengeType needed -- reuses
-- story_dialogue, investigation, multiple_choice, interactive_diagram,
-- drag_and_drop, browser_simulation (generic console fallback) and
-- boss_encounter, same as Act 1 and Act 5. Byte's ongoing facility sweep
-- turns up more matching boards than expected, and a first attempt to
-- push new firmware to several at once bricks multiple of them --
-- diagnosing a missing A/B partition scheme with no verified rollback
-- path, and closing on a real OTA pipeline (two partitions, checksummed
-- images, a bootloader that only switches after verifying). Closes on the
-- pivot into Act 14, "Connected Things" (device identity/connectivity at
-- unknown scale).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-boot-and-update', 'world-vec-boot-and-update', 'boot-and-update', '2H - Boot and Update', 'Build a real firmware update pipeline -- reset sequences, bootloaders, firmware images, checksums, signed firmware concepts, OTA updates, A/B partitions, rollback, recovery mode, version compatibility and safe migrations -- after a first attempt to update several boards at once leaves multiple of them completely unresponsive.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-boot-and-update-1', 'campaign-vec-boot-and-update', 'what-a-boot-actually-does', 'What a Boot Actually Does', 'Reset sequences, bootloaders, firmware images, checksums, signed firmware concepts and OTA updates.', 1),
  ('operation-vec-boot-and-update-2', 'campaign-vec-boot-and-update', 'updating-without-bricking', 'Updating Without Bricking', 'A/B partitions, rollback, recovery mode, version compatibility, safe migrations, and the fleet that got bricked finding all of it out the hard way.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-boot-and-update-01', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'reset-sequence', 'Reset Sequence', 'Vector Division has more than two devices to update now -- Byte''s ongoing facility sweep is turning up more of them every day. Their first attempt to push the new RTOS firmware to several at once leaves multiple boards completely unresponsive, and it starts with the one thing every one of those boards did in the first few milliseconds after power loss.', 'beginner', ARRAY['tomas','byte'], null, null, '{"type":"simulation","simulationId":"reset-sequence-sim"}'::jsonb, '{"xp":200,"credits":25}'::jsonb, false, 1),
  ('mission-vec-boot-and-update-02', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'bootloaders', 'Bootloaders', 'Before any of the RTOS firmware the player has been reading all Arc ever runs a single line, a much smaller, much older program has to decide what to load and where -- the bootloader, and it turns out it decided badly.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-boot-and-update-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"bootloaders-sim"}'::jsonb, '{"xp":200,"credits":30}'::jsonb, false, 2),
  ('mission-vec-boot-and-update-03', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'firmware-images', 'Firmware Images', 'A firmware image is not the running program -- it is the program packaged as one contiguous block of bytes, ready to be copied into flash exactly as-is, with no interpretation and no partial credit for being almost right.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-boot-and-update-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"firmware-images-sim"}'::jsonb, '{"xp":210,"credits":30}'::jsonb, false, 3),
  ('mission-vec-boot-and-update-04', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'checksums', 'Checksums', 'A flash write can fail halfway through and still leave something in memory that looks like a firmware image at a glance. A checksum is how the bootloader tells the difference between an image and the wreckage of one.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-boot-and-update-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"checksums-sim"}'::jsonb, '{"xp":210,"credits":30}'::jsonb, false, 4),
  ('mission-vec-boot-and-update-05', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'signed-firmware-concepts', 'Signed Firmware Concepts', 'A checksum proves an image was not corrupted in transit. It proves nothing about who wrote it -- which is a different guarantee entirely, and the fleet does not yet have it.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-boot-and-update-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"signed-firmware-sim"}'::jsonb, '{"xp":220,"credits":35}'::jsonb, false, 5),
  ('mission-vec-boot-and-update-06', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-1', 'ota-updates', 'OTA Updates', 'Hand-flashing one board at a time worked when Vector Division had two boards. Byte''s sweep has already found more than that, sitting in places nobody wants to physically visit twice.', 'beginner', ARRAY['byte','tomas'], '{"requiredMissionIds":["mission-vec-boot-and-update-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"ota-updates-sim"}'::jsonb, '{"xp":220,"credits":35}'::jsonb, false, 6),
  ('mission-vec-boot-and-update-07', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'ab-partitions', 'A/B Partitions', 'The bricked boards all share one design flaw: there was only ever one place in flash for firmware to live, and the update wrote directly over the only copy that worked.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-boot-and-update-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"ab-partitions-sim"}'::jsonb, '{"xp":230,"credits":35}'::jsonb, false, 7),
  ('mission-vec-boot-and-update-08', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'rollback', 'Rollback', 'Two partitions only help if something is actually watching the new one and willing to admit it failed. Nothing on the bricked boards ever asked that question.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-boot-and-update-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"rollback-sim"}'::jsonb, '{"xp":230,"credits":40}'::jsonb, false, 8),
  ('mission-vec-boot-and-update-09', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'recovery-mode', 'Recovery Mode', 'A/B partitioning and rollback assume at least one valid image always survives somewhere. For the boards that already bricked, neither partition does -- which is exactly the case recovery mode exists for.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-boot-and-update-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"recovery-mode-sim"}'::jsonb, '{"xp":240,"credits":40}'::jsonb, false, 9),
  ('mission-vec-boot-and-update-10', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'version-compatibility', 'Version Compatibility', 'A checksum can pass, a signature can verify, and a rollback can be ready, and the update can still be wrong -- because the new firmware assumes a hardware revision the board in front of it does not actually have.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-boot-and-update-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"version-compatibility-sim"}'::jsonb, '{"xp":240,"credits":40}'::jsonb, false, 10),
  ('mission-vec-boot-and-update-11', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'safe-migrations', 'Safe Migrations', 'A firmware update can also change the shape of the data a board keeps across resets. Getting the new code onto the board is only half the job -- the saved configuration has to survive the crossing too, or Act 12''s bug just happens again with new firmware attached.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-boot-and-update-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"safe-migrations-sim"}'::jsonb, '{"xp":250,"credits":45}'::jsonb, false, 11),
  ('mission-vec-boot-and-update-12', 'world-vec-boot-and-update', 'campaign-vec-boot-and-update', 'operation-vec-boot-and-update-2', 'the-bricked-fleet', 'The Bricked Fleet', 'Every concept this Act taught, turned on the boards that went dark the moment Vector Division tried to update more than one at a time -- closing the whole of Arc II with a real answer to a question bigger than firmware ever needed to ask before: not two devices anymore, an unknown number of them.', 'boss', ARRAY['tomas','byte','imani'], '{"requiredMissionIds":["mission-vec-boot-and-update-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-bricked-fleet-boss-sim"}'::jsonb, '{"xp":1050,"credits":220,"badgeIds":["the-bricked-fleet"],"skillXp":{"robotics_fundamentals":135}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-boot-and-update-01', 1, 'byte', 'The facility sweep keeps finding more of these controllers. Fourteen this week, twenty-two the week before. I do not have a final number yet, and I am starting to think there is not a small one.'),
  ('mission-vec-boot-and-update-01', 2, 'tomas', 'Fine. The RTOS firmware from the last two Acts is finally solid -- it remembers its configuration correctly now, no more flash wear corruption. Time to actually get it onto more than the two boards we have been hand-flashing on this bench.'),
  ('mission-vec-boot-and-update-01', 3, 'byte', 'I pushed it to six boards at once through the existing update path. Three came back fine. Three did not come back at all -- no boot log, no heartbeat, nothing on the diagnostic bus.'),
  ('mission-vec-boot-and-update-01', 4, 'tomas', 'Completely unresponsive is a specific kind of failure, not a vague one. Before we guess why, we start at the one thing every single board did in the first few milliseconds after we cut its power to update it: the reset sequence.'),
  ('mission-vec-boot-and-update-01', 5, 'tomas', 'Every device that has ever run correctly has gone through this exact sequence a thousand times without either of us thinking about it once. It stopped being invisible the moment three boards stopped coming back.'),

  ('mission-vec-boot-and-update-02', 1, 'tomas', 'The RTOS firmware never runs first. Something much smaller and much older has to decide what to load and where before a single line of the operating system executes. That is the bootloader, and on these boards it lives in a part of flash the update itself is not even allowed to touch.'),
  ('mission-vec-boot-and-update-02', 2, 'tomas', 'A bootloader''s entire job is deciding, so it has to be trustworthy in a way nothing it loads has to be. If the bootloader itself is wrong, there is no layer above it left to catch the mistake.'),

  ('mission-vec-boot-and-update-03', 1, 'tomas', 'A firmware image is not "the program." It is the program flattened into one contiguous block of bytes, meant to be copied into flash exactly as it is, byte for byte, with nothing in between to interpret or negotiate.'),
  ('mission-vec-boot-and-update-03', 2, 'byte', 'Which means there is no such thing as a mostly-complete image. Either every byte the bootloader expects is present in order, or what is sitting in flash is not a firmware image at all -- it is only bytes that used to be one.'),

  ('mission-vec-boot-and-update-04', 1, 'tomas', 'A flash write that gets interrupted halfway -- power blip, bad connection, anything -- can leave behind something that is the right size, in the right place, and still completely wrong. A checksum is a single number computed from every byte of a correct image, so the bootloader can recompute it and catch exactly that.'),
  ('mission-vec-boot-and-update-04', 2, 'byte', 'If the recomputed checksum does not match the one stored with the image, the bootloader has proof the image is damaged, without ever needing to understand what the firmware actually does.'),

  ('mission-vec-boot-and-update-05', 1, 'tomas', 'A checksum answers one question: did this image arrive intact. It says nothing at all about who produced it in the first place. A corrupted image and a deliberately hostile image can both fail or pass a checksum for completely unrelated reasons.'),
  ('mission-vec-boot-and-update-05', 2, 'byte', 'Signed firmware adds the second guarantee. The image is signed with a private key only Vector Division holds, and the bootloader verifies that signature with a matching public key before it will ever boot the image -- proof of origin, not just proof of intactness.'),

  ('mission-vec-boot-and-update-06', 1, 'byte', 'We had two boards on a bench. Hand-flashing each one over a wired connection was tedious but fine. The sweep has already found more than that, in places nobody wants to physically visit even once, let alone every time firmware changes.'),
  ('mission-vec-boot-and-update-06', 2, 'tomas', 'Over-the-air update means exactly what it sounds like: pushing a new firmware image to a device remotely, over whatever network connection it already has, instead of a technician plugging in a cable. It is not a convenience feature at this point. It is the only path that scales past two devices at all.'),

  ('mission-vec-boot-and-update-07', 1, 'tomas', 'Here is the design flaw shared by all three bricked boards. There was only ever one place in flash where firmware could live. The update erased that one copy and started writing the new image directly over it.'),
  ('mission-vec-boot-and-update-07', 2, 'byte', 'On the three that failed, the write itself was interrupted partway through -- a power fluctuation, most likely, mid-sweep. When it stopped, the old image was already gone and the new one was not finished. There was nothing left in flash for the bootloader to boot at all.'),
  ('mission-vec-boot-and-update-07', 3, 'tomas', 'A/B partitioning means keeping two full copies of flash available for firmware -- partition A and partition B. The update always writes the new image into whichever partition is not currently running, and the one that is running never gets touched until the new one is confirmed good.'),

  ('mission-vec-boot-and-update-08', 1, 'tomas', 'Two partitions only help if something actually checks whether the new one is good before committing to it, and can back out if it is not. Nothing in the update path we used ever asked that question. It just wrote and switched.'),
  ('mission-vec-boot-and-update-08', 2, 'byte', 'Rollback means the bootloader boots into the new partition provisionally, watches for confirmation that it is actually running correctly, and automatically switches back to the last known-good partition if that confirmation never comes.'),
  ('mission-vec-boot-and-update-08', 3, 'tomas', 'A working rollback would have caught every one of the three bad writes and simply kept running the old firmware, with nobody needing to notice until the next scheduled check. That is the entire point.'),

  ('mission-vec-boot-and-update-09', 1, 'byte', 'A/B partitioning and rollback both assume something -- that at least one full, valid image exists somewhere on the device to fall back to. None of that helps the three boards already sitting in front of us right now, because on those, neither partition holds anything valid at all.'),
  ('mission-vec-boot-and-update-09', 2, 'tomas', 'That is exactly the case recovery mode exists for. A minimal fallback environment, small enough to live somewhere the normal update process can never overwrite, whose only job is accepting a fresh image over a direct physical connection when nothing else on the board can boot.'),

  ('mission-vec-boot-and-update-10', 1, 'tomas', 'Even a perfectly signed, perfectly checksummed, properly A/B-partitioned update can still be the wrong update. If the new firmware assumes a hardware revision or a sensor variant the target board does not actually have, everything can verify correctly and the board still ends up in a state it was never designed to run.'),
  ('mission-vec-boot-and-update-10', 2, 'byte', 'Version compatibility means checking the target''s actual hardware revision and current firmware version before committing an update, not just checking that the update file itself is valid.'),

  ('mission-vec-boot-and-update-11', 1, 'tomas', 'One more thing an update can silently break: the shape of the configuration a board keeps across resets. New firmware can expect a new field, a renamed field, a different layout entirely -- and if it just reads the old configuration as if it were the new shape, that is Act 12''s bug walking back in wearing new firmware.'),
  ('mission-vec-boot-and-update-11', 2, 'byte', 'A safe migration checks the stored configuration''s own version tag, transforms it into the new shape explicitly if it is older, and only ever proceeds once that transformation is confirmed -- it never simply assumes the old data already matches.'),

  ('mission-vec-boot-and-update-12', 1, 'imani', 'Three boards bricked on our first real attempt to update more than one device at once. Walk me through what actually happened, and then tell me what stops it from happening to the next fifty.'),
  ('mission-vec-boot-and-update-12', 2, 'tomas', 'There was only one place in flash for firmware to live, so the update erased the working image before the new one was confirmed. A power fluctuation interrupted the write on three boards. When it stopped, there was no valid image left anywhere on them -- not the old one, not the new one.'),
  ('mission-vec-boot-and-update-12', 3, 'byte', 'And nothing was watching. No checksum gate before boot, no signature check, no partition to fall back to, no rollback to trigger. The bootloader had exactly one image to try, and it was the damaged one.'),
  ('mission-vec-boot-and-update-12', 4, 'tomas', 'The fix is everything this Act built, put together as one pipeline instead of six separate ideas. Two partitions, so the running image is never overwritten until its replacement is proven good. Checksummed and signed images, so the bootloader can prove an image is both intact and genuinely ours before it ever runs it. And a bootloader that only switches to the new image after that verification passes, with rollback ready the moment it does not.'),
  ('mission-vec-boot-and-update-12', 5, 'byte', 'Built that way, this exact failure cannot happen again. A bad write leaves the inactive partition damaged and the active one completely untouched. The device just keeps running what it was already running, and reports the failed update instead of disappearing.'),
  ('mission-vec-boot-and-update-12', 6, 'imani', 'Firmware can now be updated safely at any scale Vector Division can actually reach. That closes Arc II -- you went in with firmware that could not even remember itself correctly across a reset, and you come out with a real pipeline for pushing working firmware to every device that needs it.'),
  ('mission-vec-boot-and-update-12', 7, 'imani', 'So here is the question I have been building toward all Arc, and it is not a firmware question anymore. Byte''s sweep keeps finding more devices every single day. Vector Division can now update however many of them exist safely. What we do not actually know yet is how many that is.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-boot-and-update-01-o1', 'mission-vec-boot-and-update-01', 1, 'Read the incident', 'Judge what "completely unresponsive" actually rules out compared to a board that simply fails to reach the new firmware.'),
  ('mission-vec-boot-and-update-01-o2', 'mission-vec-boot-and-update-01', 2, 'Name where to start', 'Choose the correct first thing to examine, given that every board -- working and bricked alike -- passed through it identically.'),

  ('mission-vec-boot-and-update-02-o1', 'mission-vec-boot-and-update-02', 1, 'Define a bootloader''s role', 'Choose the accurate description of what a bootloader specifically does before the operating system runs.'),
  ('mission-vec-boot-and-update-02-o2', 'mission-vec-boot-and-update-02', 2, 'Explain why it must be trusted', 'State why a bootloader has to be more trustworthy than the firmware it loads.'),

  ('mission-vec-boot-and-update-03-o1', 'mission-vec-boot-and-update-03', 1, 'Define a firmware image', 'Choose the accurate description of what a firmware image actually is.'),
  ('mission-vec-boot-and-update-03-o2', 'mission-vec-boot-and-update-03', 2, 'Judge partial images', 'State whether a partially written firmware image can ever be safely booted.'),

  ('mission-vec-boot-and-update-04-o1', 'mission-vec-boot-and-update-04', 1, 'Explain what a checksum proves', 'Choose the accurate description of what a checksum verifies about an image.'),
  ('mission-vec-boot-and-update-04-o2', 'mission-vec-boot-and-update-04', 2, 'Judge an interrupted write', 'Find the evidence showing a checksum would catch an image left behind by an interrupted flash write.'),

  ('mission-vec-boot-and-update-05-o1', 'mission-vec-boot-and-update-05', 1, 'Tell checksums from signatures', 'Choose the accurate distinction between what a checksum guarantees and what a signature guarantees.'),
  ('mission-vec-boot-and-update-05-o2', 'mission-vec-boot-and-update-05', 2, 'Sort the guarantees', 'Sort each property into something a checksum alone provides or something only a signature provides.'),

  ('mission-vec-boot-and-update-06-o1', 'mission-vec-boot-and-update-06', 1, 'Explain why OTA is necessary now', 'State why hand-flashing stopped being a viable update path for Vector Division.'),
  ('mission-vec-boot-and-update-06-o2', 'mission-vec-boot-and-update-06', 2, 'Define OTA correctly', 'Choose the accurate description of what an over-the-air update actually is.'),

  ('mission-vec-boot-and-update-07-o1', 'mission-vec-boot-and-update-07', 1, 'Diagnose the shared flaw', 'Find the evidence identifying the design flaw shared by all three bricked boards.'),
  ('mission-vec-boot-and-update-07-o2', 'mission-vec-boot-and-update-07', 2, 'Define A/B partitioning', 'Choose the accurate description of how A/B partitioning prevents that exact flaw.'),

  ('mission-vec-boot-and-update-08-o1', 'mission-vec-boot-and-update-08', 1, 'Define rollback correctly', 'Choose the accurate description of what a working rollback mechanism actually does.'),
  ('mission-vec-boot-and-update-08-o2', 'mission-vec-boot-and-update-08', 2, 'Judge the missing piece', 'State what the bricked update path was missing that a working rollback would have supplied.'),

  ('mission-vec-boot-and-update-09-o1', 'mission-vec-boot-and-update-09', 1, 'Define recovery mode', 'Choose the accurate description of what recovery mode is for.'),
  ('mission-vec-boot-and-update-09-o2', 'mission-vec-boot-and-update-09', 2, 'Judge when it applies', 'State why recovery mode is the only remaining option for the three boards already bricked.'),

  ('mission-vec-boot-and-update-10-o1', 'mission-vec-boot-and-update-10', 1, 'Define version compatibility', 'Choose the accurate description of what checking version compatibility actually protects against.'),
  ('mission-vec-boot-and-update-10-o2', 'mission-vec-boot-and-update-10', 2, 'Judge a verified-but-wrong update', 'State how an update can pass every checksum and signature check and still be the wrong update.'),

  ('mission-vec-boot-and-update-11-o1', 'mission-vec-boot-and-update-11', 1, 'Define a safe migration', 'Choose the accurate description of what a safe configuration migration actually does.'),
  ('mission-vec-boot-and-update-11-o2', 'mission-vec-boot-and-update-11', 2, 'Connect it back to Act 12', 'Find the evidence explaining how skipping a migration would reproduce Act 12''s bug under new firmware.'),

  ('mission-vec-boot-and-update-12-o1', 'mission-vec-boot-and-update-12', 1, 'Diagnose the bricking', 'Judge the actual root cause of why the three boards went completely unresponsive.'),
  ('mission-vec-boot-and-update-12-o2', 'mission-vec-boot-and-update-12', 2, 'Prove nothing could catch it', 'Find the evidence proving no safeguard in the old update path could have caught the interrupted write.'),
  ('mission-vec-boot-and-update-12-o3', 'mission-vec-boot-and-update-12', 3, 'Design the fix', 'Choose the correct redesign that prevents this exact failure from ever happening again.'),
  ('mission-vec-boot-and-update-12-o4', 'mission-vec-boot-and-update-12', 4, 'State the diagnosis', 'Having judged the cause, the missing safeguards, and the fix, state what Vector Division actually built and what question it opens next.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-boot-and-update-01-o1-c1', 'mission-vec-boot-and-update-01-o1', 1, 'multiple_choice', 'Three boards did not simply fail to receive the new firmware -- they became completely unresponsive, with no boot log and no heartbeat. What does that rule out?', '{"question":"Three boards did not simply fail to receive the new firmware -- they became completely unresponsive, with no boot log and no heartbeat. What does that rule out?","options":[{"id":"a","text":"It rules out a hardware problem entirely"},{"id":"b","text":"It rules out the old firmware simply still running unchanged -- something replaced or damaged whatever the board needed in order to boot at all, not just failed to add something new"},{"id":"c","text":"It proves the boards were physically destroyed"},{"id":"d","text":"It rules out any connection to the update attempt"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-01-o2-c1', 'mission-vec-boot-and-update-01-o2', 1, 'multiple_choice', 'Every board, whether it survived the update or not, passed through exactly one identical process first. What should Vector Division examine before guessing at the update logic itself?', '{"question":"Every board, whether it survived the update or not, passed through exactly one identical process first. What should Vector Division examine before guessing at the update logic itself?","options":[{"id":"a","text":"The RTOS firmware''s application-level features"},{"id":"b","text":"The reset sequence -- the fixed process every one of these boards runs in the first few milliseconds after power is restored, before any application code exists to run"},{"id":"c","text":"The facility''s network cabling"},{"id":"d","text":"The count of how many boards the sweep has found so far"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-02-o1-c1', 'mission-vec-boot-and-update-02-o1', 1, 'multiple_choice', 'Before the operating system runs, a bootloader''s job is to...', '{"question":"Before the operating system runs, a bootloader''s job is to...","options":[{"id":"a","text":"Run the full application logic at reduced speed"},{"id":"b","text":"Decide which firmware image is valid and where it lives, then hand control to it -- a small, separate program the update itself is not allowed to overwrite"},{"id":"c","text":"Manage the device''s network connection"},{"id":"d","text":"Log every sensor reading to flash"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-02-o2-c1', 'mission-vec-boot-and-update-02-o2', 1, 'multiple_choice', 'Why does a bootloader need to be more trustworthy than the firmware it loads?', '{"question":"Why does a bootloader need to be more trustworthy than the firmware it loads?","options":[{"id":"a","text":"It does not, both need identical levels of trust"},{"id":"b","text":"It is the last layer that can catch a mistake -- if the bootloader itself decides wrong, there is nothing above it left to intervene before the board runs whatever it loaded"},{"id":"c","text":"Bootloaders are never actually executed on real hardware"},{"id":"d","text":"Trust only matters for firmware sent over a network, not for local code"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-03-o1-c1', 'mission-vec-boot-and-update-03-o1', 1, 'multiple_choice', 'A firmware image is best described as...', '{"question":"A firmware image is best described as...","options":[{"id":"a","text":"A description of the program that the bootloader interprets on the fly"},{"id":"b","text":"The compiled program flattened into one contiguous block of bytes, meant to be copied into flash exactly as-is, with no interpretation required"},{"id":"c","text":"A live network connection to the running program"},{"id":"d","text":"Only the source code before compilation"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-03-o2-c1', 'mission-vec-boot-and-update-03-o2', 1, 'multiple_choice', 'Can a partially written firmware image -- correct for the first half of its bytes, missing the rest -- ever be safely booted?', '{"question":"Can a partially written firmware image -- correct for the first half of its bytes, missing the rest -- ever be safely booted?","options":[{"id":"a","text":"Yes, as long as the missing part is small"},{"id":"b","text":"No -- an image is only valid as a complete, exact block of bytes, so a partial write is not a lesser version of the firmware, it is not a valid image at all"},{"id":"c","text":"Yes, the bootloader can fill in missing bytes automatically"},{"id":"d","text":"It depends only on which half is missing"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-04-o1-c1', 'mission-vec-boot-and-update-04-o1', 1, 'multiple_choice', 'A checksum verifies...', '{"question":"A checksum verifies...","options":[{"id":"a","text":"That the firmware performs correctly once running"},{"id":"b","text":"That the bytes actually present in flash match what was intended to be written -- a single computed value that changes if even one byte is wrong, without needing to understand what the firmware does"},{"id":"c","text":"That the firmware was written by an authorized engineer"},{"id":"d","text":"That the board has enough power to boot"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-04-o2-c1', 'mission-vec-boot-and-update-04-o2', 1, 'investigation', 'Which evidence shows a checksum check would have caught the image left by an interrupted flash write?', '{"evidence":[{"id":"e1","label":"Flash trace","detail":"The interrupted write left an image the correct total size in flash, but with the final third of its bytes never actually written, still holding old erased-flash values"},{"id":"e2","label":"Power log","detail":"Facility-wide power draw stayed within normal range that day"},{"id":"e3","label":"Network log","detail":"The OTA transfer reported a completed connection to the update server"}],"question":"Which evidence shows a checksum check would have caught the image left by an interrupted flash write?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-boot-and-update-05-o1-c1', 'mission-vec-boot-and-update-05-o1', 1, 'multiple_choice', 'The real distinction between a checksum and a signature is...', '{"question":"The real distinction between a checksum and a signature is...","options":[{"id":"a","text":"They guarantee the exact same thing, just computed differently"},{"id":"b","text":"A checksum proves an image was not corrupted in transit or storage; a signature, verified against a trusted key, proves the image genuinely came from Vector Division and was not substituted by anyone else"},{"id":"c","text":"A signature is only relevant for the bootloader itself, never for firmware images"},{"id":"d","text":"A checksum is stronger, so a signature is redundant"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-05-o2-c1', 'mission-vec-boot-and-update-05-o2', 1, 'drag_and_drop', 'Sort each guarantee into what a checksum alone provides or what only a signature provides.', '{"items":[{"id":"g1","text":"Proof the image bytes match what was originally written, with none corrupted"},{"id":"g2","text":"Proof the image was produced by a party holding Vector Division''s private key"},{"id":"g3","text":"Detection of a transmission error introduced by a bad connection"},{"id":"g4","text":"Rejection of an intact but deliberately substituted hostile image"}],"targets":[{"id":"checksum","label":"Checksum alone provides"},{"id":"signature","label":"Only a signature provides"}]}'::jsonb, '{"correctMapping":{"g1":"checksum","g2":"signature","g3":"checksum","g4":"signature"}}'::jsonb),

  ('mission-vec-boot-and-update-06-o1-c1', 'mission-vec-boot-and-update-06-o1', 1, 'multiple_choice', 'Why did hand-flashing stop being a viable update path for Vector Division?', '{"question":"Why did hand-flashing stop being a viable update path for Vector Division?","options":[{"id":"a","text":"Hand-flashing was never viable, even for two boards"},{"id":"b","text":"It required a technician to physically visit and connect to every device, which does not scale once the facility sweep is finding new devices faster than anyone can visit them"},{"id":"c","text":"Hand-flashing is technically impossible on this hardware"},{"id":"d","text":"It was replaced only because it was slightly slower than OTA"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-06-o2-c1', 'mission-vec-boot-and-update-06-o2', 1, 'multiple_choice', 'An over-the-air (OTA) update is best described as...', '{"question":"An over-the-air (OTA) update is best described as...","options":[{"id":"a","text":"A firmware update pushed remotely over a device''s existing network connection, with no technician physically present"},{"id":"b","text":"Any update that happens to be wireless in origin regardless of how it reaches the device"},{"id":"c","text":"A firmware update that only works on devices with no bootloader"},{"id":"d","text":"An update that requires no verification of any kind"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-boot-and-update-07-o1-c1', 'mission-vec-boot-and-update-07-o1', 1, 'investigation', 'Which evidence identifies the design flaw shared by all three bricked boards?', '{"evidence":[{"id":"e1","label":"Flash layout record","detail":"Each board''s flash had exactly one region reserved for firmware, with the update process erasing that region before writing the new image into the same space"},{"id":"e2","label":"Power log","detail":"A brief power fluctuation occurred mid-sweep across the facility"},{"id":"e3","label":"Network log","detail":"All six boards received the update payload over the same OTA channel"}],"question":"Which evidence identifies the design flaw shared by all three bricked boards?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-boot-and-update-07-o2-c1', 'mission-vec-boot-and-update-07-o2', 1, 'multiple_choice', 'A/B partitioning prevents this exact flaw by...', '{"question":"A/B partitioning prevents this exact flaw by...","options":[{"id":"a","text":"Writing the new image faster so interruptions are less likely"},{"id":"b","text":"Keeping two full firmware regions in flash and always writing the new image into whichever one is not currently running, so the working copy is never erased until its replacement is proven good"},{"id":"c","text":"Storing two copies of the same firmware in the same region"},{"id":"d","text":"Eliminating the need for a bootloader entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-08-o1-c1', 'mission-vec-boot-and-update-08-o1', 1, 'multiple_choice', 'A working rollback mechanism does what, specifically?', '{"question":"A working rollback mechanism does what, specifically?","options":[{"id":"a","text":"Deletes the new firmware image immediately after every update, regardless of outcome"},{"id":"b","text":"Boots the new partition provisionally, watches for confirmation that it is actually running correctly, and automatically switches back to the last known-good partition if that confirmation never arrives"},{"id":"c","text":"Requires a technician to manually approve every single boot"},{"id":"d","text":"Only applies to updates that fail a checksum, never to ones that pass"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-08-o2-c1', 'mission-vec-boot-and-update-08-o2', 1, 'multiple_choice', 'What did the bricked update path lack that a working rollback would have supplied?', '{"question":"What did the bricked update path lack that a working rollback would have supplied?","options":[{"id":"a","text":"Faster network transfer speeds"},{"id":"b","text":"Any check confirming the new write succeeded before committing to it, and any known-good fallback to return to when it did not"},{"id":"c","text":"A visible progress indicator during the update"},{"id":"d","text":"A larger flash chip"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-09-o1-c1', 'mission-vec-boot-and-update-09-o1', 1, 'multiple_choice', 'Recovery mode is best described as...', '{"question":"Recovery mode is best described as...","options":[{"id":"a","text":"A second copy of the full RTOS kept for redundancy"},{"id":"b","text":"A minimal fallback environment, stored somewhere the normal update process can never overwrite, whose only job is accepting a fresh image over a direct physical connection when nothing else on the board can boot"},{"id":"c","text":"A setting that disables all firmware checks"},{"id":"d","text":"A feature only available before the first update ever occurs"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-09-o2-c1', 'mission-vec-boot-and-update-09-o2', 1, 'investigation', 'Why is recovery mode the only remaining option for the three boards already bricked, rather than A/B partitioning or rollback?', '{"evidence":[{"id":"e1","label":"Flash trace","detail":"Both the primary firmware region and any secondary region on the bricked boards were confirmed empty or invalid -- no complete image survives anywhere on the device"},{"id":"e2","label":"Facilities note","detail":"The three bricked boards are still physically accessible on the current bench"},{"id":"e3","label":"Network log","detail":"The boards no longer respond to any OTA traffic at all"}],"question":"Why is recovery mode the only remaining option for the three boards already bricked?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-boot-and-update-10-o1-c1', 'mission-vec-boot-and-update-10-o1', 1, 'multiple_choice', 'Checking version compatibility before an update specifically protects against...', '{"question":"Checking version compatibility before an update specifically protects against...","options":[{"id":"a","text":"Corruption introduced during the network transfer"},{"id":"b","text":"Installing firmware that is fully intact and genuinely authentic, but was built for a different hardware revision or prior firmware version than the target device actually has"},{"id":"c","text":"A missing digital signature"},{"id":"d","text":"An interrupted flash write"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-10-o2-c1', 'mission-vec-boot-and-update-10-o2', 1, 'multiple_choice', 'How can an update pass every checksum and signature check and still be the wrong update for a given board?', '{"question":"How can an update pass every checksum and signature check and still be the wrong update for a given board?","options":[{"id":"a","text":"It cannot, passing both checks guarantees a correct update"},{"id":"b","text":"Checksums and signatures verify that the image is intact and genuinely from Vector Division, but say nothing about whether that specific image was built for the target board''s actual hardware revision or current firmware version"},{"id":"c","text":"Checksums and signatures only apply to bootloaders, not application firmware"},{"id":"d","text":"It only happens if the image is corrupted, which the checks already rule out"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-boot-and-update-11-o1-c1', 'mission-vec-boot-and-update-11-o1', 1, 'multiple_choice', 'A safe configuration migration does what during an update?', '{"question":"A safe configuration migration does what during an update?","options":[{"id":"a","text":"Deletes the old configuration and starts from factory defaults every time"},{"id":"b","text":"Checks the stored configuration''s own version tag and explicitly transforms it into the new firmware''s expected shape when it is older, rather than assuming the old data already matches"},{"id":"c","text":"Copies the configuration byte-for-byte with no checks, trusting the new firmware to interpret it correctly"},{"id":"d","text":"Only applies to firmware images, never to saved configuration data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-11-o2-c1', 'mission-vec-boot-and-update-11-o2', 1, 'investigation', 'Which evidence explains how skipping a migration step would reproduce Act 12''s configuration bug under new firmware?', '{"evidence":[{"id":"e1","label":"Tomas''s note","detail":"New firmware expects a configuration field the old stored format never included; if the field is simply read as if present, the board interprets whatever bytes happen to sit there as that field''s value -- the same class of misread that caused Act 12''s forgotten configuration bug"},{"id":"e2","label":"Build log","detail":"The new firmware compiles without errors or warnings"},{"id":"e3","label":"Power log","detail":"The board''s power draw during the update stayed within normal range"}],"question":"Which evidence explains how skipping a migration step would reproduce Act 12''s configuration bug under new firmware?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-boot-and-update-12-o1-c1', 'mission-vec-boot-and-update-12-o1', 1, 'multiple_choice', 'Putting the evidence together, what actually bricked the three boards?', '{"question":"Putting the evidence together, what actually bricked the three boards?","options":[{"id":"a","text":"A malicious firmware image substituted during transfer"},{"id":"b","text":"A single-region flash layout with no A/B partitioning meant the update erased the only working firmware copy before the new one finished writing, and a power fluctuation interrupted that write, leaving no valid image anywhere on the device"},{"id":"c","text":"Permanent hardware damage unrelated to the update"},{"id":"d","text":"A checksum mismatch that the bootloader correctly rejected"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-12-o2-c1', 'mission-vec-boot-and-update-12-o2', 1, 'investigation', 'Which evidence proves no safeguard in the old update path could have caught the interrupted write before it bricked the boards?', '{"evidence":[{"id":"e1","label":"Update path audit","detail":"The old update process performed no checksum verification, no signature check, no A/B fallback, and no rollback trigger anywhere between writing the image and rebooting into it"},{"id":"e2","label":"Network log","detail":"The OTA transfer reported a completed connection to the update server on all six boards"},{"id":"e3","label":"Facilities note","detail":"The three bricked boards are physically identical to the three that succeeded"}],"question":"Which evidence proves no safeguard in the old update path could have caught the interrupted write?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-boot-and-update-12-o3-c1', 'mission-vec-boot-and-update-12-o3', 1, 'multiple_choice', 'Which redesign actually prevents this exact failure from ever happening again, rather than only reducing its odds?', '{"question":"Which redesign actually prevents this exact failure from ever happening again, rather than only reducing its odds?","options":[{"id":"a","text":"Adding a warning message before the update starts, with no other changes"},{"id":"b","text":"A/B partitions so the running image is never overwritten until its replacement is proven good, checksummed and signed images so the bootloader can verify an image is intact and genuinely authentic before ever running it, and a bootloader that only switches to the new image after that verification passes, with rollback ready if it does not"},{"id":"c","text":"Updating boards one at a time instead of six at once"},{"id":"d","text":"Increasing the flash chip''s total size"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-boot-and-update-12-o4-c1', 'mission-vec-boot-and-update-12-o4', 1, 'boss_encounter', 'Having diagnosed the bricking, proven nothing could have caught it, and designed the fix, state what Vector Division actually built this Act and what question it opens next.', '{"stages":[{"objectiveRef":"mission-vec-boot-and-update-12-o1","label":"Diagnose the bricking"},{"objectiveRef":"mission-vec-boot-and-update-12-o2","label":"Prove nothing could catch it"},{"objectiveRef":"mission-vec-boot-and-update-12-o3","label":"Design the fix"}],"task":"State the diagnosis in one sentence: the update had no A/B partitioning and no verified rollback path, so a failed write left several boards without any valid firmware image at all, recoverable only through a physical connection -- and the fix is a real OTA pipeline of two partitions, checksummed and signed images, and a bootloader that only ever switches to a new image after confirming it is genuinely valid. Then close Arc II: firmware can now be updated safely at any scale Vector Division can reach, but the still-open question is how many devices that scale actually needs to cover."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-boot-and-update-12-o1","mission-vec-boot-and-update-12-o2","mission-vec-boot-and-update-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-boot-and-update-01-o1-c1', 'orientation', 'Compare "did not receive the update" to "cannot boot anything at all" -- those are different failure classes.', 10, 1),
  ('mission-vec-boot-and-update-01-o1-c1', 'solution', 'No boot log and no heartbeat rule out the old firmware simply persisting unchanged -- something about the board''s ability to boot at all was damaged, not merely left un-updated.', 20, 2),
  ('mission-vec-boot-and-update-01-o2-c1', 'orientation', 'Find the one process common to every board regardless of outcome.', 10, 1),
  ('mission-vec-boot-and-update-01-o2-c1', 'solution', 'The reset sequence -- the fixed process every board runs in its first milliseconds after power is restored, before anything application-level exists yet.', 20, 2),

  ('mission-vec-boot-and-update-02-o1-c1', 'orientation', 'A bootloader runs before the operating system exists at all -- ask what has to happen for the OS to even start.', 10, 1),
  ('mission-vec-boot-and-update-02-o1-c1', 'solution', 'It decides which image is valid and where it lives, then hands off control -- a small program the update process itself is never allowed to overwrite.', 20, 2),
  ('mission-vec-boot-and-update-02-o2-c1', 'orientation', 'Ask what layer exists above the bootloader to catch a bootloader mistake.', 10, 1),
  ('mission-vec-boot-and-update-02-o2-c1', 'solution', 'None -- it is the last layer that can catch an error before whatever it loads simply runs, so it has to be right on its own.', 20, 2),

  ('mission-vec-boot-and-update-03-o1-c1', 'orientation', 'Think about what the bootloader actually copies into flash -- a description, or the raw bytes themselves.', 10, 1),
  ('mission-vec-boot-and-update-03-o1-c1', 'solution', 'A firmware image is the compiled program flattened into one contiguous byte block, copied into flash exactly as-is, with no interpretation.', 20, 2),
  ('mission-vec-boot-and-update-03-o2-c1', 'orientation', 'Ask whether "half correct" is even a meaningful category for a block of bytes meant to be read as one exact unit.', 10, 1),
  ('mission-vec-boot-and-update-03-o2-c1', 'solution', 'No -- a partial image is not a lesser version of the firmware, it simply is not a valid image, complete or otherwise.', 20, 2),

  ('mission-vec-boot-and-update-04-o1-c1', 'orientation', 'A checksum does not read code, it reads bytes.', 10, 1),
  ('mission-vec-boot-and-update-04-o1-c1', 'solution', 'It verifies that the bytes present match what was intended, without needing to understand what the firmware does.', 20, 2),
  ('mission-vec-boot-and-update-04-o2-c1', 'orientation', 'Look for evidence describing bytes that are the right size but not actually all written.', 10, 1),
  ('mission-vec-boot-and-update-04-o2-c1', 'solution', 'e1: the interrupted write left the correct size in flash but with unwritten bytes at the end -- a checksum recomputed over those bytes would not match and would catch it.', 20, 2),

  ('mission-vec-boot-and-update-05-o1-c1', 'orientation', 'One guarantee is about intactness. The other is about origin. They are not interchangeable.', 10, 1),
  ('mission-vec-boot-and-update-05-o1-c1', 'solution', 'A checksum proves the image was not corrupted; a signature, checked against a trusted key, proves it genuinely came from Vector Division.', 20, 2),
  ('mission-vec-boot-and-update-05-o2-c1', 'orientation', 'Ask whether each property is about "did the bytes change" or "who produced the bytes."', 10, 1),
  ('mission-vec-boot-and-update-05-o2-c1', 'solution', 'Checksum: intact bytes, transmission-error detection. Signature: proof of the private key holder, rejection of an intact but substituted hostile image.', 20, 2),

  ('mission-vec-boot-and-update-06-o1-c1', 'orientation', 'Think about what scales and what does not once the number of devices is unknown and growing.', 10, 1),
  ('mission-vec-boot-and-update-06-o1-c1', 'solution', 'A technician physically visiting every device does not scale once the sweep is finding new ones faster than anyone can reach them.', 20, 2),
  ('mission-vec-boot-and-update-06-o2-c1', 'orientation', 'The defining feature is how the update reaches the device, not how fast it travels.', 10, 1),
  ('mission-vec-boot-and-update-06-o2-c1', 'solution', 'OTA is a firmware update pushed remotely over a device''s existing network connection, with no technician physically present.', 20, 2),

  ('mission-vec-boot-and-update-07-o1-c1', 'orientation', 'Look for the evidence describing the flash layout itself, not the network or power conditions.', 10, 1),
  ('mission-vec-boot-and-update-07-o1-c1', 'solution', 'e1: only one region existed for firmware, and the update erased it before writing the replacement into the same space -- the shared design flaw.', 20, 2),
  ('mission-vec-boot-and-update-07-o2-c1', 'orientation', 'The fix is about never touching the copy that still works until the new one is proven.', 10, 1),
  ('mission-vec-boot-and-update-07-o2-c1', 'solution', 'A/B partitioning writes the new image into the inactive partition, leaving the running one untouched until the new one is confirmed good.', 20, 2),

  ('mission-vec-boot-and-update-08-o1-c1', 'orientation', 'Rollback is a two-part behavior: watch, then revert.', 10, 1),
  ('mission-vec-boot-and-update-08-o1-c1', 'solution', 'It boots the new partition provisionally, watches for confirmation of correct operation, and automatically reverts to known-good if confirmation never arrives.', 20, 2),
  ('mission-vec-boot-and-update-08-o2-c1', 'orientation', 'Ask what step is missing between "write finished" and "boot the result."', 10, 1),
  ('mission-vec-boot-and-update-08-o2-c1', 'solution', 'A check that the write actually succeeded, and a known-good fallback to return to when it did not -- both absent from the old path.', 20, 2),

  ('mission-vec-boot-and-update-09-o1-c1', 'orientation', 'It exists specifically for the case where nothing else on the board can boot at all.', 10, 1),
  ('mission-vec-boot-and-update-09-o1-c1', 'solution', 'A minimal fallback environment, stored where updates can never overwrite it, whose only job is accepting a fresh image over a direct connection when nothing else can boot.', 20, 2),
  ('mission-vec-boot-and-update-09-o2-c1', 'orientation', 'Ask whether either partition on the bricked boards actually holds anything valid right now.', 10, 1),
  ('mission-vec-boot-and-update-09-o2-c1', 'solution', 'e1: neither region held a complete valid image -- with nothing to fall back to on the board itself, only a physical recovery connection remains.', 20, 2),

  ('mission-vec-boot-and-update-10-o1-c1', 'orientation', 'Checksums and signatures both look inward at the image itself, never outward at the target board.', 10, 1),
  ('mission-vec-boot-and-update-10-o1-c1', 'solution', 'It protects against installing an intact, authentic image that was simply built for the wrong hardware revision or prior firmware version.', 20, 2),
  ('mission-vec-boot-and-update-10-o2-c1', 'orientation', 'Ask what question a checksum and a signature simply never ask.', 10, 1),
  ('mission-vec-boot-and-update-10-o2-c1', 'solution', 'Both checks verify intactness and origin, not whether that specific image matches the target''s actual hardware revision or firmware version.', 20, 2),

  ('mission-vec-boot-and-update-11-o1-c1', 'orientation', 'A safe migration reads the old data''s own version, not just the new firmware''s expectations.', 10, 1),
  ('mission-vec-boot-and-update-11-o1-c1', 'solution', 'It checks the stored configuration''s version tag and explicitly transforms older data into the new shape, rather than assuming it already matches.', 20, 2),
  ('mission-vec-boot-and-update-11-o2-c1', 'orientation', 'Think about what happens when new firmware reads a field that simply is not there in the old data.', 10, 1),
  ('mission-vec-boot-and-update-11-o2-c1', 'solution', 'e1: reading a field the old format never had means the firmware interprets whatever bytes happen to be there -- the same class of misread that caused Act 12''s bug.', 20, 2),

  ('mission-vec-boot-and-update-12-o1-c1', 'orientation', 'Combine the single-region flash layout with the interrupted write -- what does that leave behind?', 10, 1),
  ('mission-vec-boot-and-update-12-o1-c1', 'solution', 'No A/B partitioning meant the update erased the only working copy before the write finished; a power fluctuation interrupted it, leaving no valid image anywhere on the device.', 20, 2),
  ('mission-vec-boot-and-update-12-o2-c1', 'orientation', 'Look for an audit of the update path itself, not the network or the hardware.', 10, 1),
  ('mission-vec-boot-and-update-12-o2-c1', 'solution', 'e1: the old path had no checksum, no signature check, no A/B fallback, and no rollback -- nothing existed anywhere to catch the interrupted write.', 20, 2),
  ('mission-vec-boot-and-update-12-o3-c1', 'orientation', 'A real fix combines every safeguard this Act covered into one pipeline, not just one of them.', 10, 1),
  ('mission-vec-boot-and-update-12-o3-c1', 'solution', 'A/B partitions, checksummed and signed images, and a bootloader that only switches after verification, with rollback ready -- together, not separately.', 20, 2),
  ('mission-vec-boot-and-update-12-o4-c1', 'orientation', 'Combine the diagnosis and the fix, then look at what Byte''s sweep has been surfacing all Act as the real next question.', 15, 1),
  ('mission-vec-boot-and-update-12-o4-c1', 'solution', 'No A/B partitioning and no verified rollback left several boards with no valid firmware at all after a failed write; the fix is a real OTA pipeline of two partitions, checksummed and signed images, and a bootloader that only switches after confirming validity. Firmware can now update safely at any scale Vector Division can reach -- the open question is how many devices that scale actually needs to cover.', 25, 2);
