-- AI/ML pathway ("Cipher Division") Act 2 -- "Python for Intelligence" content.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other pathway. The world row for
-- this Act already exists (world-ai-python-for-intelligence, act-ai-1).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-python-for-intelligence', 'world-ai-python-for-intelligence', 'python-for-intelligence', '2A - Python for Intelligence', 'The Python every serious ML tool at Cipher Division is built on -- lists, dictionaries, functions, NumPy arrays, and pandas DataFrames -- learned by actually reading Echo''s interaction log instead of just talking about it.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-python-for-intelligence-1', 'campaign-ai-python-for-intelligence', 'first-principles', 'First Principles', 'Plain Python and NumPy fundamentals: lists, dictionaries, functions, arrays, shapes and vectorization.', 1),
  ('operation-ai-python-for-intelligence-2', 'campaign-ai-python-for-intelligence', 'the-array-mindset', 'The Array Mindset', 'Broadcasting, pandas DataFrames, filtering, grouping, reproducibility, and the first real pass over Echo''s log.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-python-for-intelligence-01', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'python-refresher', 'Python Refresher', 'Echo''s interaction log just landed on your desk, and nobody can read it by hand. Before Byte loads a single row, he wants proof you can read and write plain Python.', 'beginner', ARRAY['maya','byte'], null, null, '{"type":"simulation","simulationId":"python-refresher-sim"}'::jsonb, '{"xp":80,"credits":15}'::jsonb, false, 1),
  ('mission-ai-python-for-intelligence-02', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'lists-and-dictionaries', 'Lists and Dictionaries', 'Every row of Echo''s log is really a Python structure underneath. Lists carry order. Dictionaries carry names. Confuse them and you misread the data before you even start.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"lists-and-dicts-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-ai-python-for-intelligence-03', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'functions', 'Functions', 'Reusable logic against Echo''s log starts as a function -- parameters, arguments, and the difference between returning a value and merely printing one.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"functions-sim"}'::jsonb, '{"xp":90,"credits":20}'::jsonb, false, 3),
  ('mission-ai-python-for-intelligence-04', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'numpy-arrays', 'NumPy Arrays', 'Lists get slow the moment real math starts. NumPy arrays are the fix -- and they behave nothing like a list the moment you touch them with an operator.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"numpy-arrays-sim"}'::jsonb, '{"xp":100,"credits":20}'::jsonb, false, 4),
  ('mission-ai-python-for-intelligence-05', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'shapes', 'Shapes', 'Shape is the first thing to check on any array before doing anything else with it -- how many dimensions, and how large each one actually is.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"array-shapes-sim"}'::jsonb, '{"xp":100,"credits":20}'::jsonb, false, 5),
  ('mission-ai-python-for-intelligence-06', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-1', 'vectorization', 'Vectorization', 'Vectorization replaces a hand-written loop with one operation across an entire array -- on a million-row log, that is the difference between seconds and minutes.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"vectorization-sim"}'::jsonb, '{"xp":110,"credits":20}'::jsonb, false, 6),
  ('mission-ai-python-for-intelligence-07', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'broadcasting', 'Broadcasting', 'Broadcasting lets NumPy combine arrays of different shapes without a loop to line them up -- as long as the shapes are actually compatible.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"broadcasting-sim"}'::jsonb, '{"xp":110,"credits":25}'::jsonb, false, 7),
  ('mission-ai-python-for-intelligence-08', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'pandas-dataframes', 'pandas DataFrames', 'Arjun hands over a real slice of Echo''s log as a pandas DataFrame -- named columns, mixed types, and a structure built to be filtered, grouped, and trusted.', 'beginner', ARRAY['arjun','byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"pandas-dataframes-sim"}'::jsonb, '{"xp":120,"credits":25}'::jsonb, false, 8),
  ('mission-ai-python-for-intelligence-09', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'filtering', 'Filtering', 'Reading every row does not scale. Filtering does -- boolean masks that keep only the rows of Echo''s log that actually matter to the question being asked.', 'beginner', ARRAY['arjun'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"filtering-sim"}'::jsonb, '{"xp":120,"credits":25}'::jsonb, false, 9),
  ('mission-ai-python-for-intelligence-10', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'grouping-and-aggregation', 'Grouping and Aggregation', 'Filtering answers questions about single rows. Grouping answers questions about categories -- averages and counts filtering alone cannot see.', 'beginner', ARRAY['arjun'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"groupby-aggregation-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 10),
  ('mission-ai-python-for-intelligence-11', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'reproducibility', 'Reproducibility', 'Before touching Echo''s real log, one more discipline: reproducibility. A result nobody else can rebuild is not a result Cipher Division can trust.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"reproducibility-sim"}'::jsonb, '{"xp":130,"credits":30}'::jsonb, false, 11),
  ('mission-ai-python-for-intelligence-12', 'world-ai-python-for-intelligence', 'campaign-ai-python-for-intelligence', 'operation-ai-python-for-intelligence-2', 'the-million-row-dataset', 'The Million-Row Dataset', 'The full interaction log, not a practice sample. Over a million rows, and a timeline that does not match the six hours anyone thought Echo had been active.', 'boss', ARRAY['maya','byte'], '{"requiredMissionIds":["mission-ai-python-for-intelligence-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"million-row-dataset-boss-sim"}'::jsonb, '{"xp":420,"credits":90,"badgeIds":["the-million-row-dataset"],"skillXp":{"python_for_ml":45,"ai_ml_fundamentals":15}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-python-for-intelligence-01', 1, 'maya', 'Echo''s entire interaction log just landed on my desk. Every request, every response, every timestamp since Cipher Labs went active.'),
  ('mission-ai-python-for-intelligence-01', 2, 'maya', 'Nobody can read a file like this by hand. Byte wants to start with you at the fundamentals, because everything after this depends on getting them right.'),
  ('mission-ai-python-for-intelligence-01', 3, 'byte', 'Python. Variables, types, control flow, functions -- the language every serious data and ML tool in Cipher Division is built on top of. If you already know it, this will be quick. If you do not, this is where you cannot skip.'),
  ('mission-ai-python-for-intelligence-01', 4, 'byte', 'Before I load a single row of Echo''s log, I want proof you can read and write plain Python without me holding your hand. Ready?'),

  ('mission-ai-python-for-intelligence-02', 1, 'byte', 'Echo''s log does not arrive as one blob of text. Every row is a record, and in Python two structures carry almost all of it: lists for ordered sequences, dictionaries for named fields.'),
  ('mission-ai-python-for-intelligence-02', 2, 'byte', 'A list is an ordered collection you access by position. A dictionary is a set of key-value pairs you access by name. Get this distinction wrong and you will misread every row Echo ever wrote.'),
  ('mission-ai-python-for-intelligence-02', 3, 'byte', 'Here is a single row from the log, already parsed into Python for you. Let us see if you can work with it correctly.'),

  ('mission-ai-python-for-intelligence-03', 1, 'byte', 'Every reusable piece of logic Cipher Division runs against Echo''s log starts as a function -- a named block that takes input, does something, and hands a result back.'),
  ('mission-ai-python-for-intelligence-03', 2, 'byte', 'Parameters are the placeholders a function declares. Arguments are the actual values you hand it when you call it. Return sends a value back to whoever called the function. Print just displays something and hands nothing back at all.'),
  ('mission-ai-python-for-intelligence-03', 3, 'byte', 'Confusing return and print breaks pipelines in ways that are miserable to debug later. Let us make sure you know the difference now.'),

  ('mission-ai-python-for-intelligence-04', 1, 'byte', 'Lists get slow and clumsy the moment you are doing math across a million rows. NumPy arrays fix that -- one data type, packed tightly, built for numerical work.'),
  ('mission-ai-python-for-intelligence-04', 2, 'byte', 'A NumPy array looks like a list on the surface, but it behaves completely differently the moment you touch it with an operator.'),
  ('mission-ai-python-for-intelligence-04', 3, 'byte', 'Echo''s response-time column is about to become a NumPy array. Let us see if you can spot where the list habits stop working.'),

  ('mission-ai-python-for-intelligence-05', 1, 'byte', 'Shape is the first thing to check on any array before doing anything else with it -- how many dimensions it has, and how large each one is.'),
  ('mission-ai-python-for-intelligence-05', 2, 'byte', 'A one-dimensional array is a plain sequence. A two-dimensional array is rows and columns, like a small table. Get the shape wrong and every operation after it either crashes or silently produces nonsense.'),

  ('mission-ai-python-for-intelligence-06', 1, 'byte', 'Vectorization means applying one operation to an entire array at once, instead of writing a loop that visits each element by hand.'),
  ('mission-ai-python-for-intelligence-06', 2, 'byte', 'It is not just shorter to write. NumPy runs the loop internally, in optimized compiled code -- on a million-row log, that is the difference between seconds and minutes.'),

  ('mission-ai-python-for-intelligence-07', 1, 'byte', 'Broadcasting is what lets NumPy combine arrays of different shapes without you writing a loop to line them up by hand, as long as the shapes are compatible.'),
  ('mission-ai-python-for-intelligence-07', 2, 'byte', 'It is not magic. There are real rules for which shapes are allowed to combine, and getting them wrong throws an error instead of silently producing the wrong answer -- which, honestly, is the safer failure.'),

  ('mission-ai-python-for-intelligence-08', 1, 'arjun', 'Arjun Vale. Arrays get you the math. A DataFrame gets you the whole table -- rows, named columns, mixed types, lined up the way Echo''s log actually looks once it is parsed.'),
  ('mission-ai-python-for-intelligence-08', 2, 'byte', 'Think of a DataFrame as a dictionary of columns, or a spreadsheet that knows how to compute. Every column underneath is really a pandas Series.'),
  ('mission-ai-python-for-intelligence-08', 3, 'arjun', 'Let us load a small sample of the log and see if you can read it correctly before we hand you the real thing.'),

  ('mission-ai-python-for-intelligence-09', 1, 'arjun', 'Most of what you do with a real log is not reading every row -- it is asking for the rows that matter. That is filtering.'),
  ('mission-ai-python-for-intelligence-09', 2, 'arjun', 'In pandas, a filter starts as a boolean mask: one True or False value per row. Apply the mask to the DataFrame and only the True rows survive.'),

  ('mission-ai-python-for-intelligence-10', 1, 'arjun', 'Filtering answers questions about individual rows. Grouping answers questions about categories -- average response time per event type, count of queries per hour, patterns filtering alone cannot show you.'),
  ('mission-ai-python-for-intelligence-10', 2, 'arjun', 'groupby splits the table by a column''s values, then an aggregation like mean or count collapses each group down to one number.'),

  ('mission-ai-python-for-intelligence-11', 1, 'byte', 'Before you touch Echo''s real log, one more discipline: reproducibility. Anyone rerunning your analysis, including you next week, needs to land on the exact same result.'),
  ('mission-ai-python-for-intelligence-11', 2, 'byte', 'Any random sampling, any shuffling of rows, needs a fixed seed. Without one, every run tells a slightly different story, and nobody can tell which run was actually right.'),

  ('mission-ai-python-for-intelligence-12', 1, 'maya', 'Everything this Act taught you, we need right now, on the real thing. Echo''s full interaction log, not a sample Byte built for practice.'),
  ('mission-ai-python-for-intelligence-12', 2, 'byte', 'I pulled three pieces of evidence out of a first pass over the file. Cipher Division needs your read on each one before anyone trusts it.'),
  ('mission-ai-python-for-intelligence-12', 3, 'byte', 'One thing already does not add up. The log holds well over a million rows. Nobody thought Echo had been active long enough to generate that many.'),
  ('mission-ai-python-for-intelligence-12', 4, 'maya', 'Confirm what the data actually says, not what we assumed going in. How many rows there really are, what the timestamps really show, and whether any of it could be an innocent logging bug instead of Echo itself.'),
  ('mission-ai-python-for-intelligence-12', 5, 'byte', 'Three pieces of evidence. Judge each one on its own, then tell Cipher Division what the file actually proves.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-python-for-intelligence-01-o1', 'mission-ai-python-for-intelligence-01', 1, 'Confirm the assignment', 'Confirm you are ready to start reading Echo''s log the right way.'),
  ('mission-ai-python-for-intelligence-01-o2', 'mission-ai-python-for-intelligence-01', 2, 'Catch the bug', 'Find the line that will crash before Echo''s log is even opened.'),

  ('mission-ai-python-for-intelligence-02-o1', 'mission-ai-python-for-intelligence-02', 1, 'Fix the lookup', 'Find the line that uses the wrong access pattern for the structure it is called on.'),
  ('mission-ai-python-for-intelligence-02-o2', 'mission-ai-python-for-intelligence-02', 2, 'Sort the structures', 'Match each property to the structure it actually describes, list or dictionary.'),

  ('mission-ai-python-for-intelligence-03-o1', 'mission-ai-python-for-intelligence-03', 1, 'Find the missing return', 'Find the line that stops this function from ever handing its result back.'),
  ('mission-ai-python-for-intelligence-03-o2', 'mission-ai-python-for-intelligence-03', 2, 'Name the placeholder', 'Identify what a function parameter actually is.'),

  ('mission-ai-python-for-intelligence-04-o1', 'mission-ai-python-for-intelligence-04', 1, 'Spot the list habit', 'Find the line that treats a NumPy array like a Python list.'),
  ('mission-ai-python-for-intelligence-04-o2', 'mission-ai-python-for-intelligence-04', 2, 'Match the array operations', 'Match each NumPy call to what it actually does.'),

  ('mission-ai-python-for-intelligence-05-o1', 'mission-ai-python-for-intelligence-05', 1, 'Catch the reshape error', 'Find the reshape call that does not fit the data it is reshaping.'),
  ('mission-ai-python-for-intelligence-05-o2', 'mission-ai-python-for-intelligence-05', 2, 'Read the shape', 'State what a given array shape actually represents.'),

  ('mission-ai-python-for-intelligence-06-o1', 'mission-ai-python-for-intelligence-06', 1, 'Fix the manual loop', 'Find the line that sends this loop one index past the end of the array.'),
  ('mission-ai-python-for-intelligence-06-o2', 'mission-ai-python-for-intelligence-06', 2, 'Define vectorization', 'State what vectorization actually means in NumPy.'),

  ('mission-ai-python-for-intelligence-07-o1', 'mission-ai-python-for-intelligence-07', 1, 'Catch the shape mismatch', 'Find the line that combines two arrays with incompatible shapes.'),
  ('mission-ai-python-for-intelligence-07-o2', 'mission-ai-python-for-intelligence-07', 2, 'State the broadcasting rule', 'State the actual rule that decides whether two shapes can broadcast together.'),

  ('mission-ai-python-for-intelligence-08-o1', 'mission-ai-python-for-intelligence-08', 1, 'Catch the bad attribute', 'Find the line that calls an attribute a DataFrame does not have.'),
  ('mission-ai-python-for-intelligence-08-o2', 'mission-ai-python-for-intelligence-08', 2, 'Match the DataFrame operations', 'Match each pandas call to what it actually does.'),

  ('mission-ai-python-for-intelligence-09-o1', 'mission-ai-python-for-intelligence-09', 1, 'Fix the boolean mask', 'Find the line that combines two conditions the wrong way.'),
  ('mission-ai-python-for-intelligence-09-o2', 'mission-ai-python-for-intelligence-09', 2, 'Explain the filter', 'State why indexing a DataFrame with a boolean Series keeps only certain rows.'),

  ('mission-ai-python-for-intelligence-10-o1', 'mission-ai-python-for-intelligence-10', 1, 'Catch the misspelled call', 'Find the line that misspells a pandas method name.'),
  ('mission-ai-python-for-intelligence-10-o2', 'mission-ai-python-for-intelligence-10', 2, 'Explain the aggregation', 'State what a groupby followed by mean actually computes.'),

  ('mission-ai-python-for-intelligence-11-o1', 'mission-ai-python-for-intelligence-11', 1, 'Explain the seed', 'State why Cipher Division needs a fixed random seed before sampling Echo''s log.'),
  ('mission-ai-python-for-intelligence-11-o2', 'mission-ai-python-for-intelligence-11', 2, 'Fix the ordering', 'Find the line that is out of order and defeats the reproducibility of this sample.'),

  ('mission-ai-python-for-intelligence-12-o1', 'mission-ai-python-for-intelligence-12', 1, 'Read the row count', 'Judge which finding actually confirms the log holds far more than six hours of activity.'),
  ('mission-ai-python-for-intelligence-12-o2', 'mission-ai-python-for-intelligence-12', 2, 'Read the timestamps', 'Find the line that reveals how long Echo has really been logging activity.'),
  ('mission-ai-python-for-intelligence-12-o3', 'mission-ai-python-for-intelligence-12', 3, 'Rule out the logging bug', 'Judge whether the huge row count could be an innocent duplication bug instead of real activity.'),
  ('mission-ai-python-for-intelligence-12-o4', 'mission-ai-python-for-intelligence-12', 4, 'State what the data proves', 'Having judged the row count, the timeline, and the alternate explanation, state what Echo''s log actually proves.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-python-for-intelligence-01-o1-c1', 'mission-ai-python-for-intelligence-01-o1', 1, 'story_dialogue', 'Confirm you are ready to continue.', '{"lines":[{"characterId":"byte","text":"Before I load a single row of Echo''''s log -- are you in?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),
  ('mission-ai-python-for-intelligence-01-o2-c1', 'mission-ai-python-for-intelligence-01-o2', 1, 'code_debugging', 'Byte''s script previews the log file. One line will crash it before it even opens the file. Find it.', '{"language":"python","code":"log_path = \"echo_interactions.log\"\nrow_count = 0\nprint(\"Preparing to scan \" + log_path)\nprint(\"Estimated rows: \" + row_count)\nwith open(log_path) as f:\n    for line in f:\n        row_count += 1","question":"Byte wrote a quick script to preview Echo''''s log file before opening it. One line will crash it before it even reads a single row. Which line?"}'::jsonb, '{"requiredLineIds":["print(\"Estimated rows: \" + row_count)"]}'::jsonb),

  ('mission-ai-python-for-intelligence-02-o1-c1', 'mission-ai-python-for-intelligence-02-o1', 1, 'code_debugging', 'Find the line that reads this row with the wrong access pattern.', '{"language":"python","code":"row = {\"timestamp\": \"03:12:41\", \"event\": \"query\", \"response_ms\": 118}\nevents = [\"query\", \"response\", \"idle\", \"query\"]\nprint(row[\"event\"])\nprint(events[0])\nprint(row[0])","question":"This snippet reads a single row from Echo''''s log. One line uses the wrong access pattern for the structure it is called on. Which line?"}'::jsonb, '{"requiredLineIds":["print(row[0])"]}'::jsonb),
  ('mission-ai-python-for-intelligence-02-o2-c1', 'mission-ai-python-for-intelligence-02-o2', 1, 'drag_and_drop', 'Match each property to the structure it actually describes.', '{"items":[{"id":"i1","text":"Accessed by position, using an integer index"},{"id":"i2","text":"Accessed by a named key"},{"id":"i3","text":"Can hold duplicate values"},{"id":"i4","text":"Each key must be unique"}],"targets":[{"id":"t1","label":"List"},{"id":"t2","label":"Dictionary"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-python-for-intelligence-03-o1-c1', 'mission-ai-python-for-intelligence-03-o1', 1, 'code_debugging', 'This function should hand back the average response time. It does not. Find the bug.', '{"language":"python","code":"def average_response_ms(times):\n    total = sum(times)\n    count = len(times)\n    print(total / count)\n\nsample = [118, 204, 97, 150]\navg = average_response_ms(sample)\nprint(\"Average:\", avg)","question":"This function is supposed to hand back Echo''''s average response time so it can be printed later. Instead avg comes out as None. Which line is the bug?"}'::jsonb, '{"requiredLineIds":["    print(total / count)"]}'::jsonb),
  ('mission-ai-python-for-intelligence-03-o2-c1', 'mission-ai-python-for-intelligence-03-o2', 1, 'multiple_choice', 'Identify what times actually is in this function.', '{"question":"In def average_response_ms(times):, what is times?","options":[{"id":"a","text":"An argument"},{"id":"b","text":"A parameter"},{"id":"c","text":"A return value"},{"id":"d","text":"A global variable"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-python-for-intelligence-04-o1-c1', 'mission-ai-python-for-intelligence-04-o1', 1, 'code_debugging', 'One line here assumes a NumPy array behaves like a Python list. Find it.', '{"language":"python","code":"import numpy as np\n\nresponse_times = np.array([118, 204, 97, 150])\nprint(response_times.shape)\nprint(response_times * 2)\nresponse_times.append(133)\nprint(response_times)","question":"Byte imported Echo''''s response times as a NumPy array. One line assumes the array behaves like a Python list. Which line breaks?"}'::jsonb, '{"requiredLineIds":["response_times.append(133)"]}'::jsonb),
  ('mission-ai-python-for-intelligence-04-o2-c1', 'mission-ai-python-for-intelligence-04-o2', 1, 'drag_and_drop', 'Match each NumPy call to what it actually does.', '{"items":[{"id":"i1","text":"np.array(a_list)"},{"id":"i2","text":"arr.shape"},{"id":"i3","text":"arr.dtype"},{"id":"i4","text":"np.zeros(5)"}],"targets":[{"id":"t1","label":"Converts a Python list into a NumPy array"},{"id":"t2","label":"Tuple describing the length along each dimension"},{"id":"t3","label":"The data type of every element in the array"},{"id":"t4","label":"Creates a new array of the given length, filled with zeros"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),

  ('mission-ai-python-for-intelligence-05-o1-c1', 'mission-ai-python-for-intelligence-05-o1', 1, 'code_debugging', 'One reshape call here asks for a shape that does not fit the data. Find it.', '{"language":"python","code":"import numpy as np\n\nlog_sample = np.array([118, 204, 97, 150, 88, 176])\nprint(log_sample.shape)\ntable = log_sample.reshape(2, 3)\nprint(table.shape)\nbroken = log_sample.reshape(2, 4)\nprint(broken.shape)","question":"log_sample holds 6 response times. One reshape call asks for a shape that does not fit the data. Which line?"}'::jsonb, '{"requiredLineIds":["broken = log_sample.reshape(2, 4)"]}'::jsonb),
  ('mission-ai-python-for-intelligence-05-o2-c1', 'mission-ai-python-for-intelligence-05-o2', 1, 'multiple_choice', 'State what a given array shape represents.', '{"question":"An array with shape (1000, 4) most likely represents...","options":[{"id":"a","text":"4 rows of 1000 columns each"},{"id":"b","text":"1000 rows, each with 4 columns"},{"id":"c","text":"A single dimension of 4000 values"},{"id":"d","text":"1000 separate arrays"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-python-for-intelligence-06-o1-c1', 'mission-ai-python-for-intelligence-06-o1', 1, 'code_debugging', 'This loop is supposed to convert milliseconds to seconds. It crashes. Find the bug.', '{"language":"python","code":"import numpy as np\n\nresponse_ms = np.array([118, 204, 97, 150])\nresponse_sec = np.zeros(4)\nfor i in range(len(response_ms) + 1):\n    response_sec[i] = response_ms[i] / 1000\nprint(response_sec)","question":"This loop is supposed to convert each response time from milliseconds to seconds. It crashes with an IndexError. Which line causes it?"}'::jsonb, '{"requiredLineIds":["for i in range(len(response_ms) + 1):"]}'::jsonb),
  ('mission-ai-python-for-intelligence-06-o2-c1', 'mission-ai-python-for-intelligence-06-o2', 1, 'multiple_choice', 'State what vectorization actually means.', '{"question":"Vectorization in NumPy primarily means...","options":[{"id":"a","text":"Writing a for loop with fewer lines of code"},{"id":"b","text":"Applying an operation to an entire array at once instead of looping element by element in Python"},{"id":"c","text":"Converting an array to a list"},{"id":"d","text":"Running code on a GPU"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-python-for-intelligence-07-o1-c1', 'mission-ai-python-for-intelligence-07-o1', 1, 'code_debugging', 'This subtraction between two arrays raises an error. Find the line.', '{"language":"python","code":"import numpy as np\n\nresponse_ms = np.array([118, 204, 97, 150])\nbaseline = np.array([100, 100])\nadjusted = response_ms - baseline\nprint(adjusted)","question":"Byte tried to subtract a baseline from Echo''''s response times. One line raises a broadcasting error. Which line?"}'::jsonb, '{"requiredLineIds":["adjusted = response_ms - baseline"]}'::jsonb),
  ('mission-ai-python-for-intelligence-07-o2-c1', 'mission-ai-python-for-intelligence-07-o2', 1, 'multiple_choice', 'State the actual broadcasting rule.', '{"question":"NumPy can broadcast two arrays together when, for every dimension compared from the right...","options":[{"id":"a","text":"The sizes are always identical"},{"id":"b","text":"The sizes are equal, or at least one of them is 1"},{"id":"c","text":"One array always has exactly one dimension"},{"id":"d","text":"Broadcasting never checks shapes"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-python-for-intelligence-08-o1-c1', 'mission-ai-python-for-intelligence-08-o1', 1, 'code_debugging', 'One line here calls an attribute a DataFrame does not have. Find it.', '{"language":"python","code":"import pandas as pd\n\nlog = pd.DataFrame({\n    \"timestamp\": [\"03:12:41\", \"03:12:44\", \"03:12:50\"],\n    \"event\": [\"query\", \"response\", \"idle\"],\n    \"response_ms\": [118, 204, 0]\n})\nprint(log.columns)\nprint(log[\"event\"])\nprint(log.rows)","question":"This snippet loads three rows of Echo''''s log into a DataFrame. One line calls an attribute that does not exist. Which line?"}'::jsonb, '{"requiredLineIds":["print(log.rows)"]}'::jsonb),
  ('mission-ai-python-for-intelligence-08-o2-c1', 'mission-ai-python-for-intelligence-08-o2', 1, 'drag_and_drop', 'Match each pandas call to what it actually does.', '{"items":[{"id":"i1","text":"pd.DataFrame({...})"},{"id":"i2","text":"log.columns"},{"id":"i3","text":"log[\"event\"]"},{"id":"i4","text":"log.head()"}],"targets":[{"id":"t1","label":"Creates a new DataFrame from columns of data"},{"id":"t2","label":"Returns the column names"},{"id":"t3","label":"Returns one column as a Series"},{"id":"t4","label":"Previews the first few rows"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),

  ('mission-ai-python-for-intelligence-09-o1-c1', 'mission-ai-python-for-intelligence-09-o1', 1, 'code_debugging', 'This filter is supposed to find slow query events. It crashes. Find the bug.', '{"language":"python","code":"import pandas as pd\n\nlog = pd.DataFrame({\n    \"event\": [\"query\", \"response\", \"idle\", \"query\"],\n    \"response_ms\": [118, 204, 0, 97]\n})\nqueries = log[log[\"event\"] == \"query\"]\nprint(queries)\nslow = log[log[\"response_ms\"] > 100 and log[\"event\"] == \"query\"]\nprint(slow)","question":"This filter is supposed to find query events slower than 100ms. It crashes instead. Which line is the bug?"}'::jsonb, '{"requiredLineIds":["slow = log[log[\"response_ms\"] > 100 and log[\"event\"] == \"query\"]"]}'::jsonb),
  ('mission-ai-python-for-intelligence-09-o2-c1', 'mission-ai-python-for-intelligence-09-o2', 1, 'multiple_choice', 'Explain why the boolean mask keeps certain rows.', '{"question":"In pandas, log[log[\"response_ms\"] > 100] works because...","options":[{"id":"a","text":"log[\"response_ms\"] > 100 produces a Series of True/False values, one per row, and indexing a DataFrame with that keeps only the True rows"},{"id":"b","text":"pandas automatically deletes rows over 100"},{"id":"c","text":"It sorts the DataFrame by response_ms"},{"id":"d","text":"It is identical to log.drop(\"response_ms\")"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-ai-python-for-intelligence-10-o1-c1', 'mission-ai-python-for-intelligence-10-o1', 1, 'code_debugging', 'One of these lines misspells a pandas method name. Find it.', '{"language":"python","code":"import pandas as pd\n\nlog = pd.DataFrame({\n    \"event\": [\"query\", \"response\", \"query\", \"idle\"],\n    \"response_ms\": [118, 204, 97, 0]\n})\nby_event = log.groupby(\"event\")\naverage = by_event.mean()\nprint(average)\ncounts = log.groupbi(\"event\")[\"response_ms\"].count()\nprint(counts)","question":"One of these lines misspells a pandas method name and will crash. Which line?"}'::jsonb, '{"requiredLineIds":["counts = log.groupbi(\"event\")[\"response_ms\"].count()"]}'::jsonb),
  ('mission-ai-python-for-intelligence-10-o2-c1', 'mission-ai-python-for-intelligence-10-o2', 1, 'multiple_choice', 'State what this groupby and mean actually compute.', '{"question":"log.groupby(\"event\")[\"response_ms\"].mean() computes...","options":[{"id":"a","text":"The overall average response time across the whole log"},{"id":"b","text":"The average response_ms separately for each distinct value of event"},{"id":"c","text":"The count of rows per event"},{"id":"d","text":"A random sample of response times"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-python-for-intelligence-11-o1-c1', 'mission-ai-python-for-intelligence-11-o1', 1, 'multiple_choice', 'Explain why a fixed random seed matters here.', '{"question":"Why does Cipher Division care about setting a random seed before sampling rows from Echo''''s log?","options":[{"id":"a","text":"It makes the code run faster"},{"id":"b","text":"Without a fixed seed, a random sample changes every run, so nobody can verify or rebuild someone else''''s findings"},{"id":"c","text":"It is required by Python syntax"},{"id":"d","text":"It has no real effect, it is just convention"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-python-for-intelligence-11-o2-c1', 'mission-ai-python-for-intelligence-11-o2', 1, 'code_debugging', 'This sample is supposed to be reproducible. It is not. Find the misplaced line.', '{"language":"python","code":"import numpy as np\nimport pandas as pd\n\nlog = pd.DataFrame({\"response_ms\": [118, 204, 97, 150, 88, 176]})\nsample = log.sample(n=3)\nnp.random.seed(42)\nprint(sample)","question":"This code is supposed to draw a reproducible sample of 3 rows. It is not reproducible. Which line is misplaced?"}'::jsonb, '{"requiredLineIds":["np.random.seed(42)"]}'::jsonb),

  ('mission-ai-python-for-intelligence-12-o1-c1', 'mission-ai-python-for-intelligence-12-o1', 1, 'investigation', 'Judge which finding actually proves the log holds far more than six hours of activity.', '{"evidence":[{"id":"e1","label":"log.shape output","detail":"(1247003, 6) -- over 1.2 million rows, 6 columns, no errors on load"},{"id":"e2","label":"File size on disk","detail":"The raw log file is 410MB before parsing"},{"id":"e3","label":"Column list","detail":"Columns include timestamp, event, response_ms, session_id, model_version, source_ip"}],"question":"Which finding actually confirms Echo''''s log holds far more data than six hours of activity could produce?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-python-for-intelligence-12-o2-c1', 'mission-ai-python-for-intelligence-12-o2', 1, 'code_debugging', 'Find the line that reveals how long the log actually spans.', '{"language":"python","code":"import pandas as pd\n\nlog = pd.read_csv(\"echo_interactions.log\")\nlog[\"timestamp\"] = pd.to_datetime(log[\"timestamp\"])\nspan = log[\"timestamp\"].max() - log[\"timestamp\"].min()\nprint(span)\nprint(log[\"timestamp\"].min())\nprint(log[\"timestamp\"].max())","question":"Byte loaded the full log and parsed its timestamps. Which line produces the number that actually proves Echo has been logging far longer than six hours?"}'::jsonb, '{"requiredLineIds":["span = log[\"timestamp\"].max() - log[\"timestamp\"].min()"]}'::jsonb),
  ('mission-ai-python-for-intelligence-12-o3-c1', 'mission-ai-python-for-intelligence-12-o3', 1, 'multiple_choice', 'Judge whether the row count could be an innocent duplication bug.', '{"question":"Byte checked for an innocent explanation first: could the huge row count just be a logging bug duplicating entries, rather than proof Echo has been active longer? What did the data show?","options":[{"id":"a","text":"Session IDs and timestamps across the log are distinct and increase monotonically, with no duplicate blocks -- ruling out a duplication bug"},{"id":"b","text":"The log contains only one unique timestamp repeated a million times"},{"id":"c","text":"Every row has an identical session_id, suggesting a single duplicated event"},{"id":"d","text":"The file failed a checksum, meaning the data cannot be trusted at all"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-python-for-intelligence-12-o4-c1', 'mission-ai-python-for-intelligence-12-o4', 1, 'boss_encounter', 'Having judged the row count, the timeline, and the alternate explanation, state what Echo''s log actually proves.', '{"stages":[{"objectiveRef":"mission-ai-python-for-intelligence-12-o1","label":"Read the row count"},{"objectiveRef":"mission-ai-python-for-intelligence-12-o2","label":"Read the timestamps"},{"objectiveRef":"mission-ai-python-for-intelligence-12-o3","label":"Rule out the logging bug"}],"task":"State what the data actually proves about Echo''''s activity, and name the real question it leaves open."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-python-for-intelligence-12-o1","mission-ai-python-for-intelligence-12-o2","mission-ai-python-for-intelligence-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-python-for-intelligence-01-o1-c1', 'orientation', 'There is nothing to solve here -- just confirm you are ready to continue.', 0, 1),

  ('mission-ai-python-for-intelligence-01-o2-c1', 'orientation', 'Python does not automatically convert a number to text just because you used plus. Check every line that mixes a string with a number.', 10, 1),
  ('mission-ai-python-for-intelligence-01-o2-c1', 'concept', 'row_count is an integer. Adding a string and an integer with + raises a TypeError -- Python needs str(row_count) or an f-string instead.', 20, 2),
  ('mission-ai-python-for-intelligence-01-o2-c1', 'solution', 'print("Estimated rows: " + row_count) is the crash -- fix it with print("Estimated rows: " + str(row_count)) or an f-string like print(f"Estimated rows: {row_count}").', 30, 3),

  ('mission-ai-python-for-intelligence-02-o1-c1', 'orientation', 'row is a dictionary. events is a list. One of these lines calls a dictionary the way you would call a list.', 10, 1),
  ('mission-ai-python-for-intelligence-02-o1-c1', 'solution', 'print(row[0]) is the bug -- row is keyed by strings like event and timestamp, not by integer position. It needs row["event"] or similar.', 20, 2),
  ('mission-ai-python-for-intelligence-02-o2-c1', 'orientation', 'Ask whether you reach the value by counting position, or by naming it directly.', 10, 1),
  ('mission-ai-python-for-intelligence-02-o2-c1', 'solution', 'List: accessed by position, can hold duplicates. Dictionary: accessed by a named key, and each key must be unique.', 20, 2),

  ('mission-ai-python-for-intelligence-03-o1-c1', 'orientation', 'average_response_ms runs completely, but the value calling code receives back is None. Something inside never sends its result out.', 10, 1),
  ('mission-ai-python-for-intelligence-03-o1-c1', 'concept', 'print only displays a value on the screen. It does not hand that value back to whatever called the function -- return does that.', 20, 2),
  ('mission-ai-python-for-intelligence-03-o1-c1', 'solution', '    print(total / count) is the bug -- change it to return total / count so average_response_ms actually hands its result back to the caller.', 30, 3),
  ('mission-ai-python-for-intelligence-03-o2-c1', 'orientation', 'Look at where times is written -- inside the function''s own definition line, or at the call site.', 10, 1),
  ('mission-ai-python-for-intelligence-03-o2-c1', 'solution', 'times is a parameter, the placeholder name declared in the function signature. The actual list handed in at the call site is the argument.', 20, 2),

  ('mission-ai-python-for-intelligence-04-o1-c1', 'orientation', 'response_times prints a shape and handles response_times * 2 fine. One later line assumes it can grow the array the way a list grows.', 10, 1),
  ('mission-ai-python-for-intelligence-04-o1-c1', 'concept', 'Lists can grow with .append() because they are flexible containers. NumPy arrays have a fixed size in memory -- there is no .append method on them at all.', 20, 2),
  ('mission-ai-python-for-intelligence-04-o1-c1', 'solution', 'response_times.append(133) raises an AttributeError -- growing an array means np.append(response_times, 133), which returns a new array instead of changing this one in place.', 30, 3),
  ('mission-ai-python-for-intelligence-04-o2-c1', 'orientation', 'Match each call to the single thing it actually reports or builds.', 10, 1),
  ('mission-ai-python-for-intelligence-04-o2-c1', 'solution', 'np.array converts a list into an array. .shape reports dimension lengths. .dtype reports the stored type. np.zeros creates a new zero-filled array.', 20, 2),

  ('mission-ai-python-for-intelligence-05-o1-c1', 'orientation', 'reshape can only rearrange the elements that already exist -- it cannot create new ones.', 10, 1),
  ('mission-ai-python-for-intelligence-05-o1-c1', 'solution', 'broken = log_sample.reshape(2, 4) is the bug -- 2 times 4 is 8, but log_sample only holds 6 elements.', 20, 2),
  ('mission-ai-python-for-intelligence-05-o2-c1', 'orientation', 'The first number in a shape is the row count, the second is the column count.', 10, 1),
  ('mission-ai-python-for-intelligence-05-o2-c1', 'solution', 'Shape (1000, 4) means 1000 rows, each with 4 columns.', 20, 2),

  ('mission-ai-python-for-intelligence-06-o1-c1', 'orientation', 'response_sec is created with the right length, four elements, but the loop still crashes with an IndexError.', 10, 1),
  ('mission-ai-python-for-intelligence-06-o1-c1', 'concept', 'range(len(response_ms) + 1) counts one step too far -- valid indices only run from 0 up to len(response_ms) - 1.', 20, 2),
  ('mission-ai-python-for-intelligence-06-o1-c1', 'solution', 'for i in range(len(response_ms) + 1): is the bug -- it should be range(len(response_ms)). The vectorized version skips this entirely: response_sec = response_ms / 1000.', 30, 3),
  ('mission-ai-python-for-intelligence-06-o2-c1', 'orientation', 'Think about what changes: the number of lines of code, or how the operation actually runs underneath.', 10, 1),
  ('mission-ai-python-for-intelligence-06-o2-c1', 'solution', 'Vectorization means applying an operation to an entire array at once, letting NumPy run the loop internally instead of looping in plain Python.', 20, 2),

  ('mission-ai-python-for-intelligence-07-o1-c1', 'orientation', 'response_ms and baseline are both NumPy arrays, but subtracting them does not just work here.', 10, 1),
  ('mission-ai-python-for-intelligence-07-o1-c1', 'concept', 'Broadcasting only lines up two arrays automatically when their shapes match, or one of the mismatched dimensions is exactly 1. Two different lengths that are both greater than 1 cannot broadcast.', 20, 2),
  ('mission-ai-python-for-intelligence-07-o1-c1', 'solution', 'adjusted = response_ms - baseline raises a ValueError -- response_ms has shape (4,) and baseline has shape (2,), and neither condition for broadcasting is met.', 30, 3),
  ('mission-ai-python-for-intelligence-07-o2-c1', 'orientation', 'Compare dimensions from the rightmost one inward.', 10, 1),
  ('mission-ai-python-for-intelligence-07-o2-c1', 'solution', 'Two dimensions can broadcast together when they are equal, or when at least one of them is exactly 1.', 20, 2),

  ('mission-ai-python-for-intelligence-08-o1-c1', 'orientation', 'log.columns and log["event"] both work fine. The last line calls something that does not exist on a DataFrame.', 10, 1),
  ('mission-ai-python-for-intelligence-08-o1-c1', 'solution', 'print(log.rows) is the bug -- DataFrames have no .rows attribute. Use len(log) for the row count or log.index for the row labels.', 20, 2),
  ('mission-ai-python-for-intelligence-08-o2-c1', 'orientation', 'Match each call to the single thing it actually returns.', 10, 1),
  ('mission-ai-python-for-intelligence-08-o2-c1', 'solution', 'pd.DataFrame builds the table. .columns lists column names. log["event"] returns one column as a Series. .head() previews the first rows.', 20, 2),

  ('mission-ai-python-for-intelligence-09-o1-c1', 'orientation', 'queries filters correctly. The very next filter, meant to be stricter, crashes instead.', 10, 1),
  ('mission-ai-python-for-intelligence-09-o1-c1', 'concept', 'Python''s and/or only work on single True or False values. log["response_ms"] > 100 produces a whole Series of them, one per row, and Python cannot collapse that into a single answer.', 20, 2),
  ('mission-ai-python-for-intelligence-09-o1-c1', 'solution', 'slow = log[log["response_ms"] > 100 and log["event"] == "query"] is the bug -- combining boolean masks in pandas needs the & operator with each condition parenthesized: (log["response_ms"] > 100) & (log["event"] == "query").', 30, 3),
  ('mission-ai-python-for-intelligence-09-o2-c1', 'orientation', 'Think about what > 100 produces before it is used to index anything.', 10, 1),
  ('mission-ai-python-for-intelligence-09-o2-c1', 'solution', 'log["response_ms"] > 100 produces a Series of True and False, one per row. Indexing the DataFrame with that Series keeps only the rows where the value is True.', 20, 2),

  ('mission-ai-python-for-intelligence-10-o1-c1', 'orientation', 'Two groupby calls appear here. Read both spellings carefully.', 10, 1),
  ('mission-ai-python-for-intelligence-10-o1-c1', 'solution', 'counts = log.groupbi("event")["response_ms"].count() is the bug -- groupbi is misspelled and will raise an AttributeError. It needs to be groupby.', 20, 2),
  ('mission-ai-python-for-intelligence-10-o2-c1', 'orientation', 'mean is being computed after the table was already split by a column''s values.', 10, 1),
  ('mission-ai-python-for-intelligence-10-o2-c1', 'solution', 'log.groupby("event")["response_ms"].mean() computes the average response_ms separately within each distinct value of event, not one overall average.', 20, 2),

  ('mission-ai-python-for-intelligence-11-o1-c1', 'orientation', 'Think about what happens if two different people run the exact same sampling code.', 10, 1),
  ('mission-ai-python-for-intelligence-11-o1-c1', 'solution', 'Without a fixed seed, log.sample() draws a different random subset every run, so nobody, including you later, can verify or rebuild the same result.', 20, 2),
  ('mission-ai-python-for-intelligence-11-o2-c1', 'orientation', 'np.random.seed has to run before the random operation it is meant to control.', 10, 1),
  ('mission-ai-python-for-intelligence-11-o2-c1', 'solution', 'np.random.seed(42) is misplaced -- it needs to run before sample = log.sample(n=3), not after. As written, the sample was already drawn randomly before the seed did anything.', 20, 2),

  ('mission-ai-python-for-intelligence-12-o1-c1', 'orientation', 'File size and the column list do not by themselves prove anything about row count or duration.', 10, 1),
  ('mission-ai-python-for-intelligence-12-o1-c1', 'solution', 'e1: log.shape reporting 1,247,003 rows is the direct count, and that number alone is far beyond what even six hours of heavy interaction traffic could produce.', 20, 2),
  ('mission-ai-python-for-intelligence-12-o2-c1', 'orientation', 'The minimum and maximum timestamps alone do not tell you the duration -- something has to subtract them.', 10, 1),
  ('mission-ai-python-for-intelligence-12-o2-c1', 'solution', 'span = log["timestamp"].max() - log["timestamp"].min() computes the actual elapsed time the log covers, and it comes out far larger than six hours.', 20, 2),
  ('mission-ai-python-for-intelligence-12-o3-c1', 'orientation', 'A duplication bug would leave a fingerprint in the session IDs and timestamps -- repeated blocks, identical values, something that does not look like real sequential activity.', 10, 1),
  ('mission-ai-python-for-intelligence-12-o3-c1', 'solution', 'a: distinct, monotonically increasing session IDs and timestamps across the whole log rule out a duplication bug -- this looks like genuine sequential activity, not a repeated block.', 20, 2),
  ('mission-ai-python-for-intelligence-12-o4-c1', 'orientation', 'Look at what all three findings support together, not just as separate facts.', 15, 1),
  ('mission-ai-python-for-intelligence-12-o4-c1', 'solution', 'The row count is real, the timeline is real, and it is not a duplication artifact -- Echo''''s interaction log genuinely spans far longer than the six hours anyone thought it had been active. Reading the data raised more questions than it answered, and answering them means learning the actual mathematical language every model, including Echo, is built from.', 25, 2);
