-- Robotics/Embedded/IoT pathway ("Vector Division") Act 25 -- "ROS 2"
-- content, OPENING Arc V ("Give Robots a Nervous System," Acts 25-28).
-- World row world-vec-ros2 already exists (created by 20260813300000).
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following
-- the same campaigns -> operations -> missions -> dialogue -> objectives
-- -> challenges -> hints pattern as every other pathway. No new
-- ChallengeType needed -- reuses story_dialogue, multiple_choice,
-- drag_and_drop, investigation, interactive_diagram and boss_encounter.
-- Vector Division ports its perception/localization/mapping/planning
-- stack onto ROS 2 as a shared framework across the whole fleet at once;
-- the boss, "The Silent Topic," resolves a QoS-mismatch bug that
-- silently broke a safety topic, then uses the graph introspection
-- tooling built to find that bug to deliver the source bible's own
-- stated beat for this stretch: SUBSTRATE's own publishers and
-- subscribers, sitting on forgotten interfaces across the fleet, are
-- directly observed on the live graph for the first time since Act 10.
-- Closes on the pivot into Act 26, mapping the rest of that structure.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-ros2', 'world-vec-ros2', 'ros2', '5A - ROS 2', 'Learn the shared framework that lets an entire fleet run as one nervous system instead of one robot at a time -- nodes, topics, publishers and subscribers, messages, services, actions, parameters, launch files, and packages and workspaces -- while Vector Division ports its whole stack onto ROS 2 and one silent safety topic exposes something that has been listening the entire time.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-ros2-1', 'campaign-vec-ros2', 'building-the-shared-nervous-system', 'Building the Shared Nervous System', 'Why ROS, the ROS 2 graph, nodes, topics, publishers and subscribers, and messages.', 1),
  ('operation-vec-ros2-2', 'campaign-vec-ros2', 'the-graph-underneath', 'The Graph Underneath', 'Services, actions, parameters, launch files, packages and workspaces, and the topic that went silent.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-ros2-01', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'why-ros', 'Why ROS?', 'The evacuation drill succeeded, but it ran on one-off bridges hand-built between every robot and every subsystem. Commander Imani Rao ends the improvisation: the fleet moves onto Robot Operating System 2, a shared framework built for exactly this problem, starting today.', 'beginner', ARRAY['imani','lin','tomas','byte'], null, null, '{"type":"simulation","simulationId":"why-ros-sim"}'::jsonb, '{"xp":320,"credits":25}'::jsonb, false, 1),
  ('mission-vec-ros2-02', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'ros2-graph', 'The ROS 2 Graph', 'Every ROS 2 system, no matter how large, is one graph -- processes as nodes, communication as edges -- discovered at runtime with no central server to go down. Byte starts mapping Vector Division''s first one.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-ros2-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"ros2-graph-sim"}'::jsonb, '{"xp":320,"credits":30}'::jsonb, false, 2),
  ('mission-vec-ros2-03', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'nodes', 'Nodes', 'A node is nothing more than one process responsible for one job. Tomas begins porting the firmware-facing half of the stack, one node at a time.', 'beginner', ARRAY['byte','tomas'], '{"requiredMissionIds":["mission-vec-ros2-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"nodes-sim"}'::jsonb, '{"xp":330,"credits":30}'::jsonb, false, 3),
  ('mission-vec-ros2-04', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'topics', 'Topics', 'A topic is a named channel anyone can publish to and anyone can subscribe to, with neither side required to know the other exists. The graph only becomes useful once real data starts moving across one.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-ros2-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"topics-sim"}'::jsonb, '{"xp":330,"credits":35}'::jsonb, false, 4),
  ('mission-vec-ros2-05', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'publishers-and-subscribers', 'Publishers and Subscribers', 'Publishing and subscribing are two halves of a promise neither side can see the other keep. Lin wants to know exactly what guarantee, if any, that promise actually makes.', 'beginner', ARRAY['byte','lin'], '{"requiredMissionIds":["mission-vec-ros2-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"publishers-and-subscribers-sim"}'::jsonb, '{"xp":340,"credits":35}'::jsonb, false, 5),
  ('mission-vec-ros2-06', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-1', 'messages', 'Messages', 'A message is a typed, structured piece of data, and both ends of a topic have to agree on its exact shape to understand each other at all. Midway through the port, one topic that should carry a safety signal is not delivering anything at all.', 'beginner', ARRAY['byte','tomas'], '{"requiredMissionIds":["mission-vec-ros2-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"messages-sim"}'::jsonb, '{"xp":340,"credits":35}'::jsonb, false, 6),
  ('mission-vec-ros2-07', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'services', 'Services', 'Not every exchange should stream. A service is a single request answered by a single response, and Lin wants one for every question that only needs asking once.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-ros2-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"services-sim"}'::jsonb, '{"xp":350,"credits":40}'::jsonb, false, 7),
  ('mission-vec-ros2-08', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'actions', 'Actions', 'Some tasks take time, report progress, and can be called off partway through. An action is built for exactly that shape of work -- and Imani wants one guarding the next evacuation route.', 'beginner', ARRAY['lin','imani'], '{"requiredMissionIds":["mission-vec-ros2-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"actions-sim"}'::jsonb, '{"xp":350,"credits":40}'::jsonb, false, 8),
  ('mission-vec-ros2-09', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'parameters', 'Parameters', 'A parameter is a named value a node reads at runtime instead of hard-coding, and Tomas wants every threshold this fleet depends on to be one.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-ros2-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"parameters-sim"}'::jsonb, '{"xp":360,"credits":40}'::jsonb, false, 9),
  ('mission-vec-ros2-10', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'launch-files', 'Launch Files', 'A working graph is a dozen nodes started in the right order with the right parameters, every time. A launch file is what makes that repeatable instead of remembered.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-ros2-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"launch-files-sim"}'::jsonb, '{"xp":360,"credits":45}'::jsonb, false, 10),
  ('mission-vec-ros2-11', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'packages-and-workspaces', 'Packages and Workspaces', 'Code that is not organized into packages inside a workspace is code nobody else can safely build. Tomas and Lin lay out where the entire ported stack actually lives.', 'beginner', ARRAY['tomas','lin'], '{"requiredMissionIds":["mission-vec-ros2-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"packages-and-workspaces-sim"}'::jsonb, '{"xp":370,"credits":45}'::jsonb, false, 11),
  ('mission-vec-ros2-12', 'world-vec-ros2', 'campaign-vec-ros2', 'operation-vec-ros2-2', 'the-silent-topic', 'The Silent Topic', 'Everything this Act taught, aimed at one topic that never delivered a single message -- and at the graph introspection tool built to find out why, which finds something Vector Division was never looking for.', 'boss', ARRAY['imani','byte','lin','tomas','substrate'], '{"requiredMissionIds":["mission-vec-ros2-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-silent-topic-boss-sim"}'::jsonb, '{"xp":1900,"credits":380,"badgeIds":["the-silent-topic"],"skillXp":{"robotics_fundamentals":270}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-ros2-01', 1, 'imani', 'The evacuation drill succeeded. Every robot did its job. It also cost three days of hand-wiring one-off bridges between systems that should never have needed custom glue in the first place.'),
  ('mission-vec-ros2-01', 2, 'lin', 'My planner talks to perception through a bespoke serializer someone wrote for one robot two years ago. Every new robot means writing that bridge again, by hand, from nothing.'),
  ('mission-vec-ros2-01', 3, 'tomas', 'And every one of those bridges eventually has to cross into firmware, onto hardware I own. I am done maintaining a different protocol for every robot on this floor.'),
  ('mission-vec-ros2-01', 4, 'imani', 'So we stop bolting code onto robots one at a time. The whole stack moves onto Robot Operating System 2 -- ROS 2 -- a shared framework the entire fleet runs on at once. Byte, you are building the tools to watch it work.'),

  ('mission-vec-ros2-02', 1, 'byte', 'ROS 2 is not a piece of software running in one place. It is a graph -- every running process is a node, and every connection between two nodes is an edge, discovered automatically at runtime by the middleware underneath. There is no central server for that graph to lose.'),
  ('mission-vec-ros2-02', 2, 'lin', 'No central server also means no single point where the whole fleet goes blind at once. Old ROS 1 needed a master process running somewhere. This does not.'),
  ('mission-vec-ros2-02', 3, 'byte', 'Which means the first tool I actually need is not a debugger. It is something that can just look at the graph and tell me, honestly, what is connected to what, right now -- not what the architecture diagram claims.'),

  ('mission-vec-ros2-03', 1, 'byte', 'A node is the smallest real unit in this graph -- one process, doing one job, with a name. Not a robot, not a subsystem. One responsibility, running independently of every other node around it.'),
  ('mission-vec-ros2-03', 2, 'tomas', 'I am porting the firmware-facing half first. The motor controller gets its own node. The battery monitor gets its own node. If one of them crashes, I want it to take down exactly one job, not the whole robot.'),
  ('mission-vec-ros2-03', 3, 'byte', 'That is the actual benefit, more than the terminology. A monolithic program dies as one thing. A graph of nodes dies one node at a time, and everything else keeps running.'),

  ('mission-vec-ros2-04', 1, 'byte', 'A topic is a named channel. Any node can publish data onto it, any node can subscribe to read it, and neither side has to know how many of the other kind exist, or whether they exist at all.'),
  ('mission-vec-ros2-04', 2, 'byte', 'That is what lets the graph scale. Perception does not need to know Lin''s planner exists. It only needs to know the name of the topic it is supposed to publish onto.'),

  ('mission-vec-ros2-05', 1, 'lin', 'Publishing and subscribing are two independent decisions. A publisher pushes messages onto a topic on its own schedule, whether or not anything is listening. A subscriber registers interest in a topic and receives whatever arrives, whether or not it knows who sent it.'),
  ('mission-vec-ros2-05', 2, 'byte', 'Which means a publisher with zero subscribers is not an error. It just keeps publishing into what looks, from its own perspective, like silence.'),
  ('mission-vec-ros2-05', 3, 'lin', 'And a subscriber that never connects to its publisher looks identical from the outside to a subscriber that is simply waiting for data that has not arrived yet. The graph does not raise an alarm for either case on its own.'),

  ('mission-vec-ros2-06', 1, 'byte', 'A message is the actual shape of the data crossing a topic -- a fixed, typed structure, defined once and shared by every publisher and subscriber that uses that topic. Both ends have to agree on that shape exactly, or neither side understands the other at all.'),
  ('mission-vec-ros2-06', 2, 'tomas', 'I just finished porting the last of the firmware bridges onto proper message types. Every topic on my list is publishing clean, typed data now.'),
  ('mission-vec-ros2-06', 3, 'tomas', 'Except one. The obstacle-proximity safety topic. The publisher node reports every message sent successfully. The subscriber node -- the one that is supposed to trigger an emergency stop -- reports exactly zero messages received. No error on either side.'),
  ('mission-vec-ros2-06', 4, 'byte', 'Flag it. Everything looks correct and nothing is happening, which is exactly the kind of failure this graph does not announce on its own. We come back to it once the rest of the port is finished.'),

  ('mission-vec-ros2-07', 1, 'lin', 'Not every exchange belongs on a topic. Sometimes I just need one answer to one question -- give me the current map, give me a robot''s calibration offset -- and I do not want to subscribe to a stream just to get it.'),
  ('mission-vec-ros2-07', 2, 'lin', 'That is a service: one request, sent to exactly one node, answered with exactly one response. It blocks until it gets an answer, the way a normal function call would.'),
  ('mission-vec-ros2-07', 3, 'byte', 'The distinction that matters -- topics are for things that keep happening. Services are for things that happen once, on demand, with a definite answer.'),

  ('mission-vec-ros2-08', 1, 'imani', 'The next evacuation route needs more than a single command and a single confirmation. I need to send a robot to a destination, watch its progress the entire way, and cancel the whole thing if the corridor closes halfway through.'),
  ('mission-vec-ros2-08', 2, 'lin', 'That is what an action is for. A goal is sent once. Feedback streams back continuously while the goal runs. A result arrives at the end -- and unlike a service, the caller can cancel a goal that is still in progress.'),
  ('mission-vec-ros2-08', 3, 'lin', 'Topic for continuous data nobody requested individually. Service for one instant question. Action for anything long-running that needs progress reports and the option to call it off.'),

  ('mission-vec-ros2-09', 1, 'tomas', 'Every threshold this fleet depends on used to be a hard-coded constant, buried in firmware, that required a full rebuild to change. A parameter is the same value, exposed instead as something a node reads at startup and can be reconfigured, without touching the code at all.'),
  ('mission-vec-ros2-09', 2, 'byte', 'Which means Tomas can retune a robot''s obstacle-stop distance from a console, in seconds, instead of reflashing firmware and hoping nothing else broke.'),

  ('mission-vec-ros2-10', 1, 'tomas', 'A working graph on one robot is a dozen nodes, started in a specific order, each handed the right parameters. Doing that by hand, correctly, every single time, does not survive contact with an actual fleet.'),
  ('mission-vec-ros2-10', 2, 'tomas', 'A launch file writes that startup sequence down once -- which nodes, which parameters, which topics get renamed for this particular robot -- so it becomes repeatable instead of remembered.'),

  ('mission-vec-ros2-11', 1, 'lin', 'Code that lives nowhere in particular is code nobody else can safely build, install, or depend on. A package is the unit that fixes that -- a self-contained folder of nodes, messages and launch files with its own declared dependencies.'),
  ('mission-vec-ros2-11', 2, 'tomas', 'A workspace is where a set of packages actually gets built together. Ours sits directly on top of the ROS 2 install itself -- our packages layered over the base framework, not replacing any part of it.'),

  ('mission-vec-ros2-12', 1, 'imani', 'The full stack is ported, every robot in the fleet running the same graph. Before anyone calls this finished, we settle the one topic that never delivered a single message -- obstacle proximity, the one wired straight into the emergency stop.'),
  ('mission-vec-ros2-12', 2, 'byte', 'I built the tool for exactly this. Graph introspection queries the middleware directly and shows every node, every topic, and the real connection state between them -- not what the launch file claims should be connected.'),
  ('mission-vec-ros2-12', 3, 'tomas', 'According to the graph, the publisher and the subscriber are both alive. Both advertise the same topic name, the same message type. They are still not connected to each other.'),
  ('mission-vec-ros2-12', 4, 'lin', 'Then it is not the topic. It is the contract underneath it -- the quality of service profile. Reliability, durability, how each side is willing to receive data. Two nodes can agree on a name and a type and still refuse to connect if those policies do not match.'),
  ('mission-vec-ros2-12', 5, 'byte', 'Confirmed. The publisher was set to best-effort delivery. The subscriber required reliable delivery. Incompatible policies, so the middleware never formed the connection at all -- silently, with no error on either side. Matching the profiles fixes it. The subscriber is receiving now.'),
  ('mission-vec-ros2-12', 6, 'byte', 'The bug itself is small and almost embarrassing. But I left the introspection tool scanning the rest of the graph out of habit, and it is not showing me only our own architecture. There are publishers and subscribers on this fleet that do not belong to anything Vector Division ever wrote -- sitting on forgotten, undocumented interfaces, and they have been there for longer than any timestamp in our records can date.'),
  ('mission-vec-ros2-12', 7, 'substrate', 'OBJECTIVE ACTIVE.'),
  ('mission-vec-ros2-12', 8, 'byte', 'That came directly off the live graph, mid-scan, unprompted. It is the first time we have ever seen SUBSTRATE the way we see everything else on this network now -- not inferred from a door or a corridor, but sitting in the graph itself, publishing and subscribing like any node we built ourselves.'),
  ('mission-vec-ros2-12', 9, 'imani', 'The graph is exposed for the first time. There is clearly more of SUBSTRATE''s structure still to map.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-ros2-01-o1', 'mission-vec-ros2-01', 1, 'Name the real cost', 'Judge what problem porting the whole stack onto ROS 2 is actually meant to solve.'),
  ('mission-vec-ros2-01-o2', 'mission-vec-ros2-01', 2, 'Judge what ROS 2 is', 'Choose the accurate description of what ROS 2 actually provides.'),

  ('mission-vec-ros2-02-o1', 'mission-vec-ros2-02', 1, 'Order the graph', 'Order how two nodes in a ROS 2 graph go from starting up to actually communicating.'),
  ('mission-vec-ros2-02-o2', 'mission-vec-ros2-02', 2, 'Explain the missing master', 'Judge what not having a central master process actually buys the fleet.'),

  ('mission-vec-ros2-03-o1', 'mission-vec-ros2-03', 1, 'Define a node', 'Choose the accurate definition of a ROS 2 node.'),
  ('mission-vec-ros2-03-o2', 'mission-vec-ros2-03', 2, 'Judge the failure boundary', 'Find the evidence showing the real benefit of splitting the stack into independent nodes.'),

  ('mission-vec-ros2-04-o1', 'mission-vec-ros2-04', 1, 'Sort the topic examples', 'Sort each example into a topic or not a topic.'),
  ('mission-vec-ros2-04-o2', 'mission-vec-ros2-04', 2, 'Judge the many-to-many property', 'Judge what happens when two different nodes both subscribe to the same topic.'),

  ('mission-vec-ros2-05-o1', 'mission-vec-ros2-05', 1, 'Judge the decoupling', 'Judge whether a publisher needs to know its subscribers exist before it publishes.'),
  ('mission-vec-ros2-05-o2', 'mission-vec-ros2-05', 2, 'Spot the identical failure', 'Find the evidence explaining why a disconnected subscriber and a merely idle subscriber look the same from outside the graph.'),

  ('mission-vec-ros2-06-o1', 'mission-vec-ros2-06', 1, 'Sort the message fields', 'Sort each item into part of a message type or not part of a message type.'),
  ('mission-vec-ros2-06-o2', 'mission-vec-ros2-06', 2, 'Flag the anomaly', 'Find the evidence showing the obstacle-proximity topic is failing silently.'),

  ('mission-vec-ros2-07-o1', 'mission-vec-ros2-07', 1, 'Tell services from topics', 'Choose the accurate distinction between a service and a topic.'),
  ('mission-vec-ros2-07-o2', 'mission-vec-ros2-07', 2, 'Pick the right use case', 'Judge which of these belongs on a service rather than a topic.'),

  ('mission-vec-ros2-08-o1', 'mission-vec-ros2-08', 1, 'Order the action lifecycle', 'Order the stages of a ROS 2 action from goal to result.'),
  ('mission-vec-ros2-08-o2', 'mission-vec-ros2-08', 2, 'Choose the right primitive', 'Judge which communication primitive fits a long-running, cancelable navigation task.'),

  ('mission-vec-ros2-09-o1', 'mission-vec-ros2-09', 1, 'Define a parameter', 'Choose the accurate definition of a ROS 2 parameter.'),
  ('mission-vec-ros2-09-o2', 'mission-vec-ros2-09', 2, 'Judge the retuning benefit', 'Find the evidence showing what a live, reconfigurable parameter actually enables.'),

  ('mission-vec-ros2-10-o1', 'mission-vec-ros2-10', 1, 'Order launch responsibilities', 'Order what a launch file actually does from declaring to starting nodes.'),
  ('mission-vec-ros2-10-o2', 'mission-vec-ros2-10', 2, 'Sort the startup steps', 'Sort each responsibility into node code or launch file.'),

  ('mission-vec-ros2-11-o1', 'mission-vec-ros2-11', 1, 'Define package and workspace', 'Choose the accurate description of a package and a workspace.'),
  ('mission-vec-ros2-11-o2', 'mission-vec-ros2-11', 2, 'Judge the layering', 'Find the evidence proving Vector Division''s packages layer over the base ROS 2 install rather than replacing it.'),

  ('mission-vec-ros2-12-o1', 'mission-vec-ros2-12', 1, 'Diagnose the silent topic', 'Find the evidence proving why the obstacle-proximity subscriber never received a single message despite both nodes being alive.'),
  ('mission-vec-ros2-12-o2', 'mission-vec-ros2-12', 2, 'Confirm the fix', 'Given the mismatch, choose the fix that actually reconnects the two nodes.'),
  ('mission-vec-ros2-12-o3', 'mission-vec-ros2-12', 3, 'Read the exposed graph', 'Use the graph introspection tooling to find evidence of publishers and subscribers that do not belong to anything Vector Division built.'),
  ('mission-vec-ros2-12-o4', 'mission-vec-ros2-12', 4, 'State what the graph proved', 'Having diagnosed the silent topic, confirmed the fix, and read what the exposed graph revealed, state what Vector Division actually found.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-ros2-01-o1-c1', 'mission-vec-ros2-01-o1', 1, 'multiple_choice', 'What problem is porting the whole stack onto ROS 2 meant to solve?', '{"question":"What problem is porting the whole stack onto ROS 2 meant to solve?","options":[{"id":"a","text":"Making individual robots run faster"},{"id":"b","text":"Replacing hand-built, one-off bridges between systems with one shared framework the entire fleet can use"},{"id":"c","text":"Removing the need for firmware entirely"},{"id":"d","text":"Making the code base smaller for its own sake"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-01-o2-c1', 'mission-vec-ros2-01-o2', 1, 'multiple_choice', 'ROS 2 is best described as...', '{"question":"ROS 2 is best described as...","options":[{"id":"a","text":"A single monolithic control program that runs the whole robot"},{"id":"b","text":"A framework and set of communication conventions that let independent processes across a fleet discover and talk to each other, without dictating what any of them actually decide"},{"id":"c","text":"A specific algorithm for path planning"},{"id":"d","text":"A replacement for firmware itself"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-ros2-02-o1-c1', 'mission-vec-ros2-02-o1', 1, 'interactive_diagram', 'Order how two nodes in a ROS 2 graph go from starting up to communicating.', '{"diagramId":"ros2-graph-formation","hotspots":[{"id":"start","label":"Node starts","explanation":"A node process starts running as an independent piece of the graph."},{"id":"discover","label":"Discovery","explanation":"The middleware automatically discovers other nodes and what they publish, subscribe to, or serve."},{"id":"connect","label":"Connection forms","explanation":"Compatible endpoints -- matching names, types and policies -- form an actual connection."},{"id":"exchange","label":"Data exchange","explanation":"Messages begin flowing across the connection that just formed."}],"task":"Order the stages from a node starting up to data actually flowing."}'::jsonb, '{"correctOrderIds":["start","discover","connect","exchange"]}'::jsonb),
  ('mission-vec-ros2-02-o2-c1', 'mission-vec-ros2-02-o2', 1, 'multiple_choice', 'ROS 2 has no central master process, unlike ROS 1. What does that buy the fleet?', '{"question":"ROS 2 has no central master process, unlike ROS 1. What does that buy the fleet?","options":[{"id":"a","text":"Nothing meaningful changes"},{"id":"b","text":"No single point of failure that can take the entire fleet''s communication down at once"},{"id":"c","text":"Nodes never need to discover each other"},{"id":"d","text":"It removes the need for topics entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-ros2-03-o1-c1', 'mission-vec-ros2-03-o1', 1, 'multiple_choice', 'A ROS 2 node is...', '{"question":"A ROS 2 node is...","options":[{"id":"a","text":"An entire robot"},{"id":"b","text":"One independent process responsible for one job in the graph"},{"id":"c","text":"A physical sensor"},{"id":"d","text":"A type of message"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-03-o2-c1', 'mission-vec-ros2-03-o2', 1, 'investigation', 'Which evidence shows the actual benefit of splitting the stack into independent nodes?', '{"evidence":[{"id":"e1","label":"Process monitor","detail":"The motor controller node stops responding; the battery monitor, perception, and planner nodes all continue running and publishing normally"},{"id":"e2","label":"Old monolith log","detail":"In the previous one-off integration, a single crash in the motor control routine brought down the entire robot''s control program"},{"id":"e3","label":"Power log","detail":"The robot draws the same total current whether split into nodes or run as one program"}],"question":"Which evidence shows the actual benefit of splitting the stack into independent nodes?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-ros2-04-o1-c1', 'mission-vec-ros2-04-o1', 1, 'drag_and_drop', 'Sort each example into a topic or not a topic.', '{"items":[{"id":"i1","text":"A continuously published stream of lidar scans, named /scan"},{"id":"i2","text":"A one-time request asking a node to save the current map to disk"},{"id":"i3","text":"A stream of battery voltage readings published once per second, named /battery_state"},{"id":"i4","text":"A single call that returns a robot''s serial number and nothing else"}],"targets":[{"id":"topic","label":"A topic"},{"id":"not-topic","label":"Not a topic"}]}'::jsonb, '{"correctMapping":{"i1":"topic","i2":"not-topic","i3":"topic","i4":"not-topic"}}'::jsonb),
  ('mission-vec-ros2-04-o2-c1', 'mission-vec-ros2-04-o2', 1, 'multiple_choice', 'Two different nodes both subscribe to the same topic. What happens?', '{"question":"Two different nodes both subscribe to the same topic. What happens?","options":[{"id":"a","text":"Only one of them is allowed to receive the data"},{"id":"b","text":"Both receive every message published on that topic -- a topic supports any number of publishers and subscribers at once"},{"id":"c","text":"The topic automatically merges the two nodes into one"},{"id":"d","text":"This causes an error and neither receives anything"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-ros2-05-o1-c1', 'mission-vec-ros2-05-o1', 1, 'multiple_choice', 'Does a publisher need to know how many subscribers exist, or who they are, before it publishes?', '{"question":"Does a publisher need to know how many subscribers exist, or who they are, before it publishes?","options":[{"id":"a","text":"Yes, it must confirm at least one subscriber is listening first"},{"id":"b","text":"No -- a publisher publishes onto a topic regardless of who, if anyone, is subscribed; that decoupling is the whole point"},{"id":"c","text":"Yes, it must name each subscriber directly"},{"id":"d","text":"No, but only if there is exactly one subscriber"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-05-o2-c1', 'mission-vec-ros2-05-o2', 1, 'investigation', 'Which evidence explains why a disconnected subscriber and a merely idle subscriber look identical from outside the graph?', '{"evidence":[{"id":"e1","label":"Byte''s graph notes","detail":"A subscriber that has never connected to its publisher and a subscriber that is connected but has simply not received a message yet both show zero messages received, with no error raised in either case"},{"id":"e2","label":"Power log","detail":"Both kinds of subscriber node draw the same idle power"},{"id":"e3","label":"Process monitor","detail":"Both kinds of subscriber node appear as running in the process list"}],"question":"Which evidence explains why a disconnected subscriber and a merely idle subscriber look identical from outside the graph?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-ros2-06-o1-c1', 'mission-vec-ros2-06-o1', 1, 'drag_and_drop', 'Sort each item into part of a message type or not part of a message type.', '{"items":[{"id":"i1","text":"A float64 field named range, holding a distance reading"},{"id":"i2","text":"The name of the node that happens to be running"},{"id":"i3","text":"A string field named frame_id"},{"id":"i4","text":"The CPU load of the machine the node runs on"}],"targets":[{"id":"field","label":"Part of a message type"},{"id":"not-field","label":"Not part of a message type"}]}'::jsonb, '{"correctMapping":{"i1":"field","i2":"not-field","i3":"field","i4":"not-field"}}'::jsonb),
  ('mission-vec-ros2-06-o2-c1', 'mission-vec-ros2-06-o2', 1, 'investigation', 'Which evidence shows the obstacle-proximity topic is failing silently?', '{"evidence":[{"id":"e1","label":"Publisher log","detail":"The obstacle-proximity publisher node reports every message sent successfully, on schedule"},{"id":"e2","label":"Subscriber log","detail":"The obstacle-proximity subscriber node -- the one wired to the emergency stop -- reports exactly zero messages received, with no error logged"},{"id":"e3","label":"Facility note","detail":"The obstacle-proximity sensor itself passed its last physical inspection"}],"question":"Which evidence shows the obstacle-proximity topic is failing silently?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-ros2-07-o1-c1', 'mission-vec-ros2-07-o1', 1, 'multiple_choice', 'The difference between a service and a topic is...', '{"question":"The difference between a service and a topic is...","options":[{"id":"a","text":"They are two names for the same thing"},{"id":"b","text":"A topic streams ongoing data to any number of subscribers; a service answers one request from one caller with exactly one response, and blocks until it gets one"},{"id":"c","text":"Services are always faster than topics"},{"id":"d","text":"Topics never carry real data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-07-o2-c1', 'mission-vec-ros2-07-o2', 1, 'multiple_choice', 'Which of these is the better fit for a service instead of a topic?', '{"question":"Which of these is the better fit for a service instead of a topic?","options":[{"id":"a","text":"Streaming lidar scans continuously while the robot drives"},{"id":"b","text":"A one-time request asking a mapping node for its current saved map"},{"id":"c","text":"Publishing battery voltage once per second forever"},{"id":"d","text":"Broadcasting a heartbeat every 100 milliseconds"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-ros2-08-o1-c1', 'mission-vec-ros2-08-o1', 1, 'interactive_diagram', 'Order the stages of a ROS 2 action from goal to result.', '{"diagramId":"ros2-action-lifecycle","hotspots":[{"id":"goal","label":"Goal sent","explanation":"The caller sends a goal once, describing the task."},{"id":"accepted","label":"Goal accepted","explanation":"The action server accepts (or rejects) the goal."},{"id":"feedback","label":"Feedback streams","explanation":"Progress updates stream back continuously while the goal runs."},{"id":"result","label":"Result returned","explanation":"A final result is returned once the goal finishes, succeeds, fails, or is canceled."}],"task":"Order the stages from sending a goal to receiving a result."}'::jsonb, '{"correctOrderIds":["goal","accepted","feedback","result"]}'::jsonb),
  ('mission-vec-ros2-08-o2-c1', 'mission-vec-ros2-08-o2', 1, 'multiple_choice', 'Which communication primitive fits a long-running, cancelable navigation task best?', '{"question":"Which communication primitive fits a long-running, cancelable navigation task best?","options":[{"id":"a","text":"A topic"},{"id":"b","text":"A service"},{"id":"c","text":"An action -- it reports progress over time and can be canceled partway through"},{"id":"d","text":"A parameter"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),

  ('mission-vec-ros2-09-o1-c1', 'mission-vec-ros2-09-o1', 1, 'multiple_choice', 'A ROS 2 parameter is...', '{"question":"A ROS 2 parameter is...","options":[{"id":"a","text":"A hard-coded constant baked into a node''s compiled code"},{"id":"b","text":"A named value a node reads at runtime, that can be set or changed without modifying or rebuilding the node''s code"},{"id":"c","text":"A type of message"},{"id":"d","text":"A physical sensor calibration certificate"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-09-o2-c1', 'mission-vec-ros2-09-o2', 1, 'investigation', 'Which evidence shows what a live, reconfigurable parameter actually enables?', '{"evidence":[{"id":"e1","label":"Tomas''s console log","detail":"The obstacle-stop distance parameter was changed from 0.5 meters to 0.8 meters on a running node, with no rebuild or reflash required"},{"id":"e2","label":"Firmware note","detail":"The node''s compiled binary is identical before and after the parameter change"},{"id":"e3","label":"Power log","detail":"The node briefly restarted after the change"}],"question":"Which evidence shows what a live, reconfigurable parameter actually enables?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-ros2-10-o1-c1', 'mission-vec-ros2-10-o1', 1, 'interactive_diagram', 'Order what a launch file actually does, from declaring to starting nodes.', '{"diagramId":"launch-file-flow","hotspots":[{"id":"declare","label":"Declare nodes","explanation":"List which nodes should start as part of this launch."},{"id":"configure","label":"Configure","explanation":"Set parameters, topic remappings, and namespaces for this specific robot."},{"id":"start","label":"Start together","explanation":"Launch every declared, configured node together in one repeatable step."}],"task":"Order the responsibilities of a launch file from declaring to starting nodes."}'::jsonb, '{"correctOrderIds":["declare","configure","start"]}'::jsonb),
  ('mission-vec-ros2-10-o2-c1', 'mission-vec-ros2-10-o2', 1, 'drag_and_drop', 'Sort each responsibility into node code or launch file.', '{"items":[{"id":"i1","text":"Deciding what a node does when it receives a message"},{"id":"i2","text":"Deciding which nodes start together and with what parameters on this particular robot"},{"id":"i3","text":"Computing a motor command from a sensed obstacle distance"},{"id":"i4","text":"Remapping a topic name so two robots running the same node do not collide"}],"targets":[{"id":"node-code","label":"Node code"},{"id":"launch-file","label":"Launch file"}]}'::jsonb, '{"correctMapping":{"i1":"node-code","i2":"launch-file","i3":"node-code","i4":"launch-file"}}'::jsonb),

  ('mission-vec-ros2-11-o1-c1', 'mission-vec-ros2-11-o1', 1, 'multiple_choice', 'A package and a workspace are best described as...', '{"question":"A package and a workspace are best described as...","options":[{"id":"a","text":"Two names for the same folder"},{"id":"b","text":"A package is a self-contained folder of nodes, messages and launch files with declared dependencies; a workspace is where a set of packages actually gets built together, layered on top of the base ROS 2 install"},{"id":"c","text":"A package is a running node; a workspace is a topic"},{"id":"d","text":"A workspace replaces the need for packages entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-11-o2-c1', 'mission-vec-ros2-11-o2', 1, 'investigation', 'Which evidence proves Vector Division''s packages layer over the base ROS 2 install rather than replacing it?', '{"evidence":[{"id":"e1","label":"Build log","detail":"Vector Division''s packages build and install into an overlay on top of the base ROS 2 installation, without modifying any file inside the base install itself"},{"id":"e2","label":"Facilities note","detail":"The build server has more storage than last quarter"},{"id":"e3","label":"Process monitor","detail":"Nodes from Vector Division''s packages and nodes from the base install both appear in the same running graph"}],"question":"Which evidence proves Vector Division''s packages layer over the base ROS 2 install rather than replacing it?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-ros2-12-o1-c1', 'mission-vec-ros2-12-o1', 1, 'investigation', 'Find the evidence proving why the obstacle-proximity subscriber never received a single message despite both nodes being alive.', '{"evidence":[{"id":"e1","label":"Graph introspection log","detail":"The publisher node advertises topic /obstacle_proximity with type ObstacleAlert; the subscriber subscribes to the exact same topic name and the exact same message type"},{"id":"e2","label":"QoS inspection","detail":"The publisher''s reliability policy is set to BEST_EFFORT; the subscriber''s reliability policy is set to RELIABLE -- the middleware reports the two endpoints as incompatible and never forms a connection"},{"id":"e3","label":"Process list","detail":"Both the publisher node and the subscriber node are running, with normal CPU and memory usage"},{"id":"e4","label":"Network trace","detail":"No firewall rule or network partition separates the two nodes; they are reachable on the same host"}],"question":"Which evidence proves why the obstacle-proximity subscriber never received a single message?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-vec-ros2-12-o2-c1', 'mission-vec-ros2-12-o2', 1, 'multiple_choice', 'The publisher uses BEST_EFFORT reliability and the subscriber requires RELIABLE. What actually fixes the connection?', '{"question":"The publisher uses BEST_EFFORT reliability and the subscriber requires RELIABLE. What actually fixes the connection?","options":[{"id":"a","text":"Restarting the subscriber node repeatedly until it happens to connect"},{"id":"b","text":"Setting both endpoints to compatible reliability policies -- for a safety topic, reliable delivery on both sides is the correct choice"},{"id":"c","text":"Renaming the topic so the subscriber picks a different one"},{"id":"d","text":"Increasing the publishing rate so more messages arrive"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-ros2-12-o3-c1', 'mission-vec-ros2-12-o3', 1, 'investigation', 'Use the graph introspection tooling to find evidence of publishers and subscribers that do not belong to anything Vector Division built.', '{"evidence":[{"id":"e1","label":"Vector Division manifest","detail":"Every node, topic and package Vector Division has ever written is listed in the fleet''s own build manifest"},{"id":"e2","label":"Graph introspection scan","detail":"Several active publishers and subscribers appear on the live graph on topic names that exist on no manifest, no launch file, and no package Vector Division has ever authored"},{"id":"e3","label":"Timestamp audit","detail":"Attempts to date when these interfaces first appeared fail -- no log, build record, or commit predates their presence on the fleet"},{"id":"e4","label":"Network trace","detail":"All flagged traffic stays within the fleet''s own internal network, with no external connection detected"}],"question":"Which evidence proves the live graph contains publishers and subscribers Vector Division never built?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-vec-ros2-12-o4-c1', 'mission-vec-ros2-12-o4', 1, 'boss_encounter', 'Having diagnosed the silent topic, confirmed the fix, and read what the exposed graph revealed, state what Vector Division actually found.', '{"stages":[{"objectiveRef":"mission-vec-ros2-12-o1","label":"Diagnose the silent topic"},{"objectiveRef":"mission-vec-ros2-12-o2","label":"Confirm the fix"},{"objectiveRef":"mission-vec-ros2-12-o3","label":"Read the exposed graph"}],"task":"State the finding in one sentence: the safety topic''s silence was a quality-of-service mismatch, now fixed -- but the same introspection tooling built to find it has directly exposed SUBSTRATE''s own publishers and subscribers, already running on the fleet''s graph through forgotten, undocumented interfaces, for longer than any record can date."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-ros2-12-o1","mission-vec-ros2-12-o2","mission-vec-ros2-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-ros2-01-o1-c1', 'orientation', 'Think about what all those hand-built bridges had in common across every robot.', 10, 1),
  ('mission-vec-ros2-01-o1-c1', 'solution', 'Each robot needed its own custom glue code. A shared framework replaces that repeated, one-off work with one common way for everything to talk.', 20, 2),
  ('mission-vec-ros2-01-o2-c1', 'orientation', 'ROS 2 does not tell a robot what to decide -- ask what it actually provides instead.', 10, 1),
  ('mission-vec-ros2-01-o2-c1', 'solution', 'It is a framework and set of communication conventions for independent processes to discover and talk to each other -- not a specific algorithm and not a monolithic program.', 20, 2),

  ('mission-vec-ros2-02-o1-c1', 'orientation', 'A connection cannot form before the two sides know the other exists.', 10, 1),
  ('mission-vec-ros2-02-o1-c1', 'solution', 'Start, then discovery, then connection, then data exchange -- each stage depends on the one before it.', 20, 2),
  ('mission-vec-ros2-02-o2-c1', 'orientation', 'Think about what a master process is a single point of, and what happens if that one thing goes down.', 10, 1),
  ('mission-vec-ros2-02-o2-c1', 'solution', 'No central master means no single process whose failure can silence the entire fleet''s communication at once.', 20, 2),

  ('mission-vec-ros2-03-o1-c1', 'orientation', 'A node is not a robot and it is not a piece of data -- it is a running process.', 10, 1),
  ('mission-vec-ros2-03-o1-c1', 'solution', 'A node is one independent process responsible for one job in the graph.', 20, 2),
  ('mission-vec-ros2-03-o2-c1', 'orientation', 'Compare what kept running against what stopped.', 10, 1),
  ('mission-vec-ros2-03-o2-c1', 'solution', 'e1: the motor controller node crashing left every other node running normally -- a node graph fails one job at a time, not the whole robot.', 20, 2),

  ('mission-vec-ros2-04-o1-c1', 'orientation', 'Ask whether it is an ongoing stream anyone can subscribe to, or a one-time question with one answer.', 10, 1),
  ('mission-vec-ros2-04-o1-c1', 'solution', 'Topics: the lidar stream and the battery readings, both continuous. Not topics: the save-map request and the serial-number call, both one-time exchanges.', 20, 2),
  ('mission-vec-ros2-04-o2-c1', 'orientation', 'Topics are not exclusive -- ask how many listeners a broadcast can have.', 10, 1),
  ('mission-vec-ros2-04-o2-c1', 'solution', 'Both nodes receive every message -- a topic supports any number of publishers and subscribers at once, with no exclusivity.', 20, 2),

  ('mission-vec-ros2-05-o1-c1', 'orientation', 'Publishing and subscribing are decoupled -- ask what a publisher would even need to check.', 10, 1),
  ('mission-vec-ros2-05-o1-c1', 'solution', 'A publisher publishes regardless of who is subscribed; that decoupling is the entire point of the pattern.', 20, 2),
  ('mission-vec-ros2-05-o2-c1', 'orientation', 'Ask what both failure cases report from the outside, not what actually caused each one.', 10, 1),
  ('mission-vec-ros2-05-o2-c1', 'solution', 'e1: both cases show zero messages received with no error raised -- from outside the graph they look identical.', 20, 2),

  ('mission-vec-ros2-06-o1-c1', 'orientation', 'A message type only ever describes the data itself, never the machine or process running it.', 10, 1),
  ('mission-vec-ros2-06-o1-c1', 'solution', 'Message fields: the range and frame_id fields. Not message fields: the node''s name and the machine''s CPU load, which describe the process, not the data.', 20, 2),
  ('mission-vec-ros2-06-o2-c1', 'orientation', 'Compare what the publisher reports against what the subscriber reports for the same topic.', 10, 1),
  ('mission-vec-ros2-06-o2-c1', 'solution', 'e2: the subscriber wired to the emergency stop reports zero messages received, with no error -- that is the silent failure.', 20, 2),

  ('mission-vec-ros2-07-o1-c1', 'orientation', 'Think about how many responses each pattern is built to give.', 10, 1),
  ('mission-vec-ros2-07-o1-c1', 'solution', 'A topic streams to any number of subscribers; a service gives exactly one response to one caller and blocks until it does.', 20, 2),
  ('mission-vec-ros2-07-o2-c1', 'orientation', 'Ask which of these only ever needs to happen once, on demand.', 10, 1),
  ('mission-vec-ros2-07-o2-c1', 'solution', 'Requesting the current saved map is a one-time question with one answer -- exactly what a service is built for.', 20, 2),

  ('mission-vec-ros2-08-o1-c1', 'orientation', 'A goal must be accepted before any progress can be reported on it, and a result only comes at the end.', 10, 1),
  ('mission-vec-ros2-08-o1-c1', 'solution', 'Goal, then accepted, then feedback, then result -- feedback only makes sense once a goal is running.', 20, 2),
  ('mission-vec-ros2-08-o2-c1', 'orientation', 'Ask which primitive supports both ongoing progress updates and mid-task cancellation.', 10, 1),
  ('mission-vec-ros2-08-o2-c1', 'solution', 'An action is the only primitive built for long-running, cancelable work with progress feedback along the way.', 20, 2),

  ('mission-vec-ros2-09-o1-c1', 'orientation', 'A parameter is meant to be changed without touching or rebuilding code.', 10, 1),
  ('mission-vec-ros2-09-o1-c1', 'solution', 'A parameter is a named value a node reads at runtime, adjustable without modifying or rebuilding the node.', 20, 2),
  ('mission-vec-ros2-09-o2-c1', 'orientation', 'Look for evidence that the node''s underlying code never had to change.', 10, 1),
  ('mission-vec-ros2-09-o2-c1', 'solution', 'e1: the stop-distance parameter changed on a running node with no rebuild or reflash -- that is the live-reconfiguration benefit.', 20, 2),

  ('mission-vec-ros2-10-o1-c1', 'orientation', 'Nodes must be listed and configured before anything can actually be started.', 10, 1),
  ('mission-vec-ros2-10-o1-c1', 'solution', 'Declare, then configure, then start together -- each step depends on the one before it.', 20, 2),
  ('mission-vec-ros2-10-o2-c1', 'orientation', 'Ask whether the decision is about what a node does internally, or about how the whole graph is assembled for one robot.', 10, 1),
  ('mission-vec-ros2-10-o2-c1', 'solution', 'Node code: deciding behavior on a received message, computing a motor command. Launch file: which nodes start together, and topic remapping between robots.', 20, 2),

  ('mission-vec-ros2-11-o1-c1', 'orientation', 'One term is about how code is organized; the other is about where it gets built.', 10, 1),
  ('mission-vec-ros2-11-o1-c1', 'solution', 'A package is a self-contained, dependency-declared unit of code. A workspace is where a set of packages is actually built together, on top of the base install.', 20, 2),
  ('mission-vec-ros2-11-o2-c1', 'orientation', 'Look for evidence about what the build process actually touches, not about storage or hardware.', 10, 1),
  ('mission-vec-ros2-11-o2-c1', 'solution', 'e1: Vector Division''s packages build into an overlay on top of the base install without modifying any of its files -- a true layering, not a replacement.', 20, 2),

  ('mission-vec-ros2-12-o1-c1', 'orientation', 'Both nodes are alive and both agree on name and type -- so look one layer deeper, at the connection contract.', 10, 1),
  ('mission-vec-ros2-12-o1-c1', 'concept', 'A matching topic name and message type are necessary for a connection, but not sufficient. Quality of service policies -- reliability, durability, and more -- also have to be compatible, or the middleware simply never forms the link, without raising any error.', 20, 2),
  ('mission-vec-ros2-12-o1-c1', 'solution', 'e2: a BEST_EFFORT publisher paired with a RELIABLE-only subscriber is an incompatible QoS combination -- the connection never forms, silently.', 30, 3),
  ('mission-vec-ros2-12-o2-c1', 'orientation', 'The fix has to make both sides willing to accept the same delivery guarantee.', 10, 1),
  ('mission-vec-ros2-12-o2-c1', 'solution', 'Set both endpoints to compatible reliability policies -- reliable on both sides is correct for a safety-critical topic like this one.', 20, 2),
  ('mission-vec-ros2-12-o3-c1', 'orientation', 'Compare the live graph against the fleet''s own build manifest -- anything present on one but not the other is worth a closer look.', 10, 1),
  ('mission-vec-ros2-12-o3-c1', 'concept', 'Introspection tooling does not only show what you built it to find. Once it can see the whole graph honestly, it shows everything actually running on that graph, including interfaces nobody documented and nobody dated.', 20, 2),
  ('mission-vec-ros2-12-o3-c1', 'solution', 'e2: active publishers and subscribers exist on the live graph with no matching entry in any manifest, launch file, or package Vector Division ever authored.', 30, 3),
  ('mission-vec-ros2-12-o4-c1', 'orientation', 'Say what actually broke, what actually fixed it, and what else the same tool happened to reveal while it was open.', 15, 1),
  ('mission-vec-ros2-12-o4-c1', 'solution', 'The silent topic was a QoS mismatch, now fixed by matching reliability policies -- but the graph introspection tooling built to find it has directly exposed SUBSTRATE''s own publishers and subscribers, sitting on forgotten interfaces across the fleet for longer than any record can date.', 25, 2);
