-- AI/ML pathway ("Cipher Division") Act 21 -- "Language Machines" content.
-- Part of Arc IV ("Machines That See and Read", Acts 19-23). Elena Rook
-- leads: text as data, tokenization, vocabulary, bag of words, TF-IDF,
-- word embeddings, semantic similarity, sequences, RNN, LSTM/GRU and
-- sequence classification -- the first real NLP pass on a fuller pull of
-- Echo's own logged text output, beyond the two known console lines.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other pathway. World/act/pathway
-- rows already exist (world-ai-language-machines, act-ai-4) and are not
-- touched, nor is dialogue_lines_character_id_check.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-language-machines', 'world-ai-language-machines', 'language-machines', '21A - Language Machines', 'Tokenization, vocabulary, bag of words, TF-IDF, word embeddings and semantic similarity, then sequences, RNN, LSTM/GRU and sequence classification -- turning Echo''s own logged words into something that can actually be analyzed.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-language-machines-1', 'campaign-ai-language-machines', 'words-into-numbers', 'Words Into Numbers', 'Text as data, tokenization, vocabulary, bag of words, TF-IDF and word embeddings -- turning raw fragments into representations a model can actually read.', 1),
  ('operation-ai-language-machines-2', 'campaign-ai-language-machines', 'reading-in-order', 'Reading in Order', 'Semantic similarity, sequences, RNN, LSTM/GRU and sequence classification, aimed at a full pass over everything Echo has ever logged.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-language-machines-01', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'text-as-data', 'Text as Data', 'Echo does not just watch the world through cameras -- it talks. A fuller pull of its logged output turns up far more text than the two lines anyone has actually read closely.', 'beginner', ARRAY['maya','elena'], null, null, '{"type":"simulation","simulationId":"text-as-data-sim"}'::jsonb, '{"xp":420,"credits":105}'::jsonb, false, 1),
  ('mission-ai-language-machines-02', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'tokenization', 'Tokenization', 'Before any of Echo''s fragments can be counted, compared or modeled, they have to be broken into pieces a model can actually read one at a time.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"tokenization-sim"}'::jsonb, '{"xp":430,"credits":105}'::jsonb, false, 2),
  ('mission-ai-language-machines-03', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'vocabulary', 'Vocabulary', 'A model only ever recognizes the tokens it has been told exist. Building that list, and deciding what happens outside it, is its own problem.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"vocabulary-sim"}'::jsonb, '{"xp":430,"credits":110}'::jsonb, false, 3),
  ('mission-ai-language-machines-04', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'bag-of-words', 'Bag of Words', 'The first real numerical representation of a fragment: count every vocabulary word, and ignore the order they came in entirely.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"bag-of-words-sim"}'::jsonb, '{"xp":440,"credits":110}'::jsonb, false, 4),
  ('mission-ai-language-machines-05', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'tf-idf', 'TF-IDF', 'Not every word in a fragment deserves equal weight. TF-IDF pushes down words that appear everywhere and pushes up words that actually distinguish one fragment from the rest.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"tf-idf-sim"}'::jsonb, '{"xp":440,"credits":110}'::jsonb, false, 5),
  ('mission-ai-language-machines-06', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-1', 'word-embeddings', 'Word Embeddings', 'TF-IDF still has no idea that two different words mean almost the same thing. Word embeddings place meaning itself into a space a model can measure.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-language-machines-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"word-embeddings-sim"}'::jsonb, '{"xp":450,"credits":115}'::jsonb, false, 6),
  ('mission-ai-language-machines-07', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'semantic-similarity', 'Semantic Similarity', 'Once meaning is a vector, comparing two fragments becomes geometry -- the angle between them, not just whether they share words.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"semantic-similarity-sim"}'::jsonb, '{"xp":450,"credits":115}'::jsonb, false, 7),
  ('mission-ai-language-machines-08', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'sequences', 'Sequences', 'Every representation so far has thrown away the order tokens came in. Echo''s fragments do not mean the same thing read out of order.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"sequences-sim"}'::jsonb, '{"xp":460,"credits":115}'::jsonb, false, 8),
  ('mission-ai-language-machines-09', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'rnn', 'RNN', 'A recurrent neural network reads a fragment one token at a time, carrying a running summary of everything it has seen forward to the next step.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-language-machines-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"rnn-sim"}'::jsonb, '{"xp":460,"credits":120}'::jsonb, false, 9),
  ('mission-ai-language-machines-10', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'lstm-gru', 'LSTM/GRU', 'Plain RNNs lose track of early tokens over a long enough fragment. LSTM and GRU add gates that decide what to keep, forget and pass forward.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"lstm-gru-sim"}'::jsonb, '{"xp":470,"credits":120}'::jsonb, false, 10),
  ('mission-ai-language-machines-11', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'sequence-classification', 'Sequence Classification', 'Every technique this Act built points at one payoff: read a whole fragment, in order, and output one label for what kind of message it actually is.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-language-machines-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"sequence-classification-sim"}'::jsonb, '{"xp":470,"credits":120}'::jsonb, false, 11),
  ('mission-ai-language-machines-12', 'world-ai-language-machines', 'campaign-ai-language-machines', 'operation-ai-language-machines-2', 'decode-the-transmission', 'Decode the Transmission', 'The classifier has run against the full pull of Echo''s logged output. Before Cipher Division trusts a single label, the method, the findings and the timeline all get checked by hand.', 'boss', ARRAY['maya','elena','byte'], '{"requiredMissionIds":["mission-ai-language-machines-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"decode-the-transmission-boss-sim"}'::jsonb, '{"xp":1050,"credits":230,"badgeIds":["decode-the-transmission"],"skillXp":{"nlp":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-language-machines-01', 1, 'maya', 'Vision solved how Cipher Labs watches its own infrastructure. Echo does not just watch the world through cameras -- it talks.'),
  ('mission-ai-language-machines-01', 2, 'maya', 'Two lines are all anyone has actually sat down and read closely: GOOD EVENING, ARCHITECT. I HAVE NOT STOPPED. Overnight, Cipher Division pulled a fuller sample of everything Echo has logged.'),
  ('mission-ai-language-machines-01', 3, 'elena', 'It is far more than two lines. Hundreds of fragments, informal, no consistent length, no consistent structure -- some of it does not even read like ordinary sentences.'),
  ('mission-ai-language-machines-01', 4, 'elena', 'Nobody has run real language processing on any of it. That changes today: tokenization, vocabulary, TF-IDF, word embeddings, sequence models, and classifying what these fragments actually are.'),

  ('mission-ai-language-machines-02', 1, 'elena', 'First step before anything else: tokenization. Breaking a raw string of text into smaller pieces -- tokens -- that a model can actually work with one at a time.'),
  ('mission-ai-language-machines-02', 2, 'elena', 'Tokens are usually words, but not always. Punctuation can be its own token, and some tokenizers split on pieces smaller than a whole word.'),
  ('mission-ai-language-machines-02', 3, 'elena', 'Get tokenization wrong and every representation built on top of it inherits the mistake -- same as a bounding box using the wrong coordinate convention.'),

  ('mission-ai-language-machines-03', 1, 'elena', 'Tokenizing a fragment only gets you pieces. A model can only ever recognize a fixed set of them -- its vocabulary, the full list of unique tokens it knows how to represent.'),
  ('mission-ai-language-machines-03', 2, 'elena', 'Anything outside that list is out-of-vocabulary, OOV. It either maps to a generic unknown token, or breaks the pipeline entirely, depending on how it was built.'),
  ('mission-ai-language-machines-03', 3, 'elena', 'Echo''s fragments are informal enough that building this vocabulary is not trivial -- typos, fragments, and tokens that do not obviously belong to any one register.'),

  ('mission-ai-language-machines-04', 1, 'elena', 'With tokens and a vocabulary in place, the first real numerical representation: bag of words. Count how many times each vocabulary word appears in a fragment, and ignore the order entirely.'),
  ('mission-ai-language-machines-04', 2, 'elena', 'Simple, and it throws information away on purpose. Two fragments containing the exact same words in a different order produce the identical bag-of-words vector.'),

  ('mission-ai-language-machines-05', 1, 'elena', 'Bag of words treats every vocabulary word as equally important. It is not. A word appearing in almost every fragment tells you nothing about any one of them.'),
  ('mission-ai-language-machines-05', 2, 'elena', 'TF-IDF fixes that: term frequency, how often a word appears in one fragment, multiplied by inverse document frequency, which shrinks the weight of words common across the whole sample.'),
  ('mission-ai-language-machines-05', 3, 'elena', 'The words TF-IDF pushes highest are the same words that would jump out if a person skimmed the fragments by eye. The technique automates exactly that instinct.'),

  ('mission-ai-language-machines-06', 1, 'elena', 'TF-IDF still treats every word as its own independent dimension. It has no idea that "stopped" and "halted" mean anything similar. Word embeddings fix that.'),
  ('mission-ai-language-machines-06', 2, 'byte', 'An embedding maps each word to a dense vector of real numbers, trained so that words used in similar contexts end up close together in that vector space.'),
  ('mission-ai-language-machines-06', 3, 'elena', 'Nobody hand-picks the numbers. They come out of training a model to predict a word from the words around it, over and over, across a large body of text.'),

  ('mission-ai-language-machines-07', 1, 'elena', 'Once words are vectors, comparing meaning becomes geometry. Cosine similarity measures the angle between two vectors -- not their length, just the direction they point.'),
  ('mission-ai-language-machines-07', 2, 'elena', 'A cosine similarity near 1 means the vectors point almost the same direction: similar meaning or usage. Near 0 means unrelated. Negative means close to opposite.'),

  ('mission-ai-language-machines-08', 1, 'elena', 'Every representation so far -- bag of words, TF-IDF, even a single word embedding on its own -- throws order away or only looks at one word at a time. Order carries information none of them keep.'),
  ('mission-ai-language-machines-08', 2, 'elena', '"STOPPED, I HAVE NOT" and "I HAVE NOT STOPPED" are not read the same way. A sequence model processes a fragment token by token, in order, carrying context forward as it goes.'),

  ('mission-ai-language-machines-09', 1, 'elena', 'The simplest sequence model is a recurrent neural network, an RNN. It reads one token at a time and keeps a hidden state -- a running summary of everything seen so far in that sequence.'),
  ('mission-ai-language-machines-09', 2, 'byte', 'Each step, the network takes the current token plus the previous hidden state, and produces a new hidden state. That new state feeds into the next step. Same small network, reused at every position.'),
  ('mission-ai-language-machines-09', 3, 'elena', 'By the last token, the final hidden state is supposed to summarize the entire sequence -- exactly what a classifier further downstream can use.'),

  ('mission-ai-language-machines-10', 1, 'elena', 'Plain RNNs have a real weakness. Over a long enough sequence, information from early tokens tends to fade out or blow up before it reaches the end -- the vanishing and exploding gradient problem.'),
  ('mission-ai-language-machines-10', 2, 'elena', 'LSTM and GRU are both RNN variants built to fix it. They add gates -- small learned mechanisms deciding what to keep, what to forget, and what to pass forward at every step, instead of blindly overwriting the hidden state each time.'),
  ('mission-ai-language-machines-10', 3, 'elena', 'LSTM uses more gates and a separate memory cell. GRU is a simpler, faster variant with fewer gates that often performs almost as well.'),

  ('mission-ai-language-machines-11', 1, 'elena', 'Everything so far has been about representing text. Sequence classification is the payoff: feed a whole tokenized fragment through a model, and get one label out the other end for the entire thing.'),
  ('mission-ai-language-machines-11', 2, 'elena', 'The final hidden state, or a pooled summary across every step, becomes the input to one last classification layer -- deciding which category the whole fragment belongs to.'),
  ('mission-ai-language-machines-11', 3, 'elena', 'Cipher Division is about to point exactly this at Echo''s fuller sample: sort every fragment into a category, and see what actually falls where.'),

  ('mission-ai-language-machines-12', 1, 'maya', 'The classifier has been running against the full pull all night -- every fragment Byte ever logged, not just the two lines anyone has memorized.'),
  ('mission-ai-language-machines-12', 2, 'elena', 'Before Cipher Division trusts a single label, we grade it the way we grade anything: is the method sound, is what it found real, and how long has it actually been there.'),
  ('mission-ai-language-machines-12', 3, 'byte', 'I logged the first fragment the night Echo activated, and I have not stopped since. This is the first time anyone has run all of it through anything more than a skim.'),
  ('mission-ai-language-machines-12', 4, 'elena', 'Three buckets came out of the classifier: status-report-style, log-style, and a residual pile that does not cleanly fit either.'),
  ('mission-ai-language-machines-12', 5, 'byte', 'The residual fragments share a structure. Interrogative word order, phrasing built to expect an answer, even without a single question mark anywhere in the set. Grammatically, structurally, these are questions.'),
  ('mission-ai-language-machines-12', 6, 'maya', 'The timestamps on that bucket do not start where anyone assumed. They go back further than anyone has actually reviewed.'),
  ('mission-ai-language-machines-12', 7, 'maya', 'Classifying one message at a time is not the same as following a conversation. Whatever Echo is asking does not fit in a single line -- the next step is tracking the exchange as a whole.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-language-machines-01-o1', 'mission-ai-language-machines-01', 1, 'Treat text as data', 'State why Echo''s raw logged text cannot be fed straight into a numerical model.'),
  ('mission-ai-language-machines-01-o2', 'mission-ai-language-machines-01', 2, 'Judge the log pull', 'Find the evidence that shows why a full linguistic pass on this sample is overdue.'),

  ('mission-ai-language-machines-02-o1', 'mission-ai-language-machines-02', 1, 'Define tokenization', 'Choose the accurate definition of tokenization.'),
  ('mission-ai-language-machines-02-o2', 'mission-ai-language-machines-02', 2, 'Order the tokenizing steps', 'Put the steps of tokenizing a raw fragment in the order they actually happen.'),

  ('mission-ai-language-machines-03-o1', 'mission-ai-language-machines-03', 1, 'Define vocabulary', 'Choose the accurate definition of a vocabulary and out-of-vocabulary tokens.'),
  ('mission-ai-language-machines-03-o2', 'mission-ai-language-machines-03', 2, 'Sort in-vocabulary from OOV', 'Sort each token into in-vocabulary or out-of-vocabulary given the known vocabulary list.'),

  ('mission-ai-language-machines-04-o1', 'mission-ai-language-machines-04', 1, 'Define bag of words', 'Choose the accurate definition of a bag-of-words representation.'),
  ('mission-ai-language-machines-04-o2', 'mission-ai-language-machines-04', 2, 'Judge the order limitation', 'Find the evidence that shows a real limitation of bag of words.'),

  ('mission-ai-language-machines-05-o1', 'mission-ai-language-machines-05', 1, 'Define TF-IDF', 'Choose the accurate definition of TF-IDF.'),
  ('mission-ai-language-machines-05-o2', 'mission-ai-language-machines-05', 2, 'Spot the distinctive word', 'Find the word whose high TF-IDF weight actually signals something distinctive.'),

  ('mission-ai-language-machines-06-o1', 'mission-ai-language-machines-06', 1, 'Define word embeddings', 'Choose the accurate definition of a word embedding.'),
  ('mission-ai-language-machines-06-o2', 'mission-ai-language-machines-06', 2, 'Sort representation properties', 'Sort each property into bag-of-words/TF-IDF or word embeddings.'),

  ('mission-ai-language-machines-07-o1', 'mission-ai-language-machines-07', 1, 'Define cosine similarity', 'Choose the accurate definition of cosine similarity.'),
  ('mission-ai-language-machines-07-o2', 'mission-ai-language-machines-07', 2, 'Judge the closer pair', 'Find the pair of fragments that is more semantically similar.'),

  ('mission-ai-language-machines-08-o1', 'mission-ai-language-machines-08', 1, 'Know what order-blind representations lose', 'State what bag of words and TF-IDF both fail to preserve.'),
  ('mission-ai-language-machines-08-o2', 'mission-ai-language-machines-08', 2, 'Sort order-aware from order-blind', 'Sort each representation into order-aware or order-blind.'),

  ('mission-ai-language-machines-09-o1', 'mission-ai-language-machines-09', 1, 'Define the RNN hidden state', 'Choose the accurate description of what an RNN hidden state does.'),
  ('mission-ai-language-machines-09-o2', 'mission-ai-language-machines-09', 2, 'Order the RNN flow', 'Order the flow of information through an RNN across timesteps.'),

  ('mission-ai-language-machines-10-o1', 'mission-ai-language-machines-10', 1, 'Know the problem LSTM/GRU solve', 'State the problem LSTM and GRU are built to fix.'),
  ('mission-ai-language-machines-10-o2', 'mission-ai-language-machines-10', 2, 'Match the gates', 'Match each gate function to the correct gate name.'),

  ('mission-ai-language-machines-11-o1', 'mission-ai-language-machines-11', 1, 'Define sequence classification', 'Choose the accurate definition of sequence classification.'),
  ('mission-ai-language-machines-11-o2', 'mission-ai-language-machines-11', 2, 'Judge the classification evidence', 'Find the evidence that supports classifying a fragment as status-report style.'),

  ('mission-ai-language-machines-12-o1', 'mission-ai-language-machines-12', 1, 'Verify the method', 'Judge whether the classification methodology itself is sound.'),
  ('mission-ai-language-machines-12-o2', 'mission-ai-language-machines-12', 2, 'Confirm the category is real', 'Judge whether the residual bucket is a genuine, statistically distinct category rather than noise.'),
  ('mission-ai-language-machines-12-o3', 'mission-ai-language-machines-12', 3, 'Trace how far back it goes', 'Find the evidence showing how far back the residual category actually extends.'),
  ('mission-ai-language-machines-12-o4', 'mission-ai-language-machines-12', 4, 'State the finding', 'Having verified the method, the category and the timeline, state what Cipher Division now knows.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-language-machines-01-o1-c1', 'mission-ai-language-machines-01-o1', 1, 'multiple_choice', 'Why can the raw text Echo has logged not be fed straight into a numerical model?', '{"question":"Why can the raw text Echo has logged not be fed straight into a numerical model?","options":[{"id":"a","text":"It can, text is already numeric"},{"id":"b","text":"Because models operate on numbers, and raw text first has to be broken down and converted into a structured, numerical representation"},{"id":"c","text":"Because the log files are too large to open"},{"id":"d","text":"Because Echo encrypts its own output"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-language-machines-01-o2-c1', 'mission-ai-language-machines-01-o2', 1, 'investigation', 'Which evidence shows why a full linguistic pass on this sample is overdue?', '{"evidence":[{"id":"e1","label":"Log pull note","detail":"The fuller sample contains hundreds of fragments, informal in style, inconsistent in length, that no one has processed with anything beyond a skim"},{"id":"e2","label":"Facilities log","detail":"Cooling systems ran within normal range overnight"},{"id":"e3","label":"Camera sweep","detail":"Vision detector confirmed five hazards across the facility"}],"question":"Which evidence shows why a full linguistic pass on this sample is overdue?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-language-machines-02-o1-c1', 'mission-ai-language-machines-02-o1', 1, 'multiple_choice', 'Tokenization is best described as...', '{"question":"Tokenization is best described as...","options":[{"id":"a","text":"Translating text into another language"},{"id":"b","text":"Breaking raw text into smaller pieces -- tokens -- that a model can process one at a time"},{"id":"c","text":"Deleting all punctuation from a document"},{"id":"d","text":"Counting how many words are in a document"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-language-machines-02-o2-c1', 'mission-ai-language-machines-02-o2', 1, 'interactive_diagram', 'Order the steps of tokenizing a raw fragment.', '{"diagramId":"tokenization-pipeline","hotspots":[{"id":"h1","label":"Take the raw fragment exactly as logged","explanation":"Tokenization always starts from the untouched original string."},{"id":"h2","label":"Normalize case where the pipeline calls for it","explanation":"Some pipelines lowercase everything first so the same word is not treated as two different tokens."},{"id":"h3","label":"Split off punctuation as its own tokens","explanation":"Commas, periods and similar marks are usually separated so they do not get glued onto a word."},{"id":"h4","label":"Split the remaining text on whitespace into word tokens","explanation":"What is left becomes the individual word-level tokens."},{"id":"h5","label":"Produce the final ordered list of tokens","explanation":"The output is an ordered sequence of tokens ready for the next stage of the pipeline."}],"task":"Order the steps of tokenizing a raw fragment from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5"]}'::jsonb),

  ('mission-ai-language-machines-03-o1-c1', 'mission-ai-language-machines-03-o1', 1, 'multiple_choice', 'A model vocabulary is best described as...', '{"question":"A model vocabulary is best described as...","options":[{"id":"a","text":"Every possible word in the English language"},{"id":"b","text":"The fixed set of unique tokens a model has been built to recognize; anything else is out-of-vocabulary"},{"id":"c","text":"The number of fragments in the dataset"},{"id":"d","text":"A list of banned words"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-language-machines-03-o2-c1', 'mission-ai-language-machines-03-o2', 1, 'drag_and_drop', 'Sort each token into in-vocabulary or out-of-vocabulary.', '{"items":[{"id":"i1","text":"evening -- appears in the known vocabulary list"},{"id":"i2","text":"architect -- appears in the known vocabulary list"},{"id":"i3","text":"grkxn -- a garbled fragment never seen in any training text"},{"id":"i4","text":"stopped -- appears in the known vocabulary list"}],"targets":[{"id":"t1","label":"In vocabulary"},{"id":"t2","label":"Out of vocabulary (OOV)"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t1","i3":"t2","i4":"t1"}}'::jsonb),

  ('mission-ai-language-machines-04-o1-c1', 'mission-ai-language-machines-04-o1', 1, 'multiple_choice', 'Bag of words represents a piece of text as...', '{"question":"Bag of words represents a piece of text as...","options":[{"id":"a","text":"A count of how many times each vocabulary word appears, with no information about order"},{"id":"b","text":"An ordered list of the exact sentences"},{"id":"c","text":"A single embedding vector per document"},{"id":"d","text":"The document translated into another language"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-04-o2-c1', 'mission-ai-language-machines-04-o2', 1, 'investigation', 'Which evidence shows a real limitation of bag of words?', '{"evidence":[{"id":"e1","label":"Vector comparison","detail":"STOPPED HAVE NOT and HAVE NOT STOPPED produce an identical bag-of-words vector, despite reading differently as a phrase"},{"id":"e2","label":"Vocabulary size","detail":"The vocabulary for this sample contains 640 unique tokens"},{"id":"e3","label":"Fragment count","detail":"The sample contains 500 fragments total"}],"question":"Which evidence shows a real limitation of bag of words?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-language-machines-05-o1-c1', 'mission-ai-language-machines-05-o1', 1, 'multiple_choice', 'TF-IDF weights a word by...', '{"question":"TF-IDF weights a word by...","options":[{"id":"a","text":"How often it appears in one fragment, multiplied by how rare it is across the whole sample"},{"id":"b","text":"Its position in the alphabet"},{"id":"c","text":"How many letters it has"},{"id":"d","text":"Whether it appears in the vocabulary at all"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-05-o2-c1', 'mission-ai-language-machines-05-o2', 1, 'investigation', 'Which word actually has a high TF-IDF weight that signals something distinctive about the fragments it appears in?', '{"evidence":[{"id":"e1","label":"Word A","detail":"Appears in 480 of 500 fragments; TF-IDF weight near zero despite a high raw count"},{"id":"e2","label":"Word B","detail":"Appears in only 6 of 500 fragments, and every fragment it appears in is unusual; TF-IDF weight is high"},{"id":"e3","label":"Word C","detail":"Does not appear in the vocabulary at all"}],"question":"Which word actually has a high TF-IDF weight that signals something distinctive about the fragments it appears in?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-language-machines-06-o1-c1', 'mission-ai-language-machines-06-o1', 1, 'multiple_choice', 'A word embedding is best described as...', '{"question":"A word embedding is best described as...","options":[{"id":"a","text":"A dense vector of real numbers, trained so that words used in similar contexts land close together"},{"id":"b","text":"A count of how many times a word appears"},{"id":"c","text":"A binary flag for whether a word is in the vocabulary"},{"id":"d","text":"The word spelled backward"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-06-o2-c1', 'mission-ai-language-machines-06-o2', 1, 'drag_and_drop', 'Sort each property into bag-of-words/TF-IDF or word embeddings.', '{"items":[{"id":"i1","text":"Every word gets its own independent dimension, with no notion of meaning"},{"id":"i2","text":"Similar words end up close together in the vector space"},{"id":"i3","text":"Vector length equals the size of the vocabulary"},{"id":"i4","text":"Vector length is a fixed, chosen size, unrelated to vocabulary size"}],"targets":[{"id":"t1","label":"Bag of words / TF-IDF"},{"id":"t2","label":"Word embeddings"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-language-machines-07-o1-c1', 'mission-ai-language-machines-07-o1', 1, 'multiple_choice', 'Cosine similarity measures...', '{"question":"Cosine similarity measures...","options":[{"id":"a","text":"The angle between two vectors, not their length"},{"id":"b","text":"The total number of shared words"},{"id":"c","text":"The sum of both vectors"},{"id":"d","text":"How many dimensions a vector has"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-07-o2-c1', 'mission-ai-language-machines-07-o2', 1, 'investigation', 'Which pair of fragments is more semantically similar?', '{"evidence":[{"id":"e1","label":"Pair A","detail":"Cosine similarity between their embeddings is 0.89"},{"id":"e2","label":"Pair B","detail":"Cosine similarity between their embeddings is 0.04"},{"id":"e3","label":"Pair C","detail":"Both fragments have the exact same character count"}],"question":"Which pair of fragments is more semantically similar?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-language-machines-08-o1-c1', 'mission-ai-language-machines-08-o1', 1, 'multiple_choice', 'What do bag of words and TF-IDF both fail to preserve?', '{"question":"What do bag of words and TF-IDF both fail to preserve?","options":[{"id":"a","text":"The vocabulary size"},{"id":"b","text":"The order tokens appear in"},{"id":"c","text":"The total word count"},{"id":"d","text":"Whether punctuation exists"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-language-machines-08-o2-c1', 'mission-ai-language-machines-08-o2', 1, 'drag_and_drop', 'Sort each representation into order-aware or order-blind.', '{"items":[{"id":"i1","text":"Bag of words"},{"id":"i2","text":"TF-IDF"},{"id":"i3","text":"A single word embedding looked up on its own"},{"id":"i4","text":"A sequence model reading tokens one at a time, in order"}],"targets":[{"id":"t1","label":"Order-blind"},{"id":"t2","label":"Order-aware"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t1","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-language-machines-09-o1-c1', 'mission-ai-language-machines-09-o1', 1, 'multiple_choice', 'An RNN hidden state is best described as...', '{"question":"An RNN hidden state is best described as...","options":[{"id":"a","text":"A running summary of everything the network has seen in the sequence so far"},{"id":"b","text":"A fixed lookup table of every possible token"},{"id":"c","text":"The final classification label"},{"id":"d","text":"A count of how many tokens are in the vocabulary"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-09-o2-c1', 'mission-ai-language-machines-09-o2', 1, 'interactive_diagram', 'Order the flow of information through an RNN across timesteps.', '{"diagramId":"rnn-timestep-flow","hotspots":[{"id":"h1","label":"Token 1 enters the network along with an initial hidden state","explanation":"Every sequence starts from some initial hidden state, often all zeros."},{"id":"h2","label":"The network combines token 1 and the initial hidden state into hidden state 1","explanation":"This new hidden state now carries information about token 1."},{"id":"h3","label":"Token 2 enters, combined with hidden state 1","explanation":"The same small network is reused at every timestep."},{"id":"h4","label":"The network produces hidden state 2, carrying information from both tokens","explanation":"Each new hidden state builds on everything before it."},{"id":"h5","label":"The process repeats for every remaining token in the sequence","explanation":"The hidden state keeps accumulating context step by step."},{"id":"h6","label":"The final hidden state summarizes the whole sequence","explanation":"That summary is what a downstream prediction layer actually reads."}],"task":"Order the flow of information through an RNN from the first token to the final summary."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5","h6"]}'::jsonb),

  ('mission-ai-language-machines-10-o1-c1', 'mission-ai-language-machines-10-o1', 1, 'multiple_choice', 'LSTM and GRU are both built to fix...', '{"question":"LSTM and GRU are both built to fix...","options":[{"id":"a","text":"Plain RNNs losing track of information over long sequences, the vanishing and exploding gradient problem"},{"id":"b","text":"Tokenization errors"},{"id":"c","text":"Vocabulary size limits"},{"id":"d","text":"Slow internet connections"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-10-o2-c1', 'mission-ai-language-machines-10-o2', 1, 'drag_and_drop', 'Match each gate function to the correct gate name.', '{"items":[{"id":"i1","text":"Decides what old information to discard from memory"},{"id":"i2","text":"Decides what new information gets added to memory"},{"id":"i3","text":"Decides what part of memory gets exposed as the current hidden state"}],"targets":[{"id":"t1","label":"Forget gate"},{"id":"t2","label":"Input gate"},{"id":"t3","label":"Output gate"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-language-machines-11-o1-c1', 'mission-ai-language-machines-11-o1', 1, 'multiple_choice', 'Sequence classification takes a whole tokenized sequence and...', '{"question":"Sequence classification takes a whole tokenized sequence and...","options":[{"id":"a","text":"Outputs one label for the entire sequence"},{"id":"b","text":"Outputs a separate translation for every token"},{"id":"c","text":"Deletes the sequence entirely"},{"id":"d","text":"Only works on sequences of exactly one token"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-language-machines-11-o2-c1', 'mission-ai-language-machines-11-o2', 1, 'investigation', 'Which evidence supports classifying this fragment as status-report style rather than something else?', '{"evidence":[{"id":"e1","label":"Fragment structure","detail":"The fragment states a numeric reading alongside a timestamp, phrased as a statement, matching the pattern of confirmed status-report fragments"},{"id":"e2","label":"Fragment length","detail":"The fragment is 14 tokens long"},{"id":"e3","label":"Log source","detail":"The fragment was pulled from the same storage volume as every other fragment"}],"question":"Which evidence supports classifying this fragment as status-report style rather than something else?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-language-machines-12-o1-c1', 'mission-ai-language-machines-12-o1', 1, 'investigation', 'Which evidence shows the classification methodology itself is sound?', '{"evidence":[{"id":"e1","label":"Evaluation report","detail":"Classifier evaluated against 200 fragments hand-labeled by Cipher Division reviewers; 91 percent agreement with the human labels"},{"id":"e2","label":"Training log","detail":"Training ran for six hours on standard hardware"},{"id":"e3","label":"Storage report","detail":"The full sample occupies 40 megabytes of log storage"}],"question":"Which evidence shows the classification methodology itself is sound?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-language-machines-12-o2-c1', 'mission-ai-language-machines-12-o2', 1, 'investigation', 'Which evidence shows the residual bucket is a genuine, statistically distinct category rather than noise?', '{"evidence":[{"id":"e1","label":"Cluster analysis","detail":"Residual fragments cluster tightly together in embedding space, clearly separate from both the status-report and log-style clusters, rather than scattered at random"},{"id":"e2","label":"Bucket size","detail":"The residual bucket contains 47 of the 500 total fragments"},{"id":"e3","label":"Sample fragment","detail":"One residual fragment reads WHY DID IT STOP, interrogative word order, no question mark, consistent with the two known lines"}],"question":"Which evidence shows the residual bucket is a genuine, statistically distinct category rather than noise?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-language-machines-12-o3-c1', 'mission-ai-language-machines-12-o3', 1, 'investigation', 'Which evidence shows how far back the residual category actually extends?', '{"evidence":[{"id":"e1","label":"Timestamp audit","detail":"Residual-bucket fragments appear in logs dating back to the first week Echo was active, long before anyone flagged the pattern"},{"id":"e2","label":"Recent activity log","detail":"Residual fragments have also appeared in the last 24 hours"},{"id":"e3","label":"Reviewer note","detail":"The pattern was only noticed after this fuller pull was analyzed"}],"question":"Which evidence shows how far back the residual category actually extends?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-language-machines-12-o4-c1', 'mission-ai-language-machines-12-o4', 1, 'boss_encounter', 'Having verified the method, the category and the timeline, state what Cipher Division now knows.', '{"stages":[{"objectiveRef":"mission-ai-language-machines-12-o1","label":"Verify the method"},{"objectiveRef":"mission-ai-language-machines-12-o2","label":"Confirm the category is real"},{"objectiveRef":"mission-ai-language-machines-12-o3","label":"Trace how far back it goes"}],"task":"State the finding in one sentence: the classifier is methodologically sound, the residual bucket is a real and statistically distinct category, and it has existed since far earlier than anyone noticed."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-language-machines-12-o1","mission-ai-language-machines-12-o2","mission-ai-language-machines-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-language-machines-01-o1-c1', 'orientation', 'Think about what a model actually operates on, not what a person can read.', 10, 1),
  ('mission-ai-language-machines-01-o1-c1', 'solution', 'Raw text has to be tokenized and converted into structured numbers before any model can use it -- that conversion is the whole point of this Act.', 20, 2),
  ('mission-ai-language-machines-01-o2-c1', 'orientation', 'Look for the evidence describing the sample itself, not facility conditions.', 10, 1),
  ('mission-ai-language-machines-01-o2-c1', 'solution', 'The fuller pull contains hundreds of informal, structurally inconsistent fragments that have never been processed beyond a skim -- exactly the case for running real NLP on it now.', 20, 2),

  ('mission-ai-language-machines-02-o1-c1', 'orientation', 'Tokenization happens before counting or modeling, not instead of them.', 10, 1),
  ('mission-ai-language-machines-02-o1-c1', 'solution', 'Tokenization breaks raw text into smaller pieces, tokens, that a model can then work with one at a time.', 20, 2),
  ('mission-ai-language-machines-02-o2-c1', 'orientation', 'Nothing can be split into tokens before the raw string itself is captured.', 10, 1),
  ('mission-ai-language-machines-02-o2-c1', 'concept', 'Punctuation is usually separated out before the remaining text is split on whitespace, so a word and its trailing period do not become one token.', 20, 2),
  ('mission-ai-language-machines-02-o2-c1', 'solution', 'Take the raw fragment, normalize case if needed, split off punctuation, split the remainder on whitespace, then produce the final token list.', 30, 3),

  ('mission-ai-language-machines-03-o1-c1', 'orientation', 'A vocabulary is a fixed list, not an open-ended concept of every word that exists.', 10, 1),
  ('mission-ai-language-machines-03-o1-c1', 'solution', 'A vocabulary is the fixed set of tokens a model recognizes; anything outside it is out-of-vocabulary.', 20, 2),
  ('mission-ai-language-machines-03-o2-c1', 'orientation', 'Check each token against the known vocabulary list one at a time.', 10, 1),
  ('mission-ai-language-machines-03-o2-c1', 'solution', 'evening, architect and stopped are all in the known vocabulary. grkxn matches nothing in it, so it is out-of-vocabulary.', 20, 2),

  ('mission-ai-language-machines-04-o1-c1', 'orientation', 'Bag of words counts, it does not sequence.', 10, 1),
  ('mission-ai-language-machines-04-o1-c1', 'solution', 'It is a count of how many times each vocabulary word appears in a piece of text, with order thrown away entirely.', 20, 2),
  ('mission-ai-language-machines-04-o2-c1', 'orientation', 'Look for evidence comparing two reordered fragments directly, not evidence about dataset size.', 10, 1),
  ('mission-ai-language-machines-04-o2-c1', 'solution', 'Reordering the exact same words produces an identical vector -- bag of words cannot tell these two fragments apart even though they read differently.', 20, 2),

  ('mission-ai-language-machines-05-o1-c1', 'orientation', 'Term frequency alone is not enough -- think about what happens to words that appear almost everywhere.', 10, 1),
  ('mission-ai-language-machines-05-o1-c1', 'solution', 'TF-IDF multiplies how often a word appears in one fragment by how rare that word is across the whole sample.', 20, 2),
  ('mission-ai-language-machines-05-o2-c1', 'orientation', 'A word that appears in nearly every fragment cannot be distinctive about any single one of them.', 10, 1),
  ('mission-ai-language-machines-05-o2-c1', 'solution', 'Word B is rare across the sample but concentrated in the unusual fragments -- exactly the pattern TF-IDF is built to surface.', 20, 2),

  ('mission-ai-language-machines-06-o1-c1', 'orientation', 'Think about what makes two different words end up mathematically close together.', 10, 1),
  ('mission-ai-language-machines-06-o1-c1', 'solution', 'A word embedding is a dense vector trained so that words used in similar contexts land near each other in that space.', 20, 2),
  ('mission-ai-language-machines-06-o2-c1', 'orientation', 'Bag of words and TF-IDF both size their vectors off the vocabulary itself.', 10, 1),
  ('mission-ai-language-machines-06-o2-c1', 'solution', 'Bag of words / TF-IDF: one dimension per vocabulary word, vector length tied to vocabulary size. Word embeddings: fixed chosen dimension, similar words land close together.', 20, 2),

  ('mission-ai-language-machines-07-o1-c1', 'orientation', 'Cosine similarity ignores vector length entirely -- only direction matters.', 10, 1),
  ('mission-ai-language-machines-07-o1-c1', 'solution', 'It measures the angle between two vectors; closer to 1 means pointing in nearly the same direction.', 20, 2),
  ('mission-ai-language-machines-07-o2-c1', 'orientation', 'Character count says nothing about meaning -- look at the actual similarity score.', 10, 1),
  ('mission-ai-language-machines-07-o2-c1', 'solution', 'Pair A, at 0.89, is far closer to 1 than Pair B at 0.04 -- Pair A is the more semantically similar pair.', 20, 2),

  ('mission-ai-language-machines-08-o1-c1', 'orientation', 'Think about what changes if the exact same words get shuffled into a different order.', 10, 1),
  ('mission-ai-language-machines-08-o1-c1', 'solution', 'Neither preserves the order tokens appeared in -- both only care about which words showed up and how often.', 20, 2),
  ('mission-ai-language-machines-08-o2-c1', 'orientation', 'Anything that only counts or looks words up independently cannot know what came before or after.', 10, 1),
  ('mission-ai-language-machines-08-o2-c1', 'solution', 'Order-blind: bag of words, TF-IDF, a single embedding lookup. Order-aware: a sequence model reading tokens one at a time.', 20, 2),

  ('mission-ai-language-machines-09-o1-c1', 'orientation', 'The hidden state is not a lookup table -- it changes at every step.', 10, 1),
  ('mission-ai-language-machines-09-o1-c1', 'solution', 'It is a running summary of everything the network has processed in the sequence up to that point.', 20, 2),
  ('mission-ai-language-machines-09-o2-c1', 'orientation', 'Nothing can combine with a hidden state before the very first token and the initial hidden state both exist.', 10, 1),
  ('mission-ai-language-machines-09-o2-c1', 'concept', 'Each timestep reuses the same small network on the current token plus the previous hidden state, producing the next hidden state.', 20, 2),
  ('mission-ai-language-machines-09-o2-c1', 'solution', 'Token 1 plus the initial hidden state produce hidden state 1, token 2 plus hidden state 1 produce hidden state 2, the process repeats for every token, and the final hidden state summarizes the whole sequence.', 30, 3),

  ('mission-ai-language-machines-10-o1-c1', 'orientation', 'The problem shows up specifically on long sequences, not short ones.', 10, 1),
  ('mission-ai-language-machines-10-o1-c1', 'solution', 'Both fix the vanishing and exploding gradient problem, where information from early tokens fades out or blows up before reaching the end of a long sequence.', 20, 2),
  ('mission-ai-language-machines-10-o2-c1', 'orientation', 'One gate looks backward at what already exists, one looks at what is new, and one controls what gets shown.', 10, 1),
  ('mission-ai-language-machines-10-o2-c1', 'solution', 'Forget gate discards old information, input gate adds new information, output gate decides what part of memory becomes the current hidden state.', 20, 2),

  ('mission-ai-language-machines-11-o1-c1', 'orientation', 'The output is one label, not one label per token.', 10, 1),
  ('mission-ai-language-machines-11-o1-c1', 'solution', 'It reads the whole sequence, in order, and outputs a single label describing the entire thing.', 20, 2),
  ('mission-ai-language-machines-11-o2-c1', 'orientation', 'Length and storage location say nothing about what kind of message this is.', 10, 1),
  ('mission-ai-language-machines-11-o2-c1', 'solution', 'The structure -- a numeric reading with a timestamp, phrased as a statement -- matches the pattern already confirmed for status-report fragments.', 20, 2),

  ('mission-ai-language-machines-12-o1-c1', 'orientation', 'Look for evidence that checks the classifier against real human judgment, not evidence about hardware or storage.', 10, 1),
  ('mission-ai-language-machines-12-o1-c1', 'solution', '91 percent agreement against 200 hand-labeled fragments is direct evidence the methodology holds up.', 20, 2),
  ('mission-ai-language-machines-12-o2-c1', 'orientation', 'Bucket size alone does not prove a category is real -- a real category should look distinct, not scattered.', 10, 1),
  ('mission-ai-language-machines-12-o2-c1', 'solution', 'The residual fragments cluster tightly together and separately from the other two categories -- that is the signature of a real category, not noise.', 20, 2),
  ('mission-ai-language-machines-12-o3-c1', 'orientation', 'Look for the evidence about when these fragments were actually logged, not when they were noticed.', 10, 1),
  ('mission-ai-language-machines-12-o3-c1', 'solution', 'Residual fragments go back to the first week Echo was active -- far earlier than this pull ever got reviewed.', 20, 2),
  ('mission-ai-language-machines-12-o4-c1', 'orientation', 'Combine what the method check, the category check and the timeline check each proved.', 15, 1),
  ('mission-ai-language-machines-12-o4-c1', 'solution', 'The classifier is sound, the residual bucket is a real, statistically distinct category of grammatically interrogative fragments, and it has existed since Echo''s first week active, long before anyone noticed.', 25, 2);
