-- Backend Engineering ("The Fracture") Act -- "Event-Driven Architecture"
-- content. Arc IV ("Stream"), between Kafka & Event Streaming (before) and
-- Advanced Event Systems (after). 1 campaign, 2 operations, 12 missions
-- (11 lessons + boss), using the slug-based id scheme (world-be-event-driven
-- already inserted by 20260810320000_backend_renumber_and_acts19_31_spine.sql).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be-event-driven', 'world-be-event-driven', 'event-driven-architecture', '19A - Event-Driven Architecture', 'A dispatch order is marked "confirmed" in the orders service and "never received" in fulfillment -- both true, from what each service actually saw. Learn why systems built on events, not requests, can be exactly this honest and still this wrong.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be-event-driven-1', 'campaign-be-event-driven', 'events-not-requests', 'Events, Not Requests', 'Commands, events, pub/sub, and the two ways services can coordinate without one blocking on the other -- then the consistency model and the failure it makes possible.', 1),
  ('operation-be-event-driven-2', 'campaign-be-event-driven', 'closing-the-gap', 'Closing the Gap', 'The patterns that make eventual consistency safe -- transactional outbox, inbox, change data capture, sagas and compensations -- then the incident that made all five necessary.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be-event-driven-01', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'events-vs-commands', 'Events vs Commands', 'A command tells another service what to do and waits for an answer. An event announces that something already happened and expects nothing back. The dispatch order that opened this Act got that distinction wrong in a way that''s about to matter a lot.', 'advanced', ARRAY['mira','forge'], null, null, '{"type":"simulation","simulationId":"events-vs-commands-sim"}'::jsonb, '{"xp":228,"credits":44}'::jsonb, false, 1),
  ('mission-be-event-driven-02', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'pub-sub', 'Pub/Sub', 'A publisher doesn''t address a message to anyone. It puts it on a topic and walks away, trusting that whoever needs to know is already listening -- and that''s exactly the trust the dispatch order incident is about to test.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-event-driven-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"pub-sub-sim"}'::jsonb, '{"xp":230,"credits":44}'::jsonb, false, 2),
  ('mission-be-event-driven-03', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'choreography', 'Choreography', 'No conductor, no single file with the whole plan -- every service just reacts to the event in front of it and publishes its own event in turn. It works beautifully, right up until someone asks "what''s supposed to happen, in order, when an order is placed?"', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-event-driven-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"choreography-sim"}'::jsonb, '{"xp":231,"credits":45}'::jsonb, false, 3),
  ('mission-be-event-driven-04', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'orchestration', 'Orchestration', 'An orchestrator is the conductor choreography refuses to have: one process that calls each step, knows the whole flow, and can tell you exactly where things stand. The tradeoff is just as real -- now that one process is a dependency every step needs.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-event-driven-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"orchestration-sim"}'::jsonb, '{"xp":233,"credits":45}'::jsonb, false, 4),
  ('mission-be-event-driven-05', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'eventual-consistency', 'Eventual Consistency', 'Every service that reacts to an event is, for some window of time, telling the truth about a world that''s already changed. Eventual consistency is the promise that the window closes -- not that it doesn''t exist.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-event-driven-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"eventual-consistency-sim"}'::jsonb, '{"xp":234,"credits":45}'::jsonb, false, 5),
  ('mission-be-event-driven-06', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-1', 'dual-write-failure', 'Dual-Write Failure', 'This is the incident, stripped to its actual shape: the orders service wrote its own database, then tried to publish an event -- two separate operations, two separate chances to fail, and nothing forcing them to succeed or fail together.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-event-driven-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"dual-write-failure-sim"}'::jsonb, '{"xp":236,"credits":46}'::jsonb, false, 6),
  ('mission-be-event-driven-07', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'transactional-outbox', 'Transactional Outbox', 'The fix for a dual write isn''t "try harder to publish." It''s removing the second network call from the equation: write the event to a table in the exact same database transaction as the business write, then let a separate relay publish it whenever it can.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-event-driven-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"transactional-outbox-sim"}'::jsonb, '{"xp":237,"credits":46}'::jsonb, false, 7),
  ('mission-be-event-driven-08', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'inbox-pattern', 'Inbox Pattern', 'An outbox makes sure an event actually gets published. It says nothing about what happens when a consumer receives that same event twice -- because on an unreliable network, "at least once" delivery is the honest promise, and "exactly once" processing is something you build yourself.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-event-driven-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"inbox-pattern-sim"}'::jsonb, '{"xp":238,"credits":46}'::jsonb, false, 8),
  ('mission-be-event-driven-09', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'change-data-capture', 'Change Data Capture Concepts', 'CDC skips the outbox table entirely by reading the database''s own transaction log and turning every row change into an event automatically -- the application never calls publish() at all, it just writes to the database like normal.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-event-driven-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"change-data-capture-sim"}'::jsonb, '{"xp":240,"credits":46}'::jsonb, false, 9),
  ('mission-be-event-driven-10', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'saga-pattern', 'Saga Pattern', 'A single database transaction can''t span three services. A saga is what replaces it: a sequence of local transactions, each with its own event, and a defined way to undo everything that already happened if a later step fails.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-event-driven-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"saga-pattern-sim"}'::jsonb, '{"xp":241,"credits":47}'::jsonb, false, 10),
  ('mission-be-event-driven-11', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'compensating-transactions', 'Compensating Transactions', 'You can''t roll back a card charge the way you roll back a database transaction -- the money already moved. A compensating transaction is the deliberate, business-meaningful action that undoes the effect, not the operation.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-event-driven-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"compensating-transactions-sim"}'::jsonb, '{"xp":242,"credits":47}'::jsonb, false, 11),
  ('mission-be-event-driven-12', 'world-be-event-driven', 'campaign-be-event-driven', 'operation-be-event-driven-2', 'the-lost-order', 'The Lost Order', 'The dispatch order that opened this Act, laid bare: a database write that succeeded, an event publish that silently didn''t, and eleven missions'' worth of lessons about to be tested at once.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-event-driven-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"lost-order-boss-sim"}'::jsonb, '{"xp":537,"credits":124,"badgeIds":["lost-order"],"skillXp":{"messaging":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be-event-driven-01', 1, 'mira', 'The audit stream taught us how to move data reliably. This Act asks a sharper question: does every service that reacts to something even agree on what "reacting" means?'),
  ('mission-be-event-driven-01', 2, 'forge', 'Case in point -- a dispatch order from last week. Orders service logged it "confirmed." Fulfillment logged it "never received." Both logs are honest. Neither one is wrong. That should worry you.'),
  ('mission-be-event-driven-01', 3, 'mira', 'It starts with a word we throw around too loosely: "event." Before we untangle the incident, you need to know exactly what separates an event from a command -- the rest of this Act depends on getting that right.'),
  ('mission-be-event-driven-02', 1, 'forge', 'Publish/subscribe is the mechanism behind "event, not command." A publisher writes to a topic. It has no idea who''s subscribed, how many subscribers there are, or whether any of them are even running right now.'),
  ('mission-be-event-driven-02', 2, 'forge', 'That''s the whole appeal -- orders doesn''t need to know fulfillment exists. It also means orders has no way to know if fulfillment missed something.'),
  ('mission-be-event-driven-03', 1, 'mira', 'Choreography is what pub/sub looks like at the system level: OrderPlaced triggers Payment, PaymentCompleted triggers Fulfillment, FulfillmentStarted triggers Notification. Nobody''s in charge. Everybody just reacts.'),
  ('mission-be-event-driven-03', 2, 'mira', 'It scales beautifully, and it''s nearly impossible to look at and answer "what''s the whole flow, actually" -- because that flow only exists as the sum of every service''s independent reactions.'),
  ('mission-be-event-driven-04', 1, 'forge', 'Orchestration flips it: one orchestrator calls payment, waits, calls fulfillment, waits, calls notification. It knows the entire flow because it wrote the entire flow.'),
  ('mission-be-event-driven-04', 2, 'forge', 'The cost is coupling. The orchestrator has to know about every service it calls. Take it down, and nothing new gets fulfilled -- even if every downstream service is perfectly healthy.'),
  ('mission-be-event-driven-05', 1, 'mira', 'Choreographed or orchestrated, the moment a system starts reacting to events instead of blocking on requests, it stops being consistent in the instant sense. Fulfillment doesn''t know about an order the microsecond it''s placed -- it knows a little later, once its event arrives.'),
  ('mission-be-event-driven-05', 2, 'mira', 'That gap has a name: eventual consistency. The system is guaranteed to agree eventually. It says nothing about how long "eventually" takes, or what a user sees while they''re waiting.'),
  ('mission-be-event-driven-06', 1, 'mira', 'Here''s the shape of the actual incident, stripped down to the two operations that matter.'),
  ('mission-be-event-driven-06', 2, 'forge', 'Write to the orders database. Publish OrderConfirmed to the broker. Two separate systems, two separate network calls, and nothing forcing them to succeed or fail together.'),
  ('mission-be-event-driven-06', 3, 'mira', 'That''s a dual write. It''s not a rare mistake -- it''s the default shape of "save data, then tell everyone" unless you go out of your way to prevent it.'),
  ('mission-be-event-driven-07', 1, 'forge', 'The fix for a dual write isn''t "try the publish harder." It''s the outbox pattern: write the event to a table in the exact same database transaction as the business write. Either both rows exist, or neither does.'),
  ('mission-be-event-driven-07', 2, 'forge', 'A separate relay process picks up outbox rows and publishes them, retrying forever if it has to. The business transaction is never blocked on the broker being reachable.'),
  ('mission-be-event-driven-08', 1, 'mira', 'Outbox handles the sending side. The inbox pattern handles receiving: record every event id you''ve already processed, and check that table before doing the work -- not after.'),
  ('mission-be-event-driven-08', 2, 'mira', 'Networks retry. Brokers redeliver. A consumer that isn''t idempotent will double-charge, double-ship, double-email, all while insisting each request was brand new.'),
  ('mission-be-event-driven-09', 1, 'forge', 'Change data capture reads the database''s own transaction log and turns row changes into a stream of events. The application never calls publish() at all -- it just writes to the database like normal, and CDC notices.'),
  ('mission-be-event-driven-09', 2, 'forge', 'That sidesteps the dual-write problem structurally. There''s only one write, to the database, and the event is derived from it after the fact, guaranteed to reflect exactly what was committed.'),
  ('mission-be-event-driven-10', 1, 'mira', 'Some operations are bigger than one dual-write. Booking a trip means reserving a flight, charging a card, and booking a hotel -- three services, three databases, no transaction that can span all three.'),
  ('mission-be-event-driven-10', 2, 'mira', 'A saga replaces one big transaction with a sequence of local transactions, each publishing its own event to trigger the next step -- and, critically, each with a defined way to undo itself if a later step fails.'),
  ('mission-be-event-driven-11', 1, 'forge', 'A database rollback undoes work nobody outside the transaction ever saw. A compensating transaction is different: the original action already had a visible effect on the outside world, so undoing it takes a whole new action, not just discarding a change.'),
  ('mission-be-event-driven-11', 2, 'forge', '"Refund the charge" is not the same operation as "don''t charge." It has its own logic, its own failure modes -- and sometimes it can''t fully undo the original action at all. Ask anyone who''s tried to un-ship a package.'),
  ('mission-be-event-driven-12', 1, 'mira', 'Everything this Act taught leads here. The dispatch order from day one -- confirmed in orders, never received in fulfillment. Both true. Let''s finally find out why.'),
  ('mission-be-event-driven-12', 2, 'forge', 'I pulled the orders-service code from the night of the incident, and the logs from the exact minute it happened. Walk through both with me.'),
  ('mission-be-event-driven-12', 3, 'mira', 'Don''t just diagnose it. Tell me the one fix that actually closes the gap for good -- not the ones that just make the symptom quieter.'),
  ('mission-be-event-driven-12', 4, 'forge', 'Outbox table''s live now, built fresh for this fix. ...and there''s already a row in it that shouldn''t be there. Four months old, from before this table even existed -- some ad-hoc script wrote it. Destination topic: "dispatch//fulfillment." Doubled slash.'),
  ('mission-be-event-driven-12', 5, 'mira', 'Unrelated to tonight. Noted anyway -- file it, tag it, same pattern we''ve been finding all Arc. We''re not chasing it today.'),
  ('mission-be-event-driven-12', 6, 'forge', 'What we are doing is making sure no order goes missing like this again. Outbox is live, and it''s not going anywhere.'),
  ('mission-be-event-driven-12', 7, 'mira', 'Every service in this system reacts to events now, not requests. Which means nobody can point to one place anymore that shows what actually happened, in order, across all of them. That''s the next problem. Not today''s.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be-event-driven-01-o1', 'mission-be-event-driven-01', 1, 'Command or event?', 'Sort each message into command or event.'),
  ('mission-be-event-driven-01-o2', 'mission-be-event-driven-01', 2, 'Read the incident', 'Find the evidence that shows the orders service was publishing an event, not issuing a command.'),
  ('mission-be-event-driven-02-o1', 'mission-be-event-driven-02', 1, 'Order the pub/sub flow', 'Put the publish/subscribe flow in the order it actually happens.'),
  ('mission-be-event-driven-02-o2', 'mission-be-event-driven-02', 2, 'Find the blind spot', 'Find the evidence that explains how a missing subscriber goes unnoticed for weeks.'),
  ('mission-be-event-driven-03-o1', 'mission-be-event-driven-03', 1, 'Trace the chain', 'Order the choreography reaction chain that fulfills an order.'),
  ('mission-be-event-driven-03-o2', 'mission-be-event-driven-03', 2, 'Name the tradeoff', 'State what a pure choreography design costs you in exchange for its independence.'),
  ('mission-be-event-driven-04-o1', 'mission-be-event-driven-04', 1, 'Spot the coupling', 'Identify the failure mode that''s unique to orchestration.'),
  ('mission-be-event-driven-04-o2', 'mission-be-event-driven-04', 2, 'Weigh the tradeoffs', 'Sort each tradeoff into choreography or orchestration.'),
  ('mission-be-event-driven-05-o1', 'mission-be-event-driven-05', 1, 'Explain the lag', 'Find the evidence that explains a stale read without anything being broken.'),
  ('mission-be-event-driven-06-o1', 'mission-be-event-driven-06', 1, 'Find the dual write', 'Identify the line where the database and the event can permanently disagree.'),
  ('mission-be-event-driven-06-o2', 'mission-be-event-driven-06', 2, 'Confirm the silent failure', 'Find the evidence that the publish failure was caught, but never handled.'),
  ('mission-be-event-driven-07-o1', 'mission-be-event-driven-07', 1, 'Order the outbox flow', 'Put the transactional outbox flow in the order it actually happens.'),
  ('mission-be-event-driven-07-o2', 'mission-be-event-driven-07', 2, 'Find the broken guarantee', 'Identify the line that writes the outbox row outside the transaction meant to protect it.'),
  ('mission-be-event-driven-08-o1', 'mission-be-event-driven-08', 1, 'Find the missing idempotency check', 'Identify the line that needs an idempotency check before it runs.'),
  ('mission-be-event-driven-08-o2', 'mission-be-event-driven-08', 2, 'Pick the correct pattern', 'Choose the correct inbox-pattern fix for a handler that isn''t idempotent.'),
  ('mission-be-event-driven-09-o1', 'mission-be-event-driven-09', 1, 'Name what CDC reads', 'Identify what change data capture actually reads to produce its events.'),
  ('mission-be-event-driven-09-o2', 'mission-be-event-driven-09', 2, 'Sort outbox vs CDC', 'Sort each tradeoff into the outbox pattern or change data capture.'),
  ('mission-be-event-driven-10-o1', 'mission-be-event-driven-10', 1, 'Order the saga', 'Order a saga''s steps, including its compensations, after a late failure.'),
  ('mission-be-event-driven-10-o2', 'mission-be-event-driven-10', 2, 'Name the coordination style', 'Identify what determines whether a given saga is choreographed or orchestrated.'),
  ('mission-be-event-driven-11-o1', 'mission-be-event-driven-11', 1, 'Match the compensation', 'Match each original action to its compensating transaction.'),
  ('mission-be-event-driven-11-o2', 'mission-be-event-driven-11', 2, 'Spot the incomplete compensation', 'Find the evidence that shows a compensation that can''t fully undo the original action.'),
  ('mission-be-event-driven-12-o1', 'mission-be-event-driven-12', 1, 'Diagnose the dual-write', 'Find the evidence that''s the actual root cause, not just a symptom of it.'),
  ('mission-be-event-driven-12-o2', 'mission-be-event-driven-12', 2, 'Pick the real fix', 'Choose the one fix that actually closes the gap for good.'),
  ('mission-be-event-driven-12-o3', 'mission-be-event-driven-12', 3, 'File the anomaly', 'Decide what''s worth flagging even though it isn''t part of tonight''s incident.'),
  ('mission-be-event-driven-12-o4', 'mission-be-event-driven-12', 4, 'Close the incident', 'State the one architectural rule that closes this incident for good.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be-event-driven-01-o1-c1', 'mission-be-event-driven-01-o1', 1, 'drag_and_drop', 'Sort each message into command or event.', '{"items":[{"id":"i1","text":"ChargeCustomer -- please charge this customer $40 now"},{"id":"i2","text":"OrderPlaced -- a customer placed order #4471"},{"id":"i3","text":"CancelShipment -- cancel shipment #88 immediately"},{"id":"i4","text":"PaymentFailed -- payment for order #4471 did not go through"},{"id":"i5","text":"SendConfirmationEmail -- send this exact email to this exact address"}],"targets":[{"id":"t1","label":"Command (names the action to take, expects a response)"},{"id":"t2","label":"Event (announces something that already happened, expects nothing back)"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2","i5":"t1"}}'::jsonb),
  ('mission-be-event-driven-01-o2-c1', 'mission-be-event-driven-01-o2', 1, 'investigation', 'Which evidence shows the orders service is publishing an event, not issuing a command?', '{"evidence":[{"id":"ev1","label":"Orders service log","detail":"Wrote order #4471 to its own database, then published OrderConfirmed and moved on -- no code path waits for fulfillment to respond."},{"id":"ev2","label":"Fulfillment service log","detail":"No OrderConfirmed message for #4471 ever arrived in fulfillment''s queue."},{"id":"ev3","label":"API contract","detail":"POST /orders returns 201 Created the moment the order row is written, before any downstream service is even contacted."}],"question":"Which evidence shows the orders service is publishing an event, not issuing a command -- and expecting nothing back?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be-event-driven-02-o1-c1', 'mission-be-event-driven-02-o1', 1, 'interactive_diagram', 'Order the pub/sub flow from publish to independent processing.', '{"diagramId":"pub-sub-flow","hotspots":[{"id":"publish","label":"Publisher writes an event to a topic","explanation":"The publisher''s job ends here -- it does not address the message to any specific subscriber."},{"id":"broker","label":"Message broker stores and routes the event","explanation":"The broker holds the topic and delivers to whoever is currently subscribed."},{"id":"subscribe","label":"Subscribers receive their own copy","explanation":"Each subscriber gets the event independently; one subscriber succeeding says nothing about another."},{"id":"process","label":"Each subscriber processes independently","explanation":"A slow or failing subscriber does not block the publisher or any other subscriber."}],"task":"Order the pub/sub flow from publish to independent processing."}'::jsonb, '{"correctOrderIds":["publish","broker","subscribe","process"]}'::jsonb),
  ('mission-be-event-driven-02-o2-c1', 'mission-be-event-driven-02-o2', 1, 'investigation', 'Which evidence explains how a missing subscriber goes unnoticed for weeks?', '{"evidence":[{"id":"ev1","label":"Broker subscription list","detail":"The orders topic has 4 registered subscribers; fulfillment unsubscribed silently after a deploy 3 weeks ago and was never re-added."},{"id":"ev2","label":"Publisher code","detail":"orders service calls publish(event) and never checks a subscriber count or expects a return value."},{"id":"ev3","label":"Monitoring dashboard","detail":"Topic publish-throughput graph looks completely normal -- publish volume never dropped."}],"question":"Which two pieces of evidence together explain how this goes unnoticed for weeks?"}'::jsonb, '{"requiredEvidenceIds":["ev2","ev3"]}'::jsonb),

  ('mission-be-event-driven-03-o1-c1', 'mission-be-event-driven-03-o1', 1, 'interactive_diagram', 'Order the choreography reaction chain that fulfills an order.', '{"diagramId":"choreography-chain","hotspots":[{"id":"order_placed","label":"OrderPlaced published by the orders service","explanation":"The chain''s only trigger -- nothing downstream was asked to run, it just reacts."},{"id":"payment_reacts","label":"Payment service reacts, charges the customer, publishes PaymentCompleted","explanation":"Payment only knows it should react to OrderPlaced -- it has no idea who reacts to it next."},{"id":"fulfillment_reacts","label":"Fulfillment service reacts to PaymentCompleted, publishes FulfillmentStarted","explanation":"Fulfillment never talked to orders directly -- it only ever heard from payment''s event."},{"id":"notification_reacts","label":"Notification service reacts to FulfillmentStarted and emails the customer","explanation":"The last link in the chain, with no idea any of the earlier services exist."}],"task":"Order the choreography reaction chain that fulfills an order."}'::jsonb, '{"correctOrderIds":["order_placed","payment_reacts","fulfillment_reacts","notification_reacts"]}'::jsonb),
  ('mission-be-event-driven-03-o2-c1', 'mission-be-event-driven-03-o2', 1, 'multiple_choice', 'A new engineer asks "where''s the code that defines the whole order-fulfillment flow?" What''s the honest answer in a pure choreography design?', '{"question":"A new engineer asks \"where''s the code that defines the whole order-fulfillment flow?\" What''s the honest answer in a pure choreography design?","options":[{"id":"a","text":"In the orders service, at the top"},{"id":"b","text":"There isn''t one file -- the flow only exists as the sum of every service''s independent event reactions, scattered across services"},{"id":"c","text":"In the message broker''s configuration"},{"id":"d","text":"In a shared library every service imports"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be-event-driven-04-o1-c1', 'mission-be-event-driven-04-o1', 1, 'multiple_choice', 'Which failure mode is unique to orchestration and doesn''t apply to a pure choreography design?', '{"question":"Which failure mode is unique to orchestration and doesn''t apply to a pure choreography design?","options":[{"id":"a","text":"A single service crashing can silently stop new work from progressing, because the ability to see and drive the whole flow lives in one place"},{"id":"b","text":"Services can''t communicate with each other"},{"id":"c","text":"Events can''t be published more than once"},{"id":"d","text":"Nothing -- they have exactly the same failure modes"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-be-event-driven-04-o2-c1', 'mission-be-event-driven-04-o2', 1, 'drag_and_drop', 'Sort each tradeoff into choreography or orchestration.', '{"items":[{"id":"c1","text":"No single point of coordination failure"},{"id":"c2","text":"The whole flow is visible in one place"},{"id":"c3","text":"Hard to answer \"what happens end to end\" by reading code"},{"id":"c4","text":"Adding a new step means touching the central coordinator"}],"targets":[{"id":"choreography","label":"Choreography"},{"id":"orchestration","label":"Orchestration"}]}'::jsonb, '{"correctMapping":{"c1":"choreography","c2":"orchestration","c3":"choreography","c4":"orchestration"}}'::jsonb),

  ('mission-be-event-driven-05-o1-c1', 'mission-be-event-driven-05-o1', 1, 'investigation', 'A customer refreshes their order page one second after placing it and sees "pending," not "confirmed" -- even though the order really was confirmed. Which evidence explains this without anything being broken?', '{"evidence":[{"id":"ev1","label":"Orders database","detail":"order #5521 status = confirmed, committed 400ms ago"},{"id":"ev2","label":"Read-model database (used by the order page)","detail":"order #5521 status = pending, last updated 1.2s ago, still waiting on the OrderConfirmed event"},{"id":"ev3","label":"Event broker lag metric","detail":"Average end-to-end event delivery lag: 600-900ms under current load"}],"question":"Which evidence shows the order page isn''t wrong, just reading a copy that hasn''t caught up yet?"}'::jsonb, '{"requiredEvidenceIds":["ev2","ev3"]}'::jsonb),

  ('mission-be-event-driven-06-o1-c1', 'mission-be-event-driven-06-o1', 1, 'code_debugging', 'If eventBus.publish throws after the update already committed, which line is where the database and the event can permanently disagree?', '{"language":"typescript","code":"async function confirmOrder(orderId: string) {\n  await db.orders.update(orderId, { status: \"confirmed\" });\n  await eventBus.publish(\"OrderConfirmed\", { orderId });\n}","question":"If eventBus.publish throws after the update already committed, which line is where the database and the event can permanently disagree?"}'::jsonb, '{"requiredLineIds":["  await eventBus.publish(\"OrderConfirmed\", { orderId });"]}'::jsonb),
  ('mission-be-event-driven-06-o2-c1', 'mission-be-event-driven-06-o2', 1, 'investigation', 'Which evidence shows the publish failure was caught, but never handled?', '{"evidence":[{"id":"ev1","label":"Orders database","detail":"order #4471 status = confirmed, transaction log shows a clean commit"},{"id":"ev2","label":"Broker ingest log","detail":"No publish attempt for order #4471 appears anywhere in the broker''s ingest log -- the call never even reached the broker"},{"id":"ev3","label":"Application error log","detail":"orders-service, 04:12:03 -- ECONNRESET calling event-broker:9092, caught by an empty catch block, never logged, never retried"}],"question":"Which evidence shows the publish failure was caught, but never handled?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be-event-driven-07-o1-c1', 'mission-be-event-driven-07-o1', 1, 'interactive_diagram', 'Order the transactional outbox flow.', '{"diagramId":"outbox-flow","hotspots":[{"id":"begin_txn","label":"Begin one database transaction","explanation":"Everything that follows either all commits together or all rolls back together."},{"id":"write_business_row","label":"Write the business row (e.g. the orders table)","explanation":"The actual state change the operation is meant to make."},{"id":"write_outbox_row","label":"Write a row to the outbox table describing the event, same transaction","explanation":"Recording intent to publish, guaranteed to exist if and only if the business row does."},{"id":"commit_txn","label":"Commit -- both rows exist, or neither does","explanation":"The atomicity guarantee the dual write never had."},{"id":"relay_reads","label":"A separate relay process reads unpublished outbox rows","explanation":"Runs independently of the request, on its own schedule."},{"id":"relay_publishes","label":"Relay publishes each event to the broker and marks it published","explanation":"Retries as long as it takes -- the business transaction already succeeded and is never blocked on this step."}],"task":"Order the transactional outbox flow."}'::jsonb, '{"correctOrderIds":["begin_txn","write_business_row","write_outbox_row","commit_txn","relay_reads","relay_publishes"]}'::jsonb),
  ('mission-be-event-driven-07-o2-c1', 'mission-be-event-driven-07-o2', 1, 'code_debugging', 'This is meant to be a transactional outbox, but the guarantee is broken. Which line writes the outbox row outside the transaction that''s supposed to protect it?', '{"language":"typescript","code":"async function confirmOrder(orderId: string) {\n  await db.transaction(async (tx) => {\n    await tx.orders.update(orderId, { status: \"confirmed\" });\n  });\n  await db.outbox.insert({ type: \"OrderConfirmed\", payload: { orderId } });\n}","question":"This is meant to be a transactional outbox, but the guarantee is broken. Which line writes the outbox row outside the transaction that''s supposed to protect it?"}'::jsonb, '{"requiredLineIds":["  await db.outbox.insert({ type: \"OrderConfirmed\", payload: { orderId } });"]}'::jsonb),

  ('mission-be-event-driven-08-o1-c1', 'mission-be-event-driven-08-o1', 1, 'code_debugging', 'This handler will ship and notify twice if the broker redelivers the same event id. Which line is missing an idempotency check before it, and would need one added?', '{"language":"typescript","code":"async function handleOrderConfirmed(event: OrderConfirmedEvent) {\n  await shipments.create({ orderId: event.orderId });\n  await notifications.send(event.orderId, \"Your order shipped!\");\n}","question":"This handler will ship and notify twice if the broker redelivers the same event id. Which line is missing an idempotency check before it, and would need one added?"}'::jsonb, '{"requiredLineIds":["  await shipments.create({ orderId: event.orderId });"]}'::jsonb),
  ('mission-be-event-driven-08-o2-c1', 'mission-be-event-driven-08-o2', 1, 'multiple_choice', 'Which of these is the correct inbox-pattern fix for the shipments handler above?', '{"question":"Which of these is the correct inbox-pattern fix for the shipments handler above?","options":[{"id":"a","text":"Check event.id against a table of already-processed event ids inside the same transaction as creating the shipment, and skip the work if it''s already present"},{"id":"b","text":"Retry the handler faster so duplicates are less likely to land close together"},{"id":"c","text":"Ask the publisher to promise it will never redeliver, ever"},{"id":"d","text":"Ignore it -- shipping an order twice is rare enough not to matter"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-be-event-driven-09-o1-c1', 'mission-be-event-driven-09-o1', 1, 'multiple_choice', 'What does change data capture actually read to produce its events?', '{"question":"What does change data capture actually read to produce its events?","options":[{"id":"a","text":"The application''s HTTP access logs"},{"id":"b","text":"The database''s transaction/write-ahead log -- the same internal log used for replication and crash recovery"},{"id":"c","text":"A polling query run against the table every second"},{"id":"d","text":"The outbox table, same as the outbox pattern"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be-event-driven-09-o2-c1', 'mission-be-event-driven-09-o2', 1, 'drag_and_drop', 'Sort each tradeoff into the outbox pattern or change data capture.', '{"items":[{"id":"d1","text":"Application code has to remember to write the outbox row"},{"id":"d2","text":"No application code changes needed at all"},{"id":"d3","text":"Requires infrastructure that can read the database''s internal log format"},{"id":"d4","text":"Event schema is exactly whatever the application explicitly wrote to a table"}],"targets":[{"id":"outbox","label":"Transactional outbox"},{"id":"cdc","label":"Change data capture"}]}'::jsonb, '{"correctMapping":{"d1":"outbox","d2":"cdc","d3":"cdc","d4":"outbox"}}'::jsonb),

  ('mission-be-event-driven-10-o1-c1', 'mission-be-event-driven-10-o1', 1, 'interactive_diagram', 'Order a saga''s steps, including its compensations, after a late failure.', '{"diagramId":"saga-flow","hotspots":[{"id":"reserve_flight","label":"Reserve the flight seat (local transaction, publishes FlightReserved)","explanation":"The first local transaction -- committed on its own, with no lock held on any other service."},{"id":"charge_card","label":"Charge the customer''s card (local transaction, publishes PaymentCharged)","explanation":"Reacts to FlightReserved -- its own local transaction, its own event."},{"id":"book_hotel_fails","label":"Book the hotel room -- fails, no room available","explanation":"The step that breaks the saga and triggers compensation for everything already done."},{"id":"compensate_payment","label":"Compensating transaction: refund the card charge","explanation":"Undoes the payment step''s visible effect, since the charge itself can''t be un-committed."},{"id":"compensate_flight","label":"Compensating transaction: release the reserved flight seat","explanation":"Undoes the first step last, unwinding the saga in reverse order."}],"task":"Order a saga''s steps, including its compensations, after a late failure."}'::jsonb, '{"correctOrderIds":["reserve_flight","charge_card","book_hotel_fails","compensate_payment","compensate_flight"]}'::jsonb),
  ('mission-be-event-driven-10-o2-c1', 'mission-be-event-driven-10-o2', 1, 'multiple_choice', 'A saga can be implemented as a chain of services each reacting to the previous step''s event, or as one saga orchestrator calling each step directly. What determines which coordination pattern a given saga is using?', '{"question":"A saga can be implemented as a chain of services each reacting to the previous step''s event, or as one saga orchestrator calling each step directly. What determines which coordination pattern a given saga is using?","options":[{"id":"a","text":"Whether there''s a central process that knows the whole saga and calls each step, versus every step reacting only to the event before it"},{"id":"b","text":"Whether the saga uses Kafka or RabbitMQ underneath"},{"id":"c","text":"Sagas can only ever be choreographed"},{"id":"d","text":"Sagas can only ever be orchestrated"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-be-event-driven-11-o1-c1', 'mission-be-event-driven-11-o1', 1, 'drag_and_drop', 'Match each original action to its compensating transaction.', '{"items":[{"id":"i1","text":"ChargeCard $400"},{"id":"i2","text":"ReserveSeat 14B"},{"id":"i3","text":"CreateShipment #881"},{"id":"i4","text":"SendWelcomeEmail"}],"targets":[{"id":"t1","label":"RefundCharge $400"},{"id":"t2","label":"ReleaseSeat 14B"},{"id":"t3","label":"CancelShipment #881 (only if not yet dispatched)"},{"id":"t4","label":"No true compensation exists -- send a correction email instead"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),
  ('mission-be-event-driven-11-o2-c1', 'mission-be-event-driven-11-o2', 1, 'investigation', 'Which evidence shows a compensating transaction that genuinely cannot undo the original action?', '{"evidence":[{"id":"ev1","label":"Shipment status","detail":"Shipment #881 status = \"in transit,\" left the warehouse 40 minutes ago"},{"id":"ev2","label":"Compensation attempt log","detail":"CancelShipment #881 was called; the warehouse system returned \"cannot cancel, already dispatched\""},{"id":"ev3","label":"Saga state","detail":"Saga step 3 (shipment) marked failed-to-compensate, flagged for manual handling"}],"question":"Which evidence shows a compensating transaction that genuinely cannot undo the original action?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be-event-driven-12-o1-c1', 'mission-be-event-driven-12-o1', 1, 'investigation', 'Which evidence is the actual root cause, not just a symptom of it?', '{"evidence":[{"id":"ev1","label":"Orders service code","detail":"confirmOrder() writes the order row, then calls eventBus.publish(...) as a separate step, with no shared transaction between the two"},{"id":"ev2","label":"Application logs","detail":"04:12:03 -- order #4471 committed. 04:12:03 -- eventBus.publish threw ECONNRESET, caught by an empty catch block, never logged, never retried"},{"id":"ev3","label":"Fulfillment service","detail":"No OrderConfirmed event for #4471 ever arrived -- fulfillment has no record the order exists"}],"question":"Which evidence is the actual root cause, not just a symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),
  ('mission-be-event-driven-12-o2-c1', 'mission-be-event-driven-12-o2', 1, 'multiple_choice', 'Three fixes are on the table besides the right one. Which one actually closes the gap for good?', '{"question":"Three fixes are on the table besides the right one. Which one actually closes the gap for good?","options":[{"id":"a","text":"Retry the publish call a few times and hope the network blip doesn''t happen again"},{"id":"b","text":"Publish the event first, then write to the database"},{"id":"c","text":"Add more logging around the publish call so it''s easier to notice next time"},{"id":"d","text":"Write the event to an outbox table in the same database transaction as the order write, and let a separate relay process publish it, retrying until it succeeds"}]}'::jsonb, '{"correctOptionId":"d"}'::jsonb),
  ('mission-be-event-driven-12-o3-c1', 'mission-be-event-driven-12-o3', 1, 'investigation', 'Which evidence is worth flagging and filing, even though it isn''t part of tonight''s incident?', '{"evidence":[{"id":"ev1","label":"New outbox table (populated while building the fix)","detail":"One row, created four months before this table existed, written by an old ad-hoc retry script: destination_topic = \"dispatch//fulfillment\", published = false, untouched since"},{"id":"ev2","label":"Topic registry","detail":"No topic named \"dispatch//fulfillment\" was ever intentionally created -- the correct topic is \"dispatch/fulfillment\""},{"id":"ev3","label":"Incident timeline","detail":"This row predates tonight''s incident by four months and is unrelated to order #4471"}],"question":"Which evidence is worth flagging and filing, even though it isn''t part of tonight''s incident?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),
  ('mission-be-event-driven-12-o4-c1', 'mission-be-event-driven-12-o4', 1, 'boss_encounter', 'Having found the root cause, picked the real fix, and filed the anomaly, state the one architectural rule that closes this incident for good.', '{"stages":[{"objectiveRef":"mission-be-event-driven-12-o1","label":"The root cause"},{"objectiveRef":"mission-be-event-driven-12-o2","label":"The right fix"},{"objectiveRef":"mission-be-event-driven-12-o3","label":"The filed anomaly"}],"task":"Having found the root cause, picked the real fix, and filed the anomaly, state the one architectural rule that closes this incident for good: a business write and the event announcing it must commit together, in one transaction, or the event does not get to happen at all."}'::jsonb, '{"requiredObjectiveIds":["mission-be-event-driven-12-o1","mission-be-event-driven-12-o2","mission-be-event-driven-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be-event-driven-01-o1-c1', 'orientation', 'One of these expects a reply that changes what happens next. The other one doesn''t care if anyone''s listening.', 10, 1),
  ('mission-be-event-driven-01-o1-c1', 'concept', 'A command is named as an instruction, imperative, verb-first. An event is named as a fact that already happened, usually past tense.', 20, 2),
  ('mission-be-event-driven-01-o1-c1', 'solution', 'i1, i3, i5 are commands (ChargeCustomer, CancelShipment, SendConfirmationEmail); i2 and i4 are events (OrderPlaced, PaymentFailed) -- both already-happened facts.', 30, 3),
  ('mission-be-event-driven-01-o2-c1', 'orientation', 'Look for the line that shows nobody was ever going to wait for an answer.', 10, 1),
  ('mission-be-event-driven-01-o2-c1', 'solution', 'ev1 -- the write commits, the event publishes, and the code moves on. That''s the entire shape of "fire an event," and it''s also exactly why nobody noticed the publish had failed.', 20, 2),

  ('mission-be-event-driven-02-o1-c1', 'orientation', 'The publisher''s part of the story ends well before anyone actually does the work an event triggers.', 10, 1),
  ('mission-be-event-driven-02-o1-c1', 'solution', 'Publish, then the broker stores and routes it, then each subscriber receives its own copy, then each processes it independently.', 20, 2),
  ('mission-be-event-driven-02-o2-c1', 'orientation', 'One entry shows the actual cause. One shows why the cause went unnoticed. Neither alone explains "unnoticed for weeks."', 10, 1),
  ('mission-be-event-driven-02-o2-c1', 'solution', 'ev2 -- the publisher never checks who''s listening -- and ev3 -- the dashboard measures publish volume, not delivery, so a missing subscriber never shows up on it.', 20, 2),

  ('mission-be-event-driven-03-o1-c1', 'orientation', 'Each service in this chain only knows about the event immediately before it -- not the one that started everything.', 10, 1),
  ('mission-be-event-driven-03-o1-c1', 'solution', 'OrderPlaced, then payment reacts and publishes PaymentCompleted, then fulfillment reacts and publishes FulfillmentStarted, then notification reacts last.', 20, 2),
  ('mission-be-event-driven-03-o2-c1', 'orientation', 'Ask where you''d have to look, across how many files, to answer that question honestly.', 10, 1),
  ('mission-be-event-driven-03-o2-c1', 'solution', 'There is no single file -- the flow is only ever the sum of every service''s independent reactions, which is exactly choreography''s tradeoff for its independence.', 20, 2),

  ('mission-be-event-driven-04-o1-c1', 'orientation', 'Ask what happens to new work if the one process that knows the whole flow goes down.', 10, 1),
  ('mission-be-event-driven-04-o1-c1', 'solution', 'The orchestrator becomes a single point of coordination failure -- every downstream service can be healthy and idle, waiting on a call that never comes.', 20, 2),
  ('mission-be-event-driven-04-o2-c1', 'orientation', 'Visibility and coupling trade against each other in exactly opposite directions here.', 10, 1),
  ('mission-be-event-driven-04-o2-c1', 'solution', 'c1 and c3 describe choreography''s independence and its opacity; c2 and c4 describe orchestration''s visibility and its coupling to a central coordinator.', 20, 2),

  ('mission-be-event-driven-05-o1-c1', 'orientation', 'Two different stores can both be telling the truth about two different points in time.', 10, 1),
  ('mission-be-event-driven-05-o1-c1', 'concept', 'Eventual consistency guarantees the gap closes -- it never promises the gap doesn''t exist in the meantime.', 20, 2),
  ('mission-be-event-driven-05-o1-c1', 'solution', 'ev2 shows the read model is still waiting on the event, and ev3 shows why: normal delivery lag under load, not a bug in either store.', 30, 3),

  ('mission-be-event-driven-06-o1-c1', 'orientation', 'The database write and the event publish are two separate lines with nothing tying their outcomes together.', 10, 1),
  ('mission-be-event-driven-06-o1-c1', 'concept', 'The update already committed by the time the second line runs -- whatever happens to that second line, the first one can''t be undone.', 20, 2),
  ('mission-be-event-driven-06-o1-c1', 'solution', 'The publish line -- if it throws, the order is already confirmed in the database and nothing rolls that back.', 30, 3),
  ('mission-be-event-driven-06-o2-c1', 'orientation', 'A failure that''s truly silent has to be caught somewhere and then simply dropped.', 10, 1),
  ('mission-be-event-driven-06-o2-c1', 'solution', 'ev3 -- an empty catch block swallows the ECONNRESET with no log line and no retry, which is exactly how a real failure produces zero evidence anywhere else.', 20, 2),

  ('mission-be-event-driven-07-o1-c1', 'orientation', 'Nothing about the relay process is allowed to affect whether the business transaction commits.', 10, 1),
  ('mission-be-event-driven-07-o1-c1', 'solution', 'Begin the transaction, write the business row, write the outbox row, commit both together, then a separate relay reads and publishes unpublished rows.', 20, 2),
  ('mission-be-event-driven-07-o2-c1', 'orientation', 'Compare where the transaction actually opens and closes against where the outbox write happens.', 10, 1),
  ('mission-be-event-driven-07-o2-c1', 'concept', 'db.transaction(...) already returned and committed by the time the next line runs -- anything after that point is unprotected.', 20, 2),
  ('mission-be-event-driven-07-o2-c1', 'solution', 'The db.outbox.insert(...) call happens after the transaction block has already closed, so it has exactly the same dual-write risk the outbox pattern was supposed to remove.', 30, 3),

  ('mission-be-event-driven-08-o1-c1', 'orientation', 'Nothing in this handler asks "have I already done this for this event id?"', 10, 1),
  ('mission-be-event-driven-08-o1-c1', 'solution', 'The shipments.create(...) call -- it needs an idempotency check against the event id before it, or a redelivered event creates a second shipment.', 20, 2),
  ('mission-be-event-driven-08-o2-c1', 'orientation', 'The check and the side effect it guards need to succeed or fail together.', 10, 1),
  ('mission-be-event-driven-08-o2-c1', 'solution', 'Record the event id in an inbox table in the same transaction as the shipment write, and skip the work entirely if that id is already there.', 20, 2),

  ('mission-be-event-driven-09-o1-c1', 'orientation', 'The application code around CDC looks completely unchanged -- which is a hint about where CDC actually gets its information.', 10, 1),
  ('mission-be-event-driven-09-o1-c1', 'solution', 'CDC reads the database''s own transaction/write-ahead log -- the internal log the database already keeps for replication and crash recovery.', 20, 2),
  ('mission-be-event-driven-09-o2-c1', 'orientation', 'One approach needs the application to remember something extra. The other needs infrastructure that understands the database''s internals.', 10, 1),
  ('mission-be-event-driven-09-o2-c1', 'solution', 'Outbox: the app writes the row and defines the event schema explicitly. CDC: no app change needed, but it requires log-reading infrastructure.', 20, 2),

  ('mission-be-event-driven-10-o1-c1', 'orientation', 'Compensations run in the opposite order from the steps that need undoing -- last committed, first undone.', 10, 1),
  ('mission-be-event-driven-10-o1-c1', 'solution', 'Reserve the flight, charge the card, the hotel booking fails, refund the charge, then release the flight seat -- unwinding in reverse.', 20, 2),
  ('mission-be-event-driven-10-o2-c1', 'orientation', 'This is the exact same choreography-versus-orchestration distinction from earlier in this Act, applied to a saga specifically.', 10, 1),
  ('mission-be-event-driven-10-o2-c1', 'solution', 'Whether one process knows and drives the whole saga, or every step only reacts to the event immediately before it.', 20, 2),

  ('mission-be-event-driven-11-o1-c1', 'orientation', 'Three of these have a clean, mechanical inverse. One of them does not have a true inverse at all.', 10, 1),
  ('mission-be-event-driven-11-o1-c1', 'solution', 'ChargeCard -> RefundCharge, ReserveSeat -> ReleaseSeat, CreateShipment -> CancelShipment (only pre-dispatch), SendWelcomeEmail -> no true undo, send a correction instead.', 20, 2),
  ('mission-be-event-driven-11-o2-c1', 'orientation', 'Look for the entry where the compensation was actually attempted and explicitly rejected, not just where the original action succeeded.', 10, 1),
  ('mission-be-event-driven-11-o2-c1', 'solution', 'ev2 -- the cancellation was actually attempted and the warehouse system refused it, because the shipment had already physically left.', 20, 2),

  ('mission-be-event-driven-12-o1-c1', 'orientation', 'One entry is a consequence of the failure. One entry is the failure itself, caught and then discarded.', 10, 1),
  ('mission-be-event-driven-12-o1-c1', 'solution', 'ev2 -- the commit succeeded, the publish threw, and an empty catch block swallowed it. That''s the root cause; ev1 and ev3 are just its downstream effects.', 20, 2),
  ('mission-be-event-driven-12-o2-c1', 'orientation', 'Three of these options either don''t fix atomicity or just move the same problem somewhere else.', 10, 1),
  ('mission-be-event-driven-12-o2-c1', 'solution', 'Only the outbox removes the second network call from the critical path entirely -- retrying hopes, publish-then-write flips the risk, and logging just documents the same failure faster.', 20, 2),
  ('mission-be-event-driven-12-o3-c1', 'orientation', 'This one isn''t part of tonight''s incident at all -- ask what makes it worth filing anyway.', 10, 1),
  ('mission-be-event-driven-12-o3-c1', 'solution', 'ev1 -- a four-month-old, never-published outbox row with a malformed doubled-slash topic name is exactly the kind of anomaly worth tagging and tracking, even unresolved.', 20, 2),
  ('mission-be-event-driven-12-o4-c1', 'orientation', 'Look at what the fix and the rejected alternatives all had in common as a single rule, not as separate judgments.', 15, 1),
  ('mission-be-event-driven-12-o4-c1', 'solution', 'The business write and the event announcing it must commit together, in one transaction -- if the write happens, the event is guaranteed to eventually happen too, and if the write doesn''t happen, the event never gets to either.', 25, 2);
