-- Backend Engineering ("The Fracture") -- "Kubernetes & Platform Backends" content.
-- Closes Arc VII (Operate) and is the last Act of the currently-authored range
-- (Acts 1-31 of an eventual 32; Act 32 is deferred to its own session).
-- Uses the NEW slug-based id convention: world-be-kubernetes / campaign-be-kubernetes /
-- operation-be-kubernetes-N / mission-be-kubernetes-NN, unlike earlier numeric-id Acts.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the same
-- campaigns -> operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every prior Act.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be-kubernetes', 'world-be-kubernetes', 'orchestrating-the-fleet', 'Kubernetes & Platform Backends', 'Deploys are safe now, but safe deploys onto a handful of manually-managed boxes does not scale to what Forge actually runs. This Act builds the mental model, the objects and the operational discipline Kubernetes actually demands -- and closes Arc VII by finally reading every manifest in the cluster in one sitting.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be-kubernetes-1', 'campaign-be-kubernetes', 'the-cluster-model', 'The Cluster Model', 'The control loop, pods, Deployments, Services, ConfigMaps and Secrets, and Ingress -- the objects that make up a running cluster.', 1),
  ('operation-be-kubernetes-2', 'campaign-be-kubernetes', 'keeping-it-alive', 'Keeping It Alive', 'Probes, resource requests and limits, autoscaling, scheduled work, and the debugging discipline that turns a crash loop into a diagnosis.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be-kubernetes-01', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'kubernetes-mental-model', 'Kubernetes Mental Model', 'Deployment Friday made rollouts safe. It said nothing about dozens of services on a fleet of boxes nobody wants to babysit by hand. Kubernetes'' entire pitch is one sentence: tell it what you want, and it keeps making that true.', 'advanced', ARRAY['mira','forge'], null, null, '{"type":"simulation","simulationId":"k8s-mental-model-sim"}'::jsonb, '{"xp":331,"credits":64}'::jsonb, false, 1),
  ('mission-be-kubernetes-02', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'pods', 'Pods', 'Kubernetes never schedules a container directly. It schedules a pod -- and the gap between those two words is the first thing that trips up everyone who learned Docker first.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-kubernetes-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"pods-sim"}'::jsonb, '{"xp":333,"credits":64}'::jsonb, false, 2),
  ('mission-be-kubernetes-03', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'deployments', 'Deployments', 'A pod created by hand dies once and stays dead. A Deployment is the promise that never stops -- it keeps the right number of pods running through crashes, node failures and every planned update.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-kubernetes-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"deployments-sim"}'::jsonb, '{"xp":335,"credits":65}'::jsonb, false, 3),
  ('mission-be-kubernetes-04', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'services', 'Services', 'Every pod restart hands out a brand-new IP address. A Service is the one address that never changes -- and the label selector underneath it is the only thing standing between traffic finding your pods and total silence.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-kubernetes-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"services-sim"}'::jsonb, '{"xp":337,"credits":65}'::jsonb, false, 4),
  ('mission-be-kubernetes-05', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'configmaps-and-secrets', 'ConfigMaps and Secrets', 'Baking config into a container image means rebuilding an image just to change a URL. ConfigMaps and Secrets pull configuration out of the image entirely -- and the line between the two is a line worth taking seriously.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-kubernetes-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"configmaps-secrets-sim"}'::jsonb, '{"xp":339,"credits":65}'::jsonb, false, 5),
  ('mission-be-kubernetes-06', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-1', 'ingress', 'Ingress', 'A LoadBalancer Service per microservice means a new cloud load balancer, and a new bill, for every single service that needs external traffic. Ingress is the one entry point that routes by host and path instead.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-kubernetes-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"ingress-sim"}'::jsonb, '{"xp":341,"credits":66}'::jsonb, false, 6),
  ('mission-be-kubernetes-07', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'liveness-and-readiness', 'Liveness and Readiness', 'Kubernetes has no idea whether a process that''s still running is actually working. Probes are the only thing that tells it -- and getting the timing wrong causes exactly the kind of restart loop this Act is building toward.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be-kubernetes-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"liveness-readiness-sim"}'::jsonb, '{"xp":343,"credits":66}'::jsonb, false, 7),
  ('mission-be-kubernetes-08', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'resource-requests-and-limits', 'Resource Requests and Limits', 'A pod with no resources block at all is technically valid YAML -- and it is also the exact setup behind the crash loop that opened this whole Act. Requests and limits are not optional tuning; they are what makes scheduling and survival possible at all.', 'advanced', ARRAY['forge','mira'], '{"requiredMissionIds":["mission-be-kubernetes-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"resource-requests-limits-sim"}'::jsonb, '{"xp":345,"credits":66}'::jsonb, false, 8),
  ('mission-be-kubernetes-09', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'horizontal-pod-autoscaling', 'Horizontal Pod Autoscaling', 'A fixed replica count is either wasteful at 3am or underwater at rush hour. The Horizontal Pod Autoscaler adjusts replica count automatically -- but it can only do the math against numbers that actually exist.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-kubernetes-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"hpa-sim"}'::jsonb, '{"xp":347,"credits":67}'::jsonb, false, 9),
  ('mission-be-kubernetes-10', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'jobs-and-cronjobs', 'Jobs and CronJobs', 'Not everything Forge runs is a long-lived server. Some things run once and finish. Some things run on a schedule, forever, whether or not anyone is watching. Kubernetes has an object for each, and the difference matters more than it looks like it should.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-kubernetes-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"jobs-cronjobs-sim"}'::jsonb, '{"xp":349,"credits":67}'::jsonb, false, 10),
  ('mission-be-kubernetes-11', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'rolling-updates-and-debugging', 'Rolling Updates and Debugging', 'Everything up to here assumes the cluster is healthy. This mission is the toolkit for when it is not -- how a rolling update actually rolls, and the handful of commands that turn "something is broken" into "here is exactly what and why."', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be-kubernetes-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"rolling-updates-debugging-sim"}'::jsonb, '{"xp":350,"credits":68}'::jsonb, false, 11),
  ('mission-be-kubernetes-12', 'world-be-kubernetes', 'campaign-be-kubernetes', 'operation-be-kubernetes-2', 'crashloop-city', 'CrashLoop City', 'The incident that opened this Act, finally in front of you: a service with no memory limits, scheduled next to three other pods on the same node, OOM-killed under load, and killed again on every restart after. Fix it for real -- then read every manifest in the cluster, because one of them was never supposed to still be running.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be-kubernetes-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"crashloop-city-boss-sim"}'::jsonb, '{"xp":700,"credits":162,"badgeIds":["crashloop-city"],"skillXp":{"kubernetes":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be-kubernetes-01', 1, 'mira', 'Deploy pipeline''s solid now. Rolling updates, health checks, no more six-minute Fridays. But we''re running dozens of services across a handful of boxes, and every one of them still gets babysat by a human who knows which box it lives on.'),
  ('mission-be-kubernetes-01', 2, 'forge', 'That doesn''t scale past about fifteen services before someone starts keeping a spreadsheet. Kubernetes is the answer every serious platform team eventually reaches for -- not because it''s simple, it very much is not, but because it replaces ''a human remembers'' with ''a system continuously checks.'''),
  ('mission-be-kubernetes-01', 3, 'forge', 'The mental model underneath all of it is one idea: you declare what you want -- three replicas of this, running that image -- and a set of control loops keep comparing what you asked for against what''s actually running, and correcting the difference. Forever. That''s the whole trick.'),
  ('mission-be-kubernetes-01', 4, 'mira', 'Learn the pieces first. The control loop only matters once you know what it''s actually watching.'),

  ('mission-be-kubernetes-02', 1, 'forge', 'First surprise: Kubernetes doesn''t run containers. It runs pods. A pod is one or more containers that share a network namespace and, optionally, storage -- as far as the network''s concerned, they''re one machine.'),
  ('mission-be-kubernetes-02', 2, 'forge', 'Most pods run exactly one container. The ''more than one'' case exists for tightly coupled helpers -- a sidecar that ships logs, a proxy that intercepts traffic -- things that only make sense living on the same localhost as the container they''re helping.'),

  ('mission-be-kubernetes-03', 1, 'mira', 'A raw pod is a promise with no follow-through -- kill it, and nothing brings it back. Nobody runs pods directly in production. They run Deployments.'),
  ('mission-be-kubernetes-03', 2, 'mira', 'A Deployment doesn''t manage pods directly either. It manages a ReplicaSet, which manages the pods. You''ll almost never touch a ReplicaSet by hand -- but knowing that middle layer exists is exactly what makes ''why didn''t my pod count change'' debuggable.'),

  ('mission-be-kubernetes-04', 1, 'forge', 'Pods are disposable on purpose -- every restart, every reschedule, hands out a new IP. Nothing durable should ever hardcode a pod IP.'),
  ('mission-be-kubernetes-04', 2, 'forge', 'A Service gives you one stable virtual IP and DNS name that always routes to whichever pods currently match its label selector -- whatever they are, wherever they''re running, right now.'),

  ('mission-be-kubernetes-05', 1, 'mira', 'If changing a feature flag means rebuilding a container image, something''s modeled wrong. Config doesn''t belong baked into the image -- it belongs injected at runtime.'),
  ('mission-be-kubernetes-05', 2, 'forge', 'ConfigMaps hold that -- URLs, flags, anything non-sensitive. Secrets hold the same shape of data for anything sensitive: API keys, passwords, tokens. They look almost identical in the API. They are not the same thing operationally.'),
  ('mission-be-kubernetes-05', 3, 'forge', 'One caveat people trip over constantly: a Secret''s values are base64-encoded by default, not encrypted. Base64 is an encoding, not a cipher -- anyone with read access to the Secret object can decode it in one command.'),

  ('mission-be-kubernetes-06', 1, 'forge', 'A LoadBalancer Service works. It also provisions a real cloud load balancer, with a real monthly cost, per service. Multiply that by dozens of services and finance notices before anyone else does.'),
  ('mission-be-kubernetes-06', 2, 'forge', 'Ingress is a single entry point that routes by hostname and path to whichever internal Service actually owns that traffic -- one external load balancer in front of everything, plus rules an Ingress controller reads and enforces.'),

  ('mission-be-kubernetes-07', 1, 'mira', 'A process can be alive -- PID still running, no crash -- and still be completely unable to serve a request. Deadlocked, stuck waiting on a connection pool that never frees up, whatever. Kubernetes can''t see any of that on its own.'),
  ('mission-be-kubernetes-07', 2, 'mira', 'Probes are how you tell it what ''working'' actually means for this specific service. Get the timing wrong on one of these and you don''t catch failures faster -- you cause new ones.'),

  ('mission-be-kubernetes-08', 1, 'forge', 'Remember the incident that pulled us into this Act -- a service scheduled next to three others on the same node, OOM-killed, restarted, OOM-killed again? This is the mission where we find out why that was ever possible.'),
  ('mission-be-kubernetes-08', 2, 'forge', 'A request is what a pod asks for -- the scheduler uses it to decide which node has room. A limit is a hard ceiling -- go over it in memory, and the kernel kills the container outright. Skip both, and the scheduler is guessing, and any one pod can starve its neighbors with nothing stopping it.'),
  ('mission-be-kubernetes-08', 3, 'mira', 'No limits doesn''t mean unlimited and safe. It means unlimited until the node runs out, and then something on that node dies -- maybe not even the pod that caused it.'),

  ('mission-be-kubernetes-09', 1, 'forge', 'A Deployment holding steady at five replicas all day is wrong twice -- overpaying overnight, underwater during a spike. The HPA watches a metric and adjusts replica count for you.'),
  ('mission-be-kubernetes-09', 2, 'forge', 'Here''s the part that trips people up: the HPA usually targets a percentage of the pod''s resource request -- ''keep average CPU near 50 percent of what was requested.'' No request set means no denominator, means the HPA has nothing to compute a percentage against.'),

  ('mission-be-kubernetes-10', 1, 'mira', 'A Deployment is for things meant to run forever. A monthly report generator isn''t that -- it runs, finishes, and should be allowed to actually stop.'),
  ('mission-be-kubernetes-10', 2, 'forge', 'That''s a Job -- run to completion, tracked until it succeeds or exhausts its retries. A CronJob is just a Job on a schedule, created fresh on whatever cadence you give it -- standard cron syntax, minute hour day month weekday.'),

  ('mission-be-kubernetes-11', 1, 'forge', 'A rolling update doesn''t stop the old version and start the new one. It brings up new pods gradually, waits for each to pass its readiness probe, and only then retires an old one -- maxSurge controls how many extra pods it''s allowed above the target count, maxUnavailable controls how many can be missing at once.'),
  ('mission-be-kubernetes-11', 2, 'forge', 'When something goes wrong, three commands cover most of it: kubectl get pods for status and restart count, kubectl describe pod for events and the last termination reason, kubectl logs for what the container itself actually said before it died.'),

  ('mission-be-kubernetes-12', 1, 'mira', 'This is the incident that pulled you into this Act. dispatch-api, scheduled next to three other services on the same node, OOM-killed, restarted, OOM-killed again. Nobody could stop it because nobody agreed on why it was happening.'),
  ('mission-be-kubernetes-12', 2, 'forge', 'I''ve pulled the pod''s manifest, its describe output, and the node''s summary. Walk through it properly this time -- not ''restart it and hope,'' the actual cause.'),
  ('mission-be-kubernetes-12', 3, 'forge', 'Once you''ve got the real cause, you''ll see the fix is one you''ve already learned. The wrong answers all sound reasonable under pressure -- that''s exactly why they''re dangerous.'),
  ('mission-be-kubernetes-12', 4, 'mira', 'Fix it, and then keep going. While you had every deployment manifest open at once, I want you to actually read all of them. Every one. Something nobody''s done in one sitting.'),
  ('mission-be-kubernetes-12', 5, 'forge', 'Found something. A CronJob, scheduled every day at 2:00 AM, running a container image nobody currently at Forge remembers deploying. Its only argument is a single string -- a path containing ''//''.'),
  ('mission-be-kubernetes-12', 6, 'forge', 'It has apparently been running successfully, silently, every single night, for longer than anyone here has actually been checking.'),
  ('mission-be-kubernetes-12', 7, 'mira', 'Say that again. Successfully. Every night. Nobody deployed it, nobody''s touched it, and it has never once failed loudly enough for anyone to notice.'),
  ('mission-be-kubernetes-12', 8, 'forge', 'That''s the part I can''t get past. A crash loop gets noticed because it''s loud. This is the opposite of loud. This has been working, exactly as intended, this whole time.'),
  ('mission-be-kubernetes-12', 9, 'mira', 'Log it. Don''t chase it tonight -- we don''t have enough to know what it is or who''s behind it, and guessing now just wastes the lead.'),
  ('mission-be-kubernetes-12', 10, 'mira', 'Here''s where we actually are. Every core piece of what Forge builds, secures, connects, scales, and now operates, is real, running, and -- as far as anyone can prove -- healthy.'),
  ('mission-be-kubernetes-12', 11, 'forge', 'What''s left isn''t a new skill. It''s the question sitting underneath all of them: what happens when the whole thing has to survive something bigger than any single failure this campaign has simulated.'),
  ('mission-be-kubernetes-12', 12, 'mira', 'That question doesn''t have an easy answer yet. Arc VII closes here. Whatever''s running at 2 AM keeps running whether we''re watching or not -- so, starting now, we watch.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be-kubernetes-01-o1', 'mission-be-kubernetes-01', 1, 'Declarative, not imperative', 'Understand the shift from telling the cluster what to do to telling it what you want.'),
  ('mission-be-kubernetes-01-o2', 'mission-be-kubernetes-01', 2, 'Map the control plane', 'Match each control plane component to the job it actually does.'),
  ('mission-be-kubernetes-02-o1', 'mission-be-kubernetes-02', 1, 'Why the pod exists', 'Understand why Kubernetes wraps containers in a pod instead of scheduling them directly.'),
  ('mission-be-kubernetes-02-o2', 'mission-be-kubernetes-02', 2, 'Read the pod manifest', 'Find the line that actually determines what image this pod runs.'),
  ('mission-be-kubernetes-03-o1', 'mission-be-kubernetes-03', 1, 'The ownership chain', 'Order the objects from what you actually edit down to what''s actually running.'),
  ('mission-be-kubernetes-03-o2', 'mission-be-kubernetes-03', 2, 'Debug the deployment', 'Find the line stopping this deployment from running any pods at all.'),
  ('mission-be-kubernetes-04-o1', 'mission-be-kubernetes-04', 1, 'Match the service type', 'Match each Service type to what it actually exposes.'),
  ('mission-be-kubernetes-04-o2', 'mission-be-kubernetes-04', 2, 'Find the broken selector', 'Find the evidence that explains why this service has zero working endpoints.'),
  ('mission-be-kubernetes-05-o1', 'mission-be-kubernetes-05', 1, 'ConfigMap or Secret', 'Sort each value into where it actually belongs.'),
  ('mission-be-kubernetes-05-o2', 'mission-be-kubernetes-05', 2, 'Spot the real mistake', 'Find the evidence that shows a security assumption nobody should have made.'),
  ('mission-be-kubernetes-06-o1', 'mission-be-kubernetes-06', 1, 'Route the paths', 'Match each path rule to the service it should route to.'),
  ('mission-be-kubernetes-06-o2', 'mission-be-kubernetes-06', 2, 'Debug the ingress', 'Find the line sending traffic to a service that was never created.'),
  ('mission-be-kubernetes-07-o1', 'mission-be-kubernetes-07', 1, 'Match the probe to its job', 'Match liveness, readiness and startup probes to what each one actually controls.'),
  ('mission-be-kubernetes-07-o2', 'mission-be-kubernetes-07', 2, 'Debug the probe config', 'Find the line causing a slow-starting service to be killed before it ever finishes booting.'),
  ('mission-be-kubernetes-08-o1', 'mission-be-kubernetes-08', 1, 'Requests vs limits', 'Match each concept to the guarantee it actually provides.'),
  ('mission-be-kubernetes-08-o2', 'mission-be-kubernetes-08', 2, 'Find what''s missing', 'Find the evidence that explains why this specific pod kept getting OOM-killed.'),
  ('mission-be-kubernetes-09-o1', 'mission-be-kubernetes-09', 1, 'How the HPA actually decides', 'Understand what the HPA measures against to decide when to scale.'),
  ('mission-be-kubernetes-09-o2', 'mission-be-kubernetes-09', 2, 'Debug the HPA', 'Find the evidence that explains why this HPA never scales the deployment at all.'),
  ('mission-be-kubernetes-10-o1', 'mission-be-kubernetes-10', 1, 'Job or CronJob', 'Sort each use case into the object that actually fits it.'),
  ('mission-be-kubernetes-10-o2', 'mission-be-kubernetes-10', 2, 'Read the schedule', 'Find the line that determines exactly when this CronJob runs.'),
  ('mission-be-kubernetes-11-o1', 'mission-be-kubernetes-11', 1, 'Order the rollout', 'Order the steps of a rolling update as they actually happen.'),
  ('mission-be-kubernetes-11-o2', 'mission-be-kubernetes-11', 2, 'Read the crash', 'Find the evidence that identifies the real problem, not just that a problem exists.'),
  ('mission-be-kubernetes-12-o1', 'mission-be-kubernetes-12', 1, 'Diagnose the crash', 'Find the evidence that identifies the actual root cause of the repeated OOM kills.'),
  ('mission-be-kubernetes-12-o2', 'mission-be-kubernetes-12', 2, 'Reject the decoys', 'Choose the fix that actually addresses the root cause, not the ones that only look like it does.'),
  ('mission-be-kubernetes-12-o3', 'mission-be-kubernetes-12', 3, 'The 2 AM CronJob', 'Find the evidence that reveals what the full manifest audit actually turned up.'),
  ('mission-be-kubernetes-12-o4', 'mission-be-kubernetes-12', 4, 'Close the case', 'Synthesize the diagnosis, the fix and the discovery into what this incident, and this Act, actually add up to.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be-kubernetes-01-o1-c1', 'mission-be-kubernetes-01-o1', 1, 'multiple_choice', 'A teammate says they''ll just SSH into a node and start three more containers by hand if traffic spikes. Why is that the wrong instinct for how Kubernetes is meant to be operated?', '{"question":"A teammate says: \"I''ll just SSH into the node and start three more containers by hand if traffic spikes.\" Why is that the wrong instinct for how Kubernetes is meant to be operated?","options":[{"id":"a","text":"It''s not wrong, kubectl run is just a shortcut for the same thing"},{"id":"b","text":"Because it fights the control loop -- Kubernetes continuously reconciles actual state back toward the declared desired state, so a hand-started container isn''t tracked and won''t survive the next reconciliation"},{"id":"c","text":"Because SSH access is disabled on Kubernetes nodes by design"},{"id":"d","text":"Because containers started manually always crash immediately"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be-kubernetes-01-o2-c1', 'mission-be-kubernetes-01-o2', 1, 'drag_and_drop', 'Match each control plane component to the job it actually does.', '{"items":[{"id":"c1","text":"API server"},{"id":"c2","text":"etcd"},{"id":"c3","text":"Scheduler"},{"id":"c4","text":"Controller manager"},{"id":"c5","text":"kubelet"}],"targets":[{"id":"t1","label":"The front door -- every request to read or change cluster state goes through this"},{"id":"t2","label":"The cluster''s source of truth -- the actual desired-state data lives here"},{"id":"t3","label":"Decides which node a new pod should run on"},{"id":"t4","label":"Runs the reconciliation loops that notice drift and correct it"},{"id":"t5","label":"The agent on each node that actually starts and watches containers"}]}'::jsonb, '{"correctMapping":{"c1":"t1","c2":"t2","c3":"t3","c4":"t4","c5":"t5"}}'::jsonb),

  ('mission-be-kubernetes-02-o1-c1', 'mission-be-kubernetes-02-o1', 1, 'multiple_choice', 'A sidecar container that ships logs needs to reach its main container over localhost, and both need to come up or go down together. Why does Kubernetes model this as one pod instead of two independently scheduled containers?', '{"question":"A sidecar container that ships logs needs to reach its main container over localhost, and both need to come up or go down together. Why does Kubernetes model this as one pod instead of two independently scheduled containers?","options":[{"id":"a","text":"Because Kubernetes can only schedule one container at a time"},{"id":"b","text":"Because a pod guarantees its containers share a network namespace and lifecycle -- they''re always scheduled to the same node together, and can talk over localhost"},{"id":"c","text":"Because sidecars are a Docker-only concept that Kubernetes doesn''t actually support"},{"id":"d","text":"Because containers in different pods can never communicate at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be-kubernetes-02-o2-c1', 'mission-be-kubernetes-02-o2', 1, 'code_debugging', 'Which single line determines the actual container image this pod will run?', '{"language":"yaml","code":"apiVersion: v1\nkind: Pod\nmetadata:\n  name: dispatch-api\n  labels:\n    app: dispatch-api\nspec:\n  containers:\n    - name: dispatch-api\n      image: forge/dispatch-api:1.4.2\n      ports:\n        - containerPort: 8080","question":"Which single line determines the actual container image this pod will run?"}'::jsonb, '{"requiredLineIds":["      image: forge/dispatch-api:1.4.2"]}'::jsonb),

  ('mission-be-kubernetes-03-o1-c1', 'mission-be-kubernetes-03-o1', 1, 'interactive_diagram', 'Order these from what you edit down to what''s actually running.', '{"diagramId":"deployment-ownership-chain","hotspots":[{"id":"deployment","label":"Deployment","explanation":"You declare the desired state here -- image, replica count, update strategy."},{"id":"replicaset","label":"ReplicaSet","explanation":"Created and owned by the Deployment -- its only job is keeping exactly N pods matching a label selector alive."},{"id":"pod","label":"Pod","explanation":"Created and owned by the ReplicaSet -- the actual running containers."}],"task":"Order these from what you edit down to what''s actually running."}'::jsonb, '{"correctOrderIds":["deployment","replicaset","pod"]}'::jsonb),
  ('mission-be-kubernetes-03-o2-c1', 'mission-be-kubernetes-03-o2', 1, 'code_debugging', 'This deployment has zero running pods and nothing in the logs is complaining. Which line is actually responsible?', '{"language":"yaml","code":"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: dispatch-api\nspec:\n  replicas: 0\n  selector:\n    matchLabels:\n      app: dispatch-api\n  template:\n    metadata:\n      labels:\n        app: dispatch-api\n    spec:\n      containers:\n        - name: dispatch-api\n          image: forge/dispatch-api:1.4.2","question":"This deployment has zero running pods and nothing in the logs is complaining. Which line is actually responsible?"}'::jsonb, '{"requiredLineIds":["  replicas: 0"]}'::jsonb),

  ('mission-be-kubernetes-04-o1-c1', 'mission-be-kubernetes-04-o1', 1, 'drag_and_drop', 'Match each Service type to what it actually exposes.', '{"items":[{"id":"s1","text":"ClusterIP"},{"id":"s2","text":"NodePort"},{"id":"s3","text":"LoadBalancer"},{"id":"s4","text":"Headless (clusterIP: None)"}],"targets":[{"id":"t1","label":"Internal-only virtual IP, reachable only from inside the cluster -- the default"},{"id":"t2","label":"Opens the same static port on every node''s own IP, reachable from outside the cluster"},{"id":"t3","label":"Provisions an external load balancer from the cloud provider, with its own public IP"},{"id":"t4","label":"No virtual IP at all -- DNS returns the pod IPs directly, for clients that need to talk to a specific pod"}]}'::jsonb, '{"correctMapping":{"s1":"t1","s2":"t2","s3":"t3","s4":"t4"}}'::jsonb),
  ('mission-be-kubernetes-04-o2-c1', 'mission-be-kubernetes-04-o2', 1, 'investigation', 'Which evidence explains why this service has zero endpoints, even though the pods are running and healthy?', '{"evidence":[{"id":"ev1","label":"Service manifest","detail":"spec.selector: { app: dispatch-api-v2 }"},{"id":"ev2","label":"Deployment manifest","detail":"template.metadata.labels: { app: dispatch-api }"},{"id":"ev3","label":"kubectl get endpoints output","detail":"dispatch-api   <none>"}],"question":"Which evidence explains why this service has zero endpoints, even though the pods are running and healthy?"}'::jsonb, '{"requiredEvidenceIds":["ev1","ev2"]}'::jsonb),

  ('mission-be-kubernetes-05-o1-c1', 'mission-be-kubernetes-05-o1', 1, 'drag_and_drop', 'Sort each value into where it actually belongs.', '{"items":[{"id":"v1","text":"Public API base URL"},{"id":"v2","text":"Database password"},{"id":"v3","text":"Feature flag: new-dispatch-ui"},{"id":"v4","text":"Third-party payment API key"},{"id":"v5","text":"Log level (info/debug)"}],"targets":[{"id":"configmap","label":"ConfigMap"},{"id":"secret","label":"Secret"}]}'::jsonb, '{"correctMapping":{"v1":"configmap","v2":"secret","v3":"configmap","v4":"secret","v5":"configmap"}}'::jsonb),
  ('mission-be-kubernetes-05-o2-c1', 'mission-be-kubernetes-05-o2', 1, 'investigation', 'Which evidence shows the actual mistake still sitting unresolved, even after the key was moved into a Secret?', '{"evidence":[{"id":"ev1","label":"Code review comment","detail":"Someone moved the payment API key from a ConfigMap into a Secret after a review flagged it"},{"id":"ev2","label":"Security note","detail":"\"Secrets are base64, and base64 is reversible in one command -- treat it as access control, not encryption. RBAC on who can read the Secret object is what actually protects it.\""},{"id":"ev3","label":"Cluster audit","detail":"The Secret in question has no RBAC restriction beyond the default namespace-wide read access every service account already has"}],"question":"Which evidence shows the actual mistake still sitting unresolved, even after the key was moved into a Secret?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be-kubernetes-06-o1-c1', 'mission-be-kubernetes-06-o1', 1, 'drag_and_drop', 'Match each path rule to the service it should route to.', '{"items":[{"id":"p1","text":"/api/dispatch"},{"id":"p2","text":"/api/citizens"},{"id":"p3","text":"/"}],"targets":[{"id":"t1","label":"dispatch-api Service"},{"id":"t2","label":"citizens-api Service"},{"id":"t3","label":"web-frontend Service"}]}'::jsonb, '{"correctMapping":{"p1":"t1","p2":"t2","p3":"t3"}}'::jsonb),
  ('mission-be-kubernetes-06-o2-c1', 'mission-be-kubernetes-06-o2', 1, 'code_debugging', 'Requests to api.nexuscity.io/dispatch return a 503 from the ingress controller itself. The actual Service is named dispatch-api. Which line is wrong?', '{"language":"yaml","code":"apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: platform-ingress\nspec:\n  rules:\n    - host: api.nexuscity.io\n      http:\n        paths:\n          - path: /dispatch\n            pathType: Prefix\n            backend:\n              service:\n                name: dispatch-service\n                port:\n                  number: 80","question":"Requests to api.nexuscity.io/dispatch return a 503 from the ingress controller itself. The actual Service is named dispatch-api. Which line is wrong?"}'::jsonb, '{"requiredLineIds":["                name: dispatch-service"]}'::jsonb),

  ('mission-be-kubernetes-07-o1-c1', 'mission-be-kubernetes-07-o1', 1, 'drag_and_drop', 'Match liveness, readiness and startup probes to what each one actually controls.', '{"items":[{"id":"p1","text":"Liveness probe"},{"id":"p2","text":"Readiness probe"},{"id":"p3","text":"Startup probe"}],"targets":[{"id":"t1","label":"Fails this and Kubernetes restarts the container -- it assumes the process is stuck and a restart is the only fix"},{"id":"t2","label":"Fails this and the pod is pulled out of Service traffic routing, but left running -- for temporary not-ready states"},{"id":"t3","label":"Runs only during boot, before the other two are even evaluated -- protects slow-starting apps from being killed mid-startup"}]}'::jsonb, '{"correctMapping":{"p1":"t1","p2":"t2","p3":"t3"}}'::jsonb),
  ('mission-be-kubernetes-07-o2-c1', 'mission-be-kubernetes-07-o2', 1, 'code_debugging', 'This service takes about 20 seconds to finish booting before /healthz responds. Which line is why it gets killed and restarted before it ever comes up?', '{"language":"yaml","code":"apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: dispatch-api\nspec:\n  template:\n    spec:\n      containers:\n        - name: dispatch-api\n          image: forge/dispatch-api:1.5.0\n          livenessProbe:\n            httpGet:\n              path: /healthz\n              port: 8080\n            initialDelaySeconds: 2\n            periodSeconds: 5","question":"This service takes about 20 seconds to finish booting before /healthz responds. Which line is why it gets killed and restarted before it ever comes up?"}'::jsonb, '{"requiredLineIds":["            initialDelaySeconds: 2"]}'::jsonb),

  ('mission-be-kubernetes-08-o1-c1', 'mission-be-kubernetes-08-o1', 1, 'drag_and_drop', 'Match each concept to the guarantee it actually provides.', '{"items":[{"id":"r1","text":"Request"},{"id":"r2","text":"Limit"},{"id":"r3","text":"No resources block at all"}],"targets":[{"id":"t1","label":"What the scheduler reserves on a node before placing this pod -- guarantees at least this much is available"},{"id":"t2","label":"A hard ceiling -- exceed it in memory and the container is killed; exceed it in CPU and the container is throttled"},{"id":"t3","label":"The scheduler places the pod with no real guarantee of resources, and the pod has no ceiling stopping it from consuming everything on the node"}]}'::jsonb, '{"correctMapping":{"r1":"t1","r2":"t2","r3":"t3"}}'::jsonb),
  ('mission-be-kubernetes-08-o2-c1', 'mission-be-kubernetes-08-o2', 1, 'investigation', 'Which evidence points at the actual root cause of the repeated OOM kills, not just a symptom of it?', '{"evidence":[{"id":"ev1","label":"Pod manifest","detail":"containers: - name: dispatch-api, image: forge/dispatch-api:1.5.0 -- no resources block present"},{"id":"ev2","label":"kubectl describe pod output","detail":"Last State: Terminated, Reason: OOMKilled, Exit Code: 137, Restart Count: 14"},{"id":"ev3","label":"Node summary","detail":"Four pods scheduled on this node; three others also have no resources block set"}],"question":"Which evidence points at the actual root cause of the repeated OOM kills, not just a symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be-kubernetes-09-o1-c1', 'mission-be-kubernetes-09-o1', 1, 'multiple_choice', 'An HPA is configured with targetCPUUtilizationPercentage: 50. What is that 50 percent actually measured against?', '{"question":"An HPA is configured with targetCPUUtilizationPercentage: 50. What is that 50 percent actually measured against?","options":[{"id":"a","text":"The node''s total available CPU"},{"id":"b","text":"The container''s CPU limit"},{"id":"c","text":"The container''s CPU request -- utilization is expressed relative to what was requested, since that''s the baseline the scheduler reserved"},{"id":"d","text":"A fixed number of CPU cores, regardless of what''s requested"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-be-kubernetes-09-o2-c1', 'mission-be-kubernetes-09-o2', 1, 'investigation', 'Which evidence explains why this HPA has never scaled the deployment, even under heavy load?', '{"evidence":[{"id":"ev1","label":"kubectl describe hpa output","detail":"Warning FailedGetResourceMetric: missing request for cpu on container dispatch-api"},{"id":"ev2","label":"HPA manifest","detail":"metrics: [{ type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: 50 } } }]"},{"id":"ev3","label":"Deployment manifest","detail":"containers: - name: dispatch-api, image: forge/dispatch-api:1.5.0 -- no resources.requests set"}],"question":"Which evidence explains why this HPA has never scaled the deployment, even under heavy load?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be-kubernetes-10-o1-c1', 'mission-be-kubernetes-10-o1', 1, 'drag_and_drop', 'Sort each use case into the object that actually fits it.', '{"items":[{"id":"u1","text":"One-time database migration script"},{"id":"u2","text":"Nightly backup of the citizen registry"},{"id":"u3","text":"Long-running API server"},{"id":"u4","text":"Batch job reprocessing a week of failed dispatch events"}],"targets":[{"id":"job","label":"Job"},{"id":"cronjob","label":"CronJob"},{"id":"deployment","label":"Deployment"}]}'::jsonb, '{"correctMapping":{"u1":"job","u2":"cronjob","u3":"deployment","u4":"job"}}'::jsonb),
  ('mission-be-kubernetes-10-o2-c1', 'mission-be-kubernetes-10-o2', 1, 'code_debugging', 'Which line determines exactly when this CronJob fires?', '{"language":"yaml","code":"apiVersion: batch/v1\nkind: CronJob\nmetadata:\n  name: registry-backup\nspec:\n  schedule: \"0 3 * * *\"\n  jobTemplate:\n    spec:\n      template:\n        spec:\n          containers:\n            - name: backup\n              image: forge/registry-backup:2.1.0\n          restartPolicy: OnFailure","question":"Which line determines exactly when this CronJob fires?"}'::jsonb, '{"requiredLineIds":["  schedule: \"0 3 * * *\""]}'::jsonb),

  ('mission-be-kubernetes-11-o1-c1', 'mission-be-kubernetes-11-o1', 1, 'interactive_diagram', 'Order the steps of a rolling update as they actually happen.', '{"diagramId":"rolling-update-sequence","hotspots":[{"id":"new_pod_created","label":"New pod created","explanation":"A new pod running the updated image is created, on top of the existing old pods, up to the maxSurge limit."},{"id":"new_pod_ready","label":"New pod passes readiness","explanation":"The new pod must pass its readiness probe before it''s considered available and added to Service traffic."},{"id":"old_pod_terminated","label":"Old pod terminated","explanation":"Only once a new pod is confirmed ready does an old pod get terminated, keeping availability above maxUnavailable throughout."},{"id":"repeat","label":"Cycle repeats","explanation":"The cycle repeats, one small batch at a time, until every old pod has been replaced."}],"task":"Order the steps of a rolling update as they actually happen."}'::jsonb, '{"correctOrderIds":["new_pod_created","new_pod_ready","old_pod_terminated","repeat"]}'::jsonb),
  ('mission-be-kubernetes-11-o2-c1', 'mission-be-kubernetes-11-o2', 1, 'investigation', 'CrashLoopBackOff by itself only says the pod keeps failing and restarting. Which evidence actually explains why?', '{"evidence":[{"id":"ev1","label":"kubectl get pods output","detail":"dispatch-api-7d9f   0/1   CrashLoopBackOff   Restarts: 9"},{"id":"ev2","label":"kubectl describe pod output","detail":"Last State: Terminated, Reason: OOMKilled, Exit Code: 137"},{"id":"ev3","label":"kubectl logs --previous output","detail":"connecting to database... connection pool initialized... (log ends abruptly, no error message)"}],"question":"CrashLoopBackOff by itself only says the pod keeps failing and restarting. Which evidence actually explains why?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be-kubernetes-12-o1-c1', 'mission-be-kubernetes-12-o1', 1, 'investigation', 'Which evidence points at the actual root cause of the crash loop, not just a symptom of it?', '{"evidence":[{"id":"ev1","label":"Pod manifest (dispatch-api)","detail":"containers: - name: dispatch-api, image: forge/dispatch-api:1.5.0 -- no resources block present anywhere in the spec"},{"id":"ev2","label":"kubectl describe pod output","detail":"Last State: Terminated, Reason: OOMKilled, Exit Code: 137, Restart Count: 22"},{"id":"ev3","label":"Node summary","detail":"This node is running dispatch-api alongside three other pods, none of which have resource limits set either -- all four are competing for the same unreserved memory"}],"question":"Which evidence points at the actual root cause of the crash loop, not just a symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),
  ('mission-be-kubernetes-12-o2-c1', 'mission-be-kubernetes-12-o2', 1, 'multiple_choice', 'dispatch-api keeps getting OOM-killed and restarted, sharing a node with three other pods that also have no resource limits set. What actually fixes this, for good?', '{"question":"dispatch-api keeps getting OOM-killed and restarted, sharing a node with three other pods that also have no resource limits set. What actually fixes this, for good?","options":[{"id":"a","text":"Restart the pod manually whenever it crashes so it never sits down for long"},{"id":"b","text":"Give the whole cluster more nodes so there''s more memory to go around"},{"id":"c","text":"Disable the liveness probe so Kubernetes stops restarting it"},{"id":"d","text":"Set an explicit memory request and limit on dispatch-api, and its neighbors, so the scheduler can place it sensibly and no pod can consume memory the others need"}]}'::jsonb, '{"correctOptionId":"d"}'::jsonb),
  ('mission-be-kubernetes-12-o3-c1', 'mission-be-kubernetes-12-o3', 1, 'investigation', 'Which evidence best captures what makes this CronJob actually unsettling, not just unfamiliar?', '{"evidence":[{"id":"ev1","label":"Manifest audit note","detail":"First time anyone has read every deployment manifest in the cluster in one sitting -- turned up a CronJob nobody remembers writing"},{"id":"ev2","label":"CronJob manifest","detail":"schedule: \"0 2 * * *\", image: registry.internal/legacy-sync:unknown, args: [\"/data/citizens//export\"]"},{"id":"ev3","label":"CronJob run history","detail":"Every scheduled run for as far back as history is retained: Succeeded. Zero failures."}],"question":"Which evidence best captures what makes this CronJob actually unsettling, not just unfamiliar?"}'::jsonb, '{"requiredEvidenceIds":["ev2","ev3"]}'::jsonb),
  ('mission-be-kubernetes-12-o4-c1', 'mission-be-kubernetes-12-o4', 1, 'boss_encounter', 'Having diagnosed the crash, rejected the decoy fixes and found the CronJob, state what this incident actually adds up to.', '{"stages":[{"objectiveRef":"mission-be-kubernetes-12-o1","label":"Diagnose the crash"},{"objectiveRef":"mission-be-kubernetes-12-o2","label":"Reject the decoys"},{"objectiveRef":"mission-be-kubernetes-12-o3","label":"The 2 AM CronJob"}],"task":"Having diagnosed the crash, rejected the decoy fixes and found the CronJob, state what this incident actually adds up to: the crash loop is fixed with real requests and limits, but the manifest audit it forced turned up a CronJob nobody remembers deploying, running every night at 2:00 AM against a path containing \"//\", succeeding silently every single time. Every core piece of what Forge builds, secures, connects, scales and now operates is real, running, and -- as far as anyone can prove -- healthy. What''s left isn''t a new skill. It''s the question underneath all of them: what happens when the whole thing has to survive something bigger than any single failure this campaign has simulated. That question doesn''t have an easy answer yet."}'::jsonb, '{"requiredObjectiveIds":["mission-be-kubernetes-12-o1","mission-be-kubernetes-12-o2","mission-be-kubernetes-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be-kubernetes-01-o1-c1', 'orientation', 'Ask what happens to that hand-started container the next time the control loop runs.', 10, 1),
  ('mission-be-kubernetes-01-o1-c1', 'concept', 'The scheduler and controllers only know about what''s declared. Anything created outside that declaration is invisible to reconciliation.', 20, 2),
  ('mission-be-kubernetes-01-o1-c1', 'solution', 'The control loop reconciles actual state back to declared desired state -- a manually started container isn''t part of that declaration, so nothing protects or tracks it, and it can vanish on the next reconciliation.', 30, 3),

  ('mission-be-kubernetes-01-o2-c1', 'orientation', 'Two of these store or serve state. Three of these actively make decisions.', 10, 1),
  ('mission-be-kubernetes-01-o2-c1', 'concept', 'Everything goes through the API server first. etcd is just data. The scheduler decides placement once; the controller manager keeps deciding forever; the kubelet is the only one running on every node.', 20, 2),
  ('mission-be-kubernetes-01-o2-c1', 'solution', 'API server -> front door, etcd -> source of truth, Scheduler -> placement decision, Controller manager -> ongoing reconciliation, kubelet -> per-node agent that runs containers.', 30, 3),

  ('mission-be-kubernetes-02-o1-c1', 'orientation', 'Ask what two containers in different pods can and can''t assume about each other.', 10, 1),
  ('mission-be-kubernetes-02-o1-c1', 'concept', 'Containers in separate pods can be scheduled to different nodes entirely, with no shared localhost and no guarantee they come up together.', 20, 2),
  ('mission-be-kubernetes-02-o1-c1', 'solution', 'A pod is the unit that guarantees co-location, a shared network namespace and a shared lifecycle -- exactly what a sidecar needs and two independent pods can''t promise.', 30, 3),

  ('mission-be-kubernetes-02-o2-c1', 'orientation', 'The container name and the containerPort describe it. One field actually names what runs.', 10, 1),
  ('mission-be-kubernetes-02-o2-c1', 'solution', 'image: forge/dispatch-api:1.4.2 is the only line that names the actual artifact being run.', 20, 2),

  ('mission-be-kubernetes-03-o1-c1', 'orientation', 'Whatever you edit has to exist before it can create anything underneath it.', 10, 1),
  ('mission-be-kubernetes-03-o1-c1', 'solution', 'Deployment, then ReplicaSet, then Pod -- each layer is created and owned by the one above it.', 20, 2),

  ('mission-be-kubernetes-03-o2-c1', 'orientation', 'The selector and template look fine. Check the field that actually sets how many pods should exist.', 10, 1),
  ('mission-be-kubernetes-03-o2-c1', 'concept', 'A Deployment with a valid template but replicas: 0 is working exactly as declared -- zero is a legitimate, deliberate desired state.', 20, 2),
  ('mission-be-kubernetes-03-o2-c1', 'solution', 'replicas: 0 -- the deployment is healthy and correctly reconciled, it was just told to run zero pods.', 30, 3),

  ('mission-be-kubernetes-04-o1-c1', 'orientation', 'Two of these expose the service outside the cluster. One has no virtual IP at all.', 10, 1),
  ('mission-be-kubernetes-04-o1-c1', 'solution', 'ClusterIP -> internal only, NodePort -> a port on every node, LoadBalancer -> a cloud provider''s external load balancer, Headless -> DNS returns pod IPs directly, no virtual IP.', 20, 2),

  ('mission-be-kubernetes-04-o2-c1', 'orientation', 'A Service finds pods purely by matching labels -- compare what it''s looking for against what the pods actually have.', 10, 1),
  ('mission-be-kubernetes-04-o2-c1', 'concept', 'ev3 only shows the symptom -- no endpoints. The actual cause is the mismatch between what the Service selects for and what the pods are labeled with.', 20, 2),
  ('mission-be-kubernetes-04-o2-c1', 'solution', 'The Service selects app: dispatch-api-v2, but the pods are labeled app: dispatch-api -- they never match, so the Service never gets a single endpoint.', 30, 3),

  ('mission-be-kubernetes-05-o1-c1', 'orientation', 'Ask which of these a citizen or attacker gaining read access should never see in plaintext.', 10, 1),
  ('mission-be-kubernetes-05-o1-c1', 'solution', 'ConfigMap: base URL, feature flag, log level. Secret: database password, third-party API key.', 20, 2),

  ('mission-be-kubernetes-05-o2-c1', 'orientation', 'Moving the key into a Secret changed where it lives, not necessarily who can read it.', 10, 1),
  ('mission-be-kubernetes-05-o2-c1', 'concept', 'Base64 encoding was never the actual protection -- access control on who can read the Secret object always was.', 20, 2),
  ('mission-be-kubernetes-05-o2-c1', 'solution', 'ev3: the Secret has no RBAC restriction beyond default namespace-wide read access -- moving the key to a Secret didn''t restrict who can actually read it.', 30, 3),

  ('mission-be-kubernetes-06-o1-c1', 'orientation', 'Match by what each path prefix is actually named for.', 10, 1),
  ('mission-be-kubernetes-06-o1-c1', 'solution', '/api/dispatch -> dispatch-api, /api/citizens -> citizens-api, / -> web-frontend.', 20, 2),

  ('mission-be-kubernetes-06-o2-c1', 'orientation', 'Compare the backend service name in the rule against the Service that actually exists.', 10, 1),
  ('mission-be-kubernetes-06-o2-c1', 'solution', 'name: dispatch-service names a Service that was never created -- the real one is dispatch-api, so the ingress controller has nothing to route to.', 20, 2),

  ('mission-be-kubernetes-07-o1-c1', 'orientation', 'One removes traffic without killing anything. One kills and restarts. One only matters before the other two even start.', 10, 1),
  ('mission-be-kubernetes-07-o1-c1', 'solution', 'Liveness -> restart on failure, Readiness -> pulled from traffic but left running, Startup -> guards the boot window before the others activate.', 20, 2),

  ('mission-be-kubernetes-07-o2-c1', 'orientation', 'Compare how long the app actually takes to boot against how soon the liveness probe starts checking.', 10, 1),
  ('mission-be-kubernetes-07-o2-c1', 'concept', 'initialDelaySeconds is how long Kubernetes waits before the very first probe -- set it shorter than real boot time and the first check fails before the app could ever have passed it.', 20, 2),
  ('mission-be-kubernetes-07-o2-c1', 'solution', 'initialDelaySeconds: 2 gives the app two seconds to boot before the first liveness check, but it needs about twenty -- so it gets killed and restarted before it can ever come up cleanly.', 30, 3),

  ('mission-be-kubernetes-08-o1-c1', 'orientation', 'One is a floor, one is a ceiling, one is the absence of both.', 10, 1),
  ('mission-be-kubernetes-08-o1-c1', 'solution', 'Request -> scheduling guarantee, Limit -> hard ceiling with enforcement, No resources block -> no guarantee and no ceiling at all.', 20, 2),

  ('mission-be-kubernetes-08-o2-c1', 'orientation', 'ev2 and ev3 describe what happened. One piece of evidence describes why it was even possible.', 10, 1),
  ('mission-be-kubernetes-08-o2-c1', 'concept', 'OOMKilled and a crowded node are symptoms of the same missing thing -- nothing in the manifest ever told the scheduler or the kernel what this pod was allowed to use.', 20, 2),
  ('mission-be-kubernetes-08-o2-c1', 'solution', 'ev1: no resources block at all is the root cause -- without it, the scheduler placed the pod blind, and nothing capped what it, or its neighbors, could consume.', 30, 3),

  ('mission-be-kubernetes-09-o1-c1', 'orientation', 'The HPA needs a baseline number to compute a percentage against -- ask where that baseline actually comes from.', 10, 1),
  ('mission-be-kubernetes-09-o1-c1', 'solution', 'c: utilization is computed relative to the CPU request, since that''s the number the scheduler already reserved as the baseline.', 20, 2),

  ('mission-be-kubernetes-09-o2-c1', 'orientation', 'The HPA manifest and the warning both describe the same missing piece from two different angles.', 10, 1),
  ('mission-be-kubernetes-09-o2-c1', 'concept', 'Percent utilization is meaningless without a denominator -- and the CPU request is that denominator.', 20, 2),
  ('mission-be-kubernetes-09-o2-c1', 'solution', 'ev3: the deployment has no resources.requests set, so there''s no baseline to compute utilization percentage against -- the HPA can never decide to scale.', 30, 3),

  ('mission-be-kubernetes-10-o1-c1', 'orientation', 'Ask whether each task is meant to run forever, run once, or run once on a repeating schedule.', 10, 1),
  ('mission-be-kubernetes-10-o1-c1', 'solution', 'Migration -> Job, nightly backup -> CronJob, API server -> Deployment, batch reprocess -> Job.', 20, 2),

  ('mission-be-kubernetes-10-o2-c1', 'orientation', 'Cron syntax reads minute, hour, day of month, month, day of week.', 10, 1),
  ('mission-be-kubernetes-10-o2-c1', 'solution', 'schedule: "0 3 * * *" -- every day at 3:00 AM.', 20, 2),

  ('mission-be-kubernetes-11-o1-c1', 'orientation', 'Availability can never dip below what maxUnavailable allows -- ask what has to happen before an old pod is allowed to go.', 10, 1),
  ('mission-be-kubernetes-11-o1-c1', 'solution', 'New pod created, then it passes readiness, then an old pod is terminated, then the cycle repeats until the rollout finishes.', 20, 2),

  ('mission-be-kubernetes-11-o2-c1', 'orientation', 'The pod status tells you something is wrong. It doesn''t tell you what.', 10, 1),
  ('mission-be-kubernetes-11-o2-c1', 'concept', 'Exit code 137 and a Terminated reason are the actual diagnosis -- the status field is just the label for a pattern of restarts.', 20, 2),
  ('mission-be-kubernetes-11-o2-c1', 'solution', 'ev2: Reason: OOMKilled, Exit Code: 137 -- the container is being killed for exceeding its memory limit, not failing on its own.', 30, 3),

  ('mission-be-kubernetes-12-o1-c1', 'orientation', 'The describe output and the node summary both describe what happened. One piece of evidence explains why it was ever possible.', 10, 1),
  ('mission-be-kubernetes-12-o1-c1', 'concept', 'A missing resources block means the scheduler placed this pod with no guarantee and no ceiling -- everything after that is a consequence, not the cause.', 20, 2),
  ('mission-be-kubernetes-12-o1-c1', 'solution', 'ev1: no resources block in the pod manifest is the root cause -- the OOM kills and the crowded node are downstream of that one missing piece.', 30, 3),

  ('mission-be-kubernetes-12-o2-c1', 'orientation', 'Each wrong option treats a symptom. Only one option changes what the scheduler and the kernel actually know.', 10, 1),
  ('mission-be-kubernetes-12-o2-c1', 'concept', 'Manual restarts, more nodes and a disabled probe all leave the real gap in place -- no declared request or limit on any of the four competing pods.', 20, 2),
  ('mission-be-kubernetes-12-o2-c1', 'solution', 'd: setting an explicit memory request and limit on dispatch-api and its neighbors gives the scheduler a real number to place against and a real ceiling that stops any one pod from starving the rest.', 30, 3),

  ('mission-be-kubernetes-12-o3-c1', 'orientation', 'Unfamiliar would just be ev1. Ask what makes this specific CronJob different from an ordinary undocumented one.', 10, 1),
  ('mission-be-kubernetes-12-o3-c1', 'concept', 'A doubled slash and a name nobody recognizes would be a decent story on its own. A perfect, unbroken success record for as long as anyone has telemetry is the part that''s actually hard to explain away.', 20, 2),
  ('mission-be-kubernetes-12-o3-c1', 'solution', 'ev2 and ev3 together: the manifest carries the same "//" pattern Forge has tracked all campaign, and it has succeeded on every single run ever recorded -- deliberate-looking and completely invisible at once.', 30, 3),

  ('mission-be-kubernetes-12-o4-c1', 'orientation', 'Put the fix, the rejected decoys and the CronJob discovery together -- what do all three actually say about where Forge stands right now?', 15, 1),
  ('mission-be-kubernetes-12-o4-c1', 'solution', 'The crash loop is genuinely fixed with real resource requests and limits. But reading every manifest to fix it surfaced a silent, always-succeeding 2 AM CronJob carrying the same doubled-slash pattern -- proof that everything Forge runs is real and healthy, and proof there is still something in it nobody has explained.', 25, 2);
