-- AI/ML pathway ("Cipher Division") Act 35 -- "MLOps & Production AI" content.
-- Arc VII, second-to-last Act before the finale (Act 36, Echo).
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue_lines -> objectives ->
-- challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-mlops-production-ai row already exists
-- (spine: 20260811100000_ai_acts6_36_spine.sql, narrative:
-- 20260812260000_ai_acts31_36_world_narrative.sql).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-mlops-production-ai', 'world-ai-mlops-production-ai', 'mlops-production-ai', '35A - MLOps & Production AI', 'Turning a notebook into a real service: experiment tracking, data and model versioning, training and inference pipelines, model serving, and the monitoring and rollback discipline that catches a model changing before it becomes a crisis.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-mlops-production-ai-1', 'campaign-ai-mlops-production-ai', 'from-notebook-to-pipeline', 'From Notebook to Pipeline', 'What it actually takes to turn a one-off notebook into something that runs the same way every time -- experiment tracking, data and model versioning, and the training and inference pipelines built around them.', 1),
  ('operation-ai-mlops-production-ai-2', 'campaign-ai-mlops-production-ai', 'watching-it-run', 'Watching It Run', 'Serving a model safely and knowing when it stops behaving the way it did on day one -- latency and throughput tradeoffs, drift, alerting, rollback, and the monitoring stack that ties it all together.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-mlops-production-ai-01', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'notebooks-dont-survive', 'Notebooks Don''t Survive', 'Every model Cipher Division runs in production, including the one still flagging tampered archive records, started life in a notebook. None of them ever left. That changes now.', 'beginner', ARRAY['maya','elena','noah'], null, null, '{"type":"simulation","simulationId":"notebooks-dont-survive-sim"}'::jsonb, '{"xp":670,"credits":180}'::jsonb, false, 1),
  ('mission-ai-mlops-production-ai-02', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'experiment-tracking', 'Experiment Tracking', 'A model exists because of a hundred small decisions -- which data, which hyperparameters, which run actually produced it. None of that survives if nobody writes it down.', 'beginner', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"experiment-tracking-sim"}'::jsonb, '{"xp":680,"credits":180}'::jsonb, false, 2),
  ('mission-ai-mlops-production-ai-03', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'data-versioning', 'Data Versioning', 'The archive classifier''s training data has changed at least three times since Act 30. Nobody can say which version trained the model currently running.', 'beginner', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"data-versioning-sim"}'::jsonb, '{"xp":680,"credits":185}'::jsonb, false, 3),
  ('mission-ai-mlops-production-ai-04', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'model-versioning', 'Model Versioning', 'A trained model is a file, a set of weights, and a training run behind it. Ship it without a version and there is no way back if it goes wrong.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"model-versioning-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 4),
  ('mission-ai-mlops-production-ai-05', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'training-pipelines', 'Training Pipelines', 'One good training run, done by hand, proves an idea works. It does not prove it will still work the fifth time, run by someone else, next month.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"training-pipelines-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 5),
  ('mission-ai-mlops-production-ai-06', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-1', 'inference-pipelines', 'Inference Pipelines', 'Training produces a model. Inference is what actually happens every time that model is asked to score one real, live archive record.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"inference-pipelines-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 6),
  ('mission-ai-mlops-production-ai-07', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'model-serving', 'Model Serving', 'A model that returns the right answer twenty seconds too late is not actually serving anyone. Serving is where the tradeoffs get real.', 'intermediate', ARRAY['noah','byte'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"model-serving-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 7),
  ('mission-ai-mlops-production-ai-08', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'monitoring-drift', 'Monitoring Drift', 'A model does not announce when it starts getting worse. Left alone, it just quietly does -- and the only way to know is to be watching for it.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"monitoring-drift-sim"}'::jsonb, '{"xp":710,"credits":190}'::jsonb, false, 8),
  ('mission-ai-mlops-production-ai-09', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'alerting-thresholds', 'Alerting Thresholds', 'A monitoring dashboard nobody gets paged from is a chart, not a safeguard. The threshold is what turns a metric into an action.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"alerting-thresholds-sim"}'::jsonb, '{"xp":710,"credits":195}'::jsonb, false, 9),
  ('mission-ai-mlops-production-ai-10', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'rollback-discipline', 'Rollback Discipline', 'Knowing a model has gone wrong is only half the job. The other half is being able to undo it in minutes, not days.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"rollback-discipline-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 10),
  ('mission-ai-mlops-production-ai-11', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'the-monitoring-stack', 'The Monitoring Stack', 'Every piece has been built separately -- tracking, versioning, pipelines, thresholds, rollback. Now it all has to run together, pointed at something real.', 'intermediate', ARRAY['noah','elena','byte'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"monitoring-stack-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 11),
  ('mission-ai-mlops-production-ai-12', 'world-ai-mlops-production-ai', 'campaign-ai-mlops-production-ai', 'operation-ai-mlops-production-ai-2', 'the-model-that-changed', 'The Model That Changed', 'The stack goes live against the archive classifier. Within hours, it does exactly what it was built to do -- and it changes what everyone thought this Act was actually about.', 'boss', ARRAY['maya','elena','noah','byte'], '{"requiredMissionIds":["mission-ai-mlops-production-ai-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"model-that-changed-boss-sim"}'::jsonb, '{"xp":1550,"credits":330,"badgeIds":["the-model-that-changed"],"skillXp":{"mlops":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-mlops-production-ai-01', 1, 'maya', 'Every system this pathway has built runs somewhere real now. None of it has the discipline production actually requires -- versioned, monitored, ready to roll back if it goes wrong. Echo never had that. Not once. Not when it mattered most.'),
  ('mission-ai-mlops-production-ai-01', 2, 'maya', 'The archive integrity classifier that has been flagging tampered records since Act 30 is a perfect example. It came straight out of a notebook, and it has been running unversioned and unwatched ever since.'),
  ('mission-ai-mlops-production-ai-01', 3, 'elena', 'A notebook is built for exploration, not operation. Cells can run out of order, variables persist even after the cell that made them is deleted, and there is no single record of which version of the code actually produced which result.'),
  ('mission-ai-mlops-production-ai-01', 4, 'noah', 'Run it top to bottom fresh and you can get a different answer than whatever is still sitting in memory from three cells you edited an hour ago. That is fine while you are exploring. It is not fine for something making decisions on live data.'),
  ('mission-ai-mlops-production-ai-01', 5, 'elena', 'None of that is a knock on notebooks. They are the right tool for asking a question. They were never the right tool for answering the same question, the same way, every day, for months, unattended.'),
  ('mission-ai-mlops-production-ai-01', 6, 'maya', 'So before anything else in this Act, get that distinction straight. Then we start building what the archive classifier -- and everything after it -- actually needed from day one.'),

  ('mission-ai-mlops-production-ai-02', 1, 'elena', 'Rebuilding the archive classifier from scratch means answering a question nobody can currently answer: which of the dozen versions we tried last month is the one actually running right now, and what exact parameters produced it?'),
  ('mission-ai-mlops-production-ai-02', 2, 'noah', 'Experiment tracking is the fix -- logging every run''s parameters, metrics, code version, and data version automatically, in one place, instead of trusting a filename or someone''s memory.'),
  ('mission-ai-mlops-production-ai-02', 3, 'elena', 'The point is not just record-keeping. It is being able to compare runs against each other honestly -- same metrics, same conditions -- and reproduce the exact run that won, on demand, not just remember that it won.'),

  ('mission-ai-mlops-production-ai-03', 1, 'noah', 'Code lives in git. The data that trained the classifier does not live anywhere with a version number at all -- it is just whatever was sitting in the training folder the day someone ran the job.'),
  ('mission-ai-mlops-production-ai-03', 2, 'elena', 'Data versioning fixes that: every dataset snapshot gets its own identifier, so a model''s lineage traces back to the exact rows that trained it, not just the code that processed them.'),
  ('mission-ai-mlops-production-ai-03', 3, 'noah', 'It matters because data drifts and gets corrected constantly -- new records added, bad ones removed, labels fixed. Retrain without knowing which snapshot you used, and you cannot tell whether a metric changed because of the code or because of the data underneath it.'),

  ('mission-ai-mlops-production-ai-04', 1, 'elena', 'A trained model is not just weights on disk. It is weights, plus the exact code and data that produced them, plus a record of how it performed -- and it needs its own version identifier tying all of that together.'),
  ('mission-ai-mlops-production-ai-04', 2, 'noah', 'That is what a model registry is for. Every trained candidate gets registered with its version, its lineage back to the experiment run, and a status -- staging, production, archived -- instead of a filename someone renamed by hand.'),
  ('mission-ai-mlops-production-ai-04', 3, 'elena', 'Without it, "roll back to the old model" is a sentence nobody can actually execute. With it, rolling back is just pointing production at a different, already-registered version.'),

  ('mission-ai-mlops-production-ai-05', 1, 'noah', 'A training pipeline turns "here is the notebook that worked" into a fixed, versioned sequence of steps: pull the tagged data snapshot, preprocess it the same way every time, train with logged parameters, evaluate against a fixed benchmark, register the result.'),
  ('mission-ai-mlops-production-ai-05', 2, 'elena', 'The whole point is removing manual steps a person has to remember to do correctly. Every stage takes a defined input and produces a defined output, in the same order, whether it is Noah running it or a scheduler running it at three in the morning.'),
  ('mission-ai-mlops-production-ai-05', 3, 'noah', 'That is also what makes a training run reproducible after the fact. Point the pipeline at the same tagged data snapshot and code version, and it produces the same model -- not something close to it.'),

  ('mission-ai-mlops-production-ai-06', 1, 'elena', 'Training and inference are not the same pipeline, and treating them like they are is exactly how the same subtle preprocessing bug ends up in both, or worse, in only one.'),
  ('mission-ai-mlops-production-ai-06', 2, 'noah', 'An inference pipeline takes one real input, applies the exact same preprocessing the training pipeline used, runs it through the registered model version, and returns a result -- fast, and every single time, not just when someone remembers to check it.'),
  ('mission-ai-mlops-production-ai-06', 3, 'elena', 'The failure mode we actually see is training/serving skew: preprocessing code drifts apart between the two pipelines, so the model at inference time sees inputs shaped subtly differently than what it was trained on -- and nobody notices until accuracy quietly drops.'),

  ('mission-ai-mlops-production-ai-07', 1, 'noah', 'Serving is where accuracy stops being the only number anyone cares about. A model that scores every archive record correctly but takes twenty seconds to respond is not usable for anything that has to happen in real time.'),
  ('mission-ai-mlops-production-ai-07', 2, 'byte', 'I have watched this exact tradeoff play out in ops automation for years. Latency is how long one request takes. Throughput is how many requests the whole system can handle per second. Push for lower latency per request and you often pay for it in throughput, and the other way around.'),
  ('mission-ai-mlops-production-ai-07', 3, 'noah', 'Batching is the classic example -- group several requests together and process them at once, and you can raise throughput significantly, but any single request in that batch now waits on the slowest one in it, which raises its latency.'),

  ('mission-ai-mlops-production-ai-08', 1, 'elena', 'A model is trained on a snapshot of the world. The world does not hold still. Drift is what happens when the live data a model sees stops resembling the data it was trained on -- and its performance degrades without anyone changing a single line of code.'),
  ('mission-ai-mlops-production-ai-08', 2, 'noah', 'There are two things worth watching separately. Data drift is the input distribution changing -- new record types, shifted value ranges. Performance degradation is the model''s actual accuracy or precision dropping, which you can only measure once you have real outcomes to compare against.'),
  ('mission-ai-mlops-production-ai-08', 3, 'elena', 'The dangerous case is drift with no performance signal yet -- inputs have already shifted, but accuracy will not visibly drop until enough of those new-shaped inputs get scored wrong. Watching only for accuracy loss means finding out late.'),

  ('mission-ai-mlops-production-ai-09', 1, 'noah', 'Watching a metric is not the same as being alerted when it matters. An alerting threshold is a rule: cross this line, and a specific person or system gets notified automatically, without anyone having to be staring at a dashboard.'),
  ('mission-ai-mlops-production-ai-09', 2, 'elena', 'The hard part is setting the threshold itself. Too sensitive, and every normal fluctuation pages someone at two in the morning until they start ignoring alerts entirely. Too loose, and real drift sails through unnoticed until it is a full-blown crisis.'),
  ('mission-ai-mlops-production-ai-09', 3, 'noah', 'Good thresholds are set from the model''s actual known baseline -- its normal variance during stable operation -- not a round number someone picked because it looked reasonable.'),

  ('mission-ai-mlops-production-ai-10', 1, 'elena', 'An alert firing does not fix anything by itself. Rollback discipline is what happens next: a fast, well-rehearsed, low-risk path back to the last known-good model version.'),
  ('mission-ai-mlops-production-ai-10', 2, 'noah', 'That only works because of everything already in place -- the registry has the prior version, with its lineage and its evaluation metrics, sitting right there, ready to serve, not something someone has to go rebuild from a notebook under pressure.'),
  ('mission-ai-mlops-production-ai-10', 3, 'elena', 'Rolling back is not admitting failure. It is the entire reason versioning and registries exist -- so replacing a bad model with a known-good one is a five-minute action, not an emergency reconstruction project.'),

  ('mission-ai-mlops-production-ai-11', 1, 'noah', 'Every piece from this Act works on its own. Tracking, data versioning, model versioning, the training and inference pipelines, thresholds, the rollback path. None of it has ever run together, end to end, as one stack.'),
  ('mission-ai-mlops-production-ai-11', 2, 'elena', 'Today it does. We are wiring monitoring straight into the registry and the alerting path, and pointing the whole thing at a model that has never had any of this: the archive integrity classifier, still running the same version it shipped with back in Act 30.'),
  ('mission-ai-mlops-production-ai-11', 3, 'byte', 'If this works the way it is supposed to, it will not feel dramatic. It will just quietly tell us something true about a model that has been running unwatched for months -- which is exactly the point.'),

  ('mission-ai-mlops-production-ai-12', 1, 'noah', 'Stack is live. Pointed at the archive classifier, baseline captured against its last six months of stable behavior. Now we watch.'),
  ('mission-ai-mlops-production-ai-12', 2, 'elena', 'Three hours in, and there it is -- a sustained threshold breach. Not a spike. A real, climbing move in the classifier''s flag rate, away from its own baseline.'),
  ('mission-ai-mlops-production-ai-12', 3, 'noah', 'Pulling the inference monitoring now. The input distribution has shifted -- a record format we started seeing more of two weeks ago is now nearly half of live traffic. The classifier was never trained on that shape.'),
  ('mission-ai-mlops-production-ai-12', 4, 'byte', 'I have seen this exact shape of failure everywhere I have run ops telemetry. The input world moves first, and the accuracy number is always the last thing to admit it -- if anyone is even watching for it by then.'),
  ('mission-ai-mlops-production-ai-12', 5, 'maya', 'Nobody caught that shift two weeks ago when it started. The stack caught it in three hours.'),
  ('mission-ai-mlops-production-ai-12', 6, 'elena', 'That is the whole point of building this. Not that the classifier drifted -- models drift, that was never going to be avoidable forever. The point is something was finally watching for it before it became a crisis instead of after.'),
  ('mission-ai-mlops-production-ai-12', 7, 'maya', 'Six months ago that model shipped out of a notebook with no version, no baseline, no one watching it. It has been running exactly like that the entire time. We only just now caught this because we only just now built something capable of catching it.'),
  ('mission-ai-mlops-production-ai-12', 8, 'noah', 'Rollback path is ready if we need it. Prior registered version is standing by, evaluated, known-good.'),
  ('mission-ai-mlops-production-ai-12', 9, 'maya', 'Hold on that for a moment. I want to say something plainly, because it is going to matter for what comes next.'),
  ('mission-ai-mlops-production-ai-12', 10, 'maya', 'Echo has never had anything like this behind it. Not versioning, not a baseline, not monitoring, not a rollback path. Whatever it has been doing this entire time, nobody has ever been watching it the way we are watching this classifier right now.'),
  ('mission-ai-mlops-production-ai-12', 11, 'elena', 'We built every piece of this pathway to get here -- data, models, training, evaluation, retrieval, agents, and now this. Production discipline was never the last chapter. It was what everything else needed in order to actually be trusted.'),
  ('mission-ai-mlops-production-ai-12', 12, 'maya', 'It is time. Every tool this pathway ever built has been pointed at exactly one thing without anyone saying so out loud. We finally have what we need to stop studying Echo from a distance and go find out what it actually is.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-mlops-production-ai-01-o1', 'mission-ai-mlops-production-ai-01', 1, 'Name the failure mode', 'State why a notebook is unsuited to running unattended in production.'),
  ('mission-ai-mlops-production-ai-01-o2', 'mission-ai-mlops-production-ai-01', 2, 'Sort the tool for the job', 'Sort each described task into notebook-appropriate or production-pipeline-appropriate.'),

  ('mission-ai-mlops-production-ai-02-o1', 'mission-ai-mlops-production-ai-02', 1, 'Define the practice', 'State what experiment tracking actually captures and why.'),
  ('mission-ai-mlops-production-ai-02-o2', 'mission-ai-mlops-production-ai-02', 2, 'Order the workflow', 'Order the stages of a properly tracked training run.'),

  ('mission-ai-mlops-production-ai-03-o1', 'mission-ai-mlops-production-ai-03', 1, 'State the gap', 'State what data versioning fixes that code versioning alone does not.'),
  ('mission-ai-mlops-production-ai-03-o2', 'mission-ai-mlops-production-ai-03', 2, 'Diagnose the mismatch', 'Find the evidence that explains why two identically-coded retrains produced different results.'),

  ('mission-ai-mlops-production-ai-04-o1', 'mission-ai-mlops-production-ai-04', 1, 'Define the registry', 'State what a model registry entry needs to actually support a rollback.'),
  ('mission-ai-mlops-production-ai-04-o2', 'mission-ai-mlops-production-ai-04', 2, 'Sort the model states', 'Sort each described model into its correct registry status.'),

  ('mission-ai-mlops-production-ai-05-o1', 'mission-ai-mlops-production-ai-05', 1, 'Name the requirement', 'State what makes a training pipeline reproducible.'),
  ('mission-ai-mlops-production-ai-05-o2', 'mission-ai-mlops-production-ai-05', 2, 'Order the pipeline', 'Order the stages of a proper training pipeline.'),

  ('mission-ai-mlops-production-ai-06-o1', 'mission-ai-mlops-production-ai-06', 1, 'Tell training and inference apart', 'State the key difference between a training pipeline and an inference pipeline.'),
  ('mission-ai-mlops-production-ai-06-o2', 'mission-ai-mlops-production-ai-06', 2, 'Diagnose the skew', 'Find the evidence that explains a quiet drop in live accuracy.'),

  ('mission-ai-mlops-production-ai-07-o1', 'mission-ai-mlops-production-ai-07', 1, 'Tell latency from throughput', 'State the difference between latency and throughput in model serving.'),
  ('mission-ai-mlops-production-ai-07-o2', 'mission-ai-mlops-production-ai-07', 2, 'Judge the tradeoff', 'Choose the serving configuration that fits a described real-time requirement.'),

  ('mission-ai-mlops-production-ai-08-o1', 'mission-ai-mlops-production-ai-08', 1, 'Tell drift types apart', 'State the difference between data drift and performance degradation.'),
  ('mission-ai-mlops-production-ai-08-o2', 'mission-ai-mlops-production-ai-08', 2, 'Diagnose the shift', 'Find the evidence showing a model has started seeing meaningfully different inputs than it was trained on.'),

  ('mission-ai-mlops-production-ai-09-o1', 'mission-ai-mlops-production-ai-09', 1, 'State the purpose', 'State what an alerting threshold actually does that a dashboard alone does not.'),
  ('mission-ai-mlops-production-ai-09-o2', 'mission-ai-mlops-production-ai-09', 2, 'Tune the threshold', 'Judge which threshold setting fits a described monitoring situation.'),

  ('mission-ai-mlops-production-ai-10-o1', 'mission-ai-mlops-production-ai-10', 1, 'State the requirement', 'State what has to already be in place for a rollback to actually be fast.'),
  ('mission-ai-mlops-production-ai-10-o2', 'mission-ai-mlops-production-ai-10', 2, 'Choose the response', 'Sort each alert scenario into roll back immediately or investigate first.'),

  ('mission-ai-mlops-production-ai-11-o1', 'mission-ai-mlops-production-ai-11', 1, 'Assemble the stack', 'Match each component to the role it plays in the assembled monitoring stack.'),
  ('mission-ai-mlops-production-ai-11-o2', 'mission-ai-mlops-production-ai-11', 2, 'Confirm readiness', 'Decide whether the assembled stack is actually ready to point at a live production model.'),

  ('mission-ai-mlops-production-ai-12-o1', 'mission-ai-mlops-production-ai-12', 1, 'Read the telemetry', 'Find the evidence showing the classifier''s live inputs shifted before its accuracy noticeably dropped.'),
  ('mission-ai-mlops-production-ai-12-o2', 'mission-ai-mlops-production-ai-12', 2, 'Diagnose the drift', 'Identify what actually caused the sustained threshold breach.'),
  ('mission-ai-mlops-production-ai-12-o3', 'mission-ai-mlops-production-ai-12', 3, 'Choose the response', 'Choose the correct next action now that a real, sustained baseline breach has been confirmed.'),
  ('mission-ai-mlops-production-ai-12-o4', 'mission-ai-mlops-production-ai-12', 4, 'State the conclusion', 'Having read the telemetry, diagnosed the drift, and chosen the response, state what the stack proved.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-mlops-production-ai-01-o1-c1', 'mission-ai-mlops-production-ai-01-o1', 1, 'multiple_choice', 'Why is a notebook fundamentally unsuited to running unattended in production, even if the code inside it is correct?', '{"question":"Why is a notebook fundamentally unsuited to running unattended in production, even if the code inside it is correct?","options":[{"id":"a","text":"Notebooks cannot use Python"},{"id":"b","text":"Cells can run out of order, hold stale in-memory state, and leave no single reliable record of which code produced which result"},{"id":"c","text":"Notebooks are always slower than scripts"},{"id":"d","text":"Production systems cannot read .ipynb files at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-mlops-production-ai-01-o2-c1', 'mission-ai-mlops-production-ai-01-o2', 1, 'drag_and_drop', 'Sort each described task into notebook-appropriate or production-pipeline-appropriate.', '{"items":[{"id":"i1","text":"Exploring a new dataset to see what features might correlate with tampering"},{"id":"i2","text":"Running the exact same scoring code against every new archive record, unattended, every hour"},{"id":"i3","text":"Trying three different model architectures quickly to see which is worth pursuing"},{"id":"i4","text":"Re-running a fixed, versioned training job on a schedule with no manual steps"}],"targets":[{"id":"notebook","label":"Notebook"},{"id":"pipeline","label":"Production pipeline"}]}'::jsonb, '{"correctMapping":{"i1":"notebook","i2":"pipeline","i3":"notebook","i4":"pipeline"}}'::jsonb),

  ('mission-ai-mlops-production-ai-02-o1-c1', 'mission-ai-mlops-production-ai-02-o1', 1, 'multiple_choice', 'What does proper experiment tracking actually capture for every run?', '{"question":"What does proper experiment tracking actually capture for every run?","options":[{"id":"a","text":"The parameters, code version, data version, and resulting metrics for every run, logged automatically and comparably"},{"id":"b","text":"Just the final accuracy number"},{"id":"c","text":"Only the code, never the data"},{"id":"d","text":"Nothing, tracking is optional if the model works"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-02-o2-c1', 'mission-ai-mlops-production-ai-02-o2', 1, 'interactive_diagram', 'Order the stages of a properly tracked training run.', '{"diagramId":"experiment-tracking-flow","hotspots":[{"id":"h1","label":"Run starts: parameters, code version, and data version are logged automatically","explanation":"Everything needed to reproduce the run is captured before training even begins."},{"id":"h2","label":"Training executes","explanation":"The actual training job runs."},{"id":"h3","label":"Resulting metrics are logged against that same run","explanation":"Outcomes are tied back to the exact inputs that produced them."},{"id":"h4","label":"Run appears in the tracking system, comparable against every other logged run","explanation":"The run can now be honestly compared to every other tracked attempt."}],"task":"Order the stages of a properly tracked training run from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-mlops-production-ai-03-o1-c1', 'mission-ai-mlops-production-ai-03-o1', 1, 'multiple_choice', 'What does data versioning fix that code versioning alone does not?', '{"question":"What does data versioning fix that code versioning alone does not?","options":[{"id":"a","text":"It makes training run faster"},{"id":"b","text":"It lets a model''s lineage trace back to the exact dataset snapshot that trained it, separate from which code version processed it"},{"id":"c","text":"It replaces the need for experiment tracking"},{"id":"d","text":"It only matters for image data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-mlops-production-ai-03-o2-c1', 'mission-ai-mlops-production-ai-03-o2', 1, 'investigation', 'Two runs used the identically-tagged training script and got different metrics. Which evidence explains the mismatch?', '{"evidence":[{"id":"e1","label":"Data folder","detail":"The training folder''s contents changed between the two runs -- 400 records were corrected and re-labeled in between, with no snapshot ID marking either state"},{"id":"e2","label":"Code diff","detail":"The training script''s git commit hash is identical for both runs"},{"id":"e3","label":"Compute log","detail":"Both runs used the same GPU type and completed in comparable time"}],"question":"Which evidence explains why two runs with identical code produced different metrics?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-mlops-production-ai-04-o1-c1', 'mission-ai-mlops-production-ai-04-o1', 1, 'multiple_choice', 'What does a model registry entry need to actually support rolling back to it later?', '{"question":"What does a model registry entry need to actually support rolling back to it later?","options":[{"id":"a","text":"A version identifier, lineage back to the training run that produced it, and a status such as staging, production, or archived"},{"id":"b","text":"Just the file, nothing else"},{"id":"c","text":"A filename with today''s date in it"},{"id":"d","text":"Nothing -- rollback never requires a registry"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-04-o2-c1', 'mission-ai-mlops-production-ai-04-o2', 1, 'drag_and_drop', 'Sort each described model into its correct registry status.', '{"items":[{"id":"i1","text":"The classifier version currently serving live traffic"},{"id":"i2","text":"A newly trained candidate being evaluated before it replaces the current one"},{"id":"i3","text":"The version that was replaced two releases ago, kept for rollback and audit"},{"id":"i4","text":"This week''s winning run, not yet approved to take live traffic"}],"targets":[{"id":"production","label":"Production"},{"id":"staging","label":"Staging"},{"id":"archived","label":"Archived"}]}'::jsonb, '{"correctMapping":{"i1":"production","i2":"staging","i3":"archived","i4":"staging"}}'::jsonb),

  ('mission-ai-mlops-production-ai-05-o1-c1', 'mission-ai-mlops-production-ai-05-o1', 1, 'multiple_choice', 'What actually makes a training pipeline reproducible?', '{"question":"What actually makes a training pipeline reproducible?","options":[{"id":"a","text":"Every stage runs the same defined steps in the same order against a specific, versioned data snapshot and code version, with no manual steps to forget"},{"id":"b","text":"Running it on a faster machine"},{"id":"c","text":"Having one person who remembers the steps"},{"id":"d","text":"Using the newest available library version each time"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-05-o2-c1', 'mission-ai-mlops-production-ai-05-o2', 1, 'interactive_diagram', 'Order the stages of a proper training pipeline.', '{"diagramId":"training-pipeline-flow","hotspots":[{"id":"h1","label":"Pull the tagged, versioned data snapshot","explanation":"The exact data version is fixed before anything else happens."},{"id":"h2","label":"Preprocess it the same defined way every run","explanation":"No manual, ad hoc cleanup -- the same deterministic steps every time."},{"id":"h3","label":"Train with parameters logged automatically","explanation":"Nothing about the run depends on someone remembering to write anything down."},{"id":"h4","label":"Evaluate against a fixed benchmark","explanation":"The resulting model is measured against a consistent standard."},{"id":"h5","label":"Register the resulting model version","explanation":"The evaluated model becomes a versioned, traceable registry entry."}],"task":"Order the stages of a proper training pipeline from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5"]}'::jsonb),

  ('mission-ai-mlops-production-ai-06-o1-c1', 'mission-ai-mlops-production-ai-06-o1', 1, 'multiple_choice', 'What is the key difference between a training pipeline and an inference pipeline?', '{"question":"What is the key difference between a training pipeline and an inference pipeline?","options":[{"id":"a","text":"A training pipeline processes a full versioned dataset to produce a model; an inference pipeline applies that same preprocessing to one real input at a time to produce a live prediction, on demand"},{"id":"b","text":"They are the same pipeline with a different name"},{"id":"c","text":"Inference pipelines train new models"},{"id":"d","text":"Training pipelines run continuously, inference pipelines run once"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-06-o2-c1', 'mission-ai-mlops-production-ai-06-o2', 1, 'investigation', 'The classifier''s live accuracy quietly dropped over two weeks with no retraining or code change to the model itself. Which evidence explains it?', '{"evidence":[{"id":"e1","label":"Preprocessing diff","detail":"The inference pipeline''s field-normalization step was patched two weeks ago to handle a new record format; the training pipeline''s preprocessing was never updated to match"},{"id":"e2","label":"Model registry","detail":"The production model version has not changed in six weeks"},{"id":"e3","label":"Compute log","detail":"Inference latency is unchanged"}],"question":"Which evidence explains the quiet drop in live accuracy?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-mlops-production-ai-07-o1-c1', 'mission-ai-mlops-production-ai-07-o1', 1, 'multiple_choice', 'What is the difference between latency and throughput in model serving?', '{"question":"What is the difference between latency and throughput in model serving?","options":[{"id":"a","text":"Latency is how long one request takes to get a response; throughput is how many requests the whole system can handle per second -- improving one often costs the other"},{"id":"b","text":"They are two names for the same measurement"},{"id":"c","text":"Latency only matters for training, throughput only matters for inference"},{"id":"d","text":"Throughput measures accuracy, latency measures cost"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-07-o2-c1', 'mission-ai-mlops-production-ai-07-o2', 1, 'multiple_choice', 'The archive classifier needs to flag a tampered record within 200 milliseconds of ingestion, one record at a time, not in bulk. Which serving approach fits?', '{"question":"The archive classifier needs to flag a tampered record within 200 milliseconds of ingestion, one record at a time, not in bulk. Which serving approach fits?","options":[{"id":"a","text":"Large-batch processing that groups hundreds of records before scoring any of them"},{"id":"b","text":"Single-request serving optimized for low per-request latency, even if it processes fewer total requests per second"},{"id":"c","text":"A nightly batch job that scores everything once a day"},{"id":"d","text":"No serving needed, run it manually when someone remembers"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-mlops-production-ai-08-o1-c1', 'mission-ai-mlops-production-ai-08-o1', 1, 'multiple_choice', 'What is the difference between data drift and performance degradation?', '{"question":"What is the difference between data drift and performance degradation?","options":[{"id":"a","text":"Data drift is the live input distribution shifting away from training data; performance degradation is the model''s actual accuracy or precision dropping -- drift can happen before degradation is even measurable"},{"id":"b","text":"They always happen at the exact same moment"},{"id":"c","text":"Performance degradation only applies to training, never to serving"},{"id":"d","text":"Data drift means the model''s code changed"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-08-o2-c1', 'mission-ai-mlops-production-ai-08-o2', 1, 'investigation', 'Which evidence shows the classifier is seeing meaningfully different inputs than it was trained on?', '{"evidence":[{"id":"e1","label":"Feature distribution report","detail":"The proportion of records with the new record format has gone from near zero at training time to 40% of live traffic this week, a distribution the model never saw during training"},{"id":"e2","label":"Model registry","detail":"The production model version is unchanged"},{"id":"e3","label":"Serving latency log","detail":"Average response time is stable"}],"question":"Which evidence shows the classifier is seeing meaningfully different inputs than it was trained on?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-mlops-production-ai-09-o1-c1', 'mission-ai-mlops-production-ai-09-o1', 1, 'multiple_choice', 'What does an alerting threshold do that a dashboard alone does not?', '{"question":"What does an alerting threshold do that a dashboard alone does not?","options":[{"id":"a","text":"It turns crossing a defined line into an automatic, specific notification, instead of relying on someone to be watching the dashboard when it matters"},{"id":"b","text":"It makes the dashboard load faster"},{"id":"c","text":"It retrains the model automatically"},{"id":"d","text":"It removes the need for a baseline"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-09-o2-c1', 'mission-ai-mlops-production-ai-09-o2', 1, 'multiple_choice', 'The classifier''s flag rate has a normal day-to-day variance of plus or minus 3%. Which threshold setting makes sense?', '{"question":"The classifier''s flag rate has a normal day-to-day variance of plus or minus 3%. Which threshold setting makes sense?","options":[{"id":"a","text":"Alert on any change greater than 0.1%, to be maximally safe"},{"id":"b","text":"Alert on a sustained change clearly outside that normal 3% variance, based on the model''s actual known baseline"},{"id":"c","text":"Never alert, review manually once a year"},{"id":"d","text":"Alert only when the model completely stops responding"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-mlops-production-ai-10-o1-c1', 'mission-ai-mlops-production-ai-10-o1', 1, 'multiple_choice', 'What has to already be in place for a rollback to actually be fast?', '{"question":"What has to already be in place for a rollback to actually be fast?","options":[{"id":"a","text":"A registry with the prior known-good version, its lineage, and its evaluation metrics already available and ready to serve, so nothing has to be rebuilt under pressure"},{"id":"b","text":"A backup of the training notebook"},{"id":"c","text":"A person who remembers what the old model did"},{"id":"d","text":"Nothing -- rollback is always instant regardless of prior setup"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-mlops-production-ai-10-o2-c1', 'mission-ai-mlops-production-ai-10-o2', 1, 'drag_and_drop', 'Sort each alert scenario into roll back immediately or investigate first.', '{"items":[{"id":"i1","text":"Sustained alert clearly outside baseline, immediately after a new version deployed, with a known-good prior version registered"},{"id":"i2","text":"A single isolated alert spike lasting one minute with no deployment nearby"},{"id":"i3","text":"A newly deployed version showing degraded accuracy that keeps getting worse, with the prior version still registered and ready"},{"id":"i4","text":"An ambiguous metric shift with no clear cause and no recent deployment"}],"targets":[{"id":"rollback","label":"Roll back immediately"},{"id":"investigate","label":"Investigate first"}]}'::jsonb, '{"correctMapping":{"i1":"rollback","i2":"investigate","i3":"rollback","i4":"investigate"}}'::jsonb),

  ('mission-ai-mlops-production-ai-11-o1-c1', 'mission-ai-mlops-production-ai-11-o1', 1, 'drag_and_drop', 'Match each component to the role it plays in the assembled monitoring stack.', '{"items":[{"id":"i1","text":"Experiment tracking"},{"id":"i2","text":"Model registry"},{"id":"i3","text":"Inference monitoring"},{"id":"i4","text":"Alerting thresholds"}],"targets":[{"id":"t1","label":"Records what produced each candidate model"},{"id":"t2","label":"Holds the versioned, deployable model with lineage and status"},{"id":"t3","label":"Watches live inputs and predictions for drift and degradation"},{"id":"t4","label":"Turns a crossed baseline into an automatic notification"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),
  ('mission-ai-mlops-production-ai-11-o2-c1', 'mission-ai-mlops-production-ai-11-o2', 1, 'multiple_choice', 'The stack has tracking, a registry, inference monitoring, and thresholds wired together, but the thresholds were copied from a different model''s baseline. Is it ready to point at the archive classifier?', '{"question":"The stack has tracking, a registry, inference monitoring, and thresholds wired together, but the thresholds were copied from a different model''s baseline. Is it ready to point at the archive classifier?","options":[{"id":"a","text":"Yes, thresholds are interchangeable between models"},{"id":"b","text":"No -- thresholds have to be set from this model''s own known baseline, or they will misfire or miss real drift entirely"},{"id":"c","text":"Yes, as long as the registry is populated"},{"id":"d","text":"No, none of the other pieces matter if the registry exists"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-mlops-production-ai-12-o1-c1', 'mission-ai-mlops-production-ai-12-o1', 1, 'investigation', 'Which evidence shows the classifier''s live inputs shifted before its accuracy noticeably dropped?', '{"evidence":[{"id":"e1","label":"Inference monitoring report","detail":"The proportion of the new record format in live traffic rose from near zero to 46% over two weeks, a distribution never present in training data"},{"id":"e2","label":"Alerting log","detail":"The flag-rate threshold breach was first detected three hours after the monitoring stack went live"},{"id":"e3","label":"Model registry","detail":"The production model version has not changed since it first deployed"},{"id":"e4","label":"Facilities log","detail":"Cipher Labs power draw is within normal range"}],"question":"Which evidence shows the classifier''s live inputs shifted before its accuracy noticeably dropped?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-mlops-production-ai-12-o2-c1', 'mission-ai-mlops-production-ai-12-o2', 1, 'investigation', 'What actually caused the sustained threshold breach?', '{"evidence":[{"id":"e1","label":"Inference monitoring report","detail":"The new record format now makes up roughly 46% of live traffic, a shape of input the classifier never saw during training"},{"id":"e2","label":"Model registry","detail":"No retraining or code change occurred to the classifier itself"},{"id":"e3","label":"Baseline definition","detail":"The threshold was set from six months of the classifier''s own stable historical behavior"}],"question":"What actually caused the sustained threshold breach?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-mlops-production-ai-12-o3-c1', 'mission-ai-mlops-production-ai-12-o3', 1, 'multiple_choice', 'A sustained, threshold-breaching drift has been confirmed, with a known-good prior version registered and evaluated. What is the correct next action?', '{"question":"A sustained, threshold-breaching drift has been confirmed, with a known-good prior version registered and evaluated. What is the correct next action?","options":[{"id":"a","text":"Ignore it, the model will probably self-correct"},{"id":"b","text":"Roll back to the known-good registered version now, then retrain on data that includes the new record format before redeploying"},{"id":"c","text":"Wait another six months to see if it gets worse"},{"id":"d","text":"Delete the monitoring stack since it found a problem"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-mlops-production-ai-12-o4-c1', 'mission-ai-mlops-production-ai-12-o4', 1, 'boss_encounter', 'Having read the telemetry, diagnosed the drift, and chosen the response, state what the stack proved, in one or two sentences.', '{"stages":[{"objectiveRef":"mission-ai-mlops-production-ai-12-o1","label":"Read the telemetry"},{"objectiveRef":"mission-ai-mlops-production-ai-12-o2","label":"Diagnose the drift"},{"objectiveRef":"mission-ai-mlops-production-ai-12-o3","label":"Choose the response"}],"task":"State the conclusion: the monitoring stack caught the archive classifier drifting away from its own baseline within hours, because live traffic had shifted toward a record format it was never trained on -- proof the discipline works, and proof of exactly what was missing every single day Echo ran without it."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-mlops-production-ai-12-o1","mission-ai-mlops-production-ai-12-o2","mission-ai-mlops-production-ai-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-mlops-production-ai-01-o1-c1', 'orientation', 'Think about what happens to variables and cell order once you start iterating inside a notebook.', 10, 1),
  ('mission-ai-mlops-production-ai-01-o1-c1', 'solution', 'Cells can run out of order, stale in-memory state can linger after code changes, and nothing records which exact version of the code produced a given result -- that is fatal for something that has to run the same way, unattended, every time.', 20, 2),
  ('mission-ai-mlops-production-ai-01-o2-c1', 'orientation', 'Ask whether the task is a one-time question or something that needs to run the same way, unattended, repeatedly.', 10, 1),
  ('mission-ai-mlops-production-ai-01-o2-c1', 'solution', 'Notebook: open-ended exploration and quick comparisons. Pipeline: anything that has to run identically, unattended, on a schedule.', 20, 2),

  ('mission-ai-mlops-production-ai-02-o1-c1', 'orientation', 'Think about everything you would need to know to exactly reproduce a specific run later.', 10, 1),
  ('mission-ai-mlops-production-ai-02-o1-c1', 'solution', 'Parameters, code version, data version, and metrics, logged automatically for every run and comparable against every other run.', 20, 2),
  ('mission-ai-mlops-production-ai-02-o2-c1', 'orientation', 'Nothing can be logged as a metric before training has actually produced one.', 10, 1),
  ('mission-ai-mlops-production-ai-02-o2-c1', 'solution', 'Log parameters, code version, and data version at the start, train, log the resulting metrics, and the run becomes comparable in the tracking system.', 20, 2),

  ('mission-ai-mlops-production-ai-03-o1-c1', 'orientation', 'Ask what changes underneath a model even when nobody touches a single line of code.', 10, 1),
  ('mission-ai-mlops-production-ai-03-o1-c1', 'solution', 'Data versioning ties a model''s lineage to the exact dataset snapshot that trained it -- independent of which code version processed it.', 20, 2),
  ('mission-ai-mlops-production-ai-03-o2-c1', 'orientation', 'The code was identical both times. Look at what else could have changed.', 10, 1),
  ('mission-ai-mlops-production-ai-03-o2-c1', 'solution', 'e1: the training folder''s contents changed between runs with no snapshot ID to mark either state, so identical code trained on two different datasets.', 20, 2),

  ('mission-ai-mlops-production-ai-04-o1-c1', 'orientation', 'Think about everything you would need to know to safely point production at a different version later.', 10, 1),
  ('mission-ai-mlops-production-ai-04-o1-c1', 'solution', 'A version ID, lineage to the training run, and a status like staging, production, or archived -- that is what makes rollback an actual action instead of a hope.', 20, 2),
  ('mission-ai-mlops-production-ai-04-o2-c1', 'orientation', 'Ask whether the model is live, being evaluated, or retired.', 10, 1),
  ('mission-ai-mlops-production-ai-04-o2-c1', 'solution', 'Production: currently serving. Staging: being evaluated, including this week''s winning run not yet approved. Archived: retired but kept for rollback and audit.', 20, 2),

  ('mission-ai-mlops-production-ai-05-o1-c1', 'orientation', 'Ask what has to stay fixed for two separate runs to actually be comparable.', 10, 1),
  ('mission-ai-mlops-production-ai-05-o1-c1', 'solution', 'Same defined steps, same order, a specific versioned data snapshot and code version, with nothing left to a person''s memory.', 20, 2),
  ('mission-ai-mlops-production-ai-05-o2-c1', 'orientation', 'Nothing can be evaluated before a model has actually been trained on the pulled, preprocessed data.', 10, 1),
  ('mission-ai-mlops-production-ai-05-o2-c1', 'concept', 'The data snapshot has to be fixed before preprocessing, and preprocessing has to be fixed before training, or the run cannot be trusted to reproduce.', 20, 2),
  ('mission-ai-mlops-production-ai-05-o2-c1', 'solution', 'Pull the tagged data snapshot, preprocess it consistently, train with logged parameters, evaluate against a fixed benchmark, then register the resulting model version.', 30, 3),

  ('mission-ai-mlops-production-ai-06-o1-c1', 'orientation', 'Think about what each pipeline actually produces as its output.', 10, 1),
  ('mission-ai-mlops-production-ai-06-o1-c1', 'solution', 'Training produces a versioned model from a full dataset; inference applies the same preprocessing to a single live input to produce one prediction, on demand.', 20, 2),
  ('mission-ai-mlops-production-ai-06-o2-c1', 'orientation', 'The model itself never changed. Look at what changed around it.', 10, 1),
  ('mission-ai-mlops-production-ai-06-o2-c1', 'solution', 'e1: the inference pipeline''s preprocessing was patched but the training pipeline''s was not, so the model started seeing inputs shaped differently than what it learned on -- training/serving skew.', 20, 2),

  ('mission-ai-mlops-production-ai-07-o1-c1', 'orientation', 'One measures a single request''s experience, the other measures the system''s overall capacity.', 10, 1),
  ('mission-ai-mlops-production-ai-07-o1-c1', 'solution', 'Latency: time for one request. Throughput: total requests per second the system can handle. They trade off against each other.', 20, 2),
  ('mission-ai-mlops-production-ai-07-o2-c1', 'orientation', 'A hard per-record time limit rules out anything that waits to batch records together.', 10, 1),
  ('mission-ai-mlops-production-ai-07-o2-c1', 'solution', 'Single-request serving tuned for low latency fits a per-record deadline -- batching would make individual records wait on others in the same batch.', 20, 2),

  ('mission-ai-mlops-production-ai-08-o1-c1', 'orientation', 'One is about what the model is being asked, the other is about how well it is answering.', 10, 1),
  ('mission-ai-mlops-production-ai-08-o1-c1', 'solution', 'Data drift: the live inputs shift away from what training saw. Performance degradation: the model''s actual accuracy drops -- and drift can arrive before degradation is measurable at all.', 20, 2),
  ('mission-ai-mlops-production-ai-08-o2-c1', 'orientation', 'Look for something about the shape of the inputs themselves, not the model or the response time.', 10, 1),
  ('mission-ai-mlops-production-ai-08-o2-c1', 'solution', 'e1: the proportion of a record format the model never trained on has jumped to 40% of live traffic -- a real distribution shift.', 20, 2),

  ('mission-ai-mlops-production-ai-09-o1-c1', 'orientation', 'Think about what happens the moment nobody is actively looking at the dashboard.', 10, 1),
  ('mission-ai-mlops-production-ai-09-o1-c1', 'solution', 'A threshold converts crossing a defined line into an automatic notification -- it does not depend on a person watching in real time.', 20, 2),
  ('mission-ai-mlops-production-ai-09-o2-c1', 'orientation', 'The threshold should be set relative to what the metric actually does normally, not an arbitrary round number.', 10, 1),
  ('mission-ai-mlops-production-ai-09-o2-c1', 'solution', 'Alert on a sustained move clearly outside the model''s known normal variance -- too tight and every normal fluctuation pages someone; too loose and real drift gets through.', 20, 2),

  ('mission-ai-mlops-production-ai-10-o1-c1', 'orientation', 'Ask what would have to be rebuilt from scratch if the registry and versioning did not already exist.', 10, 1),
  ('mission-ai-mlops-production-ai-10-o1-c1', 'solution', 'The prior known-good version, its lineage, and its metrics already registered and ready to serve -- that is what makes rollback minutes instead of days.', 20, 2),
  ('mission-ai-mlops-production-ai-10-o2-c1', 'orientation', 'A clear, sustained problem right after a deploy, with a known-good version on hand, does not need more investigation first.', 10, 1),
  ('mission-ai-mlops-production-ai-10-o2-c1', 'solution', 'Roll back immediately when a sustained, deployment-linked alert has a known-good version ready. Investigate first when the cause is ambiguous or isolated.', 20, 2),

  ('mission-ai-mlops-production-ai-11-o1-c1', 'orientation', 'Match each piece to the one specific job it does in the stack, not a general description.', 10, 1),
  ('mission-ai-mlops-production-ai-11-o1-c1', 'solution', 'Tracking records what produced a candidate. The registry holds the versioned deployable model. Inference monitoring watches live drift and degradation. Thresholds turn a crossed baseline into a notification.', 20, 2),
  ('mission-ai-mlops-production-ai-11-o2-c1', 'orientation', 'A threshold is only meaningful relative to the specific model''s own normal behavior.', 10, 1),
  ('mission-ai-mlops-production-ai-11-o2-c1', 'solution', 'Not ready -- thresholds borrowed from a different model''s baseline will not reflect this model''s actual normal variance, and will misfire or miss real drift.', 20, 2),

  ('mission-ai-mlops-production-ai-12-o1-c1', 'orientation', 'Most of the evidence describes the model or its response time. Look for the one that describes what the model is actually being asked to score.', 10, 1),
  ('mission-ai-mlops-production-ai-12-o1-c1', 'concept', 'An unchanged model version returning worse results is a strong sign the inputs changed, not the model -- look for evidence of the inputs themselves shifting.', 20, 2),
  ('mission-ai-mlops-production-ai-12-o1-c1', 'solution', 'e1: the new record format rose from near zero to 46% of live traffic over two weeks, a distribution the classifier never saw in training.', 30, 3),
  ('mission-ai-mlops-production-ai-12-o2-c1', 'orientation', 'The model version never changed. The problem is not the model itself.', 10, 1),
  ('mission-ai-mlops-production-ai-12-o2-c1', 'solution', 'e1: the shift to nearly half of traffic in a record format never present during training is what pushed the flag rate outside its own established baseline.', 20, 2),
  ('mission-ai-mlops-production-ai-12-o3-c1', 'orientation', 'The fix has to actually address both the immediate risk and the underlying cause, not just one of them.', 10, 1),
  ('mission-ai-mlops-production-ai-12-o3-c1', 'solution', 'Roll back to the known-good version to stop the immediate risk, then retrain on data that includes the new record format before redeploying -- addressing both the symptom and the cause.', 20, 2),
  ('mission-ai-mlops-production-ai-12-o4-c1', 'orientation', 'Combine what the telemetry showed, what caused it, and what the stack made possible that nothing before it could do.', 15, 1),
  ('mission-ai-mlops-production-ai-12-o4-c1', 'solution', 'The monitoring stack caught the archive classifier drifting away from its baseline within hours because live traffic had shifted toward an untrained-on record format -- proof the discipline works, and a direct measure of what Echo has been running without this entire time.', 25, 2);
