-- Robotics/Embedded/IoT pathway ("Vector Division") Act 31 -- "Fleets"
-- content, closing Arc VI ("Autonomy Leaves the Lab," Acts 29-31). World
-- row world-vec-fleets already exists (created earlier, index 30 under
-- act-vec-6). 1 campaign, 2 operations, 12 missions (11 lessons + boss),
-- following the same campaigns -> operations -> missions -> dialogue ->
-- objectives -> challenges -> hints pattern as every other pathway. No new
-- ChallengeType needed -- reuses multiple_choice, drag_and_drop,
-- investigation, interactive_diagram, browser_simulation and
-- boss_encounter, same as every prior Act.
--
-- Act 30 closed on a genuinely trustworthy edge device, transitioning
-- into: "One trustworthy edge device is solved. The next question is how
-- to give an entire fleet that same intelligence, at once, without losing
-- track of any single one of them." Act 31 delivers exactly that: the
-- first Nexus-wide staged rollout of edge-AI-capable firmware, at a scale
-- Vector Division has never actually counted before -- device identity,
-- fleet registries, task assignment, heartbeat health, remote
-- diagnostics, telemetry at scale, OTA at scale, staged canary rollouts,
-- fleet maps and automatic failure isolation. It is a positive reveal:
-- three cohorts genuinely fail during the rollout, and are caught and
-- rolled back automatically within minutes, without a single working
-- device ever being touched -- and the registry, counted honestly for the
-- first time, proves the fleet is not thousands of devices but millions,
-- echoing Act 15's "thousands, not one door" reveal at a new order of
-- magnitude. Closes Arc VI, transitioning into Act 32, "Safety-Critical
-- Machines."

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-fleets', 'world-vec-fleets', 'fleets', '6C - Fleets', 'Learn what changes when one intelligent, updatable device becomes a million of them -- device and robot identity, the fleet registry, task assignment, heartbeat and health, remote diagnostics, telemetry at scale, OTA at scale, staged rollouts, fleet maps and failure isolation -- while Vector Division stages the first Nexus-wide rollout of edge-AI firmware and finds out how large the fleet it is responsible for actually is.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-fleets-1', 'campaign-vec-fleets', 'counting-the-fleet', 'Counting the Fleet', 'One robot versus a fleet, device and robot identity, the fleet registry, task assignment, heartbeat and health, and remote diagnostics.', 1),
  ('operation-vec-fleets-2', 'campaign-vec-fleets', 'the-rollout-at-scale', 'The Rollout at Scale', 'Telemetry at scale, OTA at scale, staged rollouts and canaries, fleet maps, failure isolation, and the million-device rollout that held.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-fleets-01', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'one-robot-vs-a-fleet', 'One Robot vs. a Fleet', 'For the first time, Vector Division counts every device Byte has ever registered, not just the facilities the team has physically walked -- and the number is not what anyone expected.', 'beginner', ARRAY['imani','byte'], null, null, '{"type":"simulation","simulationId":"one-robot-vs-a-fleet-sim"}'::jsonb, '{"xp":380,"credits":25}'::jsonb, false, 1),
  ('mission-vec-fleets-02', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'device-and-robot-identity', 'Device and Robot Identity', 'A fleet cannot manage what it cannot tell apart. Every device needs an identity that survives reboots, reassignment, and being one of a million identical-looking units.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-fleets-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"device-and-robot-identity-sim"}'::jsonb, '{"xp":380,"credits":30}'::jsonb, false, 2),
  ('mission-vec-fleets-03', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'the-fleet-registry', 'The Fleet Registry', 'Somewhere, one system has to be the single source of truth for every device that exists -- what it is, where it lives, what firmware it runs, and whether anyone has heard from it lately.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-fleets-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"fleet-registry-sim"}'::jsonb, '{"xp":390,"credits":30}'::jsonb, false, 3),
  ('mission-vec-fleets-04', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'task-assignment', 'Task Assignment', 'A single robot just does what it is told. A fleet has to decide who does what, and get that decision right even when devices come online, go offline, or fail mid-task.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-fleets-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"task-assignment-sim"}'::jsonb, '{"xp":390,"credits":35}'::jsonb, false, 4),
  ('mission-vec-fleets-05', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'heartbeat-and-health', 'Heartbeat and Health', 'A registry entry is a claim. A heartbeat is proof the claim is still true -- and the gap between the two is where a fleet quietly starts losing track of its own devices.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-fleets-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"heartbeat-and-health-sim"}'::jsonb, '{"xp":400,"credits":35}'::jsonb, false, 5),
  ('mission-vec-fleets-06', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-1', 'remote-diagnostics', 'Remote Diagnostics', 'When a device stops reporting, someone has to be able to ask it questions from a distance, without physically standing next to it, and get honest answers back.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-fleets-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"remote-diagnostics-sim"}'::jsonb, '{"xp":400,"credits":35}'::jsonb, false, 6),
  ('mission-vec-fleets-07', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'telemetry-at-scale', 'Telemetry at Scale', 'A million devices reporting individually would drown any dashboard in noise. Telemetry at scale has to answer a different question: not what one device did, but what the fleet is doing.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-vec-fleets-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"telemetry-at-scale-sim"}'::jsonb, '{"xp":410,"credits":40}'::jsonb, false, 7),
  ('mission-vec-fleets-08', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'ota-at-scale', 'OTA at Scale', 'Updating one controller is a known problem. Updating a million of them, correctly, without leaving any of them dead mid-flight, is Tomas Vey''s actual job today.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-fleets-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"ota-at-scale-sim"}'::jsonb, '{"xp":410,"credits":40}'::jsonb, false, 8),
  ('mission-vec-fleets-09', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'staged-rollouts', 'Staged Rollouts and Canaries', 'Nobody pushes new firmware to every device at once. A staged rollout moves in waves on purpose, so a bad build is only ever wrong for the smallest group possible.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-fleets-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"staged-rollouts-sim"}'::jsonb, '{"xp":420,"credits":40}'::jsonb, false, 9),
  ('mission-vec-fleets-10', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'fleet-maps', 'Fleet Maps', 'A registry is a list. A fleet map is the same information laid out so a person can actually see where trouble is clustering before it spreads any further.', 'beginner', ARRAY['byte','imani'], '{"requiredMissionIds":["mission-vec-fleets-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"fleet-maps-sim"}'::jsonb, '{"xp":420,"credits":45}'::jsonb, false, 10),
  ('mission-vec-fleets-11', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'failure-isolation', 'Failure Isolation', 'A canary catching a problem only matters if the fleet actually does something about it -- automatically, immediately, without waiting for a person to notice first.', 'beginner', ARRAY['byte','sera'], '{"requiredMissionIds":["mission-vec-fleets-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"failure-isolation-sim"}'::jsonb, '{"xp":430,"credits":45}'::jsonb, false, 11),
  ('mission-vec-fleets-12', 'world-vec-fleets', 'campaign-vec-fleets', 'operation-vec-fleets-2', 'the-million-device-rollout', 'The Million-Device Rollout', 'Every lesson this Act taught, running at once, on a rollout that finally reaches the fleet''s true size -- staged waves, live health telemetry and automatic failure isolation, deciding in minutes whether millions of devices keep the update or get it pulled back.', 'boss', ARRAY['imani','byte','tomas'], '{"requiredMissionIds":["mission-vec-fleets-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"million-device-rollout-boss-sim"}'::jsonb, '{"xp":2600,"credits":500,"badgeIds":["the-million-device-rollout"],"skillXp":{"robotics_fundamentals":370}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-fleets-01', 1, 'imani', 'Act 30 proved one edge device could think correctly with no uplink at all. Today we stop talking about one device.'),
  ('mission-vec-fleets-01', 2, 'byte', 'I have been quietly running the number while you talk. Every registration, every fleet manager, every facility Vector Division has physically walked -- that count has always been the number I report.'),
  ('mission-vec-fleets-01', 3, 'imani', 'That count is not the real count. I need the number if we stop restricting it to facilities we have walked, and count every device you have ever registered, Nexus-wide.'),
  ('mission-vec-fleets-01', 4, 'byte', 'Running that query for the first time in my existence. One moment.'),
  ('mission-vec-fleets-01', 5, 'byte', 'That number is not thousands. Counted honestly, Nexus-wide, it is in the millions. I have never said that word about anything Vector Division is responsible for before.'),
  ('mission-vec-fleets-01', 6, 'imani', 'One device''s lessons -- identity, health, safe updates -- have to hold at that count, all at once, without losing track of a single one. That is what we stage by the end of this Act.'),
  ('mission-vec-fleets-01', 7, 'byte', 'Then it is worth finding out whether ''one robot'' and ''a fleet'' are actually the same problem at a different size, or something else entirely.'),

  ('mission-vec-fleets-02', 1, 'byte', 'Ask a fleet management system which device this is, and it cannot answer with a serial number stamped on a case somewhere. It needs an identity the software itself can verify, every single time, at any scale.'),
  ('mission-vec-fleets-02', 2, 'byte', 'A device identity is not just a name. It is a unique identifier tied to a specific physical unit, one that survives a reboot, a firmware update, even a physical reassignment to a different facility -- or the fleet starts mixing devices up the moment two of them look alike.'),
  ('mission-vec-fleets-02', 3, 'imani', 'We already lost track of one door once because nobody thought to ask what actually identified it as itself. I am not doing that again at a million times the scale.'),

  ('mission-vec-fleets-03', 1, 'byte', 'The fleet registry is the single source of truth: every device''s identity, its current firmware version, its last known location, and the last time it reported in, all queryable in one place.'),
  ('mission-vec-fleets-03', 2, 'byte', 'Before today, that registry only held devices Vector Division had physically onboarded. It never had an entry for anything we had not personally walked up to.'),
  ('mission-vec-fleets-03', 3, 'imani', 'Then the first job is not staging a rollout. It is making the registry tell the truth about how many devices actually exist, not how many we have personally met.'),

  ('mission-vec-fleets-04', 1, 'byte', 'One robot only ever has one job: whatever it was told to do. A fleet has to decide who does what, and get that decision right again the instant a device goes offline mid-task.'),
  ('mission-vec-fleets-04', 2, 'byte', 'A task assignment scheme is either static, one job per device forever, or dynamic, reassigned live based on who is actually available and healthy right now.'),
  ('mission-vec-fleets-04', 3, 'imani', 'Static assignment is simple, right up until a device fails. Then it is simply wrong, and nobody notices until whatever that device owned quietly stops happening at all.'),

  ('mission-vec-fleets-05', 1, 'byte', 'A heartbeat is a small, regular signal a device sends just to say it is still alive and functioning -- not what it is doing, only that it is still there to ask.'),
  ('mission-vec-fleets-05', 2, 'byte', 'A registry entry is a claim about a device. A heartbeat is the only thing keeping that claim honest over time. Miss enough heartbeats, and the registry is describing a device that may no longer actually exist in that state.'),
  ('mission-vec-fleets-05', 3, 'imani', 'Health is not binary forever. A device can be healthy, degraded, or unresponsive, and the fleet has to tell those three apart in real time, not after something breaks.'),

  ('mission-vec-fleets-06', 1, 'byte', 'When a device goes quiet or reports something strange, someone needs to be able to ask it direct questions from here -- current firmware version, last error code, memory usage -- without a technician standing next to it.'),
  ('mission-vec-fleets-06', 2, 'byte', 'Remote diagnostics only works if the device can still answer at all. A device that has genuinely failed cannot self-report why it failed, which is its own kind of answer.'),
  ('mission-vec-fleets-06', 3, 'imani', 'Byte, run it against the test cohort first. I want proof this actually tells us something true before we trust it against the real number.'),

  ('mission-vec-fleets-07', 1, 'byte', 'One device''s telemetry is a story. A million devices'' telemetry is a statistic, and the fleet cannot afford to read every device''s story individually.'),
  ('mission-vec-fleets-07', 2, 'byte', 'At scale, telemetry has to be aggregated -- rolled up by cohort, by firmware version, by facility -- so a person can ask whether the fleet is healthy and get an answer in seconds, not a scroll through a million individual logs.'),
  ('mission-vec-fleets-07', 3, 'byte', 'The individual record still exists underneath, for when something specific needs investigating. It is simply never the first thing anyone looks at anymore.'),

  ('mission-vec-fleets-08', 1, 'tomas', 'Tomas Vey, again. Over-the-air update on one board is a known quantity by now. A million boards, simultaneously, with real bandwidth limits and real devices that can lose power mid-flash, is a very different problem.'),
  ('mission-vec-fleets-08', 2, 'tomas', 'The core rule does not change with scale: verify the image before flashing it, keep a fallback the device can boot into if the new image fails, and never leave a device with no working firmware at all, no matter how many are updating at once.'),
  ('mission-vec-fleets-08', 3, 'byte', 'Scale just multiplies the ways that rule can be violated. Bandwidth gets shared across every device downloading at once, and a fallback that works for one device has to work identically for all of them.'),

  ('mission-vec-fleets-09', 1, 'tomas', 'Nobody sane pushes new firmware to every device simultaneously. A staged rollout moves in canary waves -- a small percentage first, then more, then the rest -- so a bad build only ever touches the smallest group possible.'),
  ('mission-vec-fleets-09', 2, 'tomas', 'Each wave gets watched before the next one starts. If the canary wave looks wrong, the rollout stops there. It never gets the chance to reach wave two.'),
  ('mission-vec-fleets-09', 3, 'byte', 'The wave size is a bet: small enough that a failure costs almost nothing, large enough that a real problem actually shows up statistically instead of hiding in noise.'),

  ('mission-vec-fleets-10', 1, 'byte', 'A registry answers what exists. A fleet map answers where trouble is clustering -- the same data, laid out so a human eye can spot a pattern a list of rows would hide.'),
  ('mission-vec-fleets-10', 2, 'byte', 'Group failures by facility, by firmware version, by cohort, and a fleet map turns ''three devices failed somewhere'' into ''three devices failed, all in the same canary wave, all on the same build'' -- which is an actual lead.'),
  ('mission-vec-fleets-10', 3, 'imani', 'I do not want a wall of green dots. I want the map to make it obvious the instant something stops being green.'),

  ('mission-vec-fleets-11', 1, 'sera', 'Sera Holt. A canary wave catching a bad build is worthless if a person still has to notice it and manually pull the update. At this scale, noticing has to be automatic, or it might as well not happen at all.'),
  ('mission-vec-fleets-11', 2, 'byte', 'Failure isolation means containing a bad outcome to the smallest possible blast radius the moment it is detected -- pausing the rollout and rolling back the affected cohort, without ever letting a failing wave touch the next one.'),
  ('mission-vec-fleets-11', 3, 'sera', 'Automatic does not mean unaccountable. Every automatic rollback still has to be explainable afterward, in plain terms, to someone who was not watching it happen.'),

  ('mission-vec-fleets-12', 1, 'imani', 'Everyone standing by. This is not a test cohort anymore. In four minutes we push the staged rollout live against every device Byte has ever registered, Nexus-wide, all at once.'),
  ('mission-vec-fleets-12', 2, 'byte', 'Wave one is live. Canary cohort, two percent of the fleet, watching health telemetry in real time. So far, green across the board.'),
  ('mission-vec-fleets-12', 3, 'byte', 'Wave two started clean. Then three cohorts, anywhere in the wave, went from healthy to unresponsive within the same ninety-second window. Not adjacent facilities. Not the same hardware batch. Simply three, at once.'),
  ('mission-vec-fleets-12', 4, 'tomas', 'Automatic failure isolation already caught it. All three cohorts paused, rolled back, and quarantined from the next wave before I even finished reading the alert. Nothing outside those three was ever touched.'),
  ('mission-vec-fleets-12', 5, 'byte', 'Final count, now that the rollout has actually run against the real registry instead of a subset: the fleet is not thousands of devices. Counted Nexus-wide, the way we should have been counting from the start, it is in the millions. I have never said that number about anything Vector Division owns before today.'),
  ('mission-vec-fleets-12', 6, 'imani', 'The rollout did not succeed because nothing went wrong. It succeeded because everything that went wrong was caught and contained exactly the way it was designed to be, without a single working device ever being touched by the failure.'),
  ('mission-vec-fleets-12', 7, 'imani', 'That closes it. The fleet is unified, updated, and finally intelligent enough to act for itself in the moments that matter. That capability is no longer the open question. What happens when it makes the wrong call, at this scale, is -- and that is where we go next.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-fleets-01-o1', 'mission-vec-fleets-01', 1, 'Tell one device from a fleet', 'Sort what changes in kind, not just in degree, once a single robot becomes a fleet of them.'),
  ('mission-vec-fleets-01-o2', 'mission-vec-fleets-01', 2, 'Judge why the honest count matters', 'Judge why counting every registered device Nexus-wide matters more than counting only what has been physically walked.'),

  ('mission-vec-fleets-02-o1', 'mission-vec-fleets-02', 1, 'Define device identity', 'Choose the accurate description of what a device identity actually is.'),
  ('mission-vec-fleets-02-o2', 'mission-vec-fleets-02', 2, 'Explain why identity must be deliberate', 'Find the evidence explaining why device identity has to be assigned deliberately, not assumed from manufacturing defaults.'),

  ('mission-vec-fleets-03-o1', 'mission-vec-fleets-03', 1, 'Define the fleet registry', 'Choose the accurate description of what the fleet registry actually is.'),
  ('mission-vec-fleets-03-o2', 'mission-vec-fleets-03', 2, 'Explain the undercount', 'Find the evidence explaining why the registry undercounted the real fleet before today.'),

  ('mission-vec-fleets-04-o1', 'mission-vec-fleets-04', 1, 'Tell static from dynamic assignment', 'Sort each task assignment example into static or dynamic.'),
  ('mission-vec-fleets-04-o2', 'mission-vec-fleets-04', 2, 'Judge why static assignment breaks at scale', 'Judge why static task assignment fails differently across a fleet than it would for a single device.'),

  ('mission-vec-fleets-05-o1', 'mission-vec-fleets-05', 1, 'Define a heartbeat', 'Choose the accurate description of what a heartbeat signal actually confirms.'),
  ('mission-vec-fleets-05-o2', 'mission-vec-fleets-05', 2, 'Explain the missed-heartbeat threshold', 'Find the evidence explaining why a single missed heartbeat does not immediately mark a device as unhealthy.'),

  ('mission-vec-fleets-06-o1', 'mission-vec-fleets-06', 1, 'Define remote diagnostics', 'Choose the accurate description of what remote diagnostics actually provides.'),
  ('mission-vec-fleets-06-o2', 'mission-vec-fleets-06', 2, 'Find the honest response', 'Identify which diagnostic response indicates the device is healthy and answering honestly.'),

  ('mission-vec-fleets-07-o1', 'mission-vec-fleets-07', 1, 'Explain why telemetry must aggregate', 'Choose the accurate description of why telemetry at fleet scale differs from single-device telemetry.'),
  ('mission-vec-fleets-07-o2', 'mission-vec-fleets-07', 2, 'Sort aggregate from individual', 'Sort each telemetry statement into aggregate/rolled-up or individual device record.'),

  ('mission-vec-fleets-08-o1', 'mission-vec-fleets-08', 1, 'State the OTA rule at any scale', 'Choose the accurate statement of the core OTA safety rule that does not change with scale.'),
  ('mission-vec-fleets-08-o2', 'mission-vec-fleets-08', 2, 'Order the OTA-at-scale sequence', 'Order the OTA-at-scale update sequence from first to last.'),

  ('mission-vec-fleets-09-o1', 'mission-vec-fleets-09', 1, 'Define a staged canary rollout', 'Choose the accurate description of what a staged, canary-based rollout actually is.'),
  ('mission-vec-fleets-09-o2', 'mission-vec-fleets-09', 2, 'Order the rollout waves', 'Order the staged rollout''s waves from first to last.'),

  ('mission-vec-fleets-10-o1', 'mission-vec-fleets-10', 1, 'Define a fleet map', 'Choose the accurate description of what a fleet map adds beyond the raw registry.'),
  ('mission-vec-fleets-10-o2', 'mission-vec-fleets-10', 2, 'Spot the clustering pattern', 'Find the evidence showing why plotting failures on a fleet map reveals an actual pattern.'),

  ('mission-vec-fleets-11-o1', 'mission-vec-fleets-11', 1, 'Define failure isolation', 'Choose the accurate description of what failure isolation actually does during a rollout.'),
  ('mission-vec-fleets-11-o2', 'mission-vec-fleets-11', 2, 'Prove containment was automatic', 'Find the evidence proving the failing cohorts were contained automatically, without a person intervening first.'),

  ('mission-vec-fleets-12-o1', 'mission-vec-fleets-12', 1, 'Confirm the wave structure held', 'Confirm via staged-rollout and canary reasoning that the wave structure correctly limited the blast radius of the failing cohorts.'),
  ('mission-vec-fleets-12-o2', 'mission-vec-fleets-12', 2, 'Prove the automatic rollback', 'Prove via heartbeat, health and failure-isolation reasoning that the three failing cohorts were detected and rolled back automatically within minutes.'),
  ('mission-vec-fleets-12-o3', 'mission-vec-fleets-12', 3, 'Confirm the true fleet count', 'Confirm via fleet-registry and telemetry-at-scale reasoning that the final registry count genuinely reached into the millions once counted Nexus-wide.'),
  ('mission-vec-fleets-12-o4', 'mission-vec-fleets-12', 4, 'State the outcome', 'Having confirmed all three, state what the rollout actually proved about the fleet and about Vector Division''s next problem.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-fleets-01-o1-c1', 'mission-vec-fleets-01-o1', 1, 'drag_and_drop', 'Sort each statement into what is true of one robot, or what is true of a fleet.', '{"items":[{"id":"i1","text":"A single controller''s health can be checked by walking up to it"},{"id":"i2","text":"Millions of devices need a single system tracking whether each one is still alive, right now"},{"id":"i3","text":"One firmware update means flashing one board and watching it boot"},{"id":"i4","text":"An update rolled out badly must be contained to a small group automatically, not caught by a person watching one screen"}],"targets":[{"id":"one_robot","label":"One Robot"},{"id":"fleet","label":"A Fleet"}]}'::jsonb, '{"correctMapping":{"i1":"one_robot","i2":"fleet","i3":"one_robot","i4":"fleet"}}'::jsonb),
  ('mission-vec-fleets-01-o2-c1', 'mission-vec-fleets-01-o2', 1, 'multiple_choice', 'Byte''s old count only reflected facilities Vector Division has physically walked. Why does counting every registered device Nexus-wide matter more than that old number?', '{"question":"Byte''s old count only reflected facilities Vector Division has physically walked. Why does counting every registered device Nexus-wide matter more than that old number?","options":[{"id":"a","text":"It does not, the two numbers should always match"},{"id":"b","text":"A fleet is only as accurate as what it actually tracks -- if the registry only reflects what one team has personally visited, the real fleet, and its real risk, stays invisible until something fails"},{"id":"c","text":"Nexus-wide counting is only useful for billing purposes"},{"id":"d","text":"The smaller number is always safer to plan a rollout around"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-fleets-02-o1-c1', 'mission-vec-fleets-02-o1', 1, 'multiple_choice', 'A device identity, in a fleet context, is best described as...', '{"question":"A device identity, in a fleet context, is best described as...","options":[{"id":"a","text":"Whatever name a technician happens to write on the case"},{"id":"b","text":"A unique identifier tied to one specific physical unit, that survives reboots, firmware updates and even reassignment, so the fleet never confuses two devices for each other"},{"id":"c","text":"The device''s current IP address"},{"id":"d","text":"A property that only matters if the device is online right now"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-02-o2-c1', 'mission-vec-fleets-02-o2', 1, 'investigation', 'Which evidence explains why device identity has to be assigned deliberately, not assumed from manufacturing defaults?', '{"evidence":[{"id":"e1","label":"Provisioning log","detail":"Two newly manufactured controllers were flashed with the same default serial number before a unique-identity step was added to the process"},{"id":"e2","label":"Facilities note","detail":"The affected devices were later assigned to different regions"},{"id":"e3","label":"Power log","detail":"Both devices report normal voltage"}],"question":"Which evidence explains why device identity has to be assigned deliberately, not assumed from manufacturing defaults?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-fleets-03-o1-c1', 'mission-vec-fleets-03-o1', 1, 'multiple_choice', 'The fleet registry is best described as...', '{"question":"The fleet registry is best described as...","options":[{"id":"a","text":"A folder of individual maintenance notes kept by each facility"},{"id":"b","text":"The single source of truth for every device''s identity, current firmware version, last known location and last time it reported in, queryable in one place"},{"id":"c","text":"A backup copy of each device''s firmware image"},{"id":"d","text":"A list that only includes devices currently powered on"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-03-o2-c1', 'mission-vec-fleets-03-o2', 1, 'investigation', 'Which evidence explains why the registry undercounted the real fleet before today?', '{"evidence":[{"id":"e1","label":"Registry audit","detail":"The registry historically only gained an entry when a Vector Division technician personally onboarded a device on site"},{"id":"e2","label":"Nexus device directory","detail":"A separate, Nexus-wide device directory already existed with entries the registry had never imported"},{"id":"e3","label":"Power log","detail":"Devices continue drawing normal power whether registered or not"}],"question":"Which evidence explains why the registry undercounted the real fleet before today?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-fleets-04-o1-c1', 'mission-vec-fleets-04-o1', 1, 'drag_and_drop', 'Sort each example into static or dynamic task assignment.', '{"items":[{"id":"i1","text":"Each device is permanently assigned one fixed job when it is provisioned, never reassigned"},{"id":"i2","text":"Jobs are reassigned live based on which devices are currently online and healthy"},{"id":"i3","text":"A device that fails mid-task keeps its job forever until a technician intervenes manually"},{"id":"i4","text":"A device going offline triggers its job to be picked up by another available device automatically"}],"targets":[{"id":"static","label":"Static assignment"},{"id":"dynamic","label":"Dynamic assignment"}]}'::jsonb, '{"correctMapping":{"i1":"static","i2":"dynamic","i3":"static","i4":"dynamic"}}'::jsonb),
  ('mission-vec-fleets-04-o2-c1', 'mission-vec-fleets-04-o2', 1, 'multiple_choice', 'Why does static task assignment break down at fleet scale in a way it might not for a single device?', '{"question":"Why does static task assignment break down at fleet scale in a way it might not for a single device?","options":[{"id":"a","text":"Static assignment is always wrong, even for one device"},{"id":"b","text":"With a single device a failure is obvious immediately; across a fleet, a statically assigned device can fail silently, and whatever it owned simply stops happening until someone notices the gap"},{"id":"c","text":"Dynamic assignment uses less network bandwidth"},{"id":"d","text":"Static assignment only works with wired connections"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-fleets-05-o1-c1', 'mission-vec-fleets-05-o1', 1, 'multiple_choice', 'A heartbeat, in fleet monitoring, is best described as...', '{"question":"A heartbeat, in fleet monitoring, is best described as...","options":[{"id":"a","text":"A full telemetry report sent once per day"},{"id":"b","text":"A small, regular signal a device sends to confirm it is still alive and functioning, independent of what task it is actually performing"},{"id":"c","text":"An error message sent only when something breaks"},{"id":"d","text":"A command sent from the fleet manager to the device"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-05-o2-c1', 'mission-vec-fleets-05-o2', 1, 'investigation', 'Which evidence explains why a single missed heartbeat does not immediately mark a device as unhealthy?', '{"evidence":[{"id":"e1","label":"Health monitor log","detail":"A device is marked unhealthy only after missing three consecutive expected heartbeats, not after missing one"},{"id":"e2","label":"Power log","detail":"The device''s power draw stayed nominal throughout"},{"id":"e3","label":"Facilities note","detail":"The device is physically located in a hard-to-reach maintenance shaft"}],"question":"Which evidence explains why a single missed heartbeat does not immediately mark a device as unhealthy?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-fleets-06-o1-c1', 'mission-vec-fleets-06-o1', 1, 'multiple_choice', 'Remote diagnostics is best described as...', '{"question":"Remote diagnostics is best described as...","options":[{"id":"a","text":"Physically opening a device to inspect its board"},{"id":"b","text":"The ability to query a device''s current state -- firmware version, last error, resource usage -- from a distance, without anyone standing next to it"},{"id":"c","text":"A log file stored only on the device itself"},{"id":"d","text":"A feature that only works after a device has already failed completely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-06-o2-c1', 'mission-vec-fleets-06-o2', 1, 'browser_simulation', 'Which diagnostic response indicates the device is healthy and answering honestly?', '{"screen":"REMOTE DIAGNOSTIC CONSOLE -- TEST COHORT","question":"Which diagnostic response indicates the device is healthy and answering honestly?","records":[{"id":"r1","code":"NO_RESPONSE","detail":"Device did not answer the diagnostic query at all"},{"id":"r2","code":"REPORT_OK","detail":"Firmware v4.2.1, uptime 14d, last error: none, memory usage nominal"},{"id":"r3","code":"PARTIAL_TIMEOUT","detail":"Device answered the identity query but timed out on the firmware version query"},{"id":"r4","code":"STALE_CACHE","detail":"Response matches a cached report from six hours prior, not a live read"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),

  ('mission-vec-fleets-07-o1-c1', 'mission-vec-fleets-07-o1', 1, 'multiple_choice', 'Telemetry at fleet scale differs from single-device telemetry mainly in that...', '{"question":"Telemetry at fleet scale differs from single-device telemetry mainly in that...","options":[{"id":"a","text":"It stops being useful once there are too many devices"},{"id":"b","text":"It has to be aggregated -- rolled up by cohort, firmware version or facility -- so a person can judge overall fleet health without reading a million individual records"},{"id":"c","text":"It only ever reports errors, never normal status"},{"id":"d","text":"It requires every device to report on the exact same schedule"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-07-o2-c1', 'mission-vec-fleets-07-o2', 1, 'drag_and_drop', 'Sort each telemetry statement into aggregate/rolled-up or individual device record.', '{"items":[{"id":"i1","text":"94% of devices on firmware v4.2.1 report healthy"},{"id":"i2","text":"Device unit-88213 reports firmware v4.2.1, healthy"},{"id":"i3","text":"Cohort west-annex-3 shows a 6% unhealthy rate, above the 2% baseline"},{"id":"i4","text":"Device unit-04471''s last heartbeat was 12 seconds ago"}],"targets":[{"id":"aggregate","label":"Aggregate/rolled-up view"},{"id":"individual","label":"Individual device record"}]}'::jsonb, '{"correctMapping":{"i1":"aggregate","i2":"individual","i3":"aggregate","i4":"individual"}}'::jsonb),

  ('mission-vec-fleets-08-o1-c1', 'mission-vec-fleets-08-o1', 1, 'multiple_choice', 'The core safety rule for an over-the-air update does not change with fleet scale. That rule is...', '{"question":"The core safety rule for an over-the-air update does not change with fleet scale. That rule is...","options":[{"id":"a","text":"Update as many devices as possible as fast as possible"},{"id":"b","text":"Verify the new image before flashing it, and keep a fallback the device can boot into if the new image fails, so no device is ever left with no working firmware at all"},{"id":"c","text":"Only update devices that are already online"},{"id":"d","text":"Skip verification once a build has passed once, to save time"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-08-o2-c1', 'mission-vec-fleets-08-o2', 1, 'interactive_diagram', 'Order the OTA-at-scale update sequence from first to last.', '{"diagramId":"ota-at-scale-flow","hotspots":[{"id":"download","label":"Download","explanation":"Device downloads the new firmware image, sharing available bandwidth with every other device updating at once."},{"id":"verify","label":"Verify","explanation":"Device checks the image''s integrity and signature before touching its working firmware."},{"id":"flash_backup","label":"Flash to backup slot","explanation":"New image is written to a secondary slot, leaving the current working firmware untouched."},{"id":"boot_test","label":"Boot and self-test","explanation":"Device boots into the new image and confirms it is actually functional."},{"id":"commit","label":"Commit or roll back","explanation":"Device marks the new image as active, or automatically reverts to the previous working image if the self-test failed."}],"task":"Order the OTA-at-scale update sequence from first to last."}'::jsonb, '{"correctOrderIds":["download","verify","flash_backup","boot_test","commit"]}'::jsonb),

  ('mission-vec-fleets-09-o1-c1', 'mission-vec-fleets-09-o1', 1, 'multiple_choice', 'A staged, canary-based rollout means...', '{"question":"A staged, canary-based rollout means...","options":[{"id":"a","text":"Pushing the new firmware to every device at the exact same time"},{"id":"b","text":"Releasing the update to a small percentage of the fleet first, watching its health, and only expanding to larger waves if that canary group stays healthy"},{"id":"c","text":"Only updating devices chosen at random with no monitoring afterward"},{"id":"d","text":"Testing the update exclusively in a lab, never on real fleet devices"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-09-o2-c1', 'mission-vec-fleets-09-o2', 1, 'interactive_diagram', 'Order the staged rollout''s waves from first to last.', '{"diagramId":"staged-rollout-waves","hotspots":[{"id":"canary","label":"Canary wave","explanation":"A small percentage of the fleet, watched closely before anything else proceeds."},{"id":"early","label":"Early wave","explanation":"A larger slice, released only once the canary wave stays healthy."},{"id":"broad","label":"Broad wave","explanation":"Most of the remaining fleet, released once earlier waves confirm the build is sound."},{"id":"full","label":"Full fleet","explanation":"The rollout completes across every remaining device."}],"task":"Order the staged rollout''s waves from first to last."}'::jsonb, '{"correctOrderIds":["canary","early","broad","full"]}'::jsonb),

  ('mission-vec-fleets-10-o1-c1', 'mission-vec-fleets-10-o1', 1, 'multiple_choice', 'A fleet map, compared to the raw registry, is best described as...', '{"question":"A fleet map, compared to the raw registry, is best described as...","options":[{"id":"a","text":"A completely separate data source with its own numbers"},{"id":"b","text":"The same registry and telemetry data, laid out visually by facility, cohort or firmware version so a person can spot a clustering pattern that a list of rows would hide"},{"id":"c","text":"A tool that only shows devices currently offline"},{"id":"d","text":"A static image updated once a day"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-10-o2-c1', 'mission-vec-fleets-10-o2', 1, 'investigation', 'Which evidence shows why plotting failures on a fleet map, instead of reading them as isolated rows, reveals an actual pattern?', '{"evidence":[{"id":"e1","label":"Fleet map view","detail":"Three unhealthy devices, plotted, all fall inside the same canary wave and the same firmware build -- not scattered randomly across the fleet"},{"id":"e2","label":"Weather report","detail":"The affected region experienced normal weather conditions"},{"id":"e3","label":"Facilities note","detail":"The three facilities have no shared physical infrastructure"}],"question":"Which evidence shows why plotting failures on a fleet map, instead of reading them as isolated rows, reveals an actual pattern?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-fleets-11-o1-c1', 'mission-vec-fleets-11-o1', 1, 'multiple_choice', 'Failure isolation, in a fleet rollout, means...', '{"question":"Failure isolation, in a fleet rollout, means...","options":[{"id":"a","text":"Waiting for a human to notice a problem before doing anything about it"},{"id":"b","text":"Automatically containing a detected failure to the smallest possible group of devices -- pausing the rollout and rolling back only the affected cohort, without letting it reach the next wave"},{"id":"c","text":"Shutting down the entire fleet the moment any single device reports an error"},{"id":"d","text":"Ignoring failures below a certain severity threshold permanently"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-11-o2-c1', 'mission-vec-fleets-11-o2', 1, 'investigation', 'Which evidence proves the failing cohorts were contained automatically, without a person having to notice and intervene first?', '{"evidence":[{"id":"e1","label":"Rollback log","detail":"The moment three cohorts failed health checks, the rollout system automatically paused those cohorts and reverted them to the last known-good firmware, without pausing the wave for any healthy cohort"},{"id":"e2","label":"Access log","detail":"No engineer logged into the rollout console during the failure window"},{"id":"e3","label":"Power log","detail":"Facility-wide power stayed within normal range throughout"}],"question":"Which evidence proves the failing cohorts were contained automatically, without a person having to notice and intervene first?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-fleets-12-o1-c1', 'mission-vec-fleets-12-o1', 1, 'multiple_choice', 'The three failing cohorts appeared inside a rollout wave already in progress. What proves the staged wave structure actually limited the blast radius, rather than the fleet simply getting lucky?', '{"question":"The three failing cohorts appeared inside a rollout wave already in progress. What proves the staged wave structure actually limited the blast radius, rather than the fleet simply getting lucky?","options":[{"id":"a","text":"Luck -- the three cohorts happened to be small ones"},{"id":"b","text":"The failures were contained to the wave already in progress and never reached the un-released remainder of the fleet, exactly the outcome canary staging is designed to guarantee"},{"id":"c","text":"The devices that failed were the only ones running the new firmware anywhere in the fleet"},{"id":"d","text":"The rollout had already finished before the failures were noticed"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-12-o2-c1', 'mission-vec-fleets-12-o2', 1, 'investigation', 'Which evidence proves the three failing cohorts were detected and automatically rolled back within minutes, with no working device ever touched?', '{"evidence":[{"id":"e1","label":"Health telemetry timeline","detail":"Three cohorts transitioned from healthy to unresponsive within a ninety-second window; automatic rollback for all three completed within four minutes of the first missed heartbeat, with zero manual intervention logged"},{"id":"e2","label":"Facilities note","detail":"The three cohorts share no physical location or hardware batch"},{"id":"e3","label":"Access log","detail":"No engineer was logged into the rollout console during the incident"}],"question":"Which evidence proves the three failing cohorts were detected and automatically rolled back within minutes, with no working device ever touched?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-fleets-12-o3-c1', 'mission-vec-fleets-12-o3', 1, 'multiple_choice', 'Byte''s registry count, run against the real fleet instead of a subset, finally reflects devices counted Nexus-wide rather than only facilities Vector Division has physically walked. What does that final number actually confirm?', '{"question":"Byte''s registry count, run against the real fleet instead of a subset, finally reflects devices counted Nexus-wide rather than only facilities Vector Division has physically walked. What does that final number actually confirm?","options":[{"id":"a","text":"The fleet is roughly the same size it was always assumed to be, in the low thousands"},{"id":"b","text":"The true fleet, counted honestly for the first time, reaches into the millions -- an order of magnitude the team had never actually measured before today"},{"id":"c","text":"The registry count is unreliable and should be ignored"},{"id":"d","text":"Nexus-wide counting double-counts every device and should be discounted"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-fleets-12-o4-c1', 'mission-vec-fleets-12-o4', 1, 'boss_encounter', 'Having confirmed the wave structure held, the rollback was automatic, and the true count, state what the rollout actually proved.', '{"stages":[{"objectiveRef":"mission-vec-fleets-12-o1","label":"Confirm the wave structure held"},{"objectiveRef":"mission-vec-fleets-12-o2","label":"Prove the automatic rollback"},{"objectiveRef":"mission-vec-fleets-12-o3","label":"Confirm the true fleet count"}],"task":"State the outcome in one sentence: the staged rollout succeeded not because nothing went wrong, but because the three failing cohorts were caught and rolled back automatically within minutes, containing the failure exactly as designed, while the registry finally proved the fleet Vector Division is responsible for is not thousands of devices -- it is millions."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-fleets-12-o1","mission-vec-fleets-12-o2","mission-vec-fleets-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-fleets-01-o1-c1', 'orientation', 'Ask whether the statement can be checked by walking up to one machine, or requires tracking many at once.', 10, 1),
  ('mission-vec-fleets-01-o1-c1', 'concept', 'A single robot''s state is checkable directly. A fleet''s state can only be known through a system built to track many devices continuously, without anyone walking up to each one.', 20, 2),
  ('mission-vec-fleets-01-o1-c1', 'solution', 'One robot: checking one controller by walking up to it, and flashing one board. Fleet: tracking whether millions are alive right now, and automatically containing a bad update to a small group.', 30, 3),
  ('mission-vec-fleets-01-o2-c1', 'orientation', 'Ask what happens to risk that exists but was never counted.', 10, 1),
  ('mission-vec-fleets-01-o2-c1', 'solution', 'The undercounted number hides real risk -- a fleet''s actual exposure cannot be managed if the registry only reflects what one team has personally visited.', 20, 2),

  ('mission-vec-fleets-02-o1-c1', 'orientation', 'A name written on a case does not survive a firmware reflash or a move to a new facility.', 10, 1),
  ('mission-vec-fleets-02-o1-c1', 'solution', 'A device identity is a unique identifier tied to the physical unit itself, surviving reboots, updates and reassignment -- otherwise two devices eventually look identical to the fleet.', 20, 2),
  ('mission-vec-fleets-02-o2-c1', 'orientation', 'Look for the record showing two devices sharing something that should have been unique.', 10, 1),
  ('mission-vec-fleets-02-o2-c1', 'solution', 'e1: two controllers were flashed with the same default serial number before a unique-identity step existed -- exactly the collision a deliberate identity scheme prevents.', 20, 2),

  ('mission-vec-fleets-03-o1-c1', 'orientation', 'Ask what one system would need to hold for a person to trust a single query over walking to every facility.', 10, 1),
  ('mission-vec-fleets-03-o1-c1', 'solution', 'The registry is the single source of truth -- identity, firmware version, location, and last check-in, queryable in one place.', 20, 2),
  ('mission-vec-fleets-03-o2-c1', 'orientation', 'Ask how an entry ever got created in the old registry in the first place.', 10, 1),
  ('mission-vec-fleets-03-o2-c1', 'solution', 'e1: entries only existed when a technician personally onboarded a device on site -- anything never physically visited was invisible to the registry.', 20, 2),

  ('mission-vec-fleets-04-o1-c1', 'orientation', 'Ask whether the job can change based on who is currently available, or is fixed forever.', 10, 1),
  ('mission-vec-fleets-04-o1-c1', 'solution', 'Static: fixed forever regardless of failure. Dynamic: reassigned live based on who is actually online and healthy.', 20, 2),
  ('mission-vec-fleets-04-o2-c1', 'orientation', 'Think about who notices a single device''s silence versus who notices one silent device among a million.', 10, 1),
  ('mission-vec-fleets-04-o2-c1', 'solution', 'At fleet scale a statically assigned device can fail silently, and whatever it owned simply stops happening until someone notices the gap -- which single-device thinking never had to account for.', 20, 2),

  ('mission-vec-fleets-05-o1-c1', 'orientation', 'A heartbeat says nothing about what the device is doing, only that it exists.', 10, 1),
  ('mission-vec-fleets-05-o1-c1', 'solution', 'A heartbeat is a small regular signal confirming a device is alive and functioning, independent of its actual task.', 20, 2),
  ('mission-vec-fleets-05-o2-c1', 'orientation', 'Ask what a single dropped signal could mean besides an actual failure.', 10, 1),
  ('mission-vec-fleets-05-o2-c1', 'solution', 'e1: a device is marked unhealthy only after three consecutive missed heartbeats -- one miss alone is treated as noise, not proof of failure.', 20, 2),

  ('mission-vec-fleets-06-o1-c1', 'orientation', 'Think about what makes this different from physically opening the device.', 10, 1),
  ('mission-vec-fleets-06-o1-c1', 'solution', 'Remote diagnostics queries a device''s live state -- firmware version, last error, resource usage -- from a distance, with nobody standing next to it.', 20, 2),
  ('mission-vec-fleets-06-o2-c1', 'orientation', 'Rule out the responses that either did not answer, answered incompletely, or answered with old data.', 10, 1),
  ('mission-vec-fleets-06-o2-c1', 'solution', 'r2: a full, current report with no errors and nominal resource usage is the only genuinely healthy, honest answer.', 20, 2),

  ('mission-vec-fleets-07-o1-c1', 'orientation', 'Think about what a person actually needs to answer whether the fleet is healthy, versus reading every device''s row.', 10, 1),
  ('mission-vec-fleets-07-o1-c1', 'solution', 'Telemetry at scale is aggregated by cohort, firmware version or facility, so overall health can be judged in seconds instead of a scroll through a million records.', 20, 2),
  ('mission-vec-fleets-07-o2-c1', 'orientation', 'Ask whether the statement is about one specific device or about a rolled-up group.', 10, 1),
  ('mission-vec-fleets-07-o2-c1', 'solution', 'Aggregate: the percentage-based and cohort-rate statements. Individual: the two statements naming one specific device.', 20, 2),

  ('mission-vec-fleets-08-o1-c1', 'orientation', 'Think about what must never happen to a device, no matter how many are updating at once.', 10, 1),
  ('mission-vec-fleets-08-o1-c1', 'solution', 'Verify the image first, and always keep a fallback the device can boot into -- so no device is ever left with no working firmware, at any scale.', 20, 2),
  ('mission-vec-fleets-08-o2-c1', 'orientation', 'Nothing can be flashed before it is verified, and nothing can be committed before it has proven itself booting.', 10, 1),
  ('mission-vec-fleets-08-o2-c1', 'solution', 'Download, then verify, then flash to a backup slot, then boot and self-test, then commit or roll back.', 20, 2),

  ('mission-vec-fleets-09-o1-c1', 'orientation', 'Think about what a canary group is actually for, before assuming it means a random small batch.', 10, 1),
  ('mission-vec-fleets-09-o1-c1', 'solution', 'A staged rollout releases to a small percentage first, watches its health, and only expands to larger waves if that canary group stays healthy.', 20, 2),
  ('mission-vec-fleets-09-o2-c1', 'orientation', 'Each wave has to prove itself before the next one is allowed to begin.', 10, 1),
  ('mission-vec-fleets-09-o2-c1', 'solution', 'Canary, then early, then broad, then full fleet -- each wave gated on the health of the one before it.', 20, 2),

  ('mission-vec-fleets-10-o1-c1', 'orientation', 'A map does not add new data -- it changes how existing data is seen.', 10, 1),
  ('mission-vec-fleets-10-o1-c1', 'solution', 'A fleet map lays out the same registry and telemetry data visually by facility, cohort or firmware, so clustering patterns become visible that a row-by-row list would hide.', 20, 2),
  ('mission-vec-fleets-10-o2-c1', 'orientation', 'Ask whether the three failures share something in common, or are scattered with nothing linking them.', 10, 1),
  ('mission-vec-fleets-10-o2-c1', 'solution', 'e1: all three unhealthy devices fall inside the same canary wave and firmware build -- a clustering pattern that only becomes obvious once plotted together.', 20, 2),

  ('mission-vec-fleets-11-o1-c1', 'orientation', 'Ask who takes the containment action -- a person watching a dashboard, or the system itself.', 10, 1),
  ('mission-vec-fleets-11-o1-c1', 'solution', 'Failure isolation automatically contains a detected failure to the smallest possible group, pausing and rolling back only the affected cohort before it reaches the next wave.', 20, 2),
  ('mission-vec-fleets-11-o2-c1', 'orientation', 'Look for a log showing the rollback happening with nobody logged in to trigger it.', 10, 1),
  ('mission-vec-fleets-11-o2-c1', 'solution', 'e1: the rollout system paused and reverted the three failing cohorts automatically, with no engineer logged in during the window -- containment happened without waiting on a person.', 20, 2),

  ('mission-vec-fleets-12-o1-c1', 'orientation', 'Ask whether the failure spread past the wave already underway, or stayed inside it.', 15, 1),
  ('mission-vec-fleets-12-o1-c1', 'solution', 'The failures never reached the un-released remainder of the fleet -- containment within the active wave is exactly what canary staging is built to guarantee, not luck.', 25, 2),
  ('mission-vec-fleets-12-o2-c1', 'orientation', 'Look for the single record that ties together detection speed and the absence of any manual trigger.', 15, 1),
  ('mission-vec-fleets-12-o2-c1', 'solution', 'The health telemetry timeline shows detection and full automatic rollback completing within four minutes of the first missed heartbeat, with zero manual intervention logged.', 25, 2),
  ('mission-vec-fleets-12-o3-c1', 'orientation', 'Compare what the team had always assumed against what counting Nexus-wide, honestly, actually produced.', 15, 1),
  ('mission-vec-fleets-12-o3-c1', 'solution', 'The true fleet, counted for the first time without restricting to facilities physically walked, reaches into the millions -- an order of magnitude beyond what anyone had actually measured before today.', 25, 2),
  ('mission-vec-fleets-12-o4-c1', 'orientation', 'Combine what held, what caught the failure, and what the real count turned out to be -- that is the whole outcome.', 15, 1),
  ('mission-vec-fleets-12-o4-c1', 'solution', 'The rollout succeeded not because nothing went wrong, but because three failing cohorts were caught and rolled back automatically within minutes, containing the failure exactly as designed, while the registry finally proved the fleet is not thousands of devices -- it is millions.', 25, 2);
