-- Backend Engineering ("The Fracture") Act 16 -- "Caching" content.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), opening the
-- back half of Arc III. Same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every world.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be16', 'world-be-16', 'caching', '16A - Caching', 'The transit dashboard now asks the database the same question thousands of times a second, and the database is starting to lose. Learn why identical reads deserve a different kind of memory before it runs out of patience.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be16-1', 'campaign-be16', 'cache-fundamentals', 'Cache Fundamentals', 'What caching actually buys you, where a cache can live, Redis itself, and the two read patterns -- cache-aside and read-through -- that get data into it in the first place.', 1),
  ('operation-be16-2', 'campaign-be16', 'caching-under-load', 'Caching Under Load', 'Keeping a cache honest once real traffic hits it: writes, expiration, invalidation, staleness, and the stampede that happens when everything expires at once.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be16-01', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'why-cache', 'Why Cache?', 'Thousands of clients ask the same question every few seconds, and the database answers every single one of them individually. Learn what actually justifies putting something faster in front of it.', 'intermediate', ARRAY['forge'], null, null, '{"type":"simulation","simulationId":"why-cache-sim"}'::jsonb, '{"xp":165,"credits":30}'::jsonb, false, 1),
  ('mission-be16-02', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'local-cache', 'Local Cache', 'The simplest cache lives right inside the process asking the question -- and that simplicity is exactly what breaks the moment there is more than one process.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be16-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"local-cache-sim"}'::jsonb, '{"xp":168,"credits":30}'::jsonb, false, 2),
  ('mission-be16-03', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'distributed-cache', 'Distributed Cache', 'Move the cache out of any single process and into a shared service every replica can reach, and the whole fleet finally agrees on one answer.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be16-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"distributed-cache-sim"}'::jsonb, '{"xp":172,"credits":31}'::jsonb, false, 3),
  ('mission-be16-04', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'redis-fundamentals', 'Redis Fundamentals', 'Redis is the shared, in-memory store Forge actually reaches for -- fast enough to answer in under a millisecond, simple enough to misuse just as fast.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be16-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"redis-fundamentals-sim"}'::jsonb, '{"xp":175,"credits":31}'::jsonb, false, 4),
  ('mission-be16-05', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'cache-aside', 'Cache-Aside', 'The most common caching pattern there is: check the cache, and only bother the database when the cache genuinely does not know.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be16-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"cache-aside-sim"}'::jsonb, '{"xp":178,"credits":32}'::jsonb, false, 5),
  ('mission-be16-06', 'world-be-16', 'campaign-be16', 'operation-be16-1', 'read-through', 'Read-Through', 'Same miss-then-fetch behavior as cache-aside, but the responsibility for reaching the database moves out of application code and into the cache itself.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be16-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"read-through-sim"}'::jsonb, '{"xp":182,"credits":32}'::jsonb, false, 6),
  ('mission-be16-07', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'write-through', 'Write-Through', 'Reads are not the only thing that touch a cache. A write has to decide too -- and write-through decides by updating both places before calling the job done.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be16-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"write-through-sim"}'::jsonb, '{"xp":200,"credits":38}'::jsonb, false, 7),
  ('mission-be16-08', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'ttl-and-eviction', 'TTL and Eviction', 'Nothing should be trusted forever, and nothing fits in memory forever either. TTLs and eviction policies are two different answers to two different limits.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be16-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"ttl-eviction-sim"}'::jsonb, '{"xp":205,"credits":39}'::jsonb, false, 8),
  ('mission-be16-09', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'cache-invalidation', 'Cache Invalidation', 'The moment you already know an answer changed, waiting for a TTL to catch up is a choice -- usually the wrong one.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be16-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"cache-invalidation-sim"}'::jsonb, '{"xp":210,"credits":40}'::jsonb, false, 9),
  ('mission-be16-10', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'stale-data', 'Stale Data', 'Even a cache with correct invalidation logic can serve a stale answer if a read and a write land in the wrong order by a matter of milliseconds.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be16-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"stale-data-sim"}'::jsonb, '{"xp":215,"credits":41}'::jsonb, false, 10),
  ('mission-be16-11', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'cache-stampede-and-hot-keys', 'Cache Stampede and Hot Keys', 'One overloaded key, or one key that expires and takes a wave of simultaneous requests down with it -- two different failure shapes with two different names.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be16-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"cache-stampede-sim"}'::jsonb, '{"xp":220,"credits":42}'::jsonb, false, 11),
  ('mission-be16-12', 'world-be-16', 'campaign-be16', 'operation-be16-2', 'the-stampede', 'The Stampede', 'A popular cache key goes cold on every replica at the same instant, and all of them ask the database the same question at once. Everything this Act taught, at once -- plus something stranger sitting right next to the fix.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be16-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-stampede-boss-sim"}'::jsonb, '{"xp":500,"credits":115,"badgeIds":["stampede"],"skillXp":{"caching":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be16-01', 1, 'forge', 'The realtime feed''s live now, and the transit dashboard calls the same endpoint every open screen is watching: next three arrivals, refreshed every few seconds. Same question, over and over, from thousands of screens at once.'),
  ('mission-be16-01', 2, 'forge', 'The database is answering every single one of those individually, like it''s never heard the question before. That''s not a bug. That''s just what happens right before somebody puts a cache in front of it.'),
  ('mission-be16-02', 1, 'mira', 'Simplest possible cache: keep the last answer in memory, right inside the process that''s already running it. A plain map, a local variable, whatever your language calls it.'),
  ('mission-be16-02', 2, 'mira', 'It''s fast, because there''s no network hop at all. But Forge Division doesn''t run one process -- it runs a fleet of identical replicas behind a load balancer, and that''s where this gets interesting.'),
  ('mission-be16-03', 1, 'forge', 'The fix for six replicas giving six different answers is to stop caching inside each one and put the cache somewhere all six can reach instead -- a separate service every replica talks to over the network.'),
  ('mission-be16-03', 2, 'forge', 'One shared cache, one shared answer. It costs a network hop instead of zero, but it buys back consistency across the whole fleet.'),
  ('mission-be16-04', 1, 'mira', 'Redis is what Forge actually runs for this: an in-memory key-value store, fast enough to answer in under a millisecond, with commands as simple as GET and SET.'),
  ('mission-be16-04', 2, 'mira', 'Every key can carry an expiration too -- set it once, at write time, and Redis forgets the key on its own instead of holding onto it forever.'),
  ('mission-be16-05', 1, 'forge', 'Cache-aside puts the application in charge: check the cache first. Hit, return it immediately. Miss, go to the database, get the real answer, write it into the cache yourself, then return it.'),
  ('mission-be16-05', 2, 'forge', 'It is called cache-aside because the cache sits beside the database, not in front of it -- your own code decides when to read from which.'),
  ('mission-be16-06', 1, 'mira', 'Read-through looks similar from the outside -- same check-then-fetch behavior -- but the responsibility moves. The cache layer itself knows how to reach the database on a miss.'),
  ('mission-be16-06', 2, 'mira', 'Your application code just asks the cache for a value and never touches the database directly. That''s the entire difference: who owns the job of repopulating on a miss.'),
  ('mission-be16-07', 1, 'forge', 'Cache-aside and read-through are both about reads. Write-through is about writes: every write goes to the cache and the database together, before the write even counts as done.'),
  ('mission-be16-07', 2, 'forge', 'The payoff is the cache is never stale right after a write -- there''s no window where the database already has the new value and the cache is still handing out the old one.'),
  ('mission-be16-08', 1, 'mira', 'Every cached value should eventually stop being trusted. A TTL -- time to live -- is how you put an expiration date on an answer instead of promising it''s good forever.'),
  ('mission-be16-08', 2, 'mira', 'But Redis doesn''t have unlimited memory either. Once it fills up, an eviction policy decides what gets thrown out early to make room -- and which policy you pick changes what actually survives.'),
  ('mission-be16-09', 1, 'forge', 'TTL handles the case where a stale answer is fine for a little while. Invalidation is different -- it''s what you do the instant you already know an answer changed, instead of waiting for the clock to catch up.'),
  ('mission-be16-09', 2, 'forge', 'A route''s schedule gets updated, and if nothing tells the cache that happened, the cache keeps confidently handing out the old schedule until its TTL finally gets around to expiring.'),
  ('mission-be16-10', 1, 'mira', 'Even with invalidation wired up correctly, there''s a narrower race hiding underneath cache-aside: a write can finish updating the database while a read that started just before it is still on its way to repopulating the cache with the old value.'),
  ('mission-be16-10', 2, 'mira', 'Get the ordering wrong and the write wins in the database while the read wins in the cache -- and the cache is what everyone actually reads from.'),
  ('mission-be16-11', 1, 'forge', 'Two related failure modes worth naming separately. A hot key is one single key so popular it overwhelms the shard handling it, all on its own, even while the rest of the cache is fine.'),
  ('mission-be16-11', 2, 'forge', 'A cache stampede is what happens when a popular key expires and a wave of concurrent requests all miss at the exact same moment -- every one of them turns around and hits the database at once, for the same answer.'),
  ('mission-be16-12', 1, 'mira', 'For about six seconds this afternoon, every replica missed on the exact same key at the exact same moment, and all six of them went straight to the database at once. Same key, same instant, every single copy.'),
  ('mission-be16-12', 2, 'forge', 'Not a gradual falloff. Not one replica warming up while the others still had it cached. All six, simultaneous. Database connections spiked from twelve to a hundred and eighteen in under four milliseconds.'),
  ('mission-be16-12', 3, 'mira', 'Find out why. Everything this Act taught, at once.'),
  ('mission-be16-12', 4, 'forge', '...found it. Every replica set this key''s TTL using the exact same deploy timestamp as the seed -- no randomness added anywhere. Deploy finished, the TTL clock started, and five minutes later all six clocks hit zero within the same millisecond.'),
  ('mission-be16-12', 5, 'mira', 'So they were never really independent. They were always going to expire together -- the deploy just decided exactly when.'),
  ('mission-be16-12', 6, 'forge', '...one more thing. The actual key sitting in Redis isn''t arrivals:route-42. It''s //arrivals:route-42 -- prefixed with a doubled slash nobody remembers adding, and grepping the codebase doesn''t turn up who did.'),
  ('mission-be16-12', 7, 'mira', 'Noted. File it. Jitter and a lock fix today''s incident. That symbol doesn''t go away just because we fixed the thing sitting next to it.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be16-01-o1', 'mission-be16-01', 1, 'Justify the cache', 'Decide whether the next-three-arrivals endpoint is actually a good candidate for caching.'),
  ('mission-be16-02-o1', 'mission-be16-02', 1, 'Spot the limitation', 'Explain what breaks when an in-process cache meets more than one replica.'),
  ('mission-be16-03-o1', 'mission-be16-03', 1, 'Match the tradeoff', 'Sort each property into local cache or distributed cache.'),
  ('mission-be16-04-o1', 'mission-be16-04', 1, 'Read the Redis call', 'Find the line responsible for a cached key that never expires.'),
  ('mission-be16-05-o1', 'mission-be16-05', 1, 'Order the read path', 'Put the steps of a cache-aside read, on a miss, in the order they actually happen.'),
  ('mission-be16-06-o1', 'mission-be16-06', 1, 'Tell the patterns apart', 'Decide who is actually responsible for repopulating the cache on a miss.'),
  ('mission-be16-07-o1', 'mission-be16-07', 1, 'Find the write-through gap', 'Find the line that updates the database without keeping the cache in sync.'),
  ('mission-be16-08-o1', 'mission-be16-08', 1, 'Match the eviction policy', 'Match each eviction policy to what it actually evicts first.'),
  ('mission-be16-09-o1', 'mission-be16-09', 1, 'Find the missing invalidation', 'Find the evidence that explains why a stale answer kept being served after an update.'),
  ('mission-be16-10-o1', 'mission-be16-10', 1, 'Diagnose the race', 'Work out what the cache actually ends up holding when a read and a write overlap.'),
  ('mission-be16-11-o1', 'mission-be16-11', 1, 'Choose the mitigation', 'Choose the change that actually stops concurrent misses from all hitting the database at once.'),
  ('mission-be16-12-o1', 'mission-be16-12', 1, 'Diagnose the stampede', 'Identify the evidence that this was a synchronized, mass expiration event, not organic load growth.'),
  ('mission-be16-12-o2', 'mission-be16-12', 2, 'Confirm the shared TTL seed', 'Confirm what actually caused every replica to expire the same key at the same instant.'),
  ('mission-be16-12-o3', 'mission-be16-12', 3, 'Choose the fix', 'Pick the fix that actually addresses expiration happening in lockstep across every replica.'),
  ('mission-be16-12-o4', 'mission-be16-12', 4, 'Close the incident', 'Close the incident, and file the cache-key anomaly as a separate, unresolved thread.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be16-01-o1-c1', 'mission-be16-01-o1', 1, 'multiple_choice', 'The /routes/42/next-arrivals endpoint answers thousands of clients every few seconds. What actually makes it a strong caching candidate?', '{"question":"The /routes/42/next-arrivals endpoint is queried by thousands of clients every few seconds, and returns nearly the same answer to almost all of them within any given window. What actually makes this a strong caching candidate?","options":[{"id":"a","text":"It is reached with a GET request"},{"id":"b","text":"The same computed result answers a huge number of near-simultaneous requests, and it is fine for that answer to be a few seconds old"},{"id":"c","text":"It happens to query a database at all"},{"id":"d","text":"The endpoint does not require authentication"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be16-02-o1-c1', 'mission-be16-02-o1', 1, 'multiple_choice', 'Each of 6 replicas keeps its own in-memory cache. One replica''s entry is cleared, the other five are not. What happens?', '{"question":"The dispatch API runs on 6 replicas behind a load balancer. Each replica keeps its own in-memory cache of next-arrivals results. A route''s schedule changes and one replica''s cache entry is cleared -- the other five are not. What actually happens next?","options":[{"id":"a","text":"Different clients get different answers to the identical question, purely depending on which replica the load balancer happened to route them to"},{"id":"b","text":"Nothing -- in-memory caches automatically stay in sync across replicas"},{"id":"c","text":"The load balancer detects the mismatch and blocks the stale replicas automatically"},{"id":"d","text":"All 6 replicas share the same process memory by default"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-be16-03-o1-c1', 'mission-be16-03-o1', 1, 'drag_and_drop', 'Sort each property into local cache or distributed cache.', '{"items":[{"id":"p1","text":"Zero network hop, the fastest possible read"},{"id":"p2","text":"Gives the same answer no matter which replica handles the request"},{"id":"p3","text":"Lost entirely the moment that one process restarts"},{"id":"p4","text":"Survives an individual app replica restarting or redeploying"},{"id":"p5","text":"Memory usage duplicated separately across every replica"}],"targets":[{"id":"t1","label":"Local (in-process) cache"},{"id":"t2","label":"Distributed (shared) cache"}]}'::jsonb, '{"correctMapping":{"p1":"t1","p2":"t2","p3":"t1","p4":"t2","p5":"t1"}}'::jsonb),

  ('mission-be16-04-o1-c1', 'mission-be16-04-o1', 1, 'code_debugging', 'This function caches arrivals data in Redis, but the cached value never expires on its own. Which line is responsible?', '{"language":"typescript","code":"async function cacheArrivals(routeId, data) {\n  const key = \"arrivals:\" + routeId;\n  await redis.set(key, JSON.stringify(data));\n  return data;\n}","question":"This function caches arrivals data in Redis but the cached value never expires on its own. Which line is responsible for that missing expiration?"}'::jsonb, '{"requiredLineIds":["  await redis.set(key, JSON.stringify(data));"]}'::jsonb),

  ('mission-be16-05-o1-c1', 'mission-be16-05-o1', 1, 'interactive_diagram', 'Put the steps of a cache-aside read, on a miss, in the order they actually happen.', '{"diagramId":"cache-aside-read-path","hotspots":[{"id":"check_cache","label":"Check the cache","explanation":"The application asks the cache first, before touching the database at all."},{"id":"cache_miss","label":"Cache reports a miss","explanation":"The cache has no value stored for this key."},{"id":"query_db","label":"Query the database","explanation":"Only now does the application go to the database for the real answer."},{"id":"populate_cache","label":"Write the result into the cache","explanation":"The application writes the database''s answer into the cache itself, so the next request can hit."},{"id":"return_result","label":"Return the result","explanation":"The application finally returns the answer to the original caller."}],"task":"Put the steps of a cache-aside read, on a miss, in the order they actually happen."}'::jsonb, '{"correctOrderIds":["check_cache","cache_miss","query_db","populate_cache","return_result"]}'::jsonb),

  ('mission-be16-06-o1-c1', 'mission-be16-06-o1', 1, 'multiple_choice', 'In cache-aside, application code populates the cache on a miss. In read-through, who does that?', '{"question":"In cache-aside, the application code checks the cache and, on a miss, queries the database itself and writes the result back into the cache. In read-through, who actually does that on-miss database query and cache population?","options":[{"id":"a","text":"The application code, exactly the same as cache-aside"},{"id":"b","text":"The caching layer itself, transparently -- the application only ever asks the cache for a value and never queries the database directly"},{"id":"c","text":"Neither -- read-through never reaches the database at all"},{"id":"d","text":"The database pushes updates into the cache on its own schedule"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be16-07-o1-c1', 'mission-be16-07-o1', 1, 'code_debugging', 'This function is supposed to implement write-through. Which line shows the gap where it updates the database but leaves the cache untouched?', '{"language":"typescript","code":"async function updateArrivalOverride(routeId, override) {\n  await db.query(\"UPDATE route_overrides SET eta = $1 WHERE route_id = $2\", [override.eta, routeId]);\n  return override;\n}","question":"This function is supposed to implement write-through for route overrides, so the cache is never stale right after a write. Which line shows the gap -- where it updates the database but does nothing to the cache?"}'::jsonb, '{"requiredLineIds":["  await db.query(\"UPDATE route_overrides SET eta = $1 WHERE route_id = $2\", [override.eta, routeId]);"]}'::jsonb),

  ('mission-be16-08-o1-c1', 'mission-be16-08-o1', 1, 'drag_and_drop', 'Match each eviction policy to what it actually evicts first.', '{"items":[{"id":"e1","text":"LRU"},{"id":"e2","text":"LFU"},{"id":"e3","text":"Random"},{"id":"e4","text":"noeviction"}],"targets":[{"id":"t1","label":"Evicts whichever key hasn''t been read in the longest time"},{"id":"t2","label":"Evicts whichever key has been read the fewest total times"},{"id":"t3","label":"Evicts a key at random, regardless of recency or frequency"},{"id":"t4","label":"Refuses new writes once memory is full instead of evicting anything"}]}'::jsonb, '{"correctMapping":{"e1":"t1","e2":"t2","e3":"t3","e4":"t4"}}'::jsonb),

  ('mission-be16-09-o1-c1', 'mission-be16-09-o1', 1, 'investigation', 'Which piece of evidence is the actual root cause of riders seeing the old arrival time for over a minute after the real update?', '{"evidence":[{"id":"ev1","label":"Update log","detail":"route_overrides row for route-42 updated at 14:02:11 with a new eta."},{"id":"ev2","label":"Cache TTL","detail":"arrivals:route-42 was cached at 13:58:40 with a 300-second TTL, expiring at 14:03:40."},{"id":"ev3","label":"Invalidation log","detail":"No DEL or explicit expire call for arrivals:route-42 appears anywhere between 14:02:11 and 14:03:40."}],"question":"Which piece of evidence is the actual root cause of riders seeing the old arrival time for over a minute after the real update?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be16-10-o1-c1', 'mission-be16-10-o1', 1, 'multiple_choice', 'Request A reads (miss) before Request B updates and deletes the key, then A finally writes its outdated result into the cache. What does the cache hold afterward?', '{"question":"Request A reads arrivals:route-42 (cache miss) and begins querying the database for the old value. Before A finishes, Request B updates the database with a new eta and deletes the cache key. Then A finally writes its (now outdated) result into the cache. What is the actual state of the cache after this?","options":[{"id":"a","text":"The cache correctly holds the new value, since B deleted the key"},{"id":"b","text":"The cache holds A''s stale value, because A wrote it after B''s deletion completed, even though A read it before B''s update happened"},{"id":"c","text":"The cache is empty and stays empty"},{"id":"d","text":"The database and cache are guaranteed to always match after any single write"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be16-11-o1-c1', 'mission-be16-11-o1', 1, 'multiple_choice', 'A single popular key is about to expire under heavy concurrent read traffic. Which change most directly prevents every concurrent miss from hitting the database at once?', '{"question":"A single popular key is about to expire under heavy concurrent read traffic. Which change most directly prevents every one of those concurrent misses from hitting the database at once?","options":[{"id":"a","text":"Increase the number of Redis replicas"},{"id":"b","text":"Let only the first request that misses actually query the database and repopulate the cache, while the rest wait briefly for that result instead of each querying independently"},{"id":"c","text":"Increase the TTL to a very large number so it rarely expires"},{"id":"d","text":"Remove the key from the cache entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be16-12-o1-c1', 'mission-be16-12-o1', 1, 'code_debugging', 'Six replicas logged a cache miss for the same key within the same millisecond. Which line is the direct downstream consequence?', '{"language":"log","code":"14:32:07.001 cache MISS key=arrivals:route-42 replica=api-1\n14:32:07.001 cache MISS key=arrivals:route-42 replica=api-2\n14:32:07.001 cache MISS key=arrivals:route-42 replica=api-3\n14:32:07.001 cache MISS key=arrivals:route-42 replica=api-4\n14:32:07.001 cache MISS key=arrivals:route-42 replica=api-5\n14:32:07.001 cache MISS key=arrivals:route-42 replica=api-6\n14:32:07.004 db connections_active=118 (baseline=12)","question":"Six replicas logged a cache miss for the exact same key within the same millisecond. Which line is the direct downstream consequence of that -- the database actually absorbing all six lookups at once?"}'::jsonb, '{"requiredLineIds":["14:32:07.004 db connections_active=118 (baseline=12)"]}'::jsonb),

  ('mission-be16-12-o2-c1', 'mission-be16-12-o2', 1, 'investigation', 'Which evidence explains why every replica''s copy of this key expired at the same instant, instead of gradually over time?', '{"evidence":[{"id":"ev1","label":"Redis TTL config","detail":"Every replica calls SET on this key with a fixed 300-second expiration, seeded from the deploy timestamp -- no randomness added."},{"id":"ev2","label":"Deploy log","detail":"All 6 replicas finished their rolling deploy within the same 4-second window."},{"id":"ev3","label":"Cache hit-rate graph","detail":"Hit rate for arrivals:route-42 stayed above 99 percent for the five minutes before the incident."}],"question":"Which evidence actually explains why every replica''s copy of this key expired at the same instant, instead of gradually over time?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be16-12-o3-c1', 'mission-be16-12-o3', 1, 'multiple_choice', 'Every replica''s TTL for this key is deploy-time seeded and expires in lockstep. What actually fixes the stampede?', '{"question":"Given that every replica''s TTL for this key is deploy-time seeded and expires in lockstep, what actually fixes the stampede?","options":[{"id":"a","text":"Increase the Redis instance''s available memory"},{"id":"b","text":"Add random jitter to each key''s TTL, and use a lock so only one request repopulates the cache on a miss while the rest wait for that result"},{"id":"c","text":"Shorten the TTL from 300 seconds to 30 seconds"},{"id":"d","text":"Remove caching for this key entirely and query the database directly every time"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be16-12-o4-c1', 'mission-be16-12-o4', 1, 'boss_encounter', 'Close the incident: state what caused every replica to expire this key at once, and how the fix addresses it.', '{"stages":[{"objectiveRef":"mission-be16-12-o1","label":"Diagnose the stampede"},{"objectiveRef":"mission-be16-12-o2","label":"Confirm the shared TTL seed"},{"objectiveRef":"mission-be16-12-o3","label":"Choose the fix"}],"task":"Close the incident: a shared, unjittered deploy-time TTL made every replica expire this key at the same instant, and all six requests hit the database together the moment it happened. Jittered TTLs plus a single-flight lock fix it. File the doubled-slash key prefix as a separate, unresolved anomaly -- it is not explained by today''s fix."}'::jsonb, '{"requiredObjectiveIds":["mission-be16-12-o1","mission-be16-12-o2","mission-be16-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be16-01-o1-c1', 'orientation', 'Not every database-backed endpoint is worth caching -- ask what specifically is being repeated here.', 10, 1),
  ('mission-be16-01-o1-c1', 'concept', 'A cache trades a small amount of staleness for a huge reduction in duplicate work -- that trade only pays off when the answer is shared and briefly reusable.', 20, 2),
  ('mission-be16-01-o1-c1', 'solution', 'It is the combination of many requests wanting the identical answer, plus tolerance for that answer being a few seconds old, that makes caching pay off here.', 30, 3),

  ('mission-be16-02-o1-c1', 'orientation', 'A load balancer routes each request to one specific replica -- nothing forces that replica''s memory to match any other replica''s.', 10, 1),
  ('mission-be16-02-o1-c1', 'solution', 'Which replica happens to answer becomes the deciding factor -- the same request can get a fresh or stale answer purely based on load-balancer routing, not on anything about the request itself.', 20, 2),

  ('mission-be16-03-o1-c1', 'orientation', 'Ask which of these properties depend on being inside one specific process, and which depend on being reachable from all of them.', 10, 1),
  ('mission-be16-03-o1-c1', 'solution', 'p1, p3 and p5 all describe being trapped inside one process''s own memory -- that''s the local cache. p2 and p4 both describe surviving or staying consistent beyond any single process -- that''s the distributed cache.', 20, 2),

  ('mission-be16-04-o1-c1', 'orientation', 'Two lines here touch Redis at all -- only one of them is where an expiration would actually need to be set.', 10, 1),
  ('mission-be16-04-o1-c1', 'concept', 'A plain SET call with no expiration option makes a key live forever, until something else explicitly deletes it.', 20, 2),
  ('mission-be16-04-o1-c1', 'solution', 'redis.set(key, JSON.stringify(data)) never passes an expiration -- it needs an option like EX so Redis forgets the key on its own.', 30, 3),

  ('mission-be16-05-o1-c1', 'orientation', 'Nothing gets written into the cache until the application already has a real answer in hand.', 10, 1),
  ('mission-be16-05-o1-c1', 'solution', 'Check the cache, miss, query the database, write the result into the cache, then return it to the caller.', 20, 2),

  ('mission-be16-06-o1-c1', 'orientation', 'Both patterns behave the same from the outside on a miss -- the difference is which piece of code owns the database call.', 10, 1),
  ('mission-be16-06-o1-c1', 'solution', 'In read-through, the cache itself is the thing that knows how to reach the database -- the application never queries the database directly.', 20, 2),

  ('mission-be16-07-o1-c1', 'orientation', 'Write-through needs two things to happen together on every write -- count how many of them this function actually does.', 10, 1),
  ('mission-be16-07-o1-c1', 'concept', 'A function that only updates the database has implemented write-behind by accident: the database changes, but the cache has no idea yet.', 20, 2),
  ('mission-be16-07-o1-c1', 'solution', 'The db.query call updates the database and nothing else -- write-through requires a matching cache write, or invalidation, right alongside it, which this function never does.', 30, 3),

  ('mission-be16-08-o1-c1', 'orientation', 'One of these four does not evict anything at all -- read its name literally.', 10, 1),
  ('mission-be16-08-o1-c1', 'solution', 'LRU evicts by recency, LFU evicts by frequency, Random evicts without regard to either, and noeviction refuses new writes instead of evicting.', 20, 2),

  ('mission-be16-09-o1-c1', 'orientation', 'An update log and a TTL both describe timing -- neither one, by itself, explains why the cache kept the old value.', 10, 1),
  ('mission-be16-09-o1-c1', 'concept', 'If a write changes the source of truth and nothing separately tells the cache to forget its old value, the cache has no way to know anything changed.', 20, 2),
  ('mission-be16-09-o1-c1', 'solution', 'The invalidation log shows no DEL or expire call was ever issued for this key after the update -- that absence is the actual cause, not the TTL length or the update timing.', 30, 3),

  ('mission-be16-10-o1-c1', 'orientation', 'Track what each request actually writes, and when, not just what each one read.', 10, 1),
  ('mission-be16-10-o1-c1', 'solution', 'Request A read the old value before B''s update, but writes that old value into the cache after B already deleted the key -- so A''s late, stale write is the last thing to happen, and it is what the cache ends up holding.', 20, 2),

  ('mission-be16-11-o1-c1', 'orientation', 'The problem isn''t that the key expired -- it''s that every concurrent request reacted to the miss independently.', 10, 1),
  ('mission-be16-11-o1-c1', 'solution', 'Letting only one request repopulate the cache while the rest wait for that result (a single-flight lock) is what actually stops every concurrent miss from hitting the database at once.', 20, 2),

  ('mission-be16-12-o1-c1', 'orientation', 'Six identical misses at the same timestamp is the trigger -- look for the line that shows what happened right after, to the database itself.', 10, 1),
  ('mission-be16-12-o1-c1', 'solution', 'Connections jumping from a baseline of 12 to 118 in three milliseconds is the database taking all six simultaneous lookups at once.', 20, 2),
  ('mission-be16-12-o2-c1', 'orientation', 'A near-simultaneous deploy alone wouldn''t synchronize anything unless something else ties expiration to that same moment.', 10, 1),
  ('mission-be16-12-o2-c1', 'concept', 'A TTL seeded from a shared deploy timestamp, with no jitter, makes every replica''s clock start -- and therefore end -- at nearly the same instant.', 20, 2),
  ('mission-be16-12-o2-c1', 'solution', 'The TTL config is the actual cause: every replica seeds this key''s 300-second expiration from the same deploy timestamp with no added randomness, so they all reach zero together.', 30, 3),
  ('mission-be16-12-o3-c1', 'orientation', 'The fix needs to break two things at once: the shared expiration moment, and every request reacting to a miss independently.', 10, 1),
  ('mission-be16-12-o3-c1', 'solution', 'Jitter spreads out when each replica''s copy actually expires, and a single-flight lock means only one request repopulates the cache on a miss instead of all of them hitting the database together.', 20, 2),
  ('mission-be16-12-o4-c1', 'orientation', 'Separate what you fixed today from what you merely noticed sitting next to it.', 15, 1),
  ('mission-be16-12-o4-c1', 'solution', 'The stampede was caused by a shared, unjittered deploy-time TTL causing synchronized expiration across every replica; jitter plus a single-flight lock fixes it. The //-prefixed key is filed separately, still unexplained.', 25, 2);
