-- AI/ML pathway ("Cipher Division") Act 11 -- "Unsupervised Territory" content.
-- Still Arc II ("Machines That Predict", Acts 7-12 -- Arc II closes at Act
-- 12, not here). Echo's interaction log is far bigger than anything Cipher
-- Division has ever labeled; clustering, dimensionality reduction and
-- anomaly detection are used to find out what is actually sitting in the
-- unlabeled remainder. 1 campaign, 2 operations, 12 missions (11 lessons +
-- boss), following the same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every other
-- pathway. The world/act rows already exist
-- (world-ai-unsupervised-territory, act-ai-2).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-unsupervised-territory', 'world-ai-unsupervised-territory', 'unsupervised-territory', '11A - Unsupervised Territory', 'Clustering, dimensionality reduction and anomaly detection: finding structure in data nobody has ever labeled, and learning to tell a genuine pattern in Echo''s interaction log from one that only looks like a pattern by chance.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-unsupervised-territory-1', 'campaign-ai-unsupervised-territory', 'structure-without-labels', 'Structure Without Labels', 'What unsupervised learning actually does, and the clustering methods that find groups with nobody handing the algorithm a label.', 1),
  ('operation-ai-unsupervised-territory-2', 'campaign-ai-unsupervised-territory', 'trusting-the-pattern', 'Trusting the Pattern', 'Cut the log down to something visible, hunt for outliers, and learn to prove a cluster is real before Cipher Division acts on it.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-unsupervised-territory-01', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'unsupervised-learning', 'Unsupervised Learning', 'The tournament-winning model only works on interactions Cipher Division already knows how to label. Buried in the rest of Echo''s log is activity nobody has ever categorized at all.', 'beginner', ARRAY['maya','byte'], null, null, '{"type":"simulation","simulationId":"unsupervised-learning-sim"}'::jsonb, '{"xp":220,"credits":50}'::jsonb, false, 1),
  ('mission-ai-unsupervised-territory-02', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'clustering', 'Clustering', 'No labels, no correct answer to train toward -- just examples, grouped so the ones alike sit together and the ones unlike sit apart.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"clustering-sim"}'::jsonb, '{"xp":230,"credits":50}'::jsonb, false, 2),
  ('mission-ai-unsupervised-territory-03', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'k-means', 'k-Means', 'Pick k centers, assign every point to its nearest one, recompute the centers, repeat -- k-Means finds groups by never stopping to ask what they mean.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"k-means-sim"}'::jsonb, '{"xp":230,"credits":55}'::jsonb, false, 3),
  ('mission-ai-unsupervised-territory-04', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'choosing-k', 'Choosing k', 'k-Means never tells you the right number of groups. Guess wrong and either real structure gets fused together, or one real cluster gets torn apart.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"choosing-k-sim"}'::jsonb, '{"xp":240,"credits":55}'::jsonb, false, 4),
  ('mission-ai-unsupervised-territory-05', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'dbscan', 'DBSCAN', 'DBSCAN does not ask for k at all -- it grows clusters wherever points are packed densely enough, and calls everything else noise.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"dbscan-sim"}'::jsonb, '{"xp":240,"credits":55}'::jsonb, false, 5),
  ('mission-ai-unsupervised-territory-06', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-1', 'hierarchical-clustering', 'Hierarchical Clustering', 'Hierarchical clustering never commits to one number of groups. It builds the whole family tree of mergers and lets a team cut it wherever they need.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"hierarchical-clustering-sim"}'::jsonb, '{"xp":250,"credits":60}'::jsonb, false, 6),
  ('mission-ai-unsupervised-territory-07', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'dimensionality', 'Dimensionality', 'Echo''s log has more columns than any dataset Cipher Division has clustered so far -- and past a point, more columns make every point look equally far from every other point.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"dimensionality-sim"}'::jsonb, '{"xp":250,"credits":60}'::jsonb, false, 7),
  ('mission-ai-unsupervised-territory-08', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'pca', 'PCA', 'PCA does not throw features away. It finds the handful of directions that carry almost all the real variation, and lets everything else go quietly.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"pca-sim"}'::jsonb, '{"xp":260,"credits":60}'::jsonb, false, 8),
  ('mission-ai-unsupervised-territory-09', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'visualization', 'Visualization', 'A cluster that only exists in a table of numbers is easy to doubt. A cluster that can actually be seen on a plot is a lot harder to wave away -- and just as easy to over-trust.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"visualization-sim"}'::jsonb, '{"xp":260,"credits":65}'::jsonb, false, 9),
  ('mission-ai-unsupervised-territory-10', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'anomaly-detection', 'Anomaly Detection', 'Not every unusual point belongs to a cluster. Some of them belong to nothing at all -- and that is exactly what makes them worth a second look.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"anomaly-detection-sim"}'::jsonb, '{"xp":270,"credits":65}'::jsonb, false, 10),
  ('mission-ai-unsupervised-territory-11', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'cluster-evaluation', 'Cluster Evaluation', 'A cluster on a plot proves nothing by itself. Cipher Division needs a way to tell a real cluster from one that only exists because of a bad k or an unscaled feature.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"cluster-evaluation-sim"}'::jsonb, '{"xp":270,"credits":65}'::jsonb, false, 11),
  ('mission-ai-unsupervised-territory-12', 'world-ai-unsupervised-territory', 'campaign-ai-unsupervised-territory', 'operation-ai-unsupervised-territory-2', 'find-the-unknown-population', 'Find the Unknown Population', 'A small, distinct population is sitting inside Echo''s unlabeled log. Prove it is real, prove it is not an artifact, and prove it does not match anything Cipher Division has ever named.', 'boss', ARRAY['maya','byte'], '{"requiredMissionIds":["mission-ai-unsupervised-territory-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"unknown-population-boss-sim"}'::jsonb, '{"xp":680,"credits":150,"badgeIds":["find-the-unknown-population"],"skillXp":{"unsupervised_learning":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-unsupervised-territory-01', 1, 'maya', 'The representation-learning tangent can wait. Right now Cipher Division has a nearer problem: the tournament produced a production-ready classifier, and it is useless on most of Echo''s log.'),
  ('mission-ai-unsupervised-territory-01', 2, 'byte', 'Every model built this Arc, k-NN through the winning forest, only works on interactions someone already labeled emergency or routine. That labeled slice is a small fraction of the full log.'),
  ('mission-ai-unsupervised-territory-01', 3, 'maya', 'Millions of rows past that fraction have never been looked at by a human or a model. I want to know what is actually in there before anyone decides it does not matter.'),
  ('mission-ai-unsupervised-territory-01', 4, 'byte', 'Which means switching approaches entirely. No labels this time -- which means no correct answer to train against. Lesson one: what unsupervised learning actually is, and what it can and cannot promise you without one.'),

  ('mission-ai-unsupervised-territory-02', 1, 'byte', 'Clustering is the core unsupervised task on the table: group the data so that items inside a group are more similar to each other than to items in any other group -- with nobody telling the algorithm what the groups should be called.'),
  ('mission-ai-unsupervised-territory-02', 2, 'byte', 'It does not predict a label, because there is not one to predict. It proposes structure. Naming what that structure actually means is still on us.'),

  ('mission-ai-unsupervised-territory-03', 1, 'byte', 'k-Means is the simplest way to actually do this. Choose a number of clusters, k. Drop k centers into the data. Assign every point to whichever center is nearest.'),
  ('mission-ai-unsupervised-territory-03', 2, 'byte', 'Then move each center to the average position of the points now assigned to it, and repeat -- assign, recompute, assign, recompute -- until the centers stop moving.'),
  ('mission-ai-unsupervised-territory-03', 3, 'byte', 'It is fast, and it is blind. It will confidently produce k groups even if the real number is completely different, or if there is no real group structure at all.'),

  ('mission-ai-unsupervised-territory-04', 1, 'byte', 'k-Means never tells you k is wrong. Pick k too low and it fuses two real clusters into one. Pick it too high and it slices one real cluster into fragments.'),
  ('mission-ai-unsupervised-territory-04', 2, 'byte', 'The elbow method helps: plot how much error shrinks as k grows. Real structure produces a sharp bend where adding more clusters stops helping much. Past that bend, more k is mostly just chopping noise into smaller pieces.'),

  ('mission-ai-unsupervised-territory-05', 1, 'byte', 'DBSCAN skips the k question entirely. It grows a cluster outward from any point that has enough neighbors packed close by, keeps adding neighbors of neighbors, and stops when the density runs out.'),
  ('mission-ai-unsupervised-territory-05', 2, 'byte', 'Points that never end up dense enough to join any cluster get labeled noise instead of forced into the nearest group. That single feature is why DBSCAN handles outliers that k-Means cannot.'),

  ('mission-ai-unsupervised-territory-06', 1, 'byte', 'Hierarchical clustering commits to nothing upfront. Start with every point as its own cluster, then repeatedly merge the two closest clusters, one merge at a time, until everything is one giant cluster.'),
  ('mission-ai-unsupervised-territory-06', 2, 'byte', 'Draw that merge history and you get a dendrogram -- a full tree of the data''s structure. Cut it at any height and you get however many clusters that height implies, chosen after seeing the whole picture instead of guessing k in advance.'),

  ('mission-ai-unsupervised-territory-07', 1, 'byte', 'Echo''s log carries far more columns than anything Cipher Division has clustered before -- dozens of measured fields per interaction, not the handful the tournament models used.'),
  ('mission-ai-unsupervised-territory-07', 2, 'byte', 'Past a certain number of dimensions, distance stops meaning much. The nearest point and the farthest point start looking almost equally far away, and every distance-based method -- k-Means, DBSCAN, all of it -- gets less reliable.'),

  ('mission-ai-unsupervised-territory-08', 1, 'byte', 'Principal Component Analysis is the standard fix. It does not pick a subset of the original columns and discard the rest -- it finds new directions, combinations of the original features, that capture the most variation in the data.'),
  ('mission-ai-unsupervised-territory-08', 2, 'byte', 'Keep the first few of those directions and you often keep almost all the real structure, in a fraction of the dimensions -- exactly what distance-based clustering needs to work well again.'),

  ('mission-ai-unsupervised-territory-09', 1, 'byte', 'Reduce Echo''s log to two or three of those principal directions and, for the first time, the unlabeled data can actually be looked at -- plotted, not just summarized in a table of numbers.'),
  ('mission-ai-unsupervised-territory-09', 2, 'byte', 'A visible, separated cluster on that plot is not proof of anything by itself. It is a reason to look closer, and just as easily a reason to fool yourself if the eye sees a pattern the data does not actually support.'),

  ('mission-ai-unsupervised-territory-10', 1, 'byte', 'Clustering asks which group a point belongs to. Anomaly detection asks a different question: does this point belong to any group at all, or does it sit far from every dense region in the data?'),
  ('mission-ai-unsupervised-territory-10', 2, 'byte', 'A point can be rare without being anomalous -- a real, if uncommon, kind of normal. The evidence has to show the point does not fit any known pattern, not just that it does not show up often.'),

  ('mission-ai-unsupervised-territory-11', 1, 'byte', 'Before anyone treats a cluster as real, it has to survive scrutiny. The silhouette score measures how much closer a point sits to its own cluster than to the next nearest one -- close to one is well-separated, close to zero or negative means the boundary is not real.'),
  ('mission-ai-unsupervised-territory-11', 2, 'byte', 'Two more checks matter just as much: does the cluster survive a different, reasonable choice of k, and does it survive with the features properly scaled? A cluster that vanishes under either test was never a cluster -- it was an artifact.'),

  ('mission-ai-unsupervised-territory-12', 1, 'maya', 'The clustering ran on the unlabeled slice of Echo''s log. One result is sitting at the top of Byte''s report, and I want it taken apart before anyone gets excited about it.'),
  ('mission-ai-unsupervised-territory-12', 2, 'byte', 'A small cluster, clearly separated from the rest of the unlabeled data by silhouette score, and it survived every check we usually use to catch an artifact.'),
  ('mission-ai-unsupervised-territory-12', 3, 'maya', 'Survived which checks, exactly. Show me it is not just a bad choice of k. Show me it is not just one unscaled feature doing all the work. I have watched both of those masquerade as a discovery before.'),
  ('mission-ai-unsupervised-territory-12', 4, 'byte', 'Checked. The cluster holds across multiple reasonable k values, and it reappears with features properly scaled. It is not an artifact of either mistake.'),
  ('mission-ai-unsupervised-territory-12', 5, 'maya', 'Then the last question. Does it look like anything we already have a name for -- emergency, routine, anything from the labeled side of the log?'),
  ('mission-ai-unsupervised-territory-12', 6, 'byte', 'No match. Its feature profile does not resemble emergency interactions, does not resemble routine ones, does not resemble anything Cipher Division has previously described or explained.'),
  ('mission-ai-unsupervised-territory-12', 7, 'maya', 'Then we have something real, and something with no label at all. That is not evidence of anything by itself -- a pattern nobody can name is not automatically a threat, or a discovery, or anything else yet.'),
  ('mission-ai-unsupervised-territory-12', 8, 'maya', 'Turning it into something Cipher Division can actually act on is next. Whether tonight''s finding was worth the team''s attention gets decided by what happens after this, not by what was found tonight.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-unsupervised-territory-01-o1', 'mission-ai-unsupervised-territory-01', 1, 'Draw the line', 'Identify what actually distinguishes unsupervised learning from every model Cipher Division has built so far.'),
  ('mission-ai-unsupervised-territory-01-o2', 'mission-ai-unsupervised-territory-01', 2, 'Sort the task', 'Sort each task into supervised or unsupervised based on whether labels are available.'),

  ('mission-ai-unsupervised-territory-02-o1', 'mission-ai-unsupervised-territory-02', 1, 'Define clustering', 'Choose the accurate description of what clustering is actually trying to do.'),
  ('mission-ai-unsupervised-territory-02-o2', 'mission-ai-unsupervised-territory-02', 2, 'Tell it apart from classification', 'Find the evidence that shows a model is doing clustering rather than classification.'),

  ('mission-ai-unsupervised-territory-03-o1', 'mission-ai-unsupervised-territory-03', 1, 'Order the algorithm', 'Put the stages of k-Means in the order they actually happen.'),
  ('mission-ai-unsupervised-territory-03-o2', 'mission-ai-unsupervised-territory-03', 2, 'Name the assumption', 'Identify what k-Means implicitly assumes about the clusters it finds.'),

  ('mission-ai-unsupervised-territory-04-o1', 'mission-ai-unsupervised-territory-04', 1, 'Read the elbow', 'Identify what a good choice of k looks like on an elbow plot.'),
  ('mission-ai-unsupervised-territory-04-o2', 'mission-ai-unsupervised-territory-04', 2, 'Pick the right k', 'Find the evidence that points to the right choice of k for a dataset.'),

  ('mission-ai-unsupervised-territory-05-o1', 'mission-ai-unsupervised-territory-05', 1, 'Contrast with k-Means', 'Identify what DBSCAN does differently from k-Means.'),
  ('mission-ai-unsupervised-territory-05-o2', 'mission-ai-unsupervised-territory-05', 2, 'Match the vocabulary', 'Match each DBSCAN concept to its definition.'),

  ('mission-ai-unsupervised-territory-06-o1', 'mission-ai-unsupervised-territory-06', 1, 'Order the merges', 'Put the stages of agglomerative hierarchical clustering in the order they actually happen.'),
  ('mission-ai-unsupervised-territory-06-o2', 'mission-ai-unsupervised-territory-06', 2, 'Name the advantage', 'State what a dendrogram lets a team do that choosing k-Means or DBSCAN outright does not.'),

  ('mission-ai-unsupervised-territory-07-o1', 'mission-ai-unsupervised-territory-07', 1, 'Name the curse', 'Identify what happens to distance-based methods as dimensions grow very large.'),
  ('mission-ai-unsupervised-territory-07-o2', 'mission-ai-unsupervised-territory-07', 2, 'Diagnose the failure', 'Find the evidence that explains why clustering on the raw, full-width log produced no usable structure.'),

  ('mission-ai-unsupervised-territory-08-o1', 'mission-ai-unsupervised-territory-08', 1, 'Define PCA', 'Choose the accurate description of what PCA actually does to a dataset.'),
  ('mission-ai-unsupervised-territory-08-o2', 'mission-ai-unsupervised-territory-08', 2, 'Judge the reduction', 'Find the evidence that shows a reduced representation preserves most of the real structure in the data.'),

  ('mission-ai-unsupervised-territory-09-o1', 'mission-ai-unsupervised-territory-09', 1, 'Know its limits', 'Identify what a plot after dimensionality reduction is actually good for.'),
  ('mission-ai-unsupervised-territory-09-o2', 'mission-ai-unsupervised-territory-09', 2, 'Read the plot', 'Find the evidence that makes a reasonable visual case for a real, separate group worth investigating further.'),

  ('mission-ai-unsupervised-territory-10-o1', 'mission-ai-unsupervised-territory-10', 1, 'Contrast with clustering', 'Identify how anomaly detection differs from clustering as a goal.'),
  ('mission-ai-unsupervised-territory-10-o2', 'mission-ai-unsupervised-territory-10', 2, 'Spot the real anomaly', 'Find the evidence that points to an actual anomaly rather than a merely rare but ordinary interaction.'),

  ('mission-ai-unsupervised-territory-11-o1', 'mission-ai-unsupervised-territory-11', 1, 'Read the silhouette score', 'State what a silhouette score close to one indicates about a cluster.'),
  ('mission-ai-unsupervised-territory-11-o2', 'mission-ai-unsupervised-territory-11', 2, 'Catch the artifact', 'Find the evidence that would actually prove a cluster is an artifact rather than something real.'),

  ('mission-ai-unsupervised-territory-12-o1', 'mission-ai-unsupervised-territory-12', 1, 'Judge whether it is real', 'Evaluate whether the candidate cluster is genuinely well-separated or just an illusion in the plot.'),
  ('mission-ai-unsupervised-territory-12-o2', 'mission-ai-unsupervised-territory-12', 2, 'Rule out the artifact', 'Determine whether a bad choice of k or an unscaled feature could explain the cluster instead.'),
  ('mission-ai-unsupervised-territory-12-o3', 'mission-ai-unsupervised-territory-12', 3, 'Check against known categories', 'Compare the cluster against every category Cipher Division has previously used to see whether any of them match.'),
  ('mission-ai-unsupervised-territory-12-o4', 'mission-ai-unsupervised-territory-12', 4, 'Name the discovery', 'Having judged realness, ruled out artifacts, and checked against known categories, state exactly what has been found -- and what has not.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-unsupervised-territory-01-o1-c1', 'mission-ai-unsupervised-territory-01-o1', 1, 'multiple_choice', 'What actually distinguishes unsupervised learning from every model Cipher Division built in Acts 7 through 10?', '{"question":"What actually distinguishes unsupervised learning from every model Cipher Division built in Acts 7 through 10?","options":[{"id":"a","text":"It uses a different programming language"},{"id":"b","text":"There are no labels available at all -- there is no correct answer to train toward"},{"id":"c","text":"It requires far less data than supervised learning"},{"id":"d","text":"It only works on image data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-01-o2-c1', 'mission-ai-unsupervised-territory-01-o2', 1, 'drag_and_drop', 'Sort each task into supervised or unsupervised.', '{"items":[{"id":"i1","text":"Predict whether an interaction is an emergency, using interactions already flagged emergency or routine"},{"id":"i2","text":"Group Echo''s un-flagged interactions by similarity, with no flags available at all"},{"id":"i3","text":"Predict a sale price from a table of past sales with known prices"},{"id":"i4","text":"Find natural groupings in a set of purchases with no category tags attached"}],"targets":[{"id":"supervised","label":"Supervised"},{"id":"unsupervised","label":"Unsupervised"}]}'::jsonb, '{"correctMapping":{"i1":"supervised","i2":"unsupervised","i3":"supervised","i4":"unsupervised"}}'::jsonb),

  ('mission-ai-unsupervised-territory-02-o1-c1', 'mission-ai-unsupervised-territory-02-o1', 1, 'multiple_choice', 'What is clustering actually trying to do?', '{"question":"What is clustering actually trying to do?","options":[{"id":"a","text":"Predict a numeric label for each example"},{"id":"b","text":"Group examples so items within a group are more similar to each other than to items in other groups"},{"id":"c","text":"Sort examples into groups that were already named ahead of time"},{"id":"d","text":"Reduce the number of features in a dataset"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-02-o2-c1', 'mission-ai-unsupervised-territory-02-o2', 1, 'investigation', 'Which evidence shows this model is doing clustering rather than classification?', '{"evidence":[{"id":"e1","label":"Model output","detail":"Assigns every interaction to group 1, 2, or 3, with no group ever given a name by the model itself"},{"id":"e2","label":"Training log","detail":"Model was trained on examples already marked emergency or routine"},{"id":"e3","label":"Feature list","detail":"Model uses seven numeric fields describing each interaction"}],"question":"Which evidence shows this model is doing clustering rather than classification?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-unsupervised-territory-03-o1-c1', 'mission-ai-unsupervised-territory-03-o1', 1, 'interactive_diagram', 'Order the stages of k-Means from first to last.', '{"diagramId":"k-means-loop","hotspots":[{"id":"k1","label":"Choose the number of clusters, k","explanation":"k is set before the algorithm runs -- it is never learned from the data itself."},{"id":"k2","label":"Place k initial centers","explanation":"Starting positions for the k centers are picked, often at random."},{"id":"k3","label":"Assign every point to its nearest center","explanation":"Each point joins whichever of the k centers is currently closest to it."},{"id":"k4","label":"Recompute each center as the mean of its assigned points","explanation":"Every center moves to the average position of the points now assigned to it."},{"id":"k5","label":"Repeat until the centers stop moving","explanation":"Assignment and recomputation alternate until no center''s position changes."}],"task":"Order the stages of k-Means from first to last."}'::jsonb, '{"correctOrderIds":["k1","k2","k3","k4","k5"]}'::jsonb),
  ('mission-ai-unsupervised-territory-03-o2-c1', 'mission-ai-unsupervised-territory-03-o2', 1, 'multiple_choice', 'What does k-Means implicitly assume about the clusters it finds?', '{"question":"What does k-Means implicitly assume about the clusters it finds?","options":[{"id":"a","text":"That every cluster is roughly round and similar in size to the others"},{"id":"b","text":"That the correct number of clusters is always known in advance by the algorithm itself"},{"id":"c","text":"That the data must already be labeled"},{"id":"d","text":"That clusters can have any arbitrary, winding shape"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-ai-unsupervised-territory-04-o1-c1', 'mission-ai-unsupervised-territory-04-o1', 1, 'multiple_choice', 'The elbow method plots how much clustering error shrinks as k increases. What indicates a good choice of k?', '{"question":"The elbow method plots how much clustering error shrinks as k increases. What indicates a good choice of k?","options":[{"id":"a","text":"The largest k tried, since more clusters always fit the data better"},{"id":"b","text":"The point where adding more clusters stops producing much additional improvement -- the bend in the curve"},{"id":"c","text":"Whichever k produces exactly two clusters"},{"id":"d","text":"The smallest k tried, regardless of the curve''s shape"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-04-o2-c1', 'mission-ai-unsupervised-territory-04-o2', 1, 'investigation', 'Which evidence points to the right choice of k for this dataset?', '{"evidence":[{"id":"e1","label":"Elbow plot","detail":"Error drops sharply from k=1 to k=4, then flattens almost completely from k=4 onward"},{"id":"e2","label":"Team note","detail":"Increasing k always decreases training time"},{"id":"e3","label":"Ops log","detail":"The dataset was collected over a six-month period"}],"question":"Which evidence points to the right choice of k for this dataset?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-unsupervised-territory-05-o1-c1', 'mission-ai-unsupervised-territory-05-o1', 1, 'multiple_choice', 'What does DBSCAN do differently from k-Means?', '{"question":"What does DBSCAN do differently from k-Means?","options":[{"id":"a","text":"It requires k to be set even more precisely than k-Means does"},{"id":"b","text":"It grows clusters from areas of high point density and labels sparse points as noise, without needing k at all"},{"id":"c","text":"It only works on data with exactly two features"},{"id":"d","text":"It always produces the same number of clusters as k-Means"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-05-o2-c1', 'mission-ai-unsupervised-territory-05-o2', 1, 'drag_and_drop', 'Match each DBSCAN concept to its definition.', '{"items":[{"id":"d1","text":"Core point"},{"id":"d2","text":"Border point"},{"id":"d3","text":"Noise point"}],"targets":[{"id":"t1","label":"Has enough neighbors packed within its radius to anchor a cluster"},{"id":"t2","label":"Sits within reach of a core point but does not have enough neighbors of its own to anchor one"},{"id":"t3","label":"Is not close enough to any cluster to be claimed by it"}]}'::jsonb, '{"correctMapping":{"d1":"t1","d2":"t2","d3":"t3"}}'::jsonb),

  ('mission-ai-unsupervised-territory-06-o1-c1', 'mission-ai-unsupervised-territory-06-o1', 1, 'interactive_diagram', 'Order the stages of agglomerative hierarchical clustering from first to last.', '{"diagramId":"agglomerative-clustering","hotspots":[{"id":"g1","label":"Start with every point as its own cluster","explanation":"No merging has happened yet -- each point is its own group of one."},{"id":"g2","label":"Find the two closest clusters","explanation":"Closeness is measured between whole clusters, not just single points."},{"id":"g3","label":"Merge those two clusters into one","explanation":"The closest pair becomes a single cluster going forward."},{"id":"g4","label":"Repeat until only one cluster remains","explanation":"Merging continues, tracked the whole way, until everything has combined."},{"id":"g5","label":"Cut the resulting dendrogram at the desired height","explanation":"The height chosen determines how many clusters come out at the end."}],"task":"Order the stages of agglomerative hierarchical clustering from first to last."}'::jsonb, '{"correctOrderIds":["g1","g2","g3","g4","g5"]}'::jsonb),
  ('mission-ai-unsupervised-territory-06-o2-c1', 'mission-ai-unsupervised-territory-06-o2', 1, 'multiple_choice', 'What does a dendrogram let a team do that choosing k-Means or DBSCAN outright does not?', '{"question":"What does a dendrogram let a team do that choosing k-Means or DBSCAN outright does not?","options":[{"id":"a","text":"Skip clustering entirely"},{"id":"b","text":"See the full merge history and choose how many clusters to keep after seeing the whole hierarchy, not before"},{"id":"c","text":"Guarantee perfectly round clusters"},{"id":"d","text":"Avoid needing any distance measure at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-unsupervised-territory-07-o1-c1', 'mission-ai-unsupervised-territory-07-o1', 1, 'multiple_choice', 'As the number of dimensions in a dataset grows very large, what tends to happen to distance-based methods like k-Means or DBSCAN?', '{"question":"As the number of dimensions in a dataset grows very large, what tends to happen to distance-based methods like k-Means or DBSCAN?","options":[{"id":"a","text":"They become more accurate, since more features means more information"},{"id":"b","text":"Points start looking almost equally far from each other, and distance stops being a reliable signal"},{"id":"c","text":"They automatically switch to using fewer features"},{"id":"d","text":"Nothing changes -- dimensionality has no effect on distance"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-07-o2-c1', 'mission-ai-unsupervised-territory-07-o2', 1, 'investigation', 'Which evidence explains why clustering on the raw, full-width log produced no usable structure?', '{"evidence":[{"id":"e1","label":"Clustering report","detail":"Run on all 60 raw fields, silhouette scores were close to zero across every k tried"},{"id":"e2","label":"Ops note","detail":"The log was collected from Echo''s production servers"},{"id":"e3","label":"Storage log","detail":"The full unlabeled log takes up several gigabytes"}],"question":"Which evidence explains why clustering on the raw, full-width log produced no usable structure?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-unsupervised-territory-08-o1-c1', 'mission-ai-unsupervised-territory-08-o1', 1, 'multiple_choice', 'What does PCA actually do to a dataset?', '{"question":"What does PCA actually do to a dataset?","options":[{"id":"a","text":"Deletes whichever original columns seem least important"},{"id":"b","text":"Finds new directions, combinations of the original features, that capture the most variation, and keeps only the top few"},{"id":"c","text":"Removes duplicate rows from the data"},{"id":"d","text":"Converts every feature into a label"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-08-o2-c1', 'mission-ai-unsupervised-territory-08-o2', 1, 'investigation', 'Which evidence shows the reduced representation actually preserves most of the real structure in the data?', '{"evidence":[{"id":"e1","label":"PCA report","detail":"The first three principal components together capture 91 percent of the total variance in the data"},{"id":"e2","label":"PCA report","detail":"Component ordering is based on the order columns appeared in the raw log"},{"id":"e3","label":"Compute log","detail":"PCA finished running in under a minute"}],"question":"Which evidence shows the reduced representation actually preserves most of the real structure in the data?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-unsupervised-territory-09-o1-c1', 'mission-ai-unsupervised-territory-09-o1', 1, 'multiple_choice', 'After reducing Echo''s log to its top principal components and plotting it, what is that plot actually good for?', '{"question":"After reducing Echo''s log to its top principal components and plotting it, what is that plot actually good for?","options":[{"id":"a","text":"Serving as final, sufficient proof that any visible grouping is a real cluster"},{"id":"b","text":"A first look that suggests where to investigate further -- not proof by itself"},{"id":"c","text":"Replacing the need for any clustering algorithm entirely"},{"id":"d","text":"Guaranteeing the exact number of real clusters in the data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-09-o2-c1', 'mission-ai-unsupervised-territory-09-o2', 1, 'investigation', 'Which evidence makes a reasonable visual case for a real, separate group worth investigating further?', '{"evidence":[{"id":"e1","label":"Plot A","detail":"Shows one small, tight group of points sitting clearly apart from a large, diffuse main body"},{"id":"e2","label":"Plot B","detail":"Shows points spread in one continuous blob with no visible gaps anywhere"},{"id":"e3","label":"Plot A caption","detail":"Axes are the first two principal components, together explaining 78 percent of variance"}],"question":"Which evidence makes a reasonable visual case for a real, separate group worth investigating further?"}'::jsonb, '{"requiredEvidenceIds":["e1","e3"]}'::jsonb),

  ('mission-ai-unsupervised-territory-10-o1-c1', 'mission-ai-unsupervised-territory-10-o1', 1, 'multiple_choice', 'How does anomaly detection differ from clustering as a goal?', '{"question":"How does anomaly detection differ from clustering as a goal?","options":[{"id":"a","text":"Anomaly detection groups similar points together, exactly like clustering"},{"id":"b","text":"Anomaly detection asks whether a point fits any dense pattern at all, rather than which group it belongs to"},{"id":"c","text":"Anomaly detection requires labeled data and clustering does not"},{"id":"d","text":"They are the same technique with different names"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-10-o2-c1', 'mission-ai-unsupervised-territory-10-o2', 1, 'investigation', 'Which evidence actually points to an anomaly, rather than a merely rare but ordinary interaction?', '{"evidence":[{"id":"e1","label":"Interaction record","detail":"Occurs only 12 times in the whole log, but its feature values sit well inside the normal range for a known, common interaction type"},{"id":"e2","label":"Interaction record","detail":"Occurs 9 times in the whole log, and its feature values fall far outside the range seen for every known interaction type"},{"id":"e3","label":"Log summary","detail":"The full unlabeled log contains just over one million interactions"}],"question":"Which evidence actually points to an anomaly, rather than a merely rare but ordinary interaction?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-unsupervised-territory-11-o1-c1', 'mission-ai-unsupervised-territory-11-o1', 1, 'multiple_choice', 'A cluster has a silhouette score close to 1. What does that indicate?', '{"question":"A cluster has a silhouette score close to 1. What does that indicate?","options":[{"id":"a","text":"The cluster is poorly separated and probably not real"},{"id":"b","text":"Points in the cluster sit much closer to their own cluster than to the next nearest one -- a well-separated cluster"},{"id":"c","text":"The cluster contains exactly one point"},{"id":"d","text":"The score is unrelated to cluster quality"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-unsupervised-territory-11-o2-c1', 'mission-ai-unsupervised-territory-11-o2', 1, 'investigation', 'Which evidence would actually prove a cluster is an artifact rather than something real?', '{"evidence":[{"id":"e1","label":"Stability check","detail":"The cluster reappears with a nearly identical silhouette score across k=6, k=7, and k=8"},{"id":"e2","label":"Scaling check","detail":"The cluster only appears when one unscaled feature with a much larger numeric range is left unscaled; it disappears once features are properly scaled"},{"id":"e3","label":"Team note","detail":"The analysis was run on a single afternoon"}],"question":"Which evidence would actually prove a cluster is an artifact rather than something real?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-unsupervised-territory-12-o1-c1', 'mission-ai-unsupervised-territory-12-o1', 1, 'investigation', 'Which evidence actually supports the candidate cluster being a real, well-separated group rather than a coincidence of the plot?', '{"evidence":[{"id":"e1","label":"Silhouette report","detail":"The candidate cluster scores 0.81 average silhouette, versus scores near zero for random groupings of the same size"},{"id":"e2","label":"Separation plot","detail":"On the top two principal components, the candidate cluster sits as a tight, visibly separated group away from the rest of the unlabeled data"},{"id":"e3","label":"Ops note","detail":"The candidate cluster was first spotted during a routine overnight run"}],"question":"Which evidence actually supports the candidate cluster being a real, well-separated group rather than a coincidence of the plot?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-unsupervised-territory-12-o2-c1', 'mission-ai-unsupervised-territory-12-o2', 1, 'investigation', 'Which evidence rules out a bad choice of k or an unscaled feature as the explanation for this cluster?', '{"evidence":[{"id":"e1","label":"k-stability check","detail":"The cluster reappears with a consistent silhouette score across k=5 through k=9, not just the k originally tried"},{"id":"e2","label":"Scaling check","detail":"The cluster still appears, essentially unchanged, after every feature is properly scaled to a common range"},{"id":"e3","label":"Counter-example","detail":"A separate run on properly scaled data with k deliberately set badly produced three unstable clusters that vanished when k changed"}],"question":"Which evidence rules out a bad choice of k or an unscaled feature as the explanation for this cluster?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),
  ('mission-ai-unsupervised-territory-12-o3-c1', 'mission-ai-unsupervised-territory-12-o3', 1, 'investigation', 'Which evidence shows this cluster does not correspond to any category Cipher Division has previously used?', '{"evidence":[{"id":"e1","label":"Feature comparison","detail":"The cluster''s average feature profile does not match the emergency-interaction profile from the labeled tournament data"},{"id":"e2","label":"Feature comparison","detail":"The cluster''s average feature profile does not match the routine-interaction profile either"},{"id":"e3","label":"Historical note","detail":"No category used anywhere in Cipher Division''s prior labeling ever described this feature combination"},{"id":"e4","label":"Ops log","detail":"The cluster was detected using the same clustering pipeline validated in the previous objective"}],"question":"Which evidence shows this cluster does not correspond to any category Cipher Division has previously used?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2","e3"]}'::jsonb),
  ('mission-ai-unsupervised-territory-12-o4-c1', 'mission-ai-unsupervised-territory-12-o4', 1, 'boss_encounter', 'Having judged realness, ruled out artifacts, and checked against known categories, state exactly what has been found -- and what has not.', '{"stages":[{"objectiveRef":"mission-ai-unsupervised-territory-12-o1","label":"Judge whether it is real"},{"objectiveRef":"mission-ai-unsupervised-territory-12-o2","label":"Rule out the artifact"},{"objectiveRef":"mission-ai-unsupervised-territory-12-o3","label":"Check against known categories"}],"task":"State what tonight''s clustering run actually found: a small, well-separated, statistically real cluster in Echo''s unlabeled log that does not match any category Cipher Division has ever used -- and nothing more than that, yet."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-unsupervised-territory-12-o1","mission-ai-unsupervised-territory-12-o2","mission-ai-unsupervised-territory-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-unsupervised-territory-01-o1-c1', 'orientation', 'Ask whether there is a correct answer available anywhere in the data for the model to be checked against.', 10, 1),
  ('mission-ai-unsupervised-territory-01-o1-c1', 'solution', 'Unsupervised learning has no labels at all, so there is no correct answer to train toward -- that is the entire distinction.', 20, 2),
  ('mission-ai-unsupervised-territory-01-o2-c1', 'orientation', 'Ask whether the correct answer already exists somewhere in each dataset, attached to the examples.', 10, 1),
  ('mission-ai-unsupervised-territory-01-o2-c1', 'solution', 'Supervised: predicting from data that already carries flags or known prices. Unsupervised: grouping data with no flags or category tags at all.', 20, 2),

  ('mission-ai-unsupervised-territory-02-o1-c1', 'orientation', 'Clustering never produces a label a person wrote down ahead of time.', 10, 1),
  ('mission-ai-unsupervised-territory-02-o1-c1', 'solution', 'Clustering groups examples so that items within a group are more similar to each other than to items outside it -- it proposes structure, not a prediction.', 20, 2),
  ('mission-ai-unsupervised-territory-02-o2-c1', 'orientation', 'A clustering model has no concept of a named answer -- only group numbers it invented itself.', 10, 1),
  ('mission-ai-unsupervised-territory-02-o2-c1', 'solution', 'e1: the model assigns unnamed group numbers with nothing trained against a label -- that is clustering, not classification.', 20, 2),

  ('mission-ai-unsupervised-territory-03-o1-c1', 'orientation', 'Nothing can be assigned to a center until the centers actually exist.', 10, 1),
  ('mission-ai-unsupervised-territory-03-o1-c1', 'concept', 'The loop only stops once assigning points and recomputing centers no longer changes anything.', 20, 2),
  ('mission-ai-unsupervised-territory-03-o1-c1', 'solution', 'Choose k, place initial centers, assign points to the nearest center, recompute each center as a mean, repeat until the centers stop moving.', 30, 3),
  ('mission-ai-unsupervised-territory-03-o2-c1', 'orientation', 'Think about what shape a center-and-nearest-point rule naturally produces.', 10, 1),
  ('mission-ai-unsupervised-territory-03-o2-c1', 'solution', 'k-Means implicitly assumes clusters are roughly round and similarly sized -- it has no way to represent an arbitrary or stretched-out shape.', 20, 2),

  ('mission-ai-unsupervised-territory-04-o1-c1', 'orientation', 'Look for where the curve stops dropping and starts going flat.', 10, 1),
  ('mission-ai-unsupervised-territory-04-o1-c1', 'solution', 'A good k sits at the bend where additional clusters stop meaningfully reducing error -- past that point, extra k is mostly noise.', 20, 2),
  ('mission-ai-unsupervised-territory-04-o2-c1', 'orientation', 'Training time and collection period are not signals about how many real groups exist.', 10, 1),
  ('mission-ai-unsupervised-territory-04-o2-c1', 'solution', 'e1: the sharp drop through k=4 followed by a flat line is the elbow -- the evidence that k=4 is the right choice.', 20, 2),

  ('mission-ai-unsupervised-territory-05-o1-c1', 'orientation', 'Think about what DBSCAN never has to be told before it runs.', 10, 1),
  ('mission-ai-unsupervised-territory-05-o1-c1', 'solution', 'DBSCAN grows clusters from dense neighborhoods and labels sparse points as noise, with no k required at all.', 20, 2),
  ('mission-ai-unsupervised-territory-05-o2-c1', 'orientation', 'Ask how close each kind of point is to a dense neighborhood, and whether it anchors one or just borrows from one.', 10, 1),
  ('mission-ai-unsupervised-territory-05-o2-c1', 'solution', 'Core point: anchors a cluster with enough close neighbors. Border point: near a core point but not dense enough itself. Noise point: not close enough to any cluster.', 20, 2),

  ('mission-ai-unsupervised-territory-06-o1-c1', 'orientation', 'Every point begins alone -- nothing has merged yet at the start.', 10, 1),
  ('mission-ai-unsupervised-territory-06-o1-c1', 'concept', 'The dendrogram only exists once merging has been tracked all the way to a single cluster.', 20, 2),
  ('mission-ai-unsupervised-territory-06-o1-c1', 'solution', 'Start with every point alone, repeatedly merge the two closest clusters until one remains, then cut the resulting dendrogram at the height that gives the desired number of clusters.', 30, 3),
  ('mission-ai-unsupervised-territory-06-o2-c1', 'orientation', 'k-Means and DBSCAN each commit to a cluster count before or during the run. A dendrogram does not.', 10, 1),
  ('mission-ai-unsupervised-territory-06-o2-c1', 'solution', 'A dendrogram shows the entire merge history, letting a team choose the number of clusters after seeing the whole hierarchy instead of guessing k upfront.', 20, 2),

  ('mission-ai-unsupervised-territory-07-o1-c1', 'orientation', 'Ask what happens to the gap between the nearest and farthest point as more columns get added.', 10, 1),
  ('mission-ai-unsupervised-territory-07-o1-c1', 'solution', 'In very high dimensions, points start looking almost equally far apart, so distance-based methods lose their signal.', 20, 2),
  ('mission-ai-unsupervised-territory-07-o2-c1', 'orientation', 'A silhouette score near zero across every k tried is not a coincidence.', 10, 1),
  ('mission-ai-unsupervised-territory-07-o2-c1', 'solution', 'e1: silhouette scores near zero on all 60 raw fields, across every k, is the curse of dimensionality showing up directly in the results.', 20, 2),

  ('mission-ai-unsupervised-territory-08-o1-c1', 'orientation', 'PCA builds new directions -- it does not simply pick which original columns to keep.', 10, 1),
  ('mission-ai-unsupervised-territory-08-o1-c1', 'solution', 'PCA finds new directions combining the original features that capture the most variation, then keeps only the top few of them.', 20, 2),
  ('mission-ai-unsupervised-territory-08-o2-c1', 'orientation', 'The runtime and the column ordering do not describe how much real structure survived the reduction.', 10, 1),
  ('mission-ai-unsupervised-territory-08-o2-c1', 'solution', 'e1: 91 percent of total variance captured by just three components means almost all the real structure survived the reduction.', 20, 2),

  ('mission-ai-unsupervised-territory-09-o1-c1', 'orientation', 'A plot is something to investigate further, not a verdict by itself.', 10, 1),
  ('mission-ai-unsupervised-territory-09-o1-c1', 'solution', 'Reduced plots are a useful first look that suggests where to dig deeper -- they are not sufficient proof of a real cluster on their own.', 20, 2),
  ('mission-ai-unsupervised-territory-09-o2-c1', 'orientation', 'A convincing visual case needs both a visible gap and confidence that the axes actually represent the data well.', 10, 1),
  ('mission-ai-unsupervised-territory-09-o2-c1', 'concept', 'A plot with almost no variance explained could show a gap that means nothing -- the caption matters as much as the shape.', 20, 2),
  ('mission-ai-unsupervised-territory-09-o2-c1', 'solution', 'e1 and e3 together: a visibly separated group, on axes that explain 78 percent of variance, is a reasonable case worth investigating -- unlike Plot B''s single continuous blob.', 30, 3),

  ('mission-ai-unsupervised-territory-10-o1-c1', 'orientation', 'Clustering asks which group. Anomaly detection asks a different question entirely.', 10, 1),
  ('mission-ai-unsupervised-territory-10-o1-c1', 'solution', 'Anomaly detection asks whether a point fits any dense pattern at all, rather than which group it should join.', 20, 2),
  ('mission-ai-unsupervised-territory-10-o2-c1', 'orientation', 'Rarity alone is not the same as being far outside every known pattern.', 10, 1),
  ('mission-ai-unsupervised-territory-10-o2-c1', 'solution', 'e2: values far outside every known interaction type''s range, not just a low count, is what actually marks a true anomaly.', 20, 2),

  ('mission-ai-unsupervised-territory-11-o1-c1', 'orientation', 'A silhouette score near one means a point is much closer to its own cluster than to any other.', 10, 1),
  ('mission-ai-unsupervised-territory-11-o1-c1', 'solution', 'A score close to one indicates points sit much closer to their own cluster than to the next nearest one -- a well-separated cluster.', 20, 2),
  ('mission-ai-unsupervised-territory-11-o2-c1', 'orientation', 'A real cluster should not depend on leaving one feature unscaled to appear.', 10, 1),
  ('mission-ai-unsupervised-territory-11-o2-c1', 'solution', 'e2: a cluster that disappears once features are properly scaled was only ever an artifact of one unscaled feature dominating the distance calculation.', 20, 2),

  ('mission-ai-unsupervised-territory-12-o1-c1', 'orientation', 'A real cluster should look separated both in a numeric score and in the plot, not just one or the other.', 10, 1),
  ('mission-ai-unsupervised-territory-12-o1-c1', 'concept', 'When a raw score and a visual layout point the same direction, that is a much stronger case than either one alone.', 20, 2),
  ('mission-ai-unsupervised-territory-12-o1-c1', 'solution', 'e1 and e2 together: a 0.81 silhouette score far above random groupings, plus a visibly separated group on the top principal components, together support a genuine cluster.', 30, 3),
  ('mission-ai-unsupervised-territory-12-o2-c1', 'orientation', 'Both the k-choice explanation and the unscaled-feature explanation need to be checked directly, not assumed away.', 10, 1),
  ('mission-ai-unsupervised-territory-12-o2-c1', 'concept', 'A cluster that survives when k changes, and survives when features are scaled properly, cannot be blamed on either mistake.', 20, 2),
  ('mission-ai-unsupervised-territory-12-o2-c1', 'solution', 'e1 and e2 together: consistent across k=5 through k=9, and unchanged after proper scaling -- neither a bad k nor an unscaled feature explains this cluster.', 30, 3),
  ('mission-ai-unsupervised-territory-12-o3-c1', 'orientation', 'A true unknown population should fail to match every category Cipher Division already has a name for.', 10, 1),
  ('mission-ai-unsupervised-territory-12-o3-c1', 'concept', 'Checking against one known category is not enough -- it has to fail to match all of them, and the historical record has to back that up.', 20, 2),
  ('mission-ai-unsupervised-territory-12-o3-c1', 'solution', 'e1, e2 and e3 together: no match to emergency, no match to routine, and no prior category anywhere in Cipher Division''s history ever described this feature combination.', 30, 3),
  ('mission-ai-unsupervised-territory-12-o4-c1', 'orientation', 'Report exactly what the evidence supports -- realness, and the absence of a match -- nothing beyond that.', 15, 1),
  ('mission-ai-unsupervised-territory-12-o4-c1', 'solution', 'Tonight''s run found a small, well-separated, statistically real cluster in Echo''s unlabeled log that does not match any category Cipher Division has ever used -- not what it means, only that it is real and unnamed.', 25, 2);
