-- AI/ML pathway ("Cipher Division") Act 19 -- "Machines That See" content.
-- Opens Arc IV ("Machines That See and Read", Acts 19-23). 1 campaign,
-- 2 operations, 12 missions (11 lessons + boss), following the same
-- campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other Act in this pathway.
-- Does not touch worlds/acts/pathways -- world-ai-machines-that-see and its
-- narrative fields already exist from 20260812070000_ai_acts16_20_world_narrative.sql.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-machines-that-see', 'world-ai-machines-that-see', 'machines-that-see', '19A - Machines That See', 'Images as tensors, channels, convolution, kernels, feature maps, padding, stride, pooling, CNNs, classification and augmentation -- learning to read a camera feed with the same rigor applied to every other kind of data this pathway has covered.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-machines-that-see-1', 'campaign-ai-machines-that-see', 'pixels-as-data', 'Pixels as Data', 'What an image actually is as a tensor, and the core convolution operation that lets a model read one.', 1),
  ('operation-ai-machines-that-see-2', 'campaign-ai-machines-that-see', 'reading-the-feed', 'Reading the Feed', 'Stride, pooling, full CNN architectures, classification and augmentation, assembled into a model that can actually judge a reactor-housing camera feed.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-machines-that-see-01', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'images-as-tensors', 'Images as Tensors', 'Cooling-system camera feeds have been flagging inconsistently since Echo first spiked the grid in Act 1. Before any of it can be modeled, a camera frame has to be understood as what it actually is: a tensor of numbers.', 'beginner', ARRAY['maya','elena'], null, null, '{"type":"simulation","simulationId":"images-as-tensors-sim"}'::jsonb, '{"xp":350,"credits":85}'::jsonb, false, 1),
  ('mission-ai-machines-that-see-02', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'channels', 'Channels', 'Grayscale, RGB, thermal -- Cipher Labs'' cooling cameras do not all capture the same channels, and a model that assumes otherwise breaks silently.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-machines-that-see-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"channels-sim"}'::jsonb, '{"xp":360,"credits":85}'::jsonb, false, 2),
  ('mission-ai-machines-that-see-03', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'convolution', 'Convolution', 'The operation underneath every CNN: sliding a small window across an image and turning what it covers into a single number, one position at a time.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"convolution-sim"}'::jsonb, '{"xp":360,"credits":90}'::jsonb, false, 3),
  ('mission-ai-machines-that-see-04', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'kernels', 'Kernels', 'The small matrix convolution actually slides across an image -- and the thing training spends its time deciding the values of.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"kernels-sim"}'::jsonb, '{"xp":370,"credits":90}'::jsonb, false, 4),
  ('mission-ai-machines-that-see-05', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'feature-maps', 'Feature Maps', 'The output of sliding one kernel across an entire image: a grid that lights up wherever that kernel''s pattern actually appears.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-machines-that-see-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"feature-maps-sim"}'::jsonb, '{"xp":370,"credits":90}'::jsonb, false, 5),
  ('mission-ai-machines-that-see-06', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-1', 'padding', 'Padding', 'Every convolution shrinks the image a little unless something is done about it. Padding is that something.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"padding-sim"}'::jsonb, '{"xp":380,"credits":95}'::jsonb, false, 6),
  ('mission-ai-machines-that-see-07', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'stride', 'Stride', 'How far the kernel jumps between positions -- and the simplest way a convolutional layer can downsample an image on purpose.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"stride-sim"}'::jsonb, '{"xp":380,"credits":95}'::jsonb, false, 7),
  ('mission-ai-machines-that-see-08', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'pooling', 'Pooling', 'A second, simpler way to shrink a feature map on purpose -- and make the model care less about a pattern''s exact pixel position.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-machines-that-see-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"pooling-sim"}'::jsonb, '{"xp":390,"credits":95}'::jsonb, false, 8),
  ('mission-ai-machines-that-see-09', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'cnns', 'CNNs', 'Convolution, kernels, feature maps, padding, stride and pooling stop being six separate ideas the moment they get stacked into an actual convolutional neural network.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"cnn-architecture-sim"}'::jsonb, '{"xp":390,"credits":100}'::jsonb, false, 9),
  ('mission-ai-machines-that-see-10', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'classification', 'Classification', 'The final step: turning a CNN''s extracted features into an actual answer -- damaged or not damaged -- along with a number saying how confident that answer is.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"image-classification-sim"}'::jsonb, '{"xp":400,"credits":100}'::jsonb, false, 10),
  ('mission-ai-machines-that-see-11', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'augmentation', 'Augmentation', 'Cooling-camera frames never look exactly the same twice. Augmentation is how a CNN learns to survive that instead of memorizing one clean version of every frame.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-machines-that-see-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"augmentation-sim"}'::jsonb, '{"xp":400,"credits":100}'::jsonb, false, 11),
  ('mission-ai-machines-that-see-12', 'world-ai-machines-that-see', 'campaign-ai-machines-that-see', 'operation-ai-machines-that-see-2', 'identify-the-damaged-reactor', 'Identify the Damaged Reactor', 'A CNN classifier flags one reactor-housing frame that this month''s entire manual inspection sweep called clean. Confirm whether it deserves to be believed before anyone touches that reactor.', 'boss', ARRAY['maya','elena','byte'], '{"requiredMissionIds":["mission-ai-machines-that-see-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"damaged-reactor-boss-sim"}'::jsonb, '{"xp":950,"credits":210,"badgeIds":["identify-the-damaged-reactor"],"skillXp":{"computer_vision":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-machines-that-see-01', 1, 'maya', 'Cooling-system camera feeds across Cipher Labs have been flagging inconsistently since Echo''s power draw first spiked back in Act 1. Nobody has ever taught a model to actually look at them.'),
  ('mission-ai-machines-that-see-01', 2, 'maya', 'Every model this pathway has built so far ate rows and columns of numbers. A camera frame does not look like a spreadsheet. I want to know if that is actually true before we treat it as some brand new problem.'),
  ('mission-ai-machines-that-see-01', 3, 'elena', 'It is not as different as it looks. A grayscale image is a 2D grid of numbers, one per pixel, each one a brightness value from 0 to 255. Add color, and it becomes a 3D grid -- height, width, and a third dimension for channels. Still a tensor. Still numbers.'),
  ('mission-ai-machines-that-see-01', 4, 'elena', 'What changes is the shape and what the numbers mean, not the discipline. Everything Arc III taught about honest evaluation, real baselines, controlled comparisons -- none of that goes away because the input is pixels instead of a table. We just need a new set of tools built for grids instead of rows: convolutional neural networks.'),

  ('mission-ai-machines-that-see-02', 1, 'elena', 'A channel is one full grid of numbers layered on top of the same height and width. Grayscale images have one channel: brightness. Color images usually have three: red, green and blue, each its own full grid.'),
  ('mission-ai-machines-that-see-02', 2, 'byte', 'I pulled the cooling-camera feed specs. Most of Cipher Labs runs standard RGB, three channels. Two reactor-adjacent units run thermal-only cameras -- one channel, intensity mapped to heat instead of light.'),
  ('mission-ai-machines-that-see-02', 3, 'elena', 'That matters. A model built assuming three channels will break, silently, on a one-channel thermal frame unless someone accounts for it. Channels are not decoration. They are part of the tensor shape.'),

  ('mission-ai-machines-that-see-03', 1, 'elena', 'Convolution is the core operation. Take a small window, a few pixels wide, place it over one corner of the image, multiply each pixel underneath it by a matching weight, and add the results into one number.'),
  ('mission-ai-machines-that-see-03', 2, 'elena', 'Then slide the window over by a step, and do it again. Repeat across the whole image, and the output is a brand new grid, usually smaller, built entirely out of those local, weighted sums.'),
  ('mission-ai-machines-that-see-03', 3, 'elena', 'That local window is the whole point. Instead of looking at an entire cooling-camera frame at once, the model looks at small patches, the way a person''s eye actually settles on one detail before another.'),

  ('mission-ai-machines-that-see-04', 1, 'elena', 'The kernel, sometimes called a filter, is the small matrix of weights that convolution multiplies against the image. A 3x3 kernel has nine numbers. Those numbers are not hand-picked. They are exactly what training learns.'),
  ('mission-ai-machines-that-see-04', 2, 'elena', 'Different kernel values detect different things. One learned pattern of weights lights up on vertical edges. Another lights up on horizontal edges. Another on a corner, or a texture, or eventually something nobody would think to name.'),
  ('mission-ai-machines-that-see-04', 3, 'elena', 'A CNN never gets handed a single kernel. It learns dozens, sometimes hundreds, each one becoming its own small detector.'),

  ('mission-ai-machines-that-see-05', 1, 'elena', 'Run one kernel across an entire image, and the result is a feature map -- a grid the same rough shape as the input, except every value now says how strongly that kernel''s pattern showed up at that position.'),
  ('mission-ai-machines-that-see-05', 2, 'byte', 'I ran an edge-detecting kernel across a cooling-vent frame. The feature map lit up bright exactly along the vent''s metal seams and stayed flat everywhere else. That is the kernel doing its job, visibly.'),
  ('mission-ai-machines-that-see-05', 3, 'elena', 'A CNN keeps dozens of these feature maps, one per kernel, stacked together. High activation somewhere on a feature map is the model''s clearest evidence that whatever that kernel detects is actually present, right there.'),

  ('mission-ai-machines-that-see-06', 1, 'elena', 'Slide a kernel across an image without changing anything else, and the output is smaller than the input -- the kernel cannot center itself over the outermost pixels, so those positions get dropped.'),
  ('mission-ai-machines-that-see-06', 2, 'elena', 'Padding adds extra pixels, usually zeros, around the border before convolving. Do it right, and the output stays the same size as the input instead of shrinking with every layer.'),
  ('mission-ai-machines-that-see-06', 3, 'elena', 'Two names worth knowing: valid padding, which is really no padding at all and lets the output shrink, and same padding, which adds just enough border to keep the output size matching the input.'),

  ('mission-ai-machines-that-see-07', 1, 'elena', 'Stride is how many pixels the kernel moves between each position. Stride 1 slides one pixel at a time and produces a large, dense output. Stride 2 skips every other position and produces a smaller, coarser one.'),
  ('mission-ai-machines-that-see-07', 2, 'elena', 'Bigger stride means fewer positions checked, a smaller output, and less compute, at the cost of some spatial detail. It is a deliberate downsampling knob, not an accident.'),
  ('mission-ai-machines-that-see-07', 3, 'elena', 'The output size formula matters here, not just the intuition. Get stride or padding wrong in code and the layer dimensions stop lining up with what the next layer expects.'),

  ('mission-ai-machines-that-see-08', 1, 'elena', 'Pooling shrinks a feature map by summarizing small regions into a single value, no learned weights involved. Max pooling keeps the strongest activation in each region. Average pooling keeps the mean.'),
  ('mission-ai-machines-that-see-08', 2, 'byte', 'I ran max pooling on that vent-seam feature map from mission five. The bright activation line survived. Most of the flat, near-zero background got compressed away entirely.'),
  ('mission-ai-machines-that-see-08', 3, 'elena', 'That is the real benefit, beyond just making the data smaller. Pooling makes the model a little less sensitive to a pattern sitting at exactly pixel 104 versus pixel 106 -- it cares that the pattern was somewhere in that region.'),

  ('mission-ai-machines-that-see-09', 1, 'elena', 'Stack it all together and this is a CNN: convolutional layers extracting feature maps, pooling layers shrinking them down, repeated a few times, then a flatten step and one or more ordinary fully connected layers at the end.'),
  ('mission-ai-machines-that-see-09', 2, 'elena', 'Early convolutional layers tend to learn simple things -- edges, textures. Later layers, built on top of the earlier feature maps, learn more complex shapes assembled out of those simple ones.'),
  ('mission-ai-machines-that-see-09', 3, 'elena', 'By the time the signal reaches the fully connected layers at the end, it is no longer a grid of pixels at all. It is a compact set of numbers describing what was found, ready to be turned into an actual decision.'),

  ('mission-ai-machines-that-see-10', 1, 'elena', 'The last layer of a classification CNN outputs one number per possible class, run through a function called softmax that turns them into probabilities adding up to 1.'),
  ('mission-ai-machines-that-see-10', 2, 'elena', 'For a reactor-housing frame, that might mean 0.94 probability damaged and 0.06 probability undamaged. The predicted class is whichever probability is highest, but the number itself, the confidence, is worth reading too.'),
  ('mission-ai-machines-that-see-10', 3, 'elena', 'A model that is right 90 percent of the time and always says so at 51 percent confidence is telling you something different than one that is right 90 percent of the time and says so at 99 percent. Confidence is not just decoration on top of the label.'),

  ('mission-ai-machines-that-see-11', 1, 'elena', 'Data augmentation creates modified copies of training images -- rotated, flipped, brightened, cropped, slightly noised -- and trains on those too, without needing a single new real photograph.'),
  ('mission-ai-machines-that-see-11', 2, 'elena', 'It works because it forces the model to learn the actual pattern, a fracture, a seam, a hazard, rather than memorizing one exact camera angle and one exact lighting condition it happened to see in training.'),
  ('mission-ai-machines-that-see-11', 3, 'elena', 'Every augmentation should mirror something that genuinely varies in the real cooling-camera feeds -- angle, brightness, glare, partial obstruction. Augmenting for variation that never actually happens just adds noise for nothing.'),

  ('mission-ai-machines-that-see-12', 1, 'maya', 'Every classifier in this Act has been practice. This one is not. Reactor-housing cameras covered this month''s maintenance sweep, and every frame in it was cleared by a human reviewer.'),
  ('mission-ai-machines-that-see-12', 2, 'elena', 'I ran the CNN classifier we built all Act on that same feed anyway -- convolution, kernels, feature maps, padding, stride, pooling, augmentation, all of it. It flagged one frame the human sweep called clean: a hairline fracture in a reactor housing panel.'),
  ('mission-ai-machines-that-see-12', 3, 'byte', 'That is exactly the kind of damage a busy human reviewer skims right past -- faint, low-contrast, buried in one frame out of hundreds checked in a single shift. The model did not skim anything.'),
  ('mission-ai-machines-that-see-12', 4, 'elena', 'Reactor housings run hottest near Echo''s highest-draw racks. That does not prove Echo caused this fracture, Cipher Division cannot show that link yet, but it is exactly the kind of physical stress worth watching now that a model can actually see it.'),
  ('mission-ai-machines-that-see-12', 5, 'maya', 'Do not take the model''s word for it, and do not take the reviewer''s word for it either. Read the activation evidence, confirm this model actually earned its accuracy, and explain what the sweep missed, before anyone treats this as real.'),
  ('mission-ai-machines-that-see-12', 6, 'maya', 'One classifier answering yes or no is not enough for a facility this size. Cipher Labs needs to know exactly where every problem is, not just whether one exists somewhere in the frame.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-machines-that-see-01-o1', 'mission-ai-machines-that-see-01', 1, 'Read the tensor', 'Identify the correct shape of a digital image once it is represented as a tensor.'),
  ('mission-ai-machines-that-see-01-o2', 'mission-ai-machines-that-see-01', 2, 'Confirm the shift in data', 'Find the evidence that this cooling-camera problem genuinely requires a new kind of model, not just a new dataset.'),

  ('mission-ai-machines-that-see-02-o1', 'mission-ai-machines-that-see-02', 1, 'Count the channels', 'Determine how many channels a given camera frame actually has.'),
  ('mission-ai-machines-that-see-02-o2', 'mission-ai-machines-that-see-02', 2, 'Match channel to meaning', 'Sort individual color values into the channel structure they actually belong to.'),

  ('mission-ai-machines-that-see-03-o1', 'mission-ai-machines-that-see-03', 1, 'Order the operation', 'Put the steps of a single convolution pass in the order they actually happen.'),

  ('mission-ai-machines-that-see-04-o1', 'mission-ai-machines-that-see-04', 1, 'Define the kernel', 'Choose the accurate definition of a convolutional kernel.'),
  ('mission-ai-machines-that-see-04-o2', 'mission-ai-machines-that-see-04', 2, 'Match kernel to pattern', 'Match a kernel''s weight pattern to the effect it produces.'),

  ('mission-ai-machines-that-see-05-o1', 'mission-ai-machines-that-see-05', 1, 'Define the feature map', 'Choose the accurate definition of a feature map.'),
  ('mission-ai-machines-that-see-05-o2', 'mission-ai-machines-that-see-05', 2, 'Locate the activation', 'Find the evidence showing a kernel genuinely detecting a structure in the frame.'),

  ('mission-ai-machines-that-see-06-o1', 'mission-ai-machines-that-see-06', 1, 'Explain the purpose', 'State why a CNN commonly uses padding around its input.'),
  ('mission-ai-machines-that-see-06-o2', 'mission-ai-machines-that-see-06', 2, 'Match padding to effect', 'Match valid and same padding to what each actually does to the output size.'),

  ('mission-ai-machines-that-see-07-o1', 'mission-ai-machines-that-see-07', 1, 'Explain the effect', 'State what increasing stride does to a convolutional layer''s output.'),
  ('mission-ai-machines-that-see-07-o2', 'mission-ai-machines-that-see-07', 2, 'Fix the size calculation', 'Find the bug in a helper function meant to compute convolutional output size.'),

  ('mission-ai-machines-that-see-08-o1', 'mission-ai-machines-that-see-08', 1, 'Explain the purpose', 'State the main purpose of a pooling layer in a CNN.'),
  ('mission-ai-machines-that-see-08-o2', 'mission-ai-machines-that-see-08', 2, 'Match pooling to behavior', 'Match max pooling and average pooling to what each actually keeps.'),

  ('mission-ai-machines-that-see-09-o1', 'mission-ai-machines-that-see-09', 1, 'Order the architecture', 'Put the stages of a simple CNN in order from raw input to final output.'),

  ('mission-ai-machines-that-see-10-o1', 'mission-ai-machines-that-see-10', 1, 'Read the output', 'Interpret a softmax output as a predicted class and a confidence value.'),
  ('mission-ai-machines-that-see-10-o2', 'mission-ai-machines-that-see-10', 2, 'Judge the confidence', 'Find the evidence showing a prediction that genuinely deserves to be treated as reliable.'),

  ('mission-ai-machines-that-see-11-o1', 'mission-ai-machines-that-see-11', 1, 'Explain the purpose', 'State why data augmentation generally helps a CNN generalize better.'),
  ('mission-ai-machines-that-see-11-o2', 'mission-ai-machines-that-see-11', 2, 'Match augmentation to defense', 'Match each augmentation technique to the real-world variation it defends against.'),

  ('mission-ai-machines-that-see-12-o1', 'mission-ai-machines-that-see-12', 1, 'Read the activation evidence', 'Determine whether the CNN''s internal feature-map activity genuinely points at a real structural flaw, not noise.'),
  ('mission-ai-machines-that-see-12-o2', 'mission-ai-machines-that-see-12', 2, 'Confirm the model earned it', 'Judge whether the classifier''s flag reflects genuine, honestly-validated performance rather than a lucky guess.'),
  ('mission-ai-machines-that-see-12-o3', 'mission-ai-machines-that-see-12', 3, 'Explain what the human review missed', 'Determine why this month''s manual inspection sweep cleared a frame the CNN flagged.'),
  ('mission-ai-machines-that-see-12-o4', 'mission-ai-machines-that-see-12', 4, 'Confirm the reactor finding', 'Having read the activation evidence, confirmed the model was properly validated, and explained what the manual sweep missed, state Cipher Division''s finding on the flagged reactor-housing frame.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-machines-that-see-01-o1-c1', 'mission-ai-machines-that-see-01-o1', 1, 'multiple_choice', 'Identify the correct tensor shape of a color camera frame.', '{"question":"A color security-camera frame that is 480 pixels tall and 640 pixels wide, stored as height, width, channels, has tensor shape...","options":[{"id":"a","text":"480 x 640"},{"id":"b","text":"480 x 640 x 3"},{"id":"c","text":"3 x 3 x 3"},{"id":"d","text":"640 only"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-01-o2-c1', 'mission-ai-machines-that-see-01-o2', 1, 'investigation', 'Find the evidence that this data genuinely requires a new kind of model.', '{"evidence":[{"id":"e1","label":"Facilities note","detail":"Cooling-camera frames are 2D grids of raw RGB pixel values, with no rows, columns of named fields, or labels attached the way spreadsheet data has"},{"id":"e2","label":"Ops dashboard","detail":"Cipher Labs power draw has been elevated since Echo first activated in Act 1"},{"id":"e3","label":"Storage log","detail":"Camera frames are stored as JPEG files on the same servers as every other Cipher Division dataset"}],"question":"Which evidence actually proves this data needs a new kind of model, not just new storage?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-machines-that-see-02-o1-c1', 'mission-ai-machines-that-see-02-o1', 1, 'multiple_choice', 'Count the channels of a thermal-only frame.', '{"question":"A thermal-only camera frame, with one heat-intensity value per pixel, has how many channels?","options":[{"id":"a","text":"0"},{"id":"b","text":"1"},{"id":"c","text":"3"},{"id":"d","text":"However many pixels wide the image is"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-02-o2-c1', 'mission-ai-machines-that-see-02-o2', 1, 'drag_and_drop', 'Sort each pixel value into the channel structure it belongs to.', '{"items":[{"id":"i1","text":"Red channel value at a pixel"},{"id":"i2","text":"Green channel value at a pixel"},{"id":"i3","text":"Blue channel value at a pixel"},{"id":"i4","text":"Single grayscale or thermal channel value at a pixel"}],"targets":[{"id":"t1","label":"Part of a 3-channel RGB grid"},{"id":"t2","label":"The entire channel dimension of a 1-channel grid"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t1","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-machines-that-see-03-o1-c1', 'mission-ai-machines-that-see-03-o1', 1, 'interactive_diagram', 'Order the steps of a single convolution pass.', '{"diagramId":"convolution-steps","hotspots":[{"id":"place","label":"Place the kernel over the top-left region of the input","explanation":"Convolution always starts anchored at a fixed starting position."},{"id":"multiply","label":"Multiply each value under the kernel by the kernel''s matching weight","explanation":"Every pixel covered by the window gets paired with one learned weight."},{"id":"sum","label":"Sum all the multiplied values into a single number","explanation":"That single sum becomes one value in the output grid."},{"id":"slide","label":"Slide the kernel to the next position by the stride","explanation":"The window moves across the image a fixed number of pixels at a time."},{"id":"repeat","label":"Repeat until the kernel has covered the entire input","explanation":"The finished output grid is complete once every position has been visited."}],"task":"Order the steps of a single convolution pass from first to last."}'::jsonb, '{"correctOrderIds":["place","multiply","sum","slide","repeat"]}'::jsonb),

  ('mission-ai-machines-that-see-04-o1-c1', 'mission-ai-machines-that-see-04-o1', 1, 'multiple_choice', 'Choose the accurate definition of a convolutional kernel.', '{"question":"A convolutional kernel is best described as...","options":[{"id":"a","text":"A fixed image-processing filter that never changes"},{"id":"b","text":"A small matrix of weights, learned during training, that convolution slides across the input to detect a pattern"},{"id":"c","text":"The entire trained model"},{"id":"d","text":"A single pixel value"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-04-o2-c1', 'mission-ai-machines-that-see-04-o2', 1, 'drag_and_drop', 'Match each kernel weight pattern to the effect it produces.', '{"items":[{"id":"i1","text":"A kernel whose weights are high on one side and low on the opposite side"},{"id":"i2","text":"A kernel whose weights are highest in the center and taper outward evenly"},{"id":"i3","text":"A kernel whose weights emphasize the center pixel strongly against its neighbors"}],"targets":[{"id":"t1","label":"Edge detector"},{"id":"t2","label":"Blur / smoothing"},{"id":"t3","label":"Sharpen"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-machines-that-see-05-o1-c1', 'mission-ai-machines-that-see-05-o1', 1, 'multiple_choice', 'Choose the accurate definition of a feature map.', '{"question":"A feature map is best described as...","options":[{"id":"a","text":"The raw, unprocessed input image"},{"id":"b","text":"The output of one kernel applied across the entire input, showing where its pattern is present"},{"id":"c","text":"A label attached by a human reviewer"},{"id":"d","text":"The final classification decision"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-05-o2-c1', 'mission-ai-machines-that-see-05-o2', 1, 'investigation', 'Find the evidence of a kernel genuinely detecting a structure.', '{"evidence":[{"id":"e1","label":"Feature map A","detail":"Edge-detecting kernel produces near-zero values everywhere except a bright, continuous line tracing the vent''s metal seam"},{"id":"e2","label":"Feature map B","detail":"Blur kernel produces uniformly moderate values across the whole frame with no distinct region"},{"id":"e3","label":"Raw frame metadata","detail":"Frame was captured at 14:02 by camera unit 7"}],"question":"Which evidence shows a kernel actually detecting a specific structure in the frame, rather than reacting to the whole image equally or being irrelevant to detection?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-machines-that-see-06-o1-c1', 'mission-ai-machines-that-see-06-o1', 1, 'multiple_choice', 'State why a CNN commonly uses padding.', '{"question":"Why does a CNN commonly use padding around the input before convolving?","options":[{"id":"a","text":"To make the image look nicer"},{"id":"b","text":"To prevent the output size from shrinking with every convolutional layer and to preserve information at the borders"},{"id":"c","text":"To remove color channels"},{"id":"d","text":"To speed up training with no other effect"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-06-o2-c1', 'mission-ai-machines-that-see-06-o2', 1, 'drag_and_drop', 'Match each padding style to its effect on output size.', '{"items":[{"id":"i1","text":"No extra border pixels are added; the kernel only slides over positions fully inside the original input"},{"id":"i2","text":"Enough border pixels, usually zeros, are added so the output stays the same height and width as the input"}],"targets":[{"id":"t1","label":"Valid padding"},{"id":"t2","label":"Same padding"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2"}}'::jsonb),

  ('mission-ai-machines-that-see-07-o1-c1', 'mission-ai-machines-that-see-07-o1', 1, 'multiple_choice', 'State the effect of increasing stride.', '{"question":"Increasing the stride of a convolutional layer, with kernel size and padding held fixed, mainly does what to the output?","options":[{"id":"a","text":"Increases the output size and detail"},{"id":"b","text":"Decreases the output size, checking fewer positions and losing some spatial detail"},{"id":"c","text":"Has no effect on output size"},{"id":"d","text":"Changes the number of channels only"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-07-o2-c1', 'mission-ai-machines-that-see-07-o2', 1, 'code_debugging', 'Find the line that does not match the standard output-size formula.', '{"language":"python","code":"def conv_output_size(input_size, kernel_size, padding, stride):\n    # Standard formula: floor((input_size - kernel_size + 2 * padding) / stride) + 1\n    numerator = input_size - kernel_size + padding\n    return numerator // stride + 1\n\nresult = conv_output_size(input_size=32, kernel_size=3, padding=1, stride=1)\nprint(result)","question":"This helper is supposed to compute a convolutional layer''s output size, but it does not match the standard formula in the comment. Which line has the bug?"}'::jsonb, '{"requiredLineIds":["    numerator = input_size - kernel_size + padding"]}'::jsonb),

  ('mission-ai-machines-that-see-08-o1-c1', 'mission-ai-machines-that-see-08-o1', 1, 'multiple_choice', 'State the main purpose of a pooling layer.', '{"question":"What is the main purpose of a pooling layer in a CNN?","options":[{"id":"a","text":"To learn new weighted patterns the way convolution does"},{"id":"b","text":"To shrink feature maps and reduce sensitivity to a pattern''s exact pixel position, with no learned weights"},{"id":"c","text":"To add color channels"},{"id":"d","text":"To increase the image resolution"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-08-o2-c1', 'mission-ai-machines-that-see-08-o2', 1, 'drag_and_drop', 'Match each pooling type to what it actually keeps.', '{"items":[{"id":"i1","text":"Keeps the strongest activation value in each region, discarding the rest"},{"id":"i2","text":"Keeps the mean of all activation values in each region, smoothing the result"}],"targets":[{"id":"t1","label":"Max pooling"},{"id":"t2","label":"Average pooling"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2"}}'::jsonb),

  ('mission-ai-machines-that-see-09-o1-c1', 'mission-ai-machines-that-see-09-o1', 1, 'interactive_diagram', 'Order the stages of a simple CNN from input to output.', '{"diagramId":"cnn-architecture","hotspots":[{"id":"input","label":"Input image tensor","explanation":"The raw pixel grid, height by width by channels, enters the network unchanged."},{"id":"conv1","label":"Convolutional layer extracts a first set of feature maps","explanation":"Early kernels typically learn simple patterns like edges and textures."},{"id":"pool1","label":"Pooling layer shrinks the feature maps","explanation":"Downsamples the feature maps and reduces sensitivity to exact position."},{"id":"conv2","label":"A second convolutional layer builds more complex features from the pooled maps","explanation":"Deeper layers combine simple patterns into more complex shapes."},{"id":"flatten","label":"Flatten the final feature maps into a single vector","explanation":"Turns the remaining grid of numbers into a plain list a fully connected layer can use."},{"id":"fc","label":"Fully connected layer produces the final output","explanation":"Ordinary dense layers turn the flattened features into a decision."}],"task":"Order the stages of a simple CNN from raw input to final output."}'::jsonb, '{"correctOrderIds":["input","conv1","pool1","conv2","flatten","fc"]}'::jsonb),

  ('mission-ai-machines-that-see-10-o1-c1', 'mission-ai-machines-that-see-10-o1', 1, 'multiple_choice', 'Interpret a softmax output.', '{"question":"A CNN''s final softmax layer outputs [0.05, 0.92, 0.03] over three classes: undamaged, damaged, unclear. What is the model''s prediction and confidence?","options":[{"id":"a","text":"Undamaged, 5 percent confidence"},{"id":"b","text":"Damaged, 92 percent confidence"},{"id":"c","text":"Unclear, 3 percent confidence"},{"id":"d","text":"The output cannot be interpreted without more information"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-10-o2-c1', 'mission-ai-machines-that-see-10-o2', 1, 'investigation', 'Find the evidence of a prediction that genuinely deserves trust.', '{"evidence":[{"id":"e1","label":"Prediction log, frame A","detail":"Model predicts damaged at 97 percent confidence, and a manual re-inspection confirms a visible fracture"},{"id":"e2","label":"Prediction log, frame B","detail":"Model predicts damaged at 52 percent confidence on a frame that is mostly obscured by steam"},{"id":"e3","label":"Model version","detail":"Model was last retrained three weeks ago"}],"question":"Which evidence shows a prediction that genuinely deserves being treated as reliable, not just technically the highest-probability class?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-machines-that-see-11-o1-c1', 'mission-ai-machines-that-see-11-o1', 1, 'multiple_choice', 'State why augmentation helps generalization.', '{"question":"Why does training a CNN with data augmentation generally help it generalize better?","options":[{"id":"a","text":"It adds entirely new real-world photographs to the dataset"},{"id":"b","text":"It exposes the model to realistic variations of existing images, discouraging it from memorizing one exact version of each"},{"id":"c","text":"It removes the need for a validation set"},{"id":"d","text":"It always increases training accuracy, which is the actual goal"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-machines-that-see-11-o2-c1', 'mission-ai-machines-that-see-11-o2', 1, 'drag_and_drop', 'Match each augmentation technique to what it defends against.', '{"items":[{"id":"i1","text":"Randomly rotating training images by a small angle"},{"id":"i2","text":"Randomly adjusting brightness and contrast"},{"id":"i3","text":"Randomly flipping images horizontally"},{"id":"i4","text":"Randomly occluding a small patch of the image"}],"targets":[{"id":"t1","label":"Camera angle varying slightly between installations"},{"id":"t2","label":"Lighting conditions changing across time of day"},{"id":"t3","label":"Mirrored camera orientation"},{"id":"t4","label":"Partial obstruction, like steam or a passing object"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),

  ('mission-ai-machines-that-see-12-o1-c1', 'mission-ai-machines-that-see-12-o1', 1, 'investigation', 'Judge whether the model''s internal activity points at a real flaw.', '{"evidence":[{"id":"e1","label":"Feature-map activation","detail":"A late convolutional layer shows a sharp, localized activation spike tracing a thin hairline line across the reactor housing, in a region no other frame in the dataset activates"},{"id":"e2","label":"Raw frame","detail":"To the eye, the same region looks like a faint shadow blending into the housing''s texture"},{"id":"e3","label":"Camera metadata","detail":"Frame was captured by camera unit 12 at standard resolution"}],"question":"Which evidence shows the model''s internal activity is actually tracking a real structural feature, not just reacting to noise?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-machines-that-see-12-o2-c1', 'mission-ai-machines-that-see-12-o2', 1, 'investigation', 'Judge whether the model earned this specific flag.', '{"evidence":[{"id":"e1","label":"Training log","detail":"Model was trained with augmentation covering realistic angle, lighting and partial-obstruction variation, and evaluated on a held-out test set never used during training or tuning"},{"id":"e2","label":"Held-out test performance","detail":"On the held-out test set, the model correctly identifies 96 percent of known past reactor-housing defects, including several confirmed only after the fact by physical inspection"},{"id":"e3","label":"Deployment note","detail":"The model runs on the same servers as the cooling-camera storage system"}],"question":"Which evidence shows this specific flag deserves to be trusted, not just that the model exists?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-machines-that-see-12-o3-c1', 'mission-ai-machines-that-see-12-o3', 1, 'investigation', 'Determine why the manual sweep missed the fracture.', '{"evidence":[{"id":"e1","label":"Sweep log","detail":"This month''s manual sweep covered over 400 camera frames in a single shift, roughly nine seconds of review per frame"},{"id":"e2","label":"Reviewer note","detail":"Frame was marked clean, with nothing unusual noted on a quick visual pass"},{"id":"e3","label":"Facilities schedule","detail":"The reactor housing was last serviced six months ago, on schedule"}],"question":"Which evidence best explains why a real fracture went unnoticed by the manual sweep?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-machines-that-see-12-o4-c1', 'mission-ai-machines-that-see-12-o4', 1, 'boss_encounter', 'Having judged the activation, the validation and the human miss, state the finding on the flagged frame.', '{"stages":[{"objectiveRef":"mission-ai-machines-that-see-12-o1","label":"Read the activation evidence"},{"objectiveRef":"mission-ai-machines-that-see-12-o2","label":"Confirm the model earned it"},{"objectiveRef":"mission-ai-machines-that-see-12-o3","label":"Explain what the human review missed"}],"task":"State the finding in one sentence: a properly trained CNN spotted a genuine hairline fracture in the reactor housing camera feed that this month''s entire manual inspection missed, exactly the kind of damage a busy human reviewer skims past in a fast visual check, plausibly related to the same power and thermal stress Echo has been causing since Act 1, though Cipher Division cannot yet prove a direct causal link."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-machines-that-see-12-o1","mission-ai-machines-that-see-12-o2","mission-ai-machines-that-see-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-machines-that-see-01-o1-c1', 'orientation', 'Count the dimensions a color image actually needs: how tall, how wide, and how many color channels.', 10, 1),
  ('mission-ai-machines-that-see-01-o1-c1', 'concept', 'Height and width describe the grid of pixels; channels describe how many numbers sit at each pixel position.', 20, 2),
  ('mission-ai-machines-that-see-01-o1-c1', 'solution', '480 x 640 x 3 -- height, width, and three channels for red, green and blue.', 30, 3),
  ('mission-ai-machines-that-see-01-o2-c1', 'orientation', 'File format and storage location do not change what kind of data something structurally is.', 10, 1),
  ('mission-ai-machines-that-see-01-o2-c1', 'solution', 'e1: raw pixel grids with no named fields or labels are structurally different from tabular data -- that is what actually calls for a new class of model.', 20, 2),

  ('mission-ai-machines-that-see-02-o1-c1', 'orientation', 'Thermal cameras record one physical quantity per pixel: heat.', 10, 1),
  ('mission-ai-machines-that-see-02-o1-c1', 'solution', 'One channel -- a single intensity grid, no separate red, green or blue.', 20, 2),
  ('mission-ai-machines-that-see-02-o2-c1', 'orientation', 'RGB channels are three separate grids that together make one color image; a grayscale or thermal channel stands alone.', 10, 1),
  ('mission-ai-machines-that-see-02-o2-c1', 'concept', 'Ask how many full grids exist at all for each case, then which grids belong to the same image.', 20, 2),
  ('mission-ai-machines-that-see-02-o2-c1', 'solution', 'Red, green and blue are each one of three grids stacked in an RGB image; a grayscale or thermal frame has just the one grid making up its whole channel dimension.', 30, 3),

  ('mission-ai-machines-that-see-03-o1-c1', 'orientation', 'Nothing can be summed before the kernel is actually positioned over pixels and multiplied against them.', 10, 1),
  ('mission-ai-machines-that-see-03-o1-c1', 'concept', 'One output value comes from one placement of the kernel: position, multiply, sum. Only after that does the window move.', 20, 2),
  ('mission-ai-machines-that-see-03-o1-c1', 'solution', 'Place the kernel, multiply against the weights, sum into one value, slide to the next position, repeat until the whole input is covered.', 30, 3),

  ('mission-ai-machines-that-see-04-o1-c1', 'orientation', 'A kernel is not the whole model, and it is not fixed by a person the way classical filters are.', 10, 1),
  ('mission-ai-machines-that-see-04-o1-c1', 'solution', 'A small matrix of learned weights that convolution slides across the input to detect one specific pattern.', 20, 2),
  ('mission-ai-machines-that-see-04-o2-c1', 'orientation', 'Think about what each weight pattern would respond most strongly to.', 10, 1),
  ('mission-ai-machines-that-see-04-o2-c1', 'concept', 'A steep change from one side of the kernel to the other responds to a boundary; an even spread responds to a smooth region; a strong center against weak neighbors emphasizes contrast at that one point.', 20, 2),
  ('mission-ai-machines-that-see-04-o2-c1', 'solution', 'High-on-one-side, low-on-the-other detects edges; an even, tapering spread blurs or smooths; a strong center against weak neighbors sharpens.', 30, 3),

  ('mission-ai-machines-that-see-05-o1-c1', 'orientation', 'A feature map is downstream of the input, not the input itself, and it comes before any final decision.', 10, 1),
  ('mission-ai-machines-that-see-05-o1-c1', 'solution', 'The feature map is what one kernel produces once it has been convolved across the whole input.', 20, 2),
  ('mission-ai-machines-that-see-05-o2-c1', 'orientation', 'A kernel that is actually detecting something specific should look different at the structure than it does everywhere else.', 10, 1),
  ('mission-ai-machines-that-see-05-o2-c1', 'concept', 'Uniform activation everywhere is a sign the kernel is not distinguishing anything in that particular frame; localized, sharp activation at one structure is.', 20, 2),
  ('mission-ai-machines-that-see-05-o2-c1', 'solution', 'e1: a bright, continuous activation tracing exactly the vent seam is a kernel picking out a real structure, not reacting evenly to the whole frame.', 30, 3),

  ('mission-ai-machines-that-see-06-o1-c1', 'orientation', 'Without padding, the outer pixels never get to sit at the center of the kernel.', 10, 1),
  ('mission-ai-machines-that-see-06-o1-c1', 'solution', 'Padding keeps the output from shrinking every layer and stops the model from effectively ignoring border pixels.', 20, 2),
  ('mission-ai-machines-that-see-06-o2-c1', 'orientation', 'One option adds nothing at the border; the other adds exactly enough to keep the output size unchanged.', 10, 1),
  ('mission-ai-machines-that-see-06-o2-c1', 'solution', 'Valid padding: no border added, output shrinks. Same padding: border added so output size matches input size.', 20, 2),

  ('mission-ai-machines-that-see-07-o1-c1', 'orientation', 'A larger stride means the kernel visits fewer positions across the same input.', 10, 1),
  ('mission-ai-machines-that-see-07-o1-c1', 'solution', 'Fewer positions visited means a smaller output grid and some loss of fine spatial detail, in exchange for less compute.', 20, 2),
  ('mission-ai-machines-that-see-07-o2-c1', 'orientation', 'Compare the code line by line against the formula written in the comment directly above it.', 10, 1),
  ('mission-ai-machines-that-see-07-o2-c1', 'concept', 'The comment says padding is doubled in the formula. Check whether the code actually multiplies it by two.', 20, 2),
  ('mission-ai-machines-that-see-07-o2-c1', 'solution', 'The numerator line adds padding instead of 2 * padding, so it does not match the standard formula and will undercount the output size whenever padding is greater than zero.', 30, 3),

  ('mission-ai-machines-that-see-08-o1-c1', 'orientation', 'Pooling has no learned weights of its own -- it just summarizes what convolution already produced.', 10, 1),
  ('mission-ai-machines-that-see-08-o1-c1', 'solution', 'Pooling reduces feature map size and makes the model a bit more tolerant of a pattern''s exact position, with no weights to learn.', 20, 2),
  ('mission-ai-machines-that-see-08-o2-c1', 'orientation', 'One operation preserves the single loudest signal in a region; the other blends everything in the region together.', 10, 1),
  ('mission-ai-machines-that-see-08-o2-c1', 'solution', 'Max pooling keeps the strongest value per region; average pooling keeps the mean, producing a smoother result.', 20, 2),

  ('mission-ai-machines-that-see-09-o1-c1', 'orientation', 'Nothing can be flattened until the convolutional and pooling stages have already produced their final feature maps.', 10, 1),
  ('mission-ai-machines-that-see-09-o1-c1', 'concept', 'Convolution and pooling typically alternate, extracting then shrinking, before the data is ever reshaped into a flat vector.', 20, 2),
  ('mission-ai-machines-that-see-09-o1-c1', 'solution', 'Input image, convolutional layer, pooling layer, a second convolutional layer, flatten, fully connected layer.', 30, 3),

  ('mission-ai-machines-that-see-10-o1-c1', 'orientation', 'Softmax outputs are probabilities across the classes -- read them as such, in the order the classes are listed.', 10, 1),
  ('mission-ai-machines-that-see-10-o1-c1', 'solution', '0.92 is the highest probability, corresponding to damaged, so the model''s prediction is damaged at 92 percent confidence.', 20, 2),
  ('mission-ai-machines-that-see-10-o2-c1', 'orientation', 'A high-probability prediction on a clear frame is a stronger signal than a near-toss-up prediction on an obscured one.', 10, 1),
  ('mission-ai-machines-that-see-10-o2-c1', 'concept', 'Confidence near 50 percent on a two-way call is barely more informative than a coin flip, even if it is technically the higher number.', 20, 2),
  ('mission-ai-machines-that-see-10-o2-c1', 'solution', 'e1: 97 percent confidence, confirmed by manual re-inspection, is a genuinely reliable prediction, unlike frame B''s near-toss-up 52 percent on an obscured frame.', 30, 3),

  ('mission-ai-machines-that-see-11-o1-c1', 'orientation', 'Augmentation manufactures variation from existing images; it does not add new real photographs.', 10, 1),
  ('mission-ai-machines-that-see-11-o1-c1', 'solution', 'Realistic variations discourage the model from memorizing one exact version of each training image, which is exactly what helps it generalize.', 20, 2),
  ('mission-ai-machines-that-see-11-o2-c1', 'orientation', 'Match each transformation to the real-world condition it most directly imitates.', 10, 1),
  ('mission-ai-machines-that-see-11-o2-c1', 'concept', 'Rotation imitates angle differences, brightness and contrast imitate lighting changes, flipping imitates mirrored orientation, and occlusion imitates something physically blocking part of the view.', 20, 2),
  ('mission-ai-machines-that-see-11-o2-c1', 'solution', 'Rotation defends against angle variation, brightness or contrast against lighting changes, horizontal flip against mirrored orientation, occlusion against partial obstruction like steam.', 30, 3),

  ('mission-ai-machines-that-see-12-o1-c1', 'orientation', 'A faint shadow in the raw frame and a sharp, localized activation spike in the feature map are not necessarily describing the same thing. Check whether the model''s activation is isolated to real structure.', 10, 1),
  ('mission-ai-machines-that-see-12-o1-c1', 'concept', 'Noise tends to activate broadly or inconsistently across frames; a genuine structural feature produces a localized, repeatable activation exactly where that structure sits.', 20, 2),
  ('mission-ai-machines-that-see-12-o1-c1', 'solution', 'e1: a sharp, localized activation tracing a hairline line, in a region no other frame in the dataset activates the same way, is the model tracking a real structural feature, not noise.', 30, 3),
  ('mission-ai-machines-that-see-12-o2-c1', 'orientation', 'The model existing and being accurate on average are two different claims. Ask what was actually measured on data it never trained or tuned on.', 10, 1),
  ('mission-ai-machines-that-see-12-o2-c1', 'solution', 'e2: 96 percent accuracy on a held-out test set, including defects only confirmed afterward by physical inspection, is the honest evidence this specific flag deserves to be trusted.', 20, 2),
  ('mission-ai-machines-that-see-12-o3-c1', 'orientation', 'Nine seconds a frame is not a lot of time to catch something faint.', 10, 1),
  ('mission-ai-machines-that-see-12-o3-c1', 'concept', 'A fast, high-volume manual pass is exactly the condition under which a low-contrast, easy-to-miss defect slips through, regardless of how careful the reviewer generally is.', 20, 2),
  ('mission-ai-machines-that-see-12-o3-c1', 'solution', 'e1: over 400 frames reviewed in a single shift, roughly nine seconds per frame, is more than enough to explain a faint hairline fracture getting missed on a quick visual pass.', 30, 3),
  ('mission-ai-machines-that-see-12-o4-c1', 'orientation', 'Weigh all three findings together: what the activation showed, whether the model earned trust, and why the human pass missed it.', 15, 1),
  ('mission-ai-machines-that-see-12-o4-c1', 'solution', 'A properly trained CNN spotted a genuine hairline fracture in the reactor housing feed that the entire manual sweep missed, exactly the kind of damage a tired reviewer skims past on a fast pass. It plausibly ties to the same power and thermal stress Echo has been causing since Act 1, though Cipher Division cannot yet prove that link directly.', 25, 2);
