-- Backend Engineering ("The Fracture") Act 10 -- "SQL Mastery" content.
-- Last Act currently authored (of an eventual 32). 1 campaign, 2 operations,
-- 12 missions.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be10', 'world-be-10', 'sql-mastery', '10A - SQL Mastery', 'Leadership wants one report answering how far the pattern actually reaches. No existing query can answer it -- yet.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be10-1', 'campaign-be10', 'asking-bigger-questions', 'Asking Bigger Questions', 'Aggregation, GROUP BY, HAVING, subqueries, CTEs and window function concepts.', 1),
  ('operation-be10-2', 'campaign-be10', 'shaping-and-maintaining-data', 'Shaping and Maintaining Data', 'Views, normalization, denormalization, migrations, ORMs -- then the report itself.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be10-01', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'aggregation', 'Aggregation', 'A single row answers "what is this." Aggregation answers "how many, how much, on average" across a whole group of rows at once.', 'intermediate', ARRAY['forge'], null, null, '{"type":"simulation","simulationId":"aggregation-sim"}'::jsonb, '{"xp":160,"credits":28}'::jsonb, false, 1),
  ('mission-be10-02', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'group-by', 'GROUP BY', 'COUNT(*) alone answers one number for the whole table. GROUP BY splits the rows into buckets first, then aggregates within each bucket separately.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be10-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"group-by-sim"}'::jsonb, '{"xp":165,"credits":28}'::jsonb, false, 2),
  ('mission-be10-03', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'having', 'HAVING', 'WHERE filters rows before grouping. HAVING filters groups after aggregating -- try to filter on COUNT(*) with WHERE and Postgres refuses; the count doesn''t exist yet at that point.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be10-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"having-sim"}'::jsonb, '{"xp":165,"credits":30}'::jsonb, false, 3),
  ('mission-be10-04', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'subqueries', 'Subqueries', 'Sometimes a question depends on the answer to a smaller question first. A subquery is a SELECT nested inside another query, run first, then used by the outer one.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be10-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"subqueries-sim"}'::jsonb, '{"xp":170,"credits":30}'::jsonb, false, 4),
  ('mission-be10-05', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'ctes', 'CTEs', 'A CTE -- WITH name AS (...) -- names a subquery so you can reference it, sometimes more than once, without nesting parentheses inside parentheses.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be10-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"ctes-sim"}'::jsonb, '{"xp":175,"credits":32}'::jsonb, false, 5),
  ('mission-be10-06', 'world-be-10', 'campaign-be10', 'operation-be10-1', 'window-functions-concepts', 'Window Functions Concepts', 'Aggregation collapses rows into one. A window function computes something across a group of rows -- a running total, a rank -- without collapsing them.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be10-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"window-functions-sim"}'::jsonb, '{"xp":175,"credits":32}'::jsonb, false, 6),
  ('mission-be10-07', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'views', 'Views', 'A view is a saved query that behaves like a table when you SELECT from it -- useful for hiding a complicated join behind a simple name.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be10-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"views-sim"}'::jsonb, '{"xp":180,"credits":32}'::jsonb, false, 7),
  ('mission-be10-08', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'normalization', 'Normalization', 'Normalization means each fact lives in exactly one place. Store the same value in two tables and the day they disagree, nobody can tell you which one is true.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be10-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"normalization-sim"}'::jsonb, '{"xp":185,"credits":32}'::jsonb, false, 8),
  ('mission-be10-09', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'denormalization', 'Denormalization', 'Normalization isn''t free. Sometimes you deliberately duplicate a value to make one specific read fast, and accept the sync cost on purpose.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be10-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"denormalization-sim"}'::jsonb, '{"xp":185,"credits":35}'::jsonb, false, 9),
  ('mission-be10-10', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'database-migrations', 'Database Migrations', 'A migration is a versioned, repeatable change to the schema, applied in order, on every environment, so production and the schema in your head never quietly diverge.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be10-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"migrations-sim"}'::jsonb, '{"xp":190,"credits":35}'::jsonb, false, 10),
  ('mission-be10-11', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'orms-and-query-builders', 'ORMs and Query Builders', 'An ORM maps rows to objects and writes SQL for you. Both ORMs and query builders exist to keep you from hand-building SQL strings out of user input.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be10-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"orm-query-builder-sim"}'::jsonb, '{"xp":190,"credits":35}'::jsonb, false, 11),
  ('mission-be10-12', 'world-be-10', 'campaign-be10', 'operation-be10-2', 'the-impossible-report', 'The Impossible Report', 'One report, across every system that could contain the pattern. Everything this Act taught, at once -- and an answer nobody was ready for.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be10-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"impossible-report-boss-sim"}'::jsonb, '{"xp":450,"credits":100,"badgeIds":["impossible-report"],"skillXp":{"databases":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be10-01', 1, 'forge', 'A single row answers "what is this." Aggregation answers "how many, how much, on average" across a whole group of rows at once.'),
  ('mission-be10-02', 1, 'mira', 'COUNT(*) alone answers one number for the whole table. GROUP BY splits the rows into buckets first, then aggregates within each bucket separately.'),
  ('mission-be10-03', 1, 'forge', 'WHERE filters rows before grouping. HAVING filters groups after aggregating. Try to filter on COUNT(*) with WHERE and Postgres just refuses -- the count doesn''t exist yet at that point in the query.'),
  ('mission-be10-04', 1, 'mira', 'Sometimes a question depends on the answer to a smaller question first. A subquery is a SELECT nested inside another query -- run first, then used by the outer one.'),
  ('mission-be10-05', 1, 'forge', 'A CTE -- WITH name AS (...) -- names a subquery so you can reference it, sometimes more than once, without nesting parentheses inside parentheses inside parentheses. Same idea, more readable.'),
  ('mission-be10-06', 1, 'mira', 'Aggregation collapses rows into one. A window function computes something across a group of rows -- a running total, a rank -- without collapsing them. Every original row survives, with an extra computed column.'),
  ('mission-be10-07', 1, 'forge', 'A view is a saved query that behaves like a table when you SELECT from it. Same underlying data, computed fresh every time -- useful for hiding a complicated join behind a simple name.'),
  ('mission-be10-08', 1, 'mira', 'Normalization means each fact lives in exactly one place. Store a citizen''s district name in two different tables, and the day they disagree, nobody can tell you which one is true.'),
  ('mission-be10-09', 1, 'forge', 'Normalization isn''t free, though. A fully normalized schema means every report needs five joins. Sometimes you deliberately duplicate a value -- denormalize -- to make one specific read fast, and accept the sync cost on purpose.'),
  ('mission-be10-10', 1, 'mira', 'A migration is a versioned, repeatable change to the schema -- add a column, add a constraint -- applied in order, on every environment, so the schema in production and the schema in your head never quietly diverge.'),
  ('mission-be10-11', 1, 'forge', 'An ORM maps rows to objects and writes SQL for you. A query builder is a lighter version -- still SQL underneath, just composed with method calls instead of string concatenation. Both exist to keep you from hand-building SQL strings out of user input.'),
  ('mission-be10-12', 1, 'mira', 'Leadership wants one number: how many doubled-slash anomalies have ever touched a Forge-managed system, across every table that could contain one. Nobody''s been able to answer it.'),
  ('mission-be10-12', 2, 'forge', 'Because it''s never been one query. Dozens of tables, some normalized, some not, none of them designed to be searched this way. This is everything you''ve learned this Act, at once.'),
  ('mission-be10-12', 3, 'forge', '...I finished it. Every occurrence, every system, months apart, going back further than I expected.'),
  ('mission-be10-12', 4, 'mira', 'How far?'),
  ('mission-be10-12', 5, 'forge', 'Further than Arc I. This isn''t new. It''s not a bug -- it''s never once caused a crash. It''s been here the entire time we''ve been calling it noise.'),
  ('mission-be10-12', 6, 'mira', 'Then it''s not noise. Log everything Forge just found as a single tracked entity. We stop treating it as background static starting now -- and Arc III starts by finding out how far it actually reaches.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be10-01-o1', 'mission-be10-01', 1, 'Find the aggregate', 'Identify the function collapsing every matching row into a single count.'),
  ('mission-be10-02-o1', 'mission-be10-02', 1, 'Find the bucket', 'Identify what determines the buckets each COUNT(*) is computed within.'),
  ('mission-be10-03-o1', 'mission-be10-03', 1, 'Choose the right clause', 'Pick the clause that filters on an aggregate result.'),
  ('mission-be10-04-o1', 'mission-be10-04', 1, 'Find the subquery', 'Identify the part of the query evaluated first, on its own.'),
  ('mission-be10-05-o1', 'mission-be10-05', 1, 'Find the CTE definition', 'Identify the line that names the CTE the rest of the query references.'),
  ('mission-be10-06-o1', 'mission-be10-06', 1, 'Choose the right tool', 'Pick the tool that computes a per-group value without collapsing any rows.'),
  ('mission-be10-07-o1', 'mission-be10-07', 1, 'Find the view definition', 'Identify what makes this query reusable under a simple name.'),
  ('mission-be10-08-o1', 'mission-be10-08', 1, 'Spot the duplicated fact', 'Find the evidence showing the same fact stored in more than one place.'),
  ('mission-be10-09-o1', 'mission-be10-09', 1, 'Choose the tradeoff', 'Pick the reasonable denormalization strategy for a fast, frequent read.'),
  ('mission-be10-10-o1', 'mission-be10-10', 1, 'Find the risky migration', 'Identify which schema change would fail against existing bad data.'),
  ('mission-be10-11-o1', 'mission-be10-11', 1, 'Explain the real value', 'State why ORMs and query builders matter beyond convenience.'),
  ('mission-be10-12-o1', 'mission-be10-12', 1, 'Choose the right structure', 'Pick the correct query shape for combining differently-shaped tables into one report.'),
  ('mission-be10-12-o2', 'mission-be10-12', 2, 'Find the detection logic', 'Identify the line that actually searches for the anomaly pattern.'),
  ('mission-be10-12-o3', 'mission-be10-12', 3, 'Interpret the result', 'State what the report''s scope and timeline actually suggest.'),
  ('mission-be10-12-o4', 'mission-be10-12', 4, 'Close the report', 'State what the finished report actually proves, without speculating about who or what is responsible.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be10-01-o1-c1', 'mission-be10-01-o1', 1, 'code_debugging', 'Which line is the aggregate function collapsing every matching row into a single count?', '{"language":"sql","code":"SELECT COUNT(*) AS total_citizens\nFROM citizens\nWHERE is_active = true;","question":"Which line is the aggregate function collapsing every matching row into a single count?"}'::jsonb, '{"requiredLineIds":["SELECT COUNT(*) AS total_citizens"]}'::jsonb),

  ('mission-be10-02-o1-c1', 'mission-be10-02-o1', 1, 'code_debugging', 'Which line determines the buckets each COUNT(*) is computed separately within?', '{"language":"sql","code":"SELECT district, COUNT(*) AS citizen_count\nFROM citizens\nGROUP BY district;","question":"Which line determines the buckets each COUNT(*) is computed separately within?"}'::jsonb, '{"requiredLineIds":["GROUP BY district;"]}'::jsonb),

  ('mission-be10-03-o1-c1', 'mission-be10-03-o1', 1, 'multiple_choice', 'You want only districts with more than 500 active citizens. Which clause do you filter that with?', '{"question":"You want only districts with more than 500 active citizens. Which clause do you filter that condition with?","options":[{"id":"a","text":"WHERE COUNT(*) > 500"},{"id":"b","text":"HAVING COUNT(*) > 500"},{"id":"c","text":"ORDER BY COUNT(*) > 500"},{"id":"d","text":"LIMIT COUNT(*) > 500"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be10-04-o1-c1', 'mission-be10-04-o1', 1, 'code_debugging', 'Which line is the subquery -- the part evaluated first, on its own, before the outer SELECT runs?', '{"language":"sql","code":"SELECT full_name\nFROM citizens\nWHERE citizen_id IN (\n  SELECT citizen_id FROM addresses WHERE city = ''''Nexus City''''\n);","question":"Which line is the subquery -- the part evaluated first, on its own, before the outer SELECT runs?"}'::jsonb, '{"requiredLineIds":["  SELECT citizen_id FROM addresses WHERE city = ''''Nexus City''''"]}'::jsonb),

  ('mission-be10-05-o1-c1', 'mission-be10-05-o1', 1, 'code_debugging', 'Which line names the CTE that the rest of the query then references by name?', '{"language":"sql","code":"WITH active_citizens AS (\n  SELECT * FROM citizens WHERE is_active = true\n)\nSELECT district, COUNT(*)\nFROM active_citizens\nGROUP BY district;","question":"Which line names the CTE that the rest of the query then references by name?"}'::jsonb, '{"requiredLineIds":["WITH active_citizens AS ("]}'::jsonb),

  ('mission-be10-06-o1-c1', 'mission-be10-06-o1', 1, 'multiple_choice', 'You want each citizen''s row to also show their rank by registration date within their district, without losing any rows. What''s the right tool?', '{"question":"You want each citizen''s row to also show their rank by registration date within their district, without losing any rows. What''s the right tool?","options":[{"id":"a","text":"GROUP BY district"},{"id":"b","text":"A window function like RANK() OVER (PARTITION BY district ORDER BY registered_at)"},{"id":"c","text":"A subquery that deletes all but the earliest row per district"},{"id":"d","text":"HAVING RANK() = 1"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be10-07-o1-c1', 'mission-be10-07-o1', 1, 'code_debugging', 'Which line is what makes this query reusable under a simple name instead of being retyped every time?', '{"language":"sql","code":"CREATE VIEW active_citizens_by_district AS\nSELECT district, COUNT(*) AS citizen_count\nFROM citizens\nWHERE is_active = true\nGROUP BY district;","question":"Which line is what makes this query reusable under a simple name instead of being retyped every time?"}'::jsonb, '{"requiredLineIds":["CREATE VIEW active_citizens_by_district AS"]}'::jsonb),

  ('mission-be10-08-o1-c1', 'mission-be10-08-o1', 1, 'investigation', 'Which evidence shows the same fact is being stored in more than one place, with nothing keeping them in sync?', '{"evidence":[{"id":"ev1","label":"citizens table","detail":"has a district_name column"},{"id":"ev2","label":"addresses table","detail":"also has a district_name column, occasionally spelled differently"},{"id":"ev3","label":"districts table","detail":"the actual source of truth, referenced by neither table via foreign key"}],"question":"Which evidence shows the same fact is being stored in more than one place, with nothing keeping them in sync?"}'::jsonb, '{"requiredEvidenceIds":["ev1","ev2"]}'::jsonb),

  ('mission-be10-09-o1-c1', 'mission-be10-09-o1', 1, 'multiple_choice', 'A dashboard needs a citizen count per district, refreshed every few seconds, under heavy load. What''s a reasonable denormalization tradeoff here?', '{"question":"A dashboard needs a citizen count per district, refreshed every few seconds, under heavy load. What''s a reasonable denormalization tradeoff here?","options":[{"id":"a","text":"Never denormalize, always compute it live with a JOIN and GROUP BY"},{"id":"b","text":"Maintain a separate district_citizen_counts table, updated on every citizen insert/delete, read directly by the dashboard"},{"id":"c","text":"Store the count as a text field with no update process at all"},{"id":"d","text":"Ask every dashboard user to run the query themselves"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be10-10-o1-c1', 'mission-be10-10-o1', 1, 'code_debugging', 'Which line would fail outright if even one existing row already has a duplicate national_id?', '{"language":"sql","code":"alter table citizens add column verified_at timestamptz;\nalter table citizens add constraint citizens_national_id_unique unique (national_id);","question":"Which line would fail outright if even one existing row already has a duplicate national_id?"}'::jsonb, '{"requiredLineIds":["alter table citizens add constraint citizens_national_id_unique unique (national_id);"]}'::jsonb),

  ('mission-be10-11-o1-c1', 'mission-be10-11-o1', 1, 'multiple_choice', 'Why do ORMs and query builders matter for more than just convenience?', '{"question":"Why do ORMs and query builders matter for more than just convenience?","options":[{"id":"a","text":"They make queries run faster than raw SQL, always"},{"id":"b","text":"They parameterize values by default, which is most of what prevents SQL injection from string-concatenated queries"},{"id":"c","text":"They remove the need to understand SQL at all"},{"id":"d","text":"They only matter for very large teams"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be10-12-o1-c1', 'mission-be10-12-o1', 1, 'multiple_choice', 'The report needs a count of anomaly-tagged rows across five differently-shaped tables. What''s the right query shape?', '{"question":"The report needs a count of anomaly-tagged rows across five differently-shaped tables (citizens, addresses, service_logs, routing_config, audit_trail). What''s the right query shape?","options":[{"id":"a","text":"Five separate manual queries, added up by hand"},{"id":"b","text":"A single query using UNION ALL across five SELECTs, one per table, each producing the same shape of row, then aggregated together"},{"id":"c","text":"One giant JOIN across all five tables at once"},{"id":"d","text":"A subquery inside a subquery inside a subquery, one per table"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be10-12-o2-c1', 'mission-be10-12-o2', 1, 'code_debugging', 'Which line actually finds the doubled-slash pattern inside the citizens table?', '{"language":"sql","code":"WITH tagged_rows AS (\n  SELECT ''''citizens'''' AS source_table, citizen_id AS row_id FROM citizens WHERE source_tag LIKE ''''%//%''''\n  UNION ALL\n  SELECT ''''addresses'''', address_id FROM addresses WHERE notes LIKE ''''%//%''''\n)\nSELECT source_table, COUNT(*) AS anomaly_count\nFROM tagged_rows\nGROUP BY source_table;","question":"Which line actually finds the doubled-slash pattern inside the citizens table?"}'::jsonb, '{"requiredLineIds":["  SELECT ''''citizens'''' AS source_table, citizen_id AS row_id FROM citizens WHERE source_tag LIKE ''''%//%''''"]}'::jsonb),
  ('mission-be10-12-o3-c1', 'mission-be10-12-o3', 1, 'multiple_choice', 'The finished report shows the pattern across 40+ tables, predating every incident Forge has investigated so far. What does this most strongly suggest?', '{"question":"The finished report shows the pattern appears across 40+ tables, spanning back before Act 2''s first recorded incident. What does this most strongly suggest?","options":[{"id":"a","text":"It''s random database noise with no real cause"},{"id":"b","text":"It''s a single isolated bug, now fixed"},{"id":"c","text":"It''s a deliberate, long-running, and widely distributed pattern that predates every incident Forge has investigated so far"},{"id":"d","text":"It proves nothing without more data"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-be10-12-o4-c1', 'mission-be10-12-o4', 1, 'boss_encounter', 'State what the finished report actually proves, without speculating about who or what is responsible.', '{"stages":[{"objectiveRef":"mission-be10-12-o1","label":"Choose the right structure"},{"objectiveRef":"mission-be10-12-o2","label":"Find the detection logic"},{"objectiveRef":"mission-be10-12-o3","label":"Interpret the result"}],"task":"State what the finished report actually proves: the pattern is deliberate, distributed across dozens of systems, and has been present far longer than anyone at Forge Division realized -- without speculating about who or what is responsible for it."}'::jsonb, '{"requiredObjectiveIds":["mission-be10-12-o1","mission-be10-12-o2","mission-be10-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be10-01-o1-c1', 'orientation', 'One clause here produces a single row no matter how many rows matched.', 10, 1),
  ('mission-be10-01-o1-c1', 'solution', 'COUNT(*) is the aggregate -- it collapses every WHERE-matched row into one number.', 20, 2),

  ('mission-be10-02-o1-c1', 'orientation', 'Every non-aggregated column in the SELECT list has to appear here too.', 10, 1),
  ('mission-be10-02-o1-c1', 'solution', 'GROUP BY district is what splits the table into per-district buckets before COUNT(*) runs on each.', 20, 2),

  ('mission-be10-03-o1-c1', 'orientation', 'WHERE runs before grouping happens -- the aggregate doesn''t exist yet at that point.', 10, 1),
  ('mission-be10-03-o1-c1', 'solution', 'HAVING filters after the GROUP BY has already produced its aggregated groups.', 20, 2),

  ('mission-be10-04-o1-c1', 'orientation', 'One SELECT is nested inside parentheses inside the other.', 10, 1),
  ('mission-be10-04-o1-c1', 'solution', 'The inner SELECT citizen_id FROM addresses ... runs first and produces the list the outer query''s IN checks against.', 20, 2),

  ('mission-be10-05-o1-c1', 'orientation', 'Look for the keyword that introduces a named, reusable subquery.', 10, 1),
  ('mission-be10-05-o1-c1', 'solution', 'WITH active_citizens AS ( is the CTE definition -- everything after it references active_citizens by name.', 20, 2),

  ('mission-be10-06-o1-c1', 'orientation', 'The requirement to keep every row, while still computing something per-group, rules out GROUP BY entirely.', 10, 1),
  ('mission-be10-06-o1-c1', 'solution', 'A window function computes the rank per PARTITION without collapsing any rows -- exactly what GROUP BY can''t do.', 20, 2),

  ('mission-be10-07-o1-c1', 'orientation', 'One line names the thing; everything after it is the query the name stands for.', 10, 1),
  ('mission-be10-07-o1-c1', 'solution', 'CREATE VIEW active_citizens_by_district AS is what lets future queries just SELECT FROM active_citizens_by_district.', 20, 2),

  ('mission-be10-08-o1-c1', 'orientation', 'Look for the same real-world fact spelled out independently in two different tables.', 10, 1),
  ('mission-be10-08-o1-c1', 'solution', 'ev1 and ev2 -- district_name exists in both tables with no shared source of truth, so they can, and do, drift apart.', 20, 2),

  ('mission-be10-09-o1-c1', 'orientation', 'The goal is a fast, frequent read -- the tradeoff is accepting a bit of write-side complexity to get it.', 10, 1),
  ('mission-be10-09-o1-c1', 'solution', 'A maintained summary table is the classic denormalization trade: faster reads, in exchange for keeping it updated on every write.', 20, 2),

  ('mission-be10-10-o1-c1', 'orientation', 'One of these two changes only checks something about the data already in the table; the other doesn''t.', 10, 1),
  ('mission-be10-10-o1-c1', 'solution', 'Adding a UNIQUE constraint requires every existing row to already satisfy it -- a pre-existing duplicate makes this migration fail.', 20, 2),

  ('mission-be10-11-o1-c1', 'orientation', 'Think back to what made a raw string-concatenated query dangerous in the first place.', 10, 1),
  ('mission-be10-11-o1-c1', 'solution', 'Parameterized queries, what ORMs and query builders default to, are the main defense against SQL injection -- values never get concatenated directly into query text.', 20, 2),

  ('mission-be10-12-o1-c1', 'orientation', 'You need one combined, aggregatable result set built from five differently-shaped sources.', 10, 1),
  ('mission-be10-12-o1-c1', 'solution', 'UNION ALL stacks each table''s matching rows into one common shape first, so the final GROUP BY/COUNT works across all of them at once.', 20, 2),
  ('mission-be10-12-o2-c1', 'orientation', 'The detection logic is a WHERE condition matching a text pattern -- look for the LIKE.', 10, 1),
  ('mission-be10-12-o2-c1', 'solution', 'WHERE source_tag LIKE ''%//%'' is what actually searches the citizens table for the pattern.', 20, 2),
  ('mission-be10-12-o3-c1', 'orientation', 'A pattern this old and this spread out is very hard to explain as either random or a single fixed incident.', 10, 1),
  ('mission-be10-12-o3-c1', 'solution', 'The scope and timeline together point at something deliberate and long-running, not noise and not an isolated, already-fixed bug.', 20, 2),
  ('mission-be10-12-o4-c1', 'orientation', 'Stick to what the data actually shows -- scope, distribution, timeline -- not what it might mean.', 15, 1),
  ('mission-be10-12-o4-c1', 'solution', 'The report proves the pattern is deliberate, spans dozens of systems, and predates every incident investigated so far -- it does not say who or what is responsible, and neither should you yet.', 25, 2);
