-- AI/ML pathway ("Cipher Division") Act 32 -- "LangGraph, Workflows & MCP" content.
-- Arc VI, Acts 28-33 (this Act does not close the Arc; Act 33 does).
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue_lines -> objectives ->
-- challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-langgraph-workflows-mcp row already exists.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-langgraph-workflows-mcp', 'world-ai-langgraph-workflows-mcp', 'langgraph-workflows-mcp', '32A - LangGraph, Workflows & MCP', 'Turn a single agent into a durable graph -- state design, conditional routing, checkpointing and resuming after a crash, human approval gates, and the MCP architecture that gives an agent safe, structured access to tools.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-langgraph-workflows-mcp-1', 'campaign-ai-langgraph-workflows-mcp', 'the-graph-model', 'The Graph Model', 'What turns a single agent into a durable graph -- nodes, edges, state design, conditional routing, checkpointing, durable execution, and the human sign-off a real investigation needs before a risky step.', 1),
  ('operation-ai-langgraph-workflows-mcp-2', 'campaign-ai-langgraph-workflows-mcp', 'safe-structured-access', 'Safe, Structured Access', 'MCP''s architecture for giving an agent safe tool access -- primitives, server and client roles, structured access patterns -- and the first checkpointed graph built to survive being killed mid-run.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-langgraph-workflows-mcp-01', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'graph-mental-model', 'The Graph Mental Model', 'The infinite-loop agent is retired. What replaces it gets drawn before it gets built -- as a graph of nodes and edges, not one long chain of reasoning that runs until something stops it.', 'beginner', ARRAY['maya','elena','noah'], null, null, '{"type":"simulation","simulationId":"graph-mental-model-sim"}'::jsonb, '{"xp":670,"credits":180}'::jsonb, false, 1),
  ('mission-ai-langgraph-workflows-mcp-02', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'state-design', 'State Design', 'A graph is only as good as what flows through it. State design is the difference between a workflow that tracks the investigation precisely and one that loses track of its own progress.', 'beginner', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"state-design-sim"}'::jsonb, '{"xp":680,"credits":180}'::jsonb, false, 2),
  ('mission-ai-langgraph-workflows-mcp-03', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'conditional-routing', 'Conditional Routing', 'Not every step in the graph runs every time. Conditional routing is what lets the workflow branch -- checking a condition and sending state down one edge instead of another.', 'beginner', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"conditional-routing-sim"}'::jsonb, '{"xp":680,"credits":185}'::jsonb, false, 3),
  ('mission-ai-langgraph-workflows-mcp-04', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'checkpointing', 'Checkpointing', 'Every node in the graph can save its work as it goes. Checkpointing is what makes that saved work durable -- a snapshot the workflow can be resumed from later, exactly as it was.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"checkpointing-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 4),
  ('mission-ai-langgraph-workflows-mcp-05', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'durable-execution', 'Durable Execution', 'A checkpoint is only useful if something actually resumes from it. Durable execution is the guarantee that a killed workflow restarts from its last checkpoint instead of from zero.', 'intermediate', ARRAY['noah','byte'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"durable-execution-sim"}'::jsonb, '{"xp":690,"credits":185}'::jsonb, false, 5),
  ('mission-ai-langgraph-workflows-mcp-06', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-1', 'human-in-the-loop', 'Human-in-the-Loop', 'Some steps in this investigation are not safe to let a graph take on its own. A human-in-the-loop approval gate is what pauses the workflow -- durably -- until a person says go.', 'intermediate', ARRAY['maya','elena'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"human-in-the-loop-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 6),
  ('mission-ai-langgraph-workflows-mcp-07', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'mcp-architecture', 'MCP Architecture', 'Every tool call this pathway has built so far was wired in by hand. MCP is the protocol that lets an agent discover and use tools through one consistent, structured interface instead.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"mcp-architecture-sim"}'::jsonb, '{"xp":700,"credits":190}'::jsonb, false, 7),
  ('mission-ai-langgraph-workflows-mcp-08', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'mcp-primitives', 'Tools, Resources, Prompts', 'MCP does not expose one kind of thing to an agent. Tools, resources, and prompts are three distinct primitives, and mixing them up is what breaks an integration before it ever runs.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"mcp-primitives-sim"}'::jsonb, '{"xp":710,"credits":190}'::jsonb, false, 8),
  ('mission-ai-langgraph-workflows-mcp-09', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'mcp-server-client', 'Server vs Client', 'MCP has two sides, and Cipher Division''s investigation only needs to build one of them. Knowing which is which decides whether the archive''s tools stay safe to expose at all.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"mcp-server-client-sim"}'::jsonb, '{"xp":710,"credits":195}'::jsonb, false, 9),
  ('mission-ai-langgraph-workflows-mcp-10', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'safe-tool-access', 'Safe Tool Access', 'An MCP server that hands an agent every tool with full permissions is not an integration. It is a liability. Safe, structured tool access is what keeps the archive''s real risk contained.', 'intermediate', ARRAY['noah','maya'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"safe-tool-access-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 10),
  ('mission-ai-langgraph-workflows-mcp-11', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'the-checkpointed-graph', 'The Checkpointed Graph', 'Every piece is built: state, routing, checkpoints, durable execution, an approval gate, and safe MCP tool access. What is left is assembling them into one real graph and pointing it at the archive.', 'intermediate', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"checkpointed-graph-sim"}'::jsonb, '{"xp":720,"credits":195}'::jsonb, false, 11),
  ('mission-ai-langgraph-workflows-mcp-12', 'world-ai-langgraph-workflows-mcp', 'campaign-ai-langgraph-workflows-mcp', 'operation-ai-langgraph-workflows-mcp-2', 'kill-and-resume', 'Kill and Resume', 'The checkpointed investigation goes live. Halfway through, on purpose, someone kills the process -- to find out whether everything this Act built actually holds.', 'boss', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-langgraph-workflows-mcp-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"kill-and-resume-boss-sim"}'::jsonb, '{"xp":1550,"credits":330,"badgeIds":["durable-resume"],"skillXp":{"langgraph_mcp":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-langgraph-workflows-mcp-01', 1, 'maya', 'The infinite-loop agent is decommissioned. Good riddance. What replaces it does not get built the same way -- one long reasoning chain with no shape to it.'),
  ('mission-ai-langgraph-workflows-mcp-01', 2, 'elena', 'We draw it as a graph before we write a line of it. Nodes are steps -- check a checksum, read a log, ask a question. Edges are the allowed transitions between them.'),
  ('mission-ai-langgraph-workflows-mcp-01', 3, 'elena', 'State is what actually moves along those edges -- the current findings, which records are checked, what still needs deciding. Every node reads it, does its work, and writes an updated version back.'),
  ('mission-ai-langgraph-workflows-mcp-01', 4, 'noah', 'The shape matters because it is visible. Draw the graph and you can see every path the investigation is allowed to take, before it ever runs -- instead of trusting a model to reason its way there each time.'),
  ('mission-ai-langgraph-workflows-mcp-01', 5, 'maya', 'Start with the vocabulary, because everything for the rest of this Act sits on top of it. Nodes, edges, state. Get that straight first.'),

  ('mission-ai-langgraph-workflows-mcp-02', 1, 'noah', 'The graph is only as good as what flows through it. If state does not track the right things, every node downstream is working half-blind.'),
  ('mission-ai-langgraph-workflows-mcp-02', 2, 'elena', 'Good state design names exactly what the investigation needs to track -- records_checked, current_findings, pending_approval -- as explicit fields, not a wall of prior text a node has to re-read and reinterpret.'),
  ('mission-ai-langgraph-workflows-mcp-02', 3, 'elena', 'Every node''s job is narrow: read the fields it needs from state, do its work, write an update. Not rewrite the whole thing, not guess at fields nobody defined.'),
  ('mission-ai-langgraph-workflows-mcp-02', 4, 'noah', 'Get the schema wrong up front and it shows up everywhere downstream -- routing nodes with nothing to branch on, checkpoints saving data nobody asked for.'),

  ('mission-ai-langgraph-workflows-mcp-03', 1, 'elena', 'Not every node runs every time. After a checksum check, the graph needs to send state down a different edge depending on what the check actually found.'),
  ('mission-ai-langgraph-workflows-mcp-03', 2, 'elena', 'That is conditional routing -- an edge whose destination is decided by a function that reads the current state, not a fixed, single next step.'),
  ('mission-ai-langgraph-workflows-mcp-03', 3, 'noah', 'It looks like the deterministic routing from the last Act, and it is the same instinct: a plain rule, plain code, deciding the branch. The difference here is the branch is baked into the graph''s structure itself, not a one-off if-statement.'),
  ('mission-ai-langgraph-workflows-mcp-03', 4, 'elena', 'Mismatch found: route to the deep-check node. Mismatch not found: route straight to the report node. The graph itself enforces that only one of those paths is ever taken.'),

  ('mission-ai-langgraph-workflows-mcp-04', 1, 'noah', 'Every node can do real work and still lose it all if the process dies before anything is saved. Checkpointing is what makes a node''s progress survive past the node itself.'),
  ('mission-ai-langgraph-workflows-mcp-04', 2, 'noah', 'A checkpoint is a snapshot of the full state, written durably, right after a node finishes -- not held in memory, not gone the moment the process exits.'),
  ('mission-ai-langgraph-workflows-mcp-04', 3, 'elena', 'The granularity matters. Checkpoint after every node and a crash loses at most one step''s work. Checkpoint only at the very end and a crash loses the entire investigation.'),
  ('mission-ai-langgraph-workflows-mcp-04', 4, 'byte', 'I have lost entire overnight jobs to this exact gap, more than once. A crash five minutes before the finish line with no checkpoint in between is five minutes and five hours, indistinguishable.'),

  ('mission-ai-langgraph-workflows-mcp-05', 1, 'byte', 'A checkpoint sitting in storage does nothing on its own. Something has to actually notice the process died and pick the saved state back up.'),
  ('mission-ai-langgraph-workflows-mcp-05', 2, 'noah', 'That is durable execution -- the guarantee that when a workflow is interrupted, restarting it resumes from the last checkpoint instead of starting the whole graph over from node one.'),
  ('mission-ai-langgraph-workflows-mcp-05', 3, 'noah', 'Resuming correctly means two things at once: the state comes back exactly as it was saved, and any node whose work was already checkpointed does not run again.'),
  ('mission-ai-langgraph-workflows-mcp-05', 4, 'elena', 'That second part is the one people get wrong. Restore the state but re-run every node anyway, and a resumed workflow can end up repeating a step it already finished -- including ones that were not safe to repeat.'),

  ('mission-ai-langgraph-workflows-mcp-06', 1, 'maya', 'Some steps in this investigation should not happen just because a graph decided they should. Quarantining a record, escalating a finding -- those need a person to actually say yes.'),
  ('mission-ai-langgraph-workflows-mcp-06', 2, 'elena', 'A human-in-the-loop approval gate is a node that pauses the graph and waits. Not a timeout, not a retry -- an actual halt, with the state checkpointed, until a human responds.'),
  ('mission-ai-langgraph-workflows-mcp-06', 3, 'elena', 'The checkpoint is what makes the pause safe. The workflow can sit paused for a minute or a day; when the approval comes back, it resumes from exactly that point, not from the beginning.'),
  ('mission-ai-langgraph-workflows-mcp-06', 4, 'maya', 'Put the gate in front of anything irreversible. If a wrong decision there is expensive to undo, a person signs off before the graph is allowed to act on it.'),

  ('mission-ai-langgraph-workflows-mcp-07', 1, 'elena', 'Every tool call this pathway has built so far was wired in by hand -- a function, a description, registered directly with the agent. That does not scale past one team''s tools.'),
  ('mission-ai-langgraph-workflows-mcp-07', 2, 'elena', 'MCP, the Model Context Protocol, is a standard interface between an agent and the tools, data, and prompts it needs. One protocol an agent can speak to any MCP-compliant source, instead of a custom integration for each one.'),
  ('mission-ai-langgraph-workflows-mcp-07', 3, 'noah', 'The point is not that MCP does something a direct tool call could not. It is that it does it the same way everywhere, so an agent built for one MCP server can work with any other with no custom glue code.'),
  ('mission-ai-langgraph-workflows-mcp-07', 4, 'elena', 'For the archive investigation, that means the record store, the migration logs, and the checksum service can all sit behind MCP servers, exposed to the agent through one consistent interface.'),

  ('mission-ai-langgraph-workflows-mcp-08', 1, 'elena', 'MCP exposes three distinct kinds of thing to an agent, and they are not interchangeable. Confuse them and the integration breaks before it ever runs.'),
  ('mission-ai-langgraph-workflows-mcp-08', 2, 'elena', 'Tools are actions the agent can invoke -- verify a checksum, quarantine a record, something with a side effect. Resources are data the agent can read -- a log file, a record, no side effect at all.'),
  ('mission-ai-langgraph-workflows-mcp-08', 3, 'elena', 'Prompts are reusable templates a server exposes for a specific task -- a pre-written investigation prompt, filled in with the right arguments, instead of the agent guessing at the wording each time.'),
  ('mission-ai-langgraph-workflows-mcp-08', 4, 'byte', 'Wire a read-only log as a tool instead of a resource, and now the agent thinks calling it can change something. That mismatch is exactly the kind of confidently wrong assumption that gets an agent in trouble.'),

  ('mission-ai-langgraph-workflows-mcp-09', 1, 'noah', 'MCP has two sides, and it matters which one Cipher Division is actually building. The archive investigation only needs one of them.'),
  ('mission-ai-langgraph-workflows-mcp-09', 2, 'noah', 'An MCP server exposes tools, resources, and prompts -- it is the thing that owns the record store, the logs, the checksum service, and answers requests for them.'),
  ('mission-ai-langgraph-workflows-mcp-09', 3, 'elena', 'An MCP client is the thing that connects to a server and uses what it exposes -- in our case, the agent itself, or the framework running it.'),
  ('mission-ai-langgraph-workflows-mcp-09', 4, 'noah', 'We are building servers around the archive''s own data and tools, once, and letting any MCP client -- this investigation''s agent included -- connect to them the same way.'),

  ('mission-ai-langgraph-workflows-mcp-10', 1, 'noah', 'An MCP server that hands over every tool with full permissions to whatever connects is not an integration. It is an open door into the archive.'),
  ('mission-ai-langgraph-workflows-mcp-10', 2, 'maya', 'Safe, structured tool access starts with least privilege -- a server exposes exactly the tools a given client needs, nothing broader, and nothing that touches data outside its actual job.'),
  ('mission-ai-langgraph-workflows-mcp-10', 3, 'noah', 'It also means validating what comes back. A tool''s output is still untrusted input to whatever consumes it next -- checked and typed, not assumed safe because it came from your own server.'),
  ('mission-ai-langgraph-workflows-mcp-10', 4, 'maya', 'Every quarantined record in this archive got there because something trusted data it should have checked first. The tool layer does not get to repeat that mistake.'),

  ('mission-ai-langgraph-workflows-mcp-11', 1, 'maya', 'Every piece is built now: state, routing, checkpoints, durable execution, an approval gate, MCP tools behind least privilege. What is missing is one real graph that uses all of it at once.'),
  ('mission-ai-langgraph-workflows-mcp-11', 2, 'elena', 'Lay it out end to end: ingest the flagged record, route on its checksum result, check logs through an MCP tool, checkpoint after each step, pause at the approval gate before quarantine, resume, conclude.'),
  ('mission-ai-langgraph-workflows-mcp-11', 3, 'noah', 'Every node writes to state and checkpoints before the next one runs. Every risky action sits behind the approval gate. Every external check goes through an MCP tool with only the access it actually needs.'),
  ('mission-ai-langgraph-workflows-mcp-11', 4, 'maya', 'This is the design that goes live. Get the graph right here, on paper, before it touches the real archive.'),

  ('mission-ai-langgraph-workflows-mcp-12', 1, 'maya', 'The checkpointed investigation went live twenty minutes ago, against the two records still quarantined from the last Act. Full graph -- routing, checkpoints, the approval gate, MCP tools, all of it.'),
  ('mission-ai-langgraph-workflows-mcp-12', 2, 'noah', 'It just passed the checksum-routing node and wrote its first checkpoint. Right on schedule. I am going to kill the process now, on purpose, to see what actually happens next.'),
  ('mission-ai-langgraph-workflows-mcp-12', 3, 'elena', 'Wait -- confirm the checkpoint landed first. If we kill it before that write finishes, this proves nothing except that we skipped a step.'),
  ('mission-ai-langgraph-workflows-mcp-12', 4, 'noah', 'Confirmed. Checkpoint written, state includes the checksum result. Killing it now.'),
  ('mission-ai-langgraph-workflows-mcp-12', 5, 'maya', 'Process is down. No graceful shutdown, no cleanup -- exactly what an actual crash would look like. Now we find out if this was worth building.'),
  ('mission-ai-langgraph-workflows-mcp-12', 6, 'noah', 'Restarting the workflow against the same investigation ID. If durable execution works the way we designed it, it should come back at the checkpoint, not at node one.'),
  ('mission-ai-langgraph-workflows-mcp-12', 7, 'elena', 'It is resuming. State restored -- checksum result is there, unchanged. It did not touch verify_checksum again. It went straight to the next node.'),
  ('mission-ai-langgraph-workflows-mcp-12', 8, 'maya', 'That is the entire point of this Act. Walk the resume log with me, node by node, and confirm nothing ran twice that shouldn''t have -- especially anything that touches the actual archive.'),
  ('mission-ai-langgraph-workflows-mcp-12', 9, 'noah', 'Pulling the full resume trace now.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-langgraph-workflows-mcp-01-o1', 'mission-ai-langgraph-workflows-mcp-01', 1, 'Name the pieces', 'State what nodes, edges, and state actually are in the graph model.'),
  ('mission-ai-langgraph-workflows-mcp-01-o2', 'mission-ai-langgraph-workflows-mcp-01', 2, 'Sort the pieces', 'Sort each described part of the investigation workflow into node, edge, or state.'),

  ('mission-ai-langgraph-workflows-mcp-02-o1', 'mission-ai-langgraph-workflows-mcp-02', 1, 'Define good state design', 'State what makes a state schema actually useful to a graph.'),
  ('mission-ai-langgraph-workflows-mcp-02-o2', 'mission-ai-langgraph-workflows-mcp-02', 2, 'Design the schema', 'Match each state field to what it should actually track.'),

  ('mission-ai-langgraph-workflows-mcp-03-o1', 'mission-ai-langgraph-workflows-mcp-03', 1, 'Define conditional routing', 'State what decides where a conditional edge sends the state next.'),
  ('mission-ai-langgraph-workflows-mcp-03-o2', 'mission-ai-langgraph-workflows-mcp-03', 2, 'Diagnose the misroute', 'Find the evidence that explains why the workflow routed down the wrong edge.'),

  ('mission-ai-langgraph-workflows-mcp-04-o1', 'mission-ai-langgraph-workflows-mcp-04', 1, 'Define checkpointing', 'State what a checkpoint actually is.'),
  ('mission-ai-langgraph-workflows-mcp-04-o2', 'mission-ai-langgraph-workflows-mcp-04', 2, 'Order the write', 'Order the stages of writing a checkpoint after a node runs.'),

  ('mission-ai-langgraph-workflows-mcp-05-o1', 'mission-ai-langgraph-workflows-mcp-05', 1, 'Define durable execution', 'State what durable execution actually guarantees.'),
  ('mission-ai-langgraph-workflows-mcp-05-o2', 'mission-ai-langgraph-workflows-mcp-05', 2, 'Diagnose the repeated step', 'Find the evidence that explains why a completed, checkpointed step ran a second time on resume.'),

  ('mission-ai-langgraph-workflows-mcp-06-o1', 'mission-ai-langgraph-workflows-mcp-06', 1, 'Define the gate', 'State what a human-in-the-loop approval gate actually does.'),
  ('mission-ai-langgraph-workflows-mcp-06-o2', 'mission-ai-langgraph-workflows-mcp-06', 2, 'Place the gate', 'Sort each action into needing an approval gate or being safe to automate.'),

  ('mission-ai-langgraph-workflows-mcp-07-o1', 'mission-ai-langgraph-workflows-mcp-07', 1, 'Define MCP', 'State the actual problem MCP solves.'),
  ('mission-ai-langgraph-workflows-mcp-07-o2', 'mission-ai-langgraph-workflows-mcp-07', 2, 'Order the tool call', 'Order the sequence of an MCP tool call from connection to result.'),

  ('mission-ai-langgraph-workflows-mcp-08-o1', 'mission-ai-langgraph-workflows-mcp-08', 1, 'Tell the primitives apart', 'State how MCP tools, resources, and prompts actually differ.'),
  ('mission-ai-langgraph-workflows-mcp-08-o2', 'mission-ai-langgraph-workflows-mcp-08', 2, 'Sort the primitives', 'Sort each item into tool, resource, or prompt.'),

  ('mission-ai-langgraph-workflows-mcp-09-o1', 'mission-ai-langgraph-workflows-mcp-09', 1, 'Tell the roles apart', 'State the difference between an MCP server and an MCP client.'),
  ('mission-ai-langgraph-workflows-mcp-09-o2', 'mission-ai-langgraph-workflows-mcp-09', 2, 'Diagnose the wrong role', 'Find the evidence that explains why the agent cannot use a service as a tool.'),

  ('mission-ai-langgraph-workflows-mcp-10-o1', 'mission-ai-langgraph-workflows-mcp-10', 1, 'Define least privilege', 'State what least privilege means for an MCP server exposing archive tools.'),
  ('mission-ai-langgraph-workflows-mcp-10-o2', 'mission-ai-langgraph-workflows-mcp-10', 2, 'Justify output validation', 'State why a tool''s returned output still needs validation.'),

  ('mission-ai-langgraph-workflows-mcp-11-o1', 'mission-ai-langgraph-workflows-mcp-11', 1, 'Define node completion', 'State what must happen before any node in the assembled graph is considered complete.'),
  ('mission-ai-langgraph-workflows-mcp-11-o2', 'mission-ai-langgraph-workflows-mcp-11', 2, 'Order the full graph', 'Order the full checkpointed investigation graph from ingest to conclusion.'),

  ('mission-ai-langgraph-workflows-mcp-12-o1', 'mission-ai-langgraph-workflows-mcp-12', 1, 'Read the resume trace', 'Find the evidence showing the workflow resumed from its last checkpoint instead of restarting from node one.'),
  ('mission-ai-langgraph-workflows-mcp-12-o2', 'mission-ai-langgraph-workflows-mcp-12', 2, 'Confirm no repeated risk', 'Find the evidence showing no already-completed, side-effecting step ran a second time after the restart.'),
  ('mission-ai-langgraph-workflows-mcp-12-o3', 'mission-ai-langgraph-workflows-mcp-12', 3, 'Choose the correct verification', 'Choose the fact that actually proves durable execution worked, not just that the process came back up.'),
  ('mission-ai-langgraph-workflows-mcp-12-o4', 'mission-ai-langgraph-workflows-mcp-12', 4, 'State the conclusion', 'Having read the trace, confirmed no repeat, and chosen the right verification, state what happened and why it worked.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-langgraph-workflows-mcp-01-o1-c1', 'mission-ai-langgraph-workflows-mcp-01-o1', 1, 'multiple_choice', 'In the graph model for an agent workflow, what do nodes, edges, and state actually represent?', '{"question":"In the graph model for an agent workflow, what do nodes, edges, and state actually represent?","options":[{"id":"a","text":"Nodes are steps of work; edges are the allowed transitions between steps; state is the data that flows along those edges and gets updated by each node"},{"id":"b","text":"Nodes are data, edges are steps, state is a log of every prompt sent"},{"id":"c","text":"Edges are the only thing that does work, nodes just connect them"},{"id":"d","text":"State is a fixed set of instructions given once at the start and never modified"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-01-o2-c1', 'mission-ai-langgraph-workflows-mcp-01-o2', 1, 'drag_and_drop', 'Sort each described part of the investigation workflow into node, edge, or state.', '{"items":[{"id":"i1","text":"The step that checks a record''s checksum against its stored value"},{"id":"i2","text":"The path taken when a checksum check comes back mismatched"},{"id":"i3","text":"The current list of records already checked in this investigation"},{"id":"i4","text":"The step that reads the migration log for a flagged record"}],"targets":[{"id":"node","label":"Node"},{"id":"edge","label":"Edge"},{"id":"state","label":"State"}]}'::jsonb, '{"correctMapping":{"i1":"node","i2":"edge","i3":"state","i4":"node"}}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-02-o1-c1', 'mission-ai-langgraph-workflows-mcp-02-o1', 1, 'multiple_choice', 'What makes a state schema for an investigation graph actually useful?', '{"question":"What makes a state schema for an investigation graph actually useful?","options":[{"id":"a","text":"Explicit, named fields for exactly what the investigation needs to track -- like records_checked or pending_approval -- so every node can read and update state without reinterpreting free text"},{"id":"b","text":"One long unstructured text field holding everything ever said"},{"id":"c","text":"No schema at all, since the model can infer structure on demand"},{"id":"d","text":"A schema defined once and never allowed to change after the first node runs"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-02-o2-c1', 'mission-ai-langgraph-workflows-mcp-02-o2', 1, 'drag_and_drop', 'Match each state field to what it should actually track.', '{"items":[{"id":"i1","text":"records_checked"},{"id":"i2","text":"current_findings"},{"id":"i3","text":"pending_approval"},{"id":"i4","text":"checkpoint_id"}],"targets":[{"id":"t1","label":"Which records have already been examined"},{"id":"t2","label":"The investigation''s current conclusions so far"},{"id":"t3","label":"Whether an action is waiting on human sign-off"},{"id":"t4","label":"Which saved snapshot the workflow would resume from"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-03-o1-c1', 'mission-ai-langgraph-workflows-mcp-03-o1', 1, 'multiple_choice', 'What decides where a conditional edge sends the state next?', '{"question":"What decides where a conditional edge sends the state next?","options":[{"id":"a","text":"A routing function that reads the current state and returns which node comes next, based on what it finds"},{"id":"b","text":"The order nodes were defined in the code"},{"id":"c","text":"A random selection among all defined edges"},{"id":"d","text":"The user manually clicking which node to run"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-03-o2-c1', 'mission-ai-langgraph-workflows-mcp-03-o2', 1, 'investigation', 'After a checksum mismatch, the workflow routed to the report node instead of the deep-check node. Which evidence explains it?', '{"evidence":[{"id":"e1","label":"Routing function","detail":"check_route reads state.checksum_result and returns deep_check on mismatch, report on match"},{"id":"e2","label":"Trace log","detail":"state.checksum_result was mismatch when check_route ran, but the workflow proceeded to the report node"},{"id":"e3","label":"Node code","detail":"The verify_checksum node writes its result to state.result instead of state.checksum_result"}],"question":"Which evidence explains why the routing sent state down the wrong edge?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-04-o1-c1', 'mission-ai-langgraph-workflows-mcp-04-o1', 1, 'multiple_choice', 'What is a checkpoint, in a durable graph workflow?', '{"question":"What is a checkpoint, in a durable graph workflow?","options":[{"id":"a","text":"A durable, saved snapshot of the full state, written after a node finishes, that the workflow can be resumed from later"},{"id":"b","text":"A comment left in the code explaining what a node does"},{"id":"c","text":"A temporary variable that is cleared when the process exits"},{"id":"d","text":"A log message printed to the console for debugging"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-04-o2-c1', 'mission-ai-langgraph-workflows-mcp-04-o2', 1, 'interactive_diagram', 'Order the stages of writing a checkpoint after a node runs.', '{"diagramId":"checkpoint-write","hotspots":[{"id":"h1","label":"Node finishes its work and produces an updated state","explanation":"The node completes and has a new version of state ready."},{"id":"h2","label":"The updated state is serialized","explanation":"State is converted into a storable form."},{"id":"h3","label":"The serialized state is written durably to checkpoint storage, tagged with this workflow run''s id and step","explanation":"The write goes somewhere that survives the process exiting."},{"id":"h4","label":"Only after the write succeeds does the graph proceed to the next node","explanation":"Progress is not considered safe until the checkpoint is confirmed."}],"task":"Order the stages of writing a checkpoint after a node runs."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-05-o1-c1', 'mission-ai-langgraph-workflows-mcp-05-o1', 1, 'multiple_choice', 'What does durable execution guarantee?', '{"question":"What does durable execution guarantee?","options":[{"id":"a","text":"That when a workflow is interrupted, restarting it resumes from the last checkpoint -- restored state, and no re-running of nodes whose work was already saved"},{"id":"b","text":"That a workflow will never be interrupted"},{"id":"c","text":"That a workflow always finishes within a fixed amount of time"},{"id":"d","text":"That state is held only in memory for speed"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-05-o2-c1', 'mission-ai-langgraph-workflows-mcp-05-o2', 1, 'investigation', 'The workflow was killed right after checkpointing a checksum result. On restart, it re-ran verify_checksum and quarantine_record a second time. Which evidence explains it?', '{"evidence":[{"id":"e1","label":"Resume log","detail":"Restart restored state.checksum_result correctly from the last checkpoint"},{"id":"e2","label":"Resume log","detail":"Restart then re-ran the graph from its very first node instead of the node after the last checkpoint, calling verify_checksum and quarantine_record a second time"},{"id":"e3","label":"Checkpoint storage","detail":"The checkpoint for the checksum step was written correctly and is intact"}],"question":"Which evidence explains why a completed, checkpointed step ran a second time on resume?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-06-o1-c1', 'mission-ai-langgraph-workflows-mcp-06-o1', 1, 'multiple_choice', 'What does a human-in-the-loop approval gate actually do in a graph workflow?', '{"question":"What does a human-in-the-loop approval gate actually do in a graph workflow?","options":[{"id":"a","text":"Pauses the graph at that node, checkpoints the state, and waits for a human decision before the workflow is allowed to continue"},{"id":"b","text":"Sends a notification but lets the workflow continue regardless"},{"id":"c","text":"Retries the node automatically until it succeeds without human input"},{"id":"d","text":"Skips the node entirely if no human responds within a second"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-06-o2-c1', 'mission-ai-langgraph-workflows-mcp-06-o2', 1, 'drag_and_drop', 'Sort each action into needing an approval gate or being safe to automate.', '{"items":[{"id":"i1","text":"Quarantining a record based on a confirmed checksum mismatch"},{"id":"i2","text":"Reading a migration log entry"},{"id":"i3","text":"Escalating a finding as confirmed tampering in the case file"},{"id":"i4","text":"Verifying a checksum against its stored value"}],"targets":[{"id":"gate","label":"Needs an approval gate"},{"id":"safe","label":"Safe to automate"}]}'::jsonb, '{"correctMapping":{"i1":"gate","i2":"safe","i3":"gate","i4":"safe"}}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-07-o1-c1', 'mission-ai-langgraph-workflows-mcp-07-o1', 1, 'multiple_choice', 'What problem does MCP actually solve, compared to wiring each tool in by hand?', '{"question":"What problem does MCP actually solve, compared to wiring each tool in by hand?","options":[{"id":"a","text":"It gives an agent one standard interface to discover and use tools, resources, and prompts from any compliant server, instead of a custom integration built for each one"},{"id":"b","text":"It makes every model call free"},{"id":"c","text":"It replaces the need for tool descriptions entirely"},{"id":"d","text":"It is a faster version of a single tool call, nothing more"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-07-o2-c1', 'mission-ai-langgraph-workflows-mcp-07-o2', 1, 'interactive_diagram', 'Order the sequence of an MCP tool call from connection to result.', '{"diagramId":"mcp-tool-use","hotspots":[{"id":"h1","label":"Client connects to an MCP server","explanation":"The connection is established before anything else can happen."},{"id":"h2","label":"Server advertises the tools, resources, and prompts it exposes","explanation":"The client learns what is available."},{"id":"h3","label":"Client selects a tool it needs and calls it with arguments","explanation":"A specific tool is invoked with the right input."},{"id":"h4","label":"Server executes the tool and returns a structured result","explanation":"The call completes and the result comes back in a defined shape."}],"task":"Order the sequence of an MCP tool call from connection to result."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-08-o1-c1', 'mission-ai-langgraph-workflows-mcp-08-o1', 1, 'multiple_choice', 'How do MCP tools, resources, and prompts actually differ?', '{"question":"How do MCP tools, resources, and prompts actually differ?","options":[{"id":"a","text":"Tools are invocable actions with side effects; resources are readable data with no side effect; prompts are reusable templates for a specific task"},{"id":"b","text":"They are three names for the same primitive"},{"id":"c","text":"Resources are the only primitive that can be called by an agent"},{"id":"d","text":"Prompts are raw binary data, never text"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-08-o2-c1', 'mission-ai-langgraph-workflows-mcp-08-o2', 1, 'drag_and_drop', 'Sort each item into tool, resource, or prompt.', '{"items":[{"id":"i1","text":"quarantine_record -- changes a record''s status"},{"id":"i2","text":"The current contents of the migration log file"},{"id":"i3","text":"A pre-written characterize-this-record template, filled in per record"},{"id":"i4","text":"verify_checksum -- computes and compares a hash"}],"targets":[{"id":"tool","label":"Tool"},{"id":"resource","label":"Resource"},{"id":"prompt","label":"Prompt"}]}'::jsonb, '{"correctMapping":{"i1":"tool","i2":"resource","i3":"prompt","i4":"tool"}}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-09-o1-c1', 'mission-ai-langgraph-workflows-mcp-09-o1', 1, 'multiple_choice', 'What is the difference between an MCP server and an MCP client?', '{"question":"What is the difference between an MCP server and an MCP client?","options":[{"id":"a","text":"A server exposes tools, resources, and prompts for others to use; a client connects to a server and consumes what it exposes"},{"id":"b","text":"A server is always the agent, and a client is always the data source"},{"id":"c","text":"There is no functional difference, only a naming convention"},{"id":"d","text":"A client exposes tools; a server only ever calls them"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-09-o2-c1', 'mission-ai-langgraph-workflows-mcp-09-o2', 1, 'investigation', 'The investigation agent cannot reach checksum_service as a tool. Which evidence explains why?', '{"evidence":[{"id":"e1","label":"Build ticket","detail":"checksum_service was implemented to connect outward to other servers and consume their tools, matching the client role"},{"id":"e2","label":"Integration log","detail":"The investigation agent, acting as an MCP client, cannot find checksum_service advertising any tools to connect to"},{"id":"e3","label":"Network log","detail":"checksum_service and the agent are both reachable on the network with no firewall issue"}],"question":"Which evidence explains why the agent cannot use checksum_service as a tool?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-10-o1-c1', 'mission-ai-langgraph-workflows-mcp-10-o1', 1, 'multiple_choice', 'What does least privilege mean for an MCP server exposing archive tools?', '{"question":"What does least privilege mean for an MCP server exposing archive tools?","options":[{"id":"a","text":"Each client only gets access to the specific tools it actually needs for its job, not the full set the server could technically expose"},{"id":"b","text":"Every client gets every tool, for simplicity"},{"id":"c","text":"Least privilege only applies to human users, not agents"},{"id":"d","text":"Access is granted once and never reviewed again"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-10-o2-c1', 'mission-ai-langgraph-workflows-mcp-10-o2', 1, 'multiple_choice', 'Why should a tool''s returned output still be validated before an agent acts on it?', '{"question":"Why should a tool''s returned output still be validated before an agent acts on it?","options":[{"id":"a","text":"Because it is still untrusted input to whatever consumes it next, regardless of coming from your own server -- and treating it as automatically safe is the same mistake that let the archive get poisoned"},{"id":"b","text":"Because MCP requires all output to be encrypted"},{"id":"c","text":"Tool output never needs validation once the tool itself is trusted"},{"id":"d","text":"Because validation makes tool calls run faster"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-11-o1-c1', 'mission-ai-langgraph-workflows-mcp-11-o1', 1, 'multiple_choice', 'In the assembled investigation graph, what must happen before any node is considered complete?', '{"question":"In the assembled investigation graph, what must happen before any node is considered complete?","options":[{"id":"a","text":"Its updated state must be checkpointed, and any node reachable next must be decided by the routing function reading that state"},{"id":"b","text":"The node must ask the model to summarize what happened, then discard the result"},{"id":"c","text":"Nothing -- checkpointing only matters at the very end of the graph"},{"id":"d","text":"The node must re-run every prior node to confirm nothing changed"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-11-o2-c1', 'mission-ai-langgraph-workflows-mcp-11-o2', 1, 'interactive_diagram', 'Order the full checkpointed investigation graph from ingest to conclusion.', '{"diagramId":"full-investigation-graph","hotspots":[{"id":"h1","label":"Ingest the flagged record into state","explanation":"The investigation begins with the record loaded into state."},{"id":"h2","label":"verify_checksum node runs through an MCP tool with least-privilege access, result is checkpointed","explanation":"The first check runs and its result is saved durably."},{"id":"h3","label":"Conditional routing reads the checksum result and sends state to the deep-check or report edge","explanation":"The branch depends on what the checksum step found."},{"id":"h4","label":"Deep-check nodes read logs through MCP resources, checkpointing after each","explanation":"Further investigation proceeds with each step saved."},{"id":"h5","label":"Approval gate pauses before any irreversible action like quarantine, state checkpointed while it waits","explanation":"Nothing irreversible happens without a human decision."},{"id":"h6","label":"On approval, the workflow resumes from the checkpoint and completes the action","explanation":"Once approved, the paused work resumes exactly where it left off."},{"id":"h7","label":"Final node writes the conclusion to the case file","explanation":"The investigation ends with a recorded conclusion."}],"task":"Order the full checkpointed investigation graph from ingest to conclusion."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5","h6","h7"]}'::jsonb),

  ('mission-ai-langgraph-workflows-mcp-12-o1-c1', 'mission-ai-langgraph-workflows-mcp-12-o1', 1, 'investigation', 'Which evidence shows the workflow resumed from its last checkpoint instead of restarting from the beginning?', '{"evidence":[{"id":"e1","label":"Process log","detail":"Workflow process was killed at 14:32:07, immediately after the checkpoint for the checksum-routing node was confirmed written"},{"id":"e2","label":"Restart log","detail":"New process started at 14:33:15, loaded the checkpoint for investigation ai-arc-0447, and resumed at the node immediately after checksum-routing, not at the graph''s first node"},{"id":"e3","label":"State diff","detail":"Restored state.checksum_result matches exactly what was checkpointed before the kill, unchanged"},{"id":"e4","label":"Facilities log","detail":"Cipher Labs power draw is within normal range"}],"question":"Which evidence shows the workflow resumed from its last checkpoint instead of restarting from the beginning?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-12-o2-c1', 'mission-ai-langgraph-workflows-mcp-12-o2', 1, 'investigation', 'Which evidence shows no already-completed, side-effecting step ran a second time after the restart?', '{"evidence":[{"id":"e1","label":"Tool call log (pre-kill)","detail":"verify_checksum was called once on ai-arc-0447 before the kill, result checkpointed"},{"id":"e2","label":"Tool call log (post-restart)","detail":"verify_checksum does not appear again anywhere in the post-restart trace; the deep-check node ran directly using the checkpointed result"},{"id":"e3","label":"Quarantine log","detail":"No quarantine action was taken before the approval gate was reached on the resumed run"},{"id":"e4","label":"Tool registry","detail":"verify_checksum remains accurately described and online"}],"question":"Which evidence shows no already-completed, side-effecting step ran a second time after the restart?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-12-o3-c1', 'mission-ai-langgraph-workflows-mcp-12-o3', 1, 'multiple_choice', 'What actually proves durable execution worked here, not just that the process came back online?', '{"question":"What actually proves durable execution worked here, not just that the process came back online?","options":[{"id":"a","text":"The resumed state matches the checkpointed state exactly, execution picked up after the last completed node, and no already-completed side-effecting step ran again"},{"id":"b","text":"The process shows a new process ID after restart"},{"id":"c","text":"The restart happened in under two minutes"},{"id":"d","text":"The workflow printed a resumed-successfully log line"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-langgraph-workflows-mcp-12-o4-c1', 'mission-ai-langgraph-workflows-mcp-12-o4', 1, 'boss_encounter', 'Having read the trace, confirmed no repeat, and chosen the right verification, state what happened and why it worked, in one sentence.', '{"stages":[{"objectiveRef":"mission-ai-langgraph-workflows-mcp-12-o1","label":"Read the resume trace"},{"objectiveRef":"mission-ai-langgraph-workflows-mcp-12-o2","label":"Confirm no repeated risk"},{"objectiveRef":"mission-ai-langgraph-workflows-mcp-12-o3","label":"Choose the correct verification"}],"task":"State the conclusion in one sentence: killed deliberately right after a checkpoint, the workflow restarted, restored its exact state, resumed after the last completed node, and never re-ran verify_checksum or took any action twice -- proof the checkpointing and durable execution design actually holds under a real interruption."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-langgraph-workflows-mcp-12-o1","mission-ai-langgraph-workflows-mcp-12-o2","mission-ai-langgraph-workflows-mcp-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-langgraph-workflows-mcp-01-o1-c1', 'orientation', 'Think about what does work, what connects work, and what carries data between them.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-01-o1-c1', 'solution', 'Nodes do the work, edges are the allowed transitions, and state is the data passed along and updated at each step.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-01-o2-c1', 'orientation', 'Ask whether each item performs work, connects two steps, or just holds data.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-01-o2-c1', 'solution', 'Checking a checksum and reading a log are nodes. The path taken after a mismatch is an edge. The running list of checked records is state.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-02-o1-c1', 'orientation', 'Think about what lets a node act without re-reading and reinterpreting a wall of prior text.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-02-o1-c1', 'solution', 'A useful schema names exact fields -- records_checked, pending_approval -- that every node can read and update directly.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-02-o2-c1', 'orientation', 'Match each field name to the one fact it is clearly meant to hold.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-02-o2-c1', 'solution', 'records_checked tracks what has been examined, current_findings tracks conclusions, pending_approval tracks sign-off status, checkpoint_id tracks the resume point.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-03-o1-c1', 'orientation', 'Ask what the edge actually reads before it decides.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-03-o1-c1', 'solution', 'A routing function reads the current state and returns which node should run next, based on what it finds.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-03-o2-c1', 'orientation', 'The routing function''s logic was not wrong. Check what field it was actually reading from.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-03-o2-c1', 'solution', 'e3: the checksum node wrote its result to state.result, not state.checksum_result -- the field the routing function actually reads -- so the routing function never saw the real value.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-04-o1-c1', 'orientation', 'Think about what gets saved, and what saving it durably actually protects against.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-04-o1-c1', 'solution', 'A checkpoint is a durable, saved snapshot of the full state, written after a node finishes, that a workflow can resume from.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-04-o2-c1', 'orientation', 'Nothing can be written before the node has actually produced an updated state.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-04-o2-c1', 'solution', 'The node finishes and produces updated state, the state is serialized, it is written durably tagged to this run and step, then the graph proceeds only once the write succeeds.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-05-o1-c1', 'orientation', 'Focus on what resuming is supposed to skip, not just what it restores.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-05-o1-c1', 'solution', 'Durable execution restores state from the last checkpoint and skips re-running nodes whose work was already saved.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-05-o2-c1', 'orientation', 'The checkpoint itself was fine. Look at what the restart actually did with it.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-05-o2-c1', 'solution', 'e2: the restart restored state correctly but resumed execution from the first node instead of the node after the last checkpoint, so verify_checksum and quarantine_record ran a second time.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-06-o1-c1', 'orientation', 'Think about what happens to the workflow, and to the state, the moment it hits the gate.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-06-o1-c1', 'solution', 'The gate pauses the graph, checkpoints the state, and waits for a human decision before continuing.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-06-o2-c1', 'orientation', 'Ask whether getting this step wrong is expensive and hard to undo.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-06-o2-c1', 'solution', 'Quarantining a record and escalating a confirmed finding are irreversible enough to need a gate. Reading a log and verifying a checksum have no side effect and can run freely.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-07-o1-c1', 'orientation', 'Ask what stays the same across every tool, no matter which server it comes from.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-07-o1-c1', 'solution', 'MCP gives one standard interface for discovering and using tools, resources, and prompts, from any compliant server.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-07-o2-c1', 'orientation', 'Nothing can be selected before the client knows what a server actually exposes.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-07-o2-c1', 'solution', 'Connect to the server, the server advertises what it exposes, the client selects and calls a tool, the server executes it and returns a structured result.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-08-o1-c1', 'orientation', 'Ask which primitive acts, which one just reads, and which one is a reusable template.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-08-o1-c1', 'solution', 'Tools act and can have side effects, resources are read-only data, prompts are reusable task templates.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-08-o2-c1', 'orientation', 'Anything that changes something is a tool. Anything just read is a resource. A reusable template is a prompt.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-08-o2-c1', 'solution', 'quarantine_record and verify_checksum are tools, the migration log contents are a resource, and the characterize-record template is a prompt.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-09-o1-c1', 'orientation', 'One side exposes capabilities. The other side connects and uses them.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-09-o1-c1', 'solution', 'A server exposes tools, resources, and prompts. A client connects to a server and consumes what it exposes.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-09-o2-c1', 'orientation', 'The network is fine. Ask which role checksum_service was actually built to play.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-09-o2-c1', 'solution', 'e1: checksum_service was built as a client, not a server, so it has nothing to advertise and the investigation agent -- itself a client -- has no server to connect to.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-10-o1-c1', 'orientation', 'Think about scope: what a client actually needs, versus everything the server could technically offer.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-10-o1-c1', 'solution', 'Least privilege means a client only gets the specific tools it needs, not the server''s full capability set.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-10-o2-c1', 'orientation', 'Ask where the archive''s original poisoning came from in the first place.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-10-o2-c1', 'solution', 'Tool output is still untrusted input downstream -- treating it as safe just because it came from your own server repeats the exact mistake that poisoned the archive.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-11-o1-c1', 'orientation', 'Think about what the routing function needs to exist, and what a resume needs to find, once this node is done.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-11-o1-c1', 'solution', 'Its updated state must be checkpointed, and the routing function decides the next node by reading that saved state.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-11-o2-c1', 'orientation', 'Nothing irreversible can happen before the approval gate, and nothing can resume before a checkpoint exists to resume from.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-11-o2-c1', 'solution', 'Ingest, verify checksum through MCP with checkpointing, route on the result, deep-check with checkpointing, pause at the approval gate before anything irreversible, resume and act, then conclude.', 20, 2),

  ('mission-ai-langgraph-workflows-mcp-12-o1-c1', 'orientation', 'Most of the trace is boring on purpose -- look for the one line marking exactly where execution picked back up.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-12-o1-c1', 'concept', 'A resumed workflow restarting cleanly at node one would still look like it came back -- that alone does not prove the checkpoint was actually used.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-12-o1-c1', 'solution', 'e2: the restart loaded the checkpoint for ai-arc-0447 and resumed at the node after checksum-routing, not at the graph''s first node.', 30, 3),
  ('mission-ai-langgraph-workflows-mcp-12-o2-c1', 'orientation', 'Check whether verify_checksum shows up anywhere at all after the restart.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-12-o2-c1', 'solution', 'e2: verify_checksum never runs again after the restart -- the deep-check node used the already-checkpointed result directly.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-12-o3-c1', 'orientation', 'A process restarting is not the same claim as a workflow resuming correctly.', 10, 1),
  ('mission-ai-langgraph-workflows-mcp-12-o3-c1', 'solution', 'Matching restored state, resuming after the last completed node, and no repeated side-effecting step -- together -- is what actually proves it worked.', 20, 2),
  ('mission-ai-langgraph-workflows-mcp-12-o4-c1', 'orientation', 'Combine what the trace showed, what did not repeat, and what that proves.', 15, 1),
  ('mission-ai-langgraph-workflows-mcp-12-o4-c1', 'solution', 'Killed right after a checkpoint, the workflow restarted, restored its exact state, resumed after the last completed node, and never repeated verify_checksum or any other action -- the checkpointing and durable execution design held under a real interruption.', 25, 2);
