-- Robotics/Embedded/IoT pathway ("Vector Division") Act 9 -- "Runaway
-- Motor" content, under world-vec-actuators (already inserted separately,
-- Arc II "Firmware Controls Reality"). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as Acts 1 and 2. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram, browser_simulation (generic console fallback) and
-- boss_encounter. Picks up immediately after Act 8's live, calibrated
-- proximity sensor: Vector Division now tests the door's actual motor and
-- driver on the bench, discovers the emergency stop does not cut motor
-- power, and closes on Sera Holt naming the real fail-safe fix -- while a
-- second, live incident (a Nexus reactor arm oscillating) opens Act 10.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-actuators', 'world-vec-actuators', 'actuators', '2D - Runaway Motor', 'Learn the vocabulary of actuation itself -- DC motors, motor drivers, PWM speed control, servos, steppers, relays, solenoids, encoders, closed-loop motion and emergency stops -- while Vector Division discovers that a trustworthy sensor is only half the loop, and the door''s motor does not stop when it is told to.', 9);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-actuators-1', 'campaign-vec-actuators', 'the-other-half-of-the-loop', 'The Other Half of the Loop', 'Actuator fundamentals, DC motors, motor drivers, PWM speed control, servo motors and stepper motors.', 1),
  ('operation-vec-actuators-2', 'campaign-vec-actuators', 'the-line-that-was-never-power', 'The Line That Was Never Power', 'Relays, solenoids, encoders, closed-loop motion, emergency stops and the runaway motor itself.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-actuators-01', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'actuator-fundamentals', 'Actuator Fundamentals', 'With trustworthy sensor data in hand, Vector Division pulls the door''s motor assembly onto the bench to test it directly -- and it does not stop when the emergency stop is triggered.', 'beginner', ARRAY['imani','tomas','byte'], null, null, '{"type":"simulation","simulationId":"actuator-fundamentals-sim"}'::jsonb, '{"xp":160,"credits":20}'::jsonb, false, 1),
  ('mission-vec-actuators-02', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'dc-motors', 'DC Motors', 'A DC motor has no idea what a command is. Feed it voltage across two terminals and it turns -- that simplicity is exactly why so much can go wrong outside the motor itself.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-actuators-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"dc-motors-sim"}'::jsonb, '{"xp":160,"credits":25}'::jsonb, false, 2),
  ('mission-vec-actuators-03', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'motor-drivers', 'Motor Drivers', 'A controller''s logic pins cannot push the current a motor needs. A motor driver sits between the two -- and everything it does, it does through one enable line worth understanding precisely.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-actuators-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"motor-drivers-sim"}'::jsonb, '{"xp":170,"credits":25}'::jsonb, false, 3),
  ('mission-vec-actuators-04', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'pwm-speed-control', 'PWM Speed Control', 'A motor driver does not have a dial for speed. It has a switch flipped fast enough that the motor only feels the average -- and that average is the entire trick behind PWM.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-actuators-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"pwm-speed-control-sim"}'::jsonb, '{"xp":170,"credits":30}'::jsonb, false, 4),
  ('mission-vec-actuators-05', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'servo-motors', 'Servo Motors', 'A servo does not just spin. It holds a commanded angle against a load -- because somewhere inside its case, a feedback loop nobody outside has to manage is already running.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-actuators-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"servo-motors-sim"}'::jsonb, '{"xp":180,"credits":30}'::jsonb, false, 5),
  ('mission-vec-actuators-06', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-1', 'stepper-motors', 'Stepper Motors', 'A stepper motor does not know where it is either -- it only knows how many steps it has been told to take, which means one missed step is a lie it will repeat forever.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-actuators-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"stepper-motors-sim"}'::jsonb, '{"xp":180,"credits":30}'::jsonb, false, 6),
  ('mission-vec-actuators-07', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'relays', 'Relays', 'A relay is the oldest trick for letting a small, safe signal control a large, dangerous one -- an electromagnet and a mechanical switch, nothing more, and nothing less reliable when built correctly.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-actuators-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"relays-sim"}'::jsonb, '{"xp":190,"credits":35}'::jsonb, false, 7),
  ('mission-vec-actuators-08', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'solenoids', 'Solenoids', 'A solenoid does not rotate. It pulls, once, in a straight line -- and the door''s physical lock latch turns out to be exactly that kind of actuator, wired somewhere Byte never checked.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-actuators-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"solenoids-sim"}'::jsonb, '{"xp":190,"credits":35}'::jsonb, false, 8),
  ('mission-vec-actuators-09', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'encoders', 'Encoders', 'A command tells a motor what it should do. An encoder is the only device on the bench that will tell you what the motor actually did -- and the two are not always the same.', 'beginner', ARRAY['tomas'], '{"requiredMissionIds":["mission-vec-actuators-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"encoders-sim"}'::jsonb, '{"xp":200,"credits":35}'::jsonb, false, 9),
  ('mission-vec-actuators-10', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'closed-loop-motion', 'Closed-Loop Motion', 'An open-loop command is a hope. A closed-loop system checks the encoder against the command constantly and corrects the difference -- which is precisely the evidence about to prove the motor never lost its command at all.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-actuators-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"closed-loop-motion-sim"}'::jsonb, '{"xp":200,"credits":40}'::jsonb, false, 10),
  ('mission-vec-actuators-11', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'emergency-stops', 'Emergency Stops', 'An emergency stop is not one part. It is a whole chain, from a button to whatever it actually interrupts -- and Sera Holt wants that chain traced link by link before anyone touches this door''s motor again.', 'beginner', ARRAY['sera','tomas'], '{"requiredMissionIds":["mission-vec-actuators-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"emergency-stops-sim"}'::jsonb, '{"xp":210,"credits":40}'::jsonb, false, 11),
  ('mission-vec-actuators-12', 'world-vec-actuators', 'campaign-vec-actuators', 'operation-vec-actuators-2', 'runaway-motor', 'Runaway Motor', 'Everything this Act taught, turned on one bench test: why the emergency stop fired and the motor kept turning anyway -- and what has to change before Vector Division trusts an e-stop on anything again.', 'boss', ARRAY['imani','tomas','byte','sera'], '{"requiredMissionIds":["mission-vec-actuators-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"runaway-motor-boss-sim"}'::jsonb, '{"xp":800,"credits":170,"badgeIds":["runaway-motor"],"skillXp":{"robotics_fundamentals":100}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-actuators-01', 1, 'imani', 'The proximity sensor is calibrated and filtered. It reports the truth now. So we are done with the door, correct?'),
  ('mission-vec-actuators-01', 2, 'tomas', 'A sensor that can be trusted is only half the loop, Commander. The other half is whatever the door does in response -- its actuators. We pulled the motor assembly onto the bench to test it directly, on its own, before we ever trust it wired back into the door.'),
  ('mission-vec-actuators-01', 3, 'byte', 'First bench run, standard test procedure. Motor spun up clean on command. Then I triggered the emergency stop input exactly as documented.'),
  ('mission-vec-actuators-01', 4, 'byte', 'The motor did not stop. It kept turning for a full two seconds after the e-stop signal fired, at full commanded speed, before someone cut power at the wall.'),
  ('mission-vec-actuators-01', 5, 'tomas', 'That is not a calibration problem and it is not a sensor problem. That is an actuator that ignored a safety command. We are going to learn what a motor, a driver and an emergency stop actually are, in that order, before we ask why one of them failed.'),
  ('mission-vec-actuators-01', 6, 'imani', 'Understood. Nobody touches that bench again until you can tell me exactly what an e-stop is supposed to interrupt, and exactly what this one actually interrupted instead.'),

  ('mission-vec-actuators-02', 1, 'tomas', 'An actuator is anything that converts a control signal into physical force or motion -- motors, solenoids, relays, all of it. The motor on our bench is the actuator here. Everything else is what talks to it.'),
  ('mission-vec-actuators-02', 2, 'tomas', 'A DC motor is about as simple as actuation gets. Apply voltage across its two terminals and it turns. Reverse the polarity and it turns the other way. It has no firmware, no memory, and no idea an emergency stop exists -- it only ever knows the voltage it is currently receiving.'),

  ('mission-vec-actuators-03', 1, 'tomas', 'A microcontroller''s output pin can supply a few milliamps at a few volts. This motor wants amps, not milliamps. A motor driver is the circuit that sits between the two -- it takes a small logic-level signal in and switches large motor current out.'),
  ('mission-vec-actuators-03', 2, 'tomas', 'Every motor driver I have worked with has an enable line: a single pin that, when held high, lets the driver pass current to the motor at all, and when pulled low, tells the driver to stop passing current regardless of any other input.'),
  ('mission-vec-actuators-03', 3, 'byte', 'So the enable line is not the motor''s power. It is a permission signal to the driver, and the driver is what actually switches the power.'),

  ('mission-vec-actuators-04', 1, 'tomas', 'A motor driver rarely gives you a smooth analog voltage to control speed. Instead it switches full voltage on and off very fast, and the motor -- too slow to react to each individual switch -- only feels the average.'),
  ('mission-vec-actuators-04', 2, 'tomas', 'That is pulse-width modulation. The percentage of each cycle spent on, the duty cycle, sets the effective average voltage. Fifty percent duty cycle at 12 volts behaves, to the motor, like roughly 6 volts held steady.'),

  ('mission-vec-actuators-05', 1, 'tomas', 'A plain DC motor only knows voltage in, rotation out. A servo motor is a small package built around one: a DC motor, a gear train, a position sensor, and a tiny control loop, all sealed inside one case.'),
  ('mission-vec-actuators-05', 2, 'tomas', 'Send it a target angle and it drives itself there and holds -- fighting back against a load trying to push it off that angle. You never see the internal loop. You only ever see the angle it commits to.'),

  ('mission-vec-actuators-06', 1, 'tomas', 'A stepper motor moves in fixed increments, one discrete step at a time, instead of spinning continuously. Send it one pulse, it rotates exactly one step. Send it a thousand pulses, it has moved exactly a thousand steps -- in theory.'),
  ('mission-vec-actuators-06', 2, 'tomas', 'In theory, because a stepper has no idea whether a step it was commanded to take actually happened. If the load stalls it and it misses one step, the motor''s internal count still says it moved. It will be wrong by that same amount forever, until something re-references it.'),

  ('mission-vec-actuators-07', 1, 'tomas', 'A relay is the blunt-force version of a driver: an electromagnetic coil that, when energized by a small safe signal, pulls a mechanical switch closed on a completely separate, much larger circuit.'),
  ('mission-vec-actuators-07', 2, 'tomas', 'The two sides never touch electrically. That isolation is the entire reason relays still show up in safety wiring decades after transistor drivers got cheap -- a coil failing does not put mains voltage on your logic board.'),

  ('mission-vec-actuators-08', 1, 'tomas', 'A solenoid is a coil wrapped around a movable metal core. Energize the coil and the core snaps in one straight-line motion, usually a pull, sometimes a push. No rotation, no continuous motion -- one throw, on or off.'),
  ('mission-vec-actuators-08', 2, 'byte', 'I finally found the door''s physical lock latch in the archived wiring. It is a solenoid, on its own separate circuit -- one I never had visibility into, because nothing about a solenoid firing looks like network traffic.'),

  ('mission-vec-actuators-09', 1, 'tomas', 'A command says what a motor should do. An encoder is a sensor, usually mounted right on the motor shaft, that reports what the motor actually did -- typically as a stream of pulses you can count to get position or speed.'),
  ('mission-vec-actuators-09', 2, 'tomas', 'Command and encoder are supposed to agree. When they do not, the encoder is telling you something real happened that the command alone could never have shown you.'),

  ('mission-vec-actuators-10', 1, 'tomas', 'Open-loop control sends a command and hopes. Closed-loop control sends a command, reads the encoder, compares the two, and continuously corrects the difference -- a loop running many times a second, not a one-shot instruction.'),
  ('mission-vec-actuators-10', 2, 'byte', 'Which means if a closed-loop system''s encoder shows the motor still being driven after a stop command was issued, that is not the motor disobeying on its own. Something is still actively sending it drive commands.'),

  ('mission-vec-actuators-11', 1, 'sera', 'Sera Holt. I heard a motor kept running for two seconds after an emergency stop fired, and I want it understood, precisely, before this bench sees another test.'),
  ('mission-vec-actuators-11', 2, 'sera', 'An emergency stop is never one component. It is a chain: a trigger, a signal path, and whatever that path is actually wired to interrupt. Most e-stop failures I have investigated were never a broken button. They were a chain that interrupted the wrong link.'),
  ('mission-vec-actuators-11', 3, 'sera', 'Cutting a driver''s logic-level enable line is not the same as cutting the motor''s power rail. One tells the driver to stop passing current politely. The other makes current physically impossible. Confuse those two and your e-stop only works when everything downstream is already behaving.'),
  ('mission-vec-actuators-11', 4, 'tomas', 'Which is exactly the question this bench never answered: which of those two, on this door, does the e-stop actually reach.'),

  ('mission-vec-actuators-12', 1, 'imani', 'Two seconds of a motor ignoring an emergency stop is two seconds too many. Before this door''s motor goes anywhere near people again, I want the full chain traced and the failure explained.'),
  ('mission-vec-actuators-12', 2, 'sera', 'Trace the actual circuit the e-stop button feeds. Do not assume it reaches the motor''s power. Prove where it actually terminates.'),
  ('mission-vec-actuators-12', 3, 'byte', 'The encoder log during those two seconds is unambiguous. The motor kept receiving fresh drive commands the entire time the e-stop was asserted. Something was still actively telling it to turn.'),
  ('mission-vec-actuators-12', 4, 'tomas', 'And the enable line reading, pulled straight off the driver during the same window, is stuck. Not toggling, not floating -- held high, exactly as if the e-stop had never asserted at all.'),
  ('mission-vec-actuators-12', 5, 'sera', 'That line has cut this motor cleanly on every single test for thirty years. Thirty years of the enable signal never once failing on its own is not the same claim as the enable signal cannot fail. Somebody built a fail-safe on top of a component they never actually watched fail.'),
  ('mission-vec-actuators-12', 6, 'imani', 'Then tell me what actually happened, why it happened exactly this once, and what has to change so it cannot happen again. After that, we have a bigger problem -- a robotic arm at a Nexus reactor facility just started oscillating instead of holding still, and reacting to a runaway motor is not the same as controlling one precisely.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-actuators-01-o1', 'mission-vec-actuators-01', 1, 'Classify the failure', 'Judge what kind of failure a motor ignoring an emergency stop actually represents.'),
  ('mission-vec-actuators-01-o2', 'mission-vec-actuators-01', 2, 'Find the bench evidence', 'Identify which piece of bench evidence proves the motor kept turning after the e-stop fired.'),

  ('mission-vec-actuators-02-o1', 'mission-vec-actuators-02', 1, 'Define an actuator', 'Choose the accurate definition of an actuator.'),
  ('mission-vec-actuators-02-o2', 'mission-vec-actuators-02', 2, 'Predict the DC motor''s behavior', 'Judge what a DC motor does when its terminal voltage is reversed.'),

  ('mission-vec-actuators-03-o1', 'mission-vec-actuators-03', 1, 'Explain the driver''s role', 'Choose the accurate description of what a motor driver does.'),
  ('mission-vec-actuators-03-o2', 'mission-vec-actuators-03', 2, 'Define the enable line', 'Choose the accurate description of what a driver''s enable line actually controls.'),

  ('mission-vec-actuators-04-o1', 'mission-vec-actuators-04', 1, 'Compute the effective voltage', 'Given a duty cycle and supply voltage, choose the correct effective average voltage.'),
  ('mission-vec-actuators-04-o2', 'mission-vec-actuators-04', 2, 'Explain why PWM works', 'Choose the accurate reason a motor responds to PWM as a smooth average.'),

  ('mission-vec-actuators-05-o1', 'mission-vec-actuators-05', 1, 'Identify what is inside a servo', 'Sort each component into whether it is part of a sealed servo package.'),
  ('mission-vec-actuators-05-o2', 'mission-vec-actuators-05', 2, 'Explain servo holding behavior', 'Choose the accurate description of how a servo holds a commanded angle against a load.'),

  ('mission-vec-actuators-06-o1', 'mission-vec-actuators-06', 1, 'Explain open-loop stepping', 'Choose the accurate description of what happens when a stepper motor misses a step.'),
  ('mission-vec-actuators-06-o2', 'mission-vec-actuators-06', 2, 'Find the stall evidence', 'Identify which piece of evidence shows a stepper''s internal count no longer matches its true position.'),

  ('mission-vec-actuators-07-o1', 'mission-vec-actuators-07', 1, 'Explain relay isolation', 'Choose the accurate reason relays are still used in safety wiring.'),

  ('mission-vec-actuators-08-o1', 'mission-vec-actuators-08', 1, 'Tell solenoids from motors', 'Sort each actuator description into solenoid or rotating motor.'),
  ('mission-vec-actuators-08-o2', 'mission-vec-actuators-08', 2, 'Find the hidden circuit', 'Identify which piece of evidence shows the door''s lock latch is wired on a separate circuit Byte never monitored.'),

  ('mission-vec-actuators-09-o1', 'mission-vec-actuators-09', 1, 'Define the encoder''s role', 'Choose the accurate distinction between a command and an encoder reading.'),
  ('mission-vec-actuators-09-o2', 'mission-vec-actuators-09', 2, 'Read a mismatch', 'Judge what it means when an encoder reading disagrees with the last issued command.'),

  ('mission-vec-actuators-10-o1', 'mission-vec-actuators-10', 1, 'Tell open-loop from closed-loop', 'Choose the accurate distinction between open-loop and closed-loop control.'),
  ('mission-vec-actuators-10-o2', 'mission-vec-actuators-10', 2, 'Interpret the bench encoder log', 'Given the bench encoder log, judge whether the motor was still receiving drive commands after the stop was issued.'),

  ('mission-vec-actuators-11-o1', 'mission-vec-actuators-11', 1, 'Order the e-stop chain', 'Order an emergency stop chain from trigger to physical interruption.'),
  ('mission-vec-actuators-11-o2', 'mission-vec-actuators-11', 2, 'Tell enable-cut from power-cut', 'Choose the accurate distinction between cutting a driver''s enable line and cutting motor power.'),

  ('mission-vec-actuators-12-o1', 'mission-vec-actuators-12', 1, 'Trace the actual e-stop circuit', 'Identify which piece of evidence proves the e-stop was wired to the driver''s enable line, not motor power.'),
  ('mission-vec-actuators-12-o2', 'mission-vec-actuators-12', 2, 'Prove the stuck bit', 'Given the driver and encoder telemetry, judge what it proves about why the motor kept turning.'),
  ('mission-vec-actuators-12-o3', 'mission-vec-actuators-12', 3, 'State the correct fail-safe redesign', 'Choose the accurate fix for the emergency-stop chain.'),
  ('mission-vec-actuators-12-o4', 'mission-vec-actuators-12', 4, 'Deliver the diagnosis', 'Having traced the circuit, proven the stuck bit, and named the fix, state the full diagnosis of the runaway motor.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-actuators-01-o1-c1', 'mission-vec-actuators-01-o1', 1, 'multiple_choice', 'The motor kept turning for two seconds at full commanded speed after the emergency stop signal fired. What kind of failure does that represent?', '{"question":"The motor kept turning for two seconds at full commanded speed after the emergency stop signal fired. What kind of failure does that represent?","options":[{"id":"a","text":"A sensor calibration error, since the door''s proximity sensor was only just fixed"},{"id":"b","text":"An actuator-side safety failure -- the motor did not disengage when a safety command told it to, which is a different category of problem than a mis-sensed distance"},{"id":"c","text":"Normal behavior, all motors coast briefly after any stop command"},{"id":"d","text":"A network failure, since the e-stop signal must not have reached the bench at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-01-o2-c1', 'mission-vec-actuators-01-o2', 1, 'investigation', 'Which piece of bench evidence proves the motor kept turning after the emergency stop fired?', '{"evidence":[{"id":"e1","label":"Proximity sensor log","detail":"Calibrated sensor reported accurate distance readings throughout the test, unrelated to the motor"},{"id":"e2","label":"Bench test log","detail":"Motor speed telemetry shows full commanded RPM continuing for two full seconds after the e-stop input was asserted"},{"id":"e3","label":"Facilities note","detail":"The bench power supply is rated for continuous operation"}],"question":"Which piece of bench evidence proves the motor kept turning after the emergency stop fired?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-actuators-02-o1-c1', 'mission-vec-actuators-02-o1', 1, 'multiple_choice', 'An actuator is best defined as...', '{"question":"An actuator is best defined as...","options":[{"id":"a","text":"Any device that measures a physical quantity"},{"id":"b","text":"A device that converts a control signal into physical force or motion"},{"id":"c","text":"Any component that stores electrical energy"},{"id":"d","text":"A device that only ever produces rotational motion"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-02-o2-c1', 'mission-vec-actuators-02-o2', 1, 'multiple_choice', 'A DC motor is spinning clockwise. Its terminal voltage polarity is reversed. What happens?', '{"question":"A DC motor is spinning clockwise. Its terminal voltage polarity is reversed. What happens?","options":[{"id":"a","text":"It stops and stays stopped until polarity is restored"},{"id":"b","text":"It reverses direction, spinning counterclockwise -- the motor only ever responds to the voltage currently present at its terminals"},{"id":"c","text":"It speeds up in the same direction"},{"id":"d","text":"Nothing changes, DC motors ignore polarity"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-03-o1-c1', 'mission-vec-actuators-03-o1', 1, 'multiple_choice', 'A motor driver''s job is to...', '{"question":"A motor driver''s job is to...","options":[{"id":"a","text":"Replace the need for a controller entirely"},{"id":"b","text":"Take a small logic-level control signal and switch the larger current a motor actually needs, since a controller pin cannot supply that current directly"},{"id":"c","text":"Store energy for the motor to draw on later"},{"id":"d","text":"Convert motor motion back into a sensor signal"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-03-o2-c1', 'mission-vec-actuators-03-o2', 1, 'multiple_choice', 'A driver''s enable line, when pulled low, does what?', '{"question":"A driver''s enable line, when pulled low, does what?","options":[{"id":"a","text":"Physically disconnects the motor''s power rail at a switch"},{"id":"b","text":"Tells the driver''s internal logic to stop passing current to the motor -- a permission signal to the driver, not a cut on the motor''s power rail itself"},{"id":"c","text":"Reverses the motor''s direction"},{"id":"d","text":"Has no effect unless the motor is already stopped"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-04-o1-c1', 'mission-vec-actuators-04-o1', 1, 'multiple_choice', 'A 12 volt supply is switched with a 25 percent duty cycle. What is the approximate effective voltage the motor experiences?', '{"question":"A 12 volt supply is switched with a 25 percent duty cycle. What is the approximate effective voltage the motor experiences?","options":[{"id":"a","text":"12 volts, duty cycle does not affect voltage"},{"id":"b","text":"Roughly 3 volts (25 percent of 12)"},{"id":"c","text":"25 volts"},{"id":"d","text":"0 volts, since it is off most of the time"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-04-o2-c1', 'mission-vec-actuators-04-o2', 1, 'multiple_choice', 'Why does a motor respond to a fast-switched PWM signal as a smooth average speed instead of jerking on and off?', '{"question":"Why does a motor respond to a fast-switched PWM signal as a smooth average speed instead of jerking on and off?","options":[{"id":"a","text":"The driver secretly smooths the voltage into a true analog signal first"},{"id":"b","text":"The motor''s mechanical inertia is too slow to react to each individual on/off switch, so it physically responds only to the average power delivered"},{"id":"c","text":"PWM only works below a certain voltage"},{"id":"d","text":"It does jerk, smoothness is an illusion of the sensor readings"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-05-o1-c1', 'mission-vec-actuators-05-o1', 1, 'drag_and_drop', 'Sort each item into whether it is sealed inside a standard servo package or not.', '{"items":[{"id":"i1","text":"A small DC motor"},{"id":"i2","text":"A gear train"},{"id":"i3","text":"A position sensor for feedback"},{"id":"i4","text":"A separate motor driver chip the user must wire externally"}],"targets":[{"id":"inside","label":"Sealed inside the servo package"},{"id":"outside","label":"Not part of the servo package"}]}'::jsonb, '{"correctMapping":{"i1":"inside","i2":"inside","i3":"inside","i4":"outside"}}'::jsonb),
  ('mission-vec-actuators-05-o2-c1', 'mission-vec-actuators-05-o2', 1, 'multiple_choice', 'A servo is commanded to hold 90 degrees while a load tries to push it toward 80 degrees. What happens?', '{"question":"A servo is commanded to hold 90 degrees while a load tries to push it toward 80 degrees. What happens?","options":[{"id":"a","text":"It drifts to 80 degrees and stays there, servos cannot resist a load"},{"id":"b","text":"Its internal feedback loop continuously senses the deviation and drives the motor to fight back toward 90 degrees, without any external command needed"},{"id":"c","text":"It shuts off entirely to protect itself"},{"id":"d","text":"It oscillates uncontrollably with no way to settle"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-06-o1-c1', 'mission-vec-actuators-06-o1', 1, 'multiple_choice', 'A stepper motor is commanded to take 1,000 steps but stalls and physically misses 3 of them. What does the motor''s internal step count now show?', '{"question":"A stepper motor is commanded to take 1,000 steps but stalls and physically misses 3 of them. What does the motor''s internal step count now show?","options":[{"id":"a","text":"997, the motor automatically detects and corrects the missed steps"},{"id":"b","text":"1,000 -- an open-loop stepper has no way to sense a missed step, so its internal count will be wrong by exactly 3 steps until something re-references its true position"},{"id":"c","text":"0, a stall resets the count entirely"},{"id":"d","text":"The motor stops issuing any further steps once one is missed"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-06-o2-c1', 'mission-vec-actuators-06-o2', 1, 'investigation', 'Which piece of evidence shows a stepper''s internal count no longer matches its true position?', '{"evidence":[{"id":"e1","label":"Command log","detail":"Controller issued exactly 1,000 step pulses and believes the motor is now 1,000 steps from home"},{"id":"e2","label":"External position check","detail":"A separate physical measurement shows the shaft only 997 steps from home"},{"id":"e3","label":"Power log","detail":"Supply voltage to the stepper stayed within normal range throughout"}],"question":"Which piece of evidence shows a stepper''s internal count no longer matches its true position?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-actuators-07-o1-c1', 'mission-vec-actuators-07-o1', 1, 'multiple_choice', 'Why do relays still show up in safety-critical wiring even though transistor-based drivers are cheaper and faster?', '{"question":"Why do relays still show up in safety-critical wiring even though transistor-based drivers are cheaper and faster?","options":[{"id":"a","text":"Relays are always faster than transistor drivers"},{"id":"b","text":"A relay''s coil and switched contacts are electrically isolated from each other, so a failure on the control side cannot put dangerous voltage directly onto the logic side"},{"id":"c","text":"Relays never fail, unlike transistors"},{"id":"d","text":"Relays require no power to operate"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-08-o1-c1', 'mission-vec-actuators-08-o1', 1, 'drag_and_drop', 'Sort each actuator description into solenoid or rotating motor.', '{"items":[{"id":"a1","text":"A coil that pulls a metal core in one straight-line motion when energized"},{"id":"a2","text":"A shaft that spins continuously as long as voltage is applied"},{"id":"a3","text":"A door lock latch that snaps in or out with a single throw"},{"id":"a4","text":"A device that turns fixed increments, one discrete step at a time"}],"targets":[{"id":"solenoid","label":"Solenoid"},{"id":"rotating","label":"Rotating motor"}]}'::jsonb, '{"correctMapping":{"a1":"solenoid","a2":"rotating","a3":"solenoid","a4":"rotating"}}'::jsonb),
  ('mission-vec-actuators-08-o2-c1', 'mission-vec-actuators-08-o2', 1, 'investigation', 'Which piece of evidence shows the door''s lock latch is wired on a separate circuit Byte never monitored?', '{"evidence":[{"id":"e1","label":"Archived wiring diagram","detail":"The lock latch solenoid is powered from its own dedicated circuit with no connection to any network-monitored controller"},{"id":"e2","label":"Facilities note","detail":"The door housing is painted the same color as the rest of the corridor"},{"id":"e3","label":"Power log","detail":"Overall facility power draw stayed within normal range"}],"question":"Which piece of evidence shows the door''s lock latch is wired on a separate circuit Byte never monitored?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-actuators-09-o1-c1', 'mission-vec-actuators-09-o1', 1, 'multiple_choice', 'A command and an encoder reading differ in that...', '{"question":"A command and an encoder reading differ in that...","options":[{"id":"a","text":"They are the same value, just reported through different wires"},{"id":"b","text":"A command states what a motor should do; an encoder reports what the motor actually did -- and the two are not guaranteed to agree"},{"id":"c","text":"Encoders only exist on stepper motors"},{"id":"d","text":"Commands are always more accurate than encoders"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-09-o2-c1', 'mission-vec-actuators-09-o2', 1, 'multiple_choice', 'An encoder shows a motor shaft still turning at full speed, but the last issued command was a stop. What does that mismatch mean?', '{"question":"An encoder shows a motor shaft still turning at full speed, but the last issued command was a stop. What does that mismatch mean?","options":[{"id":"a","text":"The encoder is malfunctioning, since the command is always correct"},{"id":"b","text":"Something is real about the discrepancy -- either the motor is coasting on its own with no drive, or something is still actively driving it despite the stop command"},{"id":"c","text":"The mismatch is meaningless and can be ignored"},{"id":"d","text":"The motor has switched into a mode where it ignores all future commands permanently"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-10-o1-c1', 'mission-vec-actuators-10-o1', 1, 'multiple_choice', 'Open-loop and closed-loop control differ in that...', '{"question":"Open-loop and closed-loop control differ in that...","options":[{"id":"a","text":"Open-loop sends a command and never checks the result; closed-loop continuously compares a feedback reading against the command and corrects the difference"},{"id":"b","text":"They are two names for the same technique"},{"id":"c","text":"Closed-loop is always slower than open-loop"},{"id":"d","text":"Open-loop is only used with stepper motors"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-actuators-10-o2-c1', 'mission-vec-actuators-10-o2', 1, 'browser_simulation', 'Given this bench encoder log spanning the e-stop event, was the motor still receiving drive commands after the stop was issued?', '{"screen":"BENCH ENCODER LOG -- MOTOR TEST -- T+0.0s TO T+2.0s","question":"Given this bench encoder log spanning the e-stop event, was the motor still receiving drive commands after the stop was issued?","records":[{"id":"r1","code":"T+0.0s ESTOP_ASSERTED","detail":"Emergency stop input asserted, motor at full commanded RPM"},{"id":"r2","code":"T+0.5s ENCODER=full_rpm","detail":"Encoder still reads full commanded RPM, no decay -- consistent with fresh drive commands continuing to arrive, not coasting"},{"id":"r3","code":"T+1.0s ENCODER=full_rpm","detail":"Encoder still reads full commanded RPM, unchanged"},{"id":"r4","code":"T+2.0s POWER_CUT_MANUAL","detail":"Wall power manually cut, motor stops immediately"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),

  ('mission-vec-actuators-11-o1-c1', 'mission-vec-actuators-11-o1', 1, 'interactive_diagram', 'Order the emergency stop chain from trigger to physical interruption.', '{"diagramId":"estop-chain","hotspots":[{"id":"trigger","label":"Trigger","explanation":"The e-stop button or safety condition that initiates the stop."},{"id":"signal","label":"Signal path","explanation":"The wiring or logic carrying the stop signal from the trigger onward."},{"id":"interrupt","label":"Interruption point","explanation":"Whatever component the signal actually acts on -- this is the link that determines what really gets stopped."},{"id":"result","label":"Physical result","explanation":"The actual, physical consequence of that interruption -- motion stopping, or not."}],"task":"Order the stages of an emergency stop chain from trigger to physical result."}'::jsonb, '{"correctOrderIds":["trigger","signal","interrupt","result"]}'::jsonb),
  ('mission-vec-actuators-11-o2-c1', 'mission-vec-actuators-11-o2', 1, 'multiple_choice', 'Cutting a driver''s logic-level enable line and cutting a motor''s power rail differ in that...', '{"question":"Cutting a driver''s logic-level enable line and cutting a motor''s power rail differ in that...","options":[{"id":"a","text":"They are functionally identical, both always stop the motor with equal certainty"},{"id":"b","text":"Cutting the enable line asks the driver''s internal logic to stop passing current; cutting the power rail makes current physically impossible regardless of what the driver''s logic is doing"},{"id":"c","text":"Cutting the power rail is always the weaker of the two options"},{"id":"d","text":"Enable lines do not exist on real motor drivers"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-actuators-12-o1-c1', 'mission-vec-actuators-12-o1', 1, 'investigation', 'Which piece of evidence proves the door''s emergency stop was wired to the driver''s enable line rather than motor power?', '{"evidence":[{"id":"e1","label":"Original wiring schematic","detail":"The e-stop button''s output connects directly and only to the motor driver''s enable pin -- no path anywhere on the schematic runs to the motor''s power rail"},{"id":"e2","label":"Facilities note","detail":"The bench power supply is rated for continuous operation"},{"id":"e3","label":"Proximity sensor log","detail":"The calibrated sensor reported accurate readings throughout the incident"}],"question":"Which piece of evidence proves the door''s emergency stop was wired to the driver''s enable line rather than motor power?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-actuators-12-o2-c1', 'mission-vec-actuators-12-o2', 1, 'browser_simulation', 'Given the driver and encoder telemetry pulled during the two-second failure, what actually explains the motor continuing to run?', '{"screen":"DRIVER + ENCODER TELEMETRY -- E-STOP WINDOW -- T+0.0s TO T+2.0s","question":"Given the driver and encoder telemetry pulled during the two-second failure, what actually explains the motor continuing to run?","records":[{"id":"r1","code":"ESTOP_SIGNAL=ASSERTED@T+0.0s","detail":"Emergency stop input correctly asserted at the button, on schedule"},{"id":"r2","code":"ENABLE_PIN=HIGH throughout T+0.0s-T+2.0s","detail":"Driver''s enable pin read stuck HIGH for the entire window -- never dropped low despite the e-stop asserting, as if the stop signal never reached the driver at all"},{"id":"r3","code":"ENCODER=full_rpm throughout T+0.0s-T+2.0s","detail":"Encoder confirms the motor kept receiving live drive commands the entire window, consistent with the enable pin never actually disabling the driver"},{"id":"r4","code":"SUPPLY_RAIL=12.0V nominal","detail":"Motor power rail stayed at a normal, healthy voltage the entire time"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-actuators-12-o3-c1', 'mission-vec-actuators-12-o3', 1, 'multiple_choice', 'Given the enable line stuck high is what let the motor keep running, what is the correct fail-safe redesign?', '{"question":"Given the enable line stuck high is what let the motor keep running, what is the correct fail-safe redesign?","options":[{"id":"a","text":"Add a second enable line as a backup, wired the same way as the first"},{"id":"b","text":"Wire the emergency stop to physically cut motor power at the driver stage -- for example through a relay in series with the supply rail -- so a stuck logic-level enable signal can no longer keep the motor running"},{"id":"c","text":"Increase the PWM frequency so the driver responds faster"},{"id":"d","text":"Replace the DC motor with a stepper motor, since steppers cannot run away"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-actuators-12-o4-c1', 'mission-vec-actuators-12-o4', 1, 'boss_encounter', 'Having traced the actual e-stop circuit, proven the stuck enable line, and named the fix, deliver the full diagnosis of the runaway motor.', '{"stages":[{"objectiveRef":"mission-vec-actuators-12-o1","label":"Trace the actual e-stop circuit"},{"objectiveRef":"mission-vec-actuators-12-o2","label":"Prove the stuck bit"},{"objectiveRef":"mission-vec-actuators-12-o3","label":"State the correct fail-safe redesign"}],"task":"State the diagnosis in full: the emergency-stop line was wired to cut the motor driver''s logic-level enable signal, not the motor''s actual power rail -- a design that worked perfectly for thirty years because the enable signal never once failed on its own, until a single stuck bit made it fail exactly the way nobody had planned for. The fix is to cut power at the driver stage, not just the logic enable."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-actuators-12-o1","mission-vec-actuators-12-o2","mission-vec-actuators-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-actuators-01-o1-c1', 'orientation', 'Ask whether the motor failed to sense correctly, or failed to obey a command correctly.', 10, 1),
  ('mission-vec-actuators-01-o1-c1', 'solution', 'It is an actuator-side safety failure -- the motor did not disengage on a safety command, a different failure category than a sensor misreading distance.', 20, 2),
  ('mission-vec-actuators-01-o2-c1', 'orientation', 'Look for a log showing motor speed over time, not the proximity sensor.', 10, 1),
  ('mission-vec-actuators-01-o2-c1', 'solution', 'e2: the bench test log shows full commanded RPM continuing for two seconds after the e-stop input was asserted.', 20, 2),

  ('mission-vec-actuators-02-o1-c1', 'orientation', 'An actuator does not measure the world -- it changes it.', 10, 1),
  ('mission-vec-actuators-02-o1-c1', 'solution', 'An actuator converts a control signal into physical force or motion.', 20, 2),
  ('mission-vec-actuators-02-o2-c1', 'orientation', 'A DC motor only ever responds to the voltage present right now at its terminals.', 10, 1),
  ('mission-vec-actuators-02-o2-c1', 'solution', 'Reversing polarity reverses direction -- clockwise becomes counterclockwise.', 20, 2),

  ('mission-vec-actuators-03-o1-c1', 'orientation', 'A controller pin cannot supply the current a motor needs on its own.', 10, 1),
  ('mission-vec-actuators-03-o1-c1', 'solution', 'A motor driver takes a small logic-level signal and switches the larger current the motor actually needs.', 20, 2),
  ('mission-vec-actuators-03-o2-c1', 'orientation', 'The enable line talks to the driver''s logic, not directly to the motor''s power wires.', 10, 1),
  ('mission-vec-actuators-03-o2-c1', 'solution', 'Pulling enable low tells the driver''s internal logic to stop passing current -- it is a permission signal to the driver, not a physical cut on the power rail.', 20, 2),

  ('mission-vec-actuators-04-o1-c1', 'orientation', 'Multiply the supply voltage by the duty cycle as a fraction.', 10, 1),
  ('mission-vec-actuators-04-o1-c1', 'solution', '12V times 0.25 is 3 volts effective.', 20, 2),
  ('mission-vec-actuators-04-o2-c1', 'orientation', 'Think about how fast the switching happens compared to how fast the motor can physically respond.', 10, 1),
  ('mission-vec-actuators-04-o2-c1', 'solution', 'The motor''s mechanical inertia is too slow to react to each individual switch, so it physically averages the power delivered instead.', 20, 2),

  ('mission-vec-actuators-05-o1-c1', 'orientation', 'Ask what a servo needs internally to hold a position without the user managing a loop themselves.', 10, 1),
  ('mission-vec-actuators-05-o1-c1', 'solution', 'Inside: the motor, gear train, and position sensor. Outside: a separate driver chip is not part of a standard servo package.', 20, 2),
  ('mission-vec-actuators-05-o2-c1', 'orientation', 'The servo does not need a new external command to resist the load -- its own loop is already running.', 10, 1),
  ('mission-vec-actuators-05-o2-c1', 'solution', 'Its internal feedback loop continuously senses the deviation from 90 degrees and drives the motor to correct it, with no external command needed.', 20, 2),

  ('mission-vec-actuators-06-o1-c1', 'orientation', 'An open-loop stepper has no sensor telling it whether a step actually happened.', 10, 1),
  ('mission-vec-actuators-06-o1-c1', 'solution', 'The internal count still shows 1,000 -- it will be wrong by exactly the 3 missed steps until something externally re-references true position.', 20, 2),
  ('mission-vec-actuators-06-o2-c1', 'orientation', 'Look for a reading taken independently of the controller''s own step count.', 10, 1),
  ('mission-vec-actuators-06-o2-c1', 'solution', 'e2: an external physical position check showing only 997 steps traveled proves the internal count of 1,000 no longer matches reality.', 20, 2),

  ('mission-vec-actuators-07-o1-c1', 'orientation', 'Think about what happens on the logic side if the coil circuit fails.', 10, 1),
  ('mission-vec-actuators-07-o1-c1', 'solution', 'The coil and switched contacts are electrically isolated, so a control-side failure cannot put dangerous voltage directly onto the logic side.', 20, 2),

  ('mission-vec-actuators-08-o1-c1', 'orientation', 'Ask whether the motion is a single straight-line throw, or continuous/incremental rotation.', 10, 1),
  ('mission-vec-actuators-08-o1-c1', 'solution', 'Solenoid: the straight-line coil pull and the door latch throw. Rotating motor: the continuously spinning shaft and the discrete-step device.', 20, 2),
  ('mission-vec-actuators-08-o2-c1', 'orientation', 'Look for a wiring diagram, not a note about paint or overall power draw.', 10, 1),
  ('mission-vec-actuators-08-o2-c1', 'solution', 'e1: the archived wiring diagram shows the lock solenoid on its own dedicated circuit with no connection to any network-monitored controller.', 20, 2),

  ('mission-vec-actuators-09-o1-c1', 'orientation', 'One states an intent, the other reports a physical outcome.', 10, 1),
  ('mission-vec-actuators-09-o1-c1', 'solution', 'A command states what a motor should do; an encoder reports what it actually did -- and the two are not guaranteed to match.', 20, 2),
  ('mission-vec-actuators-09-o2-c1', 'orientation', 'Do not assume the command is automatically correct just because it was issued.', 10, 1),
  ('mission-vec-actuators-09-o2-c1', 'solution', 'The mismatch is real information: either the motor is coasting unpowered, or something is still actively driving it despite the stop command.', 20, 2),

  ('mission-vec-actuators-10-o1-c1', 'orientation', 'Ask whether the system ever checks its own result against the command.', 10, 1),
  ('mission-vec-actuators-10-o1-c1', 'solution', 'Open-loop never checks the result; closed-loop continuously compares feedback against the command and corrects the difference.', 20, 2),
  ('mission-vec-actuators-10-o2-c1', 'orientation', 'Compare the encoder value right after the e-stop against what coasting to a stop would look like.', 10, 1),
  ('mission-vec-actuators-10-o2-c1', 'solution', 'r2: the encoder holding at full RPM with no decay is consistent with fresh drive commands still arriving, not the motor simply coasting down.', 20, 2),

  ('mission-vec-actuators-11-o1-c1', 'orientation', 'Nothing can be interrupted before a signal reaches it, and nothing can produce a physical result before it is interrupted.', 10, 1),
  ('mission-vec-actuators-11-o1-c1', 'solution', 'Trigger, then signal path, then the interruption point, then the physical result.', 20, 2),
  ('mission-vec-actuators-11-o2-c1', 'orientation', 'One acts on the driver''s decision-making; the other acts on the wire carrying the current itself.', 10, 1),
  ('mission-vec-actuators-11-o2-c1', 'solution', 'Cutting enable asks the driver''s logic to stop passing current; cutting power makes current physically impossible no matter what the logic is doing.', 20, 2),

  ('mission-vec-actuators-12-o1-c1', 'orientation', 'Look for the original schematic tracing the e-stop button''s actual output path, not a note about the power supply or the sensor.', 10, 1),
  ('mission-vec-actuators-12-o1-c1', 'solution', 'e1: the schematic shows the e-stop output running only to the driver''s enable pin, with no path anywhere to the motor''s power rail.', 20, 2),
  ('mission-vec-actuators-12-o2-c1', 'orientation', 'Compare when the e-stop asserted against when the enable pin actually changed state.', 10, 1),
  ('mission-vec-actuators-12-o2-c1', 'solution', 'r2: the enable pin read stuck HIGH the entire window, never dropping low despite the e-stop asserting -- the stop signal never actually reached the driver''s logic.', 20, 2),
  ('mission-vec-actuators-12-o3-c1', 'orientation', 'The fix has to make the failure of one logic signal unable to keep current flowing.', 10, 1),
  ('mission-vec-actuators-12-o3-c1', 'solution', 'Cut motor power directly at the driver stage, such as with a relay in series on the supply rail, so a stuck enable signal alone can no longer keep the motor running.', 20, 2),
  ('mission-vec-actuators-12-o4-c1', 'orientation', 'Combine the circuit trace, the stuck-bit proof, and the fix into one diagnosis: what was wired, why it worked for thirty years, and why it failed this once.', 15, 1),
  ('mission-vec-actuators-12-o4-c1', 'solution', 'The emergency-stop line was wired to cut the motor driver''s logic-level enable signal, not the motor''s actual power rail -- a design that worked perfectly for thirty years because the enable signal never once failed on its own, until a single stuck bit made it fail exactly the way nobody had planned for. The fix is to cut power at the driver stage, not just the logic enable.', 25, 2);
