-- Phase 2.4t: world-19 mission content, generated from
-- docs/12-world-story-bible.md. Mission 1 is cross-world-gated on
-- the previous world's boss mission where applicable. World 19 opens
-- Act 3 (The Shield): Luna's first formal incident review, reframing
-- everything traced since World 0 in terms of risk and controls.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-19a', 'world-19', 'rules-of-defense', '19A - Rules of Defense', 'Luna convenes the Guardians'' first formal incident review after the Nexus Market key traced back to a service that should''ve been decommissioned. Time to think in risk and controls, not just artifacts.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-19a-1', 'campaign-19a', 'foundations', 'Foundations', 'CIA, authentication vs. authorization, least privilege, and threat/vulnerability/risk, learned by classifying systems already encountered in the field.', 1),
  ('operation-19a-2', 'campaign-19a', 'investigation', 'Investigation', 'Defense in depth and layered control design, applied to build a full protection plan for Nexus Market.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-w19-01', 'world-19', 'campaign-19a', 'operation-19a-1', 'incident-review', 'Rules of Defense', 'Luna convenes the Guardians'' first formal incident review. The recruit is asked to stop cataloguing artifacts and start reasoning about risk.', 'intro', ARRAY['luna', 'ava'], '{"requiredMissionIds":["mission-w18-06"]}'::jsonb, null, '{"type":"none"}'::jsonb, '{"xp":60,"credits":10}'::jsonb, false, 1),
  ('mission-w19-02', 'world-19', 'campaign-19a', 'operation-19a-1', 'three-pillars', 'The Three Pillars', 'Confidentiality, integrity and availability pull against each other. Every control decision trades one for another.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w19-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"cia-triad-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-w19-03', 'world-19', 'campaign-19a', 'operation-19a-1', 'who-goes-there', 'Who Goes There?', 'Authentication proves who you are. Authorization decides what you''re allowed to do once you''re in. Confusing the two is how privilege creeps.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w19-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"access-control-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 3),
  ('mission-w19-04', 'world-19', 'campaign-19a', 'operation-19a-1', 'threat-vulnerability-risk', 'Threat, Vulnerability, Risk', 'Three words people use interchangeably and shouldn''t. Getting them right decides what actually gets fixed first.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w19-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"risk-triage-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 4),
  ('mission-w19-05', 'world-19', 'campaign-19a', 'operation-19a-2', 'layers-of-defense', 'Layers of Defense', 'One control failing shouldn''t mean the whole system falls. Defense in depth, zero trust and attack surface, mapped onto systems you already know.', 'beginner', ARRAY['luna'], '{"requiredMissionIds":["mission-w19-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"defense-in-depth-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 5),
  ('mission-w19-06', 'world-19', 'campaign-19a', 'operation-19a-2', 'defend-nexus', 'Defend Nexus', 'Build a layered control plan for the Nexus Market breach and explain the residual risk that remains no matter what you deploy.', 'boss', ARRAY['luna', 'ava'], '{"requiredMissionIds":["mission-w19-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"rules-of-defense-boss-sim"}'::jsonb, '{"xp":300,"credits":60,"badgeIds":["rules-of-defense"],"skillXp":{"pentesting":50}}'::jsonb, true, 6);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-w19-01', 1, 'luna', 'Sit down. This isn''t a live incident -- it''s a review. We traced an API key back to a service that should''ve been decommissioned after Project SENTINEL, and nobody in this building can tell me why it was still running.'),
  ('mission-w19-01', 2, 'luna', 'Every world so far, you''ve asked what happened. Today I need a different question: what should have stopped this, and why didn''t it.'),
  ('mission-w19-01', 3, 'ava', 'It''s a different muscle. You''ve been chasing artifacts -- packets, binaries, log lines. Today we''re talking about risk and controls: what protects a system, and how well.'),
  ('mission-w19-01', 4, 'luna', 'We''ll use systems you already know. Nexus Market. SkyPort''s maintenance gateway. The sentinel-sync account. You''re not investigating them again -- you''re grading their defenses.'),
  ('mission-w19-02', 1, 'luna', 'CIA: confidentiality, integrity, availability. Every system you''ve touched had to balance the three, and every breach you''ve investigated broke at least one of them.'),
  ('mission-w19-03', 1, 'luna', 'Authentication proves who you are. Authorization decides what you''re allowed to do once you''re in. Most privilege creep starts by quietly confusing the two.'),
  ('mission-w19-04', 1, 'luna', 'Threat, vulnerability, risk. A threat is who or what might cause harm. A vulnerability is the weakness that lets them. Risk is the two multiplied by what''s actually at stake.'),
  ('mission-w19-05', 1, 'luna', 'No single control should be the only thing standing between an attacker and the objective. Build layers, and assume any one of them can fail.'),
  ('mission-w19-06', 1, 'luna', 'This is the review''s capstone. Build the layered plan for Nexus Market -- not just what would have stopped this specific key, but what keeps failing even after one layer does its job.'),
  ('mission-w19-06', 2, 'luna', 'Confirmed: no expiration, no scope, still valid eight months after the service should''ve been dead. That''s not a one-off mistake.'),
  ('mission-w19-06', 3, 'ava', 'I pulled records from three other organizations Guardian intel tracks. Two of them made the exact same design choice -- unscoped, non-expiring service credentials -- years before Nexus Market existed.'),
  ('mission-w19-06', 4, 'luna', 'Different companies, different industries, same compromise, years apart. That''s not coincidence. That''s a pattern.'),
  ('mission-w19-06', 5, 'luna', 'Which means our next question isn''t what broke. It''s who benefits from studying how things break. Time to learn how adversaries actually plan and behave.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-w19-01-o1', 'mission-w19-01', 1, 'Open the review', 'Confirm you''re ready to think in terms of risk and controls, not just artifacts.'),
  ('mission-w19-02-o1', 'mission-w19-02', 1, 'Classify the impact', 'Sort each scenario by which pillar of the CIA triad it actually violates.'),
  ('mission-w19-03-o1', 'mission-w19-03', 1, 'Tell the controls apart', 'Match each scenario to authentication, authorization, or least privilege.'),
  ('mission-w19-04-o1', 'mission-w19-04', 1, 'Sort threat from vulnerability from risk', 'Classify each statement correctly.'),
  ('mission-w19-05-o1', 'mission-w19-05', 1, 'Stack the layers', 'Order the controls from outermost to innermost, building a defense-in-depth stack.'),
  ('mission-w19-06-o1', 'mission-w19-06', 1, 'Diagnose the control failure', 'Find the evidence that explains how the stolen key kept working long after it should have been dead.'),
  ('mission-w19-06-o2', 'mission-w19-06', 2, 'Design the layered plan', 'Map each proposed control to the layer of defense it actually strengthens.'),
  ('mission-w19-06-o3', 'mission-w19-06', 3, 'Close the review', 'Confirm the root cause and the layered control plan for Nexus Market.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-w19-01-o1-c1', 'mission-w19-01-o1', 1, 'story_dialogue', 'Confirm you''re ready to continue.', '{"lines":[{"characterId":"luna","text":"Before we start: are you ready to reason about risk, not just artifacts?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),
  ('mission-w19-02-o1-c1', 'mission-w19-02-o1', 1, 'drag_and_drop', 'Sort each scenario by which pillar of the CIA triad it actually violates.', '{"items":[{"id":"p1","text":"Nexus Market''s stolen API key let an unauthorized service read every customer''s order history."},{"id":"p2","text":"The rogue SkyPort access point sat close enough to the maintenance controller to alter sensor values before they were logged."},{"id":"p3","text":"World 5''s route leak didn''t steal anything -- it delayed legitimate traffic long enough to measure how fast defenders noticed."},{"id":"p4","text":"The sentinel-sync account could read configuration files no service account should ever touch."}],"targets":[{"id":"confidentiality","label":"Confidentiality"},{"id":"integrity","label":"Integrity"},{"id":"availability","label":"Availability"}]}'::jsonb, '{"correctMapping":{"p1":"confidentiality","p2":"integrity","p3":"availability","p4":"confidentiality"}}'::jsonb),
  ('mission-w19-03-o1-c1', 'mission-w19-03-o1', 1, 'drag_and_drop', 'Match each scenario to authentication, authorization, or least privilege.', '{"items":[{"id":"a1","text":"A maintenance technician''s badge cryptographically proves it''s genuinely them, not just anyone holding a copy."},{"id":"a2","text":"Once verified, the system checks whether that specific technician is permitted to open the server room door, not just any door."},{"id":"a3","text":"The technician is issued a badge that opens only the two rooms their job actually requires, nothing more."},{"id":"a4","text":"sentinel-sync authenticates successfully every single time -- the real failure is that no one ever re-checked what it should still be allowed to touch."}],"targets":[{"id":"authentication","label":"Authentication"},{"id":"authorization","label":"Authorization"},{"id":"least_privilege","label":"Least Privilege"}]}'::jsonb, '{"correctMapping":{"a1":"authentication","a2":"authorization","a3":"least_privilege","a4":"authorization"}}'::jsonb),
  ('mission-w19-04-o1-c1', 'mission-w19-04-o1', 1, 'drag_and_drop', 'Classify each statement as a threat, a vulnerability, or a risk.', '{"items":[{"id":"t1","text":"An external actor willing to reuse leaked credentials against any service that will accept them."},{"id":"t2","text":"Nexus Market''s decommissioned service still accepted the old API key because no one ever revoked it."},{"id":"t3","text":"The likelihood that the unrevoked key gets reused, multiplied by the impact of exposing every customer''s order history."},{"id":"t4","text":"The maintenance network''s Wi-Fi clients trusted any access point broadcasting the right SSID, with no way to verify it was the real one."}],"targets":[{"id":"threat","label":"Threat"},{"id":"vulnerability","label":"Vulnerability"},{"id":"risk","label":"Risk"}]}'::jsonb, '{"correctMapping":{"t1":"threat","t2":"vulnerability","t3":"risk","t4":"vulnerability"}}'::jsonb),
  ('mission-w19-05-o1-c1', 'mission-w19-05-o1', 1, 'interactive_diagram', 'Order these controls from outermost to innermost, building a defense-in-depth stack for the SkyPort maintenance network.', '{"hotspots":[{"id":"perimeter","label":"Network segmentation keeping the maintenance VLAN away from the rest of campus","explanation":"The outermost boundary -- an attacker has to get past this before touching anything else."},{"id":"network_monitor","label":"Wireless intrusion detection watching for unrecognized BSSIDs","explanation":"Catches an intruder already inside radio range who hasn''t reached a host yet."},{"id":"host","label":"A hardened Linux gateway with sentinel-sync''s excess privileges revoked","explanation":"Assumes the network layer was bypassed -- the host itself should still resist misuse."},{"id":"app","label":"Authentication and authorization checks on the maintenance controller''s management interface","explanation":"Assumes someone reached the host -- the application itself still checks who they are and what they''re allowed to do."},{"id":"data","label":"Encrypted, access-logged sensor data at rest","explanation":"The last layer -- even if everything else fails, the data itself resists being read or silently altered."}],"task":"Order these controls from outermost to innermost, building a defense-in-depth stack for the SkyPort maintenance network."}'::jsonb, '{"correctOrderIds":["perimeter","network_monitor","host","app","data"]}'::jsonb),
  ('mission-w19-06-o1-c1', 'mission-w19-06-o1', 1, 'investigation', 'Which evidence explains how the stolen key kept working long after it should have been dead?', '{"evidence":[{"id":"e1","label":"Identity provider client list","detail":"The decommissioned service was never removed from the identity provider''s list of valid API clients."},{"id":"e2","label":"WAF traffic logs","detail":"Ordinary traffic patterns around the breach window -- nothing unusual here."},{"id":"e3","label":"API key configuration","detail":"The key had no expiration date and no scoped permissions -- it could read every table the service could reach."},{"id":"e4","label":"Support ticket history","detail":"Customers reported slow page loads the week before -- unrelated performance noise."}],"question":"Which evidence explains how the stolen key kept working long after it should have been dead?"}'::jsonb, '{"requiredEvidenceIds":["e1","e3"]}'::jsonb),
  ('mission-w19-06-o2-c1', 'mission-w19-06-o2', 1, 'drag_and_drop', 'Map each proposed control to the layer of defense it actually strengthens.', '{"items":[{"id":"c1","text":"Revoke the decommissioned service''s API key immediately and require expiration dates on all future keys."},{"id":"c2","text":"Isolate legacy and decommissioned services on a network segment that cannot reach production databases."},{"id":"c3","text":"Alert when an API key suddenly accesses data volumes far outside its historical baseline."},{"id":"c4","text":"Require a documented decommissioning checklist that revokes credentials before a service is marked retired."}],"targets":[{"id":"identity_access","label":"Identity & Access"},{"id":"network_segmentation","label":"Network Segmentation"},{"id":"monitoring_detection","label":"Monitoring & Detection"},{"id":"governance_process","label":"Governance & Process"}]}'::jsonb, '{"correctMapping":{"c1":"identity_access","c2":"network_segmentation","c3":"monitoring_detection","c4":"governance_process"}}'::jsonb),
  ('mission-w19-06-o3-c1', 'mission-w19-06-o3', 1, 'boss_encounter', 'Confirm the root cause and the layered control plan for Nexus Market.', '{"stages":[{"objectiveRef":"mission-w19-06-o1","label":"The root cause"},{"objectiveRef":"mission-w19-06-o2","label":"The layered control plan"}],"task":"Confirm the root cause and the layered control plan for Nexus Market."}'::jsonb, '{"requiredObjectiveIds":["mission-w19-06-o1","mission-w19-06-o2"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-w19-01-o1-c1', 'orientation', 'There''s nothing to solve here -- just confirm you''re ready to continue.', 0, 1),
  ('mission-w19-02-o1-c1', 'orientation', 'Ask what each scenario actually breaks: who can see it, whether it can be trusted, or whether it''s there when needed.', 10, 1),
  ('mission-w19-02-o1-c1', 'concept', 'Confidentiality is about who can read it. Integrity is about whether it can be silently changed. Availability is about whether it''s there when it''s needed.', 20, 2),
  ('mission-w19-02-o1-c1', 'solution', 'p1 and p4 are confidentiality (unauthorized reading), p2 is integrity (values could be altered before logging), and p3 is availability (legitimate traffic delayed, not stolen).', 30, 3),
  ('mission-w19-03-o1-c1', 'orientation', 'Ask whether each scenario is proving identity, checking permission, or limiting how much permission exists in the first place.', 10, 1),
  ('mission-w19-03-o1-c1', 'concept', 'Authentication answers "who are you." Authorization answers "what are you allowed to do." Least privilege answers "how little can you be allowed to do and still do the job."', 20, 2),
  ('mission-w19-03-o1-c1', 'tool_direction', 'a2 and a4 both involve a system deciding what an already-verified identity can touch -- that''s the same category, even though one is a person and one is a service account.', 30, 3),
  ('mission-w19-03-o1-c1', 'solution', 'a1 is authentication (proving identity), a2 and a4 are authorization (checking what a verified identity may do), and a3 is least privilege (deliberately minimizing what''s granted).', 40, 4),
  ('mission-w19-04-o1-c1', 'orientation', 'One of these four is a person or actor, two are weaknesses, and one is a calculation combining likelihood and impact.', 10, 1),
  ('mission-w19-04-o1-c1', 'concept', 'A threat is a potential cause of harm. A vulnerability is a weakness that a threat could exploit. Risk is what happens when you multiply the two by what''s actually at stake.', 20, 2),
  ('mission-w19-04-o1-c1', 'tool_direction', 'Look for the item that''s explicitly a likelihood-times-impact statement -- that''s risk, not a threat or a vulnerability by itself.', 30, 3),
  ('mission-w19-04-o1-c1', 'solution', 't1 is the threat (an actor willing to act), t2 and t4 are vulnerabilities (weaknesses that let the threat succeed), and t3 is the risk (likelihood times impact).', 40, 4),
  ('mission-w19-05-o1-c1', 'orientation', 'Start from the outside: what does an attacker have to get past first, before they ever touch a host?', 10, 1),
  ('mission-w19-05-o1-c1', 'concept', 'Defense in depth assumes every layer can fail -- so each layer should assume the one before it already did.', 20, 2),
  ('mission-w19-05-o1-c1', 'tool_direction', 'Network segmentation and wireless detection come before anything that assumes an attacker already reached a host.', 30, 3),
  ('mission-w19-05-o1-c1', 'solution', 'The stack runs perimeter (segmentation) -> network monitoring (wireless IDS) -> host hardening -> application-level authn/authz -> data-at-rest protection, each layer assuming the previous one failed.', 40, 4),
  ('mission-w19-06-o1-c1', 'orientation', 'Two of these four items are the actual root cause; the other two are unrelated noise.', 15, 1),
  ('mission-w19-06-o1-c1', 'concept', 'A stolen key staying useful for eight months needs two things to be true at once: it was never revoked, and it was never limited in what it could reach.', 25, 2),
  ('mission-w19-06-o1-c1', 'tool_direction', 'Check the identity provider''s client list and the key''s own configuration -- ignore traffic volume and unrelated support tickets.', 35, 3),
  ('mission-w19-06-o1-c1', 'solution', 'e1 (the key was never removed from the identity provider''s valid client list) and e3 (it had no expiration and no scoped permissions) together explain how it kept working; e2 and e4 are unrelated noise.', 45, 4),
  ('mission-w19-06-o2-c1', 'orientation', 'Ask what each control directly changes: who can authenticate, where traffic can travel, what gets noticed, or what process prevents this happening again.', 15, 1),
  ('mission-w19-06-o2-c1', 'concept', 'Identity controls limit what a credential can do. Network controls limit where traffic can travel. Monitoring controls catch what got through. Governance controls prevent the mistake from recurring.', 25, 2),
  ('mission-w19-06-o2-c1', 'tool_direction', 'The credential-specific fixes (revoking, expiring, scoping keys) are identity/access; the process fix (a decommissioning checklist) is governance, not identity.', 35, 3),
  ('mission-w19-06-o2-c1', 'solution', 'c1 (revoke and expire keys) is identity_access, c2 (isolate legacy services) is network_segmentation, c3 (alert on anomalous access volume) is monitoring_detection, and c4 (decommissioning checklist) is governance_process.', 45, 4),
  ('mission-w19-06-o3-c1', 'orientation', 'You already have both pieces -- combine the root cause with the layered plan.', 20, 1),
  ('mission-w19-06-o3-c1', 'concept', 'The report needs to say both why the key kept working and what stops that specific failure from recurring, at more than one layer.', 30, 2),
  ('mission-w19-06-o3-c1', 'tool_direction', 'State the root cause first (unrevoked, unscoped, non-expiring key), then the layered fix across identity, network, monitoring and governance.', 40, 3),
  ('mission-w19-06-o3-c1', 'near_solution', 'Root cause: an unrevoked, unscoped, non-expiring API key for a decommissioned service. Fix: revoke/scope/expire keys, segment legacy services, monitor for anomalous access, and enforce a decommissioning checklist.', 50, 4),
  ('mission-w19-06-o3-c1', 'solution', 'The stolen key kept working because it was never revoked from the identity provider and had no expiration or scope limiting what it could read. The layered plan addresses this at every level -- identity (revoke, scope, expire), network (segment legacy services), monitoring (alert on anomalous access volume) and governance (a decommissioning checklist) -- but residual risk remains: any future credential someone forgets to revoke is still a single point of failure until the checklist itself is audited.', 60, 5);
