-- Phase 2.4s: world-18 mission content, generated from
-- docs/12-world-story-bible.md. Mission 1 is cross-world-gated on
-- the previous world's boss mission where applicable.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-18a', 'world-18', 'broken-marketplace', '18A - The Broken Marketplace', 'The recovered API key surfaces on Nexus Market, a training clone of a breached commerce platform, alongside a trail of suspicious account activity.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-18a-1', 'campaign-18a', 'foundations', 'Foundations', 'Browsers, servers, HTTP, sessions and databases, learned as the mental model underneath every web request.', 1),
  ('operation-18a-2', 'campaign-18a', 'investigation', 'Investigation', 'Trace one purchase on Nexus Market from browser request to database record.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-w18-01', 'world-18', 'campaign-18a', 'operation-18a-1', 'broken-marketplace', 'The Broken Marketplace', 'The API key recovered from the replica surfaces on Nexus Market, a training clone of a breached commerce platform -- along with a trail of suspicious account activity.', 'intro', ARRAY['ava', 'byte'], '{"requiredMissionIds":["mission-w17-06"]}'::jsonb, null, '{"type":"none"}'::jsonb, '{"xp":60,"credits":10}'::jsonb, false, 1),
  ('mission-w18-02', 'world-18', 'campaign-18a', 'operation-18a-1', 'anatomy-of-a-request', 'Anatomy of a Request', 'Every click is a conversation: a request out, a response back. Learn the vocabulary before you go looking for what''s wrong with it.', 'beginner', ARRAY['ava'], '{"requiredMissionIds":["mission-w18-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"http-inspector-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 2),
  ('mission-w18-03', 'world-18', 'campaign-18a', 'operation-18a-1', 'the-session-problem', 'The Session Problem', 'HTTP forgets you the instant the response finishes. Cookies and sessions are the patch -- and the patch can be built badly.', 'beginner', ARRAY['ava'], '{"requiredMissionIds":["mission-w18-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"cookie-session-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 3),
  ('mission-w18-04', 'world-18', 'campaign-18a', 'operation-18a-2', 'the-api-trail', 'The API Trail', 'Nexus Market''s own API left a trail. Follow the calls that don''t belong to any real customer.', 'beginner', ARRAY['ava'], '{"requiredMissionIds":["mission-w18-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"api-trail-sim"}'::jsonb, '{"xp":100,"credits":15}'::jsonb, false, 4),
  ('mission-w18-05', 'world-18', 'campaign-18a', 'operation-18a-2', 'what-the-database-knows', 'What the Database Knows', 'The page shows one order. The database holds the relationships that explain it.', 'beginner', ARRAY['ava'], '{"requiredMissionIds":["mission-w18-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"db-relationship-sim"}'::jsonb, '{"xp":90,"credits":15}'::jsonb, false, 5),
  ('mission-w18-06', 'world-18', 'campaign-18a', 'operation-18a-2', 'reconstruct-the-purchase', 'Reconstruct the Purchase', 'Trace one transaction from browser request to database record, and find exactly where the stolen key fits.', 'boss', ARRAY['ava', 'byte'], '{"requiredMissionIds":["mission-w18-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"reconstruct-purchase-boss-sim"}'::jsonb, '{"xp":300,"credits":60,"badgeIds":["reconstruct-the-purchase"],"skillXp":{"web_security":50}}'::jsonb, true, 6);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-w18-01', 1, 'ava', 'That API key Byte pulled out of the replica isn''t theoretical anymore. It shows up in Nexus Market''s logs -- a training clone of a commerce platform that got breached for real.'),
  ('mission-w18-01', 2, 'ava', 'Before we touch any of it: you cannot secure a system you do not understand. We''re building the mental model first. Browser, server, HTTP, sessions, APIs, database. In that order.'),
  ('mission-w18-01', 3, 'byte', 'I''ll be here for the parts that need a second pair of eyes on the wire. This world''s mostly yours, Ava''s show.'),
  ('mission-w18-01', 4, 'ava', 'There''s also a trail of suspicious account activity sitting on top of all this. We''ll get to it. Foundations first.'),
  ('mission-w18-02', 1, 'ava', 'Every page load is a request and a response. Learn what''s actually inside each one before you try to spot what''s wrong.'),
  ('mission-w18-03', 1, 'ava', 'HTTP has no memory of you between requests. Everything that feels like being ''logged in'' is a patch built on top of that -- and patches can be built badly.'),
  ('mission-w18-04', 1, 'ava', 'Nexus Market has an API behind its storefront, same as every modern app. Not every call to it came from a real customer clicking around.'),
  ('mission-w18-05', 1, 'ava', 'The storefront shows you one order at a time. The database underneath knows how that order connects to a user, a payment, and everything else -- if you know how to ask it.'),
  ('mission-w18-06', 1, 'ava', 'One purchase, start to finish. Browser request, server response, session, API call, database record. Reconstruct all of it, and tell me exactly where that stolen key fits in.'),
  ('mission-w18-06', 2, 'ava', '...There it is. The key''s sitting in the Authorization header of an internal API call that has no business still existing.'),
  ('mission-w18-06', 3, 'byte', 'I traced the service on the other end. It''s tagged in Nexus Market''s own deployment records: inventory-sync-legacy, decommissioned as part of Project SENTINEL''s cleanup.'),
  ('mission-w18-06', 4, 'ava', 'Decommissioned on paper. Not decommissioned in reality. That key kept authenticating against a service that should have died with the rest of Project SENTINEL, and nobody checked.'),
  ('mission-w18-06', 5, 'ava', 'This isn''t one bad password or one bad access point anymore. It''s the same mistake happening at a systemic level, over and over, across everything we''ve investigated. Luna needs to see this.'),
  ('mission-w18-06', 6, 'byte', 'She''s already asked for a formal review. Might be time to stop treating these as separate incidents.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-w18-01-o1', 'mission-w18-01', 1, 'Acknowledge the briefing', 'Confirm you understand why the mental model comes before the investigation.'),
  ('mission-w18-02-o1', 'mission-w18-02', 1, 'Read the request', 'Identify the correct request/response sequence for a given browser action.'),
  ('mission-w18-03-o1', 'mission-w18-03', 1, 'Spot the unsafe session', 'Identify which session-cookie configuration is vulnerable to theft.'),
  ('mission-w18-04-o1', 'mission-w18-04', 1, 'Find the rogue call', 'Identify the API call that doesn''t belong to a real customer.'),
  ('mission-w18-05-o1', 'mission-w18-05', 1, 'Trace the relationship', 'Identify which rows a given query actually returns.'),
  ('mission-w18-06-o1', 'mission-w18-06', 1, 'Trace the request chain', 'Identify the evidence that shows the stolen key in use.'),
  ('mission-w18-06-o2', 'mission-w18-06', 2, 'Identify the service', 'Determine what the key was actually authenticating against.'),
  ('mission-w18-06-o3', 'mission-w18-06', 3, 'Close the investigation', 'Submit the full transaction trace and where the key fits.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-w18-01-o1-c1', 'mission-w18-01-o1', 1, 'story_dialogue', 'Confirm you''re ready to continue.', '{"lines":[{"characterId":"ava","text":"You cannot secure a system you do not understand. Ready to build that understanding first?"}]}'::jsonb, '{"acknowledged":true}'::jsonb),
  ('mission-w18-02-o1-c1', 'mission-w18-02-o1', 1, 'multiple_choice', 'You click "Buy Now" on a product page. Which sequence correctly describes what actually happens at the HTTP level?', '{"question":"You click \"Buy Now\" on a product page. Which sequence correctly describes what actually happens at the HTTP level?","options":[{"id":"a","text":"The browser directly modifies the server''s database over a raw TCP connection"},{"id":"b","text":"The browser sends an HTTP request (e.g. POST /orders) to the server; the server processes it and sends back an HTTP response with a status code"},{"id":"c","text":"The server pushes the purchase to the browser before the browser asks for anything"},{"id":"d","text":"The purchase happens entirely inside the browser, with no server involved"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-w18-03-o1-c1', 'mission-w18-03-o1', 1, 'browser_simulation', 'Two versions of the session cookie Nexus Market sets after login. Identify the one that''s vulnerable to theft over an insecure network or via injected script.', '{"instructions":"Two versions of the session cookie Nexus Market sets after login. Identify the one that''s vulnerable to theft over an insecure network or via injected script.","pages":[{"id":"cookie-a","url":"Set-Cookie: session=8f2a...c91; Path=/","title":"Session cookie -- version A","indicators":{"secure":false,"httpOnly":false,"sameSite":false}},{"id":"cookie-b","url":"Set-Cookie: session=8f2a...c91; Secure; HttpOnly; SameSite=Strict","title":"Session cookie -- version B","indicators":{"secure":true,"httpOnly":true,"sameSite":true}}]}'::jsonb, '{"correctPageId":"cookie-a"}'::jsonb),
  ('mission-w18-04-o1-c1', 'mission-w18-04-o1', 1, 'investigation', 'Which API call doesn''t belong to a real customer?', '{"evidence":[{"id":"call1","label":"GET /api/products?category=electronics","detail":"Standard browsing call, matches a normal customer session, ordinary rate"},{"id":"call2","label":"POST /api/internal/inventory-sync, header Authorization: Bearer <key>","detail":"Hits an internal endpoint not exposed in the public API docs, using a static bearer token instead of a customer session"},{"id":"call3","label":"GET /api/orders/8842","detail":"A logged-in customer checking their own order status, matches their session cookie"},{"id":"call4","label":"POST /api/cart/add","detail":"Ordinary add-to-cart call tied to an active customer session"}],"question":"Which API call doesn''t belong to a real customer?"}'::jsonb, '{"requiredEvidenceIds":["call2"]}'::jsonb),
  ('mission-w18-05-o1-c1', 'mission-w18-05-o1', 1, 'investigation', 'Given the query, which order rows does it actually return?', '{"evidence":[{"id":"query","label":"Query","detail":"SELECT * FROM orders WHERE user_id = 4821 AND status = ''completed'';"},{"id":"row1","label":"Order 101","detail":"user_id=4821, status=''completed''"},{"id":"row2","label":"Order 102","detail":"user_id=4821, status=''pending''"},{"id":"row3","label":"Order 103","detail":"user_id=5190, status=''completed''"},{"id":"row4","label":"Order 104","detail":"user_id=4821, status=''completed''"}],"question":"Given the query, which order rows does it actually return?"}'::jsonb, '{"requiredEvidenceIds":["row1","row4"]}'::jsonb),
  ('mission-w18-06-o1-c1', 'mission-w18-06-o1', 1, 'investigation', 'Which evidence shows the stolen key actually being used?', '{"evidence":[{"id":"req1","label":"Browser request","detail":"POST /api/checkout, session cookie attached, no Authorization header -- this is the customer''s own request"},{"id":"log1","label":"Server-side call log","detail":"Immediately after checkout, the server makes an outbound call: POST https://inventory-sync-legacy.internal/api/update, header Authorization: Bearer <the recovered API key>"},{"id":"dbrow","label":"Database record","detail":"orders table row for this purchase, foreign-keyed to a users row and a payments row -- no anomaly on its own"},{"id":"unrelated","label":"CDN asset request","detail":"GET /static/logo.png, unrelated static asset load"}],"question":"Which evidence shows the stolen key actually being used?"}'::jsonb, '{"requiredEvidenceIds":["log1"]}'::jsonb),
  ('mission-w18-06-o2-c1', 'mission-w18-06-o2', 1, 'multiple_choice', 'Nexus Market''s deployment records tag the service on the other end of that call as inventory-sync-legacy, marked decommissioned as part of Project SENTINEL''s cleanup years ago. What does that tell you?', '{"question":"Nexus Market''s deployment records tag the service on the other end of that call as inventory-sync-legacy, marked decommissioned as part of Project SENTINEL''s cleanup years ago. What does that tell you?","options":[{"id":"a","text":"Nothing -- decommission tickets don''t matter once filed"},{"id":"b","text":"The decommission was recorded but never actually carried out, so the key kept working against infrastructure that should have been retired with the rest of Project SENTINEL"},{"id":"c","text":"The key must belong to a completely unrelated, currently-supported service"},{"id":"d","text":"The ticket proves the service is secure because someone reviewed it once"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-w18-06-o3-c1', 'mission-w18-06-o3', 1, 'boss_encounter', 'Submit the full transaction trace and where the key fits.', '{"stages":[{"objectiveRef":"mission-w18-06-o1","label":"The stolen key in use"},{"objectiveRef":"mission-w18-06-o2","label":"The undecommissioned service"}],"task":"Submit the full transaction trace and where the key fits."}'::jsonb, '{"requiredObjectiveIds":["mission-w18-06-o1","mission-w18-06-o2"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-w18-01-o1-c1', 'orientation', 'There''s nothing to solve here -- just confirm you''re ready to continue.', 0, 1),
  ('mission-w18-02-o1-c1', 'orientation', 'Nothing in a normal web app skips the network entirely.', 10, 1),
  ('mission-w18-02-o1-c1', 'solution', 'The browser sends an HTTP request, the server processes it and replies with an HTTP response carrying a status code -- everything else here either skips the network or reverses the roles incorrectly.', 20, 2),
  ('mission-w18-03-o1-c1', 'orientation', 'Three flags on a cookie each block a different way of stealing it.', 15, 1),
  ('mission-w18-03-o1-c1', 'concept', 'Secure stops it from ever being sent over plain HTTP; HttpOnly stops JavaScript from reading it; SameSite limits it being sent cross-site.', 25, 2),
  ('mission-w18-03-o1-c1', 'tool_direction', 'Compare which flags are actually present on each version.', 35, 3),
  ('mission-w18-03-o1-c1', 'solution', 'Version A has none of the three protective flags set -- it can be sent over an insecure connection, read by injected script, and attached to cross-site requests. Version B has all three set correctly.', 45, 4),
  ('mission-w18-04-o1-c1', 'orientation', 'Three of these four calls are exactly what you''d expect from a logged-in customer browsing normally.', 15, 1),
  ('mission-w18-04-o1-c1', 'concept', 'A static bearer token hitting an undocumented internal endpoint isn''t how customer traffic looks.', 25, 2),
  ('mission-w18-04-o1-c1', 'tool_direction', 'Compare the authentication method each call uses against what a real customer session actually looks like.', 35, 3),
  ('mission-w18-04-o1-c1', 'solution', 'call2 authenticates with a static bearer token against an internal, undocumented endpoint instead of a normal customer session -- that''s the call that doesn''t belong to a real customer.', 45, 4),
  ('mission-w18-05-o1-c1', 'orientation', 'Both conditions in the WHERE clause have to be true for a row to match, not just one.', 15, 1),
  ('mission-w18-05-o1-c1', 'concept', 'user_id = 4821 rules out one row immediately; status = ''completed'' rules out a second.', 25, 2),
  ('mission-w18-05-o1-c1', 'tool_direction', 'Check each row against both conditions independently before deciding it matches.', 35, 3),
  ('mission-w18-05-o1-c1', 'solution', 'Only Order 101 and Order 104 satisfy both user_id = 4821 AND status = ''completed'' -- Order 102 fails on status, Order 103 fails on user_id.', 45, 4),
  ('mission-w18-06-o1-c1', 'orientation', 'Only one of these four items shows the key actually being transmitted.', 20, 1),
  ('mission-w18-06-o1-c1', 'concept', 'The customer''s own request and the database record are both legitimate parts of the transaction on their own -- look for the outbound call that doesn''t belong to the customer at all.', 30, 2),
  ('mission-w18-06-o1-c1', 'tool_direction', 'Check which log entry carries an Authorization header with the key Byte recovered.', 40, 3),
  ('mission-w18-06-o1-c1', 'solution', 'The server-side outbound call to inventory-sync-legacy carries the recovered API key in its Authorization header -- that''s the key in active use, well outside anything the customer''s own browser request triggered directly.', 50, 4),
  ('mission-w18-06-o2-c1', 'orientation', 'A ticket being filed and a service actually being shut down are two different events.', 20, 1),
  ('mission-w18-06-o2-c1', 'solution', 'The service was marked decommissioned as part of Project SENTINEL''s cleanup, but it was never actually shut down -- so the key kept authenticating successfully against infrastructure that should have been retired years ago.', 30, 2),
  ('mission-w18-06-o3-c1', 'orientation', 'You''ve already traced the request and identified the service -- combine both into one chain.', 25, 1),
  ('mission-w18-06-o3-c1', 'concept', 'The full trace needs the browser request, the outbound call carrying the key, and what that call''s destination actually is.', 35, 2),
  ('mission-w18-06-o3-c1', 'tool_direction', 'State the checkout request first, then the internal call and the key, then the service it should never have reached.', 45, 3),
  ('mission-w18-06-o3-c1', 'near_solution', 'Checkout request -> outbound call to inventory-sync-legacy carrying the recovered key -> a service marked decommissioned under Project SENTINEL but never actually shut down.', 55, 4),
  ('mission-w18-06-o3-c1', 'solution', 'The customer''s checkout request triggers a server-side call to inventory-sync-legacy, carrying the API key recovered from the replica in its Authorization header -- a service Nexus Market''s own records mark as decommissioned under Project SENTINEL, but that was never actually shut down.', 65, 5);
