-- AI/ML pathway ("Cipher Division") Act 27 -- "Building with LLMs" content.
-- Arc V, Acts 24-27. This Act closes Arc V and pivots into Arc VI.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue_lines -> objectives ->
-- challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-building-with-llms row already exists.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-building-with-llms', 'world-ai-building-with-llms', 'building-with-llms', '27A - Building with LLMs', 'Give the new model actual engineering discipline: message roles and system instructions, structured JSON output validated against a real schema, tool calling with bounded function schemas, streaming, and the retries, rate limits and timeouts that decide whether it survives production.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-building-with-llms-1', 'campaign-ai-building-with-llms', 'structured-by-default', 'Structured by Default', 'Message roles, system instructions, prompt structure, structured outputs, JSON schema and validation -- the discipline that makes every response predictable before anything gets trusted.', 1),
  ('operation-ai-building-with-llms-2', 'campaign-ai-building-with-llms', 'production-ready', 'Production Ready', 'Retries and parse failures, tool calling, function schemas, streaming, rate limits and timeouts -- the engineering that makes the assistant survive contact with the real world.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-building-with-llms-01', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'messages-and-roles', 'Messages and Roles', 'The team stops treating a request to the model as one block of text. It is a list of messages, and getting the roles wrong means the model cannot tell an instruction from a question.', 'beginner', ARRAY['maya','elena','noah'], null, null, '{"type":"simulation","simulationId":"messages-and-roles-sim"}'::jsonb, '{"xp":580,"credits":150}'::jsonb, false, 1),
  ('mission-ai-building-with-llms-02', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'system-instructions', 'System Instructions', 'A system message pins down scope, tone and format before a single user question arrives -- the strongest single lever Cipher Division has over how the assistant behaves by default.', 'beginner', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"system-instructions-sim"}'::jsonb, '{"xp":590,"credits":150}'::jsonb, false, 2),
  ('mission-ai-building-with-llms-03', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'prompt-structure', 'Prompt Structure', 'A well-organized prompt separates the task, the reference material and the expected format, so the model never has to guess which sentence is the actual question.', 'beginner', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"prompt-structure-sim"}'::jsonb, '{"xp":590,"credits":155}'::jsonb, false, 3),
  ('mission-ai-building-with-llms-04', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'structured-outputs', 'Structured Outputs', 'Prose has to be scraped for the one fact code actually needed. Structured JSON output removes the scraping entirely -- if the request actually asks for it.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"structured-outputs-sim"}'::jsonb, '{"xp":600,"credits":155}'::jsonb, false, 4),
  ('mission-ai-building-with-llms-05', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'json-schema', 'JSON Schema', 'A JSON schema pins the output shape down precisely enough that wrong stops meaning anything at all and starts meaning a short, checkable list of ways it can fail.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"json-schema-sim"}'::jsonb, '{"xp":600,"credits":155}'::jsonb, false, 5),
  ('mission-ai-building-with-llms-06', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-1', 'validation', 'Validation', 'A schema tells the model what shape to aim for. Only validation in code proves it actually landed there before anything downstream gets to trust it.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"validation-sim"}'::jsonb, '{"xp":610,"credits":160}'::jsonb, false, 6),
  ('mission-ai-building-with-llms-07', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'retries-and-parse-failures', 'Retries and Parse Failures', 'Parse failures are not rare -- they are Tuesday. The fix is a bounded retry, not a crash and not a silent shrug at bad data.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-building-with-llms-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"retries-and-parse-failures-sim"}'::jsonb, '{"xp":610,"credits":160}'::jsonb, false, 7),
  ('mission-ai-building-with-llms-08', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'tool-calling', 'Tool Calling', 'Sometimes the right answer is not something the model already knows. Tool calling lets it ask a real function for the value instead of guessing.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-building-with-llms-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"tool-calling-sim"}'::jsonb, '{"xp":620,"credits":160}'::jsonb, false, 8),
  ('mission-ai-building-with-llms-09', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'function-schemas', 'Function Schemas', 'A function schema is the exact map of what the model is allowed to call and what arguments are allowed to reach it -- too loose, and a real system is one bad guess away from a bad call.', 'intermediate', ARRAY['noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"function-schemas-sim"}'::jsonb, '{"xp":620,"credits":165}'::jsonb, false, 9),
  ('mission-ai-building-with-llms-10', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'streaming', 'Streaming', 'Waiting for a full response is the difference between a tool that feels instant and one that feels frozen. Streaming changes both the experience and the failure modes.', 'intermediate', ARRAY['noah','elena'], '{"requiredMissionIds":["mission-ai-building-with-llms-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"streaming-sim"}'::jsonb, '{"xp":630,"credits":165}'::jsonb, false, 10),
  ('mission-ai-building-with-llms-11', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'rate-limits-and-timeouts', 'Rate Limits and Timeouts', 'Every request rides a real network with real limits. A rate limit needs backoff. A stalled request needs its own timeout. Neither gets fixed by hoping.', 'intermediate', ARRAY['noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"rate-limits-and-timeouts-sim"}'::jsonb, '{"xp":630,"credits":165}'::jsonb, false, 11),
  ('mission-ai-building-with-llms-12', 'world-ai-building-with-llms', 'campaign-ai-building-with-llms', 'operation-ai-building-with-llms-2', 'the-unreliable-assistant', 'The Unreliable Assistant', 'The new assistant gets stress-tested under three real failures at once -- malformed output, a stalled connection, a bad tool call -- and Cipher Division has to prove it is production-ready, not just demo-ready.', 'boss', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-building-with-llms-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-unreliable-assistant-boss-sim"}'::jsonb, '{"xp":1350,"credits":290,"badgeIds":["the-unreliable-assistant"],"skillXp":{"llm_engineering":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-building-with-llms-01', 1, 'maya', 'A model this confident, even when it is wrong, is not something Cipher Division can run on instinct. Every output this tool ever produces now needs structure, validation and a way to fail safely -- starting with how it is even allowed to respond.'),
  ('mission-ai-building-with-llms-01', 2, 'elena', 'Start with the most basic structure there is. A request to the model is not one block of text -- it is a list of messages, and each message carries a role: system, user, or assistant.'),
  ('mission-ai-building-with-llms-01', 3, 'noah', 'System carries the model''s standing instructions, set before anything else happens. User is whatever the person actually typed. Assistant is the model''s own prior replies, fed back in so a multi-turn conversation has memory of itself.'),
  ('mission-ai-building-with-llms-01', 4, 'elena', 'Get the roles wrong and the model has no way to tell an instruction from a question from its own past answer. That confusion is exactly where today''s lesson starts.'),

  ('mission-ai-building-with-llms-02', 1, 'elena', 'Messages tell the model who said what. System instructions decide what the model is even allowed to do with any of it.'),
  ('mission-ai-building-with-llms-02', 2, 'noah', 'A system message is where scope, tone and format get pinned down before a single user question ever arrives -- what the assistant should refuse, what it should always cite, what shape its answers should take.'),
  ('mission-ai-building-with-llms-02', 3, 'elena', 'It is not a guarantee. A determined user can still push against it. But a clear system message is the strongest single lever Cipher Division has over how this thing behaves by default.'),

  ('mission-ai-building-with-llms-03', 1, 'elena', 'System instructions set the standing rules. The user message still has to be organized well, or the model has to guess what actually matters inside it.'),
  ('mission-ai-building-with-llms-03', 2, 'noah', 'Good structure separates the task from the reference material from the format request, usually with clear delimiters, so the model does not confuse an instruction with a piece of quoted evidence sitting right next to it.'),
  ('mission-ai-building-with-llms-03', 3, 'elena', 'Dump everything into one unstructured paragraph and the model has to guess which sentence is the actual question. Structure it -- task, context, format -- and there is no guessing left to do.'),

  ('mission-ai-building-with-llms-04', 1, 'elena', 'Ask a model to explain itself in prose and downstream code has to scrape a paragraph for the one fact it actually needed. That is fragile in a way Cipher Division cannot ship.'),
  ('mission-ai-building-with-llms-04', 2, 'noah', 'Structured output flips it. Instead of asking the model to write about the answer, ask it to return the answer itself, in a fixed shape like JSON, that code can parse directly with no scraping involved.'),
  ('mission-ai-building-with-llms-04', 3, 'elena', 'The request still goes through the same message list from before. What changes is the instruction: return only a JSON object shaped like this, nothing else around it.'),

  ('mission-ai-building-with-llms-05', 1, 'elena', 'Asking for JSON only gets you free-form JSON. The model can still invent field names, use the wrong type, or leave a required field out entirely.'),
  ('mission-ai-building-with-llms-05', 2, 'noah', 'A JSON schema pins the shape down precisely: which fields exist, what type each one is, which ones are required, sometimes even a fixed set of allowed values. Pass it alongside the request and the model has an exact target to hit.'),
  ('mission-ai-building-with-llms-05', 3, 'elena', 'It is still not a guarantee. Schema-guided output can still drift. But it narrows what wrong even looks like, from anything at all down to a short, checkable list of ways it can fail.'),

  ('mission-ai-building-with-llms-06', 1, 'noah', 'A schema tells the model what shape to aim for. It does not guarantee the model actually hit it. Every response still needs to be checked in code before anything downstream trusts it.'),
  ('mission-ai-building-with-llms-06', 2, 'elena', 'That means parsing the JSON, then validating it against the schema -- right types, required fields present, no unexpected surprises -- before a single value gets used for a real decision.'),
  ('mission-ai-building-with-llms-06', 3, 'noah', 'Skip that step and "we asked for structured output" quietly becomes "we assumed structured output." Those are not the same sentence.'),

  ('mission-ai-building-with-llms-07', 1, 'noah', 'Even with a schema and validation in place, a response will eventually fail to parse or fail validation -- truncated JSON, an extra trailing comma, a field that came back the wrong type. That is not rare. That is Tuesday.'),
  ('mission-ai-building-with-llms-07', 2, 'elena', 'The wrong response to a parse failure is to crash, and the other wrong response is to silently keep whatever garbage came back. The right response is to retry, often with the error fed back to the model, up to a bounded number of attempts.'),
  ('mission-ai-building-with-llms-07', 3, 'noah', 'Bounded matters as much as retry does. Retry forever on a request that will never succeed and Cipher Division has built an infinite loop, not a safety net.'),

  ('mission-ai-building-with-llms-08', 1, 'noah', 'Sometimes the right answer is not something the model already knows. It is a value that lives in a real system, like the current containment status of Echo, that only a function call can actually fetch.'),
  ('mission-ai-building-with-llms-08', 2, 'elena', 'Tool calling lets the model ask for that instead of guessing. Rather than answering directly, it can return a tool call: the name of a function and the arguments it wants to call it with.'),
  ('mission-ai-building-with-llms-08', 3, 'noah', 'The model never runs that function itself. The application reads the tool call, runs the real function locally, and feeds the result back in as a new message so the model can finish its answer with real data.'),

  ('mission-ai-building-with-llms-09', 1, 'noah', 'A tool call only works if the model knows exactly what functions exist and exactly what arguments each one takes. That is the function schema: a name, a description, and a JSON schema for its parameters, same shape as the output schemas from earlier.'),
  ('mission-ai-building-with-llms-09', 2, 'noah', 'Too vague and the model guesses wrong arguments. Too permissive and the model can pass anything through to a real function running against real systems. A tight, bounded schema is what keeps that call safe to actually execute.'),

  ('mission-ai-building-with-llms-10', 1, 'noah', 'Every example so far waited for the full response before doing anything with it. For anything user-facing, that wait is the difference between a tool that feels instant and one that feels frozen.'),
  ('mission-ai-building-with-llms-10', 2, 'elena', 'Streaming sends the response back in small chunks, as the model generates them, instead of one block at the end. The application reads each chunk as it arrives and can display it immediately.'),
  ('mission-ai-building-with-llms-10', 3, 'noah', 'It changes how failure looks, too. A streamed response can stop partway through -- a dropped connection, a timeout mid-stream -- and the application has to handle an incomplete answer, not just a missing one.'),

  ('mission-ai-building-with-llms-11', 1, 'noah', 'Streaming or not, every request to the model goes over a real network, to a real service with real limits. Two failure modes show up constantly in production: a rate limit response, and a request that simply hangs.'),
  ('mission-ai-building-with-llms-11', 2, 'noah', 'A rate limit is not the model refusing to answer. It is the provider saying too many requests arrived too fast. The fix is backoff: wait, then retry, waiting longer each time it happens again, not slamming the same request immediately.'),
  ('mission-ai-building-with-llms-11', 3, 'noah', 'A timeout is different. The request never got a response at all inside a reasonable window. That needs its own fixed timeout and its own retry, or the whole application just hangs waiting on one stuck call forever.'),

  ('mission-ai-building-with-llms-12', 1, 'maya', 'The assistant has passed every lesson on its own. Today it gets tested the way it will actually be used -- three real failure conditions, hitting at once, not one tidy example at a time.'),
  ('mission-ai-building-with-llms-12', 2, 'noah', 'Malformed output the parser cannot read. A request that stalls and never comes back. A tool call that arrives with an argument that does not make sense. None of these are rare edge cases. I have hit all three in real systems, usually in the same bad week.'),
  ('mission-ai-building-with-llms-12', 3, 'elena', 'A notebook that works once, in a demo, is not a product. Cipher Division does not get to assume any of this will not happen -- every failure needs an engineered, tested response waiting for it before it happens.'),
  ('mission-ai-building-with-llms-12', 4, 'maya', 'Diagnose each failure. Choose the engineered fix, not the easy one. Then give Cipher Division a straight answer: is this assistant ready to run unsupervised.'),
  ('mission-ai-building-with-llms-12', 5, 'noah', 'Stress-tested under real failure conditions -- malformed output, a stalled connection, a tool call with bad arguments -- the assistant only becomes trustworthy once every one of those failures has an engineered, tested response, not a hope that it will not happen.'),
  ('mission-ai-building-with-llms-12', 6, 'maya', 'A reliable assistant that still knows nothing beyond its training is not enough. Cipher Division needs it to actually look things up.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-building-with-llms-01-o1', 'mission-ai-building-with-llms-01', 1, 'Identify the Roles', 'State what the system role actually does in a chat completion request.'),
  ('mission-ai-building-with-llms-01-o2', 'mission-ai-building-with-llms-01', 2, 'Fix the Role Bug', 'Find the line that uses a role the API does not recognize.'),

  ('mission-ai-building-with-llms-02-o1', 'mission-ai-building-with-llms-02', 1, 'Place the Policy', 'Decide whether a standing behavioral policy belongs in the system message or the user message.'),
  ('mission-ai-building-with-llms-02-o2', 'mission-ai-building-with-llms-02', 2, 'Spot the Weak Instruction', 'Find the system instruction draft that is actually specific and checkable.'),

  ('mission-ai-building-with-llms-03-o1', 'mission-ai-building-with-llms-03', 1, 'Order a Well-Structured Prompt', 'Put the parts of a well-structured prompt in the order they should appear.'),
  ('mission-ai-building-with-llms-03-o2', 'mission-ai-building-with-llms-03', 2, 'Explain the Delimiter', 'State why quoted reference material needs a clear delimiter inside a prompt.'),

  ('mission-ai-building-with-llms-04-o1', 'mission-ai-building-with-llms-04', 1, 'Choose Structured Output', 'State why structured JSON output beats free-form prose for programmatic use.'),
  ('mission-ai-building-with-llms-04-o2', 'mission-ai-building-with-llms-04', 2, 'Fix the Missing Format Instruction', 'Find the line that never tells the model to return JSON only.'),

  ('mission-ai-building-with-llms-05-o1', 'mission-ai-building-with-llms-05', 1, 'Read a JSON Schema', 'State what listing a field as required in a JSON schema actually means.'),
  ('mission-ai-building-with-llms-05-o2', 'mission-ai-building-with-llms-05', 2, 'Match Schema Keywords', 'Match each JSON schema keyword to what it actually constrains.'),

  ('mission-ai-building-with-llms-06-o1', 'mission-ai-building-with-llms-06', 1, 'Know What Validation Checks', 'State what code should still do after the model returns JSON matching the requested schema.'),
  ('mission-ai-building-with-llms-06-o2', 'mission-ai-building-with-llms-06', 2, 'Fix the Missing Validation', 'Find the line that uses parsed data before it has been validated.'),

  ('mission-ai-building-with-llms-07-o1', 'mission-ai-building-with-llms-07', 1, 'Design the Retry Loop', 'Order the steps of a bounded retry loop for parse failures.'),
  ('mission-ai-building-with-llms-07-o2', 'mission-ai-building-with-llms-07', 2, 'Fix the Unbounded Retry', 'Find the line that lets a failing request retry forever.'),

  ('mission-ai-building-with-llms-08-o1', 'mission-ai-building-with-llms-08', 1, 'Trace the Tool-Calling Cycle', 'Order the steps that turn a tool call into a finished answer.'),
  ('mission-ai-building-with-llms-08-o2', 'mission-ai-building-with-llms-08', 2, 'Spot the Missing Step', 'Find the evidence explaining why the model never produced a final answer.'),

  ('mission-ai-building-with-llms-09-o1', 'mission-ai-building-with-llms-09', 1, 'Read a Function Schema', 'State what a function schema parameters actually constrain.'),
  ('mission-ai-building-with-llms-09-o2', 'mission-ai-building-with-llms-09', 2, 'Fix the Loose Schema', 'Find the line that lets the model pass an argument value that should never be allowed.'),

  ('mission-ai-building-with-llms-10-o1', 'mission-ai-building-with-llms-10', 1, 'Know What Streaming Changes', 'State what actually changes about response delivery when streaming is enabled.'),
  ('mission-ai-building-with-llms-10-o2', 'mission-ai-building-with-llms-10', 2, 'Fix the Broken Stream Handler', 'Find the line that displays each chunk but never saves it.'),

  ('mission-ai-building-with-llms-11-o1', 'mission-ai-building-with-llms-11', 1, 'Diagnose the Rate Limit', 'State what an HTTP 429 response actually indicates and how a client should respond.'),
  ('mission-ai-building-with-llms-11-o2', 'mission-ai-building-with-llms-11', 2, 'Fix the Missing Backoff', 'Find the line that retries immediately with no delay after a rate limit error.'),

  ('mission-ai-building-with-llms-12-o1', 'mission-ai-building-with-llms-12', 1, 'Handle the Malformed Response', 'Diagnose the parse failure and choose the correct engineered response.'),
  ('mission-ai-building-with-llms-12-o2', 'mission-ai-building-with-llms-12', 2, 'Handle the Stalled Request', 'Diagnose the timeout failure and choose the correct engineered response.'),
  ('mission-ai-building-with-llms-12-o3', 'mission-ai-building-with-llms-12', 3, 'Handle the Bad Tool Call', 'Diagnose the bad-argument failure and choose the correct engineered response.'),
  ('mission-ai-building-with-llms-12-o4', 'mission-ai-building-with-llms-12', 4, 'Rule on the Assistant', 'Having fixed all three failures, state whether the assistant is ready to run unsupervised.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-building-with-llms-01-o1-c1', 'mission-ai-building-with-llms-01-o1', 1, 'multiple_choice', 'State what the system role actually does in a chat completion request.', '{"question":"In a chat completion request, what does a message with the system role actually do?","options":[{"id":"a","text":"It carries the literal question the user typed"},{"id":"b","text":"It sets standing instructions and constraints that shape the model behavior for the entire conversation"},{"id":"c","text":"It replays a prior reply from the assistant back into the conversation"},{"id":"d","text":"It has no effect and can always be safely left out"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-01-o2-c1', 'mission-ai-building-with-llms-01-o2', 1, 'code_debugging', 'Find the line that uses a role the API does not recognize.', '{"language":"python","code":"messages = [\n    {\"role\": \"system\", \"content\": \"You are the Cipher Division assistant. Answer only from verified evidence.\"},\n    {\"role\": \"human\", \"content\": \"What is the current containment status of Echo?\"},\n]\n\nresponse = client.chat.completions.create(\n    model=\"cipher-llm-1\",\n    messages=messages,\n)","question":"This request gets rejected before the model ever sees it. Which line uses a role the API does not recognize?"}'::jsonb, '{"requiredLineIds":["    {\"role\": \"human\", \"content\": \"What is the current containment status of Echo?\"},"]}'::jsonb),

  ('mission-ai-building-with-llms-02-o1-c1', 'mission-ai-building-with-llms-02-o1', 1, 'multiple_choice', 'Decide where a standing behavioral policy belongs.', '{"question":"Cipher Division is building an assistant that must never reveal raw incident logs to unauthorized roles and must always answer in three bullet points. Where does that policy belong?","options":[{"id":"a","text":"In the user message, restated every single turn"},{"id":"b","text":"In the system message, set once, so it applies to the whole conversation by default"},{"id":"c","text":"It cannot be enforced by the model at all, so there is no point setting it anywhere"},{"id":"d","text":"In the assistant message, so the model can approve it itself"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-02-o2-c1', 'mission-ai-building-with-llms-02-o2', 1, 'investigation', 'Find the system instruction draft that is actually specific and checkable.', '{"evidence":[{"id":"e1","label":"Draft A","detail":"Be helpful and follow instructions well."},{"id":"e2","label":"Draft B","detail":"Answer only using the evidence provided in this conversation. If the evidence does not support an answer, state that directly instead of guessing."},{"id":"e3","label":"Team note","detail":"Cipher Division wants a system instruction that can actually be checked against a transcript afterward, not just a good intention."}],"question":"Which draft actually gives the model a concrete, checkable rule instead of a vague intention?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-building-with-llms-03-o1-c1', 'mission-ai-building-with-llms-03-o1', 1, 'interactive_diagram', 'Order the parts of a well-structured prompt.', '{"diagramId":"prompt-structure-template","hotspots":[{"id":"state","label":"State the task in one clear sentence","explanation":"The model needs to know what it is actually being asked to do before anything else is useful."},{"id":"context","label":"Provide the reference material, clearly delimited","explanation":"Quoted content marked off from the instructions keeps the model from treating the reference material as another command."},{"id":"format","label":"Specify the exact output format expected","explanation":"Naming the format last locks in how the finished answer should look, once the task and material are already clear."}],"task":"Order the parts of a well-structured prompt from first to last."}'::jsonb, '{"correctOrderIds":["state","context","format"]}'::jsonb),
  ('mission-ai-building-with-llms-03-o2-c1', 'mission-ai-building-with-llms-03-o2', 1, 'multiple_choice', 'State why quoted reference material needs a clear delimiter.', '{"question":"Why wrap quoted reference material in clear delimiters, such as triple quotes or tags, inside a prompt?","options":[{"id":"a","text":"So the model can tell where an instruction ends and quoted content begins, instead of treating quoted text as another instruction"},{"id":"b","text":"Delimiters make the request cheaper to run"},{"id":"c","text":"Delimiters are required by every model provider or the request fails outright"},{"id":"d","text":"Delimiters translate the content into another language automatically"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-ai-building-with-llms-04-o1-c1', 'mission-ai-building-with-llms-04-o1', 1, 'multiple_choice', 'State why structured JSON output beats free-form prose for programmatic use.', '{"question":"Cipher Division needs to extract a severity level and an incident id from every model reply, automatically, in code. Why ask for structured JSON output instead of free-form prose?","options":[{"id":"a","text":"JSON output is always shorter, which is the only real benefit"},{"id":"b","text":"A fixed, parseable shape lets code read the exact fields it needs directly, without fragile text-scraping that breaks the moment phrasing changes"},{"id":"c","text":"Free-form prose cannot be generated by a language model at all"},{"id":"d","text":"JSON removes the need for a system instruction entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-04-o2-c1', 'mission-ai-building-with-llms-04-o2', 1, 'code_debugging', 'Find the line that never tells the model to return JSON only.', '{"language":"python","code":"system_prompt = \"You are the Cipher Division triage assistant.\"\nuser_prompt = \"Classify this incident and return the severity and incident id.\"\n\nresponse = client.chat.completions.create(\n    model=\"cipher-llm-1\",\n    messages=[\n        {\"role\": \"system\", \"content\": system_prompt},\n        {\"role\": \"user\", \"content\": user_prompt},\n    ],\n)\n\nresult = json.loads(response.choices[0].message.content)","question":"This call fails with a JSON parsing error almost every time it runs. Which line never actually instructs the model to return JSON, and only JSON?"}'::jsonb, '{"requiredLineIds":["user_prompt = \"Classify this incident and return the severity and incident id.\""]}'::jsonb),

  ('mission-ai-building-with-llms-05-o1-c1', 'mission-ai-building-with-llms-05-o1', 1, 'multiple_choice', 'State what a required field in a JSON schema actually means.', '{"question":"In a JSON schema, what does listing a field inside required actually mean?","options":[{"id":"a","text":"The field is optional but recommended"},{"id":"b","text":"The output is invalid unless that field is present"},{"id":"c","text":"The field must always be the first key in the object"},{"id":"d","text":"The field gets removed automatically if it is present"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-05-o2-c1', 'mission-ai-building-with-llms-05-o2', 1, 'drag_and_drop', 'Match each JSON schema keyword to what it actually constrains.', '{"items":[{"id":"i1","text":"type"},{"id":"i2","text":"required"},{"id":"i3","text":"enum"},{"id":"i4","text":"properties"}],"targets":[{"id":"t1","label":"Restricts a field to one of a fixed list of allowed values"},{"id":"t2","label":"Defines the data type expected for a field, such as string or integer"},{"id":"t3","label":"Lists which fields must be present for the output to be valid"},{"id":"t4","label":"Defines the set of fields an object is allowed to have, and their individual schemas"}]}'::jsonb, '{"correctMapping":{"i1":"t2","i2":"t3","i3":"t1","i4":"t4"}}'::jsonb),

  ('mission-ai-building-with-llms-06-o1-c1', 'mission-ai-building-with-llms-06-o1', 1, 'multiple_choice', 'State what code should still do after the model returns matching JSON.', '{"question":"After a model returns JSON that matches the requested schema, what should code still do before using it?","options":[{"id":"a","text":"Trust it immediately, since a schema was provided in the request"},{"id":"b","text":"Validate the parsed result against the schema in code, checking required fields and correct types, before using any of the values"},{"id":"c","text":"Nothing further is needed once the JSON parses successfully"},{"id":"d","text":"Re-run the exact same request a second time just in case"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-06-o2-c1', 'mission-ai-building-with-llms-06-o2', 1, 'code_debugging', 'Find the line that uses parsed data before it has been validated.', '{"language":"python","code":"data = json.loads(response.choices[0].message.content)\nincident_id = data[\"incident_id\"]\nseverity = data[\"severity\"]\nopen_ticket(incident_id, severity)","question":"This code goes straight from parsing to using the fields, with no schema validation step in between. Which line is the first to treat unvalidated data as if it were already confirmed safe?"}'::jsonb, '{"requiredLineIds":["incident_id = data[\"incident_id\"]"]}'::jsonb),

  ('mission-ai-building-with-llms-07-o1-c1', 'mission-ai-building-with-llms-07-o1', 1, 'interactive_diagram', 'Order the steps of a bounded retry loop for parse failures.', '{"diagramId":"retry-on-parse-failure","hotspots":[{"id":"send","label":"Send the request to the model","explanation":"Every attempt starts with a real request going out."},{"id":"parse","label":"Attempt to parse and validate the response","explanation":"The raw response gets checked against the schema before it is trusted."},{"id":"check","label":"Check whether parsing and validation both succeeded","explanation":"Success ends the loop; failure moves to the retry decision."},{"id":"retry","label":"On failure, increment the attempt count and retry, feeding the error back","explanation":"A new attempt goes out, now with the previous failure included as context."},{"id":"fail","label":"If the attempt limit is reached, stop and fail safely","explanation":"An unbounded retry is not a safety net -- a bounded one that fails cleanly is."}],"task":"Order the steps of a bounded retry loop for parse failures, from first to last."}'::jsonb, '{"correctOrderIds":["send","parse","check","retry","fail"]}'::jsonb),
  ('mission-ai-building-with-llms-07-o2-c1', 'mission-ai-building-with-llms-07-o2', 1, 'code_debugging', 'Find the line that lets a failing request retry forever.', '{"language":"python","code":"attempt = 0\nwhile True:\n    response = call_model(messages)\n    try:\n        data = json.loads(response)\n        validate(data)\n        break\n    except (json.JSONDecodeError, ValidationError):\n        attempt += 1\n        messages.append({\"role\": \"user\", \"content\": \"That was not valid JSON. Try again.\"})","question":"This loop never stops retrying, even against a request that will never succeed. Which line has no bound on how many times it can run?"}'::jsonb, '{"requiredLineIds":["while True:"]}'::jsonb),

  ('mission-ai-building-with-llms-08-o1-c1', 'mission-ai-building-with-llms-08-o1', 1, 'interactive_diagram', 'Order the steps that turn a tool call into a finished answer.', '{"diagramId":"tool-calling-cycle","hotspots":[{"id":"request","label":"Send the request with the available tool definitions","explanation":"The model needs to know what functions exist before it can ask for one."},{"id":"toolcall","label":"Model responds with a tool call instead of a direct answer","explanation":"A function name and arguments come back, not a finished reply."},{"id":"execute","label":"Application executes the real function locally","explanation":"The model never runs anything itself -- the application does, using the arguments provided."},{"id":"return","label":"Application sends the function result back as a new message","explanation":"The model needs the real result added to the conversation to continue."},{"id":"final","label":"Model produces its final answer using the real result","explanation":"Only now does the model have what it needs to finish answering."}],"task":"Order the steps of a tool-calling cycle from first to last."}'::jsonb, '{"correctOrderIds":["request","toolcall","execute","return","final"]}'::jsonb),
  ('mission-ai-building-with-llms-08-o2-c1', 'mission-ai-building-with-llms-08-o2', 1, 'investigation', 'Find the evidence explaining why the model never produced a final answer.', '{"evidence":[{"id":"e1","label":"Trace log","detail":"Model returned a tool call requesting check_containment_status with argument system: echo; the application executed the function and logged a result of contained"},{"id":"e2","label":"Trace log, continued","detail":"No further message was ever sent back to the model after the function executed; the conversation ended there with no final assistant reply"},{"id":"e3","label":"Ops note","detail":"The application server had no errors or crashes logged during this request"}],"question":"The user never received a final answer, even though the tool call executed successfully. Which evidence explains why?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-building-with-llms-09-o1-c1', 'mission-ai-building-with-llms-09-o1', 1, 'multiple_choice', 'State what a function schema parameters field actually constrains.', '{"question":"A function schema for check_containment_status defines a required system parameter of type string. What does that actually constrain?","options":[{"id":"a","text":"Nothing -- function schemas are only documentation and are never enforced"},{"id":"b","text":"The exact argument shape the model is expected to provide when it calls this function, which the application should still validate before executing"},{"id":"c","text":"How fast the function itself runs once it is called"},{"id":"d","text":"The system message for the entire conversation"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-09-o2-c1', 'mission-ai-building-with-llms-09-o2', 1, 'code_debugging', 'Find the line that lets the model pass an argument value that should never be allowed.', '{"language":"python","code":"tool_schema = {\n    \"name\": \"check_containment_status\",\n    \"description\": \"Check the current containment status of a named system.\",\n    \"parameters\": {\n        \"type\": \"object\",\n        \"properties\": {\n            \"system\": {\"type\": \"string\"},\n        },\n        \"required\": [\"system\"],\n    },\n}","question":"This schema lets the model pass any string at all as system, including systems that do not exist or that this function was never meant to touch. Which line should restrict system to a fixed, known list of values?"}'::jsonb, '{"requiredLineIds":["            \"system\": {\"type\": \"string\"},"]}'::jsonb),

  ('mission-ai-building-with-llms-10-o1-c1', 'mission-ai-building-with-llms-10-o1', 1, 'multiple_choice', 'State what streaming actually changes about response delivery.', '{"question":"What does streaming actually change about how a chat completion response is delivered?","options":[{"id":"a","text":"The model computes a completely different answer than it would without streaming"},{"id":"b","text":"The response arrives in incremental chunks as they are generated, instead of as one complete block returned at the end"},{"id":"c","text":"Streaming removes the need for a system message"},{"id":"d","text":"Streaming guarantees the response can never fail partway through"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-10-o2-c1', 'mission-ai-building-with-llms-10-o2', 1, 'code_debugging', 'Find the line that displays each chunk but never saves it.', '{"language":"python","code":"full_reply = \"\"\nfor chunk in client.chat.completions.create(\n    model=\"cipher-llm-1\",\n    messages=messages,\n    stream=True,\n):\n    delta = chunk.choices[0].delta.content\n    print(delta)\n\ndisplay_to_user(full_reply)","question":"Each chunk shows up on screen as it arrives, but the value passed to display_to_user is always empty. Which line prints a chunk but never adds it to full_reply?"}'::jsonb, '{"requiredLineIds":["    print(delta)"]}'::jsonb),

  ('mission-ai-building-with-llms-11-o1-c1', 'mission-ai-building-with-llms-11-o1', 1, 'multiple_choice', 'State what an HTTP 429 response actually indicates.', '{"question":"A request comes back instantly with an HTTP 429 status. What does that actually indicate?","options":[{"id":"a","text":"The model refused to answer the question on ethical grounds"},{"id":"b","text":"Too many requests arrived in too short a window; the client should back off and retry after a delay, not immediately"},{"id":"c","text":"The network connection was physically severed"},{"id":"d","text":"The response was streamed instead of returned as one block"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-building-with-llms-11-o2-c1', 'mission-ai-building-with-llms-11-o2', 1, 'code_debugging', 'Find the line that retries immediately with no delay.', '{"language":"python","code":"for attempt in range(5):\n    try:\n        return call_model(messages)\n    except RateLimitError:\n        continue","question":"This retry loop hammers the provider with an identical request the instant it gets rate-limited. Which line retries with no delay or backoff at all?"}'::jsonb, '{"requiredLineIds":["        continue"]}'::jsonb),

  ('mission-ai-building-with-llms-12-o1-c1', 'mission-ai-building-with-llms-12-o1', 1, 'investigation', 'Diagnose the malformed-output failure and choose the engineered fix.', '{"evidence":[{"id":"e1","label":"Test run log","detail":"Under load, the model occasionally returns a response with a trailing comma or a missing closing brace, and JSON parsing fails every time this happens"},{"id":"e2","label":"Proposed response A","detail":"Catch the parse error, log it, and return whatever partial text arrived to the caller as if it were valid data"},{"id":"e3","label":"Proposed response B","detail":"Catch the parse error, validate against the schema, and if it fails, retry the request with a bounded attempt count, feeding the error back to the model"},{"id":"e4","label":"Proposed response C","detail":"Ignore the error and assume this will not happen again in production"}],"question":"Which proposed response is the correct, engineered fix for a model response that fails to parse as valid JSON?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),
  ('mission-ai-building-with-llms-12-o2-c1', 'mission-ai-building-with-llms-12-o2', 1, 'investigation', 'Diagnose the stalled-request failure and choose the engineered fix.', '{"evidence":[{"id":"e1","label":"Test run log","detail":"A request to the model occasionally never returns at all -- no error, no response, the connection just stays open indefinitely"},{"id":"e2","label":"Proposed response A","detail":"Let the request wait as long as it takes, since the model will eventually respond"},{"id":"e3","label":"Proposed response B","detail":"Set an explicit timeout on the request, and on timeout, retry with backoff up to a bounded number of attempts"},{"id":"e4","label":"Proposed response C","detail":"Restart the entire application whenever a single request stalls"}],"question":"Which proposed response is the correct, engineered fix for a request that stalls and never returns?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),
  ('mission-ai-building-with-llms-12-o3-c1', 'mission-ai-building-with-llms-12-o3', 1, 'investigation', 'Diagnose the bad-tool-call failure and choose the engineered fix.', '{"evidence":[{"id":"e1","label":"Test run log","detail":"The model requested a tool call to check_containment_status with a system argument set to a value that does not correspond to any real system Cipher Division tracks"},{"id":"e2","label":"Proposed response A","detail":"Execute the function immediately with whatever arguments the model provided"},{"id":"e3","label":"Proposed response B","detail":"Validate the tool call arguments against the function schema before executing anything, and reject the call if the arguments are invalid or unrecognized"},{"id":"e4","label":"Proposed response C","detail":"Assume the model always provides valid arguments, since it was given the function schema"}],"question":"Which proposed response is the correct, engineered fix for a tool call that arrives with a bad or unrecognized argument?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),
  ('mission-ai-building-with-llms-12-o4-c1', 'mission-ai-building-with-llms-12-o4', 1, 'boss_encounter', 'Bring the three engineered fixes together into a final verdict.', '{"stages":[{"objectiveRef":"mission-ai-building-with-llms-12-o1","label":"Handle the Malformed Response"},{"objectiveRef":"mission-ai-building-with-llms-12-o2","label":"Handle the Stalled Request"},{"objectiveRef":"mission-ai-building-with-llms-12-o3","label":"Handle the Bad Tool Call"}],"task":"Bring the three engineered fixes together and state the verdict: is this assistant ready to run unsupervised, and what made it that way?"}'::jsonb, '{"requiredObjectiveIds":["mission-ai-building-with-llms-12-o1","mission-ai-building-with-llms-12-o2","mission-ai-building-with-llms-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-building-with-llms-01-o1-c1', 'orientation', 'Think about what standing context the model needs before the user ever types anything.', 10, 1),
  ('mission-ai-building-with-llms-01-o1-c1', 'solution', 'The system role sets standing instructions and constraints that shape the model behavior for the entire conversation, set once rather than restated by the user.', 20, 2),
  ('mission-ai-building-with-llms-01-o2-c1', 'orientation', 'Only three roles are valid in a standard chat completion message list: system, user, and assistant.', 10, 1),
  ('mission-ai-building-with-llms-01-o2-c1', 'concept', '"human" looks like a reasonable word for who is talking, but it is not one of the roles the API actually recognizes.', 20, 2),
  ('mission-ai-building-with-llms-01-o2-c1', 'solution', 'The message using role "human" is invalid -- it needed to be "user" instead, matching one of the roles the API actually accepts.', 30, 3),

  ('mission-ai-building-with-llms-02-o1-c1', 'orientation', 'Ask which message gets set once, before any user turn, versus which one gets typed fresh every time.', 10, 1),
  ('mission-ai-building-with-llms-02-o1-c1', 'solution', 'A standing policy like this belongs in the system message, set once, so it applies by default to the whole conversation instead of needing to be repeated.', 20, 2),
  ('mission-ai-building-with-llms-02-o2-c1', 'orientation', 'A good system instruction should be specific enough that someone could check a transcript afterward and say whether it was followed.', 10, 1),
  ('mission-ai-building-with-llms-02-o2-c1', 'solution', 'Draft B is specific and checkable: answer only from provided evidence, and say so directly when the evidence does not cover it. Draft A is too vague to ever verify.', 20, 2),

  ('mission-ai-building-with-llms-03-o1-c1', 'orientation', 'State what needs doing before anything else can even be labeled reference material.', 10, 1),
  ('mission-ai-building-with-llms-03-o1-c1', 'concept', 'Reference material only makes sense once the model knows what task it supports; the output format only matters once both the task and the material are clear.', 20, 2),
  ('mission-ai-building-with-llms-03-o1-c1', 'solution', 'State the task, then provide the delimited reference material, then specify the exact output format expected.', 30, 3),
  ('mission-ai-building-with-llms-03-o2-c1', 'orientation', 'Ask what could go wrong if quoted text sat right next to an instruction with nothing marking where one ends and the other begins.', 10, 1),
  ('mission-ai-building-with-llms-03-o2-c1', 'solution', 'Delimiters let the model tell where an instruction ends and quoted content begins, instead of treating text inside the quote as another instruction to follow.', 20, 2),

  ('mission-ai-building-with-llms-04-o1-c1', 'orientation', 'Think about what code actually has to do with a paragraph of prose versus a fixed JSON object.', 10, 1),
  ('mission-ai-building-with-llms-04-o1-c1', 'solution', 'A fixed, parseable shape lets code read the exact fields it needs directly -- no fragile text-scraping that breaks the moment the model phrases something differently.', 20, 2),
  ('mission-ai-building-with-llms-04-o2-c1', 'orientation', 'json.loads only succeeds if the model actually returned pure JSON and nothing else around it.', 10, 1),
  ('mission-ai-building-with-llms-04-o2-c1', 'concept', 'Neither prompt ever tells the model to return JSON only, with no explanation text wrapped around it.', 20, 2),
  ('mission-ai-building-with-llms-04-o2-c1', 'solution', 'user_prompt never instructs the model to respond with JSON only. Without that instruction, the model is free to answer in prose, which json.loads cannot parse.', 30, 3),

  ('mission-ai-building-with-llms-05-o1-c1', 'orientation', 'Ask what happens to the output if a field listed here is missing.', 10, 1),
  ('mission-ai-building-with-llms-05-o1-c1', 'solution', 'Required means the output is invalid unless that field is present -- it is not a suggestion, it is a condition for a passing response.', 20, 2),
  ('mission-ai-building-with-llms-05-o2-c1', 'orientation', 'Match each keyword to the one specific thing it constrains: shape, type, presence, or allowed values.', 10, 1),
  ('mission-ai-building-with-llms-05-o2-c1', 'solution', 'type sets the data type, required lists must-have fields, enum restricts to a fixed list of values, and properties defines the full set of fields an object may have.', 20, 2),

  ('mission-ai-building-with-llms-06-o1-c1', 'orientation', 'A schema in the request is a target for the model to aim at. It is not proof the model actually hit it.', 10, 1),
  ('mission-ai-building-with-llms-06-o1-c1', 'solution', 'Even after requesting a schema, code should validate the parsed result -- required fields present, correct types -- before trusting any of the values.', 20, 2),
  ('mission-ai-building-with-llms-06-o2-c1', 'orientation', 'Look for a validation step between parsing the JSON and using its fields for anything real.', 10, 1),
  ('mission-ai-building-with-llms-06-o2-c1', 'concept', 'There is no call here that checks the parsed data against the schema before it gets used -- parsing succeeding is not the same as the data being correct.', 20, 2),
  ('mission-ai-building-with-llms-06-o2-c1', 'solution', 'incident_id gets pulled straight out of the parsed data and used with no validation step ever having run -- the code assumes the schema was followed instead of confirming it.', 30, 3),

  ('mission-ai-building-with-llms-07-o1-c1', 'orientation', 'Nothing can be checked before the response has actually been sent and something has come back to parse.', 10, 1),
  ('mission-ai-building-with-llms-07-o1-c1', 'concept', 'Failing safely after too many attempts is just as much a designed step as retrying is -- an unbounded loop is not a safety net.', 20, 2),
  ('mission-ai-building-with-llms-07-o1-c1', 'solution', 'Send the request, parse and validate the response, check whether it succeeded, retry with the error fed back on failure, and fail safely once the attempt limit is reached.', 30, 3),
  ('mission-ai-building-with-llms-07-o2-c1', 'orientation', 'Ask what stops this loop from running if the model keeps failing every single time.', 10, 1),
  ('mission-ai-building-with-llms-07-o2-c1', 'concept', 'There is no attempt counter checked against a maximum anywhere in this loop, only a condition that is always true.', 20, 2),
  ('mission-ai-building-with-llms-07-o2-c1', 'solution', 'while True: never stops on its own -- it needed a bounded attempt count checked each time through the loop, with a safe failure once that limit is reached.', 30, 3),

  ('mission-ai-building-with-llms-08-o1-c1', 'orientation', 'The model never runs a real function itself -- something else has to actually execute it.', 10, 1),
  ('mission-ai-building-with-llms-08-o1-c1', 'concept', 'The model cannot finish a real answer until it has seen the actual result of the function it asked for.', 20, 2),
  ('mission-ai-building-with-llms-08-o1-c1', 'solution', 'Send the request with tool definitions, receive a tool call from the model, execute the real function locally, send the result back as a new message, then let the model produce its final answer.', 30, 3),
  ('mission-ai-building-with-llms-08-o2-c1', 'orientation', 'The function executed successfully. Ask what should have happened immediately after that, and whether it actually did.', 10, 1),
  ('mission-ai-building-with-llms-08-o2-c1', 'solution', 'The function result was never sent back to the model as a new message -- without that, the model has nothing to finish its answer with, and the conversation just stops.', 20, 2),

  ('mission-ai-building-with-llms-09-o1-c1', 'orientation', 'A function schema describes what the model should send, not what happens once the real function runs.', 10, 1),
  ('mission-ai-building-with-llms-09-o1-c1', 'solution', 'The schema defines the exact argument shape the model is expected to provide, and the application should still validate it before ever executing anything.', 20, 2),
  ('mission-ai-building-with-llms-09-o2-c1', 'orientation', 'Ask what stops the model from passing a system value that does not correspond to anything real.', 10, 1),
  ('mission-ai-building-with-llms-09-o2-c1', 'concept', 'A plain string type has no restriction on which values are allowed -- it accepts anything that is text at all.', 20, 2),
  ('mission-ai-building-with-llms-09-o2-c1', 'solution', '"system": {"type": "string"} needed an enum listing the actual known systems, so the model cannot pass a value this function was never meant to handle.', 30, 3),

  ('mission-ai-building-with-llms-10-o1-c1', 'orientation', 'Ask whether the model computes something different, or whether only the delivery of the same answer changes.', 10, 1),
  ('mission-ai-building-with-llms-10-o1-c1', 'solution', 'Streaming only changes delivery -- the response arrives in incremental chunks as they are generated, instead of as one block returned at the end.', 20, 2),
  ('mission-ai-building-with-llms-10-o2-c1', 'orientation', 'full_reply is created empty and never appears again until it gets displayed at the end.', 10, 1),
  ('mission-ai-building-with-llms-10-o2-c1', 'concept', 'Printing a chunk shows it on screen, but showing something and saving it are two different actions -- one of them is missing here.', 20, 2),
  ('mission-ai-building-with-llms-10-o2-c1', 'solution', 'print(delta) only displays each chunk -- it never adds delta to full_reply, so by the time display_to_user runs, full_reply is still empty.', 30, 3),

  ('mission-ai-building-with-llms-11-o1-c1', 'orientation', 'A 429 is not the model making a decision about the question -- it is the provider making a decision about the request rate.', 10, 1),
  ('mission-ai-building-with-llms-11-o1-c1', 'solution', 'A 429 means too many requests arrived too fast; the client should back off and retry after a delay, not immediately repeat the same request.', 20, 2),
  ('mission-ai-building-with-llms-11-o2-c1', 'orientation', 'Ask how much time passes between this exception being caught and the next attempt starting.', 10, 1),
  ('mission-ai-building-with-llms-11-o2-c1', 'concept', 'continue jumps straight back to the top of the loop with nothing in between -- no wait, no delay, nothing that actually counts as backoff.', 20, 2),
  ('mission-ai-building-with-llms-11-o2-c1', 'solution', 'continue retries immediately with zero delay -- it needed a growing wait, such as an increasing sleep, before the next attempt.', 30, 3),

  ('mission-ai-building-with-llms-12-o1-c1', 'orientation', 'Ignoring the error is not a fix, and treating partial text as if it were valid data is worse than the crash it avoids.', 10, 1),
  ('mission-ai-building-with-llms-12-o1-c1', 'solution', 'Response B is the engineered fix: validate against the schema, and on failure, retry with a bounded attempt count while feeding the error back to the model.', 20, 2),
  ('mission-ai-building-with-llms-12-o2-c1', 'orientation', 'Waiting indefinitely is not patience -- it is an application with no upper bound on how long it can hang.', 10, 1),
  ('mission-ai-building-with-llms-12-o2-c1', 'solution', 'Response B is the engineered fix: an explicit timeout, with retry and backoff up to a bounded number of attempts, instead of waiting forever or restarting everything.', 20, 2),
  ('mission-ai-building-with-llms-12-o3-c1', 'orientation', 'A correct function schema does not guarantee the model always sends arguments that match it.', 10, 1),
  ('mission-ai-building-with-llms-12-o3-c1', 'solution', 'Response B is the engineered fix: validate the tool call arguments against the function schema before executing anything, and reject the call outright if they do not hold up.', 20, 2),
  ('mission-ai-building-with-llms-12-o4-c1', 'orientation', 'Look at what all three engineered fixes have in common as an approach, not as three separate technical answers.', 15, 1),
  ('mission-ai-building-with-llms-12-o4-c1', 'solution', 'Every failure mode -- malformed output, a stalled connection, a bad tool call -- now has a validated, bounded, engineered response instead of an assumption that it will not happen. That is what makes the assistant ready to run unsupervised.', 25, 2);
