-- Robotics/Embedded/IoT pathway ("Vector Division") Act 6 -- "Time Is a
-- Requirement" content, under world-vec-time-is-a-requirement (already
-- inserted separately, act-vec-2, index 5). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns ->
-- operations -> missions -> dialogue -> objectives -> challenges -> hints
-- pattern as every prior Act. No new ChallengeType needed -- reuses
-- story_dialogue, multiple_choice, drag_and_drop, investigation,
-- interactive_diagram, browser_simulation (generic console fallback) and
-- boss_encounter.
--
-- This Act opens Arc II ("Firmware Controls Reality"). Vector Division
-- writes its first real firmware fix for the door frozen back in Act 4 --
-- and discovers the fix is logically correct and still misses its
-- deadline once, because its interrupt handler blocked on a slow sensor
-- read at exactly the moment the door's own hardware safety timeout was
-- also expiring. The boss mission ("Missed Deadline") traces that one
-- failure end to end and closes on the requirement that sets up Act 7:
-- a fix that only works on the bench cannot be trusted on a live system.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-time-is-a-requirement', 'world-vec-time-is-a-requirement', 'time-is-a-requirement', '2A - Time Is a Requirement', 'Learn the vocabulary of firmware timing -- polling and interrupts, interrupt service routines, latency and jitter, timer scheduling, finite state machines, cooperative and preemptive scheduling, critical sections, atomic operations, priority inversion and real-time thinking -- while Vector Division learns why its first real firmware fix for the door was logically correct and still missed its deadline.', 6);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-time-is-a-requirement-1', 'campaign-vec-time-is-a-requirement', 'reacting-in-time', 'Reacting In Time', 'Polling versus interrupts, interrupt service routines, latency and jitter, timer scheduling, finite state machines and cooperative scheduling -- the vocabulary firmware uses to notice the world and respond to it in time.', 1),
  ('operation-vec-time-is-a-requirement-2', 'campaign-vec-time-is-a-requirement', 'the-deadline-that-was-real', 'The Deadline That Was Real', 'Preemption, critical sections, atomic operations, priority inversion and real-time thinking -- the concepts that decide whether a logically correct fix survives contact with a hardware deadline.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-time-is-a-requirement-01', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'polling-vs-interrupts', 'Polling vs Interrupts', 'Vector Division has a firmware fix ready for the door that froze mid-cycle back in Act 4. It passed every functional test on the bench. Before it goes anywhere near a live door, Tomas Vey wants to know whether polling or interrupts decided how fast it actually reacts -- because that choice is about to matter more than the logic ever did.', 'beginner', ARRAY['imani','tomas','byte'], null, null, '{"type":"simulation","simulationId":"polling-vs-interrupts-sim"}'::jsonb, '{"xp":130,"credits":20}'::jsonb, false, 1),
  ('mission-vec-time-is-a-requirement-02', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'interrupt-service-routines', 'Interrupt Service Routines', 'An interrupt only buys speed if the code running inside it behaves. Tomas walks the door fix''s interrupt service routine and the one rule it cannot afford to break.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"interrupt-service-routines-sim"}'::jsonb, '{"xp":130,"credits":20}'::jsonb, false, 2),
  ('mission-vec-time-is-a-requirement-03', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'latency-and-jitter', 'Latency and Jitter', 'Fast on average is not the same claim as fast every time. Latency measures the delay; jitter measures how much that delay can swing -- and one swing is about to explain everything.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"latency-and-jitter-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 3),
  ('mission-vec-time-is-a-requirement-04', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'timer-scheduling', 'Timer Scheduling', 'The door does not wait patiently for firmware to finish thinking. Its own hardware safety timeout is already counting down, on a clock the fix does not control.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"timer-scheduling-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 4),
  ('mission-vec-time-is-a-requirement-05', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'finite-state-machines', 'Finite State Machines', 'Four states, fixed rules, no exceptions -- the fix finally has to enforce the same state machine Act 1 only ever observed from the outside.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"finite-state-machines-sim"}'::jsonb, '{"xp":150,"credits":25}'::jsonb, false, 5),
  ('mission-vec-time-is-a-requirement-06', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-1', 'cooperative-scheduling', 'Cooperative Scheduling', 'One task at a time, each expected to step aside politely. Cooperative scheduling only holds together if every task actually keeps that promise.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"cooperative-scheduling-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 6),
  ('mission-vec-time-is-a-requirement-07', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'preemption-concepts', 'Preemption Concepts', 'An interrupt does not ask permission to preempt whatever was running. That is exactly why nothing can rescue an interrupt handler that misbehaves once it has already started.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"preemption-concepts-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 7),
  ('mission-vec-time-is-a-requirement-08', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'critical-sections', 'Critical Sections', 'Every interrupt handler is already a critical section by hardware guarantee. The only question left is how long it stays safe to make it run.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"critical-sections-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 8),
  ('mission-vec-time-is-a-requirement-09', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'atomic-operations', 'Atomic Operations', 'A quick flag check and a slow sensor read look similar on paper. Only one of them is atomic -- and the door fix mistook one for the other.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"atomic-operations-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 9),
  ('mission-vec-time-is-a-requirement-10', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'priority-inversion', 'Priority Inversion', 'A famous scheduling failure has a precise definition, and the door fix''s bug does not quite match it. Telling the two apart keeps the investigation honest.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"priority-inversion-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 10),
  ('mission-vec-time-is-a-requirement-11', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'real-time-thinking', 'Real-Time Thinking', 'Every lesson this Act collapses into one habit: judge code by whether it finishes in time, not only by whether it computes the right answer.', 'beginner', ARRAY['tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"real-time-thinking-sim"}'::jsonb, '{"xp":180,"credits":35}'::jsonb, false, 11),
  ('mission-vec-time-is-a-requirement-12', 'world-vec-time-is-a-requirement', 'campaign-vec-time-is-a-requirement', 'operation-vec-time-is-a-requirement-2', 'missed-deadline', 'Missed Deadline', 'Bench testing just reproduced the one run in thousands where the door fix''s logic was correct and the door sealed too late anyway. Vector Division has to trace exactly where those milliseconds went, and prove it, before this fix goes near anything alive.', 'boss', ARRAY['imani','tomas','byte'], '{"requiredMissionIds":["mission-vec-time-is-a-requirement-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"missed-deadline-boss-sim"}'::jsonb, '{"xp":650,"credits":140,"badgeIds":["missed-the-deadline"],"skillXp":{"robotics_fundamentals":85}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-time-is-a-requirement-01', 1, 'imani', 'Vector Division has a firmware fix ready for the door that froze mid-cycle back in Act 4''s incident. The code passed every check on the bench. Before anyone certifies it, I want to know it will actually run in time on real hardware, not just correctly.'),
  ('mission-vec-time-is-a-requirement-01', 2, 'tomas', 'Correct and correct-in-time are not the same claim, and this Act is where we stop treating them as one. First question: how does firmware even notice something happened in the first place?'),
  ('mission-vec-time-is-a-requirement-01', 3, 'tomas', 'Two approaches, same job. Polling checks a sensor over and over in a loop, whether or not anything changed. An interrupt lets the hardware itself tap the processor on the shoulder the instant a condition is true, and everything else pauses to listen.'),
  ('mission-vec-time-is-a-requirement-01', 4, 'byte', 'Our fix uses an interrupt -- fast to react, in theory. But "in theory" is exactly the phrase Tomas keeps warning me not to trust anymore.'),
  ('mission-vec-time-is-a-requirement-01', 5, 'tomas', 'Then let us stop trusting it and start proving it.'),

  ('mission-vec-time-is-a-requirement-02', 1, 'tomas', 'The code that runs the instant an interrupt fires has a name: the interrupt service routine, or ISR. It is not an ordinary function. Ordinary code assumes it can take as long as it wants. An ISR cannot assume that.'),
  ('mission-vec-time-is-a-requirement-02', 2, 'tomas', 'The rule is simple to say and hard to follow: keep an ISR as short as possible, and never let it wait on anything slow. Every other part of the system is frozen, or at least deprioritized, for as long as that ISR is running.'),
  ('mission-vec-time-is-a-requirement-02', 3, 'byte', 'Which means whatever runs inside the door fix''s ISR had better already be fast, or it is holding the entire processor hostage without anyone choosing that on purpose.'),

  ('mission-vec-time-is-a-requirement-03', 1, 'tomas', 'Latency is the delay between an event happening and the system''s response to it. Every real system has some latency. The question is never whether, it is how much, and how consistent.'),
  ('mission-vec-time-is-a-requirement-03', 2, 'tomas', 'Jitter is how much that delay varies from one occurrence to the next. A system with high latency but zero jitter is at least predictable. A system with low average latency but occasional huge spikes can be far more dangerous.'),
  ('mission-vec-time-is-a-requirement-03', 3, 'byte', 'So a fix that responds fast almost every time and then, once, responds catastrophically late -- that is not a latency problem in the way most people mean it. That is a jitter problem.'),
  ('mission-vec-time-is-a-requirement-03', 4, 'tomas', 'Keep that distinction. It is going to matter more than anything else you learn this Act.'),

  ('mission-vec-time-is-a-requirement-04', 1, 'tomas', 'Hardware timers are how firmware measures time without watching a clock on a wall. Set one to count down from a fixed value, and when it hits zero, it can fire its own interrupt -- no software loop required.'),
  ('mission-vec-time-is-a-requirement-04', 2, 'tomas', 'The door itself has one of these. A hardware safety timeout, counting independently of anything our fix does. If the door has not confirmed a safe seal by the time that timer expires, the timeout wins and forces a fault state.'),
  ('mission-vec-time-is-a-requirement-04', 3, 'byte', 'So there are two clocks that matter here: how long our fix actually takes to respond, and how long the door''s own timeout gives it before deciding the fix failed. Those numbers are about to matter to each other.'),

  ('mission-vec-time-is-a-requirement-05', 1, 'tomas', 'A finite state machine is a fixed set of named states, plus rules for exactly which state can move to which other state, and on what trigger. It is the cleanest way to describe a door, and it is the cleanest way to describe firmware that controls one.'),
  ('mission-vec-time-is-a-requirement-05', 2, 'tomas', 'The fix models the door across four states -- OPEN, CLOSING, SEALED, FAULT -- the same four Byte''s Act 1 investigation already found in the door''s telemetry. Firmware just has to actually enforce the transitions this time.'),
  ('mission-vec-time-is-a-requirement-05', 3, 'byte', 'Which means every legal path through this machine already existed on paper. The only new question is whether the fix always reaches SEALED before the door''s own timeout reaches FAULT.'),

  ('mission-vec-time-is-a-requirement-06', 1, 'tomas', 'Vector Division''s firmware runs more than one task on a single processor. Cooperative scheduling means each task voluntarily yields control back to the scheduler when it is done, or when it is safe to pause -- nothing forces it to give up the processor.'),
  ('mission-vec-time-is-a-requirement-06', 2, 'tomas', 'That works cleanly as long as every task actually yields when it says it will. A task that keeps running past its turn, waiting on something slow, is not just late. It is blocking every other task behind it too.'),
  ('mission-vec-time-is-a-requirement-06', 3, 'byte', 'The door fix''s main loop is written this way -- one task at a time, each expected to finish or yield quickly. If the interrupt handler we already looked at ever behaves like a task that refuses to yield, cooperative scheduling has no way to force it aside.'),

  ('mission-vec-time-is-a-requirement-07', 1, 'tomas', 'Preemption is the opposite instinct. A preemptive scheduler can forcibly suspend a running task to let a higher-priority one run, with or without the first task''s permission.'),
  ('mission-vec-time-is-a-requirement-07', 2, 'tomas', 'Interrupts are already a form of preemption -- the hardware itself preempts whatever code was running, no yielding required. That is exactly why an ISR is dangerous if it misbehaves: nothing can preempt it back.'),
  ('mission-vec-time-is-a-requirement-07', 3, 'byte', 'So once that ISR starts running, it is the highest-priority thing on the entire processor, by hardware guarantee, whether it deserves to be or not.'),

  ('mission-vec-time-is-a-requirement-08', 1, 'tomas', 'A critical section is any stretch of code that touches shared data or shared hardware in a way that breaks if it gets interrupted halfway through. While a task is inside one, it usually needs to run without being disturbed.'),
  ('mission-vec-time-is-a-requirement-08', 2, 'tomas', 'The trap is that people learn to protect the critical section and stop there. Protecting it from being interrupted is not the same question as how long it is safe to make it run once nothing can interrupt it.'),
  ('mission-vec-time-is-a-requirement-08', 3, 'byte', 'And an ISR is already, by hardware guarantee, one giant critical section the instant it starts. Which means every rule about keeping critical sections short applies to it doubled.'),

  ('mission-vec-time-is-a-requirement-09', 1, 'tomas', 'An atomic operation is one that completes as a single indivisible step, from the rest of the system''s point of view. Nothing can observe it half-finished, and nothing can interrupt it partway through.'),
  ('mission-vec-time-is-a-requirement-09', 2, 'tomas', 'Reading a single hardware flag bit is usually atomic. Reading a sensor over a slow bus, waiting for it to finish converting and respond, is the opposite of atomic -- it is a whole sequence of steps stretched out over time.'),
  ('mission-vec-time-is-a-requirement-09', 3, 'byte', 'Which is the exact distinction the door fix got wrong. It treated a slow sensor read like it was a quick, atomic flag check, and put it directly inside the one place that could least afford to wait.'),

  ('mission-vec-time-is-a-requirement-10', 1, 'tomas', 'Priority inversion is a specific, famous failure: a high-priority task ends up waiting on a low-priority task that is holding a resource it needs, while a medium-priority task keeps running in between and delays everyone.'),
  ('mission-vec-time-is-a-requirement-10', 2, 'tomas', 'It is not what happened to our fix. There was no lock being held by a low-priority task, and nothing medium-priority cut in line. I want you to be able to tell the two apart, because they get confused constantly, and confusing them wastes an investigation.'),
  ('mission-vec-time-is-a-requirement-10', 3, 'byte', 'So the door fix''s bug is priority inversion''s cousin, not priority inversion itself. Same neighborhood -- a task waiting too long for the wrong reason -- different exact mechanism.'),

  ('mission-vec-time-is-a-requirement-11', 1, 'tomas', 'Everything this Act taught is really one habit: stop asking only whether code computes the right answer, and start asking whether it computes it inside the time the physical world actually allows.'),
  ('mission-vec-time-is-a-requirement-11', 2, 'tomas', 'A real-time system does not get graded on being fast on average. It gets graded on its worst case, because the worst case is the one moment a deadline actually gets tested.'),
  ('mission-vec-time-is-a-requirement-11', 3, 'byte', 'By every functional test Vector Division ran, the door fix was correct. It is only when you ask how late can this get, even once, that the story changes.'),
  ('mission-vec-time-is-a-requirement-11', 4, 'tomas', 'That question is the whole Act. Let us go answer it, on the one board where it already went wrong.'),

  ('mission-vec-time-is-a-requirement-12', 1, 'imani', 'Bench testing just reproduced it. One run, out of thousands, where the door fix did not seal in time, and the door''s own safety timeout won instead. I need the real explanation, in order, before this fix goes anywhere near a live system.'),
  ('mission-vec-time-is-a-requirement-12', 2, 'tomas', 'The fix''s logic was never wrong. Every functional test agrees on that. So walk the timing, not the code, from the interrupt to the timeout, and tell me exactly where those thousandths of a second went.'),
  ('mission-vec-time-is-a-requirement-12', 3, 'byte', 'Tracing it now. The ISR fired on schedule, right when the sensor edge occurred. Everything after that point is where it gets interesting.'),
  ('mission-vec-time-is-a-requirement-12', 4, 'tomas', 'Trace the block first. Then trace where it landed against the door''s own clock. Then tell me, in one sentence, what kind of bug this actually was.'),
  ('mission-vec-time-is-a-requirement-12', 5, 'imani', 'And once you can say it in one sentence, say the next one too: what does Vector Division have to guarantee before this fix, or anything like it, gets trusted on a door with people standing near it again?');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-time-is-a-requirement-01-o1', 'mission-vec-time-is-a-requirement-01', 1, 'Tell polling from interrupts', 'Sort each scenario into polling or interrupt-driven, before judging which one the door fix actually used.'),
  ('mission-vec-time-is-a-requirement-01-o2', 'mission-vec-time-is-a-requirement-01', 2, 'Judge the fix''s approach', 'Decide which approach the door fix used, and what that choice immediately commits the firmware to.'),

  ('mission-vec-time-is-a-requirement-02-o1', 'mission-vec-time-is-a-requirement-02', 1, 'Define an ISR''s obligation', 'Choose the accurate description of the core rule an interrupt service routine must follow.'),
  ('mission-vec-time-is-a-requirement-02-o2', 'mission-vec-time-is-a-requirement-02', 2, 'Locate the fix''s ISR', 'Find the evidence describing what code actually runs inside the door fix''s interrupt handler.'),

  ('mission-vec-time-is-a-requirement-03-o1', 'mission-vec-time-is-a-requirement-03', 1, 'Tell latency from jitter', 'Choose the accurate distinction between latency and jitter.'),
  ('mission-vec-time-is-a-requirement-03-o2', 'mission-vec-time-is-a-requirement-03', 2, 'Spot the jitter signature', 'Read the door fix''s timing log and find the record that reveals its real risk.'),

  ('mission-vec-time-is-a-requirement-04-o1', 'mission-vec-time-is-a-requirement-04', 1, 'Explain hardware timer scheduling', 'Choose the accurate description of what a hardware timer buys firmware.'),
  ('mission-vec-time-is-a-requirement-04-o2', 'mission-vec-time-is-a-requirement-04', 2, 'Identify the door''s own deadline', 'Find the evidence describing the door''s independent hardware safety timeout.'),

  ('mission-vec-time-is-a-requirement-05-o1', 'mission-vec-time-is-a-requirement-05', 1, 'Order the state machine', 'Order the door''s normal sealing path through its finite state machine.'),
  ('mission-vec-time-is-a-requirement-05-o2', 'mission-vec-time-is-a-requirement-05', 2, 'Judge a proposed transition', 'Decide whether skipping a state in the door''s model is ever legal.'),

  ('mission-vec-time-is-a-requirement-06-o1', 'mission-vec-time-is-a-requirement-06', 1, 'Explain cooperative scheduling', 'Choose the accurate description of how a cooperatively scheduled task gives up the processor.'),
  ('mission-vec-time-is-a-requirement-06-o2', 'mission-vec-time-is-a-requirement-06', 2, 'Judge the risk', 'Decide what happens to the rest of the system if one cooperative task never yields.'),

  ('mission-vec-time-is-a-requirement-07-o1', 'mission-vec-time-is-a-requirement-07', 1, 'Tell preemptive from cooperative', 'Choose the accurate distinction between preemptive and cooperative scheduling.'),
  ('mission-vec-time-is-a-requirement-07-o2', 'mission-vec-time-is-a-requirement-07', 2, 'Apply it to the ISR', 'Judge what, if anything, can preempt the door fix''s ISR once it has started.'),

  ('mission-vec-time-is-a-requirement-08-o1', 'mission-vec-time-is-a-requirement-08', 1, 'Define a critical section', 'Choose the accurate description of what makes a stretch of code a critical section.'),
  ('mission-vec-time-is-a-requirement-08-o2', 'mission-vec-time-is-a-requirement-08', 2, 'Spot the compounding risk', 'Judge why blocking inside an ISR is worse than blocking somewhere else in the system.'),

  ('mission-vec-time-is-a-requirement-09-o1', 'mission-vec-time-is-a-requirement-09', 1, 'Define atomicity', 'Choose the accurate description of what makes an operation atomic.'),
  ('mission-vec-time-is-a-requirement-09-o2', 'mission-vec-time-is-a-requirement-09', 2, 'Classify the sensor read', 'Find the evidence showing the sensor read the ISR relies on is not atomic.'),

  ('mission-vec-time-is-a-requirement-10-o1', 'mission-vec-time-is-a-requirement-10', 1, 'Define priority inversion precisely', 'Choose the precise definition of priority inversion.'),
  ('mission-vec-time-is-a-requirement-10-o2', 'mission-vec-time-is-a-requirement-10', 2, 'Rule it out for the door fix', 'Judge whether the door fix''s bug actually matches the mechanism of priority inversion.'),

  ('mission-vec-time-is-a-requirement-11-o1', 'mission-vec-time-is-a-requirement-11', 1, 'State the real-time mindset', 'Choose the accurate statement of what real-time thinking actually requires.'),
  ('mission-vec-time-is-a-requirement-11-o2', 'mission-vec-time-is-a-requirement-11', 2, 'Judge what actually matters for grading', 'Decide which metric determines whether a real-time deadline gets missed.'),

  ('mission-vec-time-is-a-requirement-12-o1', 'mission-vec-time-is-a-requirement-12', 1, 'Trace the block', 'Identify exactly where, in its execution, the ISR blocked on the one failing run.'),
  ('mission-vec-time-is-a-requirement-12-o2', 'mission-vec-time-is-a-requirement-12', 2, 'Trace the timing overlap', 'Read the failing run''s timing trace and find the record showing the overlap with the door''s own deadline.'),
  ('mission-vec-time-is-a-requirement-12-o3', 'mission-vec-time-is-a-requirement-12', 3, 'Classify the bug', 'Judge what kind of bug this actually was, given the fix was logically correct and still missed the deadline once.'),
  ('mission-vec-time-is-a-requirement-12-o4', 'mission-vec-time-is-a-requirement-12', 4, 'State the redesign mandate', 'Having traced the block, the overlap and the classification, state what the fix must guarantee before it is trusted on a live door.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-time-is-a-requirement-01-o1-c1', 'mission-vec-time-is-a-requirement-01-o1', 1, 'drag_and_drop', 'Sort each scenario into polling or interrupt-driven, based on how it notices something happened.', '{"items":[{"id":"i1","text":"A loop that checks a button pin every millisecond even when nothing has changed"},{"id":"i2","text":"A doorbell wired so pressing it immediately triggers a chime circuit, with nobody watching the wire"},{"id":"i3","text":"A thermostat that rechecks its temperature sensor once every scheduling cycle regardless of whether it changed"},{"id":"i4","text":"A hardware line that halts the running program the instant a sensor crosses its threshold"},{"id":"i5","text":"A background task that spends most of its time re-reading a status flag in a tight loop"}],"targets":[{"id":"polling","label":"Polling"},{"id":"interrupt","label":"Interrupt-driven"}]}'::jsonb, '{"correctMapping":{"i1":"polling","i2":"interrupt","i3":"polling","i4":"interrupt","i5":"polling"}}'::jsonb),
  ('mission-vec-time-is-a-requirement-01-o2-c1', 'mission-vec-time-is-a-requirement-01-o2', 1, 'multiple_choice', 'The door fix reacts to a sensor edge with no loop reading that sensor repeatedly anywhere in the code. Which approach did Vector Division use, and what does that choice immediately commit the firmware to?', '{"question":"The door fix reacts to a sensor edge with no loop reading that sensor repeatedly anywhere in the code. Which approach did Vector Division use, and what does that choice immediately commit the firmware to?","options":[{"id":"a","text":"Polling -- and it commits the firmware to wasting cycles checking nothing"},{"id":"b","text":"An interrupt -- and it commits the firmware to running that reaction inside a special interrupt context, with its own rules about what code is safe to put there"},{"id":"c","text":"Neither -- sensors report themselves without any code involved"},{"id":"d","text":"Polling -- and it commits the firmware to never missing an event"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-02-o1-c1', 'mission-vec-time-is-a-requirement-02-o1', 1, 'multiple_choice', 'What is the core rule an interrupt service routine must follow that ordinary code does not?', '{"question":"What is the core rule an interrupt service routine must follow that ordinary code does not?","options":[{"id":"a","text":"It must be written in a special language"},{"id":"b","text":"It must run to completion quickly and avoid waiting on anything slow, since it holds up the rest of the system while it runs"},{"id":"c","text":"It must always call other functions to stay organized"},{"id":"d","text":"It must poll a sensor internally before returning"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-02-o2-c1', 'mission-vec-time-is-a-requirement-02-o2', 1, 'investigation', 'Which evidence describes what code actually runs inside the door fix''s ISR?', '{"evidence":[{"id":"e1","label":"Firmware note","detail":"The door fix''s ISR fires on the sensor''s edge and immediately calls a routine that reads the sensor''s exact position"},{"id":"e2","label":"Facilities note","detail":"The door''s motor housing was repainted last maintenance cycle"},{"id":"e3","label":"Power log","detail":"The board draws nominal current throughout normal operation"}],"question":"Which evidence describes what code actually runs inside the door fix''s ISR?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-time-is-a-requirement-03-o1-c1', 'mission-vec-time-is-a-requirement-03-o1', 1, 'multiple_choice', 'Latency and jitter differ in that...', '{"question":"Latency and jitter differ in that...","options":[{"id":"a","text":"They are the same measurement with different names"},{"id":"b","text":"Latency is the delay from event to response; jitter is how much that delay varies across occurrences -- a system can have low average latency and still have dangerous jitter"},{"id":"c","text":"Jitter only applies to network systems, never firmware"},{"id":"d","text":"Latency is measured in volts, jitter in amps"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-03-o2-c1', 'mission-vec-time-is-a-requirement-03-o2', 1, 'browser_simulation', 'Which record reveals the fix''s real risk -- not its average performance, but its worst case?', '{"screen":"TIMING LOG -- DOOR FIX -- ISR RESPONSE INTERVALS","question":"Which record reveals the fix''s real risk -- not its average performance, but its worst case?","records":[{"id":"r1","code":"AVG=1.2ms","detail":"Average ISR response time across 10,000 trigger events"},{"id":"r2","code":"MIN=0.9ms","detail":"Fastest recorded ISR response time"},{"id":"r3","code":"MAX=340ms","detail":"One single recorded ISR response time, wildly outside every other sample, on trigger 6,204 of 10,000"},{"id":"r4","code":"COUNT=10000","detail":"Total trigger events sampled during bench testing"}]}'::jsonb, '{"correctOptionId":"r3"}'::jsonb),

  ('mission-vec-time-is-a-requirement-04-o1-c1', 'mission-vec-time-is-a-requirement-04-o1', 1, 'multiple_choice', 'A hardware timer that fires an interrupt when it reaches zero is useful because...', '{"question":"A hardware timer that fires an interrupt when it reaches zero is useful because...","options":[{"id":"a","text":"It replaces the need for any interrupt at all"},{"id":"b","text":"It lets firmware schedule a time-based event precisely, without a software loop burning cycles checking a clock"},{"id":"c","text":"It only works while the processor is powered off"},{"id":"d","text":"It can only be set once per device lifetime"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-04-o2-c1', 'mission-vec-time-is-a-requirement-04-o2', 1, 'investigation', 'Which evidence describes the door''s own independent deadline?', '{"evidence":[{"id":"e1","label":"Hardware spec","detail":"The door''s safety timeout is a countdown timer, independent of the firmware fix, that forces a FAULT state if no confirmed seal signal arrives before it expires"},{"id":"e2","label":"Facilities note","detail":"The door''s hinges were serviced two years ago"},{"id":"e3","label":"Power log","detail":"Standby current draw is within spec"}],"question":"Which evidence describes the door''s own independent deadline?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-time-is-a-requirement-05-o1-c1', 'mission-vec-time-is-a-requirement-05-o1', 1, 'interactive_diagram', 'Order the door''s normal sealing path through its finite state machine, from first to last.', '{"diagramId":"door-fsm","hotspots":[{"id":"open","label":"OPEN","explanation":"Door at rest, fully open, no seal requested."},{"id":"closing","label":"CLOSING","explanation":"Seal requested, motor engaged, obstacle and occupancy sensors active."},{"id":"sealed","label":"SEALED","explanation":"Confirmed closed and locked, reached only after a clean CLOSING pass."}],"task":"Order the states of the door''s normal successful seal from first to last."}'::jsonb, '{"correctOrderIds":["open","closing","sealed"]}'::jsonb),
  ('mission-vec-time-is-a-requirement-05-o2-c1', 'mission-vec-time-is-a-requirement-05-o2', 1, 'multiple_choice', 'In the fix''s finite state machine, is a direct transition from OPEN straight to SEALED, skipping CLOSING, ever legal?', '{"question":"In the fix''s finite state machine, is a direct transition from OPEN straight to SEALED, skipping CLOSING, ever legal?","options":[{"id":"a","text":"Yes, if the door senses no obstacle"},{"id":"b","text":"No -- the model only defines OPEN, CLOSING, SEALED and FAULT, and only a completed CLOSING pass can lead to SEALED; skipping it is not a transition the machine allows"},{"id":"c","text":"Yes, but only during maintenance mode"},{"id":"d","text":"State machines do not define illegal transitions, only legal ones"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-06-o1-c1', 'mission-vec-time-is-a-requirement-06-o1', 1, 'multiple_choice', 'In cooperative scheduling, a task gives up the processor...', '{"question":"In cooperative scheduling, a task gives up the processor...","options":[{"id":"a","text":"Whenever a higher-priority task demands it, automatically"},{"id":"b","text":"Only when it voluntarily yields or finishes -- the scheduler cannot force it aside"},{"id":"c","text":"Every single clock cycle, by hardware design"},{"id":"d","text":"Never -- cooperative tasks run forever once started"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-06-o2-c1', 'mission-vec-time-is-a-requirement-06-o2', 1, 'multiple_choice', 'Under cooperative scheduling, what happens if one task never yields because it is stuck waiting on something slow?', '{"question":"Under cooperative scheduling, what happens if one task never yields because it is stuck waiting on something slow?","options":[{"id":"a","text":"Nothing, other tasks run anyway on a separate core"},{"id":"b","text":"Every other task behind it is blocked too, since nothing can force the stuck task aside"},{"id":"c","text":"The scheduler automatically kills the stuck task after one second"},{"id":"d","text":"Cooperative scheduling is immune to this problem by design"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-07-o1-c1', 'mission-vec-time-is-a-requirement-07-o1', 1, 'multiple_choice', 'Preemptive scheduling differs from cooperative scheduling in that...', '{"question":"Preemptive scheduling differs from cooperative scheduling in that...","options":[{"id":"a","text":"Preemptive scheduling can forcibly suspend a running task for a higher-priority one; cooperative scheduling can only ever wait for a task to yield"},{"id":"b","text":"They are identical, just different names for the same mechanism"},{"id":"c","text":"Cooperative scheduling is always faster than preemptive"},{"id":"d","text":"Preemptive scheduling never uses interrupts"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-time-is-a-requirement-07-o2-c1', 'mission-vec-time-is-a-requirement-07-o2', 1, 'multiple_choice', 'Once the door fix''s ISR begins running, what can preempt it?', '{"question":"Once the door fix''s ISR begins running, what can preempt it?","options":[{"id":"a","text":"Any other task in the system, at any time"},{"id":"b","text":"Effectively nothing on this hardware -- an ISR runs to completion once started, which is exactly why it must never run long or block"},{"id":"c","text":"The cooperative scheduler, the moment it wants to"},{"id":"d","text":"A lower-priority interrupt, immediately"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-08-o1-c1', 'mission-vec-time-is-a-requirement-08-o1', 1, 'multiple_choice', 'A critical section is best described as...', '{"question":"A critical section is best described as...","options":[{"id":"a","text":"Any function with more than ten lines of code"},{"id":"b","text":"A stretch of code touching shared data or hardware that must not be interrupted partway through without risking corruption or an inconsistent state"},{"id":"c","text":"Code that only runs once at startup"},{"id":"d","text":"A section of code written by a specific engineer"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-08-o2-c1', 'mission-vec-time-is-a-requirement-08-o2', 1, 'multiple_choice', 'Why is blocking inside an ISR worse than an ordinary function blocking somewhere else in the system?', '{"question":"Why is blocking inside an ISR worse than an ordinary function blocking somewhere else in the system?","options":[{"id":"a","text":"It is not worse, all blocking is equally bad"},{"id":"b","text":"An ISR is already a critical section nothing else can interrupt, so a block inside it does not just delay one task -- it stalls the entire processor for as long as the block lasts"},{"id":"c","text":"ISRs cannot technically block, so the question does not apply"},{"id":"d","text":"Blocking inside an ISR only affects that one interrupt''s future occurrences, nothing else"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-09-o1-c1', 'mission-vec-time-is-a-requirement-09-o1', 1, 'multiple_choice', 'An atomic operation is one that...', '{"question":"An atomic operation is one that...","options":[{"id":"a","text":"Always takes exactly one clock cycle, with no exceptions"},{"id":"b","text":"Completes as a single indivisible step that nothing can observe half-finished or interrupt partway through"},{"id":"c","text":"Can only be performed by hardware, never software"},{"id":"d","text":"Is any operation that returns a boolean value"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-09-o2-c1', 'mission-vec-time-is-a-requirement-09-o2', 1, 'investigation', 'Which evidence shows the sensor read is not an atomic operation?', '{"evidence":[{"id":"e1","label":"Bus spec","detail":"The sensor requires issuing a request, waiting for an internal conversion, then polling for a ready flag before the value can be read -- a multi-step exchange, not a single register access"},{"id":"e2","label":"Facilities note","detail":"The sensor was calibrated during the last maintenance window"},{"id":"e3","label":"Power log","detail":"The sensor draws consistent current whether idle or converting"}],"question":"Which evidence shows the sensor read is not an atomic operation?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-time-is-a-requirement-10-o1-c1', 'mission-vec-time-is-a-requirement-10-o1', 1, 'multiple_choice', 'Priority inversion specifically describes...', '{"question":"Priority inversion specifically describes...","options":[{"id":"a","text":"Any situation where a task runs slower than expected"},{"id":"b","text":"A high-priority task blocked waiting on a resource held by a low-priority task, while an unrelated medium-priority task keeps preempting and delaying the low-priority task from finishing"},{"id":"c","text":"An interrupt firing at the wrong priority level"},{"id":"d","text":"A scheduler that runs tasks in reverse order"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-10-o2-c1', 'mission-vec-time-is-a-requirement-10-o2', 1, 'multiple_choice', 'Does the door fix''s bug -- an ISR blocking on a slow sensor read -- match the specific mechanism of priority inversion?', '{"question":"Does the door fix''s bug -- an ISR blocking on a slow sensor read -- match the specific mechanism of priority inversion?","options":[{"id":"a","text":"Yes, exactly -- any delay caused by waiting counts as priority inversion"},{"id":"b","text":"No -- there is no lower-priority task holding a needed resource and no medium-priority task cutting in line; this is a blocking-inside-an-ISR problem, a related but distinct failure"},{"id":"c","text":"Yes, because the ISR is technically the lowest-priority code on the system"},{"id":"d","text":"It cannot be determined without a scheduler more complex than this one"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-11-o1-c1', 'mission-vec-time-is-a-requirement-11-o1', 1, 'multiple_choice', 'Real-time thinking, as this Act has built it up, means...', '{"question":"Real-time thinking, as this Act has built it up, means...","options":[{"id":"a","text":"Writing code as fast as possible in every case"},{"id":"b","text":"Judging correctness not only by what a program computes, but also by whether it computes it inside the deadline the physical world imposes"},{"id":"c","text":"Avoiding interrupts entirely in favor of polling"},{"id":"d","text":"Testing only the average-case performance of a system"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-11-o2-c1', 'mission-vec-time-is-a-requirement-11-o2', 1, 'multiple_choice', 'For a real-time system, which metric matters most for judging whether a deadline will be missed?', '{"question":"For a real-time system, which metric matters most for judging whether a deadline will be missed?","options":[{"id":"a","text":"Average response time across many trials"},{"id":"b","text":"Worst-case response time -- the rare, slowest occurrence is the one that actually determines whether a hard deadline gets missed"},{"id":"c","text":"Total number of successful responses"},{"id":"d","text":"The system''s idle power draw"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-time-is-a-requirement-12-o1-c1', 'mission-vec-time-is-a-requirement-12-o1', 1, 'multiple_choice', 'Byte traces the ISR''s execution on the one failing run. Where did it actually block?', '{"question":"Byte traces the ISR''s execution on the one failing run. Where did it actually block?","options":[{"id":"a","text":"It never blocked; the ISR ran to completion instantly every time"},{"id":"b","text":"Inside the ISR itself, at the call to read the sensor over its slow bus -- the exact operation shown earlier not to be atomic -- while the hardware guarantee that nothing preempts an ISR meant nothing could rescue it"},{"id":"c","text":"In the cooperative scheduler, which refused to run the ISR at all"},{"id":"d","text":"In a completely unrelated low-priority task holding a lock"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-12-o2-c1', 'mission-vec-time-is-a-requirement-12-o2', 1, 'browser_simulation', 'Which record shows exactly where this run''s delay overlapped the door''s own deadline?', '{"screen":"TIMING TRACE -- FAILING RUN -- ISR vs DOOR SAFETY TIMEOUT","question":"Which record shows exactly where this run''s delay overlapped the door''s own deadline?","records":[{"id":"r1","code":"ISR_START=t+0.0ms","detail":"ISR begins on the sensor edge, same as every other run"},{"id":"r2","code":"ISR_BLOCK=289ms","detail":"ISR stalls inside the sensor read on the slow bus for 289 milliseconds, versus roughly 1 millisecond on every other recorded run"},{"id":"r3","code":"TIMEOUT_WINDOW=300ms","detail":"Door''s independent hardware safety timeout expires 300 milliseconds after CLOSING begins, regardless of what the fix is doing"},{"id":"r4","code":"SEAL_CONFIRMED=none","detail":"No confirmed seal signal reached the door before its timeout fired"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-time-is-a-requirement-12-o3-c1', 'mission-vec-time-is-a-requirement-12-o3', 1, 'multiple_choice', 'Given the ISR was logically correct but blocked for 289 of a 300 millisecond deadline window on one run in thousands, what kind of bug was this?', '{"question":"Given the ISR was logically correct but blocked for 289 of a 300 millisecond deadline window on one run in thousands, what kind of bug was this?","options":[{"id":"a","text":"A logic bug -- the fix computed the wrong seal decision"},{"id":"b","text":"A timing bug -- the fix always computed the correct decision, but a non-atomic, blocking sensor read inside an interrupt context occasionally consumed almost the entire deadline before that correct decision could ever be delivered"},{"id":"c","text":"A power bug -- insufficient voltage caused the miss"},{"id":"d","text":"Not a bug at all -- the door''s timeout itself is misconfigured"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-time-is-a-requirement-12-o4-c1', 'mission-vec-time-is-a-requirement-12-o4', 1, 'boss_encounter', 'Having traced the block, the timing overlap and classified the bug, state the fix''s redesign mandate and what it means for deployment.', '{"stages":[{"objectiveRef":"mission-vec-time-is-a-requirement-12-o1","label":"Trace the block"},{"objectiveRef":"mission-vec-time-is-a-requirement-12-o2","label":"Trace the timing overlap"},{"objectiveRef":"mission-vec-time-is-a-requirement-12-o3","label":"Classify the bug"}],"task":"State the mandate in one sentence: the interrupt handler must never call anything that can block -- a slow sensor read has no place inside it -- and a fix that only works on the bench is not a fix that can be trusted on a live system, because deploying it for real means finally learning to speak the maintenance bus''s own language, not just read it."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-time-is-a-requirement-12-o1","mission-vec-time-is-a-requirement-12-o2","mission-vec-time-is-a-requirement-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-time-is-a-requirement-01-o1-c1', 'orientation', 'Ask whether the system checks repeatedly no matter what, or reacts only when something actually changes.', 10, 1),
  ('mission-vec-time-is-a-requirement-01-o1-c1', 'solution', 'Polling: the button loop, the thermostat recheck, and the background flag-reading task (i1, i3, i5). Interrupt-driven: the doorbell chime and the threshold-crossing hardware line (i2, i4).', 20, 2),
  ('mission-vec-time-is-a-requirement-01-o2-c1', 'orientation', 'Look for whether anything in the fix repeatedly rereads the sensor in a loop.', 10, 1),
  ('mission-vec-time-is-a-requirement-01-o2-c1', 'solution', 'No repeated read means it is interrupt-driven, which commits the fix to running its reaction inside a special interrupt context with its own rules.', 20, 2),

  ('mission-vec-time-is-a-requirement-02-o1-c1', 'orientation', 'Ask what an ISR is allowed to assume about how long it can safely take.', 10, 1),
  ('mission-vec-time-is-a-requirement-02-o1-c1', 'solution', 'An ISR must run to completion quickly and never wait on anything slow, since it holds up the rest of the system for as long as it runs.', 20, 2),
  ('mission-vec-time-is-a-requirement-02-o2-c1', 'orientation', 'Look for the firmware note describing what the ISR actually calls, not a note about the door''s appearance.', 10, 1),
  ('mission-vec-time-is-a-requirement-02-o2-c1', 'solution', 'e1: the ISR fires on the sensor''s edge and immediately calls a routine that reads the sensor''s exact position.', 20, 2),

  ('mission-vec-time-is-a-requirement-03-o1-c1', 'orientation', 'One measures the delay itself; the other measures how much that delay changes between occurrences.', 10, 1),
  ('mission-vec-time-is-a-requirement-03-o1-c1', 'solution', 'Latency is the delay from event to response; jitter is how much that delay varies -- low average latency can still hide dangerous jitter.', 20, 2),
  ('mission-vec-time-is-a-requirement-03-o2-c1', 'orientation', 'Ignore the average and the minimum -- look for the one value that stands far outside the rest.', 10, 1),
  ('mission-vec-time-is-a-requirement-03-o2-c1', 'solution', 'r3, the single 340 millisecond response buried among thousands of sub-2-millisecond ones, is the real risk -- the worst case, not the average.', 20, 2),

  ('mission-vec-time-is-a-requirement-04-o1-c1', 'orientation', 'Think about what a software loop would otherwise have to do to catch the same moment.', 10, 1),
  ('mission-vec-time-is-a-requirement-04-o1-c1', 'solution', 'A hardware timer lets firmware schedule a time-based event precisely without a software loop burning cycles checking a clock.', 20, 2),
  ('mission-vec-time-is-a-requirement-04-o2-c1', 'orientation', 'Look for the evidence describing a timer that runs independently of the fix, not a maintenance note.', 10, 1),
  ('mission-vec-time-is-a-requirement-04-o2-c1', 'solution', 'e1: the door''s safety timeout is an independent countdown that forces FAULT if no confirmed seal arrives before it expires.', 20, 2),

  ('mission-vec-time-is-a-requirement-05-o1-c1', 'orientation', 'Nothing can reach SEALED without first passing through the state where obstacles get checked.', 10, 1),
  ('mission-vec-time-is-a-requirement-05-o1-c1', 'solution', 'OPEN, then CLOSING, then SEALED -- the only path a normal, successful seal follows.', 20, 2),
  ('mission-vec-time-is-a-requirement-05-o2-c1', 'orientation', 'Ask whether the model even defines a direct OPEN-to-SEALED transition anywhere.', 10, 1),
  ('mission-vec-time-is-a-requirement-05-o2-c1', 'solution', 'No -- only a completed CLOSING pass can lead to SEALED; skipping it is not a transition the machine allows.', 20, 2),

  ('mission-vec-time-is-a-requirement-06-o1-c1', 'orientation', 'Ask who decides when a cooperative task stops running: the task itself, or something else.', 10, 1),
  ('mission-vec-time-is-a-requirement-06-o1-c1', 'solution', 'A cooperative task only gives up the processor when it voluntarily yields or finishes -- the scheduler cannot force it aside.', 20, 2),
  ('mission-vec-time-is-a-requirement-06-o2-c1', 'orientation', 'Think about what happens to every task waiting behind one that never lets go.', 10, 1),
  ('mission-vec-time-is-a-requirement-06-o2-c1', 'solution', 'Every other task behind it is blocked too, since nothing can force the stuck task aside.', 20, 2),

  ('mission-vec-time-is-a-requirement-07-o1-c1', 'orientation', 'Ask which scheduler can act without the running task''s cooperation.', 10, 1),
  ('mission-vec-time-is-a-requirement-07-o1-c1', 'solution', 'Preemptive scheduling can forcibly suspend a running task for a higher-priority one; cooperative scheduling can only wait for a task to yield.', 20, 2),
  ('mission-vec-time-is-a-requirement-07-o2-c1', 'orientation', 'Think about what hardware guarantee applies to an ISR once it starts.', 10, 1),
  ('mission-vec-time-is-a-requirement-07-o2-c1', 'solution', 'Effectively nothing on this hardware -- an ISR runs to completion once started, which is exactly why it must never run long or block.', 20, 2),

  ('mission-vec-time-is-a-requirement-08-o1-c1', 'orientation', 'Focus on what kind of data or hardware is being touched, not the length of the code.', 10, 1),
  ('mission-vec-time-is-a-requirement-08-o1-c1', 'solution', 'A critical section is any stretch of code touching shared data or hardware that must not be interrupted partway through without risking corruption.', 20, 2),
  ('mission-vec-time-is-a-requirement-08-o2-c1', 'orientation', 'Think about how many other tasks an ISR''s block affects, compared to an ordinary function''s block.', 10, 1),
  ('mission-vec-time-is-a-requirement-08-o2-c1', 'solution', 'An ISR is already a critical section nothing else can interrupt, so a block inside it stalls the entire processor, not just one task.', 20, 2),

  ('mission-vec-time-is-a-requirement-09-o1-c1', 'orientation', 'Ask whether anything else in the system could ever observe the operation half-finished.', 10, 1),
  ('mission-vec-time-is-a-requirement-09-o1-c1', 'solution', 'An atomic operation completes as a single indivisible step that nothing can observe half-finished or interrupt partway through.', 20, 2),
  ('mission-vec-time-is-a-requirement-09-o2-c1', 'orientation', 'Look for the evidence describing multiple steps stretched over time, not a calibration note.', 10, 1),
  ('mission-vec-time-is-a-requirement-09-o2-c1', 'solution', 'e1: the sensor needs a request, a wait for conversion, then a ready-flag poll -- a multi-step exchange, not a single register access.', 20, 2),

  ('mission-vec-time-is-a-requirement-10-o1-c1', 'orientation', 'The definition needs three roles at once: a high-priority task, a low-priority task holding something, and a medium-priority task cutting in.', 10, 1),
  ('mission-vec-time-is-a-requirement-10-o1-c1', 'solution', 'Priority inversion is a high-priority task blocked on a resource held by a low-priority task, while an unrelated medium-priority task keeps preempting and delaying the low-priority task.', 20, 2),
  ('mission-vec-time-is-a-requirement-10-o2-c1', 'orientation', 'Check whether a lock and a medium-priority task are actually present in the door fix''s bug.', 10, 1),
  ('mission-vec-time-is-a-requirement-10-o2-c1', 'solution', 'No -- there is no lower-priority task holding a needed resource and no medium-priority task cutting in line; this is a blocking-inside-an-ISR problem, related but distinct.', 20, 2),

  ('mission-vec-time-is-a-requirement-11-o1-c1', 'orientation', 'Think about what gets added to "is this the right answer" once time enters the question.', 10, 1),
  ('mission-vec-time-is-a-requirement-11-o1-c1', 'solution', 'Real-time thinking judges correctness by whether code computes the right answer inside the deadline the physical world imposes, not only by what it computes.', 20, 2),
  ('mission-vec-time-is-a-requirement-11-o2-c1', 'orientation', 'Ask which single number determines whether a hard deadline actually gets missed.', 10, 1),
  ('mission-vec-time-is-a-requirement-11-o2-c1', 'solution', 'Worst-case response time -- the rare, slowest occurrence is the one that actually determines whether a hard deadline gets missed.', 20, 2),

  ('mission-vec-time-is-a-requirement-12-o1-c1', 'orientation', 'Look for the one operation inside the ISR that was never a quick, single-step flag check.', 10, 1),
  ('mission-vec-time-is-a-requirement-12-o1-c1', 'solution', 'The block happened at the sensor read on the slow bus -- a non-atomic operation placed inside a context nothing else can preempt.', 20, 2),
  ('mission-vec-time-is-a-requirement-12-o2-c1', 'orientation', 'Compare the block duration against the door''s own timeout window, not against the average run.', 10, 1),
  ('mission-vec-time-is-a-requirement-12-o2-c1', 'solution', 'r2: a 289 millisecond block inside a 300 millisecond deadline window left almost no margin -- that is the overlap.', 20, 2),
  ('mission-vec-time-is-a-requirement-12-o3-c1', 'orientation', 'Ask whether the wrong thing was computed, or whether the right thing simply arrived too late.', 10, 1),
  ('mission-vec-time-is-a-requirement-12-o3-c1', 'solution', 'It is a timing bug -- the fix always computed the correct decision, but a blocking, non-atomic sensor read inside an interrupt context occasionally consumed almost the entire deadline before that correct decision could be delivered.', 20, 2),
  ('mission-vec-time-is-a-requirement-12-o4-c1', 'orientation', 'Combine all three findings into one mandate about what the interrupt handler is never allowed to do again.', 15, 1),
  ('mission-vec-time-is-a-requirement-12-o4-c1', 'solution', 'The interrupt handler must never call anything that can block, a slow sensor read has no place inside it, and a fix that only works on the bench cannot be trusted on a live system until Vector Division can finally speak the maintenance bus''s own language, not just read it.', 25, 2);
