-- Robotics/Embedded/IoT pathway ("Vector Division") Act 19 -- "Kinematics"
-- content, under world-vec-kinematics (already inserted separately, Arc IV,
-- index 18). 1 campaign, 2 operations, 12 missions (11 lessons + boss),
-- following the same campaigns -> operations -> missions -> dialogue ->
-- objectives -> challenges -> hints pattern as every prior Act. No new
-- ChallengeType needed -- reuses story_dialogue, multiple_choice,
-- drag_and_drop, investigation, interactive_diagram, browser_simulation
-- (generic console fallback) and boss_encounter. Dr. Lin Ortega continues
-- as the dominant teaching voice (established in Act 18); Commander Imani
-- Rao frames the incident; Byte assists with computation only. Act 18
-- closed on: knowing where a joint is is not the same as knowing how to
-- command it to a new position -- that takes kinematics. Act 19 opens
-- exactly there: Vector Division commands the newly-located arm to a
-- maintenance position, and it correctly refuses. The boss mission proves
-- why: the target lies outside the arm's real, joint-limited reachable
-- workspace, a limit the original planning software never modeled because
-- it assumed idealized, unlimited joints. Not a singularity -- a genuinely
-- unreachable target. Closes on the next problem: a robot that also has to
-- navigate a floor while it moves.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-kinematics', 'world-vec-kinematics', 'kinematics', '4A - Kinematics', 'Learn how a robot arm''s links and joints translate into commanded motion -- forward and inverse kinematics, the Jacobian, singularities, joint limits, trajectory points, interpolation, velocity constraints and motion profiles -- while Vector Division tries to command the newly-located warehouse arm to a maintenance position it flatly, correctly refuses to reach.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-kinematics-1', 'campaign-vec-kinematics', 'the-refusal', 'The Refusal', 'Links and joints, revolute versus prismatic joints, forward kinematics practice, inverse kinematics intuition, Jacobian intuition, and singularities.', 1),
  ('operation-vec-kinematics-2', 'campaign-vec-kinematics', 'the-unreachable-target', 'The Unreachable Target', 'Joint limits, trajectory points, interpolation, velocity constraints, motion profiles, and the boss diagnosis itself.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-kinematics-01', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'links-and-joints', 'Links and Joints', 'With the warehouse arm''s true position finally known, Vector Division tries to command it to a specific maintenance position. The arm refuses, and at first nobody can explain why. Dr. Lin Ortega starts where she always starts -- not with the failure, but with what the arm is actually made of.', 'beginner', ARRAY['imani','lin','byte'], null, null, '{"type":"simulation","simulationId":"links-and-joints-sim"}'::jsonb, '{"xp":260,"credits":25}'::jsonb, false, 1),
  ('mission-vec-kinematics-02', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'revolute-prismatic-joints', 'Revolute and Prismatic Joints', 'Not every joint moves the same way. Some rotate, some slide -- and the arm''s refusal only makes sense once each of its joints is classified correctly.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-kinematics-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"revolute-prismatic-joints-sim"}'::jsonb, '{"xp":260,"credits":30}'::jsonb, false, 2),
  ('mission-vec-kinematics-03', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'forward-kinematics-practice', 'Forward Kinematics Practice', 'Given every joint angle, the arm''s tip position is not a mystery -- it is a calculation. Forward kinematics turns known joint values into a known point in space.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-kinematics-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"forward-kinematics-practice-sim"}'::jsonb, '{"xp":270,"credits":30}'::jsonb, false, 3),
  ('mission-vec-kinematics-04', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'inverse-kinematics-intuition', 'Inverse Kinematics Intuition', 'The maintenance position is a target point, not a set of joint angles. Getting from the point back to the angles is the exact opposite problem -- and it does not always have an answer.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-kinematics-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"inverse-kinematics-intuition-sim"}'::jsonb, '{"xp":270,"credits":35}'::jsonb, false, 4),
  ('mission-vec-kinematics-05', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'jacobian-intuition', 'Jacobian Intuition', 'A small nudge on one joint does not move the arm''s tip by the same small amount in every direction. The Jacobian is simply the map from joint motion to tip motion, at a given pose.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-kinematics-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"jacobian-intuition-sim"}'::jsonb, '{"xp":280,"credits":35}'::jsonb, false, 5),
  ('mission-vec-kinematics-06', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-1', 'singularities', 'Singularities', 'At certain poses, the arm loses the ability to move its tip in some direction no matter which joints turn. That is a singularity -- and it is a completely different failure than simply being out of reach.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-kinematics-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"singularities-sim"}'::jsonb, '{"xp":280,"credits":35}'::jsonb, false, 6),
  ('mission-vec-kinematics-07', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'joint-limits', 'Joint Limits', 'The arm''s original planning software assumed every joint could rotate freely, without limit. The hardware bolted to the floor was never built that way.', 'beginner', ARRAY['lin','imani'], '{"requiredMissionIds":["mission-vec-kinematics-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"joint-limits-sim"}'::jsonb, '{"xp":290,"credits":40}'::jsonb, false, 7),
  ('mission-vec-kinematics-08', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'trajectory-points', 'Trajectory Points', 'A single target position is not a motion plan. Getting there safely means choosing a sequence of intermediate points the arm will actually pass through.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-kinematics-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"trajectory-points-sim"}'::jsonb, '{"xp":290,"credits":40}'::jsonb, false, 8),
  ('mission-vec-kinematics-09', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'interpolation', 'Interpolation', 'Between one trajectory point and the next, the arm still has to move somehow. Interpolation decides exactly what path it takes to fill that gap.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-kinematics-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"interpolation-sim"}'::jsonb, '{"xp":300,"credits":40}'::jsonb, false, 9),
  ('mission-vec-kinematics-10', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'velocity-constraints', 'Velocity Constraints', 'Every joint has a maximum safe speed. A path that is geometrically valid can still be physically impossible to execute in the time allotted.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-kinematics-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"velocity-constraints-sim"}'::jsonb, '{"xp":300,"credits":45}'::jsonb, false, 10),
  ('mission-vec-kinematics-11', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'motion-profiles', 'Motion Profiles', 'A joint should not snap instantly to full speed. A motion profile shapes how it accelerates, cruises and decelerates, so the arm arrives smoothly instead of violently.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-kinematics-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"motion-profiles-sim"}'::jsonb, '{"xp":310,"credits":45}'::jsonb, false, 11),
  ('mission-vec-kinematics-12', 'world-vec-kinematics', 'campaign-vec-kinematics', 'operation-vec-kinematics-2', 'the-unreachable-target', 'The Unreachable Target', 'Everything this Act taught, turned on one refusal: why the arm was right to refuse the maintenance position, and why that was never a malfunction at all.', 'boss', ARRAY['imani','lin','byte'], '{"requiredMissionIds":["mission-vec-kinematics-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"unreachable-target-boss-sim"}'::jsonb, '{"xp":1400,"credits":290,"badgeIds":["the-unreachable-target"],"skillXp":{"robotics_fundamentals":185}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-kinematics-01', 1, 'imani', 'The arm''s position is no longer a mystery. We know exactly where every joint sits, in the correct frame, right now. So Vector Division tried the obvious next step -- command it to a known maintenance position.'),
  ('mission-vec-kinematics-01', 2, 'byte', 'And it refused. Not an error, not a crash. The planning software rejected the command outright, and none of us can say why yet.'),
  ('mission-vec-kinematics-01', 3, 'lin', 'Dr. Lin Ortega. Knowing where a joint is right now is not the same as knowing how to command it to a new position. That takes kinematics -- and before we can explain a refusal, we need to agree on what the arm is actually built from.'),
  ('mission-vec-kinematics-01', 4, 'lin', 'A robot arm is a chain of rigid links, connected end to end by joints. A link does not bend and does not stretch -- it is simply a solid segment with a fixed length. All the motion in the entire arm lives in the joints, not the links.'),
  ('mission-vec-kinematics-01', 5, 'lin', 'That distinction sounds almost too simple to matter. It is the entire foundation of everything we are about to do, because it means every possible pose of the arm can be described completely by a short list of joint values.'),
  ('mission-vec-kinematics-01', 6, 'byte', 'So the refusal is not the arm being broken. It is the arm''s planning software telling us something about that short list of values that we have not understood yet.'),

  ('mission-vec-kinematics-02', 1, 'lin', 'Joints come in two basic types, and this arm uses both. A revolute joint rotates -- it has an angle, measured in degrees or radians, and that angle is its one degree of freedom.'),
  ('mission-vec-kinematics-02', 2, 'lin', 'A prismatic joint slides -- it has a linear extension, measured in a distance, and that distance is its one degree of freedom. No rotation involved at all, just a straight-line offset.'),
  ('mission-vec-kinematics-02', 3, 'lin', 'This arm is five revolute joints and one prismatic joint at the base, which extends the whole arm outward before any rotation happens. Mislabel even one joint''s type and every downstream calculation about it is wrong from the start.'),

  ('mission-vec-kinematics-03', 1, 'lin', 'Forward kinematics is the easy direction. Give me every joint''s current value -- five angles and one extension -- and I can calculate exactly where the tip of the arm sits in space. It is pure geometry, chained link by link from the base outward.'),
  ('mission-vec-kinematics-03', 2, 'byte', 'Which is exactly how we found the arm''s true position in the first place, once we had the real coordinate frame. Feed in the joint values, walk the chain, and the tip position falls out the other end.'),
  ('mission-vec-kinematics-03', 3, 'lin', 'Correct. And notice what forward kinematics never has to ask: whether those joint values are even reachable. It only describes where the tip goes if the arm holds exactly those values. It says nothing about whether it can get there.'),

  ('mission-vec-kinematics-04', 1, 'lin', 'Inverse kinematics is the direction we actually need for the maintenance position. We do not have joint values -- we have a target point in space, and we need the joint values that put the tip there.'),
  ('mission-vec-kinematics-04', 2, 'lin', 'That is a fundamentally harder problem. Forward kinematics always has exactly one answer for a given set of joint values. Inverse kinematics for a given point can have one answer, several answers, or none at all.'),
  ('mission-vec-kinematics-04', 3, 'byte', 'None at all. That is the sentence I keep circling back to. If the maintenance target has zero valid joint-angle solutions, the planning software was not malfunctioning when it refused. It was reporting exactly that.'),

  ('mission-vec-kinematics-05', 1, 'lin', 'Before we can prove there is no solution, we need one more tool. The Jacobian describes how a small change in each joint value translates into a small change in the tip''s position and orientation, at whatever pose the arm currently holds.'),
  ('mission-vec-kinematics-05', 2, 'lin', 'It is not one fixed ratio. Nudge a joint near the base and the tip can sweep a wide arc. Nudge the same joint with the arm fully extended and that same small nudge moves the tip much farther. The Jacobian changes with the pose.'),
  ('mission-vec-kinematics-05', 3, 'byte', 'So the Jacobian is really a map of how responsive the tip is to each joint, right now. Useful for planning small moves. Less obviously useful for judging whether a distant target is reachable at all.'),

  ('mission-vec-kinematics-06', 1, 'lin', 'It is still useful there, because of what happens when the Jacobian breaks down. At certain poses, some direction of tip motion becomes completely unavailable, no matter how any joint moves. That pose is a singularity.'),
  ('mission-vec-kinematics-06', 2, 'lin', 'A fully extended arm reaching straight out is the classic example. At that exact pose, the arm cannot move its tip any farther outward along that same line, no matter which joint you command -- it has run out of directions to add motion in.'),
  ('mission-vec-kinematics-06', 3, 'byte', 'That sounds a lot like what happened with the maintenance position. Is that our answer -- the arm hit a singularity?'),
  ('mission-vec-kinematics-06', 4, 'lin', 'Do not assume it yet. A singularity is a specific, testable failure -- it means the target is exactly at the edge of what full extension can reach along one direction, with real solutions everywhere just short of it. An unreachable target because of joint limits looks completely different, and we have not tested for either one yet.'),

  ('mission-vec-kinematics-07', 1, 'lin', 'Here is the piece the original planning software never modeled. Every real joint has hard limits -- a minimum and maximum angle it can physically reach, set by the motor, the gearbox, or the housing itself.'),
  ('mission-vec-kinematics-07', 2, 'imani', 'And this arm was bolted to the floor and wired into that maintenance bay years before that planning software was ever installed. Nobody re-derived its limits when the software went in -- it assumed idealized, unlimited joints because that assumption was easier to write, not because it was true.'),
  ('mission-vec-kinematics-07', 3, 'lin', 'Which means the set of points the arm can actually reach -- its real reachable workspace -- is smaller than the software''s model believes it is. Every joint limit shrinks that workspace a little more.'),

  ('mission-vec-kinematics-08', 1, 'lin', 'Reachability aside, moving safely is never one giant leap from current pose to target pose. A trajectory is broken into a sequence of intermediate joint-value points the arm passes through in order, each one individually reachable.'),
  ('mission-vec-kinematics-08', 2, 'lin', 'Choosing those points well keeps the arm away from obstacles, away from singularities, and inside its joint limits at every single step -- not just at the very end.'),

  ('mission-vec-kinematics-09', 1, 'lin', 'Between one trajectory point and the next, the arm still needs a defined path, not a mystery. Interpolation is the rule for filling that gap -- linear interpolation moves each joint at a constant rate between the two points, arriving at both at the same time.'),
  ('mission-vec-kinematics-09', 2, 'byte', 'Other interpolation methods curve the path instead of holding it straight, trading a longer route for smoother motion. But the core idea is the same either way -- a defined, calculable path between two known points, not an undefined jump.'),

  ('mission-vec-kinematics-10', 1, 'lin', 'A path can be geometrically perfect and still be impossible to execute. Every joint has a maximum velocity -- a fastest safe rate of change -- set by its motor and gearbox, the same way it has a position limit.'),
  ('mission-vec-kinematics-10', 2, 'lin', 'Demand a joint travel farther than its maximum velocity allows in the time given, and the plan is invalid before the arm ever moves, regardless of whether every individual point along the way was reachable.'),

  ('mission-vec-kinematics-11', 1, 'lin', 'And even within velocity limits, a joint should never simply snap from zero speed to full speed. A motion profile shapes velocity over time -- accelerate smoothly, cruise at a steady rate, decelerate smoothly into the stop.'),
  ('mission-vec-kinematics-11', 2, 'lin', 'Skip the profile and you get a jolt at the start and a jolt at the stop -- both are exactly the kind of load that wears out gearboxes and strips the precision this arm needs for maintenance work.'),

  ('mission-vec-kinematics-12', 1, 'imani', 'Every concept this Act taught is sitting inside one refusal. Not why the software failed -- why the arm was right. Prove it, in order, the way Dr. Ortega taught you.'),
  ('mission-vec-kinematics-12', 2, 'lin', 'Three things, and they are not interchangeable. First: given the arm''s real joint limits, what is its actual reachable workspace. Second: does the maintenance target fall inside or outside that workspace. Third: rule out the other explanation before you accept this one.'),
  ('mission-vec-kinematics-12', 3, 'byte', 'The other explanation being a singularity. I raised it back at Mission 6 and you told me not to assume it yet. Now we actually have to prove it is not that.'),
  ('mission-vec-kinematics-12', 4, 'lin', 'Correct. A singularity means real solutions exist right up to the edge of a pose, then vanish in one specific direction at that exact pose. An unreachable target means no valid joint-angle solution exists anywhere near it at all. Different evidence, different diagnosis.'),
  ('mission-vec-kinematics-12', 5, 'imani', 'Walk all three. Workspace, target, and the ruled-out alternative. Then tell me plainly why that arm was never malfunctioning.'),
  ('mission-vec-kinematics-12', 6, 'lin', 'One arm''s geometry is already this much work sitting bolted to a floor. A robot that also has to navigate an entire floor while it moves is the next real problem, and it will not wait for us to finish admiring this one.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-kinematics-01-o1', 'mission-vec-kinematics-01', 1, 'Tell links from joints', 'Choose the accurate description of what a link is and what a joint is.'),
  ('mission-vec-kinematics-01-o2', 'mission-vec-kinematics-01', 2, 'Locate the arm''s degrees of freedom', 'Find the evidence identifying how many joint values fully describe the arm''s pose.'),

  ('mission-vec-kinematics-02-o1', 'mission-vec-kinematics-02', 1, 'Sort the joint types', 'Sort each joint description into revolute or prismatic.'),
  ('mission-vec-kinematics-02-o2', 'mission-vec-kinematics-02', 2, 'Classify the base joint', 'Judge which joint type the arm''s base extension actually is.'),

  ('mission-vec-kinematics-03-o1', 'mission-vec-kinematics-03', 1, 'Define forward kinematics', 'Choose the accurate description of what forward kinematics computes.'),
  ('mission-vec-kinematics-03-o2', 'mission-vec-kinematics-03', 2, 'Know its limits', 'Judge what forward kinematics never has to determine about a set of joint values.'),

  ('mission-vec-kinematics-04-o1', 'mission-vec-kinematics-04', 1, 'Define inverse kinematics', 'Choose the accurate description of what inverse kinematics solves for.'),
  ('mission-vec-kinematics-04-o2', 'mission-vec-kinematics-04', 2, 'Count the possible outcomes', 'Judge how many valid joint-angle solutions an inverse kinematics problem can have.'),

  ('mission-vec-kinematics-05-o1', 'mission-vec-kinematics-05', 1, 'Define the Jacobian', 'Choose the accurate description of what the Jacobian maps.'),
  ('mission-vec-kinematics-05-o2', 'mission-vec-kinematics-05', 2, 'Judge its pose dependence', 'Decide whether the same joint nudge always produces the same tip motion regardless of pose.'),

  ('mission-vec-kinematics-06-o1', 'mission-vec-kinematics-06', 1, 'Define a singularity', 'Choose the accurate description of what happens to the arm at a singular pose.'),
  ('mission-vec-kinematics-06-o2', 'mission-vec-kinematics-06', 2, 'Spot the classic case', 'Find the evidence identifying the textbook example of a singular pose.'),

  ('mission-vec-kinematics-07-o1', 'mission-vec-kinematics-07', 1, 'Explain joint limits', 'Choose the accurate description of what a joint limit is and where it comes from.'),
  ('mission-vec-kinematics-07-o2', 'mission-vec-kinematics-07', 2, 'Find the planning software''s flaw', 'Find the evidence proving the original planning software never modeled the arm''s real joint limits.'),

  ('mission-vec-kinematics-08-o1', 'mission-vec-kinematics-08', 1, 'Define a trajectory point', 'Choose the accurate description of why a motion plan needs intermediate points.'),
  ('mission-vec-kinematics-08-o2', 'mission-vec-kinematics-08', 2, 'Judge a bad trajectory', 'Judge why a trajectory that is only reachable at its final point is unsafe.'),

  ('mission-vec-kinematics-09-o1', 'mission-vec-kinematics-09', 1, 'Define interpolation', 'Choose the accurate description of what interpolation provides between two trajectory points.'),

  ('mission-vec-kinematics-10-o1', 'mission-vec-kinematics-10', 1, 'Define a velocity constraint', 'Choose the accurate description of what a joint velocity limit restricts.'),
  ('mission-vec-kinematics-10-o2', 'mission-vec-kinematics-10', 2, 'Judge an impossible plan', 'Judge whether a geometrically valid path can still be physically impossible to execute.'),

  ('mission-vec-kinematics-11-o1', 'mission-vec-kinematics-11', 1, 'Define a motion profile', 'Choose the accurate description of what a motion profile shapes over time.'),
  ('mission-vec-kinematics-11-o2', 'mission-vec-kinematics-11', 2, 'Judge the consequence of skipping it', 'Judge what happens to a joint that snaps directly to full speed with no profile.'),

  ('mission-vec-kinematics-12-o1', 'mission-vec-kinematics-12', 1, 'Compute the reachable workspace', 'Given the arm''s real joint limits, judge which target points fall inside its actual reachable workspace.'),
  ('mission-vec-kinematics-12-o2', 'mission-vec-kinematics-12', 2, 'Prove the target is unreachable', 'Find the evidence proving the maintenance target has no valid joint-angle solution under the real joint limits.'),
  ('mission-vec-kinematics-12-o3', 'mission-vec-kinematics-12', 3, 'Rule out a singularity', 'Judge whether the maintenance target''s failure pattern matches a singularity or an out-of-workspace target.'),
  ('mission-vec-kinematics-12-o4', 'mission-vec-kinematics-12', 4, 'State the diagnosis', 'Having computed the workspace, proven the target unreachable and ruled out a singularity, state why the arm was right to refuse.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-kinematics-01-o1-c1', 'mission-vec-kinematics-01-o1', 1, 'multiple_choice', 'What is the accurate distinction between a link and a joint?', '{"question":"What is the accurate distinction between a link and a joint?","options":[{"id":"a","text":"A link is a rigid, fixed-length segment; a joint is where motion actually happens between two links"},{"id":"b","text":"Links and joints are two names for the same part of the arm"},{"id":"c","text":"A joint is rigid and fixed-length; a link is where motion happens"},{"id":"d","text":"Links carry all the arm''s motion, joints are purely structural"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-kinematics-01-o2-c1', 'mission-vec-kinematics-01-o2', 1, 'investigation', 'Which piece of evidence identifies how many joint values fully describe the arm''s pose?', '{"evidence":[{"id":"e1","label":"Facilities note","detail":"The arm is bolted to a fixed mounting plate in the maintenance bay"},{"id":"e2","label":"Mechanical survey","detail":"The arm has exactly six joints along its chain, each with one independent value -- five rotation angles and one linear extension"},{"id":"e3","label":"Paint log","detail":"The arm''s housing was last repainted eight years ago"}],"question":"Which piece of evidence identifies how many joint values fully describe the arm''s pose?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-vec-kinematics-02-o1-c1', 'mission-vec-kinematics-02-o1', 1, 'drag_and_drop', 'Sort each joint description into revolute or prismatic.', '{"items":[{"id":"j1","text":"A joint whose one degree of freedom is a rotation angle"},{"id":"j2","text":"A joint whose one degree of freedom is a linear sliding distance"},{"id":"j3","text":"An elbow-style joint that swings between two limit angles"},{"id":"j4","text":"A joint that extends a segment outward along a straight rail, with no rotation"}],"targets":[{"id":"revolute","label":"Revolute"},{"id":"prismatic","label":"Prismatic"}]}'::jsonb, '{"correctMapping":{"j1":"revolute","j2":"prismatic","j3":"revolute","j4":"prismatic"}}'::jsonb),
  ('mission-vec-kinematics-02-o2-c1', 'mission-vec-kinematics-02-o2', 1, 'multiple_choice', 'The arm''s base joint extends the entire arm outward along a straight rail before any rotation happens, with no angle involved. What type of joint is it?', '{"question":"The arm''s base joint extends the entire arm outward along a straight rail before any rotation happens, with no angle involved. What type of joint is it?","options":[{"id":"a","text":"Revolute, because it is the first joint in the chain"},{"id":"b","text":"Prismatic, because its one degree of freedom is a linear distance, not an angle"},{"id":"c","text":"Neither, base joints are always fixed"},{"id":"d","text":"Both at once, since it moves the whole arm"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-03-o1-c1', 'mission-vec-kinematics-03-o1', 1, 'multiple_choice', 'Forward kinematics computes...', '{"question":"Forward kinematics computes...","options":[{"id":"a","text":"The joint values needed to reach a given target point"},{"id":"b","text":"The tip position and orientation that results from a given, known set of joint values"},{"id":"c","text":"The maximum safe speed for each joint"},{"id":"d","text":"Whether a given target point is reachable at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-03-o2-c1', 'mission-vec-kinematics-03-o2', 1, 'multiple_choice', 'Given a specific set of joint values, what does forward kinematics never have to determine?', '{"question":"Given a specific set of joint values, what does forward kinematics never have to determine?","options":[{"id":"a","text":"The resulting tip position in space"},{"id":"b","text":"Whether those joint values are actually reachable by the real hardware -- it assumes they are already held and simply describes where the tip ends up"},{"id":"c","text":"The chain of links between the base and the tip"},{"id":"d","text":"The order the links connect in"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-04-o1-c1', 'mission-vec-kinematics-04-o1', 1, 'multiple_choice', 'Inverse kinematics solves for...', '{"question":"Inverse kinematics solves for...","options":[{"id":"a","text":"The tip position resulting from known joint values"},{"id":"b","text":"The joint values that place the tip at a given target position"},{"id":"c","text":"The maximum velocity of each joint"},{"id":"d","text":"The physical length of each link"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-04-o2-c1', 'mission-vec-kinematics-04-o2', 1, 'multiple_choice', 'For a given target point, how many valid joint-angle solutions can inverse kinematics have?', '{"question":"For a given target point, how many valid joint-angle solutions can inverse kinematics have?","options":[{"id":"a","text":"Always exactly one, the same as forward kinematics"},{"id":"b","text":"One, several, or none at all, depending on the target and the arm''s geometry"},{"id":"c","text":"Always infinite"},{"id":"d","text":"Always zero unless the target is the arm''s current position"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-05-o1-c1', 'mission-vec-kinematics-05-o1', 1, 'multiple_choice', 'The Jacobian maps...', '{"question":"The Jacobian maps...","options":[{"id":"a","text":"Joint limits to link lengths"},{"id":"b","text":"Small changes in joint values to the resulting small changes in tip position and orientation, at a given pose"},{"id":"c","text":"Target points directly to joint values, solving inverse kinematics outright"},{"id":"d","text":"Motor voltage to joint velocity"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-05-o2-c1', 'mission-vec-kinematics-05-o2', 1, 'multiple_choice', 'Does the same small nudge to one joint always move the tip by the same amount, regardless of the arm''s current pose?', '{"question":"Does the same small nudge to one joint always move the tip by the same amount, regardless of the arm''s current pose?","options":[{"id":"a","text":"Yes, joint-to-tip motion is a fixed ratio"},{"id":"b","text":"No -- the Jacobian changes with pose, so the same nudge can sweep a wide arc near the base or a much larger distance when the arm is extended"},{"id":"c","text":"Yes, but only for revolute joints"},{"id":"d","text":"No, because link lengths change during motion"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-06-o1-c1', 'mission-vec-kinematics-06-o1', 1, 'multiple_choice', 'At a singular pose, the arm...', '{"question":"At a singular pose, the arm...","options":[{"id":"a","text":"Cannot move at all, in any direction"},{"id":"b","text":"Loses the ability to move its tip in at least one specific direction, no matter which joints are commanded, while other directions may still work fine"},{"id":"c","text":"Exceeds its joint limits automatically"},{"id":"d","text":"Is simply out of the planning software''s range"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-06-o2-c1', 'mission-vec-kinematics-06-o2', 1, 'investigation', 'Which evidence identifies the textbook example of a singular pose?', '{"evidence":[{"id":"e1","label":"Kinematics note","detail":"With the arm fully extended in a straight line, it cannot move its tip any farther outward along that same line, regardless of which joint is commanded"},{"id":"e2","label":"Facilities note","detail":"The arm''s base is bolted to a reinforced steel plate"},{"id":"e3","label":"Power log","detail":"The arm draws peak current during its fastest moves"}],"question":"Which evidence identifies the textbook example of a singular pose?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-kinematics-07-o1-c1', 'mission-vec-kinematics-07-o1', 1, 'multiple_choice', 'A joint limit is...', '{"question":"A joint limit is...","options":[{"id":"a","text":"A software setting that can always be safely overridden"},{"id":"b","text":"The physical minimum and maximum value a joint can actually reach, set by its motor, gearbox or housing -- a hardware fact, not a software choice"},{"id":"c","text":"The same thing as a singularity"},{"id":"d","text":"Only relevant to prismatic joints, never revolute ones"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-07-o2-c1', 'mission-vec-kinematics-07-o2', 1, 'investigation', 'Which evidence proves the original planning software never modeled the arm''s real joint limits?', '{"evidence":[{"id":"e1","label":"Software design note","detail":"The planning software''s joint model assumes unlimited rotation and extension on every axis, with no minimum or maximum values configured anywhere"},{"id":"e2","label":"Installation record","detail":"The arm was bolted into the maintenance bay years before the planning software was installed"},{"id":"e3","label":"Paint log","detail":"The arm''s housing was last repainted eight years ago"}],"question":"Which evidence proves the original planning software never modeled the arm''s real joint limits?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-vec-kinematics-08-o1-c1', 'mission-vec-kinematics-08-o1', 1, 'multiple_choice', 'Why does a safe motion plan need intermediate trajectory points instead of one direct jump to the target?', '{"question":"Why does a safe motion plan need intermediate trajectory points instead of one direct jump to the target?","options":[{"id":"a","text":"It does not, a single jump is always safest"},{"id":"b","text":"Each intermediate point can be checked individually for reachability, obstacles and joint limits, rather than trusting that everything in between the start and end is automatically safe"},{"id":"c","text":"Trajectory points only exist to slow the arm down"},{"id":"d","text":"Intermediate points are purely a display feature with no effect on real motion"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-08-o2-c1', 'mission-vec-kinematics-08-o2', 1, 'multiple_choice', 'A trajectory is only verified reachable at its final point, not at any point in between. Why is that unsafe?', '{"question":"A trajectory is only verified reachable at its final point, not at any point in between. Why is that unsafe?","options":[{"id":"a","text":"It is not unsafe, only the final point matters"},{"id":"b","text":"The path between the start and the final point could pass through an unreachable configuration, a singularity, or a joint limit violation that was never checked"},{"id":"c","text":"Final-point-only checks are always faster and equally safe"},{"id":"d","text":"Unsafe only if the arm is moving backward"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-09-o1-c1', 'mission-vec-kinematics-09-o1', 1, 'multiple_choice', 'Interpolation between two trajectory points provides...', '{"question":"Interpolation between two trajectory points provides...","options":[{"id":"a","text":"A random path between the two points"},{"id":"b","text":"A defined, calculable path filling the gap between two known points, rather than leaving the motion between them undefined"},{"id":"c","text":"A way to skip one of the two points entirely"},{"id":"d","text":"A method for computing joint limits"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-10-o1-c1', 'mission-vec-kinematics-10-o1', 1, 'multiple_choice', 'A joint velocity constraint restricts...', '{"question":"A joint velocity constraint restricts...","options":[{"id":"a","text":"The joint''s minimum and maximum position"},{"id":"b","text":"The fastest safe rate of change for that joint, set by its motor and gearbox"},{"id":"c","text":"Only how the arm accelerates, never its top speed"},{"id":"d","text":"The arm''s total reachable workspace"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-10-o2-c1', 'mission-vec-kinematics-10-o2', 1, 'multiple_choice', 'Can a path that is geometrically valid at every point still be physically impossible to execute?', '{"question":"Can a path that is geometrically valid at every point still be physically impossible to execute?","options":[{"id":"a","text":"No, geometric validity guarantees the plan can always be executed"},{"id":"b","text":"Yes -- if the plan demands a joint travel farther than its maximum velocity allows in the time given, it is invalid regardless of geometric reachability"},{"id":"c","text":"No, velocity is never a factor once positions are all reachable"},{"id":"d","text":"Only for prismatic joints"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-11-o1-c1', 'mission-vec-kinematics-11-o1', 1, 'multiple_choice', 'A motion profile shapes...', '{"question":"A motion profile shapes...","options":[{"id":"a","text":"The final target position only"},{"id":"b","text":"How a joint''s velocity changes over time -- accelerating smoothly, cruising, then decelerating into the stop, rather than snapping instantly to speed"},{"id":"c","text":"The number of joints in the chain"},{"id":"d","text":"The arm''s reachable workspace"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-11-o2-c1', 'mission-vec-kinematics-11-o2', 1, 'multiple_choice', 'What happens to a joint that snaps directly from zero speed to full speed with no motion profile?', '{"question":"What happens to a joint that snaps directly from zero speed to full speed with no motion profile?","options":[{"id":"a","text":"Nothing, instant speed changes are harmless to hardware"},{"id":"b","text":"It takes a jolt of load at the start and again at the stop, exactly the kind of stress that wears out gearboxes and degrades precision"},{"id":"c","text":"It automatically becomes a singularity"},{"id":"d","text":"It exceeds its position limit"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-kinematics-12-o1-c1', 'mission-vec-kinematics-12-o1', 1, 'investigation', 'Given the arm''s real joint limits, which piece of evidence establishes its actual reachable workspace?', '{"evidence":[{"id":"e1","label":"Mechanical survey","detail":"With every joint held at its real physical limits, forward kinematics computes the outer boundary of points the tip can ever reach -- a workspace smaller than a full sphere around the base"},{"id":"e2","label":"Software design note","detail":"The planning software''s model assumes unlimited rotation and extension, producing a workspace far larger than the real hardware permits"},{"id":"e3","label":"Paint log","detail":"The arm''s housing was last repainted eight years ago"}],"question":"Which evidence establishes the arm''s actual reachable workspace, using its real joint limits rather than the software''s idealized assumption?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-kinematics-12-o2-c1', 'mission-vec-kinematics-12-o2', 1, 'browser_simulation', 'Given this inverse-kinematics solver output for the maintenance target, does a valid joint-angle solution exist?', '{"screen":"KINEMATICS SOLVER -- MAINTENANCE TARGET -- SOLUTION SEARCH","question":"Given this inverse-kinematics solver output for the maintenance target, does a valid joint-angle solution exist?","records":[{"id":"r1","code":"SOLVE_ATTEMPT_1","detail":"Nearest candidate solution requires joint 4 at 172 degrees, exceeding its physical limit of 150 degrees"},{"id":"r2","code":"NO_SOLUTION","detail":"Every candidate solution within the search space requires at least one joint value beyond its real physical limit -- the target lies outside the arm''s reachable workspace entirely, not merely difficult to reach"},{"id":"r3","code":"SOLVE_ATTEMPT_2","detail":"Alternate elbow-up configuration also requires joint 4 beyond its physical limit"},{"id":"r4","code":"JACOBIAN_RANK_FULL","detail":"Jacobian rank remains full throughout the search, ruling out a singularity as the cause"}]}'::jsonb, '{"correctOptionId":"r2"}'::jsonb),
  ('mission-vec-kinematics-12-o3-c1', 'mission-vec-kinematics-12-o3', 1, 'multiple_choice', 'The solver reports no candidate solution exists anywhere in the search space, and the Jacobian stays full rank throughout -- it never drops. What does that pattern rule out?', '{"question":"The solver reports no candidate solution exists anywhere in the search space, and the Jacobian stays full rank throughout -- it never drops. What does that pattern rule out?","options":[{"id":"a","text":"It rules out joint limits as a factor entirely"},{"id":"b","text":"It rules out a singularity -- a singularity would show real solutions right up to one specific pose before vanishing in a single direction, not a total absence of solutions with a full-rank Jacobian throughout"},{"id":"c","text":"It proves the arm''s hardware is malfunctioning"},{"id":"d","text":"It proves the target is actually reachable"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-kinematics-12-o4-c1', 'mission-vec-kinematics-12-o4', 1, 'boss_encounter', 'Having computed the real reachable workspace, proven the target has no valid solution, and ruled out a singularity, state why the arm was right to refuse.', '{"stages":[{"objectiveRef":"mission-vec-kinematics-12-o1","label":"Compute the reachable workspace"},{"objectiveRef":"mission-vec-kinematics-12-o2","label":"Prove the target is unreachable"},{"objectiveRef":"mission-vec-kinematics-12-o3","label":"Rule out a singularity"}],"task":"State the diagnosis in one sentence: the requested maintenance position lies outside the arm''s actual reachable workspace once its real joint limits are accounted for, because the original planning software assumed idealized, unlimited joints that were never physically true of the hardware bolted to the floor -- the refusal was correct, not a malfunction."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-kinematics-12-o1","mission-vec-kinematics-12-o2","mission-vec-kinematics-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-kinematics-01-o1-c1', 'orientation', 'Ask which part physically stays the same shape, and which part is where all the motion actually happens.', 10, 1),
  ('mission-vec-kinematics-01-o1-c1', 'solution', 'A link is a rigid, fixed-length segment; a joint is where motion between two links actually occurs.', 20, 2),
  ('mission-vec-kinematics-01-o2-c1', 'orientation', 'Look for a survey describing the chain of joints, not the mounting or appearance.', 10, 1),
  ('mission-vec-kinematics-01-o2-c1', 'solution', 'e2: six joints, each with one independent value -- five angles and one linear extension -- fully describe the arm''s pose.', 20, 2),

  ('mission-vec-kinematics-02-o1-c1', 'orientation', 'Ask whether the one degree of freedom is an angle or a straight-line distance.', 10, 1),
  ('mission-vec-kinematics-02-o1-c1', 'solution', 'Revolute: the rotation-angle joint and the swinging elbow joint (j1, j3). Prismatic: the sliding-distance joint and the straight-rail extension (j2, j4).', 20, 2),
  ('mission-vec-kinematics-02-o2-c1', 'orientation', 'Check whether the joint''s motion is measured in degrees or in distance.', 10, 1),
  ('mission-vec-kinematics-02-o2-c1', 'solution', 'Prismatic -- its degree of freedom is a linear extension, with no angle involved at all.', 20, 2),

  ('mission-vec-kinematics-03-o1-c1', 'orientation', 'Forward kinematics starts from what you already know about the joints.', 10, 1),
  ('mission-vec-kinematics-03-o1-c1', 'solution', 'It computes the tip position and orientation that results from a known, given set of joint values.', 20, 2),
  ('mission-vec-kinematics-03-o2-c1', 'orientation', 'It assumes the joint values are already held -- ask what it never has to check about that assumption.', 10, 1),
  ('mission-vec-kinematics-03-o2-c1', 'solution', 'It never has to determine whether those joint values are actually reachable by the real hardware -- it just describes where the tip ends up if they are held.', 20, 2),

  ('mission-vec-kinematics-04-o1-c1', 'orientation', 'Inverse kinematics starts from the opposite piece of information as forward kinematics.', 10, 1),
  ('mission-vec-kinematics-04-o1-c1', 'solution', 'It solves for the joint values that place the tip at a given target position.', 20, 2),
  ('mission-vec-kinematics-04-o2-c1', 'orientation', 'Think about whether a single target point could be reached more than one way, or not at all.', 10, 1),
  ('mission-vec-kinematics-04-o2-c1', 'solution', 'One, several, or none at all -- the count depends entirely on the target and the arm''s geometry.', 20, 2),

  ('mission-vec-kinematics-05-o1-c1', 'orientation', 'The Jacobian connects small joint changes to small tip changes, not target points to joint values directly.', 10, 1),
  ('mission-vec-kinematics-05-o1-c1', 'solution', 'It maps small changes in joint values to the resulting small changes in tip position and orientation, at the current pose.', 20, 2),
  ('mission-vec-kinematics-05-o2-c1', 'orientation', 'Compare a small nudge near the base to the same nudge with the arm fully extended.', 10, 1),
  ('mission-vec-kinematics-05-o2-c1', 'solution', 'No -- the Jacobian changes with pose, so the same nudge can sweep very different tip distances depending on how the arm is currently posed.', 20, 2),

  ('mission-vec-kinematics-06-o1-c1', 'orientation', 'A singularity is not total paralysis -- it is a loss of motion in a specific direction.', 10, 1),
  ('mission-vec-kinematics-06-o1-c1', 'solution', 'At a singular pose the tip loses the ability to move in at least one specific direction, no matter which joints move, while other directions can remain fine.', 20, 2),
  ('mission-vec-kinematics-06-o2-c1', 'orientation', 'Think about what happens when the arm is stretched out as far as it can physically go.', 10, 1),
  ('mission-vec-kinematics-06-o2-c1', 'solution', 'e1: a fully extended arm cannot move its tip any farther outward along that same line -- the classic singular pose.', 20, 2),

  ('mission-vec-kinematics-07-o1-c1', 'orientation', 'A joint limit comes from the physical hardware, not from a configuration file someone could freely change.', 10, 1),
  ('mission-vec-kinematics-07-o1-c1', 'solution', 'It is the physical minimum and maximum value a joint can actually reach, fixed by its motor, gearbox or housing.', 20, 2),
  ('mission-vec-kinematics-07-o2-c1', 'orientation', 'Look for a note about what the software''s joint model actually assumes, not about installation dates.', 10, 1),
  ('mission-vec-kinematics-07-o2-c1', 'solution', 'e1: the software''s joint model assumes unlimited rotation and extension, with no minimum or maximum configured anywhere.', 20, 2),

  ('mission-vec-kinematics-08-o1-c1', 'orientation', 'Ask what could go wrong strictly between the start and the end of a single giant leap.', 10, 1),
  ('mission-vec-kinematics-08-o1-c1', 'solution', 'Intermediate points let each step be individually checked for reachability, obstacles and joint limits, instead of trusting the whole path in between is automatically safe.', 20, 2),
  ('mission-vec-kinematics-08-o2-c1', 'orientation', 'Reachable at the end does not guarantee reachable everywhere along the way there.', 10, 1),
  ('mission-vec-kinematics-08-o2-c1', 'solution', 'The path in between could pass through an unreachable configuration, a singularity, or a joint limit violation that final-point-only checking would never catch.', 20, 2),

  ('mission-vec-kinematics-09-o1-c1', 'orientation', 'Interpolation exists specifically to avoid leaving the motion between two known points undefined.', 10, 1),
  ('mission-vec-kinematics-09-o1-c1', 'solution', 'It provides a defined, calculable path filling the gap between two known trajectory points.', 20, 2),

  ('mission-vec-kinematics-10-o1-c1', 'orientation', 'A velocity constraint is about speed of change, not about position.', 10, 1),
  ('mission-vec-kinematics-10-o1-c1', 'solution', 'It restricts the fastest safe rate of change for a joint, set by its motor and gearbox.', 20, 2),
  ('mission-vec-kinematics-10-o2-c1', 'orientation', 'Geometric validity says the points are reachable. It says nothing about how fast the arm must move between them.', 10, 1),
  ('mission-vec-kinematics-10-o2-c1', 'solution', 'Yes -- demanding a joint travel farther than its maximum velocity allows in the time given makes the plan invalid regardless of geometric reachability.', 20, 2),

  ('mission-vec-kinematics-11-o1-c1', 'orientation', 'A motion profile is about the shape of speed over time, not about the target itself.', 10, 1),
  ('mission-vec-kinematics-11-o1-c1', 'solution', 'It shapes how a joint''s velocity changes over time -- smooth acceleration, a cruise, then smooth deceleration into the stop.', 20, 2),
  ('mission-vec-kinematics-11-o2-c1', 'orientation', 'Think about what an instant speed change does to gears and precision, not to position limits.', 10, 1),
  ('mission-vec-kinematics-11-o2-c1', 'solution', 'It takes a jolt of load at the start and the stop -- exactly the stress that wears out gearboxes and degrades precision over time.', 20, 2),

  ('mission-vec-kinematics-12-o1-c1', 'orientation', 'Use the real physical limits, not the software''s idealized assumption, to define the boundary.', 10, 1),
  ('mission-vec-kinematics-12-o1-c1', 'solution', 'e1: forward kinematics at the real joint limits computes the true outer boundary of the workspace, smaller than the software''s idealized model.', 20, 2),
  ('mission-vec-kinematics-12-o2-c1', 'orientation', 'Look for the record where the solver reports the search exhausted, not an individual attempt.', 10, 1),
  ('mission-vec-kinematics-12-o2-c1', 'solution', 'r2: NO_SOLUTION -- every candidate requires a joint beyond its real physical limit, meaning the target lies entirely outside the reachable workspace.', 20, 2),
  ('mission-vec-kinematics-12-o3-c1', 'orientation', 'A singularity would show the Jacobian losing rank at one pose. Check whether that happened here.', 10, 1),
  ('mission-vec-kinematics-12-o3-c1', 'solution', 'The Jacobian staying full rank throughout, combined with zero solutions anywhere in the search, rules out a singularity -- this is a genuinely out-of-workspace target instead.', 20, 2),
  ('mission-vec-kinematics-12-o4-c1', 'orientation', 'Combine the three findings into one sentence: the real workspace, the missing solution, and the ruled-out alternative.', 15, 1),
  ('mission-vec-kinematics-12-o4-c1', 'solution', 'The maintenance position lies outside the arm''s actual reachable workspace once its real joint limits are accounted for -- the planning software assumed idealized, unlimited joints that were never physically true of the hardware. The refusal was correct, not a malfunction.', 25, 2);
