-- AI/ML pathway ("Cipher Division") Act 28 -- "Embeddings & Vector Search" content.
-- Opens Arc VI ("Knowledge & Agents", Acts 28-33). Elena Rook leads, with
-- Noah Kim taking over the production-infra half of the Operation: dense
-- embeddings, the query-versus-document embedding distinction, similarity
-- metrics, chunking, chunk size, overlap, semantic boundaries, metadata,
-- vector stores, retrievers, and top-k/filters -- built into a real,
-- production-grade vector index over Cipher Division's own investigation
-- archive (every log, finding and piece of evidence since Act 1), closing
-- on a genuine retrieval failure traced to a chunk boundary that split the
-- one fact a query needed, and pointing forward to RAG.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other pathway. World/act/pathway
-- rows already exist (world-ai-embeddings-vector-search, act-ai-6) and are
-- not touched, nor is dialogue_lines_character_id_check.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-embeddings-vector-search', 'world-ai-embeddings-vector-search', 'embeddings-vector-search', '28A - Embeddings & Vector Search', 'Turn Cipher Division''s entire investigation archive -- every log, every finding, every piece of evidence gathered since Act 1 -- into dense embeddings, real chunks, and a production vector index the assistant can actually search.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-embeddings-vector-search-1', 'campaign-ai-embeddings-vector-search', 'chunk-and-embed', 'Chunk and Embed', 'Dense embeddings, the query-versus-document distinction, similarity metrics, and every real decision behind splitting an archive into chunks worth searching.', 1),
  ('operation-ai-embeddings-vector-search-2', 'campaign-ai-embeddings-vector-search', 'index-and-retrieve', 'Index and Retrieve', 'Semantic boundaries, metadata, vector stores, retrievers, and top-k and filters -- assembled into an index Cipher Division can actually trust, tested against a document that never should have gone missing.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-embeddings-vector-search-01', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'dense-embeddings', 'Dense Embeddings', 'The assistant Cipher Division just hardened still knows nothing beyond its training. The fix starts with turning the entire investigation archive into vectors it can actually search.', 'beginner', ARRAY['maya','elena'], null, null, '{"type":"simulation","simulationId":"dense-embeddings-sim"}'::jsonb, '{"xp":590,"credits":155}'::jsonb, false, 1),
  ('mission-ai-embeddings-vector-search-02', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'query-vs-document-embeddings', 'Query vs Document Embeddings', 'A search question and the archive record that answers it are not quite the same kind of text -- and some embedding models know it.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-vs-document-embeddings-sim"}'::jsonb, '{"xp":600,"credits":155}'::jsonb, false, 2),
  ('mission-ai-embeddings-vector-search-03', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'similarity-metrics', 'Similarity Metrics', 'Cosine similarity is not the only way to measure how close two embeddings are, and the alternatives do not always agree.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"similarity-metrics-sim"}'::jsonb, '{"xp":600,"credits":160}'::jsonb, false, 3),
  ('mission-ai-embeddings-vector-search-04', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'chunking', 'Chunking', 'One embedding for an entire report says everything and nothing. The archive gets split before it gets searched.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"chunking-sim"}'::jsonb, '{"xp":610,"credits":160}'::jsonb, false, 4),
  ('mission-ai-embeddings-vector-search-05', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'chunk-size', 'Chunk Size', 'Too small loses context. Too large drowns the one detail a query actually needed. Cipher Division just watched both happen.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"chunk-size-sim"}'::jsonb, '{"xp":610,"credits":160}'::jsonb, false, 5),
  ('mission-ai-embeddings-vector-search-06', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-1', 'overlap', 'Overlap', 'Wherever a chunk boundary lands, something in the source document sits on top of it. Overlap decides whether that something survives the cut.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"overlap-sim"}'::jsonb, '{"xp":620,"credits":165}'::jsonb, false, 6),
  ('mission-ai-embeddings-vector-search-07', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'semantic-boundaries', 'Semantic Boundaries', 'A chunker that counts characters does not know what it is cutting. One that reads structure does.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"semantic-boundaries-sim"}'::jsonb, '{"xp":620,"credits":165}'::jsonb, false, 7),
  ('mission-ai-embeddings-vector-search-08', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'metadata', 'Metadata', 'An embedding says what a chunk means. Metadata says where it came from -- and lets a search rule out most of the archive before similarity is even computed.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"metadata-sim"}'::jsonb, '{"xp":630,"credits":165}'::jsonb, false, 8),
  ('mission-ai-embeddings-vector-search-09', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'vector-stores', 'Vector Stores', 'Every technique this Operation built has to land somewhere real. Noah is building the system that actually holds it.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"vector-stores-sim"}'::jsonb, '{"xp":630,"credits":170}'::jsonb, false, 9),
  ('mission-ai-embeddings-vector-search-10', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'retrievers', 'Retrievers', 'The assistant does not know what a vector is, and it should not have to. The retriever is what stands between a plain question and the right chunk.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"retrievers-sim"}'::jsonb, '{"xp":640,"credits":170}'::jsonb, false, 10),
  ('mission-ai-embeddings-vector-search-11', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'top-k-filters', 'Top-k/Filters', 'How many results come back, and from how much of the archive, turns out to matter as much as the search itself.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"top-k-filters-sim"}'::jsonb, '{"xp":640,"credits":170}'::jsonb, false, 11),
  ('mission-ai-embeddings-vector-search-12', 'world-ai-embeddings-vector-search', 'campaign-ai-embeddings-vector-search', 'operation-ai-embeddings-vector-search-2', 'the-missing-document', 'The Missing Document', 'A real record sits in the archive the whole time, and the retriever never finds it. Cipher Division has to work out why before it can trust the index at all.', 'boss', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-embeddings-vector-search-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"missing-document-boss-sim"}'::jsonb, '{"xp":1400,"credits":300,"badgeIds":["the-missing-document"],"skillXp":{"vector_search":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-embeddings-vector-search-01', 1, 'maya', 'Act 27 gave Cipher Division an assistant that finally holds together under real failure conditions. It is reliable. It is also completely blind to anything outside its training -- every fact about Echo gathered since Act 1 is invisible to it unless someone puts it in front of the model by hand.'),
  ('mission-ai-embeddings-vector-search-01', 2, 'elena', 'Dr. Elena Rook. So Cipher Division stops asking the model to remember and starts building something that can actually look things up. Every log, every finding, every piece of evidence gathered since Act 1, turned into an index the assistant can search.'),
  ('mission-ai-embeddings-vector-search-01', 3, 'maya', 'That means solving the same problem this Arc keeps circling back to: turning meaning into something comparable. Dense embeddings, similarity, chunking -- the whole retrieval pipeline, built for real this time, at the scale of an actual archive instead of one night of messages.'),
  ('mission-ai-embeddings-vector-search-01', 4, 'elena', 'First piece is the same piece Arc IV started with: dense embeddings. Not a sparse count of which words appear -- a compact, learned vector where every one of a few hundred or a few thousand numbers carries part of the meaning.'),

  ('mission-ai-embeddings-vector-search-02', 1, 'elena', 'Every piece of text going into this index gets embedded twice in effect: once as a document sitting in the archive, and separately, every time someone searches, as a query. Some embedding models treat those two roles differently on purpose.'),
  ('mission-ai-embeddings-vector-search-02', 2, 'byte', 'A short question and a long report are not really the same kind of text, even when they are about the same fact. A query is asking. A document is telling. Models trained for retrieval often learn separate query and document behavior instead of pretending both are identical.'),
  ('mission-ai-embeddings-vector-search-02', 3, 'elena', 'Get this wrong -- embed a query as if it were a document, or the reverse -- and even a genuine match can end up farther apart in the space than it should be. Small detail. It breaks retrieval quietly, not loudly.'),

  ('mission-ai-embeddings-vector-search-03', 1, 'elena', 'Cosine similarity is not the only way to compare two embeddings. Dot product and Euclidean distance both show up across real retrieval systems, and they do not always agree with each other.'),
  ('mission-ai-embeddings-vector-search-03', 2, 'elena', 'Dot product measures direction and magnitude together -- useful when a model was trained so longer or more confident vectors should score higher. Euclidean distance measures straight-line distance in the space -- sensitive to scale in a way cosine similarity is built to ignore.'),
  ('mission-ai-embeddings-vector-search-03', 3, 'elena', 'None of them is universally correct. The right metric depends on how the embedding model itself was trained. Pick the wrong one and two genuinely similar chunks can score as distant.'),

  ('mission-ai-embeddings-vector-search-04', 1, 'elena', 'A single embedding vector can only carry so much. Feed it an entire forty-page incident report and the result is one point that vaguely represents everything in the report and precisely represents nothing in it.'),
  ('mission-ai-embeddings-vector-search-04', 2, 'elena', 'Chunking splits a document into smaller pieces first, each one embedded separately. A query about one specific detail can then match the one chunk that actually contains it, instead of competing against an average of the whole document.'),
  ('mission-ai-embeddings-vector-search-04', 3, 'elena', 'Not everything needs it. A two-line evidence tag is already small enough to stand as its own chunk. The archive Cipher Division is indexing is full of both kinds.'),

  ('mission-ai-embeddings-vector-search-05', 1, 'elena', 'Chunk size is a tradeoff, not a solved default. Chunks too small lose surrounding context -- a name with nothing around it to explain who they are. Chunks too large dilute the embedding -- one specific fact drowned inside several paragraphs of unrelated detail.'),
  ('mission-ai-embeddings-vector-search-05', 2, 'byte', 'A chunk mixing three different topics gets an embedding that vaguely represents all three and precisely represents none. A query about just one of those topics has to compete against that dilution.'),
  ('mission-ai-embeddings-vector-search-05', 3, 'elena', 'Cipher Division has already run a live test on this. The result is not encouraging.'),

  ('mission-ai-embeddings-vector-search-06', 1, 'elena', 'Chunk boundaries are drawn somewhere, and wherever they land, something in the source document sits right on top of one. Overlap means each chunk shares a slice of text with its neighbor instead of ending exactly where the next one begins.'),
  ('mission-ai-embeddings-vector-search-06', 2, 'elena', 'Without it, a single fact that happens to straddle a cut point can end up split in half, present in neither chunk''s embedding in any recognizable way. With enough overlap, that same fact appears whole in at least one chunk.'),
  ('mission-ai-embeddings-vector-search-06', 3, 'elena', 'It costs storage and compute -- every overlapping slice gets embedded twice. Cipher Division is about to find out exactly what skipping it can cost instead.'),

  ('mission-ai-embeddings-vector-search-07', 1, 'elena', 'Fixed-size chunking counts characters and cuts, with no regard for what is actually being cut. Semantic-boundary chunking looks at the structure of the text instead -- sentence endings, paragraph breaks, section headings -- and cuts there instead.'),
  ('mission-ai-embeddings-vector-search-07', 2, 'elena', 'It does not remove every risk. A single sentence can still carry too much on its own to be split safely. But it removes the laziest failure -- slicing a fact in half in the middle of a word or a clause for no reason beyond a character count.'),
  ('mission-ai-embeddings-vector-search-07', 3, 'elena', 'This is the difference between a chunker that respects what the document is actually saying and one that does not look at the document at all.'),

  ('mission-ai-embeddings-vector-search-08', 1, 'elena', 'Every chunk gets embedded, but the embedding alone throws away useful information: which document it came from, which Act, what kind of record it is, when it was filed. Metadata keeps all of that attached to the chunk, stored alongside the vector.'),
  ('mission-ai-embeddings-vector-search-08', 2, 'elena', 'A query can then be narrowed before similarity even gets computed -- search only logs, only Act one through Act ten, only records tagged evidence instead of dialogue. The embedding finds what is similar. Metadata decides what is even eligible to be compared.'),

  ('mission-ai-embeddings-vector-search-09', 1, 'noah', 'Noah Kim. A vector store is not just a folder of numbers. It is the system that holds every chunk''s embedding and metadata together, and answers a nearest-neighbor query against millions of them without falling over.'),
  ('mission-ai-embeddings-vector-search-09', 2, 'elena', 'Everything this Act has built so far -- dense embeddings, chunking, chunk size, overlap, semantic boundaries, metadata -- all of it feeds into what actually goes into the store.'),
  ('mission-ai-embeddings-vector-search-09', 3, 'noah', 'Get the ingestion order wrong and the store holds garbage. Chunk first, embed the chunks, attach the metadata, then write all three into the store together. Skip a step or run it out of order and nothing downstream can be trusted.'),

  ('mission-ai-embeddings-vector-search-10', 1, 'noah', 'A vector store is the storage. A retriever is the interface in front of it -- the thing the eventual assistant actually calls with a plain question and gets back the right chunks.'),
  ('mission-ai-embeddings-vector-search-10', 2, 'elena', 'It hides everything underneath: embedding the query with the correct query-mode encoder, running the nearest-neighbor search, applying whatever metadata filters apply, and handing back a ranked, readable list instead of raw vectors.'),
  ('mission-ai-embeddings-vector-search-10', 3, 'noah', 'The assistant Cipher Division built in Act 27 does not know what a vector is. It just needs an answer to look things up. The retriever is what makes that possible.'),

  ('mission-ai-embeddings-vector-search-11', 1, 'noah', 'Top-k decides how many chunks the retriever actually hands back. Set it too small and a real answer sitting at rank six never reaches the assistant. Set it too large and the assistant has to wade through noise to find the one chunk that mattered.'),
  ('mission-ai-embeddings-vector-search-11', 2, 'elena', 'Filters and top-k work together. Narrow with metadata first -- the right Act range, the right record type -- and a smaller top-k becomes safe, because almost everything left over is already relevant.'),
  ('mission-ai-embeddings-vector-search-11', 3, 'noah', 'Skip the filters and top-k has to do all the work alone, competing against the entire archive at once.'),

  ('mission-ai-embeddings-vector-search-12', 1, 'maya', 'Index is built. Every log, every finding, every piece of evidence Cipher Division has gathered since Act 1 -- chunked, embedded, stored. Before this becomes the assistant''s memory, we test it against something we already know the answer to.'),
  ('mission-ai-embeddings-vector-search-12', 2, 'elena', 'Query: who accessed Cipher Labs in the six hours before Echo''s unauthorized activation. Report ARC-0091 answers that, filed the same night Byte first logged the anomaly. It has been sitting in the archive since Act 1.'),
  ('mission-ai-embeddings-vector-search-12', 3, 'noah', 'Running the search now. Top five results back -- none of them are ARC-0091. Its chunks barely register against the query at all.'),
  ('mission-ai-embeddings-vector-search-12', 4, 'maya', 'So we rule it out in order. Is the document actually indexed. What is different about its chunks. And whether a fix actually retrieves it, not just explains why it did not.'),
  ('mission-ai-embeddings-vector-search-12', 5, 'elena', 'Confirmed first: ARC-0091 is in the index. Full document, embedded, stored, present in every collection count Noah has pulled.'),
  ('mission-ai-embeddings-vector-search-12', 6, 'noah', 'It is the chunks themselves. ARC-0091 got processed with the same fixed-size splitter as everything else -- cut every few hundred characters, no regard for sentence boundaries, no overlap between windows.'),
  ('mission-ai-embeddings-vector-search-12', 7, 'elena', 'And the one line that answers the query -- the name, the timestamp, the fact that it was a diagnostic push and not an intrusion -- sits exactly on a cut. Half the sentence ends one chunk. The other half opens the next.'),
  ('mission-ai-embeddings-vector-search-12', 8, 'maya', 'So neither chunk actually contains the fact on its own. One holds an unrelated paragraph about badge readers with a stray name attached. The other holds a maintenance ticket number with no name attached at all. Each chunk''s embedding reflects whatever dominates it -- and neither one is the fact we needed.'),
  ('mission-ai-embeddings-vector-search-12', 9, 'noah', 'Re-chunked it with sentence-aware boundaries and overlap, the way this Act keeps insisting on. Re-embedded, re-indexed. Running the same query again.'),
  ('mission-ai-embeddings-vector-search-12', 10, 'elena', 'ARC-0091, rank one now. A real, relevant record sat in the archive the whole time, and the retriever never found it -- not because the document was gone, but because it was chunked and embedded in a way that buried the one detail that made it match.'),
  ('mission-ai-embeddings-vector-search-12', 11, 'maya', 'Finding documents is not the same as answering questions with them. Retrieval is only half the system Cipher Division actually needs.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-embeddings-vector-search-01-o1', 'mission-ai-embeddings-vector-search-01', 1, 'Define dense embeddings', 'Choose the accurate description of what a dense embedding actually is.'),
  ('mission-ai-embeddings-vector-search-01-o2', 'mission-ai-embeddings-vector-search-01', 2, 'Justify the index', 'Find the evidence showing why the archive actually needs a real embedding index instead of keyword search.'),

  ('mission-ai-embeddings-vector-search-02-o1', 'mission-ai-embeddings-vector-search-02', 1, 'Separate the two roles', 'Choose the accurate description of why a search query and an archive document are not always embedded the same way.'),
  ('mission-ai-embeddings-vector-search-02-o2', 'mission-ai-embeddings-vector-search-02', 2, 'Sort by role', 'Sort each piece of text by whether it should be embedded as a search query or as a document to be indexed.'),

  ('mission-ai-embeddings-vector-search-03-o1', 'mission-ai-embeddings-vector-search-03', 1, 'Match metric to meaning', 'Choose the accurate description of what each similarity metric actually measures.'),
  ('mission-ai-embeddings-vector-search-03-o2', 'mission-ai-embeddings-vector-search-03', 2, 'Read the scores', 'Given similarity scores under different metrics, judge which pair is the genuine match.'),

  ('mission-ai-embeddings-vector-search-04-o1', 'mission-ai-embeddings-vector-search-04', 1, 'Explain why chunking matters', 'State why documents get split into chunks before being embedded, instead of embedding each document as one vector.'),
  ('mission-ai-embeddings-vector-search-04-o2', 'mission-ai-embeddings-vector-search-04', 2, 'Decide what needs chunking', 'Sort each archive item by whether it needs to be split into chunks before indexing.'),

  ('mission-ai-embeddings-vector-search-05-o1', 'mission-ai-embeddings-vector-search-05', 1, 'Know the tradeoff', 'State what happens to retrieval when chunk size is set too large or too small.'),
  ('mission-ai-embeddings-vector-search-05-o2', 'mission-ai-embeddings-vector-search-05', 2, 'Read the retrieval test', 'Find the evidence showing chunk size caused a real retrieval failure.'),

  ('mission-ai-embeddings-vector-search-06-o1', 'mission-ai-embeddings-vector-search-06', 1, 'Explain overlap', 'State what overlapping chunk windows are actually for.'),
  ('mission-ai-embeddings-vector-search-06-o2', 'mission-ai-embeddings-vector-search-06', 2, 'Spot the risk of skipping it', 'Find the evidence showing what can happen to a fact that lands on a chunk boundary when there is no overlap.'),

  ('mission-ai-embeddings-vector-search-07-o1', 'mission-ai-embeddings-vector-search-07', 1, 'Define semantic chunking', 'State what it means to chunk at semantic boundaries rather than at a fixed character count.'),
  ('mission-ai-embeddings-vector-search-07-o2', 'mission-ai-embeddings-vector-search-07', 2, 'Judge the boundary choice', 'Sort each chunking approach by whether it respects semantic boundaries or cuts through them.'),

  ('mission-ai-embeddings-vector-search-08-o1', 'mission-ai-embeddings-vector-search-08', 1, 'Define chunk metadata', 'Choose the accurate description of what metadata attached to a chunk is for.'),
  ('mission-ai-embeddings-vector-search-08-o2', 'mission-ai-embeddings-vector-search-08', 2, 'Use metadata to narrow a search', 'Find the evidence showing metadata successfully narrowing a search to the right part of the archive.'),

  ('mission-ai-embeddings-vector-search-09-o1', 'mission-ai-embeddings-vector-search-09', 1, 'Define a vector store', 'Choose the accurate description of what a production vector store actually provides.'),
  ('mission-ai-embeddings-vector-search-09-o2', 'mission-ai-embeddings-vector-search-09', 2, 'Order the ingestion pipeline', 'Put the stages of getting one archive document into the vector store in the order they actually run.'),

  ('mission-ai-embeddings-vector-search-10-o1', 'mission-ai-embeddings-vector-search-10', 1, 'Define a retriever', 'Choose the accurate description of what a retriever actually does, as an abstraction over the vector store.'),
  ('mission-ai-embeddings-vector-search-10-o2', 'mission-ai-embeddings-vector-search-10', 2, 'Order the retriever''s steps', 'Put the steps a retriever runs on an incoming query in the order they actually happen.'),

  ('mission-ai-embeddings-vector-search-11-o1', 'mission-ai-embeddings-vector-search-11', 1, 'Know the top-k tradeoff', 'State what happens when top-k is set too small for a retrieval query.'),
  ('mission-ai-embeddings-vector-search-11-o2', 'mission-ai-embeddings-vector-search-11', 2, 'Combine filters and top-k', 'Sort each retrieval setup by whether it is likely to return focused results or noisy, unfocused ones.'),

  ('mission-ai-embeddings-vector-search-12-o1', 'mission-ai-embeddings-vector-search-12', 1, 'Confirm the record exists', 'Verify Report ARC-0091 genuinely made it into the archive index, rather than being missing entirely.'),
  ('mission-ai-embeddings-vector-search-12-o2', 'mission-ai-embeddings-vector-search-12', 2, 'Diagnose the chunk boundary', 'Find the evidence identifying why ARC-0091''s chunks failed to match the query despite the document being relevant.'),
  ('mission-ai-embeddings-vector-search-12-o3', 'mission-ai-embeddings-vector-search-12', 3, 'Confirm the fix', 'Confirm the re-chunked, re-indexed version of the report actually retrieves for the query now.'),
  ('mission-ai-embeddings-vector-search-12-o4', 'mission-ai-embeddings-vector-search-12', 4, 'Deliver the finding', 'Having confirmed the record exists, diagnosed the chunk boundary, and confirmed the fix, state what actually happened.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-embeddings-vector-search-01-o1-c1', 'mission-ai-embeddings-vector-search-01-o1', 1, 'multiple_choice', 'A dense embedding is best described as...', '{"question":"A dense embedding is best described as...","options":[{"id":"a","text":"A sparse vector with one slot per possible word, mostly zeros"},{"id":"b","text":"A compact vector of continuous numbers, learned so that similar meaning ends up close together in the space"},{"id":"c","text":"The raw text stored byte for byte"},{"id":"d","text":"A random vector reassigned every time the same text is embedded"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-01-o2-c1', 'mission-ai-embeddings-vector-search-01-o2', 1, 'investigation', 'Which evidence actually shows why keyword search over the archive is not enough?', '{"evidence":[{"id":"e1","label":"Search log","detail":"A keyword search across the archive for the phrase unauthorized activation returns zero results, even though at least one report describes Cipher Labs coming online without anyone authorizing it, in different words"},{"id":"e2","label":"Storage note","detail":"The archive currently totals several hundred documents across twenty-seven Acts of investigation"},{"id":"e3","label":"Ops note","detail":"Cipher Labs draws more power at night than during the day"}],"question":"Which evidence actually shows why keyword search over the archive is not enough?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-02-o1-c1', 'mission-ai-embeddings-vector-search-02-o1', 1, 'multiple_choice', 'Why do some embedding models treat query embeddings and document embeddings differently?', '{"question":"Why do some embedding models treat query embeddings and document embeddings differently?","options":[{"id":"a","text":"Because queries and documents are always written in different languages"},{"id":"b","text":"Because a short question and the passage that answers it play different roles, so a model trained for retrieval often represents them differently even though both are just text"},{"id":"c","text":"Because document embeddings never actually get compared to anything"},{"id":"d","text":"There is no real difference, this distinction does not affect retrieval at all"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-02-o2-c1', 'mission-ai-embeddings-vector-search-02-o2', 1, 'drag_and_drop', 'Sort each piece of text by whether it should be embedded as a search query or as a document to be indexed.', '{"items":[{"id":"i1","text":"What time did Echo first send a message nobody sent"},{"id":"i2","text":"Full incident report describing the six hours before Cipher Labs came online"},{"id":"i3","text":"Did anyone access Cipher Labs before activation"},{"id":"i4","text":"Byte''s complete anomaly log from the night of activation"}],"targets":[{"id":"query","label":"Search query"},{"id":"document","label":"Document to be indexed"}]}'::jsonb, '{"correctMapping":{"i1":"query","i2":"document","i3":"query","i4":"document"}}'::jsonb),

  ('mission-ai-embeddings-vector-search-03-o1-c1', 'mission-ai-embeddings-vector-search-03-o1', 1, 'multiple_choice', 'Which statement correctly matches a similarity metric to what it measures?', '{"question":"Which statement correctly matches a similarity metric to what it measures?","options":[{"id":"a","text":"Cosine similarity measures the angle between two vectors, ignoring their length"},{"id":"b","text":"Euclidean distance measures the angle between two vectors"},{"id":"c","text":"Dot product can only ever return a value between zero and one"},{"id":"d","text":"All three metrics always produce identical rankings"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-embeddings-vector-search-03-o2-c1', 'mission-ai-embeddings-vector-search-03-o2', 1, 'investigation', 'Which pair is the genuine semantic match, once vector magnitude stops being allowed to distort the comparison?', '{"evidence":[{"id":"e1","label":"Metric comparison, Pair A","detail":"Cosine similarity 0.89, dot product 41.2, Euclidean distance 3.1 -- consistently ranked as the closest pair across all three metrics"},{"id":"e2","label":"Metric comparison, Pair B","detail":"Cosine similarity 0.20, dot product 55.0, Euclidean distance 9.4 -- high dot product driven mostly by one vector having a much larger magnitude"},{"id":"e3","label":"Metric comparison, Pair C","detail":"Cosine similarity 0.15, dot product 2.1, Euclidean distance 8.9"}],"question":"Which pair is the genuine semantic match, once vector magnitude stops being allowed to distort the comparison?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-04-o1-c1', 'mission-ai-embeddings-vector-search-04-o1', 1, 'multiple_choice', 'Why split a long document into chunks before embedding it, instead of embedding the whole document as one vector?', '{"question":"Why split a long document into chunks before embedding it, instead of embedding the whole document as one vector?","options":[{"id":"a","text":"Chunking makes documents load faster on screen"},{"id":"b","text":"One embedding for an entire long document blends everything it contains into a single vague point, making it hard for a query about one specific detail to match"},{"id":"c","text":"Embedding models cannot process more than one sentence at a time under any circumstance"},{"id":"d","text":"Chunking is only needed for images, never for text"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-04-o2-c1', 'mission-ai-embeddings-vector-search-04-o2', 1, 'drag_and_drop', 'Sort each archive item by whether it needs to be split into chunks before indexing.', '{"items":[{"id":"i1","text":"A forty-page incident report covering an entire night of activity"},{"id":"i2","text":"A single evidence tag: Report ARC-0091, filed Act 1"},{"id":"i3","text":"A full transcript of every dialogue line from an entire Act"},{"id":"i4","text":"A one-sentence log entry: Cooling systems nominal at 02:00"}],"targets":[{"id":"needs-chunking","label":"Needs chunking"},{"id":"single-chunk-fine","label":"Fine as a single chunk"}]}'::jsonb, '{"correctMapping":{"i1":"needs-chunking","i2":"single-chunk-fine","i3":"needs-chunking","i4":"single-chunk-fine"}}'::jsonb),

  ('mission-ai-embeddings-vector-search-05-o1-c1', 'mission-ai-embeddings-vector-search-05-o1', 1, 'multiple_choice', 'What happens when a chunk is set far too large, mixing several unrelated topics together?', '{"question":"What happens when a chunk is set far too large, mixing several unrelated topics together?","options":[{"id":"a","text":"Nothing changes, chunk size has no effect on embeddings"},{"id":"b","text":"The chunk''s embedding ends up as a vague average across every topic in it, making it harder for a query about just one of those topics to match strongly"},{"id":"c","text":"The chunk becomes impossible to embed at all"},{"id":"d","text":"Larger chunks always retrieve better, with no downside"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-05-o2-c1', 'mission-ai-embeddings-vector-search-05-o2', 1, 'investigation', 'Which evidence shows chunk size itself is what caused the drop in retrieval quality?', '{"evidence":[{"id":"e1","label":"Retrieval test, large chunk","detail":"A 2000-word chunk covering three separate incidents scores only 0.31 cosine similarity against a query naming one specific detail from the middle incident"},{"id":"e2","label":"Retrieval test, focused chunk","detail":"The same detail, re-embedded alone as its own roughly 200-word chunk, scores 0.86 cosine similarity against the identical query"},{"id":"e3","label":"Server log","detail":"The vector store completed the batch embedding job in under four minutes"}],"question":"Which evidence shows chunk size itself is what caused the drop in retrieval quality?"}'::jsonb, '{"requiredEvidenceIds":["e1","e2"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-06-o1-c1', 'mission-ai-embeddings-vector-search-06-o1', 1, 'multiple_choice', 'Overlapping chunk windows exist mainly to...', '{"question":"Overlapping chunk windows exist mainly to...","options":[{"id":"a","text":"Make the archive take up less storage"},{"id":"b","text":"Reduce the chance that a fact sitting near a chunk boundary gets split in half, present whole in neither chunk"},{"id":"c","text":"Make every chunk exactly the same length"},{"id":"d","text":"Remove the need for chunk size decisions entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-06-o2-c1', 'mission-ai-embeddings-vector-search-06-o2', 1, 'investigation', 'Which evidence shows what can happen to a fact without any chunk overlap?', '{"evidence":[{"id":"e1","label":"Boundary test, no overlap","detail":"A sentence naming which engineer ran a diagnostic push is split by a fixed-size chunk boundary with zero overlap -- the name lands in one chunk, the phrase diagnostic push lands in the next, and neither chunk contains the whole fact"},{"id":"e2","label":"Boundary test, with overlap","detail":"The identical sentence, chunked with a hundred-token overlap between windows, appears completely intact inside at least one chunk"},{"id":"e3","label":"Storage note","detail":"Adding overlap increased total stored chunk count by roughly fifteen percent"}],"question":"Which evidence shows what can happen to a fact without any chunk overlap?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-07-o1-c1', 'mission-ai-embeddings-vector-search-07-o1', 1, 'multiple_choice', 'Chunking at semantic boundaries means...', '{"question":"Chunking at semantic boundaries means...","options":[{"id":"a","text":"Splitting text at a fixed number of characters regardless of content"},{"id":"b","text":"Splitting text at natural structural points -- sentence endings, paragraph breaks, section headings -- instead of an arbitrary character count"},{"id":"c","text":"Never splitting a document under any circumstances"},{"id":"d","text":"Splitting text randomly to avoid any predictable pattern"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-07-o2-c1', 'mission-ai-embeddings-vector-search-07-o2', 1, 'drag_and_drop', 'Sort each chunking approach by whether it respects semantic boundaries or cuts through them.', '{"items":[{"id":"i1","text":"Cutting every 500 characters with no regard for sentence endings"},{"id":"i2","text":"Cutting at the end of each paragraph, keeping full sentences intact"},{"id":"i3","text":"Cutting in the middle of a name because the character count ran out"},{"id":"i4","text":"Cutting at section headings that already divide the report into topics"}],"targets":[{"id":"respects-boundaries","label":"Respects semantic boundaries"},{"id":"cuts-through-boundaries","label":"Cuts through boundaries"}]}'::jsonb, '{"correctMapping":{"i1":"cuts-through-boundaries","i2":"respects-boundaries","i3":"cuts-through-boundaries","i4":"respects-boundaries"}}'::jsonb),

  ('mission-ai-embeddings-vector-search-08-o1-c1', 'mission-ai-embeddings-vector-search-08-o1', 1, 'multiple_choice', 'Metadata attached to a chunk is best described as...', '{"question":"Metadata attached to a chunk is best described as...","options":[{"id":"a","text":"A second embedding computed for the same chunk"},{"id":"b","text":"Structured information about the chunk -- source document, Act, record type, timestamp -- stored alongside its embedding so a search can be narrowed by more than similarity alone"},{"id":"c","text":"A compressed copy of the chunk''s text"},{"id":"d","text":"A random tag with no effect on search"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-08-o2-c1', 'mission-ai-embeddings-vector-search-08-o2', 1, 'investigation', 'Which evidence shows metadata filtering actually improving which results come back first?', '{"evidence":[{"id":"e1","label":"Filtered search","detail":"Restricting the query to chunks tagged record type evidence and Act one through Act ten returns three highly relevant results in under a second"},{"id":"e2","label":"Unfiltered search","detail":"The same query across the full unfiltered archive of twenty-seven Acts returns several loosely related dialogue chunks ahead of the actual evidence records"},{"id":"e3","label":"Server note","detail":"The vector store currently holds several hundred thousand chunks total"}],"question":"Which evidence shows metadata filtering actually improving which results come back first?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-09-o1-c1', 'mission-ai-embeddings-vector-search-09-o1', 1, 'multiple_choice', 'A production vector store is best described as...', '{"question":"A production vector store is best described as...","options":[{"id":"a","text":"A plain text file listing every document in the archive"},{"id":"b","text":"A system that stores each chunk''s embedding and metadata together and can answer nearest-neighbor queries against a very large number of them efficiently"},{"id":"c","text":"A cache that only holds the five most recent search results"},{"id":"d","text":"A backup copy of the raw, unchunked archive"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-09-o2-c1', 'mission-ai-embeddings-vector-search-09-o2', 1, 'interactive_diagram', 'Order the stages of getting one archive document into the vector store.', '{"diagramId":"archive-ingestion-pipeline","hotspots":[{"id":"collect","label":"Collect the source document","explanation":"Pull the raw record -- log, finding, or piece of evidence -- from the archive."},{"id":"chunk","label":"Split it into chunks","explanation":"Break the document into smaller pieces at sensible boundaries before anything gets embedded."},{"id":"embed","label":"Embed each chunk","explanation":"Run every chunk through the encoder to produce its dense embedding."},{"id":"tag","label":"Attach metadata","explanation":"Record which document, Act, and record type each chunk came from."},{"id":"store","label":"Write to the vector store","explanation":"Save the embedding and its metadata together so it can be searched later."}],"task":"Order the stages of getting one archive document into the vector store."}'::jsonb, '{"correctOrderIds":["collect","chunk","embed","tag","store"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-10-o1-c1', 'mission-ai-embeddings-vector-search-10-o1', 1, 'multiple_choice', 'A retriever is best described as...', '{"question":"A retriever is best described as...","options":[{"id":"a","text":"The raw storage layer that holds embeddings on disk"},{"id":"b","text":"The interface that takes a plain query, embeds it, searches the vector store, applies any filters, and returns ranked, readable results"},{"id":"c","text":"A separate model that generates new documents from scratch"},{"id":"d","text":"A manual process where a person searches the archive by hand"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-10-o2-c1', 'mission-ai-embeddings-vector-search-10-o2', 1, 'interactive_diagram', 'Order the steps a retriever runs for one incoming query.', '{"diagramId":"retriever-query-pipeline","hotspots":[{"id":"receive","label":"Receive the incoming query","explanation":"The retriever gets a plain question or phrase, not a vector."},{"id":"embed-query","label":"Embed the query","explanation":"The query is embedded using the correct query-mode encoder, matching how the corpus was embedded."},{"id":"search","label":"Search the vector store","explanation":"The query embedding is compared against stored chunk embeddings to find the nearest matches."},{"id":"filter","label":"Apply metadata filters","explanation":"Any requested filters -- Act range, record type -- narrow which chunks are eligible."},{"id":"rank-return","label":"Rank and return results","explanation":"The closest eligible chunks are ranked and handed back as the retrieval result."}],"task":"Order the steps a retriever runs for one incoming query."}'::jsonb, '{"correctOrderIds":["receive","embed-query","search","filter","rank-return"]}'::jsonb),

  ('mission-ai-embeddings-vector-search-11-o1-c1', 'mission-ai-embeddings-vector-search-11-o1', 1, 'multiple_choice', 'What happens if top-k is set too small for a retrieval query?', '{"question":"What happens if top-k is set too small for a retrieval query?","options":[{"id":"a","text":"Nothing, top-k has no real effect on results"},{"id":"b","text":"A genuinely relevant chunk ranked just outside the cutoff never gets returned to the assistant at all"},{"id":"c","text":"The vector store stops working entirely"},{"id":"d","text":"Every chunk in the archive gets returned regardless of the setting"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-embeddings-vector-search-11-o2-c1', 'mission-ai-embeddings-vector-search-11-o2', 1, 'drag_and_drop', 'Sort each retrieval setup by whether it is likely to return focused results or noisy, unfocused ones.', '{"items":[{"id":"i1","text":"Top-k of 3, no metadata filters, searched across the full twenty-seven-Act archive"},{"id":"i2","text":"Top-k of 3, filtered to record type evidence and Act one through Act five"},{"id":"i3","text":"Top-k of 50, no metadata filters, searched across the full archive"},{"id":"i4","text":"Top-k of 5, filtered to the specific Act the query is actually about"}],"targets":[{"id":"focused-relevant","label":"Focused, relevant results"},{"id":"noisy-unfocused","label":"Noisy, unfocused results"}]}'::jsonb, '{"correctMapping":{"i1":"noisy-unfocused","i2":"focused-relevant","i3":"noisy-unfocused","i4":"focused-relevant"}}'::jsonb),

  ('mission-ai-embeddings-vector-search-12-o1-c1', 'mission-ai-embeddings-vector-search-12-o1', 1, 'investigation', 'Before diagnosing anything, is Report ARC-0091 actually present in the vector index?', '{"evidence":[{"id":"e1","label":"Ingestion log","detail":"ARC-0091 was processed in the initial ingestion batch: chunked, embedded, and written to the vector store with all other Act 1 records, confirmed present in the current chunk count"},{"id":"e2","label":"Unrelated ticket","detail":"An open ticket requests a dark mode option for the archive dashboard"},{"id":"e3","label":"Facilities log","detail":"Cipher Labs cooling systems logged normal activity overnight"}],"question":"Before diagnosing anything, is Report ARC-0091 actually present in the vector index?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-embeddings-vector-search-12-o2-c1', 'mission-ai-embeddings-vector-search-12-o2', 1, 'investigation', 'What is actually different about the chunks that came from ARC-0091?', '{"evidence":[{"id":"e1","label":"Chunk boundary diff","detail":"ARC-0091 was split with a fixed-size splitter, five hundred characters per chunk, zero overlap -- the sentence naming which engineer ran a diagnostic push falls exactly across the boundary between two consecutive chunks, split roughly in half"},{"id":"e2","label":"Encoder consistency check","detail":"The query and every chunk in the index, including both halves of the split sentence, were embedded with the identical encoder in the identical mode -- ruling out a mismatch between query and document embeddings"},{"id":"e3","label":"Unrelated metric","detail":"Average chunk embedding time across the whole archive was 40 milliseconds"}],"question":"What is actually different about the chunks that came from ARC-0091?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-embeddings-vector-search-12-o3-c1', 'mission-ai-embeddings-vector-search-12-o3', 1, 'investigation', 'Does a corrected version of ARC-0091 actually retrieve for the same query now?', '{"evidence":[{"id":"e1","label":"Re-index test","detail":"ARC-0091 re-chunked with sentence-aware boundaries and a hundred-token overlap, re-embedded, and re-indexed -- the same query now ranks it first, with cosine similarity of 0.90, well above every other candidate"},{"id":"e2","label":"Unrelated log","detail":"The vector store reported normal memory usage during the re-indexing job"},{"id":"e3","label":"Unrelated ticket","detail":"A separate request asks to increase the dashboard refresh rate"}],"question":"Does a corrected version of ARC-0091 actually retrieve for the same query now?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-embeddings-vector-search-12-o4-c1', 'mission-ai-embeddings-vector-search-12-o4', 1, 'boss_encounter', 'Having confirmed the record exists, diagnosed the chunk boundary, and confirmed the fix, state what actually happened.', '{"stages":[{"objectiveRef":"mission-ai-embeddings-vector-search-12-o1","label":"Confirm the record exists"},{"objectiveRef":"mission-ai-embeddings-vector-search-12-o2","label":"Diagnose the chunk boundary"},{"objectiveRef":"mission-ai-embeddings-vector-search-12-o3","label":"Confirm the fix"}],"task":"State the finding: explain why Report ARC-0091 never surfaced for the query despite being relevant and fully indexed, and confirm the corrected version actually resolves it."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-embeddings-vector-search-12-o1","mission-ai-embeddings-vector-search-12-o2","mission-ai-embeddings-vector-search-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-embeddings-vector-search-01-o1-c1', 'orientation', 'Think about what fills most of the vector -- mostly zeros, or mostly meaningful numbers.', 10, 1),
  ('mission-ai-embeddings-vector-search-01-o1-c1', 'solution', 'A dense embedding is a compact vector of continuous numbers, learned so similar meaning lands close together -- the opposite of a sparse, mostly-zero word-count vector.', 20, 2),
  ('mission-ai-embeddings-vector-search-01-o2-c1', 'orientation', 'Look for a case where the right words did not appear, but the right meaning did.', 10, 1),
  ('mission-ai-embeddings-vector-search-01-o2-c1', 'concept', 'Keyword search only matches literal words. A paraphrase of the same fact, in different words, is invisible to it.', 20, 2),
  ('mission-ai-embeddings-vector-search-01-o2-c1', 'solution', 'e1: a keyword search for the exact phrase misses a report that describes the same event in different words -- proof that literal word matching is not enough for this archive.', 30, 3),

  ('mission-ai-embeddings-vector-search-02-o1-c1', 'orientation', 'Think about what a short question and a long passage are each actually doing.', 10, 1),
  ('mission-ai-embeddings-vector-search-02-o1-c1', 'solution', 'A query asks, a document answers -- different roles, so a model trained for retrieval can learn to represent them differently even though both are just text.', 20, 2),
  ('mission-ai-embeddings-vector-search-02-o2-c1', 'orientation', 'Ask whether each piece of text is asking something or reporting something.', 10, 1),
  ('mission-ai-embeddings-vector-search-02-o2-c1', 'solution', 'Query: the two questions. Document: the incident report and Byte''s anomaly log -- both reporting facts rather than asking.', 20, 2),

  ('mission-ai-embeddings-vector-search-03-o1-c1', 'orientation', 'Angle and straight-line distance are not the same measurement.', 10, 1),
  ('mission-ai-embeddings-vector-search-03-o1-c1', 'solution', 'Cosine similarity measures the angle between two vectors and ignores their length -- the other options describe it incorrectly.', 20, 2),
  ('mission-ai-embeddings-vector-search-03-o2-c1', 'orientation', 'A high dot product can come from a longer vector, not necessarily a closer one.', 10, 1),
  ('mission-ai-embeddings-vector-search-03-o2-c1', 'concept', 'Look for the pair that stays close together across all three metrics, not just the one with the single highest number.', 20, 2),
  ('mission-ai-embeddings-vector-search-03-o2-c1', 'solution', 'Pair A ranks closest under cosine similarity, dot product, and Euclidean distance alike -- Pair B''s high dot product is mostly its vector length, not real closeness.', 30, 3),

  ('mission-ai-embeddings-vector-search-04-o1-c1', 'orientation', 'One vector for an entire long document has to represent everything in it at once.', 10, 1),
  ('mission-ai-embeddings-vector-search-04-o1-c1', 'solution', 'A single embedding for a long document blends every topic in it into one vague point, making it hard for a query about one specific detail to match strongly.', 20, 2),
  ('mission-ai-embeddings-vector-search-04-o2-c1', 'orientation', 'Length is the first thing to check -- can this stand as one coherent chunk already?', 10, 1),
  ('mission-ai-embeddings-vector-search-04-o2-c1', 'solution', 'Needs chunking: the forty-page report and the full Act transcript. Fine as a single chunk: the one-line evidence tag and the one-sentence log entry.', 20, 2),

  ('mission-ai-embeddings-vector-search-05-o1-c1', 'orientation', 'A chunk that covers three topics has to represent all three in the same handful of numbers.', 10, 1),
  ('mission-ai-embeddings-vector-search-05-o1-c1', 'solution', 'Too large a chunk mixes unrelated topics into one vague average embedding, weakening its match to a query about just one of them.', 20, 2),
  ('mission-ai-embeddings-vector-search-05-o2-c1', 'orientation', 'Compare the same fact, embedded two different ways, against the identical query.', 10, 1),
  ('mission-ai-embeddings-vector-search-05-o2-c1', 'concept', 'A much higher similarity score after shrinking the chunk down to just the relevant detail points at chunk size, not the query or the encoder.', 20, 2),
  ('mission-ai-embeddings-vector-search-05-o2-c1', 'solution', 'e1 and e2 together: the same detail scores 0.31 buried in a 2000-word chunk, and 0.86 alone in a focused chunk -- chunk size caused the drop.', 30, 3),

  ('mission-ai-embeddings-vector-search-06-o1-c1', 'orientation', 'A chunk boundary has to be drawn somewhere, and something in the document always sits near it.', 10, 1),
  ('mission-ai-embeddings-vector-search-06-o1-c1', 'solution', 'Overlap lets neighboring chunks share a slice of text, so a fact sitting near a boundary still appears whole in at least one chunk instead of split across two.', 20, 2),
  ('mission-ai-embeddings-vector-search-06-o2-c1', 'orientation', 'Look for the test where a single fact ends up divided between two separate chunks.', 10, 1),
  ('mission-ai-embeddings-vector-search-06-o2-c1', 'solution', 'e1: with zero overlap, a sentence naming who ran a diagnostic push gets split across a chunk boundary, and neither resulting chunk contains the complete fact.', 20, 2),

  ('mission-ai-embeddings-vector-search-07-o1-c1', 'orientation', 'Ask what the chunker is actually looking at when it decides where to cut.', 10, 1),
  ('mission-ai-embeddings-vector-search-07-o1-c1', 'solution', 'Semantic-boundary chunking cuts at sentence endings, paragraph breaks, and headings instead of counting characters blindly.', 20, 2),
  ('mission-ai-embeddings-vector-search-07-o2-c1', 'orientation', 'A boundary that lands mid-sentence or mid-name is not respecting structure.', 10, 1),
  ('mission-ai-embeddings-vector-search-07-o2-c1', 'solution', 'Respects boundaries: cutting at paragraph ends and section headings. Cuts through boundaries: a fixed 500-character cut, and a cut that lands in the middle of a name.', 20, 2),

  ('mission-ai-embeddings-vector-search-08-o1-c1', 'orientation', 'The embedding captures meaning. Something else has to capture where that meaning came from.', 10, 1),
  ('mission-ai-embeddings-vector-search-08-o1-c1', 'solution', 'Metadata is structured information -- source document, Act, record type, timestamp -- stored with the chunk''s embedding so a search can be narrowed by more than similarity alone.', 20, 2),
  ('mission-ai-embeddings-vector-search-08-o2-c1', 'orientation', 'Compare what ranks first with the filter applied against what ranks first without it.', 10, 1),
  ('mission-ai-embeddings-vector-search-08-o2-c1', 'solution', 'e1: filtering to the right record type and Act range returns three highly relevant results almost immediately, instead of competing against the entire unfiltered archive.', 20, 2),

  ('mission-ai-embeddings-vector-search-09-o1-c1', 'orientation', 'Think about what has to be stored together for a nearest-neighbor query to work at all.', 10, 1),
  ('mission-ai-embeddings-vector-search-09-o1-c1', 'solution', 'A vector store holds each chunk''s embedding and metadata together and can answer nearest-neighbor queries against a very large number of them efficiently.', 20, 2),
  ('mission-ai-embeddings-vector-search-09-o2-c1', 'orientation', 'Nothing can be embedded before it exists as a chunk, and nothing can be stored before it has both an embedding and metadata.', 10, 1),
  ('mission-ai-embeddings-vector-search-09-o2-c1', 'concept', 'Metadata gets attached once the chunk and its embedding both already exist, not before.', 20, 2),
  ('mission-ai-embeddings-vector-search-09-o2-c1', 'solution', 'Collect the document, split it into chunks, embed each chunk, attach metadata, write everything to the vector store.', 30, 3),

  ('mission-ai-embeddings-vector-search-10-o1-c1', 'orientation', 'The retriever is not the storage. It is what stands in front of the storage.', 10, 1),
  ('mission-ai-embeddings-vector-search-10-o1-c1', 'solution', 'A retriever takes a plain query, embeds it, searches the vector store, applies filters, and returns ranked, readable results -- the interface, not the storage itself.', 20, 2),
  ('mission-ai-embeddings-vector-search-10-o2-c1', 'orientation', 'The query has to become an embedding before anything can be searched against it.', 10, 1),
  ('mission-ai-embeddings-vector-search-10-o2-c1', 'concept', 'Filters narrow what is eligible only after a search has something to search against.', 20, 2),
  ('mission-ai-embeddings-vector-search-10-o2-c1', 'solution', 'Receive the query, embed the query, search the vector store, apply metadata filters, rank and return results.', 30, 3),

  ('mission-ai-embeddings-vector-search-11-o1-c1', 'orientation', 'Think about what happens to a relevant result that lands just past the cutoff.', 10, 1),
  ('mission-ai-embeddings-vector-search-11-o1-c1', 'solution', 'A chunk ranked just outside a too-small top-k never reaches the assistant at all, even if it was genuinely relevant.', 20, 2),
  ('mission-ai-embeddings-vector-search-11-o2-c1', 'orientation', 'A small top-k is only safe once filters have already ruled out most of the archive.', 10, 1),
  ('mission-ai-embeddings-vector-search-11-o2-c1', 'solution', 'Focused and relevant: filtered searches with a reasonable top-k. Noisy and unfocused: any search with no metadata filters, competing against the full twenty-seven-Act archive regardless of top-k.', 20, 2),

  ('mission-ai-embeddings-vector-search-12-o1-c1', 'orientation', 'Check the index itself before questioning the search.', 10, 1),
  ('mission-ai-embeddings-vector-search-12-o1-c1', 'solution', 'The ingestion log confirms the report is fully embedded, chunked, and present in the store -- it was never missing from the index.', 20, 2),
  ('mission-ai-embeddings-vector-search-12-o2-c1', 'orientation', 'Compare where the chunk boundaries actually fell against where the one distinguishing detail actually sits in the text.', 10, 1),
  ('mission-ai-embeddings-vector-search-12-o2-c1', 'concept', 'Ruling out the encoder matters too -- if query and document used the same embedding mode, the problem is not a mismatch between them.', 20, 2),
  ('mission-ai-embeddings-vector-search-12-o2-c1', 'solution', 'The one sentence naming who ran the diagnostic push was split exactly at a fixed-size chunk boundary with no overlap -- half of it in one chunk, half in the next, so neither chunk''s embedding reflects the complete fact.', 30, 3),
  ('mission-ai-embeddings-vector-search-12-o3-c1', 'orientation', 'Run the identical query again, only after the fix.', 10, 1),
  ('mission-ai-embeddings-vector-search-12-o3-c1', 'solution', 'Re-chunked with sentence-aware boundaries and overlap, then re-embedded and re-indexed, the report now ranks first against the same query with a high similarity score.', 20, 2),
  ('mission-ai-embeddings-vector-search-12-o4-c1', 'orientation', 'State what actually happened, not what almost happened -- the record was always there.', 15, 1),
  ('mission-ai-embeddings-vector-search-12-o4-c1', 'solution', 'The report was never missing from the archive. It was chunked and embedded in a way that split the one fact that mattered across a boundary, so no single chunk''s embedding ever matched the query -- and re-chunking it correctly fixed the retrieval, confirming the diagnosis.', 25, 2);
