-- Robotics/Embedded/IoT pathway ("Vector Division") Act 18 -- "Robot
-- Geometry" content, under world-vec-robot-geometry (already inserted
-- separately, act-vec-4, opening Arc IV). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same pattern as every
-- other Act. This is Dr. Lin Ortega's first Act speaking in the entire
-- pathway -- reserved since Act 1 specifically for this moment.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-vec-robot-geometry', 'world-vec-robot-geometry', 'robot-geometry', '4A - Robot Geometry', 'Learn the vocabulary of where a robot actually is -- coordinate frames, vectors, rotation, translation, transformation matrices, homogeneous coordinates, robot frames, forward kinematics, degrees of freedom and workspace -- while Dr. Lin Ortega resolves a warehouse arm''s position that has never once matched where anyone can find it standing.', 18);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-vec-robot-geometry-1', 'campaign-vec-robot-geometry', 'where-relative-to-what', 'Where, Relative to What', 'Coordinate frames, 2D and 3D vectors, rotation intuition, translation, transformation matrices.', 1),
  ('operation-vec-robot-geometry-2', 'campaign-vec-robot-geometry', 'chaining-the-frames', 'Chaining the Frames', 'Homogeneous coordinates, robot frames, forward kinematics, degrees of freedom and workspace.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-vec-robot-geometry-01', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', 'coordinate-frames', 'Coordinate Frames', 'The fleet audit turns up a warehouse handling arm whose logged position has never once matched where anyone can actually find it standing. Commander Rao brings in someone who can answer where a robot is, precisely: Dr. Lin Ortega.', 'beginner', ARRAY['imani','lin','byte'], null, null, '{"type":"simulation","simulationId":"coordinate-frames-sim"}'::jsonb, '{"xp":250,"credits":25}'::jsonb, false, 1),
  ('mission-vec-robot-geometry-02', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', '2d-vectors', '2D Vectors', 'A vector is not just a number. It is a magnitude and a direction together, and a robot''s position is meaningless without both.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"2d-vectors-sim"}'::jsonb, '{"xp":250,"credits":30}'::jsonb, false, 2),
  ('mission-vec-robot-geometry-03', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', '3d-vectors', '3D Vectors', 'The arm does not just move across a floor. It reaches up, down and out, and nothing about it can be described in only two dimensions.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"3d-vectors-sim"}'::jsonb, '{"xp":260,"credits":30}'::jsonb, false, 3),
  ('mission-vec-robot-geometry-04', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', 'rotation-intuition', 'Rotation Intuition', 'Two arms can occupy the exact same point in space and still be pointed in completely different directions. Position alone never tells the whole story.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"rotation-intuition-sim"}'::jsonb, '{"xp":260,"credits":35}'::jsonb, false, 4),
  ('mission-vec-robot-geometry-05', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', 'translation', 'Translation', 'A translation moves a point without turning it. Combine translation with rotation and you can describe any rigid motion an arm can make.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"translation-sim"}'::jsonb, '{"xp":270,"credits":35}'::jsonb, false, 5),
  ('mission-vec-robot-geometry-06', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-1', 'transformation-matrices', 'Transformation Matrices', 'A transformation matrix packages a rotation and a translation into one operation, so moving a point from one frame to another becomes a single, repeatable calculation.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-robot-geometry-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"transformation-matrices-sim"}'::jsonb, '{"xp":270,"credits":35}'::jsonb, false, 6),
  ('mission-vec-robot-geometry-07', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'homogeneous-coordinates', 'Homogeneous Coordinates', 'An ordinary matrix cannot represent a translation by multiplication alone. Homogeneous coordinates add one extra number that makes it possible -- and makes chaining transforms nothing more than multiplying matrices together.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"homogeneous-coordinates-sim"}'::jsonb, '{"xp":280,"credits":40}'::jsonb, false, 7),
  ('mission-vec-robot-geometry-08', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'robot-frames', 'Robot Frames', 'A real robot is not one frame. It is a chain of them -- base, shoulder, elbow, wrist, gripper -- each one only ever described relative to the frame before it.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"robot-frames-sim"}'::jsonb, '{"xp":280,"credits":40}'::jsonb, false, 8),
  ('mission-vec-robot-geometry-09', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'forward-kinematics', 'Forward Kinematics', 'Forward kinematics answers one exact question: given every joint angle, where does the end of the arm actually end up in the world.', 'beginner', ARRAY['lin','byte'], '{"requiredMissionIds":["mission-vec-robot-geometry-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"forward-kinematics-sim"}'::jsonb, '{"xp":290,"credits":40}'::jsonb, false, 9),
  ('mission-vec-robot-geometry-10', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'degrees-of-freedom', 'Degrees of Freedom', 'Degrees of freedom count the independent ways an arm can actually move. An arm with too few of them simply cannot reach some positions, no matter how it is commanded.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"degrees-of-freedom-sim"}'::jsonb, '{"xp":290,"credits":45}'::jsonb, false, 10),
  ('mission-vec-robot-geometry-11', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'workspace', 'Workspace', 'A workspace is the entire set of positions an arm can physically reach. Everything outside it is not a bug to fix. It is geometry to respect.', 'beginner', ARRAY['lin'], '{"requiredMissionIds":["mission-vec-robot-geometry-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"workspace-sim"}'::jsonb, '{"xp":300,"credits":45}'::jsonb, false, 11),
  ('mission-vec-robot-geometry-12', 'world-vec-robot-geometry', 'campaign-vec-robot-geometry', 'operation-vec-robot-geometry-2', 'where-is-the-arm', 'Where Is the Arm?', 'Everything this Act taught, turned on one arm: not to relocate it, to finally explain why every position it has ever reported was true and useless at the same time.', 'boss', ARRAY['imani','lin','byte'], '{"requiredMissionIds":["mission-vec-robot-geometry-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"where-is-the-arm-boss-sim"}'::jsonb, '{"xp":1350,"credits":280,"badgeIds":["where-is-the-arm"],"skillXp":{"robotics_fundamentals":175}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-vec-robot-geometry-01', 1, 'imani', 'The fleet audit turned up something Byte cannot classify with anything either of us knows. A warehouse handling arm. Every position it has ever logged disagrees with where anyone can actually find it standing.'),
  ('mission-vec-robot-geometry-01', 2, 'byte', 'I checked my own numbers three times. The arm''s telemetry is internally consistent -- every reading agrees with every other reading. It is simply wrong about where it is in the building, and I do not have the vocabulary to say why.'),
  ('mission-vec-robot-geometry-01', 3, 'imani', 'That is why I brought in someone who does. Dr. Lin Ortega, roboticist. She spent a decade making sure a robot always knows exactly where it is before anyone lets it move.'),
  ('mission-vec-robot-geometry-01', 4, 'lin', 'Dr. Lin Ortega. Before anything else, one rule: "where is the arm" is not a complete question. Where is the arm, relative to what. Every position anyone has ever logged was relative to something. The real question is whether anyone ever wrote down what that something was.'),
  ('mission-vec-robot-geometry-01', 5, 'lin', 'That something is called a coordinate frame -- an origin point and a set of directions everything else gets measured against. Change the frame, and the exact same physical position gets an entirely different number.'),

  ('mission-vec-robot-geometry-02', 1, 'lin', 'A vector is not a single number. It is a magnitude and a direction, always together. "Three meters" means nothing on its own. "Three meters, along the frame''s x-axis" means everything.'),
  ('mission-vec-robot-geometry-02', 2, 'lin', 'In two dimensions a vector is just a pair of numbers, one per axis. Add two vectors and you add each axis separately -- nothing more exotic than that.'),

  ('mission-vec-robot-geometry-03', 1, 'lin', 'The arm does not live on a flat floor plan. It reaches up, down and out, and describing that honestly takes a third number -- height, along a third axis perpendicular to the first two.'),
  ('mission-vec-robot-geometry-03', 2, 'lin', 'Everything from two dimensions still holds. Add a third component, and every rule you already trust simply extends one axis further.'),

  ('mission-vec-robot-geometry-04', 1, 'lin', 'Two arms can occupy the exact same point in space and still be aimed in completely different directions. Position alone never tells the whole story -- orientation is a separate fact that has to be tracked alongside it.'),
  ('mission-vec-robot-geometry-04', 2, 'lin', 'A rotation changes which way something is facing without moving where it is. For a gripper about to pick something up, orientation often matters more than position does.'),

  ('mission-vec-robot-geometry-05', 1, 'lin', 'A translation is the opposite of a rotation -- it moves a point to a new location without changing which way anything is facing at all.'),
  ('mission-vec-robot-geometry-05', 2, 'lin', 'Any rigid motion at all, no matter how complicated it looks, can be described completely as one rotation and one translation, combined.'),

  ('mission-vec-robot-geometry-06', 1, 'lin', 'A transformation matrix packages a rotation and a translation into a single object. Multiply a point by that matrix, and you get exactly where that point lands in a different frame.'),
  ('mission-vec-robot-geometry-06', 2, 'byte', 'Which means converting a position from one coordinate frame to another is not guesswork or approximation. It is one exact multiplication, provided the matrix itself is correct.'),
  ('mission-vec-robot-geometry-06', 3, 'lin', 'Provided the matrix is correct. Keep that condition. It is going to matter.'),

  ('mission-vec-robot-geometry-07', 1, 'lin', 'An ordinary matrix can rotate a point through multiplication, but it cannot translate one that way -- translation needs addition, not multiplication, and the two do not mix cleanly.'),
  ('mission-vec-robot-geometry-07', 2, 'lin', 'Homogeneous coordinates fix that with one trick: add an extra constant component to every point. Suddenly translation becomes just another matrix multiplication, and rotation and translation can finally be combined into one operation.'),
  ('mission-vec-robot-geometry-07', 3, 'lin', 'The real payoff is chaining. Multiply several of these matrices together in order, and you get one single transform all the way from the first frame to the last.'),

  ('mission-vec-robot-geometry-08', 1, 'lin', 'A real robot is never one frame. It is a chain of them -- base, shoulder, elbow, wrist, gripper -- and each link is only ever described relative to the joint immediately before it, never directly against the room.'),
  ('mission-vec-robot-geometry-08', 2, 'lin', 'That chain is deliberate. A joint only needs to know its own small, local relationship to its parent. Nothing has to reason about the whole arm at once just to describe one link.'),

  ('mission-vec-robot-geometry-09', 1, 'lin', 'Forward kinematics answers one exact question: given every joint angle right now, where does the very end of the arm actually end up in the world.'),
  ('mission-vec-robot-geometry-09', 2, 'lin', 'Chain every joint''s local transform together, base to gripper, multiply them in order, and the answer falls straight out -- one position, in the base frame, or in any frame you choose to convert it into afterward.'),
  ('mission-vec-robot-geometry-09', 3, 'byte', 'I have this arm''s current joint angles logged. Nothing has ever run forward kinematics on them against the actual facility frame before.'),

  ('mission-vec-robot-geometry-10', 1, 'lin', 'Degrees of freedom count the independent ways a robot can actually move -- one per joint that can rotate or slide on its own, with no other joint able to substitute for it.'),
  ('mission-vec-robot-geometry-10', 2, 'lin', 'An arm with fewer degrees of freedom than the space it is asked to work in simply cannot reach some positions at all, no matter how carefully it is commanded. That is not a bug. It is a geometric fact.'),

  ('mission-vec-robot-geometry-11', 1, 'lin', 'A workspace is the complete set of positions an arm can physically reach, given its link lengths and joint limits. It is a shape, not a list -- and anything outside that shape is unreachable by definition.'),
  ('mission-vec-robot-geometry-11', 2, 'lin', 'Old planning software loves to forget this and assume an arm can reach anywhere its math allows. The physical arm was never that generous.'),

  ('mission-vec-robot-geometry-12', 1, 'imani', 'Everything this Act taught you, we are using right now, on one arm. Not to move it. To finally explain why every position it has ever logged has been true and useless at the same time.'),
  ('mission-vec-robot-geometry-12', 2, 'lin', 'Start with its own report. Whatever frame that number is relative to, it has been telling the truth the entire time.'),
  ('mission-vec-robot-geometry-12', 3, 'byte', 'The arm''s logged position is self-consistent against its own base frame, every single time it has ever reported. It has never once been wrong about where it is relative to itself.'),
  ('mission-vec-robot-geometry-12', 4, 'lin', 'Then the error is not in the arm. It is in whatever the facility floor plan assumes it is being measured against.'),
  ('mission-vec-robot-geometry-12', 5, 'imani', 'So which is it. Explain it the way you would explain it to someone standing in the corridor, not to another engineer.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-vec-robot-geometry-01-o1', 'mission-vec-robot-geometry-01', 1, 'Define the frame', 'Choose the accurate definition of a coordinate frame.'),
  ('mission-vec-robot-geometry-01-o2', 'mission-vec-robot-geometry-01', 2, 'Ask the right question', 'State what is actually missing from the arm''s reported position.'),

  ('mission-vec-robot-geometry-02-o1', 'mission-vec-robot-geometry-02', 1, 'Define a vector', 'Choose the accurate definition of a vector.'),
  ('mission-vec-robot-geometry-02-o2', 'mission-vec-robot-geometry-02', 2, 'Add two vectors', 'Compute the sum of two 2D vectors.'),

  ('mission-vec-robot-geometry-03-o1', 'mission-vec-robot-geometry-03', 1, 'Extend to 3D', 'Identify the correctly extended 3D form of a 2D vector.'),

  ('mission-vec-robot-geometry-04-o1', 'mission-vec-robot-geometry-04', 1, 'Separate position from orientation', 'Sort each statement into a fact about position or a fact about orientation.'),
  ('mission-vec-robot-geometry-04-o2', 'mission-vec-robot-geometry-04', 2, 'Judge what rotation changes', 'Choose the accurate description of what a rotation does and does not change.'),

  ('mission-vec-robot-geometry-05-o1', 'mission-vec-robot-geometry-05', 1, 'Define translation', 'Choose the accurate definition of a translation.'),
  ('mission-vec-robot-geometry-05-o2', 'mission-vec-robot-geometry-05', 2, 'Decompose a rigid motion', 'Identify the two components any rigid motion can always be broken into.'),

  ('mission-vec-robot-geometry-06-o1', 'mission-vec-robot-geometry-06', 1, 'Explain the matrix''s job', 'Choose the accurate description of what a transformation matrix does.'),
  ('mission-vec-robot-geometry-06-o2', 'mission-vec-robot-geometry-06', 2, 'Spot the failure condition', 'State what happens to the result if the transformation matrix itself is wrong.'),

  ('mission-vec-robot-geometry-07-o1', 'mission-vec-robot-geometry-07', 1, 'Explain the extra component', 'Choose the reason homogeneous coordinates add an extra number to every point.'),
  ('mission-vec-robot-geometry-07-o2', 'mission-vec-robot-geometry-07', 2, 'Explain chaining', 'State what multiplying several homogeneous transforms together in order produces.'),

  ('mission-vec-robot-geometry-08-o1', 'mission-vec-robot-geometry-08', 1, 'Order the chain', 'Order a robot arm''s frames from base to gripper.'),
  ('mission-vec-robot-geometry-08-o2', 'mission-vec-robot-geometry-08', 2, 'Explain the local relationship', 'Choose the accurate description of how each frame in the chain relates to the one before it.'),

  ('mission-vec-robot-geometry-09-o1', 'mission-vec-robot-geometry-09', 1, 'Define forward kinematics', 'Choose the accurate definition of forward kinematics.'),
  ('mission-vec-robot-geometry-09-o2', 'mission-vec-robot-geometry-09', 2, 'State the method', 'Choose the correct way to compute the end effector''s position from joint angles.'),

  ('mission-vec-robot-geometry-10-o1', 'mission-vec-robot-geometry-10', 1, 'Define degrees of freedom', 'Choose the accurate definition of a degree of freedom.'),
  ('mission-vec-robot-geometry-10-o2', 'mission-vec-robot-geometry-10', 2, 'Judge a consequence', 'State what happens when an arm has fewer degrees of freedom than the task requires.'),

  ('mission-vec-robot-geometry-11-o1', 'mission-vec-robot-geometry-11', 1, 'Define workspace', 'Choose the accurate definition of a robot''s workspace.'),

  ('mission-vec-robot-geometry-12-o1', 'mission-vec-robot-geometry-12', 1, 'Confirm the arm''s own frame', 'Find the evidence proving the arm''s logged position is self-consistent within its own base frame.'),
  ('mission-vec-robot-geometry-12-o2', 'mission-vec-robot-geometry-12', 2, 'Find the missing transform', 'Find the evidence proving no recorded transform exists between the arm''s frame and the facility floor plan''s frame.'),
  ('mission-vec-robot-geometry-12-o3', 'mission-vec-robot-geometry-12', 3, 'Compute the true position', 'Choose the correct real-world position once the arm''s own report is composed with the correct frame transform.'),
  ('mission-vec-robot-geometry-12-o4', 'mission-vec-robot-geometry-12', 4, 'State the diagnosis', 'Having confirmed all three, explain in plain terms why the arm''s position has always been true and useless at the same time.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-vec-robot-geometry-01-o1-c1', 'mission-vec-robot-geometry-01-o1', 1, 'multiple_choice', 'A coordinate frame is best described as...', '{"question":"A coordinate frame is best described as...","options":[{"id":"a","text":"A single number describing distance"},{"id":"b","text":"An origin point and a set of reference directions that every other position gets measured against"},{"id":"c","text":"A physical object bolted to a robot"},{"id":"d","text":"A synonym for a robot''s workspace"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-robot-geometry-01-o2-c1', 'mission-vec-robot-geometry-01-o2', 1, 'multiple_choice', 'The arm''s telemetry is internally consistent but disagrees with reality. What question does that raise?', '{"question":"The arm''s telemetry is internally consistent but disagrees with reality. What question does that raise?","options":[{"id":"a","text":"Whether the arm''s sensors are broken"},{"id":"b","text":"Whether anyone ever recorded which coordinate frame the arm''s reported position is actually relative to"},{"id":"c","text":"Whether the arm needs new firmware"},{"id":"d","text":"Whether the arm is being hacked"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-02-o1-c1', 'mission-vec-robot-geometry-02-o1', 1, 'multiple_choice', 'A vector is best described as...', '{"question":"A vector is best described as...","options":[{"id":"a","text":"A single number with no direction"},{"id":"b","text":"A magnitude and a direction together"},{"id":"c","text":"Only ever used for velocity, never position"},{"id":"d","text":"A synonym for a coordinate frame"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-robot-geometry-02-o2-c1', 'mission-vec-robot-geometry-02-o2', 1, 'multiple_choice', 'Add the 2D vectors (3, 2) and (1, 4).', '{"question":"Add the 2D vectors (3, 2) and (1, 4).","options":[{"id":"a","text":"(4, 6)"},{"id":"b","text":"(3, 8)"},{"id":"c","text":"(2, -2)"},{"id":"d","text":"(4, 2)"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-robot-geometry-03-o1-c1', 'mission-vec-robot-geometry-03-o1', 1, 'multiple_choice', 'The 2D vector (2, 5) is correctly extended into 3D, adding a height of 1, as...', '{"question":"The 2D vector (2, 5) is correctly extended into 3D, adding a height of 1, as...","options":[{"id":"a","text":"(2, 5, 1)"},{"id":"b","text":"(1, 2, 5)"},{"id":"c","text":"(2, 1, 5)"},{"id":"d","text":"(2, 5)"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-robot-geometry-04-o1-c1', 'mission-vec-robot-geometry-04-o1', 1, 'drag_and_drop', 'Sort each statement into a fact about position or a fact about orientation.', '{"items":[{"id":"i1","text":"The gripper is centered two meters from the wall"},{"id":"i2","text":"The gripper is pointed straight down"},{"id":"i3","text":"The arm''s base sits at the corner of the workbench"},{"id":"i4","text":"The wrist is rotated ninety degrees from neutral"}],"targets":[{"id":"position","label":"Position"},{"id":"orientation","label":"Orientation"}]}'::jsonb, '{"correctMapping":{"i1":"position","i2":"orientation","i3":"position","i4":"orientation"}}'::jsonb),
  ('mission-vec-robot-geometry-04-o2-c1', 'mission-vec-robot-geometry-04-o2', 1, 'multiple_choice', 'A pure rotation applied to an object...', '{"question":"A pure rotation applied to an object...","options":[{"id":"a","text":"Changes both its position and its orientation"},{"id":"b","text":"Changes only its orientation, leaving its position unchanged"},{"id":"c","text":"Changes only its position, leaving its orientation unchanged"},{"id":"d","text":"Changes neither"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-05-o1-c1', 'mission-vec-robot-geometry-05-o1', 1, 'multiple_choice', 'A translation is best described as...', '{"question":"A translation is best described as...","options":[{"id":"a","text":"A change in orientation with no change in position"},{"id":"b","text":"A change in position with no change in orientation"},{"id":"c","text":"A synonym for rotation"},{"id":"d","text":"Only applicable in three dimensions"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-robot-geometry-05-o2-c1', 'mission-vec-robot-geometry-05-o2', 1, 'multiple_choice', 'Any rigid motion, however complex it looks, can always be described completely as...', '{"question":"Any rigid motion, however complex it looks, can always be described completely as...","options":[{"id":"a","text":"One rotation and one translation, combined"},{"id":"b","text":"An unlimited, unpredictable number of separate operations"},{"id":"c","text":"A single scalar number"},{"id":"d","text":"A change in the object''s size"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-robot-geometry-06-o1-c1', 'mission-vec-robot-geometry-06-o1', 1, 'multiple_choice', 'A transformation matrix is best described as...', '{"question":"A transformation matrix is best described as...","options":[{"id":"a","text":"A rotation and translation packaged into one operation, applied to a point by multiplication"},{"id":"b","text":"A way to store a robot''s color"},{"id":"c","text":"Only usable for rotation, never translation"},{"id":"d","text":"A synonym for a degree of freedom"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-robot-geometry-06-o2-c1', 'mission-vec-robot-geometry-06-o2', 1, 'multiple_choice', 'If the transformation matrix used to convert a position between frames is wrong, the result is...', '{"question":"If the transformation matrix used to convert a position between frames is wrong, the result is...","options":[{"id":"a","text":"Automatically corrected by the receiving frame"},{"id":"b","text":"A confidently wrong position, internally consistent but incorrect, with nothing to flag it as wrong"},{"id":"c","text":"Impossible, matrices cannot be wrong"},{"id":"d","text":"Only a problem if the object is also rotating"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-07-o1-c1', 'mission-vec-robot-geometry-07-o1', 1, 'multiple_choice', 'Homogeneous coordinates add an extra constant component to every point in order to...', '{"question":"Homogeneous coordinates add an extra constant component to every point in order to...","options":[{"id":"a","text":"Make translation expressible as matrix multiplication, alongside rotation"},{"id":"b","text":"Store the point''s color"},{"id":"c","text":"Remove the need for rotation entirely"},{"id":"d","text":"Reduce the number of dimensions needed"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-robot-geometry-07-o2-c1', 'mission-vec-robot-geometry-07-o2', 1, 'multiple_choice', 'Multiplying several homogeneous transformation matrices together, in order, produces...', '{"question":"Multiplying several homogeneous transformation matrices together, in order, produces...","options":[{"id":"a","text":"A single combined transform all the way from the first frame to the last"},{"id":"b","text":"An error, matrices cannot be chained"},{"id":"c","text":"Only the final rotation, discarding all translations"},{"id":"d","text":"A random result"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-robot-geometry-08-o1-c1', 'mission-vec-robot-geometry-08-o1', 1, 'interactive_diagram', 'Order a robot arm''s frames from base to gripper.', '{"diagramId":"robot-frame-chain","hotspots":[{"id":"base","label":"Base frame","explanation":"The root frame everything else is ultimately measured relative to."},{"id":"shoulder","label":"Shoulder frame","explanation":"Local frame at the first joint, relative to the base."},{"id":"elbow","label":"Elbow frame","explanation":"Local frame at the second joint, relative to the shoulder."},{"id":"wrist","label":"Wrist frame","explanation":"Local frame at the third joint, relative to the elbow."},{"id":"gripper","label":"Gripper frame","explanation":"The final frame, relative to the wrist -- where the arm actually does work."}],"task":"Order the chain of frames from the base to the gripper."}'::jsonb, '{"correctOrderIds":["base","shoulder","elbow","wrist","gripper"]}'::jsonb),
  ('mission-vec-robot-geometry-08-o2-c1', 'mission-vec-robot-geometry-08-o2', 1, 'multiple_choice', 'Each frame in a robot''s chain is defined relative to...', '{"question":"Each frame in a robot''s chain is defined relative to...","options":[{"id":"a","text":"The room itself, directly, every time"},{"id":"b","text":"The frame immediately before it in the chain"},{"id":"c","text":"The gripper frame, regardless of position in the chain"},{"id":"d","text":"Nothing -- frames in a chain are independent"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-09-o1-c1', 'mission-vec-robot-geometry-09-o1', 1, 'multiple_choice', 'Forward kinematics answers which question?', '{"question":"Forward kinematics answers which question?","options":[{"id":"a","text":"Given a target position, what joint angles reach it"},{"id":"b","text":"Given the current joint angles, where does the end effector actually end up"},{"id":"c","text":"How much current does each joint motor draw"},{"id":"d","text":"How fast can the arm move"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-vec-robot-geometry-09-o2-c1', 'mission-vec-robot-geometry-09-o2', 1, 'multiple_choice', 'The correct way to compute the end effector''s position from joint angles is to...', '{"question":"The correct way to compute the end effector''s position from joint angles is to...","options":[{"id":"a","text":"Guess based on the arm''s overall length"},{"id":"b","text":"Chain each joint''s local transform together, base to gripper, and multiply them in order"},{"id":"c","text":"Only use the base frame and ignore intermediate joints"},{"id":"d","text":"Average all joint angles together"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-10-o1-c1', 'mission-vec-robot-geometry-10-o1', 1, 'multiple_choice', 'A degree of freedom is best described as...', '{"question":"A degree of freedom is best described as...","options":[{"id":"a","text":"An independent way the robot can move, with no other joint able to substitute for it"},{"id":"b","text":"A synonym for a coordinate frame"},{"id":"c","text":"The maximum speed of a joint"},{"id":"d","text":"The number of sensors on the arm"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-robot-geometry-10-o2-c1', 'mission-vec-robot-geometry-10-o2', 1, 'multiple_choice', 'An arm with fewer degrees of freedom than the task it is asked to perform will...', '{"question":"An arm with fewer degrees of freedom than the task it is asked to perform will...","options":[{"id":"a","text":"Simply be unable to reach some positions, regardless of how it is commanded"},{"id":"b","text":"Always find a way to compensate automatically"},{"id":"c","text":"Move faster to make up the difference"},{"id":"d","text":"Have no effect on reachability at all"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-vec-robot-geometry-11-o1-c1', 'mission-vec-robot-geometry-11-o1', 1, 'multiple_choice', 'A robot''s workspace is best described as...', '{"question":"A robot''s workspace is best described as...","options":[{"id":"a","text":"A list of positions engineers approve one at a time"},{"id":"b","text":"The complete set of positions the arm can physically reach, given its link lengths and joint limits"},{"id":"c","text":"The room the robot is installed in"},{"id":"d","text":"A synonym for degrees of freedom"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-vec-robot-geometry-12-o1-c1', 'mission-vec-robot-geometry-12-o1', 1, 'investigation', 'Which evidence proves the arm''s logged position is self-consistent within its own base frame?', '{"evidence":[{"id":"e1","label":"Telemetry cross-check","detail":"Every joint-angle reading and every reported end-effector position agree with each other under forward kinematics computed in the arm''s own base frame"},{"id":"e2","label":"Facility note","detail":"The floor plan was last updated during a renovation decades ago"},{"id":"e3","label":"Power log","detail":"The arm draws steady power regardless of position"}],"question":"Which evidence proves the arm''s logged position is self-consistent within its own base frame?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-robot-geometry-12-o2-c1', 'mission-vec-robot-geometry-12-o2', 1, 'investigation', 'Which evidence proves no recorded transform exists between the arm''s frame and the facility floor plan''s frame?', '{"evidence":[{"id":"e1","label":"Documentation search", "detail":"No transform, calibration record or survey linking the arm''s base frame to the floor plan''s frame exists anywhere in facility records"},{"id":"e2","label":"Maintenance log","detail":"The arm has been serviced on a normal schedule with no reported hardware faults"},{"id":"e3","label":"Telemetry cross-check","detail":"The arm''s joint angles are all within their rated limits"}],"question":"Which evidence proves no recorded transform exists between the arm''s frame and the facility floor plan''s frame?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-vec-robot-geometry-12-o3-c1', 'mission-vec-robot-geometry-12-o3', 1, 'multiple_choice', 'Once the arm''s own reported position is correctly composed with the true transform to the facility frame, the result is...', '{"question":"Once the arm''s own reported position is correctly composed with the true transform to the facility frame, the result is...","options":[{"id":"a","text":"The arm''s actual, physical position in the building, matching exactly where the floor team finds it"},{"id":"b","text":"Identical to the arm''s uncorrected base-frame report"},{"id":"c","text":"Undefined, because two frames can never be composed"},{"id":"d","text":"Only valid if the arm is powered off"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-vec-robot-geometry-12-o4-c1', 'mission-vec-robot-geometry-12-o4', 1, 'boss_encounter', 'Having confirmed the arm''s own frame, the missing transform, and the true corrected position, explain why the arm''s reported position has always been true and useless at the same time.', '{"stages":[{"objectiveRef":"mission-vec-robot-geometry-12-o1","label":"Confirm the arm''s own frame"},{"objectiveRef":"mission-vec-robot-geometry-12-o2","label":"Find the missing transform"},{"objectiveRef":"mission-vec-robot-geometry-12-o3","label":"Compute the true position"}],"task":"State the diagnosis in one sentence: the arm''s logged coordinates were always correct for its own base frame, but the facility''s floor-plan documentation used a different, undocumented reference frame from decades ago, so every position report was internally consistent and externally meaningless, with no transform ever recorded between the two."}'::jsonb, '{"requiredObjectiveIds":["mission-vec-robot-geometry-12-o1","mission-vec-robot-geometry-12-o2","mission-vec-robot-geometry-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-vec-robot-geometry-01-o1-c1', 'orientation', 'A frame is what everything else gets measured against, not a measurement itself.', 10, 1),
  ('mission-vec-robot-geometry-01-o1-c1', 'solution', 'A coordinate frame is an origin and a set of reference directions that every other position is measured relative to.', 20, 2),
  ('mission-vec-robot-geometry-01-o2-c1', 'orientation', 'The numbers are not wrong. The context around them might be missing.', 10, 1),
  ('mission-vec-robot-geometry-01-o2-c1', 'solution', 'The real question is whether anyone ever recorded which frame the arm''s position is actually relative to.', 20, 2),

  ('mission-vec-robot-geometry-02-o1-c1', 'orientation', 'A vector always has two parts, never just one.', 10, 1),
  ('mission-vec-robot-geometry-02-o1-c1', 'solution', 'A vector is a magnitude and a direction together.', 20, 2),
  ('mission-vec-robot-geometry-02-o2-c1', 'orientation', 'Add each axis separately: x with x, y with y.', 10, 1),
  ('mission-vec-robot-geometry-02-o2-c1', 'solution', '(3+1, 2+4) = (4, 6).', 20, 2),

  ('mission-vec-robot-geometry-03-o1-c1', 'orientation', 'The new component goes in its own new axis position, not replacing an old one.', 10, 1),
  ('mission-vec-robot-geometry-03-o1-c1', 'solution', '(2, 5, 1) -- the original x and y stay, height is added as a third component.', 20, 2),

  ('mission-vec-robot-geometry-04-o1-c1', 'orientation', 'Ask whether the statement is about where something is, or which way it is facing.', 10, 1),
  ('mission-vec-robot-geometry-04-o1-c1', 'solution', 'Position: the distance from the wall, the base at the corner. Orientation: pointed down, rotated ninety degrees.', 20, 2),
  ('mission-vec-robot-geometry-04-o2-c1', 'orientation', 'A rotation turns something without sliding it anywhere.', 10, 1),
  ('mission-vec-robot-geometry-04-o2-c1', 'solution', 'A pure rotation changes only orientation, leaving position unchanged.', 20, 2),

  ('mission-vec-robot-geometry-05-o1-c1', 'orientation', 'Translation is the opposite of rotation.', 10, 1),
  ('mission-vec-robot-geometry-05-o1-c1', 'solution', 'A translation changes position without changing orientation.', 20, 2),
  ('mission-vec-robot-geometry-05-o2-c1', 'orientation', 'Two operations are always enough, no matter how the motion looks.', 10, 1),
  ('mission-vec-robot-geometry-05-o2-c1', 'solution', 'Any rigid motion decomposes into one rotation and one translation, combined.', 20, 2),

  ('mission-vec-robot-geometry-06-o1-c1', 'orientation', 'Think of it as rotation and translation, bundled into one operation.', 10, 1),
  ('mission-vec-robot-geometry-06-o1-c1', 'solution', 'A transformation matrix packages rotation and translation, applied to a point through multiplication.', 20, 2),
  ('mission-vec-robot-geometry-06-o2-c1', 'orientation', 'The math does not know it is wrong -- it just produces a number.', 10, 1),
  ('mission-vec-robot-geometry-06-o2-c1', 'solution', 'A wrong matrix produces a confidently wrong, internally consistent position with nothing to flag it.', 20, 2),

  ('mission-vec-robot-geometry-07-o1-c1', 'orientation', 'Ordinary matrix multiplication alone cannot shift a point''s position.', 10, 1),
  ('mission-vec-robot-geometry-07-o1-c1', 'solution', 'The extra component lets translation be expressed as matrix multiplication, alongside rotation.', 20, 2),
  ('mission-vec-robot-geometry-07-o2-c1', 'orientation', 'Each multiplication moves a point one frame further along the chain.', 10, 1),
  ('mission-vec-robot-geometry-07-o2-c1', 'solution', 'Chained multiplication produces one combined transform from the first frame all the way to the last.', 20, 2),

  ('mission-vec-robot-geometry-08-o1-c1', 'orientation', 'Nothing downstream can be described before its parent joint is defined.', 10, 1),
  ('mission-vec-robot-geometry-08-o1-c1', 'solution', 'Base, then shoulder, then elbow, then wrist, then gripper.', 20, 2),
  ('mission-vec-robot-geometry-08-o2-c1', 'orientation', 'Each link only needs to know its small, local relationship to what comes before it.', 10, 1),
  ('mission-vec-robot-geometry-08-o2-c1', 'solution', 'Each frame is defined relative to the frame immediately before it in the chain.', 20, 2),

  ('mission-vec-robot-geometry-09-o1-c1', 'orientation', 'It goes from joint angles to a position, not the other direction.', 10, 1),
  ('mission-vec-robot-geometry-09-o1-c1', 'solution', 'Forward kinematics computes where the end effector ends up, given the current joint angles.', 20, 2),
  ('mission-vec-robot-geometry-09-o2-c1', 'orientation', 'No single frame skips the chain in between.', 10, 1),
  ('mission-vec-robot-geometry-09-o2-c1', 'solution', 'Chain every joint''s local transform together, base to gripper, and multiply them in order.', 20, 2),

  ('mission-vec-robot-geometry-10-o1-c1', 'orientation', 'It is about independence, not just counting joints.', 10, 1),
  ('mission-vec-robot-geometry-10-o1-c1', 'solution', 'A degree of freedom is an independent way the robot can move that nothing else can substitute for.', 20, 2),
  ('mission-vec-robot-geometry-10-o2-c1', 'orientation', 'No amount of clever commanding invents a joint that is not there.', 10, 1),
  ('mission-vec-robot-geometry-10-o2-c1', 'solution', 'Too few degrees of freedom means some positions are simply unreachable, regardless of command.', 20, 2),

  ('mission-vec-robot-geometry-11-o1-c1', 'orientation', 'It is defined by physical geometry, not by approval or policy.', 10, 1),
  ('mission-vec-robot-geometry-11-o1-c1', 'solution', 'A workspace is the full set of positions the arm can physically reach given its links and joint limits.', 20, 2),

  ('mission-vec-robot-geometry-12-o1-c1', 'orientation', 'Look for a check that compares the arm''s own numbers against each other, not against the building.', 10, 1),
  ('mission-vec-robot-geometry-12-o1-c1', 'solution', 'e1: forward kinematics computed purely in the arm''s own base frame matches its reported position every time.', 20, 2),
  ('mission-vec-robot-geometry-12-o2-c1', 'orientation', 'Look for what is missing from the records, not what is present.', 10, 1),
  ('mission-vec-robot-geometry-12-o2-c1', 'solution', 'e1: no transform, calibration or survey linking the arm''s frame to the floor plan''s frame exists anywhere.', 20, 2),
  ('mission-vec-robot-geometry-12-o3-c1', 'orientation', 'Composing the arm''s own report with the correct transform should finally match physical reality.', 10, 1),
  ('mission-vec-robot-geometry-12-o3-c1', 'solution', 'The corrected position matches exactly where the floor team actually finds the arm standing.', 20, 2),
  ('mission-vec-robot-geometry-12-o4-c1', 'orientation', 'State what was true about the arm''s own math, and what was missing between it and the building.', 15, 1),
  ('mission-vec-robot-geometry-12-o4-c1', 'solution', 'The arm''s coordinates were always correct for its own base frame. The floor plan used a different, undocumented frame from decades ago, and nobody ever recorded the transform between the two -- true and useless at the same time.', 25, 2);
