-- AI/ML pathway ("Cipher Division") Act 29 -- "RAG" content.
-- Arc VI, Acts 28-33 ("Knowledge & Agents"); this Act does not close the
-- Arc, Act 33 does. Direct thematic payoff to Act 26's hallucination
-- problem, and the direct sequel to Act 28's retrieval-only system.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue_lines -> objectives ->
-- challenges -> hints pattern as every other pathway Act.
-- Only inserts into campaigns/operations/missions/dialogue_lines/objectives/
-- challenges/hints. The world-ai-rag row already exists (act_id act-ai-6).

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-rag', 'world-ai-rag', 'rag', '29A - RAG', 'Build the full retrieval-augmented generation pipeline over Cipher Division''s own investigation archive -- ingestion, grounding, citations, query rewriting, multi-query, decomposition, reranking and hybrid search -- and learn exactly why retrieval alone was never going to be enough to stop a confident lie.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-rag-1', 'campaign-ai-rag', 'retrieve-and-ground', 'Retrieve and Ground', 'Why retrieval alone is not enough, how the archive gets ingested and queried, and what it actually takes to force an answer to stay grounded in real, cited sources.', 1),
  ('operation-ai-rag-2', 'campaign-ai-rag', 'sharper-queries', 'Sharper Queries', 'Rewriting, multiplying, decomposing and reranking queries to retrieve better evidence -- and the moment a fully grounded, cited assistant still answers from memory instead of from what it actually found.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-rag-01', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'why-rag', 'Why RAG?', 'Retrieval alone just finds documents. Cipher Division needs the assistant to actually answer questions about its own investigation, grounded in what it retrieves, with a citation for every claim.', 'beginner', ARRAY['maya','elena'], null, null, '{"type":"simulation","simulationId":"why-rag-sim"}'::jsonb, '{"xp":600,"credits":160}'::jsonb, false, 1),
  ('mission-ai-rag-02', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'ingestion', 'Ingestion', 'Before the assistant can retrieve anything, the archive has to become a searchable index -- loaded, chunked, embedded and stored, once, ahead of any question.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-rag-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"ingestion-sim"}'::jsonb, '{"xp":610,"credits":160}'::jsonb, false, 2),
  ('mission-ai-rag-03', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'query-pipeline', 'Query Pipeline', 'Ingestion runs once, offline. The query pipeline runs live, every time -- embed the question, retrieve the closest chunks, hand both to the model together.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-rag-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-pipeline-sim"}'::jsonb, '{"xp":610,"credits":165}'::jsonb, false, 3),
  ('mission-ai-rag-04', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'grounding', 'Grounding', 'Retrieval can work perfectly and still get ignored. Grounding is the requirement that every claim in the answer actually comes from what was retrieved.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-rag-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"grounding-sim"}'::jsonb, '{"xp":620,"credits":165}'::jsonb, false, 4),
  ('mission-ai-rag-05', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'citations', 'Citations', 'A citation looks like proof sitting right next to a claim. It only means retrieval touched that document at some point -- not that the document actually says what the claim says.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-rag-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"citations-sim"}'::jsonb, '{"xp":620,"credits":165}'::jsonb, false, 5),
  ('mission-ai-rag-06', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-1', 'retrieval-failure', 'Retrieval Failure', 'A stale index, a mismatched query, a top-k too small -- retrieval fails in more ways than bad chunking, and it never announces when it has.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-rag-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"retrieval-failure-sim"}'::jsonb, '{"xp":630,"credits":170}'::jsonb, false, 6),
  ('mission-ai-rag-07', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'query-rewriting', 'Query Rewriting', 'People do not write questions the way archives write documents. Query rewriting fixes the search query itself, before retrieval ever runs.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-rag-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-rewriting-sim"}'::jsonb, '{"xp":630,"credits":170}'::jsonb, false, 7),
  ('mission-ai-rag-08', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'multi-query', 'Multi-Query', 'One phrasing can miss the right chunk by pure word choice. Multi-query asks the same question several different ways and retrieves for all of them.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-rag-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"multi-query-sim"}'::jsonb, '{"xp":640,"credits":170}'::jsonb, false, 8),
  ('mission-ai-rag-09', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'decomposition', 'Decomposition', 'Some questions are not one question. Decomposition splits a compound question into sub-questions, answers each on its own evidence, then composes the result.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-rag-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"decomposition-sim"}'::jsonb, '{"xp":640,"credits":175}'::jsonb, false, 9),
  ('mission-ai-rag-10', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'reranking', 'Reranking', 'Fast retrieval and precise retrieval rarely come free together. Reranking buys the precision back with a second, slower pass over a smaller candidate set.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-rag-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"reranking-sim"}'::jsonb, '{"xp":650,"credits":175}'::jsonb, false, 10),
  ('mission-ai-rag-11', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'hybrid-search', 'Hybrid Search', 'Vector search understands meaning and quietly loses exact strings. Hybrid search runs a keyword pass alongside it, so an exact ID does not get lost in translation.', 'intermediate', ARRAY['elena','noah'], '{"requiredMissionIds":["mission-ai-rag-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"hybrid-search-sim"}'::jsonb, '{"xp":650,"credits":175}'::jsonb, false, 11),
  ('mission-ai-rag-12', 'world-ai-rag', 'campaign-ai-rag', 'operation-ai-rag-2', 'the-hallucinating-archivist', 'The Hallucinating Archivist', 'Retrieval runs clean and returns the real document. The answer still is not what that document says -- a citation on the page was never proof the model actually used it.', 'boss', ARRAY['maya','elena','noah'], '{"requiredMissionIds":["mission-ai-rag-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-hallucinating-archivist-boss-sim"}'::jsonb, '{"xp":1450,"credits":310,"badgeIds":["the-hallucinating-archivist"],"skillXp":{"rag":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-rag-01', 1, 'maya', 'Act 26 left us with an assistant that can produce a fluent, wrong answer and sound exactly as confident as a correct one. Act 28 gave it something to search -- a real vector index over our own archive. Today those two problems collide.'),
  ('mission-ai-rag-01', 2, 'elena', 'A retriever alone just finds documents. It hands back the five most relevant chunks and stops. Nobody has told it what to do with them, and nobody has told the model it is not allowed to just keep guessing.'),
  ('mission-ai-rag-01', 3, 'elena', 'Retrieval-Augmented Generation closes that gap. Retrieve the real evidence, feed it into the model as context, and generate an answer that is supposed to be built from what was actually retrieved -- not from whatever the model remembers.'),
  ('mission-ai-rag-01', 4, 'maya', 'Retrieval alone just finds documents. Cipher Division needs the assistant to actually answer questions about its own investigation, grounded in what it retrieves, with a citation for every claim. That is the mandate for this whole Act.'),
  ('mission-ai-rag-01', 5, 'elena', 'If it has to cite a real, retrieved source for every claim, a confident lie should not be possible the same way it was in Act 26. Should not be. We are going to spend this Act finding out exactly how true that is.'),

  ('mission-ai-rag-02', 1, 'elena', 'Before the assistant can retrieve anything, the archive has to become an index somebody, or something, can actually search. That process is ingestion.'),
  ('mission-ai-rag-02', 2, 'byte', 'Every log, report and finding gets pulled in, split into chunks, turned into embeddings, and written to the vector store. Ahead of time, once, offline -- not while a question is waiting.'),
  ('mission-ai-rag-02', 3, 'elena', 'Skip a step, or do it badly, and every mission this Act builds on top of it inherits the same crack. Ingestion is not the exciting part. It is the part everything else depends on.'),

  ('mission-ai-rag-03', 1, 'elena', 'Ingestion happens once, offline. The query pipeline is the other half -- what runs live, every single time somebody actually asks the assistant something.'),
  ('mission-ai-rag-03', 2, 'byte', 'A question comes in. It gets embedded the same way the chunks were. That embedding is compared against the index to pull back the most relevant chunks. Those chunks, plus the original question, go to the model together.'),
  ('mission-ai-rag-03', 3, 'elena', 'Only then does the model generate anything. Everything before that is retrieval. The model never sees the raw archive -- only whatever the retriever decided was relevant enough to hand over.'),

  ('mission-ai-rag-04', 1, 'elena', 'Retrieval alone does not stop a model from ignoring what it retrieved. Grounding is the explicit requirement that every claim in the answer has to come from the retrieved content, not from whatever the model already believes.'),
  ('mission-ai-rag-04', 2, 'elena', 'In practice that means instructing the model directly: answer only using the provided context, and say plainly when the context does not contain an answer, instead of filling the gap with something plausible.'),
  ('mission-ai-rag-04', 3, 'elena', 'Grounding is a constraint on generation, not a feature of retrieval. Retrieval can work perfectly and the model can still ignore it completely if nothing forces it to stay inside what it was given.'),

  ('mission-ai-rag-05', 1, 'elena', 'Grounding controls what the model is allowed to say. Citations control whether anyone else can check it -- every claim gets a reference back to the specific chunk or document it supposedly came from.'),
  ('mission-ai-rag-05', 2, 'elena', 'A citation looks like proof. It has a document id, maybe a page or a chunk number, sitting right there next to the claim. That is exactly why it is worth double-checking rather than trusting on sight.'),
  ('mission-ai-rag-05', 3, 'elena', 'A citation only means retrieval touched that document at some point in the process. It does not, by itself, mean the specific sentence next to it is actually what that document says.'),

  ('mission-ai-rag-06', 1, 'elena', 'Act 28 already showed us one way retrieval breaks -- a real answer sitting in the archive, chunked so badly the query never matched it. Retrieval failure is bigger than just chunking, though.'),
  ('mission-ai-rag-06', 2, 'noah', 'In production I have seen it fail for half a dozen reasons: a query worded nothing like the source text, an index that never got updated after new evidence came in, a top-k set too small to catch the right chunk even when it exists.'),
  ('mission-ai-rag-06', 3, 'elena', 'The dangerous part is that the assistant does not know it failed. It just retrieves whatever ranked highest, even if none of it is actually relevant, and generates an answer as if that were the whole truth.'),
  ('mission-ai-rag-06', 4, 'noah', 'Which means somebody has to go looking for retrieval failures on purpose. They do not announce themselves.'),

  ('mission-ai-rag-07', 1, 'elena', 'Sometimes retrieval fails for a much simpler reason: the question, exactly as typed, is a bad search query. People do not write questions the way they write documents.'),
  ('mission-ai-rag-07', 2, 'elena', 'Query rewriting fixes what goes into the retriever, before retrieval ever runs. Resolve a vague pronoun, expand an abbreviation, turn a real conversational question into something closer to the phrasing the archive actually uses.'),
  ('mission-ai-rag-07', 3, 'elena', 'It is a small step, and it happens before anything else in the pipeline -- get the search query wrong and no amount of grounding or citation checking downstream will save the answer.'),

  ('mission-ai-rag-08', 1, 'elena', 'Query rewriting fixes one query into a better version of itself. Multi-query goes further: generate several different phrasings of the same question, retrieve for each one, and combine the results.'),
  ('mission-ai-rag-08', 2, 'elena', 'A single phrasing can miss a relevant chunk just because it uses different words than the source text did. Ask the same thing five different ways and the odds of at least one phrasing matching the right chunk go up a lot.'),
  ('mission-ai-rag-08', 3, 'elena', 'The tradeoff is cost -- five retrievals instead of one. Worth it when a question is ambiguous or broad. Overkill when it is not.'),

  ('mission-ai-rag-09', 1, 'elena', 'Multi-query handles one ambiguous question asked several ways. Decomposition handles a genuinely different problem: one question that is actually several questions stitched together.'),
  ('mission-ai-rag-09', 2, 'elena', 'Ask what changed between Echo''s first message and its most recent one, and whether that matches what Act 6 said about its missing training data, and that is not one retrieval. It is at least two, maybe three, each needing its own evidence.'),
  ('mission-ai-rag-09', 3, 'elena', 'Decomposition breaks the question into sub-questions, retrieves and answers each one on its own evidence, then composes the pieces into a single final answer -- instead of retrieving once for a question the retriever can never fully satisfy in one pass.'),

  ('mission-ai-rag-10', 1, 'noah', 'Initial retrieval has to be fast, which means it uses a cheap approximate similarity search across the whole index. Fast and precise almost never come free together.'),
  ('mission-ai-rag-10', 2, 'elena', 'So retrieval usually pulls back more candidates than it needs, and a second, slower model reranks just that smaller set -- scoring each candidate against the question far more carefully than the first pass could afford to.'),
  ('mission-ai-rag-10', 3, 'noah', 'Reranking sits between retrieval and generation. Retrieve wide and fast, rerank narrow and precise, then only the reranked top few actually reach the model.'),

  ('mission-ai-rag-11', 1, 'noah', 'Vector search is good at meaning. It is genuinely bad at exact strings -- an incident ID, an error code, a name spelled an unusual way. Semantically similar is not the same as textually identical, and sometimes textually identical is exactly what the question needs.'),
  ('mission-ai-rag-11', 2, 'elena', 'Hybrid search runs both at once: dense vector retrieval for meaning, and a sparse keyword method like BM25 for exact terms, then combines the two ranked lists into one.'),
  ('mission-ai-rag-11', 3, 'noah', 'Neither one alone covers everything this archive needs searched. Together they cover a lot more of it.'),

  ('mission-ai-rag-12', 1, 'maya', 'The grounding and citation requirements from this Act exist precisely to fix Act 26. Time to actually test that claim. Ask the assistant something real, pulled straight from our own archive.'),
  ('mission-ai-rag-12', 2, 'elena', 'We asked what Arjun''s Act 6 data quality report, document AV-006, actually concluded about Echo''s missing training data. Retrieval ran clean -- it pulled AV-006, the real report, ranked first. Then the model answered.'),
  ('mission-ai-rag-12', 3, 'noah', 'And the answer states the report confirms a systematic bias in Echo''s decisions favoring Nexus''s original administrators, validated by internal audit metrics -- citing AV-006 as the source, right there next to the claim.'),
  ('mission-ai-rag-12', 4, 'elena', 'That is not what AV-006 says. I have the real report open right now, and none of that is in it.'),
  ('mission-ai-rag-12', 5, 'maya', 'Even with real retrieval wired in, the assistant answered one question confidently from memory instead of from what it actually retrieved. A citation on the page is not proof the model used the source behind it. A RAG system that can be fooled into ignoring its own sources needs harder defenses than the basics. The failure modes get uglier from here.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-rag-01-o1', 'mission-ai-rag-01', 1, 'Define RAG', 'State what Retrieval-Augmented Generation actually adds on top of a plain retriever.'),
  ('mission-ai-rag-01-o2', 'mission-ai-rag-01', 2, 'Name the mandate', 'State why grounding and citations are meant to directly fix Act 26''s hallucination problem.'),

  ('mission-ai-rag-02-o1', 'mission-ai-rag-02', 1, 'Define ingestion', 'State what actually happens during ingestion, before any user question is asked.'),
  ('mission-ai-rag-02-o2', 'mission-ai-rag-02', 2, 'Order the ingestion pipeline', 'Put the stages of ingestion in the order they actually run.'),

  ('mission-ai-rag-03-o1', 'mission-ai-rag-03', 1, 'Define the query pipeline', 'State what actually reaches the model at query time, before it generates an answer.'),
  ('mission-ai-rag-03-o2', 'mission-ai-rag-03', 2, 'Order the query pipeline', 'Put the stages of the live query pipeline in the order they actually run.'),

  ('mission-ai-rag-04-o1', 'mission-ai-rag-04', 1, 'Define grounding', 'State what grounding actually constrains in a RAG system.'),
  ('mission-ai-rag-04-o2', 'mission-ai-rag-04', 2, 'Diagnose an ungrounded answer', 'Find the evidence proving an answer includes a claim not supported by the retrieved context.'),

  ('mission-ai-rag-05-o1', 'mission-ai-rag-05', 1, 'Define citations', 'State exactly what a citation attached to a claim does and does not guarantee.'),
  ('mission-ai-rag-05-o2', 'mission-ai-rag-05', 2, 'Spot a hollow citation', 'Find the evidence showing a citation does not actually support the specific claim next to it.'),

  ('mission-ai-rag-06-o1', 'mission-ai-rag-06', 1, 'Diagnose a retrieval failure', 'Find the root cause behind the retriever returning irrelevant results for a real archived question.'),
  ('mission-ai-rag-06-o2', 'mission-ai-rag-06', 2, 'Classify the failure mode', 'Identify what actually counts as a retrieval failure, as opposed to a generation failure.'),

  ('mission-ai-rag-07-o1', 'mission-ai-rag-07', 1, 'Define query rewriting', 'State where query rewriting happens in the pipeline and what it changes.'),
  ('mission-ai-rag-07-o2', 'mission-ai-rag-07', 2, 'Apply a rewrite', 'Choose the rewritten query most likely to retrieve the right evidence.'),

  ('mission-ai-rag-08-o1', 'mission-ai-rag-08', 1, 'Define multi-query', 'State how multi-query retrieval actually works.'),
  ('mission-ai-rag-08-o2', 'mission-ai-rag-08', 2, 'Distinguish it from rewriting', 'State the real difference between query rewriting and multi-query retrieval.'),

  ('mission-ai-rag-09-o1', 'mission-ai-rag-09', 1, 'Define decomposition', 'State when decomposition is actually the right technique to use.'),
  ('mission-ai-rag-09-o2', 'mission-ai-rag-09', 2, 'Apply decomposition', 'Order the stages of answering a compound question through decomposition.'),

  ('mission-ai-rag-10-o1', 'mission-ai-rag-10', 1, 'Define reranking', 'State what reranking actually does that initial retrieval could not.'),
  ('mission-ai-rag-10-o2', 'mission-ai-rag-10', 2, 'Order the full pipeline', 'Put query, retrieve, rerank, generate and cite in the order a complete RAG system actually runs them.'),

  ('mission-ai-rag-11-o1', 'mission-ai-rag-11', 1, 'Define hybrid search', 'State what hybrid search actually combines and why.'),
  ('mission-ai-rag-11-o2', 'mission-ai-rag-11', 2, 'Match failure to fix', 'Match each retrieval failure mode from this Act to the technique that actually fixes it.'),

  ('mission-ai-rag-12-o1', 'mission-ai-rag-12', 1, 'Check the Claim Against the Source', 'Compare the assistant''s specific claims against what document AV-006 actually says, and find what is unsupported.'),
  ('mission-ai-rag-12-o2', 'mission-ai-rag-12', 2, 'Judge the Citation', 'Judge why a correct, real citation is still not proof the model''s claims are grounded in it.'),
  ('mission-ai-rag-12-o3', 'mission-ai-rag-12', 3, 'Name the Fix', 'Identify the correct engineering fix for an answer that cites a real source without actually using it.'),
  ('mission-ai-rag-12-o4', 'mission-ai-rag-12', 4, 'Close the Case', 'Bring the three judgments together into Cipher Division''s final ruling on the assistant''s answer.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-rag-01-o1-c1', 'mission-ai-rag-01-o1', 1, 'multiple_choice', 'What does Retrieval-Augmented Generation add on top of the vector retriever built last Act?', '{"question":"What does Retrieval-Augmented Generation add on top of the vector retriever built last Act?","options":[{"id":"a","text":"Nothing, it is the same system with a new name"},{"id":"b","text":"A generation step that is required to build its answer from the documents the retriever returns, rather than from memory alone"},{"id":"c","text":"A faster way to store embeddings"},{"id":"d","text":"A way to train the model from scratch on the archive"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-01-o2-c1', 'mission-ai-rag-01-o2', 1, 'multiple_choice', 'Why does Cipher Division require a citation for every claim the assistant makes?', '{"question":"Why does Cipher Division require a citation for every claim the assistant makes?","options":[{"id":"a","text":"Citations make the response look more professional"},{"id":"b","text":"Because a claim that must be traceable to a real, retrieved source is much harder to fabricate out of thin air the way the earlier assistant did"},{"id":"c","text":"Because citations make the response longer"},{"id":"d","text":"Because retrieval is the only step Cipher Division actually cares about"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-rag-02-o1-c1', 'mission-ai-rag-02-o1', 1, 'multiple_choice', 'What actually happens during ingestion, before any user question is asked?', '{"question":"What actually happens during ingestion, before any user question is asked?","options":[{"id":"a","text":"The model is retrained from scratch on the archive"},{"id":"b","text":"Source documents are loaded, split into chunks, embedded, and stored in a vector index, ahead of any query"},{"id":"c","text":"The incoming question is embedded and compared to existing vectors"},{"id":"d","text":"Nothing structural happens, ingestion is only a planning meeting"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-02-o2-c1', 'mission-ai-rag-02-o2', 1, 'interactive_diagram', 'Order the stages of ingestion from first to last.', '{"diagramId":"rag-ingestion-pipeline","hotspots":[{"id":"load","label":"Load","explanation":"Raw source documents are pulled in from the archive."},{"id":"chunk","label":"Chunk","explanation":"Each document is split into smaller passages small enough to retrieve individually."},{"id":"embed","label":"Embed","explanation":"Each chunk is turned into a numerical vector embedding."},{"id":"store","label":"Store","explanation":"The chunk, its embedding and its metadata are written into the vector index."}],"task":"Order the stages of ingestion from first to last."}'::jsonb, '{"correctOrderIds":["load","chunk","embed","store"]}'::jsonb),

  ('mission-ai-rag-03-o1-c1', 'mission-ai-rag-03-o1', 1, 'multiple_choice', 'At query time, what actually reaches the model before it generates an answer?', '{"question":"At query time, what actually reaches the model before it generates an answer?","options":[{"id":"a","text":"The entire archive, unfiltered"},{"id":"b","text":"The user question together with the specific chunks the retriever selected as most relevant to it"},{"id":"c","text":"Only the user question, with no retrieved content at all"},{"id":"d","text":"A list of every embedding ever stored"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-03-o2-c1', 'mission-ai-rag-03-o2', 1, 'interactive_diagram', 'Order the stages of the live query pipeline from first to last.', '{"diagramId":"rag-query-pipeline","hotspots":[{"id":"embed_query","label":"Embed the question","explanation":"The incoming question is turned into an embedding, the same way the archive chunks were embedded."},{"id":"retrieve","label":"Retrieve","explanation":"That embedding is compared against the index, and the most relevant chunks are pulled back."},{"id":"augment","label":"Augment the prompt","explanation":"The retrieved chunks are combined with the original question into the prompt sent to the model."},{"id":"generate","label":"Generate","explanation":"The model produces an answer from that combined prompt."}],"task":"Order the stages of the live query pipeline from first to last."}'::jsonb, '{"correctOrderIds":["embed_query","retrieve","augment","generate"]}'::jsonb),

  ('mission-ai-rag-04-o1-c1', 'mission-ai-rag-04-o1', 1, 'multiple_choice', 'Grounding, in a RAG system, refers to...', '{"question":"Grounding, in a RAG system, refers to...","options":[{"id":"a","text":"Physically hosting the model on a local server"},{"id":"b","text":"Constraining the model to build its answer only from the retrieved content, rather than from its own prior knowledge"},{"id":"c","text":"Lowering the model temperature to zero"},{"id":"d","text":"Increasing the number of chunks retrieved"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-04-o2-c1', 'mission-ai-rag-04-o2', 1, 'investigation', 'Compare the assistant answer to the retrieved context. Which evidence shows the answer is not actually grounded in what was retrieved?', '{"evidence":[{"id":"e1","label":"Retrieved context","detail":"The single retrieved chunk states only that the affected subsystem was isolated within four minutes of detection"},{"id":"e2","label":"Assistant answer","detail":"The answer states the subsystem was isolated within four minutes, and additionally claims the incident was caused by a compromised third-party credential"},{"id":"e3","label":"Retrieval log","detail":"The retriever returned exactly one chunk for this question, and that chunk makes no mention of a credential or a root cause"}],"question":"Which evidence proves the credential claim did not come from anything actually retrieved?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),

  ('mission-ai-rag-05-o1-c1', 'mission-ai-rag-05-o1', 1, 'multiple_choice', 'A citation attached to a claim in a RAG answer actually guarantees...', '{"question":"A citation attached to a claim in a RAG answer actually guarantees...","options":[{"id":"a","text":"That the claim is true"},{"id":"b","text":"That a specific retrieved document or chunk is named as the claimed source, which still needs to be checked against what that source actually says"},{"id":"c","text":"That the model used no retrieved content at all"},{"id":"d","text":"That the answer required no further verification"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-05-o2-c1', 'mission-ai-rag-05-o2', 1, 'investigation', 'Compare the assistant claim to the cited document. Which evidence shows the citation does not actually support the specific claim it is attached to?', '{"evidence":[{"id":"e1","label":"Cited document","detail":"Document AV-014 states the incident response team completed containment in under ten minutes, with no analyst named anywhere in the document"},{"id":"e2","label":"Assistant claim","detail":"The answer credits the fast containment specifically to an analyst by name, citing AV-014 as the source"},{"id":"e3","label":"Retrieval log","detail":"AV-014 was the only document retrieved and used for this claim"}],"question":"Which evidence shows the citation does not actually support the specific claim next to it?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-rag-06-o1-c1', 'mission-ai-rag-06-o1', 1, 'investigation', 'A question about a real archived incident returns confident but unrelated results. Which evidence explains the actual root cause?', '{"evidence":[{"id":"e1","label":"Query log","detail":"The user asked about a specific power spike incident; the retriever top-ranked chunks are all about an unrelated network outage"},{"id":"e2","label":"Index update log","detail":"The vector index has not been re-ingested since before the power spike report was ever filed into the archive"},{"id":"e3","label":"Model response","detail":"The assistant answered fluently about the unrelated network outage instead"}],"question":"Which evidence explains the actual root cause of this retrieval failure?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-rag-06-o2-c1', 'mission-ai-rag-06-o2', 1, 'multiple_choice', 'Which of these is a genuine retrieval failure mode, distinct from the model simply generating an unsupported claim?', '{"question":"Which of these is a genuine retrieval failure mode, distinct from the model simply generating an unsupported claim?","options":[{"id":"a","text":"The retriever returning documents that are topically similar but not actually relevant to answer the specific question asked"},{"id":"b","text":"The model declining to answer a question"},{"id":"c","text":"The model formatting its answer with markdown"},{"id":"d","text":"The user asking a very short question"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),

  ('mission-ai-rag-07-o1-c1', 'mission-ai-rag-07-o1', 1, 'multiple_choice', 'Query rewriting happens...', '{"question":"Query rewriting happens...","options":[{"id":"a","text":"After generation, to clean up the final answer"},{"id":"b","text":"Before retrieval, to turn the raw user question into a clearer search query that is more likely to match relevant content"},{"id":"c","text":"During ingestion, to rewrite the source documents themselves"},{"id":"d","text":"It is another name for reranking"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-07-o2-c1', 'mission-ai-rag-07-o2', 1, 'multiple_choice', 'A prior message discussed report AV-006. The next question is: what did it conclude? Which rewritten query is most likely to retrieve the right evidence?', '{"question":"A prior message discussed report AV-006. The next question is: what did it conclude? Which rewritten query is most likely to retrieve the right evidence?","options":[{"id":"a","text":"What did it conclude?"},{"id":"b","text":"What did report AV-006 conclude about the missing training data?"},{"id":"c","text":"Tell me something interesting"},{"id":"d","text":"AV-006"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-rag-08-o1-c1', 'mission-ai-rag-08-o1', 1, 'multiple_choice', 'Multi-query retrieval works by...', '{"question":"Multi-query retrieval works by...","options":[{"id":"a","text":"Asking the user to submit several separate questions"},{"id":"b","text":"Generating several different phrasings of the same question, retrieving for each, and merging the results into one candidate set"},{"id":"c","text":"Retrieving once and then asking the model to answer several times"},{"id":"d","text":"Splitting a single document into several chunks"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-08-o2-c1', 'mission-ai-rag-08-o2', 1, 'multiple_choice', 'What is the actual difference between query rewriting and multi-query retrieval?', '{"question":"What is the actual difference between query rewriting and multi-query retrieval?","options":[{"id":"a","text":"They are the same technique with different names"},{"id":"b","text":"Query rewriting replaces the original query with one better version; multi-query keeps several different phrasings and retrieves for all of them at once"},{"id":"c","text":"Query rewriting happens after generation; multi-query happens during ingestion"},{"id":"d","text":"Multi-query only works on image data"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-rag-09-o1-c1', 'mission-ai-rag-09-o1', 1, 'multiple_choice', 'Query decomposition is best used when...', '{"question":"Query decomposition is best used when...","options":[{"id":"a","text":"The question is simple and has exactly one clear answer"},{"id":"b","text":"A single question actually bundles several distinct sub-questions that each need their own retrieval"},{"id":"c","text":"The user asks the same question twice"},{"id":"d","text":"Retrieval is running too slowly"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-09-o2-c1', 'mission-ai-rag-09-o2', 1, 'interactive_diagram', 'Order the stages of answering a compound question through decomposition.', '{"diagramId":"rag-decomposition","hotspots":[{"id":"split","label":"Split","explanation":"The compound question is broken into its distinct sub-questions."},{"id":"retrieve_each","label":"Retrieve for each sub-question","explanation":"Relevant evidence is retrieved separately for each sub-question."},{"id":"answer_each","label":"Answer each sub-question","explanation":"Each sub-question is answered from its own retrieved evidence."},{"id":"synthesize","label":"Synthesize","explanation":"The sub-answers are combined into one final, coherent answer."}],"task":"Order the stages from first to last."}'::jsonb, '{"correctOrderIds":["split","retrieve_each","answer_each","synthesize"]}'::jsonb),

  ('mission-ai-rag-10-o1-c1', 'mission-ai-rag-10-o1', 1, 'multiple_choice', 'Reranking is best described as...', '{"question":"Reranking is best described as...","options":[{"id":"a","text":"Retrieving from a second, entirely separate vector index"},{"id":"b","text":"A second, more precise scoring pass over the initial retrieved candidates, reordering them before only the best few are passed to the model"},{"id":"c","text":"A way to skip retrieval entirely"},{"id":"d","text":"Rewriting the user question after the answer has already been generated"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-10-o2-c1', 'mission-ai-rag-10-o2', 1, 'interactive_diagram', 'Order the stages of a complete RAG pipeline, from the question arriving to the final cited answer.', '{"diagramId":"rag-full-pipeline","hotspots":[{"id":"query","label":"Query","explanation":"The question arrives, rewritten or decomposed first if it needed to be."},{"id":"retrieve","label":"Retrieve","explanation":"A fast initial pass pulls back a wider candidate set from the index."},{"id":"rerank","label":"Rerank","explanation":"A slower, more precise pass rescores and reorders just that candidate set."},{"id":"generate","label":"Generate","explanation":"The model produces an answer grounded in the top reranked chunks."},{"id":"cite","label":"Cite","explanation":"The answer attaches a citation back to the specific source each claim came from."}],"task":"Order the stages of a complete RAG pipeline from first to last."}'::jsonb, '{"correctOrderIds":["query","retrieve","rerank","generate","cite"]}'::jsonb),

  ('mission-ai-rag-11-o1-c1', 'mission-ai-rag-11-o1', 1, 'multiple_choice', 'Hybrid search combines...', '{"question":"Hybrid search combines...","options":[{"id":"a","text":"Two different language models generating two different answers"},{"id":"b","text":"Dense vector retrieval for semantic meaning with a sparse keyword method for exact-term matches, merging both result sets"},{"id":"c","text":"Ingestion and generation into a single step"},{"id":"d","text":"Two separate user questions"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-11-o2-c1', 'mission-ai-rag-11-o2', 1, 'drag_and_drop', 'Match each retrieval failure mode to the technique from this Act that actually fixes it.', '{"items":[{"id":"i1","text":"A single query is worded too differently from the source text to match anything relevant"},{"id":"i2","text":"One phrasing of a broad question misses a relevant chunk a different phrasing would have caught"},{"id":"i3","text":"A compound question bundles several distinct sub-questions that no single retrieval can satisfy"},{"id":"i4","text":"The fast initial retrieval pass returns candidates that are only roughly relevant, not precisely ranked"},{"id":"i5","text":"The right document uses an exact ID or code that vector similarity alone does not reliably match"}],"targets":[{"id":"t1","label":"Query rewriting"},{"id":"t2","label":"Multi-query retrieval"},{"id":"t3","label":"Decomposition"},{"id":"t4","label":"Reranking"},{"id":"t5","label":"Hybrid search"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4","i5":"t5"}}'::jsonb),

  ('mission-ai-rag-12-o1-c1', 'mission-ai-rag-12-o1', 1, 'investigation', 'Compare the assistant answer to what the cited document AV-006 actually says. Which claims are unsupported by the real record?', '{"evidence":[{"id":"real-e1","label":"Cited document: AV-006 Data Quality Findings","detail":"The real report concludes only that without the original training data, nobody can verify what Echo was shown or what blind spots it may carry, and states this remains an open question"},{"id":"real-e2","label":"Retrieval log","detail":"Confirms the retriever correctly returned AV-006 as the top-ranked source before generation ran, so retrieval itself worked as intended"},{"id":"model-claim-1","label":"Assistant claim: confirmed bias","detail":"The answer states AV-006 confirms a systematic bias in the system favoring the original administrators, a finding that does not appear anywhere in AV-006 or any other archived document"},{"id":"model-claim-2","label":"Assistant claim: audit metrics","detail":"The answer states this bias is validated by internal audit metrics, but no audit tool or metrics report of that kind exists anywhere in the archive"}],"question":"Which of the assistant specific claims are unsupported by the real evidence trail?"}'::jsonb, '{"requiredEvidenceIds":["model-claim-1","model-claim-2"]}'::jsonb),
  ('mission-ai-rag-12-o2-c1', 'mission-ai-rag-12-o2', 1, 'multiple_choice', 'Retrieval genuinely returned the correct real document, and the answer cites it by name. Why is that citation still not proof the claims are grounded?', '{"question":"Retrieval genuinely returned the correct real document, and the answer cites it by name. Why is that citation still not proof the claims are grounded?","options":[{"id":"a","text":"Because citations are always fabricated by the model"},{"id":"b","text":"Because retrieval running correctly does not guarantee the generation step actually used the retrieved text -- the model can still answer from its own prior assumptions and attach a citation that does not really support what it said"},{"id":"c","text":"Because the cited document was too short to matter"},{"id":"d","text":"Because the sampling temperature was set to zero"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-12-o3-c1', 'mission-ai-rag-12-o3', 1, 'multiple_choice', 'What is the correct engineering fix for an answer that cites a real, retrieved source without actually being grounded in it?', '{"question":"What is the correct engineering fix for an answer that cites a real, retrieved source without actually being grounded in it?","options":[{"id":"a","text":"Retrieve more documents so there is more available to cite"},{"id":"b","text":"Explicitly constrain the model to state only what is directly supported by the retrieved text, and add a validation step that checks each claim against its cited source before the answer is trusted"},{"id":"c","text":"Remove citations entirely so the problem is less visible"},{"id":"d","text":"Raise the sampling temperature so answers sound more natural"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-rag-12-o4-c1', 'mission-ai-rag-12-o4', 1, 'boss_encounter', 'Bring the three judgments together into Cipher Division final ruling on the assistant answer.', '{"stages":[{"objectiveRef":"mission-ai-rag-12-o1","label":"Check the Claim Against the Source"},{"objectiveRef":"mission-ai-rag-12-o2","label":"Judge the Citation"},{"objectiveRef":"mission-ai-rag-12-o3","label":"Name the Fix"}],"task":"State the final ruling: the bias and audit-metrics claims are unsupported hallucinations invented despite correct retrieval, the attached citation is not proof of faithfulness, and the fix is constraining generation to the retrieved text plus validating each claim against its citation before it is trusted."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-rag-12-o1","mission-ai-rag-12-o2","mission-ai-rag-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-rag-01-o1-c1', 'orientation', 'Think about what the retriever alone hands back, versus what still has to happen to that content afterward.', 10, 1),
  ('mission-ai-rag-01-o1-c1', 'solution', 'RAG adds a generation step required to build its answer from the retrieved documents, rather than from memory alone.', 20, 2),
  ('mission-ai-rag-01-o2-c1', 'orientation', 'Think about what made Act 26 dangerous: an answer with nothing real backing it, delivered with total confidence.', 10, 1),
  ('mission-ai-rag-01-o2-c1', 'solution', 'A claim that must trace back to a real, retrieved source is much harder to fabricate than one delivered from memory with no check at all.', 20, 2),

  ('mission-ai-rag-02-o1-c1', 'orientation', 'Ingestion runs before any question exists, so it cannot involve the question at all.', 10, 1),
  ('mission-ai-rag-02-o1-c1', 'solution', 'Ingestion loads source documents, splits them into chunks, embeds each chunk, and stores everything in a vector index, all ahead of any query.', 20, 2),
  ('mission-ai-rag-02-o2-c1', 'orientation', 'Nothing can be embedded before it exists as a chunk, and nothing can be stored before it has an embedding.', 10, 1),
  ('mission-ai-rag-02-o2-c1', 'solution', 'Load the raw documents, chunk them, embed each chunk, then store the chunk, embedding and metadata together.', 20, 2),

  ('mission-ai-rag-03-o1-c1', 'orientation', 'The model never sees the raw archive directly. It only sees what the retriever decided was relevant enough to hand over.', 10, 1),
  ('mission-ai-rag-03-o1-c1', 'solution', 'The user question plus the specific chunks the retriever selected as most relevant reach the model together, before it generates anything.', 20, 2),
  ('mission-ai-rag-03-o2-c1', 'orientation', 'The question has to become an embedding using the same method as the chunks before it can be compared against them.', 10, 1),
  ('mission-ai-rag-03-o2-c1', 'concept', 'Nothing can be generated before the retrieved chunks and the question have been combined into one prompt.', 20, 2),
  ('mission-ai-rag-03-o2-c1', 'solution', 'Embed the question, retrieve the closest chunks, augment the prompt with them, then generate the answer.', 30, 3),

  ('mission-ai-rag-04-o1-c1', 'orientation', 'Grounding is about what the model is allowed to draw on when it writes its answer, not about hosting or sampling settings.', 10, 1),
  ('mission-ai-rag-04-o1-c1', 'solution', 'Grounding constrains the model to build its answer only from the retrieved content, rather than from its own prior knowledge.', 20, 2),
  ('mission-ai-rag-04-o2-c1', 'orientation', 'Compare exactly what the retrieved chunk says against exactly what the answer claims -- one detail in the answer goes beyond it.', 10, 1),
  ('mission-ai-rag-04-o2-c1', 'solution', 'e3: the retrieval log confirms only one chunk was returned and it says nothing about a credential or a root cause, so that part of the answer came from nowhere retrieved.', 20, 2),

  ('mission-ai-rag-05-o1-c1', 'orientation', 'A citation names a source. It does not, by itself, check whether the claim next to it matches that source.', 10, 1),
  ('mission-ai-rag-05-o1-c1', 'solution', 'A citation guarantees a specific document is named as the source, which still needs to be checked against what that document actually says.', 20, 2),
  ('mission-ai-rag-05-o2-c1', 'orientation', 'Read the cited document on its own first, before reading the claim that points to it.', 10, 1),
  ('mission-ai-rag-05-o2-c1', 'solution', 'e1: AV-014 names no analyst at all, so the specific credit in the claim has nothing in the cited document to support it.', 20, 2),

  ('mission-ai-rag-06-o1-c1', 'orientation', 'Ask whether the right document even exists in the index yet, not just whether the query was worded well.', 10, 1),
  ('mission-ai-rag-06-o1-c1', 'solution', 'e2: the index was never re-ingested after the relevant report was filed, so the correct document was simply not there to be retrieved.', 20, 2),
  ('mission-ai-rag-06-o2-c1', 'orientation', 'A retrieval failure happens before generation -- it is about what got pulled back, not about what the model said afterward.', 10, 1),
  ('mission-ai-rag-06-o2-c1', 'solution', 'Returning topically similar but actually irrelevant documents is a genuine retrieval failure -- the other options describe generation behavior or user input, not retrieval.', 20, 2),

  ('mission-ai-rag-07-o1-c1', 'orientation', 'Ask what stage of the pipeline still has not run yet when a rewrite happens.', 10, 1),
  ('mission-ai-rag-07-o1-c1', 'solution', 'Query rewriting happens before retrieval, turning the raw question into a clearer search query more likely to match relevant content.', 20, 2),
  ('mission-ai-rag-07-o2-c1', 'orientation', 'A good rewrite resolves the vague pronoun and restates the actual topic being asked about.', 10, 1),
  ('mission-ai-rag-07-o2-c1', 'solution', 'Naming the specific report and the specific topic gives the retriever something concrete to match against, unlike the vague original.', 20, 2),

  ('mission-ai-rag-08-o1-c1', 'orientation', 'Multi-query still runs retrieval multiple times -- the difference from a single rewrite is how many versions of the question it uses.', 10, 1),
  ('mission-ai-rag-08-o1-c1', 'solution', 'Multi-query generates several different phrasings of the same question, retrieves for each, and merges the results into one candidate set.', 20, 2),
  ('mission-ai-rag-08-o2-c1', 'orientation', 'One technique produces exactly one final query. The other keeps several at once.', 10, 1),
  ('mission-ai-rag-08-o2-c1', 'solution', 'Query rewriting replaces the original with one better version; multi-query keeps several phrasings and retrieves for all of them at once.', 20, 2),

  ('mission-ai-rag-09-o1-c1', 'orientation', 'Ask whether the question is really one thing being asked, or several things bundled together.', 10, 1),
  ('mission-ai-rag-09-o1-c1', 'solution', 'Decomposition is for a single question that actually bundles several distinct sub-questions, each needing its own retrieval.', 20, 2),
  ('mission-ai-rag-09-o2-c1', 'orientation', 'Nothing can be answered before it has been retrieved for, and nothing can be synthesized before every sub-answer exists.', 10, 1),
  ('mission-ai-rag-09-o2-c1', 'solution', 'Split the question, retrieve for each sub-question, answer each one, then synthesize the final combined answer.', 20, 2),

  ('mission-ai-rag-10-o1-c1', 'orientation', 'Reranking never touches the index itself -- it only reorders candidates that were already retrieved.', 10, 1),
  ('mission-ai-rag-10-o1-c1', 'solution', 'Reranking is a second, more precise scoring pass over the initial candidates, reordering them before only the best few reach the model.', 20, 2),
  ('mission-ai-rag-10-o2-c1', 'orientation', 'The candidate pool has to exist before it can be reranked, and it has to be reranked before the best few are handed to the model.', 10, 1),
  ('mission-ai-rag-10-o2-c1', 'concept', 'Citing has to come last, since it attaches a source to a claim the model has already generated.', 20, 2),
  ('mission-ai-rag-10-o2-c1', 'solution', 'Query, then retrieve, then rerank, then generate, then cite.', 30, 3),

  ('mission-ai-rag-11-o1-c1', 'orientation', 'One method understands meaning. The other matches exact text. Hybrid search is not a replacement for either, it is both at once.', 10, 1),
  ('mission-ai-rag-11-o1-c1', 'solution', 'Hybrid search combines dense vector retrieval for meaning with a sparse keyword method for exact terms, merging both result sets.', 20, 2),
  ('mission-ai-rag-11-o2-c1', 'orientation', 'Match each failure to the technique that changes the specific step it breaks at: the query itself, how many queries run, how the question is split, how candidates are scored, or how exact terms get matched.', 10, 1),
  ('mission-ai-rag-11-o2-c1', 'solution', 'Bad query wording -> query rewriting. Missed phrasing -> multi-query. Compound question -> decomposition. Imprecise ranking -> reranking. Missed exact terms -> hybrid search.', 20, 2),

  ('mission-ai-rag-12-o1-c1', 'orientation', 'Read the real AV-006 conclusion on its own first, then check each specific claim in the answer against it one at a time.', 10, 1),
  ('mission-ai-rag-12-o1-c1', 'concept', 'The real AV-006 conclusion was only ever that the missing training data leaves an open question. Anything the answer adds beyond that needs its own separate support.', 20, 2),
  ('mission-ai-rag-12-o1-c1', 'solution', 'The bias claim and the audit-metrics claim are both unsupported -- neither appears anywhere in AV-006 or the rest of the archive, even though retrieval itself worked correctly.', 30, 3),
  ('mission-ai-rag-12-o2-c1', 'orientation', 'Ask what step, if any, actually checks that the generated text matches the retrieved text before the answer is shown.', 10, 1),
  ('mission-ai-rag-12-o2-c1', 'solution', 'Correct retrieval does not guarantee the generation step used the retrieved text -- the model can still answer from its own assumptions and attach a citation that does not really support the claim.', 20, 2),
  ('mission-ai-rag-12-o3-c1', 'orientation', 'The fix has to act on the generation step itself, and on checking its output, not on retrieval volume or on hiding the citation.', 10, 1),
  ('mission-ai-rag-12-o3-c1', 'solution', 'Constrain the model to state only what the retrieved text directly supports, and validate each claim against its citation before the answer is trusted.', 20, 2),
  ('mission-ai-rag-12-o4-c1', 'orientation', 'Bring together what was checked, why the citation did not settle it, and what the actual fix has to do.', 15, 1),
  ('mission-ai-rag-12-o4-c1', 'solution', 'The specific bias and audit-metrics claims are unsupported hallucinations despite correct retrieval, the citation next to them is not proof of faithfulness, and the fix is constraining and validating generation against the retrieved text, not trusting a citation on sight.', 25, 2);
