-- AI/ML pathway ("Cipher Division") Act 14 -- "Learning by Gradient" content.
-- Arc III ("Neural Systems", Acts 13-18). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns -> operations
-- -> missions -> dialogue -> objectives -> challenges -> hints pattern as
-- every other pathway. The world-ai-learning-by-gradient row (act-ai-3)
-- already exists and already carries this Act's real narrative fields --
-- this file only adds the campaign/operations/missions/dialogue/objectives/
-- challenges/hints under it.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-learning-by-gradient', 'world-ai-learning-by-gradient', 'learning-by-gradient', '14A - Learning by Gradient', 'How a network actually learns: loss, backpropagation and the chain rule, gradient descent and the variants people actually use, and the specific ways training can quietly fail -- aimed at properly re-testing a slice of Echo''s gradients that never settled the way Act 3 expected.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-learning-by-gradient-1', 'campaign-ai-learning-by-gradient', 'the-error-signal', 'The Error Signal', 'Loss, backpropagation, the chain rule, gradients, gradient descent and SGD -- how an error turns into a specific instruction for every parameter.', 1),
  ('operation-ai-learning-by-gradient-2', 'campaign-ai-learning-by-gradient', 'descent-and-its-failures', 'Descent and Its Failures', 'Mini-batches, momentum, Adam, learning rates and the specific ways optimization fails -- tested against Cipher Division''s own toy network and against Echo.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-learning-by-gradient-01', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'loss', 'Loss', 'The hand-built network can compute, but it cannot yet learn -- and the reason starts with the one number that tells any network whether it was wrong.', 'beginner', ARRAY['maya','elena','byte'], null, null, '{"type":"simulation","simulationId":"loss-sim"}'::jsonb, '{"xp":250,"credits":55}'::jsonb, false, 1),
  ('mission-ai-learning-by-gradient-02', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'backpropagation', 'Backpropagation', 'Loss produces one number for the whole network. Backpropagation turns that number into a separate, specific instruction for every parameter in it.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"backpropagation-sim"}'::jsonb, '{"xp":260,"credits":60}'::jsonb, false, 2),
  ('mission-ai-learning-by-gradient-03', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'chain-rule', 'Chain Rule', 'Backpropagation is not new math -- it is one old calculus rule, the chain rule, applied once per layer, all the way back through the network.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"chain-rule-sim"}'::jsonb, '{"xp":260,"credits":60}'::jsonb, false, 3),
  ('mission-ai-learning-by-gradient-04', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'gradients', 'Gradients', 'Chain the local slopes together and what falls out for every parameter is its gradient -- the same object Act 3 taught, now attached to something real: how wrong the network currently is.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"gradients-training-sim"}'::jsonb, '{"xp":270,"credits":60}'::jsonb, false, 4),
  ('mission-ai-learning-by-gradient-05', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'gradient-descent', 'Gradient Descent', 'A gradient points toward more loss. Gradient descent is the obvious next move: step the opposite way, a little at a time.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"gradient-descent-sim"}'::jsonb, '{"xp":270,"credits":65}'::jsonb, false, 5),
  ('mission-ai-learning-by-gradient-06', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-1', 'sgd', 'SGD', 'Computing the gradient over an entire dataset, every single step, is too slow for anything real. Stochastic Gradient Descent estimates it from one example at a time instead.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"sgd-sim"}'::jsonb, '{"xp":280,"credits":65}'::jsonb, false, 6),
  ('mission-ai-learning-by-gradient-07', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'mini-batches', 'Mini-Batches', 'Full-batch and single-example SGD are two extremes almost nobody actually trains on. The real default sits in the middle: small, randomly sampled batches.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"mini-batches-sim"}'::jsonb, '{"xp":280,"credits":65}'::jsonb, false, 7),
  ('mission-ai-learning-by-gradient-08', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'momentum', 'Momentum', 'Plain gradient descent reacts only to the current gradient and forgets everything before it. Momentum gives updates memory, and lets consistent directions build up speed.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"momentum-sim"}'::jsonb, '{"xp":290,"credits":70}'::jsonb, false, 8),
  ('mission-ai-learning-by-gradient-09', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'adam', 'Adam', 'Momentum tracks one running average. Adam tracks two, scaling every parameter''s step individually -- and it is the optimizer most people reach for first.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"adam-sim"}'::jsonb, '{"xp":290,"credits":70}'::jsonb, false, 9),
  ('mission-ai-learning-by-gradient-10', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'learning-rates', 'Learning Rates', 'Every optimizer still has one dial none of them remove: the learning rate. Get it wrong and training breaks in two completely different directions.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"learning-rates-sim"}'::jsonb, '{"xp":300,"credits":70}'::jsonb, false, 10),
  ('mission-ai-learning-by-gradient-11', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'optimization-failures', 'Optimization Failures', 'Loss, gradients, and every optimizer variant still fail in a handful of specific, recognizable ways -- and recognizing the signature matters more than knowing the name.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"optimization-failures-sim"}'::jsonb, '{"xp":300,"credits":75}'::jsonb, false, 11),
  ('mission-ai-learning-by-gradient-12', 'world-ai-learning-by-gradient', 'campaign-ai-learning-by-gradient', 'operation-ai-learning-by-gradient-2', 'the-vanishing-path', 'The Vanishing Path', 'Cipher Division''s own toy network, pushed until it fails the textbook way, set directly against the Act 3 evidence from Echo -- to find out if the two failures are actually the same thing.', 'boss', ARRAY['maya','elena','byte'], '{"requiredMissionIds":["mission-ai-learning-by-gradient-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"the-vanishing-path-boss-sim"}'::jsonb, '{"xp":780,"credits":170,"badgeIds":["the-vanishing-path"],"skillXp":{"optimization":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-learning-by-gradient-01', 1, 'maya', 'The hand-built network can compute now -- forward pass works, Elena confirmed it end to end. But it cannot learn anything yet. That is where we are.'),
  ('mission-ai-learning-by-gradient-01', 2, 'elena', 'Today has two goals, not one. First, learn how a network actually trains: loss, backpropagation, the chain rule, gradient descent and the variants people actually use. Second, once that vocabulary is real, I want to properly re-test something Byte flagged back in Act 3.'),
  ('mission-ai-learning-by-gradient-01', 3, 'byte', 'A small slice of Echo''s parameters, three values, sampled at three checkpoints. The gradients never settled the way a finished, normally-trained model''s should -- they reversed direction, held their magnitude, refused to shrink toward zero. We noted it. We never had the tools to properly explain it.'),
  ('mission-ai-learning-by-gradient-01', 4, 'elena', 'We still do not, not yet. But by the end of this Act we will actually understand what makes gradients behave one way instead of another -- which means we can finally test that finding properly instead of just staring at it. Start simple: a loss function.'),
  ('mission-ai-learning-by-gradient-01', 5, 'elena', 'A loss function takes what the network predicted and what it should have predicted, and turns the gap between them into a single number. No loss, no way to tell the network it was wrong, and no way to point it toward better.'),

  ('mission-ai-learning-by-gradient-02', 1, 'elena', 'Loss gives us one number for the whole network. Backpropagation is the algorithm that turns that one number into a separate instruction for every single parameter: how much, and in which direction, each one should change.'),
  ('mission-ai-learning-by-gradient-02', 2, 'byte', 'It runs backward on purpose. Start at the output, where the loss was computed, and work toward the input, layer by layer, because each layer''s share of the blame depends on everything that came after it.'),
  ('mission-ai-learning-by-gradient-02', 3, 'elena', 'The output layer is easy -- its error is right there. Every layer before that needs its error passed back to it from the layer in front, which is exactly why the order matters as much as the arithmetic.'),

  ('mission-ai-learning-by-gradient-03', 1, 'elena', 'Backpropagation is not a new piece of math. It is one very old rule, applied over and over: the chain rule, for taking the derivative of a function built out of other functions.'),
  ('mission-ai-learning-by-gradient-03', 2, 'elena', 'If y depends on u, and u depends on x, the chain rule says the derivative of y with respect to x is the derivative of y with respect to u, times the derivative of u with respect to x. Multiply the local slopes together.'),
  ('mission-ai-learning-by-gradient-03', 3, 'elena', 'A network is exactly that kind of nested function -- a prediction is a function of the last layer, which is a function of the layer before it, all the way back to the input. Backpropagation is the chain rule, applied once per layer.'),

  ('mission-ai-learning-by-gradient-04', 1, 'elena', 'Chain the local slopes together, layer by layer, all the way through the network, and what you get for each parameter is its gradient with respect to the loss -- the same object Act 3 taught, now attached to something real: how wrong the network currently is.'),
  ('mission-ai-learning-by-gradient-04', 2, 'byte', 'The gradient of the loss with respect to one parameter answers a specific question: if that parameter increased slightly, would the loss go up or down, and by how much?'),
  ('mission-ai-learning-by-gradient-04', 3, 'elena', 'That is the whole reason this matters for Echo. A gradient that stops changing sign and shrinks toward zero is a network settling into an answer. A gradient that keeps flipping direction is a network that has not settled on anything -- which is exactly the shape of what Byte found back in Act 3.'),

  ('mission-ai-learning-by-gradient-05', 1, 'elena', 'The gradient points toward the direction that increases the loss fastest. Gradient descent is the obvious move once you know that: step the opposite way.'),
  ('mission-ai-learning-by-gradient-05', 2, 'elena', 'The update rule is one line: new parameter equals old parameter, minus a learning rate, times the gradient. The learning rate controls how big a step to take; the gradient controls which direction.'),
  ('mission-ai-learning-by-gradient-05', 3, 'elena', 'Do that for every parameter, every step, and the loss should fall a little each time -- assuming the step size is sane, which will turn out to be its own entire problem later in this Act.'),

  ('mission-ai-learning-by-gradient-06', 1, 'elena', 'Gradient descent as we just described it assumes you compute the gradient using the entire training set, every single step. For anything real, that is far too slow to run once, let alone thousands of times.'),
  ('mission-ai-learning-by-gradient-06', 2, 'elena', 'Stochastic Gradient Descent estimates the gradient from a single random training example at a time instead of the whole dataset. Each step is cheap and noisy, but noisy in a direction that is still, on average, correct.'),
  ('mission-ai-learning-by-gradient-06', 3, 'elena', 'The trade is real: full-batch gradient descent takes smooth, accurate steps but painfully slowly. SGD takes fast, rough steps that jitter around but cover far more ground in the same amount of time.'),

  ('mission-ai-learning-by-gradient-07', 1, 'elena', 'Full-batch and single-example SGD are two extremes. Almost nothing trains on either one in practice. The actual default is the middle ground: mini-batches.'),
  ('mission-ai-learning-by-gradient-07', 2, 'elena', 'A mini-batch is a small, randomly sampled group of examples -- often somewhere between 32 and a few hundred -- averaged together to estimate the gradient for one update step.'),
  ('mission-ai-learning-by-gradient-07', 3, 'byte', 'It buys back some of what single-example SGD gives up. The gradient estimate is smoother than one example alone, but you are still not paying the full cost of the entire dataset every step.'),

  ('mission-ai-learning-by-gradient-08', 1, 'elena', 'Plain gradient descent, batch or mini-batch, reacts only to the current gradient and forgets everything about the steps that came before it. Momentum fixes that by giving updates memory.'),
  ('mission-ai-learning-by-gradient-08', 2, 'elena', 'Instead of stepping purely by the current gradient, momentum keeps a running velocity -- a weighted average of past gradients -- and steps by that instead. Consistent directions build up speed; directions that keep flipping cancel out.'),
  ('mission-ai-learning-by-gradient-08', 3, 'elena', 'The practical effect is real: momentum smooths out the jitter mini-batches introduce, and it can carry an update straight through a shallow flat patch that would stall plain gradient descent completely.'),

  ('mission-ai-learning-by-gradient-09', 1, 'elena', 'Momentum tracks one thing: an average direction. Adam tracks two -- that same running average of gradients, and a running average of how large each parameter''s recent gradients have been, so it can scale each parameter''s step individually.'),
  ('mission-ai-learning-by-gradient-09', 2, 'elena', 'The practical result is a per-parameter learning rate. Parameters with small, consistent gradients get relatively bigger steps. Parameters with large, noisy gradients get their steps automatically shrunk.'),
  ('mission-ai-learning-by-gradient-09', 3, 'elena', 'It is not magic, and it is not always the best choice, but it is the default most people reach for first precisely because it needs the least manual tuning to get something reasonable running.'),

  ('mission-ai-learning-by-gradient-10', 1, 'elena', 'Every optimizer we just covered still has one dial none of them remove: the learning rate. It controls how large a step every update takes, and getting it wrong breaks training in two completely different ways.'),
  ('mission-ai-learning-by-gradient-10', 2, 'byte', 'Too small, and training crawls -- the loss creeps down so slowly it looks stalled, even though every step is technically correct.'),
  ('mission-ai-learning-by-gradient-10', 3, 'elena', 'Too large, and updates overshoot the direction they were supposed to improve, sometimes so badly the loss gets worse step after step instead of better. There is a workable range in between, and finding it is half the practical skill of training anything.'),

  ('mission-ai-learning-by-gradient-11', 1, 'elena', 'Put loss, gradients, and every optimizer variant together and training still fails in a handful of specific, recognizable ways. Knowing their signatures matters more than knowing their names.'),
  ('mission-ai-learning-by-gradient-11', 2, 'byte', 'Vanishing gradients: the gradient shrinks toward zero as it propagates backward through many layers, so the earliest layers barely update at all, and training stalls even though the loss has not actually bottomed out.'),
  ('mission-ai-learning-by-gradient-11', 3, 'elena', 'Exploding gradients are the opposite failure -- gradients grow instead of shrink, and updates blow parameters up to huge or invalid values. A network can also get stuck on a plateau or a saddle point, where the gradient is genuinely near zero without the loss actually being good.'),

  ('mission-ai-learning-by-gradient-12', 1, 'maya', 'Two things on the table today: our own toy network, pushed until it breaks in the textbook way, and the three checkpoints Byte pulled from Echo back in Act 3. Line them up.'),
  ('mission-ai-learning-by-gradient-12', 2, 'byte', 'I built the toy network to fail on purpose -- eight layers deep, sigmoid activations, weights initialized far too small. If backpropagation and the chain rule work the way we just learned, this should be a clean demonstration.'),
  ('mission-ai-learning-by-gradient-12', 3, 'elena', 'Watch the gradient magnitude at each layer, not just the loss. A healthy network''s gradients stay a comparable size from the last layer to the first. A vanishing network''s gradients shrink, layer by layer, until the earliest layers barely move at all.'),
  ('mission-ai-learning-by-gradient-12', 4, 'byte', 'Confirmed, on both counts. The toy network''s gradients shrink toward zero exactly the way the textbook predicts, and Echo''s three checkpoints do the opposite -- reversing direction, holding their magnitude, never shrinking toward anything. The team''s own toy network reproduces a textbook vanishing-gradient failure under the right bad conditions -- and it looks nothing like what Echo''s gradients actually did. Whatever kept Echo''s gradients moving, it was not this.'),
  ('mission-ai-learning-by-gradient-12', 5, 'maya', 'That is not a disappointment. That is one explanation, ruled out with actual rigor instead of a guess. Ruling out the ordinary explanation does not make the real one obvious. Before chasing Echo''s gradients any further, Cipher Division needs to actually be able to train a stable deep network at all.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-learning-by-gradient-01-o1', 'mission-ai-learning-by-gradient-01', 1, 'Define loss', 'Choose the accurate definition of a loss function.'),
  ('mission-ai-learning-by-gradient-01-o2', 'mission-ai-learning-by-gradient-01', 2, 'Compute a loss value', 'Compute a squared-error loss by hand.'),

  ('mission-ai-learning-by-gradient-02-o1', 'mission-ai-learning-by-gradient-02', 1, 'Define backpropagation', 'Choose the accurate definition of backpropagation.'),
  ('mission-ai-learning-by-gradient-02-o2', 'mission-ai-learning-by-gradient-02', 2, 'Order the pass', 'Order the stages of one backpropagation pass.'),

  ('mission-ai-learning-by-gradient-03-o1', 'mission-ai-learning-by-gradient-03', 1, 'Apply the chain rule', 'Apply the chain rule to compute a derivative of a composed function.'),
  ('mission-ai-learning-by-gradient-03-o2', 'mission-ai-learning-by-gradient-03', 2, 'Match the local pieces', 'Match each part of a chain-rule expression to what it represents.'),

  ('mission-ai-learning-by-gradient-04-o1', 'mission-ai-learning-by-gradient-04', 1, 'Read a gradient''s sign', 'Judge what a gradient''s sign means for the loss.'),
  ('mission-ai-learning-by-gradient-04-o2', 'mission-ai-learning-by-gradient-04', 2, 'Judge what a settled gradient looks like', 'Judge what a shrinking, sign-stable gradient indicates about training.'),

  ('mission-ai-learning-by-gradient-05-o1', 'mission-ai-learning-by-gradient-05', 1, 'Order one update', 'Order the stages of a single gradient descent update.'),
  ('mission-ai-learning-by-gradient-05-o2', 'mission-ai-learning-by-gradient-05', 2, 'Apply the update rule', 'Apply the gradient descent update rule by hand.'),

  ('mission-ai-learning-by-gradient-06-o1', 'mission-ai-learning-by-gradient-06', 1, 'Define SGD', 'Choose the accurate definition of Stochastic Gradient Descent.'),
  ('mission-ai-learning-by-gradient-06-o2', 'mission-ai-learning-by-gradient-06', 2, 'Sort the trade-offs', 'Sort properties into full-batch gradient descent or SGD.'),

  ('mission-ai-learning-by-gradient-07-o1', 'mission-ai-learning-by-gradient-07', 1, 'Define a mini-batch', 'Choose the accurate definition of a mini-batch update.'),
  ('mission-ai-learning-by-gradient-07-o2', 'mission-ai-learning-by-gradient-07', 2, 'Judge batch size trade-offs', 'Find the evidence describing the practical mini-batch compromise.'),

  ('mission-ai-learning-by-gradient-08-o1', 'mission-ai-learning-by-gradient-08', 1, 'Define momentum', 'Choose the accurate definition of momentum.'),
  ('mission-ai-learning-by-gradient-08-o2', 'mission-ai-learning-by-gradient-08', 2, 'Match the behavior', 'Match gradient behavior to what momentum does with it.'),

  ('mission-ai-learning-by-gradient-09-o1', 'mission-ai-learning-by-gradient-09', 1, 'Define Adam', 'Choose the accurate definition of what Adam adds over plain momentum.'),
  ('mission-ai-learning-by-gradient-09-o2', 'mission-ai-learning-by-gradient-09', 2, 'Match optimizer to characteristic', 'Match SGD, momentum and Adam to their defining behavior.'),

  ('mission-ai-learning-by-gradient-10-o1', 'mission-ai-learning-by-gradient-10', 1, 'Define what it controls', 'State what a learning rate actually controls.'),
  ('mission-ai-learning-by-gradient-10-o2', 'mission-ai-learning-by-gradient-10', 2, 'Diagnose from a loss curve', 'Find the evidence explaining an unstable, worsening loss curve.'),

  ('mission-ai-learning-by-gradient-11-o1', 'mission-ai-learning-by-gradient-11', 1, 'Match symptom to failure', 'Match each training symptom to its optimization failure mode.'),
  ('mission-ai-learning-by-gradient-11-o2', 'mission-ai-learning-by-gradient-11', 2, 'Diagnose likely causes', 'Find the setup most likely to produce vanishing gradients specifically.'),

  ('mission-ai-learning-by-gradient-12-o1', 'mission-ai-learning-by-gradient-12', 1, 'Diagnose the vanishing signature', 'Diagnose the toy network''s failure from its own training evidence.'),
  ('mission-ai-learning-by-gradient-12-o2', 'mission-ai-learning-by-gradient-12', 2, 'Compare against Echo', 'Compare the toy network''s signature against the Act 3 evidence from Echo''s gradients.'),
  ('mission-ai-learning-by-gradient-12-o3', 'mission-ai-learning-by-gradient-12', 3, 'Judge the real fix', 'Judge what would actually fix the toy network''s vanishing-gradient problem.'),
  ('mission-ai-learning-by-gradient-12-o4', 'mission-ai-learning-by-gradient-12', 4, 'State the finding', 'Having diagnosed the toy network, compared it to Echo, and judged the fix, state what Cipher Division actually found.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-learning-by-gradient-01-o1-c1', 'mission-ai-learning-by-gradient-01-o1', 1, 'multiple_choice', 'A loss function is best described as...', '{"question":"A loss function is best described as...","options":[{"id":"a","text":"A count of how many layers a network has"},{"id":"b","text":"A single number measuring how far a prediction is from the true target, computed after each forward pass"},{"id":"c","text":"The learning rate used to update parameters"},{"id":"d","text":"The total size of the training dataset"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-01-o2-c1', 'mission-ai-learning-by-gradient-01-o2', 1, 'multiple_choice', 'A model predicts 7.0 for an example whose true value is 5.0. Using squared error, (predicted minus true) squared, what is the loss?', '{"question":"A model predicts 7.0 for an example whose true value is 5.0. Using squared error, (predicted minus true) squared, what is the loss?","options":[{"id":"a","text":"2"},{"id":"b","text":"4"},{"id":"c","text":"-4"},{"id":"d","text":"12"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-learning-by-gradient-02-o1-c1', 'mission-ai-learning-by-gradient-02-o1', 1, 'multiple_choice', 'Backpropagation is best described as...', '{"question":"Backpropagation is best described as...","options":[{"id":"a","text":"A way to randomly initialize a network''s weights"},{"id":"b","text":"The algorithm that computes how much each parameter contributed to the loss, by propagating the error backward through the network"},{"id":"c","text":"A method for collecting more training data"},{"id":"d","text":"A type of loss function"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-02-o2-c1', 'mission-ai-learning-by-gradient-02-o2', 1, 'interactive_diagram', 'Order the stages of one backpropagation pass.', '{"diagramId":"backprop-pass","hotspots":[{"id":"h1","label":"Run a forward pass and get the network''s prediction","explanation":"Backpropagation always starts from an actual prediction -- there is nothing to correct yet without one."},{"id":"h2","label":"Compute the loss by comparing the prediction to the true target","explanation":"The single number backpropagation will distribute backward."},{"id":"h3","label":"Compute the output layer''s share of the error","explanation":"The layer closest to the loss gets its gradient first, since it is the most direct."},{"id":"h4","label":"Propagate that error backward, layer by layer, computing each layer''s gradient","explanation":"Each earlier layer''s gradient depends on everything already computed in the layers after it."}],"task":"Order the stages of one backpropagation pass from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),

  ('mission-ai-learning-by-gradient-03-o1-c1', 'mission-ai-learning-by-gradient-03-o1', 1, 'multiple_choice', 'Let y = u^2 where u = 2x. Using the chain rule (dy/du times du/dx), what is dy/dx when x = 3?', '{"question":"Let y = u^2 where u = 2x. Using the chain rule (dy/du times du/dx), what is dy/dx when x = 3?","options":[{"id":"a","text":"6"},{"id":"b","text":"12"},{"id":"c","text":"24"},{"id":"d","text":"48"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-ai-learning-by-gradient-03-o2-c1', 'mission-ai-learning-by-gradient-03-o2', 1, 'drag_and_drop', 'Match each piece of a two-step chain-rule expression to what it represents.', '{"items":[{"id":"i1","text":"dy/du"},{"id":"i2","text":"du/dx"},{"id":"i3","text":"dy/du times du/dx"}],"targets":[{"id":"t1","label":"The outer function''s local slope"},{"id":"t2","label":"The inner function''s local slope"},{"id":"t3","label":"The full chain-rule derivative, dy/dx"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-learning-by-gradient-04-o1-c1', 'mission-ai-learning-by-gradient-04-o1', 1, 'multiple_choice', 'The gradient of the loss with respect to a parameter is positive. What does that mean for the loss if that parameter is increased slightly?', '{"question":"The gradient of the loss with respect to a parameter is positive. What does that mean for the loss if that parameter is increased slightly?","options":[{"id":"a","text":"The loss would increase"},{"id":"b","text":"The loss would decrease"},{"id":"c","text":"The loss is unaffected"},{"id":"d","text":"The parameter is already optimal"}]}'::jsonb, '{"correctOptionId":"a"}'::jsonb),
  ('mission-ai-learning-by-gradient-04-o2-c1', 'mission-ai-learning-by-gradient-04-o2', 1, 'multiple_choice', 'Across training, a well-behaved parameter''s gradient shrinks toward zero and stops changing sign. What does that indicate?', '{"question":"Across training, a well-behaved parameter''s gradient shrinks toward zero and stops changing sign. What does that indicate?","options":[{"id":"a","text":"The network is diverging"},{"id":"b","text":"The network is approaching a point where the loss stops improving in that direction -- it is settling"},{"id":"c","text":"The parameter has been deleted"},{"id":"d","text":"Training has not started yet"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-learning-by-gradient-05-o1-c1', 'mission-ai-learning-by-gradient-05-o1', 1, 'interactive_diagram', 'Order the stages of one gradient descent update.', '{"diagramId":"gradient-descent-step","hotspots":[{"id":"h1","label":"Run a forward pass and compute the loss","explanation":"You need a current loss before you know how to improve it."},{"id":"h2","label":"Run backpropagation to compute the gradient of the loss with respect to each parameter","explanation":"The gradient tells you the direction that increases the loss."},{"id":"h3","label":"Multiply each gradient by the learning rate","explanation":"This scales the step size for each parameter''s update."},{"id":"h4","label":"Subtract that scaled value from each parameter","explanation":"Subtracting, not adding, moves the parameter opposite the gradient -- toward less loss."}],"task":"Order the stages of one gradient descent update from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4"]}'::jsonb),
  ('mission-ai-learning-by-gradient-05-o2-c1', 'mission-ai-learning-by-gradient-05-o2', 1, 'multiple_choice', 'A parameter is currently 0.50, its gradient is 0.20, and the learning rate is 0.1. What is the parameter''s new value after one gradient descent update?', '{"question":"A parameter is currently 0.50, its gradient is 0.20, and the learning rate is 0.1. What is the parameter''s new value after one gradient descent update?","options":[{"id":"a","text":"0.52"},{"id":"b","text":"0.48"},{"id":"c","text":"0.70"},{"id":"d","text":"0.30"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-learning-by-gradient-06-o1-c1', 'mission-ai-learning-by-gradient-06-o1', 1, 'multiple_choice', 'Stochastic Gradient Descent is best described as...', '{"question":"Stochastic Gradient Descent is best described as...","options":[{"id":"a","text":"Gradient descent that never updates parameters"},{"id":"b","text":"Estimating the gradient using a single randomly chosen training example at each step, instead of the full dataset"},{"id":"c","text":"A way to compute loss without labels"},{"id":"d","text":"Gradient descent with the learning rate fixed at zero"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-06-o2-c1', 'mission-ai-learning-by-gradient-06-o2', 1, 'drag_and_drop', 'Sort each property into full-batch gradient descent or stochastic gradient descent.', '{"items":[{"id":"i1","text":"Each step uses the entire training set"},{"id":"i2","text":"Each step is cheap and can run very fast"},{"id":"i3","text":"Gradient estimates are smooth and accurate"},{"id":"i4","text":"Gradient estimates are noisy but still useful on average"}],"targets":[{"id":"t1","label":"Full-batch gradient descent"},{"id":"t2","label":"Stochastic gradient descent"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-learning-by-gradient-07-o1-c1', 'mission-ai-learning-by-gradient-07-o1', 1, 'multiple_choice', 'A mini-batch update computes the gradient using...', '{"question":"A mini-batch update computes the gradient using...","options":[{"id":"a","text":"Exactly one training example"},{"id":"b","text":"The entire training dataset"},{"id":"c","text":"A small, randomly sampled subset of the training data, averaged together"},{"id":"d","text":"No training data, only the previous gradient"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),
  ('mission-ai-learning-by-gradient-07-o2-c1', 'mission-ai-learning-by-gradient-07-o2', 1, 'investigation', 'Which run shows the practical mini-batch compromise Cipher Division would actually want to train with day to day?', '{"evidence":[{"id":"e1","label":"Batch size 1 (pure SGD) run","detail":"Loss curve is extremely jittery step to step, though it trends downward over time"},{"id":"e2","label":"Batch size 4096 run","detail":"Loss curve is very smooth, but each step takes far longer and memory usage is near the hardware limit"},{"id":"e3","label":"Batch size 64 run","detail":"Loss curve is reasonably smooth, each step is fast, and memory usage stays modest"}],"question":"Which run shows the practical mini-batch compromise Cipher Division would actually want to train with day to day?"}'::jsonb, '{"requiredEvidenceIds":["e3"]}'::jsonb),

  ('mission-ai-learning-by-gradient-08-o1-c1', 'mission-ai-learning-by-gradient-08-o1', 1, 'multiple_choice', 'Momentum in gradient-based optimization works by...', '{"question":"Momentum in gradient-based optimization works by...","options":[{"id":"a","text":"Ignoring all past gradients and using only the current one, unchanged"},{"id":"b","text":"Accumulating a running average of past gradients into a velocity term, and stepping using that velocity instead of the raw current gradient"},{"id":"c","text":"Randomly resetting parameters every few steps"},{"id":"d","text":"Increasing the learning rate to infinity"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-08-o2-c1', 'mission-ai-learning-by-gradient-08-o2', 1, 'drag_and_drop', 'Match each gradient pattern to what momentum does with it.', '{"items":[{"id":"i1","text":"Gradient keeps pointing the same direction across several steps"},{"id":"i2","text":"Gradient flips direction step to step, back and forth"}],"targets":[{"id":"t1","label":"Momentum builds up speed"},{"id":"t2","label":"Momentum''s velocity partially cancels out, damping the oscillation"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2"}}'::jsonb),

  ('mission-ai-learning-by-gradient-09-o1-c1', 'mission-ai-learning-by-gradient-09-o1', 1, 'multiple_choice', 'Adam improves on plain momentum by...', '{"question":"Adam improves on plain momentum by...","options":[{"id":"a","text":"Removing the learning rate entirely"},{"id":"b","text":"Also tracking the recent magnitude of each parameter''s gradients, and using that to scale each parameter''s step individually"},{"id":"c","text":"Using only the sign of the gradient, never its size"},{"id":"d","text":"Training exclusively on a single example per step"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-09-o2-c1', 'mission-ai-learning-by-gradient-09-o2', 1, 'drag_and_drop', 'Match each optimizer to its defining behavior.', '{"items":[{"id":"i1","text":"Uses the raw current gradient only, no memory of past steps"},{"id":"i2","text":"Accumulates a running average direction, but the same learning rate for every parameter"},{"id":"i3","text":"Adapts the step size per parameter based on recent gradient magnitude, on top of a running average direction"}],"targets":[{"id":"t1","label":"Plain SGD"},{"id":"t2","label":"Momentum"},{"id":"t3","label":"Adam"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),

  ('mission-ai-learning-by-gradient-10-o1-c1', 'mission-ai-learning-by-gradient-10-o1', 1, 'multiple_choice', 'A learning rate controls...', '{"question":"A learning rate controls...","options":[{"id":"a","text":"How many layers the network has"},{"id":"b","text":"The size of the step taken during each parameter update"},{"id":"c","text":"How the loss function is defined"},{"id":"d","text":"The number of training examples used"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-10-o2-c1', 'mission-ai-learning-by-gradient-10-o2', 1, 'investigation', 'Run B''s loss is swinging wildly and trending upward. What is the most likely cause?', '{"evidence":[{"id":"e1","label":"Run A","detail":"Loss decreases by a tiny, barely visible amount every step, over thousands of steps, never stalling completely"},{"id":"e2","label":"Run B","detail":"Loss swings wildly step to step and trends upward overall instead of down"},{"id":"e3","label":"Run C","detail":"Loss decreases steadily and levels off after a reasonable number of steps"}],"question":"Run B''s loss is swinging wildly and trending upward. What is the most likely cause?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-learning-by-gradient-11-o1-c1', 'mission-ai-learning-by-gradient-11-o1', 1, 'drag_and_drop', 'Match each training symptom to its optimization failure mode.', '{"items":[{"id":"i1","text":"Earliest layers'' weights barely change across thousands of steps, while later layers train normally"},{"id":"i2","text":"Parameter values suddenly become extremely large or invalid (NaN) within a few steps"},{"id":"i3","text":"Loss stays flat for a long stretch, then suddenly starts dropping again"}],"targets":[{"id":"t1","label":"Vanishing gradients"},{"id":"t2","label":"Exploding gradients"},{"id":"t3","label":"Plateau / saddle point"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3"}}'::jsonb),
  ('mission-ai-learning-by-gradient-11-o2-c1', 'mission-ai-learning-by-gradient-11-o2', 1, 'investigation', 'Which setup is most likely to produce a vanishing-gradient failure specifically?', '{"evidence":[{"id":"e1","label":"Architecture note","detail":"A very deep network using sigmoid activations throughout, with small random weight initialization"},{"id":"e2","label":"Architecture note","detail":"A network using an unusually high learning rate combined with poorly scaled input features"},{"id":"e3","label":"Training log","detail":"Loss and gradient magnitudes are both stable and reasonable throughout"}],"question":"Which setup is most likely to produce a vanishing-gradient failure specifically?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-learning-by-gradient-12-o1-c1', 'mission-ai-learning-by-gradient-12-o1', 1, 'investigation', 'Which evidence directly shows the toy network''s gradients vanishing as they propagate backward through the layers?', '{"evidence":[{"id":"e1","label":"Layer-by-layer gradient log","detail":"Gradient magnitude at the output layer: 0.31. At the middle layer: 0.02. At the first layer: 0.00004 -- shrinking by roughly two orders of magnitude per layer"},{"id":"e2","label":"Training curve","detail":"Loss drops sharply for the first few steps, then flattens almost completely, while the earliest layers'' weights barely move from their initial values"},{"id":"e3","label":"Architecture note","detail":"Eight layers deep, sigmoid activations throughout, weights initialized from a very small random range"}],"question":"Which evidence directly shows the toy network''s gradients vanishing as they propagate backward through the layers?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-learning-by-gradient-12-o2-c1', 'mission-ai-learning-by-gradient-12-o2', 1, 'investigation', 'Which evidence shows that Echo''s actual gradient behavior does not match the toy network''s vanishing-gradient signature?', '{"evidence":[{"id":"e1","label":"Toy network gradient log","detail":"Gradient magnitude collapses from 0.31 at the output layer to 0.00004 at the first layer, shrinking steadily toward zero with depth"},{"id":"e2","label":"Act 3 Echo checkpoints","detail":"Echo''s sampled gradient held a magnitude near 0.4 across three checkpoints, reversing direction each time, never shrinking toward zero"},{"id":"e3","label":"Facilities log","detail":"Cipher Labs'' cooling systems ran within normal range throughout both the toy-network run and the original Act 3 sampling window"}],"question":"Which evidence shows that Echo''s actual gradient behavior does not match the toy network''s vanishing-gradient signature?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-learning-by-gradient-12-o3-c1', 'mission-ai-learning-by-gradient-12-o3', 1, 'multiple_choice', 'The toy network''s failure came from sigmoid activations that saturate, combined with weights initialized too small, across eight layers. What would actually fix its vanishing-gradient problem?', '{"question":"The toy network''s failure came from sigmoid activations that saturate, combined with weights initialized too small, across eight layers. What would actually fix its vanishing-gradient problem?","options":[{"id":"a","text":"Lower the learning rate even further"},{"id":"b","text":"Switch to a non-saturating activation such as ReLU and use an initialization scheme that keeps gradient magnitude stable across layers"},{"id":"c","text":"Add more layers to give the network more capacity"},{"id":"d","text":"Increase the mini-batch size"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-learning-by-gradient-12-o4-c1', 'mission-ai-learning-by-gradient-12-o4', 1, 'boss_encounter', 'Having diagnosed the toy network, compared it to Echo, and judged the fix, state what Cipher Division actually found.', '{"stages":[{"objectiveRef":"mission-ai-learning-by-gradient-12-o1","label":"Diagnose the vanishing signature"},{"objectiveRef":"mission-ai-learning-by-gradient-12-o2","label":"Compare against Echo"},{"objectiveRef":"mission-ai-learning-by-gradient-12-o3","label":"Judge the real fix"}],"task":"State the finding in one sentence: the toy network''s failure is a genuine, textbook vanishing gradient, and it does not match what Echo''s gradients actually did -- so vanishing gradients are now ruled out, not explained."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-learning-by-gradient-12-o1","mission-ai-learning-by-gradient-12-o2","mission-ai-learning-by-gradient-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-learning-by-gradient-01-o1-c1', 'orientation', 'Loss is computed after a prediction is made, comparing it to something.', 10, 1),
  ('mission-ai-learning-by-gradient-01-o1-c1', 'concept', 'Ask what the single number is actually meant to measure -- distance from correct, not architecture size.', 20, 2),
  ('mission-ai-learning-by-gradient-01-o1-c1', 'solution', 'b -- loss is one number measuring how far a prediction is from the true target, computed after a forward pass.', 30, 3),
  ('mission-ai-learning-by-gradient-01-o2-c1', 'orientation', 'Subtract the true value from the prediction first, then square the result.', 10, 1),
  ('mission-ai-learning-by-gradient-01-o2-c1', 'solution', '7 minus 5 is 2, and 2 squared is 4.', 20, 2),

  ('mission-ai-learning-by-gradient-02-o1-c1', 'orientation', 'Backpropagation does not create data or initialize weights -- it works with a prediction that already exists.', 10, 1),
  ('mission-ai-learning-by-gradient-02-o1-c1', 'solution', 'b -- backpropagation computes each parameter''s share of the loss by propagating the error backward through the network.', 20, 2),
  ('mission-ai-learning-by-gradient-02-o2-c1', 'orientation', 'Nothing can be corrected before a prediction and a loss both exist.', 10, 1),
  ('mission-ai-learning-by-gradient-02-o2-c1', 'concept', 'The output layer''s error is the most direct to compute -- everything earlier depends on it.', 20, 2),
  ('mission-ai-learning-by-gradient-02-o2-c1', 'solution', 'Forward pass, compute the loss, compute the output layer''s error, propagate it backward layer by layer.', 30, 3),

  ('mission-ai-learning-by-gradient-03-o1-c1', 'orientation', 'Compute the outer derivative and the inner derivative separately first, then multiply them.', 10, 1),
  ('mission-ai-learning-by-gradient-03-o1-c1', 'concept', 'dy/du = 2u, and du/dx = 2 -- multiply them, then substitute the value of x.', 20, 2),
  ('mission-ai-learning-by-gradient-03-o1-c1', 'solution', 'At x=3, u=6, so dy/du=12 and du/dx=2. 12 times 2 is 24.', 30, 3),
  ('mission-ai-learning-by-gradient-03-o2-c1', 'orientation', 'One piece describes the outer function''s slope, one the inner function''s slope, and one is the full chained result.', 10, 1),
  ('mission-ai-learning-by-gradient-03-o2-c1', 'solution', 'dy/du is the outer function''s local slope, du/dx is the inner function''s local slope, and dy/du times du/dx is the full chain-rule derivative dy/dx.', 20, 2),

  ('mission-ai-learning-by-gradient-04-o1-c1', 'orientation', 'A positive gradient points toward the direction that increases the loss.', 10, 1),
  ('mission-ai-learning-by-gradient-04-o1-c1', 'solution', 'a -- increasing a parameter with a positive gradient increases the loss, which is why training moves it the opposite way.', 20, 2),
  ('mission-ai-learning-by-gradient-04-o2-c1', 'orientation', 'Think about what nothing left to climb toward would look like in the gradient itself.', 10, 1),
  ('mission-ai-learning-by-gradient-04-o2-c1', 'solution', 'b -- a gradient shrinking toward zero and holding its sign is the signature of a parameter settling near a good value.', 20, 2),

  ('mission-ai-learning-by-gradient-05-o1-c1', 'orientation', 'Nothing can be scaled or subtracted before the gradient itself has been computed.', 10, 1),
  ('mission-ai-learning-by-gradient-05-o1-c1', 'concept', 'Backpropagation has to run before the update rule can use its result.', 20, 2),
  ('mission-ai-learning-by-gradient-05-o1-c1', 'solution', 'Forward pass and loss, then backpropagation for the gradient, then scale by the learning rate, then subtract from the parameter.', 30, 3),
  ('mission-ai-learning-by-gradient-05-o2-c1', 'orientation', 'Multiply the learning rate by the gradient first, then subtract that from the current value.', 10, 1),
  ('mission-ai-learning-by-gradient-05-o2-c1', 'solution', '0.1 times 0.20 is 0.02. 0.50 minus 0.02 is 0.48.', 20, 2),

  ('mission-ai-learning-by-gradient-06-o1-c1', 'orientation', 'Stochastic means random -- ask what is being chosen randomly.', 10, 1),
  ('mission-ai-learning-by-gradient-06-o1-c1', 'solution', 'b -- SGD estimates the gradient from one randomly chosen example per step rather than the whole dataset.', 20, 2),
  ('mission-ai-learning-by-gradient-06-o2-c1', 'orientation', 'Ask which approach touches every example before taking a single step, and which touches only one.', 10, 1),
  ('mission-ai-learning-by-gradient-06-o2-c1', 'solution', 'Full-batch: uses the entire set, smooth and accurate. SGD: cheap and fast per step, noisy but useful on average.', 20, 2),

  ('mission-ai-learning-by-gradient-07-o1-c1', 'orientation', 'It is not one example and not the whole dataset -- it is a sampled group in between.', 10, 1),
  ('mission-ai-learning-by-gradient-07-o1-c1', 'solution', 'c -- a mini-batch is a small, randomly sampled subset of the data, averaged into one gradient estimate.', 20, 2),
  ('mission-ai-learning-by-gradient-07-o2-c1', 'orientation', 'Weigh smoothness against speed and memory, not just one of them alone.', 10, 1),
  ('mission-ai-learning-by-gradient-07-o2-c1', 'solution', 'e3 -- batch size 64 gets a reasonably smooth estimate without the memory and time cost of the full 4096-example batch.', 20, 2),

  ('mission-ai-learning-by-gradient-08-o1-c1', 'orientation', 'Momentum is defined by what it remembers, not by what it discards.', 10, 1),
  ('mission-ai-learning-by-gradient-08-o1-c1', 'solution', 'b -- momentum accumulates past gradients into a velocity term and steps using that, not the raw current gradient alone.', 20, 2),
  ('mission-ai-learning-by-gradient-08-o2-c1', 'orientation', 'Think of velocity as an average -- consistent pushes add up, opposing pushes partly cancel.', 10, 1),
  ('mission-ai-learning-by-gradient-08-o2-c1', 'solution', 'A consistent direction lets momentum build up speed. A direction that keeps flipping gets its velocity damped instead.', 20, 2),

  ('mission-ai-learning-by-gradient-09-o1-c1', 'orientation', 'Ask what Adam tracks beyond just a running direction.', 10, 1),
  ('mission-ai-learning-by-gradient-09-o1-c1', 'solution', 'b -- Adam also tracks recent gradient magnitude per parameter and uses it to scale that parameter''s step.', 20, 2),
  ('mission-ai-learning-by-gradient-09-o2-c1', 'orientation', 'Rank them by how much memory and per-parameter adjustment each one keeps.', 10, 1),
  ('mission-ai-learning-by-gradient-09-o2-c1', 'solution', 'Plain SGD: no memory. Momentum: a running direction, one shared learning rate. Adam: a running direction plus a per-parameter step size.', 20, 2),

  ('mission-ai-learning-by-gradient-10-o1-c1', 'orientation', 'It is not about architecture or data -- it is about step size.', 10, 1),
  ('mission-ai-learning-by-gradient-10-o1-c1', 'solution', 'b -- the learning rate sets how big a step each update takes.', 20, 2),
  ('mission-ai-learning-by-gradient-10-o2-c1', 'orientation', 'A loss that gets worse, not just noisy, usually means the steps are too large, not too small.', 10, 1),
  ('mission-ai-learning-by-gradient-10-o2-c1', 'solution', 'e2 -- wild swings and an upward trend are the signature of a learning rate large enough to overshoot and destabilize training.', 20, 2),

  ('mission-ai-learning-by-gradient-11-o1-c1', 'orientation', 'Match by where the failure shows up: early layers only, sudden blowups, or a stall followed by recovery.', 10, 1),
  ('mission-ai-learning-by-gradient-11-o1-c1', 'solution', 'Vanishing gradients: earliest layers stuck. Exploding gradients: sudden huge or invalid values. Plateau or saddle point: flat, then moving again later.', 20, 2),
  ('mission-ai-learning-by-gradient-11-o2-c1', 'orientation', 'Vanishing gradients are strongly tied to depth and activation choice, not learning rate size.', 10, 1),
  ('mission-ai-learning-by-gradient-11-o2-c1', 'solution', 'e1 -- deep sigmoid layers with small initial weights is the classic recipe for gradients that shrink to almost nothing by the first layer.', 20, 2),

  ('mission-ai-learning-by-gradient-12-o1-c1', 'orientation', 'Depth is the key variable here -- compare the gradient at the first layer to the gradient at the last.', 10, 1),
  ('mission-ai-learning-by-gradient-12-o1-c1', 'concept', 'A gradient that is reasonable near the output but collapses near the input, specifically because of depth, is the vanishing-gradient signature, not just noise.', 20, 2),
  ('mission-ai-learning-by-gradient-12-o1-c1', 'solution', 'e1 -- gradient magnitude collapses from 0.31 at the output layer to 0.00004 at the first layer, shrinking roughly two orders of magnitude per layer.', 30, 3),
  ('mission-ai-learning-by-gradient-12-o2-c1', 'orientation', 'Set the toy network''s pattern next to Echo''s pattern and compare direction and magnitude, not just one number.', 10, 1),
  ('mission-ai-learning-by-gradient-12-o2-c1', 'concept', 'Vanishing gradients shrink toward zero and stop reversing. Ask whether Echo''s readings ever did that.', 20, 2),
  ('mission-ai-learning-by-gradient-12-o2-c1', 'solution', 'e2 -- Echo''s gradient held its magnitude near 0.4 and kept reversing direction across all three checkpoints, the opposite of a gradient vanishing toward zero.', 30, 3),
  ('mission-ai-learning-by-gradient-12-o3-c1', 'orientation', 'The problem is structural -- activation choice and initialization -- not the step size.', 10, 1),
  ('mission-ai-learning-by-gradient-12-o3-c1', 'solution', 'b -- a non-saturating activation plus an initialization scheme designed to preserve gradient magnitude across depth addresses the actual cause, unlike a smaller learning rate or a bigger network.', 20, 2),
  ('mission-ai-learning-by-gradient-12-o4-c1', 'orientation', 'Combine what the diagnosis, the comparison and the fix each already established -- do not restate them individually.', 15, 1),
  ('mission-ai-learning-by-gradient-12-o4-c1', 'solution', 'The toy network reproduces a genuine vanishing-gradient failure under bad conditions, and it looks nothing like Echo''s actual gradients -- ruling vanishing gradients out as Echo''s explanation, without yet explaining what is.', 25, 2);
