-- Backend Engineering ("The Fracture") Act 18 -- "RabbitMQ & Brokered Messaging" content.
-- Closes Arc III (Connect). 1 campaign, 2 operations, 12 missions (11 lessons + boss),
-- following the same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every prior Act.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be18', 'world-be-18', 'rabbitmq-and-brokered-messaging', '18A - RabbitMQ & Brokered Messaging', 'Four independent teams need the same event, in their own time, without ever calling each other directly. Arc III closes with a real message broker -- and one malformed message that nearly proves it wasn''t configured to survive itself.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be18-1', 'campaign-be18', 'the-broker-model', 'The Broker Model', 'Why a broker exists, RabbitMQ''s architecture, exchanges, queues, bindings and routing keys as the vocabulary underneath everything else.', 1),
  ('operation-be18-2', 'campaign-be18', 'routing-and-reliability', 'Routing and Reliability', 'The three exchange types in practice, acknowledgements and prefetch, dead-letter exchanges, and the incident that forces an audit of the whole broker.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be18-01', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'message-broker-fundamentals', 'Message Broker Fundamentals', 'Four independent teams need to react to the same event, in their own time, without ever calling each other directly. That''s not a job-queue problem anymore -- it''s what a message broker actually exists to solve.', 'advanced', ARRAY['mira','forge'], null, null, '{"type":"simulation","simulationId":"message-broker-fundamentals-sim"}'::jsonb, '{"xp":220,"credits":42}'::jsonb, false, 1),
  ('mission-be18-02', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'rabbitmq-architecture', 'RabbitMQ Architecture', 'Producer, exchange, binding, queue, consumer -- five pieces that describe the entire path a message takes through RabbitMQ, and every bug this Act traces back to exactly one of them behaving unexpectedly.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be18-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"rabbitmq-architecture-sim"}'::jsonb, '{"xp":222,"credits":42}'::jsonb, false, 2),
  ('mission-be18-03', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'exchanges', 'Exchanges', 'An exchange routes, it never stores. Publish to one with nothing bound to it and RabbitMQ won''t complain -- it''ll just quietly drop the message on the floor.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be18-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"exchanges-sim"}'::jsonb, '{"xp":224,"credits":43}'::jsonb, false, 3),
  ('mission-be18-04', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'queues', 'Queues', 'A queue is the one place in this whole system a message actually waits. Declare it wrong and a routine broker restart erases it, messages and all.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be18-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"queues-sim"}'::jsonb, '{"xp":226,"credits":43}'::jsonb, false, 4),
  ('mission-be18-05', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'bindings', 'Bindings', 'The rule connecting an exchange to a queue is its own piece of config, easy to write once and even easier to forget you never wrote at all.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be18-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"bindings-sim"}'::jsonb, '{"xp":228,"credits":43}'::jsonb, false, 5),
  ('mission-be18-06', 'world-be-18', 'campaign-be18', 'operation-be18-1', 'routing-keys', 'Routing Keys', 'A routing key is just a label a producer attaches to a message. What it actually means depends entirely on which kind of exchange reads it.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be18-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"routing-keys-sim"}'::jsonb, '{"xp":230,"credits":44}'::jsonb, false, 6),
  ('mission-be18-07', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'direct-exchange', 'Direct Exchange', 'The simplest exchange RabbitMQ has: a routing key either matches a binding key exactly, or the message doesn''t go there at all.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be18-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"direct-exchange-sim"}'::jsonb, '{"xp":232,"credits":44}'::jsonb, false, 7),
  ('mission-be18-08', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'topic-exchange', 'Topic Exchange', 'A topic exchange trades exact matching for wildcard patterns -- * for one word, # for any number of them -- and that flexibility is exactly where a routing key can hide in plain sight.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be18-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"topic-exchange-sim"}'::jsonb, '{"xp":234,"credits":44}'::jsonb, false, 8),
  ('mission-be18-09', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'fanout-exchange', 'Fanout Exchange', 'A fanout exchange ignores the routing key entirely and broadcasts to every bound queue -- exactly the shape four independent teams needed for the same outage advisory.', 'advanced', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be18-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"fanout-exchange-sim"}'::jsonb, '{"xp":236,"credits":45}'::jsonb, false, 9),
  ('mission-be18-10', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'acknowledgements-and-prefetch', 'Acknowledgements and Prefetch', 'A message stays "delivered but unconfirmed" until a consumer acks it -- and what happens between delivery and that ack decides whether a crash loses a message or loops it forever.', 'advanced', ARRAY['forge','mira'], '{"requiredMissionIds":["mission-be18-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"ack-prefetch-sim"}'::jsonb, '{"xp":238,"credits":45}'::jsonb, false, 10),
  ('mission-be18-11', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'dead-letter-exchanges', 'Dead-Letter Exchanges', 'Every message that gets rejected, expires, or overflows a queue has to go somewhere. Without a dead-letter exchange configured, "somewhere" is nowhere at all.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be18-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"dead-letter-exchange-sim"}'::jsonb, '{"xp":240,"credits":46}'::jsonb, false, 11),
  ('mission-be18-12', 'world-be-18', 'campaign-be18', 'operation-be18-2', 'the-poison-message', 'The Poison Message', 'One malformed message, six hours of endless redelivery, and an exchange audit that turns up something nobody meant to leave in production config. Everything this Act taught, at once.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be18-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"poison-message-boss-sim"}'::jsonb, '{"xp":530,"credits":122,"badgeIds":["poison-message"],"skillXp":{"messaging":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be18-01', 1, 'mira', 'The million jobs incident made one thing obvious: a queue works when one service owns the job end to end. It stops working the moment four independent teams -- inventory, billing, notifications, audit -- all need to react to the same event, in their own language, on their own schedule.'),
  ('mission-be18-01', 2, 'forge', 'That''s what a message broker actually is: a service that sits between producers and consumers, decoupling ''something happened'' from ''here''s everyone who needs to know.'' Nobody calls anybody directly. Everybody just talks to the broker.'),
  ('mission-be18-01', 3, 'forge', 'We''re standing up RabbitMQ for exactly that: fan the outage-advisory event out to four services at once, without any of them ever knowing the other three exist.'),

  ('mission-be18-02', 1, 'forge', 'RabbitMQ''s whole model is four pieces: a producer publishes a message to an exchange. The exchange, using bindings, decides which queues get a copy. A consumer reads from a queue. The exchange never talks to a consumer directly, and a queue never talks to a producer directly.'),
  ('mission-be18-02', 2, 'mira', 'Keep that mental model exact. Every bug this Act traces back to one of those four pieces doing something you didn''t expect.'),

  ('mission-be18-03', 1, 'mira', 'An exchange is the router, and only the router. It never stores a message itself -- it receives one from a producer and, in the same instant, decides which bound queues, if any, get a copy.'),
  ('mission-be18-03', 2, 'forge', 'That ''if any'' is the part people miss. Publish to an exchange with zero bindings, and RabbitMQ doesn''t error, doesn''t queue it up for later -- it just drops the message on the floor.'),

  ('mission-be18-04', 1, 'forge', 'A queue is the only place in this whole system a message actually rests. Everything upstream is instantaneous routing -- the queue is where ''waiting for a consumer'' really happens.'),
  ('mission-be18-04', 2, 'forge', 'Declare it wrong and you find out the hard way. A queue declared non-durable disappears, messages and all, the moment RabbitMQ restarts.'),

  ('mission-be18-05', 1, 'mira', 'A binding is the one piece of config that actually connects an exchange to a queue. No binding, no path -- the exchange can be perfectly configured and the queue can be perfectly durable, and a message between them still goes nowhere.'),
  ('mission-be18-05', 2, 'forge', 'It''s also the piece everyone forgets to write down. An exchange and a queue can both exist for months before anyone notices nothing actually binds them.'),

  ('mission-be18-06', 1, 'forge', 'A routing key is just a string a producer attaches to a message -- nothing more. RabbitMQ doesn''t interpret it on its own; what it means, and how strictly it has to match, depends entirely on the exchange type it arrives at.'),
  ('mission-be18-06', 2, 'mira', 'Same key, different exchange, completely different behavior. Learn the key as a label first -- the meaning comes from the three exchange types next.'),

  ('mission-be18-07', 1, 'forge', 'A direct exchange is the simplest case: exact match, nothing else. A message routes to a queue only if its routing key is character-for-character identical to that queue''s binding key.'),
  ('mission-be18-07', 2, 'mira', 'Good for one job, one queue -- like routing advisory.audit messages to exactly the audit queue and nowhere else.'),

  ('mission-be18-08', 1, 'mira', 'A topic exchange routes by pattern instead of exact match. A routing key is dot-separated words, and a binding key can use * to match exactly one word or # to match zero or more.'),
  ('mission-be18-08', 2, 'forge', 'advisory.*.audit matches advisory.critical.audit but not advisory.audit -- and advisory.# matches everything that starts with advisory, no matter how many words follow.'),

  ('mission-be18-09', 1, 'forge', 'A fanout exchange ignores the routing key completely. Publish one message, and every queue bound to it gets an identical copy -- no pattern matching, no filtering.'),
  ('mission-be18-09', 2, 'mira', 'That''s exactly the shape the outage-advisory event needs: audit, inventory, billing and notifications all need the same event, unfiltered. Fanout is the exchange we actually put in front of it.'),

  ('mission-be18-10', 1, 'forge', 'A consumer doesn''t just read a message off a queue -- it has to acknowledge it. Until RabbitMQ gets that ack, the message stays counted as ''delivered but unconfirmed,'' and if the consumer disconnects before acking, RabbitMQ puts it right back on the queue.'),
  ('mission-be18-10', 2, 'mira', 'That single behavior is either the safety net that saves you or the thing that loops forever, depending on whether the consumer can ever actually reach the ack.'),

  ('mission-be18-11', 1, 'mira', 'A dead-letter exchange is where a message goes when a queue gives up on it -- rejected without requeue, expired past its TTL, or bounced off a queue that hit its max length. Without one configured, none of those failure paths go anywhere at all.'),
  ('mission-be18-11', 2, 'forge', 'Configure it once, on the queue itself, with an x-dead-letter-exchange argument, and every one of those failure paths finally has somewhere to land instead of vanishing or looping.'),

  ('mission-be18-12', 1, 'forge', 'Incident: RabbitMQ has been redelivering the same message to the audit consumer for six hours straight. Every delivery crashes the consumer before it can ack, so RabbitMQ puts it right back on the queue and hands it out again.'),
  ('mission-be18-12', 2, 'mira', 'Classic poison message. It''s not attacking anything -- it''s just malformed enough that our own code can''t survive processing it, and nothing was ever told to give up on it.'),
  ('mission-be18-12', 3, 'forge', 'No dead-letter exchange configured on this queue. Every rejected or crashed-out message has always had exactly one destination: back onto the same queue, forever.'),
  ('mission-be18-12', 4, 'forge', 'Fixing this meant auditing every exchange and every binding in the broker -- something nobody had actually done since RabbitMQ went in. Found something in the process I didn''t expect.'),
  ('mission-be18-12', 5, 'forge', 'A topic-exchange binding, buried in infrastructure config, routing key forge.events//audit. Not a message key from a producer -- a routing key someone wrote directly into the broker''s own setup.'),
  ('mission-be18-12', 6, 'mira', 'That''s three layers now. Application code, back in the early Acts. The database layer -- Act 9, Act 11, Act 13. And now the message layer, sitting in infrastructure config nobody thought to look at until a poison message forced the audit.'),
  ('mission-be18-12', 7, 'mira', 'I''m not saying what it is. I''m saying it''s not confined to any one part of the stack anymore, and that changes what kind of problem this is.'),
  ('mission-be18-12', 8, 'forge', 'Whatever it is, it''s patient. Every place we''ve found it, it''s been sitting there a while before anyone noticed. Poison message''s fixed either way -- the dead-letter exchange goes in today.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be18-01-o1', 'mission-be18-01', 1, 'Diagnose why a broker is the actual fix', 'Find the evidence that explains the root cause of the cascading failure, not just one of its symptoms.'),
  ('mission-be18-02-o1', 'mission-be18-02', 1, 'Match the architecture piece to its job', 'Match each RabbitMQ architecture piece to what it actually does.'),
  ('mission-be18-03-o1', 'mission-be18-03', 1, 'Diagnose the vanishing messages', 'Find the evidence that explains why messages are disappearing with no errors at all.'),
  ('mission-be18-04-o1', 'mission-be18-04', 1, 'Match the queue property', 'Match each queue declaration property to what it actually controls.'),
  ('mission-be18-04-o2', 'mission-be18-04', 2, 'Find the durability bug', 'Debug a queue declaration that doesn''t survive a broker restart.'),
  ('mission-be18-05-o1', 'mission-be18-05', 1, 'Diagnose the missing binding', 'Find the evidence that explains why a healthy consumer never receives a single message.'),
  ('mission-be18-06-o1', 'mission-be18-06', 1, 'Explain what decides routing', 'Choose what actually determines whether a message reaches a queue.'),
  ('mission-be18-07-o1', 'mission-be18-07', 1, 'Find the exact-match bug', 'Debug a direct-exchange binding that never fires for the message it was meant to route.'),
  ('mission-be18-08-o1', 'mission-be18-08', 1, 'Match the routing key to the pattern', 'Decide whether each routing key matches a given topic-exchange binding pattern.'),
  ('mission-be18-09-o1', 'mission-be18-09', 1, 'Choose the right exchange', 'Choose the exchange type that fits broadcasting one event identically to every consumer.'),
  ('mission-be18-10-o1', 'mission-be18-10', 1, 'Find the premature ack', 'Debug a consumer that acknowledges a message before it''s actually finished processing it.'),
  ('mission-be18-10-o2', 'mission-be18-10', 2, 'Diagnose the prefetch imbalance', 'Find the evidence that explains why one consumer is overloaded while others sit idle.'),
  ('mission-be18-11-o1', 'mission-be18-11', 1, 'Find the missing destination', 'Debug a queue declaration where failed messages have nowhere configured to go.'),
  ('mission-be18-11-o2', 'mission-be18-11', 2, 'Order the dead-letter flow', 'Order the path a message takes from failure to landing in a dead-letter queue.'),
  ('mission-be18-12-o1', 'mission-be18-12', 1, 'Diagnose the redelivery loop', 'Find the evidence that explains why RabbitMQ redelivers this message forever instead of eventually giving up on it.'),
  ('mission-be18-12-o2', 'mission-be18-12', 2, 'Design the fix', 'Choose the combination of changes that actually stops this failure mode without silently losing the message.'),
  ('mission-be18-12-o3', 'mission-be18-12', 3, 'Confirm the escalation', 'Find the piece of evidence from the exchange audit that is the actual escalation, not just confirmation the rest of the broker is healthy.'),
  ('mission-be18-12-o4', 'mission-be18-12', 4, 'Close the incident', 'Synthesize the diagnosis, the fix, and the audit finding into the full resolution.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be18-01-o1-c1', 'mission-be18-01-o1', 1, 'investigation', 'Which evidence explains the actual root cause of the cascading failure, not just one of its symptoms?', '{"evidence":[{"id":"ev1","label":"Incident timeline","detail":"Notification service called inventory, billing and audit directly over HTTP after every advisory; when audit''s endpoint timed out, the entire advisory pipeline stalled, including inventory and billing which had already succeeded."},{"id":"ev2","label":"Postmortem note","detail":"Every one of the three downstream calls was synchronous and tightly coupled to the notification service''s own request lifecycle -- none of them could fail or lag independently."},{"id":"ev3","label":"Team complaint","detail":"Adding a fifth downstream team requires a code change and redeploy of the notification service itself."}],"question":"Which evidence explains the actual root cause of the cascading failure, not just one of its symptoms?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be18-02-o1-c1', 'mission-be18-02-o1', 1, 'drag_and_drop', 'Match each RabbitMQ architecture piece to what it actually does.', '{"items":[{"id":"p1","text":"Producer"},{"id":"p2","text":"Exchange"},{"id":"p3","text":"Binding"},{"id":"p4","text":"Queue"},{"id":"p5","text":"Consumer"}],"targets":[{"id":"t1","label":"Publishes messages, with no idea who, if anyone, receives them"},{"id":"t2","label":"Routes an incoming message to zero or more queues, based on its type and the bindings attached to it"},{"id":"t3","label":"The rule connecting an exchange to a queue, optionally filtered by a routing key"},{"id":"t4","label":"Holds messages durably until a consumer is ready for them"},{"id":"t5","label":"Reads messages off a queue and does the actual work"}]}'::jsonb, '{"correctMapping":{"p1":"t1","p2":"t2","p3":"t3","p4":"t4","p5":"t5"}}'::jsonb),

  ('mission-be18-03-o1-c1', 'mission-be18-03-o1', 1, 'investigation', 'Which evidence explains why messages are vanishing even though the producer sees no errors at all?', '{"evidence":[{"id":"ev1","label":"Publish confirm","detail":"The producer receives a normal publish confirmation from RabbitMQ for every message sent to advisory.exchange."},{"id":"ev2","label":"Queue inspection","detail":"advisory.exchange currently has zero queues bound to it -- it was created ahead of the consumer teams being ready."},{"id":"ev3","label":"Consumer report","detail":"None of the four downstream teams have received a single advisory message since the exchange was created."}],"question":"Which evidence explains why messages are vanishing even though the producer sees no errors at all?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be18-04-o1-c1', 'mission-be18-04-o1', 1, 'drag_and_drop', 'Match each queue declaration property to what it actually controls.', '{"items":[{"id":"q1","text":"durable: true"},{"id":"q2","text":"exclusive: true"},{"id":"q3","text":"autoDelete: true"},{"id":"q4","text":"No special flags set"}],"targets":[{"id":"t1","label":"The queue definition survives a broker restart, as long as its messages are marked persistent too"},{"id":"t2","label":"Only the connection that declared it can use it; deleted the moment that connection closes"},{"id":"t3","label":"Deleted automatically once its last consumer disconnects"},{"id":"t4","label":"A completely ordinary, permanent, shared queue"}]}'::jsonb, '{"correctMapping":{"q1":"t1","q2":"t2","q3":"t3","q4":"t4"}}'::jsonb),
  ('mission-be18-04-o2-c1', 'mission-be18-04-o2', 1, 'code_debugging', 'After a routine broker restart, the audit team''s queue -- and everything queued in it -- was gone. Which line caused that?', '{"language":"javascript","code":"channel.assertQueue(\"advisory.audit\", {\n  durable: false,\n  autoDelete: false,\n});","question":"After a routine broker restart, the audit team''s queue -- and everything queued in it -- was gone. Which line caused that?"}'::jsonb, '{"requiredLineIds":["  durable: false,"]}'::jsonb),

  ('mission-be18-05-o1-c1', 'mission-be18-05-o1', 1, 'investigation', 'Which evidence explains why the billing team''s healthy, connected consumer never receives a single message?', '{"evidence":[{"id":"ev1","label":"Exchange status","detail":"advisory.topic exchange is declared and receiving messages with no errors."},{"id":"ev2","label":"Queue status","detail":"billing.advisories queue exists, is durable, and has an active consumer waiting."},{"id":"ev3","label":"Binding list","detail":"Querying RabbitMQ''s binding list for advisory.topic returns entries for audit and inventory only -- billing is missing."}],"question":"Which evidence explains why the billing team''s healthy, connected consumer never receives a single message?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be18-06-o1-c1', 'mission-be18-06-o1', 1, 'multiple_choice', 'A producer publishes with routing key advisory.critical.audit. What determines whether any queue actually receives it?', '{"question":"A producer publishes with routing key advisory.critical.audit. What determines whether any queue actually receives it?","options":[{"id":"a","text":"The routing key alone, since RabbitMQ always does an exact match"},{"id":"b","text":"The exchange type the message is published to, combined with the binding keys configured on that exchange -- direct, topic and fanout each interpret the routing key differently"},{"id":"c","text":"Nothing -- routing keys are purely for logging"},{"id":"d","text":"The order the queues were declared in"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be18-07-o1-c1', 'mission-be18-07-o1', 1, 'code_debugging', 'This direct-exchange binding never fires for the published message. Which line is responsible?', '{"language":"javascript","code":"channel.bindQueue(\"audit-queue\", \"advisory.direct\", \"advisory.audit\");\nchannel.publish(\"advisory.direct\", \"Advisory.audit\", Buffer.from(payload));","question":"This direct-exchange binding never fires for the published message. Which line is responsible?"}'::jsonb, '{"requiredLineIds":["channel.publish(\"advisory.direct\", \"Advisory.audit\", Buffer.from(payload));"]}'::jsonb),

  ('mission-be18-08-o1-c1', 'mission-be18-08-o1', 1, 'drag_and_drop', 'Decide whether each routing key matches the topic-exchange binding pattern advisory.*.audit.', '{"items":[{"id":"k1","text":"advisory.critical.audit"},{"id":"k2","text":"advisory.audit"},{"id":"k3","text":"advisory.low.audit"},{"id":"k4","text":"advisory.critical.audit.followup"}],"targets":[{"id":"t1","label":"Matches advisory.*.audit"},{"id":"t2","label":"Does not match advisory.*.audit"}]}'::jsonb, '{"correctMapping":{"k1":"t1","k2":"t2","k3":"t1","k4":"t2"}}'::jsonb),

  ('mission-be18-09-o1-c1', 'mission-be18-09-o1', 1, 'multiple_choice', 'Four independent teams all need an identical copy of every outage-advisory event, with no filtering by routing key. Which exchange type fits?', '{"question":"Four independent teams all need an identical copy of every outage-advisory event, with no filtering by routing key. Which exchange type fits?","options":[{"id":"a","text":"Direct -- exact match keeps things simple"},{"id":"b","text":"Topic -- wildcard patterns give the most flexibility"},{"id":"c","text":"Fanout -- it broadcasts to every bound queue regardless of routing key, which is exactly ''everyone gets everything''"},{"id":"d","text":"It doesn''t matter, all three behave the same with four queues bound"}]}'::jsonb, '{"correctOptionId":"c"}'::jsonb),

  ('mission-be18-10-o1-c1', 'mission-be18-10-o1', 1, 'code_debugging', 'If processAdvisory throws on a malformed message, RabbitMQ has already been told the message succeeded. Which line causes that?', '{"language":"javascript","code":"channel.consume(\"advisory.audit\", (msg) => {\n  channel.ack(msg);\n  processAdvisory(JSON.parse(msg.content.toString()));\n});","question":"If processAdvisory throws on a malformed message, RabbitMQ has already been told the message succeeded. Which line causes that?"}'::jsonb, '{"requiredLineIds":["  channel.ack(msg);"]}'::jsonb),
  ('mission-be18-10-o2-c1', 'mission-be18-10-o2', 1, 'investigation', 'Which evidence explains the actual mechanism behind one consumer being overloaded while others sit idle?', '{"evidence":[{"id":"ev1","label":"Consumer config","detail":"channel.prefetch(0) is the config used on every consumer connected to advisory.audit -- 0 means unlimited unacknowledged messages per consumer."},{"id":"ev2","label":"Load pattern","detail":"One slow consumer instance was handed 40,000 unacknowledged messages in the first ten seconds of a traffic spike, while three idle consumer instances sat with none."},{"id":"ev3","label":"Memory alert","detail":"The slow consumer''s process was killed by an out-of-memory error, and all 40,000 unacked messages were redelivered at once."}],"question":"Which evidence explains the actual mechanism behind one consumer being overloaded while others sit idle?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be18-11-o1-c1', 'mission-be18-11-o1', 1, 'code_debugging', 'Messages here expire via TTL after 60 seconds, but nothing catches them afterward. Which line configures a fate for expired messages without specifying where they actually go?', '{"language":"javascript","code":"channel.assertQueue(\"advisory.audit\", {\n  durable: true,\n  arguments: {\n    \"x-message-ttl\": 60000,\n  },\n});","question":"Messages here expire via TTL after 60 seconds, but nothing catches them afterward. Which line configures a fate for expired messages without specifying where they actually go?"}'::jsonb, '{"requiredLineIds":["    \"x-message-ttl\": 60000,"]}'::jsonb),
  ('mission-be18-11-o2-c1', 'mission-be18-11-o2', 1, 'interactive_diagram', 'Order the path a message takes from failure to landing in a dead-letter queue.', '{"diagramId":"dead-letter-flow","hotspots":[{"id":"message_delivered","label":"Message delivered to the original queue''s consumer","explanation":"The consumer receives it exactly like any other message."},{"id":"fails_repeatedly","label":"Consumer nacks it without requeue, or it exceeds its TTL or the queue''s max length","explanation":"One of RabbitMQ''s defined dead-letter triggers fires."},{"id":"dead_lettered","label":"RabbitMQ republishes it to the queue''s configured x-dead-letter-exchange","explanation":"This only happens if the argument was actually set on the queue."},{"id":"dlx_queue","label":"The dead-letter exchange routes it into a separate dead-letter queue","explanation":"Isolated from the healthy flow, where it can be inspected or alerted on."}],"task":"Order the path a message takes from failure to landing in a dead-letter queue."}'::jsonb, '{"correctOrderIds":["message_delivered","fails_repeatedly","dead_lettered","dlx_queue"]}'::jsonb),

  ('mission-be18-12-o1-c1', 'mission-be18-12-o1', 1, 'investigation', 'Which evidence explains why RabbitMQ keeps redelivering this message forever instead of eventually giving up on it?', '{"evidence":[{"id":"ev1","label":"Consumer logs","detail":"The consumer process crashes with an unhandled parse error every time it dequeues this specific message, before reaching the ack call."},{"id":"ev2","label":"Queue metrics","detail":"The redelivery count for this message is at 4,812 and climbing, roughly one redelivery every 4 seconds since it arrived."},{"id":"ev3","label":"Queue config","detail":"advisory.audit queue has no x-dead-letter-exchange argument and no maximum delivery count configured."}],"question":"Which evidence explains why RabbitMQ keeps redelivering this message forever instead of eventually giving up on it?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),
  ('mission-be18-12-o2-c1', 'mission-be18-12-o2', 1, 'multiple_choice', 'Which combination of changes actually stops this specific failure mode, without silently losing the message?', '{"question":"Which combination of changes actually stops this specific failure mode, without silently losing the message?","options":[{"id":"a","text":"Just increase the consumer''s memory limit"},{"id":"b","text":"Configure a dead-letter exchange on the queue plus a delivery-count limit, so after N failed attempts the message dead-letters instead of redelivering forever, and only ack the message after processing actually succeeds"},{"id":"c","text":"Switch the consumer to auto-ack so it never blocks waiting for an acknowledgement"},{"id":"d","text":"Delete the queue and recreate it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-be18-12-o3-c1', 'mission-be18-12-o3', 1, 'investigation', 'Which piece of evidence from the exchange audit is the actual escalation, not just confirmation the rest of the broker is healthy?', '{"evidence":[{"id":"ev1","label":"Exchange audit","detail":"advisory.topic and three other exchanges are correctly bound and behaving exactly as documented."},{"id":"ev2","label":"Infrastructure config diff","detail":"A topic-exchange binding, defined directly in infrastructure config rather than by any known service, uses routing key forge.events//audit -- no producer in the codebase publishes anything resembling that key."},{"id":"ev3","label":"Historical note","detail":"The doubled-slash pattern has already turned up in application code from early Acts and in the database layer across Acts 9, 11 and 13."}],"question":"Which piece of evidence from the exchange audit is the actual escalation, not just confirmation the rest of the broker is healthy?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),
  ('mission-be18-12-o4-c1', 'mission-be18-12-o4', 1, 'boss_encounter', 'Having diagnosed the redelivery loop, designed the fix, and confirmed what the audit turned up, state both halves of the resolution.', '{"stages":[{"objectiveRef":"mission-be18-12-o1","label":"Diagnose the redelivery loop"},{"objectiveRef":"mission-be18-12-o2","label":"Design the fix"},{"objectiveRef":"mission-be18-12-o3","label":"Confirm the escalation"}],"task":"Having diagnosed the redelivery loop, designed the fix, and confirmed what the audit turned up, state both halves of the resolution: a dead-letter exchange with a delivery-count limit is the missing safeguard that would have stopped one bad message from looping forever, and forge.events//audit, found in the broker''s own infrastructure config, means the pattern now spans application code, the database layer and the message layer alike."}'::jsonb, '{"requiredObjectiveIds":["mission-be18-12-o1","mission-be18-12-o2","mission-be18-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be18-01-o1-c1', 'orientation', 'Two of these describe specific pain. One describes the design decision that produced all of it.', 10, 1),
  ('mission-be18-01-o1-c1', 'concept', 'A synchronous call chain fails as a unit -- if any one link in it can''t finish, nothing downstream of the call that''s waiting on it can finish either, even the parts that already succeeded.', 20, 2),
  ('mission-be18-01-o1-c1', 'solution', 'ev2: the calls being synchronous and tightly coupled to one service''s request lifecycle is the actual root cause -- ev1 is one instance of that failing, ev3 is a separate, related symptom.', 30, 3),

  ('mission-be18-02-o1-c1', 'orientation', 'One of these pieces only makes a decision. One only stores. Two only pass messages along.', 10, 1),
  ('mission-be18-02-o1-c1', 'concept', 'Nothing in this chain talks to anything two steps away -- a producer never reaches a queue directly, and a consumer never reaches an exchange directly.', 20, 2),
  ('mission-be18-02-o1-c1', 'solution', 'Producer publishes, exchange routes, binding connects exchange to queue, queue holds, consumer reads and works.', 30, 3),

  ('mission-be18-03-o1-c1', 'orientation', 'A successful publish confirmation only proves the exchange received the message -- not that anything happened to it afterward.', 10, 1),
  ('mission-be18-03-o1-c1', 'concept', 'An exchange with no bindings has nowhere to route a message to. RabbitMQ doesn''t hold it, buffer it, or error -- it just has nothing to do with it.', 20, 2),
  ('mission-be18-03-o1-c1', 'solution', 'ev2: zero bindings on the exchange means every message it receives has nowhere to go and is simply discarded, with no error anywhere in the pipeline.', 30, 3),

  ('mission-be18-04-o1-c1', 'orientation', 'Two of these decide what happens to the queue itself. One decides who else can use it.', 10, 1),
  ('mission-be18-04-o1-c1', 'solution', 'durable -> survives a restart, exclusive -> single-connection-only and deleted with it, autoDelete -> deleted when the last consumer leaves, no flags -> ordinary permanent queue.', 20, 2),
  ('mission-be18-04-o2-c1', 'orientation', 'A queue that isn''t marked durable doesn''t survive the one event it most needs to survive.', 10, 1),
  ('mission-be18-04-o2-c1', 'concept', 'durable: false means the queue''s own definition, not just its messages, is wiped whenever RabbitMQ restarts.', 20, 2),
  ('mission-be18-04-o2-c1', 'solution', 'durable: false is the bug -- it should be durable: true so the queue definition survives a broker restart.', 30, 3),

  ('mission-be18-05-o1-c1', 'orientation', 'Two of these confirm the pieces on either side are fine. One confirms the connection between them was never made.', 10, 1),
  ('mission-be18-05-o1-c1', 'concept', 'An exchange and a queue can both be perfectly healthy and still have no path between them at all -- that path is a separate, third thing that has to be declared.', 20, 2),
  ('mission-be18-05-o1-c1', 'solution', 'ev3: billing has no binding in the list at all -- the exchange and the queue are both fine, but nothing connects them.', 30, 3),

  ('mission-be18-06-o1-c1', 'orientation', 'The same routing key sent to a direct exchange and a topic exchange can produce completely different results.', 10, 1),
  ('mission-be18-06-o1-c1', 'solution', 'b: routing is decided by the exchange type plus its bindings, not by the routing key in isolation.', 20, 2),

  ('mission-be18-07-o1-c1', 'orientation', 'A direct exchange''s match is exact -- character for character, including case.', 10, 1),
  ('mission-be18-07-o1-c1', 'concept', 'advisory.audit and Advisory.audit are two different strings as far as an exact match is concerned, even though they read the same to a human.', 20, 2),
  ('mission-be18-07-o1-c1', 'solution', 'The publish call uses Advisory.audit (capital A), which doesn''t exactly match the bound key advisory.audit -- the message never routes.', 30, 3),

  ('mission-be18-08-o1-c1', 'orientation', 'Count the dot-separated words. * matches exactly one word, no more, no fewer.', 10, 1),
  ('mission-be18-08-o1-c1', 'concept', 'advisory.*.audit needs precisely three words: advisory, one word matched by *, then audit -- two words or four words both fail to match.', 20, 2),
  ('mission-be18-08-o1-c1', 'solution', 'advisory.critical.audit and advisory.low.audit match (exactly three words). advisory.audit (two words) and advisory.critical.audit.followup (four words) don''t.', 30, 3),

  ('mission-be18-09-o1-c1', 'orientation', 'The requirement is ''everyone gets everything, unfiltered'' -- that phrase names the exchange type directly.', 10, 1),
  ('mission-be18-09-o1-c1', 'solution', 'c: fanout ignores routing keys entirely and copies every message to every bound queue -- exactly this requirement.', 20, 2),

  ('mission-be18-10-o1-c1', 'orientation', 'Acking is a promise to RabbitMQ that processing already succeeded -- once made, it can''t be taken back.', 10, 1),
  ('mission-be18-10-o1-c1', 'concept', 'Ack before processing means a crash during processing leaves RabbitMQ believing the message is done, even though it never actually was.', 20, 2),
  ('mission-be18-10-o1-c1', 'solution', 'channel.ack(msg) runs before processAdvisory -- it should run after processing succeeds, not before it''s even attempted.', 30, 3),
  ('mission-be18-10-o2-c1', 'orientation', 'Prefetch limits how many unacked messages one consumer can be holding at once -- 0 means no limit at all.', 10, 1),
  ('mission-be18-10-o2-c1', 'concept', 'With no prefetch limit, RabbitMQ can hand an entire backlog to whichever consumer happens to be first in line, regardless of how fast that consumer actually is.', 20, 2),
  ('mission-be18-10-o2-c1', 'solution', 'ev1: prefetch(0) removes the per-consumer cap, so RabbitMQ dumps messages onto one consumer instead of spreading them fairly -- that''s the mechanism, not just the resulting overload.', 30, 3),

  ('mission-be18-11-o1-c1', 'orientation', 'A TTL gives a message an expiration date. It doesn''t say what happens after it expires.', 10, 1),
  ('mission-be18-11-o1-c1', 'concept', 'x-message-ttl needs a partner argument, x-dead-letter-exchange, to actually catch anything that expires -- one without the other just discards it silently.', 20, 2),
  ('mission-be18-11-o1-c1', 'solution', '"x-message-ttl": 60000 sets an expiration with nothing to catch it -- the queue needs an x-dead-letter-exchange argument alongside it.', 30, 3),
  ('mission-be18-11-o2-c1', 'orientation', 'Nothing can be dead-lettered until it fails first, and it has to be delivered before it can fail.', 10, 1),
  ('mission-be18-11-o2-c1', 'concept', 'The dead-letter exchange only receives a message because the original queue was explicitly configured to send it there -- it''s not automatic.', 20, 2),
  ('mission-be18-11-o2-c1', 'solution', 'Delivered, then fails via nack/TTL/max-length, then republished to the configured dead-letter exchange, then routed into its own dead-letter queue.', 30, 3),

  ('mission-be18-12-o1-c1', 'orientation', 'The crash log and the redelivery count are both symptoms happening over and over. One piece of evidence explains why ''over and over'' never stops.', 10, 1),
  ('mission-be18-12-o1-c1', 'concept', 'Nothing about RabbitMQ''s default behavior gives up on a message on its own -- something has to be explicitly configured to cap redelivery or catch failures, or it never ends.', 20, 2),
  ('mission-be18-12-o1-c1', 'solution', 'ev3: no dead-letter exchange and no delivery-count limit means there''s no configured point where RabbitMQ would ever stop redelivering it.', 30, 3),
  ('mission-be18-12-o2-c1', 'orientation', 'The fix has two separate jobs: stop this message from looping, and make sure a future crash-before-ack doesn''t reintroduce the same bug.', 10, 1),
  ('mission-be18-12-o2-c1', 'solution', 'b: a dead-letter exchange with a delivery-count limit gives redelivery a stopping point, and acking only after success prevents crashes from being mistaken for completions.', 20, 2),
  ('mission-be18-12-o3-c1', 'orientation', 'The other exchanges behaving normally is reassuring. It isn''t new information about what the audit found.', 10, 1),
  ('mission-be18-12-o3-c1', 'concept', 'A binding that no known producer created, sitting directly in infrastructure config, is the one entry the audit wasn''t expecting to find.', 20, 2),
  ('mission-be18-12-o3-c1', 'solution', 'ev2: the forge.events//audit binding, written directly into infra config with no producer behind it, is the actual new finding -- not just confirmation everything else checks out.', 30, 3),
  ('mission-be18-12-o4-c1', 'orientation', 'This mission had two separate jobs: fix the technical incident, and register what the audit turned up along the way.', 15, 1),
  ('mission-be18-12-o4-c1', 'solution', 'A dead-letter exchange with a delivery-count limit closes the redelivery loop for good. Separately, forge.events//audit confirms the pattern now reaches application code, the database layer, and the message layer alike.', 25, 2);
