-- AI/ML pathway (Cipher Division) Act 16 -- "PyTorch Forge" content.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), following the
-- same campaigns -> operations -> missions -> dialogue -> objectives ->
-- challenges -> hints pattern as every other pathway. Part of Arc III
-- ("Neural Systems", Acts 13-18). Builds on the World row already updated
-- by 20260812070000_ai_acts16_20_world_narrative.sql
-- (world-ai-pytorch-forge, act-ai-3). Does not insert into worlds, acts or
-- pathways -- those rows already exist.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-pytorch-forge', 'world-ai-pytorch-forge', 'pytorch-forge', '16A - PyTorch Forge', 'Real tensors, autograd, nn.Module, Dataset and DataLoader, and a hand-written training loop -- moving from toy hand-built networks to a production framework without ever losing the understanding underneath it.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-pytorch-forge-1', 'campaign-ai-pytorch-forge', 'the-primitives', 'The Primitives', 'Tensors, shapes, devices, autograd and nn.Module -- the objects every PyTorch program is actually built from, understood one at a time before anything gets automated.', 1),
  ('operation-ai-pytorch-forge-2', 'campaign-ai-pytorch-forge', 'the-real-loop', 'The Real Loop', 'Dataset, DataLoader, a real training loop, a real validation loop, optimizers and saving models -- assembled by hand, then stress-tested against a shortcut nobody has read yet.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-pytorch-forge-01', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'tensors', 'Tensors', 'Before a network, before a layer, before a gradient -- everything in PyTorch is built from one object. Elena wants every primitive understood before any of it gets used.', 'beginner', ARRAY['maya','elena'], null, null, '{"type":"simulation","simulationId":"tensors-sim"}'::jsonb, '{"xp":320,"credits":75}'::jsonb, false, 1),
  ('mission-ai-pytorch-forge-02', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'shapes', 'Shapes', 'Get a tensor''s shape wrong and PyTorch does not warn -- it refuses to run the operation. Shapes are read, not guessed.', 'beginner', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"shapes-sim"}'::jsonb, '{"xp":330,"credits":75}'::jsonb, false, 2),
  ('mission-ai-pytorch-forge-03', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'devices', 'Devices', 'Two tensors on different devices cannot touch. Knowing where a tensor actually lives, and moving it there on purpose, is what keeps a training run from failing on its very first line.', 'beginner', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-pytorch-forge-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"devices-sim"}'::jsonb, '{"xp":330,"credits":80}'::jsonb, false, 3),
  ('mission-ai-pytorch-forge-04', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'autograd', 'Autograd', 'Autograd is what makes training possible without hand-deriving a single gradient. Track the right tensors, and PyTorch computes every derivative for you.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"autograd-sim"}'::jsonb, '{"xp":340,"credits":80}'::jsonb, false, 4),
  ('mission-ai-pytorch-forge-05', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'nn-module', 'nn.Module', 'nn.Module keeps every parameter a network owns registered and trainable, automatically -- as long as one line at the top of every subclass actually gets called.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"nn-module-sim"}'::jsonb, '{"xp":340,"credits":80}'::jsonb, false, 5),
  ('mission-ai-pytorch-forge-06', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-1', 'dataset', 'Dataset', 'A Dataset is a contract: report how many examples exist, and return exactly one of them by index. Break that contract quietly, and a model trains on lies nobody notices.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"dataset-sim"}'::jsonb, '{"xp":350,"credits":85}'::jsonb, false, 6),
  ('mission-ai-pytorch-forge-07', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'dataloader', 'DataLoader', 'Dataset answers how to fetch one example. DataLoader turns that into shuffled, parallel-loaded batches a training loop can actually consume, one epoch at a time.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-pytorch-forge-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"dataloader-sim"}'::jsonb, '{"xp":350,"credits":85}'::jsonb, false, 7),
  ('mission-ai-pytorch-forge-08', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'training-loop', 'Training Loop', 'Clear old gradients, forward pass, loss, backward pass, optimizer step -- the same five steps, in the same order, for every network this pathway will ever train.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"training-loop-sim"}'::jsonb, '{"xp":360,"credits":85}'::jsonb, false, 8),
  ('mission-ai-pytorch-forge-09', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'validation-loop', 'Validation Loop', 'Training and evaluating the same network are not the same operation. Dropout and BatchNorm behave differently depending on which mode the model is told it is in.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"validation-loop-sim"}'::jsonb, '{"xp":360,"credits":90}'::jsonb, false, 9),
  ('mission-ai-pytorch-forge-10', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'optimizers', 'Optimizers', 'An optimizer only knows the parameters it was handed at construction, and only ever reads the gradients already sitting on them.', 'intermediate', ARRAY['elena'], '{"requiredMissionIds":["mission-ai-pytorch-forge-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"optimizers-sim"}'::jsonb, '{"xp":370,"credits":90}'::jsonb, false, 10),
  ('mission-ai-pytorch-forge-11', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'saving-models', 'Saving Models', 'Save the parameter values, not the Python object itself. Load them into a freshly built model of the same shape, and check its work in evaluation mode, every time.', 'intermediate', ARRAY['elena','byte'], '{"requiredMissionIds":["mission-ai-pytorch-forge-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"saving-models-sim"}'::jsonb, '{"xp":370,"credits":90}'::jsonb, false, 11),
  ('mission-ai-pytorch-forge-12', 'world-ai-pytorch-forge', 'campaign-ai-pytorch-forge', 'operation-ai-pytorch-forge-2', 'train-without-the-wizard', 'Train Without the Wizard', 'Byte''s one-line training wizard reports a good number on every run. Before Cipher Division trusts one of them, somebody has to read exactly what the wizard''s validation step actually does.', 'boss', ARRAY['maya','elena','byte'], '{"requiredMissionIds":["mission-ai-pytorch-forge-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"train-without-the-wizard-boss-sim"}'::jsonb, '{"xp":850,"credits":190,"badgeIds":["train-without-the-wizard"],"skillXp":{"pytorch":55,"ai_ml_fundamentals":20}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-pytorch-forge-01', 1, 'maya', 'The overfit stress test held. Diagnosed, fixed, and proven honest on a held-out set nobody tuned against. That network can finally be trusted.'),
  ('mission-ai-pytorch-forge-01', 2, 'maya', 'Which means it is time to leave the toy examples behind. A stable, honestly-trained network is ready for something real, and I want the next one built in an actual framework, not another loop we wrote from scratch.'),
  ('mission-ai-pytorch-forge-01', 3, 'elena', 'Agreed on the framework. Not agreed on skipping the internals. PyTorch will hide tensors, autograd, modules and data loading behind convenient defaults the moment we let it. I want us to build one primitive at a time first, so nobody in this room ever has to trust a hidden default again.'),
  ('mission-ai-pytorch-forge-01', 4, 'maya', 'Then that is the rule for this Act. Every shortcut PyTorch offers gets understood before it gets used.'),
  ('mission-ai-pytorch-forge-01', 5, 'elena', 'Starting with the most basic object in the entire framework. Before a network, before a layer, before a gradient, everything in PyTorch is built out of one thing: the tensor.'),

  ('mission-ai-pytorch-forge-02', 1, 'elena', 'Tensors are not just numbers, they have shape: how many dimensions, and how large each one is. Get the shape wrong and PyTorch will not politely correct it. It will refuse to run the operation.'),
  ('mission-ai-pytorch-forge-02', 2, 'elena', 'A batch of 32 grayscale 28 by 28 images is not a mystery object, it is a tensor of shape (32, 1, 28, 28): batch, channels, height, width. Every layer downstream expects that exact convention.'),
  ('mission-ai-pytorch-forge-02', 3, 'elena', 'Broadcasting lets PyTorch line up tensors of different shapes automatically, but only under specific rules. Outside those rules, a shape mismatch is not a warning, it is a crash, and a useful one. Read the error, it names the exact shapes that disagreed.'),

  ('mission-ai-pytorch-forge-03', 1, 'elena', 'Every tensor lives somewhere: CPU memory, or a GPU''s memory, and that location is its device. Two tensors on different devices cannot be combined in a single operation, full stop.'),
  ('mission-ai-pytorch-forge-03', 2, 'byte', 'I have watched this exact error take down a training run on the very first line: tensors expected on the same device, but found two. Usually because one tensor got created before the .to(device) call and never moved.'),
  ('mission-ai-pytorch-forge-03', 3, 'elena', 'The pattern that avoids it: decide the device once, up front, then move the model and every tensor that touches it, inputs, labels, everything, onto that same device before anything runs.'),

  ('mission-ai-pytorch-forge-04', 1, 'elena', 'Autograd is what makes training possible without hand-deriving a single gradient. Any tensor created with requires_grad set to True gets tracked in a computational graph as it is used in operations.'),
  ('mission-ai-pytorch-forge-04', 2, 'elena', 'Call .backward() on a final scalar value, the loss, and PyTorch walks that graph backward, computing the gradient of the loss with respect to every tracked tensor, and storing it in that tensor''s .grad.'),
  ('mission-ai-pytorch-forge-04', 3, 'elena', 'Miss requires_grad on the tensors that are supposed to learn, and there is no graph to walk. Backward has nothing to compute, and it will tell you exactly that.'),

  ('mission-ai-pytorch-forge-05', 1, 'elena', 'nn.Module is the base class for every layer and every network in PyTorch. It exists to solve one problem: keeping track of every parameter a model owns, automatically, so nothing gets left out of training.'),
  ('mission-ai-pytorch-forge-05', 2, 'elena', 'Subclass it, call the parent constructor first, define layers as attributes in __init__, and describe the forward pass in forward(). Skip that parent constructor call and nn.Module has nowhere to register anything assigned after it.'),
  ('mission-ai-pytorch-forge-05', 3, 'elena', 'That is not a style preference. It is the one line that makes every other convenience in this framework actually work.'),

  ('mission-ai-pytorch-forge-06', 1, 'elena', 'A Dataset is a contract, not a data structure: implement __len__ to report how many examples exist, and __getitem__ to return exactly one example by index. Everything else, batching, shuffling, loading in parallel, is somebody else''s job.'),
  ('mission-ai-pytorch-forge-06', 2, 'elena', 'Keep those two methods honest and consistent with each other. An index that returns the wrong label for the wrong reading will not raise an error. It will quietly train the model on lies.'),

  ('mission-ai-pytorch-forge-07', 1, 'elena', 'Dataset answers one question: how do I get example number seven. DataLoader answers a different one: how do I turn thousands of single examples into shuffled, batched tensors a training loop can actually consume.'),
  ('mission-ai-pytorch-forge-07', 2, 'byte', 'The distinction matters because the two jobs do not mix well. Random access to one example, and organizing many examples into batches efficiently, are different problems with different solutions.'),
  ('mission-ai-pytorch-forge-07', 3, 'elena', 'Iterate a DataLoader with a for loop, once per epoch, and it hands back one batch at a time, reshuffled if you asked for it. Reach for it any other way, and it stops behaving like the rest of the loop expects.'),

  ('mission-ai-pytorch-forge-08', 1, 'elena', 'Every PyTorch training loop, however dressed up, is the same five steps in the same order: clear old gradients, run the forward pass, compute the loss, run backward to get new gradients, then step the optimizer.'),
  ('mission-ai-pytorch-forge-08', 2, 'elena', 'Reorder them and the loop still runs. It just trains on nonsense. This step order is not a style convention. It is the actual mechanism.'),

  ('mission-ai-pytorch-forge-09', 1, 'elena', 'Training and evaluating a network are not the same operation, even though both just run data through the model. Layers like Dropout and BatchNorm behave differently depending on which mode the model is in.'),
  ('mission-ai-pytorch-forge-09', 2, 'elena', 'model.eval() switches that behavior off for evaluation: Dropout stops zeroing activations, BatchNorm uses its running statistics instead of the current batch. model.train() switches it back on. Forget either call and the model being measured is not the one that was actually trained.'),
  ('mission-ai-pytorch-forge-09', 3, 'elena', 'Wrap the whole validation pass in torch.no_grad() as well. Nothing in validation needs a gradient, and building the graph anyway wastes memory for no benefit.'),

  ('mission-ai-pytorch-forge-10', 1, 'elena', 'An optimizer does exactly one job: read the .grad every tracked parameter accumulated during backward, and use it to update that parameter''s value according to some rule, plain SGD, or something adaptive like Adam.'),
  ('mission-ai-pytorch-forge-10', 2, 'elena', 'It only knows about the parameters it was handed at construction. Rebuild the model after the optimizer already exists, and the optimizer keeps faithfully updating parameters that no forward pass ever touches again.'),

  ('mission-ai-pytorch-forge-11', 1, 'elena', 'Save a model''s state_dict, its parameter values as a plain dictionary, not the whole Python object. The object depends on the exact class definition and file layout at save time. The state_dict does not.'),
  ('mission-ai-pytorch-forge-11', 2, 'byte', 'Loading it back is two steps, not one: construct the same architecture fresh, then call load_state_dict on it with the saved dictionary. Skip the fresh construction and there is no matching structure for the weights to land in.'),
  ('mission-ai-pytorch-forge-11', 3, 'elena', 'And after loading a model for inference, the exact same rule from validation applies. Nobody skips model.eval() before checking its work. Not even for a quick sanity check.'),

  ('mission-ai-pytorch-forge-12', 1, 'byte', 'Before Elena finishes hand-writing our first real training script, I built something faster. One call, train_and_validate: point it at a model and both loaders, and it trains and reports validation numbers back, no extra code needed.'),
  ('mission-ai-pytorch-forge-12', 2, 'maya', 'And the numbers.'),
  ('mission-ai-pytorch-forge-12', 3, 'byte', 'Good. Consistently good, across three separate runs this week.'),
  ('mission-ai-pytorch-forge-12', 4, 'elena', 'That is exactly the sentence that made me distrust my own spreadsheet three Acts ago. A number that looks fine at a glance, from a tool nobody in this room has actually read yet.'),
  ('mission-ai-pytorch-forge-12', 5, 'maya', 'Then read it before it trains anything else. Every line, the same discipline this whole Act was built on.'),
  ('mission-ai-pytorch-forge-12', 6, 'byte', '...Go ahead. I would rather be wrong in front of you now than wrong in production later.'),
  ('mission-ai-pytorch-forge-12', 7, 'elena', 'Three checks. What the wizard''s own code actually does during validation. Why that makes every number it ever reported unreliable. And whether a corrected pass finally gives us something we can trust.'),
  ('mission-ai-pytorch-forge-12', 8, 'maya', 'Knowing PyTorch this well raises an obvious question: is it even the right framework for what Cipher Division needs to ship. There is another one, and the answer might not be a technical one at all.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-pytorch-forge-01-o1', 'mission-ai-pytorch-forge-01', 1, 'Define the primitive', 'Identify what a torch.Tensor actually is, underneath the framework.'),
  ('mission-ai-pytorch-forge-01-o2', 'mission-ai-pytorch-forge-01', 2, 'Spot the dtype trap', 'Find which line creates the dtype mismatch that crashes a simple matrix multiply.'),

  ('mission-ai-pytorch-forge-02-o1', 'mission-ai-pytorch-forge-02', 1, 'Read a shape', 'Identify the correct tensor shape for a batch of images, following PyTorch convention.'),
  ('mission-ai-pytorch-forge-02-o2', 'mission-ai-pytorch-forge-02', 2, 'Debug the reshape', 'Find which line drops a dimension it should have kept.'),

  ('mission-ai-pytorch-forge-03-o1', 'mission-ai-pytorch-forge-03', 1, 'Explain device placement', 'State why tensors on different devices cannot be combined in one operation.'),
  ('mission-ai-pytorch-forge-03-o2', 'mission-ai-pytorch-forge-03', 2, 'Debug the device mismatch', 'Find which tensor was never moved onto the chosen device.'),

  ('mission-ai-pytorch-forge-04-o1', 'mission-ai-pytorch-forge-04', 1, 'Explain autograd', 'State what calling backward on a loss tensor actually computes.'),
  ('mission-ai-pytorch-forge-04-o2', 'mission-ai-pytorch-forge-04', 2, 'Debug the missing graph', 'Find which tensor was never told to track gradients in the first place.'),

  ('mission-ai-pytorch-forge-05-o1', 'mission-ai-pytorch-forge-05', 1, 'Explain nn.Module', 'Identify what nn.Module actually gives a custom layer or network.'),
  ('mission-ai-pytorch-forge-05-o2', 'mission-ai-pytorch-forge-05', 2, 'Debug the missing constructor', 'Find which line fails because the parent constructor was never called.'),

  ('mission-ai-pytorch-forge-06-o1', 'mission-ai-pytorch-forge-06', 1, 'Define the Dataset contract', 'Identify the two methods every PyTorch Dataset must implement.'),
  ('mission-ai-pytorch-forge-06-o2', 'mission-ai-pytorch-forge-06', 2, 'Debug the misaligned label', 'Find which line pairs every reading with the wrong label.'),

  ('mission-ai-pytorch-forge-07-o1', 'mission-ai-pytorch-forge-07', 1, 'Explain the split', 'State why Dataset and DataLoader are kept as two separate classes.'),
  ('mission-ai-pytorch-forge-07-o2', 'mission-ai-pytorch-forge-07', 2, 'Debug the frozen batch', 'Find which line causes the model to see only the first batch, every epoch.'),

  ('mission-ai-pytorch-forge-08-o1', 'mission-ai-pytorch-forge-08', 1, 'Order the training loop', 'Put the five steps of a standard training loop in the order they actually run.'),
  ('mission-ai-pytorch-forge-08-o2', 'mission-ai-pytorch-forge-08', 2, 'Debug the missing reset', 'Find which line is where gradients from the previous batch silently accumulate.'),

  ('mission-ai-pytorch-forge-09-o1', 'mission-ai-pytorch-forge-09', 1, 'Explain eval mode', 'State what calling model.eval() before validation actually changes.'),
  ('mission-ai-pytorch-forge-09-o2', 'mission-ai-pytorch-forge-09', 2, 'Debug the missing no_grad', 'Find which line wastes memory building a graph validation never uses.'),

  ('mission-ai-pytorch-forge-10-o1', 'mission-ai-pytorch-forge-10', 1, 'Explain optimizer.step()', 'State exactly what an optimizer step reads and updates.'),
  ('mission-ai-pytorch-forge-10-o2', 'mission-ai-pytorch-forge-10', 2, 'Debug the stale reference', 'Find which line disconnects the optimizer from the model actually being trained.'),

  ('mission-ai-pytorch-forge-11-o1', 'mission-ai-pytorch-forge-11', 1, 'Explain state_dict', 'Identify the recommended way to save a trained PyTorch model.'),
  ('mission-ai-pytorch-forge-11-o2', 'mission-ai-pytorch-forge-11', 2, 'Debug the missing eval before inference', 'Find which line runs inference with the model still in training mode.'),

  ('mission-ai-pytorch-forge-12-o1', 'mission-ai-pytorch-forge-12', 1, 'Diagnose the blind spot', 'Find the evidence proving the wizard never switches the network into evaluation mode before validating.'),
  ('mission-ai-pytorch-forge-12-o2', 'mission-ai-pytorch-forge-12', 2, 'Judge why the numbers were unreliable', 'Find the evidence proving the wizard''s reported validation numbers were never a stable measurement.'),
  ('mission-ai-pytorch-forge-12-o3', 'mission-ai-pytorch-forge-12', 3, 'Confirm the corrected fix', 'Find the evidence proving a corrected validation pass produces a real, trustworthy number.'),
  ('mission-ai-pytorch-forge-12-o4', 'mission-ai-pytorch-forge-12', 4, 'Synthesize the verdict', 'Having diagnosed the blind spot, judged its consequences, and confirmed the fix, state Cipher Division''s verdict on the wizard.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-pytorch-forge-01-o1-c1', 'mission-ai-pytorch-forge-01-o1', 1, 'multiple_choice', 'What is a torch.Tensor, at its core?', '{"question":"What is a torch.Tensor, at its core?","options":[{"id":"a","text":"A Python list with a few extra methods"},{"id":"b","text":"An n-dimensional array with a dtype and a device, the core data structure every PyTorch operation is built on"},{"id":"c","text":"A file format used only for saving trained models"},{"id":"d","text":"A synonym for a neural network layer"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-01-o2-c1', 'mission-ai-pytorch-forge-01-o2', 1, 'code_debugging', 'This raises a dtype mismatch error the moment it runs. Which line is where the mismatch actually gets created?', '{"language":"python","code":"import torch\n\ndata = [[1, 2], [3, 4]]\nx = torch.tensor(data)\nweights = torch.tensor([[0.5, 0.5], [0.5, 0.5]])\noutput = x @ weights\nprint(output)","question":"This raises a dtype mismatch error the moment it runs. Which line is where the mismatch actually gets created?"}'::jsonb, '{"requiredLineIds":["x = torch.tensor(data)"]}'::jsonb),

  ('mission-ai-pytorch-forge-02-o1-c1', 'mission-ai-pytorch-forge-02-o1', 1, 'multiple_choice', 'A tensor holds a batch of 32 grayscale 28x28 images. What shape should it have, following PyTorch convention?', '{"question":"A tensor holds a batch of 32 grayscale 28x28 images. What shape should it have, following PyTorch convention?","options":[{"id":"a","text":"(28, 28, 32, 1)"},{"id":"b","text":"(32, 1, 28, 28)"},{"id":"c","text":"(32, 28, 28, 1)"},{"id":"d","text":"(1, 32, 28, 28)"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-02-o2-c1', 'mission-ai-pytorch-forge-02-o2', 1, 'code_debugging', 'view() raises a RuntimeError here about the number of elements not matching. Which line drops a dimension it should have kept?', '{"language":"python","code":"import torch\n\nimages = torch.randn(4, 3, 28, 28)\nflat = images.view(4, 28 * 28)\nprint(flat.shape)","question":"view() raises a RuntimeError here about the number of elements not matching. Which line drops a dimension it should have kept?"}'::jsonb, '{"requiredLineIds":["flat = images.view(4, 28 * 28)"]}'::jsonb),

  ('mission-ai-pytorch-forge-03-o1-c1', 'mission-ai-pytorch-forge-03-o1', 1, 'multiple_choice', 'Why can two tensors on different devices not be combined in one operation?', '{"question":"Why can two tensors on different devices not be combined in one operation?","options":[{"id":"a","text":"PyTorch arbitrarily forbids it for reasons unrelated to performance"},{"id":"b","text":"Combining them would require copying data between separate physical memory spaces, which PyTorch requires to be an explicit step, not a hidden one"},{"id":"c","text":"Tensors on different devices always have different dtypes as well"},{"id":"d","text":"They can actually be combined automatically, PyTorch just does not report it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-03-o2-c1', 'mission-ai-pytorch-forge-03-o2', 1, 'code_debugging', 'This raises a RuntimeError about tensors on different devices. Which line creates the tensor that was never moved onto device?', '{"language":"python","code":"import torch\n\ndevice = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\nmodel_weights = torch.randn(10, 10, device=device)\ninputs = torch.randn(10, 10)\noutput = inputs @ model_weights","question":"This raises a RuntimeError about tensors on different devices. Which line creates the tensor that was never moved onto device?"}'::jsonb, '{"requiredLineIds":["inputs = torch.randn(10, 10)"]}'::jsonb),

  ('mission-ai-pytorch-forge-04-o1-c1', 'mission-ai-pytorch-forge-04-o1', 1, 'multiple_choice', 'What does calling .backward() on a loss tensor actually do?', '{"question":"What does calling .backward() on a loss tensor actually do?","options":[{"id":"a","text":"Resets every parameter to its initial value"},{"id":"b","text":"Walks the computational graph backward from that tensor, computing the gradient of it with respect to every tensor that requires_grad, and storing the result in .grad"},{"id":"c","text":"Deletes the computational graph immediately, before any gradient is computed"},{"id":"d","text":"Runs the forward pass a second time to double-check it"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-04-o2-c1', 'mission-ai-pytorch-forge-04-o2', 1, 'code_debugging', 'y.backward() raises a RuntimeError because y has no grad_fn. Which line is the root cause?', '{"language":"python","code":"import torch\n\nw = torch.randn(3, 3)\nx = torch.randn(3, 3)\ny = (w @ x).sum()\ny.backward()\nprint(w.grad)","question":"y.backward() raises a RuntimeError because y has no grad_fn. Which line is the root cause?"}'::jsonb, '{"requiredLineIds":["w = torch.randn(3, 3)"]}'::jsonb),

  ('mission-ai-pytorch-forge-05-o1-c1', 'mission-ai-pytorch-forge-05-o1', 1, 'multiple_choice', 'The main thing nn.Module gives a custom layer or network is...', '{"question":"The main thing nn.Module gives a custom layer or network is...","options":[{"id":"a","text":"Faster matrix multiplication"},{"id":"b","text":"Automatic tracking of every parameter assigned as an attribute, so calling .parameters() finds all of them for the optimizer"},{"id":"c","text":"A built-in dataset loader"},{"id":"d","text":"A guarantee the model will not overfit"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-05-o2-c1', 'mission-ai-pytorch-forge-05-o2', 1, 'code_debugging', 'Constructing TinyNet() raises an AttributeError before forward ever runs. Which line fails, and why?', '{"language":"python","code":"import torch.nn as nn\n\nclass TinyNet(nn.Module):\n    def __init__(self):\n        self.linear = nn.Linear(10, 1)\n\n    def forward(self, x):\n        return self.linear(x)","question":"Constructing TinyNet() raises an AttributeError before forward ever runs. Which line fails, and why?"}'::jsonb, '{"requiredLineIds":["        self.linear = nn.Linear(10, 1)"]}'::jsonb),

  ('mission-ai-pytorch-forge-06-o1-c1', 'mission-ai-pytorch-forge-06-o1', 1, 'multiple_choice', 'A PyTorch Dataset is required to implement...', '{"question":"A PyTorch Dataset is required to implement...","options":[{"id":"a","text":"train() and eval()"},{"id":"b","text":"__len__ and __getitem__"},{"id":"c","text":"forward() and backward()"},{"id":"d","text":"batch() and shuffle()"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-06-o2-c1', 'mission-ai-pytorch-forge-06-o2', 1, 'code_debugging', 'Every example this Dataset returns is paired with the wrong label, and the last index raises an IndexError. Which line is responsible?', '{"language":"python","code":"import torch\nfrom torch.utils.data import Dataset\n\nclass ReadingsDataset(Dataset):\n    def __init__(self, readings, labels):\n        self.readings = readings\n        self.labels = labels\n\n    def __len__(self):\n        return len(self.readings)\n\n    def __getitem__(self, idx):\n        return self.readings[idx], self.labels[idx + 1]","question":"Every example this Dataset returns is paired with the wrong label, and the last index raises an IndexError. Which line is responsible?"}'::jsonb, '{"requiredLineIds":["        return self.readings[idx], self.labels[idx + 1]"]}'::jsonb),

  ('mission-ai-pytorch-forge-07-o1-c1', 'mission-ai-pytorch-forge-07-o1', 1, 'multiple_choice', 'Why does PyTorch separate Dataset from DataLoader instead of combining them into one class?', '{"question":"Why does PyTorch separate Dataset from DataLoader instead of combining them into one class?","options":[{"id":"a","text":"It is a historical accident with no real reason behind it"},{"id":"b","text":"Dataset handles single-example access; DataLoader handles batching, shuffling and parallel loading -- two different jobs with different concerns"},{"id":"c","text":"DataLoader fully replaces Dataset in modern PyTorch code"},{"id":"d","text":"Dataset is only used for validation, DataLoader only for training"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-07-o2-c1', 'mission-ai-pytorch-forge-07-o2', 1, 'code_debugging', 'The loss never changes across epochs, as if the model only ever sees one batch. Which line causes that?', '{"language":"python","code":"from torch.utils.data import DataLoader\n\ntrain_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)\n\nfor epoch in range(num_epochs):\n    batch_inputs, batch_labels = next(iter(train_loader))\n    train_step(batch_inputs, batch_labels)","question":"The loss never changes across epochs, as if the model only ever sees one batch. Which line causes that?"}'::jsonb, '{"requiredLineIds":["    batch_inputs, batch_labels = next(iter(train_loader))"]}'::jsonb),

  ('mission-ai-pytorch-forge-08-o1-c1', 'mission-ai-pytorch-forge-08-o1', 1, 'interactive_diagram', 'Order the five steps of a standard PyTorch training loop, for one batch, from first to last.', '{"diagramId":"pytorch-training-loop","hotspots":[{"id":"clear","label":"Clear old gradients: optimizer.zero_grad()","explanation":"Gradients accumulate by default. Clearing them first keeps each step measuring only the current batch."},{"id":"forward","label":"Forward pass: outputs = model(inputs)","explanation":"Run the current batch through the network using its current parameters."},{"id":"loss","label":"Compute the loss: loss = loss_fn(outputs, labels)","explanation":"Compare predictions to the true labels and reduce the difference to a single scalar."},{"id":"backward","label":"Backward pass: loss.backward()","explanation":"Walk the computational graph backward, filling in .grad for every tracked parameter."},{"id":"step","label":"Optimizer step: optimizer.step()","explanation":"Use the freshly computed gradients to actually update every tracked parameter''s value."}],"task":"Order the five steps of a standard PyTorch training loop, for one batch, from first to last."}'::jsonb, '{"correctOrderIds":["clear","forward","loss","backward","step"]}'::jsonb),
  ('mission-ai-pytorch-forge-08-o2-c1', 'mission-ai-pytorch-forge-08-o2', 1, 'code_debugging', 'optimizer.zero_grad() is never called anywhere in this loop. Which line is where gradients from the previous batch silently accumulate?', '{"language":"python","code":"for epoch in range(num_epochs):\n    for inputs, labels in train_loader:\n        outputs = model(inputs)\n        loss = loss_fn(outputs, labels)\n        loss.backward()\n        optimizer.step()","question":"optimizer.zero_grad() is never called anywhere in this loop. Which line is where gradients from the previous batch silently accumulate?"}'::jsonb, '{"requiredLineIds":["        loss.backward()"]}'::jsonb),

  ('mission-ai-pytorch-forge-09-o1-c1', 'mission-ai-pytorch-forge-09-o1', 1, 'multiple_choice', 'Calling model.eval() before running validation mainly changes the behavior of...', '{"question":"Calling model.eval() before running validation mainly changes the behavior of...","options":[{"id":"a","text":"The optimizer"},{"id":"b","text":"Layers like Dropout and BatchNorm, which behave differently during training versus evaluation"},{"id":"c","text":"The formula used by the loss function"},{"id":"d","text":"The dtype every tensor is stored in"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-09-o2-c1', 'mission-ai-pytorch-forge-09-o2', 1, 'code_debugging', 'This validation pass runs correctly but wastes memory building a computational graph it never uses. Which line is where that unnecessary graph gets built?', '{"language":"python","code":"def validate(model, val_loader, loss_fn):\n    model.eval()\n    total_loss = 0.0\n    for inputs, labels in val_loader:\n        outputs = model(inputs)\n        loss = loss_fn(outputs, labels)\n        total_loss += loss.item()\n    return total_loss / len(val_loader)","question":"This validation pass runs correctly but wastes memory building a computational graph it never uses. Which line is where that unnecessary graph gets built?"}'::jsonb, '{"requiredLineIds":["        outputs = model(inputs)"]}'::jsonb),

  ('mission-ai-pytorch-forge-10-o1-c1', 'mission-ai-pytorch-forge-10-o1', 1, 'multiple_choice', 'What does optimizer.step() actually do?', '{"question":"What does optimizer.step() actually do?","options":[{"id":"a","text":"Runs the forward pass again"},{"id":"b","text":"Reads the .grad already computed for each parameter it was given, and updates the value of that parameter according to the update rule the optimizer implements"},{"id":"c","text":"Computes the loss for the current batch"},{"id":"d","text":"Deletes parameters that are no longer being used"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-10-o2-c1', 'mission-ai-pytorch-forge-10-o2', 1, 'code_debugging', 'Training runs without error, but the loss never improves no matter how long it trains. Which line creates the disconnect between the optimizer and the model actually being trained?', '{"language":"python","code":"model = TinyNet()\noptimizer = torch.optim.Adam(model.parameters(), lr=1e-3)\nmodel = TinyNet()  # reset before training starts\n\nfor epoch in range(num_epochs):\n    train_one_epoch(model, optimizer)","question":"Training runs without error, but the loss never improves no matter how long it trains. Which line creates the disconnect between the optimizer and the model actually being trained?"}'::jsonb, '{"requiredLineIds":["model = TinyNet()  # reset before training starts"]}'::jsonb),

  ('mission-ai-pytorch-forge-11-o1-c1', 'mission-ai-pytorch-forge-11-o1', 1, 'multiple_choice', 'The recommended way to save a trained PyTorch model is...', '{"question":"The recommended way to save a trained PyTorch model is...","options":[{"id":"a","text":"torch.save(model, path), saving the entire Python object"},{"id":"b","text":"torch.save(model.state_dict(), path), saving just the parameter values as a plain dictionary"},{"id":"c","text":"Copying the .py file that defines the model class"},{"id":"d","text":"Saving only the optimizer state"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-pytorch-forge-11-o2-c1', 'mission-ai-pytorch-forge-11-o2', 1, 'code_debugging', 'Predictions from this loaded model are inconsistent between runs on the exact same input. Which line is missing the call that would fix it?', '{"language":"python","code":"model = TinyNet()\nmodel.load_state_dict(torch.load(\"weights.pt\"))\npredictions = model(new_inputs)","question":"Predictions from this loaded model are inconsistent between runs on the exact same input. Which line is missing the call that would fix it?"}'::jsonb, '{"requiredLineIds":["predictions = model(new_inputs)"]}'::jsonb),

  ('mission-ai-pytorch-forge-12-o1-c1', 'mission-ai-pytorch-forge-12-o1', 1, 'investigation', 'Which evidence proves the wizard never actually switches the network into evaluation mode before validating?', '{"evidence":[{"id":"e1","label":"Wizard source, train_and_validate","detail":"def train_and_validate(model, train_loader, val_loader, optimizer, loss_fn, epochs):\n    model.train()\n    for epoch in range(epochs):\n        for inputs, labels in train_loader:\n            optimizer.zero_grad()\n            outputs = model(inputs)\n            loss = loss_fn(outputs, labels)\n            loss.backward()\n            optimizer.step()\n        val_loss = 0.0\n        with torch.no_grad():\n            for inputs, labels in val_loader:\n                outputs = model(inputs)\n                val_loss += loss_fn(outputs, labels).item()\n        print(epoch, val_loss / len(val_loader))\n    return model"},{"id":"e2","label":"Model architecture","detail":"TinyNet contains nn.Dropout(0.5) after its first layer and a BatchNorm1d layer before its output, and both behave differently in training mode versus evaluation mode"},{"id":"e3","label":"Validation metrics log","detail":"On the same fixed validation set, with no shuffling, the reported loss is different on almost every epoch, even late in training when the model should have stabilized"}],"question":"Which evidence proves the wizard never actually switches the network into evaluation mode before validating?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-pytorch-forge-12-o2-c1', 'mission-ai-pytorch-forge-12-o2', 1, 'investigation', 'Which evidence proves the reported validation numbers were never a stable measurement of anything?', '{"evidence":[{"id":"e1","label":"Repeated pass, training mode, identical batch","detail":"The same validation batch, run twice back to back with no data change and no code change, produces loss values of 0.41 and then 0.53"},{"id":"e2","label":"Repeated pass, evaluation mode, identical batch","detail":"The identical batch, run twice back to back after adding model.eval(), produces a loss of 0.44 both times"},{"id":"e3","label":"Wizard changelog","detail":"A recent commit reformatted the print statements for readability. No logic changed"}],"question":"Which evidence proves the reported validation numbers were never a stable measurement of anything?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),
  ('mission-ai-pytorch-forge-12-o3-c1', 'mission-ai-pytorch-forge-12-o3', 1, 'investigation', 'Which evidence confirms the corrected validation pass now produces a real, trustworthy number?', '{"evidence":[{"id":"e1","label":"Corrected validation block","detail":"model.eval() is added immediately before the torch.no_grad() validation block, and model.train() is called again immediately after it, before the training loop for the next epoch resumes"},{"id":"e2","label":"Re-run validation log","detail":"The same validation batch, same weights, run three times back to back after the fix: loss is 0.44, 0.44, 0.44, identical every time"},{"id":"e3","label":"Held-out test set comparison","detail":"The corrected model scores 0.45 loss on a held-out test set it never saw during training or tuning, within normal noise of the corrected validation number"}],"question":"Which evidence confirms the corrected validation pass now produces a real, trustworthy number?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-pytorch-forge-12-o4-c1', 'mission-ai-pytorch-forge-12-o4', 1, 'boss_encounter', 'Having diagnosed the blind spot, judged its consequences, and confirmed the fix, state Cipher Division''s verdict.', '{"stages":[{"objectiveRef":"mission-ai-pytorch-forge-12-o1","label":"Diagnose the blind spot"},{"objectiveRef":"mission-ai-pytorch-forge-12-o2","label":"Judge why the numbers were unreliable"},{"objectiveRef":"mission-ai-pytorch-forge-12-o3","label":"Confirm the corrected fix"}],"task":"State the verdict in one sentence: the wizard trains correctly but never calls model.eval() before validating, so Dropout and BatchNorm kept behaving as if still training, every validation score it ever reported was noise dressed up as a metric, and adding the missing eval and train mode switch is what finally makes the number real."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-pytorch-forge-12-o1","mission-ai-pytorch-forge-12-o2","mission-ai-pytorch-forge-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-pytorch-forge-01-o1-c1', 'orientation', 'Think about what a tensor actually stores, not what a model or a layer stores.', 10, 1),
  ('mission-ai-pytorch-forge-01-o1-c1', 'solution', 'A tensor is PyTorch''s core n-dimensional array, carrying a dtype and a device alongside its values -- every layer, loss and gradient in the framework is ultimately just tensors.', 20, 2),
  ('mission-ai-pytorch-forge-01-o2-c1', 'orientation', 'Check what dtype each tensor actually ends up with, not just what values they hold.', 10, 1),
  ('mission-ai-pytorch-forge-01-o2-c1', 'concept', 'torch.tensor infers a dtype from the Python values it is given -- a list of plain ints becomes int64 by default, not float32.', 20, 2),
  ('mission-ai-pytorch-forge-01-o2-c1', 'solution', 'data is a list of ints, so x = torch.tensor(data) becomes an int64 tensor, while weights, built from 0.5 literals, is float32 -- matmul refuses to combine the two dtypes.', 30, 3),

  ('mission-ai-pytorch-forge-02-o1-c1', 'orientation', 'PyTorch convention orders dimensions batch first, then channels, then the spatial dimensions.', 10, 1),
  ('mission-ai-pytorch-forge-02-o1-c1', 'solution', '(32, 1, 28, 28): a batch of 32, 1 channel, 28 by 28 pixels, in that order.', 20, 2),
  ('mission-ai-pytorch-forge-02-o2-c1', 'orientation', 'Count the total elements in the original tensor, then compare it to what the target shape asks for.', 10, 1),
  ('mission-ai-pytorch-forge-02-o2-c1', 'concept', 'images has 4 times 3 times 28 times 28 elements. The target shape 4 by (28 times 28) only accounts for one of the three non-batch dimensions.', 20, 2),
  ('mission-ai-pytorch-forge-02-o2-c1', 'solution', 'flat = images.view(4, 28 * 28) drops the channel dimension entirely -- it needed to keep all three non-batch dimensions to preserve every element, for example view(4, 3 * 28 * 28).', 30, 3),

  ('mission-ai-pytorch-forge-03-o1-c1', 'orientation', 'Think about what device actually means physically, not just as a Python attribute.', 10, 1),
  ('mission-ai-pytorch-forge-03-o1-c1', 'solution', 'Combining tensors across devices would require silently copying data between separate memory spaces -- PyTorch makes that an explicit .to(device) call instead of a hidden cost.', 20, 2),
  ('mission-ai-pytorch-forge-03-o2-c1', 'orientation', 'Compare the device argument each tensor was actually created with.', 10, 1),
  ('mission-ai-pytorch-forge-03-o2-c1', 'concept', 'model_weights is explicitly created with device=device. inputs is not, so it defaults to CPU regardless of what device was chosen.', 20, 2),
  ('mission-ai-pytorch-forge-03-o2-c1', 'solution', 'inputs = torch.randn(10, 10) never receives device=device, so it stays on CPU while model_weights lives on whatever device was selected -- the matmul cannot combine the two.', 30, 3),

  ('mission-ai-pytorch-forge-04-o1-c1', 'orientation', 'Autograd only tracks tensors that were explicitly told to be tracked.', 10, 1),
  ('mission-ai-pytorch-forge-04-o1-c1', 'solution', 'backward() walks the graph built by every tracked operation and fills in .grad for each tensor that requires_grad -- it is the mechanism that replaces hand-deriving gradients.', 20, 2),
  ('mission-ai-pytorch-forge-04-o2-c1', 'orientation', 'Check requires_grad on every tensor that feeds into y, not just y itself.', 10, 1),
  ('mission-ai-pytorch-forge-04-o2-c1', 'concept', 'Neither w nor x was created with requires_grad=True, so PyTorch never builds a graph for the operations that produced y -- there is nothing for backward to walk.', 20, 2),
  ('mission-ai-pytorch-forge-04-o2-c1', 'solution', 'w = torch.randn(3, 3) is the tensor that was supposed to learn, and it never gets requires_grad=True -- add it there and the graph, and the gradient, both exist.', 30, 3),

  ('mission-ai-pytorch-forge-05-o1-c1', 'orientation', 'Think about what has to exist before a layer can be registered as part of a model.', 10, 1),
  ('mission-ai-pytorch-forge-05-o1-c1', 'solution', 'nn.Module keeps an internal registry of every submodule and parameter assigned to it, so .parameters(), and the optimizer, can find all of them automatically.', 20, 2),
  ('mission-ai-pytorch-forge-05-o2-c1', 'orientation', '__init__ never calls the parent class constructor before assigning anything.', 10, 1),
  ('mission-ai-pytorch-forge-05-o2-c1', 'concept', 'nn.Module.__setattr__ relies on internal registries that only exist after super().__init__() runs -- skip that call and there is nothing for an assigned submodule to register into.', 20, 2),
  ('mission-ai-pytorch-forge-05-o2-c1', 'solution', 'self.linear = nn.Linear(10, 1) is the line that fails, because __init__ never calls super().__init__() first -- add that one line and the assignment succeeds.', 30, 3),

  ('mission-ai-pytorch-forge-06-o1-c1', 'orientation', 'One method reports size, the other retrieves a single example -- DataLoader depends on both being correct.', 10, 1),
  ('mission-ai-pytorch-forge-06-o1-c1', 'solution', '__len__ reports how many examples exist, __getitem__ returns one example by index -- that is the entire contract a Dataset must satisfy.', 20, 2),
  ('mission-ai-pytorch-forge-06-o2-c1', 'orientation', 'Compare the index used for readings to the index used for labels on the same line.', 10, 1),
  ('mission-ai-pytorch-forge-06-o2-c1', 'concept', 'readings[idx] and labels[idx + 1] use two different indices for what should be the same example -- every pair is off by one.', 20, 2),
  ('mission-ai-pytorch-forge-06-o2-c1', 'solution', 'return self.readings[idx], self.labels[idx + 1] pairs each reading with the label belonging to the next example, not its own, and reads past the end of labels on the final index -- it should read self.labels[idx].', 30, 3),

  ('mission-ai-pytorch-forge-07-o1-c1', 'orientation', 'One class knows how to fetch example number seven. The other class knows how to assemble many examples into a batch.', 10, 1),
  ('mission-ai-pytorch-forge-07-o1-c1', 'solution', 'Dataset is single-example access by index. DataLoader wraps it to produce shuffled, batched tensors -- keeping the two apart lets either one change without touching the other.', 20, 2),
  ('mission-ai-pytorch-forge-07-o2-c1', 'orientation', 'iter(train_loader) creates a brand-new iterator every single time it is called.', 10, 1),
  ('mission-ai-pytorch-forge-07-o2-c1', 'concept', 'Calling iter() fresh each epoch and immediately taking next() from it grabs only the very first batch of a freshly reshuffled loader -- the rest of the dataset is never reached.', 20, 2),
  ('mission-ai-pytorch-forge-07-o2-c1', 'solution', 'batch_inputs, batch_labels = next(iter(train_loader)) should instead be a for loop over train_loader itself, so every batch in the epoch actually gets consumed instead of just the first one, every time.', 30, 3),

  ('mission-ai-pytorch-forge-08-o1-c1', 'orientation', 'Nothing can be compared to a label until the model has actually produced an output for the current batch.', 10, 1),
  ('mission-ai-pytorch-forge-08-o1-c1', 'concept', 'Gradients have to be computed before an optimizer step can use them, and old gradients have to be cleared before new ones are computed, otherwise they mix.', 20, 2),
  ('mission-ai-pytorch-forge-08-o1-c1', 'solution', 'Clear old gradients, run the forward pass, compute the loss, run backward, then step the optimizer -- in exactly that order, every batch.', 30, 3),
  ('mission-ai-pytorch-forge-08-o2-c1', 'orientation', 'Gradients from backward() do not overwrite .grad by default -- they add to whatever is already sitting there.', 10, 1),
  ('mission-ai-pytorch-forge-08-o2-c1', 'concept', 'Without a zero_grad() call anywhere in the loop, each backward() call adds new gradients on top of whatever was left from every earlier batch, instead of starting from zero.', 20, 2),
  ('mission-ai-pytorch-forge-08-o2-c1', 'solution', 'loss.backward() is where the accumulation actually happens -- with no zero_grad() call before it, each call adds to the existing .grad instead of replacing it, so gradients silently compound across the whole loop.', 30, 3),

  ('mission-ai-pytorch-forge-09-o1-c1', 'orientation', 'Not every layer behaves the same way on every forward pass -- some depend on which mode the model is in.', 10, 1),
  ('mission-ai-pytorch-forge-09-o1-c1', 'solution', 'model.eval() turns off the randomness in Dropout and switches BatchNorm to its running statistics instead of the current batch -- forget it and validation measures a model that is not the one that was actually trained.', 20, 2),
  ('mission-ai-pytorch-forge-09-o2-c1', 'orientation', 'Nothing in a validation pass needs a gradient -- the model is not being updated here.', 10, 1),
  ('mission-ai-pytorch-forge-09-o2-c1', 'concept', 'Without torch.no_grad(), every forward pass still builds a full computational graph for backward, even though backward is never going to be called.', 20, 2),
  ('mission-ai-pytorch-forge-09-o2-c1', 'solution', 'outputs = model(inputs) is where that unused graph gets built -- wrapping the loop body in torch.no_grad() stops PyTorch from tracking operations it will never need to walk backward through.', 30, 3),

  ('mission-ai-pytorch-forge-10-o1-c1', 'orientation', 'The optimizer does not recompute anything itself -- it only consumes what backward() already left behind.', 10, 1),
  ('mission-ai-pytorch-forge-10-o1-c1', 'solution', 'optimizer.step() reads the existing .grad for each parameter and updates that parameter according to the optimizer rule, SGD, Adam, whatever was chosen, and nothing more.', 20, 2),
  ('mission-ai-pytorch-forge-10-o2-c1', 'orientation', 'Check exactly which model object the optimizer was constructed with, versus which model object actually gets trained.', 10, 1),
  ('mission-ai-pytorch-forge-10-o2-c1', 'concept', 'torch.optim.Adam(model.parameters(), ...) captures references to one specific set of parameter tensors at construction time -- it has no way of knowing if the name model later points somewhere else.', 20, 2),
  ('mission-ai-pytorch-forge-10-o2-c1', 'solution', 'model = TinyNet()  # reset before training starts creates a brand-new set of parameters that the optimizer was never given -- optimizer.step() keeps updating the old, now-unused TinyNet forever.', 30, 3),

  ('mission-ai-pytorch-forge-11-o1-c1', 'orientation', 'Think about what has to stay stable for the saved weights to still fit after loading.', 10, 1),
  ('mission-ai-pytorch-forge-11-o1-c1', 'solution', 'Saving state_dict() keeps just the parameter values, independent of the exact class file -- reload it into a freshly constructed instance of the same architecture and the weights fit right back in.', 20, 2),
  ('mission-ai-pytorch-forge-11-o2-c1', 'orientation', 'A freshly constructed model defaults to training mode, and loading weights does not change that.', 10, 1),
  ('mission-ai-pytorch-forge-11-o2-c1', 'concept', 'TinyNet() starts in training mode by default. Loading a state_dict changes the parameter values, not the mode Dropout or BatchNorm layers are running in.', 20, 2),
  ('mission-ai-pytorch-forge-11-o2-c1', 'solution', 'predictions = model(new_inputs) runs with the model still in training mode -- add model.eval() right before it, and predictions become stable and repeatable.', 30, 3),

  ('mission-ai-pytorch-forge-12-o1-c1', 'orientation', 'Read exactly which calls appear inside the wizard''s validation block, not what the function is named.', 10, 1),
  ('mission-ai-pytorch-forge-12-o1-c1', 'concept', 'torch.no_grad() controls whether gradients get tracked. It has nothing to do with whether Dropout or BatchNorm think the model is still training.', 20, 2),
  ('mission-ai-pytorch-forge-12-o1-c1', 'solution', 'e1: the source shows model.train() called once at the very top and model.eval() never called before the validation block -- torch.no_grad() is present and correct, but it does not substitute for switching modes.', 30, 3),
  ('mission-ai-pytorch-forge-12-o2-c1', 'orientation', 'Compare what happens when the exact same batch is scored twice in a row.', 10, 1),
  ('mission-ai-pytorch-forge-12-o2-c1', 'concept', 'A trustworthy validation number should not change when nothing about the model or the data changes between two calls.', 20, 2),
  ('mission-ai-pytorch-forge-12-o2-c1', 'solution', 'e1: the same batch, scored twice back to back in training mode, gives two different losses, 0.41 then 0.53, purely from the randomness in Dropout still being active. That is not noise from the data. It is noise from the mode the model was left in.', 30, 3),
  ('mission-ai-pytorch-forge-12-o3-c1', 'orientation', 'A fix only counts once it is shown to work, not just described.', 10, 1),
  ('mission-ai-pytorch-forge-12-o3-c1', 'concept', 'Repeatability on the same batch proves the mode switch is working. Matching a held-out test set proves the number means something beyond that one batch.', 20, 2),
  ('mission-ai-pytorch-forge-12-o3-c1', 'solution', 'e2: after adding the eval and train mode switching, the same batch produces an identical loss every time, 0.44 three times in a row, proof the number is now a real, reproducible measurement instead of a coin flip.', 30, 3),
  ('mission-ai-pytorch-forge-12-o4-c1', 'orientation', 'Weigh all three findings together: what the code shows, why the numbers were unreliable, and what the corrected re-run proves.', 15, 1),
  ('mission-ai-pytorch-forge-12-o4-c1', 'solution', 'The wizard trains correctly but never calls model.eval() before validating, so Dropout and BatchNorm kept running as if still in training -- every validation score it ever reported was noise, not a measurement. Adding the missing eval and train mode switch, and confirming the fix on a held-out set, is what finally makes the number real.', 25, 2);
