-- Backend Engineering ("The Fracture") Act 11 -- "Database Performance" content.
-- 1 campaign, 2 operations, 12 missions (11 lessons + boss), closing Arc II
-- alongside Act 12 and Act 13. Same campaigns -> operations -> missions ->
-- dialogue -> objectives -> challenges -> hints pattern as every world.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-be11', 'world-be-11', 'database-performance', '11A - Database Performance', 'A dashboard query that used to return instantly now takes fourteen seconds, and clients are timing out waiting on it. Learn what actually makes a query fast before you try to explain why this one suddenly isn''t.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-be11-1', 'campaign-be11', 'indexing-fundamentals', 'Indexing Fundamentals', 'What an index actually is, B-tree intuition, composite indexes, column ordering, covering indexes and how to read a query plan.', 1),
  ('operation-be11-2', 'campaign-be11', 'performance-in-practice', 'Performance In Practice', 'Sequential vs index scans, N+1 queries, connection pools, and diagnosing the query that will not stay fast.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-be11-01', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'what-is-an-index', 'What Is an Index?', 'A table with no index is a phone book with the pages shuffled -- finding one entry means reading every page until you get lucky.', 'intermediate', ARRAY['forge'], null, null, '{"type":"simulation","simulationId":"index-basics-sim"}'::jsonb, '{"xp":165,"credits":30}'::jsonb, false, 1),
  ('mission-be11-02', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'b-tree-intuition', 'B-Tree Intuition', 'Postgres''s default index isn''t a list -- it''s a balanced tree shaped so any value can be found in a handful of comparisons, not millions.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be11-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"btree-intuition-sim"}'::jsonb, '{"xp":168,"credits":30}'::jsonb, false, 2),
  ('mission-be11-03', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'composite-indexes', 'Composite Indexes', 'One index can span more than one column -- but only certain queries actually benefit, and which ones depends entirely on column order.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be11-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"composite-index-sim"}'::jsonb, '{"xp":172,"credits":31}'::jsonb, false, 3),
  ('mission-be11-04', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'index-ordering', 'Index Ordering', 'The same two columns, indexed in a different order, produce a functionally different index that solves a different problem.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be11-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"index-ordering-sim"}'::jsonb, '{"xp":175,"credits":31}'::jsonb, false, 4),
  ('mission-be11-05', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'covering-index-concepts', 'Covering Index Concepts', 'Sometimes an index can answer a query entirely on its own, without the planner ever touching the table it indexes.', 'intermediate', ARRAY['forge'], '{"requiredMissionIds":["mission-be11-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"covering-index-sim"}'::jsonb, '{"xp":178,"credits":32}'::jsonb, false, 5),
  ('mission-be11-06', 'world-be-11', 'campaign-be11', 'operation-be11-1', 'query-plans', 'Query Plans', 'EXPLAIN doesn''t run your query differently -- it just shows you the plan Postgres already decided to use, if you know how to read it.', 'intermediate', ARRAY['mira'], '{"requiredMissionIds":["mission-be11-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"query-plan-sim"}'::jsonb, '{"xp":182,"credits":32}'::jsonb, false, 6),
  ('mission-be11-07', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'sequential-vs-index-scan', 'Sequential vs Index Scan', 'Given the choice, the planner doesn''t always pick the index. Sometimes reading the whole table really is faster.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be11-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"seq-vs-index-scan-sim"}'::jsonb, '{"xp":186,"credits":33}'::jsonb, false, 7),
  ('mission-be11-08', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'n-plus-1-queries', 'N+1 Queries', 'One query to fetch a list, then one more query per item in that list -- fine with ten rows, catastrophic with ten thousand.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be11-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"n-plus-1-sim"}'::jsonb, '{"xp":189,"credits":33}'::jsonb, false, 8),
  ('mission-be11-09', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'connection-pools', 'Connection Pools', 'Opening a database connection isn''t free. A pool keeps a set of them open and ready instead of paying that cost on every request.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be11-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"connection-pool-sim"}'::jsonb, '{"xp":192,"credits":34}'::jsonb, false, 9),
  ('mission-be11-10', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'slow-query-investigation', 'Slow Query Investigation', 'A slow query rarely announces its own cause. You have to go looking for the gap between what the planner expected and what actually happened.', 'advanced', ARRAY['mira'], '{"requiredMissionIds":["mission-be11-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"slow-query-sim"}'::jsonb, '{"xp":195,"credits":34}'::jsonb, false, 10),
  ('mission-be11-11', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'database-profiling', 'Database Profiling', 'pg_stat_statements tracks every query Postgres has run -- and the one most worth fixing isn''t always the slowest-looking one.', 'advanced', ARRAY['forge'], '{"requiredMissionIds":["mission-be11-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"db-profiling-sim"}'::jsonb, '{"xp":198,"credits":35}'::jsonb, false, 11),
  ('mission-be11-12', 'world-be-11', 'campaign-be11', 'operation-be11-2', 'the-14-second-query', 'The 14-Second Query', 'A routine dashboard query now takes fourteen seconds and times out clients citywide. Everything this Act taught, at once -- plus something stranger sitting right next to the fix.', 'boss', ARRAY['mira','forge'], '{"requiredMissionIds":["mission-be11-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"14-second-query-boss-sim"}'::jsonb, '{"xp":460,"credits":100,"badgeIds":["14-second-query"],"skillXp":{"databases":30}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-be11-01', 1, 'forge', 'A table with no index is a phone book with the pages ripped out and shuffled. Looking up one name means reading every page until you get lucky.'),
  ('mission-be11-01', 2, 'forge', 'An index is a separate, sorted structure that points back at where a row actually lives. It costs disk space and a little write overhead -- and buys you a lookup that doesn''t have to touch every row.'),
  ('mission-be11-02', 1, 'mira', 'Postgres''s default index type is a B-tree -- a balanced tree where every leaf sits the same distance from the root. That''s what makes lookup time predictable no matter where in the tree a value lives.'),
  ('mission-be11-02', 2, 'mira', 'Each level you descend eliminates a huge fraction of the remaining rows. A tree only three or four levels deep can still index millions of rows.'),
  ('mission-be11-03', 1, 'forge', 'A composite index spans more than one column, in a fixed order: CREATE INDEX ... ON table (col_a, col_b). It''s still one B-tree -- just sorted by col_a first, then col_b within each col_a value.'),
  ('mission-be11-03', 2, 'forge', 'That means it helps queries filtering on col_a alone, or on col_a and col_b together -- but not queries filtering on col_b alone. Order matters.'),
  ('mission-be11-04', 1, 'mira', 'Swap the column order in a composite index and you get a functionally different index. (status, district) sorts by status first; (district, status) sorts by district first. Same two columns, different job.'),
  ('mission-be11-04', 2, 'mira', 'Sort direction matters too. Match a composite index''s column order and direction to how a query actually filters and sorts, and the planner can skip an extra sort step entirely.'),
  ('mission-be11-05', 1, 'forge', 'If every column a query needs -- filtered, selected, all of it -- is already sitting in the index itself, Postgres never has to jump back to the table row at all. That''s a covering index.'),
  ('mission-be11-05', 2, 'forge', 'It costs more disk space, since the index is now duplicating extra column data, not just the key you search on. Nothing''s free, but this trade is usually worth it for a hot read.'),
  ('mission-be11-06', 1, 'mira', 'EXPLAIN shows you the plan the query planner chose -- which scan type, which order, estimated cost -- without actually running the query. EXPLAIN ANALYZE runs it too, with real timing alongside the estimate.'),
  ('mission-be11-06', 2, 'mira', 'Reading a plan top-to-bottom is usually backwards. The innermost, most-indented node runs first; the outermost node is the last step, the one that hands you the final result.'),
  ('mission-be11-07', 1, 'forge', 'A sequential scan reads every row, in physical order, checking each one against the filter. An index scan jumps straight to matching rows. Obviously index scan wins... except when it doesn''t.'),
  ('mission-be11-07', 2, 'forge', 'If a query matches a huge fraction of the table, a sequential scan can beat an index scan outright. Random-access lookups for that many rows cost more than just reading the table straight through.'),
  ('mission-be11-08', 1, 'mira', 'N+1 is one query to fetch a list of N rows, then N more queries -- one per row -- to fetch something related to each. Ten districts means eleven queries. Ten thousand requests means ten thousand and one.'),
  ('mission-be11-08', 2, 'mira', 'The fix is almost always to fetch the related data in one extra query -- a JOIN, or a single WHERE ... IN (...) covering every id from the first query -- instead of querying inside a loop.'),
  ('mission-be11-09', 1, 'forge', 'Opening a fresh TCP connection, then a fresh Postgres backend process, then authenticating -- all of that happens before your query even runs. A connection pool keeps connections already open and hands one out per request.'),
  ('mission-be11-09', 2, 'forge', 'Set the pool too small and requests queue up waiting for a free connection under load. Set it too large and you can exceed Postgres''s own max_connections and start getting rejected outright.'),
  ('mission-be11-10', 1, 'mira', 'EXPLAIN ANALYZE gives you both the planner''s estimate and the real, measured execution. When those two numbers disagree wildly, that mismatch is usually the actual clue -- not the total runtime by itself.'),
  ('mission-be11-10', 2, 'mira', 'A row estimate off by a hundred times usually means the planner''s statistics are stale, or the query is shaped in a way the planner can''t reason about well. Either way, that''s where to start looking.'),
  ('mission-be11-11', 1, 'forge', 'pg_stat_statements aggregates every distinct query shape Postgres has run: total calls, total time, mean time. A 50ms query firing 200,000 times a day can cost more total time than a slow one that only runs twice.'),
  ('mission-be11-11', 2, 'forge', 'That''s why you sort by total_time, not mean_time, when deciding what to fix first. The biggest total cost isn''t always the scariest-looking single query.'),
  ('mission-be11-12', 1, 'mira', 'The district-summary dashboard used to return in under a second. Right now it''s taking fourteen -- and clients are timing out before it even finishes.'),
  ('mission-be11-12', 2, 'forge', 'Nothing about the query changed. What changed is load -- the anomaly-tracking queries Data Systems just finished are hammering this same table harder than anything has before.'),
  ('mission-be11-12', 3, 'mira', 'Find out what''s actually costing us those fourteen seconds. Everything this Act taught, at once.'),
  ('mission-be11-12', 4, 'forge', '...found it. source_tag was never indexed. Every one of these dashboard queries has been doing a full sequential scan on it this whole time -- it just never mattered until the table saw this much extra traffic.'),
  ('mission-be11-12', 5, 'mira', 'source_tag. That''s the same column that let a duplicate slip past us months ago, back in the civic registry. Didn''t expect to see it again here.'),
  ('mission-be11-12', 6, 'forge', '...one more thing. While the query was still running, two dashboards displaying the same report showed two different totals, for a few seconds, at the same time. Same report, same moment, different numbers. That''s not an indexing problem.'),
  ('mission-be11-12', 7, 'mira', 'Noted. File it. We fix the query today -- we''re not done asking about that.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-be11-01-o1', 'mission-be11-01', 1, 'Define the tradeoff', 'Explain what an index actually costs, and what it buys you.'),
  ('mission-be11-02-o1', 'mission-be11-02', 1, 'Order the descent', 'Order the steps a B-tree index lookup actually takes.'),
  ('mission-be11-03-o1', 'mission-be11-03', 1, 'Match the index to the query', 'Decide which query a composite index on (district, status) can actually help.'),
  ('mission-be11-04-o1', 'mission-be11-04', 1, 'Choose the right column order', 'Pick the index definition that actually matches how the dashboard filters and sorts.'),
  ('mission-be11-05-o1', 'mission-be11-05', 1, 'Spot the covering index', 'Identify which index lets this exact query skip the table entirely.'),
  ('mission-be11-06-o1', 'mission-be11-06', 1, 'Read the plan', 'Identify which node in this query plan actually runs first.'),
  ('mission-be11-07-o1', 'mission-be11-07', 1, 'Predict the planner''s choice', 'Decide when the planner would prefer a sequential scan over an available index.'),
  ('mission-be11-08-o1', 'mission-be11-08', 1, 'Spot the N+1', 'Find the line that turns one fast query into N extra ones.'),
  ('mission-be11-09-o1', 'mission-be11-09', 1, 'Diagnose the pool size', 'Explain what happens when concurrent demand exceeds the pool''s available connections.'),
  ('mission-be11-10-o1', 'mission-be11-10', 1, 'Find the real clue', 'Identify which evidence actually points at the root cause, not just a symptom of slowness.'),
  ('mission-be11-11-o1', 'mission-be11-11', 1, 'Pick the right fix target', 'Choose which query actually costs the system more, based on total time.'),
  ('mission-be11-12-o1', 'mission-be11-12', 1, 'Diagnose the scan', 'Identify why the query plan shows a sequential scan instead of an index scan.'),
  ('mission-be11-12-o2', 'mission-be11-12', 2, 'Confirm the missing index', 'Confirm that source_tag genuinely has no index backing this filter.'),
  ('mission-be11-12-o3', 'mission-be11-12', 3, 'Choose the fix', 'Pick the fix that actually addresses a sequential scan caused by a missing index.'),
  ('mission-be11-12-o4', 'mission-be11-12', 4, 'Close the incident', 'Close the incident, and file the dashboard discrepancy as a separate, unresolved anomaly.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-be11-01-o1-c1', 'mission-be11-01-o1', 1, 'multiple_choice', 'A citizens table has 3 million rows and no index on national_id. What does a lookup by national_id cost, and what would an index change?', '{"question":"A citizens table has 3 million rows and no index on national_id. What does WHERE national_id = ''4471-AX'' cost, and what would an index change?","options":[{"id":"a","text":"Nothing changes -- Postgres always reads the whole table regardless"},{"id":"b","text":"Without an index, Postgres must scan all 3 million rows looking for a match; an index lets it jump almost directly to the matching row(s)"},{"id":"c","text":"An index makes every write instantly free"},{"id":"d","text":"An index only matters for tables under 100 rows"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-02-o1-c1', 'mission-be11-02-o1', 1, 'interactive_diagram', 'Order how a B-tree index actually finds a row.', '{"diagramId":"btree-lookup-descent","hotspots":[{"id":"root","label":"Start at the root node","explanation":"The search begins by comparing the target value against the root node''s keys."},{"id":"branch","label":"Follow the matching branch down","explanation":"Each comparison eliminates a whole subtree, narrowing the search fast."},{"id":"leaf","label":"Reach a leaf node","explanation":"Leaf nodes hold the actual indexed values, in sorted order."},{"id":"fetch","label":"Fetch the matching row(s) from the table","explanation":"The leaf entry points at the physical row(s), which are fetched last."}],"task":"Order how a B-tree index actually finds a row, from first step to last."}'::jsonb, '{"correctOrderIds":["root","branch","leaf","fetch"]}'::jsonb),

  ('mission-be11-03-o1-c1', 'mission-be11-03-o1', 1, 'multiple_choice', 'There''s a composite index on service_requests (district, status). Which query can it help most directly?', '{"question":"There''s a composite index on service_requests (district, status). Which query can it help most directly?","options":[{"id":"a","text":"WHERE status = ''open''"},{"id":"b","text":"WHERE district = ''north'' AND status = ''open''"},{"id":"c","text":"WHERE priority = ''high''"},{"id":"d","text":"ORDER BY status"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-04-o1-c1', 'mission-be11-04-o1', 1, 'multiple_choice', 'The dashboard always filters by district first, then sorts matching rows by created_at descending. Which index definition serves that best?', '{"question":"The dashboard always filters by district first, then sorts matching rows by created_at descending. Which index definition serves that best?","options":[{"id":"a","text":"CREATE INDEX ON service_requests (created_at)"},{"id":"b","text":"CREATE INDEX ON service_requests (district, created_at DESC)"},{"id":"c","text":"CREATE INDEX ON service_requests (status)"},{"id":"d","text":"CREATE INDEX ON service_requests (created_at, district)"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-05-o1-c1', 'mission-be11-05-o1', 1, 'investigation', 'Which index lets this query be answered from the index alone, without a trip back to the table?', '{"evidence":[{"id":"ev1","label":"Query","detail":"SELECT district, status FROM service_requests WHERE district = ''north''"},{"id":"ev2","label":"Index A","detail":"CREATE INDEX ON service_requests (district)"},{"id":"ev3","label":"Index B","detail":"CREATE INDEX ON service_requests (district, status)"}],"question":"Which index lets this query be answered from the index alone, without a trip back to the table?"}'::jsonb, '{"requiredEvidenceIds":["ev3"]}'::jsonb),

  ('mission-be11-06-o1-c1', 'mission-be11-06-o1', 1, 'code_debugging', 'Which line in this query plan actually runs first, before anything else?', '{"language":"sql","code":"Sort  (cost=120.50..122.75 rows=900 width=64)\n  Sort Key: created_at DESC\n  ->  Seq Scan on service_requests  (cost=0.00..85.00 rows=900 width=64)\n        Filter: (district = ''''north'''')","question":"Which line in this query plan actually runs first, before anything else?"}'::jsonb, '{"requiredLineIds":["  ->  Seq Scan on service_requests  (cost=0.00..85.00 rows=900 width=64)"]}'::jsonb),

  ('mission-be11-07-o1-c1', 'mission-be11-07-o1', 1, 'multiple_choice', 'service_requests has an index on status. A query filters WHERE status = ''closed'', and 85% of all rows are closed. What will the planner likely choose, and why?', '{"question":"service_requests has an index on status. A query filters WHERE status = ''closed'', and 85% of all rows are closed. What will the planner likely choose, and why?","options":[{"id":"a","text":"Index scan, because an index always wins when one exists"},{"id":"b","text":"Sequential scan, because matching 85% of rows means the index would still touch nearly every row anyway, plus the extra cost of jumping back to the table each time"},{"id":"c","text":"Neither -- Postgres will refuse to run the query"},{"id":"d","text":"It depends only on table size, never on the fraction of matching rows"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-08-o1-c1', 'mission-be11-08-o1', 1, 'code_debugging', 'Which line is what actually executes N extra queries, once per row from the first query?', '{"language":"typescript","code":"const requests = await db.query(''''SELECT id, citizen_id FROM service_requests'''');\nfor (const r of requests) {\n  const citizen = await db.query(''''SELECT full_name FROM citizens WHERE id = $1'''', [r.citizen_id]);\n  r.citizenName = citizen.full_name;\n}\nreturn requests;","question":"Which line is what actually executes N extra queries, once per row from the first query?"}'::jsonb, '{"requiredLineIds":["  const citizen = await db.query(''''SELECT full_name FROM citizens WHERE id = $1'''', [r.citizen_id]);"]}'::jsonb),

  ('mission-be11-09-o1-c1', 'mission-be11-09-o1', 1, 'multiple_choice', 'A service has a connection pool of 10, and suddenly needs to run 40 concurrent queries. What actually happens to requests 11 through 40?', '{"question":"A service has a connection pool of 10, and suddenly needs to run 40 concurrent queries. What actually happens to requests 11 through 40?","options":[{"id":"a","text":"They fail immediately with a connection error"},{"id":"b","text":"They queue, waiting for one of the 10 connections to free up, adding latency but not necessarily failing outright"},{"id":"c","text":"Postgres automatically creates 30 more connections to match demand"},{"id":"d","text":"Nothing -- pool size has no effect on concurrent query limits"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-10-o1-c1', 'mission-be11-10-o1', 1, 'investigation', 'Which piece of evidence points at the actual root cause, not just a symptom of it?', '{"evidence":[{"id":"ev1","label":"Total runtime","detail":"14,212 ms"},{"id":"ev2","label":"Planner estimate vs actual","detail":"Planner estimated 40 rows returned by a filter step; actual rows returned was 380,000"},{"id":"ev3","label":"Server CPU graph","detail":"CPU usage spiked to 60% during the query"}],"question":"Which piece of evidence points at the actual root cause, not just a symptom of it?"}'::jsonb, '{"requiredEvidenceIds":["ev2"]}'::jsonb),

  ('mission-be11-11-o1-c1', 'mission-be11-11-o1', 1, 'multiple_choice', 'pg_stat_statements shows Query A: 40ms mean, 3 calls/day. Query B: 12ms mean, 900,000 calls/day. Which one is actually costing the system more total time?', '{"question":"pg_stat_statements shows Query A: 40ms mean, 3 calls/day. Query B: 12ms mean, 900,000 calls/day. Which one is actually costing the system more total time?","options":[{"id":"a","text":"Query A, because 40ms is a slower single query"},{"id":"b","text":"Query B -- 12ms times 900,000 calls is roughly 10,800 seconds a day, dwarfing Query A''s total cost"},{"id":"c","text":"They cost the same, since mean time is all that matters"},{"id":"d","text":"Impossible to know without EXPLAIN on both"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-12-o1-c1', 'mission-be11-12-o1', 1, 'code_debugging', 'Which line is the actual evidence that this query is scanning the whole table instead of using an index?', '{"language":"sql","code":"Aggregate  (cost=98531.00..98531.01 rows=1 width=8) (actual time=14201.442..14201.443 rows=1 loops=1)\n  ->  Seq Scan on dashboard_reports  (cost=0.00..97845.00 rows=274000 width=0) (actual time=0.031..14188.220 rows=274310 loops=1)\n        Filter: (source_tag = ''''anomaly-review'''')\n        Rows Removed by Filter: 1725690","question":"Which line is the actual evidence that this query is scanning the whole table instead of using an index?"}'::jsonb, '{"requiredLineIds":["  ->  Seq Scan on dashboard_reports  (cost=0.00..97845.00 rows=274000 width=0) (actual time=0.031..14188.220 rows=274310 loops=1)"]}'::jsonb),

  ('mission-be11-12-o2-c1', 'mission-be11-12-o2', 1, 'investigation', 'Which evidence directly confirms the missing index is the actual cause, not just a contributing factor?', '{"evidence":[{"id":"ev1","label":"pg_indexes for dashboard_reports","detail":"Indexes present: dashboard_reports_pkey (id). No index on source_tag."},{"id":"ev2","label":"Table row count","detail":"2,000,000 rows, growing daily"},{"id":"ev3","label":"Query frequency","detail":"This exact query shape runs roughly 40 times per hour from various dashboards"}],"question":"Which evidence directly confirms the missing index is the actual cause, not just a contributing factor?"}'::jsonb, '{"requiredEvidenceIds":["ev1"]}'::jsonb),

  ('mission-be11-12-o3-c1', 'mission-be11-12-o3', 1, 'multiple_choice', 'Given the EXPLAIN output showing a sequential scan filtering on source_tag, what''s the correct fix?', '{"question":"Given the EXPLAIN output showing a sequential scan filtering on source_tag, what''s the correct fix?","options":[{"id":"a","text":"Rewrite the query to avoid using WHERE entirely"},{"id":"b","text":"CREATE INDEX ON dashboard_reports (source_tag) -- give the planner an index it can actually use for this filter"},{"id":"c","text":"Increase the server''s CPU allocation"},{"id":"d","text":"Cache the entire table in application memory"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-be11-12-o4-c1', 'mission-be11-12-o4', 1, 'boss_encounter', 'Close the incident: state what actually caused the fourteen-second query, and file the dashboard discrepancy separately.', '{"stages":[{"objectiveRef":"mission-be11-12-o1","label":"Diagnose the scan"},{"objectiveRef":"mission-be11-12-o2","label":"Confirm the missing index"},{"objectiveRef":"mission-be11-12-o3","label":"Choose the fix"}],"task":"Close the incident: a missing index on source_tag forced a full sequential scan under load that used to be cheap enough to ignore. File the dashboard discrepancy as a separate, unresolved anomaly -- it is not explained by the indexing fix."}'::jsonb, '{"requiredObjectiveIds":["mission-be11-12-o1","mission-be11-12-o2","mission-be11-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-be11-01-o1-c1', 'orientation', 'Think about the two very different costs at play: reading rows, and maintaining a second structure.', 10, 1),
  ('mission-be11-01-o1-c1', 'solution', 'Without an index, matching a row means checking every row (a sequential scan). An index trades some write cost and storage for near-direct lookups.', 20, 2),

  ('mission-be11-02-o1-c1', 'orientation', 'Nothing can be fetched from the table until the tree tells you where to look.', 10, 1),
  ('mission-be11-02-o1-c1', 'solution', 'Root, then branch, then leaf, then the table fetch itself.', 20, 2),

  ('mission-be11-03-o1-c1', 'orientation', 'The leading column of a composite index has to be involved for the index to help directly.', 10, 1),
  ('mission-be11-03-o1-c1', 'solution', 'district is the leading column -- filtering on district (alone or with status) can use the index; filtering on status alone generally can''t.', 20, 2),

  ('mission-be11-04-o1-c1', 'orientation', 'The leading column should match the filter that always happens first.', 10, 1),
  ('mission-be11-04-o1-c1', 'solution', '(district, created_at DESC) puts the always-present filter column first, and matches the sort direction the dashboard actually needs.', 20, 2),

  ('mission-be11-05-o1-c1', 'orientation', 'Check whether every column the SELECT needs is already present in the index, not just the WHERE column.', 10, 1),
  ('mission-be11-05-o1-c1', 'concept', 'A covering index that includes both the filtered and selected columns lets Postgres answer the whole query from the index''s own leaf entries.', 20, 2),
  ('mission-be11-05-o1-c1', 'solution', 'Index B includes status alongside district -- both columns the query needs are in the index, so it never needs the table itself.', 30, 3),

  ('mission-be11-06-o1-c1', 'orientation', 'Plans read bottom-up in execution order, even though indentation nests the other way.', 10, 1),
  ('mission-be11-06-o1-c1', 'solution', 'The Seq Scan node is the innermost step -- it runs first; Sort runs last, on the scan''s output.', 20, 2),

  ('mission-be11-07-o1-c1', 'orientation', 'An index scan pays a per-row cost to jump back to the table. Ask what happens once nearly every row matches.', 10, 1),
  ('mission-be11-07-o1-c1', 'solution', 'When a filter matches most of the table, a sequential scan reading straight through ends up cheaper than an index scan paying random-access cost per matching row.', 20, 2),

  ('mission-be11-08-o1-c1', 'orientation', 'Look inside the loop -- what runs once per iteration instead of once total?', 10, 1),
  ('mission-be11-08-o1-c1', 'solution', 'The db.query call inside the for loop fires once per request row -- that''s the N extra queries.', 20, 2),

  ('mission-be11-09-o1-c1', 'orientation', 'A pool being "full" and a request "failing" aren''t automatically the same thing.', 10, 1),
  ('mission-be11-09-o1-c1', 'solution', 'Requests beyond the pool size wait in a queue for a connection to free up -- that shows up as latency, and only becomes outright failure if the wait exceeds a timeout.', 20, 2),

  ('mission-be11-10-o1-c1', 'orientation', 'Runtime and CPU usage are both just symptoms -- ask what would explain a bad plan being chosen in the first place.', 10, 1),
  ('mission-be11-10-o1-c1', 'solution', 'A planner estimate off by four orders of magnitude means the planner was working from bad information -- that mismatch is what actually explains the wrong plan being chosen.', 20, 2),

  ('mission-be11-11-o1-c1', 'orientation', 'Multiply mean time by call count before comparing -- a single number in isolation doesn''t tell you total cost.', 10, 1),
  ('mission-be11-11-o1-c1', 'solution', 'Total time is mean time times call count. Query B''s enormous call volume makes its total system cost far larger, even with a faster mean.', 20, 2),

  ('mission-be11-12-o1-c1', 'orientation', 'The status line at the top is the last step. Look for the node with no arrow pointing into it from below.', 10, 1),
  ('mission-be11-12-o1-c1', 'concept', 'A Seq Scan node with a huge actual-rows count and no matching index in the plan is the signature of a missing index, not a bad query shape.', 20, 2),
  ('mission-be11-12-o1-c1', 'solution', 'The Seq Scan on dashboard_reports, with 274,310 actual rows read and 14+ seconds spent, is the direct evidence of a full-table scan.', 30, 3),
  ('mission-be11-12-o2-c1', 'orientation', 'Confirming a missing index means checking what indexes actually exist, not just what the plan implies.', 10, 1),
  ('mission-be11-12-o2-c1', 'solution', 'pg_indexes shows only the primary key index exists on dashboard_reports -- source_tag genuinely has no index backing it.', 20, 2),
  ('mission-be11-12-o3-c1', 'orientation', 'The fix should target the exact thing the plan showed was missing.', 10, 1),
  ('mission-be11-12-o3-c1', 'solution', 'CREATE INDEX ON dashboard_reports (source_tag) gives the planner what it needs to stop scanning the whole table for this filter.', 20, 2),
  ('mission-be11-12-o4-c1', 'orientation', 'Separate what you fixed from what you merely noticed -- only one of those is today''s job.', 15, 1),
  ('mission-be11-12-o4-c1', 'solution', 'The missing index on source_tag caused the full scan and the 14-second runtime; the dashboards briefly disagreeing is a separate, filed, unresolved anomaly -- not something today''s fix explains.', 25, 2);
