-- AI/ML pathway ("Cipher Division") Act 7 -- "First Prediction" content.
-- Opens Arc II ("Machines That Predict"). 1 campaign, 2 operations, 12
-- missions (11 lessons + boss), following the same campaigns -> operations
-- -> missions -> dialogue -> objectives -> challenges -> hints pattern as
-- every other Act. The `worlds`/`acts`/`pathways` rows already exist
-- (20260811100000_ai_acts6_36_spine.sql); this migration only adds content
-- beneath the existing world-ai-first-prediction row.

insert into public.campaigns (id, world_id, slug, title, description, sort_order) values
  ('campaign-ai-first-prediction', 'world-ai-first-prediction', 'first-prediction', '7A - First Prediction', 'Cipher Division''s leakage-checked dataset finally earns its keep: build a real regression model to predict Cipher Labs'' grid load, learn to read loss honestly, and ship a number that survives contact with held-out data.', 1);

insert into public.operations (id, campaign_id, slug, title, description, sort_order) values
  ('operation-ai-first-prediction-1', 'campaign-ai-first-prediction', 'the-first-line', 'The First Line', 'The vocabulary and mechanics of regression itself: what it predicts, how a line fits data, and how a loss function scores that fit.', 1),
  ('operation-ai-first-prediction-2', 'campaign-ai-first-prediction', 'honest-fit', 'Honest Fit', 'Training a model for real: gradient descent, learning rate, the two ways a fit can fail, and how to score it honestly with R-squared.', 2);

insert into public.missions (
  id, world_id, campaign_id, operation_id, slug, title, description, difficulty,
  character_ids, prerequisites, required_skills, lab, rewards, is_boss, sort_order
) values
  ('mission-ai-first-prediction-01', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'regression', 'Regression', 'Cipher Division''s first real regression model: predict Cipher Labs'' grid load from the leakage-checked data Act 6 finally earned, and use it as a proxy for Echo''s own activity.', 'beginner', ARRAY['maya','byte'], null, null, '{"type":"simulation","simulationId":"grid-load-intro-sim"}'::jsonb, '{"xp":130,"credits":25}'::jsonb, false, 1),
  ('mission-ai-first-prediction-02', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'linear-regression', 'Linear Regression', 'The simplest regression model there is: a straight line, one slope, one intercept, one prediction.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-01"]}'::jsonb, null, '{"type":"simulation","simulationId":"linear-regression-sim"}'::jsonb, '{"xp":140,"credits":25}'::jsonb, false, 2),
  ('mission-ai-first-prediction-03', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'best-fit-line', 'Best-Fit Line', 'Infinite lines fit a scatter of points. Only one minimizes the error across all of them -- learn what best fit actually means.', 'beginner', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-02"]}'::jsonb, null, '{"type":"simulation","simulationId":"best-fit-line-sim"}'::jsonb, '{"xp":140,"credits":30}'::jsonb, false, 3),
  ('mission-ai-first-prediction-04', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'loss-functions', 'Loss Functions', 'Before any model can improve, it needs a single number that says exactly how wrong it currently is.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-03"]}'::jsonb, null, '{"type":"simulation","simulationId":"loss-function-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 4),
  ('mission-ai-first-prediction-05', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'mse', 'MSE', 'Mean Squared Error: square every residual before averaging, so big misses cost far more than small ones.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-04"]}'::jsonb, null, '{"type":"simulation","simulationId":"mse-sim"}'::jsonb, '{"xp":150,"credits":30}'::jsonb, false, 5),
  ('mission-ai-first-prediction-06', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-1', 'mae', 'MAE', 'Mean Absolute Error: average every residual''s plain size, treating every unit of error the same.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-05"]}'::jsonb, null, '{"type":"simulation","simulationId":"mae-sim"}'::jsonb, '{"xp":160,"credits":30}'::jsonb, false, 6),
  ('mission-ai-first-prediction-07', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'gradient-descent', 'Gradient Descent', 'The algorithm that actually closes the gap between a bad model and a good one, one downhill step at a time.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-06"]}'::jsonb, null, '{"type":"simulation","simulationId":"gradient-descent-sim"}'::jsonb, '{"xp":160,"credits":35}'::jsonb, false, 7),
  ('mission-ai-first-prediction-08', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'learning-rate', 'Learning Rate', 'The size of each gradient descent step decides whether training crawls, converges, or blows up entirely.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-07"]}'::jsonb, null, '{"type":"simulation","simulationId":"learning-rate-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 8),
  ('mission-ai-first-prediction-09', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'underfitting', 'Underfitting', 'When a model is too simple for the pattern in front of it, no amount of training time will save it.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-08"]}'::jsonb, null, '{"type":"simulation","simulationId":"underfitting-sim"}'::jsonb, '{"xp":170,"credits":35}'::jsonb, false, 9),
  ('mission-ai-first-prediction-10', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'overfitting', 'Overfitting', 'When a model is too eager, it stops learning the pattern and starts memorizing the noise instead.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-09"]}'::jsonb, null, '{"type":"simulation","simulationId":"overfitting-sim"}'::jsonb, '{"xp":180,"credits":35}'::jsonb, false, 10),
  ('mission-ai-first-prediction-11', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'r-squared', 'R2', 'A number that says how much of the real variation in grid load the model actually explains -- and how to catch it lying.', 'intermediate', ARRAY['byte'], '{"requiredMissionIds":["mission-ai-first-prediction-10"]}'::jsonb, null, '{"type":"simulation","simulationId":"r-squared-sim"}'::jsonb, '{"xp":180,"credits":40}'::jsonb, false, 11),
  ('mission-ai-first-prediction-12', 'world-ai-first-prediction', 'campaign-ai-first-prediction', 'operation-ai-first-prediction-2', 'predict-the-grid-load', 'Predict the Grid Load', 'One model undertrained, one overtrained. Diagnose both honestly, and ship the grid-load predictor Cipher Division can actually trust.', 'boss', ARRAY['maya','byte'], '{"requiredMissionIds":["mission-ai-first-prediction-11"]}'::jsonb, null, '{"type":"simulation","simulationId":"predict-grid-load-boss-sim"}'::jsonb, '{"xp":580,"credits":125,"badgeIds":["predict-the-grid-load"],"skillXp":{"regression":50,"ai_ml_fundamentals":15}}'::jsonb, true, 12);

insert into public.dialogue_lines (mission_id, sort_order, character_id, text) values
  ('mission-ai-first-prediction-01', 1, 'maya', 'The split held. Train, validation, test, no duplicated blocks, no leakage. For the first time, Cipher Division has a dataset it can actually trust.'),
  ('mission-ai-first-prediction-01', 2, 'maya', 'Grid load at Cipher Labs has been fluctuating since Echo woke up -- thousands of accelerators drawing power in patterns nobody scheduled. We need to predict it, partly to plan capacity, and partly because more load likely means Echo is doing more.'),
  ('mission-ai-first-prediction-01', 3, 'byte', 'That is a regression problem. Classification predicts a category, a label from a fixed set. Regression predicts a number, a continuous value that can land almost anywhere.'),
  ('mission-ai-first-prediction-01', 4, 'byte', 'Grid load in megawatts is not "high" or "low" as categories, it is a number. This is Cipher Division''s first real regression model.'),

  ('mission-ai-first-prediction-02', 1, 'byte', 'Simplest regression model there is: linear regression. Predict the output y as a weighted sum of inputs plus a constant. One input, one weight: y = mx + b.'),
  ('mission-ai-first-prediction-02', 2, 'byte', 'm is the slope, how much y changes per unit of x. b is the intercept, the predicted value when x is zero. Training finds the m and b that fit the data best.'),
  ('mission-ai-first-prediction-02', 3, 'byte', 'For grid load, x could be something like hour of day, y is predicted megawatts. Simple, but it is the model every other regression method builds on.'),

  ('mission-ai-first-prediction-03', 1, 'byte', 'Infinite lines could be drawn through a scatter of points. Best fit means the one line that minimizes total prediction error across every point, not just the ones near it.'),
  ('mission-ai-first-prediction-03', 2, 'byte', 'The vertical gap between each real point and the line''s prediction is called a residual. A best-fit line is not one with zero residuals, that almost never happens. It is the line whose residuals, in aggregate, are smallest.'),
  ('mission-ai-first-prediction-03', 3, 'byte', 'Chase a line that hits every point perfectly and you get something that snakes wildly and predicts nothing sensible on a new day. Best fit is a balance, not a perfect trace.'),

  ('mission-ai-first-prediction-04', 1, 'byte', 'A model needs a number that says how wrong it currently is. That number is the loss, produced by a loss function, and training exists to make that number smaller.'),
  ('mission-ai-first-prediction-04', 2, 'byte', 'No single correct loss function exists. Different loss functions punish different kinds of mistakes differently, which is a choice, not a formality.'),
  ('mission-ai-first-prediction-04', 3, 'byte', 'For grid load regression, we compare a few loss functions to decide which one actually fits what Cipher Division cares about getting wrong.'),

  ('mission-ai-first-prediction-05', 1, 'byte', 'Mean Squared Error, MSE: take every residual, square it, average across all examples. Squaring does two things at once.'),
  ('mission-ai-first-prediction-05', 2, 'byte', 'It makes every error positive, so overshooting and undershooting cannot cancel out. And it punishes big errors far more than small ones, since squaring grows fast.'),
  ('mission-ai-first-prediction-05', 3, 'byte', 'A model that is usually close but occasionally wildly wrong will get a bad MSE score, even if it is right most of the time. MSE hates outlier mistakes.'),

  ('mission-ai-first-prediction-06', 1, 'byte', 'Mean Absolute Error, MAE: take every residual''s absolute value, average across all examples. No squaring.'),
  ('mission-ai-first-prediction-06', 2, 'byte', 'Every unit of error counts the same in MAE, whether it is one big miss or several small ones. That makes MAE more robust to outliers than MSE, but also less sensitive to a single bad prediction.'),
  ('mission-ai-first-prediction-06', 3, 'byte', 'Choosing MSE over MAE, or the reverse, is a judgment call about which kind of mistake actually worries Cipher Division more.'),

  ('mission-ai-first-prediction-07', 1, 'byte', 'Knowing the loss is high does not fix it. Gradient descent is the algorithm that actually nudges parameters to make loss smaller, step by step.'),
  ('mission-ai-first-prediction-07', 2, 'byte', 'At each step, it computes the gradient, the direction the loss would increase fastest if a parameter moved, then moves the parameter the opposite way, downhill.'),
  ('mission-ai-first-prediction-07', 3, 'byte', 'Repeat that enough times on enough data and the parameters settle near a minimum, a point where nudging further does not reduce loss much more.'),

  ('mission-ai-first-prediction-08', 1, 'byte', 'Gradient descent knows which direction to step. Learning rate decides how big that step is.'),
  ('mission-ai-first-prediction-08', 2, 'byte', 'Too small, and training crawls, needing far more steps than Cipher Division has time for. Too large, and updates overshoot the minimum, sometimes making loss worse with every step instead of better.'),
  ('mission-ai-first-prediction-08', 3, 'byte', 'Grid load training just showed both failure modes back to back. Worth knowing the symptoms cold before we tune anything for real.'),

  ('mission-ai-first-prediction-09', 1, 'byte', 'Underfitting is what happens when a model is too simple, or undertrained, to capture the real pattern in the data. It does poorly everywhere, training data included.'),
  ('mission-ai-first-prediction-09', 2, 'byte', 'A straight line trying to fit a curve that clearly bends will underfit no matter how long you train it. The model''s shape itself is the ceiling on how well it can ever do.'),
  ('mission-ai-first-prediction-09', 3, 'byte', 'Watch for it in the loss: both training loss and validation loss stay high and roughly flat. Neither one is doing well, because the model genuinely cannot represent the pattern.'),

  ('mission-ai-first-prediction-10', 1, 'byte', 'Overfitting is the opposite failure. The model is complex enough, or trained long enough, that it starts memorizing quirks and noise in the training data instead of the real underlying pattern.'),
  ('mission-ai-first-prediction-10', 2, 'byte', 'Training loss looks great, sometimes almost zero. That is the trap. Validation loss, on data the model never trained on, stays high or even gets worse as training continues.'),
  ('mission-ai-first-prediction-10', 3, 'byte', 'This is the same lesson Act 6 taught with the fake 99% model, just showing up again in a new shape. A model can look excellent and still be wrong, if you only ever check it on data it has already memorized.'),

  ('mission-ai-first-prediction-11', 1, 'byte', 'R-squared, R2, answers a different question than loss does: not how wrong is the model, but how much of the variation in the real data does the model actually explain, compared to just guessing the average every time.'),
  ('mission-ai-first-prediction-11', 2, 'byte', 'R2 of 1 means the model explains all the variation, R2 of 0 means it does no better than always predicting the mean. R2 can even go negative, meaning the model is worse than that flat guess.'),
  ('mission-ai-first-prediction-11', 3, 'byte', 'A suspiciously perfect R2 deserves the same instinct as that fake 99% model in Act 6: check it on held-out data before trusting it, not just on the data it trained on.'),

  ('mission-ai-first-prediction-12', 1, 'maya', 'Time to actually build it. Clean, split, leakage-checked data from Act 6, going into Cipher Division''s first real regression model for grid load.'),
  ('mission-ai-first-prediction-12', 2, 'byte', 'I ran two versions tonight before you arrived. Neither is the answer yet. Diagnose both from the actual logs, not from which one looks more impressive.'),
  ('mission-ai-first-prediction-12', 3, 'byte', 'The first version undertrained a straight line against a curve that clearly bends. The second version threw a lot of capacity at the same modest dataset and trained it a long time.'),
  ('mission-ai-first-prediction-12', 4, 'maya', 'This is not only about capacity planning. Every load spike in that curve tracks with Echo doing more. Misjudge the model and we misjudge Echo.'),
  ('mission-ai-first-prediction-12', 5, 'maya', 'Same rule as Act 6. Honestly evaluated beats impressive-looking, every time. Ship the number you can actually defend.'),
  ('mission-ai-first-prediction-12', 6, 'byte', 'Once we have an honest regression model running, the next question is different in kind. Grid load is a number to predict. The next thing Cipher Division needs to predict is a yes-or-no: is a given activity spike an emergency, or not. That is not regression anymore. That is classification.');

insert into public.objectives (id, mission_id, sort_order, title, description) values
  ('mission-ai-first-prediction-01-o1', 'mission-ai-first-prediction-01', 1, 'Tell regression from classification', 'Confirm what kind of prediction problem grid load actually is.'),
  ('mission-ai-first-prediction-01-o2', 'mission-ai-first-prediction-01', 2, 'See why it matters twice over', 'Find the evidence explaining the project''s dual purpose.'),

  ('mission-ai-first-prediction-02-o1', 'mission-ai-first-prediction-02', 1, 'Read the equation', 'Identify what the slope in a linear regression equation actually represents.'),
  ('mission-ai-first-prediction-02-o2', 'mission-ai-first-prediction-02', 2, 'Match the terms', 'Match each symbol in y = mx + b to what it represents.'),

  ('mission-ai-first-prediction-03-o1', 'mission-ai-first-prediction-03', 1, 'Define best fit', 'Choose the accurate definition of a best-fit line.'),
  ('mission-ai-first-prediction-03-o2', 'mission-ai-first-prediction-03', 2, 'Judge the residuals', 'Identify which of three candidate fits is the actual best-fit line.'),

  ('mission-ai-first-prediction-04-o1', 'mission-ai-first-prediction-04', 1, 'Define the role', 'State what a loss function''s job actually is.'),
  ('mission-ai-first-prediction-04-o2', 'mission-ai-first-prediction-04', 2, 'Spot high vs low loss', 'Sort predictions into low-loss and high-loss based on their error size.'),

  ('mission-ai-first-prediction-05-o1', 'mission-ai-first-prediction-05', 1, 'Define MSE', 'Choose the accurate description of how MSE penalizes error.'),
  ('mission-ai-first-prediction-05-o2', 'mission-ai-first-prediction-05', 2, 'Compare two models', 'Determine which of two residual sets produces the lower MSE.'),

  ('mission-ai-first-prediction-06-o1', 'mission-ai-first-prediction-06', 1, 'Define MAE', 'Choose the accurate description of how MAE penalizes error.'),
  ('mission-ai-first-prediction-06-o2', 'mission-ai-first-prediction-06', 2, 'Match the property', 'Sort properties into MSE or MAE.'),

  ('mission-ai-first-prediction-07-o1', 'mission-ai-first-prediction-07', 1, 'Order the steps', 'Put the stages of gradient descent in the order they actually happen.'),
  ('mission-ai-first-prediction-07-o2', 'mission-ai-first-prediction-07', 2, 'Read the direction', 'State which direction a parameter should move given a positive gradient.'),

  ('mission-ai-first-prediction-08-o1', 'mission-ai-first-prediction-08', 1, 'Define the role', 'State what the learning rate actually controls.'),
  ('mission-ai-first-prediction-08-o2', 'mission-ai-first-prediction-08', 2, 'Diagnose the run', 'Identify which training run shows a learning rate set too high.'),

  ('mission-ai-first-prediction-09-o1', 'mission-ai-first-prediction-09', 1, 'Diagnose underfitting', 'Find the evidence that is the clearest statistical signature of underfitting.'),
  ('mission-ai-first-prediction-09-o2', 'mission-ai-first-prediction-09', 2, 'Know the fix', 'Choose the correct fix for an underfitting model.'),

  ('mission-ai-first-prediction-10-o1', 'mission-ai-first-prediction-10', 1, 'Diagnose overfitting', 'Find the evidence that is the clearest statistical signature of overfitting.'),
  ('mission-ai-first-prediction-10-o2', 'mission-ai-first-prediction-10', 2, 'Know the fix', 'Choose the correct fix for an overfitting model.'),

  ('mission-ai-first-prediction-11-o1', 'mission-ai-first-prediction-11', 1, 'Define R2', 'Choose the accurate description of what R2 measures.'),
  ('mission-ai-first-prediction-11-o2', 'mission-ai-first-prediction-11', 2, 'Judge a suspicious number', 'Identify which reported R2 figure is actually trustworthy.'),

  ('mission-ai-first-prediction-12-o1', 'mission-ai-first-prediction-12', 1, 'Diagnose the early model', 'Read the early model''s loss logs and pin down its actual failure mode.'),
  ('mission-ai-first-prediction-12-o2', 'mission-ai-first-prediction-12', 2, 'Diagnose the late model', 'Read the late model''s loss logs and pin down its actual failure mode.'),
  ('mission-ai-first-prediction-12-o3', 'mission-ai-first-prediction-12', 3, 'Judge the evaluation honestly', 'Decide which R2 figure actually reflects trustworthy performance.'),
  ('mission-ai-first-prediction-12-o4', 'mission-ai-first-prediction-12', 4, 'Choose what ships', 'Having diagnosed both models and judged the evaluation, state Cipher Division''s final call.');

insert into public.challenges (id, objective_id, sort_order, type, prompt, content, completion_conditions) values
  ('mission-ai-first-prediction-01-o1-c1', 'mission-ai-first-prediction-01-o1', 1, 'multiple_choice', 'Predicting Cipher Labs'' megawatt grid load for the next hour is...', '{"question":"Predicting Cipher Labs'' megawatt grid load for the next hour is...","options":[{"id":"a","text":"A classification problem, because the load falls into risk tiers"},{"id":"b","text":"A regression problem, because the output is a continuous numeric value"},{"id":"c","text":"Neither, it is a database query"},{"id":"d","text":"A labeling problem"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-01-o2-c1', 'mission-ai-first-prediction-01-o2', 1, 'investigation', 'Which evidence explains why Cipher Division is building this predictor for two separate reasons at once?', '{"evidence":[{"id":"e1","label":"Facilities and Byte joint note","detail":"Since Echo''s activation, grid load has swung unpredictably, threatening capacity planning, and every spike checked so far tracks with a rise in Echo''s own compute activity"},{"id":"e2","label":"Ops dashboard","detail":"The operations dashboard''s color theme was updated last week to match new Cipher Division branding"},{"id":"e3","label":"HR log","detail":"Two new analysts joined Cipher Division''s night shift this month"}],"question":"Which evidence explains why Cipher Division is building this predictor for two separate reasons at once?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-first-prediction-02-o1-c1', 'mission-ai-first-prediction-02-o1', 1, 'multiple_choice', 'In y = mx + b, what does m represent?', '{"question":"In y = mx + b, what does m represent?","options":[{"id":"a","text":"The predicted output itself"},{"id":"b","text":"The slope: how much y changes per one-unit change in x"},{"id":"c","text":"The input feature"},{"id":"d","text":"A random error term"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-02-o2-c1', 'mission-ai-first-prediction-02-o2', 1, 'drag_and_drop', 'Match each symbol in y = mx + b to what it represents.', '{"items":[{"id":"i1","text":"m"},{"id":"i2","text":"b"},{"id":"i3","text":"x"},{"id":"i4","text":"y"}],"targets":[{"id":"t1","label":"Slope (weight)"},{"id":"t2","label":"Intercept (bias)"},{"id":"t3","label":"Input feature"},{"id":"t4","label":"Predicted output"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t3","i4":"t4"}}'::jsonb),

  ('mission-ai-first-prediction-03-o1-c1', 'mission-ai-first-prediction-03-o1', 1, 'multiple_choice', 'A best-fit line is best described as...', '{"question":"A best-fit line is best described as...","options":[{"id":"a","text":"A line that passes through every data point exactly"},{"id":"b","text":"The line whose overall residuals (prediction errors) are smallest across all points"},{"id":"c","text":"The line with the steepest possible slope"},{"id":"d","text":"Any line drawn through the middle of the chart"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-03-o2-c1', 'mission-ai-first-prediction-03-o2', 1, 'investigation', 'Which fit is the actual best-fit line for this data?', '{"evidence":[{"id":"e1","label":"Fit A","detail":"Passes near most points, small residuals scattered evenly above and below the line"},{"id":"e2","label":"Fit B","detail":"Passes through 3 of 20 points exactly, then swings wildly, leaving huge residuals on the rest"},{"id":"e3","label":"Fit C","detail":"A flat horizontal line ignoring the data''s clear upward trend"}],"question":"Which fit is the actual best-fit line for this data?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-first-prediction-04-o1-c1', 'mission-ai-first-prediction-04-o1', 1, 'multiple_choice', 'A loss function''s job is to...', '{"question":"A loss function''s job is to...","options":[{"id":"a","text":"Store the training data"},{"id":"b","text":"Produce a single number measuring how wrong the model''s current predictions are"},{"id":"c","text":"Select which features to use"},{"id":"d","text":"Draw the best-fit line directly"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-04-o2-c1', 'mission-ai-first-prediction-04-o2', 1, 'drag_and_drop', 'Sort each prediction into low loss or high loss.', '{"items":[{"id":"i1","text":"Predicted 42 MW, actual was 43 MW"},{"id":"i2","text":"Predicted 15 MW, actual was 61 MW"},{"id":"i3","text":"Predicted 90 MW, actual was 91 MW"},{"id":"i4","text":"Predicted 20 MW, actual was 75 MW"}],"targets":[{"id":"t1","label":"Low loss (small error)"},{"id":"t2","label":"High loss (large error)"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-first-prediction-05-o1-c1', 'mission-ai-first-prediction-05-o1', 1, 'multiple_choice', 'MSE penalizes errors by...', '{"question":"MSE penalizes errors by...","options":[{"id":"a","text":"Taking the absolute value of each residual and averaging"},{"id":"b","text":"Squaring each residual, then averaging, so large errors count far more than small ones"},{"id":"c","text":"Counting how many predictions were wrong"},{"id":"d","text":"Ignoring outlier errors entirely"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-05-o2-c1', 'mission-ai-first-prediction-05-o2', 1, 'investigation', 'Which model has the lower MSE across these four days?', '{"evidence":[{"id":"e1","label":"Model A residuals","detail":"Errors of 1, 1, 1, 1 MW across four test days"},{"id":"e2","label":"Model B residuals","detail":"Errors of 0, 0, 0, 8 MW across four test days"},{"id":"e3","label":"Unrelated note","detail":"Both models were trained on the same hardware"}],"question":"Which model has the lower MSE across these four days?"}'::jsonb, '{"requiredEvidenceIds":["e1"]}'::jsonb),

  ('mission-ai-first-prediction-06-o1-c1', 'mission-ai-first-prediction-06-o1', 1, 'multiple_choice', 'MAE penalizes errors by...', '{"question":"MAE penalizes errors by...","options":[{"id":"a","text":"Squaring each residual before averaging"},{"id":"b","text":"Averaging the absolute value of each residual, treating every unit of error equally"},{"id":"c","text":"Only counting the largest error"},{"id":"d","text":"Ignoring small errors under one unit"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-06-o2-c1', 'mission-ai-first-prediction-06-o2', 1, 'drag_and_drop', 'Sort each property into MSE or MAE.', '{"items":[{"id":"i1","text":"Squares residuals before averaging"},{"id":"i2","text":"Averages absolute residuals"},{"id":"i3","text":"Heavily punishes rare, large outlier errors"},{"id":"i4","text":"Treats every unit of error equally regardless of size"}],"targets":[{"id":"t1","label":"MSE"},{"id":"t2","label":"MAE"}]}'::jsonb, '{"correctMapping":{"i1":"t1","i2":"t2","i3":"t1","i4":"t2"}}'::jsonb),

  ('mission-ai-first-prediction-07-o1-c1', 'mission-ai-first-prediction-07-o1', 1, 'interactive_diagram', 'Order the steps of gradient descent from first to last.', '{"diagramId":"gradient-descent-loop","hotspots":[{"id":"h1","label":"Start with random parameters","explanation":"Before any training, m and b begin at arbitrary values."},{"id":"h2","label":"Make a prediction","explanation":"Use the current parameters to predict every training example."},{"id":"h3","label":"Compute the loss","explanation":"Compare predictions to real labels and produce a loss number."},{"id":"h4","label":"Compute the gradient","explanation":"Find the direction that would make the loss increase fastest."},{"id":"h5","label":"Update parameters opposite the gradient","explanation":"Nudge m and b downhill, the direction that decreases loss."},{"id":"h6","label":"Repeat until loss stops shrinking","explanation":"Keep looping until further updates barely change the loss."}],"task":"Order the steps of gradient descent from first to last."}'::jsonb, '{"correctOrderIds":["h1","h2","h3","h4","h5","h6"]}'::jsonb),
  ('mission-ai-first-prediction-07-o2-c1', 'mission-ai-first-prediction-07-o2', 1, 'multiple_choice', 'If the gradient with respect to a parameter is positive, gradient descent should...', '{"question":"If the gradient with respect to a parameter is positive, gradient descent should...","options":[{"id":"a","text":"Increase that parameter, moving in the direction of the gradient"},{"id":"b","text":"Decrease that parameter, moving opposite the gradient, since that direction reduces loss"},{"id":"c","text":"Leave that parameter unchanged"},{"id":"d","text":"Reset that parameter to zero"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-first-prediction-08-o1-c1', 'mission-ai-first-prediction-08-o1', 1, 'multiple_choice', 'The learning rate controls...', '{"question":"The learning rate controls...","options":[{"id":"a","text":"How many training examples are used"},{"id":"b","text":"The size of each parameter update step during gradient descent"},{"id":"c","text":"Which loss function is used"},{"id":"d","text":"How the data is split into train and test"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-08-o2-c1', 'mission-ai-first-prediction-08-o2', 1, 'investigation', 'Which run shows a learning rate that is set too high?', '{"evidence":[{"id":"e1","label":"Run 1 loss log","detail":"Loss barely moves after 500 steps, decreasing by a tiny fraction each time"},{"id":"e2","label":"Run 2 loss log","detail":"Loss swings wildly, increasing on some steps, and grows larger overall as training continues"},{"id":"e3","label":"Run 3 loss log","detail":"Loss decreases steadily and levels off after 200 steps"}],"question":"Which run shows a learning rate that is set too high?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-first-prediction-09-o1-c1', 'mission-ai-first-prediction-09-o1', 1, 'investigation', 'Which single piece of evidence is the clearest sign of underfitting, as opposed to overfitting or a bad learning rate?', '{"evidence":[{"id":"e1","label":"Training loss log","detail":"Training loss stays high and flat after many steps, never dropping much"},{"id":"e2","label":"Validation loss log","detail":"Validation loss is also high and stays close to training loss the whole time"},{"id":"e3","label":"Model description","detail":"A single straight line is being fit to grid load data that visibly curves through the day"}],"question":"Which single piece of evidence is the clearest sign of underfitting, as opposed to overfitting or a bad learning rate?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-first-prediction-09-o2-c1', 'mission-ai-first-prediction-09-o2', 1, 'multiple_choice', 'The most direct fix for underfitting is...', '{"question":"The most direct fix for underfitting is...","options":[{"id":"a","text":"Collect less data"},{"id":"b","text":"Increase model capacity or train it longer and better, since the current model cannot represent the pattern"},{"id":"c","text":"Increase the learning rate to any value"},{"id":"d","text":"Remove all features"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-first-prediction-10-o1-c1', 'mission-ai-first-prediction-10-o1', 1, 'investigation', 'Which single piece of evidence is the clearest sign of overfitting, as opposed to underfitting?', '{"evidence":[{"id":"e1","label":"Training loss log","detail":"Training loss drops to nearly zero within a few hundred steps"},{"id":"e2","label":"Validation loss log","detail":"Validation loss decreases early, then rises steadily even as training loss keeps falling"},{"id":"e3","label":"Model description","detail":"A very high-capacity model with many parameters is being fit to a modest amount of grid load data"}],"question":"Which single piece of evidence is the clearest sign of overfitting, as opposed to underfitting?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-first-prediction-10-o2-c1', 'mission-ai-first-prediction-10-o2', 1, 'multiple_choice', 'The most direct fix for overfitting is...', '{"question":"The most direct fix for overfitting is...","options":[{"id":"a","text":"Increase model capacity even further"},{"id":"b","text":"Reduce model complexity, add regularization, or get more data, and stop training once validation loss stops improving"},{"id":"c","text":"Delete the validation set so the numbers look better"},{"id":"d","text":"Switch to a much larger learning rate"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),

  ('mission-ai-first-prediction-11-o1-c1', 'mission-ai-first-prediction-11-o1', 1, 'multiple_choice', 'R2 measures...', '{"question":"R2 measures...","options":[{"id":"a","text":"The exact number of parameters in the model"},{"id":"b","text":"How much of the variation in the true values the model explains, relative to just predicting the mean every time"},{"id":"c","text":"The learning rate used during training"},{"id":"d","text":"How many training steps were run"}]}'::jsonb, '{"correctOptionId":"b"}'::jsonb),
  ('mission-ai-first-prediction-11-o2-c1', 'mission-ai-first-prediction-11-o2', 1, 'investigation', 'Which report should Cipher Division actually trust as a fair evaluation of the model?', '{"evidence":[{"id":"e1","label":"Report A","detail":"R2 of 0.997 on the training set, not yet checked on validation or test data"},{"id":"e2","label":"Report B","detail":"R2 of 0.81 on the held-out test set, consistent with validation results"},{"id":"e3","label":"Report C","detail":"Model was trained using the GPU cluster reserved for Byte''s own processes"}],"question":"Which report should Cipher Division actually trust as a fair evaluation of the model?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),

  ('mission-ai-first-prediction-12-o1-c1', 'mission-ai-first-prediction-12-o1', 1, 'investigation', 'Which evidence is the clearest statistical signature of underfitting in the early model?', '{"evidence":[{"id":"e1","label":"Early model training loss","detail":"Training loss stays high and roughly flat around 40 MW-squared after 1,000 steps, never dropping much further"},{"id":"e2","label":"Early model validation loss","detail":"Validation loss is also high, close to training loss, around 42 MW-squared, the whole run"},{"id":"e3","label":"Load curve overlay","detail":"The model''s straight-line predictions miss the daily load spikes that line up with Echo''s known high-activity windows"}],"question":"Which evidence is the clearest statistical signature of underfitting in the early model, as opposed to overfitting?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-first-prediction-12-o2-c1', 'mission-ai-first-prediction-12-o2', 1, 'investigation', 'Which evidence is the clearest statistical signature of overfitting in the late model?', '{"evidence":[{"id":"e1","label":"Late model training loss","detail":"Training loss drops to almost zero within a few hundred steps"},{"id":"e2","label":"Late model validation loss","detail":"Validation loss falls at first, then climbs back up well above training loss as training continues"},{"id":"e3","label":"Model description","detail":"A high-capacity model with many parameters, trained far longer than the early version, on the same modest dataset"}],"question":"Which evidence is the clearest statistical signature of overfitting in the late model, as opposed to underfitting?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-first-prediction-12-o3-c1', 'mission-ai-first-prediction-12-o3', 1, 'investigation', 'Which R2 figure is the one Cipher Division should actually trust and report?', '{"evidence":[{"id":"e1","label":"Final model, training R2","detail":"Final model reports R2 of 0.85 on the training set alone"},{"id":"e2","label":"Final model, held-out R2","detail":"Final model reports R2 of 0.79 on the validation and test sets, close to its training score"},{"id":"e3","label":"Late (overfit) model, training R2","detail":"Late overfit model reports R2 of 0.98 on the training set alone, never checked further"}],"question":"Which R2 figure is the one Cipher Division should actually trust and report?"}'::jsonb, '{"requiredEvidenceIds":["e2"]}'::jsonb),
  ('mission-ai-first-prediction-12-o4-c1', 'mission-ai-first-prediction-12-o4', 1, 'boss_encounter', 'Having diagnosed underfitting in the early model, overfitting in the late model, and identified the honestly-evaluated R2, state which model Cipher Division should actually ship.', '{"stages":[{"objectiveRef":"mission-ai-first-prediction-12-o1","label":"Diagnose the early model"},{"objectiveRef":"mission-ai-first-prediction-12-o2","label":"Diagnose the late model"},{"objectiveRef":"mission-ai-first-prediction-12-o3","label":"Judge the evaluation honestly"}],"task":"State the call in one sentence: reject both the underfit early model and the overfit late model, and ship only the version whose validation and test R2 stay close to its training R2 -- the one that is honestly evaluated rather than merely impressive-looking."}'::jsonb, '{"requiredObjectiveIds":["mission-ai-first-prediction-12-o1","mission-ai-first-prediction-12-o2","mission-ai-first-prediction-12-o3"],"allCorrect":true}'::jsonb);

insert into public.hints (challenge_id, tier, text, xp_cost, sort_order) values
  ('mission-ai-first-prediction-01-o1-c1', 'orientation', 'Ask whether the output is one of a fixed set of categories, or a number that can take almost any value.', 10, 1),
  ('mission-ai-first-prediction-01-o1-c1', 'solution', 'Megawatts is a continuous numeric value, not a category -- that makes this a regression problem.', 20, 2),
  ('mission-ai-first-prediction-01-o2-c1', 'orientation', 'Look for the one entry that names both an operational reason and an Echo-related reason at once.', 10, 1),
  ('mission-ai-first-prediction-01-o2-c1', 'solution', 'e1: unpredictable load threatens capacity planning, and every spike checked tracks with Echo''s own activity -- that is the dual purpose.', 20, 2),

  ('mission-ai-first-prediction-02-o1-c1', 'orientation', 'm multiplies x directly in the equation -- think about what changing it does to the line.', 10, 1),
  ('mission-ai-first-prediction-02-o1-c1', 'solution', 'm is the slope: it sets how much the predicted y changes for each one-unit increase in x.', 20, 2),
  ('mission-ai-first-prediction-02-o2-c1', 'orientation', 'x goes in, y comes out. m and b are the two numbers training actually finds.', 10, 1),
  ('mission-ai-first-prediction-02-o2-c1', 'solution', 'm is the slope, b is the intercept, x is the input feature, y is the predicted output.', 20, 2),

  ('mission-ai-first-prediction-03-o1-c1', 'orientation', 'A best-fit line almost never touches every point exactly.', 10, 1),
  ('mission-ai-first-prediction-03-o1-c1', 'solution', 'Best fit means the smallest overall residuals across all points, not a perfect trace through any of them.', 20, 2),
  ('mission-ai-first-prediction-03-o2-c1', 'orientation', 'A line that swings wildly to hit a few points exactly is not minimizing overall error.', 10, 1),
  ('mission-ai-first-prediction-03-o2-c1', 'concept', 'Fit C ignores the trend entirely, and Fit B trades a few perfect hits for huge misses everywhere else.', 20, 2),
  ('mission-ai-first-prediction-03-o2-c1', 'solution', 'Fit A: small, evenly scattered residuals across the whole dataset is what an actual best-fit line looks like.', 30, 3),

  ('mission-ai-first-prediction-04-o1-c1', 'orientation', 'A loss function does not touch the data or the features directly -- it scores the model''s current predictions.', 10, 1),
  ('mission-ai-first-prediction-04-o1-c1', 'solution', 'A loss function produces a single number that measures how wrong the model''s current predictions are.', 20, 2),
  ('mission-ai-first-prediction-04-o2-c1', 'orientation', 'Compare each predicted value to the actual value and look at the size of the gap.', 10, 1),
  ('mission-ai-first-prediction-04-o2-c1', 'solution', 'Low loss: 42 vs 43, and 90 vs 91 (gaps of 1). High loss: 15 vs 61, and 20 vs 75 (gaps of dozens).', 20, 2),

  ('mission-ai-first-prediction-05-o1-c1', 'orientation', 'Squaring a number always makes it positive, and grows much faster for larger numbers.', 10, 1),
  ('mission-ai-first-prediction-05-o1-c1', 'solution', 'MSE squares every residual before averaging, so large errors are penalized far more heavily than small ones.', 20, 2),
  ('mission-ai-first-prediction-05-o2-c1', 'orientation', 'Square each residual, sum them, then divide by the count, for both models.', 10, 1),
  ('mission-ai-first-prediction-05-o2-c1', 'concept', 'Model A: (1+1+1+1)/4 = 1. Model B: (0+0+0+64)/4 = 16 -- one big miss dominates the average once it is squared.', 20, 2),
  ('mission-ai-first-prediction-05-o2-c1', 'solution', 'Model A has the lower MSE (1 versus 16), even though Model B was perfect on three of the four days.', 30, 3),

  ('mission-ai-first-prediction-06-o1-c1', 'orientation', 'MAE does not square anything -- it just takes the plain size of each error.', 10, 1),
  ('mission-ai-first-prediction-06-o1-c1', 'solution', 'MAE averages the absolute value of each residual, so every unit of error is weighted equally.', 20, 2),
  ('mission-ai-first-prediction-06-o2-c1', 'orientation', 'Ask which loss function grows fastest when a single error gets much larger than the rest.', 10, 1),
  ('mission-ai-first-prediction-06-o2-c1', 'solution', 'MSE: squares residuals, heavily punishes rare large outliers. MAE: averages absolute residuals, treats every unit of error equally.', 20, 2),

  ('mission-ai-first-prediction-07-o1-c1', 'orientation', 'Nothing can be compared to a label until the model has actually made a prediction with its current parameters.', 10, 1),
  ('mission-ai-first-prediction-07-o1-c1', 'concept', 'You cannot compute a gradient before you know the loss, and you cannot know the loss before you have compared a prediction to the truth.', 20, 2),
  ('mission-ai-first-prediction-07-o1-c1', 'solution', 'Start with random parameters, predict, compute the loss, compute the gradient, update the parameters opposite the gradient, repeat.', 30, 3),
  ('mission-ai-first-prediction-07-o2-c1', 'orientation', 'The gradient points toward higher loss, not lower loss.', 10, 1),
  ('mission-ai-first-prediction-07-o2-c1', 'solution', 'Move opposite the gradient -- if the gradient is positive, decrease the parameter, since that is the direction that reduces loss.', 20, 2),

  ('mission-ai-first-prediction-08-o1-c1', 'orientation', 'The learning rate does not decide which direction to move -- the gradient already does that.', 10, 1),
  ('mission-ai-first-prediction-08-o1-c1', 'solution', 'The learning rate controls how large each parameter update step is.', 20, 2),
  ('mission-ai-first-prediction-08-o2-c1', 'orientation', 'A learning rate that is too high causes updates to overshoot, not to move slowly.', 10, 1),
  ('mission-ai-first-prediction-08-o2-c1', 'solution', 'Run 2: loss swings and grows larger overall -- that is a learning rate set too high, causing overshoot past the minimum.', 20, 2),

  ('mission-ai-first-prediction-09-o1-c1', 'orientation', 'Underfitting shows up the same way on both the data the model trained on and the data it did not.', 10, 1),
  ('mission-ai-first-prediction-09-o1-c1', 'concept', 'If validation loss were much worse than training loss, that would point to overfitting instead. Here they stay close together.', 20, 2),
  ('mission-ai-first-prediction-09-o1-c1', 'solution', 'e2: validation loss staying high and close to training loss is the signature of underfitting -- the model is bad everywhere, not just on new data.', 30, 3),
  ('mission-ai-first-prediction-09-o2-c1', 'orientation', 'The problem is that the model''s shape cannot represent the pattern at all.', 10, 1),
  ('mission-ai-first-prediction-09-o2-c1', 'solution', 'Give the model more capacity, or train it properly -- a too-simple model needs more expressive power, not less data or a random learning rate change.', 20, 2),

  ('mission-ai-first-prediction-10-o1-c1', 'orientation', 'Overfitting shows a gap opening up between training performance and validation performance.', 10, 1),
  ('mission-ai-first-prediction-10-o1-c1', 'concept', 'If both losses stayed high and close together, that would be underfitting instead. Here training keeps improving while validation gets worse.', 20, 2),
  ('mission-ai-first-prediction-10-o1-c1', 'solution', 'e2: validation loss rising while training loss keeps falling is the signature of overfitting -- the model is memorizing training data, not generalizing.', 30, 3),
  ('mission-ai-first-prediction-10-o2-c1', 'orientation', 'The problem is that the model has too much freedom to memorize noise.', 10, 1),
  ('mission-ai-first-prediction-10-o2-c1', 'solution', 'Reduce complexity, regularize, add more data, or stop training once validation loss stops improving -- more capacity would only make it worse.', 20, 2),

  ('mission-ai-first-prediction-11-o1-c1', 'orientation', 'R2 is compared against the simplest possible baseline: always predicting the mean.', 10, 1),
  ('mission-ai-first-prediction-11-o1-c1', 'solution', 'R2 measures how much of the real variation the model explains, relative to just guessing the mean every time.', 20, 2),
  ('mission-ai-first-prediction-11-o2-c1', 'orientation', 'A number checked only on the data it trained on has not actually been tested yet.', 10, 1),
  ('mission-ai-first-prediction-11-o2-c1', 'solution', 'Report B: consistent R2 on held-out test data is trustworthy. Report A''s 0.997 is unverified on data the model never trained on.', 20, 2),

  ('mission-ai-first-prediction-12-o1-c1', 'orientation', 'Compare the early model''s training loss to its validation loss -- are they far apart, or close together?', 10, 1),
  ('mission-ai-first-prediction-12-o1-c1', 'concept', 'Underfitting means the model performs poorly everywhere, so training and validation loss should look similarly bad.', 20, 2),
  ('mission-ai-first-prediction-12-o1-c1', 'solution', 'e2: validation loss close to a high training loss is underfitting -- the straight line genuinely cannot represent the curve in the data.', 30, 3),
  ('mission-ai-first-prediction-12-o2-c1', 'orientation', 'Compare the late model''s training loss to its validation loss -- watch what happens as training continues.', 10, 1),
  ('mission-ai-first-prediction-12-o2-c1', 'concept', 'Overfitting means training performance keeps improving while validation performance gets worse -- a widening gap, not a shared plateau.', 20, 2),
  ('mission-ai-first-prediction-12-o2-c1', 'solution', 'e2: validation loss rising while training loss keeps falling is overfitting -- the model has started memorizing the training set instead of the pattern.', 30, 3),
  ('mission-ai-first-prediction-12-o3-c1', 'orientation', 'A trustworthy R2 should hold up on data the model never trained on, not just look good on the training set.', 10, 1),
  ('mission-ai-first-prediction-12-o3-c1', 'solution', 'e2: the final model''s held-out R2 of 0.79, close to its training R2 of 0.85, is the honestly-evaluated number -- unlike the overfit model''s unchecked 0.98.', 20, 2),
  ('mission-ai-first-prediction-12-o4-c1', 'orientation', 'Look at what disqualified each of the first two models, and what the third model got right that neither of them did.', 15, 1),
  ('mission-ai-first-prediction-12-o4-c1', 'solution', 'Reject the underfit early model and the overfit late model. Ship the version whose validation and test R2 stay close to its training R2 -- honestly evaluated, not just impressive-looking.', 25, 2);
